### PR TITLE
add qlImageSize.qlgenerator v1.6.0

### PR DESCRIPTION
**Pull request by L1cardo**
After making all changes to the cask:

- [Yes] `brew cask audit --download {{cask_file}}` is error-free.
- [Yes] `brew cask style --fix {{cask_file}}` reports no offenses.
- [Yes] The commit message includes the cask’s name and version.
- [Yes] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by reitermarkus** [comment]
Sorry, this doesn't meet our [notability requirements](https://github.com/Homebrew/homebrew-cask/blob/4184d50d2d7fa4afb62e6c7eb6761ae5ac417c88/doc/faq/rejected_casks.md). Consider submitting the original project instead of your fork.

**Comment by L1cardo** [comment]
> Sorry, this doesn't meet our [notability requirements](https://github.com/Homebrew/homebrew-cask/blob/4184d50d2d7fa4afb62e6c7eb6761ae5ac417c88/doc/faq/rejected_casks.md). Consider submitting the original project instead of your fork.

The origin developer dose not build this plugin for others, this is what I built. 
Should I still submit the original?

**Comment by reitermarkus** [comment]
You can either try to convince upstream to publish binary releases or host this in your own tap for now.

**Comment by L1cardo** [comment]
It is not possible for me to convince the owner. And if I host in my own tap, it will be difficult for other to install this plugin.
Is there any other solution ?

**Comment by L1cardo** [comment]
Can let the homepage be the origin owner's repo and url be my repo ?
Like this.

**Pull request closed without merging**
