### PR TITLE
flutter 1.9.1

### PR DESCRIPTION
**Pull request by mofneko**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Welcome, @mofneko.

In the future, please don’t change the structure of the template, it’s helpful.

> - [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).

[It was already refused](https://github.com/Homebrew/homebrew-cask/pull/63170) and [you know it](https://github.com/Homebrew/homebrew-core/pull/46727#discussion_r346649366). Please don’t check the box if it isn’t true, explain it instead (the template tells you as much, at the top). That was confusing and took me a while to figure out.

Still refusing because it should be a formula *that builds from source*.

**Comment by anton-matosov** [comment]
image
from here https://flutter.dev/docs/get-started/install/macos#run-flutter-doctor
Is that the reason why flutter is not built from source and pre-built binaries are used?

**Comment by vitorgalvao** [comment]
@anton-matosov I don’t see how that would be relevant. Homebrew isn’t compiled and also uses Google Analytics.

**Comment by cweagans** [comment]
I looked into building flutter from source for Homebrew, and it's _really_ painful. Building it by hand is kind of a PITA. Automating it is even more so. Can we revisit this?

**Comment by anton-matosov** [comment]
@vitorgalvao just checking if analytics has anything to do with it.

**Pull request closed without merging**
