### PR TITLE
Upgrade datagrip to version 2016.1

### PR DESCRIPTION
**Pull request by athrunsun**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You did not fill the PR template. It is required.

**Comment by athrunsun** [comment]
@vitorgalvao Could you give me the link of a template please?

**Comment by vitorgalvao** [comment]
It shows up automatically when you submit a PR.

I’ve made the checks manually, this time.

**Comment by athrunsun** [comment]
@vitorgalvao I'm sorry about this. In the new PR I just submitted #1928 I am following the PR instructions. Would you mind take a look?
Thanks!

**Pull request merged**
