### PR TITLE
Replace colon with comma in casks with `:sparkle` livecheck block

### PR DESCRIPTION
**Pull request by FnControlOption**
- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

https://github.com/Homebrew/homebrew-cask/issues/95207

### CODE REVIEW

**Comment by tehpsy** [comment]
Suddenly all my CI builds are failing with homebrew errors like `Cask 'vu' is unreadable: undefined method `csv' for "1.2,6,1523016199":Cask::DSL::Version`.

The number of casks that fail is increasing nearly every hour, and it includes some of the casks in this PR. Any thoughts @FnControlOption @miccal?

**Comment by miccal** [comment]
@tehpsy it sounds like you are not on the latest version of Homebrew -- check `brew --version` and ensure it is at `3.3.5`.

**Comment by tehpsy** [comment]
@miccal Thanks for your quick response. Indeed that fixed it -- my machine was up to date, but my CI (CircleCI) was not. Interestingly, on CI this was fine:
```
brew install rectangle
```
whereas running the same thing from a script (which is the case in my CI pipeline) would fail:
```
#!/bin/bash --login -eo pipefail
brew install rectangle
```

**Comment by miccal** [comment]
Glad you got it sorted :)

**Pull request merged**
