### PR TITLE
Add LuminetMonitor 2.2.0

### PR DESCRIPTION
**Pull request by magcho**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> It seems the App source '/usr/local/Caskroom/luminetmonitor/2.2.0/LumiNetMonitor.app' is not there.

[How to fix](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md).

**Comment by magcho** [comment]
I have a question.

This app file is ZIP archive.
[app] include [dmg] in [zip]

```
122_ext_03_0.zip
 |-LumiNetMonitor220_mac    <- folder
    |- LumiNetMonitor220.dmg
        |-LumiNetMonitor.app
```

I don't know how I write this case. Help me.

**Comment by magcho** [comment]
@vitorgalvao Thank you berry much.

**Comment by core-code** [comment]
this is already offline. it seems there is a slightly newer version at a completely different host ( https://www.luminex.be/support/product-support/ ), however this now uses a weird installer that would seem like a pain to support. i can not find any download at the homepage linked in the cask.

**Comment by magcho** [comment]
that link was mirrorlink of agency. this agency stopped software support. I found a link instead.
(http://software.luminex.be/mac//LumiNetMonitor/2.2.1LumiNetMonitor.app.7z)

**Comment by core-code** [comment]
@magcho thanks!

**Pull request merged**
