### PR TITLE
Update superslicer from 2.3.57.12 to 2.4.58.3

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by nielsvz** [comment]
The author of SuperSlicer has clearly indicated that 2.4.58.3 is not to be considered the stable release - 2.3.57.12 still is.

SuperSlicer 2.4.58.3 crashes on startup.

**Comment by p-linnane** [comment]
@nielsvz The livecheck for this cask checks for the release tagged as 'latest' by the repo. This was bumped based off that. This commit can be reverted, but we will need to figure out a way to adjust the livecheck log if the repo is going to tag unable releases as `latest`.

```
  livecheck do
    url "https://github.com/supermerill/SuperSlicer/releases/latest"
    strategy :page_match do |page|
      match = page.match(%r{href=.*?/SuperSlicer_(\d+(?:\.\d+)+)_macos_(\d+)\.dmg}i)
      next if match.blank?

      "#{match[1]},#{match[2]}"
    end
  end

**Comment by nielsvz** [comment]
I think we should consider removing the livecheck. The author of SuperSlicer does not consider this version to be a beta, unfortunately the macOS build for this release does not start.

Additionally, it seems the releases are manually edited at times; for this release specifically, the ARM build was replaced without generating a new release on GitHub (SHA256 does not match up anymore).

**Comment by p-linnane** [comment]
That's somewhat concerning that the checksums change without new releases. I'd like a maintainer to weigh in on how this should be handled moving forward (@bevanjkay @miccal @SMillerDev).

**Comment by SMillerDev** [comment]
> I think we should consider removing the livecheck.

In that situation every tag is a new version.

> The author of SuperSlicer does not consider this version to be a beta, unfortunately the macOS build for this release does not start.

Then there is nothing homebrew can do.

**Comment by supermerill** [comment]
SuperSlicer dev here.
Sorry for the late answer. The 2.4 version need zstd to be installed before. (a first dependency)

> That's somewhat concerning that the checksums change without new releases. I'd like a maintainer to weigh in on how this should be handled moving forward

Did I do something wrong?

**Comment by p-linnane** [comment]
@supermerill Thanks for the info. I can add zstd as a dependency to this cask.

> Did I do something wrong?

No. The concern was if the checksum for the same release was going to constantly change. That could cause issues until the cask is updated each time.

**Pull request closed without merging**
