### PR TITLE
Webex Network Recording Player

### PR DESCRIPTION
**Pull request by zzamboni**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
It’s missing `uninstall`. There are [scripts](https://github.com/phinze/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/phinze/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#uninstall-stanza-details) geared for that. Do you need any help?

**Comment by zzamboni** [comment]
Thanks for the feedback, I've updated the PR with `uninstall`.

**Comment by vitorgalvao** [comment]
Thank you. Are you able to provide a [license](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#license-stanza-details) for this? On a first look it seems like it is proprietary but free to download and use (would be `:gratis`), is that the case?

**Comment by zzamboni** [comment]
Updated license.

**Comment by vitorgalvao** [comment]
Thank you.

**Pull request merged**
