### PR TITLE
monarch: update livecheck, url

### PR DESCRIPTION
**Pull request by bevanjkay**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Review by khipp — APPROVED** [review]

**Comment by bevanjkay** [comment]
Fixing! Forgot to bump the version.

**Review by krehel — APPROVED** [review]

**Comment by bevanjkay** [comment]
Doesn't look like there's currently a way to download the intel version.

**Comment by daeho-ro** [comment]
Interestingly, the list of object is here,
- https://storage.googleapis.com/monarchlauncher/

and indeed, there is no files for the path `/x64/`.

**Comment by khipp** [comment]
According to the developer, updates for Intel Macs have yet to be released: https://www.reddit.com/r/monarchapp/comments/1gic22h/monarch_website_is_back_online_at_v079/

**Comment by daeho-ro** [comment]
0.7.10 has both arm and intel now.

**Comment by krehel** [comment]
Superseded by #191439

**Pull request closed without merging**
