### PR TITLE
Update texpad to 1.7.32__104__a6eb552

### PR DESCRIPTION
**Pull request by chohner**
#### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]

**Comment by chohner** [comment]
I couldn't figure out the hash, maybe there's a cleaner way to do it - but at least it now resolves correctly.

**Comment by vitorgalvao** [comment]
> I couldn't figure out the hash, maybe there's a cleaner way to do it

What do you mean?

**Comment by chohner** [comment]
1.7.32__104__a6eb552 should probably be something like 1.7.32 (104) and 'a6eb552' some sort of hash that is now hard coded so the version string is pretty ugly.

**Comment by vitorgalvao** [comment]
Oh, don’t worry about it. We care about versions more in the sense of how they relate to the URL than just by themselves. The way you did it is fine.

**Pull request merged**
