### PR TITLE
adobe-digital-editions: update to v4.5

### PR DESCRIPTION
**Pull request by dd217**
sorry about that

### CODE REVIEW

**Comment by adityadalal924** [comment]
Please fix your commit message - it needs to be more descriptive. https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#commit-messages

**Comment by adityadalal924** [comment]
@vitorgalvao `prfixmaster` fails here, likely because of unrelated commits? 

@dd217 This PR has merge conflicts - I will fix manually with another PR. Thank you for the contribution, regardless.

**Comment by adityadalal924** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/16784

Try out `cask-repair` for easier Cask updates - details can be found in CONTRIBUTING

**Comment by vitorgalvao** [comment]
> @vitorgalvao `prfixmaster` fails here, likely because of unrelated commits?

It was due to the merge conflicts, most likely, since it doesn’t force push.

**Pull request closed without merging**
