### PR TITLE
create cask for mbt

### PR DESCRIPTION
**Pull request by ryenus**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Since it's open source and binary-only this should be a formula instead.

**Comment by ryenus** [comment]
@SMillerDev thank you for looking into this, to be honest I'm not really familiar with go stuff, so having it added as cask is the easiest for me to make it available at first. Possible let it first ship as a cask and later make it a formula? Or maybe is there a similar example I can follow to submit as a formula? Thank you!

**Comment by SMillerDev** [comment]
About 1/6 formula are in Go so there should be plenty of examples to choose from.

**Comment by ryenus** [comment]
Created the formula pr https://github.com/Homebrew/homebrew-core/pull/100956, closing this cask pr.

**Pull request closed without merging**
