### PR TITLE
Update filebot to 4.7.9

### PR DESCRIPTION
**Pull request by grantlucas**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by grantlucas** [comment]
From what I can tell, the latest version is still `4.7.9` but the checksum changed, though their Mac App store version is at `4.7.15`. I'm setting up a new computer so don't have access to an existing Filebot instance that works to check what the current version number is.

**Comment by gtmgianni** [comment]
@grantlucas That `sha256` is the checksum for Sourceforge's error page. They're currently having issues with certain services, and haven't yet restored everything to full functionality. Hence, many cask download links that are hosted on Sourceforge are not working at the moment.

**Comment by vitorgalvao** [comment]
Thank you for the submission, but this cask is usually updated by the developer, which means this `sha256` is due to the problem mentioned by @gtmgianni.

**Comment by grantlucas** [comment]
Ahh, so sorry about that. You know, I was looking at this late last night and the fact that Source Forge was having an issue came up but I completely forgot about it when I looked again this morning. Carry on! Nothing to see here 😄

**Pull request closed without merging**
