### PR TITLE
Update dbeaver-community from 22.1.5 to 22.2.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — APPROVED** [review]

**Comment by hunalme** [comment]
Hello,

I'm unable to install DBeaver using brew tool because of the "SHA256 mismatch" error. Could you please fix the homebrew file (https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dbeaver-community.rb) using correct hash values.

Regards

```
% brew install --cask dbeaver-community
...
==> Downloading https://dbeaver.io/files/22.2.0/dbeaver-ce-22.2.0-macos-x86_64.dmg
...
Error: SHA256 mismatch
Expected: 3851ca21e4569357dbc3b7063fd69536dd02dad4e620514288505f87498d8859
  Actual: 5d972b98dee5fc2a9e9310bcab599b4773bb1348f18f4620b988fb10256e6d69
    File: /Users/xxx/Library/Caches/Homebrew/downloads/f9a14944fc7beed32edacafe3989ab56315aa01785d754347e8384f67f455bf4--dbeaver-ce-22.2.0-macos-x86_64.dmg
To retry an incomplete download, remove the file above.

```

**Comment by p-linnane** [comment]
@hunalme Thanks for reporting. I've submitted a fix in #131080. You can manually change the file to the new hash if you need to install it before that gets merged.

**Comment by JBallin** [comment]
Just wondering - what caused the hash mismatch?

**Comment by p-linnane** [comment]
@JBallin This typically happens if the binary is updated in place after the cask has been updated.

**Pull request closed without merging**
