### PR TITLE
Updated Origami download URL

### PR DESCRIPTION
**Pull request by Cellane**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download origami` is error-free.
- [x] `brew cask style --fix origami` left no offenses.

### CODE REVIEW

**Comment by adidalal** [comment]
Why the URL change?

**Comment by adidalal** [comment]
Needs a `# was verified as official when first introduced to the cask` comment above this line ([example](https://github.com/caskroom/homebrew-cask/blob/4ad02c9f087deb9e553ab0129c079d73c474add8/Casks/0ad.rb#L5); [reasoning](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment)).

**Comment by Cellane** [comment]
The old one didn't work for me earlier today and the one I submitted in my commit is the one that's now found on the [http://facebook.github.io/origami/download/](project page).

Oh, and I just noticed that I messed up the URL anyway, the new one contains the version number twice and I forgot to replace the first occurrence of it.

**Comment by adidalal** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/20545

**Pull request closed without merging**
