### PR TITLE
Add Nanosaur II v2.1.0

### PR DESCRIPTION
**Pull request by EricFromCanada**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

[Nanosaur II on Wikipedia](https://en.wikipedia.org/wiki/Nanosaur_2:_Hatchling)

### CODE REVIEW

**Review by bevanjkay — DISMISSED** [review]

**Review by bevanjkay — APPROVED** [review]

**Comment by reitermarkus** [comment]
Ah Nanosaur brings back memories.

@bevanjkay, what was the problem here? This clearly isn't a syntax only change.

**Comment by bevanjkay** [comment]
@reitermarkus All the checks passed except for the notability requirement, which we have skipped before due to @EricFromCanada being a Homebrew member. We have no way of just skipping that audit, and can't merge without green CI anymore. 

Not an ideal solution... in the past what @miccal attempted would have worked by using pr-publish to push the commit irrespective of CI green/red.

**Comment by bevanjkay** [comment]
Ideally we either not make exceptions for CI (they are very rare). Or add more specific audit skip labels.

**Comment by reitermarkus** [comment]
Ok, I am actually working on exactly this at the moment, i.e. being able to skip the notability check.

Should be possible now that https://github.com/Homebrew/brew/pull/14510 is merged.

**Pull request merged**
