### PR TITLE
Update wireshark.rb

### PR DESCRIPTION
**Pull request by clentfort**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by clentfort** [comment]
Seems the runners use macos-13, the latest version requires macos-14. I'm surprised the previous PRs updating wireshark didn't have these problems.

**Comment by bevanjkay** [comment]
The issue that we are seeing is that the sparkle feed is returning a different version to that in the PR. It may be that there is a "legacy version" with a newer pubdate than the latest. If that is the case, adding a block to the livecheck strategy to map over all of the items in the Sparkle feed should resolve the issue.

**Comment by gnought** [comment]
I don't have macos-13, but `brew livecheck` returns same version **4.2.3** in 2 different strategy in my macos-12,intel and macos-14,arm

macos-12,intel
``` sh
bash-5.2$ brew --version
Homebrew 4.2.8-125-ga6d539c
bash-5.2$ brew livecheck --debug wireshark
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromKegLoader): loading wireshark
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromInstalledPathLoader): loading wireshark
Warning: Treating wireshark as a formula.

Formula:          wireshark
Livecheckable?:   Yes

URL:              https://www.wireshark.org/download.html
Strategy:         PageMatch
Regex:            /href=.*?wireshark[._-]v?(\d+\.\d*[02468](?:\.\d+)*)\.t/i

Matched Versions:
4.2.3, 4.0.13, 3.6.21

wireshark: 4.2.2 ==> 4.2.3
```

macos-14,arm

``` sh
bash-5.2$ brew --version
Homebrew 4.2.8-125-ga6d539c
Homebrew/homebrew-cask (git revision 6ccea989d2; last commit 2024-02-16)
bash-5.2$ brew livecheck --debug wireshark
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading wireshark
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromDefaultNameLoader): loading wireshark

Cask:             wireshark
Livecheckable?:   Yes

URL:              https://www.wireshark.org/update/0/Wireshark/0.0.0/macOS/arm64/en-US/stable.xml
Strategy:         Sparkle

Matched Versions:
4.2.3

wireshark: 4.2.2 ==> 4.2.3
bash-5.2$
```

**Comment by clentfort** [comment]
> The issue that we are seeing is that the sparkle feed is returning a different version to that in the PR. It may be that there is a "legacy version" with a newer pubdate than the latest. If that is the case, adding a block to the livecheck strategy to map over all of the items in the Sparkle feed should resolve the issue.

That seems to be the case. As of writing, version 3.6.21 was released 3 minutes later. (See https://www.wireshark.org/update/0/Wireshark/0.0.0/macOS/arm64/en-US/stable.xml). I don't know any Ruby, so I'd be grateful if someone could take this over. For now, I have installed wireshark the old fashioned way.

**Comment by gnought** [comment]
@clentfort mind to push a dummy commit to re-trigger the CI pipeline?
Or close the PR to let others to take over?

**Comment by clentfort** [comment]
Closing so someone else can take over.

**Pull request closed without merging**
