### PR TITLE
Update wpsoffice.rb to add zh_CN package version 2.1.2,3417

### PR DESCRIPTION
**Pull request by ctyytc**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by core-code** [comment]
thanks for your contribution. can you re-work this so only the version, sha, url and homepage stanzas are duplicated? everything else is the same anyway.

**Comment by ctyytc** [comment]
> thanks for your contribution. can you re-work this so only the version, sha, url and homepage stanzas are duplicated? everything else is the same anyway.

Only "name, depends_on, app" are same, everything else is defferent. Still need to update?

**Comment by core-code** [comment]
@vitorgalvao what do you think?

**Comment by vitorgalvao** [comment]
Even the versions are different? We’ll need to have a discussion about chinese versions of software; they’re a major hassle and should maybe be removed and sent to another (unofficial) tap.

> Only "name, depends_on, app" are same, everything else is defferent. Still need to update?

Yes. `zap` can also be unified: use the `*` glob.

Remove the `'en_US'` and the other from the end, they’re not doing anything.

**Comment by core-code** [comment]
> We’ll need to have a discussion about chinese versions of software; they’re a major hassle and should maybe be removed and sent to another (unofficial) tap.

i agree. all macOS apps should contain all languages in a unified download and app-bundle. i don't think we should invest much time to support apps from vendors that refuse to accept this and other basic macOS development rules. 
the only way how these vendors will fix their act is if enough of their users complain about the broken stuff.
however, if we spend much time to work around their problems this will only lead to them getting less complaints. this is the opposite from trying to improve the status quo.

**Comment by vitorgalvao** [comment]
> all macOS apps should contain all languages in a unified download and app-bundle.

While I agree, in the case of Chinese versions it’s likely they need to provide different downloads due to The Great Firewall, and the software might also be different, modified in accordance to governmental regulations.

For things like PokerStars it’s due to regional gambling laws, though I see little reason as to why they need a different app per legislation. Accounts are already associated with real IDs, so they could impose the restrictions in the same app.

For apps like Firefox, I have no idea. But from conversations I had with their developers, they don’t seem to understand macOS development very well (despite most of them ostensibly using Macs). I tried talking to one of them *at a developer conference* about their lack of AppleScript support and he had no idea what it was (they’re the only major browser without support for it, hence the worst browser for automation), despite an open bug report so old that if it was a person it could vote. From other reports I’ve read, their Keychain support is also broken, as are other macOS features.

**Comment by ctyytc** [comment]
@vitorgalvao @core-code Tks for reply, I fully agree that all macOS apps should contain all languages in a unified download and app-bundle. But unfortunately WPS is not yet able to do it for the time being, the Chinese version has a huge difference from the English version in terms of user login method, cloud storage form, privacy agreement, etc.

**Comment by vitorgalvao** [comment]
@ctyytc It still needs the other requested modifications.

**Comment by vitorgalvao** [comment]
Closing because this now has conflicts. @ctyytc If you’re still interested in getting this merged, please resubmit with the fixes.

**Pull request closed without merging**
