### PR TITLE
Update signal to 1.21.1

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
I cannot find any problems with the zip-file.
unzip -t says: No errors detected in compressed data of /Users/work/Downloads/Signal-Desktop-1.21.1.zip.
could somebody please have a look on that? Thanks!

**Comment by maristgeek** [comment]
```
 ~/Downloads
$ unzip -t signal-desktop-mac-1.21.1.zip
Archive:  signal-desktop-mac-1.21.1.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of signal-desktop-mac-1.21.1.zip or
        signal-desktop-mac-1.21.1.zip.zip, and cannot find signal-desktop-mac-1.21.1.zip.ZIP, period.

 ~/Downloads
$ unzip -t signal-desktop-mac-1.21.2.zip
Archive:  signal-desktop-mac-1.21.2.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of signal-desktop-mac-1.21.2.zip or
        signal-desktop-mac-1.21.2.zip.zip, and cannot find signal-desktop-mac-1.21.2.zip.ZIP, period.
```

For me (high sierra, 10.13.6) the zip for 1.21.1 and now 1.21.2 aren't quite right. Archive Utility opens/extracts them just fine but something about how they're creating zip files now seems less than right.

**Comment by vitorgalvao** [comment]
Mind anyone [telling them about it](https://github.com/signalapp/Signal-Desktop)?

**Comment by core-code** [comment]
if Archive Utility extracts them fine, there isn't really anything to tell them.

**Comment by vitorgalvao** [comment]
> if Archive Utility extracts them fine, there isn't really anything to tell them.

It appears to be a badly formed zip which some apps can get around but others not. Having a well formed zip file that every app can open is beneficial for everyone.

**Comment by core-code** [comment]
i agree that it seems to be a bug, however developers usually care little about things that are only theoretical - no real Mac user is going to decompress 'Signal' on the command-line.

in any case, they fixed it already for the upcoming 1.22 release: https://github.com/signalapp/Signal-Desktop/issues/3128

**Comment by vitorgalvao** [comment]
> however developers usually care little about things that are only theoretical

Typically, yes. But when it’s another open-source project they tend to be more receptive towards technical correctness. And if it’s a popular cask that is broken because of it, more users will ask them to do it.

**Comment by vitorgalvao** [comment]
Let’s close this and wait for stable `1.22`.

**Pull request closed without merging**
