### PR TITLE
TeamViewer: fix path to installer package

### PR DESCRIPTION
**Pull request by leogama**
Fixes this error I got with the latest TeamViewer version in master:

==> Downloading https://download.teamviewer.com/download/TeamViewer.dmg
==> Downloading from https://dl.teamviewer.com/download/version_15x/15.2.2756/TeamViewer.dmg
Warning: No checksum defined for cask 'teamviewer', skipping verification.
==> Installing Cask teamviewer
==> Running installer for teamviewer; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
==> Purging files for version 15.22.3 of Cask teamviewer
Error: Could not find PKG source file 'Install Install TeamViewer.pkg', found 'Install TeamViewer.pkg' instead.

---

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by leogama** [comment]
Strange, CI got a different download URL and the current package file location. Keep it open for a while please, I'll investigate.

**Comment by leogama** [comment]
The TeamViewer's server redirects to a different version depending on the User Agent. It gives an older release of version 15 for macOS 10.13 to 10.11, and a release of version 13 for macOS 10.10. They seem to be legacy but yet supported versions.

Should I submit those versions to `homebrew-cask-versions` and change this to be dependent on macOS Mojave and above or add if-else clauses to this cask?

**Comment by bevanjkay** [comment]
@leogama It does look like the latest version(s) of teamviewer should be dependent on mojave or later.

If the install / uninstall process is the same for the older versions an if-else block with versioning, URL and livecheck options could work for the older versions. However, it may not be necessary as I have not seen any issues raised from anybody on older versions of macOS asking for it to be included.

**Comment by leogama** [comment]
> If the install / uninstall process is the same for the older versions an if-else block with versioning, URL and livecheck options could work for the older versions.

This `curl` command is based on what `brew fetch` and `brew install` do:
```sh
for version in 10.{10..15} 11; do
    echo "==> macOS $version <=="
    curl --head --location --silent \
        --user-agent "Homebrew/3.2.14-63-g4648903 (Macintosh; Intel Mac OS X $version) curl/7.54.0" \
        https://download.teamviewer.com/download/TeamViewer.dmg \
    | grep '^location:'
done
```
And it returns:
```
==> macOS 10.10 <==
location: https://dl.teamviewer.com/download/TeamViewer.dmg
location: /download/version_15x/TeamViewer.dmg
location: /download/version_13x/TeamViewer.dmg
==> macOS 10.11 <==
location: https://dl.teamviewer.com/download/TeamViewer.dmg
location: /download/version_15x/TeamViewer.dmg
location: /download/version_15x/15.2.2756/TeamViewer.dmg
==> macOS 10.12 <==
location: https://dl.teamviewer.com/download/TeamViewer.dmg
location: /download/version_15x/TeamViewer.dmg
location: /download/version_15x/15.2.2756/TeamViewer.dmg
==> macOS 10.13 <==
location: https://dl.teamviewer.com/download/TeamViewer.dmg
location: /download/version_15x/TeamViewer.dmg
location: /download/version_15x/15.2.2756/TeamViewer.dmg
==> macOS 10.14 <==
location: https://dl.teamviewer.com/download/TeamViewer.dmg
location: /download/version_15x/TeamViewer.dmg
==> macOS 10.15 <==
location: https://dl.teamviewer.com/download/TeamViewer.dmg
location: /download/version_15x/TeamViewer.dmg
==> macOS 11 <==
location: https://dl.teamviewer.com/download/TeamViewer.dmg
location: /download/version_15x/TeamViewer.dmg
```

---
Here are the `brew fetch` debug messages on my machine (macOS 10.13 High Sierra):
```
brew fetch --cask --force --debug teamviewer
==> Downloading https://download.teamviewer.com/download/TeamViewer.dmg
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie-jar /dev/null --globoff --show-error --user-agent Homebrew/3.2.14-63-g4648903\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://download.teamviewer.com/download/TeamViewer.dmg
==> Downloading from https://dl.teamviewer.com/download/version_15x/15.2.2756/TeamViewer.dmg
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie-jar /dev/null --globoff --show-error --user-agent Homebrew/3.2.14-63-g4648903\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location --head https://dl.teamviewer.com/download/version_15x/15.2.2756/TeamViewer.dmg
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie-jar /dev/null --globoff --show-error --user-agent Homebrew/3.2.14-63-g4648903\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --header Accept-Language:\ en --fail --progress-bar --retry 3 --location --remote-time --output /Users/leogama/Library/Caches/Homebrew/downloads/be05736e528dcf66445ab64fbce55935ab099e89bc1ce99f07b9aa827d3ea6e4--TeamViewer.dmg.incomplete https://dl.teamviewer.com/download/version_15x/15.2.2756/TeamViewer.dmg
```

**Comment by bevanjkay** [comment]
@leogama Are you able to have a look at creating the if-else block, or at least starting the process (I can help where needed)?
Let's add `depends_on macos: ">= :el_capitan"`

**Comment by leogama** [comment]
The `livecheck` URL works for the 15.2 version, but I don't believe it will ever receive an upgrade.

**Comment by leogama** [comment]
`uninstall` seems to be OK, `zap` may need an addition or two.

**Comment by leogama** [comment]
@bevanjkay If everything is OK, we should probably apply the same changes to `teamviewer-host` as the TeamViewer's version check API also returns `url="https://dl.teamviewer.com/download/version_15x/update/15.2.2756/TeamViewerHost.pkg" sparkle:version="15.2.2756"` in the response.

**Comment by miccal** [comment]
Thank you @leogama, and please feel free to apply the same changes to `teamviewer-host`.

**Pull request merged**
