### PR TITLE
Kid3.app link binaries

### PR DESCRIPTION
**Pull request by beschoenen**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by adidalal** [comment]
I don't use the app, what do the binaries do?

**Comment by beschoenen** [comment]
The `kid3` binary starts the app, with an optional given folder.
```bash
kid3 ~/Music/
```
And the `kid3-cli` can be used to tag music via the, well, CLI.
http://kid3.sourceforge.net/kid3_en.html#kid3-cli

**Comment by vitorgalvao** [comment]
`kid3` seems to just be something you’re adding yourself, to call the app from the CLI. We don’t do that, and only link if it’s something officially recommended.

Reason is to not pollute `/usr/local/bin` directories of users with things only a single user wants.

**Comment by beschoenen** [comment]
The `kid3-cli` binary would be very useful, though for bash scripts or w/e.

**Comment by vitorgalvao** [comment]
Yes, that one is fine.

**Pull request merged**
