### PR TITLE
Upgrade postman to v9.19.0

### PR DESCRIPTION
**Pull request by dalisoft**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Review by bevanjkay — APPROVED** [review]

**Comment by miccal** [comment]
@bevanjkay and @SMillerDev why was this auto-merged?
```
|-> brew livecheck postman --debug

Cask:             postman
Livecheckable?:   Yes

URL:              https://dl.pstmn.io/download/latest/osx64
Strategy:         HeaderMatch

Matched Versions:
9.16.0
postman: 9.19.0 ==> 9.16.0
```

**Comment by bevanjkay** [comment]
@miccal It's a timing issue. If the CI retry starts at the same time it runs the query it shows as passing because there's no failed checks (while generate-matrix sets up). 

I think there's a couple of options. 

1. Set CI retry to start staggered 30 minutes to the auto merge. 
2. Set the 'test' and 'syntax' CI runs as required before merging (or maybe just 'syntax')

**Comment by bevanjkay** [comment]
Also this is probably okay to stay merged as a once off. Postman is providing this version as an auto-update in-app do I imagine it will change over soon for livecheck.

**Comment by bevanjkay** [comment]
Re: #124072

**Pull request closed without merging**
