### PR TITLE
Add CrashPlan Pro 4.9.0

### PR DESCRIPTION
**Pull request by yanokwa**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
@vitorgalvao Crashplan has discontinued `crashplan` and now only offers the "PRO" / business edition. Should we rename this to replace the existing Cask?

**Comment by yanokwa** [comment]
I don't think we should rename it because users have up to a year to transition from CrashPlan Home to CrashPlan for Small Business (formerly CrashPlan Pro). Until they make that transition, they will still need the CrashPlan cask.

**Comment by yanokwa** [comment]
There's also the issue of what to call this cask. CrashPlan is branding this service "CrashPlan Small Business" but the binary says "CrashPlan Pro" and that's why I chose that as the name.

**Comment by commitay** [comment]
```
 0curl: (7) Failed to connect to web-fam-msp.crashplan.com port 443: Connection refused
```
@yanokwa The download link doesn't seem to work.

**Comment by yanokwa** [comment]
Ugh! I was worried about that. It looks like that is a link that is specific to my account and times out. How unfriendly.

I think at this stage, you should probably close the PR because I can't find a public link.

**Comment by commitay** [comment]
Thanks anyway for the PR @yanokwa!

**Pull request closed without merging**
