### PR TITLE
[WIP] brew cask outdated

### PR DESCRIPTION
**Pull request by phinze**

### CODE REVIEW

**Comment by alebcay** [comment]
Prerequisite for new upgrade verb (#4678).

**Comment by mattfelsen** [comment]
This is exciting! What else needs to happen here before this PR is merged? I looked through issue #9403 but don't see any further requisites since it looks like support for `:latest` is being skipped for now.

**Comment by RickWong** [comment]
Please merge this. It's super useful.

**Comment by thom-nic** [comment]
Any word on why this is stalled?  Using `brew outdated` is super useful and it's a shame cask still doesn't have the same capability.

**Comment by alebcay** [comment]
@phinze is this still WIP?

**Comment by xyb** [comment]
What are we waiting for? Add a test case before merge this?

**Comment by salimane** [comment]
let's merge this :+1:

**Comment by vitorgalvao** [comment]
@salimane No, lets not merge this. It is clearly marked as a work in progress. Why would we just merge it?

**Comment by salimane** [comment]
@victorpopkov my bad, I was just excited to see this being worked on :)

**Comment by phinze** [comment]
Anyone else is welcome to pick up this work, but I'm not pushing it forward anytime soon. Closing to reduce repo noise.

**Comment by bgandon** [comment]
Guys, for those who have been waiting for years the unicorn-ish `brew cask outdated` to be implemented, I just released a `brew-cask-outdated` workaround script that does the job.

See: https://github.com/bgandon/brew-cask-outdated

Any help for packaging a Homebrew formula would be more than welcome!

Cheers

**Comment by salimane** [comment]
@bgandon :+1:

**Comment by vitorgalvao** [comment]
@salimane Again, I ask you refrain from useless “+1” and thumbs up comments. They only add noise.

@bgandon It’s always the users who never contributed jack shit and know nothing of the project that act the more entitled. I saw your deleted comments, and your absolute disrespect for the team paints you as the type of asshole that causes open source maintainers to burn out.

If all you wanted was a script, other users have done them in the past and presented them here respectfully and amicably. You’re not special, and your script isn’t impressive. Instead of speweing nonsense, why don’t you make the contribution to the core itself?

We’re not here to serve you. We define priorities by what we feel is important and what the team has time to work on. Many small things need fixing before we can tackle big things and do them well. If you felt some things needed to exist already and didn’t understand they didn’t, you should’ve asked, and we would’ve told you.

I kindly ask you take your toxic atitude elsewhere. You’re no longer welcome.

**Comment by vitorgalvao** [comment]
@bgandon And once the new install behavious is implemented (which is only getting sooner), your script will start working, because the method you use to check for outdated versions is deeply unreliable now and will completely break under the new behaviour.

No, this is not a simple addition like you valiantly claimed it is, and you would’ve known that if you read the issue linked in the huge bold letters at the top of the README.

**Comment by vitorgalvao** [comment]
My appologies to the other intervenients in this issue, but I take the responsibility of managing this project seriously, and find it abolutely disrespectful when someone appears from nowhere with no history of contributions or meaningful interactions and starts making demands of the free time of others and insulting the team of maintainers (even if those comments were since deleted).

**Comment by phinze** [comment]
Some relevant context from another thread:

feature_request__ brew_cask_outdated _ _issue__19115_ _caskroom_homebrew-cask

**Pull request closed without merging**
