### PR TITLE
Update virtualbox-extension-pack to 5.2.2-119230

### PR DESCRIPTION
**Pull request by unrevised6419**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by iamandrewluca** [comment]
```
brew cask reinstall virtualbox-extension-pack
```

```
==> Caveats
Installing this Cask means you have AGREED to the
VirtualBox Personal Use and Evaluation License at

https://www.virtualbox.org/wiki/VirtualBox_PUEL

==> Satisfying dependencies
All Cask dependencies satisfied.
==> Downloading http://download.virtualbox.org/virtualbox/5.2.2/Oracle_VM_VirtualBox_Exten
Already downloaded: /Users/andreiluca/Library/Caches/Homebrew/Cask/virtualbox-extension-pack--5.2.2-119230.vbox-extpack
==> Verifying checksum for Cask virtualbox-extension-pack
==> Uninstalling Cask virtualbox-extension-pack
==> sudo: VBoxManage: command not found
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- VBoxManage extpack uninstall Oracle VM VirtualBox Extension Pack

==> Standard Output of failed command:


==> Standard Error of failed command:
sudo: VBoxManage: command not found


==> Exit status of failed command:
#<Process::Status: pid 63443 exit 1>
```

**Comment by iamandrewluca** [comment]
@commitay see above output. I can't reinstall virtual box extension pack

**Comment by commitay** [comment]
Try running `brew cask install --force virtualbox-extension-pack`, if it doesn't work please post the output.

**Comment by iamandrewluca** [comment]
@commitay It seems to work now. I think was an inconsistency betwwen VirtualBox and extpack. As I looked into commits there were removed some uninstall preflights.
Sorry for this PR. It is my first time trying to contribute on this repo.
Thanks!

**Pull request closed without merging**
