### PR TITLE
Update epic-games to 7.9.4

### PR DESCRIPTION
**Pull request by muescha**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by muescha** [comment]
uploaded to Virustotal:

https://www.virustotal.com/#/file/c85890a2d184e34671756772a0e944cbb40dbf3dc2e783975fdcc4f943320142/details


**Missing Signature Info section !**


log of cask repair:

```
cask-repair epic-games
Updating taps… Already up-to-date.                                                                                                                                      
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
cask 'epic-games' do                                                                                                                                                    
  # Auto-updates to a newer version than available on the homepage.                                                                                                     
  # Latest version is posted to the forum:                                                                                                                              
  # https://forums.unrealengine.com/unreal-engine/announcements-and-releases/1928-latest-launcher-release-notes                                                         
  version '7.9.4'                                                                                                                                                       
  sha256 '1f5bc125a5173ab6c4c8e8a05f3e27d8fdb522360834e7a8c947788a1e998eed'                                                                                             
                                                                                                                                                                        
  url "https://download-dynamic.epicgames.com/Builds/UnrealEngineLauncher/Installers/EpicInstaller-#{version}.dmg"                                                      
  name 'Epic Games Launcher'                                                                                                                                            
  homepage 'https://www.epicgames.com/'                                                                                                                                 
                                                                                                                                                                        
  auto_updates true                                                                                                                                                     
                                                                                                                                                                        
  app 'Epic Games Launcher.app'                                                                                                                                         
                                                                                                                                                                        
  zap trash: [                                                                                                                                                          
               '~/Library/Caches/com.epicgames.EpicGamesLauncher',                                                                                                      
               '~/Library/Application Support/Epic',                                                                                                                    
               '~/Library/Cookies/com.epicgames.EpicGamesLauncher.binarycookies',                                                                                       
               '~/Library/Logs/Unreal Engine/EpicGamesLauncher',                                                                                                        
               '~/Library/Preferences/Unreal Engine/EpicGamesLauncher',                                                                                                 
             ]                                                                                                                                                          
end                                                                                                                                                                     
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Type the new version (or leave blank to use current one, or use `s` to skip)                                                                                            
> 7.9.4                                                                                                                                                                 
==> Downloading external files for Cask epic-games                                                                                                                      
==> Downloading https://download-dynamic.epicgames.com/Builds/UnrealEngineLauncher/Installers/EpicInstaller-7.9.4.dmg                                                   
######################################################################## 100.0%                                                                                         
==> No checksum defined for Cask epic-games, skipping verification                                                                                                      
==> Success! Downloaded to -> /Users/muescha/Library/Caches/Homebrew/Cask/epic-games--7.9.4.dmg                                                                         
diff --git a/Casks/epic-games.rb b/Casks/epic-games.rb                                                                                                                  
index 20785ff954..e9bb138277 100644                                                                                                                                     
--- a/Casks/epic-games.rb                                                                                                                                               
+++ b/Casks/epic-games.rb                                                                                                                                               
@@ -3,7 +3,7 @@ cask 'epic-games' do                                                                                                                                    
   # Latest version is posted to the forum:                                                                                                                             
   # https://forums.unrealengine.com/unreal-engine/announcements-and-releases/1928-latest-launcher-release-notes                                                        
   version '7.9.4'                                                                                                                                                      
-  sha256 '1f5bc125a5173ab6c4c8e8a05f3e27d8fdb522360834e7a8c947788a1e998eed'                                                                                            
+  sha256 'c85890a2d184e34671756772a0e944cbb40dbf3dc2e783975fdcc4f943320142'                                                                                            
                                                                                                                                                                        
   url "https://download-dynamic.epicgames.com/Builds/UnrealEngineLauncher/Installers/EpicInstaller-#{version}.dmg"                                                     
   name 'Epic Games Launcher'                                                                                                                                           
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Is everything correct? ([y]es / [n]o / [e]dit) y                                                                                                                        
Submitting…                                                                                                                                                             
                                                                                                                                                                        
You can upgrade the cask right now from your personal branch:                                                                                                           
  brew cask reinstall https://raw.githubusercontent.com/muescha/homebrew-cask/cask_repair_update-epic-games/Casks/epic-games.rb                                         
                                                                                                                                                                        
Submitted (https://github.com/caskroom/homebrew-cask/pull/47530)
```

**Comment by gtmgianni** [comment]
@muescha VirusTotal shows that the code signature is valid:

screen shot 2018-05-26 at 21 37 05

However, I've found that sometimes VirusTotal doesn't display the "Signature Info" section, even if the file is code signed. I think this may be related to whether or not you are logged in with a VirusTotal account.

**Comment by muescha** [comment]
Or maybe with an delay. Today i also see the signature without login

**Comment by vitorgalvao** [comment]
> I've found that sometimes VirusTotal doesn't display the "Signature Info" section, even if the file is code signed.

Probably not what’s happening here, but it only shows that information if an actual file is uploaded (i.e. doesn’t work if you give it a URL).

**Comment by vitorgalvao** [comment]
If uploading the file it shows sometimes and others not, but with an account it shows every time, then it may have to do with system load. Maybe they work with a priority system, and if too many users are trying to use it, it prioritises the ones with accounts.

**Pull request merged**
