### PR TITLE
Add Radar.app v0.0.7

### PR DESCRIPTION
**Pull request by vicke4**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Hi @vicke4, thank you for submission. At this time we are unable to accept this Cask as it does not meet our [minimum notability requirements](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md).

> + The Cask is for an app that is too obscure. Examples:
>   + An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars).

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if it gets notable enough we would then be happy to consider adding this to `homebrew-cask`.

**Comment by vicke4** [comment]
Hi @bevanjkay, sorry about the trouble. Radar is not an open-source app. I have changed the `url` in [my fork](https://github.com/vicke4/homebrew-cask/blob/13dc2d0aac2b375a84d4d562f4959a99d23fefe0/Casks/radar.rb) now. After the changes, I ran the following command in my local and it passed.
```
brew audit --cask --appcast --online --new-cask './Casks/radar.rb'
``` 
Could you please consider?

**Comment by carlocab** [comment]
Do you have any other means of demonstrating that your app is notable enough for inclusion into Homebrew/cask?

**Comment by vicke4** [comment]
Sure. I agree that Radar is a new app. I shared the app on [hacker news](https://news.ycombinator.com/item?id=27559941) & [reddit](https://www.reddit.com/r/webdev/comments/ncsrtp/i_built_this_crossplatform_menubar_app_to_check/) and got a decent response. I believe people like Radar, and it is a worthy addition to Homebrew/cask.

**Comment by carlocab** [comment]
I do think that GitHub stats aren't the right metric for notability here, but I'd want to hear other maintainers' opinions on this. CC @Homebrew/cask

**Comment by carlocab** [comment]
> The fact that it's self submitted enforces my idea that it's not popular enough on it's own. The code repo metrics might have been wrong, but the judgement wasn't iyam.

This is my thinking too. If a user submits this then we'll reconsider. Thanks for the PR anyway, @vicke4.

**Comment by vitorgalvao** [comment]
We used to have a provision in the rule specifically against self-submitted apps, but removed it because in practice we never enforced it. Though that’s because it’s typical for users to ask in open-source projects for the maintainer to make and submit the cask.

The popularity audit was wrong in this case because the repo is only hosting the binaries, hence shouldn’t be taken into account.

If you’ve gotten a good response on Reddit and HN, this should be resubmitted by someone else in no time, and now they already have a ready cask to copy and do so.

**Comment by vicke4** [comment]
Okay, thanks. I will ask one of the app users to send a pull request.

**Pull request closed without merging**
