### PR TITLE
Update cacoo ninja 1.2.0

### PR DESCRIPTION
**Pull request by ikikko**

### CODE REVIEW

**Comment by adityadalal924** [comment]
Why the removal of the silent option?

**Comment by ikikko** [comment]
Because we cannot update this successfully with the option.

We can install it silently. However, cacoo-ninja installer doesn't define a silent option when updating ( and uninstalling ). It may depend on the fact that updating dialog is not a normal one. That's why I decided the removal it.

I have a following error with the silent option below.

```
$ brew cask install cacoo-ninja
==> Satisfying dependencies
==> Installing Cask dependencies: adobe-air
adobe-air ... 
already installed
complete
==> Downloading http://assets.cacoo.com/extension/151111/CacooNinjaInstaller.dmg
Already downloaded: /Library/Caches/Homebrew/cacoo-ninja-1.2.0.dmg
==> Running installer script Install Cacoo Ninja.app/Contents/MacOS/Install Cacoo Ninja
==> failed due to bad configuration
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "#<Pathname:/opt/homebrew-cask/Caskroom/cacoo-ninja/1.2.0/Install Cacoo Ninja.app/Contents/MacOS/Install Cacoo Ninja>", "-silent"]

==> Output of failed command:
failed due to bad configuration


==> Exit status of failed command:
#<Process::Status: pid 2284 exit 9>
```

**Comment by adityadalal924** [comment]
Thank you for the contribution. It was merged directly as 7fb44e173e7ea42c81d5711453234c846b70558b to keep commit history cleaner. Your contribution is still credited to you.

**Comment by ikikko** [comment]
Thanks for your merge!

**Comment by vitorgalvao** [comment]
This casks [still needs work](https://github.com/caskroom/homebrew-cask/issues/10990), so if you want to help there as well, it’d be appreciated, @ikikko.

**Comment by ikikko** [comment]
@vitorgalvao 
I'm sorry, but I don't have a solution to fix it.

Do you have an idea?

**Pull request closed without merging**
