### PR TITLE
Update eloston-chromium from 110.0.5481.177-1.1 to 111.0.5563.146-1.1

### PR DESCRIPTION
**Pull request by VulpesVulpes825**
* Update eloston-chromium from 110.0.5481.177-1.1 to 111.0.5563.146-1.1
* Update eloston-chromium.rb to use "ungoogled-software/ungoogled-chromium-macos" repo
 
Related issue: [#97](https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/97),  [#100](https://github.com/ungoogled-software/ungoogled-chromium-macos/pull/100#issuecomment-1475857063), [#105](https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/105)

---
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
From the [documentation](https://docs.brew.sh/Acceptable-Casks#forks-and-apps-with-conflicting-names):

> Forks must have the vendor’s name as a prefix on the cask’s filename and token. If the original software is discontinued, forks still need to follow this rule so as to not be surprising to the user. There are two exceptions which allow the fork to replace the main cask:
> 1. The original discontinued software recommends that fork.
> 2. The fork is so overwhelmingly popular that it surpasses the original and is now the de facto project when people think of the name.

My understanding of this is that:
a. The cask was based on @kramred's fork of https://github.com/ungoogled-software/ungoogled-chromium-macos;
b. The fork is no longer being actively maintained (although there was a release 2023-02-26);
c. The original repo [ungoogled-software/ungoogled-chromium-macos](https://github.com/ungoogled-software/ungoogled-chromium-macos) now also provides binaries.

I think this change would be reasonable. @VulpesVulpes825 do you have any evidence to suggest either 1. or 2.? If not, I'll wait for another maintainer to chime in.

**Comment by p-linnane** [comment]
Seems reasonable, but I would like to get some confirmation from the current upstream before we change this.

**Comment by VulpesVulpes825** [comment]
> I think this change would be reasonable. @VulpesVulpes825 do you have any evidence to suggest either 1. or 2.? If not, I'll wait for another maintainer to chime in.

@razvanazamfirei Should be 1. The fork repo author is no longer have time to maintain the fork. (See [#2214](https://github.com/ungoogled-software/ungoogled-chromium/pull/2214#pullrequestreview-1254141943)). The author suggests the cask need to be updated to point to original repo. (See [#100](https://github.com/ungoogled-software/ungoogled-chromium-macos/pull/100#issuecomment-1474883050))

**Comment by razvanazamfirei** [comment]
> "The [cask code](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/eloston-chromium.rb) for homebrew needs an update to point here **(i.e. ungoogled-chromium-macos)** and all should be good again regarding installing/updating via brew." 

[source](https://github.com/ungoogled-software/ungoogled-chromium-macos/pull/100#issuecomment-1474883050)

This sounds reasonable! Thank you @VulpesVulpes825 for your contribution and willingness to hunt this down! You're awesome!

**Review by p-linnane — APPROVED** [review]
Thanks for the justification and your first contribution to Homebrew @VulpesVulpes825!

**Pull request merged**
