### PR TITLE
feat: add IPFS Desktop v0.7.0

### PR DESCRIPTION
**Pull request by hacdias**
Hii! I'd like to add IPFS Desktop if possible 😃 

I kept the name as `ipfs-desktop` because it is different from `ipfs` even though your documentation say to remove it.

Ref.: https://github.com/ipfs-shipyard/ipfs-desktop/issues/691

---

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by hacdias** [comment]
@vitorgalvao I don't know if `ipfs-desktop` should be called `ipfs` here. There's already an `ipfs` package on brew that is not a cask and it might generate some confusion, no?

**Comment by vitorgalvao** [comment]
> There's already an `ipfs` package on brew

There are several others in the same situation.

**Comment by hacdias** [comment]
@vitorgalvao it seems CI is emitting a warning because of that:

https://travis-ci.org/Homebrew/homebrew-cask/builds/507591873#L320

**Comment by vitorgalvao** [comment]
> it seems CI is emitting a warning because of that

Yes, that’s expected. It should be a warning and not a failure. I’ve verified the rest locally. Thank you for your contribution.

**Comment by hacdias** [comment]
@vitorgalvao thanks! I'll make sure to keep this cask updated 😄

**Pull request merged**
