### PR TITLE
Add Phoenix 1.2 (initial version)

### PR DESCRIPTION
**Pull request by keith**
First time submitting a cask. This passed audit locally. Let me know if anything needs to be changed!

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you. The cask itself looks good, but you should do a search before starting to work on a Cask. In this case, this was already here, [and has been removed](https://github.com/caskroom/homebrew-cask/pull/10734#issue-69478405).

**Comment by keith** [comment]
This is a different source repo which is separately maintained. Although it was originally a fork it is no longer one on GitHub.

**Comment by keith** [comment]
While I feel like this shouldn't be a big deal, if it is a blocker I could in theory change the name to solve this problem.

**Comment by vitorgalvao** [comment]
In that case, it needs to be renamed to `keith-phoenix`, anyway, since it is a fork. That’s in te documentation (I’m not linking you to it right now because I am not at my computer).

**Comment by keith** [comment]
Although this isn't actually a fork on GitHub and probably shouldn't be treated this way.

**Comment by vitorgalvao** [comment]
It’s still a fork. Not having it say “fork of” doesn’t change that. Users should be aware they’re not downloading the original.

**Comment by keith** [comment]
I disagree with that but I'll rename it so it can be considered "the original"

**Comment by vitorgalvao** [comment]
With all due respect, this is your first contribution. I have no idea how closely you have been following the project, but it seems that not very. Rules are in place because they need to be. Duplicates and confusion were a real issue that we worked hard on and discussed throughly to mitigate, and to do that we need hard rules and consistency. This is a pretty straightforward case, not even a case for exception. The author [**even says this is a fork**](https://github.com/keith/phoenix#history). What does it matter if they pressed “fork” or copied files to do it? Nothing.

**Comment by keith** [comment]
:+1: thanks for the explanation. Like I said I'm happy to rename the project to avoid confusion. I'll submit a PR once I've done so.

**Comment by vitorgalvao** [comment]
Thank you. There’s no harm in submitting this as `keith-phoenix` in the meantime and changing it later, but we don’t (yet) handle cask renames very well (although some code is already in place towards that), so I don’t necessarily advise that.

**Comment by keith** [comment]
Yea sounds good. I can wait till I do the rename. No need to complicate that for both of us! Hopefully I can do the rename today or tomorrow.

**Comment by kasper** [comment]
Hi! Just a quick shout-out. I took over maintaining the official Phoenix repository and will look into returning pre-built binaries once I’ve cleaned the project up a bit.

**Comment by keith** [comment]
:+1: I changed the name of my fork and it's available now https://github.com/caskroom/homebrew-cask/pull/12168

I've added at least 1 new feature so the config files are no longer perfectly compatible.

**Pull request closed without merging**
