### PR TITLE
Upgrade thebrain to v8.0.2.0 and fix install

### PR DESCRIPTION
**Pull request by scribblemaniac**

### CODE REVIEW

**Comment by scribblemaniac** [comment]
Sadly I don't see any way around the manual installer.

**Comment by vitorgalvao** [comment]
The trend for app installers is awful. I immediately trust them less. We still need an `uninstall`, for this, so we need to figure out what it does.

**Comment by scribblemaniac** [comment]
It really is, I guess I'll close this and open up an issue.

**Comment by vitorgalvao** [comment]
We can still leave this open while working on `uninstall`. No reason to throw away what’s already done.

**Comment by jawshooah** [comment]
To be fair, `pkg` installers aren't much better. Sure, they can be automated, but we still have no idea what they're doing under the hook outside of the file manifest, which isn't always accurate.

**Comment by vitorgalvao** [comment]
True. I dislike installers in general but at least `pkg` installers we understand are sometimes needed and look so “bare” we immediately get the sense of “this developer did it this way out of necessity”. `app` installers, on the other hand, need to be designed. Sure, they both can be bad or innocent, but it *feels* like one of them defaults to being more transparent than the other.

**Comment by vitorgalvao** [comment]
[What they say they do](https://twitter.com/mscaton/status/625768916258701312)

**Comment by jawshooah** [comment]
If that's the case, then `uninstall :delete => '/Applications/TheBrain.app'` and `zap :delete => '~/.TheBrain'` should be sufficient.

**Pull request closed without merging**
