### PR TITLE
Add Apptrap uninstall

### PR DESCRIPTION
**Pull request by dnicolson**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by dnicolson** [comment]
Why was the `login_item` stanza removed?

**Comment by vitorgalvao** [comment]
> Why was the `login_item` stanza removed?

Because no login item is added on install.

**Comment by dnicolson** [comment]
Most apps don't seem to add login items on install. [Itsycal](https://github.com/Homebrew/homebrew-cask/pull/54830), [Rocket](https://github.com/Homebrew/homebrew-cask/pull/54828) and [BitBar](https://github.com/Homebrew/homebrew-cask/pull/54827) were merged and they don't add login items on install.

**Comment by vitorgalvao** [comment]
> [Itsycal](https://github.com/Homebrew/homebrew-cask/pull/54830), [Rocket](https://github.com/Homebrew/homebrew-cask/pull/54828) and [BitBar](https://github.com/Homebrew/homebrew-cask/pull/54827) were merged and they don't add login items on install.

The more you mention your own submissions, the worse you’re making it. Those were merged because we *assumed* they were correct and it’s a non-destructive addition. It was only after I suspected your additions were wrong that I tested them on a VM and confirmed.

**Comment by vitorgalvao** [comment]
On further inspection, `itsycal` and `apptrap` are acceptable, because they have clear options to start on login and seem to encourage it. Chrome clearly doesn’t, though.

**Comment by vitorgalvao** [comment]
On further inspection, looks like the Chrome ones were the only incorrect ones. Apologies for having removed this one. Readding now.

**Comment by dnicolson** [comment]
Thanks. I'm unsure how Google Chrome and Google Chrome Canary were added as login items.

**Pull request merged**
