### PR TITLE
Font PalemonasMUFI 2.0 (new cask)

### PR DESCRIPTION
**Pull request by jellisjellisjellis**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [X] `brew audit --cask --new <cask>` worked successfully.
- [X] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @jellisjellisjellis.

Can you please remove all the `desc` stanzas -- we have recently decided to not bother with descriptions for fonts: https://github.com/Homebrew/homebrew-cask/pull/176580.

Thanks.

**Comment by jellisjellisjellis** [comment]
`desc` stanzas removed, `style`, `audit`, `install`, and `uninstall` tests re-run.

**Review by bevanjkay — APPROVED** [review]

**Comment by bevanjkay** [comment]
@jellisjellisjellis before we go ahead, I just want to confirm that there's no way to download all of the font variants at once? (In a single zip?)

**Comment by jellisjellisjellis** [comment]
Unfortunately, no. I've gone through the entire MUFI (Medieval Unicode Font Initiative) site and snooped URLs from archive.org. They consistently offer it as four individual files, and without a single download zip, as far back as I can find.

**Comment by miccal** [comment]
Thank you for your prompt replies and diligence here @jellisjellisjellis, most appreciated.

**Pull request merged**
