### PR TITLE
Firecamp upgraded to v0.7.0-rc-1

### PR DESCRIPTION
**Pull request by Nishchit14**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by suschizu** [comment]
@Nishchit14 - i can't find a download for version 0.6.9, 0.6.11 and 0.7.0-rv-1 on the website - the download there contains 0.6.7  - further, 0.7.0-rc-1 looks like a release candidate. 
@vitorgalvao - should this be reverted?

**Comment by vitorgalvao** [comment]
> should this be reverted?

Yes, to `0.6.7`, and we should add `https://firecamp.app/docs/installation` as an appcast.

**Comment by Nishchit14** [comment]
@suschizu thank you for informing. I am updating the doc. and release stable `0.7.0`

**Comment by suschizu** [comment]
hey @Nishchit14 - thanks - just ping me when you need help :)

**Pull request merged**
