### PR TITLE
Rename Amazon Zocalo to Amazon WorkDocs

### PR DESCRIPTION
**Pull request by mauricerkelly**
The Amazon Zocalo product has been renamed to WorkDocs. This PR 
consists of two commits - the first renames the cask file itself, 
while the second updates the contents. I _think_ this provides for
a more traceable history as the rename is preserved, whereas a 
single commit is more likely to appear as a deletion and recreation.

_Edit:_ Overall, it still shows as two files being changed, one deletion
and one creation, but the individual commits still show the actual actions.
Happy to squash if you'd prefer.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Can we download this without logging in?

**Comment by mauricerkelly** [comment]
Yes. No problem installing from command line on my machine.

**Comment by vitorgalvao** [comment]
I didn’t explain correctly. What I meant is “can we see the download link for this without logging in?”.

**Comment by mauricerkelly** [comment]
Ah, I get what you mean. Yeah. I picked it up from an Amazon page that lists the download links for Mac and Windows.




I'm away from computer right now, but I could include a link to the page as part of a comment later on this evening.




I hadn't thought a lot about it because I was updating from a similar kind of link. Sorry about that.

**Comment by vitorgalvao** [comment]
No need to comment on the cask itself, just please leave a comment on this thread, so users can find it in the future.

**Comment by mauricerkelly** [comment]
Cool. The page listing the download location is at: http://docs.aws.amazon.com/workdocs/latest/userguide/sync_client_help.html

**Pull request merged**
