### PR TITLE
Updated Natron homepage.

### PR DESCRIPTION
**Pull request by cafferata**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download natron` is error-free.
- [x] `brew cask style --fix natron` left no offenses.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You did not run the commands. There’s a failure.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 26a8eb93e33ecce087ea04b33e4bbb06569203cd. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by cafferata** [comment]
I updated the original PR with extra fixes, is this desirable?

**Comment by vitorgalvao** [comment]
It has already been fixed and merged.

**Pull request closed without merging**
