### PR TITLE
Update geburtstagschecker

### PR DESCRIPTION
**Pull request by tiiiecherle**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by miccal** [comment]
What make this change to the `app` stanza -- it is correct as-is?

**Comment by tiiiecherle** [comment]
I don't know if this is correct, but I thought
`app` should always specify the real app name in /Applications/APPNAME.app.

If not, how can I get the real installed app name form the cask?
I'm now using 

`brew cask info --json=v1 "$CASK" | jq -r '.[]|(.artifacts|map(.[]?|select(type=="string")|select(test(".app$"))))|.[]'`

But this only works if `app` is specified "correctly".

Thanks

**Comment by miccal** [comment]
> I don't know if this is correct, but I thought app should always specify the real app name in /Applications/APPNAME.app.

The `app` stanza is a link to the source file that is moved into the `/Applications` directory, as explained in the [documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md).

You can see that the test fails with:
```
Error: It seems the App source '/usr/local/Caskroom/geburtstagschecker/1.8.2,195/GeburtstagsChecker.app' is not there.
```
because the `.app` is inside the folder `GeburtstagsChecker #{version.before_comma} (#{version.after_comma})`.

**Comment by ran-dall** [comment]
@miccal You're correct on both accounts. Closing this.

**Comment by tiiiecherle** [comment]
O.k., thanks for the info. Would be nice if anyone could help out with [this](https://github.com/Homebrew/homebrew-cask/issues/83889).

**Pull request closed without merging**
