### PR TITLE
shotcut 24.09.19

### PR DESCRIPTION
**Pull request by J-A-M-E-5**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by J-A-M-E-5** [comment]
Not sure what to do now. Yes it is pre-release, but the last release files (v24.09.13) aren't there for downloading anymore so shotcut is **currently broken** in homebrew.

**Comment by p-linnane** [comment]
Previously attempted in https://github.com/Homebrew/homebrew-cask/pull/186487. CC @Homebrew/cask for thoughts.

**Comment by ddennedy** [comment]
Wow, such a strict system! All this trouble to successfully build a URL and download something. I can make the new release latest and non-pre-release even without all the other platform builds just to make homebrew happy. Maybe you can make a small change to retrigger the checks like remove the trailing slash from homepage, but there might be a check for that too! Or, something else  in the description such as "Free video editor" or "Multitrack video editor" or from our home page: "Shotcut is a free, open source, cross-platform video editor."

**Comment by p-linnane** [comment]
> Wow, such a strict system! All this trouble to successfully build a URL and download something. I can make the new release latest and non-pre-release even without all the other platform builds just to make homebrew happy. Maybe you can make a small change to retrigger the checks like remove the trailing slash from homepage, but there might be a check for that too! Or, something else in the description such as "Free video editor" or "Multitrack video editor" or from our home page: "Shotcut is a free, open source, cross-platform video editor."

I don't know why you consider it strict to expect a version to be consistent. Uploading binaries under an older tag is sloppy, insecure, and a poor user experience.

Descriptions are not for marketing fluff as defined in our [Cask Cookbook](https://docs.brew.sh/Cask-Cookbook#stanza-desc).

**Comment by ddennedy** [comment]
OK, then I will switch it back and you can fuck off

**Comment by p-linnane** [comment]
> OK, then I will switch it back and you can fuck off

You're only hurting your own users by acting this way. I'm closing this PR and banning you from interacting with Homebrew on GitHub.

**Pull request closed without merging**
