### PR TITLE
upgrade wiznote to 2015-06-16

### PR DESCRIPTION
**Pull request by ghost**
upgrade wiznote  to 2015-06-16

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please [amend](http://stackoverflow.com/a/179147/1661012) the commit message to include the name of the updated cask.

**Comment by dezon** [comment]
i will do that next time.

**Comment by vitorgalvao** [comment]
Please do it in this branch. The link teaches you how to.

**Comment by dezon** [comment]
oh..  it's ok now

**Comment by vitorgalvao** [comment]
Not the title of the the issue, the commit itself.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 8be65633e27e89def424a2dab96434a066644435. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
