### PR TITLE
Remove license from documentation

### PR DESCRIPTION
**Pull request by abookyun**
> @abookyun Mind also updating the documentation on https://github.com/caskroom/homebrew-cask?

Here I am. 😎 According to discussion here: https://github.com/caskroom/homebrew-cask/issues/17437 and https://github.com/caskroom/homebrew-cask/issues/16692. It's the second step of deprecating license stanza.

### CODE REVIEW

**Comment by abookyun** [comment]
Sorry, I just saw the comments below https://github.com/Homebrew/brew/pull/1235 talking about steps of deprecating process, and I'm not quite sure now if this PR is still needed?

**Comment by reitermarkus** [comment]
> I'm not quite sure now if this PR is still needed?

Yes, it is still needed, as the documentation is now located **only** here and has been removed from [Homebrew/brew](https://github.com/Homebrew/brew).

**Comment by abookyun** [comment]
@reitermarkus got it, thanks. I'll leave this PR here. 😎

**Review by vitorgalvao — APPROVED** [review]

**Comment by abookyun** [comment]
Yeah, thanks @vitorgalvao

**Pull request merged**
