### PR TITLE
orka3 3.0.0

### PR DESCRIPTION
**Pull request by svetlimladenov**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
I cannot find any mention of this version on https://orkadocs.macstadium.com/docs or https://orkadocs.macstadium.com/docs/downloads -- where did you get the `url` from?

I can only find mention of version 2.4.0, which already exists as a Cask: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/o/orka.rb

**Comment by svetlimladenov** [comment]
> I cannot find any mention of this version on https://orkadocs.macstadium.com/docs or https://orkadocs.macstadium.com/docs/downloads -- where did you get the `url` from?
> 
> I can only find mention of version 2.4.0, which already exists as a Cask: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/o/orka.rb

Thanks for the review @miccal !

We at [MacStadium](https://github.com/macstadium) are getting ready to put out a new Orka CLI called `orka3`. It's a completely new CLI that you can use alongside the old one. We want to make sure you can download it with `brew`  as soon as it comes out next week. That's why we're setting up a new Cask early. The documentation on the `homepage` will also be available next week. 

We just want to make sure the brew Cask is available on the release date. For us it's not a problem to merge it when the docs are published next week and everything is official.  What do you suggest here ?

**Comment by p-linnane** [comment]
I think this is fine to merge as is.

**Review by p-linnane — APPROVED** [review]

**Comment by bevanjkay** [comment]
@svetlimladenov Is the a new product that sits alongside the current `orka` cask or is it an update to version 2.4.0?

**Comment by miccal** [comment]
> I think this is fine to merge as is.

No it is not -- one of the versions should go into the `hombrew-cask-versions` repository.

**Comment by svetlimladenov** [comment]
> @svetlimladenov Is the a new product that sits alongside the current `orka` cask or is it an update to version 2.4.0?

Yes, it's a new cli that's supposed to sit alongside the current `orka` cask. 

Users of [Orka](https://www.macstadium.com/orka) will be able to use both `orka` and `orka3` as a cli based clients. That is why we named it `orka3` instead of just `orka`, and that is why we created a separate Cask.

**Review by bevanjkay — APPROVED** [review]

**Comment by svetlimladenov** [comment]
> > I think this is fine to merge as is.
> 
> No it is not -- one of the versions should go into the `hombrew-cask-versions` repository.

Please take a look in this comment https://github.com/Homebrew/homebrew-cask/pull/159271#issuecomment-1794427066 , because essentially `orka3` is a separate thing that users can use alongside `orka`.

Also after some time we will stop supporting the old `orka` cli, and we will make sure to remove it from the Casks.

What do you think, is it okay to merge it here ?

**Pull request merged**
