### PR TITLE
Update stereo-tool to 9.00

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
They upped the version but did not change the download?

**Comment by brianmorton** [comment]
@vitorgalvao well it uses a static (unversioned) download url - `http://www.stereotool.com/download/stereo_tool.zip` so that's not unusual I guess.

The unusual part is that the change announcement is in the appcast which is tagged for version `8.50` or more generiously, version `8` releases:
image

**Comment by vitorgalvao** [comment]
> well it uses a static (unversioned) download url - `http://www.stereotool.com/download/stereo_tool.zip` so that's not unusual I guess.

It is a bit unusual. It either means they’ve bumped the version but not updated the tool or that on the last update to the cask, the version wasn’t updated.

**Comment by brianmorton** [comment]
There are ~~lots~~ some casks that do this. I have previously recommended that we should just change those casks to be `:latest` and `:no_check`, but I think you all prefer to have versions and checksums... which I can understand. However in these cases I don't think it makes sense.

**Comment by vitorgalvao** [comment]
> but I think you all prefer to have versions and checksums

At one point we decided we had to make a decision on which we’d prefer (because there are many apps where we can have one or the other) and we let the users vote. They overwhelmingly preferred versioned casks.

**Comment by brianmorton** [comment]
I understand, but I still think it makes no sense at all in these cases. They are essentially just a waste of contrib time if the download URL is the same.

**Comment by vitorgalvao** [comment]
They’re not a waste because the shasum is (usually) updated.

**Pull request merged**
