### PR TITLE
cerebro: Discontinue

### PR DESCRIPTION
**Pull request by p-linnane**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.
---
Last macOS release was in 2017.

### CODE REVIEW

**Comment by p-linnane** [comment]
@miccal I think I figured out the CI issue we discussed yesterday. All the PR's that are failing are using runner image `20220922.2`. All PR's that successfully make it through CI are using `20220905.1`.

This PR used `20220905.1` to generate the matrix successfully, and then failed when it attempted the syntax check with `20220922.2`.

**Comment by ivaquero** [comment]
This project is still active

[cerebro-release](https://github.com/cerebroapp/cerebro/releases)

**Comment by p-linnane** [comment]
> This project is still active, its release link was probably changed
> 
> [current-cerebro-release](https://github.com/cerebroapp/cerebro/releases)

I've marked this as discontinued not because the project itself is discontinued, but because there has been no new macOS release for almost 5 years.

**Comment by ivaquero** [comment]
> > This project is still active, its release link was probably changed
> 
> > 
> 
> > [current-cerebro-release](https://github.com/cerebroapp/cerebro/releases)
> 
> 
> 
> I've marked this as discontinued not because the project itself is discontinued, but because there has been no new macOS release for almost 5 years.

Thanks for the explanation. I just found there is no macOS installers in the recent releases.

**Review by miccal — APPROVED** [review]

**Pull request merged**
