### PR TITLE
Fix support for El Capitan (working if SIP is off)

### PR DESCRIPTION
**Pull request by ckreon**

### CODE REVIEW

**Comment by victorpopkov** [comment]
Please [amend](http://stackoverflow.com/a/179147/1661012) the commit message to include the name of the updated cask.

**Comment by vitorgalvao** [comment]
The correct way to fix this is to remove `depends_on`.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 945a695a3027741f2b399c68dc63c7cb68553f8e. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by ckreon** [comment]
This was my first real pull request - thank you for fixing it, and apologies for the mistakes!

**Pull request closed without merging**
