### PR TITLE
Update youtube-dl-gui from 2.2.2 to 2.3.0

### PR DESCRIPTION
**Pull request by i0ntempest**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by i0ntempest** [comment]
Upstream has changed the app name (display only, bundle ID remains the same), should we move this cask file?

**Comment by bevanjkay** [comment]
@i0ntempest We should update the cask token, name etc.. to reflect upstream. So yes. 👍🏻

**Comment by i0ntempest** [comment]
Do we just remove this file then and expect users to manually reinstall using the new file? Or there's a way to modify this one to point to the new one?

**Comment by bevanjkay** [comment]
@i0ntempest I'll let some of the other maintainers chime in on this one, as I'm not 100% sure of the correct process here.

@Homebrew/cask

**Comment by vitorgalvao** [comment]
> Do we just remove this file then and expect users to manually reinstall using the new file?

Yes.

> Or there's a way to modify this one to point to the new one?

No. That’s the most pressing feature we’re missing—an equivalent to `formula_renames.json` for casks.

It’s a subpar experience but it’s what we have until someone implements the feature (PRs welcome). In the past we’ve tried workarounds or pointing some casks to others, but that’s not something I recommend anyone trying, it’s a nightmare of workarounds.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
