### PR TITLE
Update postman from 9.12.2 to 9.13.0

### PR DESCRIPTION
**Pull request by rgoldberg**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
```
Version '9.13.0' differs from '9.12.2' retrieved by livecheck.
```
@rgoldberg please do not submit PR's to update this Cask until `brew livecheck postman` shows the same version, thanks.

**Comment by rgoldberg** [comment]
If that's the case, then the bump command should do a live check and and not submit if it fails. I don't know if every cask should do this. Of not, there should be a cask setting to optionally do the live check, and this cask should use that setting.

**Comment by neutric** [comment]
`brew bump-cask-pr --online` will run `brew audit --online` before opening the PR, which would have failed with

```
audit for postman: failed
 - Version '9.13.0' differs from '9.12.2' retrieved by livecheck.
Error: 1 problem in 1 cask detected
Error: `brew audit` failed!
```
in this case.

**Comment by rgoldberg** [comment]
Thanks for info. There should be a way for cask maintainers to force the cask bump to automatically run that without forcing the user to know about it. I assume, however, that is not currently possible.

**Comment by MikeMcQuaid** [comment]
> If that's the case, then the bump command should do a live check and and not submit if it fails.

You can probably use `brew bump` to do this instead.

**Pull request closed without merging**
