### PR TITLE
Update powerpanel from 1.1.0 to 2.2.0

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by miccal** [comment]
The `dmg` now contains `CyberPower PowerPanel Personal Installer.app`, so I think this will need to be re-worked with an `installer manual:` and possibly an updated `uninstall`.

**Comment by core-code** [comment]
try adding

`  installer manual: 'CyberPower PowerPanel Personal Installer.app'
`

**Comment by core-code** [comment]
looks better now, thanks.

lets merge this now, and hope improved uninstall will be contributed.

**Comment by core-code** [comment]
but can you add

  uninstall delete: '/Applications/CyberPower PowerPanel Personal'

**Comment by suschizu** [comment]
thanks @core-code ❤️

**Comment by suschizu** [comment]
`curl: (28) Failed to connect to github.com port 443: Operation timed out
##[error]Process completed with exit code 28.
`

**Pull request merged**
