### PR TITLE
Add Keet 1.1.0

### PR DESCRIPTION
**Pull request by thom4parisot**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by p-linnane** [comment]
Any reason this doesn't also include the Intel build?

**Comment by thom4parisot** [comment]
> Any reason this doesn't also include the Intel build?

I did not know how to specify for both architectures, solely by looking at the official Cask Cookbook.

I managed to find pieces of answer here and there.
Thanks for asking, it gave me the kick to look for it.

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @thom4parisot.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by thom4parisot** [comment]
You're welcome!

Thanks for mentioning the zap. Executing `brew createzap keet` returned "No keet settings found.", even after running the application. Should I investigate further?

**Comment by miccal** [comment]
Thank you @thom4parisot.

**Review by miccal — APPROVED** [review]

**Pull request merged**
