### PR TITLE
headlamp 0.25.0-1

### PR DESCRIPTION
**Pull request by joaquimrocha**
In the last fix to 0.25.0, we didn't bump the version, so current installations of that version are kept with the broken binaries. Having this new build version should force the update for those users.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by joaquimrocha** [comment]
Hmm, seems like it validates the version from the file names. Should I rename those files in our release assets to be Headlamp-0.25.0-1-#{arch}-x86.dmg ? Or is just a CI test that can be ignored in this very specific case which is just about being able to trigger an update for users of the 0.25.0 version which may be broken?

**Comment by joaquimrocha** [comment]
> Hmm, seems like it validates the version from the file names. Should I rename those files in our release assets to be Headlamp-0.25.0-1-#{arch}-x86.dmg ? Or is just a CI test that can be ignored in this very specific case which is just about being able to trigger an update for users of the 0.25.0 version which may be broken?

I tried to work around this by adding a new binary with the version 0.25.0-1 in its name but apparently that's not where the version is being picked from. We cannot release a new version in Github just for this because it was a build error not an app one. So if the CI validation is not the same that brew actually does in the CLI (i.e. if installing this in the CLI works), I would ask you to please ignore the test, check that the binaries are correctly referenced, and accept the PR just so users who installed that broken 0.25.0 version can successfully update without requesting a reinstall.

**Comment by illume** [comment]
Hello. 

ok, CI is passing now. 

Note:  Although I changed the version number in the filename, I couldn't get livecheck to work with -1 version files( `Headlamp-0.25.0-1-mac-x64.dmg` ). So after trying many things and not getting anywhere I disabled livecheck. With the next release we can enable livecheck and put the version back into the URL.

I hope this is ok. Thanks.

**Review by samford — COMMENTED** [review]
I tried to push a commit to fix the issues with this PR but you may have unchecked the box that allows maintainers to push to your branch. In the future, please leave that option enabled, as it makes it easier for maintainers to review and fix issues with PRs. You can pull the commit from my branch here: https://github.com/samford/homebrew-cask/commit/293b145920f3cbe3e8c1e170e0172e333bf5b172

The aforementioned commit:

* Updates the `url` to handle the optional suffix appropriately (i.e., removing the suffix from the tag name when interpolating the `version`, as the tag/filename version differ).
* Updates the repository path in the `url`.
* Updates the `homepage` to resolve the redirection.
* Adds a `livecheck` block that checks the "latest" release on GitHub and matches the version from the dmg filename, handling versions like `1.2.3` and `1.2.3-4`.
* Adds `depends_on macos`, to address the related audit.

Past that, a `livecheck` block using `skip "No version information available"` should only be used when there truly isn't any version information available to check, which isn't the case here. `#skip` isn't meant to be used just to avoid the livecheck audit, so please keep that in mind.

Lastly, your commit should use a `headlamp 0.25.0-1` title (instead of `In the last fix to 0.25.0, we didn't bump the version, so current`). That's something else I addressed in my branch that should be fixed here.

**Comment by illume** [comment]
Thanks @samford

I pulled in your change, and updated the previous commit title as requested. I don't have permission to update push permissions on that repo/branch.

**Review by p-linnane — APPROVED** [review]

**Comment by samford** [comment]
Thanks, @illume. Unless there are specific restrictions for that fork's repo/branch, it may have just been that the "Allow edits and access to secrets by maintainers" checkbox was unchecked when creating the PR (it's checked by default, as in the screenshot below). Unfortunately, I don't think there's a way to modify that setting after the PR is created. Anyway, we got to where we wanted to be in the end 👍

Allow edits checkbox in the PR creation interface

**Pull request merged**
