### PR TITLE
rescuetime: bump version, update livecheck, update url

### PR DESCRIPTION
**Pull request by bevanjkay**
See https://github.com/Homebrew/homebrew-cask/pull/119932#issuecomment-1063206142

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by k4rtik** [comment]
@bevanjkay @SMillerDev this update should not have been merged without careful reading of what RT v3 is about. It led to all sorts of problems for me. See: https://community.rescuetime.com/t/whats-with-the-new-sudden-unannounced-changes/126/3

RescueTime v3 seems like a completely different product. There should perhaps be two different casks for the classic RT v2.16.7.1 and another for RTX starting with v3.0.13.2.

If you all agree, I can send a PR to make that happen.

**Comment by bevanjkay** [comment]
@k4rtik the cask was updated to version 3 on advice from the upstream vendor. 

A cask for version 2 could be submitted to `homebrew-cask-versions`.

**Comment by k4rtik** [comment]
> the cask was updated to version 3 on advice from the upstream vendor.

Who is the upstream vendor here? 

RT does not recognize brew as a source of distributing itself, see https://community.rescuetime.com/t/whats-with-the-new-sudden-unannounced-changes/126/6?u=kartik

**Comment by k4rtik** [comment]
Oh, I see the comment linked in the OP now. I don't know if we should consider a cask in `homebrew-cask-versions`. This is a breaking change for existing users (like it was for me) when we upgrade, that too without any notice!

The user-facing product is called RescueTime X (v3) and they are calling the older product RescueTime Classic.

Would it be acceptable to keep this cask to continue to be v2.x and send a PR for another called `rescuetime-x`?

**Comment by SMillerDev** [comment]
> Would it be acceptable to keep this cask to continue to be v2.x and send a PR for another called rescuetime-x?

I would prefer a new cask for rescuetime-classic. This version is the future of rescuetime according to upstream so that should be the default.

**Pull request merged**
