### PR TITLE
Suggesting to install bash completion for vagrant from homebrew repo.

### PR DESCRIPTION
**Pull request by epsimatic**

### CODE REVIEW

**Comment by ndr-qef** [comment]
The desire for convenience is understandable, but I feel that `caveats` should address critical issues, not general usage recommendations.

Admittedly, there is no strict policy concerning the content of `caveats`. @vitorgalvao, if you disagree, feel free to merge.

**Comment by vitorgalvao** [comment]
I agree.

Thank you for the contribution nonetheless, @epsimatic, and apologies for taking so long. Sometimes a submission slips through and no one notices it for a while.

**Comment by phinze** [comment]
Hmm if we have to turn away something that will improve UX simply for lack of a semantic home, I wonder if there's a missing Cask feature here? It'd be nice to allow Casks to include usage recommendations. I'll spin up an issue.

**Comment by vitorgalvao** [comment]
My biggest issue with it is the more messages we output, the more they all blend and the sooner they’ll start to be ignored. There are some messages that really need to be shown for the experience to not be broken, and if we start to blend many optional suggestions there, users will start to ignore the important ones as well.

I believe the sentiment when a `caveat` goes by and you missed it should be “wait, what was that? I should go back and check”, and never “wait, what was that? Meh, probably nothing important”.

**Pull request closed without merging**
