### PR TITLE
Bumping macFUSE to 4.0.4

### PR DESCRIPTION
**Pull request by mys721tx**
Bumps osxfuse 3.11.2 to macFUSE 4.0.4. The old caveat is removed as the
new version does not come with a kernel extension.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by fluffy-critter** [comment]
sshfs has a package dependency on osxfuse. Does this change ensure that sshfs continues to have its dependencies satisfied?

**Comment by mys721tx** [comment]
No, it would require updating Homebrew/brew and Homebrew/homebrew-core.

**Comment by core-code** [comment]
looks like a duplicate of https://github.com/Homebrew/homebrew-cask/pull/94187

**Comment by miccal** [comment]
> looks like a duplicate of #94187

Correct.

**Pull request closed without merging**
