### PR TITLE
Update Brave to 0.11.4dev

### PR DESCRIPTION
**Pull request by jikkujose**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

Couldn't figure out how to test the others with the changes; sorry to issue a PR, but hope someone will explain how to do it?

### CODE REVIEW

**Comment by reitermarkus** [comment]
You need to run `brew cask audit --download brave` and `brew cask style --fix brave`.

**Comment by JikkuJose** [comment]
I did those! But it mentioned I have the old version! How can I have the new changes in the system installed version.

**Comment by jawshooah** [comment]
You can pass the path to your updated Cask instead of just the token. So from the root of your fork, run `brew cask audit --download Casks/brave.rb; brew cask style Casks/brave.rb`

**Comment by JikkuJose** [comment]
Cool, I just did that & saw the appcast URL I added was wrong. But take a look at the warning I got:
```
==> Downloading https://github.com/brave/browser-laptop/releases/download/v0.11.4dev/Brave.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask brave
audit for brave: warning
 - appcast checkpoint mismatch
Expected: 7c389e357ae08cb0f7d9e20108fe239da609514d09c1fbcb94192998f570b6c5
Actual: 117a5d415417dd259a47dda70905f937be8fd60eca546f8df02c4716fbe59cea
Error: audit failed for casks: brave
```

I think the message had the hashes __specified__ mistakenly! That is, the hash I had used originally was `7c3..`, I changed it to the `117..` to get it pass the audit. But, I guess the labels should have been switched? My original hash should have been denoted __Actual__ & the expected one should have been well, __Expected__.

**Comment by adidalal** [comment]
Can you see if you run into the same issues when you use our script?

Check out `cask-repair`, it makes Cask updates like this quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

**Comment by JikkuJose** [comment]
Thanks, hope the new update was as per the guidelines. But I wish to wrap my head around the process! Where can I understand in a bare bones manner what appcast is without that script?

**Comment by adidalal** [comment]
Updating the `:checkpoint` value in `appcast` is required. You can find it with `curl --silent --compressed "{{appcast_url}}" | sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256 | awk '{ print $1 }'`.

There's a appcast stanza [docs](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md)?

**Pull request merged**
