### PR TITLE
dnagedcom 3.1.3.8 (new formula)

### PR DESCRIPTION
**Pull request by alexreg**
DNAGedcom app (Client for downloading & analyzing DNA matches from testing/comparison websites)

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by alexreg** [comment]
See also <https://github.com/Homebrew/homebrew-cask-versions/pull/10519>.

**Comment by alexreg** [comment]
We'll need a simple follow-up PR to uncomment the `conflicts_with` PR.

**Review by vitorgalvao — DISMISSED** [review]

**Comment by alexreg** [comment]
Thanks!

**Comment by alexreg** [comment]
Oops, I thought this PR had already merged too, sorry. Hope I didn't mess things up my squashing your commits.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
