### PR TITLE
silentknight 2.9

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
@samford The filename vs version does not appear to be a one-off change, since we've been having to update this manually each time. Can you think of a better way of handling this?

**Comment by samford** [comment]
> The filename vs version does not appear to be a one-off change, since we've been having to update this manually each time. Can you think of a better way of handling this?

What's unusual is that the version is 2.9 in the app, the plist, and on the [Downloads page](https://eclecticlight.co/downloads/) and it's only the zip filename that uses the zero-padded format (209). T2M22 uses a 2.02 version format, so the `Version` and the no-dots version in the filename align.

Assuming 2.9 is the real version, we could remove the version format override from the `livecheck` block (so it returns `2.9,2024.06`) and zero-pad the minor version (when < 2 digits) in the cask `url` instead (i.e., 2.9 would be 209 but 2.10 would be 210). Assuming that's feasible, does that sound good?

Outside of that, we may want to ask upstream about this mismatch, to see if they will use a more reasonable approach (e.g., aligning the version and no-dots version like 2.9 -> 29 or abandon the no-dot approach altogether and use a version with dots in the filename).

**Comment by p-linnane** [comment]
> Assuming 2.9 is the real version, we could remove the version format override from the `livecheck` block (so it returns `2.9,2024.06`) and zero-pad the minor version (when < 2 digits) in the cask `url` instead (i.e., 2.9 would be 209 but 2.10 would be 210). Assuming that's feasible, does that sound good?

This makes the most sense.

**Comment by samford** [comment]
I pushed a commit to update the `version`/`url` format and remove the override from the `livecheck` block. The way I handled the zero-padded no-dot version in the `url` is pretty gnarly (I'm certainly open to a better solution) but it works. This is only an issue while the minor version is less than two digits, so we should be able to switch back to `version.csv.first.no_dots` with version 2.10+.

**Comment by miccal** [comment]
Very nice :)

**Review by miccal — APPROVED** [review]

**Pull request merged**
