### PR TITLE
jamie 4.0.3

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by antonengelhardt** [comment]
@krehel Hi, do you have some automation for bumping casks or do you do it manually? I'm trying to build one too for that cask.

**Comment by bevanjkay** [comment]
The cask can be added to our [`autobump`](https://github.com/Homebrew/homebrew-cask/blob/master/.github/autobump.txt) list, then it will be checked for updates every couple of hours.

**Comment by antonengelhardt** [comment]
@bevanjkay Ok, thanks. And then I probably have to set up the autobump.yaml workflow too?

**Comment by bevanjkay** [comment]
@antonengelhardt There's an action that @BrewTestBot runs that handles the opening of the PR and bumping.

**Comment by krehel** [comment]
Not sure how often this gets bumped.  I try to "re-balance" the `autobump.yml` file every few weeks or monthly to cycle in some frequently updated software.

You're always free to set up something on your side to open a PR on an update for this.  Please don't do any mass automation though! 😄 

Raycast do something similar - you can see https://github.com/Homebrew/homebrew-cask/pull/167314 as an example.

**Comment by antonengelhardt** [comment]
@krehel Just started with this: https://github.com/antonengelhardt/jamie-release/blob/main/.github/workflows/brew.yaml

Only problem is with git i believe...

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
