### PR TITLE
Add Elgiganten Cloud Latest

### PR DESCRIPTION
**Pull request by Cubixzno1**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by Cubixzno1** [comment]
I can't see to remove the CEWE file. But I'll make a new pull request. Sorry for the inconvenience

**Review by vitorgalvao — APPROVED** [review]

**Comment by ran-dall** [comment]
> Thanks for the edit :) I tried using :latest and :no_check but the it prompted me with "Expected: No check" Received: .shasum bla bla bla.

@Cubixzno1 I'm not sure what you're referring to when you refer to 'it', but normally we try to stay away from this setup as much as possible. It might have been letting you know that it's really not preferential to use this unless you're sure that the package gets updated in place. That would mean that for whatever reason, it's not convenient/possible for HBC to track the `version` or the `sha256`

As for Travis failing, you can only add one Cask per PR.

**Comment by Cubixzno1** [comment]
@ran-dall 
It should have been a "then it" referring to the program :) hehe. My bad! 

I saw the error with multiple cask at one, but I doesn't seem to understand have to mange multiple pull request.. I'll try figure that out :) 

Have a great one!

**Comment by Cubixzno1** [comment]
@vitorgalvao 

After you edit it seems like there's and efter when travis-ci checks it:
`Error: Cask 'elgiganten-jotta' definition is invalid: invalid 'sha256' value: ':nocheck'`

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
