### PR TITLE
Updated Microsoft Teams to 1.2.00.1761 and changed to now-default pkg installer

### PR DESCRIPTION
**Pull request by mylesagray**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by reitermarkus** [comment]
This needs a rebase.

**Comment by vitorgalvao** [comment]
Why did the version go *down*?

**Review by vitorgalvao — APPROVED** [review]

**Comment by vitorgalvao** [comment]
> ==> Uninstalling packages:
com.microsoft.teams
==> Purging files for version 1.2.00.1761 of Cask microsoft-teams
Permission denied @ rb_sysopen - /Library/LaunchDaemons/com.microsoft.teams.TeamsUpdaterDaemon.plist

**Comment by core-code** [comment]
in my opinion we should avoid using pkgs, if app downloads are available too. 
whats the official rule regarding this?

**Comment by vitorgalvao** [comment]
> whats the official rule regarding this?

I think we don’t have anything written down.

> in my opinion we should avoid using pkgs, if app downloads are available too.

But that‘s my view as well.

But in this case, *are* app downloads still available? And will they continue to be? I only see the pkg in the download page, and if they’re phasing out app downloads, might as well change early.

**Comment by core-code** [comment]
> But in this case, _are_ app downloads still available? 

yes, the latest official version is '1.2.00.1761' and the app is still available and the cask is still working

> And will they continue to be? 

well, we never know anything about the future ;)

> I only see the pkg in the download page, and if they’re phasing out app downloads, might as well change early.

why not perform the change when and if the app/dmg goes away?

**Comment by mylesagray** [comment]
The pkg format seems to be the de-facto one going-forward see screenshot from in app with the .app version installed:

https://www.dropbox.com/s/t0rzao8p8fneycq/Screenshot%202019-02-15%2015.44.38.png?dl=0

The download link forces you to the pkg installer and it provides auto-updating built in.

I imagine it it a matter of time before it goes away, and it would be prudent to make the change early, resulting in no loss of functionality than waiting for the app link to break.

**Comment by core-code** [comment]
> resulting in no loss of functionality than waiting for the app link to break.

thats not a problem, i can check the cask daily

> one going-forward see screenshot from in app with the .app version installed

ok thats a problem - if users having the app version installed get weird messages bugging them to change. 

so i guess changing over to the pkg is necessary after all. can you rebase or submit a new PR against the current version of the cask? thanks!

**Comment by mylesagray** [comment]
Can do.

**Comment by mylesagray** [comment]
@core-code - updated cask to latest version and includes original fix to pkg installer.

**Comment by core-code** [comment]
thanks, looks good to me ;) no idea about the travis error, hope the team can figure it out.

**Comment by core-code** [comment]
ping

**Comment by vitorgalvao** [comment]
Ran it in a VM. Worked fine.

**Pull request merged**
