### PR TITLE
Update loom from 0.100.3 to 0.102.0

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
@homebrew/cask thoughts on this change?

**Review by gdams — APPROVED** [review]
LGTM, I've noticed a few casks where the arm version has a postifx/prefix to the URL.

**Comment by vitorgalvao** [comment]
I’d be for it if it meant we could do without the larger conditional, but as it stands we’re using the same number of (non-empty) lines and doing the same conditional check twice.

We do gain a negligible amount of bytes, but at the (also small) expense of comprehension, especially of non-programmers. I like ternaries, but they are more obtuse than if-statements. Because we still need the if-statement, I don’t see the advantage.

**Review by SMillerDev — APPROVED** [review]
Personally I find it to be easier to keep track of the changes that don't differ a lot this way. You don't have to keep track of two places where you have to check the URL, two places for the livecheck. You just have the url with a possible suffix, and the livecheck with the possible suffix.

**Pull request merged**
