### PR TITLE
Add ppamorim-fruit v1.0

### PR DESCRIPTION
**Pull request by ppamorim**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by ppamorim** [comment]
Any idea why this cask is conflicting with the formulae? I have renamed it to `ppamorim-fruit` but I am not sure if it's needed.

**Comment by vladimyr** [comment]
> Any idea why this cask is conflicting with the formulae? I have renamed it to `ppamorim-fruit` but I am not sure if it's needed.

You need to rename the file to `ppamorim-fruit.rb` too.

**Comment by miccal** [comment]
@ppamorim unfortunately this submission will not meet the [notability requirements](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md).

**Comment by ppamorim** [comment]
@vladimyr that's not the main question. The question is why there is no cask file named like `fruit` but it's available in the formulae (and why they are mixed?)?

@miccal I totally disagree with this rule. I am especially adding it in the `cask` to be able to distribute the binary to possible users.

**Comment by vladimyr** [comment]
> @vladimyr that's not the main question. The question is why there is no cask file named like `fruit` but it's available in the formulae (and why they are mixed?)?

Ok, let's take a step back. You tried to add cask named `fruit` and CI warned you about name clash with existing **formula**. Homebrew doesn't allow name clashes between **casks** and **formulas**. There is no **cask** named `fruit` but there is a **formula** named `fruit` → https://github.com/Homebrew/homebrew-core/blob/master/Formula/fruit.rb

> @miccal I totally disagree with this rule. I am especially adding this binary in the `cask` to be able to distribute the binary to possible users. Why not create a "quarantine" like status for projects that does not qualify in this status?
> Also, why this is not added in the checklist?

You can distribute the binary from your own tap too. It isn't in the checklist but it is clearly outlined in the docs. Staging tap proposal is pretty much off-topic and should be discussed separately but FWIW it is easier said than done. Creating a tap is easy but maintaining it is a different kind of story. I'm quite sure maintainers here are busy enough with the `homebrew-cask` (_production_) tap and one wouldn't want to put another (_staging_) one on their maintenance task list.

**Comment by ran-dall** [comment]
@ppamorim First off, thanks for making your first contribution to HBC! Also, really nice work on that screen saver. I might actually use it. 

> @ppamorim unfortunately this submission will not meet the notability requirements:
>>A self-submitted app from a GitHub repository that is not notable enough (under 50 stars)

---
> @miccal I totally disagree with this rule. I am especially adding this binary in the `cask` to be able to distribute it to maximum number of possible users. Why not create a "quarantine" like status for projects that does not qualify in this status?
> Also, why this is not added in the checklist?

Unfortunately, @miccal is correct. To even take it a step further, we're updating these requirements in #81026. So at this time, it looks like this would not fall under those requirements; and as much as I hate to say, we cannot accept this at this time. However, might I suggest you host this on a personal tap? Also, you're always welcome to resubmit this in the future too when this does meet the requirements.

> A self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 30 forks, 30 watchers, and 75 stars).

**Pull request closed without merging**
