### PR TITLE
Update teamviewer from 15.16.8 to 15.17.6

### PR DESCRIPTION
**Pull request by LanikSJ**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Is TeamViewer app actually showing **15.17.6** version number?
If so, then TeamViewer isn't properly updating version info.

The failure is due to appcast URL showing latest version as **15.16.8**: https://download.teamviewer.com/download/update/macupdates.xml?id=0&lang=en&version=14.7.1965&os=macos&osversion=10.15.1&type=1&channel=1

I also tried an `extract_plist` of DMG URL and it shows **15.16.8**.

According to their changelogs: https://community.teamviewer.com/English/categories/change-logs-en
TeamViewer is still on **15.16** release.

**Comment by LanikSJ** [comment]
Yes I'm getting the new version from the internal updater.

**Comment by cho-m** [comment]
It could be that TeamViewer is staging their updates and will update appcast/homepage later.

Someone may need to check if DMG from Cask ends up installing 15.16.8 or 15.17.6 since the URL is unversioned: https://download.teamviewer.com/download/TeamViewer.dmg

---

I did find a "major"-version specific RSS feed with the 15.17.6 version number: https://dl.teamviewer.com/download/version_15x/update/macupdates.xml

However, all the URLs (pkg/zip) from this XML end up returning 404 Not Found.

I also found some unlisted download URLs for pkg/zip (not dmg)
- https://dl.teamviewer.com/download/version_15x/update/15.17.6/TeamViewer.pkg
- https://dl.teamviewer.com/download/version_15x/update/15.17.6/TeamViewer.zip

Someone needs to track down if any of these links are actually valid.

**Comment by cho-m** [comment]
@LanikSJ Looks like RSS and Changelog were updated today:
- e.g. Changelog: https://community.teamviewer.com/English/categories/change-logs-en

So, probably can re-run CI tests.

**Comment by rgoldberg** [comment]
Does anything else need to be done before this can be reviewed & merged?

Thanks.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
