### PR TITLE
Add Octohub.app version 0.1

### PR DESCRIPTION
**Pull request by vinkla**
The missing app for GitHub. http://octohubapp.com/

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Can this be used without an invite? They’re not very clear on that.

**Comment by jawshooah** [comment]
Nope, just tried. You need a verification code.

**Comment by vitorgalvao** [comment]
It should then be considered a private beta. Thank you for the contribution as always, @vinkla, but adding something most users won’t be able to use is a bit weird. We should wait until they release something publicly usable.

**Comment by vinkla** [comment]
Okay, I'll keep the branch until its out of beta.

**Comment by jawshooah** [comment]
Looks like invitations are [no longer required](https://rink.hockeyapp.net/apps/8e6427d1be6e591e851b554c57a77dfc). Care to update the Cask, @vinkla?

**Comment by vinkla** [comment]
Done.

**Pull request closed without merging**
