### PR TITLE
Add PopKey.app v1.0.0

### PR DESCRIPTION
**Pull request by knilob**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 44f39ad56b1503451676c02e9e1e3938970f4eb5. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by knilob** [comment]
Was the only addition/fix the comment about Amazon AWS?

**Comment by vitorgalvao** [comment]
Yes.

**Comment by knilob** [comment]
OK, I just wanted to make sure I didn't bork it up as bad as did last time. 😃

**Pull request closed without merging**
