### PR TITLE
Update double-commander

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
we should use the preferred 'Cocoa' version instead of the 'QT' version that is only for systems older than El Capitan and will probably disappear soon

**Comment by kaznovac** [comment]
@core-code can you also introduce the `qt` version. this `cocoa` build is quite unstable on my mohave installation?

**Comment by vitorgalvao** [comment]
> this `cocoa` build is quite unstable on my mohave installation?

Please take that up with upstream.

**Comment by core-code** [comment]
[double-commander-qt.rb.txt](https://github.com/Homebrew/homebrew-cask/files/3493505/double-commander-qt.rb.txt)
i've attached the latest cask for the QT version for your convenience. can you send a PR to get it added through the normal channels? 
https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#adding-a-cask

**Comment by core-code** [comment]
sorry didn't see that comment earlier.

**Comment by kaznovac** [comment]
Thanks core-code.

@vitorgalvao `Qt` is a variation is more mature than `cocoa` GUI build.
Vendor provides both variations - it would be great if `brew cask` provides them both also (IMHO more mature and stable version unsufixed, and alternatives clearly differentiated).

Do you think `Qt` variation is viable candidate for `cask-versions`?

**Comment by vitorgalvao** [comment]
@kaznovac No, due to its dependency on systems older than what we officially support. I recommend you use a personal tap if you need the older cask.

**Pull request merged**
