### PR TITLE
Add cask "digidna-silicon" v1.0.3

### PR DESCRIPTION
**Pull request by singularitti**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by singularitti** [comment]
I know this is rejected in PR #93552, but it is very useful and I have been used it for almost a month and find it stable.

**Review by vitorgalvao — APPROVED** [review]

**Comment by cixtor** [comment]
@singularitti, @zgosalvez, @vitorgalvao does Cask `silicon.rb` conflicts with Formula `silicon.rb`?

[1] https://github.com/Homebrew/homebrew-cask/blob/master/Casks/silicon.rb  
[2] https://github.com/Homebrew/homebrew-core/blob/master/Formula/silicon.rb

**Comment by singularitti** [comment]
> @singularitti, @zgosalvez, @vitorgalvao does Cask `silicon.rb` conflicts with Formula `silicon.rb`?
> 
> [1] https://github.com/Homebrew/homebrew-cask/blob/master/Casks/silicon.rb
> [2] https://github.com/Homebrew/homebrew-core/blob/master/Formula/silicon.rb

I got that message when I was doing this PR, that's why I name it `digidna-silicon` at first. Let's see the developer's opinion.

**Comment by zgosalvez** [comment]
@cixtor, it appears that it does. You can see the actual error/warning by the test here in my PR. https://github.com/Homebrew/homebrew-cask/pull/96997

**Comment by vitorgalvao** [comment]
> does Cask `silicon.rb` conflicts with Formula `silicon.rb`?

No, they don’t conflict because they don’t try to install things in the same place. It’s a case of using `brew install silicon` or `brew install --cask silicon` as appropriate.

The warning is for possible duplicates, which doesn’t seem to the case here.

**Pull request merged**
