### PR TITLE
Upgrade MaciASL.app to v1.4

### PR DESCRIPTION
**Pull request by linuslin0**
Version v1.4 dropped support for Mac OS X Lion, use v1.3 for Lion.

### CODE REVIEW

**Comment by fanquake** [comment]
Please squash your commits.

**Comment by adityadalal924** [comment]
[Here's how to do it](http://davidwalsh.name/squash-commits-git), if you need it!

**Comment by linzhouyu** [comment]
Forgot to do the squash, sorry about that. It should be OK now.

**Comment by victorpopkov** [comment]
Thank you for the contribution. It was merged directly as 6671f81e153026340338a58d95eb45cad7df71bf to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
