### PR TITLE
Update macpar-deluxe to 5.1.1

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
I can't reproduce this error:
curl: (22) The requested URL returned error: 416
Download failed on Cask 'macpar-deluxe' with message: Download failed: https://www.xs4all.nl/~gp/MacPAR_deLuxe/MacPARdeLuxe.dmg
Download works

**Comment by vitorgalvao** [comment]
> I can't reproduce this error:
> curl: (22) The requested URL returned error: 416

I get `curl: (16) Error in the HTTP2 framing layer`.

**Comment by suschizu** [comment]
you are right - me too … is there something we can do here?

**Comment by vitorgalvao** [comment]
Maybe a [parameter](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#additional-https-url-parameters) works.

**Pull request closed without merging**
