### PR TITLE
Add BunqDesktop.app v0.8.1

### PR DESCRIPTION
**Pull request by nduijvelshoff**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Review by commitay — APPROVED** [review]

**Comment by nduijvelshoff** [comment]
@commitay app must be called bunqdesktop since bunq is a different organisation and this app is developed by the bunk community https://github.com/BunqCommunity

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md

> Remove from the end: strings such as “Desktop”, “for Desktop”.

**Review by nduijvelshoff — COMMENTED** [review]
Changes are accepted.

**Comment by nduijvelshoff** [comment]
@commitay when can the pull request be merged? (just curious)

**Comment by commitay** [comment]
When another maintainer reviews it. We're volunteers working on this in our free time. You only submitted it 30 minutes ago.

**Comment by nduijvelshoff** [comment]
As I mentioned, just curious, it's my first time and the current status is already a lot quicker then I imagined. Thumbs up for the afford @commitay.

**Pull request merged**
