### PR TITLE
Update vagrant from 2.2.9 to 2.2.10

### PR DESCRIPTION
**Pull request by ErikMinekus**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by ErikMinekus** [comment]
```
Run brew cask zap './Casks/vagrant.rb'
Error: uninstall script uninstall.tool does not exist.
==> Implied "brew cask uninstall vagrant"
==> Running uninstall script uninstall.tool
```
uninstall.tool most certainly does exist.

**Comment by miccal** [comment]
@reitermarkus why would this cask already be installed in the CI machines, thus triggering the `brew cask zap` check in [ci.yml](https://github.com/Homebrew/homebrew-cask/blob/master/.github/workflows/ci.yml#L198-L202)?

**Comment by miccal** [comment]
I think that the `executable: "uninstall.tool"` line in the `uninstall script:` should be `executable: "#{staged_path}/uninstall.tool"`, no?

**Comment by reitermarkus** [comment]
A bunch of casks are preinstalled on the CI machines. Not sure why `zap` is failing though for this one.

**Comment by reitermarkus** [comment]
Ah, I think it tries zapping the new version instead of the installed version.

**Pull request merged**
