### PR TITLE
Delete audacity-lame-library.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
Depends on a cask we don’t have anymore.

Must not be merged before https://github.com/caskroom/homebrew-cask/pull/28099 to not cause conflicts.

### CODE REVIEW

**Comment by miccal** [comment]
Sorry @vitorgalvao did I do something wrong when I merged https://github.com/caskroom/homebrew-cask/pull/28099 to cause this?

**Comment by vitorgalvao** [comment]
Perhaps something else escaped me. Will make a new PR.

**Comment by miccal** [comment]
Sorry!

**Comment by vitorgalvao** [comment]
No harm done. Not your fault, even. I thought merging the other PR wouldn’t cause a conflict, but it did.

**Comment by miccal** [comment]
I was worried I merged https://github.com/caskroom/homebrew-cask/pull/28099 when I should not have.

**Comment by vitorgalvao** [comment]
Nah, it was fine.

**Comment by miccal** [comment]
Phew!

**Pull request closed without merging**
