### PR TITLE
Add latest kerio-control-vpn-client.

### PR DESCRIPTION
**Pull request by sepehr**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

### CODE REVIEW

**Comment by miccal** [comment]
When you download the `dmg` there are two files, `Kerio Control VPN Client Installer.pkg` and `Kerio Control VPN Client Uninstaller.app`. The uninstall `app` contains an uninstall script at `Kerio Control VPN Client Uninstaller.app/Contents/Resources/uninstall` which seems to do a more thorough job of uninstalling this.

It might be better to add an `uninstall script:` to this Cask. See an example [here](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ezeep.rb#L11#L15).

**Comment by sepehr** [comment]
I went down that way at first. But it seems that the script only works through the UI. 

When you run that `uninstall` script, it halts with a non-zero exit status (without any output). I even tried to simulate the work of the `uninstall` script and execute those action scripts (residing in `action/`) separately which failed as well. 

So I took the `uninstall` script and simulated all its jobs using cask's uninstall stanza. The only thing that differs is that the uninstall script closes the *System Preferences* app. I didn't know how to do that in using uninstall stanza.

What do you think?

**Comment by miccal** [comment]
No problem if you had already tried and it calls a UI then no problem. The only thing I can see that the uninstall script does "extra" is removing the following files:
```
rm -rf /usr/local/kerio/vpnclient/!(dbSSL|config|logs)
rm -rf /Library/PreferencePanes/KVpnClient.prefPane
rm -rf /Library/LaunchDaemons/com.kerio.kvpncsvc.plist
rm -rf /Library/Extensions/kvnet.kext
```

**Comment by sepehr** [comment]
Yes, you are right and I saw those lines as well. But I though that's covered by [`pkgutil:   'com.kerio.control.kvpnclient.pkg'`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-key-pkgutil). Isn't that?

**Comment by miccal** [comment]
Ah yes, I believe you are correct.

**Review by miccal — APPROVED** [review]

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
