### PR TITLE
Update raw-photo-processor from 1876Beta to 4.8.0,1703

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by frihamn — COMMENTED** [review]
Can this be reverted? It is in fact a downgrade. As already discussed, the betas are release quality and the developer makes no distinction as clarified here: https://groups.google.com/forum/#!topic/raw-photo-processor/PJyyP2JwIwI

**Comment by suschizu** [comment]
oh, ok sorry for that! So 1876Beta is still the latest version?

**Comment by apropostech** [comment]
Yes, I believe 1876Beta is the latest (it was published 21 March).

**Comment by apropostech** [comment]
Another thought, is it allowed to add a comment in the cask regarding this to prevent it from being downgraded by error again in the future?

**Comment by vitorgalvao** [comment]
> Another thought, is it allowed to add a comment in the cask regarding this to prevent it from being downgraded by error again in the future?

No.

**Comment by suschizu** [comment]
thanks @vitorgalvao 👍  
@apropostech - do you know if there is a new website or appcast that we could use for this cask? This would perhaps be a good idea to prevent this cask from up/downgrading to version 4.8.0

**Comment by apropostech** [comment]
Unfortunately not. I subtly raised the issue in the [group discussion](https://groups.google.com/forum/#!topic/raw-photo-processor/PJyyP2JwIwI) linked to above and mentioned homebrew. The developer has moved away from publishing updates to both the official website and appcast (possibly due to convenience) and has been releasing through the google forum (as well as http://raw-rpp.livejournal.com/ ) since 2014.

Maybe the appcast stanza should be removed though to avoid confusion on that part since it is linking to what is now 5 year old versions.

**Pull request merged**
