### PR TITLE
Update stack from 2.4.1.70454 to 2.6.2.20200306

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Looks like we might need to replace the appcast.

**Comment by suschizu** [comment]
I can't find another appcast for this app - unfortunately 
should we delete the appcast here?

**Comment by vitorgalvao** [comment]
> should we delete the appcast here?

Unsure. Maybe we should wait until the next update, as it might be a temporary blip. I tried looking for the download page to see if it might be usable, but I’m not finding it.

**Comment by suschizu** [comment]
the download contains just -latest … here is the download site:
https://www.transip.nl/cp/stack/download/

**Comment by vitorgalvao** [comment]
Merging for now, let’s revisit the appcast thing later.

**Pull request merged**
