### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by commitay**
Add `brew config` for macOS and `java` version info.

I started a PR (https://github.com/caskroom/homebrew-cask/pull/35711) to add this a couple of months ago, it's more useful now then it was then.
___

Edit: Alternative option, add macOS and Java to `brew cask doctor`: https://github.com/Homebrew/brew/commit/1d5e1afa28517d3e8445c29b7e33c6a5570f4f6f

### CODE REVIEW

**Comment by miccal** [comment]
Lets add the output of `brew doctor` also, just for completeness and to mirror what they do in `brew cask`.

**Comment by commitay** [comment]
Alternative option, add macOS and Java to `brew cask doctor`: https://github.com/Homebrew/brew/commit/9494ee7bee6d5b8fd2aed865548ebc5bdc6ab539

**Comment by miccal** [comment]
Merging for now.

**Comment by commitay** [comment]
I would have liked a 👍  from the other maintiners on this or https://github.com/Homebrew/brew/commit/9494ee7bee6d5b8fd2aed865548ebc5bdc6ab539 first.

**Pull request merged**
