### PR TITLE
Initial commit of fish-app

### PR DESCRIPTION
**Pull request by krejac**
Initial commit of the standalone app of the fish shell version 2.1.1.

### CODE REVIEW

**Comment by alebcay** [comment]
Shouldn't the name of the Cask just be `fish`?

**Comment by krestenjacobsen** [comment]
Well, I thought that since there are different versions available for download - and this is the app version - I would name it accordingly.

**Comment by rolandwalker** [comment]
Hi!

Yes, the `generate_cask_token` script would assign the token `fish`.  But we would use the same name if we Cask [`fish.pkg`](http://fishshell.com/files/2.1.1/fish.pkg) from the same source (which we should).

So let's keep this unusual token for disambiguation.  Avoiding future renames is the most important reason for standardizing.

Thanks, @krestenjacobsen.  The contribution is much appreciated !

**Comment by rolandwalker** [comment]
On second thought, I have a small tweak in #9731.

**Pull request merged**
