### PR TITLE
Add RemoteViewer

### PR DESCRIPTION
**Pull request by rimenes**
A OS X client for the spice protocol

### CODE REVIEW

**Comment by adityadalal924** [comment]
Please use a versioned url, i.e. `url "http://people.freedesktop.org/~teuf/spice-gtk-osx/dmg/#{version}/RemoteViewer-#{version}-1.dmg"`

Also needs a comment about that download url being official

**Comment by vitorgalvao** [comment]
[The comment in question must follow this form](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#when-url-and-homepage-hostnames-differ-add-a-comment).

**Comment by rimenes** [comment]
Thanks. I've made contributions in the past but a lot of things have changed since then.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 9576cebf065f651828e31f817038e2f0961c9d49. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by adityadalal924** [comment]
@vitorgalvao I think the fixes you made actually broke the cask - there's no folder with `0.5.7-1`in the download url, it has to be just the version part before the `-` (the actual dmg name is still correct, though)

**Comment by vitorgalvao** [comment]
@adityadalal924 You’re right, hadn’t noticed `#{version}` was used twice. Will correct shortly.

**Pull request closed without merging**
