### PR TITLE
pushplaylabs-sidekick 122.59.1

### PR DESCRIPTION
**Pull request by adithyasunil26**
After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@adithyasunil26 Can we also update `intel` to the latest version, the livecheck is really sporadic for this cask. But we should use the latest versions that are being returned for both.

**Comment by adithyasunil26** [comment]
@bevanjkay Updated the `intel` version as well. This should work.

**Comment by bevanjkay** [comment]
If we're lucky enough to get a CI run that includes both latest versions 😄

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
