### PR TITLE
Adding synergy.rb

### PR DESCRIPTION
**Pull request by JacopKane**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Not comfortable at all with including this, as we have absolutely no guarantee these binaries weren’t tampered with.

This person is also trampling the business model of open source developers — a model they instituted to be able to continue developing software *while* asking for donations for this. So they’re actually saying “don’t pay them for their work, give me money instead for capitalising on it”. I’d feel really uncomfortable supporting that as well.

Either way, these binaries are definitely not official and do not belong in this repo. At the most they belong in [caskroom/unofficial](https://github.com/caskroom/homebrew-unofficial). I say it should not be added even there, but pinging @caskroom/maintainers for some opinions.

Either way, thank you for the submission, @JacopKane. It is a well done one.

**Comment by rolandwalker** [comment]
Hi @JacopKane !

Thanks for the Cask.  There is actually nothing wrong, and everything right, about redistributing or forking GPL'd software.  It is explicitly allowed by the license.  You can even charge a fee for redistributing, if you could convince people to pay it!

Adopting the GPL means foreclosing certain business models in the future.  That is a commitment made by the Synergy project at the time that they adopted the GPL.

However, it is also a core requirement of the GPL that distributors of a binary must distribute the source to produce the given binary.  Having looked at this site, they are not doing that, so they are in violation.  We can't in good conscience include a Cask that we know is violating the license.  

synergykm.com should fork the source of the Synergy project and host it.  If they do so we'd be happy to include their fork in the main repo.

**Comment by jzelinskie** [comment]
@rolandwalker Correct me if I wrong, but it appears they have the source code available at http://synergykm.com/binaries/ along with all of the other platforms' binaries.

**Comment by agnoster** [comment]
Yeah, what's wrong with the tarball? Do they actually need to distribute the source *in* the binary package, or just from the same page?

Anyway in the meantime I made a tap in case anyone is in a similar situation and just wants to install synergy with minimal fuss: https://github.com/agnoster/homebrew-synergykm

**Comment by vitorgalvao** [comment]
@agnoster Well, since they do seem to be complying, you can submit those to the main project if you so wish. Best on [caskroom/unofficial](https://github.com/caskroom/homebrew-unofficial).

**Pull request closed without merging**
