### PR TITLE
Add ActivityWatch v0.8.0b8

### PR DESCRIPTION
**Pull request by freayd**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Welcome.

This seems to be a CLI-only open-source tool. Please submit it first to [Homebrew/core](https://github.com/homebrew/homebrew-core) as a formula. Return here if not accepted (linking back to the pull request where it was refused).

This policy is documented in [faq/rejected_casks](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core) as a formula that builds from source. If it is rejected, you may then try again as a cask (link us to the issue so we can see the discussion and reasoning for rejection).

**Comment by freayd** [comment]
Hi @vitorgalvao .

ActivityWatch is an application managed via a local web interface. It requires the start of the program named `aw-qt`, which is small tool developed in Qt that inserts a menu in the system tray. This menu helps to manage the background server and open the web interface. Yes, `aw-qt` is launched via a terminal (they haven't developed a nice .app yet), but since it is mostly revolving around the system tray and a web interface, I understand that [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask) is the appropriate place.  ActivityWatch isn't CLI-only.

Thanks for your time and help.

**Comment by vitorgalvao** [comment]
I’d say that still qualifies it as a CLI-only app, because what matters is what we install (and what you invoke). What do you think @MikeMcQuaid? We haven’t explicitly laid out that rule, but are there formulae in `Homebrew/brew-core` that while installed as CLI tools, are interacted with via a web interface?

**Comment by MikeMcQuaid** [comment]
If it's a Qt application primarily with a web interface and tray tool I think Cask is a reasonable place for it (particularly if upstream provide official binaries).

**Comment by freayd** [comment]
[Their documentation states](https://activitywatch.readthedocs.io/en/latest/getting-started.html): 

> We’re currently working on improving the installation experience by creating proper installers and packages, but for now we offer standalone archives containing everything you need.

They have been tracking the need of a .app. See ActivityWatch/activitywatch#10

**Pull request merged**
