### PR TITLE
update to maltego chlorine

### PR DESCRIPTION
**Pull request by sroberts**
The fine folks at Paterva decided to :trollface: me a little bit and release a new point version of Maltego a week after submitting a PR for v3.5. I made a couple tweaks based on their usual naming scheme, but it tested well for me. 

Thanks for giving it a look! :sparkles:

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Should be renamed to `maltego-chlorine.rb`, not `maltego`.

**Comment by sroberts** [comment]
@vitorgalvao That's going to lead to a cask name change every single point release. That doesn't seem terribly useful to me and could lead to confusion.

Is there some reason I'm missing?

**Comment by vitorgalvao** [comment]
Ah, that would indeed be annoying. Seems like an acceptable candidate for `:target` as well (`app "Maltego Chlorine v#{version.sub(%r{\.\d+$},'')}.app", :target => 'Maltego.app'`), perhaps, but definitely an acceptable exception to the token rules. Notifying @rolandwalker @ndr-qef @phinze.

**Comment by ndr-qef** [comment]
“Chlorine”, “Carbon”, etc. appear to be codenames in their versioning scheme. I agree with @sroberts' recommendation; in fact, I would also prune `name`.

**Comment by rolandwalker** [comment]
Agreed, we don't want the token to cycle with every release.  That looks like my error in #9814 (I merely verified that the string "Carbon" was present across platforms).

As for changing the `:target` value, as usual, I oppose actually using the feature which I implemented.

**Comment by sroberts** [comment]
I don't think renaming the app with ```:target``` will make a big difference. They do have an alternative product called Maltego Casefile and some people do have to run both. 

:shipit:?

**Comment by vitorgalvao** [comment]
Seems like we have consensus. @sroberts Could you just change `name`, then, please?

**Comment by sroberts** [comment]
@vitorgalvao Name changed!

**Comment by vitorgalvao** [comment]
Everything looks fine. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by ndr-qef** [comment]
Thanks, merged as a16c281.

**Comment by sroberts** [comment]
Ahh awesome! I was still trying to figure out how to squash commits. Not used to doing that.

**Pull request closed without merging**
