### PR TITLE
Simplify "Titanium Software" casks (deeper, maintenance, onyx).

### PR DESCRIPTION
**Pull request by reitermarkus**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This is smart, but likely to break. You removed the special case, which means it’ll try to download a possibly (haven’t checked yet) non-existing download for Sierra. The `else` case should remain separate.

**Comment by reitermarkus** [comment]
It doesn't break, as `:sierra` isn't in the `depends_on` array.

**Comment by vitorgalvao** [comment]
Good point. Even so, even with it not breaking, I’d prefer to have the comment there. If anything, it keeps us alert to the fact that the cask needs to have the new URL checked and the `depends_on` altered.

**Comment by reitermarkus** [comment]
Ok, I re-added the comment above the `depends_on` stanza.

**Pull request merged**
