### PR TITLE
x2goclient: add desc

### PR DESCRIPTION
**Pull request by neutric**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by neutric** [comment]
Is there a way to tell livecheck to extract parts of the version string taken from the cask description? The current version `4.1.2.2` can be scraped off of the homepage easily, but the date that is part of the download URL and thus part of `version` (4.1.2.2,20200213 ) is a problem.

**Comment by neutric** [comment]
`:extract_plist` is also failing locally with `Error: x2goclient: Unable to get versions`

**Comment by miccal** [comment]
@neutric happy with this?

**Comment by neutric** [comment]
@miccal Thanks for your help! I prefer versioned URLs, or rather the checksumming that comes with them, but this will have to do I suppose.

**Comment by miccal** [comment]
> @miccal Thanks for your help! I prefer versioned URLs, or rather the checksumming that comes with them, but this will have to do I suppose.

I do too, but the problem was coming up with a `livecheck` that would work for the versioned `url`'s and I noticed from https://code.x2go.org/releases/ that the folder for `binary-macosx/` was not updated in a regular manner, so I think it is better to stick with the `X2GoClient_latest_macosx_10_*.dmg` links.

**Comment by neutric** [comment]
Totally understand! I tried using `binary-macosx/x2goclient/releases/`, which at least for the current version was updated at the same time the file for `latest` was, but then got stuck missing the date that is part of the versioned URL.

**Pull request merged**
