### PR TITLE
Update liteide from 36.2 to 36.3

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@suschizu Can you check if the URL works for you? It works for me.

**Comment by suschizu** [comment]
Works too for me

**Comment by vitorgalvao** [comment]
Homepage isn’t accessible for me.
image

**Comment by ran-dall** [comment]
> Homepage isn’t accessible for me.

Haven't we seen this type of behavior before?

**Comment by core-code** [comment]
i regularly get blocked by some caching/cdn servers when downloading all casks. but i think this is something different. i get the very same thing when trying to access the homepage domain.

**Comment by core-code** [comment]
lets just enter the github project page as the homepage, no?

**Comment by suschizu** [comment]
@ran-dall & @vitorgalvao  - sorry - I was testing if the URL download works - the homepage also shows the error message

**Comment by ran-dall** [comment]
> i regularly get blocked by some caching/cdn servers when downloading all casks.

Well, this is a Fastly error.

**Comment by ran-dall** [comment]
> lets just enter the github project page as the homepage, no?

Seems reasonable...

**Pull request merged**
