### PR TITLE
Update markdownmdimporter

### PR DESCRIPTION
**Pull request by vladimyr**
Use `mdimporter` stanza.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Comment by reitermarkus** [comment]
I shouldn't have merged the other ones since this isn't in a stable release yet.

**Comment by vladimyr** [comment]
> I shouldn't have merged the other ones since this isn't in a stable release yet.

Waiting for new brew's github release?

**Comment by catesandrew** [comment]
i keep getting the following error since updating, any idea how to fix?

```
Error: Cask 'markdownmdimporter' definition is invalid: invalid 'mdimporter' stanza: key not found: :mdimporterdir
```

**Comment by reitermarkus** [comment]
@catesandrew, please open a new issue with all details. Thanks!

**Comment by catesandrew** [comment]
i ended up manually removing the `markdownmdimporter/` from `Caskroom`. thanks

**Pull request merged**
