### PR TITLE
Update macupdater from 1.5.9,8735 to 2.0.0,10776

### PR DESCRIPTION
**Pull request by JeffreyBytes**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by zsoltion** [comment]
2.0 requires a separate license, should this really be a direct update?

**Comment by spaz926** [comment]
I wasn't aware this was a deciding factor for direct updates.

**Comment by reitermarkus** [comment]
> 2.0 requires a separate license

That's irrelevant, the cask should always point to the latest version. If there is a need to keep another version, it can be submitted to the `homebrew/cask-versions` tap.

**Comment by vitorgalvao** [comment]
> I wasn't aware this was a deciding factor for direct updates.

It isn’t.

**Review by vitorgalvao — DISMISSED** [review]

**Comment by spaz926** [comment]
Looks like with the release of version 2.0.0 they also changed their Sparkle appcast url. Could this be the reason the checks were failing?
Has been updated https://github.com/Homebrew/homebrew-cask/pull/97239/commits/d4e574ceaa9f3a0ca598fcde2b029db39db415c6

**Review by vitorgalvao — DISMISSED** [review]

**Comment by miccal** [comment]
Thank you @spaz926.

**Review by miccal — APPROVED** [review]

**Pull request merged**
