### PR TITLE
Update shimo from 5.0.2_8880 to 5.0.3_8887

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
their homepage seems offline. no idea how to proceed. @miccal any ideas?

**Comment by miccal** [comment]
> their homepage seems offline. no idea how to proceed. @miccal any ideas?

I have been keeping an eye on it, but I cannot find an alternative:
```
|-> curl -sLI https://www.shimovpn.com/
HTTP/1.1 500 Internal Server Error
Date: Fri, 20 Nov 2020 15:56:59 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive
Server: Apache
```

**Comment by ran-dall** [comment]
@core-code @miccal FWIW it was working for me yesterday but this morning it's offline for me too.

**Pull request merged**
