### PR TITLE
Update reaper from 5.98.0 to 5.98.1

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
can you adjust this to match the actual version number in the app? thanks!


`  version '5.98.100'
`
` url "https://www.reaper.fm/files/#{version.major}.x/reaper#{version.no_dots.sub(%r{0*$}, '')}_x86_64.dmg"
`  

`configuration: "#{version.major}.#{version.minor}#{version.patch.sub(%r{0*$}, '')}"`

**Comment by core-code** [comment]
too late, i'll just send a PR

**Comment by core-code** [comment]
@reitermarkus is there a way to prevent @BrewTestBot from auto-merging something?

**Comment by ran-dall** [comment]
@core-code I'll make note of this to prevent this from happening on the ML updates.

**Comment by core-code** [comment]
thanks, though i think the next updates should be fine since they follow the same format - until 5.99. its only changing to or from the dotzero release that makes things difficult. i've not yet found a better way to deal with their damaged version numbers ;/

**Comment by reitermarkus** [comment]
> @reitermarkus is there a way to prevent @BrewTestBot from auto-merging something?

Not right now.

**Comment by core-code** [comment]
@reitermarkus  ok thanks for the info

**Pull request merged**
