### PR TITLE
Shell Completions and manpage for alacritty

### PR DESCRIPTION
**Pull request by hybras**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:
- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

`Alacritty.app` bundles shell completions and a *gzipped* man page. 
- I symlinked the completions based on the `docker` cask.
  - Do casks not have access to `$SHELL_completion.install`? I tried and it didn't work
- How do I unzip the manpage? I know to install it with the `manpage` stanza.

### CODE REVIEW

**Comment by miccal** [comment]
>   * Do casks not have access to `$SHELL_completion.install`? I tried and it didn't work

No, unfortunalety.

> * How do I unzip the manpage? I know to install it with the `manpage` stanza.

The `manpage` stanza will automatically do that.

**Comment by miccal** [comment]
@hybras can you please confirm locally that this all works as intended?

**Comment by hybras** [comment]
Verified zsh completion and man page. I don't know how to set up completion for bash, fish.

**Comment by miccal** [comment]
Thank you @hybras.

**Pull request merged**
