### PR TITLE
pharo: Update sha256 for 2015-03-11

### PR DESCRIPTION
**Pull request by johnnyt**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
It should be changed [in this manner](https://github.com/caskroom/homebrew-cask/blob/8d12a467780d79e768a5220ea297797f825df29f/Casks/vivaldi.rb#L3) instead.

**Comment by johnnyt** [comment]
Awesome - thanks for that!

It's updated now to use the suggested `:no_check`

**Comment by alebcay** [comment]
Thanks! One last thing - could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by johnnyt** [comment]
You betcha - done!

**Comment by vitorgalvao** [comment]
Thank you.

**Pull request merged**
