### PR TITLE
Add ElasticWolf 5.1.7

### PR DESCRIPTION
**Pull request by miketheman**
Signed-off-by: Mike Fiedler <miketheman@gmail.com>

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by miketheman** [comment]
I suspect this PR, and many others are kind of stuck in CI? I know [Travis had an incident](https://www.traviscistatus.com/incidents/mc9x2wmpnvhg) that affected OSX builds, so should these in-flight ones be canceled/restarted?

**Comment by commitay** [comment]
All of the "stuck" PRs have been dealt with, it's just the backlog is a couple of thousand builds so it will take a while.

**Comment by commitay** [comment]
> fatal: Invalid symmetric difference expression ab47cfa1b73ac3c304bc6a6a5399edda965b7f81...4ded8a43c28e4f55b94a5311d45772f1c66987cc

@miketheman Can you rebase this on master please?

**Comment by miketheman** [comment]
@commitay Rebased, let's see how CI does this time.

**Comment by commitay** [comment]
Thanks!

**Review by commitay — APPROVED** [review]

**Pull request merged**
