### PR TITLE
a-better-finder-attributes: move to a/a-better-finder-attributes

### PR DESCRIPTION
**Pull request by cho-m**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

Experimenting with moving single cask to shard.

I think it will fail style assuming CI runs:
```console
❯ brew style a-better-finder-attributes
a/a-better-finder-attributes.rb:1:1: C: [Correctable] Missing frozen string literal comment.
cask "a-better-finder-attributes" do
^

1 file inspected, 1 offense detected, 1 offense autocorrectable
```

### CODE REVIEW

**Comment by p-linnane** [comment]
@cho-m Do we still need this open?

**Comment by cho-m** [comment]
We should start sharding the repo.

Some things that may need to be done:
- [ ] Agree on sharding approach, e.g. the `a/` - `z/` directories? leave `[0-9].*` casks alone? etc.
- [ ] I mentioned on Slack some URLs that won't work for any Cask we migrate. Not sure if we want to handle before or just leave them broken (assuming low impact), e.g.
  - https://github.com/Homebrew/brew/blob/master/Library/Homebrew/api.rb#L123 (we could still migrate with this broken as I think it will take the fallback using formulae.brew.sh)
    ```rb
          raw_endpoint = "#{git_head}/Casks/#{name}.rb"
    ```
  - https://github.com/Homebrew/formulae.brew.sh/blob/master/_layouts/cask.html#L23 (I think this is only used for website)
    ```html
    <p><a target="_blank" href="{{ site.taps.cask.remote }}/blob/{{ c.tap_git_head }}/Casks/{{ token }}.rb">Cask code</a> on GitHub</p>
    ```
- [ ] Commit a small number of Cask migrations to test everything is working.
- [ ] Potential mass migration or migrate in phases
- [ ] Add some checks for new Casks.

**Review by carlocab — APPROVED** [review]
Just testing something. Feel free to ignore.

**Comment by razvanazamfirei** [comment]
@reitermarkus, approach 2 makes a lot of sense to me. Last I checked, we would end up with ~500 directories. 

I've been playing around with md5 hashing the file name and taking a modulo of the hash to control the number of directories. If we use it to assign cask to directories, the distribution of casks/shard is reasonable. It would be decently easy to implement and audit, but very user-unfriendly.

**Pull request closed without merging**
