### PR TITLE
iterm2-ai-plugin 1.1 (new cask)

### PR DESCRIPTION
**Pull request by HuaDeity**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by miccal** [comment]
@p-linnane can you have a look at this please, baed on what you said in https://github.com/Homebrew/homebrew-cask/pull/176472#issue-2347612521.

Thanks.

**Comment by HuaDeity** [comment]
> @p-linnane can you have a look at this please, based on what you said in [#176472 (comment)](https://github.com/Homebrew/homebrew-cask/pull/176472#issue-2347612521).
> 
> Thanks.

But in fact, the buttons in the settings will jump to the web page and need to be manually downloaded and moved to the Application folder.

**Comment by bevanjkay** [comment]
I'm okay with including this, we should probably add `depends_on cask: "iterm2"`, as it doesn't do anything on its own.

**Comment by krehel** [comment]
> I'm okay with including this, we should probably add `depends_on cask: "iterm2"`, as it doesn't do anything on its own.

I left this out as it would mean this cask couldn't be used on `iterm2@beta` or `iterm2@nightly`.

**Review by bevanjkay — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Comment by miccal** [comment]
So, do we just not care about the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference) any longer?

**Comment by krehel** [comment]
Yeah, fair point @miccal.  Let's change it to be appropriate.

**Comment by p-linnane** [comment]
> Can we rename this without needing to add it to the renames json?

Since we just merged it, yes.

**Pull request merged**
