### PR TITLE
add Background Music, snapshot version

### PR DESCRIPTION
**Pull request by kud**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by kud** [comment]
Hello 👋🏻

I must admit, it's not the stable version but this is the point of this formula. The evolution of the stable version is a bit slow, and I need some new features from the snapshot version, that's why I created this PR. :)

**Comment by vitorgalvao** [comment]
Non-stable versions belong in [caskroom/versions](https://github.com/Homebrew/homebrew-cask-versions).

But [we won’t accept it there as well](https://github.com/Homebrew/homebrew-cask-versions#acceptable-casks):

> homebrew/cask-versions is not intended to be used for all and any old versions you personally require for xyz project; casks submitted here should be expected to be used by a reasonable number of people and supported by contributors long-term.

If you need this, consider hosting your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) for it.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/background-music-pre.rb

**Comment by kud** [comment]
I didn't understand your previous messages in my mailbox, but alright :D thank you for this cask!

**Comment by vitorgalvao** [comment]
@kud The cask is being kept up to date by a maintainer, so the comment doesn’t apply (because it is being maintained by someone that will likely keep doing it).

**Comment by kud** [comment]
Oh alright, thank you. :)

**Pull request closed without merging**
