### PR TITLE
add hp-prime version 2018_10_16

### PR DESCRIPTION
**Pull request by mircomacrelli**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
[Same question](https://github.com/Homebrew/homebrew-cask/pull/60804#issuecomment-475956382).

**Comment by mircomacrelli** [comment]
This is an emulator that can be used to test programs written with the connectivity kit without loading them on the calculator.

**Comment by vitorgalvao** [comment]
Would you ever want this if you don’t have the physical calculator?

**Comment by mircomacrelli** [comment]
It is a nice calculator. Better than the one in macos. I wold use it even if I didn't own the device.

**Comment by vitorgalvao** [comment]
To clarify, I’m not asking about you specifically. I want to know if the software is useful without the physical calculator. Because if it is not, it belongs [in another repo](https://github.com/Homebrew/homebrew-cask-drivers). That is why I’m making the same questions in both PRs, in case one is and the other isn’t.

**Comment by mircomacrelli** [comment]
Now I understand. I think this cask with the emulator could be useful even without the physical calculator. The connectivity kit, on the other hand, I think only make sense when you own the device.

**Pull request merged**
