### PR TITLE
Remove iphone-backup-extractor

### PR DESCRIPTION
**Pull request by gtmgianni**
Website has been unresponsive for at least a week.

### CODE REVIEW

**Comment by thegranddesign** [comment]
This seems like a silly reason to remove this.  There are people who've paid for this and have a license.

Regardless, the site is up.  Please revert this.

https://www.iphonebackupextractor.com/

**Comment by commitay** [comment]
@thegranddesign 
It was removed because http://supercrazyawesome.com/ is down (and it's still down) and the url
http://supercrazyawesome.com/downloads/iPhone%20Backup%20Extractor.app.zip wasn't working (and it still doesn't work)

Where did https://www.iphonebackupextractor.com/ come from?

**Comment by vitorgalvao** [comment]
> There are people who've paid for this and have a license.

There’s some confusion here. No one paid for access to this cask. Neither have they paid us for access to the software. We have no affiliation with any app and are under no obligation to provide any specific support to anything.

We’re a volunteer-run project, and our removal of a cask in no way impacts your way to get it by official means.

If a piece of software is inaccessible, that’s not a “silly reason” to remove it, but the best one there is.

**Comment by thegranddesign** [comment]
@vitorgalvao I didn’t mean paid for the cask. Obviously. I meant paid for the software. For iPhone backup extractor. I realize that you all can’t keep dead software around forever.

I misunderstood and thought you’d removed it due to the homepage being down and not due to download link so longer working which is perfectly valid. I would say that it’d probably behoove maintainers to do a quick google search before doing so though. 

@commitay supercrazyawesome.com is not the website for this software. iphonebackupextractor.com is. 

I’ll get you all the correct link in a few minutes.

**Comment by gtmgianni** [comment]
@thegranddesign A "quick Google search" showed several different applications being advertised as "iPhone Backup Extractor", including the one you are referencing.

screen shot 2018-05-10 at 20 27 12

The name of the software is clearly not unique, and the application you are referring to (the one from https://www.iphonebackupextractor.com/) does not appear to be related in any way to the application this cask was built for. If you look at the Internet Archive Wayback Machine's [most recent snapshot](http://web.archive.org/web/20171104050047/http://supercrazyawesome.com/) of the now inaccessible homepage for this cask, you will see that the iPhone Backup Extractor you are talking about, and the one this cask was originally made for, are applications built by two _different_ developers.

Using the Wayback Machine, I was also able to download a copy of the application, and compared it to the application you are referencing:

**Application this cask is built for**
screen shot 2018-05-10 at 20 37 16

**Application you are referencing**
screen shot 2018-05-10 at 20 37 02

As you can see, the apps are _completely different_ to one another, and are made by different developers. Hence, the removal of this cask was perfectly warranted, as neither the cask's homepage URL nor the download URL are available, as @commitay and @vitorgalvao have stated.

I believe this is where the confusion stems from – you happen to be using one of the several other "iPhone Backup Extractor" applications on the Internet, and have mistook this particular cask for something it is not.

You can submit a pull request to create a new cask for the application you are referencing (see the [instructions for contributing](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)), but reverting my commit is not the way to go, as that will simply bring back a cask that points to a non-existent URL.

**Comment by thegranddesign** [comment]
@gtmgianni I grant you that it's a different piece of software, but "a quick Google search" revealed it was literally the first hit.  Both the first ad-based hit and the first non-ad-based hit.

I'll submit a PR.

**Pull request merged**
