### PR TITLE
Add depends on catalina to macvim.rb

### PR DESCRIPTION
**Pull request by suschizu**
min version is 10.15

### CODE REVIEW

**Comment by core-code** [comment]
=>
`  depends_on macos: '>= :catalina'
`

**Comment by ariananggada** [comment]
i think its run perfectly in mojave

**Comment by core-code** [comment]
@ariananggada how can you launch the macvim 8.2 release on mojave? since the 10.15 requirement is embedded into the app it should refuse to launch on any earlier system

**Comment by suschizu** [comment]
> i think its run perfectly in mojave

you are right - sorry this was my mistake  -> https://github.com/Homebrew/homebrew-cask/pull/79592

**Pull request merged**
