### PR TITLE
Update sqlitestudio to 3.2.0

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
```
Error: It seems the App source '/usr/local/Caskroom/sqlitestudio/3.2.0/InstallSQLiteStudio-3.2.0' is not there.
Error: Kernel.exit
```

It's coming from a DMG, and I know HBC does some interesting things to get inside the DMG. Is it possible to replicate how HBC extracts them? Maybe a script in `developer/bin/`?

**Review by commitay — CHANGES_REQUESTED** [review]
Please change this to use https://sqlitestudio.pl/files/sqlitestudio3/complete/macosx/SQLiteStudio-3.2.0.dmg rather than the installer.

**Comment by brianmorton** [comment]
3.2.1 is out now so I'll sub a PR for that when my script gets around to it in a bit :)

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/pull/50178

**Pull request closed without merging**
