### PR TITLE
Update plex-media-server to 1.1.3.2700-6f64a8d

### PR DESCRIPTION
**Pull request by derekedmond**
Update plex-media-server to 1.1.3.2700-6f64a8d

### CODE REVIEW

**Comment by adidalal** [comment]
Also, check out `cask-repair`, it makes Cask updates like this quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

**Comment by derekedmond** [comment]
@adidalal Hi, I just tried a cask-repair. At first it didn't work. In plex-media-server.rb I needed to change  ${version.chop.chop} to ${version}. I managed to edit that and run cask-repair, but I got this error on submitting.  What am I doing wrong?

```
Submitting…
Username for 'https://github.com': derekedmond
Password for 'https://derekedmond@github.com':
To https://github.com/derekedmond/homebrew-cask
 ! [remote rejected] cask-repair_update-plex-media-server -> cask-repair_update-plex-media-server (shallow update not allowed)
error: failed to push some refs to 'https://github.com/derekedmond/homebrew-cask'
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"

There was an error submitting the pull request. Please open a bug report on the repo for this script.

```

**Comment by adidalal** [comment]
@vitorgalvao Want to take a look?

**Comment by vitorgalvao** [comment]
@derekedmond Go into the repo and `git fetch --unshallow`. A better solution is in the works.

**Pull request merged**
