### PR TITLE
Update wiznote from 2.7.8,2019-10-17 to 2.7.9,2019-10-21

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@core-code I think the ML is making a jump with the `version`, cause I can't find it anywhere. `2.7.9` part, the `2019-10-21` part is ok.

**Comment by core-code** [comment]
it seems to contain version 2.7.9 (3407) so it looks ok, can't see a problem

**Comment by ran-dall** [comment]
> it seems to contain version 2.7.9 (3407) so it looks ok, can't see a problem

@core-code The problem is that I think the ML is guessing on these version numbers. It really doesn't have a reason to assume `2.7.9` is `latest`. Which means that eventually this could be a problem. I was just letting you know, because maybe you could find a different `appcast` or change the `appcast` configuration.

**Comment by core-code** [comment]
ah thanks. guessing is indeed bad ;)

we could use 'https://www.wiz.cn/wiznote-mac.html' in this case. it does contain the real version number (before the comma). on the other hand, it doesn't contain the filename (after comma). i don't see a real solution here ;(

**Comment by ran-dall** [comment]
> i don't see a real solution here ;(

Agreed, let just leave it the way it is.

**Pull request merged**
