### PR TITLE
Fix Sage URL

### PR DESCRIPTION
**Pull request by junwei-wang**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Duplicate of https://github.com/Homebrew/homebrew-cask/pull/107285 and https://github.com/Homebrew/homebrew-cask/pull/107642.

**Comment by junwei-wang** [comment]
Why wouldn't you just merge it for this moment?
People could not install Sage via brew for this moment and there is a simple fix.

**Comment by junwei-wang** [comment]
This pull request does not conflict with #107642, which aim to updating the version of Sage.
This pull request simply make it possible to install Sage via homebrew.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/107285 is now merged, so this problem is fixed for now.

**Pull request closed without merging**
