### PR TITLE
Add FAW Circle v2.0.1

### PR DESCRIPTION
**Pull request by danielbayley**
Future Audio Workshop Circle synthesizer.

Signed-off-by: Daniel Bayley daniel.bayley@me.com

### CODE REVIEW

**Comment by vitorgalvao** [comment]
What are you trying to do in lines 12–16?

**Comment by danielbayley** [comment]
Well `uninstall :pkgutil => 'com.futureaudioworkshop.pkg.*'` works but it asks for sudo permission several times (because the `pkg` installs stuff to `/Library` rather than `~/Library). I'm trying to piece together how to do this properly from looking at other casks. What's the proper way to do it?

**Comment by vitorgalvao** [comment]
If it asks for permission multiple times, it’s due to your setup. We have no control over `sudo`, hence this is something on your side. Just tested it, and it worked fine. Please remove the lines.

Look into your `sudo` timeout time. You may have it set too low.

**Comment by danielbayley** [comment]
It was something in my `bashrc`, cheers.

Still not sure what to do for #11614 though.

**Comment by vitorgalvao** [comment]
Please [squash your commits](http://davidwalsh.name/squash-commits-git).

**Comment by vitorgalvao** [comment]
No need to close if you have difficulty squashing. I can help you do it, or do it for you. It is an obtuse process that trips up many newcomers.

**Comment by vitorgalvao** [comment]
See #11621.

**Comment by danielbayley** [comment]
Yeah it seemed to have gone a bit tits-up on my local branch (using Tower mostly) so I immediately thought "screw it, i'll just start again". Thanks.

**Pull request closed without merging**
