### PR TITLE
Update gifox from 010601.03 to 2.0.0,020000.07

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
```
 - appcast at URL 'https://api.gifox.io/appcast?prereleases=false' does not contain the version number: '2.0.0'
```

not sure whats going on here, the message doesn't seem to be true

**Comment by core-code** [comment]
not happy about changing to the feed URL that also contains beta versions, but the real one didn't work inside travis

**Comment by reitermarkus** [comment]
Maybe we should output the appcast contents on CI if it fails so we can actually see what's the problem.

**Comment by core-code** [comment]
i did modify my local copy to do just that. it seems it downloads an empty feed (balid sparkle cml but zero entries). i guess it must be an user-agent check. off the top of my head i am unsure though why it uses a different user agent than curl on the cli.

**Comment by core-code** [comment]
i am sorry but can would it be possible merge this first and investigate how to get a perfect appcast later?

**Comment by core-code** [comment]
thanks, i've opened https://github.com/Homebrew/homebrew-cask/pull/73155 to try to add the real appcast

**Pull request merged**
