### PR TITLE
iText RUPS 7.2.5 (new cask)

### PR DESCRIPTION
**Pull request by cmangla**
iText RUPS -- A GUI for viewing structural contents of a PDF file.

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.
- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

This is a java GUI application to examine PDFs. Audit succeeds with command `brew audit --cask --new --no-signing itext-rups`, but with signing checked, I get a failure regarding the wrapper script I generate in the cask:

```
audit for itext-rups: failed
 - Signature verification failed:
/private/tmp/cask-audit20241201-98220-pro4ld/itext-rups.wrapper.sh: No such file or directory

macOS on ARM requires software to be signed.
Please contact the upstream developer to let them know they should sign and notarize their software.
itext-rups
  * line 5, col 2: Signature verification failed:
    /private/tmp/cask-audit20241201-98220-pro4ld/itext-rups.wrapper.sh: No such file or directory
    
    macOS on ARM requires software to be signed.
    Please contact the upstream developer to let them know they should sign and notarize their software.
Error: 1 problem in 1 cask detected.
```

I could do with suggestions on how to fix this.

### CODE REVIEW

**Comment by p-linnane** [comment]
Thank you for your submission @cmangla. We are unable to accept it at this time because it does not pass Homebrew's signature verification check:

>macOS on ARM requires applications to be signed. Please contact the upstream developer to let them know they should sign their app.

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if the developers sign their app in the future we would be happy to consider adding this to `homebrew-cask`.

**Comment by cmangla** [comment]
> if the developers sign their app

Actually, it is not the app that is failing signature verification. It is the wrapper script contained within cask itself. I can see other casks are doing this too, so I don't understand why it fails for this one.

**Comment by p-linnane** [comment]
They may have been added prior to this check being implemented.

**Comment by cmangla** [comment]
> They may have been added prior to this check being implemented.

Could you point me to an example java application cask that I could copy? This is a java app, distributed as a `.jar` file, and it needs to be launched as `java -jar "#{jar_path}" "$@"`. Thanks.

**Pull request closed without merging**
