### PR TITLE
podman-desktop: add uninstall

### LINKED ISSUE #2404: brew uninstall podman-desktop leaves `~/Library/LaunchAgents/io.podman_desktop.PodmanDesktop.plist`
### Bug description

trying to reset my machine to do some more testing and noticed `~/Library/LaunchAgents/io.podman_desktop.PodmanDesktop.plist` is still on my machine after having run `brew uninstall podman-desktop`

shouldn't that clean it up?

### Operating system

macos silicon

### Version

0.14.1

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benoitf**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

fixes https://github.com/containers/podman-desktop/issues/2404

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Hi @benoitf, 

We would normally include this in our zap stanza, which is not run by default. That being said, there's nothing wrong with including it in the uninstall.

I've added some additional files to the zap stanza; they will not be removed by default, but if a user wants to get rid of all podman-related files they're included (I know there's likely some overlap with the podman formula.

**Comment by benoitf** [comment]
hi @razvanazamfirei 

```
    "~/.config/containers/podman",
    "~/.local/share/containers/podman",
```

should go the podman formula no ?

**Comment by benoitf** [comment]
and the same for
```
"~/.ssh/podman-machine-default*",
```

as podman machine can work without Podman Desktop

**Comment by benoitf** [comment]
@razvanazamfirei I've removed the podman cleanup as podman should work after Podman Desktop is deleted so Podman Desktop should not remove files of Podman.

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
