### PR TITLE
Update superduper to 3.2.4,118.e

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
can we revert this? the official download from their homepage does not have the ".e" suffix

**Comment by ran-dall** [comment]
@core-code I didn't see that, cause our output had `.e` . 👀. Doesn't matter to me. **I can submit a new PR if you want.**

**Comment by core-code** [comment]
sorry i thought i erased that entry - must have been a false positive as that build does not officially exist. 

nevermind, already sent one ;)

**Comment by ran-dall** [comment]
> nevermind, already sent one ;)

@core-code Ok. Cool. 👌

**Pull request merged**
