### PR TITLE
Update macs-fan-control from 1.5.8.23 to 1.5.8.1

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by suschizu** [comment]
This isn't a downgrade - the developer changed the version notation - short version string is 1.5.8.1 and bundle version 26

**Comment by core-code** [comment]
we should probably ping the developer about the confused version numbers here. ping cc @kleuter

**Review by core-code — APPROVED** [review]

**Comment by kleuter** [comment]
> This isn't a downgrade - the developer changed the version notation - short version string is 1.5.8.1 and bundle version 26

Exactly. The last number was always meant as build number and shouldn't have been considered as a part of the version.
It was put to **CFBundleShortVersionString** by mistake, but it will be in **CFBundleVersion** from now on.
Basically the app updated from 1.5.8 to 1.5.8.1 (quick fix version)

**Comment by kleuter** [comment]
https://user-images.githubusercontent.com/8030134/95072018-26c86980-073d-11eb-977a-e05f629264ad.png

**Comment by core-code** [comment]
thanks there, looking forward to this being consistent from now on.

**Pull request merged**
