### PR TITLE
Update wechat to 2.3.31.19

### PR DESCRIPTION
**Pull request by TomorrowWu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@TomorrowWu Travis is reporting the `sha` to be `51bd35f9621cff431934003ba91aa4eaa03768962c90f1888ece54122b8947c3` which is the the `sha` for `2.3.31.18`. This makes me suspect that this update isn't valid or isn't availiable.

**Comment by ran-dall** [comment]
@TomorrowWu @ElfSundae @taylorsfan I've downloaded the `.dmg`, checked the `appcast`, and checked the `.plist` of the app. I'm getting `2.3.31.18`. Can one of you show me where you got `2.3.31.19` from? 

```plist
<key>MMBundleVersion</key>
<string>2.3.31.18</string>
```

```xml
sparkle:version="13288" sparkle:shortVersionString="2.3.31.18"
```

@core-code @suschizu @vitorgalvao Have we encountered something like this before? The only thing I can think of would be that its CDN related.

**Comment by core-code** [comment]
i think we've seen this before. it seems to consistently give different versions to users based on their location (?)

maybe we could work around the problem with a language stanza?

**Comment by ran-dall** [comment]
> maybe we could work around the problem with a language stanza?

@core-code That seems like a fine idea.

**Comment by core-code** [comment]
all seems to be fine again now but lets try that if the problem appears again

**Pull request closed without merging**
