### PR TITLE
Update passenger to 4.6.1

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
its properly signed by macinmind: https://www.virustotal.com/#/file/860af97614dd12a751b132f0cf7d88110462ad88151a96f7e2dfacd6d2c3c8b2/detection

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/50896/files

**Comment by vitorgalvao** [comment]
> its properly signed by macinmind

I don’t see a signing section.

**Comment by core-code** [comment]
weirdly virustotal 
1.) doesn't show the signing section at all for some apps even when its properly signed
2.) also sometimes it shows the signing info but shows 'invalid' even when offline verification claims all is ok

anyone else noticed this?

**Comment by vitorgalvao** [comment]
> anyone else noticed this?

@commitay and I talked about this a while ago. Did you end up contacting them, @commitay?

**Comment by commitay** [comment]
Yes, the VirusTotal responses are in https://github.com/Homebrew/homebrew-cask/pull/45577. I haven't heard from them since then.

**Pull request closed without merging**
