### PR TITLE
Update pacifist to 3.5.11

### PR DESCRIPTION
**Pull request by reitermarkus**
After making all changes to the cask:
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by fanquake** [comment]
Just a heads up, looks like your including a second commit in a bunch of PRs.

**Comment by reitermarkus** [comment]
@fanquake, yes, I noticed, no idea what happened there exactly.

**Comment by adidalal** [comment]
Github seems to handle it just fine, though. 
¯\_(ツ)_/¯

**Comment by reitermarkus** [comment]
Yes, the commit even has the same hash in all PRs.

**Pull request merged**
