### PR TITLE
Add Hancom Word 2014

### PR DESCRIPTION
**Pull request by leejongyoung**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by leejongyoung** [comment]
The 2014 version is not a subscription, but a standalone version, so Cask is needed.

**Comment by bevanjkay** [comment]
Thank you @leejongyoung 
Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

**Comment by leejongyoung** [comment]
Apply zap stanza

**Comment by p-linnane** [comment]
Please add this to [`homebrew-cask-versions`](https://github.com/Homebrew/homebrew-cask-versions) since it's an alternate version.

**Pull request closed without merging**
