### PR TITLE
Update plex-media-player to 2.2.1.758-5dad2d62

### PR DESCRIPTION
**Pull request by boboldehampsink**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
`2.2.1` doesn't seem to be the public version, is it plex pass only?

**Comment by boboldehampsink** [comment]
Mmm saw this on their GitHub at the releases section

**Comment by commitay** [comment]
We track the version available for download from the homepage / listed in the appcast.

Thanks for the PR nonetheless.

**Comment by boboldehampsink** [comment]
Should we submit this as a preview version tho

**Pull request closed without merging**
