### PR TITLE
Update teamdrive.rb from 4.6.7.2328 to 4.6.7.2355

### PR DESCRIPTION
**Pull request by suschizu**
update teamdrive ❤️

### CODE REVIEW

**Comment by core-code** [comment]
`MissedUpdateML`

**Comment by core-code** [comment]
somethings very wrong with travis

**Comment by core-code** [comment]
travis stuck AGAIN

**Comment by suschizu** [comment]
I think this time travis worked 'almost' fine - just the warning seems not to be true :)
`- appcast at URL 'https://teamdrive.com/en/downloads/?utm_source=startingpage&utm_medium=cta&utm_campaign=download_en' does not contain the version number: '4.6.7.2355'`

**Pull request merged**
