### PR TITLE
Update dash to 4.1.2

### PR DESCRIPTION
**Pull request by Kapeli**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
@Kapeli Just noticed your online `appcast` is still showing `4.1.1`.

**Comment by Kapeli** [comment]
This update is a bit sensitive and I'm not releasing it to everyone at once. Appcast will be updated tomorrow to 4.1.2.

**Comment by phantomwhale** [comment]
Did the appropriate updates get done? I'm still seeing checksum issues when I `brew cask install dash` on a brand new machine?

**Comment by phantomwhale** [comment]
Ah - just saw https://github.com/caskroom/homebrew-cask/pull/42911 - guessing this is why I'm getting a checksum mismatch currently?

**Pull request merged**
