### PR TITLE
Update controlplane

### PR DESCRIPTION
**Pull request by core-code**
https://github.com/dustinrue/ControlPlane/issues/483#issuecomment-514269040

### CODE REVIEW

**Comment by core-code** [comment]
not ready to merge until we have a working link

**Comment by core-code** [comment]
the developer doesn't respond anymore and the link he has provided doesn't work. the cask download has been offline for months. my vote would be to remove the cask. if the developer every comes back with a working link, we can always re-instate it.

**Comment by vitorgalvao** [comment]
> my vote would be to remove the cask.

Agreed. https://github.com/Homebrew/homebrew-cask/delete/master/Casks/controlplane.rb.

**Comment by aheckler** [comment]
ControlPlane appears to be back on GitHub as of 5 days ago?

https://github.com/dustinrue/ControlPlane/releases

**Comment by core-code** [comment]
thanks for the heads-up:
https://github.com/Homebrew/homebrew-cask/pull/68155

**Pull request closed without merging**
