### PR TITLE
Use version conversion methods when possible.

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by fanquake** [comment]
```
Error: audit failed for 2 casks: latexit sqleditor
/usr/local/Library/Taps/caskroom/homebrew-cask/ci/travis/helpers.sh: line 45: shell_session_update: command not found
```

**Comment by vitorgalvao** [comment]
Looks just like Travis acting up.

**Comment by reitermarkus** [comment]
`latexit` fails because of:

```
 - unexpected HTTP response code retrieving appcast: 403
```

Stand-alone`curl` works fine:

```shell
$ curl -IL http://www.chachatelier.fr/latexit/downloads/LaTeXiT-2_8_0.dmg
HTTP/1.1 200 OK
Date: Tue, 12 Jul 2016 22:20:56 GMT
Content-Type: application/x-apple-diskimage
Content-Length: 11073977
Server: Apache
Last-Modified: Mon, 07 Sep 2015 21:09:09 GMT
Accept-Ranges: bytes
Age: 50451
X-Cache: HIT from localhost
X-Cache-Lookup: HIT from localhost:3129
Via: 1.1 localhost (squid/3.5.12)
Connection: keep-alive
```

**Comment by vitorgalvao** [comment]
Travis failed on a single cask, and it seemed to have just been a network hiccup.

There’s a conflict, now. Mind fixing it so we can merge, @reitermarkus?

**Comment by reitermarkus** [comment]
Ok, all is fixed now.

**Comment by vitorgalvao** [comment]
Thank you. Merging now.

**Pull request merged**
