### PR TITLE
Update bettertouchtool from 3.505-1643 to 3.506-1644

### PR DESCRIPTION
**Pull request by lubomben**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by core-code** [comment]
@vitorgalvao as expected the new appcast doesn't work better than any before

**Comment by vitorgalvao** [comment]
> as expected the new appcast doesn't work better than any before

But the TXT one is no longer live. Unless we can bring it back, the only thing to do is remove `appcast` entirely.

**Comment by core-code** [comment]
i do not want to bring the appcast back - its work and people aren't even satisfied it it "only" runs every 2 hours. unfortunately the webhost doesn't allow more frequent running of cronjobs.


one solution would be just to stick to the version which is offered in the appcast and disregard any PR that tries to update to any version which is only available via the homepage.

removing the appcast will see PRs that update to the alpha version which isn't even linked on the homepage. seems like the worst option.

**Comment by vitorgalvao** [comment]
> people aren't even satisfied it it "only" runs every 2 hours. unfortunately the webhost doesn't allow more frequent running of cronjobs.

I was surprised it was run so often! I thought it would be a once-a-day thing, or once every 12 hours max.

> one solution would be just to stick to the version which is offered in the appcast and disregard any PR that tries to update to any version which is only available via the homepage.

That might leave us with tons of new PRs to keep closing, which won’t be pleasant. This is both a problematic and popular cask, the suckiest of combinations. [If the developer doesn’t help](https://github.com/Homebrew/homebrew-cask/pull/92405#issuecomment-729926908), we’ll have to think of something else.

Pinging @miccal for ideas.

In the meantime, letting this one through, as it’s valid.

**Comment by core-code** [comment]
i think the real solution here would be for travis to learn about version numbers. basically all casks with static downloads URLs suffer from similar problems.

**Comment by vitorgalvao** [comment]
> i think the real solution here would be for travis to learn about version numbers.

What do you mean?

**Comment by core-code** [comment]
when a cask has a static download URL we only want to let PRs through automatically that correctly update the SHA (CI checks this) and the version number (CI doesn't check this, only via an appcast which is often not in in sync with the download and therefore we both have false positives and false negatives).

**Pull request merged**
