### PR TITLE
Update adguard to 1.5.8

### PR DESCRIPTION
**Pull request by nxft**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by Mycatisanalien** [comment]
verification:
screen shot 2018-06-27 at 13 45 25

**Comment by vitorgalvao** [comment]
@Mycatisanalien That is not verification. Please read the link.

**Comment by Mycatisanalien** [comment]
[VirusTotal](https://www.virustotal.com/#/file/421756ece1cad65b65f994ac803651e9b443ef61eda31c21ec8dec12d2379b1d/details)

**Comment by vitorgalvao** [comment]
Thank you, @Mycatisanalien.

**Pull request merged**
