### PR TITLE
Update cask to use Little Flocker Latest

### PR DESCRIPTION
**Pull request by securitygeneration**
- [√ ] `brew cask audit --download {{cask_file}}` is error-free.
- [√ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [√ ] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This branch has conflicts.

Also, we prefer versioned casks, like the one you submitted previously.

**Comment by securitygeneration** [comment]
I'm not sure why it ended up with conflicts. Could sort that out. As with versioning, I'm not a member of the Little Flocker project and may not be able to maintain this cask on a timely basis, hence my preference for a Latest approach. I'd rather that than an outdated cask.

**Comment by vitorgalvao** [comment]
> I'm not a member of the Little Flocker project and may not be able to maintain this cask on a timely basis

Most casks are not maintained by the developers, and no cask has a set maintainer.

> I'd rather that than an outdated cask.

We have policies, and don’t change them based on a single user’s preference. Our users in the past came in overwhelming support of versioned casks for security reasons, and so we stick with those.

**Comment by securitygeneration** [comment]
Understood.

**Pull request closed without merging**
