### PR TITLE
Update sbrowserq to 3.4

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by gtmgianni** [comment]
@commitay I can't test `brew cask install` or `uninstall` locally, because every time I run the `install` command, it automatically checks out into the `master` branch. Is this expected behaviour or is it just an issue specific to my system?

**Comment by commitay** [comment]
Please post `brew config`

**Comment by gtmgianni** [comment]
```
$ brew config
HOMEBREW_VERSION: 1.5.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 85ebe88094f9095871b6ad752077ee1100b20328
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 96da4a5429c3608b9dead2b90e01e83957857eec
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Volumes/GTM-USBX/
HOMEBREW_RUBY_WARNINGS: -W0
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.16.3 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 9.0.1
macOS: 10.13.4-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

**Comment by commitay** [comment]
https://github.com/Homebrew/brew/pull/3802 calls `brew update` when `brew cask (install|upgrade)` is run.

You can set `HOMEBREW_NO_AUTO_UPDATE=1` or `
HOMEBREW_AUTO_UPDATE_SECS=large_number`

**Comment by gtmgianni** [comment]
@commitay Thank you!

**Pull request merged**
