### PR TITLE
Fix broken link for documented exception in PR template

### PR DESCRIPTION
**Pull request by bbenzikry**

### CODE REVIEW

**Review by reitermarkus — DISMISSED** [review]

**Comment by SMillerDev** [comment]
It should probably link to https://docs.brew.sh/Acceptable-Casks instead.

**Comment by bbenzikry** [comment]
@SMillerDev done

**Comment by miccal** [comment]
Thank you @bbenzikry.

**Review by miccal — APPROVED** [review]

**Pull request merged**
