### PR TITLE
Only run keybase uninstall command if exists

### LINKED ISSUE #30145: Bug Report: uninstalling keybase causing exception
Looks like cask left some leftovers from keybase when I tried to install/uninstall it earlier, so this time I tried to install it and then uninstall for full cleanup action. Oh well, that didn't work and here the exception.

Following troubleshooting steps didn't help, so here is output. 

```
 brew untap caskroom/cask; brew cleanup; brew cask cleanup; brew update

Untapping caskroom/cask... (6,117 files, 132.1M)
Untapped 0 formulae
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3657, done.
remote: Compressing objects: 100% (3642/3642), done.
remote: Total 3657 (delta 32), reused 318 (delta 11), pack-reused 0
Receiving objects: 100% (3657/3657), 1.22 MiB | 0 bytes/s, done.
Resolving deltas: 100% (32/32), done.
Tapped 0 formulae (3,666 files, 3.8M)
==> Removing cached downloads
/Users/XXX/Library/Caches/Homebrew/Cask/atom--1.14.1.zip
/Users/XXX/Library/Caches/Homebrew/Cask/keybase--1.0.18-20170209165653,17b641d.dmg
/Users/XXX/Library/Caches/Homebrew/Cask/visual-studio-code--1.9.0,27240e71ef390bf2d66307e677c2a333cebf75af.zip
==> This operation has freed approximately 210.5M of disk space.
Already up-to-date.
```

And failure:

```bash
 $ brew cask remove keybase
Error: No such file or directory - /Applications/Keybase.app/Contents/SharedSupport/bin/keybase
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `spawn'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `popen_run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:79:in `each_output_line'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:24:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:17:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/base.rb:14:in `system_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:42:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:35:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:35:in `block in abstract_phase'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:34:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:28:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:325:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:322:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:322:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:313:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:26:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/uninstall.rb:9:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:154:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
(3) b@b-imac /usr/local/Homebrew (master) $ ls -la /Applications/Keybase.app/Contents/SharedSupport/bin/keybase
ls: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase: No such file or directory
```

### PR DESCRIPTION
**Pull request by joshka**
Fixes #30145 

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by reitermarkus** [comment]
@vitorgalvao, might be a good idea to make sure the `uninstall` stanza is called before artifacts are removed, as it may depend on them being present, as in this case. This way using `uninstall script:` and `uninstall signal:` would work as expected.

**Comment by vitorgalvao** [comment]
@reitermarkus Agreed. That sounds like the better solution.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/30162

**Comment by vitorgalvao** [comment]
In light of https://github.com/caskroom/homebrew-cask/issues/30162, this is no longer needed.

In fact, mind transforming all this into an `uninstall` [as discussed before](https://github.com/caskroom/homebrew-cask/pull/29956#discussion_r100434420), @joshka?

**Comment by reitermarkus** [comment]
@vitorgalvao, actually, `uninstall` will still fail if it doesn't exist. Maybe we should allow `uninstall script:` to fail if the script doesn't exist when using `--force`?

**Comment by vitorgalvao** [comment]
@reitermarkus I was thinking that wasn’t needed since `uninstall script:` has a `must_succeed` we can set to `false`. But now that I think of it, that should only work if the script does exist but fails, not if it doesn’t exist all.

That’s probably a good idea, yes.

**Comment by reitermarkus** [comment]
Yes, this way is still has to succeed when not using `--force`, which is preferable.

**Comment by joshka** [comment]
I may be remembering this incorrectly, but I seem to recall setting must_succeed to false didn't work due to https://github.com/Homebrew/brew/blob/4b5489e1721c6cb3fd3b9a7aeb988eb3b381ec41/Library/Homebrew/cask/lib/hbc/system_command.rb#L17

**Pull request closed without merging**
