### PR TITLE
Remove basex.rb

### PR DESCRIPTION
**Pull request by colindunn**
Download link is no longer presented on the [downloads page](http://basex.org/products/download/all-downloads/) and instead recommends installing "Mac OSX via [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/basex.rb)"

@rzyns or @bchatard is there a reason this cask should be kept?

---

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by rzyns** [comment]
Probably not. I think the only officially supported way to run it is using
their shell script, and I don't think they even bundle it as Mac App
anymore.

**Comment by colindunn** [comment]
Thanks for coming back quickly @rzyns

**Comment by reitermarkus** [comment]
Also add it to [`tap_migrations.json`](https://github.com/caskroom/homebrew-cask/blob/8f7c03cb52bf6340da34db8c676904bbd2c972a9/tap_migrations.json).

**Comment by colindunn** [comment]
Done

**Review by adidalal — APPROVED** [review]

**Pull request merged**
