### PR TITLE
Add Jump Desktop Connect v4.1.3

### PR DESCRIPTION
**Pull request by viking1304**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

Jump Desktop Connect is free server application that allows high performance desktop sharing using a fraction of bandwidth of RDP/VNC.

https://jumpdesktop.com/connect/

Jump Desktop client application can be used to access your remote desktop.

https://jumpdesktop.com/

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @viking1304.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by viking1304** [comment]
@miccal  I added and tested zap on my Mac, but test fails again with

```
Run brew ruby -r "$(brew --repository homebrew/cask)/cmd/lib/check.rb" <<'EOF'
Error: Some launch jobs were not unloaded, add them to uninstall launchctl:
com.p5sys.jump.connect.49240.A3585485-3CB2-4F00-B80F-F58B44A9BC73
Error: Some launch jobs were not unloaded, add them to uninstall launchctl:
com.p5sys.jump.connect.49240.A3585485-3CB2-4F00-B80F-F58B44A9BC73
Error: Process completed with exit code 1.
```

**Comment by miccal** [comment]
Thank you @viking1304.

**Comment by viking1304** [comment]
@miccal Thank you too, my friend! I would not be able to finish this without your help.

**Pull request merged**
