### PR TITLE
PULL_REQUEST_TEMPLATE.md: updated message for sha256 change without version

### PR DESCRIPTION
**Pull request by vitorgalvao**
After seeing it live, it seemed a bit verbose/confusing still. Suggesting this small change.

### CODE REVIEW

**Review by reitermarkus — CHANGES_REQUESTED** [review]
Maybe:

`Confirmation by developer: {{link}}`

**Comment by giannitm** [comment]
@vitorgalvao @reitermarkus Just wondering, do you think it would be wise to add new tag for pull requests which still need to be verified (e.g. https://github.com/caskroom/homebrew-cask/pull/33570). Or will the "on hold" tag suffice?

**Comment by vitorgalvao** [comment]
@giannitm Currently, it should be `on hold` + `upstream`. By I wouldn’t oppose a new label.

**Comment by vitorgalvao** [comment]
@reitermarkus How about like this? We don’t need to repeat it’s a link. The amount of earlier commits was me trying to align the text, but apparently Github always has that small indentation.

**Review by reitermarkus — APPROVED** [review]

**Comment by reitermarkus** [comment]
> The amount of earlier commits was me trying to align the text, but apparently Github always has that small indentation.

That was also driving me nuts yesterday. 😂

**Pull request merged**
