### PR TITLE
Migrated focusrite-control from homebrew-cask-drivers

### PR DESCRIPTION
**Pull request by ivicamil**
Migrated `focusrite-control` formula as asked in [this issue](https://github.com/Homebrew/homebrew-cask-drivers/issues/3414). The formula file is identical to the [one that was removed](https://github.com/Homebrew/homebrew-cask-drivers/blob/caa3028d12e80d71ea48077970218ca483e09640/Casks/focusrite-control.rb) from homebrew-cask-dtiver repo.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Hi, thank you for opening this! 
Thank you for your submitting this! Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask. Would you be able to open a PR in homebrew-cask-drivers as well? See: https://github.com/Homebrew/homebrew-cask-drivers/issues/3414#issuecomment-1506634251

Thank you!

**Comment by ivicamil** [comment]
> Hi, thank you for opening this! Thank you for your submitting this! Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask. Would you be able to open a PR in homebrew-cask-drivers as well? See: [Homebrew/homebrew-cask-drivers#3414 (comment)](https://github.com/Homebrew/homebrew-cask-drivers/issues/3414#issuecomment-1506634251)
> 
> Thank you!

I've created a PR with updated `tap_migrations.json`.

About the zap stanca, is that the following:

```
zap trash: [
    "~/Library/Application Support/Focusrite"
    #etc...
  ]
```

**Comment by razvanazamfirei** [comment]
@ivicamil, thank you! 

Yes, that's it. The zap stanza link has more info about how you can create it.

**Comment by ivicamil** [comment]
> Hi, thank you for opening this! Thank you for your submitting this! Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask. 

Added everything I could find.

**Comment by razvanazamfirei** [comment]
Wonderful! Thank you so much! I'll make some small edits, but this looks great! 👍 👍

**Review by razvanazamfirei — DISMISSED** [review]

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
