### PR TITLE
Update vscodium from 1.43.2 to 1.44.0

### PR DESCRIPTION
**Pull request by nathanwhit**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Review by core-code — COMMENTED** [review]
>  tag = '1.43.2'

whats this?

**Comment by nathanwhit** [comment]
> > tag = '1.43.2'
> 
> whats this?
The maintainer didn't create a new tag on Github for the 1.44.0 release, so the package is (most likely mistakenly) filed under the `1.43.2` tag. The original download URL assumed that the tag and version match, but in this case they don't, so I manually specified the correct tag in order to make the correct download URL.

**Comment by vitorgalvao** [comment]
We don‘t like having random variables in the middle of casks. Please hardcode the tag version into the URL instead.

**Comment by nathanwhit** [comment]
Understood. I've applied that feedback and pushed the revised version.

**Comment by reitermarkus** [comment]
Seems like there is a 1.44.0 tag now.

**Comment by nathanwhit** [comment]
Indeed there is, it looks like I was a little early on this one.
I've updated the PR once more to use the correct tag.

**Pull request merged**
