### PR TITLE
reaper-arm: Add ARM version of REAPER for compatibility with VLC and enable video editing

### PR DESCRIPTION
**Pull request by leafac**
### Why Is This Necessary If `reaper.rb` Already Exists?

Video editing requires compatibility with VLC, [which is installed with ARM](https://github.com/Homebrew/homebrew-cask/blob/77b86126e8fe50329d80c228c39681aaf46fa353/Casks/vlc.rb#L12). But [audio plugins may not work with ARM](https://www.reaper.fm/download.php), so I think it makes sense to continue pointing `reaper.rb` to x64 and have a separate Cask instead.

---

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference). **I think so, but I couldn’t find a precedent of this situation with two valid versions of the application with different architectures…**
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask). **Maybe it should go to https://github.com/Homebrew/homebrew-cask-versions? Again, I couldn’t find a precedent…**
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by leafac** [comment]
Ooops, the tests fail because this Cask is unavailable for x64 computers but GitHub Actions don’t support macOS with M1 yet…

What should I do?

**Comment by SMillerDev** [comment]
Why not make this an alternative download for reaper?

**Comment by leafac** [comment]
Hmmm, “alternative downloads,” what are they? Something that the user can select which version to install? If so, that’d be cool, can you please point me at right direction to make it work?

On the other hand, if you mean and if-then-else checking the architecture and always installing the ARM version in ARM computers, then I think that’s a bad idea. I think that users should be able to select the version that’ll be compatible with the rest of their setup: VLC as installed via Homebrew is compatible with ARM, and many audio plugins are x64-only.

**Comment by SMillerDev** [comment]
> On the other hand, if you mean and if-then-else checking the architecture and always installing the ARM version in ARM computers, then I think that’s a bad idea. I think that users should be able to select the version that’ll be compatible with the rest of their setup: VLC as installed via Homebrew is compatible with ARM, and many audio plugins are x64-only.

This is what I meant. Counter argument though, these people knowingly bought an M1 powered mac so they should expect stuff not to be perfect yet. And they can always run brew in Rosetta mode to install the Intel versions.

**Comment by leafac** [comment]
Hmmm, you make good points, but I don’t think it applies in REAPER’s case. The main use case for most people is music production; my main use case (video editing) is merely a side-gig for REAPER. So I think that maintaining compatibility with audio plugins is more important than VLC.

That said, if you’re still unconvinced, then I’m happy to change the pull request the way you suggested. Just let me know 😃

**Comment by SMillerDev** [comment]
We can always go for your route if too many people find this inconvenient. I think providing a native install as default should be the first step.

**Comment by leafac** [comment]
👍 I changed the pull request to have a single `reaper` Cask which installs the ARM version on Macs with the M1 processor.

**Comment by cho-m** [comment]
There is probably an issue with this update, which our CI can't catch right now as we don't test ARM (#107586).

The ARM-variant uses different app names:
- `REAPER-ARM.app`
- `ReaMote-ARM.app`

Right now, the Cask will try to install:
- `REAPER.app`
- `ReaMote.app`

**Comment by leafac** [comment]
Oops, yeah, thanks for catching my mistake—I forgot to change that part when I merged `reaper-arm.rb` into `reaper.rb`.

**Pull request merged**
