### PR TITLE
Update dropbox from 155.4.5493 to 156.3.4862

### PR DESCRIPTION
**Pull request by chiefmikey**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @chiefmikey bit this is a beta release.

**Comment by chiefmikey** [comment]
Ah thanks @miccal. My script runs `brew lc --newer-only` and plugs the newer version into `bump-cask-pr --version`. Do you know why `brew lc` might print a beta version or a suggestion for avoiding that?

**Comment by miccal** [comment]
Sometimes the `livecheck` for Dropbox picks up the beta version, I am not sure why. Note that stable ones have a minor version of `4`, while beta ones have a minor version of `3`.

**Comment by chiefmikey** [comment]
Good to know, thanks!!

**Pull request closed without merging**
