### PR TITLE
fix bug: bad double quotes to single quotes in internet plugins for korean bank 

### PR DESCRIPTION
**Pull request by daehyunpy**
#13004
#13008

i’m sorry, i think i forgot to fix it. 
i fixed bad double quotes.

### CODE REVIEW

**Comment by jawshooah** [comment]
@hyuna917 Just so you know, you don't have to keep closing these PRs and opening new ones. You can just push new commits to the same branch.

**Comment by jawshooah** [comment]
Also, judging from the commits listed in this PR, you really need to [rebase your branch](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) onto our `master`.

**Comment by hyuna917** [comment]
i didn’t know that! thank you @jawshooah

**Comment by jawshooah** [comment]
There's something strange going on with your branch, it seems. Try running `git fetch origin master && git rebase origin/master feature/add-plugins-for-banking && git push --force`.

**Comment by hyuna917** [comment]
Hmm, I think I did so stupid thing. It was my first time to do `rebase`. @jawshooah, do you think now it’s okay?

**Comment by alebcay** [comment]
Nope, something has gone terribly, terribly wrong.

**Comment by hyuna917** [comment]
i think i should remake a branch

**Pull request closed without merging**
