### PR TITLE
Add Infinit.app v0.9.43

### PR DESCRIPTION
**Pull request by digitalknk**

### CODE REVIEW

**Comment by adityadalal924** [comment]
Should probably [squash your commits](http://davidwalsh.name/squash-commits-git) to keep things cleaner, fyi.

**Comment by digitalknk** [comment]
Thank you @adityadalal924 , that's exactly what I was looking for!

**Comment by vitorgalvao** [comment]
#11894
#12344

Is that fixed upstream, @digitalknk? If it is, please report back so we can reopen.

**Comment by digitalknk** [comment]
@vitorgalvao The dmg I am using applies the correct infinit.app and it does not have this issue. This dmg is directly from infinit as well. Thanks for bringing this up, I was wondering why infinit never was added to Cask.

**Comment by vitorgalvao** [comment]
Thank you. It still needs to use

```ruby
version :latest
sha256 :no_check
```

though, since without it the cask would break on updates.

**Comment by digitalknk** [comment]
@vitorgalvao done and thank you again :-)

**Comment by vitorgalvao** [comment]
Thank you.

**Pull request merged**
