### PR TITLE
ResidualVM cask has been added from https://www.residualvm.org/downloads

### PR DESCRIPTION
**Pull request by volkanorhan**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
>> I checked the issues, and I found 2 old issues. I will remove the cask from homebrew-core because it is a GUI application unlike other homebrew-core applications.
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

Please don't reject this request, because as I explained above, I will remove the same cask from homebrew-core, because it is a GUI application unlike other homebrew-core applications.

### CODE REVIEW

**Comment by volkanorhan** [comment]
Build failed on CI/ci step. I looked at the logs, but it only says Error: Build failed. I couldn't see any other error message.

**Comment by miccal** [comment]
```
audit for residualvm: warning
 - possible duplicate, cask token conflicts with Homebrew core formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/residualvm.rb
```

**Comment by volkanorhan** [comment]
> This seems to be already available in Homebrew Core:
> 
> ```
> audit for residualvm: warning
>  - possible duplicate, cask token conflicts with Homebrew core formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/residualvm.rb
> ```

It is a GUI application as I explained above. I created a merge request for deletion of the homebrew-core formula. The formula to be deleted should be here, not on core side.

**Comment by miccal** [comment]
Is there an open PR in Homebrew Core to remove it?

**Comment by volkanorhan** [comment]
> Is there an open PR in Homebrew Core to remove it?

Yes, I created it today. https://github.com/Homebrew/homebrew-core/pull/55542

**Comment by ran-dall** [comment]
@volkanorhan We're going to wait till Homebrew/homebrew-core#55542 is merged. Therefore, I added the `Do Not Merge` label. It helps us keep the PR organzied.

**Comment by volkanorhan** [comment]
> @volkanorhan We're going to wait till [Homebrew/homebrew-core#55542](https://github.com/Homebrew/homebrew-core/pull/55542) is merged. Therefore, I added the `Do Not Merge` label. It helps us keep the PR organzied.

https://github.com/Homebrew/homebrew-core/pull/55542 pull request was approved. Please remove "Do Not Merge" label.

**Pull request merged**
