### PR TITLE
starnet2 02,2023 (new cask)

### PR DESCRIPTION
**Pull request by audibleblink**
- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@audibleblink How does this differ from the existing [`starnet-plus-plus`](https://github.com/Homebrew/homebrew-cask/blob/4341bac86a006e3f14f812be6e38cb1773d865b7/Casks/s/starnet-plus-plus.rb) cask?

**Comment by audibleblink** [comment]
@bevanjkay starnet-plus-plus has a different set of libraries, pytorch vs tensorflow.
the binaries hardcode different library paths and have different ways of being able to configure load paths.
starnet2 is arm64 only.
the installation packages for each tool by the author are presented as different applications.

**Comment by bevanjkay** [comment]
@carlocab Any thoughts here, as you reviewed the related `starnet++`? Thanks.

**Comment by audibleblink** [comment]
happy to make changes if there's any feedback

**Comment by razvanazamfirei** [comment]
This, generally, looks fine to me, but I'm not familiar with `starnet++`, so I'll defer to other. 

One note is that the description should probably be updated to meet our [guidelines](https://docs.brew.sh/Cask-Cookbook#stanza-desc).

**Comment by krehel** [comment]
Agreed, I'm ok here as well!

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
