### PR TITLE
steelseries-gg 54.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — DISMISSED** [review]

**Comment by bevanjkay** [comment]
There's an issue here with an overzealous `uninstall kext` - I can fix a bit later when I'm at a computer.

**Comment by bevanjkay** [comment]
It would seem unrelated if this fails due to `firefox` running. Strange, but unrelated.
Something in the installer must launch the app 🤷‍♂️

**Comment by bevanjkay** [comment]
Tried installing/uninstalling locally and firefox doesn't launch.

**Review by reitermarkus — DISMISSED** [review]

**Comment by bevanjkay** [comment]
Looks like the uninstaller launches whatever browser is available.
Set CI to uninstall firefox, and then it opens edge instead. So short of uninstalling all of the browsers on CI before running CI, we may need a way to ignore this?

Any thoughts here @reitermarkus

**Pull request closed without merging**
