### PR TITLE
Upgrade DeSmuME.app to 0.9.13

### PR DESCRIPTION
**Pull request by murs313**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by murs313** [comment]
CI failed with the following error:
```
Version '0.9.13' differs from '0_9_13' retrieved by livecheck.
```

Is the applied livecheck strategy `github_latest`? If so, I think it's because of the underscore in the tag name...
https://github.com/TASEmulators/desmume/releases/latest

I don't have an idea of the appropriate livecheck.
Can you help me?

**Comment by p-linnane** [comment]
If you run `brew lc --cask --debug desmume` it will tell you what strategy is being used. With the new URL you've provided, it's using the [Git](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy/Git.html) strategy.

I've added some suggestions to correctly grab the latest version and handle the . to _ issue. Take a look and let me know if it's helpful. I verified this works locally.

**Comment by murs313** [comment]
Thank you, @p-linnane ! I confirmed the strategy being used.

Where can I see the suggestions you added...?
Sorry if I have misunderstood due to my English ability. TT

**Comment by p-linnane** [comment]
They're right above my last comment. Or if you go to the 'Files changed' tab you can see them as well. You can merge my suggestions in or use them as a reference to implement them yourself.

**Comment by murs313** [comment]
Thanks, @p-linnane !
I know about the "suggested change" feature on github, but it doesn't appear to be there.
Maybe you have "Start a review" and not "Finish your review"?
Is there a "Pending" sign near the commit? Such as this:
スクリーンショット 2022-08-05 16 34 08

**Comment by miccal** [comment]
Thank you @murs313.

**Review by miccal — APPROVED** [review]

**Pull request merged**
