### PR TITLE
Update macspice from 3.1.25 to 3.2.1

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
@miccal This time around I had the same HTTP 403 Forbidden problem locally as CI has. I tried `bump-cask-pr` a few times over the course of ten minutes without success. Then went to `homepage` and clicked on the download link there. After that, `bump-cask-pr` worked fine. Faking user_agent doesn't seem to help. Can you verify locally?

**Comment by miccal** [comment]
For `macspice`:
```
==> Analytics
install: 16 (30 days), 28 (90 days), 79 (365 days)
```
For `captain`:
```
==> Analytics
install: 2 (30 days), 7 (90 days), 47 (365 days
```
If the `url`'s are that unstable, I would suggest removal.

**Comment by neutric** [comment]
Not necessary for `captain`: https://github.com/Homebrew/homebrew-cask/pull/116902

**Comment by neutric** [comment]
> If the `url`'s are that unstable, I would suggest removal.

Not sure I'd call them unstable. We are just missing an automated "open sesame".

**Comment by carlocab** [comment]
Can we try to contact the author at https://www.macspice.com/Support.html? Maybe they'd be willing to consider using a friendlier hosting service than Dropbox.

**Comment by neutric** [comment]
@carlocab Will do!

**Pull request closed without merging**
