### PR TITLE
Add Downloader for Apple Developers v2.0.1

### PR DESCRIPTION
**Pull request by jamesstout**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

Reason for not using the `Proposed token: downloader` - it's a bit vague, and a `brew search` on `downloader` returns 9 casks already.

### CODE REVIEW

**Comment by i0ntempest** [comment]
@vitorgalvao Did you see the submitter’s explanation for why he didn’t name this “downloader”?

**Comment by vitorgalvao** [comment]
> @vitorgalvao Did you see the submitter’s explanation for why he didn’t name this “downloader”?

I had missed that, thank you for pointing that out.

That said, the amount of casks returned by a `search` is irrelevant and the naming is upstream’s responsibility. I very much agree they should change the name [and asked about it](https://github.com/vineetchoudhary/Downloader-for-Apple-Developers/issues/5#issuecomment-715642369).

**Comment by vitorgalvao** [comment]
Putting this on hold until [the renaming](https://github.com/vineetchoudhary/Downloader-for-Apple-Developers/issues/5#issuecomment-716282569) happens.

**Comment by vitorgalvao** [comment]
Looks like the rename is going to take a while.

Thank you anyway, but we’ll close this in the meantime. You’re welcome to reopen when upstream changes the name.

**Pull request closed without merging**
