### PR TITLE
Add enpass.rb

### PR DESCRIPTION
**Pull request by Eitot**
Password manager

### CODE REVIEW

**Comment by victorpopkov** [comment]
You should check your Git configurations (`git config`). At the moment the email used in your commits doesn't point to your GitHub account so your contribution won't be credited to you.

**Comment by Eitot** [comment]
@victorpopkov: I modified it with `git config`, but how can I change or override the commit?

**Comment by victorpopkov** [comment]
Yes, the email address will be exposed. If you don't want to expose it, you could use the `<your_username>@users.noreply.github.com`.

**Comment by Eitot** [comment]
@victorpopkov: That’s indeed what I did. I wonder about my previous commits though. Didn’t realise that Github uses my email address unless I set it to private.

**Comment by Eitot** [comment]
I think I fixed it now, for both pull requests. Past commits don’t seem to have exposed my email address. Thanks for the heads-up.

**Comment by vitorgalvao** [comment]
Thank you, but this a [walled build](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#finding-a-home-for-your-cask).

We cannot accept it here. You may submit it to [caskroom/unofficial](https://github.com/caskroom/homebrew-unofficial), though.

**Pull request closed without merging**
