### PR TITLE
yes24-ebook 1.0 (new cask)

### PR DESCRIPTION
**Pull request by daeho-ro**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [v] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [v] `brew audit --cask --online <cask>` is error-free.
- [v] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [v] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [v] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [v] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [v] `brew audit --cask --new <cask>` worked successfully.
- [v] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [v] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Thank you for your submission to homebrew-cask @daeho-ro. Please try to add a [livecheck](https://docs.brew.sh/Cask-Cookbook#stanza-livecheck) to this cask.

**Comment by daeho-ro** [comment]
I have tried but cannot find any version information on the homepage or url.
https://www.yes24.com/notice/eBookGuide/guide_pc.aspx

**Comment by bevanjkay** [comment]
I found a source for the livecheck, and also pushed changes for the relevant issues that arose after this (ie. versioned download `url` being available).

**Comment by daeho-ro** [comment]
Should I change the homepage url to https://www.yes24.com/Main/default.aspx? The main domain returns 302 status but actually user can access and then redirected.

**Comment by bevanjkay** [comment]
Yeah, give that a go.

**Review by bevanjkay — APPROVED** [review]

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
