### PR TITLE
anka-build: splitting package

### PR DESCRIPTION
**Pull request by NorseGaud**
After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [?] `brew audit --cask --new <cask>` worked successfully.
```
❯ brew audit --cask --new anka-build-cloud-controller    
Error: Cask 'anka-build-cloud-controller' is unavailable: No Cask with this name exists.
```
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

We now require customers to install both the controller and registry packages separately, instead of the combined package.

### CODE REVIEW

**Comment by SMillerDev** [comment]
This means that anyone who has the original will no longer get updates after this without any notice. I think it should have a caveat for a while instead of deleting.

**Comment by NorseGaud** [comment]
Hey @SMillerDev , there won't be any updates for it. We also don't want people installing it anymore. We're fine with the removal.

**Comment by SMillerDev** [comment]
There might not be any updates for it, but people who have it installed will never know something changed. Don't you want people switching to the new casks?

**Comment by NorseGaud** [comment]
Correct, our customers have already been notified and have an upgrade guide. If they're not already on the next version, they will soon.

It won't forcefully uninstall it from customer machines though, right?

**Review by SMillerDev — CHANGES_REQUESTED** [review]
Okay, it's not just concern It's expectancy of users too. Please add a `discontinued` caveat so people will get some notice before removing the cask in a future PR. 

I'm sure you send out a notice, but more notices never hurt anyone.

**Review by SMillerDev — DISMISSED** [review]
Thanks @NorseGaud  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Review by miccal — APPROVED** [review]

**Pull request merged**
