### PR TITLE
Upgrade genymotion to 3.0.2

### PR DESCRIPTION
**Pull request by dmajumdar2012**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by dmajumdar2012** [comment]
Genymotion has a dependency on virtualbox and the latest version of vbox seems to be unstable. How can I link the dependency to a particular version of virtualbox?

**Comment by dmajumdar2012** [comment]
Looks like it maybe an issue with your build env - https://github.com/Homebrew/homebrew-cask/issues/63337

Can we please prioritize on fixing this and getting this PR merged?

Here is the release notes for Genymotion 3.0.2 - https://www.genymotion.com/product-release-note/desktop/

It fixes some major instability issues with 3.0.1

**Comment by vitorgalvao** [comment]
> How can I link the dependency to a particular version of virtualbox?

The VirtualBox issue should be temporary. There’s no point in changing the cask dependency back and forth.

> Can we please prioritize on fixing this and getting this PR merged?

As per the linked issue, the problem seems to be on Oracle’s side. If you want it fixed fast pressure them, not us.

The problems with VirtualBox do not prevent this from being merged.

**Comment by dmajumdar2012** [comment]
Thanks for getting this merged.

**Pull request merged**
