### PR TITLE
Update appcast in  segger-embedded-studio-for-arm.rb

### PR DESCRIPTION
**Pull request by suschizu**
the other one had a ssl problem

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Why’s the `macupdater.net` one failing? Can you shed some light, @core-code? I’d rather have all of your CGI appcasts on the same domain, for easy grepping when necessary.

**Comment by core-code** [comment]
well, it is failing because strictly speaking their SSL is broken:

"https://www.ssllabs.com/ssltest/analyze.html?d=www.segger.com"

python 3 seems to be picky here and refuse connection. python2 on the other server doesn't mind.

unfortunately we had the other situation too where only the macupdater.net server works for some SSLv3 (?) sites...

not sure about a good solution here, i can definitely understand not wanting to rely on 2 different CGI servers.

**Comment by core-code** [comment]
i see that they have release notes here:

https://studio.segger.com/index.htm?https://studio.segger.com/arm_segger_studio_release_notes.htm

**Comment by suschizu** [comment]
does not contain the version unfortunately (curl)

**Comment by core-code** [comment]
this seems to work fine for me

` curl https://studio.segger.com/arm_segger_studio_release_notes.htm`

**Comment by vitorgalvao** [comment]
Thank you.

**Pull request merged**
