### PR TITLE
updated apache-directory-studio (2.0.0.v20150606-M9)

### LINKED ISSUE #12110: apache-directory-studio not working
The installation of Apache Directory Studio fails with the following messages:

 brew install Caskroom/cask/apache-directory-studio
==> brew cask install Caskroom/cask/apache-directory-studio
==> Downloading http://www.us.apache.org/dist/directory/studio/dist/2.0.0.v20130628/ApacheDirectoryStudio-macosx-x8

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'apache-directory-studio' with message: Download failed: http://www.us.apache.org/dist/directory/studio/dist/2.0.0.v20130628/ApacheDirectoryStudio-macosx-x86_64-2.0.0.v20130628.dmg

### PR DESCRIPTION
**Pull request by vitorgalvao**
Fixes #12110.

### CODE REVIEW

**Comment by dscoduc** [comment]
almost...

$ brew install Caskroom/cask/apache-directory-studio
==> brew cask install Caskroom/cask/apache-directory-studio
==> Downloading http://www.us.apache.org/dist/directory/studio/2.0.0.v20150606-M9/ApacheDirectoryStudio-2.0.0.v2015
######################################################################## 100.0%
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/apache-directory-studio/2.0.0.v20150606-M9/Apache Directory Studio.app'

**Comment by vitorgalvao** [comment]
That one’s easier to fix. Just download the package, uncompress it, see where the app is and correct it. Care to take a stab at it?

**Comment by dscoduc** [comment]
I would but I am relatively new to Git and it may be an actual stab more than progress...

**Comment by vitorgalvao** [comment]
Well, you won’t get better if you don’t try. Like I said, it’s an easy fix. I can help you if you submit a PR, but I won’t fix that part anytime soon.

**Comment by dscoduc** [comment]
Can you give me some hints on where to start with the Cask sequencing?  The .rb file doesn't reference any symlinks or download paths...  I checked the '/opt/homebrew-cask/Caskroom/' folder and there isn't anything in there...

**Comment by vitorgalvao** [comment]
Just look at `url` and `app`. `app` is assuming an `Apache Directory Studio.app` at the root of the package downloaded by `url`. That error simply means it isn’t there. Likely, it either changed names or is now under a subdirectory.

**Comment by dscoduc** [comment]
Sorry for the dumb questions but which package would I need to look at to look for the url and app?

**Comment by vitorgalvao** [comment]
[`apache-directory-studio.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/apache-directory-studio.rb).

**Comment by dscoduc** [comment]
I forked it, cloned it locally, edited the URL, committed and pushed it back up to remote server...  how do I merge my fork into the actual project?

**Comment by vitorgalvao** [comment]
You don’t. You [submit a PR](https://help.github.com/articles/creating-a-pull-request/), and the team merges it.

**Comment by dscoduc** [comment]
Hmm... did I get it right?

**Comment by vitorgalvao** [comment]
Yes, it was a correct edit. However, it won’t fix the error you were getting, since that is to do with `app`.

**Comment by vitorgalvao** [comment]
Yes, it was a correct edit. However, it won’t fix the error you were getting, since that is to do with `app`. [This](https://github.com/caskroom/homebrew-cask/commit/4e05bb860f1ca1a6d949c63137c56835a3f56c79) is what was needed. Thank you for working on it, nonetheless, it was a correct contribution.

**Pull request merged**
