### PR TITLE
Add license info for Slack

### PR DESCRIPTION
**Pull request by EvanHahn**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Slack should likely be [`:gratis`, not `:freemium`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#license-stanza-details).

> They must always pertain to the license of the software itself, not the vendor's business model (a free app to access a paid service is still `:gratis`, not `:freemium`).

**Comment by EvanHahn** [comment]
@vitorgalvao Fixed.

**Comment by vitorgalvao** [comment]
Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by ndr-qef** [comment]
I took the liberty of merging as d383c29. Thanks.

**Pull request closed without merging**
