### PR TITLE
Update touchosc-bridge from 1.4.0.1 to 1.5.0

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
`1.5.0` is latest

ping @suschizu

**Comment by core-code** [comment]
try 

`url "https://hexler.net/pub/touchosc/touchosc-bridge-#{version}-macos.zip"
`

;)

**Comment by ran-dall** [comment]
I can't figuire out what's wrong with it. @vitorgalvao

**Comment by core-code** [comment]
there is trailing whitespace in the URL line:
`  url "https://hexler.net/pub/touchosc/touchosc-bridge-#{version}-macos.zip" 
`
observe the whitespace after the closing quote

**Pull request merged**
