### PR TITLE
orka: move to a subdirectory.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
We are planning on sharding homebrew/core's `Formula` directory into subdirectories. `ack` is a good first candidate:

- it's used by multiple maintainers who will notice if it's 💔
- it is not upgraded often
- it's a simple, quick install
- it's used a bit (2575th in 30d) but not loads or a little

See also (and should probably wait for being in a release) https://github.com/Homebrew/brew/pull/15811

Equivalent homebrew-core PR https://github.com/Homebrew/homebrew-core/pull/138414

### CODE REVIEW

**Comment by SMillerDev** [comment]
Seems CI can't deal with that

**Comment by MikeMcQuaid** [comment]
@SMillerDev yeh, gonna cover these issues in https://github.com/Homebrew/brew/pull/15811

**Comment by MikeMcQuaid** [comment]
If CI goes 🟢 here: feel free to merge!

**Comment by MikeMcQuaid** [comment]
(previous `brew audit` issue fixed 🎉)

**Review by miccal — APPROVED** [review]

**Pull request merged**
