### PR TITLE
Created a new cask for the LunarG Vulkan SDK v1.1.77.0.

### PR DESCRIPTION
**Pull request by apenngrace**
Created a new cask for the LunarG Vulkan SDK v1.1.77.0.

This is the first time I have tried created a cask for homebrew.  Please let me know if there is anything I need to change or fix!

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X ] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [ X] Named the cask according to the [token reference].
- [ X] `brew cask install {{cask_file}}` worked successfully.
- [ X] `brew cask uninstall {{cask_file}}` worked successfully.
- [ X] Checked there are no [open pull requests] for the same cask.
- [X ] Checked the cask was not already refused in [closed issues].
- [X ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[closed issues]: https://github.com/Homebrew/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by maddanio** [comment]
please do mege this :)

**Comment by vitorgalvao** [comment]
@apenngrace Is this open-source?

@maddanio Asking us to merge things will neither get them merged faster nor make us merge something that shouldn’t be.

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Only one instance of `caveats`, please.

Check other casks for examples.

**Comment by apenngrace** [comment]
@vitorgalvao So far, the LunarG Vulkan SDK does not appear to be completely open source.  One of the components of this SDK called [MoltenVK](https://github.com/KhronosGroup/MoltenVK) has been open-sourced recently.  On LunarG's issues site, I put in a question asking them if this SDK was open source, and I'm waiting for an answer.  So far they have been supportive of adding this formula to homebrew, they gave me the direct download url for their SDK which they don't put out publicly because they have been having issues with botnet downloads.  The URL will support 5 downloads per IP per hour.

**Comment by apenngrace** [comment]
Ok, I took a look at `caveats` on other casks and tried to match them.

**Comment by apenngrace** [comment]
@vitorgalvao Following up on your question about whether the LunarG Vulkan SDK is open source, I got this response:

> All the components within the macOS come from various open source github repositories. There isn't a single github repository that includes and builds all of the SDK components. If you look at the release notes for the macOS SDK (https://vulkan.lunarg.com/doc/sdk/1.1.77.0/mac/release_notes.html) you can see what github repositories are contributing components to the MacOS SDK.

So it sounds to me that they have a custom build process right now regarding releasing the Vulkan SDK.

**Review by vitorgalvao — APPROVED** [review]

**Comment by apenngrace** [comment]
Thank you!  Please let me know if there is anything else I need to do to merge this.  Thanks.

**Pull request merged**
