### PR TITLE
Unity 3d standard assets

### PR DESCRIPTION
**Pull request by kimegede**
## Standard Assets for Unity 3D.

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

### CODE REVIEW

**Comment by miccal** [comment]
Casks which use a `pkg` to install require an [`uninstall`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md) stanza.

**Comment by kimegede** [comment]
@miccal Updated - will just test it.

**Comment by kimegede** [comment]
@miccal uninstaller is now added and tested.

**Comment by miccal** [comment]
Thanks @kimegede.

**Comment by kimegede** [comment]
Thanks for merging! :)

**Pull request merged**
