### PR TITLE
Add Liner 0.2.0

### PR DESCRIPTION
**Pull request by aaditkamat**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

The original repository is not notable enough to pass one of the checks in the audit.

### CODE REVIEW

**Comment by khipp** [comment]
Thank you for your contribution, @aaditkamat! We only add `@beta` casks if a stable version already exists. Since the beta version appears to be the most stable, the cask should be added as `liner` instead.

With that said, do you have any additional insights into the project's status? It is still marked as beta, and the current version was released in 2022.

**Comment by aaditkamat** [comment]
> Thank you for your contribution, @aaditkamat! We only add `@beta` casks if a stable version already exists. Since the beta version appears to be the most stable, the cask should be added as `liner` instead.
> 
> With that said, do you have any additional insights into the project's status? It is still marked as beta, and the current version was released in 2022.

Not really, but I was just trying out and it seemed interesting. Feel free to close the issue if you feel necessary

**Comment by krehel** [comment]
I would position it should be hosted in your own Tap if desired.  

We accept most software, but there has been a significant influx of "AI" apps that are added and never receive updates or simply stop existing after a short while.

No updates since 2022 is a lifetime in the AI world.

**Comment by khipp** [comment]
Closing as per the above.

Feel free to resubmit this cask once development has resumed, and we would be happy to consider adding it to `homebrew-cask`.

**Pull request closed without merging**
