### PR TITLE
Add RuneLite.app 1.6.0

### PR DESCRIPTION
**Pull request by caycehouse**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars)).

**Comment by NathenSample** [comment]
@vitorgalvao That is because the repository in question is the launcher for the application, rather than the application itself.

The application this launcher is responsible for is the [Runelite third party client](https://runelite.net) for which the "main" repository can be found [here](https://github.com/runelite/runelite) (1322 stars as of posting).

The application itself is popular, it's just most people have little to no reason to interact with the launcher over the client itself.

**Comment by vitorgalvao** [comment]
@NathenSample If you don’t have the launcher, how do you run the app?

**Comment by Adam-** [comment]
I am the maintainer of this application. Maybe this is not the best thing to package due to the fact the main application is actually a launcher which downloads the real client.  The reason why he is trying to package the launcher is the game this is for forces us to do weekly client releases if we want to keep compatibility with them. If you really wanted you could package the client directly - though we do not provide that in dmg form.

Also, consider looking at download statistics to judge application usage and not just stars. The launcher has over 1m downloads on github releases.

**Comment by vitorgalvao** [comment]
> consider looking at download statistics to judge application usage and not just stars.

That’s a fair point, but the two are usually closely enough related and download statistics are more burdensome to get.

> Maybe this is not the best thing to package due to the fact the main application is actually a launcher which downloads the real client.

Yeah, this one really makes it a no go for the official repos. But you may wish to consider hosting a [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) for it.

Thank you for the insights, @Adam-.

**Pull request closed without merging**
