### PR TITLE
Revert "Add ARM version of Chromium"

### PR DESCRIPTION
**Pull request by miccal**
Reverts Homebrew/homebrew-cask#109048

### CODE REVIEW

**Comment by miccal** [comment]
Going to revert this -- the `version` numbers for the `intel` and `arm` versions are not necessarily the same, and the `livecheck` for the arm version would need to use `https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Mac_Arm%2FLAST_CHANGE?alt=media`.

Perhaps this one should be a separate Cask, like `chormium-arm` or something like that?

**Comment by miccal** [comment]
Ping @vitorgalvao and @bevanjkay for thoughts and/or ideas.

**Comment by vitorgalvao** [comment]
> Having a separate `livecheck` block for each version however would be a bad idea I think, since this Cask is already more-or-less constantly out-of-date.

The corollary might be that if the cask already lags behind, separate `livecheck` blocks might not make it worse. If a single user in each architecture commits to checking for it, it would be in great shape.

My initial reaction is that having two casks won’t make the situation better. But I’m very much open to be convinced otherwise.

The ideal solution would be to have `livecheck` and `bump-cask-pr` act on both in one swoop.

**Comment by bevanjkay** [comment]
> My initial reaction is that having two casks won’t make the situation better. But I’m very much open to be convinced otherwise.

@vitorgalvao definitely agree with this statement. A key consideration for me is portability. I understand that our primary concern probably isn't `brew bundle` but my preference would be to keeping installs consistent as much as practically possible. 

> The ideal solution would be to have `livecheck` and `bump-cask-pr` act on both in one swoop.

I think there is value in discussing this further, and perhaps implementing a solution for `livecheck` and `bump-cask-pr` to check all stanzas and update accordingly. As an aside to this, is it worth pursuing a variant or flag for `bump-cask-pr` to raise a PR with the version returned from livecheck automatically? 

I'm happy to look at opening an issue if we want to take this further.

**Pull request merged**
