### PR TITLE
adobe-dng-converter 16.3

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Trying to revert to a previous `livecheck` version. 
The server has not been returning headers to `livecheck` for some time now.

**Comment by bevanjkay** [comment]
This seems to be working but is failing the `livecheck_https_availability` audit.
There must be a mismatch somewhere in the curl logic between the `livecheck` call and the `https_availability` audit. I wonder if this is related to the issues we were having with the previous livecheck?

Any ideas here @samford?

**Review by samford — COMMENTED** [review]
Tinkering around in `Utils::Curl`, it looks like the `dng_converter_mac` URL needs both a different user agent (e.g., `:browser`) and to use a `GET` request for the server to return a response with the dmg in the `location` header. All the other combinations return a `curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)` error and the dmg isn't in the headers.

It would technically work if we added 92 to the existing special-cased exit statuses that we retry with `GET` in `#curl_headers` but there would be three failing requests before the one that works (i.e., default user agent + `HEAD`, default user agent + `GET`, `:browser` user agent + `HEAD`, then finally `:browser` user agent + `GET`), which isn't great. This seems to be unique to the adobe checks at the moment and I'm not sure that this exit status is one that makes sense to special case, so checking a different source for now (until we can manually set it to use a different user agent and `GET` in the `livecheck` block in the future) makes sense.

-----

It took some digging but `#audit_livecheck_https_availability` fails for the `uptodate.html` URL because it doesn't work with our default user agent and needs `:browser` to work. It works in livecheck because `#page_content` automatically retries with the `:browser` user agent but the audit fails because it only tries with the `:default` user agent.

A simple solution is to pass `user_agents: [:default, :browser]` to `#validate_url_for_https_availability` in `#audit_livecheck_https_availability`, to align the audit with livecheck's behavior. I'll just have to remember to remove it if/when I remove the automatic user agent retry logic in livecheck once we can specify a user agent in a `livecheck` block (I have a working implementation but I haven't had the brainpower/energy lately to wrap it up, as the PR will likely involve a lot of review/discussion).

Anyway, I'll create a brew PR for the audit change (maybe this evening) and this will be able to move forward if/when it's merged. In the interim time, I'll push a commit here to tweak this regex a bit.

**Comment by bevanjkay** [comment]
Of course all good to push here. For the regex, I had simply just reverted to an older `livecheck`. Thanks as always @samford

**Comment by samford** [comment]
I finally got around to creating a brew PR with a fix (https://github.com/Homebrew/brew/pull/17512) but there's some discussion in a brew issue (https://github.com/Homebrew/brew/issues/15350) around whether we should be switching user agents at all, so it may or may not move forward.

**Review by samford — APPROVED** [review]
The brew fix has been merged, so the livecheck audit works as expected and this passes CI now. Thanks for pointing this out, @bevanjkay.

**Review by miccal — APPROVED** [review]

**Pull request merged**
