### PR TITLE
Add opgg

### PR DESCRIPTION
**Pull request by wyq977**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version): **BETA**: 0.1.46
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

Here I added the desktop app for [OP.GG](https://na.op.gg/desktop/).

Uninstall and install works fine but I cant get audit to work nice as it throws out some errors like this

```
$ brew audit --new-cask opgg
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.6-compliant syntax, but you are running 2.6.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
audit for opgg: failed
 - exception while auditing opgg: undefined method `downcase' for nil:NilClass
Error: 1 problem in 1 cask detected
```

I looked thr and search similar error msg on github and stackoverflow and cant get it working so I was hoping to get some help here rather than opening a new issue. Pls let me know if u need any debug or verbose info. 

As for the installlation, it appears that the app is not verified (signed apple developer) so there will be a warning upon opening, not sure if this violates submission guideline. See pics below

Screen Shot 2021-02-09 at 6 47 13 PM
Screen Shot 2021-02-09 at 6 47 05 PM
Screen Shot 2021-02-09 at 3 57 38 PM

Thanks in advance

Best

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @wyq977.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

**Comment by wyq977** [comment]
You mean adding uninstall parts?

**Comment by miccal** [comment]
> You mean adding [uninstall](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md) parts?

No, I mean add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md).

**Comment by wyq977** [comment]
I added a zap trash rule using https://github.com/nrlquaker/homebrew-createzap.

**Comment by miccal** [comment]
Thank you @wyq977.

**Review by miccal — APPROVED** [review]

**Pull request merged**
