### PR TITLE
Update Firefox 66.0 to 67.0

### PR DESCRIPTION
**Pull request by LanikSJ**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

**NOTE:** This update will be _officially_ released tomorrow AM, the download is available ahead of time baring any unforeseen issues.

### CODE REVIEW

**Comment by core-code** [comment]
its out officially now

**Comment by LanikSJ** [comment]
Thank you @core-code if someone could rerun Travis we'll be in good shape.

**Comment by core-code** [comment]
AFAIK you can re-run travis by closing and re-opening the pull-request

**Comment by LanikSJ** [comment]
TIL let's see what happens. 😄

**Comment by core-code** [comment]
uhuh, even worse than before ;p is travis 'down'?

**Pull request merged**
