### PR TITLE
surge 5.0.0

### PR DESCRIPTION
**Pull request by unitof**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by razvanazamfirei — APPROVED** [review]

**Comment by unitof** [comment]
Thanks @bevanjkay! Pushed & went instantly to sleep.

**Comment by bevanjkay** [comment]
@unitof No worries. That sounds like a familiar scenario!

**Comment by cactusnix** [comment]
> Thanks @bevanjkay! Pushed & went instantly to sleep.



> Thanks @bevanjkay! Pushed & went instantly to sleep.

I downloaded from the surge mac website, it's version should be 2135, so I can't use brew install surge --cask --adopt.

**Comment by unitof** [comment]
@cactusnix Hm, not seeing that myself. Where are you seeing that version number?

The beta track is currently on build 2159: https://www.nssurge.com/mac/v5/appcast-signed-beta.xml

But the app's own [Sparkle-powered](https://sparkle-project.org) update endpoint is still on 2134: https://www.nssurge.com/mac/v5/appcast-signed.xml

**Comment by cactusnix** [comment]
@unitof I find it in my latest surge mac app, it shows me that version is 2135.
截屏2023-04-14 09 41 18

**Comment by razvanazamfirei** [comment]
From the latest version:
```xml
<dict>
	<key>CFBundleShortVersionString</key>
	<string>5.0.0</string>
</dict>
<dict>
	<key>CFBundleVersion</key>
	<string>2134</string>
</dict>
```

**Comment by cactusnix** [comment]
I downloaded it form [Surge Mac v5](https://dl.nssurge.com/mac/v5/Surge-latest.zip), and it's settings panel shows me that 5.0.0 2135

**Comment by tonyseek** [comment]
Surge Mac v5 is a paid upgrade. It requires a new license. The existed users of Surge Mac v4 will break their Surge Mac if they run `brew upgrade --cask surge` without buy a new license.

Should we keep the Surge Mac v4 in somewhere like cask-versions?

**Comment by bevanjkay** [comment]
@tonyseek you are welcome to submit a cask for `surge4` to `homebrew-cask-versions`

**Pull request merged**
