### PR TITLE
Update little-snitch from 4.6 to 5.0.1

### PR DESCRIPTION
**Pull request by core-code**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
since this requires big_sur which isn't even released yet i'd really prefer  a if/else to support older versions but i am unsure how to do that given how much has changed

**Comment by miccal** [comment]
I have updated the Catalina-and-lower version to 4.6 [here](https://github.com/Homebrew/homebrew-cask/pull/91927).

I think we should wait until Big Sur is released and officially supported by Homebrew before adding version 5.

**Comment by core-code** [comment]
fully agreed on all points, thanks for sending the updates.

**Comment by iMonZ** [comment]
For Zap:
 "/Library/StagedExtensions/Library/Extensions/LittleSnitch.kext"
This Kext is not existing anymore right?
Could you fix this please to avoid errors?

**Comment by iMonZ** [comment]
Now you can merge this request

**Comment by core-code** [comment]
@vitorgalvao @miccal since 'Big Sur' is out now should we merge this?

**Review by vitorgalvao — APPROVED** [review]

**Comment by core-code** [comment]
ouch, 5.0.1 is not available anymore it is up to 5.0.2

can't send a cask repair because as usual there are ruby issues

**Comment by core-code** [comment]
did it manually

https://github.com/Homebrew/homebrew-cask/pull/92614

**Comment by vitorgalvao** [comment]
> ouch, 5.0.1 is not available anymore it is up to 5.0.2

Even worse, just tried opening the 5.0.2 dmg manually and it says it’s corrupted. Not a great launch.

**Comment by core-code** [comment]
> Even worse, just tried opening the 5.0.2 dmg manually and it says it’s corrupted

can't really reproduce that

Apple's error messages have gone from meaningless to misleading these days

**Pull request merged**
