### PR TITLE
appium: Add zap delete stanza

### PR DESCRIPTION
**Pull request by gtmgianni**
Passes both required checks.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> Passes both required checks.

Please fill the template instead.

**Comment by giannitm** [comment]
@vitorgalvao Is there any way automatically fill in the template via the CLI when using `hub pull-request`? Or do I have to use the website instead?

**Comment by vitorgalvao** [comment]
@giannitm You’ll have to check `hub`s documentation.

You may also use `cask-repair` with the `-e` flag and do your edits. It’ll do the checks and submit with the template.

**Comment by giannitm** [comment]
Thanks @vitorgalvao.

**Pull request merged**
