### PR TITLE
Delete synergy.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
Livecheck detects a new version, yet the download with the current URL pattern does not work. Can’t verify the new one because you only have access to the downloads if you have an account, and you can only have an account if you pay.

Either someone who uses this has to fix the URL, or we have to drop the cask.

### CODE REVIEW

**Comment by i0ntempest** [comment]
I have purchased this software and there's no mention of 1.14.3 anywhere on the download page. Imo you should not livecheck synergy-core repo because a release there does not mean a release of the software will immediately follow.
There release notes pages are publicly accessible: https://symless.com/synergy/releases/synergy-1-14-2-release-notes, maybe you could livecheck this.

**Comment by vitorgalvao** [comment]
> There release notes pages are publicly accessible: https://symless.com/synergy/releases/synergy-1-14-2-release-notes, maybe you could livecheck this.

That page has the version in the URL. It is not suitable for a livecheck.

**Comment by SMillerDev** [comment]
Their releases aren't as often so it's hard to know for sure that this will be feasible, but they did post their last release on their public forum which we could check.

**Review by carlocab — APPROVED** [review]

**Comment by miccal** [comment]
@i0ntempest since you have an account for this software, can you please check if there exists a "simpler" `url` that perhaps does not include the "commit" and just uses the version number?

**Review by Tuneabq — COMMENTED** [review]
Good job!
✅

**Review by Tuneabq — COMMENTED** [review]
Awesome 😎

**Comment by i0ntempest** [comment]
I don't think so. Right now the download link on the website is: https://api2.prod.symless.com/aws-downloads/synergy/v1-core-standard/1.14.2-stable.c6918b74/synergy_1.14.2-stable.c6918b74_macos_x86-64.dmg, which I dont think is accessible unless you log in. We shall try the old url once the a new version is out, and if they do not provide new versions with the old url scheme I guess we'll have to remove it.

**Comment by i0ntempest** [comment]
bump

**Comment by carlocab** [comment]
Looks like we have to remove this, no?

**Comment by i0ntempest** [comment]
Seems like it. 1.14.3 is out, the old URL gives 403 and the new URL gives 401 unless you login.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks for the update, @i0ntempest.

**Pull request merged**
