### PR TITLE
Update megasync from 4.3.0.8 to 4.3.1.0

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Not the version they have on the app bundle, but it’s the one they have on the appcast. Seems like they might be making a mess. We’ll fix the shasum when the time comes.

**Comment by core-code** [comment]
i'll send a bug report to them immediately

**Comment by core-code** [comment]
hm there is no bug report to send because the download is obviously still at '4.3.0.8'

therefore i think updating the cask to the wrong version number is just plainly wrong. can we please not do that?

**Comment by ran-dall** [comment]
@core-code I just checked, I do have a download for this update but you're right it's still `4.3.0.8`. So I'm thinking the ML is just massively confused; I'll delete all the ML's data on this cask for it to restart the analyzation, this might fix the problem.

**Comment by core-code** [comment]
thanks there @randall ! meanwhile i'll send a PR to revert

**Pull request merged**
