### PR TITLE
zight: rename from cloudapp

### PR DESCRIPTION
**Pull request by unitof**
Revisit of #146503, now actually complete!

- zight: rename from cloudapp
- zight: add to cask_renames.json
- zight: finish rename from cloudapp
- zight: expand zap
- zight: verify URL

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by unitof** [comment]
Whaaa? Weird, it's still `CloudApp.app` after unzipping.

Their own PKG version installs as (or renames to) `Zight.app`: https://d2plwz9jdz9z5d.cloudfront.net/mac/latest/Zight.pkg

Converting to Draft for now, but anyone else welcome to dig into this.

**Comment by razvanazamfirei** [comment]
This is weird. Using the same livecheck link I get:
```rss
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>CloudApp Appcast</title>
    <description>Most recent changes with links to updates.</description>
    <link>http://downloads.getcloudapp.com/mac</link>
    <language>en</language>
    <item>
      <title>Zight 6.7 (2457)</title>
      <pubDate>Wed, 12 Apr 2023 00:00:00 +0000</pubDate>
      <enclosure url="https://d2plwz9jdz9z5d.cloudfront.net/mac/Zight-6.7.2457.zip" sparkle:version="2457" sparkle:shortVersionString="6.7" type="application/octet-stream" length="32209602"/>
    </item>
  </channel>
</rss>
```
and
```rss
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
  <channel>
    <title>CloudApp Appcast</title>
    <description>Most recent changes with links to updates.</description>
    <link>http://downloads.getcloudapp.com/mac</link>
    <language>en</language>
    <item>
      <title>CloudApp 6.6.13 (2389)</title>
      <pubDate>Thu, 02 Feb 2023 00:00:00 +0000</pubDate>
      <enclosure length="" sparkle:shortVersionString="6.6.13" sparkle:version="2389" type="application/octet-stream" url="https://d2plwz9jdz9z5d.cloudfront.net/mac/CloudApp-6.6.13.2389.zip"/>
    </item>
  </channel>
</rss>
```

**Comment by bevanjkay** [comment]
@razvanazamfirei I think upstream are still in the transition between domains/servers.,

**Comment by miccal** [comment]
Ping @unitof.

**Comment by miccal** [comment]
How I found the `url`:

1. Go to `https://share.getcloudapp.com/download`.
2. Download `https://d2plwz9jdz9z5d.cloudfront.net/mac/latest/Zight.pkg`.
3. Run `pkgutil --expand /Users/miccal/Downloads/Zight.pkg /Users/miccal/Downloads/zight`.
4. Run `strings /Users/miccal/Downloads/zight/Plugins/Installer.bundle/Contents/MacOS/Installer`.
5. In their I found the line `Downloading the latest version of Zight...` followed by two links, namely:
- `https://d2plwz9jdz9z5d.cloudfront.net/mac/builds/staging/CloudApp-6.7.2453.zip`, which is the old one with the old name, and:
- `https://d2plwz9jdz9z5d.cloudfront.net/mac/latest/Zight.zip`, which has the new name.

What a PITA.

**Comment by bevanjkay** [comment]
@miccal From what I remember when previously looking into this, the `.pkg` version just renames the app name as a part of the process
Which is where the hope of it being a proper solution in the next version came from 🙄️

It's strange that there aren't versioned binaries available yet with the rebranding, but perhaps we just merge and fix it up again if they sort it out on their end.

**Review by miccal — APPROVED** [review]

**Pull request merged**
