### PR TITLE
Update microsoft-auto-update from 4.39.21091200 to 4.40.21101001

### PR DESCRIPTION
**Pull request by eloyaldea**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Comment by eloyaldea** [comment]
Hi @miccal ! Could you help me on the comment I posted above? Sorry for the mention, I want to follow the guides I was told in the PR I mention. Thanks !

**Comment by eloyaldea** [comment]
Thanks, so whenever I want to use the `verified` option, after the `--url` flag on `brew bump-cask-pr` I write `verified: -----------` that matches the url?

**Comment by eloyaldea** [comment]
Oh I meant for the past Office updates, I wanted to change the URL because it had a download limit, and when creating the PR via `brew bump-cask-pr` I was asked to use the `verified:` option because the new URL domain didn't match with the original and I didn't know how to use said option.

**Comment by eloyaldea** [comment]
Got it, thanks!

**Pull request merged**
