### PR TITLE
Update MAMP to 3.2.1

### PR DESCRIPTION
**Pull request by ghost**
Current link returns a 404 error.

### CODE REVIEW

**Comment by radeksimko** [comment]
Thanks for noticing, but it will be necessary to update the `sha256` as well.

```
osx-10_10:~ vagrant$ brew cask install mamp
==> Downloading http://downloads.mamp.info/MAMP-PRO/releases/3.2.1/MAMP_MAMP_PRO_3.2.1.pkg
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 62d09243465007335deba5fc5a3979f0bf44695f07494216fc8fa786cdfcaf8a
Actual: 370b9b70f7b3ad7155fe84a6635366e28f277948fd15f7721b9c4aad09203a9b
File: /Library/Caches/Homebrew/mamp-3.2.1.pkg
To retry an incomplete download, remove the file above.
```

**Comment by andy-saint** [comment]
Fixed :)

**Comment by radeksimko** [comment]
Thanks, and can you please squash your two commits into one?

**Comment by andy-saint** [comment]
Sorry about this, I messed something up when rebasing (kind of new to using git). Will submit a new PR.

**Comment by facastagnini** [comment]
Just for the record, this was fixed on #10566

**Pull request closed without merging**
