### PR TITLE
Update avast-secureline-vpn: remove wildcards from `launchctl:`

### PR DESCRIPTION
**Pull request by varenc**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by varenc** [comment]
This enumerates the launchd job Avast installs since wildcards aren't working right now. (#79661).

This thing installs a lot of services. It might setup more if I actually use it, but that requires providing a credit card for a free trial.

The job `6H4HRTU5E3.com.avast.osx.secureline.avastsecurelinehelper` is an odd one.  Not sure where the id `6H4HRTU5E3` comes from but I saw it show up on two different machines and it's in a bunch of Google search results.  Though if it does vary between installs that's a very good reason for why `launchctl:` needs to support wildcards.

**Comment by varenc** [comment]
Wow. After running `cask uninstall` with my new updated Cask, Avast detected that and run `/bin/bash /Library/Application Support/AvastSecureLine/hub/autouninstall.sh` as root (somehow??). Eventually the launchd jobs I enumerated where removed, but now three new ones were installed! `com.avast.hub`, `.xpc`, and `.schedule` Presumably by this autouninstall.sh script.

Not sure what the policy is, but it's acting a bit like malware, so maybe just remove the Cask.

**Comment by varenc** [comment]
This reason for the build fail is odd:
```
Error: Some launch jobs were not unloaded, add them to uninstall launchctl:
6H4HRTU5E3.com.avast.osx.secureline.avastsecurelinehelper
com.avast.secureline.userinit
```

because those jobs are already in `uninstall launchctl:`. I suspect that the same build process for the cask currently on master would also fail in the same way?

Homebrew does run `launchctl remove <job>` and in my experience that also makes the process for the job quit, but Avast must have some unusual behavior that's preventing that.  Presumably this build passed before, but this Cask has no sha256 hash so my guess is this is new behavior. More points for 'acting a bit like malware'.

**Comment by vitorgalvao** [comment]
Nice work!

I agree their behaviour is a bit shady, but I think we should do a bit more investigating beforehand.

**Comment by varenc** [comment]
Out of curiosity I did a bit more poking around and logged all the avast related processes that start after homebrew's uninstall is triggered.

```
PID  PPID      USER     STARTED     COMMAND
33668 21239    chris     3:16PM    00:00 /bin/bash /usr/local/Homebrew/Library/Homebrew/brew.sh cask --debug uninstall avast-secureline-vpn
```
^^ this is me running cask uninstall

```
34035     1    root      3:16PM    00:00 /bin/bash /Library/Application Support/AvastSecureLine/hub/autouninstall.sh
```
^^ I think this is actually being triggered by launchd itself since the parent PID is 1. The job definition for `com.avast.secureline.uninstall` is set to keep alive no matter what as long as `/Applications/AvastSecureLine.app` still exists, so after that path stops existing, launchd startups up this job again?  This job is then responsible for all the user executions below.

```
34078 34035    root      3:16PM    00:00 /bin/bash /Library/Application Support/AvastSecureLine/hub/autouninstall.sh
34080 34078    root      3:16PM    00:00 grep /Library/Application Support/AvastSecureLine/components/update/update.sh
34554 34035    root      3:16PM    00:00 /bin/bash /Library/Application Support/AvastSecureLine/hub/uninstall.sh
34593 34554    root      3:16PM    00:00 /bin/bash /Library/Application Support/AvastSecureLine/hub/uninstall.sh
34596 34593    root      3:16PM    00:00 grep /Library/Application Support/AvastSecureLine/components/update/update.sh
34637 34554    root      3:16PM    00:01 nc -U /Library/Application Support/AvastSecureLine/run/update/502.sock
34638 23606    chris     3:16PM    00:01 /bin/bash /Library/Application Support/AvastSecureLine/hub/userinit.sh uninstall
34681 34638    chris     3:16PM    00:00 /bin/bash /Library/Application Support/AvastSecureLine/hub/userinit.sh uninstall
34736 34638    chris     3:16PM    00:00 /bin/bash /Library/Application Support/AvastSecureLine/hub/userinit.sh uninstall
34737 34736    chris     3:16PM    00:00 curl -s http://mac.sl.u.avcdn.net/macosx/avast/secureline/remoteconfig
```
^^^ This `curl` for file called `remoteconfig` file looks pretty sketchy at first...but it seems benign and is just HockeyApp related.  But even so, remote network calls triggered when a user attempts to remove software still pretty sketchy.

```
34883 34554    root      3:16PM    00:00 /bin/bash /Library/Application Support/AvastSecureLine/hub/modules/020_service.sh stop
34912 34554    root      3:16PM    00:00 /bin/bash /Library/Application Support/AvastSecureLine/hub/modules/010_burger.sh stop
34957 34554    root      3:16PM    00:01 /bin/bash /Library/Application Support/AvastSecureLine/hub/modules/020_service.sh uninstall
34959 34957    root      3:16PM    00:01 /bin/bash /Library/Application Support/AvastSecureLine/hub/modules/020_service.sh uninstall
34961 34959    root      3:16PM    00:01 grep M-VPN-AVAST
```

According to some Avast forums the only correct way to uninstall Avast is with the provided uninstaller and any attempts to do it manually will result in bad behavior.  Though the forums also claimed that AvastHUB will self-delete in a few hours after a manual uninstall...

**Pull request merged**
