### PR TITLE
Add Standard ML of New Jersey v110.91

### PR DESCRIPTION
**Pull request by k4rtik**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but this already exists as a formula (`smlnj`).

**Comment by k4rtik** [comment]
Hi @vitorgalvao, yes I am aware that it exists, but due to macOS moving to 64-bit architecture the smlnj core package is next to impossible to maintain now, it is stuck on v110.84.

I believe it's better to use the officially distributed `.pkg`as a cask instead of sources from `smlnj` (that are not moving forward in versions) to install SML/NJ compiler on macOS and hence this pull request.

**Comment by vitorgalvao** [comment]
Please point that out in `homebrew-core` beforehand, then. That software belongs there, so if it no longer fits, that needs to be discussed first.

**Comment by k4rtik** [comment]
Thanks, that's a good suggestion. I do see there is a closed issue there which is marked as an _upstream issue_ (I work with the maintainers of the upstream): https://github.com/Homebrew/homebrew-core/issues/32722

I will see if I can create a new issue to suggest migrating the formula to cask.

**Pull request closed without merging**
