### PR TITLE
Update bartender url

### PR DESCRIPTION
**Pull request by kobys8**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by ksamuel890** [comment]
It looks like the macOS 11 test was confused by the updated version number (which is in same format as prior number)

**Comment by bevanjkay** [comment]
@ksamuel890 The audit is failing because the latest version being reported by upstream is still `4.1.5,41005` - my install is saying this is the latest version in-app also.

**Comment by ksamuel890** [comment]
I believe closing this is incorrect - the checksum verification fails when trying to install from the Bartender website because it has been updated - see https://www.macbartender.com/Bartender4/blog/ and the author's latest post saying it has incremented from 4.1.5 to 4.1.6.

**Comment by bevanjkay** [comment]
@ksamuel890 The direct link to the post in question is now returning a `404` error - https://www.macbartender.com/b4blog/MacBook-Pro-Notch-Support/
So I believe that `4.1.6` has probably been removed. From what I can see the website is now returning version `4.1.7` - so I would expect the [`appcast`](https://www.macbartender.com/B2/updates/AppcastB4.xml) for Bartender to be updated shortly.

The sha256 for this cask should actually be set to `:no_check` because the download URL does not change between version.

**Comment by miccal** [comment]
@bevanjkay how did you find this `url`?

**Pull request merged**
