### PR TITLE
Update oracle-jdk-javadoc from 18 to 18.0.1

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by pthariensflame** [comment]
Seems like livecheck is being weird here?

**Comment by bevanjkay** [comment]
@pthariensflame It looks like upstream have changed the way the versions are formatted for the docs so it won't work for the livecheck anymore. We will need to find a new source for `livecheck`

**Comment by pthariensflame** [comment]
So how do we fix it, then?

**Comment by bevanjkay** [comment]
@pthariensflame Find a new source for the livecheck

**Comment by bevanjkay** [comment]
Thanks @cho-m for the fix. And thanks @pthariensflame for the bump 👍🏻

**Pull request merged**
