### PR TITLE
Formatting consistency.

### PR DESCRIPTION
**Pull request by mmhj**
Only formatted the README.md

### CODE REVIEW

**Comment by mmhj** [comment]
Not sure how the second commit failed triage.

**Comment by bevanjkay** [comment]
@mmhj We're seeing some degraded performance on the repo at the moment, it should be back to normal within a couple of hours.

**Comment by mmhj** [comment]
> @mmhj We're seeing some degraded performance on the repo at the moment, it should be back to normal within a couple of hours.

How do we resolve the triage failing for the second commit?

The changes are obviously not critical, but it seems like I can't fix it from my end.

**Comment by bevanjkay** [comment]
@mmhj We are still waiting for the degraded performance on the repo to be fixed, then a maintainer can either restart the triage, or we can force a rebase of the commits. At the moment we are still waiting for the performance issue to be resolved.

**Comment by miccal** [comment]
Thank you @mmhj.

**Pull request merged**
