### PR TITLE
Update airdisplay from 3.3.3 to 3.4.2

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by suschizu** [comment]
xcode10.1 fail: 
```
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=travis USER=travis USERNAME=travis /usr/sbin/installer -pkg /usr/local/Caskroom/airdisplay/3.4.2/Air\ Display\ Installer.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Cannot install on volume / because it is disabled.
installer: macOS High Sierra versions 10.13.4–10.13.6 are not compatible with virtual video displays. Please contact support@avatron.com for more information.
```

**Comment by miccal** [comment]
From the `homepage`:

Screen Shot 2020-07-15 at 07 21 33

**Comment by suschizu** [comment]
@miccal - oke thanks - this makes sense  … but is it possible to ignore this exception?

**Comment by miccal** [comment]
The simplest way would be to add:
```
depends_on macos: '>= :mojave'
```
but that might be a bit too restrictive?

**Comment by suschizu** [comment]
> The simplest way would be to add:
> 
> ```
> depends_on macos: '>= :mojave'
> ```
> 
> but that might be a bit too restrictive?

no I think that's the best way to solve this issue :)

**Pull request merged**
