### PR TITLE
Update qgis from 3.18.3,20210608_104042 to 3.20.0,20210618_170557

### PR DESCRIPTION
**Pull request by luispuerto**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by luispuerto** [comment]
Took me awhile to figure out how the version had to be stated…

**Comment by vicchi** [comment]
@luispuerto You beat me to it this morning! Could you possibly share the `bump-cask-pr` command you used to submit this PR as I was battling various error messages.

**Comment by cho-m** [comment]
> Took me awhile to figure out how the version had to be stated…

The easiest way for Casks with `livecheck` is to run:
```console
❯ brew livecheck qgis
qgis : 3.18.3,20210608_104042 ==> 3.20.0,20210618_170557
```

Then copy the entire portion after the arrow into the version for `brew bump-cask-pr qgis --version <copied-version>`

**Comment by luispuerto** [comment]
@vicchi 

```
$ brew bump-cask-pr qgis --version=3.20.0,20210618_170557
```

you have to state the version and them with a comma the build 😉

**Comment by vicchi** [comment]
@cho-m @luispuerto Thanks!

I was getting 

```
audit for qgis: failed
 - Use `sha256 :no_check` when URL is unversioned.
 ```

.. when I specified the the checksum and when I dropped that flag and kept `--dry-run` ...

```
Error: undefined local variable or method `remote_url' for GitHub:Module
```

**Review by cho-m — APPROVED** [review]

**Comment by luispuerto** [comment]
by the way… is there a way to install a pull request? I try to put the url fo the file and it keeps telling me that since it's not checksummed I can't install it.

**Pull request merged**
