### PR TITLE
Add Noizio v1.1

### PR DESCRIPTION
**Pull request by wmorin**

### CODE REVIEW

**Comment by ndr-qef** [comment]
The cask looks good, thanks. However, there is something we should verify before merging. The homepage features the usual “available on the Mac App Store” button, but it links to a dropbox download. Is the URL temporary?

**Comment by wmorin** [comment]
Thank you for the review. According the Twitter page, the app store account has been closed. Now, they provide a direct link. More info on https://twitter.com/noizio/status/564944568316354562

**Comment by ndr-qef** [comment]
It seems likely the Dropbox URL will be removed. The homepage states:

> Hey there. Our account is temporarily locked on the Appstore, due to the fact that it was opened in the Crimea, Ukraine. We apologize for any inconvenience. The application file is available for download from Dropbox.

There is little harm in merging, but I would expect this cask to be short-lived. Thanks, @wmorin.

**Comment by wmorin** [comment]
Thank you for the inclusion!

**Pull request merged**
