### PR TITLE
Modified README.md with better wording that should improve readabilit…

### PR DESCRIPTION
**Pull request by rasebo**
Modified README.md with better wording that should improve readability and help people not to skip key information.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but this isn’t a common issue.

Also, it changes the meaning to the wrong one. “Finally” refers to the to the list of instructions. Reporting an issue is indeed a separate part.

**Comment by rasebo** [comment]
Welcome, however it might be that it is a common behaviour and nobody thought that "finally" might actually be the issue (which would help with the high number of "fake" bugs raised). I tested it with two colleagues in the office and all three of us missed the last part and stopped at "finally".

The fact that you use the "finally" in there makes it extremely easy to skip the important part at the end, as there is no clear delimitation between the list of instructions and the category as a whole. Finally means just that something has ended, and the expectancy is that nothing after that (besides the obvious code box) is of any importance. We all just skim online text searching for keywords.

**Comment by vitorgalvao** [comment]
> I tested it with two colleagues in the office and all three of us missed the last part and stopped at "finally".

Anecdotal, but made me smile (truly), and I appreciate the effort.

I do see your point, so lets meet halfway: remove the “Finally” and have both sentences start at “If”. Unfortunately, I can’t reopen the PR (perhaps because you deleted the repository?), so if you want to submit a new one with that change, I’ll merge it.

**Comment by rasebo** [comment]
It can be difficult to provide hard evidence when it comes to behaviour. Smiling is good, so I might consider making a video next time I empirically validate something like this (no sarcasm here, really). There's nothing like watching a few definitely not dull people behaving like idiots. :)

That sounds like a good compromise. I did remove the repository, so I will fork it again and make the change. Cheers!

**Comment by vitorgalvao** [comment]
The video idea sounds fun, and good for a few laughs.

As for reforking, not sure if you know, but if you edit the file through the web interface (in this repo), it’ll take care of all that forking, branching, and the like.

**Comment by rasebo** [comment]
Ah, wasn't aware. Thanks!

**Pull request closed without merging**
