### PR TITLE
Add OpenBci v5.0.9

### PR DESCRIPTION
**Pull request by hybras**
This cask may need a livecheck stanza. [The url / filename contains the build date](https://github.com/OpenBCI/OpenBCI_GUI/issues/1024).

Verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by neutric** [comment]
Thanks for your contribution, @hybras! This was declined here / redirected to [`Homebrew/homebrew-cask-drivers`](https://github.com/Homebrew/homebrew-cask-drivers) in https://github.com/Homebrew/homebrew-cask/pull/49773 and added there in https://github.com/Homebrew/homebrew-cask-drivers/pull/476, but since then deleted. Is this still a driver as per [Acceptable-Casks.md](https://github.com/Homebrew/brew/blob/HEAD/docs/Acceptable-Casks.md#finding-a-home-for-your-cask)?

**Comment by hybras** [comment]
Yes this is a driver. Didn't realize drivers were in a seperate tap

**Comment by retiutut** [comment]
The OpenBCI GUI is a full application, the backend uses https://brainflow.org. It's not actually a driver.

**Comment by hybras** [comment]
Ok now I'm *really* confused. I don't fully understand this software, is it a driver or not? I thought it only worked with the relevant headsets? I can close this again

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @hybras.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by hybras** [comment]
Done

**Comment by miccal** [comment]
Thank you @hybras.

**Comment by retiutut** [comment]
@miccal This is a full application and not a driver. I do not think this should have been merged without the consent of myself (lead engineer on the project) or the OpenBCI team. 

This could lead to others downloaded soon to be outdated software as we regularly update this app. I discussed this with the team and we do not think it should be included in homebrew at this time.

OpenBCI users can continue to use the GUI application itself to check for updates, check our Github for this repository, or visit our website.

Thank you for understanding,
RW

**Comment by carlocab** [comment]
> I do not think this should have been merged without the consent of myself (lead engineer on the project) or the OpenBCI team.

Your software is MIT-licensed. It seems disingenuous to use an open source license on your repository but then to come here and say this, especially after you've already had the opportunity to express your opinion on this PR when you commented on it two days ago.

> This could lead others to download (soon to be) outdated software as we regularly update this app.

Software in this repository is updated in a timely manner. There are over 140,000 commits in this repository for just over 1800 casks. All bug a negligible fraction of those commits are for version updates.

This repository is also open to pull requests from anyone, so if you're that concerned about the cask shipping an outdated version, you can easily submit a pull request to update it. This can also be easily automated using, say, `brew bump-cask-pr`.

> OpenBCI users can continue to use the GUI application itself to check for updates, check our Github for this repository, or visit our website.

Users of this cask can continue to do these. Practically speaking, they are unlikely to do the latter two on a regular basis. If the latter two methods are what you're relying on for users having an up-to-date installation of your app, then they are much more likely to have outdated installations than users who rely on Homebrew Cask to keep their installations fresh.

**Comment by hybras** [comment]
I will open a pr to add `auto_updates: true`

**Comment by Andrey1994** [comment]
Hi, 

Homebrew is great and the only concern we had at OpenBCI is updating and unfortunately, we have no time to allocate for sending PRs to this repo or adding it into CI pipelines and maintaining. And we have no plans to officially use it for distribution. 

So, this
```
This repository is also open to pull requests from anyone, so if you're that concerned about the
cask shipping an outdated version, you can easily submit a pull request to update it. This can also be easily
automated using, say, brew bump-cask-pr
```
is not an option for us.

**Comment by retiutut** [comment]
>Your software is MIT-licensed. It seems disingenuous to use an open source license on your repository but then to come here and say this, especially after you've already had the opportunity to express your opinion on this PR when you commented on it two days ago.

>Ok now I'm really confused. I don't fully understand this software, is it a driver or not? I thought it only worked with the relevant headsets? I can close this again

We enjoy making open-source tools, but at the same time Github is supposed to be a place for collaboration. This PR was made and merged hastily without reaching out or collaborating with the development team as to what was really going on.

We welcome collaboration, but it should be done in a proper way and give time for others to comment and contribute. Making a PR to distribute software that someone doesn't fully understand and no other users have raised an issue about is a little weird. It would have been better to discuss this beforehand, two days and a weird GitHub issue with no explanation isn't what I would consider collaboration.

I enjoy using Home-brew for a few tools, and it's great to see that this is still being maintained.

Take Care,
RW

**Comment by hybras** [comment]
@retiutut I needed this software for a club. I though itd be convenient to make a package / cask. 

What would your team have contributed? This package downloads the github release artifact. No mirroring, no rebuilding. In fact, this package directs to openbci's homepage.

**Comment by retiutut** [comment]
> @retiutut I needed this software for a club. I though itd be convenient to make a package / cask.
> 
> What would your team have contributed? This package downloads the github release artifact. No mirroring, no rebuilding. This package directs to openbci's homepage as well.

We are here to help, but you did not give others a chance to consider how to help. We are just now hearing this from you.

**Comment by hybras** [comment]
@retiutut @Andrey1994 
OK let me enumerate ur concerns to see if i got this right.

1. Updating - Any and all existing advice about how to update, install, uninstall this software remains valid. This includes downloading the latest github release, and the in built auto update functionality. As mentioned, this cask distributes ur builds unmodified. 
2. Confusion about installation steps - [brew is not a discoverability service](https://docs.brew.sh/Acceptable-Casks#homebrew-cask-is-not-a-discoverability-service). Your users are expected to read your instructions , and homebrew in no way changes that. BTW, the website is awesome, why wouldn't anyone use it? It is not my choice whether to update macos installation instruction on ur site and *I don't care if you do*.

**Pull request merged**
