### PR TITLE
Updated RoyalTSX to version 2.0.2.1000

### PR DESCRIPTION
**Pull request by networkprogrammer**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please [amend](http://stackoverflow.com/a/179147/1661012) the commit message to include the name of the updated cask.

**Comment by fanquake** [comment]
@networkprogrammer You've only updated the name of the pull request, you need to do more than that. See @vitorgalvao's comment above.

**Comment by vitorgalvao** [comment]
@networkprogrammer Will you update this?

**Comment by networkprogrammer** [comment]
ignore, another pull request already updated the version

**Pull request closed without merging**
