### PR TITLE
add Scrolla

### PR DESCRIPTION
**Pull request by godbout**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.

UPDATE:

- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by godbout** [comment]
currently checking why the install step failed in checking that the new cask works.

**Review by p-linnane — APPROVED** [review]
Thanks @godbout!

**Comment by godbout** [comment]
@p-linnane it is me! thanks for your continuous work. (Wooshy coming soon :p)

**Comment by godbout** [comment]
@p-linnane users are reporting that Wooshy and Scrolla still don't show up in the [Homebrew page](https://brew.sh). any reason for that? is there something i'm missing somewhere? thanks.

**Comment by SMillerDev** [comment]
It's there: https://formulae.brew.sh/cask/scrolla search is done by algolia and doesn't always seem to work as people expect it.

**Comment by godbout** [comment]
thanks @SMillerDev. yes, i personally search from the `brew` command and it works fine. not sure why people go through the Homebrew page, but seems they do. thanks for the quick answer!

**Comment by lougreenwood** [comment]
@SMillerDev could you clarify what you mean by "doesn't always seem to work as people expect it"?

Seems a search engine has one expectation - find the thing they search for, I'm curious what the edge case is that the search engine can't find an exact match result?

Thanks 😊!

**Comment by SMillerDev** [comment]
Well, people make issues at the Homebrew issue trackers that they can't find things that do actually exists as pages. That's all I got. Any questions about how algolia works should probably be directed to Algolia.

**Pull request merged**
