### PR TITLE
Update santa from 0.9.33 to 1.13

### PR DESCRIPTION
**Pull request by peterlewis**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by peterlewis** [comment]
Before this gets merged, please could I ask someone with the appropriate knowledge to sanity-check it? There are a few changes with v1.0 that I'm not entirely sure about, i.e:

1. Santa.app in applications folder - I believe that the removal of this is covered with pkgutil
2. Removal of com.google.santagui
3. Addition of com.google.santa in LaunchAgents
4. Addition of com.google.santa.bundleservice in LaunchDaemons

Other than that, I've checked postinstall script and no other additional actions appear to be taken, when compared to 0.93. There's a bit more in preinstall, with regards to removal of 'cruft' from old versions, though.

**Comment by vitorgalvao** [comment]
Everything seemed to work well on CI, which looks for remnants after uninstallation. Changes are small. Let’s merge and deal with problems if they occur.

**Comment by peterlewis** [comment]
Thanks for that. If I may just ask, with regards to advising users to enable Full Disk access, following install, would a caveat be the most suitable method? I.e.:

`caveats "For Santa to utilize EndpointSecurity, it must be granted "Full Disk Access". Select the Privacy tab and grant com.google.santa.daemon.systemextension access."`

**Comment by vitorgalvao** [comment]
@peterlewis https://github.com/Homebrew/homebrew-cask/pull/84366.

**Pull request merged**
