### PR TITLE
Add Badlion Client Latest

### PR DESCRIPTION
**Pull request by julionc**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
@core-code `https://www.macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://www.badlion.net/download/client/latest/mac` should be working here, but it’s bumping into a 403. At first I thought it might be unhappy for the download to not be coming from a web browser or with some cookie, but `curl` seems to handle it.

**Comment by core-code** [comment]
i can confirm it does work fine with the CLI version of 'check_url_redirect'. 

also, it works fine with "curl" as you say.

however, it doesn't even work with "curl" on my server. i guess it is a "cloudflare" blocking issue. i see no way around that ;( 

i tried my other server but it doesn't work there either.


now the good news ... it does have an electron appcast ;)
```

$ find_appcast /Volumes/Badlion\ Client\ 2.11.1/Badlion\ Client.app 
Looking for Sparkle appcast… Not found.
Looking for HockeyApp appcast… Not found.
Looking for DevMate appcast… Not found.
Looking for electron-builder appcast… Found!
  https://client-updates.badlion.net/latest-mac.yml

```

**Comment by vitorgalvao** [comment]
Inspected the app’s plist but forgot to try the script! Thank you for the fast check.

**Comment by julionc** [comment]
```
Travis CI
audit for badlion-client: failed
202 - The URL https://www.badlion.net/ is not reachable (HTTP status code 502)
```

It seems there is an issue with the Vendor server like @core-code mention above. (Error HTTP 502 / cloudflare)

@victorpopkov I made a mistake with the last commit message. It should be 1.11.2 version.
Please, Can you squash it and merge?

**Pull request merged**
