### PR TITLE
Update onyx from 3.6.7 to 3.6.8

### PR DESCRIPTION
**Pull request by ralphrmartin**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Is this right? Mojave was using `3.6.8` before as well.

**Comment by ralphrmartin** [comment]
Not too sure, but 3.6.8 is good for 10.15.

**Comment by reitermarkus** [comment]
The website states that version 3.7.0 will be for Catalina.

> This version of OnyX will be available 10-15 days after the final version of macOS Catalina is released.

**Comment by reitermarkus** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/70307.

**Pull request closed without merging**
