### PR TITLE
Update parallels to 14.1.0-45387

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@vitorgalvao OK. I am need of your guidance. I've looked around to see if I can figure myself out (like I normally do), but I got nothing.

**Comment by core-code** [comment]
sorry i am not a travis expert and have never seen that error before. deferring to the experts ;)

**Comment by ran-dall** [comment]
@core-code Thanks for taking a look anyway...

**Comment by vitorgalvao** [comment]
```
==> Verifying SHA-256 checksum for Cask 'parallels'.
==> Installing Cask parallels
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/d20181122-35497-1iotx1t /Users/travis/Library/Caches/Homebrew/downloads/aedff9ff202bfdf350a64ad7f5e17873c093d03e5d0e6ae7ae3cd2c221938bc4--ParallelsDesktop-14.1.0-45387.dmg
mkbom -s -i /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/20181122-35497-13daw7h.list -- /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/20181122-35497-8phtqi.bom
ditto --bom /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/20181122-35497-8phtqi.bom -- /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/d20181122-35497-1iotx1t/dmg.lDSh4o /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/d20181122-35497-od7zkn
ditto: /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/d20181122-35497-od7zkn/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted
diskutil eject /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/d20181122-35497-1iotx1t/dmg.lDSh4o
==> Purging files for version 14.1.0-45387 of Cask parallels
Failure while executing; `ditto --bom /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/20181122-35497-8phtqi.bom -- /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/d20181122-35497-1iotx1t/dmg.lDSh4o /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/d20181122-35497-od7zkn` exited with 1. Here's the output:
ditto: /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/d20181122-35497-od7zkn/Parallels Desktop.app/Contents/Applications/Parallels Technical Data Reporter.app/Contents/PkgInfo: Operation not permitted
```
Ping @reitermarkus

**Pull request closed without merging**
