### PR TITLE
jenkins: add conflicts in separate stanzas for future args

### PR DESCRIPTION
**Pull request by jawshooah**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
I think I understand your thinking, here, but why would it be needed in this case? If the conflict is merely of the form “this is the same app, thought it would conflict”, they shouldn’t need further options in the future.

**Comment by jawshooah** [comment]
Right, I was thinking that we might want to implement something like Homebrew's `conflicts_with 'formula', :because => 'blah'`

**Comment by vitorgalvao** [comment]
It’s possible, but I don’t recall it ever being mentioned.

**Comment by rolandwalker** [comment]
Hi!

There is no need to change the current form.

**Comment by jawshooah** [comment]
Alright, then this is closed.

**Pull request closed without merging**
