### PR TITLE
Update wechat from 2.4.1.18 to 2.4.1.14770

### PR DESCRIPTION
**Pull request by ralphrmartin**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
I still cannot get this version from the download or the appcast. How are you getting it?

**Comment by ralphrmartin** [comment]
> On 24 May 2020, at 14:19, Vítor Galvão <notifications@github.com> wrote:
> 
> 
> I still cannot get this version from the download or the appcast. How are you getting it?

Perhaps best to ignore this. I'm not sure what the appcast version means, however.

I downloaded wechat from here:
https://mac.weixin.qq.com/
which I believe is Tencent's official URL for WeChat for the Mac

If you run the program, its about box identifies itself as

"Version 2.4.1 (14491)"

**Comment by ran-dall** [comment]
> Perhaps best to ignore this. I'm not sure what the appcast version means, however.

@ralphrmartin An `appcast` is normally a feed in which the developer indicates which versions are 'release' versions. Normally, we use these 'feeds' for verification of what's gets put in HBC. Developers sometimes have multiple versions of the same thing for multiple reasons, such as A/B testing a feature or simply just 'beta' testing a 'release' before it's made official.

**Comment by ralphrmartin** [comment]
Sorry I badly worded my remark. 
I should have said: I don't know what the last part of the appcast version refers to as in 18 in 2.4.1.18, as it is not visible to end users of the product. 
In fact, I now realise you can dig into the info.plist to see that 18.  
Clearly, I made a mistake in putting 2.4.1.14770.
So, my merge request is inappropriate.
Please cancel or delete my request (or if I have to do it, please tell me how).

**Pull request closed without merging**
