### PR TITLE
Update eqmac from 0.3.7 to 1.0.0

### PR DESCRIPTION
**Pull request by mmoole**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
According to https://github.com/bitgapp/eqMac/discussions/508, binaries are not yet available.

404 error on: https://github.com/bitgapp/eqMac/releases/download/v1.0.0/eqMac.pkg

**Comment by mmoole** [comment]
oh, whow, then something strange is happening there - downloading and sha256 was executing with success when I added the update. 
Then it seems to be better to wait a bit until this gets sorted out...

**Comment by cho-m** [comment]
I have seen the situation where download ends up grabbing 404 page as HTML, which may be what happened.

**Comment by mmoole** [comment]
actually the binary (.pkg) seems indeed to be removed, it was there just some minutes ago, now there is only those two items:
Bildschirmfoto 2021-06-24 um 19 25 16

**Comment by BenjaminHCCarr** [comment]
There was an error in the `.pkg` it was retracted and then a new version was released as GA

https://github.com/bitgapp/eqMac/discussions/508

**Review by cho-m — APPROVED** [review]
Thanks, @mmoole

**Pull request merged**
