### PR TITLE
Update brew-cask.1

### PR DESCRIPTION
**Pull request by miccal**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
The quotes we have are correct.

You should never edit this file directly. It should be generated after editing [the markdown version]( https://github.com/caskroom/homebrew-cask/blob/master/doc/man_page/brew-cask.1.md). Please correct that one instead.

**Comment by miccal** [comment]
Running `man brew-cask` via the terminal, the quotes appear as `ahelpera`?

**Comment by vitorgalvao** [comment]
> Running `man brew-cask` via the terminal, the quotes appear as `ahelpera`?

Ah, you’re right. Still, quotes should be something like `"helper"` and the fixed file should still be the markdown one.

**Comment by miccal** [comment]
OK, but how should the quotes be written so that they appear correct in Terminal?

**Comment by vitorgalvao** [comment]
`"helper"`.

**Pull request closed without merging**
