### PR TITLE
Update nvidia-geforce-now from 2.0.6.86 to 2.0.6.87

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
@suschizu this is wrong, you've updated the version but the SHA didn't change. this still contains  2.0.6.86.

@vitorgalvao any idea why this was auto-merged? changing a version without changing the SHA  is almost always wrong - except when correcting version that was wrong before. i don't think such changes should be auto-merged, since they are likely to be incorrect and need manual inspecting to see whether they are right...

**Comment by suschizu** [comment]
sorry for that - I've updated the url and the sha 
2.0.6.87 is the latest version 
https://github.com/Homebrew/homebrew-cask/pull/62765

**Comment by vitorgalvao** [comment]
> changing a version without changing the SHA is almost always wrong - except when correcting version that was wrong before. i don't think such changes should be auto-merged

Agreed. cc @reitermarkus 


> additionally, i don't think 'cask-repair -b' should go ahead in this case.

`cask-repair` makes no checks of its own, except finicky methods to detect casks it knows it can’t update (`language`, `url do`) and abort early to not screw up. Checks that later on are offloaded to `audit` and `style`.

**Comment by core-code** [comment]
ok good enough ;)

**Pull request merged**
