### PR TITLE
Added cobalt cask

### PR DESCRIPTION
**Pull request by dargonforce**
I've added a cask for Mojang's Cobalt game

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by ruseman** [comment]
Consider the commit's squashed

**Comment by vitorgalvao** [comment]
They’re not. You actually added an extra one. I’ll do it in a later PR, preserving your contribution and credit.

**Comment by vitorgalvao** [comment]
Done in #11528.

**Comment by ruseman** [comment]
Haha, I don't particularly care for credit, I just don't want to have to install cobalt the old fashioned way.  Either way, I guess I'll study up and learn to git gud

**Pull request closed without merging**
