### PR TITLE
airdash 2.0.155 (new cask)

### PR DESCRIPTION
**Pull request by FnControlOption**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

https://github.com/simonbengtsson/airdash

### CODE REVIEW

**Comment by FnControlOption** [comment]
@simonbengtsson

> audit for airdash: failed
>  - Signature verification failed:
> /private/tmp/cask-audit20240627-5879-vm1syw/AirDash.app: rejected
> 
> macOS on ARM requires software to be signed.
> Please contact the upstream developer to let them know they should sign and notarize their software.

**Comment by bevanjkay** [comment]
Thank you for the contribution @FnControlOption - closing for now, but feel free to reopen if the binaries become signed upstream.

**Comment by matthewpwatkins** [comment]
The package author added the signature to the current release. I don't have permissions to reopen @FnControlOption's PR, can someone else reopen it and rerun the signature verification? Thanks!

**Comment by bevanjkay** [comment]
It may be that the binaries are now signed but not notarized.

**Comment by krehel** [comment]
Does appear to be the case.

airdash

**Comment by matthewpwatkins** [comment]
The package author notarized his release assets. Let's try again.

**Comment by FnControlOption** [comment]
I can't reopen this PR for some reason; the button isn't there. Opened #178594

**Pull request closed without merging**
