### PR TITLE
ogdesign-eagle 3.0,41

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by krehel** [comment]
Hi team,

Some insights from your side may be helpful.  Locally this livecheck doesn't fail.  Happy to investigate if something needs to be done to make this pass.

**Comment by p-linnane** [comment]
The CI machine IP range is probably blocked from by the site. Let's rerun this without the `livecheck`.

**Review by p-linnane — APPROVED** [review]

**Comment by reitermarkus** [comment]
The livecheck fails locally for me but the URL works in a browser.

**Pull request merged**
