### PR TITLE
Update baidunetdisk from 2.2.3 to 2.2.4

### PR DESCRIPTION
**Pull request by CoolTomatos**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by iceskyzcl** [comment]
Can't open baidunetdisk 2.2.4 in macOS Catalina because mac can't check if this app is safe. I find that the newest version on baidunetdisk homepage is still 2.2.3 now? Version 2.2.3 is ok to open.

**Comment by CoolTomatos** [comment]
@iceskyzcl
Two days ago they updated the website to 2.2.4 now somehow they rolled it back. 

With either 2.2.3 or 2.2.4 you have to go the the security panel to allow the access. That’s the case for many third party Mac apps that are not from the App Store.

**Comment by iceskyzcl** [comment]
> @iceskyzcl
> Two days ago they updated the website to 2.2.4 now somehow they rolled it back.
> 
> With either 2.2.3 or 2.2.4 you have to go the the security panel to allow the access. That’s the case for many third party Mac apps that are not from the App Store.

I have allowed the access of installing the third party apps, and i can use many apps installed from brew casks, maybe version 2.2.4 has some problems?

**Comment by CoolTomatos** [comment]
@iceskyzcl
“Allow third party app” only allows apps from notarized developers by Apple. For developers not notarized, in this case baidu, you need to allow access for each single app. 
It’s had been the case since Mojave since Apple removed the option to “allow any third party app”.

**Comment by iceskyzcl** [comment]
@CoolTomatos 
Thanks. I have rolled back to 2.2.3, there's no additional access for this version in both Mojave and Catalina.

**Pull request merged**
