### PR TITLE
Update pdfelement from 6.7.12,2991 to 7.0.4,5237

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
it seems pdfelement and pdfelement-pro are the same download now. should the pdfelement-pro cask be removed or stay and be identical?

**Comment by vitorgalvao** [comment]
If it’s the same download and the same app, let’s remove one of them.

**Comment by core-code** [comment]
this one is more popular, so i guess we should remove the pro one. i'll send a pr

**Comment by core-code** [comment]
anything still missing here?

**Pull request merged**
