### PR TITLE
Update subler 1.6.11 to 1.6.12

### PR DESCRIPTION
**Pull request by JARVIS-AI**
Subler 1.6.11 to 1.6.12

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Review by JARVIS-AI — COMMENTED** [review]
`livecheck` caused differ versions

```ruby
  livecheck do
     url "https://subler.org/appcast/appcast.xml"
     strategy :sparkle
   end
```

XML is outdated 

> https://subler.org/appcast/appcast.xml

```
<title>Version 1.6.11</title>
```

This line is wrong

**Review by JARVIS-AI — COMMENTED** [review]
Fix syntax style for brew

**Review by JARVIS-AI — COMMENTED** [review]
Thanks for the regex

**Review by bevanjkay — APPROVED** [review]
Thanks @JARVIS-AI

**Pull request merged**
