### PR TITLE
snipaste 2.8.5-Beta

### PR DESCRIPTION
**Pull request by moonfruit**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — DISMISSED** [review]

**Comment by bevanjkay** [comment]
CC: @reitermarkus @samford 
This looks like it could be a side-effect of recent changes to `utils/curl`?

```
 Error: exception while auditing snipaste: undefined method `match' for ["application/json", "application/json; charset=utf-8"]:Array
```

**Comment by reitermarkus** [comment]
I guess normally `headers["content-type"]` is a string, but this seems to have two `Content-Type` headers, so it's an array.

**Comment by moonfruit** [comment]
`http -v https://www.snipaste.com/all_versions` shows this:

```http
GET /all_versions HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: www.snipaste.com
User-Agent: HTTPie/3.2.1



HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 183
Content-Type: application/json, application/json; charset=utf-8
Date: Thu, 11 May 2023 02:47:48 GMT
Server: nginx
Set-Cookie: cid=ikQ79GRcV1R2g2buJTFyAg==; expires=Thu, 31-Dec-37 23:55:55 GMT; domain=snipaste.com; path=/

{"win_store_version":"v2.8.5", "win_store_date":"2023.05.08","win_desktop_version":"v2.8.5-Beta", "win_desktop_date":"2023.05.08","mac_version":"v2.8.5-Beta", "mac_date":"2023.05.08"}
```

**Comment by razvanazamfirei** [comment]
Thanks, @moonfruit! It's an issue with 
`Content-Type: application/json, application/json; charset=utf-8` not being parsed appropriately. 

I ended up changing the `livecheck` strategy to a different source which will hopefully be more reliable.

**Review by razvanazamfirei — APPROVED** [review]

**Comment by samford** [comment]
> It's an issue with
> `Content-Type: application/json, application/json; charset=utf-8` not being parsed appropriately.

As Markus mentioned, it's because there are two `content-type` headers in a given response and [`Utils::Curl#parse_curl_response` collects duplicate headers into an array](https://github.com/Homebrew/brew/blob/32f225897e9388da44f2f55b1f1d179ed7df0af7/Library/Homebrew/utils/curl.rb#L599-L602):

```
HTTP/2 200
server: nginx
date: Thu, 11 May 2023 03:53:36 GMT
content-type: application/json
content-length: 183
content-type: application/json; charset=utf-8
set-cookie: cid=ikQ79GRcZsB2g2buJoi3Ag==; expires=Thu, 31-Dec-37 23:55:55 GMT; domain=snipaste.com; path=/

{"win_store_version":"v2.8.5", "win_store_date":"2023.05.08","win_desktop_version":"v2.8.5-Beta", "win_desktop_date":"2023.05.08","mac_version":"v2.8.5-Beta", "mac_date":"2023.05.08"}
```

This is deliberate behavior that I introduced about a year ago in Homebrew/brew#13236, as we needed to be able to handle duplicate headers instead of naively using the last instance of a given header.

Sounds like we'll have to review areas where we're working with headers and make sure that we check for and handle an array value as well.

**Pull request merged**
