### PR TITLE
Update parallels to 14.0.1-45154

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
ok this is an experiment. there are many casks where we have no appcast and there is no version information on the homepage or anywhere else at all BUT the version information is basically contained in the HTML redirect they make for their download.
normally you click on
download.dmg
but are redirected to
download.realversionnumber.dmg

i've written a CGI script and placed it on my server that returns the destination of an URL redirect.
entering this as an appcast should always yield the correct version number (unless the download URL changes)

**Comment by core-code** [comment]
i was mainly thinking about this to support @brianmorton scripts to automatically update casks. if this works with, i am all for it.

**Comment by core-code** [comment]
also, i can't get "appcast: referer" to work at least not when using cask-repair:

Error: Cask 'minecraftpe' definition is invalid: 'appcast' stanza failed with: bad argument (expected URI object or URI string)

**Comment by reitermarkus** [comment]
`appcast: :referer` isn't functional, it was merely a suggestion on how this could be officially implemented.

**Comment by core-code** [comment]
so, should we use my CGI script until another solution is actually implemented or will this be implemented soon?

there are a few other casks where the only way to get version information is from the redirect

**Comment by reitermarkus** [comment]
I don't think a dependency on a web server for this is worth it so I'd like to close this in favour of an issue for further discussion or a PR implementing `appcast: :referer` or something similar to express this behaviour.

cc @Homebrew/cask

**Comment by core-code** [comment]
i'm not sure how the dependency could hurt (except by placing load on my server) and it would be easy to replace the dependency with a different system when and if it is implemented, but ok, lets close this issue ;)

**Pull request closed without merging**
