### PR TITLE
Update synergy from 1.13.0,bdb8f767 to 1.13.1,063519a8

### PR DESCRIPTION
**Pull request by elgertam**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by reitermarkus — DISMISSED** [review]

**Comment by SMillerDev** [comment]
> appcast at URL 'https://github.com/symless/synergy-core/releases.atom' does not contain the version number '1.13.1':

**Comment by elgertam** [comment]
Looks like Symless publishes snapshot releases of Synergy quite often, and this has pushed the latest stable release off of the releases atom. I've tried to find a paging mechanism, but it seems GitHub did not implement their atom releases system that way - certainly no indication of this in the XML.

**Comment by elgertam** [comment]
I added a new URL for the appcast that includes the latest version. Should I add a comment that the next update for synergy.rb should revert it? Or is it acceptable as is?

**Comment by cho-m** [comment]
@elgertam the better option would be to replace the `appcast` with a `livecheck` section.

One option would be `:github_latest` strategy with a regex pattern for version info. This should avoid the issue with pre-release snapshots.

If you have trouble with this, one of Homebrew members can update PR. If I have time later, I can also provide an example.

**Comment by cho-m** [comment]
Taking a look at history of Cask commits, `synergy` URL format has changed multiple times.  So, it is hard to say if a `livecheck` will work in future releases (particularly for the previous version format like `"1.11.1,b207:55ec3105"`)

As for `appcast`, given the number of snapshot pre-releases and GitHub's lack of support for filtering these out on feed, it may be better to consider a different URL for maintainability.

---

### Examples of other `appcast` options

- Matching the stable releases on changelog:
   ```rb
     appcast "https://raw.githubusercontent.com/symless/synergy-core/master/ChangeLog",
             must_contain: "#{version.before_comma}-stable"
   ```
- Matching the latest GitHub release:
   ```rb
     appcast "https://github.com/symless/synergy-core/releases/latest"
   ```

---

### Example of `livecheck` that works "for now"

```rb
  livecheck do
    url "https://github.com/symless/synergy-core"
    strategy :github_latest do |page|
      version = page[%r{href=".*?/tag/v?(\d+(?:\.\d+){,2})(?:\.\d+)*-stable"}i, 1]
      commit = page[%r{href=".*?/commit/([0-9a-f]{8})[0-9a-f]*"}i, 1]
      "#{version},#{commit}"
    end
  end
```

**Comment by elgertam** [comment]
@cho-m Thank you for the help!

I ended up using your regex with one minor change: I pulled `[._-]` from the docs as the separator between the version number and "stable."

**Review by miccal — APPROVED** [review]

**Comment by miccal** [comment]
Great work here, thank you @elgertam and @cho-m.

**Pull request merged**
