### PR TITLE
Remove login items in 9 casks

### PR DESCRIPTION
**Pull request by vitorgalvao**
Following https://github.com/caskroom/homebrew-cask/issues/14854 and https://github.com/caskroom/homebrew-cask/pull/15740, adding the feature to some casks.

### CODE REVIEW

**Comment by jawshooah** [comment]
#15782 is yet to be decided, so we should probably bump the headers on these casks to v1_2 for now.

**Comment by vitorgalvao** [comment]
I always forget that.

**Comment by vitorgalvao** [comment]
I always forget that. On the other hand, we don’t implement checks yet, so increasing them isn’t actually accomplishing anything.

**Comment by vitorgalvao** [comment]
Merging now, with correct headers.

**Comment by vitorgalvao** [comment]
Merged as 6229c1adb92a8dfe60f38cadf99bd56870908ba9.

**Pull request closed without merging**
