### PR TITLE
Update Pacifist to 3.5.7

### PR DESCRIPTION
**Pull request by hanxue**

### CODE REVIEW

**Comment by hanxue** [comment]
Note: I did not update the `sha256` for appcast. How can I calculate the sha256 for appcast URL/file?

**Comment by adityadalal924** [comment]
One way is:

```
wget https://www.charlessoft.com/cgi-bin/pacifist_sparkle.cgi
shasum -a 256 pacifist_sparkle.cgi
```

**Comment by adityadalal924** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 9a3836e0564f9d9291efd4f4f600fc316b34d8ba. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by hanxue** [comment]
Thanks much for the quick merge, Aditya. Thanks also for sharing the step
on getting the sha256.

**Comment by adityadalal924** [comment]
If you are interested, https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair does all the above steps for you (install via https://github.com/vitorgalvao/homebrew-tinyscripts)

**Pull request closed without merging**
