### PR TITLE
yandex 24.10.1

### PR DESCRIPTION
**Pull request by Misaka13514**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by Misaka13514** [comment]
```
$ curl -sIXGET -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" "https://browser.yandex.ru/download/?os=mac&full=1" | grep location
location: https://download.cdn.yandex.net/browser/yandex/24_10_1_616_65930/ru/Yandex.dmg?vup=1&browser=GoogleChrome/32/130.0.0.0&banerid=6400000000:671a1523a3155aa50326a907&yandexuid=6099062721729762595&mongoID=671a1523a3155aa50326a907&pps=installID%3D6099062721729762595_1729762595437%26mongoID%3D671a1523a3155aa50326a907&hash=9bfea55bc87d40796449b0a294119860&download_date=1729762595&.exe

$ curl -sIXGET -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" "https://browser.yandex.ru/download/?os=mac&arch=arm64&full=1" | grep location
location: https://download.cdn.yandex.net/browser/yandex/24_10_1_622_65924/ru/Yandex.dmg?vup=1&browser=GoogleChrome/32/130.0.0.0&banerid=6400000000:671a1558a3155aa50326aa3c&yandexuid=9944545041729762648&mongoID=671a1558a3155aa50326aa3c&pps=installID%3D9944545041729762648_1729762648289%26mongoID%3D671a1558a3155aa50326aa3c&hash=6e0ac2327b5f93d3bc9ce775eac84f0f&download_date=1729762648&.exe

$ curl -sIXGET "https://browser.yandex.ru/download/?os=mac&full=1" | grep location
location: https://browser.yandex.ru/showcaptcha?cc=1&mt=0ACFF107980E90FA3F292DDC632B7B566A63B143DADEA9D8EB6E205FACF7EBFB8E490F34315D71821CFE46AF962FFBFC52EA41674438A0016FF0512F314B759D5A747B3DED31B68673FFFD3A9F9DE5AD6D26E874FE7FA46F7DBF9CDE550E308E2DC5F4BBA15B2B06070700678818CE628564EFE8214DF597903FEECA4B61C9EC1A9F286862CFB0CDF1636086680526B8B384DE2FAC80E6EEE6C68B895D6CAFE06E4291D065613E62CF441E6E21764844841523C01BA985FF9F262B558E3F43AE3D8C0992884C282430E1C05CE0EC2D973B19AF56F9D00ECD3D5D68D2&retpath=aHR0cHM6Ly9icm93c2VyLnlhbmRleC5ydS9kb3dubG9hZD9vcz1tYWMmZnVsbD0x_b0fc762f2b633e84b611098d3488b335&t=2/1729762658/ebde69f11a4f13b8f7644c4a49a36859&u=5401942564700198312&s=5259ae531b4daccd0369de1627c5b558
```

maybe captcha is encountered when livechecking on the GitHub Actions runner?

**Comment by khipp** [comment]
This cask has also required a few retries the last time around: https://github.com/Homebrew/homebrew-cask/pull/187641.

**Comment by Misaka13514** [comment]
I found livechecking by api will not encounter a captcha, but it will require more work to filter the version we need
API: https://api.browser.yandex.net/ab/get

**Review by khipp — APPROVED** [review]

**Comment by Misaka13514** [comment]
Thank you!

**Pull request merged**
