### PR TITLE
Update harvest to 2.1.7

### PR DESCRIPTION
**Pull request by eenick**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by eenick** [comment]
True. Appcast must not [yet] be updated for 2.1.7. 

https://www.getharvest.com/harvest/mac/release_notes.2.1.7.html

**Comment by commitay** [comment]
This is flagged by 1/57 on VirusTotal.

https://www.virustotal.com/#/file/831513173a0bc0dbdb017116d4ae91a06c597c2e0d57e6900cf67b78aa441e8e/detection

**Comment by eenick** [comment]
Good call. Hope it's a false alarm. 

As a customer of Harvest, notifying security@harvestapp.com for clarification.

**Comment by commitay** [comment]
cc @vitorgalvao 

The codesigning is valid for both so I think it might just be a flakey scan. The searching for the same match has a lot of reports of false positives.

Either way the developers to need to be contacted.

> As a customer of Harvest, notifying security@harvestapp.com for clarification.

Great, thank you!

**Comment by tjschuck** [comment]
👋 from Harvest here — @eenick did contact us, and we're looking into it!

We also believe it's a false positive.  We've contacted VirusTotal and Ikarus (the specific AV vendor that's failing the scan) to see if there's anything we can do to fix this on their end.

Thanks for your vigilance, everyone!

**Comment by commitay** [comment]
@tjschuck Can you also please confirm that the file was intentionally updated in-place?

**Comment by jorgeleria** [comment]
Hi 👋 I'm from Harvest too

> Can you also please confirm that the file was intentionally updated in-place?

I can confirm that our current build is `2.1.7 (166)` and it was pushed on purpose on July 12th.

We also got an answer from Ikarus, the false positive was removed and should not occur any more after their next database update.

Thanks a lot for the heads up on this!

**Comment by tjschuck** [comment]
And just to follow up on the earlier comments about 2.1.7 not being in our `appcast.xml` yet, it just got added today: https://www.getharvest.com/harvest/mac/appcast.xml

**Comment by alebcay** [comment]
Looks like the in-place update is confirmed as okay, VirusTotal now flags 2.1.7 (and 2.1.6) as 0/58.

**Comment by commitay** [comment]
Thanks!

**Review by commitay — APPROVED** [review]

**Pull request merged**
