### PR TITLE
captain: Remove cask

### PR DESCRIPTION
**Pull request by p-linnane**
GitHub repo has been removed, which is where downloads were being served from.

https://getcaptain.co
https://github.com/RickWong/Captain/releases

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by enavarrocu** [comment]
This is not correct. There was never a GitHub repository for this until recently. The author is releasing a new version (10.0.0). The link to the previous version is still working.

**Comment by p-linnane** [comment]
The website has no working download link since it points to GitHub. There is also no version information on the website, and only an unversioned .dmg URL. I don't believe it merits keeping this cask.

**Comment by RickWong** [comment]
> The website has no working download link since it points to GitHub. There is also no version information on the website, and only an unversioned .dmg URL. I don't believe it merits keeping this cask.

I invited you to see the new repo. Currently I'm awaiting the Apple Developer Programme approval to sign the new binaries. Not sure how long that usually takes, but will keep you posted.

**Comment by p-linnane** [comment]
@RickWong @enavarrocu Thank you both for chiming in and providing more context here. I'm happy to modify the cask for the new release and resubmit it for maintainer approval when its ready.

**Pull request closed without merging**
