### PR TITLE
Add Fantastical 2.

### PR DESCRIPTION
**Pull request by adriangoransson**

### CODE REVIEW

**Comment by andriijas** [comment]
🙌

**Comment by phinze** [comment]
Thanks for this! The license is commercial though, yeah?

**Comment by adriangoransson** [comment]
Well, there is a trial mode and when that is completed some items are
locked down. Like creating calendar entries. Reading them should still work
fine.

**Comment by phinze** [comment]
Gotchya - guess I wasn't thinking of that as "freemium", but after reading the definition again I can see how the concept applies.

I'll pull this as-is and we can discuss the semantics separately / later. :+1:

**Comment by ndr-qef** [comment]
Fantastical 2 appears to supersede the old Fantastical. We should probably update the current `fantastical` cask instead of creating a new one.

**Comment by phinze** [comment]
Ah good point @ndr-qef - I'll follow up with a PR that cleans that up.

**Comment by adriangoransson** [comment]
Fantastical2 is not backwards compatible though. It requires Yosemite which
I think justifies making it a new entry. :)

**Comment by phinze** [comment]
@adriangoransson We try not to keep versions no longer promoted by their developers in the main repo. We'll keep the 1.X series around in the `versions` tap. 

https://github.com/caskroom/homebrew-versions/commit/99767561dc9d297dcba9aa76c781a796e5357785

**Comment by adriangoransson** [comment]
Alright, seems good to me!

**Pull request merged**
