### PR TITLE
Delete Caustic App

### PR DESCRIPTION
**Pull request by gobinathm**
- App has been upgraded new version 3.2.0, but the direct download link is not valid any more.

### CODE REVIEW

**Comment by giannitm** [comment]
Found a new link @gobinathm: http://www.singlecellsoftware.com/download/Caustic_3.2.0_MacOS.dmg

**Comment by gobinathm** [comment]
@giannitm Yes that correct but it returns 404

screen shot 2017-03-27 at 12 29 08 pm

**Comment by giannitm** [comment]
@gobinathm That's strange – I also get the 404 error when I manually visit the page, however I am able to download the file by clicking on the download link...

**Comment by vitorgalvao** [comment]
@giannitm Same here. Quite weird.

**Comment by gobinathm** [comment]
@giannitm @victorpopkov  I believe the developer is now offering this app only in Mac App Store

**Comment by giannitm** [comment]
@gobinathm Yeah it seems to have migrated to the iOS App Store. Can't find any app for it on the Mac App Store.

**Review by victorpopkov — APPROVED** [review]

**Pull request merged**
