### PR TITLE
removed mavensmate.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
Can’t find the download link on the homepage and it uses a download url from a different host than the homepage. Unless someone can point to where the download url lives, we should remove this.

### CODE REVIEW

**Comment by ndr-qef** [comment]
Alternatively, we can change `url` to the GitHub host, which is suggested by http://mavensmate.com/Getting_Started/Downloads .

**Comment by vitorgalvao** [comment]
That seems to be something different than the current cask, though, as there doesn’t seem to be an app bundle in those packages.

**Comment by ndr-qef** [comment]
Quite sorry, my distraction.

**Comment by vitorgalvao** [comment]
Ah, [found something](http://mavensmate.com/Developer_Blog).



No wonder the app was nowhere to be found.

**Pull request merged**
