### PR TITLE
Add livechecks for unversioned casks.

### PR DESCRIPTION
**Pull request by reitermarkus**
Depends on https://github.com/Homebrew/brew/pull/14745 and https://github.com/Homebrew/brew/pull/14758.

### CODE REVIEW

**Comment by reitermarkus** [comment]
I think we need to tweak the audit:

```
Casks with a `livecheck` should not use `version :latest`.
```

That is true if the livecheck is actually functional, in this case there is a `skip` which is basically just documenting why `:extract_plist` cannot be used.

**Review by miccal — APPROVED** [review]

**Pull request merged**
