### PR TITLE
Update royal-tsx to 3.1.4.9

### PR DESCRIPTION
**Pull request by gobinathm**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 837fab539c863100e1e3e4a9c37b892ee1e3e29f. Your contribution is still credited to you.

**Comment by commitay** [comment]
Why does this keep [getting](https://github.com/caskroom/homebrew-cask/pull/33038) [updated](https://github.com/caskroom/homebrew-cask/pull/33065) past [`3.1.3.1000`](https://github.com/caskroom/homebrew-cask/pull/33436), which is [current](https://www.royalapplications.com/ts/osx/download)?

**Comment by vitorgalvao** [comment]
@commitay You’re right. This is the beta. Reverting.

**Comment by commitay** [comment]
@vitorgalvao PR to revert: https://github.com/caskroom/homebrew-cask/pull/33833

**Pull request closed without merging**
