### PR TITLE
Update whatroute to 2.0.12

### PR DESCRIPTION
**Pull request by SentinelWarren**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by miccal** [comment]
`brew cask style` has detected several errors with this Cask:
```
>>> brew cask style Casks/whatroute.rb
== Casks/whatroute.rb ==
C:  3:  3: Use 2 (not 1) spaces for indentation.
C:  3:  3: Tab detected.
C:  4:  3: Tab detected.
C:  5:  3: Tab detected.
C:  5:  4: Move url "https://downloads.whatroute.net/software/whatroute-#{version}.zip" out of the conditional.
C:  7:  3: Use 2 (not 1) spaces for indentation.
C:  7:  3: Tab detected.
C:  8:  3: Tab detected.
C:  9:  3: Tab detected.
C:  9:  4: Move url "https://downloads.whatroute.net/software/whatroute-#{version}.zip" out of the conditional.
```

**Comment by SentinelWarren** [comment]
@miccal what am i doing wrong?the offenses still exist!

**Comment by miccal** [comment]
@SentinelWarren the main issue it that you need to use spaces, not tabs.

I have fixed it for you - have a look at what I have done.

**Comment by SentinelWarren** [comment]
@miccal thanks bro,by the way,i think sublime should be blamed for this 😆

**Pull request merged**
