### PR TITLE
maintaining.md: new find_outdated_appcasts label

### PR DESCRIPTION
**Pull request by vitorgalvao**
Pinging @caskroom/maintainers to underline the point: **should never be applied manually**.

Currently working on the script.

### CODE REVIEW

**Comment by victorpopkov** [comment]
Understood. :+1:

**Comment by vitorgalvao** [comment]
For a bit more context, said label should only be applied by that script because I’ll later make another one that’ll loop through all the issues with said label.

**Comment by vitorgalvao** [comment]
Made some changes to the label. Still should never be applied manually, but it will also be applied to PRs.

**Comment by jawshooah** [comment]
:+1: Where are the scripts hosted? Couldn't find them in your tiny-scripts repo. Want to go ahead and open a PR to host them here? You can continue to refine them, and we can offer feedback :smile:

**Comment by vitorgalvao** [comment]
> Where are the scripts hosted?

Nowhere yet. Have been building/refining all day.

> Want to go ahead and open a PR to host them here in `developer/bin`?

Yes. These ones definitely belong in `developer/bin`, not `tiny-scripts`. I’m still finishing everything up (small tweaks here and there) and building/thinking about latter parts of the process — ideally grab all PRs with the `outdated appcasts` tag, and if they passed the build, auto-merge them; but unfortunately so far haven’t found a way to check via CLI if a Travis build has passed.

Finishing that up is basically the reason I haven’t submitted them yet (making so many changes by the minute and cutting and moving so much between them, they’re not even under version control, yet).

I’ll probably finish them tomorrow (and hopefully will find a way to do the Travis check, for the auto-merge script), and then I’d like to do a full run (only did partial ones today) to make sure everything is OK before submitting.

They’re being surprisingly straightforward and small to build, so review should be simple.

**Comment by jawshooah** [comment]
> unfortunately so far haven’t found a way to check via CLI if a Travis build has passed

`hub ci-status {{commit}}` should do the trick.

When testing the auto-merge, just to be safe, you might want to use your own fork as the source repo until you're confident it works as you expect.

**Comment by vitorgalvao** [comment]
> When testing the auto-merge, just to be safe, you might want to use your own fork as the source repo until you're confident it works as you expect.

Yes, I usually do create temporary repos to test features, specially the most annoying ones (like opening issues) until I get them right.

**Comment by adidalal** [comment]
Could also add a section to contributing, in updating a cask:

If you want to jump right in, outdated Casks are listed as issues with the "outdated appcast" label. Use cask-repair to easily submit a PR to close the issue.

**Comment by vitorgalvao** [comment]
Not really needed. I also have a script that does one better than that (which is why the label is actually useful).

**Comment by vitorgalvao** [comment]
Merging. Will submit the scripts shortly.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/18237.

**Pull request merged**
