### PR TITLE
Update radiant-player to v1.9.0

### PR DESCRIPTION
**Pull request by maticrivo**
- [ ] Commit message includes cask’s name (and new version, if applicable).
- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You need to actually run the commands.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 676781c2c0a159cbcfa527fda5bf50a5f53bd872. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by maticrivo** [comment]
@vitorgalvao thanks, and sorry, it's my first contribution here so i wasn't sure what am i supposed to do.

**Comment by vitorgalvao** [comment]
Welcome!

You’re supposed to run the given commands, substituting `{{cask_file}}` with your new modified file.

I see you likely submitted from the web interface. Those command need to be run from a terminal.

**Pull request closed without merging**
