### PR TITLE
Add Disk Arbitrator v0.5

### PR DESCRIPTION
**Pull request by realdimas**
CC @aburgh, @kainjow

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 04bbbe142d172ea8e439116f0927d86f98a8feec. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by forkbomber** [comment]
@vitorgalvao I thought launchctl uninstall was _designed_ to delete LaunchAgents .plist files as well?
At least there is a [code to clean up](../blob/master/lib/hbc/artifact/uninstall_base.rb#L215-L223) systems.

Below shouldn't be necessary anymore once uninstall_base.rb learn how to handle users' LaunchAgents:
```
  uninstall :launchctl => 'us.burghardt.Disk-Arbitrator',
            :quit => 'us.burghardt.Disk-Arbitrator',
            :delete => '~/Library/LaunchAgents/us.burghardt.Disk-Arbitrator.plist'
```

Would you suggest adding explicit :delete until :launchctl is able to delete users LaunchAgents?

**Comment by vitorgalvao** [comment]
@forkbomber You are correct. I knew we had discussed the feature, but forgot we had implemented it already.

Although in this case I can confirm (did so before making the change, and once again after your post) it doesn’t work. Pinging @jawshooah.

**Comment by forkbomber** [comment]
Moving discussion in to a separate issue #14728.

**Pull request closed without merging**
