### PR TITLE
Create qit.rb

### PR DESCRIPTION
**Pull request by hypersad**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by miccal** [comment]
The `.zip` file contains a folder called `qit-latest-mac` that itself contains the folders `bin`, `doc`, `lib` and `share` -- where do the developers recommend the folder `qit-latest-mac` be put?

**Comment by m416kar98k** [comment]
> The `.zip` file contains a folder called `qit-latest-mac` that itself contains the folders `bin`, `doc`, `lib` and `share` -- where do the developers recommend the folder `qit-latest-mac` be put?

Hi Miccal, thank you for helping on the previous Cask's upload, by the way, you could call me JoJo. It is a portable Java application which does not have a specific location as the developer shows in the video: [QIT NIIN Workshop](http://cabeen.io/qitwiki/index.php?title=WorkshopNIIN). You could find a latest JRE in the package and it is why I think it should be in Homebrew Cask, but not in Homebrew Core. The application is developed by LONI's Postdoc Ryan P. Cabeen and it is also recommended by [LONI pipeline system](https://formulae.brew.sh/cask/loni-pipeline#default). Its functionality is similar with [ITK-SNAP](https://formulae.brew.sh/cask/itk-snap).

**Comment by miccal** [comment]
> > The `.zip` file contains a folder called `qit-latest-mac` that itself contains the folders `bin`, `doc`, `lib` and `share` -- where do the developers recommend the folder `qit-latest-mac` be put?
> 
> Hi Miccal, thank you for helping on the previous Cask's upload, by the way, you could call me JoJo. It is a portable Java application which does not have a specific location as the developer shows in the video: [QIT NIIN Workshop](http://cabeen.io/qitwiki/index.php?title=WorkshopNIIN). You could find a latest JRE in the package and it is why I think it should be in Homebrew Cask, but not in Homebrew Core. The application is developed by LONI's Postdoc Ryan P. Cabeen and it is also recommended by [LONI pipeline system](https://formulae.brew.sh/cask/loni-pipeline#default). Its functionality is similar with [ITK-SNAP](https://formulae.brew.sh/cask/itk-snap).

So, putting the folder in `/Applications` would work?

**Comment by m416kar98k** [comment]
> > > The `.zip` file contains a folder called `qit-latest-mac` that itself contains the folders `bin`, `doc`, `lib` and `share` -- where do the developers recommend the folder `qit-latest-mac` be put?
> > 
> > 
> > Hi Miccal, thank you for helping on the previous Cask's upload, by the way, you could call me JoJo. It is a portable Java application which does not have a specific location as the developer shows in the video: [QIT NIIN Workshop](http://cabeen.io/qitwiki/index.php?title=WorkshopNIIN). You could find a latest JRE in the package and it is why I think it should be in Homebrew Cask, but not in Homebrew Core. The application is developed by LONI's Postdoc Ryan P. Cabeen and it is also recommended by [LONI pipeline system](https://formulae.brew.sh/cask/loni-pipeline#default). Its functionality is similar with [ITK-SNAP](https://formulae.brew.sh/cask/itk-snap).
> 
> So, putting the folder in `/Applications` would work?

Yes.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
