### PR TITLE
remote-desktop-manager-free 2023.3.7.0

### PR DESCRIPTION
**Pull request by pdcemulator**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

Also updates livecheck as old url seems outdated. New url is taked from rdm updaters latest version.

### CODE REVIEW

**Comment by pdcemulator** [comment]
Seems there is no seperate download file for cask remote-desktop-manager-free anymore.
Its using the same file as cask remote-desktop-manager, durching launch you can choose to use free version or install a license.

So I think all users should be fine using remote-desktop-manager and there is no need for remote-desktop-manager-free anymore. Please advise.

**Comment by chenrui333** [comment]
`Error: It seems the App source '/usr/local/Caskroom/remote-desktop-manager-free/2023.3.7.0/Remote Desktop Manager Free.app' is not there.`

**Comment by miccal** [comment]
Since this is now the same `url` as the `remote-desktop-manager` Cask, this should instead be marked as `discontinued`.

**Comment by miccal** [comment]
Thank you @pdcemulator.

**Review by miccal — APPROVED** [review]

**Pull request merged**
