### PR TITLE
Add Wintertime version 0.0.3

### PR DESCRIPTION
**Pull request by actuallymentor**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].

It was refused when it didn't have the required exposure. After some [reddit fame](https://www.reddit.com/r/mac/comments/b1if35/i_made_a_mac_app_that_saves_battery_by_freezing/) it now makes the 50 star requirement pointed out to me in the [previous PR](https://github.com/Homebrew/homebrew-cask/pull/60370).

- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Congrats on the quick rise!

On the technical side, why is it an Electron app? Seems a bit weird that you’re using a notoriously heavy framework to build an app to stop other heavy apps from running.

I understand what’s good about Electron apps (like the documentation!), but in this case it seems a weird choice. The interface is so simple, it could be done with AppleScript.

**Comment by actuallymentor** [comment]
> Congrats on the quick rise!

Thanks :)

> On the technical side, why is it an Electron app? Seems a bit weird that you’re using a notoriously heavy framework to build an app to stop other heavy apps from running.

Honestly, because it is what I know. I plan to add shell-only command line options to it but wanted to make sure others could use the GUI release already.

> I understand what’s good about Electron apps (like the documentation!), but in this case it seems a weird choice. The interface is so simple, it could be done with AppleScript.

True, but trying to explain how to do that to my friends usually ends in frustration :(

**Comment by vitorgalvao** [comment]
> True, but trying to explain how to do that to my friends usually ends in frustration :(

To clarify, what I mean is that you can build an app with a GUI using AppleScript alone. For example, I’ve made [`Sacar Musak`](https://github.com/vitorgalvao/sacar-musak) (an app for friends to download audio and video from websites) in about 20 lines of AppleScript.

**Comment by actuallymentor** [comment]
> > True, but trying to explain how to do that to my friends usually ends in frustration :(
> 
> To clarify, what I mean is that you can build an app with a GUI using AppleScript alone. For example, I’ve made [`Sacar Musak`](https://github.com/vitorgalvao/sacar-musak) (an app for friends to download audio and video from websites) in about 20 lines of AppleScript.

Fascinating, I had no idea that was possible. I'll for sure look into that, it would certainly be more resource efficient. Do you have favorite docs/guides that helped you understand the process?

**Comment by vitorgalvao** [comment]
> Do you have favorite docs/guides

AppleScript documentation is notoriously bad. These are the best resources I ever found:

* [Official documentation from Apple](https://developer.apple.com/library/archive/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/index.html). It includes both AppleScript and JXA.
* [JXA Cookbook](https://github.com/JXA-Cookbook/JXA-Cookbook/wiki).

If you’ve never used any of the languages, go with JXA. It’s less insane (and is JavaScript, so you’ll be more at home), but you may find less stuff online.

I’ve also bumped into [this guide](https://tylergaw.com/articles/building-osx-apps-with-js/) (seems like the website is having a few problems at the moment) a few times. But I’ve never followed the guide, so I can’t vouch for it.

**Comment by actuallymentor** [comment]
> If you’ve never used any of the languages, go with JXA. It’s less insane (and is JavaScript, so you’ll be more at home), but you may find less stuff online.

Oooh that looks exciting. Thanks for the forward!

**Pull request merged**
