### PR TITLE
clover: remove cask

### PR DESCRIPTION
**Pull request by chenrui333**
image

- https://toolfinder.co/news/clover-shutdown

----

image

### CODE REVIEW

**Comment by bevanjkay** [comment]
@chenrui333 I think we should remove this one, as it does not look to be functional anymore - existing data cannot even be exported.

Screenshot 2023-11-27 at 11 04 58 am

**Comment by chenrui333** [comment]
> @chenrui333 I think we should remove this one, as it does not look to be functional anymore - existing data cannot even be exported.
> 
> Screenshot 2023-11-27 at 11 04 58 am

totally, removing now.

**Comment by krehel** [comment]
Agreed with @bevanjkay

**Review by krehel — APPROVED** [review]

**Comment by chenrui333** [comment]
yeah, removed :)

**Pull request merged**
