### PR TITLE
Update yyets.rb

### PR DESCRIPTION
**Pull request by Loyalsoldier**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by core-code** [comment]
why revert all the recent changes? 

https://github.com/Homebrew/homebrew-cask/pull/81855

we can presume the same situation (version from website is old and immediately asks to update) will occur again in the future, no?

**Comment by Loyalsoldier** [comment]
The dmg in #81855 does not exist.

**Comment by core-code** [comment]
weird vendor. ok lets try tracking the version from the homepage again ;/

**Comment by core-code** [comment]
@fangzhengjin this PR to revert the changes from #81855 has already been commited 4 hours ago as you can see above. please do a 'brew update' and try again.

**Pull request merged**
