### PR TITLE
Cask changes for Sublime Text

### PR DESCRIPTION
**Pull request by irbrad**
- Added cask for Sublime Text 3.
- Renamed Sublime Text 2 cask to include version number in order to prevent confusion.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Sublime Text 3 is in [caskroom/versions](https://github.com/caskroom/homebrew-versions). There are numerous issues closed on this.

**Comment by irbrad** [comment]
Can I update the PR to have sublime-text in the base taproom to point to the stable build for version 3 instead of 2?  I can't find distribution statistics but a Google Trends search shows that 3 is trending more than 2: https://www.google.com/trends/explore#q=sublime%20text%202%2C%20sublime%20text%203&cmpt=q&tz=Etc%2FGMT%2B4

I understand that you don't want to have multiple versions of the same application in the root.

**Comment by vitorgalvao** [comment]
> Can I update the PR to have sublime-text in the base taproom to point to the stable build for version 3 instead of 2?

No. Version 2 is still the stable one, and more importantly is the one featured on the homepage. Consitency and predictability are important. Google search trends are meaningless, and do not represent usage.

Were the Sublime Text developers to feature version 3 as the one recommended for use, [we would change it](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#but-there-is-no-stable-version).

**Comment by irbrad** [comment]
Fair enough.  :)  Google Trends searches are fairly meaningless but they do reflect search criteria over time.  If more people are searching for it likely more people are using it.  Is there a way to get statistics from cask installs (who is installing which cask more?)?

My rationalization was that the Sublime team is putting no development time in version 2 with the last build being from just shy of two years ago today.  Version 3 has a stable build as well as the bleeding edge build.

**Comment by vitorgalvao** [comment]
> If more people are searching for it likely more people are using it.

Key word there being “likely”. We don’t know (maybe the Sublime Text team does).

> Is there a way to get statistics from cask installs

No, thankfully. There are a few (closed) issues on this.

> My rationalization was that the Sublime team is putting no development time in version 2 with the last build being from just shy of two years ago today. Version 3 has a stable build as well as the bleeding edge build.

Version 3 is also being slow as hell to update, and many people wonder for its future as well. I have no inside information as to why they still promote version 2 on the project’s homepage, but they must have their reasons.

**Comment by irbrad** [comment]
True true, wasn't meaning to start an argument or whatever or try to change your mind with my last comment.  Was just giving my rationalization for asking if the root cask should be updated.  :)

I find version 3 to be super stable but results may/will vary!

**Comment by vitorgalvao** [comment]
> wasn't meaning to start an argument or whatever or try to change your mind

Don’t worry, wasn’t taking it like that.

> I find version 3 to be super stable but results may/will vary!

So did I why I used it, but we can’t base cask rules on personal experience. The more consistent we are, the less (and better) work for maintainers and users.

**Comment by irbrad** [comment]
Can you email me about updating the epic-games-launcher cask and possibly adding another?  I don't want to spin too much in the wrong direction.  :)

brad.angelcyk@epicgames.com

**Comment by vitorgalvao** [comment]
Please open an issue (as opposed to a PR) if you have questions. That way, more people can contribute to the discussion.

**Pull request closed without merging**
