### PR TITLE
Update merlin-project to 5.0.8

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> It seems the App source '/usr/local/Caskroom/merlin-project/5.0.8/Merlin Project.app' is not there.

**Comment by ran-dall** [comment]
@vitorgalvao Yea I just reproduced. It must be a problem with the formula, cause it's currently doing it right now before the update.

**Comment by vitorgalvao** [comment]
It’s [this problem and solution](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#source-is-not-there-error).

**Comment by ran-dall** [comment]
@vitorgalvao Thanks for the lesson. I updated it. Let me know if there's anything else I can help with.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
