### PR TITLE
Boxcryptor 2.17.892

### PR DESCRIPTION
**Pull request by ondrejfuhrer**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ondrejfuhrer** [comment]
They changed the Appcast for some reason, I would suggest to wait, what happened (they removed the 2.17.892 version from appcast)

**Comment by vitorgalvao** [comment]
Let’s give it until Monday.

**Comment by ondrejfuhrer** [comment]
I just checked and it is changed again (with the latest version there), and the appcast checkpoint from my commit is valid again. Can you remove your commit?

**Comment by commitay** [comment]
> they removed the 2.17.892 version from appcast

And it's been removed again.

https://rink.hockeyapp.net/api/2/apps/7fd6db3e51a977132e3b120c613eaea8

**Comment by commitay** [comment]
The homepage and the changelog both show `2.17.892`.

The appcast versioning might be an issue with HockeyApp itself.

**Comment by ondrejfuhrer** [comment]
I asked them on twitter and the reply was:
```
Hi! 
This behavior occurs because we do staged rollouts, which means that not all users get the new updates at exactly the same time. 
Best,
Rebecca from Boxcryptor
```

Which does not make much sense, but at least we know, they consider that "normal"

**Comment by commitay** [comment]
Appcast has `2.17.892` again.

**Review by commitay — APPROVED** [review]
Verified locally.

**Pull request merged**
