### PR TITLE
libreoffice-language-pack.rb: warn about need to open LibreOffice

### PR DESCRIPTION
**Pull request by vitorgalvao**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Review by amyspark — DISMISSED** [review]
```
== Casks/libreoffice-language-pack.rb ==
C:575:  1: Layout/IndentHeredoc: Use 2 spaces for indentation in a heredoc.
C:576:  1: Layout/TrailingWhitespace: Trailing whitespace detected.
```

**Comment by commitay** [comment]
I know this is an edge case but I think if we have to start adding caveats to casks about quarantine issues we might want to reconsider having quarantine support.

**Comment by vitorgalvao** [comment]
@commitay Presumably this is an issue that’ll happen even if the users did everything manually, so I think it’s a fair exception. It’s not us causing the breakage.

**Comment by commitay** [comment]
Yes, but we are causing lots of breakage for other casks and now we're adding caveats about breakage to casks.

**Comment by tiiiecherle** [comment]
Hey, thanks for working on the issue. It was closed and I couldn`t reopen it. 

The assumption that installing the language pack before opening libreoffice when installing manually will break libreoffice, too, is wrong. It looks like an issue with the libreoffice cask.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/52758#issuecomment-427377848

**Pull request closed without merging**
