### PR TITLE
Merlin Project.app Latest

### PR DESCRIPTION
**Pull request by joniles**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

### CODE REVIEW

**Comment by miccal** [comment]
The `version` should be set to `4.0.9`.

**Comment by vitorgalvao** [comment]
> The `version` should be set to `4.0.9`.

Not in this case, because `url` is unversioned and there is no `appcast`.

**Comment by miccal** [comment]
My mistake, thanks @vitorgalvao.

**Comment by vitorgalvao** [comment]
Cask is failing `style`.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in f9e709fef880447d2f8f53aa2f2127ea32153f22. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
