### PR TITLE
Added FxFactory v7.2.6 Cask (Need Help)

### PR DESCRIPTION
**Pull request by ghost**
brew audit --new-cask <cask>
- Version '7.2.6,6943' differs from '' retrieved by livecheck.
Error: 1 problem in 1 cask detected

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x ] `brew audit --cask <cask>` is error-free.
- [ x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ x] `brew install --cask <cask>` worked successfully.
- [x ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
@lukerooneyio could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by lukerooneyio** [comment]
> @lukerooneyio could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

Hi Miccal, sorry, but it appears you removed the zap stanza and replaced it with a 'delete' stanza on line 20. I'm not sure what you'd like me to do 🤔

**Comment by miccal** [comment]
The `zap` stanza is for user-generated files, usually located in your home directory (so they start with `~/`. You will need to install this Cask and use the program to actually find them.

The files you added are system-generated, and hence should be in `uninstall` not `zap`.

**Comment by miccal** [comment]
Thank you @lukerooneyio.

**Pull request merged**
