### PR TITLE
Add Sublime Merge.app build 1058 with CLI

### PR DESCRIPTION
**Pull request by morrislaptop**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask. *
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

\* current pull request #52230 doesn't include CLI

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by yanokwa** [comment]
Might be good to also add the zap at the bottom.

```
  zap trash: [
               '~/Library/Application Support/com.apple.sharedfilelist/com.apple.LSSharedFileList.ApplicationRecentDocuments/com.sublimemerge.sfl*',
               '~/Library/Application Support/Sublime Merge',
               '~/Library/Caches/com.sublimemerge/',
               '~/Library/Preferences/com.sublimemerge.plist',
               '~/Library/Saved Application State/com.sublimemerge.savedState',
             ]
```

**Comment by morrislaptop** [comment]
Yes I don't think Sublime have code signed it, it would be similar for other apps like https://github.com/Homebrew/homebrew-cask/blob/master/Casks/gas-mask.rb

**Comment by cixtor** [comment]
@morrislaptop build 1058 has been released today [1] please update the pull-request.

[1] https://download.sublimetext.com/sublime_merge_build_1058_mac.zip

**Comment by morrislaptop** [comment]
@cixtor done

**Comment by tommyang** [comment]
To clarify my comment above. The `codesign` result above indicates that the Developer ID signature of the app is valid, _if_ extracted from zip using `ditto` or `Archive Utility` but not `unzip` (which is what `brew` [uses](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/unpack_strategy/zip.rb)). 
I performed the same check above with build 1058 zip and got the same results. 

Not sure if the problem lies in `unzip` (flags?) or how upstream packed the archive. 

----

Put that aside, might be good to add `auto_updates true` and `uninstall quit: 'com.sublimemerge'` like #52282.

**Comment by morrislaptop** [comment]
@tommyang Ahh now I understand, I'll do some digging.

**Comment by tommyang** [comment]
After some digging I see that a Homebrew maintainer recently looked into `ditto` vs `unzip` in Homebrew/brew#4621 and several related PRs. Tagging @reitermarkus for guidance.

**Comment by yanokwa** [comment]
I am unable to repro your issue, @tommyang. If I create a local cask with the contents of the PR, I am able to install and open the resulting binary with no error messages. I'm running mac OS 10.13.6 and in my Security & Privacy settings, allow apps download from "App Store and identified developers".

My brew config is as follows. Can you share yours?
```
$ brew config

HOMEBREW_VERSION: 1.7.5-63-gd44bc8b
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d44bc8be27ad37787ea9dc83f6d8377fe48c80af
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 60a233f5833dcaa5196d39ac0919eb89e394a8d2
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=/Applications
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GIT: git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MACOS_VERSION_NUMERIC: 101306
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2, 10.0.1, 9.0.4, 1.8.0_181
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11
```

@morrislaptop Might be good to update the checklist in your PR comment since #52230 is closed.

**Comment by tommyang** [comment]
@yanokwa Sure. 

#### Machine 1: Mojave 18A389
<details><summary>brew config</summary>

```
HOMEBREW_VERSION: 1.7.5-63-gd44bc8b
ORIGIN: https://github.com/Homebrew/brew
HEAD: d44bc8be27ad37787ea9dc83f6d8377fe48c80af
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 60a233f5833dcaa5196d39ac0919eb89e394a8d2
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GIT: git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MACOS_VERSION_NUMERIC: 101400
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: 10.0
XQuartz: N/A
```
</details>
<details><summary>brew cask doctor</summary>

```
==> Homebrew Version
1.7.5-63-gd44bc8b
==> macOS
10.14
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4041 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```
</details>
<details><summary>brew cask install sublime-merge --force --verbose --debug</summary>

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.sublimetext.com/sublime_merge_build_1058_mac.zip
Already downloaded: /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
/usr/bin/xattr -p com.apple.quarantine /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
==> /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip is quarantined
==> Downloaded to -> /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
==> Verifying SHA-256 checksum for Cask 'sublime-merge'.
==> Installing Cask sublime-merge
==> Cask::Installer#stage
zipinfo -1 /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
unzip /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip -d /var/folders/h8/54ydv2ns7td215pcn_t73jfh0000gn/T/d20180921-11457-17mi1o
cp -pR /var/folders/h8/54ydv2ns7td215pcn_t73jfh0000gn/T/d20180921-11457-17mi1o/Sublime\ Merge.app/. /usr/local/Caskroom/sublime-merge/1058/Sublime\ Merge.app
==> Verifying Gatekeeper status of /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
/usr/bin/xattr -p com.apple.quarantine /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
==> /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip is quarantined
==> Propagating quarantine from /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip to /usr/local/Caskroom/sublime-merge/1058
/usr/bin/xattr -p com.apple.quarantine /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
/bin/chmod -R u\+w /usr/local/Caskroom/sublime-merge/1058
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5ba5671d\;Homebrew\\x20Cask\;CAB7F22E-0742-43A5-A0FB-9717D8670308
==> Creating metadata directory /usr/local/Caskroom/sublime-merge/.metadata/1058/20180921215011.053.
==> Creating metadata subdirectory /usr/local/Caskroom/sublime-merge/.metadata/1058/20180921215011.053/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x00007f826097dc88>
==> Installing artifact of class Cask::Artifact::App
==> Moving App 'Sublime Merge.app' to '/Applications/Sublime Merge.app'.
==> Installing artifact of class Cask::Artifact::Binary
==> Linking Binary 'smerge' to '/usr/local/bin/smerge'.
/bin/ln -h -f -s -- /Applications/Sublime\ Merge.app/Contents/SharedSupport/bin/smerge /usr/local/bin/smerge
🍺  sublime-merge was successfully installed!
```
</details>

#### Machine 2: High Sierra 10.13.6
<details><summary>brew config</summary>

```
HOMEBREW_VERSION: 1.7.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d639559c4de48faad79d3ecb1ec84dc851ea66f2
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 60a233f5833dcaa5196d39ac0919eb89e394a8d2
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: 10.0
XQuartz: N/A
```
</details>
<details><summary>brew cask doctor</summary>

```
==> Homebrew Version
1.7.5
==> macOS
10.13.6
==> SIP
Enabled
==> Java
N/A
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4041 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```
</details>

<details><summary>brew cask install sublime-merge --force --verbose --debug</summary>

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.sublimetext.com/sublime_merge_build_1058_mac.zip
Already downloaded: /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
/usr/bin/xattr -p com.apple.quarantine /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
==> /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip is quarantined
==> Downloaded to -> /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
==> Verifying SHA-256 checksum for Cask 'sublime-merge'.
==> Installing Cask sublime-merge
==> Cask::Installer#stage
zipinfo -1 /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
unzip /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip -d /var/folders/10/_09th_zx2kz6z285ntwq77zr0000gn/T/d20180921-85794-5utt2p
cp -pR /var/folders/10/_09th_zx2kz6z285ntwq77zr0000gn/T/d20180921-85794-5utt2p/Sublime\ Merge.app/. /usr/local/Caskroom/sublime-merge/1058/Sublime\ Merge.app
==> Verifying Gatekeeper status of /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
/usr/bin/xattr -p com.apple.quarantine /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
==> /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip is quarantined
==> Propagating quarantine from /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip to /usr/local/Caskroom/sublime-merge/1058
/usr/bin/xattr -p com.apple.quarantine /Users/tommyang/Library/Caches/Homebrew/downloads/ca6f2ffff7463ebe64e72b830db88c9ae3e39438d78fb0d8515e5f3edb227375--sublime_merge_build_1058_mac.zip
/bin/chmod -R u\+w /usr/local/Caskroom/sublime-merge/1058
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5ba562d4\;Homebrew\\x20Cask\;E3953E51-50B3-4E9E-B9EC-C9319F86798B
==> Creating metadata directory /usr/local/Caskroom/sublime-merge/.metadata/1058/20180921214503.958.
==> Creating metadata subdirectory /usr/local/Caskroom/sublime-merge/.metadata/1058/20180921214503.958/Casks.
==> Installing artifacts
==> 4 artifact/s defined
#<SortedSet:0x00007ff2aaf54340>
==> Installing artifact of class Cask::Artifact::App
==> Moving App 'Sublime Merge.app' to '/Applications/Sublime Merge.app'.
==> Installing artifact of class Cask::Artifact::Binary
==> Linking Binary 'smerge' to '/usr/local/bin/smerge'.
/bin/ln -h -f -s -- /Applications/Sublime\ Merge.app/Contents/SharedSupport/bin/smerge /usr/local/bin/smerge
🍺  sublime-merge was successfully installed!
```
</details>

**Comment by proever** [comment]
I think this might be related to the issue @tommyang was mentioning: after running `brew cask install sublime-merge`, I get the following Gatekeeper error message: `"Sublime Merge.app” can’t be opened because it is from an unidentified developer.` Here's a screenshot of the full error message:
screen shot 2018-09-22 at 10 46 12

**Comment by piotrd** [comment]
It's not such a problem. When you open an app for the first time, just go to /Applications, right click it and click Open. You won't see that dialog next time you open the app.

**Comment by vitorgalvao** [comment]
@proever That’s expected, and it’s a security feature. See [the FAQ](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/the_app_cant_be_opened.md).

**Comment by ed-cetera** [comment]
No, it's not expected behavior. The App in the ZIP file that's referenced in the recipe is properly signed by the developers and starts without a Gatekeeper error when downloaded manually. It's definitely `brew cask install` that introduces some change triggering this problem.

**Comment by vitorgalvao** [comment]
> The App in the ZIP file that's referenced in the recipe is properly signed by the developers and starts without a Gatekeeper error when downloaded manually.

Tested on a VM, and you are correct. Pinging @amyspark.

**Pull request merged**
