### PR TITLE
Clarify this is a plugin for IE11

### PR DESCRIPTION
**Pull request by gaggle**
From its name I thought it was a desktop app, but the description on the website clarifies it is actually an IE11 plugin. The contents of `desc` here is copy-pasted from the website.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by reitermarkus** [comment]
What does this even mean? What is installed clearly isn't an IE11 plugin.

**Comment by gaggle** [comment]
> What does this even mean? What is installed clearly isn't an IE11 plugin.

Oh, sorry, I don't know what the miscommunication is then. The homepage parameter points to https://www.google.com/tools/dlpage/hangoutplugin which states it's a "Google Video Support Plugin for Internet Explorer 11". I installed this cask thinking it was an app but no app appears, so I figured it was helpful to illustrate its purpose more clearly.

I don't know where the url parameter https://dl.google.com/googletalk/googletalkplugin/GoogleVoiceAndVideoSetup.dmg comes from, but searching it results in articles [like this](https://tidbits.com/2013/03/22/how-to-set-up-and-use-google-hangouts) that describes its use as a plugin:

> Supported Web browser with the Google Talk plug-in. This should be easy, since the Google Talk plug-in (you may also see it called Google Voice and Video) works in all recent versions of Google Chrome (10+), Safari (4+), Firefox (3+), and Internet Explorer (8+). To install the plug-in, go to the Google+ Hangouts page, click the Download Plugin button, open the GoogleVoiceandVideoSetup.dmg disk image

Or am I missing the point of your comment @reitermarkus?

**Comment by reitermarkus** [comment]
> Is it just the "IE11" specific part of this commit you point out as problematic?

Yes. There is no IE11 on macOS, so having this in the description is wrong. It seems like the homepage is not pointing to what is actually being installed. I cannot find any official website pointing to this download.

**Comment by gaggle** [comment]
> > Is it just the "IE11" specific part of this commit you point out as problematic?
> 
> Yes. There is no IE11 on macOS, so having this in the description is wrong. It seems like the homepage is not pointing to what is actually being installed. I cannot find any official website pointing to this download.

Yeah I can't really find it either.

If you have any suggestions for how you'd like to manage a cask like this where we don't know what it's doing let me know, I'm happy to spend some more energy if pointed in a productive direction. Otherwise I'll just close the PR and we move on 👍

**Comment by reitermarkus** [comment]
It feels like this is some sort of legacy plugin which isn't needed anymore, might be best to remove the cask completely.

**Comment by gaggle** [comment]
> It feels like this is some sort of legacy plugin which isn't needed anymore, might be best to remove the cask completely.

Okay, if there's a process for that I can help with I'm happy to. I can't find contribution documentation for deleting casks so I'll await further instructions :)

**Comment by vitorgalvao** [comment]
I’m guessing this plugin was for all browsers, but since every major browser can now do this natively, only IE11 remains.

That, coupled with not having a proper homepage, makes it a candidate for removal.

It does have some downloads, but I’m betting those are mistakes.

> I can't find contribution documentation for deleting casks so I'll await further instructions :)

You just need to [find it on the repo](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/google-hangouts.rb) and press the trash can icon. I’ve already submitted the PR.

**Pull request closed without merging**
