### PR TITLE
clash-verge-rev 1.6.6 (new cask)

### PR DESCRIPTION
**Pull request by i0ntempest**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your submission @i0ntempest, but we cannot accept it at this time because it does not pass our signature verification check that is a requirement for new submissions:

> macOS on ARM requires software to be signed. Please contact the upstream developer to let them know they should sign and notarize their software.

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if the developers sign their app in the future we would then be happy to consider adding this to `homebrew-cask`.

**Comment by i0ntempest** [comment]
@miccal I was just going to say I'm contacting the devs and asking them to add signature: https://github.com/clash-verge-rev/clash-verge-rev/issues/1116
Can you please reopen and hold this for a bit?

**Comment by i0ntempest** [comment]
So... does HBC require a Developer ID signature now? Or was it always like this?
TBH not every developer can or wants to pay Apple $99 every year, this is pretty unfriendly to new developers... Plus there are many apps in this repo right now that are adhoc signed or not signed at all.

**Comment by i0ntempest** [comment]
Upstream has added proper code signature. Please check again.

**Comment by SMillerDev** [comment]
> TBH not every developer can or wants to pay Apple $99 every year, this is pretty unfriendly to new developers... 

The audit only checks what Apple is already enforcing on their systems, we could ignore this requirement and leave anyone who bought a mac in the last 4 years with a broken experience or we can start checking new casks for this.

You're always welcome to host software in your own tap, which has no restrictions on software inclusion and is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Review by bevanjkay — DISMISSED** [review]

**Comment by i0ntempest** [comment]
@miccal This needs to be called clash-verge-rev because clash-verge is obsolete and replaced by this. Calling this clash-verge will cause users to think this is the old archived project.

**Comment by miccal** [comment]
> @miccal This needs to be called clash-verge-rev because clash-verge is obsolete and replaced by this. Calling this clash-verge will cause users to think this is the old archived project.

I disagree.

**Comment by bevanjkay** [comment]
@miccal I would suggest that this fits under the definition of what we call a "fork".
So the token would probably need to be `clash-verge-unofficial` which I'm not particularly fond of here, or to follow the rules exactly `clash-verge-rev-clash-verge`, which is why I think `clash-verge-rev` is probably most suitable.

**Comment by miccal** [comment]
> @miccal I would suggest that this fits under the definition of what we call a "fork". 

I am well-aware what we call a "fork"; please remember that I have been a maintainer here longer than you.

> So the token would probably need to be `clash-verge-unofficial` which I'm not particularly fond of here, or to follow the token reference exactly `clash-verge-rev-clash-verge`, which is why I think `clash-verge-rev` is probably most suitable.

Again, I disagree, but life is too short to argue about such trivial things.

Do what you want: my enthusiasm for maintaining standards and consistency here in `homebrew-cask` are slowly-but-surely being whittled away by interactions such as this.

**Comment by p-linnane** [comment]
Converting to draft until we have more maintainer consensus on how to handle this. cc @Homebrew/maintainers.

**Review by MikeMcQuaid — APPROVED** [review]
I reviewed the cask and: everything about this cask source file and website screams "this is called clash-verge-rev".

> Naming does not follow the token reference.

I don't know what the token reference here is meant to be. @miccal can you please elaborate?

> or to follow the token reference exactly `clash-verge-rev-clash-verge`

If this is what the token reference says: it's clearly a terrible name and the token reference should be fixed rather than this PR.

**Review by razvanazamfirei — APPROVED** [review]
> So the token would probably need to be `clash-verge-unofficial` which I'm not particularly fond of here, or to follow the token reference exactly `clash-verge-rev-clash-verge`, which is why I think `clash-verge-rev` is probably most suitable.

I am a big fan of consistency, but we should still exercise our best judgement to avoid situations that can border on the absurd. This (`clash-verge-rev-clash-verge`) is a prime example of that. The cask token is reasonable to me.

**Comment by i0ntempest** [comment]
Upstream might change the app name in the future but it might not be "Clash Verge Rev" and certainly not anytime soon.
Anyways can we move forward on this?

**Comment by MikeMcQuaid** [comment]
@i0ntempest Yes. Thanks again for your contribution to Homebrew and your patience here, you rock!

**Comment by i0ntempest** [comment]
There's already a `depends_on` in there, don't know why it isn't picked up. I'll force push.

**Comment by bevanjkay** [comment]
CC: @EricFromCanada It looks like there may be an issue here related to the `depends_on` audit changes?

**Comment by EricFromCanada** [comment]
Just pushed an audit fix. Turns out that a cask with different SHA256 values for ARM and Intel is considered to be using on_os blocks, resulting in `@on_system_block_min_os` being blank. If so, ignore it and check the value of `depends_on macos:` instead.

**Review by MikeMcQuaid — APPROVED** [review]

**Pull request merged**
