### PR TITLE
Add Seashore.app v2.1.0

### PR DESCRIPTION
**Pull request by ahousseini**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by core-code** [comment]
did you have a look at #55467 ?

**Comment by core-code** [comment]
they passed the 20 stars now though ;)

**Comment by vitorgalvao** [comment]
> they passed the 20 stars now

We need 50.

**Comment by core-code** [comment]
ah ok thanks.
one thing that changed here though since the last discussion is that this was previously a fork, but now it is the official 'continuation' of the project, it has been blessed be the original developers and is now linked on the official homepage.
since seashore has been in cask a long time, does the star-rule still apply?

**Comment by vitorgalvao** [comment]
That does indeed change things. Let’s add it, then.

**Review by vitorgalvao — APPROVED** [review]

**Comment by core-code** [comment]
you'll want to update to 2.1.3 though ;)

**Comment by core-code** [comment]
version '2.1.3'
  sha256 'cfca508c78cd95233f3b3fe6d69c458ae963b29a00e8850f62405bea9e555302'

**Comment by core-code** [comment]
also, just for reference, the github appcast looks very fine now, but the URL the built-in update check uses is 'http://seashore.sourceforge.net/current.xml' which might be useful in the future

**Pull request merged**
