### PR TITLE
Add MiCloud 0.1.19

### PR DESCRIPTION
**Pull request by holymonson**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

---

Although the version is 0.1.19 and it mentions **beta** in [download page], it becomes public available for a long time and **should be consider as stable**. (Its windows version is 0.1.20)

[download page]: https://i.mi.com/static2?filename=MicloudWebStatic/res/home/mi-lab.htm&locale=zh_CN#3

### CODE REVIEW

**Comment by commitay** [comment]
Can't verify the `url` directly from the `homepage` but it does have a public download page.

> https://i.mi.com/static2?filename=MicloudWebStatic/res/home/mi-lab.htm&locale=zh_CN#3

**Comment by vitorgalvao** [comment]
@holymonson How do we get to that download `url` from the `homepage`, *without needing an account*?

**Comment by holymonson** [comment]
@vitorgalvao @commitay won't need an account. Please check screenshots below and pay attention to red boxes.

**Comment by commitay** [comment]
@holymonson Thanks, the english website doesn't seem to have download links.

micloud

**Review by commitay — APPROVED** [review]

**Pull request merged**
