### PR TITLE
 Remove auto_update in logseq.rb

### PR DESCRIPTION
**Pull request by peng1999**
Logseq does not have an automatic update feature. Instead, users must manually check for updates by clicking the "check for updates" button, which will direct them to the GitHub release page where they can download and install any available updates themselves.

图片

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]
Thanks @peng1999  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Review by XakV — COMMENTED** [review]
@SMillerDev @peng1999 

It appears this PR was merged on the basis that LogSeq does _not_ auto-update, however, LogSeq _does_ have that option as noted by @dericcrago in this PR https://github.com/Homebrew/homebrew-cask/pull/145213 (declined). 
Should I open another issue?
Ask @dericcrago to resubmit the PR?
Am I misunderstanding the auto_updates boolean here?
Thanks!

**Comment by conana** [comment]
Came here to add a PR for auto updates but found this discussion. As mentioned in the other PR #145213 above, logseq **does** auto update (regardless of having an additional manual update check button).

Searching Logseq project changelog shows:
image

@SMillerDev

**Comment by razvanazamfirei** [comment]
Thank you all for circling back on this! See #145213

**Pull request merged**
