### PR TITLE
Add Matterhorn 50200.6.0

### PR DESCRIPTION
**Pull request by dAnjou**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

One of the project members gave their blessing for this PR in https://github.com/matterhorn-chat/matterhorn/issues/482#issuecomment-578916122.

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This seems to be a CLI-only open-source tool. Please submit it first to [Homebrew/core](https://github.com/homebrew/homebrew-core) as a formula. Return here if not accepted (linking back to the pull request where it was refused).

This policy is documented in [faq/rejected_casks](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core) as a formula that builds from source. If it is rejected, you may then try again as a cask (link us to the issue so we can see the discussion and reasoning for rejection).

**Comment by jtdaugherty** [comment]
Greetings! I'm the maintainer for the [Matterhorn](https://github.com/matterhorn-chat/matterhorn) project that was rejected in this submission. If it's helpful, I want to comment on why building this project from source is probably not a good idea for Homebrew users, and definitely not a good idea from my perspective as the project maintainer.

Matterhorn is a Haskell project, and when Haskell projects are built from source, they fetch their dependencies in source form from public Haskell source code hosts, most commonly `hackage.haskell.org`. Those dependencies will not be in Homebrew in binary form (since it doesn't make sense to distribute binary Haskell packages in Homebrew) so a source build is the only approach possible in that case, unless Matterhorn can be distributed in binary form to avoid a source build. However, doing a source build of those dependencies means that getting a deterministic result could be tricky, because the Haskell build toolchain can select different versions of dependencies for different environments, and that would make supporting Matterhorn under those conditions onerous.

On the other hand, if we ship binaries via Homebrew, I imagine that can get tricky because Matterhorn will have runtime linking dependencies that may or may not be available in Homebrew, depending on the version of the Haskell toolchain that was used to build the program, and depending on the version of a few shared libraries that it uses.

I'm not yet entirely sure it makes sense to distribute Matterhorn via homebrew in binary form, but I am not sure that distributing it in source form will not buy Homebrew users very much. Furthermore, the development team publishes stable binary releases on a select few platforms (including Darwin hosts) but does not support an arbitrary array of build toolchain versions, which is another reason I am hesitant about making a claim that we can support source builds on Homebrew.

I'd love others to share their thoughts on the situation.

**Comment by jtdaugherty** [comment]
To summarize my previous comment, in case it isn't clear: to me, submitting to `homebrew/core` as a source package is not something I think is worth doing for the reasons I outlined, especially if the outcome (that I would want!) is for that to get rejected there.

**Comment by vitorgalvao** [comment]
I’m convinced by your arguments. Thank you for taking the time to lay them out.

**Pull request merged**
