### PR TITLE
Add Ustream Producer v6.0.6

### PR DESCRIPTION
**Pull request by scribblemaniac**
### Checklist
- [X] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:
- [X] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [X] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [X] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Did you really run the commands you checked? Because `audit` is failing with a non-trivial result. A required stanza is missing ( `license`).

**Comment by scribblemaniac** [comment]
I forgot to rerun audit after removing the license stanza. I suppose it was foolish of me to assume you could finish deprecating it in a mere 7 months. It is fixed now.

**Comment by vitorgalvao** [comment]
We haven’t even started.

We’ve done way bigger and harder things in that time (like merging with homebrew). That is simply too low priority.

Naturally, you’re welcome to take a crack at it. Any contributor can make it happen in a day.

**Comment by scribblemaniac** [comment]
True, you certainly have been up to a lot lately. Maybe I will 😉

**Pull request merged**
