### PR TITLE
Update kindavim from 45.0.0 to 2828.46.0

### PR DESCRIPTION
**Pull request by godbout**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by godbout** [comment]
thank you!

**Review by bevanjkay — DISMISSED** [review]

**Comment by p-linnane** [comment]
@godbout Give me a few minutes and I'll fix this.

**Comment by godbout** [comment]
> @godbout Give me a few minutes and I'll fix this.

thanks. honestly pushing stuff on Homebrew has never been straightforward for me. gpg signing always fails and i have to fiddle with the whole shit to get something working. a pain.

**Review by godbout — COMMENTED** [review]
🙏️

**Review by p-linnane — APPROVED** [review]

**Pull request closed without merging**
