### PR TITLE
Rename CONDUCT.md to CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by commitay**
Refs: https://github.com/Homebrew/brew/commit/a9f5c175c72c24ae13f3ffd24552a81c1c7f118f

This allows Github to detect that we have a code of conduct.

> https://github.com/caskroom/homebrew-cask/community
___

Should we add the code of conduct to the sync script?

### CODE REVIEW

**Comment by reitermarkus** [comment]
> Should we add the code of conduct to the sync script?

Yes.

**Comment by commitay** [comment]
Done.

**Review by reitermarkus — APPROVED** [review]

**Comment by vitorgalvao** [comment]
> Should we add the code of conduct to the sync script?

It seldom changes. We might add the COC to the other repos, but adding it to the sync script is unnecessary.

**Comment by vitorgalvao** [comment]
_(Should have refreshed the page before replying)_

It’s fine, then, if it’s already done.

**Pull request merged**
