### PR TITLE
Update opencore-configurator from 2.59.0.0 to 2.60.0.1

### PR DESCRIPTION
**Pull request by i0ntempest**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by i0ntempest** [comment]
The download URL is perfectly usable. Don't know what's going on with the check.

**Comment by i0ntempest** [comment]
@SMillerDev @bevanjkay Any of you could take a look at this please?

**Comment by SMillerDev** [comment]
It seems to be because cloudflare blocks Homebrew downloads. @Homebrew/cask is there a standard way to fix this?

**Comment by vitorgalvao** [comment]
A [`url` parameter](https://docs.brew.sh/Cask-Cookbook#additional-https-url-parameters) might work.

**Comment by i0ntempest** [comment]
Installing this cask using homebrew works fine on my system. It could be just blocking GitHub infrastructures.

**Comment by bevanjkay** [comment]
@SMillerDev @vitorgalvao Interesting here that CI seems to fetch the file with no issues in the `brew fetch` step however it's failing another check in the `brew audit` step regarding the URL (so probably Cloudflare). There's no shasum at the moment to check if `brew fetch` is actually grabbing a HTML page and not a file.

**Comment by samford** [comment]
I wasn't able to replicate this locally but this will likely be resolved by Homebrew/brew#13195 (i.e., the added `user_agent` argument here shouldn't be necessary and can be removed).

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
