### PR TITLE
adobe-acrobat-reader 24.002.20964

### PR DESCRIPTION
**Pull request by dalisoft**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by chenrui333** [comment]
```
 - Version '24.002.20964' differs from '24.002.20857' retrieved by livecheck.
 - Version '24.002.20964' differs from '24.002.20857' retrieved by livecheck.
 - The homepage URL https://acrobat.adobe.com/us/en/acrobat/pdf-reader.html is not reachable (HTTP status code 301)
adobe-acrobat-reader
  * Version '24.002.20964' differs from '24.002.20857' retrieved by livecheck.
  * The homepage URL https://acrobat.adobe.com/us/en/acrobat/pdf-reader.html is not reachable (HTTP status code 301)
```

**Comment by bevanjkay** [comment]
This may not receive an actual full installer. Some versions only receive patches.

**Comment by khipp** [comment]
@bevanjkay The binary seems to have the correct size ([source](https://www.adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotesDC/continuous/dccontinuousjuly2024qfe.html)). I found a corresponding `livecheck` thanks to Proxyman. ❤️

**Comment by bevanjkay** [comment]
I think we use to use that feed but changed for a reason - it's probably in the git history. I can check a bit later unless you get there first.

**Comment by dalisoft** [comment]
I found the change with git blame

https://github.com/Homebrew/homebrew-cask/pull/169567

**Comment by p-linnane** [comment]
Our livecheck is correct. If you go to Adobe's site and try to download it pulls down v24.002.20857. We can't update the cask unless Adobe ships a new installer as @bevanjkay stated.

**Comment by khipp** [comment]
The download page and livecheck version have finally been updated.

**Review by khipp — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
