### PR TITLE
Delete audacity.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
Audacity is broken *again*. This cask is a pain (see https://github.com/caskroom/homebrew-cask/pull/21952, https://github.com/caskroom/homebrew-cask/issues/15057, https://github.com/caskroom/homebrew-cask/issues/12972, https://github.com/caskroom/homebrew-cask/issues/27504, and likely others). It’s such a pain it [spawned a new feature](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#urls-that-change-on-every-visit), and yet [it still broke again](https://github.com/caskroom/homebrew-cask/issues/27504).

My opinion [stayed the same](https://github.com/caskroom/homebrew-cask/pull/23442#issuecomment-237815394):

> If an app is that difficult to get, then let it not be gettable. I vote to remove the cask altogether, if we can’t get it in a sane manner.

Pinging @SteveDaulton as [he is (was?) a member of the Audacity team](https://github.com/caskroom/homebrew-cask/issues/15057#issuecomment-155101691). I doubt they’re interested in changing their distribution mechanism, but it doesn’t hurt to ask.

Also pinging @caskroom/maintainers for opinions.

### CODE REVIEW

**Comment by shivno** [comment]
i wrote to audacity-devel and will post the results here later

**Comment by shivno** [comment]
@claui not a relevant one, and i dont expect more. i proposed to revive the sf project, which has outdated binaries. i will respond here if anything happens.

**Comment by timsutton** [comment]
Chocolatey had the [same issue recently](https://github.com/chocolatey/package-validator/wiki/ScriptsDoNotDownloadFromFossHub) with Audacity, and I've pulled my Audacity [AutoPkg recipe](https://github.com/autopkg/timsutton-recipes/commit/6d76c7ff3255639bc4d03209ce052f4d853f2d39) to comply with the fosshub [TOS](https://www.fosshub.com/tos.html). Fosshub was a huge pain to automate downloads from, anyway.

I agree with @vitorgalvao, that if the app developers choose to partner with a distribution mechanism that's hostile to automated downloads, then don't fight it. Let the people who want the app go through the proper channels to get it.

Some more background reading:

http://forum.audacityteam.org/viewtopic.php?f=50&t=94040

https://www.reddit.com/r/sysadmin/comments/5g5npg/fosshub_message_for_chocolatey_please_stop_with/

**Comment by vitorgalvao** [comment]
Thank you for the context, @timsutton, I’ve read all the links.

This part is particularly telling (emphasis added):

> FossHub is the only official download partner for Audacity.
Given that Audacity is free software, and **expenses are primarily met from advertising revenue generated by FossHub downloads** (…)

I had no idea Audacity got a share of the revenue. In that sense, I see even less incentive for them to abandon FossHub as a distribution mechanism.

Every party seems to be aware of the situation and what it means for themselves. With all the information, Audacity’s team seems to have made their choice and are happy with it, so we should honour their wishes and not distribute it in HBC.

Merging.

**Pull request merged**
