### PR TITLE
disk-sensei: fix audit error ('latest' -> :latest)

### PR DESCRIPTION
**Pull request by jawshooah**

### CODE REVIEW

**Comment by jawshooah** [comment]
Merged as fc727e8a9cb7faba61d2276e2fa94072e69b4e53.

**Comment by adityadalal924** [comment]
Whoops, I think I merged this one without looking too closely, because audit didn't complain.

`shasum` should probably also be `no_check`, because otherwise the Cask will break upon update.

**Comment by jawshooah** [comment]
> Whoops, I think I merged this one without looking too closely, because audit didn't complain.

No worries, it went right by three sets of eyes without anyone catching both problems.

> audit didn't complain

Looks like audit [did complain](https://travis-ci.org/caskroom/homebrew-cask/builds/97360071), though :stuck_out_tongue_winking_eye:

**Comment by adityadalal924** [comment]
Wow, the green checkmark must have been a phantom :D

Fixed now, anyways.

**Pull request closed without merging**
