### PR TITLE
Add foxitreader (2.4.1.0609)

### PR DESCRIPTION
**Pull request by CryoTheRenegade**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Review by commitay — APPROVED** [review]

**Comment by vitorgalvao** [comment]
@jledbetter460 Please ask about any of the changes you have questions about.

**Comment by jledbetter460** [comment]
No need. I have the mindset "If it ain't broke, there is no need to fix it."

**Comment by vitorgalvao** [comment]
> I have the mindset "If it ain't broke, there is no need to fix it."

I mean in the sense of understanding why they were made, so you know in the future.

**Comment by jledbetter460** [comment]
Yes, I do see why the changes had to be made.

**Pull request merged**
