### PR TITLE
Adobe photoshop cc

### PR DESCRIPTION
**Pull request by noranraskin**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by noranraskin** [comment]
I know there used to be a cask for photoshop and when I run `brew audit` it reports _Adobe casks were removed because they are too difficult to maintain._

But I checked and they were removed four years ago.
Since then the install and uninstall have changed and are much simpler now (as gets clear when looking at this cask)

**Comment by SMillerDev** [comment]
It fails to uninstall, so that needs to be fixed. Additionally, please write a `livecheck` and add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

**Comment by SMillerDev** [comment]
CI fails to even find the script

**Comment by gdams** [comment]
Looks like we can likely use https://helpx.adobe.com/photoshop/kb/fixed-issues.html for the livecheck URL

**Comment by vitorgalvao** [comment]
My position on Adobe casks is “remove them when they break, never add them again”. Adobe is one of the most user hostile companies ever and their casks have been a constant source of headaches. **They can’t even release fonts right!** There’s a not-too-old issue in the fonts repo about it.

Heed the warning: add Adobe casks now, regret it later. Every single HBC maintainer who had to deal with Adobe casks before the removal would tell you the same.

The only way I’d ever consider an Adobe cask a good idea would be if installing it would mean the `app` stanza. An even then I’d have my reservations about what they did to screw that up.

**Comment by vitorgalvao** [comment]
Better yet, contribute to @danielbayley’s tap: https://github.com/danielbayley/homebrew-adobe

**Comment by noranraskin** [comment]
Thank you all for the input, I'm just getting started with ruby and will try a bit more, and maybe put it into my own tap (or @danielbayley's )

**Pull request closed without merging**
