### PR TITLE
Create dockutil.rb

### PR DESCRIPTION
**Pull request by mofneko**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Thank you for your submission @mofneko but `dockutil` is already available in [`homebrew-core`](github.com/homebrew/homebrew-core)

**Comment by mofneko** [comment]
But core is not the latest version.

**Comment by bevanjkay** [comment]
Then the formula should be updated in `homebrew-core` to be the latest version.

**Comment by mofneko** [comment]
Since dockutil is provided in pkg format, it is appropriate to provide it in cask.

**Comment by bevanjkay** [comment]
See cask docs here regarding rejected casks - https://docs.brew.sh/Acceptable-Casks#rejected-casks

> App is both open-source and CLI-only (i.e. it only uses the binary artifact). In that case, and in the spirit of deduplication, submit it first to homebrew/core as a formula that builds from source. If it is rejected, you may then try again as a cask (link to the issue from your pull request so we can see the discussion and reasoning for rejection).

**Comment by mofneko** [comment]
https://github.com/Homebrew/homebrew-core/pull/132838
I also created a PR for core.
If rejected here, please consider merging into cask.

**Comment by chenrui333** [comment]
> [Homebrew/homebrew-core#132838](https://github.com/Homebrew/homebrew-core/pull/132838) I also created a PR for core. If rejected here, please consider merging into cask.

it can be submitted into core, but it has to be built from source

**Comment by mofneko** [comment]
After all, since the official is provided as pkg, I think that it is correct to distribute it with cask.
In that case, core packages will issue a PR for removal.
do you agree with my idea?

**Comment by bevanjkay** [comment]
@mofneko Because the submission is for an open source CLI package, it should be submitted to `homebrew-core` and built from source regardless of how it is packaged for distribution by upstream.

**Comment by p-linnane** [comment]
See also:
https://github.com/Homebrew/homebrew-cask/pull/125996
https://github.com/Homebrew/homebrew-cask/pull/135196

We will not be accepting this into `homebrew-cask`.

**Pull request closed without merging**
