### PR TITLE
Update omnidb to 2.6.0

### PR DESCRIPTION
**Pull request by mnencia**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by mnencia** [comment]
This is a checksum only change. I've double checked the checksum and the one in the current cask is wrong.

**Comment by commitay** [comment]
cc @vitorgalvao 

> https://www.virustotal.com/#/file/ab8d147d57a0bd20bb47e4f8e791c4979ef5c1da4f3f6320d40c89f217bc3973/details

VirusTotal says "invalid" despite all 3 signers being "valid".

Locally I get:

```
$ sha omnidb--2.6.0.dmg
ab8d147d57a0bd20bb47e4f8e791c4979ef5c1da4f3f6320d40c89f217bc3973  omnidb--2.6.0.dmg

$ spctl --assess --verbose /Volumes/OmniDB\ Installer/OmniDB.app
/Volumes/OmniDB Installer/OmniDB.app: accepted
source=Developer ID

$ codesign -vv /Volumes/OmniDB\ Installer/OmniDB.app
/Volumes/OmniDB Installer/OmniDB.app: valid on disk
/Volumes/OmniDB Installer/OmniDB.app: satisfies its Designated Requirement

$ codesign -dvv /Volumes/OmniDB\ Installer/OmniDB.app
Executable=/Volumes/OmniDB Installer/OmniDB.app/Contents/MacOS/omnidb-app
Identifier=OmniDB
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=37190 flags=0x0(none) hashes=1157+3 location=embedded
Signature size=8918
Authority=Developer ID Application: 2ndQuadrant Ltd (A4RW3NYRBU)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=19 Mar 2018 at 01:40:13
Info.plist entries=10
TeamIdentifier=A4RW3NYRBU
Sealed Resources version=2 rules=13 files=4021
Internal requirements count=1 size=168
```

**Comment by mnencia** [comment]
I contacted one of the OImniDB developers and he said the issue is that the DMG is not signed.
So he did another round of upload. I'll update the pull request.

**Comment by commitay** [comment]
Thanks @mnencia

VirusTotal still has same "invalid" and I get "valid" locally. I think this might be a problem with VirusTotal.

@vitorgalvao Are you okay with merging this and the VirusTotal warning?

> https://www.virustotal.com/#/file/cabc276e8aef6ead6dff87e038bd317662c1a8d3809746d3e5ea0f3dfd70ca39/details
```
$ sha omnidb-app_2.6.0-mac.dmg
cabc276e8aef6ead6dff87e038bd317662c1a8d3809746d3e5ea0f3dfd70ca39  omnidb-app_2.6.0-mac.dmg

$ spctl --assess --verbose /Volumes/OmniDB\ Installer/OmniDB.app
/Volumes/OmniDB Installer/OmniDB.app: accepted
source=Developer ID

$ codesign -vv /Volumes/OmniDB\ Installer/OmniDB.app
/Volumes/OmniDB Installer/OmniDB.app: valid on disk
/Volumes/OmniDB Installer/OmniDB.app: satisfies its Designated Requirement

$ codesign -dvv /Volumes/OmniDB\ Installer/OmniDB.app
Executable=/Volumes/OmniDB Installer/OmniDB.app/Contents/MacOS/omnidb-app
Identifier=OmniDB
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=37190 flags=0x0(none) hashes=1157+3 location=embedded
Signature size=8918
Authority=Developer ID Application: 2ndQuadrant Ltd (A4RW3NYRBU)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=19 Mar 2018 at 01:40:13
Info.plist entries=10
TeamIdentifier=A4RW3NYRBU
Sealed Resources version=2 rules=13 files=4021
Internal requirements count=1 size=168
```

**Comment by mnencia** [comment]
@rafaelthca this is the issue. Please help understanding if this is an issue in the dmg file or it is a virtustotal.com issue.

**Comment by mnencia** [comment]
@rafaelthca has rebuilt the package from scratch, and now virustotal says it's ok.

https://www.virustotal.com/#/file/721160ae4e0385597f03600adc71ca741f23a506c08fb8a46b27ec717ae9ac12/details

**Review by commitay — APPROVED** [review]

**Comment by commitay** [comment]
Thanks @mnencia and @rafaelthca!

**Comment by vitorgalvao** [comment]
Seems like I wasn’t needed at all! Thank you all for getting this sorted so quickly.

**Pull request merged**
