### PR TITLE
Add Spitfire Audio v3.2.16

### PR DESCRIPTION
**Pull request by mariobrostech**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

I'm a complete newbie at contributing to larger projects like Homebrew, so this is all very foreign to me. If someone can guide me through naming the cask according to the token reference, I'm more than happy to do so. Also, if someone is able to add (or guide me through adding) `brew cask zap` parameters to this cask, I'd really appreciate it. Thanks for your consideration!

### CODE REVIEW

**Comment by miccal** [comment]
> I'm a complete newbie at contributing to larger projects like Homebrew, so this is all very foreign to me. If someone can guide me through naming the cask according to the token reference, I'm more than happy to do so. 

You have named the Cask perfectly as per the token reference, thank you.

> Also, if someone is able to add (or guide me through adding) `brew cask zap` parameters to this cask, I'd really appreciate it. Thanks for your consideration!

[The `zap` stanza documentation](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md) should help with adding a `zap`, but feel free to ask for some help if you need it.

**Comment by mariobrostech** [comment]
> > I'm a complete newbie at contributing to larger projects like Homebrew, so this is all very foreign to me. If someone can guide me through naming the cask according to the token reference, I'm more than happy to do so.
> 
> You have named the Cask perfectly as per the token reference, thank you.
> 
> > Also, if someone is able to add (or guide me through adding) `brew cask zap` parameters to this cask, I'd really appreciate it. Thanks for your consideration!
> 
> [The `zap` stanza documentation](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md) should help with adding a `zap`, but feel free to ask for some help if you need it.

@miccal Thanks for the feedback! The reason I asked about the `zap` parameter is because I have no idea what I'm looking at with the `uninstall` stanza documentation. If you could guide me through it or do it yourself, I'd really appreciate it! If needed, I can get a list of files the app installs through AppCleaner.

Thanks again!

**Comment by miccal** [comment]
> If needed, I can get a list of files the app installs through AppCleaner.

@mariobrostech if you can post this list, I can then help you with the `zap` stanza.

**Comment by mariobrostech** [comment]
> > If needed, I can get a list of files the app installs through AppCleaner.
> 
> @mariobrostech if you can post this list, I can then help you with the `zap` stanza.

@miccal I installed the app, signed in, and downloaded a sample file. These are the directories AppCleaner detected:
/Applications/Spitfire Audio.app
/Library/LaunchDaemons/com.spitfireaudio.LibraryManagerHelper.plist
/Library/Logs/Spitfire Audio
/Library/PrivilegedHelperTools/com.spitfireaudio.LibraryManagerHelper
~/Library/Caches/com.spitfireaudio.spitfireaudio
~/Library/Preferences/com.spitfireaudio.spitfireaudio.plist
~/Music/Spitfire Audio

I added the last directory, but Spitfire doesn't download anything there apart from log files. The user gets to pick their library install directory. By default, it's ~/Spitfire Audio, but since this is the content directly downloaded by the app, I didn't include it because it's user-installed.

**Comment by miccal** [comment]
@mariobrostech I have added the necessary `uninstall` and `zap` stanzas. 

Could you please try to do the same this in your other PR's, thanks.

**Comment by mariobrostech** [comment]
> @mariobrostech I have added the necessary `uninstall` and `zap` stanzas.
> 
> Could you please try to do the same this in your other PR's, thanks.

@miccal Thank you so much! I'll definitely update my other PRs when I get the chance.

**Comment by mariobrostech** [comment]
@miccal Any idea on when this might get merged? Just so I have a general idea.

**Comment by vitorgalvao** [comment]
> Any idea on when this might get merged? Just so I have a general idea.

“Now” sounds good! Thank you for the contribution.

**Review by vitorgalvao — APPROVED** [review]

**Comment by core-code** [comment]
since this is a static download URL and we do *not* have an appcast, wouldn't unversioned be better?

**Comment by mariobrostech** [comment]
> since this is a static download URL and we do _not_ have an appcast, wouldn't unversioned be better?

I have no idea what that is, but I’ll read up on it tonight. Do you mind showing me an example of how that would look?

Thanks!

**Comment by core-code** [comment]
thanks there :) no need to do anything right now. i was basically asking @vitorgalvao for our policy here.

**Comment by vitorgalvao** [comment]
> since this is a static download URL and we do _not_ have an appcast, wouldn't unversioned be better?

Yes, I missed that! This is exactly why I preferred the old style where single quotes would have been used.

But found an appcast: https://github.com/Homebrew/homebrew-cask/pull/91923/

**Pull request merged**
