### PR TITLE
Update shottr from 1.6.0 to 1.6.1

### PR DESCRIPTION
**Pull request by Moulick**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by ib0ndar** [comment]
==> Upgrading shottr
==> Downloading https://shottr.cc/dl/Shottr-1.6.1.dmg
######################################################################## 100.0%
==> Purging files for version 1.6.1 of Cask shottr
Error: shottr: SHA256 mismatch
Expected: 116613e1552558ee1bab86ffea6476b264b46164fbbdd94502ff4cd852840563
  Actual: dd022de05108a282c83a9d12f7faecaab90d1b4b4646e8b9cadcd5411f1d28b0
    File: /Users/user1/Library/Caches/Homebrew/downloads/ea2b5b96c55b42b2dc5406cd9a5371c882a5c8ca947174c0664fcadbfc5b81ee--Shottr-1.6.1.dmg
To retry an incomplete download, remove the file above.

**Comment by Moulick** [comment]
As shottr is not on Github, I'll reach out to the developer and ask him to confirm the change in the hash, will try to ask him to leave a comment here as well

**Comment by shottr** [comment]
Hello! I'm Shottr developer, I recompiled the app yesterday night, that's probably what caused the problem. The new build is 1.6.1 (28) (the previous one was (27)). What is the process of updating the SHA signature in the cask?

**Comment by p-linnane** [comment]
Fixed in #135005.

**Comment by Moulick** [comment]
Opened https://github.com/Homebrew/homebrew-cask/pull/135006

**Comment by p-linnane** [comment]
@Moulick if you want to reopen it would be better since I can approve and merge it as soon as CI is green.

**Comment by Moulick** [comment]
Sure, doing

**Comment by S1rM0rk3** [comment]
Wow, I'm super impressed with how quickly you responded and fixed. Thanks for your great work.

**Pull request closed without merging**
