### PR TITLE
update switchresx.rb to v4.10.0

### PR DESCRIPTION
**Pull request by kennyb-222**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by ran-dall** [comment]
`appcast at URL 'https://www.madrau.com/SRXCurrentVersion4' does not contain the version number '4.10.0'`


@kennyb-222 I'm seeing `Current version is 4.9.2` on [their website](https://www.madrau.com/) and [`appcast`](https://www.madrau.com/SRXCurrentVersion4). Where did you see `4.10.0`?

**Comment by kennyb-222** [comment]
> `appcast at URL 'https://www.madrau.com/SRXCurrentVersion4' does not contain the version number '4.10.0'`
> 
> @kennyb-222 I'm seeing `Current version is 4.9.2` on [their website](https://www.madrau.com/) and [`appcast`](https://www.madrau.com/SRXCurrentVersion4). Where did you see `4.10.0`?

Hey @ran-dall ,

It seems that the link to v4 is static (major version only), so if you ignore the appcast/website info and just download from the link and inspect the app bundle you can see that it's v4.10.0.

DL Link:
[http://www.madrau.com/data/switchresx/SwitchResX4.zip](http://www.madrau.com/data/switchresx/SwitchResX4.zip) 

Version info:
`% defaults read /path/to/SwitchResX.app/Contents/Info.plist CFBundleVersion`
`4.10.0` 

Cheers,
Kenny

**Comment by kennyb-222** [comment]
Also based on the timestamps within the zip file it seems the app was updated on May 25th.

**Comment by ran-dall** [comment]
@kennyb-222 Thanks for the clarification. It appears it is downloading `4.10.0`, so I go ahead and merge this for you. Thank you for your cooperation.

Screen Shot 2020-05-28 at 12 08 22 AM

**Pull request merged**
