### PR TITLE
Update wowza-streaming-engine to 4.7.5

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Tried in a VM but can’t finish installation without a license key. Pinging people that previously updated this cask. Keep in mind that if we cannot devise a proper download strategy, we’ll have to remove the cask.

Pinging @yurikoles @colindunn @reitermarkus @mandrean

**Comment by adidalal** [comment]
Did a bit of poking around. It uses installbuilder, which has no easy way to unpack it. (ref: https://support.bitrock.com/hc/en-us/community/posts/115002748989-Unpack-installer-package)

**Comment by adidalal** [comment]
Think the issue is we're not sure if the uninstall .app has changed its format.
However, it seems unlikely, based on its history.

**Comment by vitorgalvao** [comment]
Let’s merge and wait for bug reports if applicable.

**Pull request merged**
