### PR TITLE
Update spotify from 1.1.81.604 to 1.1.83.956

### PR DESCRIPTION
**Pull request by rgoldberg**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by wongyiuhang** [comment]
@rgoldberg, as I read from the error logs, the new version shall be `1.1.83.956.be7ea9a7` instead of `1.1.83.956.gbe7ea9a7`.

By the way, thanks for the contributions.

**Comment by rgoldberg** [comment]
Sorry for any errors. I just copied & pasted from the About dialog in the newer version of Spotify. Any reason why the bump didn't fail due to incorrect version info?

I can't see the test logs. They seem to have been deleted from the server.

Do you need me to make changes? Or can you fix the issues? I can make changes sometime in the next 24 hours.

Thanks.

**Comment by wongyiuhang** [comment]
I'm not a contributor of homebrew-cask, therefore the following suggestions are only my personal opinions.

I may think of two options.

# Option 1️⃣ - Update this pull request
1. Update the version string in [spotify.rb](https://github.com/rgoldberg/homebrew-cask/blob/bump-spotify-1.1.83.956/Casks/spotify.rb) file

```diff
cask "spotify" do
  arch = Hardware::CPU.intel? ? "" : "ARM64"

-  version "1.1.83.956,gbe7ea9a7,16"
+  version "1.1.83.956,be7ea9a7,21"
  sha256 :no_check
```

3. Then commit the update back to `bump-spotify-1.1.83.956` branch

# Option 2️⃣ - Create a new pull request
1. Close this pull request
2. Create a new pull request with the command `brew bump-cask-pr --version 1.1.83.956.be7ea9a7 spotify`

**Comment by rgoldberg** [comment]
Opened new PR #122401

**Pull request closed without merging**
