### PR TITLE
Update gitkraken from 8.2.1 to 8.3.0

### PR DESCRIPTION
**Pull request by mheob**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by owine** [comment]
ARM builds are now available as well at `https://release.axocdn.com/darwin-arm64/GitKraken-v#{version}.zip`

`5877eb06db592692e0eb31a934273e7ad01f866f8a269d9d62931f22622b7d7d  GitKraken-v8.3.0.zip`

**Comment by owine** [comment]
> ARM builds are now available as well at `https://release.axocdn.com/darwin-arm64/GitKraken-v#{version}.zip`
> 
> `5877eb06db592692e0eb31a934273e7ad01f866f8a269d9d62931f22622b7d7d GitKraken-v8.3.0.zip`
> 
> The Big Sur performance fix is also no longer required.

I've opened #119177 to address these - This PR should be merged first and I will rebase

**Comment by mheob** [comment]
Good points @owine. Maybe I was too fast (and dirty) this time.

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/119177

**Pull request closed without merging**
