### PR TITLE
Update wechat from 2.4.1.17 to 2.4.1.18

### PR DESCRIPTION
**Pull request by YorhaL**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/82697

**Comment by alswl** [comment]
It seems CDN update latency.

**Comment by core-code** [comment]
i've thought about using language/region stanzas to solve this issue, but Travis would still fail.

since this is a static download URL maybe using version :latest is the only workable thing here?

**Comment by vitorgalvao** [comment]
> since this is a static download URL maybe using version :latest is the only workable thing here?

That would require removing the appcast as well. But this problem always happens with this cask and it’s updated a lot, so I’m not necessarily opposed.

Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/82697.

**Pull request closed without merging**
