### PR TITLE
Update firefox to 64.0.2

### PR DESCRIPTION
**Pull request by mahori**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by yan12125** [comment]
Is there a reason that this PR is still not merged? The Travis CI failure looks caused by something outside this PR. With this patch Firefox 64.0.2 installs fine and `brew cask audit firefox` reports no error.

**Comment by vitorgalvao** [comment]
Please be patient. If things have errors, those have to be looked at.

We’re here everyday and have to take things one at a time. We’re human and volunteers. Literally nobody *needs* this to be merged fast. Firefox auto-updates.

The cause of the error will be addressed in https://github.com/Homebrew/brew/pull/5533. Then we’ll restart Travis, then we’ll merge if it passes.

**Comment by vitorgalvao** [comment]
All good.

Thank you, @mahori.

**Comment by yan12125** [comment]
Sorry for my negative attitude. I appreciate all awesome work done by Homebrew maintainers. I'll checkout out how to contribute more instead of leaving such not so constructive comments again.

**Comment by vitorgalvao** [comment]
@yan12125 Don’t sweat it. Thank you for understanding and the kind words.

**Pull request merged**
