### PR TITLE
Add a console in rake with environments of Hbc

### PR DESCRIPTION
**Pull request by WitzHsiao**
I'm not sure if it's helpful with test and development

### CODE REVIEW

**Comment by WitzHsiao** [comment]
add a feature `rake console` in homebrew-cask.

**Comment by radeksimko** [comment]
Hi @WitzHsiao ,
thanks for the idea and PR, could you describe a typical use-case of such feature (i.e. how exactly do you use it during testing/development)?

**Comment by WitzHsiao** [comment]
Hi @radeksimko 
I want to create a feature like `rails console`. I can interact with Hbc object in IRB, such as seeing the included_modules and methods on Hbc, seeing the object of "casks". I think it is very helpful for beginner.

**Comment by phinze** [comment]
> I think it is very helpful for beginner.

Agreed! I don't think we should include the `test_helper.rb` to accomplish this though. There are things that get bootstrapped and shimmed for testing that will make the environment very confusing.

Try this instead to get the same context we use in `brew-cask-cmd.rb` - the starting point for runtime HBC:

```ruby
  sh 'irb -Ilib -rvendor/homebrew-fork/global -rhbc'
```

**Comment by WitzHsiao** [comment]
@phinze Thanks, that's pretty awesome.

**Pull request merged**
