### PR TITLE
v2rayu 4.2.1

### PR DESCRIPTION
**Pull request by i0ntempest**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by i0ntempest** [comment]
Again, updating from a prerelease to another prerelease. 4.2.2 is the same build but with no signature so do not update.

**Comment by p-linnane** [comment]
I'm not exactly sure what's going on with this cask. The hashes are the same for each architecture. We should downgrade this to whatever is the latest stable signed release. If they are not planning to sign releases in the future, this should be deprecated instead. cc @Homebrew/cask for additional thoughts.

**Comment by p-linnane** [comment]
Agreed that we should not downgrade if it will break things for users.

We should probably open an upstream issue asking for clarification on their release process so we can handle this correctly moving forward. I'd like to understand the use of pre-releases, the signed/unsigned situation, and why/how both architectures have the exact same hash. @i0ntempest Do you happen to speak Mandarin? If so, would you be comfortable opening an issue? If not, I can open one but it would be in English.

**Comment by i0ntempest** [comment]
I do. I’ll ask for some clarification once I get time.
I think they previously have separated x86 and arm build, but the app is now universal and they didn’t bother to change file name. 
But that’s just my speculation. I’ll ask what’s going on.

**Comment by i0ntempest** [comment]
Opened a [discussion](https://github.com/yanue/V2rayU/discussions/1441) to ask for clarification.
What I know now is the developer had his old certificated revoked, so the old 3.8 (maybe also 4.2.0 and 4.2.1) now have invalid signatures, and the recently released 3.9 (which is just 3.8 rebuild) and 4.2.2 (4.2.1 rebuild) have adhoc signatures. I do not know yet how he's going to proceed.

**Comment by p-linnane** [comment]
Thank you so much @i0ntempest 🙏

**Comment by i0ntempest** [comment]
Two weeks without any response. Opened an issue instead.

**Comment by i0ntempest** [comment]
We got a response. Upstream dev said:
1. No plans for now for adding dev certificate in future versions
2. Files are kept for compatibility reasons. We may just use V2rayU-64.dmg which is universal despite the name.
3. 4.2 should be out of beta this week
4. Don't revert to 3.8, there might be bugs

I've told him that removing the certificate will result in the cask being deprecated/removed (I believe we added this audit for cask upgrades not long ago). Let's see what he says about that.

**Comment by p-linnane** [comment]
Thanks for the follow up. Let's wait for 4.2 to be released this week, and then we can update and merge this.

**Pull request closed without merging**
