### PR TITLE
Update atomic-wallet from 2.52.1-1219 to 2.53.1-1227

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — DISMISSED** [review]

**Comment by p-linnane** [comment]
@bevanjkay Been seeing @BrewTestBot getting rate limited while merging more and more often lately. Not sure what's going on.

**Comment by bevanjkay** [comment]
@Bo98 @SMillerDev Is there anything we can do about the rate limiting?

**Review by miccal — APPROVED** [review]

**Comment by Bo98** [comment]
BrewTestBot is probably doing far too much nowadays. It was merging 42 pull requests at the same time...

Reducing its usage down to just `git push` operations may help out. I'll have a think.

**Comment by bevanjkay** [comment]
@Bo98 The other thing is that when it's failing it's causing the PRs to become non-approved. There may be a way to check if the push failed due to rate-limit and in this case it can keep it approved to try again on the next cron.

**Comment by SMillerDev** [comment]
I was thinking of just firing off the approvals slower

**Comment by Bo98** [comment]
Should be fixed now. I've managed to find the root cause: https://github.com/Homebrew/brew/pull/13801

**Pull request merged**
