### PR TITLE
chore: update livechecks for GitHub API usage

### PR DESCRIPTION
**Pull request by SMillerDev**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
See also https://github.com/Homebrew/homebrew-core/pull/130233 and https://github.com/Homebrew/brew/pull/15270

**Comment by razvanazamfirei** [comment]
Ran `brew style --fix`. Hopefully it will get rid of the syntax failure.

**Comment by samford** [comment]
I took care of `appium` (#146747), `brook` (#146749), and `ricochet` (#146754) in separate PRs, since they required additional changes.

Razvan beat me to rebasing this but I had to rebase it again to drop the `appium` commit. I'm currently doing a test run to make sure this takes care of all the existing breakages at this point.

**Comment by razvanazamfirei** [comment]
I'm just happy to be in y'all's company!

**Review by razvanazamfirei — APPROVED** [review]

**Review by samford — APPROVED** [review]
As mentioned in https://github.com/Homebrew/homebrew-core/pull/130233#pullrequestreview-1417140026, I'll create follow-up PRs to update the regexes to use `^`/`$` (like we do with `Git` regexes), so we can get these fixes merged in the interim time.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
