### PR TITLE
Add Arturia software

### PR DESCRIPTION
**Pull request by joshka**
This PR includes casks for:
- Analog Lab 1.2.4.126
- Midi Control Center 1.2.2.429
- Mini V 2.7.0.76
- Arturia Software Center 1.1.3.145

One commit per product and cask names renamed per comments by @jawshooah on previous PR #17321.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
All of these are missing `uninstall`. There are [scripts](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#uninstall-stanza-details) geared for that.

**Comment by joshka** [comment]
Thanks. I'll add this later tonight and resubmit.

**Comment by jawshooah** [comment]
No need to create a new pull request every time you need to change something. You can just fixup your existing commits (`git commit --fixup` comes in handy here), `git rebase --interactive `, and `git push --force`.

**Comment by vitorgalvao** [comment]
Closing for lack of updates. Feel free to submit again later with the fixes, @joshka.

**Pull request closed without merging**
