### PR TITLE
Add USBImager.app v1.07

### PR DESCRIPTION
**Pull request by airsquared**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues). (was previously refused, but now has 150 stars on GitLab)
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by airsquared** [comment]
This cask was previously refused, but it now has 150 stars on GitLab.

**Comment by SMillerDev** [comment]
this should be a `.rb` file. It currently has no extension

**Comment by airsquared** [comment]
Sorry, I've fixed it now.

**Comment by airsquared** [comment]
Huh, after fixing the file name the CI is giving an error related to livecheck? I didn't get this error when I did audit on my own machine.

**Comment by SMillerDev** [comment]
Likely because it wasn't recognized properly without the `.rb` extension

**Comment by airsquared** [comment]
I tried it again, and it still does seem to be working:

```
$ brew cat usbimager
cask "usbimager" do
  version "1.0.7"
  sha256 "059bf094fdcdf37b71485375255d7e0b68d71ba6316cecb472d6688b076410a6"

  url "https://gitlab.com/bztsrc/usbimager/raw/binaries/usbimager_#{version}-intel-macosx-cocoa.zip",
      verified: "gitlab.com/bztsrc/usbimager/"
  name "usbimager"
  desc "Very minimal GUI app that can write/read to disk images and USB drives"
  homepage "https://bztsrc.gitlab.io/usbimager/"

  app "USBImager.app"

  zap trash: "~/Library/Preferences/usbimager.plist"
end
$ brew audit --new-cask usbimager
audit for usbimager: passed
```

I also did try adding a manual livecheck block earlier but wasn't able to get that working, and adding `appcast` produced a warning that it shouldn't be included in new casks.

**Review by SMillerDev — APPROVED** [review]
Livecheck has been added by @cho-m , LGTM

**Pull request merged**
