### PR TITLE
Update balenaetcher from to 1.8.14, discontinue

### PR DESCRIPTION
**Pull request by eloyaldea**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Just a couple too many releases for one day, let's wait to see the outcome of https://github.com/balena-io/etcher/issues/3853 before continually bumping this one.

**Review by SMillerDev — DISMISSED** [review]

**Comment by p-linnane** [comment]
Upstream has declared this extremely frequent release cadence is now by design. After an internal discussion, Homebrew maintainers have decided to discontinue furthur support of this cask on the grounds it is now too difficult to maintain.

**Review by p-linnane — APPROVED** [review]

**Comment by JFKingsley** [comment]
Hey folks! Chiming in from the Balena side as we've had a number of requests for Etcher support on Homebrew, and I'd like to find a way forward here. While the standard release cadence we have isn't likely to change in the short term, we were wondering if it would be reasonable to instead direct the cask to pull from a URL that we point to a known-good daily release to avoid y'all having to constantly bump versioning? 

I'm admittedly somewhat unfamiliar with how brew tends to operate on this front, so please do feel free to chime in if there are any assumptions I'm not getting here. If you'd like me to open a new issue instead of continuing this one, happy to do that too!

**Comment by p-linnane** [comment]
Hi @JFKingsley. Please review the discussion we had in https://github.com/balena-io/etcher/pull/3875.

**Pull request closed without merging**
