### PR TITLE
Add Astropad.app :latest

### PR DESCRIPTION
**Pull request by johndbritton**
Adds `Astropad.app`, unfortunately they don't have a versioned download URL.

http://astropad.com/

### CODE REVIEW

**Comment by Ngrd** [comment]
Thank you for the contribution. It needed some fixes, so they were made in edcbffe418e5114992c1ef0c22a5557ca103ed79. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by johndbritton** [comment]
@Ngrd Thanks for the improvements. How did you figure out where the versioned urls were?

**Comment by Ngrd** [comment]
From the app itself: `AstroPad.app/Contents/Info.plist`. The key `SUFeedURL` contains the Sparkle appcast URL.

**Comment by johndbritton** [comment]
Nice, that's good to know for next time.

**Pull request closed without merging**
