### PR TITLE
eudic 4.6.3

### PR DESCRIPTION
**Pull request by daeho-ro**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
audit for eudic: failed
 - Version '4.6.3' differs from '4.6.0' retrieved by livecheck.
 - Version '4.6.3' differs from '4.6.0' retrieved by livecheck.
```

**Comment by razvanazamfirei** [comment]
Closing as the `livecheck` continues to fail. Please reopen when the livecheck consistently passes.

**Comment by bevanjkay** [comment]
@razvanazamfirei I think this is a CI-only failure? What do you get locally for `brew livecheck eudic`? I see 4.6.3

**Comment by razvanazamfirei** [comment]
@bevanjkay, I'm still getting 4.6.0.

```ruby
❯ brew livecheck eudic --verbose --debug
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/bin/bundle clean
#<Homebrew::CLI::Args named=["eudic"], remaining=["eudic"], d?=true, debug?=true, q?=false, quiet?=false, v?=true, verbose?=true, h?=false, help?=false, full_name?=false, tap=nil, eval_all?=false, installed?=false, newer_only?=false, json?=false, r?=false, resources?=false, formula?=false, formulae?=false, cask?=false, casks?=false, extract_plist?=false>
/Users/razvanazamfirei/.config/brew/livecheck_watchlist.txt
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading eudic
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromNameLoader): loading eudic

Cask:             eudic
Livecheckable?:   Yes

URL:              https://static.eudic.net/pkg/eudic_mac.xml
Strategies:       PageMatch, Sparkle
Strategy:         Sparkle

Matched Versions:
4.6.0 => #<Version:0x0000000105fae208 @version="4.6.0", @detected_from_url=false>

eudic: 4.6.0 ==> 4.6.0
```

**Comment by bevanjkay** [comment]
There's always been some really odd caching on this one. Maybe we just make them `version :latest` because they're unversioned `url` anyway.

**Comment by razvanazamfirei** [comment]
@bevanjkay, I'm on board with that!

**Pull request closed without merging**
