### PR TITLE
Add TurboVNC.app v2.2.1

### PR DESCRIPTION
**Pull request by adzenith**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
  - Unable to complete - I can't run `brew cask style` on my machine, and I can't figure out how to fix it. See https://github.com/Homebrew/homebrew-cask/issues/52775.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
  - The package is named `TurboVNC-#{version}.dmg`, so I've named the recipe `turbovnc`. The actual `.app` is `TurboVNC/TurboVNC Viewer.app`, but the viewer is the only thing available for Mac. Let me know if I should rename to `turbovnc-viewer`.
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
  - It worked successfully but I'm not sure how to verify that everything was removed.
  - The app comes with an uninstaller, and I'm trying to make it run, but I get:
  ```
  /usr/local/Caskroom/turbovnc/2.2.1/Uninstall TurboVNC.app/Contents/Resources/Scripts/main.scpt: /usr/local/Caskroom/turbovnc/2.2.1/Uninstall TurboVNC.app/Contents/Resources/Scripts/main.scpt: cannot execute binary file
  Error: Failure while executing; `/usr/bin/sudo -E -- /usr/local/Caskroom/turbovnc/2.2.1/Uninstall\ TurboVNC.app/Contents/Resources/Scripts/main.scpt` exited with 126. Here's the output:
  /usr/local/Caskroom/turbovnc/2.2.1/Uninstall TurboVNC.app/Contents/Resources/Scripts/main.scpt: /usr/local/Caskroom/turbovnc/2.2.1/Uninstall TurboVNC.app/Contents/Resources/Scripts/main.scpt: cannot execute binary file
  ```
  - I also am not sure if I should run the uninstaller from the staging area or from the Applications directory (it gets installed along side the viewer app).
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by adzenith** [comment]
Does anyone have any tips for how to update the formula to pass travis? `uninstall pkgutil: 'com.virtualgl.turbovnc'` is already part of the recipe.

**Comment by reitermarkus** [comment]
Is the `Uninstall TurboVNC.app/Contents/Resources/Scripts/main.scpt` an AppleScript file or a binary?

**Comment by adzenith** [comment]
I would still love to land this! I just can't figure out the CI problem.

**Comment by reitermarkus** [comment]
What type of file is `Uninstall TurboVNC.app/Contents/Resources/Scripts/main.scpt`?

**Comment by adzenith** [comment]
It's a binary file, which I'd assumed was compiled AppleScript. To double check:
```
$ file /Applications/TurboVNC/Uninstall\ TurboVNC.app/Contents/Resources/Scripts/main.scpt 
/Applications/TurboVNC/Uninstall TurboVNC.app/Contents/Resources/Scripts/main.scpt: AppleScript compiled
```

**Comment by reitermarkus** [comment]
The contents of the script show that it shows a dialog and then simply executes `/opt/TurboVNC/bin/uninstall`.

**Comment by adzenith** [comment]
Thanks so much!

**Pull request merged**
