### PR TITLE
Update mockuuups-studio to 1.1.0

### PR DESCRIPTION
**Pull request by colindunn**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by colindunn** [comment]
This has failed the build checks a few times now. Have just re-checked on my end and it still audits fine and downloads.

Not sure of the cause on this one. Thought maybe a rate-limit problem on downloads, but just tested a few times in a row and no issue with the donwload. Any ideas?

**Comment by miccal** [comment]
Build verified manually.

**Comment by colindunn** [comment]
Thanks @miccal

**Comment by miccal** [comment]
You're welcome.

**Pull request merged**
