### PR TITLE
Update mactex to 2019.0508

### PR DESCRIPTION
**Pull request by miccal**

### CODE REVIEW

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/63085

**Comment by VonUniGE** [comment]
The download url: `http://mirror.ctan.org/systems/mac/mactex/mactex-20190508.pkg` is now OK.
The travis build can be relaunched.

**Comment by ran-dall** [comment]
@miccal You can just close and reopen to relaunch Travis. 🔧

**Comment by reinhar2** [comment]
since the update, pdflatex is not found anymore as a command. Did something change or do I need to do additional post install actions?

**Comment by miccal** [comment]
@reinhar what is the output of the command `which -a pdflatex`?

**Comment by VonUniGE** [comment]
For me it's seems to work correctly:
```
$ which pdflatex
/Library/TeX/texbin/pdflatex

$ pdflatex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
```

**Comment by reinhar2** [comment]
Everything is working now. It seems like there was a problem during installation which wasn't notified.
A second re-install solved the problem and `pdflatex` is available now.

**Pull request merged**
