### PR TITLE
Add World of Tanks Latest

### PR DESCRIPTION
**Pull request by shpoont**

### CODE REVIEW

**Comment by shpoont** [comment]
Updated

**Comment by vitorgalvao** [comment]
As [stated before](https://github.com/caskroom/homebrew-cask/pull/8358#issuecomment-67801550), the North American version should be the one used. **Predictability and consistency** is what we’re going for, here; I’m not American, I’m European myself, but we start including whatever version we feel like, there ceases to be a rule. It was decided long ago the default version to be included in the main repo would be the North American one — its as arbitrary as any other, but please follow the request as made: it has a reason to be.

**Comment by shpoont** [comment]
@vitorgalvao, thanks for pointing this out again, **predictability and consistency** are indeed very important for this project. 

Unfortunately I am unable to spend more time on this "cask" and have to leave you with all the material required in order to complete it. Both PR's will be available for about a week, the branches will be deleted after this period.

**Comment by vitorgalvao** [comment]
@shpoont Apologies if I’ve offended you or seemed confrontational in any way, as it was not my intention. Your contribution is appreciated, and I hope this doesn’t deter you from future ones. It’ll be merged in [a different pull request](https://github.com/caskroom/homebrew-cask/pull/8600), as will [the others](https://github.com/caskroom/homebrew-versions/pull/640), but they’ll still include the PR as credited to you. Thank you for your work and patience on this.

**Pull request closed without merging**
