### PR TITLE
blobsaver: add livecheck

### PR DESCRIPTION
**Pull request by madmaximux**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by neutric** [comment]
The implicit livecheck based on the GitHub-URL works fine, so adding an explicit livecheck isn't necessary...

**Comment by madmaximux** [comment]
> The implicit `livecheck` based on the GitHub-URL works fine, so adding an explicit `livecheck` isn't necessary...

Sorry not understanding completely. I should close this PR? Or make an edit?

**Comment by neutric** [comment]
Sorry for not being clear. This can be closed.

**Comment by madmaximux** [comment]
Ok Thanks.

**Pull request closed without merging**
