### PR TITLE
update praat

### PR DESCRIPTION
**Pull request by psibre**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/18830#issuecomment-183886283

**Comment by psibre** [comment]
The other two commits are legit, I'm reverting the controversial one and reopening this PR.

**Comment by vitorgalvao** [comment]
Oh, right, should’ve kept open for those. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git), though?

**Comment by adidalal** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 3d61e0ce30df256c0f865b0e49d4d96591350007. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
