### PR TITLE
codeedit: update `sha256`

### PR DESCRIPTION
**Pull request by Jerry23011**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Why has the shasum changed here without a new version number? Can you ask upstream @Jerry23011?

**Comment by Jerry23011** [comment]
CC @austincondiff

**Comment by austincondiff** [comment]
We had another maintainer accidentally delete our latest release via a GitHub action while working on our CI, so we had to re-create it. Maybe this has lead what you are seeing?

**Comment by krehel** [comment]
No problem @austincondiff - thanks for the comment.  We like to check and make sure everything is fine when we see updates to sha256sums without version increments.

**Review by krehel — APPROVED** [review]

**Comment by Jerry23011** [comment]
Thank you! @austincondiff

**Pull request merged**
