### PR TITLE
Added DuckDuckGo Cask v0.27.0

### PR DESCRIPTION
**Pull request by Im-Fran**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [X] `brew audit --new-cask <cask>` worked successfully.
- [X] `brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by Im-Fran** [comment]
Hey guys, I don't know if I should mark `The submission is for a stable version or documented exception.`, because I consider it stable, but is not in 1.X. Also it requires an invite code from the DuckDuckGo iOS App to use it.

**Comment by p-linnane** [comment]
Thank you for your first contribution to `homebrew-cask` @Im-Fran.

If it is the only type of release available (no stable/beta/dev channels etc.) its fine for the main repo. 

From [Acceptable Casks](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version):

> But There Is No Stable Version!
When software is only available as a beta, development, or unstable version, its cask can go in the main repo. When stable versions become available, only those will be accepted as subsequent updates.

I'm more concerned with the need for an invite-only key to use it right now. [We just removed](https://github.com/Homebrew/homebrew-cask/pull/128728) a cask that required an API key for each user. Maintainers will need to make the final call on this one.

**Comment by Im-Fran** [comment]
Ok, thanks for the information :)

**Review by SMillerDev — COMMENTED** [review]
Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

**Comment by Im-Fran** [comment]
> Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

Thanks for the info, just added it 👍

**Review by bevanjkay — DISMISSED** [review]

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
