### PR TITLE
Update pdf-expert from 2.4.28,636 to 2.4.29,640

### PR DESCRIPTION
**Pull request by singularitti**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Are you sure this is a stable version? It’s not showing up in the appcast.

**Comment by robertleeblairjr** [comment]
> Are you sure this is a stable version? It’s not showing up in the appcast.

I was off work/school today and updating apps. I'm not enrolled in the Beta Program but when enabled was offered this update. So, I searched for the changelog and it's listed as Beta.

[https://pdfexpert.com/beta/changelog](url)

It appears the 2.4.24 is the current stable which is confirmed by the appcast. However, this version has been updated 4 times previously to link with Beta. Don't know if you guys want to go ahead and leave it as is, approve updates to this newer version and subsequent ones until the next stable, or just revert back to the current stable.

**Comment by vitorgalvao** [comment]
> or just revert back to the current stable.

That one.

**Comment by singularitti** [comment]
My fault, I forget I was enrolled in public beta program.

**Pull request closed without merging**
