### PR TITLE
Update Netbeans CPP 8.2 - sha256

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by commitay** [comment]
`sha256` only changes need to be verified. See [Updating the SHA256](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256) for how to provide verification.

**Comment by cmckni3** [comment]
I downloaded it from Oracle's website and ran shasum manually. I can provide proof.

**Comment by commitay** [comment]
Public `sha256`
> https://netbeans.org/downloads/start.html?platform=macosx&lang=en&option=cpp
> SHA-256: e9b04de3ff2ecc2218899ae5f3bc795033492d79c3ac34ccd0e83ab2c14b9ee2

**Review by commitay — APPROVED** [review]

**Comment by cmckni3** [comment]
Sweet! I guess there were some sort of undocumented patch.

**Pull request merged**
