### PR TITLE
Adds cask for App Tamer

### PR DESCRIPTION
**Pull request by shostakovich**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Long time no see. Welcome back, and thank you for the contribution. It needed some fixes, so they were made in the below referenced pull request. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by shostakovich** [comment]
Thanks for fixing it for me :)

So I need to reference the version number the next time?

**Comment by vitorgalvao** [comment]
It isn’t mandatory, but it is insanely useful for us. Makes future updates way easier, as we don’t have to keep worrying about the url.

**Comment by shostakovich** [comment]
Ok :) Thank you!

Will try to keep it in mind.

**Pull request closed without merging**
