### PR TITLE
speedy - remove appcast

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
This is no longer in development and the appcast redirects to the homepage (which doesnt even list speedy as a product anymore...).

The download still works, however, so I think just removing the appcast is sufficient for now.

**Comment by vitorgalvao** [comment]
I’d rather remove the whole cask, as otherwise it’ll just be left forgotten until (and after) it breaks.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/48657

**Comment by brianmorton** [comment]
@vitorgalvao i didn't want to remove the cask as I don't know how many people use it.

**Pull request closed without merging**
