### PR TITLE
Add Playdate Mirror.app 1.0.0

### PR DESCRIPTION
**Pull request by whoisjake**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by whoisjake** [comment]
Just a quick comment on the name:
```
If the result of that process is a generic term, such as “Macintosh Installer”, try prepending the name of the vendor or developer, followed by a hyphen. If that doesn’t work, then just create the best name you can, based on the vendor’s web page.
```

The result would have been just Mirror. This felt too generic and to match the existing [playdate-simulator](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/playdate-simulator.rb) app, I prefixed with the vendor.

**Comment by whoisjake** [comment]
I used [AppCleaner](https://freemacsoft.net/appcleaner/) to hunt for zap locations

**Comment by bevanjkay** [comment]
Thank you for your submission @whoisjake 
This cask is likely more suitable for the[ `homebrew-cask-drivers`](https://github.com/Homebrew/homebrew-cask-drivers) repo, as it requires hardware to function.

https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask
```
Driver: Software to make a hardware peripheral recognisable and usable by the system. If the software is useless without the peripheral, it’s considered a driver.
```

**Comment by whoisjake** [comment]
Thanks for the response @bevanjkay.

https://github.com/Homebrew/homebrew-cask-drivers/pull/2783

**Pull request closed without merging**
