### PR TITLE
Add egnyte 0.4.1

### PR DESCRIPTION
**Pull request by mjsteinbaugh**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [X] `brew audit --new-cask <cask>` worked successfully.
- [X] `brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
It appears that app isn't correctly signed:

```
Run brew audit --cask --appcast --online --new-cask --signing 'egnyte'
  
curl: (22) The requested URL returned error: 403
Error: 1 problem in 1 cask detected
audit for egnyte: failed
 - exception while auditing egnyte: key not found: :latest
Error: exception while auditing egnyte: key not found: :latest
Error: Process completed with exit code 1.
```

**Comment by miccal** [comment]
It seems that the `url` https://helpdesk.egnyte.com/hc/en-us/articles/205237150-Desktop-App-Installers does not accept `curl` requests:
```
|-> curl -sLI https://helpdesk.egnyte.com/hc/en-us/articles/205237150-Desktop-App-Installers
HTTP/2 403 
date: Thu, 09 Feb 2023 23:16:14 GMT
content-type: text/html; charset=UTF-8
cf-chl-bypass: 1
permissions-policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
referrer-policy: same-origin
x-frame-options: SAMEORIGIN
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=wfG%2FCISr9YU0szjRHT8qRjvCIZ42n1LvUMF1hXwQZcFyHl4cAdZIxyQHhnRivvxHErEix2iPhaitMWTQLbqapDMwOQmN8bgPBK8UQeh3F6CeJpbdbajOTqGkTCNpJbF7bQmsjXc%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 79704fc4289d8acf-PER
```

**Comment by bevanjkay** [comment]
We may be able to use the zendesk API URL for livecheck. I don't have time to dig for it now, so just for reference for now.

**Comment by mjsteinbaugh** [comment]
Oh interesting good catch on that! I couldn't figure out the signing issue

**Comment by mjsteinbaugh** [comment]
What if we change the curl user agent? Setting it to my current browser seems to work:

```sh
curl -s -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0" \
    https://helpdesk.egnyte.com/hc/en-us/articles/205237150 \
| grep -Eo 'Egnyte_.+_.+.dmg'
```

**Review by bevanjkay — APPROVED** [review]

**Comment by bevanjkay** [comment]
Thank you @mjsteinbaugh

**Comment by samford** [comment]
> What if we change the curl user agent? Setting it to my current browser seems to work

This isn't possible within `livecheck` yet but I have a working implementation locally that enables it (I've confirmed it works with other casks in the past). The changes rely on a larger feature that I haven't created a PR for yet, so it's something that's definitely coming (we have a few other casks that need a different user agent to work) but not immediately, as I have a few other things that I need to take care of first.

**Comment by bevanjkay** [comment]
Thanks @samford - for 95% of cases I have seen that need to check a Zendesk article we can use the API URL instead without issue.

**Pull request merged**
