### PR TITLE
Add `IPA Manager.app` v2.2.1

### PR DESCRIPTION
**Pull request by lwolfsonkin**
IPA Palette is a palette-class input method for OS X 10.5 and later.
It makes possible point-and-click input of International Phonetic
Alphabet symbols into Unicode-savvy applications.

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download ipa-palette` is error-free.
- [x] `brew cask style --fix ipa-palette` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install ipa-palette` worked successfully.
- [x] `brew cask uninstall ipa-palette` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]

**Comment by lwolfsonkin** [comment]
@vitorgalvao So, the standard is to call the cask `IPA Manager`, but leave its name as `IPA Palette` in a case like this, where there is a manager application for a tool? (As you did)

**Comment by vitorgalvao** [comment]
`name` is whatever the developer calls it. The token needs to follow the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).

**Comment by miccal** [comment]
@lwolfsonkin yes, the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) follows the `app` name, not the `name`.

**Comment by lwolfsonkin** [comment]
Gotcha. That makes sense. When people use `brew cask search` if they search something like `ipa pallete`, would it come up? That is, is the `name` only something that appears when you use `brew cask info`, or does the search take it into account?

**Comment by vitorgalvao** [comment]
@lwolfsonkin The `name` is to be taken into account in `search`, but currently the code for it isn’t implemented.

**Comment by miccal** [comment]
Thank you for your contribution.

**Pull request merged**
