### PR TITLE
clash-verge-rev: update sha256

### PR DESCRIPTION
**Pull request by whuwxl**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by bevanjkay** [comment]
There is an issue open upstream - we should wait for a response to make sure the binaries were replaced intentionally.
https://github.com/clash-verge-rev/clash-verge-rev/issues/1410

**Comment by whuwxl** [comment]
Hi @bevanjkay,
Thank you for your feedback. The upstream developer has pushed new commits to this git tag and released corresponding binaries. All of this can be verified at the following link: [Clash Verge Rev Releases](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.7.5).

Please let me know how you would like to proceed.

**Comment by bevanjkay** [comment]
Upstream should stop retagging as it is the "insane thing to do" - https://git-scm.com/docs/git-tag#_on_re_tagging

If this is a practice they insist on, we would need to drop the shasum check, or disable the cask.

**Comment by MystiPanda** [comment]
The purpose of retagging is to fix an urgent bug. It is indeed an unconventional operation. I can only say that it was an accident. Such problems should not occur in the future. I think this PR can be merged.

**Comment by bevanjkay** [comment]
Thank you @MystiPanda for confirming. In the future I would recommend bumping to a new tag, even if it is a simple bug fix.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
