### PR TITLE
Add Apparency.app v1.0

### PR DESCRIPTION
**Pull request by silver886**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by ran-dall** [comment]
@silver886 Have you checked if this requires an `zap`?

**Comment by silver886** [comment]
I'm not sure how to do that. It claims to be using App Sandbox.
But I checked the path in [Casks/suspicious-package.rb](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/suspicious-package.rb) published by the same developer, and found nothing.
I also used other apps like [AppCleaner](https://freemacsoft.net/appcleaner) and nothing other than empty folders and container folders.
Are there any suggestions on how or where I can check it?

**Comment by ran-dall** [comment]
@silver886 It may not be required for this software. However, to answer your question, you can always try using @nrlquaker's [createzap project](https://github.com/nrlquaker/homebrew-createzap) though.

**Comment by silver886** [comment]
@ran-dall Thank you! I added a `zap` stanza base on the output from [createzap](https://github.com/nrlquaker/homebrew-createzap).

**Pull request merged**
