### PR TITLE
Add Sound Control

### PR DESCRIPTION
**Pull request by sscotth**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [X] [If the `sha256` changed but the `version` didn’t][version-checksum],  
      provide public confirmation by the developer: {{link}}

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not already refused in [closed issues].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by sscotth** [comment]
Why delete when it could have been updated?

https://github.com/caskroom/homebrew-cask/pull/33308

**Comment by commitay** [comment]
This will need uninstall `quit:` and `launchctl:`

It also opens this during install:
sound control 1

Which then opens this:
sound control 2

**Comment by miccal** [comment]
@sscotth what @commitay has pointed out is exactly why I deleted it.

**Comment by sscotth** [comment]
@miccal I didn't see an issue posted. Only a reference to the renaming.

I thought "Additional Components Required" were a common thing with Casks like Xcode. Either way, I can try and track what is missing down in a VM.

**Comment by commitay** [comment]
Also seems to have an uninstaller in the app. https://staticz.com/support/soundcontrol/uninstall/

**Comment by miccal** [comment]
I think this is not a suitable thing to have in Cask at present.

**Comment by designorant** [comment]
For any internet wanderers looking to add it via homebrew nevertheless:
https://github.com/sscotth/homebrew-sound-control

**Pull request closed without merging**
