### PR TITLE
Update hazel from 5.0.3 to 5.0.5

### PR DESCRIPTION
**Pull request by adithyasunil26**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
```
audit for hazel: failed
 - exception while auditing hazel: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
```
I cannot reproduce this error using either a `brew`'ed `curl` or the system `curl`.

**Comment by adithyasunil26** [comment]
I am not able to figure out what's going wrong either. The updated cask seems to work perfectly fine when I run it locally. The audit is passed and installation is successful.

**Comment by miccal** [comment]
> Also the same issue on #98295

This one is not the same error as in https://github.com/Homebrew/homebrew-cask/pull/98295, as I can reproduce that one:
```
|-> curl https://smooze.co/updates/Smooze.dmg
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by adithyasunil26** [comment]
okay, my bad. I saw the same error message and thought it might be the same issue.

**Review by reitermarkus — APPROVED** [review]

**Pull request merged**
