### PR TITLE
free-gpgmail 7.1,2023.2,

### PR DESCRIPTION
**Pull request by mattcen**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by mattcen** [comment]
Sorry, I don't understand what the failed CI check is trying to tell me. 😢

**Comment by krehel** [comment]
Hi @mattcen -

The CI check is referring to the latest update for a different OS than what was updated as part of `brew bump-cask-pr`

In this case, looks like the Monterey version of the cask also received an update.  I think if you simply update that version and sha256, it'll pass.  Does look like there are new versions for Catalina and Big Sur, but are not marked as any code changes.

I checked this manually and got these values to pass local check.  Feel free to update with this info and test.

```
  on_monterey do
    version "6.3,2023.2,"
    sha256 "9630a8896e7e9c4691bda4b4cb529b28f0781aa71ad188d326a7587083b23c1a"
  end
```

**Comment by razvanazamfirei** [comment]
Thank you, @krehel!

**Comment by razvanazamfirei** [comment]
Hey @mattcen! 

Kudos on your contribution! Your efforts help improve the project and benefit users worldwide. Keep up the great work, and know that without contributions like yours it'd be impossible to keep our project going.

**Review by razvanazamfirei — APPROVED** [review]

**Comment by mattcen** [comment]
Thanks, folks! I appreciate the constrictive feedback and gratitude! 💜

**Pull request merged**
