### PR TITLE
Upgraded Onyx to current version

### PR DESCRIPTION
**Pull request by patbaumgartner**
Upgraded Onyx cask to a version which supports OSX El Capitan

### CODE REVIEW

**Comment by vitorgalvao** [comment]
There is trailing whitespace that needs to be removed.

**Comment by patbaumgartner** [comment]
Done. Sorry, did not see it.

**Comment by vitorgalvao** [comment]
Thank you. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 1426c1725c686620845aad21f9179d4bcf9833f1. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by patbaumgartner** [comment]
Thank you very much!

**Pull request closed without merging**
