### PR TITLE
Fix url and app in Pingendo3.app Cask

### PR DESCRIPTION
**Pull request by maartenpaauw**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

### CODE REVIEW

**Comment by m44rt3np44uw** [comment]
I'm not sure if I need to change te token from pingendo to pingendo3.

**Comment by miccal** [comment]
@vitorgalvao should the token be renamed in this case?

**Comment by vitorgalvao** [comment]
`3` is a version, not an integral part of the name (e.g. [c3](https://github.com/caskroom/homebrew-cask/blob/master/Casks/c3.rb)) so it is not to be included in the token (the token reference predicts this).

**Comment by vitorgalvao** [comment]
See [pharo](https://github.com/caskroom/homebrew-cask/blob/master/Casks/pharo.rb) as an example precedent of my changes,

**Comment by miccal** [comment]
Thanks @vitorgalvao, your logic and changes make perfect sense.

**Pull request merged**
