### PR TITLE
ollama 0.1.17 (new cask)

### PR DESCRIPTION
**Pull request by ongyuxing**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by ongyuxing** [comment]
I've added `conflicts_with formula: "ollama"` to the cask, but the CI is still failing. Do I need to rename this cask?

**Comment by SMillerDev** [comment]
Why add a cask in addition to the formula?

**Comment by ongyuxing** [comment]
@SMillerDev The ollama formula and cask have different uses. The formula does not support running some sub-commands independently, such as `ollama run`. Conversely, the ollama cask includes the CLI, making the formula unnecessary.

**Comment by bevanjkay** [comment]
@ongyuxing Is there no way for the formula to be updated to include the additional sub-commands?

**Comment by ongyuxing** [comment]
@bevanjkay I believe so, some commands require the Ollama.app to be running; otherwise, it will result in an error message saying "Error: could not connect to ollama app, is it running?"

**Comment by bevanjkay** [comment]
If the app includes the CLI should there be a reference to it using a `binary` stanza?
https://docs.brew.sh/Cask-Cookbook#stanza-binary

**Comment by ongyuxing** [comment]
@bevanjkay Sure, it's done.

**Comment by razvanazamfirei** [comment]
Hi, @ongyuxing! Thanks so much for your first contribution! This looks great! 👍

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
