### PR TITLE
Upgraded PhpStorm.app to 9.0.2

### PR DESCRIPTION
**Pull request by themizzi**
Upgrading Phpstorm.app to 9.0.2

### CODE REVIEW

**Comment by alebcay** [comment]
Thank you for the contribution. It was merged directly as f4927ae6d80ba6b3e63f947680b2b59de040397e to keep commit history cleaner. Your contribution is still credited to you.

**Comment by themizzi** [comment]
Thanks! If there is anything I should do different in future commits please let me know.

**Comment by alebcay** [comment]
You may want to check your Git setup. It looks like your commits aren't being credited to your GitHub account.

**Comment by themizzi** [comment]
Ah yes thank you!

**Pull request closed without merging**
