### PR TITLE
Add Samsung DeX 2.0.0.11

### PR DESCRIPTION
**Pull request by stephengroat**
extends #69650

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by stephengroat** [comment]
👋 slightly confused about the `sha256 :no_check` warning. The URL is versioned, just no versions with the version # of the app.

any advice?

**Comment by miccal** [comment]
May be better to use `https://www.samsung.com/global/download/SamsungDeXMac` as the `url`:
```
|-> curl -sLI https://www.samsung.com/global/download/SamsungDeXMac | grep -i Location
location: https://www.samsung.com/global/download/SamsungDeXMac/
location: https://org.downloadcenter.samsung.com/downloadfile/ContentsFile.aspx?CDSite=COMMON&CttFileID=7927171
Location: https://downloadcenter.samsung.com/content/SW/202101/20210112132845263/SamsungDeXSetupMac.dmg
```
No idea on a `livecheck`, though.

**Comment by miccal** [comment]
No idea on a `livecheck`, though.

**Comment by miccal** [comment]
This looks ok to me for now, so I am going to merge this and lets see how updates with it go.

**Pull request merged**
