### PR TITLE
Link shell completion scripts with Docker.app

### PR DESCRIPTION
**Pull request by jasonkarns**
- Docker.app conflicts_with docker formula (and [others](https://github.com/Homebrew/homebrew-cask/pull/105990/files#diff-69311afaafb577bb3a6618c5f2d0acf5cbd596db0236c994414a0491cccff721R31-R37))
- Docker.app installs bash shell completion

I added the `conflicts_with formula:` stanza, even though it's still a no-op stub, as it provides a bit of documentation to cask authors; but primarily so that if/when the stanza is implemented, this cask will be able to leverage it. (Note, the cask already conflicts with the binaries installed by other formulae; this is not newly-introduced by the linking of completions.)

I've noticed that there are very few completion scripts installed by casks. (Filebot being a [notable exception](https://github.com/Homebrew/homebrew-cask/blob/1212ae9879ed484487aeed96cb8d31ef497893ed/Casks/filebot.rb#L17-L18)) In general, that seems to make sense because casks are geared towards GUI apps and completion scripts are for CLIs, which are typically installed as formulae.

However, in docker's case (and perhaps others in a similar situation), I believe the completion should be installed. As noted, the Docker.app cask conflicts with the docker formula; which means only one of the two can be linked at a time. If one prefers the Docker.app cli binaries to be the ones linked, then it ought to be completion scripts that are bundled with said binaries that are installed.

Without the cask installing the completion scripts, then from the perspective of the Docker.app bundle, the app installation isn't "complete". But what's more,  if the cask is linked _over top_ of the formula installation, then it would be the formula's completion scripts being invoked for the cask binaries. That is a recipe for version conflicts and/or incompatibility.

https://github.com/Homebrew/homebrew-cask/issues/59696

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Comment by MindTooth** [comment]
Is there a reason fish & zsh is not included?  Are they not included in the Docker.app release?

The reason I'm asking is that I usually install https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/docker-completion.rb too.  But if this change could include all three, that would be great.

**Comment by jasonkarns** [comment]
@MindTooth I'd be more than happy to include them, but I'm not a fish or zsh user so I'm not familiar with where they go.

**Comment by SMillerDev** [comment]
I think with this explanation it should rather conflict with `docker-completion`

**Comment by jasonkarns** [comment]
@MindTooth I just looked up the paths via the homebrew core helpers, so I'll add them momentarily

@SMillerDev ah, yes. that one, too. though since the docker formula includes the completion scripts now, perhaps the docker-completion formula will eventually be deprecated? I can add it for now, regardless. (in any case, the cask conflicts with the docker formula's binaries)

**Comment by cho-m** [comment]
Based on `uninstall`, it looks like there are potentially multiple Formulae conflicts.
Need someone who has installed Cask to confirm if these are added by Cask into `/usr/local/bin`
- `docker`
    ```
    /usr/local/bin/docker
    ```
- `docker-compose`
    ```
    /usr/local/bin/docker-compose
    ```
- `hyperkit`
    ```
    /usr/local/bin/hyperkit
    ```
- `kubernetes-cli`
    ```
    /usr/local/bin/kubectl
    ```

**Comment by MindTooth** [comment]
@jasonkarns I believe there are more conflicts. I reserve the right to be wrong on this though.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-compose-completion.rb
https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-machine-completion.rb

**Comment by jasonkarns** [comment]
@cho-m Confirmed and added. The binaries are linked during Docker.app first-boot (possibly on subsequent boots and/or upgrades as well)

@MindTooth docker-compose-completion, yes. docker-machine no.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
