### PR TITLE
konica-minolta-bizhub-c759-c658-c368-c287-c3851-driver: migrate from `homebrew/cask-versions`

### PR DESCRIPTION
**Pull request by viking1304**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

An older implementation kept failing during an audit for an unknown reason. Hopefully, this one will pass the audit. Made based on c751i implementation.

EDIT: Here we are again in the twilight zone. The audit for MacOS 13 passed, while it failed with the same file for MacOS 11 and 12.  🤯🤯🤯

EDIT 2: The strangest thing is that both install and uninstall worked as expected, but only the audit made a problem even though the file was already downloaded?!

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Thanks for submitting this, @viking1304! GitHub has been acting up today. 

Could you add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask?

**Comment by viking1304** [comment]
> Thanks for submitting this, @viking1304! GitHub has been acting up today.

A few months ago, while this cask was in the drivers repo, I had the same problem with it (unsuccessful audit in flow caused by timeout, while it worked fine on the local machine). I eventually gave up since no one had any idea what was wrong.

I noticed that c750i driver was migrated, so I rewrote this cask in the hope it would finally work, but strange timeout problems occurred again.

> Could you add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask?

I tried, but it didn't work.

Folder `/Library/Printers/KONICAMINOLTA/Preferences/jp.konicaminolta.printers.C759` and file `/Library/Printers/KONICAMINOLTA/Preferences/jp.konicaminolta.printers.C759.plist` should be trashed. 

They have those privileges and ownership:

```
drwxrwxrwx  2 root  admin   64 May  9 20:54 jp.konicaminolta.printers.C759
-rw-rw-r--  1 root  admin    0 May  9 20:54 jp.konicaminolta.printers.C759.plist
```

I tried a few different combinations with set_ownership and set_permissions in postflight, but everything always produces the warning "The following files could not be trashed, please do so manually"

```
==> Trashing files:
/Library/Printers/KONICAMINOLTA/Preferences/jp.konicaminolta.printers.C759
/Library/Printers/KONICAMINOLTA/Preferences/jp.konicaminolta.printers.C759.plist
==> Using sudo to gain ownership of path '/Library/Printers/KONICAMINOLTA/Preferences/jp.konicaminolta.printers.C759'
==> Using sudo to gain ownership of path '/Library/Printers/KONICAMINOLTA/Preferences/jp.konicaminolta.printers.C759.pli
Warning: The following files could not be trashed, please do so manually:
/Library/Printers/KONICAMINOLTA/Preferences/jp.konicaminolta.printers.C759
/Library/Printers/KONICAMINOLTA/Preferences/jp.konicaminolta.printers.C759.plist
```

btw. folder `/Library/Printers/KONICAMINOLTA` should not be touched since it is possible that someone also has C751i drivers installed. It can be removed only if `/Library/Printers/KONICAMINOLTA/Preferences` is empty.

**Comment by razvanazamfirei** [comment]
Thank you for adding that! We'll see if we can retry and get it to pass CI, otherwise I think syntax checking only is fine. Will wait to merge until the PR in homebrew-cask-drivers is merged.

**Comment by reitermarkus** [comment]
I think for the `konica-minolta` casks it's the `livecheck` that is timing out on `macos-11`.

**Comment by viking1304** [comment]
> I think for the `konica-minolta` casks it's the `livecheck` that is timing out on `macos-11`.

I think you were right. It passed `macos-11` now.

Unfortunately, it failed on `macos-13` due to an error during the download, but it should be fine in one of the next reruns.

**Comment by razvanazamfirei** [comment]
All good now! Thank you for submitting this!

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
