### PR TITLE
Add ZuluFX 15.0.1

### PR DESCRIPTION
**Pull request by bondolo**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [X] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by bondolo** [comment]
When (if) this pull request is accepted I will start on the cask-versions ones for zulufx7, zulufx8, zulufx11

**Comment by vitorgalvao** [comment]
[We’re currently not interest in more JDK variants](https://github.com/Homebrew/homebrew-cask/issues/57387), certainly not multiples of them.

**Comment by bondolo** [comment]
OK I guess. It is a little disappointing that most of my interactions with the Homebrew team have been abrupt bordering on hostile. Do y'all have any interest in new contributors or not?

I will encourage the Zulu folks to start their own tap.

**Comment by vitorgalvao** [comment]
> It is a little disappointing that most of my interactions with the Homebrew team have been abrupt bordering on hostile.

That’s unfortunate, and certainly not our intention. Speaking for myself, I remember seeing you before and I don’t think I‘ve treated you any differently from other users, and most don’t have a problem with our handling. “Hostile” definitely sounds too strong, but that’s your perspective.

> Do y'all have any interest in new contributors or not?

[90 different contributors](https://github.com/Homebrew/homebrew-cask/pulse) in the past week alone just on this repo seems pretty conclusive evidence we do. Maybe you’ve had bad luck in what you decided to contribute, or maybe other people search open issues before submitting—they’re not that many, we’re at 29 so this was definitely findable.

**Pull request closed without merging**
