### PR TITLE
created zap stanza for Mountain Duck 3.4.0.15624

### PR DESCRIPTION
**Pull request by guydebros**
There's a folder created by Mountain Duck that I _think_ may be shared with Cyberduck if it's installed. That folder shouldn't be zapped, unless there's a way to check if Cyberduck is or isn't installed. Or maybe there could be a message saying "you'll have to delete this yourself, but this is where to find it," or maybe a prompt for confirmation. But I have no idea how to do that, and I'm not sure how this is typically handled.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by ran-dall** [comment]
> There's a folder created by Mountain Duck that I think may be shared with Cyberduck if it's installed.

@guydebros How can we determine for sure? Also, I'm pretty sure that we'd prefer an absolute path when possible. Is there a reason we're globbing instead?

**Comment by vitorgalvao** [comment]
> That folder shouldn't be zapped, unless there's a way to check if Cyberduck is or isn't installed.

[That’s incorrect](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md):

> * Shared resources such as application updaters. Since shared resources may be removed, other applications may be affected by `brew cask zap`. Understanding that is the responsibility of the end user.

But as @ran-dall pointed out, make it an absolute path.

**Comment by guydebros** [comment]
Got it. I suggested the glob because the folder name starts with a random string of numbers and letters that I assumed was unique to my install. I've never paid close attention to those group containers. Do they have the same prefix each time on every machine? In that case the absolute path would work.

**Comment by ran-dall** [comment]
> Do they have the same prefix each time on every machine?

@guydebros I believe that is the `application-group-id`, which I believe is unique to each developer.

**Comment by guydebros** [comment]
Thanks, @ran-dall, [you're right](https://developer.apple.com/documentation/foundation/filemanager/1412643-containerurl). (I'm a novice so I have to learn these things one by one.) I'll fix this, and I'll search through my old PRs because I'm certain I did the same thing for a couple other casks.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
