### PR TITLE
android-platform-tools 34.0.4

### PR DESCRIPTION
**Pull request by alionar**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by p-linnane — DISMISSED** [review]
Why did the hash change without a version change? Was this re-released or something?

**Comment by aircraft-cerier** [comment]
I can reproduce this on my machine, and would really appreciate this to get approved and merged. TIA

**Comment by aircraft-cerier** [comment]
> Why did the hash change without a version change? Was this re-released or something?

I'm not sure, but when downloading the zip directly from https://developer.android.com/tools/releases/platform-tools and doing the following command I get the same sha256 that this change implements:

```
╰ openssl sha256 ~/Desktop/platform-tools_r34.0.4-darwin.zip
SHA2-256(/Users/brcerier/Desktop/platform-tools_r34.0.4-darwin.zip)= c60d9ee0acade673b649543b2d53c632ba54f9ca083ed612176105117fa16102
```

**Comment by miccal** [comment]
Thank you @alionar.

**Review by miccal — APPROVED** [review]

**Comment by chenrui333** [comment]
fixes https://github.com/orgs/Homebrew/discussions/4661

**Pull request merged**
