### PR TITLE
Update ghost to 1.0.0

### PR DESCRIPTION
**Pull request by megawubs**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by megawubs** [comment]
The install fails now. I see the name of the app inside the `.zip` file has changed.

**Comment by victorpopkov** [comment]
Thank you for noticing. Care submitting another PR with a fix?

**Comment by megawubs** [comment]
yes, but i'm not sure what's going wrong, seems to be something with the zip file name and the name of the app. Also, the folder `/usr/local/Caskroom/ghost` is not created

**Comment by victorpopkov** [comment]
There is a just a need to change line `app "ghost-#{version}-SIGNED/Ghost.app"` to `app 'Ghost.app'`.

**Comment by megawubs** [comment]
Yes i've noticed, but even after changing that it fails... I assume I can run `brew cask install ghost` while editing the file to see if it works? Or do I need another workflow for this to test?

**Comment by megawubs** [comment]
I keep getting 
```bash
==> Verifying checksum for Cask ghost
Error: It seems the App source is not there: '/usr/local/Caskroom/ghost/1.0.0/ghost-1.0.0/Ghost.app'
```
and when i look in `/usr/local/Caskroom/` there is indeed no `ghost` folder

**Comment by victorpopkov** [comment]
You can run `brew cask install` on a local file that has been changed inside a current directory:
```bash
brew cask install ghost.rb
```
In this way, the modified cask file will be used.

**Comment by megawubs** [comment]
Thanks! will try that

**Comment by megawubs** [comment]
Fixed in #26700

**Pull request merged**
