### PR TITLE
Update GoLand to 2018.1.3,181.4892.55

### PR DESCRIPTION
**Pull request by qinxin0720**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by qinxin0720** [comment]
Upgrading goland to 2018.1.3,181.4892.55
==> Satisfying dependencies
==> Downloading https://download.jetbrains.com/go/goland-2018.1.3.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask goland
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'goland' does not match.

Expected: da00d0c2be3b49b46c119f513f9421bf879f6902747ca60305339e5bc543c94a
Actual:   4665a52f6408224329874609afbbc38bda650ef86f2ea061ac0b5bc802fce3b7
File:     /Users/xxxxxx/Library/Caches/Homebrew/Cask/goland--2018.1.3,181.4892.55.dmg

To retry an incomplete download, remove the file above.

**Comment by commitay** [comment]
https://download.jetbrains.com/go/goland-2018.1.3.dmg.sha256

> da00d0c2be3b49b46c119f513f9421bf879f6902747ca60305339e5bc543c94a *goland-2018.1.3.dmg

**Comment by qinxin0720** [comment]
How can i upgrade this cask now?

**Comment by commitay** [comment]
```
File: /Users/xxxxxx/Library/Caches/Homebrew/Cask/goland--2018.1.3,181.4892.55.dmg

To retry an incomplete download, remove the file above.
```

If that doesn't work, it's a network issue.

**Comment by qinxin0720** [comment]
On my computer ,sha256 checksum for GoLand is 4665a52f6408224329874609afbbc38bda650ef86f2ea061ac0b5bc802fce3b7

➜  ~ cd `brew --cache`/Cask 
➜  Cask ll
total 535808
-rw-r--r--  1 qinxin  staff   202M  5 10 18:34 goland--2018.1.3,181.4892.55.dmg
-rw-r--r--  1 qinxin  staff    53M  5 11 12:46 visual-studio-code--1.23.1,d0182c3417d225529c6d5ad24b7572815d0de9ac.zip.incomplete
➜  Cask openssl dgst -sha256 goland--2018.1.3,181.4892.55.dmg            
SHA256(goland--2018.1.3,181.4892.55.dmg)= 4665a52f6408224329874609afbbc38bda650ef86f2ea061ac0b5bc802fce3b7
➜  Cask

**Comment by commitay** [comment]
```
brew cask audit --download goland
==> Downloading https://download.jetbrains.com/go/goland-2018.1.3.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask goland
audit for goland: passed

sha goland--2018.1.3,181.4892.55.dmg
da00d0c2be3b49b46c119f513f9421bf879f6902747ca60305339e5bc543c94a  goland--2018.1.3,181.4892.55.dmg
```

**Comment by qinxin0720** [comment]
➜  ~ brew cask audit --download goland  
==> Downloading https://download.jetbrains.com/go/goland-2018.1.3.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask goland
==> Note: running "brew update" may fix sha256 checksum errors
audit for goland: failed
 - download not possible: Checksum for Cask 'goland' does not match.

Expected: da00d0c2be3b49b46c119f513f9421bf879f6902747ca60305339e5bc543c94a
Actual:   4665a52f6408224329874609afbbc38bda650ef86f2ea061ac0b5bc802fce3b7
File:     /Users/qinxin/Library/Caches/Homebrew/Cask/goland--2018.1.3,181.4892.55.dmg

To retry an incomplete download, remove the file above.
Error: audit failed for casks: goland


May be it's a network issue ,Thank you very much!

**Comment by qinxin0720** [comment]
I switched network and used another computer,also audit failed!

**Comment by qinxin0720** [comment]
I know why it doesn't work,the official direct URL is https://download-cf.jetbrains.com/go/goland-2018.1.3.dmg. 
But on my computer, the URL is https://download.jetbrains.8686c.com/go/goland-2018.1.3.dmg,
8686c is a CDN link.

**Pull request merged**
