### PR TITLE
greenery: update checksum

### PR DESCRIPTION
**Pull request by tmrdev**
added 2FA to web3 requests, added purchase of crypto with Transak in Quick Exchange greenery id UI update, reveal password display in modal and vCard import bug fixed

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Duplicate of https://github.com/Homebrew/homebrew-cask/pull/167509

**Comment by tmrdev** [comment]
Did the brew bump get initiated because the version of Greenery was updated on our Releases.Greenery repo?  I noticed a bug in the macOS release and I provided a fix for it and pushed a PR for it yesterday.  It has the correct sha256 value which should be:

5f062694ea82a4e97ed248b896cb7c565437a8c36221aeb85df28f97d2e78a12

The brew bump that was executed set an incorrect checksum.

**Comment by p-linnane** [comment]
> I noticed a bug in the macOS release and I provided a fix for it and pushed a PR for it yesterday.

This is why the checksum in https://github.com/Homebrew/homebrew-cask/pull/167509 is wrong. You altered the release after it was published. Once you release something you should expect that it has already been consumed in some way and make changes under an incremented version number instead. The [Git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) discusses this:

> But if you have pushed things out (or others could just read your repository directly), then others will have already seen the old tag. In that case you can do one of two things:
> 
> The sane thing. Just admit you screwed up, and use a different name. Others have already seen one tag-name, and if you keep the same name, you may be in the situation that two people both have "version X", but they actually have different "X"'s. So just call it "X.1" and be done with it.
> 
> The insane thing. You really want to call the new version "X" too, even though others have already seen the old one. So just use git tag -f again, as if you hadn’t already published the old one.

Though this calls out tags specifically, this also applies to pre-compiled binaries. A change in checksum may indicate tampering with the release by a malicious party and should be avoided.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
