### PR TITLE
 Add PrusaSlicer 2.0.0-rc 

### PR DESCRIPTION
**Pull request by ulab**
Quoting https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.0.0-rc:
> As the Slic3r Prusa Edition diverged from the original Slic3r significantly, we decided to rename the project to PrusaSlicer. The community used the Slic3r and Slic3r PE names pretty much interchangeably, which lead to confusion.

This cask replaces prusa-slic3r, since upstream decided to rename the application for above mentioned reasons. I have added a corresponding conflict with prusa-slic3r to my cask, but prusa-slic3r might need to have a conflict added with this one too.

I have found no other information on how to handle a renaming like this.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by ran-dall** [comment]
@ulab Just a note; you're PR is flooded with additional commits. Would you mind cleaning it up, please? You should only have one commit for this PR (`Add PrusaSlicer 2.0.0-rc`) and all the others should be removed.

**Comment by ulab** [comment]
I am not sure where they are coming from :-/. Those are previous pull requests I did before and which already got accepted...

**Comment by ulab** [comment]
Ok, looks like rebasing did the trick.

**Review by ran-dall — APPROVED** [review]

**Comment by ran-dall** [comment]
Just a note: `prusa-slic3r` already exsits; and should probably be removed in favor of this PR, should this PR be merged.

**Comment by ulab** [comment]
That's why I mentioned: 

>  I have added a corresponding conflict with prusa-slic3r to my cask, but prusa-slic3r might need to have a conflict added with this one too.

And yes, it probably should be removed, but I have no idea what the procedure is. 

Is there an option to tell people about the new cask? "prusa-slic3r got replaced by prusaslicer" or similar?

**Comment by ran-dall** [comment]
@ulab 👉 If you check out your branch and delete `prusa-slic3r.rb` file from the `casks` directory; you'd then be able to commit the delete of that cask to this PR, and push it back here. That way, we make sure it's deleted when this gets merged; if it does...

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
