### PR TITLE
update git-annex.rb conditional to use fallthrough

### PR DESCRIPTION
**Pull request by rolandwalker**
git-annex is not system-specific software, and should not stop working on a new release.  Also, attempt to install the Lion build on older releases.

Clarify fallthrough comments in the cases where software is expected to cease working under a new release.

### CODE REVIEW

**Comment by ndr-qef** [comment]
@vitorgalvao, I would appreciate your comment here. This PR was prompted by my confusion with regard to our use of empty conditional branches.

If you agree with the changes, feel free to merge.

**Comment by vitorgalvao** [comment]
The new wording is clearer and more accurate, so I like that on a first look.

However, can’t really say I agree with the change to `git-annex`. Although the comment is true and hence the change is logical, it is a difficult rule to follow. It demands we as maintainers have a working knowledge of the apps, to know if they break on new versions of OS X or not.

From looking at the `git-annex` cask, it seems reasonable to assume a new version will be made available for the new OS X version, but it isn’t clear to me the Lion version works on versions older than Lion, which the change suggests.

I have never used the app or followed its development, though, so I have absolutely no idea of the probability of it being discontinued or about its working conditions previously to Lion, and that is exactly my point: we need a rule we as maintainers can consistently apply. While I have no issue with using the oldest version for “everything older than”, having the newest version be specific some times and not others *when the corresponding OS X version is on the url, and there is one for every version up to the current one*, I do find it confusing and (more importantly) hard to track (what was intentional; what was a mistake?).

In the eventuality it stops being developed (let’s say on the next OS X version), we should then change it to how it is in this PR, *but* add a comment about it’s possible “breakability”. This should be done to explain it is an exception to the rule (much like comments added to cask with a version and `sha256 :no_check`).

So I believe `git-annex` should be unchanged in that regard, and that the wording should be changed to something a bit more speculative:

```
Unusual case: there is no fall-through.  The software should stop
working or be dangerous to run on the next OS X release.
```

**Comment by jawshooah** [comment]
Agreed with @vitorgalvao, although I may of course be biased, being the last one to change the `git-annex` cask.

Permitting OS X releases older than Lion to use the Lion version seems dangerous to me; this software, as a layer on top of `git`, does a lot of low-level file management, and I fear that using a version built for a later release has the potential to cause data corruption or loss.

Pinging the maintainer on this. @joeyh, would you care to weigh in?

On an unrelated note, just a minor quibble: I think the wording ought to be "...The software _may_ stop working...". This is both more accurate and more broadly applicable, and would thus be more suitable as a standard warning message.

**Comment by vitorgalvao** [comment]
@jawshooah I actually thought of “The software *might* stop” initially, but that just sounded to vague, as any software might stop working on a new OS version. With *should* it sounds to me as “it likely will stop working, though we can’t say for certain”.

**Comment by vitorgalvao** [comment]
Ah, of course, I was thinking about it absolutely reversed. These are the exception; the rule is the opposite. That still requires us to have some working knowledge of the casks themselves, but is then a much easier task since it’ll happen rarely.

Understood and agreed. I’ll let it to you to merge still, in case you decide you want to make modifications to the “older than Lion” part, following @joeyh’s comments.

**Pull request merged**
