### PR TITLE
Update zoomus from 4.6.19178.0323 to 4.6.19273.0402

### PR DESCRIPTION
**Pull request by yurikoles**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ryanrishi** [comment]
@yurikoles you might need to add `pkgutil` to the uninstall section, lines 19-28:

```diff
uninstall
# existing entries: quit, signal, login_items, delete
+ pkgutil: 'us.zoom.pkg.videmeeting'
```

See [uninstall](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md)

**Comment by core-code** [comment]
i think we should also add warning stanza here as this "software" probably has the worst security track record of anything every published for macOS (of course except Adobe products).

**Comment by yurikoles** [comment]
Nice suggestion, @core-code. But this is against HBC policy, I had made similar proposal for VSCode, which itself OpenSource project under MIT license, but its binaries had a lot of added telemetry and are distributed under EULA. @vitorgalvao ended up rejecting my proposal with motivation that HBC is not a Wikipedia, we provide way to install binaries and its up to user to make research about particular program pros and cons.

**Comment by vitorgalvao** [comment]
> @vitorgalvao ended up rejecting my proposal with motivation that HBC is not a Wikipedia, we provide way to install binaries and its up to user to make research about particular program pros and cons.

“[Not a discoverability service](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md)” are likely to have been my words, but yes, the sentiment is correct.

Though we do make an exception for malware (by removing it), which is as of now mostly detected by @core-code’s automated checks.

**Pull request merged**
