### PR TITLE
 adrive 6.1.0 update shasum 256

### PR DESCRIPTION
**Pull request by craone**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by khipp** [comment]
Thank you for your contribution, @craone! Would you mind contacting upstream to verify whether the binaries were updated in-place intentionally or if someone might have tampered with them?

**Comment by craone** [comment]
> Thank you for your contribution, @craone! Would you mind contacting upstream to verify whether the binaries were updated in-place intentionally or if someone might have tampered with them?

Sure, just a moment please.

**Comment by craone** [comment]
> Thank you for your contribution, @craone! Would you mind contacting upstream to verify whether the binaries were updated in-place intentionally or if someone might have tampered with them?

Did not reply to me, the customer service URL is: [https://cs-center.alipan.com/](https://cs-center.alipan.com/index/selfservice?a=a&uc_param_str=&build_ver=6.1.4-web&instance=alipan_pc&browser_info=Chrome+127.0.0.0+%28Blink%29&enUid=&system_ver=OS+X+10.15.7+64-bit&app_ver=6.1.4&self_service=true&platform=web#/)

**Comment by khipp** [comment]
Thank you for your patience. Since there is no precedent for this happening with this cask, I am inclined to wait for a response from upstream or for the upcoming release, which should not be that far out either.

**Comment by p-linnane** [comment]
Let's wait for the next release.

**Pull request closed without merging**
