### PR TITLE
Add Twitch TV App Latest

### PR DESCRIPTION
**Pull request by jdaltonchilders**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

`brew cask style` returns an error regarding the mismatch between the url and homepage. The name of the application is `Twitch`, but a different application exist which is also named [twitch](http://twitchapp.com/). This is why I've named the cask `twitch-tv`.

### CODE REVIEW

**Comment by MTCoster** [comment]
Isn't this the same as https://github.com/caskroom/homebrew-cask/blob/master/Casks/twitch.rb?

**Comment by giannitm** [comment]
@MTCoster I concur...

**Comment by vitorgalvao** [comment]
@MTCoster Looks like the same, yes.

@jdaltonchilders The token reference is in place precisely to avoid these cases. However, you mention the other cask, so you saw it. Why submit this one? What’s the difference?

**Comment by jdaltonchilders** [comment]
I would appear so...for some reason it never showed up when I checked.

**Comment by jdaltonchilders** [comment]
@vitorgalvao The other application is different, but it appears my cask was out of date.

**Pull request closed without merging**
