### PR TITLE
Update ssdreporter-free from 1.6.0,1542 to 1.6.0,1575

### PR DESCRIPTION
**Pull request by jabenninghoff**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by jabenninghoff** [comment]
@miccal shouldn't the token name change too? maybe @core-code can weigh in here?

**Comment by jabenninghoff** [comment]
What's odd is that the app name changed for `ssdreporter-free` but not `smartreporter-free`...

**Comment by miccal** [comment]
> @miccal shouldn't the token name change too? maybe @core-code can weigh in here?

[Yes it should, but I will now be doing it after the last time I changed an existing Cask to follow the token reference.](https://github.com/Homebrew/homebrew-cask/pull/114668)

**Comment by jabenninghoff** [comment]
> > @miccal shouldn't the token name change too? maybe @core-code can weigh in here?
> 
> [Yes it should, but I will not be doing it after the crap from last time I changed an existing Cask to follow the token reference.](https://github.com/Homebrew/homebrew-cask/pull/114668)

Hard to argue that, although I did just create this cask a couple of days ago

**Comment by miccal** [comment]
I will let another maintainer decide to merge or re-name.

**Comment by bevanjkay** [comment]
Given that the cask is young, better to change it now than when it gets more popular.

**Comment by core-code** [comment]
i don't see any point in having two casks. SSDReporter is SSDReporter only one version exists. 

the name change to append 'free' in the filesystem has been performed for one single reason, so that the name is different from the previous MAS version. the point being is that a possible previously-bought MAS version will still be around (instead of replaced) and the 'license' can be imported on launch.

**Comment by jabenninghoff** [comment]
@core-code, I think you may have figured this out already, but the confusion was because SSDReporter was released as "SSDReporter" instead of "SSDReporter Free" at one point. @miccal @bevanjkay I've submitted PR #117100, renaming this back to ssdreporter-free, which appears to be the proper name going forward.

**Pull request merged**
