### PR TITLE
Update camtasia from 2020.0.0 to 2020.0.1

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
committing myself because this fixes problems with the previous commit

**Comment by ran-dall** [comment]
@core-code Are you talking about the ML update to 2020.0.0?

**Comment by core-code** [comment]
yes the version number was/is actually 20.0.1

i guess the information in the appcast didn't contain 20.0.1 by then?

**Comment by ran-dall** [comment]
> i guess the information in the appcast didn't contain 2020.0.1 by then?

@core-code Confirmed. I just checked.

**Pull request merged**
