### PR TITLE
Add `zap` for Squidman.

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Review by gobinathm — COMMENTED** [review]
@reitermarkus verified locally

for some reason in my machine the folder didn't get deleted

```
/usr/local/squid
```

**Comment by gobinathm** [comment]
@vitorgalvao Copied the Cask locally and tried it


<details><summary>#Current Working Directory `$ pwd`</summary>

```
/usr/local
```
</details>

<details><summary>#List of Current Working Directory `$ ls`</summary>

```
Caskroom	Frameworks	bin		include		opt		sbin		var
Cellar		Homebrew	etc		lib		remotedesktop	share
```
</details>

Downloaded squidman cask from [reitermarkus's fork](https://raw.githubusercontent.com/reitermarkus/homebrew-cask/squidman/Casks/squidman.rb)

<details><summary>#installed locally copied squidman cask`$ brew cask install squidman.rb`</summary>

```
==> Caveats
Cask squidman installs files under "/usr/local". The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in Homebrew-Cask.

==> Downloading http://squidman.net/resources/downloads/SquidMan3.8.dmg
Already downloaded: /Users/gobinathm/Library/Caches/Homebrew/Cask/squidman--3.8.dmg
==> Verifying checksum for Cask squidman
==> Moving App 'SquidMan.app' to '/Applications/SquidMan.app'
🍺  squidman was successfully installed!
```
</details>

<details><summary>/usr/local after install & first run of the app `$ ls`</summary>

```
Caskroom	Frameworks	bin		include		opt		sbin		squid
Cellar		Homebrew	etc		lib		remotedesktop	share		var
```
</details>

<details><summary>`$ brew cask uninstall squidman.rb`</summary>

```
==> Removing App: '/Applications/SquidMan.app'
```
</details>

<details><summary># /usr/local after uninstall `$ ls`</summary>

```
Caskroom	Frameworks	bin		include		opt		sbin		squid
Cellar		Homebrew	etc		lib		remotedesktop	share		var
```
</details>

Curious, am I testing it wrong ?



<details><summary>Output of  `$ brew doctor`</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  macvim
  php70
```
</details>

<details><summary>Output of  `$ brew config`</summary>

```
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e5e1865873238e44e2068d277dbb2d4ae357a917
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_121
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```
</details>

**Comment by vitorgalvao** [comment]
> am I testing it wrong ?

Yes. You did `brew cask uninstall` instead of `brew cask zap`.

**Comment by gobinathm** [comment]
Right 👍  i was doing it wrong.   This works perfect 

 Off Topic Question, shouldn't we info user that they should be using Zap instead of uninstall  ?

**Review by gobinathm — APPROVED** [review]

**Comment by vitorgalvao** [comment]
> shouldn't we inform the user that they should be using Zap instead of uninstall

No, because they shouldn’t. `zap` or `uninstall` is a user choice. If this were needed, it would be in `uninstall`.

**Comment by reitermarkus** [comment]
@vitorgalvao, thanks for fixing this so quickly. 👍

**Pull request merged**
