### PR TITLE
add hotkey-eve

### PR DESCRIPTION
**Pull request by exherb**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
The [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_token_reference.md) must be followed, to avoid duplicates.

This cask does not follow it, and is indeed [a duplicate](https://github.com/caskroom/homebrew-cask/blob/master/Casks/eve.rb).

**Comment by Ngrd** [comment]
Thank you, @vitorgalvao. Good catch!

**Comment by exherb** [comment]
Why simply close it?

**Comment by jawshooah** [comment]
Because this cask [already exists](https://github.com/caskroom/homebrew-cask/blob/master/Casks/eve.rb).

**Comment by exherb** [comment]
sorry, I thought this "EVE" is the game.

**Pull request closed without merging**
