### PR TITLE
Update sensei from 1.2.16,68 to 1.3,71

### PR DESCRIPTION
**Pull request by core-code**
Created with `brew bump-cask-pr`.

---

Automatically created and submitted by muUpdateStaticHomebrewCask

### CODE REVIEW

**Comment by miccal** [comment]
@reitermarkus would adding the `-Q` and/or the `--no-warn` flag [here](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/unpack_strategy/xz.rb#L33) help with this error?

This may also help with https://github.com/Homebrew/homebrew-cask/issues/92674.

**Comment by peterlewis** [comment]
> This may also help with #92674.

Just to report back my experience:

- I tested adding `-Q` and this just caused a never-ending loop of attempts, to no avail
- I tested adding `--no-warn` and this too caused a never-ending loop of attempts.

**Comment by peterlewis** [comment]
Howdy! Just an update - After a big more digging, I believe that the cause of the issue raised in #92674 may be different to this one.

**Comment by core-code** [comment]
so is this just a CI failure in which case we should use ci-skip-install or a 'real' problem?

**Comment by miccal** [comment]
> so is this just a CI failure in which case we should use ci-skip-install or a 'real' problem?

I am having a similar issue with Little Snitch after upgrading to Big Sur, and I will try to investigate this further on the weekend. Perhaps hold-off merging this until then?

**Comment by core-code** [comment]
sure sounds good. not keen on merging something that might be a real error.

**Comment by core-code** [comment]
do the checks not run automatically anymore after pushing or adding labels?

**Comment by miccal** [comment]
Trying out https://github.com/Homebrew/brew/pull/9161

**Comment by miccal** [comment]
Thank you again @peterlewis.

**Pull request merged**
