### PR TITLE
Upgrade to Sage 9.5 release, support M1 

### PR DESCRIPTION
**Pull request by dconnolly**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by dconnolly** [comment]
Failures are because the 9.5,1.3 release is still marked as prerelease on GitHub, Sage 9.5 is stable and the [Sage_macOS](https://github.com/3-manifolds/Sage_macOS) 1.3 release has been out there for 20 days with no problems. I have pinged the maintainer to see if they are good to promote 1.3 to a stable release.

https://github.com/3-manifolds/Sage_macOS/issues/36

**Comment by miccal** [comment]
@dconnolly thank you for this. I have added this Cask to our list of allowed GitHub prereleases and updated the `livecheck` to now work with the Intel and Arm releases. Let's give it a few more days as suggested by upstream [here](https://github.com/3-manifolds/Sage_macOS/issues/36#issuecomment-1030350690), then we can merge this.

**Pull request merged**
