### PR TITLE
Remove fugu

### PR DESCRIPTION
**Pull request by razvanazamfirei**
Livecheck Status: Discontinued
Last Update: 2015

### CODE REVIEW

**Comment by SMillerDev** [comment]
When was de caveat added?

**Comment by razvanazamfirei** [comment]
Feb 8th. If there's any guidance on how long to wait before removing, please let me know.

**Comment by bevanjkay** [comment]
We generally haven't removed casks unless they are troublesome, or the annual downloads are very low (below 15-20). 
In the case of `fugu` it has had 713 downloads in the last year so we wouldn't consider removal.

**Comment by SMillerDev** [comment]
> Feb 8th. If there's any guidance on how long to wait before removing, please let me know.

For formula we wait a year: https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae#removal

**Pull request closed without merging**
