### PR TITLE
Update qiyimedia from 5.9.11 to 5.10.10

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
`appcast at URL 'https://app.iqiyi.com/mac/player/index.html' does not contain the version number: '5.10.10'`
unfortunately true - they haven't updated the version on the website until now but the downloaded version is 5.10.10 - I also can't find a better appcast … should we add a 'configuration: no-check' here? @vitorgalvao @core-code?

**Comment by core-code** [comment]
i am not sure. lets see what vitor prefers

**Comment by vitorgalvao** [comment]
The download redirects to a path that doesn’t have the version number, but it does have a date: `http://59.52.16.9/cdn/pcclient/20190628/16/33/iQIYIMedia_000.dmg`. We could add `20190628` as `after_comma`, and make the appcast your `cgi`.

Presumably you’re downloading it anyway to confirm the version, so maybe the redirected URL can be considered in that process?

**Comment by core-code** [comment]
good idea! we can use
version '20190628,5.10.10'
appcast 'https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://mbdapp.iqiyi.com/j/ot/iQIYIMedia_000.dmg'

**Comment by suschizu** [comment]
thanks :)

**Comment by core-code** [comment]
ugh, a minute ago it was working. chinese servers...

**Comment by vitorgalvao** [comment]
It’s all the same to me, but wouldn’t you rather have the real version before the comma?

**Comment by core-code** [comment]
thanks for considering. its the same for us too, just a different 'mapping number' so it doesn't matter. by having the date first we can avoid a 'configuration' for the appcast, thats why i suggested it this way.

**Pull request merged**
