### PR TITLE
Update mro to 3.3.1

### PR DESCRIPTION
**Pull request by marcionicolau**
#### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 1638f20cdb596551fbb6e26746560ba42cd14832. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by marcionicolau** [comment]
Hi @vitorgalvao I need to change the name too? I'll proceed with recommended fixes

**Comment by vitorgalvao** [comment]
The fixes are already implemented and merged. No need to worry.

**Comment by marcionicolau** [comment]
Ok! many thanks @vitorgalvao

**Pull request closed without merging**
