### PR TITLE
Add R2 v1

### PR DESCRIPTION
**Pull request by philihp**
R2 is a winning entry in the San Francisco Stupid Sh*t No One Needs and Terrible Ideas hackathon. It's a program that adds musical tones to every keystroke and mouse click to make your computer more futuristic.

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution and interest, @philihp.

While this technically passes letter of the law for [the obscurity threshold](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md), I’d say it does not really pass the spirit of it.

This is a self-proclaimed useless app that is self-submitted. It’s unnecessary overhead for us with absolutely no gain. It’s one more app to have to deal with when abandoned.

Pinging @miccal and @adidalal since you were involved in the discussion of where the threshold should be. I see your point on 50 stars being high, but when a cask is self-submitted, I think the threshold should be higher.

**Comment by miccal** [comment]
I agree with your assessment @vitorgalvao.

**Comment by philihp** [comment]
Okay cool, so the requirement is 50 stars or someone else submits the PR, and it would be accepted?

**Comment by vitorgalvao** [comment]
@philihp You’re missing the point. The [puppy analogy](https://twitter.com/ncoghlan_dev/status/598146064508538880) is useful, here: you’re giving us extra overhead for nothing. This is, by your own admission, a useless app.

**Comment by reitermarkus** [comment]
@philihp, consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) instead.

**Comment by philihp** [comment]
@reitermarkus thank you, that's a great idea. I'll make my own tap. <sup>with blackjack <sup>and hookers <sup>matter of fact...</sup></sup></sup>

**Comment by vitorgalvao** [comment]
@philihp Link to it here. That way if someone happens to land here in the future, they’ll know where to look.

**Comment by philihp** [comment]
Check it, Holmes. Tryna get your cutty app into caskroom, but they bouncer turn you away at the door cuz you only got the bare minimum pieces of flair? Instead, it's easier to make your own cask like this: https://github.com/philihp/homebrew-casket. Now I just tell my mates

    brew cask install philihp/casket/r2

This is probably even better, because now when I release a new version I ain't gotta PR back to caskroom. Instead, I can just update my own repo easy. Cut out the middle man, yadadamean? Peace.

**Pull request closed without merging**
