### PR TITLE
Update jump-desktop-connect from 6.7.69 to 6.8.91

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@p-linnane Wildcards aren't currently supported in `launchctl`
https://github.com/Homebrew/homebrew-cask/issues/79661

**Comment by p-linnane** [comment]
Boo. Not sure what we should do here then. What do you think @bevanjkay?

**Comment by bevanjkay** [comment]
@p-linnane It looks like this could well be an upstream regression. The uninstall script that is provided doesn't include a UUID in the launchctl section, it mirrors our prior uninstall stanza.

**Comment by p-linnane** [comment]
Closing this and will see what happens with the next release.

**Pull request closed without merging**
