### PR TITLE
Okapi

### PR DESCRIPTION
**Pull request by jbeagley52**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Note for other maintainers. I haven’t yet verified the url.

**Comment by neutric** [comment]
@jbeagley52 Are Okapi and Okapi-Apps two different things, or why the two otherwise identical files? 

Also, the version is referred to as M32 (see [here](https://twitter.com/OkapiFramework/status/826452183558205440) and [here](https://bintray.com/okapi/Distribution/Okapi_Applications/M32)), so it is probably better to use `version 'M32'` and then further down interpolate with e.g. `0.#{version.delete('M')}` instead of `#{version}`.

**Comment by neutric** [comment]
The URL is okay:
```bash
% curl -I "https://bintray.com/okapi/Distribution/download_file?file_path=okapi-apps_cocoa-macosx-x86_64_0.32.dmg"
HTTP/1.1 302 Found
Server: nginx
Date: Mon, 20 Feb 2017 18:42:38 GMT
Content-Length: 0
Connection: keep-alive
Location: https://dl.bintray.com/okapi/Distribution/okapi-apps_cocoa-macosx-x86_64_0.32.dmg
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000; preload
```

**Comment by vitorgalvao** [comment]
> The URL is okay

I don’t mean verify it works, I mean verify it is indeed official.

**Comment by vitorgalvao** [comment]
> @jbeagley52 Are Okapi and Okapi-Apps two different things, or why the two otherwise identical files?

Agreed. Please delete the `-apps` one. If there’s something we don’t want, are duplicates.

**Comment by neutric** [comment]
>> The URL is okay
>I don’t mean verify it works, I mean verify it is indeed official.

I know, I did that and then resolved the URL that is listed on the [page](https://bintray.com/okapi/Distribution/Okapi_Applications/M32) a couple of clicks away from okapiframework.org. Probably should have used a few more words. :)

**Comment by neutric** [comment]
@vitorgalvao My bit about the version number was unnecessary then?

**Comment by vitorgalvao** [comment]
> @vitorgalvao My bit about the version number was unnecessary then?

We don’t really care about accurate versions. We do care about interpolating it to make casks easier to update. In that vein, If a `url` does not contain the software’s version but it contains a long hash that changes every version, we’d rather use the hash for the `version` than the actual version. That said, in those cases we usually add both, separated by a comma (because then we have the easy `after_comma` and `before_comma`).

**Comment by neutric** [comment]
> We don’t really care about accurate versions. We do care about interpolating it to make casks easier to update.

Understood, thanks. :)

**Comment by jbeagley52** [comment]
@neutric They're the same thing. I originally used Okapi-Apps because of
the filename on the website, but the token generator suggested just okapi.
And I'm still useless with git, so I didn't realise I submitted both files!

**Comment by vitorgalvao** [comment]
@jbeagley52 Feel free to close and resubmit, it that’s easier for you.

**Comment by jbeagley52** [comment]
I hope this did the trick because I honestly have no idea what I'm doing when it comes to Git!

**Comment by jbeagley52** [comment]
By the way, @vitorgalvao, this needs
`target: 'Okapi'`
or else the resulting folder in /Applications will contain the version number.

**Comment by reitermarkus** [comment]
> I hope this did the trick because I honestly have no idea what I'm doing when it comes to Git!

`brew cask install git-it` 😄

**Comment by neutric** [comment]
> By the way, @vitorgalvao, this needs
> `target: 'Okapi'`
> or else the resulting folder in /Applications will contain the version number.

I am fairly certain that Vitor will just repeat himself, as he has commented on this issue [before](https://github.com/caskroom/homebrew-cask/pull/30251#discussion_r102017550): [`target:` Should Only Be Used in Select Cases](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md#target-should-only-be-used-in-select-cases) and avoiding version numbers in folder names for cosmetic reasons is not one of them.

Thanks for not giving up on this one! :)

**Pull request merged**
