### PR TITLE
Etrecheck: update license to GPL

### PR DESCRIPTION
**Pull request by martinlindhe**
License is GPL according to https://github.com/etresoft/EtreCheck/blob/master/LICENSE

### CODE REVIEW

**Comment by jawshooah** [comment]
You seem to have accidentally included a change to `natron.rb` in this PR. That must be removed before this can be merged.

**Comment by martinlindhe** [comment]
@jawshooah: yes, i based this branch on another PR branch, and apparantly failed to reset it.

Trying to fix it up and --force push changes here

**Comment by martinlindhe** [comment]
Should be correct now!

**Comment by jawshooah** [comment]
Thank you for the contribution. It was merged directly as 1269ade300353003e2603511af8de4d54e21827a to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
