### PR TITLE
Add hashicorps repo appcasts

### LINKED ISSUE #19988: Add appcasts to hashicorp casks
Missing `appcast`:

- [ ] [consul-web-ui.rb](../blob/master/Casks/consul-web-ui.rb)
- [ ] [nomad.rb](../blob/master/Casks/nomad.rb)
- [ ] [otto.rb](../blob/master/Casks/otto.rb)
- [ ] [packer.rb](../blob/master/Casks/packer.rb)
- [ ] [serf.rb](../blob/master/Casks/serf.rb)
- [ ] [vagrant.rb](../blob/master/Casks/vagrant.rb)
- [ ] [vault.rb](../blob/master/Casks/vault.rb)

### PR DESCRIPTION
**Pull request by samshadwell**
To resolve #19988

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you! Just need to squash those commits.

Also, tip for the future. If you include `Fixes #issue_number` or `Closes #issue_number` in the commit message, it automatically closes said issue when merged.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in b43b81d80661f38b6fe94c3f6262c862942d6fb3. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by samshadwell** [comment]
Ah, my mistake. I knew I was forgetting something. What were the fixes that needed to be made? Looking at the other commit you linked I can't figure out what's different. I also diff-ed the consul-web-ui one and there didn't appear to be differences (and I got lazy and didn't do the others).

**Comment by vitorgalvao** [comment]
> What were the fixes that needed to be made?

Just the squashing. But that’s [the stock message](https://github.com/vitorgalvao/tiny-scripts/blob/ef7577ab9edebccfb9bb621447aeeb1334359293/prfixmaster#L109) embedded in [`prfixmaster`](https://github.com/vitorgalvao/tiny-scripts/blob/master/prfixmaster).

**Pull request closed without merging**
