### PR TITLE
Update wechat from 2.3.27.17 to 2.3.27.18

### PR DESCRIPTION
**Pull request by vincent-guo**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vincent-guo** [comment]
It's weird.  The appcast at URL 'https://dldir1.qq.com/weixin/mac/mac-release.xml' contains the version number: '2.3.27.18', and the checksum for the newest version  of cask 'wechat' is '721185cdcb7bd4672252a7660d5ba8d582e380007482ea340eee4cd401cb7c9f'.

**Comment by vitorgalvao** [comment]
> The appcast at URL 'https://dldir1.qq.com/weixin/mac/mac-release.xml' contains the version number: '2.3.27.18'

Not for me, and not for CI. Might be taking a bit to propagate, let’s take another look later.

**Comment by vincent-guo** [comment]
For me, 'https://dldir1.qq.com/weixin/mac/mac-release.xml' show me this:

**Comment by huxuan** [comment]
Can we trigger the CI again? I suppose it may be caused by cache/cdn or something similar.

**Comment by reitermarkus** [comment]
Checksum seems to be correct now, and the appcast contains `2.3.27.18` for me locally.

**Comment by vincent-guo** [comment]
I change the version and sha256 in my computer, and install it successfully.
WX20191011-172511@2x

**Comment by vitorgalvao** [comment]
@reitermarkus If it’s working for you, I see no issue with merging.

For reference, I still get the outdated appcast.

**Pull request merged**
