### PR TITLE
Update kitty from 0.24.1 to 0.24.2

### PR DESCRIPTION
**Pull request by lithammer**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by lithammer** [comment]
https://sw.kovidgoyal.net/kitty/changelog/#id1

**Comment by page-down** [comment]
In kitty version 0.24.2, the state of `secure keyboard entry` will be saved.
The following path needs to be added to `zap trash`.

```text
~/Library/Preferences/net.kovidgoyal.kitty.plist
```

**Comment by lithammer** [comment]
Good call! Fixed.

**Comment by carlocab** [comment]
Doesn't this also leave a `~/.config/kitty`?

**Comment by carlocab** [comment]
Screenshot 2022-02-03 at 15 55 13

Barely beaten to the punch... @miccal

**Comment by lithammer** [comment]
> Doesn't this also leave a `~/.config/kitty`?

I suppose so 🤔

**Comment by page-down** [comment]
User-written `kittens` (python scripts) are also here, should they all be removed?

```text
Should zap trash user-generated content? #10156
https://github.com/Homebrew/homebrew-cask/issues/10156

Decided as yes. Zapping should remove everything.
```

I guess it's yes.

**Comment by carlocab** [comment]
Cool. Let's zap `~/.config/kitty`, then. Any takers on a PR?

**Comment by lithammer** [comment]
> Cool. Let's zap `~/.config/kitty`, then. Any takers on a PR?

https://github.com/Homebrew/homebrew-cask/pull/118596

**Pull request merged**
