### PR TITLE
Update thingsmacsandboxhelper to 3.11

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
Update found by URL sniffing, although it is the same as on the stated homepage.

I do think this should probably be renamed to `things-helper` or something similar, and perhaps the `things` cask added (there is a 15-day trial). Rationale being it is strange to have a helper and not the root program available, and the naming convention would not help anybody looking for this actually find it IMHO.

Thoughts?

**Comment by commitay** [comment]
> I do think this should probably be renamed to things-helper

https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md

> and perhaps the things cask added (there is a 15-day trial).

https://github.com/caskroom/homebrew-cask/pull/34955

**Comment by brianmorton** [comment]
@commitay thank you, I am aware. Their own website references it as `Things Helper` and it is marketed as such. So much to the technical chagrin of developers, I would contend it should be named the same here... no matter if the actual app is slightly different. But I don't really care, other than trying to help people at large.

#34955 is outdated, it is available as a stand-alone DL from their homepage:
https://culturedcode.com/things/download/

**Comment by commitay** [comment]
Can the trial be upgraded to the full version?

**Comment by brianmorton** [comment]
things

**Comment by commitay** [comment]
So the full version has to be downloaded from MAS.

> I would contend it should be named the same here... no matter if the actual app is slightly different

I concede that following the token reference sometimes leads to nonsensical naming but it was implemented because of severe problems with duplicates.  We still get PRs for "new" Casks because they don't follow the token reference.

**Pull request merged**
