### PR TITLE
add Mob v0.1.2

### PR DESCRIPTION
**Pull request by zenghongtu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Refs https://github.com/Homebrew/homebrew-cask/pull/63167#issuecomment-491636193.

How did you go from less than 10 to over 90 stars in 12 hours?

**Comment by zenghongtu** [comment]
> Refs [#63167 (comment)](https://github.com/Homebrew/homebrew-cask/pull/63167#issuecomment-491636193).
> 
> How did you go from less than 10 to over 90 stars in 12 hours?

I'm posting to V2EX ([here](https://www.v2ex.com/t/563475#reply39)) and say I need 50 stars.

A lot of friends get me a star, it's beyond my expectation.👻👻👻so so so happy!

**Comment by vitorgalvao** [comment]
Feels a bit like gaming the system, but let’s include it anyway. Thank you for being honest! And congratulations on rising so fast.

**Comment by zenghongtu** [comment]
> Feels a bit like gaming the system, but let’s include it anyway. Thank you for being honest! And congratulations on rising so fast.

Thank you very much😀

**Pull request merged**
