### PR TITLE
updated yate (3.12)

### PR DESCRIPTION
**Pull request by ghost**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by fanquake** [comment]
Do the `version` and `checkpoint` need updating also?

**Comment by vitorgalvao** [comment]
@fanquake Seems they are correct.

@wickedsp1d3r Are you sure the download is correct? Travis seems to be getting the wrong shasum.

**Comment by wickedsp1d3r** [comment]
> Are you sure the download is correct? Travis seems to be getting the wrong shasum.

Something weird is happening. I get a different shasum on every download.

**Comment by vitorgalvao** [comment]
It may be redirecting to an HTML file. Try using `https://2manyrobots.com/Updates/Yate/Yate.zip` (the file referenced in the appcast) instead.

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/pull/21446

**Pull request closed without merging**
