### PR TITLE
Add Polymail (latest)

### PR DESCRIPTION
**Pull request by esebastian**
Add Polymail app, a simple, beautiful, powerful email client

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in aaf8cdbdc03d5ac95e1fb646b39a0b1bdf77edb0. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by esebastian** [comment]
Thanks for taking care of the fixes, I'm taking note of the details for the next one.

**Comment by vitorgalvao** [comment]
For reference, I used [`find_sparkle_appcast`](https://github.com/caskroom/homebrew-cask/blob/master/developer/bin/find_sparkle_appcast) (`"$(brew --repository)/Library/Taps/caskroom/homebrew-cask/developer/bin/find_sparkle_appcast"`) to find the appacast.

**Comment by esebastian** [comment]
Thanks for the tip!

**Pull request closed without merging**
