### PR TITLE
Update launchcontrol from 1.51 to 1.51.1

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
Not sure what is going on with this one:
```
|-> curl -sLI https://www.soma-zone.com/download/files/LaunchControl-1.51.1.tar.bz2
HTTP/2 200 
date: Fri, 11 Dec 2020 01:08:51 GMT
server: Apache/2.4.46 (cPanel) OpenSSL/1.1.1g mod_bwlimited/1.4 mod_fcgid/2.3.9 Phusion_Passenger/5.3.7
strict-transport-security: max-age=63072000; includeSubdomains;
last-modified: Tue, 08 Dec 2020 07:57:43 GMT
etag: "1c46210-655c48-5b5ef4c272bc0"
accept-ranges: bytes
content-length: 6642760
vary: User-Agent
content-type: application/x-tar
```

**Comment by core-code** [comment]
the file is not available on the homepage only in the updatecheck/appcast:

`https://www.soma-zone.com/download/files/LaunchControl-1.51.1_update.tar.bz2`

**Comment by ran-dall** [comment]
@core-code @miccal I'll let you guys make the decision, but I think if it's not availible on the home page then we should close.

**Comment by miccal** [comment]
Updating this locally using either `https://www.soma-zone.com/download/files/LaunchControl-1.51.1.tar.bz2` or `https://www.soma-zone.com/download/files/LaunchControl-1.51.1_update.tar.bz2` works as intended, with both `brew fetch` and `brew install` succeeding.

I have no idea why the CI is failing.

**Comment by core-code** [comment]
if it works locally i guess ci-skip-install is the right solution

**Comment by jabenninghoff** [comment]
It sure looks like soma-zone is blocking access from GitHub Actions... I'm seeing the same problem with #95316.

**Comment by core-code** [comment]
> It sure looks like soma-zone is blocking access from GitHub Actions

if they dislike Homebrew that much i guess we should remove the cask

**Comment by jabenninghoff** [comment]
> > It sure looks like soma-zone is blocking access from GitHub Actions
> 
> if they dislike Homebrew that much i guess we should remove the cask

Seems so. I will contact support@soma-zone.com to see if it's intentional, and if not, ask them to investigate.

**Comment by jabenninghoff** [comment]
OK... I contacted soma-zone, the developer, Robby, responded. He blocked access because curl requests coming from GitHub exceeded his monthly quota of 40GB. I explained that this was likely due to the recent problems with CI that resulted in multiple requests to download from soma-zone, and that they've been resolved for now. He has removed the block but said he would block again if he sees large spikes. Out of curiosity for the maintainers, is there some way to minimize the traffic to small developers like this?

**Comment by jabenninghoff** [comment]
Re-running the automation should work now, it did for #95316

**Comment by core-code** [comment]
wow 40GB quota? this sounds like 1999 to me. you can get unlimited traffic for 1€ per month...

**Comment by jabenninghoff** [comment]
> wow 40GB quota? this sounds like 1999 to me. you can get unlimited traffic for 1€ per month...

Well, yes, maybe you can help him out? He's based in Germany and I don't know the European hosting market...

**Comment by core-code** [comment]
still, we shouldn't download the app more than 10 times per month, and at a file size of less than 7 MB he should see less than 100 MB from Github per month... something seems off here.

> He's based in Germany and I don't know the European hosting market...

i'll send some recommendations his way  :)

**Pull request merged**
