### PR TITLE
added Casks/llvm.rb

### PR DESCRIPTION
**Pull request by UnixJunkie**
Later, I'd like to add several other version of it: 3.6.0, 3.7.0, etc.
How should I do it?

_If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so._

After making all changes to the cask:
- [x] `brew cask audit --download {{cask_file}}` is error-free.
  "at least one activatable artifact stanza is required"
  I don't understand this diagnostic and what I should do to fix it.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:
- [x] Named the cask according to the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked that the cask was not already refused in [closed issues](https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed).

### CODE REVIEW

**Comment by UnixJunkie** [comment]
My goal is to add the precompiled binary version of clang+llvm.
I ship some software that relies on clang-3.8.0 so I cannot rely on the
source-based version that ships with brew (3.8.1, called llvm38 in brew)

**Comment by UnixJunkie** [comment]
If I should create homebrew/versions/llvm380 instead, just tell me so.

**Comment by miccal** [comment]
This is a CLI-only open-source tool, so you will need to submit it first to [Homebrew](https://github.com/Homebrew/homebrew-core), and if they don’t accept it you can submit it to Homebrew Cask (linking back to the pull request where it was refused).

This policy is documented in the [faq/rejected_cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md).

**Comment by vitorgalvao** [comment]
> Later, I'd like to add several other version of it: 3.6.0, 3.7.0, etc.
> How should I do it?

By submitting to [caskroom/versions](https://github.com/caskroom/homebrew-versions). Don’t bother, though, because [they won’t be accepted](https://github.com/caskroom/homebrew-versions#acceptable-casks):

> `caskroom/versions` is not intended to be used for all and any old versions you personally require for xyz project; casks submitted here should be expected to be used by a reasonable number of people and supported by contributors long-term.

> You may wish to consider hosting your own [tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) for casks you wish to personally support that do not meet the above standards.

> "at least one activatable artifact stanza is required"
> I don't understand this diagnostic and what I should do to fix it.

It means you need to read the [documentation on adding a cask, specifically the stanzas part](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#cask-stanzas). At the moment, this cask does nothing. It just downloads an archive.

All that said, and as @miccal mentioned, this is better suited for HB, and is already there. This cask adds nothing in relation to the formula, and as such has no reason to exist.

**Pull request closed without merging**
