### PR TITLE
Add VNC Viewer.app v5.3.0

### PR DESCRIPTION
**Pull request by viniciusbig**
Adding new cask for the Real VNC Client.

### CODE REVIEW

**Comment by victorpopkov** [comment]
Thank you for the contribution. However, this cask already exists: [real-vnc.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/real-vnc.rb).

**Comment by viniciusbig** [comment]
Thanks for the quick reply.

Actually this is a different cask.

real-vnc.rb is the full version of Real VNC witch includes a VNC server.
My cask is just the VNC Viewer. A simpler program, smaller, just to connect in a VNC Server.

real-vnc.rb refers to this link https://www.realvnc.com/download/vnc/latest/
real-vnc-viewer.rb refers to https://www.realvnc.com/download/viewer/

**Comment by victorpopkov** [comment]
Thank you for the explanations. Everything looks good. However, the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) should be followed to avoid duplicates. According to it, the cask should be named as `vnc-viewer.rb`. But in my opinion it would be better to leave the name as it now.

What do you think @vitorgalvao about the cask naming for this case?

**Comment by vitorgalvao** [comment]
`vnc-viewer` is the correct name. We can’t take “it makes sense in this case” as a reason, because that is exactly how duplicates happen. What makes sense for a person is different than what makes sense to another. The token reference is strict for that reason, we need an absolute answer. `name` is the place to be correct and verbose (and `name` for this cask is correct).

**Comment by viniciusbig** [comment]
I don't know if I did correctly, but I fixed the file name to match token requirements.

**Comment by vitorgalvao** [comment]
It is correct, yes, thank you. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by victorpopkov** [comment]
> We can’t take “it makes sense in this case” as a reason, because that is exactly how duplicates happen.

Fully agree. Just wanted to make sure. Thank you @vitorgalvao for the quick response.

**Comment by victorpopkov** [comment]
Thank you for the contribution. It was merged directly as 3d31b4510246a452f416a95dde3d95548e538fe9 to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
