### PR TITLE
Update imgotv from 6.4.4 to 6.4.6

### PR DESCRIPTION
**Pull request by wjlmelody**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@neutric Do you have any ideas for a livecheck here? I've found - http://pcconf.api.mgtv.com/pc/update?source=mango&ticket=&appVersion=6.4.4&osVersion=12.3.1&platform=mac&webVersion=1.1.7 - but it's reliant on passing an appVersion through, and using a dummy version (0.0.1, etc...) doesn't return the latest version.

**Comment by wjlmelody** [comment]
I didn't have any other ideas for this problem, so I emptied the livecheck in the file.

**Comment by wjlmelody** [comment]
> @neutric Do you have any ideas for a livecheck here? I've found - http://pcconf.api.mgtv.com/pc/update?source=mango&ticket=&appVersion=6.4.4&osVersion=12.3.1&platform=mac&webVersion=1.1.7 - but it's reliant on passing an appVersion through, and using a dummy version (0.0.1, etc...) doesn't return the latest version.

I didn't have any other ideas for this problem, so I emptied the livecheck in the file.

**Comment by bevanjkay** [comment]
@wjlmelody Thanks for looking into it. I'd like to spend a little bit more time looking for something before we merge this one, ideally every cask should have a functioning livecheck unless we are 100% certain it isn't possible.

**Comment by wjlmelody** [comment]
> @wjlmelody Thanks for looking into it. I'd like to spend a little bit more time looking for something before we merge this one, ideally every cask should have a functioning livecheck unless we are 100% certain it isn't possible.

Thanks. I'd like too

**Comment by neutric** [comment]
@bevanjkay I was a bit slow, sorry. Looks like all is good now...

**Pull request merged**
