### PR TITLE
updated gitkraken (0.6.2)

### LINKED ISSUE #18163: Outdated cask: gitkraken
Outdated cask: [`gitkraken`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/gitkraken.rb).

Info:
+ version: `0.6.1`.
+ appcast url: https://release.gitkraken.com/darwin/RELEASES.

Full appcast:
```text
{"name":"0.6.2","url":"http://release.gitkraken.com/darwin/v0.6.2.zip"}
```

### PR DESCRIPTION
**Pull request by vitorgalvao**
Closes #18163.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Merged as 9f3d1e1e08c737f32a76581321365c0b70e18cac.

**Comment by andreineculau** [comment]
is it on purpose that the cask uses a version-specific url?
their page shows http://release.gitkraken.com/darwin/installGitKraken.dmg

**Comment by vitorgalvao** [comment]
But we can get a versioned version, and it’s from their domain, so yes, why not use it.

**Comment by jawshooah** [comment]
@andreineculau We prefer version-specific URLs when they are available.

**Comment by andreineculau** [comment]
@vitorgalvao @jawshooah now I know. Thanks!

**Pull request closed without merging**
