### PR TITLE
Update dawnlabs-alchemy to 0.5.1

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Does the failed command work stand-alone?

```
/usr/bin/ditto -x -k -- /Users/travis/Library/Caches/Homebrew/Cask/dawnlabs-alchemy--0.5.1.zip /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/d20180630-4427-tfvhqd
```

**Comment by brianmorton** [comment]
I don't think so?

```
$ ditto -x -k -- /tmp/Alchemy-mac.zip /tmp/test/
ditto: /tmp/test//Alchemy.app/Contents/Resources/app/bin/photosorcery: Not a directory
ditto: Couldn't read pkzip local header
```

**Comment by brianmorton** [comment]
bump

**Comment by brianmorton** [comment]
Does anybody else have some insight into how I can get this PR resolved? @commitay @vitorgalvao

**Comment by reitermarkus** [comment]
Can you try manually with `unzip`?

**Comment by brianmorton** [comment]
Yes, unzipping the downloaded `Alchemy-mac.zip` resulted in `Alchemy.app`. Running the app seemed to work as expected (I got an icon added to my menubar).

**Comment by brianmorton** [comment]
Going to close this PR and blacklist the cask in the next few days unless somebody has an idea of how to resolve this.

**Pull request closed without merging**
