### PR TITLE
Update cocktail

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by jasonmp85** [comment]
Why did the testbot merge this? The `ci` check failed?

Looks like the author copy-pasted the `sha256` from a previous block. The correct value for the latest version (of both cocktail and macOS) at the time of this comment is `9f5297e5eac0158eec654bc48595856d28d68ab6a542b5847482f291d2aed6d6`, as the failed `ci` job indicates…

**Comment by ran-dall** [comment]
> Why did the testbot merge this? The ci check failed?

@jasonmp85 👉 The tool we use tends to have a glitch which improperly submits the Cask with the latest `sha256` for the latest version of cask for the 'local' operating system. The ML has policies to avoid this however it can still be executed manually, which is what happened here. As for the @BrewTestBot; it tests for correctness, and technically it's valid download, so it merged. 

Regardless, thank you 👏 for bringing it to our attention. We'll take care of it shortly.

> Looks like the author copy-pasted the `sha256` from a previous block. The correct value for the latest version (of both cocktail and macOS) at the time of this comment is `9f5297e5eac0158eec654bc48595856d28d68ab6a542b5847482f291d2aed6d6`, as the failed `ci` job indicates…

@jasonmp85 👉 Just a reminder that all the folks here are volunteers and we're all on the same team. We also speak different languages. I just wanted to point this out because the comment can be read as a bit confrontational, which I'm sure wasn't your intent. As fair as your conclusion is, this was an honest mistake.

**Comment by ran-dall** [comment]
https://github.com/Homebrew/homebrew-cask/pull/77832

**Comment by suschizu** [comment]
hey @jasonmp85 - thanks for reporting! you are right - travis just checks the mojave case and I think ignores catalina - so the sha from mojave has been added to this pull - this case normally should be updated manually - I forgot it sorry  (https://github.com/Homebrew/homebrew-cask/pull/77874)

**Comment by jasonmp85** [comment]
Thanks for the update, @suschizu… I am not sure whether my comment came across as confrontational, but I assure you it certainly wasn't intended as such. I was mostly baffled by seeing the auto-merge when I could click on _Checks_ and see for myself that `ci` was failing, and the auto-merge was obvious no person's fault. _copy-paste_ was more a description that the `sha256` matched a previous one exactly, and not some sort of criticism.

This all said, @ran-dall, I'm not entirely sure what's with the finger pointing emoji where a colon or em-dash might do, but, uh, pointing at people has got a _lot_ of cultural baggage worldwide, FWIW.

At any rate, I guess I've got an explanation that this is _understood_ and perhaps even _expected_ behavior (once understood).

Is the code for the brew bot somewhere? I'm a bit curious about what might be done to improve this in the future.

**Comment by ran-dall** [comment]
> This all said, @ran-dall, I'm not entirely sure what's with the finger pointing emoji where a colon or em-dash might do, but, uh, pointing at people has got a lot of cultural baggage worldwide, FWIW.

I dunno but what I do know is that you seem to choose to contiune to be confrontational. 😁

**Comment by ran-dall** [comment]
@jasonmp85 Also, next time please don't comment on PR, we would rather you open up an issue if you have any issues with a cask. Thanks 👍

**Pull request merged**
