### PR TITLE
Add Zandronum v3.0

### PR DESCRIPTION
**Pull request by specious**
[Zandronum](https://zandronum.com) is a multiplayer oriented port of Doom and Doom II based on [Skulltag](http://www.skulltag.com).  This package installs Zandronum along with the [Doomseeker](http://doomseeker.drdteam.org) server browser.

--

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] `sha256` changed but `version` stayed the same ([what is this?][version-checksum]).  
      I’m providing public confirmation below.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
This requires external files.

> https://zandronum.com/download
> Locate and install IWADs to ~/Library/Application Support/Zandronum/

**Comment by specious** [comment]
>This requires <strike>external files</strike> a copy of Doom.

Zandronum also works with [Freedoom](http://freedoom.github.io), which is available for free.

**Comment by specious** [comment]
[Chex Quest 3](http://www.chucktropolis.com/gamers.htm) is also free, and works with Zandronum.

**Comment by vitorgalvao** [comment]
I’m fine with including this cask. Its popularity is arguable but it seems to work with a varied enough number of games, particularly if some are free.

Yes, it requires some manual configuration, but it’s unlikely you’ll install this without already knowing how to use it, helped by [`not_a_discoverability_service.md`](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md). I’m also fine with the `caveat`.

I also think we have similar precedents, although that in and of itself isn’t any reason to auto-include (might just as well mean an auto-remove for the other ones). While I’m ambivalent on this cask, I’m not seeing a strong reason to not include it.

**Pull request merged**
