### PR TITLE
smcfancontrol: remove

### PR DESCRIPTION
**Pull request by yeSpud**
```
==> Analytics
install: 455 (30 days), 1,642 (90 days), 5,956 (365 days)
```

The website for this cask seems to no longer exist

### CODE REVIEW

**Comment by yeSpud** [comment]
Website listed was http://www.eidac.de/ for those who are curious

**Comment by bevanjkay** [comment]
Given that the cask is reasonably popular (in the top 250 casks), despite note being updated for some time.
We should be able to use the Github repo for the download.
https://github.com/hholtmann/smcFanControl
```
30 days: 455 (#248)
90 days: 1,642 (#220)
365 days: 5,956 (#241)
```

**Comment by yeSpud** [comment]
Ah

So would it be better just to update the urls in the file (as the site it points to seems to have expired and thus can only be downloaded via the github page)?

**Comment by yeSpud** [comment]
Going to close this and fix the URLs under a new PR

Thanks!

**Pull request closed without merging**
