### PR TITLE
Update doomsday-engine to 2.0.3

### PR DESCRIPTION
**Pull request by OranguTech**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by commitay — CHANGES_REQUESTED** [review]
`sha256` only changes need to be verified. See [updating the `sha256`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256) for how to provide verification.

**Comment by OranguTech** [comment]
(I'm new at this)

Just submitted this because package has failed for me over a couple months, just seems to have a wrong hash, or maybe a slightly different build revision w/ the same version?

**Comment by commitay** [comment]
```
Executable=/Volumes/doomsday_2.0.3_x86_64/Doomsday.app/Contents/MacOS/Doomsday
Identifier=
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=42464 flags=0x0(none) hashes=1322+3 location=embedded
Signature size=8917
Authority=Developer ID Application: Jaakko Keranen (VS2RUWJAF3)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=1 Oct 2017 at 10:11:43
Info.plist entries=11
TeamIdentifier=VS2RUWJAF3
Sealed Resources version=2 rules=13 files=69
Internal requirements count=1 size=160

Doomsday.app: valid on disk
Doomsday.app: satisfies its Designated Requirement

Executable=/Volumes/doomsday_2.0.3_x86_64/Doomsday Shell.app/Contents/MacOS/Doomsday Shell
Identifier=
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=4832 flags=0x0(none) hashes=146+3 location=embedded
Signature size=8916
Authority=Developer ID Application: Jaakko Keranen (VS2RUWJAF3)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=1 Oct 2017 at 10:11:33
Info.plist entries=11
TeamIdentifier=VS2RUWJAF3
Sealed Resources version=2 rules=13 files=26
Internal requirements count=1 size=160

Doomsday Shell.app: valid on disk
Doomsday Shell.app: satisfies its Designated Requirement
```

**Review by commitay — APPROVED** [review]
Verified locally.

**Comment by OranguTech** [comment]
Dowloaded from http://dengine.net/macos, which points to http://api.dengine.net/1/builds?dl=doomsday_2.0.3_x86_64.dmg. Looking further, appears to be from Build 2464: http://api.dengine.net/1/builds/2464 (Only MD5 provided), so probably that was the issue.

**Comment by commitay** [comment]
Thanks for the PR!

**Pull request merged**
