### PR TITLE
wireshark 4.0.6

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
So according to the appcasts, Big Sur is the minimum for arm64 and Sierra is the minimum for x86_64. I mean it's technically correct but that doesn't help us here.

**Comment by SMillerDev** [comment]
Should be arch dependent then?

**Comment by razvanazamfirei** [comment]
Weird, I'm getting `:mojave` as the minimum version on both downloads.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>LSMinimumSystemVersion</key>
	<string>10.14</string>
</dict>
</plist>
```

**Comment by bevanjkay** [comment]
@razvanazamfirei The audit comes from the `appcast`, not the application package (for testing minimum version).

https://www.wireshark.org/update/0/Wireshark/0.0.0/macOS/x86-64/en-US/stable.xml

**Review by miccal — APPROVED** [review]

**Pull request merged**
