### PR TITLE
Update tla-plus-toolbox version from 1.7.1(not installable) to 1.8.0

### PR DESCRIPTION
**Pull request by goto1134**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @goto1134.

**Comment by stevo-f3** [comment]
@goto1134 sha seems to be wrong:

```
==> Upgrading 1 outdated package:
tla-plus-toolbox 1.7.1 -> 1.8.0
==> Upgrading tla-plus-toolbox
==> Downloading https://github.com/tlaplus/tlaplus/releases/download/v1.8.0/TLAToolbox-1.8.0-macosx.cocoa.x86_64.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/50906927/7436818c-2266-4618-8e4e-803e643a3545?X-Amz-Algorithm=AWS4-HMAC-SHA
######################################################################## 100.0%
==> Purging files for version 1.8.0 of Cask tla-plus-toolbox
Error: tla-plus-toolbox: SHA256 mismatch
Expected: 8a593a8ddb69c6b6f05a53fc0353235b5abf8cd243c8fb8c8accbaf0d59cd6d7
  Actual: 0353bd93f318b90608f1d1bc0c7bc6b43f4631476f22b90d30be793e156bdb03
```

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/118917

**Pull request merged**
