### PR TITLE
updated bettertouchtool (1.62)

### PR DESCRIPTION
**Pull request by victorpopkov**

### CODE REVIEW

**Comment by victorpopkov** [comment]
Merged as ea404bf41d3dae27d5b2a817ea558b6bec67c1fb.

**Comment by vitorgalvao** [comment]
What’s you method for always finding and updating all of these en-masse?

**Comment by victorpopkov** [comment]
> What’s your method for always finding and updating all of these en-masse?

Just a bunch of scripts.

The first one has the same idea as `cask-repair` to update casks. I run it on a local VM with latest OS X installed.
```bash
cask-upgrade [options] <cask_name> <new_version>
```

+ Changes the version stanza value to the new one that was passed as an argument to get the new `sha256` value that was suggested by homebrew-cask and also check the download URL by making the first audit with `--download` option:
  + If fails due to `sha256 mismatch`, continue.
  + If succeeds, abort.
  + If fails for any other reason, abort.
+ Replaces the old `sha256` value with new one and also update the appcast checkpoint. After that makes the second audit:
  + If succeeds, continue.
  + If fails, abort.
+ Install the app using an updated cask. Just to verify if the symlink source is still correct and no other problems were detected:
  + If succeeds, uninstall the app.
  + If fails, abort.
+ If uninstall was also successful, make the commit to the fork. After that I usually manually open PR, just to verify if there aren't any errors.

This is a usual output:
```bash
$ cask-upgrade -i -u -c bettertouchtool.rb 1.62
Retrieving cask path...                | ../homebrew-cask/Casks/bettertouchtool.rb
Copying cask as temporary file...      | Done
Retrieving old version...              | Done
Replacing old version with new...      | 1.56 with 1.62
Copying modified cask to repository... | ../homebrew-cask
Performing first audit...              | Failed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
==> Downloading https://boastr.net/releases/btt1.62.zip
Error: audit failed
==> Verifying checksum for Cask bettertouchtool
==> Note: running "brew update" may fix sha256 checksum errors
audit for bettertouchtool: failed
 - download not possible: sha256 mismatch
Expected: f805e9976c235071a982ee5ce3dd40a2b6498f1328d2f6c065552e68fc3266c6
Actual: 4baba82c9ae7f201e67f67ff1d8db0aa63a7e9212ff946ee2d6b0fd425d376e1
File: /Library/Caches/Homebrew/bettertouchtool-1.62.zip
To retry an incomplete download, remove the file above.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Replacing sha256 checksum...           | Done
Retrieving appcast...                  | Done
Replacing appcast sha256...            | Done
Performing second audit...             | Passed
Installing...                          | Password:
Done
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
==> Downloading https://boastr.net/releases/btt1.62.zip
Already downloaded: /Library/Caches/Homebrew/bettertouchtool-1.62.zip
==> Verifying checksum for Cask bettertouchtool
==> Symlinking App 'BetterTouchTool.app' to '/Users/Vitja/Applications/BetterTouchTool.app'
==> Enabling accessibility access
🍺  bettertouchtool staged at '/opt/homebrew-cask/Caskroom/bettertouchtool/1.62' (619 files, 20M)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Uninstalling...                        | Done
Creating branch...                     | update/bettertouchtool
Adding our cask...                     | Done
Commiting...                           | Done
Pushing...                             | Done
Switching to 'master' branch...        | Done
Suggesting PR title...                 | updated bettertouchtool (1.62)
Resetting repository to original...    | Done
Removing temporary cask...             | Done
```

The second script is used to find outdated casks. It's running on a separate Linux server every 12 hours.
```bash
cask-check-updates [options]
```
+ Get all the casks that have an appcast and check if those are outdated by comparing the appcast checkpoint with the new value:
  + If the values are the same, skip this cask.
  + If values are not the same, continue.
+ Get the version number from the appcast (the most unstable part):
  + If its Sparkle appcast, then parse the XML to get the latest version (`sparkle:version`) and the build numbers (`sparkle:shortVersionString`). Of course, the are many edge cases here, but the main points are:
    - Extract all versions and build numbers. Remove extra characters (sometimes there are words like `build` or `b` in `sparkle:version`).
    - Compare versions of each `item` to get the correct order of the versions and retrieve the `item` with the latest version and build numbers.
    - Check if build and version numbers are not the same values (sometimes they are). If yes, then eliminate the build number.
    - If both version and build number are specified and values are not the same, choose the one, that is present in the `enclosure` url. Usually, this eliminates the one value. By default, the version is more preferred over the build number. But if both are present in the `enclosure` url, then use the `<version>,<build>` as the resulting output version.
  + If its GitHub appcast, then parse (the releases HTML page instead of the Atom XML itself) to get the latest version number based on the green "Latest release" label (for `homebrew-cask` to ignore unstable builds). Maybe there are values that point if it's `pre-release` or `latest` in releases.atom, but didn't find any when I first was experimenting with this idea.
  + If unknown appcast, skip this cask.
+ Compare the old and new version.
  + If those are the same, skip the cask (just an outdated checkpoint).
  + If the new version value is less than the old one, skip the cask.
+ If the version was retrieved successfully, write it to the result file along with the cask name and old version number.

For example, the yesterday output was:
```csv
audirvana-plus.rb;2.3.3;2.4
bettertouchtool.rb;1.56;1.62
bilibili.rb;2.35;2.37
coteditor.rb;2.4.3;2.4.4
dropshare.rb;4-3803;3950
gramps.rb;4.2.2-4;4.2.2
handbrake.rb;0.10.5;0.10.5 x86_64
hexchat.rb;2.10.2;2.12.0
hockey.rb;2.0.14;2.0.15
imazing.rb;1.5.1,1456163160;1.5.2
moneyguru.rb;2.9.4;2.10.0
qlcolorcode.rb;2.0.4;2.0.5
screenflick.rb;2.7.8;2.7.9
screenhero.rb;2.3.5.0;2.3.6.0
...
```

As a result, I get a CSV file with a list of outdated casks with new versions that are after being fed to the `cask-upgrade` script. The script modifies the input file with the result of the cask-upgrade outcome. Many of those are upgraded automatically and I only verify them when I open PR. Others need a manual upgrade:

Output, after processing by `cask-upgrade`:
```csv
audirvana-plus.rb;2.3.3;2.4;success
bettertouchtool.rb;1.56;1.62;success
bilibili.rb;2.35;2.37;success
coteditor.rb;2.4.3;2.4.4;success
dropshare.rb;4-3803;3950;failed
gramps.rb;4.2.2-4;4.2.2;failed
handbrake.rb;0.10.5;0.10.5 x86_64;failed
hexchat.rb;2.10.2;2.12.0;success
hockey.rb;2.0.14;2.0.15;failed
imazing.rb;1.5.1,1456163160;1.5.2;success
moneyguru.rb;2.9.4;2.10.0;failed
qlcolorcode.rb;2.0.4;2.0.5;failed
screenflick.rb;2.7.8;2.7.9;success
screenhero.rb;2.3.5.0;2.3.6.0;success
...
```
In the overall, this is not the best solution and is not stable enough in my opinion, but that's how I usually do all the updates.

**Comment by vitorgalvao** [comment]
Those actually look pretty great (particularly the messages informing about each step).

Even if unstable, have you considered sharing them? Perhaps they can be mishmashed with `cask-repair` and/or the `*_outdated_appcasts` scripts.

**Pull request closed without merging**
