### PR TITLE
bbedit: Added binary installation for helpers

### PR DESCRIPTION
**Pull request by Kreeblah**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Aren't these installed by running the command "Install Command Line Tools" from within the app itself?

I am concerned that adding these this way may mess with the recommended way to install them.

**Comment by Kreeblah** [comment]
They are, yes, but that menu option puts them in a subdirectory in `/usr/local`, regardless of which architecture (ARM vs. Intel) it's running on.  Having them linked from the cask here does result in BBEdit reporting them as correctly installed, and they do work properly.  However, I did forget to add the man pages when I submitted this originally, which are the other things that get installed, so I updated this with another commit to do that.

This should, at this point, be identical in functionality to using the menu item to install them, except the man pages and binaries will be linked to where they're located within the app bundle instead of copied to locations within `/usr/local`.

**Comment by miccal** [comment]
Thanks @Kreeblah, and one more question -- does running "Install Command Line Tools" from within the app change the name of `bbedit_tool` to just `bbedit` like you have done here?

**Comment by Kreeblah** [comment]
Sure, no problem.

Regarding the renaming, the application's "Install Command Line Tools" option does also rename the binary from `bbedit_tool` to `bbedit`.  It also looks for `bbedit` (not `bbedit_tool`) when determining what the installed helper version is, and the man page refers to it as just `bbedit`.

**Pull request merged**
