### PR TITLE
Update frhelper from 3.9.4,2019-12-09 to 3.9.4,2019-12-13

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
perhaps its better to add the bundle version too because they often just change the BV and keep the SVS (and sometimes also just change the download-token  … like here)
  
and:
`- appcast at URL 'https://www.francochinois.com/update/frhelper_mac.xml' does not contain the version number '3.9.4':`
yes true - this appcast is the SUFeedURL so normally it should be updated … but we are 2 versions behind and I can't find another feed. The release history unfortunately doesn't show the mac version updates - the only way to track the version I think would be to download the app and check the svs - not sure if the effort is worth it (not very popular) @core-code, @vitorgalvao

**Comment by core-code** [comment]
how about using 'https://www.eudic.net/v4/fr/app/download' as the appcast and 'configuration :version.after_colon' so that it only looks for the download-token (which presumably changes every time)?

**Comment by suschizu** [comment]
the download-token changes more often than the version … so sometimes (like this time) they update the download token but not the app itself - but would be oke for me (?)

**Comment by core-code** [comment]
i am not sure. lets see what vitor thinks ;)

**Comment by vitorgalvao** [comment]
Using `https://www.eudic.net/v4/fr/app/download` and the date seems best. But in that case we might as well remove the bundle version: it’s one less value to track (we wouldn’t be using it anyway) and we avoid `colon`.

**Pull request merged**
