### PR TITLE
update letter-fix to 2.3.2

### PR DESCRIPTION
**Pull request by wtnb-ytk**

### CODE REVIEW

**Comment by wtnb-ytk** [comment]
Thank you for accepting this.

This version's dmg file name is “LetterFix-2.3.2a.dmg”, but pkg file name is “LetterFix-2.3.2.pkg”.
so I added suffix "a" to after "#{version}" in url.
Perhaps it isn't good, but I didn't know how to do.
If there is a better way, I'd like to know.

**Comment by vitorgalvao** [comment]
Well, that `62451` is bound to change every release, so having `#{version}` in the `url` isn’t actually buying us anything and should be removed.

**Comment by wtnb-ytk** [comment]
I'm not good at English, so please confirm this.

In this case, version in the url does not necessarily match. Therefore, do not use #{version} in the url.
If it’s correct then I'm going to change url string to fixed string at next update.

**Comment by vitorgalvao** [comment]
Your are correct.

No need to worry about changing it, as I have already done. Thank you.

**Comment by wtnb-ytk** [comment]
Thank you, too.

**Pull request merged**
