### PR TITLE
Add JioHome v2.0.7

### PR DESCRIPTION
**Pull request by SriMouli**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SriMouli** [comment]
Not sure why livecheck erorr is coming when the cask doesn't contain livecheck
```
Error: Version '2.0.7' differs from '' retrieved by livecheck.
```

**Comment by SMillerDev** [comment]
That's why it's failing. Livecheck will try all known urls to find the latest version and here it's clearly coming up short.

**Comment by miccal** [comment]
@bevanjkay I was not able to find a suitable `livecheck` -- perhaps you may have more luck?

**Comment by miccal** [comment]
Thanks @bevanjkay.

**Pull request merged**
