### PR TITLE
travis error test

### PR DESCRIPTION
**Pull request by commitay**

### CODE REVIEW

**Comment by commitay** [comment]
@bluzi Is there something else we need to do to disable the errored comment?

**Comment by bluzi** [comment]
Actually no, if `on_error` is set to `never`, TravisCI should not trigger the webhook on error.

**Comment by bluzi** [comment]
@commitay Do you need my help on this issue, or have you figured it out already?

**Comment by commitay** [comment]
`on_failure: never` disables the `errored` comment

**Comment by bluzi** [comment]
Does it keep posting logs?

**Comment by commitay** [comment]
No, `on_failure: never` disables both errors and failures.

**Comment by bluzi** [comment]
I can add a flag to @TravisBuddy that disables error messages.
Or, you can contact TravisCI on their repository. (though it will take time)

**Comment by commitay** [comment]
We've disabled TravisBuddy for now as our build scripts and the way they error out doesn't work well with notifications.

I'm looking at improving the build scripts (which will probably require some backend changes) so hopefully we can add it back sometime in the future.

Thanks nonetheless for your help @bluzi!

**Pull request closed without merging**
