### PR TITLE
mysql-shell 8.0.33

### PR DESCRIPTION
**Pull request by razvanazamfirei**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — DISMISSED** [review]

**Review by bevanjkay — APPROVED** [review]

**Comment by Frederick888** [comment]
I'm getting hash mismatch somehow:

```
==> Purging files for version 8.0.33 of Cask mysql-shell
Error: mysql-shell: SHA256 mismatch
Expected: 0ea222d0819c94d2a7e20363f6488a7207cda7feba80835b54228850f6d09a29
  Actual: 18a993a7b6351a81f5571a29d0705d518b35e4686c41b9e1c055eff240a86743
    File: /Users/<user>/Library/Caches/Homebrew/downloads/be6664d16b1d90fa45c67afd40adfef37bf176486c8f3ff19448c369574a41e4--mysql-shell-8.0.33-macos13-x86-64bit.dmg
```

```sh
du /Users/<user>/Library/Caches/Homebrew/downloads/be6664d16b1d90fa45c67afd40adfef37bf176486c8f3ff19448c369574a41e4--mysql-shell-8.0.33-macos13-x86-64bit.dmg
133120  /Users/<user>/Library/Caches/Homebrew/downloads/be6664d16b1d90fa45c67afd40adfef37bf176486c8f3ff19448c369574a41e4--mysql-shell-8.0.33-macos13-x86-64bit.dmg
```

**Comment by bevanjkay** [comment]
@Frederick888 I am not seeing the same error - 

```
 ~  brew fetch --arch=intel mysql-shell                                                                                                                                                                                  ok | 28s | 15:28:21 
==> Downloading https://dev.mysql.com/get/Downloads/MySQL-Shell/mysql-shell-8.0.33-macos13-x86-64bit.dmg
==> Downloading from https://cdn.mysql.com//Downloads/MySQL-Shell/mysql-shell-8.0.33-macos13-x86-64bit.dmg
####################################################################################################################################################################################################################################### 100.0%
Downloaded to: /Users/.../Library/Caches/Homebrew/downloads/be6664d16b1d90fa45c67afd40adfef37bf176486c8f3ff19448c369574a41e4--mysql-shell-8.0.33-macos13-x86-64bit.dmg
SHA256: 0ea222d0819c94d2a7e20363f6488a7207cda7feba80835b54228850f6d09a29
```

It may be a CDN issue. But have you tried downloading again?

**Comment by Frederick888** [comment]
I did retry, and the SHA256 remained `18a993a7b6351a81f5571a29d0705d518b35e4686c41b9e1c055eff240a86743`. I also tested on a different machine (Linux + curl/wget) and it was the same. @bevanjkay

**Pull request merged**
