### PR TITLE
Update obsidian from 0.14.5 to 0.14.6

### PR DESCRIPTION
**Pull request by gabrielwhite**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by joshka** [comment]
@gabrielwhite the current checksum for this download seems to be `028f3ac569d1d66538941486ee9599ba07ff256ecdffcf8a33f18d1a2967ecff` - can you please confirm this?

Download: https://github.com/obsidianmd/obsidian-releases/releases/download/v0.14.6/Obsidian-0.14.6-universal.dmg

Cask install output:
```
==> Downloading https://github.com/obsidianmd/obsidian-releases/releases/download/v0.14.6/Obsidian-0.14.6-universal.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/262342594/bb42845d-c2fe-4316-9aa2-60119fee80d1?X-Amz-Algorithm=AWS4-HMAC-SHA256&
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 6b812de4d5281370b52d632cae12e42a5711062a47a55dd965900c777dec5cd6
  Actual: 028f3ac569d1d66538941486ee9599ba07ff256ecdffcf8a33f18d1a2967ecff
    File: /Users/joshka/Library/Caches/Homebrew/downloads/067b7a614e71edffad4fd8e88ada37f932d2f3e6d9ec3d9fa4e4cf411c172c36--Obsidian-0.14.6-universal.dmg
To retry an incomplete download, remove the file above.

joshka at joshka-macbook2-4 in ~
$ shasum -a 256 Downloads/Obsidian-0.14.6-universal.dmg
028f3ac569d1d66538941486ee9599ba07ff256ecdffcf8a33f18d1a2967ecff  Downloads/Obsidian-0.14.6-universal.dmg
```

(commented on the commit, but this is likely a better place for it.

**Comment by joshka** [comment]
>[SMillerDev](https://github.com/SMillerDev) commented on [759c9ac](https://github.com/Homebrew/homebrew-cask/commit/759c9ace60c7a5f7a185be34d24fce3305cf1392) [2 hours ago](https://github.com/Homebrew/homebrew-cask/commit/759c9ace60c7a5f7a185be34d24fce3305cf1392#commitcomment-71688124)

>Please see https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match

Thanks @SMillerDev - I downloaded this twice, both from the direct link on https://obsidian.md/ and via `brew install` (the links were the same). The fix is trivial, but I'm trying to confirm / understand the reason for the different checksum.

**Comment by SMillerDev** [comment]
Casks just change checksums sometimes when the vendor decides to change something. I'd be worried if you get a different checksum than our CI.

**Comment by zhengpd** [comment]
Maybe the dmg asset was updated after the first release.

```
$ stat 067b7a614e71edffad4fd8e88ada37f932d2f3e6d9ec3d9fa4e4cf411c172c36--Obsidian-0.14.6-universal.dmg

Access: 2022-04-20 04:24:00.000000000 +0800
Modify: 2022-04-20 04:24:00.000000000 +0800
Change: 2022-04-20 20:11:15.303374998 +0800
 Birth: 2022-04-20 04:24:00.000000000 +0800
```

The birth time is newer than obsidian cask update time.

**Pull request merged**
