### PR TITLE
Add CLIPS IDE v6.40

### PR DESCRIPTION
**Pull request by xyb**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
  - ~~dont know why, but audit command raise an error: undefined method `length' for nil:NilClass~~
  - ~~and I can not post the issue because Github report 400 error~~
  - ~~details of the issue I posted is here: https://gist.github.com/xyb/8a9ee3b116dcc51be8f5b65ee0e57df4~~
  - ~~sorry I do not follow the instruction, but after two weeks of trying, I did not have any way to report this, so I ended up posting it here~~
  - fixed, and `No zap stanza present for Cask 'clips-ide'`
  - but the issue of posting new bug really needs to be taken care of
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Try this -- it passed `audit` and `style` for me locally:
```
cask "clips-ide" do
  version "6.40"
  sha256 "fc76fc5cc97f2d6fc00a72f43983765adb500d8c249cd75b5fdf57f799c3c895"

  url "https://downloads.sourceforge.net/clipsrules/clips_macos_executable_#{version.no_dots}.dmg",
      verified: "downloads.sourceforge.net/clipsrules/"
  name "clips-ide"
  desc "Tool for building expert systems"
  homepage "http://www.clipsrules.net/"

  livecheck do
    url "https://sourceforge.net/projects/clipsrules/files/latest/download"
    strategy :header_match
    regex(%r{/CLIPS/(\d+(?:\.\d+)+)/}i)
  end

  depends_on macos: ">= :el_capitan"

  app "CLIPS IDE.app"
end
```
Then you just need to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap).

**Comment by xyb** [comment]
@miccal Thank your very much for your help! Although I still couldn't pass the check after modifying, but it force me to start thinking about what the difference between our two environments is. And I found that I had set up a proxy agent service. After removing it the audit process works just fine.

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @xyb.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by xyb** [comment]
@miccal I had tried `brew uninstall --zap clips-ide` and brew said `No zap stanza present for Cask 'clips-ide'`:
```
❯ brew uninstall --zap clips-ide
==> Implied `brew uninstall --cask clips-ide`
==> Backing App 'CLIPS IDE.app' up to '/opt/homebrew/Caskroom/clips-ide/6.40/CLIPS IDE.app'
==> Removing App '/Applications/CLIPS IDE.app'
Warning: No zap stanza present for Cask 'clips-ide'
==> Removing all staged versions of Cask 'clips-ide'
```

**Comment by miccal** [comment]
> @miccal I had tried `brew uninstall --zap clips-ide` and brew said `No zap stanza present for Cask 'clips-ide'`:

Yes, that is because you have not added a `zap` stanza -- please read the documentation I linked above.

**Comment by xyb** [comment]
@miccal I had checked these directories:
```
~/Library/Preferences/*clips*
~/Library/Application Scripts/
~/Library/Application Support/
~/Library/Caches/
~/Library/Containers/*clips*
~/Library/Preferences/*clips*
~/Library/Saved Application State/
```
the only file I found was `~/Library/Saved Application State/com.SSoP.CLIPSIDE.savedState`, but I don't think it should be removed when uninstalling CLIPS IDE. So does this mean that we don't need a zap stanza?

**Comment by xyb** [comment]
Sorry, I think I missed a file `~/Library/Preferences/com.SSoP.CLIPSIDE.plist` that came up after I had been using the CLIPS IDE for a few hours. I've committed the new changes.

**Comment by bevanjkay** [comment]
> the only file I found was `~/Library/Saved Application State/com.SSoP.CLIPSIDE.savedState`, but I don't think it should be removed when uninstalling CLIPS IDE. So does this mean that we don't need a zap stanza?

@xyb Why shouldn't the file be removed by the `zap` stanza?

**Comment by carlocab** [comment]
Note that files in the zap stanza are not necessarily removed with `brew uninstall`. The files in the zap stanza are removed only with `brew uninstall --zap`. The zap stanza is designed to remove all traces of the cask from your system, so it seems to me that `~/Library/Saved Application State/com.SSoP.CLIPSIDE.savedState` is exactly what we want in the zap stanza.

**Comment by miccal** [comment]
Thank you @xyb.

**Comment by xyb** [comment]
@carlocab Thank you for your advice. So far it's ok because I have checked that `~/Library/Saved Application State/com.SSoP.CLIPSIDE.savedStat` will be deleted automatically after CLIPS IDE exits.

**Pull request merged**
