### PR TITLE
Update shapes to 4.9

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by gtmgianni** [comment]
Contacted developer for confirmation: https://twitter.com/gtmgianni/status/995749255569727488

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/ShapesApp?ref_src=twsrc%5Etfw">@ShapesApp</a> <a href="https://twitter.com/iTod?ref_src=twsrc%5Etfw">@iTod</a> The SHA-256 hash for version 4.9 has changed. Could you confirm this change was not malicious, for the purpose of this pull request: <a href="https://t.co/4M2QAwyDRT">https://t.co/4M2QAwyDRT</a> Thank you in advance.<br>/cc <a href="https://twitter.com/homebrewcask?ref_src=twsrc%5Etfw">@homebrewcask</a></p>&mdash; Gianni Tam-McMillan (@gtmgianni) <a href="https://twitter.com/gtmgianni/status/995749255569727488?ref_src=twsrc%5Etfw">May 13, 2018</a></blockquote>

**Comment by gtmgianni** [comment]
Is this signature valid? I'm looking at the second signature from Apple in particular (the one that says "Failed or Weak".

screen shot 2018-05-13 at 21 24 08

**Comment by commitay** [comment]
> "Failed or Weak"

IIRC this occurs with sometimes because of the signature type, it's still considered valid.

**Comment by gtmgianni** [comment]
@commitay Should this be merged since the signature is valid?

**Pull request merged**
