### PR TITLE
AlDente: Using version 1 for <= :catalina

### PR DESCRIPTION
**Pull request by ondrejfuhrer**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Related PR: https://github.com/Homebrew/homebrew-cask/pull/100526

Thx @jconley for noticing this 🙂

### CODE REVIEW

**Comment by ondrejfuhrer** [comment]
@jconley Hmm, I just noticed that it was tested on macOS 10.15 in the https://github.com/Homebrew/homebrew-cask/runs/2016232257 and was installed successfully. Does that mean it can be installed but then cannot run?

I don't have any pre-big sur env where I can test it.

**Comment by jconley** [comment]
@ondrejfuhrer correct. the app is simply .zip'd and brew decompresses/copies... there is no installer. (some casks/apps use a .pkg installer which needs to be run to install)

**Comment by ondrejfuhrer** [comment]
> @ondrejfuhrer correct. the app is simply .zip'd and brew decompresses/copies... there is no installer. (some casks/apps use a .pkg installer which needs to be run to install)

Great, thx for the clarification @jconley 👍  then the PR should fix it.

**Comment by miccal** [comment]
Thank you @ondrejfuhrer.

**Review by miccal — APPROVED** [review]

**Pull request merged**
