### PR TITLE
Update recents to 2.0.1,4624

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
@suschizu Do you personally need the previous version?

**Comment by suschizu** [comment]
hey - hm not really - fortunately the appcast is very accurate - I think the depends on would also be enough

**Comment by commitay** [comment]
Please remove the old version and set `depends_on macos: '>= :high_sierra'.

If anyone acuually needs an older version they can open an issue or send a PR.

**Comment by reitermarkus** [comment]
Please fix the style errors.

**Pull request merged**
