### PR TITLE
Run Keyman post-install operations

### PR DESCRIPTION
**Pull request by myzhang1029**
Keyman's maintainers have kindly proposed to run the installer actions.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask keyman` is error-free.
- [x] `brew style --fix keyman` reports no offenses.

### CODE REVIEW

**Comment by myzhang1029** [comment]
macOS always refuses to run the `textinputsource` script, not sure if it is related to my M1 arch.
I'll update the "caveats" stanza when I get around that.

**Comment by vitorgalvao** [comment]
We don’t delete the quarantine, *we add it* and go to some lengths to do so. A download via `curl` (which Homebrew uses) does not add the quarantine.

To install something without quarantining, use the `--quarantine` flag.

**Comment by mcdurdin** [comment]
This is all from somewhat fuzzy memory, sorry...  

`Install Keyman.app` also has this quarantine bit applied, so the user would receive two quarantine prompts in the install -- one for the installer app, and one for `Keyman.app`, which just seems excessive.

Another reason we decided to remove the quarantine bit from `Keyman.app` was that in some circumstances macOS was not presenting UI to 'allow' Keyman to run (something to do with it being an input method, I think). This meant that Keyman would simply appear not to work, and the user would have to figure out how to go to ~/Library/Input Methods and manually remove the quarantine bit from Keyman.app.

I'd need to investigate further and do some testing to verify that my recollection is 100% correct here...

(We'd prefer not to do remove quarantine bits, but this seemed better than a broken install from the end user point-of-view. The other security prompts are not bypassed by the installer -- they are presented to the user as is appropriate, even if the current implementation is a little rough.)

**Comment by vitorgalvao** [comment]
Like I said, installing with `--no-quarantine` will not add the quarantining. You’re free to suggest that to your users. But removing the quarantining we add doesn’t make sense.

I hope you understand that I don’t know you nor your app. My concern is the users of HBC, and they have an expectation that quarantine will be added unless *they* decide not to.

**Comment by mcdurdin** [comment]
Yes, understood. I'm happy if we document the manual steps that users need to take in order to remove the quarantine bit given that macOS doesn't always prompt to do this for input methods, in my experience.

**Pull request closed without merging**
