### PR TITLE
Add HeimatDefender.app v1.1

### PR DESCRIPTION
**Pull request by chaos-engine**
After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @chaos-engine.

**Review by miccal — APPROVED** [review]

**Comment by 0x46616c6b** [comment]
Why this game is added to homebrew? "Heimatdefender" is a game from a far right german hate organisation called "Ein Prozent". They are blocked from Facebook and loosed at court about this deletion. The court follows the argumation that the organisation spread (far right) hate.

- https://de.wikipedia.org/wiki/Heimat_Defender:_Rebellion
- https://gnet-research.org/2020/09/17/no-childs-play-the-identitarian-movements-patriotic-video-game/

**I would suggest to follow platforms like Steam to not support there aim to spread hate with gamification.**

**Comment by varac** [comment]
I agree, this game should get removed. It's featuring, next to others, [Martin Sellner](https://en.wikipedia.org/wiki/Martin_Sellner) as a main character, who is a leader of the [Identitäre Bewegung](https://en.wikipedia.org/wiki/Identitarian_movement) Österreichs (IBÖ, Identitarian Movement of Austria). Hate games should not get supported.

**Comment by xshadow** [comment]
There should be no place for this in brew, this should be reverted.

**Comment by claui** [comment]
Thanks @0x46616c6b for bringing this up, and thanks @reitermarkus for reverting.

**Comment by miccal** [comment]
Apologies for merging this, I should have been more thorough when I initially checked it.

**Comment by varac** [comment]
Awesome, thanks for the quick response.

**Pull request merged**
