### PR TITLE
Update blackhole and add support for 2/16 channels

### PR DESCRIPTION
**Pull request by leafac**
After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md). **I don’t know what to do here because BlackHole now supports 2 versions: 16-channel (similar to previous versions) and 2-channel (new). I broke the `blackhole` cask into `blackhole-16ch` and `blackhole-2ch`. Maybe we should just stick with `blackhole` and continue to install the 16-channel version. Maybe we should switch to the 2-channel version, which is probably more useful to most people. Maybe we should have one of the two as a `cask-versions`.**
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
I think what you have proposed is is for the best, thanks @leafac.

**Review by miccal — APPROVED** [review]

**Comment by leafac** [comment]
Thank you very much, @miccal

**Comment by loikein** [comment]
Wait, people, I'm just a random user here, but would homebrew please give more helpful information when renaming casks instead of actually deleting them? It's been confusing two in a row now (Zoom seveal days ago).

**Comment by leafac** [comment]
@loikein I think the non-cask part of homebrew does something along those lines. Also, it seems that the non-cask and cask parts of homebrew are becoming closer and closer. Maybe something like what you want will exist for casks soon.

**Comment by loikein** [comment]
@leafac Thank you, fingers crossed…

**Pull request merged**
