### PR TITLE
xmind 22.11.3771-202305311748

### PR DESCRIPTION
**Pull request by WangEdward**
https://github.com/orgs/Homebrew/discussions/4553

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@WangEdward Can you please check with upstream to see if the version downgrade is correct?

**Comment by WangEdward** [comment]
From there updated website, it seems that 23 is now becoming the beta version ([bottom of this page](https://xmind.app/download/)) and 22 should be the stable version.
[Website now.](https://web.archive.org/web/20230603120335/https://xmind.app/desktop/release-notes/) (23 is removed from the release note)
[Website 8 hours ago.](https://web.archive.org/web/20230603031350/https://xmind.app/desktop/release-notes/)

**Comment by razvanazamfirei** [comment]
Thank you, @WangEdward!

**Review by razvanazamfirei — APPROVED** [review]

**Comment by nsteinmetz** [comment]
Hi there,

I was surprised by the version downgrade.

Maybe there should be a warning as there is a format upgrade between 22.x version and 23.x version. So rollbacking on 22.X version may lead to incompatibilities issues.

**Pull request merged**
