### PR TITLE
Update sleek to 1.1.5

### PR DESCRIPTION
**Pull request by ransome1**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@ransome1 Your PR seems to have a conflict, however I won't be able to help fix it, because maintainers cannot push to a PR opened from your `master` branch, only from those opened from a different `branch`.

**Comment by ransome1** [comment]
Sorry for the hicup, I fixed it :)

**Comment by bevanjkay** [comment]
@ransome1 Can you please run `brew style --fix sleek` to fix the style issues

**Comment by ransome1** [comment]
@bevanjkay style should be fixed now

**Pull request merged**
