### PR TITLE
Update joplin from 1.0.241 to 1.0.242

### PR DESCRIPTION
**Pull request by priitohlo**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> Error: It seems the App source '/usr/local/Caskroom/joplin/1.0.242/Joplin.app' is not there.

It’s failing due to not finding a source to install. We have [documentation on how to fix it](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md).

**Comment by priitohlo** [comment]
Hmm, that's strange. The source filename is still the same in the new release (https://github.com/laurent22/joplin/releases/download/v1.0.242/Joplin-1.0.242.dmg).

**Comment by vitorgalvao** [comment]
Rerunning tests.

**Comment by core-code** [comment]
i can confirm it is still named 'Joplin.app'
something must be off with the test

**Comment by miccal** [comment]
Already updated via https://github.com/Homebrew/homebrew-cask/pull/88783.

**Pull request closed without merging**
