### PR TITLE
Remove `sudo: false`

### PR DESCRIPTION
**Pull request by vitorgalvao**
Refs https://github.com/caskroom/homebrew-cask/issues/13608 and https://github.com/Homebrew/brew/pull/2330.

### CODE REVIEW

**Comment by sebastienbarre** [comment]
This is breaking `google-cloud-sdk` it seems.
 
I'm getting dozens and dozens of:
```
==> chmod: Unable to change file mode on /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/th...
==> chmod: Unable to change file mode on /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/VERSION: Operation
==> Using sudo to gain ownership of path '/usr/local/Caskroom/google-cloud-sdk/latest'
Error: Command failed to execute!

==> Failed command:
/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames (\"git-credential-gcloud\") /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/git-credential-gcloud.sh

==> Standard Output of failed command:


==> Standard Error of failed command:
xattr: [Errno 13] Permission denied: '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/git-credential-gcloud.sh'


==> Exit status of failed command:
#<Process::Status: pid 69886 exit 1>
Error: nothing to install
```

**Comment by snafis** [comment]
I am getting the same error as well. I got it to work by adding back `sudo:   false`, however, couldn't figure out anything obvious with permissions.

**Comment by reitermarkus** [comment]
This shouldn't have been merged yet, since the changes in https://github.com/Homebrew/brew/pull/2330 aren't in a tagged release yet.

**Comment by vitorgalvao** [comment]
My fault. I remembered that but forgot to put the `on hold` tag. When it was merged I thought that maybe a release would be soon enough to not be worth reverting.

**Comment by miccal** [comment]
@vitorgalvao @reitermarkus apologies, that completely slipped my mind when I merged this.

**Comment by timothybasanov** [comment]
It does break google-cloud-sdk: #31173.

**Comment by miccal** [comment]
@timothybasanov this will be rectified once https://github.com/Homebrew/brew/pull/2330 is in a tagged release.

**Comment by dlee** [comment]
This also breaks the miniconda package. When is Homebrew/brew#2330 expected to be in a tagged release?

**Comment by vitorgalvao** [comment]
There’s no set date for it to be fixed. If anyone is in a hurry, set `HOMEBREW_DEVELOPER=1` and update.

After the new release, just unset `HOMEBREW_DEVELOPER`.

**Pull request merged**
