### PR TITLE
Add IRPF2021 v1.3

### PR DESCRIPTION
**Pull request by alisio**
This is an app for income declaration and tax calculation made for
Brazilian tax payers.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by cho-m** [comment]
Please delete one of the files. 

Based on [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md),
`irpf2021.rb` is probably the right file/name and `irpf-2021.rb` should be deleted (`git rm irpf-2021.rb`).

**Comment by alisio** [comment]
Deleted extra file committed by accident, as requested.

**Review by SMillerDev — DISMISSED** [review]

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @alisio.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

**Comment by alisio** [comment]
> Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

Sure. Zap stanza added according to information provided by @nrlquaker's CreateZap and AppCleaner.

**Comment by cho-m** [comment]
Is trash of `"/Applications/IRPF2021.app"` necessary?
I think basic `brew uninstall` logic deals with this.

**Review by miccal — APPROVED** [review]

**Pull request merged**
