### PR TITLE
Update genymotion from 3.1.1 to 3.1.2

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Review by core-code — DISMISSED** [review]

**Comment by core-code** [comment]
@vitorgalvao any idea here?

**Comment by vitorgalvao** [comment]
> any idea here?

CI choking again. Other PRs are failing the same way. @reitermarkus Has there been any recent CI change?

**Comment by miccal** [comment]
See https://github.com/Homebrew/actions/pull/104 and https://github.com/Homebrew/actions/pull/109.

**Comment by vitorgalvao** [comment]
Thank you for investigating @miccal. Merged.

**Pull request merged**
