### PR TITLE
Metasploit

### PR DESCRIPTION
**Pull request by dcondrey**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by dcondrey** [comment]
If there are any comments I may need a couple of days to respond, I apologize.

**Review by vitorgalvao — APPROVED** [review]

**Comment by commitay** [comment]
metasploitframework-latest.pkg is a nightly build. 

See [https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers#os-x-manual-installation](https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers#os-x-manual-installation)

I think the version and shasum might have to be removed unless there is a way around this.

**Comment by commitay** [comment]
I've tried installing this and I get:

```
% brew cask install metasploit.rb            
==> Satisfying dependencies
==> Installing Formula dependencies from Homebrew
nmap ... already installed
postgresql ... already installed
complete
==> Downloading https://osx.metasploit.com/metasploitframework-latest.pkg
######################################################################## 100.0%
==> No checksum defined for Cask metasploit, skipping verification
==> Running installer script /opt/metasploit-framework/bin/msfconsole
==> sudo: /opt/metasploit-framework/bin/msfconsole: command not found
==> Running installer for metasploit; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
==> installer: Package name is Metasploit-framework
==> installer: Installing at base path /
==> installer: The install was successful.
```

This seems to be trying to run files that haven't been created by the .pkg yet.
```
==> Running installer script /opt/metasploit-framework/bin/msfconsole
==> sudo: /opt/metasploit-framework/bin/msfconsole: command not found
```

**Comment by miccal** [comment]
Ping @vitorgalvao for a final check.

**Comment by vitorgalvao** [comment]
From @commitay’s report, it seems likely the `installer` part will have to be converted into a `postflight` `system_command` instead.

**Comment by dcondrey** [comment]
I will get this fixed later today or tomorrow.  Thank you.

**Comment by commitay** [comment]
Running /opt/metasploit-framework/bin/msfconsole asks for user input to add /opt/metasploit-framework/bin to PATH, which is does by writing to ~/.profile , this doesn't work with zsh. Then asks to create a database at ~/.msf4 , when this is finished it doesn't exit, it stops at the msf > prompt.


```
  postflight do
    system_command '/opt/metasploit-framework/bin/msfconsole', input: 'y'
  end
``` 

I tried postflight after I found [this](https://github.com/caskroom/homebrew-cask/issues/31223#issuecomment-288745636) for passing input but without a way to exit it just eats cpu.


We could add binary stanzas for the contents of /opt/metasploit-framework/bin , tried this and msfconsole doesn't ask to be added to PATH if this is done first.


The uninstall script doesn't seem to be needed as "uninstall pkgutil" does the same thing as msfremove.


```
cask 'metasploit' do
  version :latest
  sha256 :no_check

  url 'https://osx.metasploit.com/metasploitframework-latest.pkg'
  name 'Metasploit Framework'
  homepage 'https://www.metasploit.com/'

  depends_on formula: %w[
                        nmap
                        postgresql
                      ]

  pkg 'metasploitframework-latest.pkg'
  binary '/opt/metasploit-framework/bin/metasploit-aggregator'
  binary '/opt/metasploit-framework/bin/msfbinscan'
  binary '/opt/metasploit-framework/bin/msfconsole'
  binary '/opt/metasploit-framework/bin/msfd'
  binary '/opt/metasploit-framework/bin/msfdb'
  binary '/opt/metasploit-framework/bin/msfelfscan'
  binary '/opt/metasploit-framework/bin/msfmachscan'
  binary '/opt/metasploit-framework/bin/msfpescan'
  binary '/opt/metasploit-framework/bin/msfremove'
  binary '/opt/metasploit-framework/bin/msfrop'
  binary '/opt/metasploit-framework/bin/msfrpc'
  binary '/opt/metasploit-framework/bin/msfrpcd'
  binary '/opt/metasploit-framework/bin/msfupdate'
  binary '/opt/metasploit-framework/bin/msfvenom'

  uninstall pkgutil: '.*metasploit.*',
            delete:  '/opt/metasploit-framework'
end

```

**Comment by commitay** [comment]
Just found #25128. Didn’t realise there was a PR for metasploit previously.

@vitorgalvao I’m probably misunderstanding the reason for `version`,`shasum` and `appcast` but the [github source releases](https://github.com/rapid7/metasploit-framework/releases) don’t look like they match the [nightly .pkgs](https://osx.metasploit.com/)

Currently the latest github release is `4.14.4` and the nightly is `metasploit-framework-4.14.3+20170321092309.git.3.d7b93b8-1rapid7-1.pkg` / `metasploitframework-latest.pkg`

I can see how this work for a cask like [vagrant](https://github.com/caskroom/homebrew-cask/blob/master/Casks/vagrant.rb) with releases in sync, just not sure how it works here.

Apologies if I am wasting your time with something that does work, just disregard this comment.

**Comment by gobinathm** [comment]
Since its not merged and there is an upgrade available. I would suggest the requestor to update it to version 4.14.5

**Comment by commitay** [comment]
Creating the database can be done by running `/opt/metasploit-framework/bin/msfdb init` without user input but this seems to require the folder `~/.msf4` be created first.

Similar issues have come up before in different forms like incorrect ownership or missing subdirectories or files.

Running `mkdir -p ~/.msf4 && /opt/metasploit-framework/bin/msfdb init` can make it work (for now at least) but the folder is created automatically with `msfconsole` without any problems so it might be easier to add a caveat.

```
  caveats <<-EOS.undent
              To create database and complete setup run:

              msfconsole
            EOS
```

**Comment by commitay** [comment]
Redid `version` and `url` as I found having `metasploitframework-latest.pkg` with a `sha` will fail with `Error: sha256 mismatch` every 24 to 48 hours.

Switching to a versioned download should keep the cask functional for a couple of weeks without being updated.

Added gpg and appcast.

```
cask 'metasploit' do
  version '4.14.6,20170325092307'
  sha256 '8367198a6e5290f88fdfbb6ff71c59ed1e20827d3fc7df2d5a4ae32cda82b315'

  url "https://osx.metasploit.com/metasploit-framework-#{version.major_minor_patch}+#{version.after_comma}-1rapid7-1.pkg"
  appcast 'https://osx.metasploit.com/LATEST',
          checkpoint: '29508eb54b33f9120fb31e02a6b3f7397927dd98b3b857a7613c402e2d223e0c'
  name 'Metasploit Framework'
  homepage 'https://www.metasploit.com/'
  gpg "#{url}.asc", key_id: '2007B954'

  depends_on formula: %w[
                        nmap
                        postgresql
                      ]

  pkg 'metasploitframework-latest.pkg'
  binary '/opt/metasploit-framework/bin/metasploit-aggregator'
  binary '/opt/metasploit-framework/bin/msfbinscan'
  binary '/opt/metasploit-framework/bin/msfconsole'
  binary '/opt/metasploit-framework/bin/msfd'
  binary '/opt/metasploit-framework/bin/msfdb'
  binary '/opt/metasploit-framework/bin/msfelfscan'
  binary '/opt/metasploit-framework/bin/msfmachscan'
  binary '/opt/metasploit-framework/bin/msfpescan'
  binary '/opt/metasploit-framework/bin/msfremove'
  binary '/opt/metasploit-framework/bin/msfrop'
  binary '/opt/metasploit-framework/bin/msfrpc'
  binary '/opt/metasploit-framework/bin/msfrpcd'
  binary '/opt/metasploit-framework/bin/msfupdate'
  binary '/opt/metasploit-framework/bin/msfvenom'

  uninstall pkgutil: '.*metasploit.*',
            delete:  '/opt/metasploit-framework'

  caveats <<-EOS.undent
              To create database and complete setup run:

              msfconsole
            EOS
end

```

**Comment by commitay** [comment]
Sorry for the spam, made a couple of BAD mistakes and deleted by accident instead of editing.

Need more :coffee::coffee:

I think this is right but I've probably done something wrong.

Redid `version` and `url` as I found `metasploitframework-latest.pkg` will fail with `sha error` every 24 to 48 hours.

Having a versioned `url` should keep the cask functional for a couple of weeks without update.

Added `gpg` and an `appcast` to match .pkg releases.

```
cask 'metasploit' do
  version '4.14.6,20170325092307'
  sha256 '8367198a6e5290f88fdfbb6ff71c59ed1e20827d3fc7df2d5a4ae32cda82b315'

  url "https://osx.metasploit.com/metasploit-framework-#{version.major_minor_patch}+#{version.after_comma}-1rapid7-1.pkg"
  appcast 'https://osx.metasploit.com/LATEST',
          checkpoint: '29508eb54b33f9120fb31e02a6b3f7397927dd98b3b857a7613c402e2d223e0c'
  name 'Metasploit Framework'
  homepage 'https://www.metasploit.com/'
  gpg "#{url}.asc", key_id: '2007B954'

  depends_on formula: %w[
                        nmap
                        postgresql
                      ]

  pkg "metasploit-framework-#{version.major_minor_patch}+#{version.after_comma}-1rapid7-1.pkg"
  binary '/opt/metasploit-framework/bin/metasploit-aggregator'
  binary '/opt/metasploit-framework/bin/msfbinscan'
  binary '/opt/metasploit-framework/bin/msfconsole'
  binary '/opt/metasploit-framework/bin/msfd'
  binary '/opt/metasploit-framework/bin/msfdb'
  binary '/opt/metasploit-framework/bin/msfelfscan'
  binary '/opt/metasploit-framework/bin/msfmachscan'
  binary '/opt/metasploit-framework/bin/msfpescan'
  binary '/opt/metasploit-framework/bin/msfremove'
  binary '/opt/metasploit-framework/bin/msfrop'
  binary '/opt/metasploit-framework/bin/msfrpc'
  binary '/opt/metasploit-framework/bin/msfrpcd'
  binary '/opt/metasploit-framework/bin/msfupdate'
  binary '/opt/metasploit-framework/bin/msfvenom'

  uninstall pkgutil: '.*metasploit.*',
            delete:  '/opt/metasploit-framework'

  caveats <<-EOS.undent
              To create database and complete setup run:

              msfconsole
            EOS
end

```

**Comment by vitorgalvao** [comment]
@commitay Why don’t you simply submit a PR?

Also, that `caveats` needs to go. We only have `caveats` pertaining to install instructions, not to usage instructions.

**Comment by commitay** [comment]
@vitorgalvao Sorry, I wasn't sure if I should do a new PR. Will do so in a minute.

**Comment by vitorgalvao** [comment]
Closed in favour of https://github.com/caskroom/homebrew-cask/pull/31311. Thank you for starting it, @dcondrey.

**Pull request closed without merging**
