### PR TITLE
Re-add QuickRadar 1.1

### PR DESCRIPTION
**Pull request by dwaite**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

https://github.com/caskroom/homebrew-cask/pull/33634

### CODE REVIEW

**Comment by dwaite** [comment]
Sorry - I was looking just at issues and not PRs, so I didn't see the removal.

The previous removal was #33634 . The site reverse DNS is still amyworrall.com, with the project appearing to be listed as an open source project on her homepage ( see http://amyworrall.com/opensource.php )

**Review by commitay — APPROVED** [review]

**Comment by vitorgalvao** [comment]
What am I missing? The page appears to still be down.

**Comment by commitay** [comment]
It was working yesterday.

**Comment by commitay** [comment]
And it's working again.

**Comment by vitorgalvao** [comment]
> And it's working again.

And it looks as abandoned as before (https://github.com/amyworrall/QuickRadar#status).

It [hasn’t gotten a commit in over a year](https://github.com/amyworrall/QuickRadar/commits/master) and is [admittedly not stable](https://github.com/amyworrall/QuickRadar#status). I think this deserves a `discontinued` `caveat`, to keep a closer eye on. I don’t expect the cask to last much.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
