### PR TITLE
updated stellarium (0.14.2)

### PR DESCRIPTION
**Pull request by vladimirdolzhenko**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as d850d4f5def0f7048d86d09460dd020894d3ba31 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by vladimirdolzhenko** [comment]
@vitorgalvao sorry - it is not clear to - why commit has not been merged ?

**Comment by vitorgalvao** [comment]
Apologies, it was an (automation) error.

**Comment by vitorgalvao** [comment]
Merged as acecb6a9ddfd7ee3e7f9c5a1d34ed2ae77dbd1c4.

**Pull request closed without merging**
