### PR TITLE
Add SwiftyBeaver

### PR DESCRIPTION
**Pull request by thii**
#### Adding a new cask
- [x] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Commit message includes cask’s name.
- [x] `brew cask audit --download swifybeaver` is error-free.
- [x] `brew cask style --fix swifybeaver` left no offenses.
- [x] `brew cask install swifybeaver` worked successfully.
- [x] `brew cask uninstall swifybeaver` worked successfully.

### CODE REVIEW

**Comment by adidalal** [comment]
Looks like a closed beta?

**Comment by thii** [comment]
@adidalal Yep. You need an invite code in order to sign up.

**Comment by adidalal** [comment]
You can add an appcast: `https://cdn.swiftybeaver.com/sbmac-appcast.xml`
Also change this to a versioned cask and add in `auto_updates true`
The versioned url: 'https://cdn.swiftybeaver.com/SBMac-#{version}.zip` with a version of 0.7.0

**Comment by adidalal** [comment]
Thank you for the contribution. It needed some fixes, so they were made in c6e10e3f63e07c88c91860c2f292f5754735ddac. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
