### PR TITLE
Upgrade CocoaPods to v1.0.0.beta.5

### PR DESCRIPTION
**Pull request by orta**

### CODE REVIEW

**Comment by orta** [comment]
uh oh, let's find that sha

**Comment by vitorgalvao** [comment]
Updating the `:checkpoint` value in `appcast` is required. You can find it with `curl --silent --compressed "{{appcast_url}}" | sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256 | awk '{ print $1 }'`.

Alternatively, you may wish to use [`cask-repair`](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair). It can at once update the cask’s version (according to what you give it) taking care of updating both the cask’s `sha256` and the appcast’s `:checkpoint`, while still giving you the chance to perform other manual fixes.

You can easily install it with `brew install vitorgalvao/tiny-scripts/cask-repair`. `cask-repair --help` will show you some options, but as a whole the script will guide you through the update process.

Also, please [squash your commits](http://davidwalsh.name/squash-commits-git).

**Comment by orta** [comment]
OK, cool, thanks.

 I'm gonna update our tooling and open another PR once that's done :+1: (don't want to leave hanging PRs around for you. Can't be too sure when I'll get around to this. )

**Comment by vitorgalvao** [comment]
Sure thing. I’ll update this one for you, then. Already done in https://github.com/caskroom/homebrew-cask/pull/19808.

The command I ran was simply `cask-repair --cask-version 1.0.0.beta.5 --blind-submit cocoapods`, and it was done. It even takes care of submitting the PR automatically.

**Comment by orta** [comment]
Thanks @vitorgalvao ! :+1: appreciated - all of this PR is done via a script as a part of our deploy process - so I want to make sure others don't need to have cask-repair installed in order to ship builds in the future

**Pull request closed without merging**
