### PR TITLE
Update miniforge from 4.9.2-7 to 4.10.0-0

### PR DESCRIPTION
**Pull request by mhdmyz**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by mhdmyz** [comment]
@miccal What was the problem with my `brew bump-cask-pr` command? I couldn't figure it out. I tried:
`brew bump-cask-pr --version '4.10.0-0' --url 'https://github.com/conda-forge/miniforge/releases/download/4.10.0-0/Miniforge3-4.10.0-0-MacOSX-arm64.sh' --sha256 '5813f9eadda46f655fdcf2daee10a8586ba067bb453551466fb66168268ea31b' --force miniforge`

**Comment by miccal** [comment]
`brew bump-cask-pr` does not handle Cask's with `if Hardware::CPU.intel?` just yet.

**Comment by mhdmyz** [comment]
> `brew bump-cask-pr` does not handle Cask's with `if Hardware::CPU.intel?` just yet.

So how did you do it? BTW I tried to update my miniforge right now with brew update and brew upgrade command and I'm getting the following error:

`Error: Cask 'miniforge' is unreadable: /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/miniforge.rb:5: syntax error, unexpected <<
<<<<<<< Updated upstream
^~
/opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/miniforge.rb:8: syntax error, unexpected ===, expecting end
=======
^~~
/opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/miniforge.rb:11: syntax error, unexpected >>, expecting end
>>>>>>> Stashed changes
^~
`

**Comment by miccal** [comment]
> So how did you do it? 

I did it manually.

> BTW I tried to update my miniforge right now with brew update and brew upgrade command and I'm getting the following error:

It looks like it is conflicting with your local changes -- what is the output of `brew doctor`?

**Comment by mhdmyz** [comment]
> It looks like it is conflicting with your local changes -- what is the output of `brew doctor`?

Exactly the same thing.

Screen Shot 1400-01-17 at 16 11 17

**Comment by miccal** [comment]
Try running `brew update-reset`, then check `brew doctor` again.

**Comment by mhdmyz** [comment]
> Try running `brew update-reset`, then check `brew doctor` again.

Thanks! It did it for me :)

What was the issue?

**Comment by miccal** [comment]
A conflict with your local changes created by `brew bump-cask-pr` and the changes I made here :)

**Comment by mhdmyz** [comment]
> A conflict with your local changes created by `brew bump-cask-pr` and the changes I made here :)

Got you! Thanks man :)

So next time If a new version was available should I tell you again to do it manually?

**Comment by miccal** [comment]
Or just submit a PR and a maintainer will fix it before merging.

**Comment by mhdmyz** [comment]
> Or just submit a PR and a maintainer will fix it before merging.

Hi Miccal! Miniforge3-4.10.1-0 is released. Can you update Miniforge on brew please?

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/104625

**Comment by mhdmyz** [comment]
> Or just submit a PR and a maintainer will fix it before merging.

Hi Miccal! Miniforge3-4.10.1-1 is released. Can you update Miniforge on brew please?

**Comment by cho-m** [comment]
@mhdmyz In case you didn't know, `bump-cask-pr` is now capable of dealing with updating both Intel/ARM sections.

Just let the command autodetect everything and run:
`brew bump-cask-pr miniforge --version 4.10.1-1`

**Pull request merged**
