### PR TITLE
clickshare 4.30.2.2,48

### LINKED ISSUE #147460: brew install -f clickshare - Error
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I am running `Homebrew 4.0.18-85-g16b2a14` on `13.3.1 (a) (22E772610a)`
I had various packages installed from `core` and `cask` including `clickshare`.
At some point, I did run `brew doctor` and had some issues related to untracked `ruby`. 
Googling for this error I see others did encounter it. I got this resolved. These were some `brew` commands suggested I apply, but I do not have the list right now. One of the commands removed all packages /bottles and all `cask` applications. So when I did run `brew list` an empty list was returned. `brew doctor` only shows this
```bash
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```
To be clear. I did not reinstall `brew` at any point here.

So first thing I installed all non-cask packages.
Next, I did try to install all `cask` packages that were also removed. One thing I noticed is that when everything was removed from `brew`, I noticed that all `cask` packages were left in the `/Applications' folder`

Installing each one by one caused errors stating that such application already exists in the `/Applications` folders.
So I did try to install it with `-f` and that did the trick for some. Some I just had to manually remove from the `/Applications' folder first.

Then I got to my main issue related to reinstalling `clickshare`. No matter what I do it is failing at the same point with error
```bash
$ brew install -f clickshare
==> Downloading https://www.barco.com/services/website/en/TdeFiles/Download?FileNumber=R3306192&TdeType=3&MajorVersion=04&MinorVersion=28&Pat
==> Downloading from https://www.barco.com/us-en/support/software/R3306192
##O=#   #                                                                                                                                   
Error: SHA256 mismatch
Expected: 9b14dddad05c87a85c7d5fa9f004dc029fcec49abd14f8b8196d675f7ebf2f9e
  Actual: 68601ecc03804c0dc8957e5693bbe0425420aa90a777b5ff6a4c827f8b999bee
    File: /Users/oxoocoffee/Library/Caches/Homebrew/downloads/8a78c5d872823df59955204baa45cdcbcbe2475f35f5e76768efc9adef1a3ffe--R3306192
```

I did try to remove the sugested file and try to `install -f`. I get the same error.
Did try to remove anything I could find in `~/Libraries` related to `shareclick` and in `/opt/homebrew`, leaving any *.rb files.
Homebrew "git status" looks clean.

Any ideas? or additial information I can provide? Hhh, I did try to install with `-v -d` but I do not see anything unusual except the same error listed above.

### Command that failed

brew install clickshare

### Output of command with `--verbose --debug`

```shell
$ brew install -v -d clickshare
==> Downloading https://formulae.brew.sh/api/formula.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.0.18-85-g16b2a14\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --fail --location --remote-time --output /Users/oxoocoffee/Library/Caches/Homebrew/api/formula.jws.json --time-cond /Users/oxoocoffee/Library/Caches/Homebrew/api/formula.jws.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3804k  100 3804k    0     0  9880k      0 --:--:-- --:--:-- --:--:-- 9985k
==> Downloading https://formulae.brew.sh/api/cask.jws.json
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.0.18-85-g16b2a14\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --fail --location --remote-time --output /Users/oxoocoffee/Library/Caches/Homebrew/api/cask.jws.json --time-cond /Users/oxoocoffee/Library/Caches/Homebrew/api/cask.jws.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  979k  100  979k    0     0  2100k      0 --:--:-- --:--:-- --:--:-- 2119k
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading clickshare
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://www.barco.com/services/website/en/TdeFiles/Download?FileNumber=R3306192&TdeType=3&MajorVersion=04&MinorVersion=28&PatchVersion=00&BuildVersion=011
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.18-85-g16b2a14\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://www.barco.com/services/website/en/TdeFiles/Download\?FileNumber=R3306192\&TdeType=3\&MajorVersion=04\&MinorVersion=28\&PatchVersion=00\&BuildVersion=011
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.18-85-g16b2a14\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://www.barco.com/services/website/en/TdeFiles/Download\?FileNumber=R3306192\&TdeType=3\&MajorVersion=04\&MinorVersion=28\&PatchVersion=00\&BuildVersion=011
==> Downloading from https://www.barco.com/us-en/support/software/R3306192
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.18-85-g16b2a14\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --location --head https://www.barco.com/us-en/support/software/R3306192
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.18-85-g16b2a14\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/oxoocoffee/Library/Caches/Homebrew/downloads/8a78c5d872823df59955204baa45cdcbcbe2475f35f5e76768efc9adef1a3ffe--R3306192.incomplete https://www.barco.com/us-en/support/software/R3306192
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  422k    0  422k    0     0  1110k      0 --:--:-- --:--:-- --:--:-- 1131k
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/oxoocoffee/Library/Caches/Homebrew/downloads/8a78c5d872823df59955204baa45cdcbcbe2475f35f5e76768efc9adef1a3ffe--R3306192
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/oxoocoffee/Library/Caches/Homebrew/downloads/8a78c5d872823df59955204baa45cdcbcbe2475f35f5e76768efc9adef1a3ffe--R3306192
==> /Users/oxoocoffee/Library/Caches/Homebrew/downloads/8a78c5d872823df59955204baa45cdcbcbe2475f35f5e76768efc9adef1a3ffe--R3306192 is not quarantined
==> Quarantining /Users/oxoocoffee/Library/Caches/Homebrew/downloads/8a78c5d872823df59955204baa45cdcbcbe2475f35f5e76768efc9adef1a3ffe--R3306192
/usr/bin/env /usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/oxoocoffee/Library/Caches/Homebrew/downloads/8a78c5d872823df59955204baa45cdcbcbe2475f35f5e76768efc9adef1a3ffe--R3306192 https://www.barco.com/services/website/en/TdeFiles/Download\?FileNumber=R3306192\&TdeType=3\&MajorVersion=04\&MinorVersion=28\&PatchVersion=00\&BuildVersion=011 https://www.barco.com/en/clickshare/app
==> Verifying checksum for '8a78c5d872823df59955204baa45cdcbcbe2475f35f5e76768efc9adef1a3ffe--R3306192'
Error: SHA256 mismatch
Expected: 9b14dddad05c87a85c7d5fa9f004dc029fcec49abd14f8b8196d675f7ebf2f9e
  Actual: a873c6b18a0f48225ee6bdbf79625cf7ac9151c6959a2811b8f8c3448c405ea6
    File: /Users/oxoocoffee/Library/Caches/Homebrew/downloads/8a78c5d872823df59955204baa45cdcbcbe2475f35f5e76768efc9adef1a3ffe--R3306192
To retry an incomplete download, remove the file above.
/opt/homebrew/Library/Homebrew/extend/pathname.rb:288:in `verify_checksum'
/opt/homebrew/Library/Homebrew/downloadable.rb:101:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:81:in `verify_download_integrity'
/opt/homebrew/Library/Homebrew/cask/download.rb:60:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:172:in `download'
/opt/homebrew/Library/Homebrew/cask/installer.rb:70:in `fetch'
/opt/homebrew/Library/Homebrew/cask/installer.rb:104:in `install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.


$ brew config
HOMEBREW_VERSION: 4.0.18-85-g16b2a14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 16b2a14c9408140b04828462b660d30056421fdb
Last commit: 5 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4d270d6afeadf9fd209436ee305089e8ac411a5b
Core tap last commit: 4 hours ago
Core tap branch: master
Core tap JSON: 18 May 19:45 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.SX90NiAFRb/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
$ brew tap
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/core
osx-cross/avr
```

### PR DESCRIPTION
**Pull request by miccal**
This is an attempt to close https://github.com/Homebrew/homebrew-cask/issues/147460

The download `url` is obtained from here: https://www.barco.com/bin/barco/tde/downloadUrl.json?fileNumber=R3306192&tdeType=3

However, I cannot get this to work via `curl`.

Help needed.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@miccal It seems as though the token is added to the download URL when hitting the API endpoint. It would likely expire, so may not be a useful link. We could use a `url do` block to combine the two, but we do tend to avoid doing that.

**Comment by miccal** [comment]
This is not going to work.

**Comment by miccal** [comment]
Note to self:

https://github.com/andreasmalta/choco_packages/blob/master/clickshare-desktop/tools/chocolateyinstall.ps1

**Comment by miccal** [comment]
May not be worth the trouble:
```
==> Analytics
install: 0 (30 days), 3 (90 days), 3 (365 days)
```

**Comment by bevanjkay** [comment]
Most likely not, however keep in mind that analytics are only showing from March onwards after the migration away from GA.

**Pull request closed without merging**
