### PR TITLE
Update archi to 4.3

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
it doesn't seem to download the correct file although the URL is exactly the same as when downloading in the browser. not sure how to fix it.

**Review by vitorgalvao — APPROVED** [review]

**Comment by core-code** [comment]
i get it to download fine using 'curl' when i just add the referer, i.e. this one works
`curl   -H 'referer: https://www.archimatetool.com/download/' 'https://www.archimatetool.com/downloads/root43/Archi-Mac-4.3.zip'
`
but this one doesn't
`curl  'https://www.archimatetool.com/downloads/root43/Archi-Mac-4.3.zip'`

**Comment by vitorgalvao** [comment]
> i get it to download fine using 'curl' when i just add the referer

I did too, that’s why I only added that initially, but since it didn’t work I added the `user_agent`, which is also failing.

**Comment by core-code** [comment]
yes, the user_agent should work.
furthermore testing the cask with
```
brew cask fetch Casks/archi.rb
brew cask audit Casks/archi.rb --download
```
succeeds too. can this be a CI only issue?

**Comment by amyspark** [comment]
Manually `wget`ing the file returns `d3985e4ebb93ada39a24f232a68b27e95eb8cf3cccb1562de2c9a606ca1bd88f`.
Travis seems to be working correctly; @core-code, please update the hash and we should be ready to go.

**Review by amyspark — APPROVED** [review]

**Pull request merged**
