### PR TITLE
brackets: update livecheck strategy

### PR DESCRIPTION
**Pull request by daeho-ro**
The homepage version is not updated correctly, so change it to github releases and ignore windows things.

----

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Is brackets discontinued upstream? It's looks like the developers have moved onto something else.

**Comment by krehel** [comment]
That is also the impression I'm getting.  The download button on https://brackets.io points to version `2.1.2`, and a recommendation to switch to https://phcode.io.

This version of Brackets is already a forked version iirc as [Adobe EOL'd the original back in 2021.](https://opensource.adobe.com/brackets.io/index.html)

**Comment by bevanjkay** [comment]
Generally we would take the website version as the source of truth in these scenarios. But sometimes there is a greater level of nuance at play.
But I do think that a deprecation is probably the right way to go.

**Comment by krehel** [comment]
Yeah true - GitHub latest is 2.2.0 which was a year ago which is out of sync with the website.

Either way, I think deprecate makes sense.  I can add in the successor app in the next couple hours.  We can always undeprecate.

**Comment by krehel** [comment]
Apparently successor merged in #170688

**Comment by krehel** [comment]
Phoenix Code merged in #170688

**Review by miccal — APPROVED** [review]

**Pull request merged**
