### PR TITLE
Add Godot With Mono v3.0.2

### PR DESCRIPTION
**Pull request by hasahmed**
The Godot Game Engine has 2 different versions. One main version, and
another version that has support for C# scripting via mono. These are
different distributed apps, but perviously only the main version has been available
through brew cask.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

I wanted to rename the app to Godot.app or perhaps Godot-Mono.app, but I couldn't figure out how. So it is what it is.

### CODE REVIEW

**Comment by commitay** [comment]
Does this depend on Mono?

**Comment by Sposito** [comment]
Line 12:
`  app "Godot_v3.0.2-stable_mono_osx64.app"`
should be:
`  app 'Godot_v3.0.2-stable_mono_osx64.app', target: 'Godot Mono.app'`
to better fit standard godot cask and has a simpler name.

**Comment by vitorgalvao** [comment]
@Sposito No, [it should not](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md#target-should-only-be-used-in-select-cases).

**Comment by hasahmed** [comment]
@commitay Yes it does. I added the dependency and committed.
@Sposito I thought that the name should be a bit nicer looking, but after reading what @vitorgalvao linked it looks as though that should be avoided. So I left it the same. But I agree that godot-mono would be better than godot-with-mono, so I changed it.

**Comment by commitay** [comment]
Thanks for the PR!

**Pull request merged**
