### PR TITLE
various: add rosetta caveats [0-9a-c]

### PR DESCRIPTION
**Pull request by wickles**
Partial test/followup for #177913 (part 1)

### CODE REVIEW

**Comment by wickles** [comment]
Some spurious failures related to https://github.com/Homebrew/brew/pull/17573

> Failed to determine artifact architecture!

even with `atom` which is just one single intel binary in the app.

```
❯ lipo -archs Atom.app/Contents/MacOS/Atom
x86_64
```

**Comment by SMillerDev** [comment]
The `amazon-music` failure is because it does not support the macOS version, so that probably needs to be deprecated.

**Comment by wickles** [comment]
That Amazon Music app probably would be compatible with rosetta but they have that weird install script causing problems. I've removed the change from this PR.

Also reverted change to `bluestacks` since the Bluestacks X app is universal despite the url containing `x64` (false positive).

**Comment by SMillerDev** [comment]
Please split this in one commit per cask.

**Comment by wickles** [comment]
> Please split this in one commit per cask.

I really would rather not.

**Comment by bevanjkay** [comment]
> I really would rather not. Why?

It is standard practice in all Homebrew repositories, it keep commit history cleaner and makes it easier to revert individual changes as required.

**Comment by wickles** [comment]
I see, thanks for clarifying. Is this expectation documented somewhere for contributors? And can you suggest some tool or snippet to simplify the task? Thanks.

**Review by SMillerDev — APPROVED** [review]
Thanks @wickles ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request merged**
