### PR TITLE
Add cask Newshosting v2.2.1

### PR DESCRIPTION
**Pull request by joshka**
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:
- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Mind pointing me to the download page, to verify the link?

**Comment by joshka** [comment]
Unfortunately it's behind a login to the control panel.
https://controlpanel.newshosting.com/customer/action/downloadclient.php

There's a free trial account available (but I'm assuming it requires payment details).
Happy to provide a screen share or similar to assist with this. Flick me an email @joshka.net and we'll take it it offline.

**Comment by vitorgalvao** [comment]
> Unfortunately it's behind a login to the control panel.

In that case, [we cannot accept it](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) (walled build). Thank you anyway.

**Comment by joshka** [comment]
Fair call. I'll submit this to homebrew-unofficial.

**Pull request closed without merging**
