### PR TITLE
Update osxfuse from 3.11.2 to 4.0.4

### PR DESCRIPTION
**Pull request by weichenw**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
FYI: https://github.com/Homebrew/brew/issues/9401.

This will require a re-name and a bit of work, which may casue issues for Formula in `homebrew-core` that have a `depends_on :osxfuse`.

I would suggest that we wait until https://github.com/Homebrew/brew/pull/9403 is merged in tagged before doing this.

**Comment by weichenw** [comment]
> FYI: [Homebrew/brew#9401](https://github.com/Homebrew/brew/issues/9401).
> 
> This will require a re-name and a bit of work, which may casue issues for Formula in `homebrew-core` that have a `depends_on :osxfuse`.
> 
> I would suggest that we wait until [Homebrew/brew#9403](https://github.com/Homebrew/brew/pull/9403) is merged in tagged before doing this.

Sure mate. Thanks.

**Comment by core-code** [comment]
> I would suggest that we wait until Homebrew/brew#9403 is merged and tagged before doing this.

seems merged already, is it tagged too? what else needs to be done here?

**Comment by reitermarkus** [comment]
> what else needs to be done here?

This needs to be renamed to `macfuse` and the `OsxfuseRequirement` in `Homebrew/brew` needs to be updated to refer to the `macfuse` cask.

**Comment by miccal** [comment]
Thank you @weichenw -- closing in favour of https://github.com/Homebrew/homebrew-cask/pull/96258.

**Pull request closed without merging**
