### PR TITLE
Update snagit to 2018.0.1

### PR DESCRIPTION
**Pull request by ElfSundae**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
`2018` is correct.

```
ls -1 /Volumes/Snagit
Applications -> /Applications
Snagit 2018.app
```

**Comment by ElfSundae** [comment]
@commitay 

`Snagit 2018` is the app (display) name, like `Office 2016`.
`2018.0.1` is the `CFBundleShortVersionString` defined in `Info.plist`

qq20171117-141634
qq20171117-141733

**Comment by commitay** [comment]
`2018` is only used in the `app` stanza

https://github.com/caskroom/homebrew-cask/blob/8649dc5d5998d8bc04415671badf524d38388f48/Casks/snagit.rb#L1-L10

**Comment by ElfSundae** [comment]
Oh, I see..

**Comment by ElfSundae** [comment]
Then this cask will not need to update anymore unless the developer released a different name like "Snagit 2019"?

**Comment by ElfSundae** [comment]
Maybe it should be:

```
version '2018.x.x' 
sha256 '............'

url 'https://download.techsmith.com/snagitmac/enu/Snagit.dmg'
app "Snagit 2018.app" 
```

**Comment by commitay** [comment]
> Then this cask will not need to update anymore unless the developer released a different name like "Snagit 2019"?

Correct.

**Pull request closed without merging**
