### PR TITLE
Add nylas-mail-lives 2.2.0

### PR DESCRIPTION
**Pull request by danielbayley**
The original project was deprecated. This PR updates the cask to use the forked community project instead.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
We need upstream to approve the fork or this needs to be renamed to `nylas-mail-lives`

**Comment by danielbayley** [comment]
> We need upstream to approve the fork

They already link to it directly in their [official blog post](https://www.nylas.com/blog/sunsetting-nylas-mail-development), so I'm sure it will be fine…

**Comment by commitay** [comment]
> They already link to it directly in their official blog post, so I'm sure it will be fine…

Sorry, no. They link to it but they do not explicitly approve it.

> Over time, we expect the open source community will step up to offer alternatives to Nylas Mail.  In fact, we already know of two community-developed alternatives:  

> Nylas Mail Lives is a fork of Nylas Mail that fixes many longstanding issues, improves the client experience, and is committed to publish new releases.  This fork is free to use and has a large group of contributors that gather at https://nylasisalive.slack.com .

**Review by commitay — APPROVED** [review]

**Comment by commitay** [comment]
To follow the fork naming rules this should be called `nylas-mail-lives-nylas-mail` but that seems redundant in this case.

**Pull request merged**
