### PR TITLE
Add PanWriter.app

### PR DESCRIPTION
**Pull request by DrJume**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Review by SMillerDev — COMMENTED** [review]
Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

**Comment by DrJume** [comment]
Done

**Comment by neutric** [comment]
This would most likely also benefit from `depends_on formula: "pandoc"` as `homepage` says:

> You also have to install pandoc to export to most formats.

**Comment by DrJume** [comment]
Yes, you are right. Thanks for the tip!

**Comment by neutric** [comment]
Question for the maintainers:
```
livecheck do
  url :url
  strategy :github_latest
end
```
seems to be slightly less common than the above but with `url :url`, as it is the implicit default, omitted. Which version do you prefer?

**Comment by miccal** [comment]
@neutric if the `url` is a GitHub release we try first to omit it entirely and see if the `livecheck` is automatic (which it is in this case).

**Comment by miccal** [comment]
Thank you @DrJume.

**Pull request merged**
