### PR TITLE
Migrate shared audit exceptions

### PR DESCRIPTION
**Pull request by Rylan12**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

---

This PR migrates the shared audit exception lists from the brew repo to homebrew/cask. See https://github.com/Homebrew/brew/pull/10087 for more information. This PR will need to be merged before https://github.com/Homebrew/brew/pull/10087. Until https://github.com/Homebrew/brew/pull/10087 is merged, these changes should have no effect on `brew audit` or any other cask functionality.

### CODE REVIEW

**Comment by Rylan12** [comment]
Bumping this. It's not super critical but it's blocking https://github.com/Homebrew/brew/pull/10087. I wouldn't mind getting this merged soon so it's not hanging over my head.

**Review by reitermarkus — APPROVED** [review]

**Comment by SeekingMeaning** [comment]
I get this error when doing `brew audit --strict` for an unrelated formula:

```
homebrew/cask:
  * audit_exceptions/github_prerelease_allowlist.json references
    formulae that are not found in the homebrew/cask tap.
    Invalid formulae: extraterm, freetube, haptickey, home-assistant, lidarr, nuclear, pock, syntax-highlight, toggl-track, xit
```

**Comment by samford** [comment]
@Rylan12 The failure that @SeekingMeaning mentioned is appearing on Homebrew/brew CI as well (and causing PRs to fail as a result). It seems to stem from `TapAuditor#check_formula_list` treating the casks in this allowlist as formulae.

**Comment by Rylan12** [comment]
Oops, it turns out this needed to be merged at the same time as https://github.com/Homebrew/brew/pull/10087. My apologies, I didn't think it through all the way. https://github.com/Homebrew/brew/pull/10087 has been merged so this should be fixed now.

**Pull request merged**
