### PR TITLE
Add MongoDB.app v3.0.2-build-4

### PR DESCRIPTION
**Pull request by jpadilla**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You need to follow the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_token_reference.md) to name casks, to prevent duplicates. Further changes are needed, so I’ll merged this in another PR. Your contribution will still be included (and still credited to you), with the appropriate modifications.

Thank you for the contribution.

**Comment by jpadilla** [comment]
@gcollazo what would you like it to be? `gcollazo-mongodb`?

**Comment by gcollazo** [comment]
Yes that's cool

**Comment by vitorgalvao** [comment]
@jpadilla @gcollazo This isn’t a choice for the app’s developer. We need consistent naming in our apps, for predictability and to avoid duplicates, and that is way more important.

It’s already being decided in https://github.com/caskroom/homebrew-cask/pull/10695. @gcollazo’s version seems to be considerably more popular than the already present one, so it should be the main one.

**Pull request closed without merging**
