### PR TITLE
Fix Snow Leopard installation in Sierra Cache Cleaner.app Cask

### PR DESCRIPTION
**Pull request by Saklad5**
_If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so._

After making all changes to the cask:
- [x] `brew cask audit —download {{cask_file}}` is error-free.
- [x] `brew cask style —fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
  Version is unchanged.

### CODE REVIEW

**Comment by Saklad5** [comment]
This Cask downloads a disk image with both a legacy version and a main version of the application. Should the Cask delete the unused app from Caskroom, or just keep it there taking up 70MB?

**Comment by Saklad5** [comment]
Sierra Cache Cleaner has additional components (ClamAV module, Single User Mode script, etc.) that are only downloaded and installed once you open the program and tell it to do so. Should this be mentioned as a caveat?

**Comment by adidalal** [comment]
Caveats are not used for those kinds of messages. You could potentially add in the deletion in a postflight, but personally I don't think it's a huge deal.

**Review by adidalal — APPROVED** [review]

**Comment by reitermarkus** [comment]
If it's not installed during installation, but when using the program, it should be a `zap`.

**Pull request merged**
