### PR TITLE
Add Linn Konfig latest

### PR DESCRIPTION
**Pull request by jmcvaughn**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

I've not named the Cask by the token reference exactly (which would be `konfig`) as this is a little ambiguous.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This belongs in [homebrew/cask-drivers](https://github.com/Homebrew/homebrew-cask-drivers)

**Comment by v0rn** [comment]
Can you explain to me why this belongs in homebrew/cask-drivers? This is a GUI application to manage Linn's music streamers over a network, no drivers involved. Thanks!

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask (emphasis changed):

> Driver: Software to make a hardware peripheral recognisable and usable by the system. **If the software is useless without the peripheral, it’s considered a driver.**

**Comment by v0rn** [comment]
Thanks very much, I shall submit there.

**Pull request closed without merging**
