### PR TITLE
Update anaconda.rb

### PR DESCRIPTION
**Pull request by mathbunnyru**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

New 4.1.1 version

### CODE REVIEW

**Comment by adidalal** [comment]
Also, check out `cask-repair`, it makes Cask updates like this quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

**Comment by mathbunnyru** [comment]
@adidalal thanks.

**Comment by mathbunnyru** [comment]
@adidalal there are errors. Can you help me with that?

```
Is everything correct? You can also make further manual edits (y/n/e) y
Submitting…
Permission denied (publicly).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: the requested upstream branch 'mathbunnyru' does not exist
hint:
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint:
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"

There was an error submitting the pull request. Have you forked the repo and made sure the pull and push remotes exist?
```

**Comment by vitorgalvao** [comment]
@mathbunnyru See https://github.com/vitorgalvao/tiny-scripts/issues/20 and https://github.com/vitorgalvao/tiny-scripts/issues/26.

**Pull request merged**
