### PR TITLE
Fix symbol arrays.

### PR DESCRIPTION
**Pull request by reitermarkus**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Just noticed that `git-annex` is also available as a Formula. The only difference is that the GUI version offers a GUI launcher for the web app, which can also be launched via `git annex webapp`. Is this enough of a difference to keep it as a Cask?

**Comment by vitorgalvao** [comment]
> Is this enough of a difference to keep it as a Cask?

I’m fine with removing it.

**Comment by adidalal** [comment]
+1 for removal. They're functionally identical

**Comment by reitermarkus** [comment]
Created a seperate PR for the removal.

**Pull request merged**
