### PR TITLE
Added vendor download comment to 197 casks

### PR DESCRIPTION
**Pull request by vitorgalvao**
@caskroom/maintainers These should be the last of them, which means that not counting some pending PRs, after this is merged we should not have any more casks in the main repo whose `url` and `homepage` hosts differ.

Exceptions include `github.io` homepages with `github.com` urls and `code.google.com` homepages with `googlecode.com` urls, since those really are the same host, in practice. Things like a `github.com` homepage with a `googlecode.com` url were checked, since those are different.

Pinging you all in case some are unaware of the policy<sup>1</sup> to add this comment in these cases. These are somewhat hard to detect automatically due to the weird format urls can take and the amount of TLDs there are with different parts, which means we should take extra care with new submissions (as opposed to updates). If someone can manage a script for this (I may try to eventually work on one, but definitely not now), that’d be a huge step.

---

<sup>1</sup> Introduced when we already had a bunch of them that did not comply, which is what these last PRs are meant to address.

### CODE REVIEW

**Comment by radeksimko** [comment]
I completely understand the problem and agree with moving away casks (to `unofficial`), that do not have an official download URL. :+1: 

Nonetheless, I don't quite like the idea of having comments as a part of a policy. I know this is DSL, but I think [Uncle Bob's thoughts](http://apdevblog.com/comments-in-code/) about comments kinda apply to this as well. TL;DR You should not be commenting the obvious and try to express your thoughts through the code instead of adding a comment.

I'd expect that having the cask in the main repo `homebrew-cask` automatically means, that the `url` stanza points to an **official** download URL, if not, it should be simply moved to `unofficial`, or am I missing something?

**Comment by ndr-qef** [comment]
> I'd expect that having the cask in the main repo `homebrew-cask` automatically means, that the `url` stanza points to an **official** download URL, if not, it should be simply moved to `unofficial`, or am I missing something?

It is a modicum of reassurance that a third-party `url` is known to be the vendor's. In its absence, processing patches to affected Casks is more time-consuming: we must trace our steps in GH issues and PRs to verify that the `url` has been previously validated, as opposed to e.g. being erroneously merged.

**Comment by vitorgalvao** [comment]
Precisely.

I’ve read the linked article, and although I had some fun with the [linked stackoverflow thread](http://stackoverflow.com/questions/184618/what-is-the-best-comment-in-source-code-you-have-ever-encountered/389723), I didn’t really buy the article<sup>1</sup>. Let’s ignore the fact the writer *admittedly* has no idea of what a good comment is or when one should be used, and is clinging to an abstract notion that they somehow take a huge amount of time, completely ignoring [they save time for other people](http://apdevblog.com/comments-in-code/#comment-1158653465)<sup>2</sup>.

Comments don’t just explain what a piece of code does, but *why it is needed*. [We do them with `:no_ckeck` in versioned casks](https://github.com/caskroom/homebrew-cask/blob/b192929052a897cf338fb5442f782a7e338777a0/Casks/adobe-air.rb#L3) because they provide context and tell a user that is learning by example “you should only use this in select cases, and this is why”.

To be fair, your concern was regarding using comments as part of policy, but what’s the alternative? Adding working code to represent the same thing is nonsensical when we have this simple, easy, and clear solution that doesn’t break anything.

The cases expressed by @ndr-qef are the main concern. [Users notice these mistakes](https://github.com/caskroom/homebrew-cask/issues/6747) (invariably a good thing), and sometimes we do too. Confirming if it was intentional or not is time consuming, without this guide.

---

<sup>1</sup> The whole thing read as “I hate comments and found this well-known book that agrees with me. A-ha! See? See? I was right; see these absolutely fabricated and exaggeratedly dumb examples that would never happen in real-world usage as proof”.

<sup>2</sup> And many times, “other people” are ourselves in the future. Sometimes we can’t even recall intent in our own code no one else will use a few months down the line, let alone do it in a project with over a thousand contributors, close to a dozen maintainers, and who know how many daily contributions.

**Comment by radeksimko** [comment]
@vitorgalvao 
The comment in case of `adobe-air` cask is a bit different story and actually "complies" with the Uncle Bob's idea - it's something, that one may not expect (replacing `dmg` under the same URL).
Whereas the proposed change/policy suggests **adding comment to each and every cask** in this repository, which in all cases **will be the same** which makes it something that can be basically automated.

I agree with the part that it may force newcomers to actually confirm, that the URL comes from an official homepage, so it helps the process of adding new casks (pushes down the number of PR turnarounds), but I'm not sure it's the best way of solving the problem.

It reminds me how Homebrew deals with licensing policies (similar problem). They force you to at least look at the licensing section in docs by requiring `Signed-Off-By` line inside each of your commit (otherwise Jenkins build goes red and points you to that URL).

If there would be any better way of noticing users about these things instead of adding the same comment to each cask, then I would definitely prefer it.

> I hate comments and found this well-known book that agrees with me.

The linked article is only describing a very small part of http://www.amazon.co.uk/Clean-Code-Handbook-Software-Craftsmanship-ebook/dp/B001GSTOAM/ , I simply found it easier to link that instead of linking the whole book and/or its chapter about comments, where you would find many more reasons, e.g. comments often get old, because people tend to update code, but forget about updating comments or just make sure that comments are still true.

----------

I'm aware that I'm probably not offering a solution, just thinking loudly what impact it may have for the whole codebase. Sorry for not being more helpful.

**Comment by ndr-qef** [comment]
> […] I'm not sure it's the best way of solving the problem.

It is not, but…

> […] just thinking loudly what impact it may have for the whole codebase

… it is also one “search and replace” away from being undone.

Commenting will likely be a provisional measure, until we feel confident that both users and maintainers can be trusted to exercise due care with regard to third-party URLs.

**Comment by vitorgalvao** [comment]
> Whereas the proposed change/policy

To be clear, this isn’t a proposal; it has been in place for quite a while. This is just making casks added before the rule was introduced (or slipped through) comply with it.

> adding comment to each and every cask in this repository

Not each and every cask. Only the ones whose download host differ from the homepage, which are the minority (though a significant number).

> which makes it something that can be basically automated.

No, it can’t, because they have to be verified by a maintainer (which is the whole point), which makes it **mandatorily a manual process**.

> I agree with the part that it may force newcomers to actually confirm

No no, it forces **us** to do it. And grabbing @ndr-qef’s comment:

> until we feel confident that both users and maintainers can be trusted to exercise due care with regard to third-party URLs.

We will never be able to do that, for the simple fact mistakes happen. We never saw a decidedly malicious contribution attempt, but that does not mean they can’t happen, and it also doesn’t mean we can’t slip up and not notice the download url is from a different host (it does happen). We have the responsibility to check these links and not just include a random dropbox download url if it isn’t given by the developer. At the same time, users should never be forced to trust us blindly, and should be able to verify these. Having the comment does mean that if they trust us they will probably be safe with that cask, because we’re asserting we checked.

> If there would be any better way of noticing users about these things instead of adding the same comment to each cask

You’ll always have to add *something* to the cask, whether a comment or code, to make this clear when, for example, you’re `brew cask cat`ing it.

> The linked article is only describing a very small part of (…)

Yes, my comment was merely directed at the post itself, not the book.

> comments often get old, because people tend to update code, but forget about updating comments or just make sure that comments are still true which then turns reading of the comment into not only unhelpful, but also time wasting process.

That doesn’t really apply to these specific comments, though. Most urls don’t change after being introduced (thanks to interpolation of the version), so the comments will keep being true. If the url ever changes it will need to be checked again, anyway. In addition, every comment specifies the host at the time it was added, so if the host changes and the comment doesn’t, it can be detected (and that one would be easily done with a script, if needed).

Either way, the policy is in place and currently works, so I’ll merge this to get these last ones out of the way. That doesn’t mean we shouldn’t continue the discussion, naturally.

**Comment by rolandwalker** [comment]
Fun discussion; sorry I missed it.  This is still undocumented, right?  That works out nicely in that the comment indicates that a maintainer checked it.

And that is what connects all sides in this debate: good comments flag edge cases or store out-of-band information. The unusual case is the divergent domain on the `url` stanza. The out-of-band information is that the URL was checked by a maintainer, personally. (Or in Vitor's case, heroically.)

**Pull request merged**
