### PR TITLE
Add setapp

### PR DESCRIPTION
**Pull request by ghost**
Added setapp version latest to Casks. Confirmed download url and install + uninstall processes.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

### CODE REVIEW

**Comment by commitay** [comment]
This has been refused previously for being a walled build. https://github.com/caskroom/homebrew-cask/pull/31121 https://github.com/caskroom/homebrew-cask/pull/31123
> https://github.com/caskroom/homebrew-cask/pull/31121#issuecomment-287660059
> However, I still cannot see any way to get to the URL without going through a login/registration (I checked before closing, and rechecked now before replying).
> 
> If you can point me to the page where you can get at the URL without going through the login/registration wall, we can merge this.

Can you get the `url` without login/registration?

**Comment by mightyfree** [comment]
Hi @commitay. Thanks for assisting. A non-walled download link is located on the footer of the setapp.com homepage: https://setapp.com/download

Once downloaded, unzip to see 'Install Setapp.app'. This app downloads SetApp.dmg at the `url` in the commit. The `url` for SetApp.dmg can be determined via network inspection, or via text inspection of the unix executable inside 'Install Setapp.app' here: /Contents/MacOS/Install Setapp

**Comment by mightyfree** [comment]
I greatly appreciate your help if you see any improvements.

**Comment by commitay** [comment]
> url for SetApp.dmg can be determined via network inspection, or via text inspection of the unix executable

This isn't really a public download. I've updated the `uninstall` but I'll let @vitorgalvao decide if this should be merged.

**Comment by mightyfree** [comment]
Thanks @commitay! This is similar to Spotify - when downloading from the Spotify website, the app then downloads a dmg. Given the popularity of Setapp, I hope this can be merged.

**Comment by mightyfree** [comment]
Additionally, MacPaw is the developer of Setapp & Devmate (also CleanMyMac). This can be confirmed from their homepage - under products tab - at https://macpaw.com

**Comment by vitorgalvao** [comment]
> Additionally, MacPaw is the developer of Setapp & Devmate (also CleanMyMac). This can be confirmed from their homepage - under products tab

That does nothing to prove the URL in this cask is legitimate. As it is, this cask cannot be accepted, because it’s a security risk (and that is a well-documented decision).

**Comment by commitay** [comment]
Closing, thank you for you PR @mightyfree

**Pull request closed without merging**
