### PR TITLE
gobdokumente: convert to `on_system` blocks

### PR DESCRIPTION
**Pull request by Rylan12**
Convert to `on_system` blocks

See #137512

### CODE REVIEW

**Comment by Rylan12** [comment]
Remind me what we decided to do about `Error: Upstream defined 10.16 as minimal OS version and the cask defined 10.11`?

**Comment by p-linnane** [comment]
For the 10.16 thing specifically we are setting it to 11 on the cask and sending a message to upstream asking them to change to 11. The audit fails, but we merge anyway.

**Comment by Rylan12** [comment]
Okay, thanks!

Think we should just add a case to the audit to treat 10.16 as the same as 11?

Also, because of this, it's safe to remove the legacy version info, right? Since no one on those OS versions could install anyway because of the `depends_on`

**Comment by p-linnane** [comment]
There is currently no logic in the audit for 10.16. I would implement it, but I'm not sure how 😄

**Comment by Rylan12** [comment]
> There is currently no logic in the audit for 10.16. I would implement it, but I'm not sure how 😄

https://github.com/Homebrew/brew/pull/14297

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
