### PR TITLE
Updated scribus to v1.4.5-r2

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by alebcay** [comment]
Looks good, thanks! :+1:

**Comment by jwthomp** [comment]
Unfortunately, this changelist breaks scribus installs as it is unable to find the dmg to download.

From the definition file: 
> version '1.4.5-r2'url 
> ....
> "http://downloads.sourceforge.net/project/scribus/scribus/#{version}/scribus-#{version}.dmg"

This results in a url with 1.4.5-r2/scribus-1.4.5-r2.dmg but the working download path should be 1.4.5/scribus-1.4.5-r2.dmg

**Comment by radeksimko** [comment]
@jwthomp Agreed, confirmed, thanks for reporting it. Patch coming soon.

**Comment by jwthomp** [comment]
I've just put up a merge request that takes the version up to the new stable 1.4.5 version of Scribus.app if you would like to use that.

**Pull request merged**
