### PR TITLE
Update iridium to 2018.11-1

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
can we keep the real version number in the cask version please? else its impossible to support the app via our cask-repair system...

**Comment by ran-dall** [comment]
@core-code Noted. I'll tweak my setup. 🔧 

In situations like these, would you prefer the real version before the comma or does it not matter for your side of the system? 

So for example `4.2.1,2018.11-1`

**Comment by ran-dall** [comment]
@core-code **Let's do it the way you suggested.**👌 Pretty much my thoughts exactly. 👍

**Comment by ran-dall** [comment]
@core-code You wanna submit a new PR for this?

**Comment by core-code** [comment]
i think @suschizu  has already done this a few days ago ;)

**Pull request merged**
