### PR TITLE
Add Lens.app v3.0.1

### PR DESCRIPTION
**Pull request by Addono**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by Addono** [comment]
So there's this other repo which is made by the authors of Lens from before the source was moved into it's own organisation:
https://github.com/kontena/homebrew-lens/blob/master/Casks/lens.rb

It's a bit outdated and advocates for using their own S3 bucket rather than the releases in Github, however now the download links on their site refer to Github, so it seems more likely to me that that is the preferred way nowadays.

**Comment by DocLM** [comment]
@Addono I was working on the same cask when i noticed your pull request. I suggest to add these lines to zap section
 
```
zap trash: [
    '~/Library/Application Support/Lens',
    '~/Library/Preferences/com.electron.kontena-lens.plist',
    '~/Library/Saved Application State/com.electron.kontena-lens.savedState',
]
```

**Comment by Addono** [comment]
@DocLM What do you think of deleting the cache folder? I haven't used the application much, but for me it hasn't created it.

Posed the question at lensapp/lens/issues/72 as well, but that was 2 hours ago so not surprised that there hasn't been an answer yet.

**Comment by DocLM** [comment]
@Addono I don't know it's an Electron app and I'm not an Electron expert but I see a common pattern in paths used by these type of applications.
See [Kitematic](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/kitematic.rb) and [Visual Studio Code](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/visual-studio-code.rb) casks for example.

**Review by vitorgalvao — APPROVED** [review]

**Comment by Addono** [comment]
@vitorgalvao The CI caught that effc94a missed a comma at the end of the line. Do you want me to squash the commits for a cleaner history?

**Comment by vitorgalvao** [comment]
> The CI caught that [effc94a](https://github.com/Homebrew/homebrew-cask/commit/effc94afe4d44f8fc1beb36f580ebda3863ffff8) missed a comma at the end of the line.

Thank you for correcting it.

> Do you want me to squash the commits for a cleaner history?

No need, thank you. I can do that at merge time.

**Comment by sshishov** [comment]
Will we support new version `3.1.0` for example?

**Comment by thamaraiselvam** [comment]
What's status on this PR? I cannot find lensapp on brew.

```
💀88% at [ 10:59:00.412 AM] ➜ brew search lensapp
No formula or cask found for "lensapp".
Closed pull requests:
Add Lens.app v3.0.1 (https://github.com/Homebrew/homebrew-cask/pull/79339)
```

**Comment by Addono** [comment]
It's called `lens` instead of `lensapp`.

**Pull request merged**
