### PR TITLE
updated slack (2.0.0)

### PR DESCRIPTION
**Pull request by debo**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as e8fc3bc96196b2e660c865c195e6489688071f92 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by debo** [comment]
@vitorgalvao not a problem, I just followed the [How To Contribute](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md) guide. Happy to help.

**Comment by vitorgalvao** [comment]
@debo Your contribution was flawless. To clarify, this is just something we usually do so history isn’t full of merge commits (happens if we just press github’s merge button).

**Comment by debo** [comment]
@vitorgalvao I know, I do use the same approach myself.

**Pull request closed without merging**
