### PR TITLE
Update macupdater from 1.4.18 to 1.4.18,6420

### PR DESCRIPTION
**Pull request by singularitti**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by singularitti** [comment]
`macupdater` actually has build versions other than `major.minor.fix` scheme. It will ask me to update if it has a newer build:
macupdater

**Comment by core-code** [comment]
there shouldn't be any further build-only updates in the future.

**Comment by singularitti** [comment]
What does it mean? Should I close this PR?

**Comment by core-code** [comment]
i think this change isn't necessary, yes. thanks anyway.

**Comment by singularitti** [comment]
Sure.

**Pull request closed without merging**
