### PR TITLE
Add ARM version of Chromium

### PR DESCRIPTION
**Pull request by yooouuri**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by yooouuri** [comment]
When I install chromium with this addition, the following error popups:

image

I have to run `xattr -cr Chromium.app`. How can I include this in the cask?

**Comment by miccal** [comment]
> I have to run `xattr -cr Chromium.app`. How can I include this in the cask?

You can't -- this needs to be installed with the `--no-quarantine` flag.

**Comment by miccal** [comment]
I am going to merge this, then submit a PR to update the `version`.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/109061#issuecomment-885698782

**Pull request merged**
