### PR TITLE
Rename cask to singularityviewer

### PR DESCRIPTION
**Pull request by alansill**
Rename to singularityviewer to avoid confusion with the Singularity app from sylabs.io (to be packaged as singularity or singularityapp in the near future).

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Welcome.

You can’t just change the app name in the cask and expect it to work. We also won’t rename it ourselves, if that’s the name the developers chose. [We have rules for casks with similar names](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md#token-overlap). Are you one of the developers of either app?

**Comment by alansill** [comment]
Thanks. I have communicated with the maintainers of the Singularity Viewer and they confirm that they were unaware of the existence of this cask, which was apparently created by someone else, and that they would prefer that if a cask exists, they would like it to have the name “singularityviewer” or “singularityvwr” (first choice probably preferred). I would be happy to forward the correspondence to confirm this.

Thanks,
Alan

On Mar 12, 2019, at 7:06 PM, Vítor Galvão <notifications@github.com<mailto:notifications@github.com>> wrote:


Welcome.

You can’t just change the app name in the cask and expect it to work. We also won’t rename it ourselves, if that’s the name the developers chose. We have rules for casks with similar names<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHomebrew%2Fhomebrew-cask%2Fblob%2Fmaster%2Fdoc%2Fcask_language_reference%2Ftoken_reference.md%23token-overlap&data=02%7C01%7Calan.sill%40ttu.edu%7C72a942a3be654ba1f10c08d6a747c134%7C178a51bf8b2049ffb65556245d5c173c%7C0%7C0%7C636880323960702932&sdata=gi2Spbe6belB2XMmb5Hti5fUdbMM58YXPsI3lK4TNnM%3D&reserved=0>. Are you one of the developers of either app?

**Comment by vitorgalvao** [comment]
@alansill Thank you for having contacted them. Unfortunately, the name of the cask has to follow a strict [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) to avoid duplicates.

That is to say, the name of the cask follows the name of the app bundle. If the developers want the cask to be named `singularityviewer`, then they must rename their app as `SingularityViewer.app` (capitalisation is irrelevant). Otherwise, the cask renames with the current name.

**Comment by alansill** [comment]
o can I contact the maintainers of the cask without putting in a pull request, then? As nearly as I can tell, this is an unauthorized cask not associated with the application developer?

I'd prefer that you reopen the pull request and that we get the cask creators to respond. If not, please suggest a way forward.

**Comment by alansill** [comment]
Here is the response of the actual SingularityViewer application maintainers. The application comes from http://www.singularityviewer.org and neither the folks at that web site nor I know where the cask currently called "singularity" comes from.

"For one we're not called 'Singularity' but 'Singularity Viewer', both the project and the software. We strive to make our executable naming unambiguous, for example singularityviewer and singularityalpha. In case naming conflicts exist in a given namespace, this is probably down to a packaging mistake and can be discussed further. Up until this moment I was not aware that we're an OS X homebrew package, it's not maintained by our team, and I don't know the person responsible for it - we ship an App package on OS X ourselves that adheres to our naming conventions to avoid conflicts. It is my opinion that the brew packaging our software should be named 'singularityviewer' or 'singularityvwr' but it's apparently not up to us.
...
It is my opinion that no brew package named 'singularity' should exist, because it's fundamentally bound to be ambiguous, as the next singularity is coming for sure, that we should be 'singularityvwr' and your project should be singularitysomethingelse. But as I said, I wouldn't know what to do about it."

**Comment by siana** [comment]
Singularity Viewer maintainer here. Singularity.app can be considered a packaging mistake from many years ago - and yeah we haven't had a fresh OS X release in years; however a new one is anticipated in several weeks, we can make sure to observe the naming then.

Yeah i was looking at the changeset and thinking "won't it break things?"

And yet i wonder, how can two differently named casks for the same app name not exist? Naming collisions in software can not always be avoided.

**Comment by alansill** [comment]
Thanks Siana for the response! I'm sure the SyLabs folks (note: I am just a user and not from SyLabs) wil be happy to come up with a name other than just "singularity" for their HomeBrew package if it comes to that; meanwhile a more accurate name along the lines of your actual project name for the Singularity Viewer would help the HomeBrew community overall. Renaming this cask to "singularityviewer" after following all of the token rules would therefore surely be a good idea when your new version is ready.

**Comment by vitorgalvao** [comment]
> How can I contact the maintainers of the cask without putting in a pull request, then?

There is no “maintainer of the cask”. No cask is associated with a specific person.

> I'd prefer that you reopen the pull request and that we get the cask creators to respond.

Closing issues does not impeded the conversation from continuing, as you noticed by replying. There are no “cask creators” to respond. Casks are maintained by a small core team and several outside contributors.

> Here is the response of the actual SingularityViewer application maintainers.

Again, not relevant. We need to follow our token reference *because it was created to serve a real need to avoid duplicates*.

> And yet i wonder, how can two differently named casks for the same app name not exist?

[We got that covered](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md#token-overlap). It two casks would have the same name, the last one to be added (or the least popular) gets the vendor name prefixed. A possibility here would be to rename this one `siana-singularity`, since it’s likely to be the least popular of the two. Analytics (number of unique downloads):

```
singularity (added 832 days ago)
30 days: 9 (#2293)
90 days: 21 (#2492)
365 days: 50 (#2373)
```

But as I said, if you rename the app bundle itself, it will be easier to rename the cask and keep the rule consistent.

> I'm sure the SyLabs folks (…) wil be happy to come up with a name other than just "singularity" for their HomeBrew package

Again, not up to them. There’s no name to “pick”. We *use* the name from what we need in accordance to our rules. Any project is free to say “I don’t want you to distribute this”, but they can’t dictate a change to our rules.

**Comment by alansill** [comment]
I appreciate all the explanation. Is it the case that if the MacOS application bundle is named "SingularityViewer.app" upon completion of its build process, that the HomeBrew formula will be named "singularityviewer" assuming that produces no collisions with your tokenization process?

Also, I see brew formulae appear with the "renamed" notation very often whenever I run a "brew update". How is it that those packages get renamed routinely without triggering these problems?

Example:

==> Renamed Formulae
gloo-ctl -> glooctl

**Comment by vitorgalvao** [comment]
> Is it the case that if the MacOS application bundle is named "SingularityViewer.app" upon completion of its build process, that the HomeBrew formula will be named "singularityviewer" assuming that produces no collisions with your tokenization process?

It’s not automatic, but yes. It’s worth nothing we’re talking about casks, here, not formulae. They are built differently.

> Also, I see brew formulae appear with the "renamed" notation very often whenever I run a "brew update". How is it that those packages get renamed routinely without triggering these problems?

Because you get that warning, this is not a problem. That warning is part of a system that keeps track os renames and transfers your installations from one name to the next. This works in formulae but not in casks (yet).

**Pull request closed without merging**
