### PR TITLE
Update streamlabs-obs from 1.6.0 to 1.7.0

### PR DESCRIPTION
**Pull request by eloyaldea**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by eloyaldea** [comment]
Hi, I wanted to update for the new naming but I don't know how to update the `livecheck` to recognize new versions. Also I don't know if it would be appropriate to change the cask name from `streamlabs-obs.rb` to `streamlabs-desktop.rb`.

**Comment by MTCoster** [comment]
Hmm, it looks like the appcast hasn't been updated for some reason. The URL was added in 861c237 (#90525) although it was never explained where it came from. Interestingly, the MacUpdater URL that it replaced does work:

> https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://streamlabs.com/slobs/download&user_agent=Mac%20OS%20X

**Comment by neutric** [comment]
> The URL was added in [861c237](https://github.com/Homebrew/homebrew-cask/commit/861c237274c24984b55ea9131e7d1f4daed9b9af) (#90525) although it was never explained where it came from

It was found inside the app bundle with the [`find-appcast`](https://github.com/Homebrew/homebrew-cask/blob/HEAD/developer/bin/find-appcast) script as explained in the [Cask Cookbook](https://docs.brew.sh/Cask-Cookbook#stanza-appcast).

**Comment by MTCoster** [comment]
> It was found inside the app bundle with the [`find-appcast`](https://github.com/Homebrew/homebrew-cask/blob/HEAD/developer/bin/find-appcast?rgh-link-date=2022-02-01T16%3A13%3A10Z) script as explained in the [Cask Cookbook](https://docs.brew.sh/Cask-Cookbook#stanza-appcast).

Thanks for pointing that out, I never knew that tool existed! The cookbook has grown so long now it could really use a table of contents

**Comment by miccal** [comment]
Thank you @eloyaldea.

This is too popular for a rename at this stage, so let's just keep it as `streamlabs-obs`:
```
==> Analytics
install: 71 (30 days), 200 (90 days), 1,071 (365 days)
```

**Comment by eloyaldea** [comment]
No problem! I saw that MacUpdater reported a new version but `livecheck` didn't, so I tried to make this PR the best I could but didn't know all the details necessary to make it work 🤓

**Comment by eloyaldea** [comment]
Hi, I have been noticing that the new method for `livecheck` is giving false new versions randomly every now and then. I don't know how could it be fixed but I wanted to let you know this.
For example, running `brew livecheck streamlabs-obs` several times shows this different results:

> streamlabs-obs : 1.7.0 ==> 8
> streamlabs-obs : 1.7.0 ==> 1.7.0
> streamlabs-obs : 1.7.0 ==> 5hVdsAYQaiNxDWG

**Pull request merged**
