### PR TITLE
Update hookmark from 5.0 to 5.0.2

### PR DESCRIPTION
**Pull request by razvanazamfirei**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Review by samford — COMMENTED** [review]
I see that this `version` idiom is used in other some casks but, as someone who only occasionally dabbles with casks, the use of the `#major`/`#minor`/`#patch` methods feels unusual here since they're altogether semantically inaccurate. Just from my own perspective, I would think that it would make some kind of sense to use commas to delimit all the version parts (e.g., `5.0.2,2023,03,b5331`) instead of cobbling together three parts into `version.csv.second` using a `.` delimiter. This would result in consistent use of `version#csv` throughout the `url` without any semantic oddness.

I would be interested to hear what the @Homebrew/cask maintainers think of this. [Please don't bother with changing the version until we come to a conclusion.]

-----

In terms of the `livecheck` block, I think there's something to be said for making the `b5331` part optional considering past versions have omitted it. I'll add some suggested changes once the question around `version` formatting is settled.

**Comment by carlocab** [comment]
I think commas are meant to delimit "split" versions. They jointly identify the artefact we're downloading, but they appear separately in the cask `url`. I'd rather not muddle that up by delimiting everything with commas (especially for casks which don't need the commas to have a sensible version).

**Comment by reitermarkus** [comment]
I think the ideal version here would look like `5.0.2,5331,2023-03`, but we don't have a good way to deal with the date dash, so using `2023.03` makes more sense for now.

**Comment by reitermarkus** [comment]
Maybe we could add `#year`, `#month` and `#day` methods for strings that look like `YYYY-MM-DD`, `YYYY-MM` and `YYYY`.

**Comment by samford** [comment]
> I think the ideal version here would look like `5.0.2,5331,2023-03`, but we don't have a good way to deal with the date dash, so using `2023.03` makes more sense for now.

I was in the process of suggesting exactly that (`5.0.2,5331,2023.03`), so I agree. After thinking about it, my issue was mainly around the idea of appending the new text to the date like `2023.03.b5331` instead of separating it with a comma like `5331,2023.03` 👍

I think we should still make the trailing `b1234` text optional in the `livecheck` block until/unless it clearly becomes a reliable part of the filename (i.e., this is the first instance of this format and sometimes upstream sources are unreliable with naming conventions, so the check may benefit from the added flexibility). I'll add a suggestion for this in a moment.

> Maybe we could add `#year`, `#month` and `#day` methods for strings that look like `YYYY-MM-DD`, `YYYY-MM` and `YYYY`.

At the very least, something like that would make more sense when reading the code compared to `#major`/`#minor`/`#patch` in this particular context. Just from a quick glance, this isn't the only cask doing this with dates (e.g., `mints`).

**Review by miccal — APPROVED** [review]

**Pull request merged**
