### PR TITLE
Update rubitrack-pro from 5.2.3 to 5.2.4

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
` - appcast at URL 'https://www.rubitrack.com/autoupdate/sparkle5.xml' does not contain the version number: '5.2.4'`
true - but the feed seems ok …

**Comment by mightyfree** [comment]
Contact rubiTrack support to have the autoupdate XML file updated for v5.2.4. https://www.rubitrack.com/support.html

**Comment by core-code** [comment]
many vendors wait a few days before enabling auto-updates to contain damage in case a new release has bugs, so they might not be interested in 'fixing' anything here...

**Comment by suschizu** [comment]
@mightyfree - I thought about this too but its quite hard to reach the developers - there is no contact-form or email on the website, just the forum 
Release date was the 1st of june - so let's wait until the end of the month

**Pull request merged**
