### PR TITLE
Updated ssh-tunnel-manager (2.2.1)

### PR DESCRIPTION
**Pull request by RJHsiao**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by RJHsiao** [comment]
Hi all,

Sorry for that I can't get the url rule about the new version release, so I just put the static url.

**Comment by adidalal** [comment]
Use format like https://github.com/caskroom/homebrew-cask/blob/master/Casks/vox-preferences-pane.rb and needs URL comment also.

**Comment by RJHsiao** [comment]
Hi @adidalal 
You'll right if there are only two integer inside the url,
but there are three integer inside the url: 
https://dl.devmate.com/org.tynsoe.sshtunnelmanager/221.003/1455813213/SSHTunnelManager-221.003.zip
"221" means the version number "2.2.1", "003" may means "build no.3", 
but how about "1455813213"? I can't sure it's a static number or variable number.

**Comment by RJHsiao** [comment]
@vitorgalvao 
OK, please check it out.

**Pull request merged**
