### PR TITLE
Submit logi-options-plus-minimal

### PR DESCRIPTION
**Pull request by ezrayellin**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [X] `brew audit --cask --new <cask>` worked successfully.
- [X] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

---

[Background](https://512pixels.net/2024/04/ai-overlay-tmp-home-folder-mac-os/)

I used the name `minimal` instead of `offline` since there are still some networking features enabled in the "offline" version.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Regarding the `token`, I think going with `logi-options-plus-offline` makes more sense, as that it what it is called by the vendor.
Whether or not this is suitable to be included in `homebrew-cask`, I'm not sure, it may be better suited to a [personal tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap), as it is maybe a bit too niche.

Strangely, the FAQ for this version provides conflicting information about the feature set. So I do wonder if it will remain this way long-term.

Screenshot 2024-05-01 at 11 15 36 am
 
Screenshot 2024-05-01 at 11 15 41 am

**Comment by ezrayellin** [comment]
> Regarding the `token`, I think going with `logi-options-plus-offline` makes more sense, as that it what it is called by the vendor. 

Updated.

**Comment by ezrayellin** [comment]
> Strangely, the FAQ for this version provides conflicting information about the feature set. So I do wonder if it will remain this way long-term.

Some of those features can be disabled with arguments to the installer, so behavior could be maintained in the future.

**Comment by ezrayellin** [comment]
> I'm not sure, it may be better suited to a [personal tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap), as it is maybe a bit too niche.

I have created a personal tap with my preferred settings for [the cask](https://github.com/ezrayellin/homebrew-personal/blob/main/Casks/logi-options-plus-minimal.rb). I'll close the pull request, it can be re-opened if desired.

**Pull request closed without merging**
