### PR TITLE
Update simple-comic.rb

### PR DESCRIPTION
**Pull request by eekleefeld**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by eekleefeld** [comment]
The version of Simple Comic currently in the Homebrew Cask repository is years old and abandoned. Submitting the location and updated version where it’s maintained now. Thank you.

**Review by miccal — APPROVED** [review]

**Comment by SMillerDev** [comment]
Since it's not an official successor but a community fork I'd say this should be it's own formula. But I'm fine if other maintainers disagree

**Comment by bevanjkay** [comment]
@SMillerDev This one is definitely odd. The original cask was also a fork of an unmaintained project.

**Comment by eekleefeld** [comment]
The current maintainer has also got the app listed on the Mac App Store. So yes, it is a community fork of a community fork, but it’s also as close to official as you can get with this sort of thing.

**Pull request merged**
