### PR TITLE
eudic: set auto_updates to true

### PR DESCRIPTION
**Pull request by hezhizhen**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by bevanjkay** [comment]
Can you confirm that the app has an in-app update mechanism that both downloads and install the update automatically?

**Comment by hezhizhen** [comment]
> Can you confirm that the app has an in-app update mechanism that both downloads and install the update automatically?

Screenshot 2024-03-09 at 20 01 27

In its settings, it allows users to enable/disable update check and tweak the frequency.

**Comment by razvanazamfirei** [comment]
Just to clarify, auto_updates applies to software that:
> both **downloads** and **installs** the update automatically

Can you confirm this is the case, not just that the software automatically checks for an update?

Thank you!

**Comment by hezhizhen** [comment]
> Just to clarify, auto_updates applies to software that:
> 
> > both **downloads** and **installs** the update automatically
> 
> Can you confirm this is the case, not just that the software automatically checks for an update?
> 
> Thank you!

Yes, it both downloads and installs the update automatically.

I've been using it for years and it's annoying to re-update it through Homebrew after it's been updated itself.

**Comment by bevanjkay** [comment]
@hezhizhen thank you for confirming. Can you address the style check failure by running `brew style --fix eudic`?

**Review by razvanazamfirei — APPROVED** [review]

**Review by bevanjkay — APPROVED** [review]

**Comment by hezhizhen** [comment]
thanks to all

**Pull request merged**
