### PR TITLE
multipass: fixes

### LINKED ISSUE #153333: multipass cask not installing bash autocompletion
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

multipass cask is not installing bash autocompletion.

bash autocaompletion is available in `/Library/Application Support/com.canonical.multipass/Resources/completions/bash/multipass` however it's not installed in `$(brew --prefix)/etc/bash_completion.d`

please note that bash completion is uninstalled

```
$ brew reinstall multipass
==> Downloading https://github.com/canonical/multipass/releases/download/v1.12.2/multipass-1.12.2+mac-Darwin.pkg
Already downloaded: /Users/gonzo/Library/Caches/Homebrew/downloads/170dcf5b513c1c99620f25102766f6eb852252e7a39b64781122fd2391bbd7c1--multipass-1.12.2+mac-Darwin.pkg
==> Uninstalling Cask multipass
==> Removing launchctl service com.canonical.multipassd
Password:
==> Uninstalling packages; your password may be necessary:
com.canonical.multipass.multipassd
com.canonical.multipass.multipass
com.canonical.multipass.multipass_gui
==> Removing files:
/Applications/Multipass.app
/Library/Application Support/com.canonical.multipass
/Library/Logs/Multipass
/usr/local/bin/multipass
/usr/local/etc/bash_completion.d/multipass
==> Purging files for version 1.12.2 of Cask multipass
==> Installing Cask multipass
==> Running installer for multipass; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is multipass
installer: Installing at base path /
installer: The install was successful.
🍺  multipass was successfully installed!
```

### Command that failed

multipass

### Output of command with `--verbose --debug`

```shell
does not apply

the issue is multipass autocompletion

$multipass <tab> (nothing happens)
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

####################################################################################
$ brew config
HOMEBREW_VERSION: 4.1.5-55-g3cd7290
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3cd72905ce3d36a84994cc6c6b9ebbdafff4e922
Last commit: 31 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ab200061798482dfc87a6c477f29dd76dd86c582
Core tap last commit: 13 hours ago
Core tap branch: master
Core tap JSON: 19 Aug 18:40 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/code -w
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
$ brew tap
homebrew/cask
homebrew/core
```

### PR DESCRIPTION
**Pull request by krehel**
* Add `bash` completion for ARM

* Update uninstall to remove `bash` completion

@Homebrew/cask - please see issue #153333 for the details on this PR.  Feedback welcomed.

The install from upstream only looks for Homebrew installed in `/usr/local`, which means the install for autocompletion doesn't work on ARM.  Ultimately, a fix should be made upstream IMHO.  This PR should fix the issue as a workaround by linking the binary to the appropriate prefix regardless of ARM or Intel.  Likewise, I removed the hard-coded `/usr/local` in the `uninstall delete` for this completion file and replaced it with `#{HOMEBREW_PREFIX}` to ensure cleanup works correctly.

I am not sure if this is something we want to support as a (even temporary) workaround, so please feel free to comment or reject this PR if deemed otherwise out of line.

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Review by razvanazamfirei — DISMISSED** [review]
This makes sense to me. We do something similar with docker and filebot.

I'm not sure if it's adding the completion to `/usr/local/etc/bash_completion.d` regardless, which is why I made the change. Happy to revert if not.

**Comment by razvanazamfirei** [comment]
Resolves #153333.

**Comment by krehel** [comment]
Let's see if this goes.  We may need some further adjustments as the `completion` does install correctly on Intel, which I would guess is why CI is complaining about the binary being there.

May need to tweak to do just on ARM, which was my initial thought.

**Comment by krehel** [comment]
Maybe we shouldn't do `arch` check in a `postflight` block, but either way there appears to be a cyclical warning bug for how to determine `arch`.

```
multipass.rb:20:5: C: [Corrected] Cask/OnSystemConditionals: Don't use if Hardware::CPU.arm?, use on_arm do instead.
    if Hardware::CPU.arm? ...
    ^^^^^^^^^^^^^^^^^^^^^
multipass.rb:20:5: C: [Corrected] Cask/OnSystemConditionals: Don't use on_arm in postflight do, use if Hardware::CPU.arm? instead.
```

**Review by miccal — APPROVED** [review]

**Pull request merged**
