### PR TITLE
Update Paragon-ntfs sha256

### PR DESCRIPTION
**Pull request by ghost**
the sha256 of the paragon-ntfs is error

### CODE REVIEW

**Comment by adityadalal924** [comment]
@vitorgalvao The commit is okay but the commit message should be updated (to something like `update shasum for paragon-ntfs`); what script should I use for cases like this?

**Comment by vitorgalvao** [comment]
@dezon `prfixmaster` works here as well. Grab it and [amend](http://stackoverflow.com/a/179147/1661012).

Also keep in mind you don’t *have* to use those scripts (but are very free to do so, naturally).

**Comment by vitorgalvao** [comment]
@adityadalal924 `prfixmaster` works here as well. Grab it and [amend](http://stackoverflow.com/a/179147/1661012).

Also keep in mind you don’t *have* to use those scripts (but are very free to do so, naturally).

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 0d898fef1bcef5a2377e0c9f52d2d14d3855e309. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
