### PR TITLE
chromedriver 115.0.5790.170

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — DISMISSED** [review]

**Comment by krehel** [comment]
I would appreciate someone else looking at this to find a path forward.  Would `ci-skip-install` be valid here?

I tested this locally on both an ARM and intel machine and there are no issues running install or uninstall.

**Comment by bevanjkay** [comment]
@krehel @p-linnane Had to add removing the `chromedriver` symlink to the ci-cleanup step to allow for the install to proceed without error.

**Comment by krehel** [comment]
That's a brilliant catch there @bevanjkay!

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
