### PR TITLE
Add GeburtstagsChecker.app

### PR DESCRIPTION
**Pull request by tiiiecherle**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> It seems the App source '/usr/local/Caskroom/geburtstagschecker/1.8,177/GeburtstagsChecker.app' is not there.

[How to fix](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md).

**Comment by tiiiecherle** [comment]
I´m sorry it`s somehow not possible to edit my pull request.
The line to change should be 
` app "UnicodeChecker #{version.major_minor} (#{version.patch})/UnicodeChecker.app"`
It would be nice if it could be updated.
Thanks

**Comment by tiiiecherle** [comment]
Thank you, just tested the latest version as local install and it works. In my opinion it is good to go. Thanks for editing the request.

**Comment by vitorgalvao** [comment]
@core-code This is an interesting case. [The `appcast`](https://earthlingsoft.net/GeburtstagsChecker/appcast.xml) has `<enclosure sparkle:version="177" sparkle:shortVersionString="1.8"`, which the system isn’t detecting from `1.8.177`, so it’s a false negative.

**Comment by core-code** [comment]
which is one of the cases where the mentioned configuration would be handy..something like:

```

appcast 'bla'
     configuration: '#{version.patch}'
```

**Comment by tiiiecherle** [comment]
Does this mean the background checking script oder the cask have to be changed?

**Comment by core-code** [comment]
neither, this shouldn't prevent merging

**Pull request merged**
