### PR TITLE
karafun 2.3.0,91,8b1dd03e90009107ae99a212322cc03b,1466486e9d

### PR DESCRIPTION
**Pull request by razvanazamfirei**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Hmm... the `shasum` didn't change here. So it may just be using a slightly different link on the cdn. It seems the existing link is still active. Maybe we make livecheck return the active version if the version/build are the same.

**Comment by samford** [comment]
It's worth mentioning that the existing `url` (https://c17.recis.io/sl/e8179eab96/8b1dd03e90009107ae99a212322cc03b/KaraFun_2.3.0.91.dmg) now gives a 404. Unless I'm missing something, I would think that we would want livecheck to surface the different version to ensure that we know to update the broken `url`. If the `livecheck` block is modified to return the current version if the first two parts match, then we wouldn't know to update this to fix the URL.

**Comment by bevanjkay** [comment]
Let's just revert to the unversioned url here with `:no_check`.

**Review by miccal — APPROVED** [review]

**Comment by razvanazamfirei** [comment]
Thanks, @miccal!

**Pull request merged**
