### PR TITLE
sonic-pi 4.4.0, now with Apple Silicon builds

### PR DESCRIPTION
**Pull request by ansonhoyt**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
   (as well as `brew audit --strict --online sonic-pi` as per your [PR docs](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request).
- [ ] `brew style --fix <cask>` reports no offenses.
   😕 I'm confused, as `Don't use if MacOS.version <= :catalina` style warnings contradicts https://docs.brew.sh/Cask-Cookbook#version-comparisons. I did have to scribble notes to get these right, so I'm optimistic the style warnings hint at a better future. 😄

I can't check all the boxes. This is my first go, so without docs coverage of the new `version` and `arch`-related style, I'll have to leave further improvements to those who are more experienced with this. I must've picked bad example casks to learn those parts from. 😨

### CODE REVIEW

**Comment by bevanjkay** [comment]
@ansonhoyt Thanks for the contribution. The docs do need updating to make use of the newer `on_{system}` blocks.
Unfortunately, this cask is one of the instances where it can look quite messy (while still being functional). Because the `on_{system}` blocks are blocks and not `if` statements, we need to duplicate a few of the MacOS versions in the middle.

**Comment by bevanjkay** [comment]
@ansonhoyt Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

**Comment by ansonhoyt** [comment]
Thanks for the tips and the commits. ❤️ Sounds like I should have trusted `brew style`, as it is perhaps more up-to-date than the docs (makes sense).

I'm chasing some deadlines, so have been slow getting back. 😞 Once I get a chance, I'll go through the updates to learn about what I missed.

**Review by miccal — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @ansonhoyt.

**Pull request merged**
