### PR TITLE
Update fugio - depends_on

### PR DESCRIPTION
**Pull request by commitay**
https://github.com/Homebrew/homebrew-core/pull/16640

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Merged as 9fcc9d86c570883014c3aa83ef6ce1d9bffa3e67.

**Comment by commitay** [comment]
https://github.com/Homebrew/homebrew-core/pull/16640 hasn't been merged yet.

**Comment by vitorgalvao** [comment]
> Homebrew/homebrew-core#16640 hasn't been merged yet.

Crap, sorry. Missed the `on hold` label.

**Comment by commitay** [comment]
No problem, I'll revert and open a new PR. Didn't want to revert without checking first.

**Pull request closed without merging**
