### PR TITLE
Update Engine Prime from 1.3.4 to 1.5.0

### PR DESCRIPTION
**Pull request by crunchtime-ali**
Update Engine Prime to the newly released version 1.5.0
https://djworx.com/denon-djs-engine-prime-v1-5-fingers-crossed/

After making all changes to a cask, verify:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ran-dall** [comment]
@crunchtime-ali Is the `15` you added because the app version is at `1.5.0`? If it is, perhaps a better approach would be to add the `15` after the version with a comma and interpolate the `url`?

**Comment by crunchtime-ali** [comment]
@ran-dall They added it in the download address just in this version. I can't tell whether they will continue like this.

This is the source of the download link https://www.denondj.com/engine-prime

**Comment by ran-dall** [comment]
@crunchtime-ali I'll merge it the way it is then, but we should definitely keep an eye on it if it changes frequently.

**Comment by crunchtime-ali** [comment]
> @crunchtime-ali I'll merge it the way it is then, but we should definitely keep an eye on it if it changes frequently.

I am watching the scene and the software closely because I used it for most DJ gigs. I will take care of it.

**Comment by ran-dall** [comment]
@crunchtime-ali Awesome, mate! Thank you! Much appreciated!

**Pull request merged**
