### PR TITLE
Update multimc from 0.6.12 to 0.6.13

### PR DESCRIPTION
**Pull request by haykam821**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
I could not find the URL that the in-app updater uses to check for the latest version, using the `:extract_plist` strategy will work for now, however the version formatting changed to include the build number.

**Comment by bevanjkay** [comment]
@haykam821 If you would like you could contact upstream to find out if there is a publically available URL to check for the latest version. Otherwise, the current strategy will work.

**Comment by haykam821** [comment]
@bevanjkay The update checker uses [this URL](https://files.multimc.org/update/osx64/stable/index.json) to get a list of possible versions, but I haven't determined whether there are specific download URLs. It doesn't look like there is a public latest version URL.

Unfortunately, it seems that GitHub Releases will not be updated because 'it doesnt need to'.

**Comment by bevanjkay** [comment]
@haykam821 Thanks for taking the time to look into this 👍🏻

**Comment by haykam821** [comment]
@bevanjkay It looks like the URL also has to be changed to [the correct platform](https://files.multimc.org/downloads/mmc-stable-osx64-5.15.2.tar.gz), even though that URL is not visible on [the website](https://multimc.org/#Download).

**Pull request merged**
