### PR TITLE
Update unity-android-support-for-editor from 2020.1.16f1,f483ad6465d6 to 2020.1.17f1,9957aee8edc2

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Comment by miccal** [comment]
How many times must I politely ask for you NOT to update these until the main `unity` Cask has been merged?

**Comment by suschizu** [comment]
@miccal - sorry - will be ignored in future

**Pull request merged**
