### PR TITLE
upgrade praat to v6.0.16

### PR DESCRIPTION
**Pull request by psibre**

### CODE REVIEW

**Comment by adidalal** [comment]
Needs a `# github.com/praat/praat was verified as official when first introduced to the cask` comment above this line ([example](https://github.com/caskroom/homebrew-cask/blob/4ad02c9f087deb9e553ab0129c079d73c474add8/Casks/0ad.rb#L5); [reasoning](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment)).

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/20488#issuecomment-208940711.

**Comment by psibre** [comment]
@adidalal if that comment has to be in the cask, then why not. Technically, the source code (and releases) starting being hosted on GitHub long after the cask was first created, but I don't think the order matters in this case.
If you need it to be official, I'm actually a member of the [praat org](https://github.com/orgs/praat/people).

**Comment by adidalal** [comment]
@vitorgalvao I prefer GH releases over third-party sites, anyway. This seems like a legitimate and useful change, any reason to not go with it?

**Comment by vitorgalvao** [comment]
> I prefer GH releases over third-party sites, anyway.

But it’s not third party, it’s official.

> (comment takes care of "verification" issue, anyways)

Yes and no. In the past I’ve found comments not corresponding to the latest URL, meaning verification was forgotten. Also, it’s an extra step for a user to actually verify the verification (versus no steps in just seeing the host corresponds).

Some other notes on https://github.com/caskroom/homebrew-cask/issues/20488#issuecomment-209235950.

> If you need it to be official, I'm actually a member of the [praat org](https://github.com/orgs/praat/people).

Wouldn’t this mean we can actually have the cask always be up to date and not breaking, since there’s someone in the organisation (you) that could make sure an update to the cask is submitted as soon as the app is updated ([`cask-repair`](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask) could even automate it)?

Why are releases done in this manner? Why not keep the old versions, or link to the github releases from the main site? Serious question, since you’re a member of the organisation, you might know the history behind it.

**Comment by vitorgalvao** [comment]
Closing for lack of reply.

To be clear, this decision is not at all set in stone, but input from @psibre is needed to know how to proceed.

**Pull request closed without merging**
