### PR TITLE
Update futuniuniu from 10.4.642_202004131013 to 10.4.644_202004161000

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@vitorgalvao This works on my system, but it fails hard both tests. What should I do with it? The update is valid.

**Comment by suschizu** [comment]
@ran-dall - mine is working - could you close yours? :)
https://github.com/Homebrew/homebrew-cask/pull/81075

**Comment by ran-dall** [comment]
👍

**Comment by ran-dall** [comment]
Closed in preference of #81075

**Pull request closed without merging**
