### PR TITLE
fontforge (new cask)

### PR DESCRIPTION
**Pull request by DomT4**
New Cask for FontForge.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
There’s trailing whitespace that needs to be removed.

**Comment by DomT4** [comment]
That's embarrassing, My apologies. Should be fixed now.

**Comment by vitorgalvao** [comment]
Think nothing of it. Thank you.

**Comment by DomT4** [comment]
Thanks for the merge!

**Comment by vitorgalvao** [comment]
Thank you for the submission.

**Pull request merged**
