### PR TITLE
Update mullvadvpn from 2021.6 to 2022.1

### PR DESCRIPTION
**Pull request by xxyzz**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by xxyzz** [comment]
There are some shell completion files in the `/Applications/Mullvad VPN.app/Contents/Resources` folder, how can I install them like `fish_completion.install` in formulas?

**Comment by miccal** [comment]
You can une an [`uninstall script:`](https://docs.brew.sh/Cask-Cookbook#uninstall-key-script) for that.

**Comment by xxyzz** [comment]
The `brew uninstall` command doesn't show any output of `uninstall.sh` and the script doesn't run on my machine for some unknown reason. Should I delete the script?

**Comment by miccal** [comment]
Yes, if it is not working then just remove it please.

**Comment by xxyzz** [comment]
User settings include account number are stored at `etc/mullvad-vpn`, will they be deleted when upgrade the app?

**Comment by miccal** [comment]
Fixed in https://github.com/Homebrew/homebrew-cask/pull/119930

**Pull request merged**
