### PR TITLE
Add Keysmith.app v0.7.2

### PR DESCRIPTION
**Pull request by euphmat**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by DanielDe** [comment]
Hi there, I'm one of the creators of Keysmith. We've just published an update (version `1.0.1`), so this Cask is now outdated. 

Should I be submitting PRs every time we update, or will Homebrew somehow pick up on the latest version since there's a link to the Appcast? 

Thanks!

**Comment by miccal** [comment]
@DanielDe instructions on updating a cask may be found [here](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

It is as simple as running the command:
```
cask-repair --version 1.0.1 --blind-submit keysmith
```

https://github.com/Homebrew/homebrew-cask/pull/88268

**Comment by ran-dall** [comment]
@DanielDe @miccal  Actually, if it has an valid `appcast` then the update should be picked up automatically.

**Comment by reitermarkus** [comment]
> update should be picked up automatically

Well, not officially. There's no official Homebrew tool/command which does this yet.

**Comment by ran-dall** [comment]
#88274

**Comment by DanielDe** [comment]
Thanks folks! I'll be sure to run the `cask-repair` line in the future.

**Pull request merged**
