### PR TITLE
Fix dsl and url in synth1-au and synth1-vst casks

### PR DESCRIPTION
**Pull request by Amorymeltzer**
- Use and interpolate version
- Remove dsl version erroneously introduced in abe5fa7

### CODE REVIEW

**Comment by adityadalal924** [comment]
Looks like the url could also use some string interpolation, if you don't mind!

**Comment by Amorymeltzer** [comment]
Heh, didn't even check the rest!  Just saw the errors.  Updated.

**Comment by adityadalal924** [comment]
Merged as 2d05a99c89d1af98ed0a9172c765cb28196bc9ec.

**Comment by jawshooah** [comment]
I was just testing out the new rubocop-cask plugin, I swear! :blush:

**Comment by Amorymeltzer** [comment]
👍

**Pull request closed without merging**
