### PR TITLE
Update Launchpad Manager Versioning

### PR DESCRIPTION
**Pull request by merktassel**
When macOS Yosemite was released, Launchpad Manager released a new version `1.0.10` at a special url for Yosemite users: http://launchpadmanager.com/download_yosemite.php/LaunchpadManagerYosemite.dmg. It was the latest version available at the time, so logic was added to the Cask to ensure that any macOS version newer than Mavericks used the Yosemite-specific download link to get `1.0.10`, and any older macOS versions used the existing download link to get the existing, older version at http://launchpadmanager.com/download.php/LaunchpadManager.dmg.

Now that new versions of both macOS and Launchpad Manager have been released, the macOS specific versions are no longer necessary and the outdated logic causes users on macOS Catalina (or anything past Mavericks) to download the (now older) Yosemite version `1.0.10` instead of the latest `1.3.11` that's now available. I've removed this logic so now Catalina users (or really, anyone past Mavericks) will retrieve the correct version rather than the Yosemite-specific outdated version.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by reitermarkus** [comment]
This should really use `version :latest`, unless you can find an appcast.

**Comment by merktassel** [comment]
> This should really use `version :latest`, unless you can find an appcast.

No appcast was available, so I pushed up a new commit to use the `version :latest` syntax you suggested.

**Comment by ikurek** [comment]
This broke Launchpad Manager for me. After update, I now get:

```
Incompatible OSX Version.
This version of Launchpad Manager is not compatible with Yosemite. Please download the Yosemite version from http://launchpadmanager.com
```

 info when I launch software.  I'm running Catalina, tried reinstalling software with

```
brew cask zap launchpad-manager
brew cask install launchpad-manager
```

but it did not help

**Comment by merktassel** [comment]
It seems the new version is no longer compatible with Yosemite. I'll add the following logic to the Cask to fix this for you:

If macOS version is Yosemite, download http://launchpadmanager.com/download_yosemite.php/LaunchpadManagerYosemite.dmg 

Else, download http://launchpadmanager.com/download.php/LaunchpadManager.dmg

Give me a few moments and I'll attach the PR here.

**Comment by merktassel** [comment]
@ikurek see https://github.com/Homebrew/homebrew-cask/pull/72076 for a fix.

**Pull request merged**
