### PR TITLE
Update loopback to 2.0.0

### PR DESCRIPTION
**Pull request by vitorgalvao**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
@core-code Pinging you in case you have a better `appcast` fot the new version.

**Comment by core-code** [comment]
this version checks this URL
`
https://rogueamoeba.net/ping/versionCheck.cgi?format=sparkle&bundleid=com.rogueamoeba.loopback&system=10141&platform=osx&arch=x86_64&version=2008000`

which seems to be up-to-date with version 2.0

**Comment by vitorgalvao** [comment]
@core-code Thank you.

**Comment by core-code** [comment]
@vitorgalvao you're welcome :)

**Comment by ykursadkaya** [comment]
Beause of Loopback 1.x.x licences are invalid for the Loopback 2, in the repo of [homebrew-cask-versions](https://github.com/Homebrew/homebrew-cask-versions) I opened a PR Homebrew/homebrew-cask-versions#6689 for "loopback1". Is it correct? due to #55890

**Pull request merged**
