### PR TITLE
Update chromium from 959064 to 962397

### PR DESCRIPTION
**Pull request by methbkts**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is there no update for the ARM build?

**Comment by methbkts** [comment]
`curl https://www.googleapis.com/storage/v1/b/chromium-browser-snapshots/o/Mac%2FLAST_CHANGE/\?alt\=media`
output -> 962420

`curl https://www.googleapis.com/storage/v1/b/chromium-browser-snapshots/o/Mac_Arm%2FLAST_CHANGE/\?alt\=media`
output -> 962417

**Comment by methbkts** [comment]
@miccal thanks for that, how do you generate the SHA for the ARM build ? Unfortunately I wasn't able to do this by my own

**Comment by miccal** [comment]
@methbkts I did it manually by downloading the relevant file.

**Pull request merged**
