### PR TITLE
Chicken 2.2b3 - changed to my version on github 

### PR DESCRIPTION
**Pull request by boecko**
I made a DMG-File  with upgraded build settings (>OSX 10.7, arch) so the app has native fullscreen support.

see https://github.com/boecko/chicken/releases/tag/v2.2b3

Checks
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Your version as `0` stars. It’s safe to assume users don’t know about it. Don’t just replace the default cask with your own, please. It’s unexpected to users. Submit your patches upstream and get them merged.

**Comment by boecko** [comment]
My repo is just 2 hours old. Even me didn't know about the repo yesterday ;)

The version from sourceforge is from 2011-11-19 (https://sourceforge.net/projects/chicken/files/) and is still targeted to 10.4
Upstream means to get involved in sourceforge and mess around with svn. No thanks

**Comment by vitorgalvao** [comment]
> My repo is just 2 hours old. Even me didn't know about the repo yesterday ;)

All the more reason. No one installing this cask will be expecting to get your version.

**Comment by jawshooah** [comment]
We have protocol for this, just create a new cask called `boecko-chicken`

**Comment by vitorgalvao** [comment]
> We have protocol for this, just create a new cask called `boecko-chicken`

Reason I didn’t mention it is we don’t want to get the repo (and the main repo, even) full of personal forks for every little change. For all we know, this new version fills @boecko needs and will never be updated again and will never have users.

Though we don’t rigidly follow HB’s policy of outright refusing tools with few stars and self-submitted apps, there is a worthy logic behind it.

In this case, I don’t think it is worthy it, at this point in time, to add this app. When and if it becomes a bit more popular, it might be.

**Comment by jawshooah** [comment]
Fair enough. @boecko, you are free to add this Cask to your own custom tap.

**Comment by boecko** [comment]
ok ..

**Pull request closed without merging**
