### PR TITLE
Update ssh-config-editor from 1.12.2,51 to 1.13,54

### PR DESCRIPTION
**Pull request by kmutahar**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by cixtor** [comment]
@kmutahar are you sure the SHA256 of version 1.13 (build 54) is `314aa85f62…`?

Because I just tried to install that version and I get `8df2ba0282…`.

```
$ cask reinstall ssh-config-editor
==> Downloading https://hejki.org/download/ssheditor/SSHConfigEditor-54.zip
==> Verifying SHA-256 checksum for Cask 'ssh-config-editor'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'ssh-config-editor' does not match.
Expected: 314aa85f62a8424fa4b7a8214f42acdb39cda00f3b932ede2a6ac81acec1a942
  Actual: 8df2ba02824e7908d2f9ddbb90999a0649cb9cbb0e2415675800bfa600fdbae3
    File: /Library/Caches/Homebrew/downloads/3decb…387ba--SSHConfigEditor-54.zip
```

**Comment by ran-dall** [comment]
@cixtor It's preferred you open an issue when you experience and issue with a cask. However, you're right, the `sha256` is incorrect. I'm posting a fix for you right now...

**Comment by ran-dall** [comment]
#83811

**Comment by kmutahar** [comment]
@cixtor Looks like they changed the file since I updated two computers and it worked I also just checked my file its the same Hash that i uploaded.

Thank you @ran-dall for updating it 

SSH-config-editors Authors didnt practice proper release protocol. In that you dont re-release the same file without a change in the version.

**Comment by ran-dall** [comment]
> SSH-config-editors Authors didnt practice proper release protocol. In that you dont re-release the same file without a change in the version.

@kmutahar It happens. Thanks for getting back to us though!

**Pull request merged**
