### PR TITLE
Update vlc to 3.0.6

### PR DESCRIPTION
**Pull request by yurikoles**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
thanks!

i was thinking about changing the appcast stanza since their current plan is to keep the appcast outdated:
 https://trac.videolan.org/vlc/ticket/20382
https://trac.videolan.org/vlc/ticket/21643

should we change it e.g. to 
http://download.videolan.org/pub/videolan/vlc/
?

**Comment by yurikoles** [comment]
> should we change it e.g. to
> http://download.videolan.org/pub/videolan/vlc/
> ?
My Cappucino.app don't see feed there.

**Comment by core-code** [comment]
technically there is no feed there, its just a website.

**Review by vitorgalvao — APPROVED** [review]

**Comment by trss** [comment]
How do I resolve the following error?

`Error: Cask 'vlc' definition is invalid: invalid 'depends_on macos' value: ":lion"`

I'm on macOS 10.13.4 High Sierra with Xcode 9.4.1.

**Comment by vitorgalvao** [comment]
@trss https://github.com/Homebrew/homebrew-cask/issues/58046

**Comment by trss** [comment]
Thanks! Worked a treat. Somehow didn't turn up when googling the error.

**Pull request merged**
