### PR TITLE
Update openvpn-connect from 3.2.6,3136 to 3.2.7,3220

### PR DESCRIPTION
**Pull request by i0ntempest**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by joewiz** [comment]
When I received this update today via `brew upgrade`, homebrew reported an error:

```bash
==> Upgrading 1 outdated package:
openvpn-connect 3.2.6,3136 -> 3.2.7,3220
==> Upgrading openvpn-connect
==> Downloading https://swupdate.openvpn.net/downloads/connect/openvpn-connect-3.2.7.3220_signed.dmg
######################################################################## 100.0%
==> Removing launchctl service org.openvpn.client
Password:
==> Removing launchctl service org.openvpn.helper
==> Running uninstall script /Applications/OpenVPN Connect/Uninstall OpenVPN Connect.app/Contents/Resources/remove.sh
==> Uninstalling packages:
org.openvpn.client.pkg
find: /Applications/OpenVPN Connect/OpenVPN Connect.app: No such file or directory
==> Purging files for version 3.2.7,3220 of Cask openvpn-connect
Error: openvpn-connect: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/bash -c set\ -euo\ pipefail'
''
'for\ path\ in\ \"\$\{@\}\"\;\ do'
'\ \ if\ \[\[\ -e\ \"\$\{path\}/.DS_Store\"\ \]\]\;\ then'
'\ \ \ \ /bin/rm\ -f\ \"\$\{path\}/.DS_Store\"'
'\ \ fi'
''
'\ \ \#\ Some\ packages\ leave\ broken\ symlinks\ around\;\ we\ clean\ them\ out\ before'
'\ \ \#\ attempting\ to\ \`rmdir\`\ to\ prevent\ extra\ cruft\ from\ accumulating.'
'\ \ /usr/bin/find\ \"\$\{path\}\"\ -mindepth\ 1\ -maxdepth\ 1\ -type\ l\ \!\ -exec\ /bin/test\ -e\ \{\}\ \\\;\ -delete'
''
'\ \ if\ \[\[\ -L\ \"\$\{path\}\"\ \]\]\;\ then'
'\ \ \ \ \#\ Delete\ directory\ symlink.'
'\ \ \ \ /bin/rm\ \"\$\{path\}\"'
'\ \ elif\ \[\[\ -d\ \"\$\{path\}\"\ \]\]\;\ then'
'\ \ \ \ \#\ Delete\ directory\ if\ empty.'
'\ \ \ \ /usr/bin/find\ \"\$\{path\}\"\ -maxdepth\ 0\ -type\ d\ -empty\ -exec\ /bin/rmdir\ \{\}\ \\\;'
'\ \ else'
'\ \ \ \ \#\ Try\ \`rmdir\`\ anyways\ to\ show\ a\ proper\ error.'
'\ \ \ \ /bin/rmdir\ \"\$\{path\}\"'
'\ \ fi'
'done'
' --` exited with 1. Here's the output:
find: /Applications/OpenVPN Connect/OpenVPN Connect.app: No such file or directory
```

I've tried uninstalling the app via `brew uninstall openvpn-connect` but got the same error.

I then tried downloading the package via https://openvpn.net/download-open-vpn/ and installing it, then running `brew uninstall openvpn-connect` but got the same error.

Without the ability to uninstall, I'm stuck. I'd appreciate any suggestions.

**Comment by reitermarkus** [comment]
@joewiz, this should be fixed once https://github.com/Homebrew/brew/pull/10869 is in a stable release.

**Comment by petr-ujezdsky** [comment]
@reitermarkus thanks a lot! Just a question - how can I know that is in the stable release? It has already been merged, but I do not see any version label or anything similar...

```
$ brew --version
Homebrew 3.0.7
Homebrew/homebrew-core (git revision ad8e5f081e; last commit 2021-03-22)
Homebrew/homebrew-cask (git revision 308828509f; last commit 2021-03-22)
```

**Comment by petr-ujezdsky** [comment]
The problem still persists

```
```

**Comment by petr-ujezdsky** [comment]
The problem still persists

```
==> Upgrading openvpn-connect
==> Downloading https://swupdate.openvpn.net/downloads/connect/openvpn-connect-3.2.7.3220_signed.dmg
Already downloaded: /Users/ujezdsky/Library/Caches/Homebrew/downloads/2b07f9715e3466d1217fe13870c1451f93e829e339701d2f10daaebf48f76bde--openvpn-connect-3.2.7.3220_signed.dmg
==> Removing launchctl service org.openvpn.client
Password:
==> Removing launchctl service org.openvpn.helper
==> Running uninstall script /Applications/OpenVPN Connect/Uninstall OpenVPN Connect.app/Contents/Resources/remove.sh
==> Purging files for version 3.2.7,3220 of Cask openvpn-connect
Error: openvpn-connect: uninstall script /Applications/OpenVPN Connect/Uninstall OpenVPN Connect.app/Contents/Resources/remove.sh does not exist.
```

I have created dummy script at that location 

```
cat "/Applications/OpenVPN Connect/Uninstall OpenVPN Connect.app/Contents/Resources/remove.sh"
#!/usr/bin/env bash
echo Fixing the upgrade
```

and then the upgrade was finally OK:

```
==> Upgrading 1 outdated package:
openvpn-connect 3.2.6,3136 -> 3.2.7,3220
==> Upgrading openvpn-connect
==> Downloading https://swupdate.openvpn.net/downloads/connect/openvpn-connect-3.2.7.3220_signed.dmg
Already downloaded: /Users/ujezdsky/Library/Caches/Homebrew/downloads/2b07f9715e3466d1217fe13870c1451f93e829e339701d2f10daaebf48f76bde--openvpn-connect-3.2.7.3220_signed.dmg
==> Removing launchctl service org.openvpn.client
Password:
==> Removing launchctl service org.openvpn.helper
==> Running uninstall script /Applications/OpenVPN Connect/Uninstall OpenVPN Connect.app/Contents/Resources/remove.sh
Hi, removing
==> Uninstalling packages; your password may be necessary:
org.openvpn.client.pkg
org.openvpn.client_framework.pkg
org.openvpn.client_launch.pkg
org.openvpn.client_uninstall.pkg
org.openvpn.helper_framework.pkg
org.openvpn.helper_launch.pkg
==> Running installer for openvpn-connect; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is OpenVPN Connect
installer: Installing at base path /
installer: The install was successful.
==> Purging files for version 3.2.6,3136 of Cask openvpn-connect
🍺  openvpn-connect was successfully upgraded!
```

Verified the dummy `remove.sh` script was updated by the proper one:
```
cat "/Applications/OpenVPN Connect/Uninstall OpenVPN Connect.app/Contents/Resources/remove.sh"
#!/usr/bin/env bash
SECONDS_SINCE_EPOCH="$(date +%s)"
LOG="/tmp/openvpn-connect-uninstall-$SECONDS_SINCE_EPOCH.log"
...
```

**Pull request merged**
