### PR TITLE
Create ossia-score.rb

### PR DESCRIPTION
**Pull request by jcelerier**
ossia score (https://ossia.io) is a software for creating live audio, video, light & multimedia shows and art installations.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Review by bevanjkay — APPROVED** [review]

**Comment by bevanjkay** [comment]
Thank you @jcelerier 🎉️

**Comment by luzpaz** [comment]
Looks like it was renamed from ossia-score to score in 19c782c0055dffb14bf51b8d2346adb1c038ba18  
This kind of screws up repology https://repology.org/project/ossia-score/history  

Screenshot_20230627_225246

No biggie, I'll just let the repology dev know that the hombrew cask 'score' should really be attributed to 'ossia-score'

**Comment by jcelerier** [comment]
@miccal why the rename? The software's name is "ossia score", not "score"

**Comment by bevanjkay** [comment]
@jcelerier The `token reference` for Homebrew is based on the name of the `.app` artifact.[ See here for reference.](https://docs.brew.sh/Cask-Cookbook#token-reference)

**Comment by jcelerier** [comment]
okay, i'll change the .app to be "ossia score" upstream

**Comment by luzpaz** [comment]
Clarification, was ossia-score renamed or removed from Casks completely ? (reason I ask is that if the former, it still hasn't shown up in repology (which may be a problem on repolgy's side)

**Comment by bevanjkay** [comment]
It was renamed to `score` as the token system follows the app's artifact naming, in this case `score.app`

**Pull request merged**
