### PR TITLE
changed paw to versioned url

### PR DESCRIPTION
**Pull request by adidalal**
The generic download URL on the homepage redirects to a versioned AWS url.

```
wget https://luckymarmot.com/paw/download
...
HTTP request sent, awaiting response... 302 FOUND
Location: https://luckymarmot-distribution.s3.amazonaws.com/paw/Paw-2.2.2.zip
```

### CODE REVIEW

**Comment by adityadalal924** [comment]
(Help needed, audit fails even though url is valid)

    Error: Cask 'paw' definition is invalid: 'url' stanza failed with: bad URI(is not URI?): https://luckymarmot-distribution.s3.amazonaws.com/paw/Paw-#{version}.zip

**Comment by Ngrd** [comment]
You have to use double quotes for the URL if using the `#{version}`.

**Comment by adityadalal924** [comment]
Thanks, made the change but not sure how to squash the two commits. audit passed though

**Comment by Ngrd** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 5e1d9f7c38c08e890113a584ae5e9d2638616776. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
