### PR TITLE
Update nomachine to 6.1.6_10

### PR DESCRIPTION
**Pull request by luispuerto**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]

**Comment by commitay** [comment]
I'd think we should remove the `zap` altogether rather than make it the `uninstall`. 

Removing `com.nomachine.uninstall` means that we aren't duplicating the uninstall and I'm also getting `kextunload` errors with this.

**Comment by commitay** [comment]
I don't know but running the script without any args doesn't do anything.

**Comment by vitorgalvao** [comment]
That’s because the script only runs if the app bundld isn’t present anymore. If you inspect it, it’s a few functions at the too and then a huge `if` statement checking for that condition.

**Comment by commitay** [comment]
Cask will run the script before the app is removed.

**Pull request merged**
