### PR TITLE
Update tankix to 577

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by giannitm** [comment]
@vitorgalvao `cask-repair` keeps setting the `sha256` stanza to `:no_check`, even when I edit the file manually by using the `e` key. Is this an intended behaviour?

**Comment by vitorgalvao** [comment]
Definitely not intended. I think I know what might be the cause.

**Comment by vitorgalvao** [comment]
Should be fixed in the latest version.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/31820

**Pull request closed without merging**
