### PR TITLE
bump kui from 11.0.0 to 11.1.0

### PR DESCRIPTION
**Pull request by starpit**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by neutric** [comment]
Since you are the author: `strategy :github_latest` comes at the cost of a limited API access and is only necessary if there are also pre-releases. If all releases are production-ready then you can omit the whole `livecheck` stanza and rely on the built-in `livecheck` for GitHub repos.

**Comment by starpit** [comment]
Hey, thanks for the feedback. I tried this a while back, and got this from one of the maintainers:

> @bevanjkay requested changes on this pull request.
> 
> In Casks/kui.rb:
> ```diff
> >    livecheck do
>      url :url
> -    strategy :github_latest
> +    strategy :git
> +    regex(/^v(\d+(?:\.\d+)*)$/)
>    end
> ```
> @starpit I think the :github_latest strategy is probably still required as some tags do not include binaries. Also, for reference, when the strategy is :git and a custom regex is not required (and the download URL is from Github), the livecheck block should be removed as it is used by default.

Perhaps a more refined version of that would work?

**Comment by neutric** [comment]
Good point with the missing binaries. I scrolled down the first releases page and the binaries seemed in place, but should have looked at the tags page as well. The implicit `livecheck` is based on tags, so in your case explicitly limiting it to the ones designated "latest" is necessary. Apologies!

**Comment by starpit** [comment]
Is the constraint with `:git` that every tag must also have a release?

**Comment by neutric** [comment]
> Is the constraint with `:git` that every tag must also have a release?

Without changing your version scheme, yes. `livecheck` looks through all tags in search of the highest version number. You could add more meaning to the version number, say add a "-release" to all those with binaries, and then filter with a regex.

**Comment by starpit** [comment]
Ok great, we will do this with the next release of Kui.

**Comment by neutric** [comment]
> Ok great, we will do this with the next release of Kui.

If easily possible for you, then 👍. Not sure how common this is, though, but a quick `grep` gave me https://github.com/duplicati/duplicati/tags. They go wild stuffing their tags with metadata. ;)

**Comment by starpit** [comment]
we don't do pre-releases on github any more. so it should be an easy enough fix. hold off on this for a second, we have a minor bug fix rolling through now. we'll release that as 11.1.1 in 10-15 minutes.

**Comment by starpit** [comment]
Updated

**Comment by miccal** [comment]
Thank you @starpit.

**Pull request merged**
