### PR TITLE
Update acslogo

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@core-code Do you know if there's there a way to add `user agent: fake` to the `appcast` so it can pass the CIs?

**Comment by core-code** [comment]
i don't think thats possible but @vitorgalvao may know better

**Comment by ran-dall** [comment]
@core-code I'll merge it for now. I like to have a clean-ish PR log when I do updates later.

**Comment by vitorgalvao** [comment]
> Do you know if there's there a way to add `user agent: fake` to the `appcast` so it can pass the CIs?

I don’t understand the question. If you mean a way of making the check behave as if `user_agent: :fake` was there when it isn’t, then no. But I also don’t get why you’d want to do that.

**Comment by core-code** [comment]
i think the point would be to be able to set the user-agent which is used to retrieve the appcast (instead of the download URL)

**Comment by vitorgalvao** [comment]
Ah, thank you for the clarification. The answer is still no, *but* what we can do is change the appcast check itself in the core to always use `:fake` (or whatever).

**Comment by core-code** [comment]
just for reference - note that the only feeds i've found that require special user-agents *and* have a cask are from the techsmith apps. i  also remember it from 'transmit' but that doesn't seem to work anymore anyway.

**Comment by ran-dall** [comment]
> ...what we can do is change the appcast check itself in the core to always use the fake user agent in the curl request.

That's a great idea.

**Pull request merged**
