### PR TITLE
Add a cask for (Verimag) lustre V4 (III-C) distribution

### PR DESCRIPTION
**Pull request by jahierwan**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference]. 
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but looks a bit too obscure, so we’re going to refuse it.

If this is open-source, try the Homebrew/homebrew-core repo.

**Comment by jahierwan** [comment]
What is obscure?

**Comment by vitorgalvao** [comment]
The software. As in “not enough of our users will want this to warrant inclusion”.

**Comment by jahierwan** [comment]
Ah, ok. 

May I suggest you warn people somewhere on the minimal number of expected users that would make contributions welcome?

**Comment by vitorgalvao** [comment]
[We do](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md).

**Comment by jahierwan** [comment]
https://en.wikipedia.org/wiki/Lustre_(programming_language)

Beside, lustre is teached in dizains of universities (http://www-verimag.imag.fr/DIST-TOOLS/SYNCHRONE/lustre-v6/lustre.png)

As a matter of fact, it was one the professor that was teaching it that asked me for a convenient 
way to install it on mac, and I though that brew was a good way.

**Comment by vitorgalvao** [comment]
Fair enough. “Obscure” is relative and open to discussion.

But is this open-source?

**Comment by jahierwan** [comment]
Not the V4 distribution. But The V6 (which is in the pipe) is

**Comment by vitorgalvao** [comment]
In that case, I’d still rather not merge this. *But*, when V6 is released, submit it to [Homebrew/core](https://github.com/homebrew/homebrew-core) as a formula that builds from source.

From [faq/rejected_casks](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core) as a formula that builds from source. If it is rejected, you may then try again as a cask (link us to the issue so we can see the discussion and reasoning for rejection).

**Comment by jahierwan** [comment]
When I wrote V6 is in the pipe, I meant that I have a cask file ready...

V6 is there, but some of the tools of its distribution uses some of the tools of the V4 distro (based on X11/tcl-tk).
V4 is still used by teachers that did not migrate to V6, which is a slightly different language.

**Comment by vitorgalvao** [comment]
Thank you for the clarification. Still, I’d rather you submitted the V6 to `homebrew-core` first, and we continue from there. Feel free to @mention me / link this PR in that discussion.

**Comment by jahierwan** [comment]
I'm ok to put v6 on core. But  note that not all the tools in V6 will work without access to the v4 distrib. 
Even it is desirable to have v4 is on cask, and v6 on core (which sounds a bit odd to me),
I think I need to publish V4 somewhere first.

In other words, in my [lustre-v6-tools cask file](https://github.com/jahierwan/homebrew-cask/blob/8d8195037ca50ba14285f82476ee6f2298632bd7/Casks/lustre-v6-tools.rb) i have: 
depends_on cask: 'lustre-v4-tools'

I don't know (yet) how to state such a dependency in homebrew-core, but anyhow, it won't work 
if lustre-v4-tools is not available.

**Comment by reitermarkus** [comment]
We don't have a way for a formula to depend on a cask, but you can add a caveat similar to this:

https://github.com/Homebrew/homebrew-core/blob/cffce1712168c9652cf49fd8cbf15029bc948e0e/Formula/scrcpy.rb#L39-L45

**Pull request closed without merging**
