### PR TITLE
Updated lots of links to use SSL

### PR DESCRIPTION
**Pull request by scribblemaniac**
I have manually tested all of the links that I have changed to make sure they had valid ssl certificates, they weren't being redirected to http, and that they were actually going to the correct pages. I did not test some of the links to amazonaws, github, and googlecode as it is quite safe to assume they all have proper ssl support. This should cover almost all of the links that can be updated to https.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You grabbed a bunch of unrelated commits.

**Comment by scribblemaniac** [comment]
I'm still getting used to the git workflow. Better?

**Comment by vitorgalvao** [comment]
Definitely. Thank you.

I’ll merge it in since it looks good, but in the future I ask that you make a commit for each cask (like [this](https://github.com/caskroom/homebrew-cask/pull/10364)).

**Comment by scribblemaniac** [comment]
Okay, will do.

**Pull request merged**
