### PR TITLE
updated duet (1.5.4.9)

### PR DESCRIPTION
**Pull request by tsparber**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by tsparber** [comment]
Updating the `appcast` checkpoint is hard, as manual changes get overwritten by `cask-repair` and `cask-repair` does not follow the redirect.

**Comment by adidalal** [comment]
Pinging @vitorgalvao about `cask-repair`

**Comment by adidalal** [comment]
Doesn't Duet not work, anyway? https://github.com/caskroom/homebrew-cask/issues/14952

**Comment by vitorgalvao** [comment]
> `cask-repair` does not follow the redirect

It should. What version are you using (get it with `brew info cask-repair`; if you installed manually, there’s no way to know)?

**Comment by adidalal** [comment]
Latest version reports:

```
• appcast is probably incorrect, as a non-200 (OK) HTTP response code was returned (302)
```

But what @tsparber is noting is that even if you manually edit, cask-repair will revert that edit when it rechecks after the manual edit

**Comment by vitorgalvao** [comment]
Reverting the edit happens both with `checkpoint:` and `sha256`. It’s by design, as you’re not supposed to do them by hand (it’s an obtuse value that you need a computer to calculate anyway, so let the computer do all the work). For that reason I don’t intend to change that behaviour, as I believe the intent to be correct.

As for the message, it says “probably” precisely to allow some leverage. @tsparber swayed me in the past (regarding the script to find sparkle appcasts) on following appcast redirects, which is why `cask-repair` also (should be, anyway) follows them. It’s a warning, not an error, as it is just meant to ask you if you’re sure, in a way. It does not stop you submitting (not passing audit, for example, does).

So my question is if the latest version of `cask-repair` is really not following redirects, and hence not getting the correct `checkpoint:`. Making it get the correct `checkpoint:` is the solution, not allowing manually editing it.

**Comment by vitorgalvao** [comment]
Just looked at it, and `cask-repair` seems to be working well. The problem, though, is that the `appcast` url is redirecting to an old version `1.5.1.1`, so no wonder no check is detected.

Which leads to the question: to what `checkpoint:` value are you trying to change it, @tsparber?

**Comment by tsparber** [comment]
Sorry, I was a bit sloppy on this one. I'm using the latest version of `cask-repair` (0.23.1 as reported by `brew info`).
I was confused by the warning about the non-200 status code and run the command to get the checksum manually (from [doc/.../appcast](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md)), which indeed does not follow the redirect and got me a different (wrong) checkpoint.
So `cask-repair` works correctly (apart from the a little bit misleading warning), the [`appcast.md`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md) might need an update.

> Doesn't Duet not work, anyway? #14952

I does work, because it moves itself to `/Application` and needs to started from there. What does not work is, when a user has the `--appdir` set to `/Application` (and so a symlink exists, which does not get overwritten by the app itself). The https://github.com/caskroom/homebrew-cask/issues/14952#issuecomment-182162172 suggests just to wait.

**Pull request merged**
