### PR TITLE
Rowanj gitx

### PR DESCRIPTION
**Pull request by NeoVG**
New pull request after finding the correct and already present cask. ;)

See https://github.com/caskroom/homebrew-cask/pull/9186 for more information and comments.

### CODE REVIEW

**Comment by jawshooah** [comment]
Your `gitx-dev` cask is still present in this PR.

**Comment by jawshooah** [comment]
There is also another GitX fork available as a cask, though I can't remember it off the top of my head and I'm on mobile. Could you do `brew cask search gitx`, find the other fork, and add it to the `conflicts_with` stanza?

**Comment by jawshooah** [comment]
Moreover, could you add corresponding `conflicts_with` stanzas to the other GitX casks?

**Comment by rolandwalker** [comment]
Hi @NeoVG!

You may leave out the `conflicts_with`.  That functionality is not ready yet.

**Comment by jawshooah** [comment]
@rolandwalker Isn't it better to be proactive? We _are_ planning on implementing that functionality, so it's better to add the stanza now than have to find conflicts later.

**Comment by jawshooah** [comment]
Never mind, I'll add the `conflicts_with` stanzas in a separate PR.

**Comment by fanquake** [comment]
Needs rebase.

**Comment by rolandwalker** [comment]
@fanquake it needed a rebase due to merge conflict with #9200, which was specifically requested to be avoided.

@NeoVG, as project owner, I apologize for the needlessly complicated process here.  This is not the usual way we do things!  Your contribution is [pure gold](https://github.com/caskroom/homebrew-cask/pull/9239/files#diff-d2b71ad8b67f486892566026971c38a7R29), and is deeply appreciated.

I fixed the interference caused by #9200 and committed your changes manually as 683134e39340ef31519b58c2328a3a2534cf927a .  I also dropped out `gitx-dev.rb`; please correct me if that was wrong.

Many thanks.

**Pull request closed without merging**
