### PR TITLE
Update Transmission Remote GUI to v5.15.4

### PR DESCRIPTION
**Pull request by PeterDaveHello**
https://github.com/transmission-remote-gui/transgui/releases/tag/v5.15.4
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
`5.15.4` is tagged as `5.14.4`

https://github.com/transmission-remote-gui/transgui/releases/download/v5.14.4/transgui-5.15.4.dmg

**Comment by PeterDaveHello** [comment]
Made an accident in the tag ... fixed now :)

**Comment by PeterDaveHello** [comment]
Hi @commitay @vitorgalvao 

Just wanna to confirm with you guys, if now I rebase the upstream commit to fix the upstream tag, will that break this cask if we didn't update cask here? Many thanks.

**Comment by vitorgalvao** [comment]
@PeterDaveHello Commits themselves won’t break the cask. If the download URL of the dmg and the dmg itself stay the same (i.e. it’ll have the same sha256), then the cask remains unchanged.

**Comment by PeterDaveHello** [comment]
Thank you!

**Pull request merged**
