### PR TITLE
Upgrade Telegram to 4.2.2

### PR DESCRIPTION
**Pull request by franklouwers**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/pull/50316

**Comment by commitay** [comment]
Thanks for the PR nonetheless!

**Comment by franklouwers** [comment]
Ha, I thought I checked, but suppose I was wrong. :)

**Comment by brianmorton** [comment]
the submission was only 2 minutes before yours, so I think you probably did check :)

**Pull request closed without merging**
