### PR TITLE
Update nova.rb to reflect new download url

### PR DESCRIPTION
**Pull request by dvclmn**
> **Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.
> 
> _In the following questions `<cask>` is the token of the cask you're submitting._
> 
> After making all changes to a cask, verify:
> 
> - [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
> - [ ] `brew audit --cask --online <cask>` is error-free.
> - [x] `brew style --fix <cask>` reports no offenses.
> 

The pull request is to address an outdated URL. `brew audit --cask --online <cask>` yields an error because of this outdated URL, so I'm unable to tick it yet.

### CODE REVIEW

**Comment by dvclmn** [comment]
Hi Homebrew team, apologies for any errors or invalidities in my pull request. My first time contributing to a project. I studied https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request and https://docs.brew.sh/Cask-Cookbook to ensure I got it right, but I suspect I haven't!

**Comment by SMillerDev** [comment]
Are versioned urls no longer working?

**Comment by p-linnane** [comment]
Looks like versioned .zips can be grabbed from https://download.panic.com/nova/.

**Review by bevanjkay — DISMISSED** [review]
Thank you @dvclmn and @p-linnane

**Review by bevanjkay — APPROVED** [review]

**Comment by dvclmn** [comment]
Thanks for the spot @p-linnane. For future reference, is something explicitly versioned better for the project, rather than something like `[Name]-Latest.zip`? Noted for future.

**Comment by bevanjkay** [comment]
@dvclmn Using versioned downloads allows us to have a `sha256` value that is referenced upon downloads. This will stop the application from being upgraded/installed if the file is different from when the PR was merged (in case upstream's server has been compromised, or in other cases the download may have not finished correctly). 

When unversioned links are used, a `sha256` value cannot be passed as the cask will break each time upstream update the application, whereas versioned downloads continue to provide the previous version until the updated version is merged.

**Comment by dvclmn** [comment]
@bevanjkay Thanks for the info, much appreciated.

**Pull request closed without merging**
