### PR TITLE
Update iboostup to 5.6.1

### PR DESCRIPTION
**Pull request by gobinathm**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by gtmgianni — APPROVED** [review]

**Comment by giannitm** [comment]
@vitorgalvao Just out of curiosity, is it beneficial for contributors to review other's pull requests, or is it not really necessary?

**Comment by gobinathm** [comment]
@giannitm based on my experience its good to check the PR which has failed Travis builds.

**Comment by giannitm** [comment]
@gobinathm Fair point.

**Comment by vitorgalvao** [comment]
There are three main instances when I review with Github’s feature:

+ ✘ There are changes that need to be made.
+ ✔ Everything looks fine but I’m not merging yet because Travis hasn’t finished.
+ ✔ Everything looks fine but I’d like for another maintainer to check/merge. This usually happens when the PR suffered a lot of changes and this is the final “alright, everything looks fine but I’d like another pair of eyes in case I missed something amidst all the changes”.

There’s no point for contributor reviews in the second or third cases, since they’ll still need to be signed off. The first case is useful, though, for two reasons:

+ You may catch something we didn’t.
+ If you start the conversation early with the user, the issue might already be solved when the maintainer arrives, which saves a lot of time and helps _tremendously_.

**Pull request merged**
