### PR TITLE
Update sapmachine-jdk from 17.0.2 to 18

### PR DESCRIPTION
**Pull request by RealCLanger**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by RealCLanger** [comment]
Hi, any reason why this is not getting merged? I see test failures but this is related to changing the major version of the cask - which should be ok. Thanks, Christoph

**Comment by SMillerDev** [comment]
Because nobody got to it yet. And because the CI failure suggests that this version isn't publicly available yet.

**Comment by RealCLanger** [comment]
> Because nobody got to it yet. And because the CI failure suggests that this version isn't publicly available yet.

OK, thanks. As for the version: It is available, was released on Tuesday last week: https://github.com/SAP/SapMachine/releases/tag/sapmachine-18

Do you need anything more?

**Comment by RealCLanger** [comment]
Nothing happens. Try again.

**Pull request closed without merging**
