### PR TITLE
Update forticlient to 6.0

### PR DESCRIPTION
**Pull request by bluelet13**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but the download on the website still points to `6.0` and the checksum is the same, so the cask appears correct.

**Comment by bluelet13** [comment]
@vitorgalvao, Thank you for checking.

Sorry, I could not provide enough information. Surely current cask is `6.0.1`, but this is invalid URL. 

```
$ brew cask install forticlient -v
Updating Homebrew...
==> Satisfying dependencies
==> Downloading https://filestore.fortinet.com/forticlient/downloads/FortiClientOnlineInstaller_6.0.1.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/2.0.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.3\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/kento-o/Library/Caches/Homebrew/downloads/d8284e14da966451e84382be3a9dc9f3e89f5d322fca942843318485c5424904--FortiClientOnlineInstaller_6.0.1.dmg.incomplete https://filestore.fortinet.com/forticlient/downloads/FortiClientOnlineInstaller_6.0.1.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'forticlient' with message: Download failed: https://filestore.fortinet.com/forticlient/downloads/FortiClientOnlineInstaller_6.0.1.dmg
```
Latest version seems to be `6.0` instead of `6.0.1`.  However, the checksum of `6.0` and `6.0.1` is the same.
```
$ /usr/bin/curl https://filestore.fortinet.com/forticlient/downloads/FortiClientOnlineInstaller_6.0.dmg | shasum -a 256   
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1191k  100 1191k    0     0   168k      0  0:00:07  0:00:07 --:--:--  174k
ef54a8fcc3588c6a7a87b6a94c976d58bf6fabbf4a48626be8d52ab72b0d01f1  -
```

**Comment by vitorgalvao** [comment]
> Surely current cask is `6.0.1`, but this is invalid URL.

That error is with *your* change. The cask as is downloads fine.

**Comment by bluelet13** [comment]
I think you are misunderstanding. Please, see [Travis CI Details](https://travis-ci.org/Homebrew/homebrew-cask/builds/501079692#L310). This error is not due to my change.
If no change, The cask is downloads fail.

**Comment by vitorgalvao** [comment]
Ah, right, I was understanding your fix in reverse.

**Pull request merged**
