### PR TITLE
Update xamarin-ios from 14.14.2.5 to 14.17.2.4

### PR DESCRIPTION
**Pull request by ccxla**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Did you use `brew bump-cask-pr`? It shouldn't have changed the `#{version}` part, as shown here: https://github.com/Homebrew/homebrew-cask/pull/104792/commits/832ff43fedd3db5de7151d6088c0abbe0e2b7c28

**Comment by ccxla** [comment]
> Did you use `brew bump-cask-pr`? It shouldn't have changed the `#{version}` part, as shown here: [832ff43](https://github.com/Homebrew/homebrew-cask/commit/832ff43fedd3db5de7151d6088c0abbe0e2b7c28)

I used `brew bump-cask-pr xamarin-ios --version=14.17.2.4 --url=https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-14.17.2.4.pkg  --sha256=no_check`.

**Comment by carlocab** [comment]
Ah, I see. You can leave out `--url` when you've already specified `--version`, especially for Casks.

**Comment by cho-m** [comment]
With versioned URL, a SHA256 should also be provided.
Doing `brew bump-cask-pr xamarin-ios --version 14.17.2.4` would auto-calculate SHA if you prefer.

---

Now the main question is if there is any resource showing **14.17.2.4** as latest stable release?
- The CI failure is due to `livecheck` URL https://software.xamarin.com/Service/Updates?v=2&pv4569c276-1397-4adb-9485-82a7696df22e=0 showing **14.14.2.5**
- Microsoft docs https://docs.microsoft.com/en-us/xamarin/ios/release-notes/ currently still shows **14.14** as latest
- The only URL I see with newer releases is GitHub repo https://github.com/xamarin/xamarin-macios/releases which tagged **14.17.0.247** and **14.17.2.4** but I don't know if these are stable releases.

**Comment by miccal** [comment]
Thank you @ccxla -- I will submit a new PR to update this Cask.

**Pull request closed without merging**
