### PR TITLE
Update boom to 1.6.11

### PR DESCRIPTION
**Pull request by core-code**
ok we have a bit of a problem here. they don't use sparkle anymore, but a homegrown solution. which is difficult to piggyback on even with sophisticated CGIs. basically they do this:

`curl -H 'Host: www.globaldelight.net' -H 'Content-Type: application/octet-stream' -H 'Accept: */*' -H 'User-Agent: Boom%202/1.6.9003 CFNetwork/1200.1 Darwin/20.1.0' -H 'Accept-Language: en-gb' --data-binary "@data.txt" --compressed 'https://www.globaldelight.net/tower/registrationauth/boom/boomCheckUpdateOffer.php'`

where you need a 500 byte binary file. 

=> current output:
`{"ResponseStatus":"1","AppVersionAvailable":"1.6.11","DownloadURL":"https:\/\/d3jbf8nvvpx3fh.cloudfront.net\/Boom2\/Update\/v1.6.11\/Boom_2_Update.dmg","ReleaseNotes":"Boom 2 (v1.6.11) comes with: \n- Minor defect fixes."}%   
`
so the other option is to use and try to observe the static download file from the homepage. lets try that

### CODE REVIEW

**Comment by core-code** [comment]
data file fyi

[data.txt](https://github.com/Homebrew/homebrew-cask/files/5324168/data.txt)

**Comment by core-code** [comment]
ping @suschizu

**Comment by core-code** [comment]
not sure why CI ignores the label

**Review by suschizu — APPROVED** [review]

**Pull request merged**
