### PR TITLE
make auto_updates true for osxfuse

### PR DESCRIPTION
**Pull request by ho-oto**
Osxfuse can be updated by itself.
https://github.com/osxfuse/osxfuse/wiki/FAQ#22-how-can-i-keep-fuse-for-os-x-up-to-date

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by reitermarkus** [comment]
> It should tell you if there is and update and if so, will also let you download and install it.

So you have to manually to into the preference pane and click update?

**Comment by miccal** [comment]
FYI: https://github.com/Homebrew/brew/issues/9401

**Comment by ho-oto** [comment]
> So you have to manually go into the preference pane and click update?
Yes

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/94187#issuecomment-738449938

**Comment by reitermarkus** [comment]
> Yes

I wouldn't call that auto-updating then.

**Comment by vitorgalvao** [comment]
> > Yes
> 
> I wouldn't call that auto-updating then.

Agreed. If the app’s “auto-update” takes more than one click (like Sparkle) and you have to manually check for it, it doesn’t qualify.

**Pull request closed without merging**
