### PR TITLE
Update aptible from 0.19.3,20220314154920,340 to 0.19.3,20220324183731,340

### PR DESCRIPTION
**Pull request by UserNotFound**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by UserNotFound** [comment]
cc: @neurosnap

**Comment by UserNotFound** [comment]
I'm not sure why this didn't get the `bump-cask-pr` label or trigger the workflow/checks? Command and output below:

```
$ brew bump-cask-pr --version 0.19.3,20220324183731,340 aptible
==> Downloading https://omnibus-aptible-toolbelt.s3.amazonaws.com/aptible/omnibus-aptible-toolbelt/master/340/pkg/aptible-toolbelt-0.19.3%2B20220324183731-mac-os-x.10.15.7-1.pkg
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/2bc456928348a7a8dcf857e2c5c53cc96fd99d1a4dd4efcc1323a792f87816f5--aptible-toolbelt-0.19.3+20220324183731-mac-os-x.10.15.7-1.pkg
==> replace /version\s+["']0\.19\.3,20220314154920,340["']/m with "version \"0.19.3,20220324183731,340\""
==> replace /sha256\s+["']e50d899e25172facbac1489a6e24a4d17431631485ca15be8b026be1c99480e8["']/m with "sha256 \"4ecbe4b716ec6f725338164159da2d8acbe964e603085f1f6919a3bb0a74e76c\""
audit for aptible: passed

1 file inspected, no offenses detected
M	Casks/aptible.rb
Switched to a new branch 'bump-aptible-0.19.3-20220324183731-340'
[bump-aptible-0.19.3-20220324183731-340 cc0b3c45a5] Update aptible from 0.19.3,20220314154920,340 to 0.19.3,20220324183731,340
 1 file changed, 2 insertions(+), 2 deletions(-)
remote:
remote: Create a pull request for 'bump-aptible-0.19.3-20220324183731-340' on GitHub by visiting:
remote:      https://github.com/UserNotFound/homebrew-cask/pull/new/bump-aptible-0.19.3-20220324183731-340
remote:
To https://github.com/UserNotFound/homebrew-cask.git
 * [new branch]            bump-aptible-0.19.3-20220324183731-340 -> bump-aptible-0.19.3-20220324183731-340
Branch 'bump-aptible-0.19.3-20220324183731-340' set up to track remote branch 'bump-aptible-0.19.3-20220324183731-340' from 'https://******@github.com/UserNotFound/homebrew-cask.git'.
```

**Comment by UserNotFound** [comment]
Thanks @carlocab !!!

**Review by carlocab — APPROVED** [review]

**Pull request merged**
