### PR TITLE
Slack: pin pre-Mojave at v4.19.0

### PR DESCRIPTION
**Pull request by augmentedfourth**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:
_not applicable_

### CODE REVIEW

**Comment by augmentedfourth** [comment]
I don't know what happened here, but the CI failure seems to be an aberration that is out of my control. Can we re-run this, or merge/approve anyway?

**Comment by miccal** [comment]
According to https://slack.com/intl/en-au/help/articles/115002037526-System-requirements-for-using-Slack the Slack app requires macOS 10.14 or above, and according to https://slack.com/intl/en-au/help/articles/1500001836081-Slack’s-deprecation-schedule#mac-1 support for macOS versions 10.13 and below was deprecated on the 1st of September 2021.

I think it would be better, then, to add a `depends_on macos: ">= :mojave"` then continue to provide old versions that are deprecated upstream.

**Comment by augmentedfourth** [comment]
I still have an old 2010 Mac that can't run an OS past 10.13, and Slack 4.19.0 still installs successfully on it, which is why I wrote the PR this way. I'd rather be able to still manage the installation via Homebrew. I know the tool is deprecated for High Sierra, but the warning message requests that users create PRs to resolve their own issues, which is what I've done here.

**Comment by miccal** [comment]
> I still have an old 2010 Mac that can't run an OS past 10.13, and Slack 4.19.0 still installs successfully on it, which is why I wrote the PR this way. I'd rather be able to still manage the installation via Homebrew. I know the tool is deprecated for High Sierra, but the warning message requests that users create PRs to resolve their own issues, which is what I've done here.

Thanks @augmentedfourth, but since support for this version of macOS has been deprecated upstream we cannot accept this change.

Please consider hosting this version [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) so that your installation can still be managed by Homebrew.

**Pull request closed without merging**
