### PR TITLE
Update amazon-music from 7.3.2,20190506:200920c097 to 7.4.0.1811,20190605:18024163ef

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
I've added a "configuration: :no_check" here because the appcast links directly to the app download (https://www.amazon.com/gp/dmusic/desktop/downloadPlayer)
I'm not sure if it's appropriate in this case @core-code, @vitorgalvao (?)

**Comment by core-code** [comment]
it doesn't really link to the app download. it links to the html site. the reason you see 'gibberish' when downloading the appcast with curl is that its gzip compressed, which makes it pretty useless unless we implement some way to handle that.

i'm fine with 'configuration: :no_check' as it makes sense here unless someone implements a unzip method for the appcast check

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/brew/pull/6240 should do it.

**Comment by core-code** [comment]
great job on the compressed appcast support :) i remember a few others that also need that, though i am not sure which ones it were.

unfortunately, it won't help in this case, unless we fake the user-agent too ^^

**Comment by vitorgalvao** [comment]
> unless we fake the user-agent too

Done.

**Comment by core-code** [comment]
> > unless we fake the user-agent too
> 
> Done.

how, where?

**Comment by vitorgalvao** [comment]
> how, where?

Same PR.

**Pull request merged**
