### PR TITLE
Add Loading.app Latest

### PR DESCRIPTION
**Pull request by Pewpewarrows**
https://github.com/BonzaiThePenguin/Loading

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/master/Casks/acorn.rb).

**Comment by Pewpewarrows** [comment]
Whoops, should be all fixed now.

**Comment by vitorgalvao** [comment]
Thank you. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by Pewpewarrows** [comment]
Done!

**Pull request merged**
