### PR TITLE
Add conflicts_with stanzas to gitx, laullon-gitx, rowanj-gitx

### PR DESCRIPTION
**Pull request by jawshooah**

### CODE REVIEW

**Comment by jawshooah** [comment]
```
'gitx' definition is invalid: 'conflicts_with' stanza may only appear once (Hbc::CaskInvalidError)
```
Is there a reason for this? We allow multiple `depends_on` stanzas, why not `conflicts_with`?

**Comment by vitorgalvao** [comment]
```ruby
conflicts_with :cask => 'laullon-gitx',
               :cask => 'rowanj-gitx'
```

should work, I think. `conflicts_with` hasn’t been implemented yet, though, it’s only a stub, so it might just be a temporary oversight.

**Comment by jawshooah** [comment]
I like that better than the array syntax, at least. I'll make the change.

**Comment by jawshooah** [comment]
Wait, no. That won't work. The options are a hash, and that would duplicate keys.

**Comment by jawshooah** [comment]
@vitorgalvao Fixed up the `conflicts_with` stanzas as per @rolandwalker's comment in #9201.

**Pull request merged**
