### PR TITLE
dendroscope 3.3.2 (new formula)

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by Ngrd** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 36d61afd72a77e7f38cb636ab5125102af026252. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by sjackman** [comment]
Thanks for the merge and fix, Victor.

**Comment by vitorgalvao** [comment]
@Ngrd two notes, here:

1. It needs the `# tuebingen.de is the official download host per the vendor homepage` comment (we need to manually check download links when the host of `url` and `homepage` differ and have that comment as confirmation a maintainer verified it).

2. Since it has `installer :manual`, it still needs an `uninstall`. `installer :manual` and `pkg` casks should not be merged until an `uninstall` is present, even if that means holding up the cask indefinitely.

**Comment by Ngrd** [comment]
Understood. Thank you @vitorgalvao for the explanations. The comment is added in https://github.com/caskroom/homebrew-cask/pull/12915.

Before deciding would it be ok to merge without `uninstall` I've tried to automate the both of installation and uninstallation processes. However, I didn't find the necessary solution that would fit this case. Furthermore, at that moment there were quite many casks already that didn't have the necessary `uninstall` when using the same `installer :manual` technique. For example:
 - `adobe-creative-cloud.rb`
 - `backblaze.rb`
 - `default-folder-x.rb`
 - `fuze.rb`
 - `google-nik-collection.rb`
 - `little-snitch.rb`
 - `omnifocus-clip-o-tron.rb`
 - `ps3-media-server.rb`
 - `scout.rb`
 - `tuneup.rb`
 - `utorrent.rb`
 - `vlc-remote.rb`

So at that point I have decided, that holding up the cask indefinitely wouldn't be ok and was referencing those casks. I will change the tactic for this cases from now on.

**Comment by vitorgalvao** [comment]
> The comment is added in #12915.

Thank you. I’m currently without access to my computer on account of a broken charger, so I appreciate you making the change.

> However, I didn't find the necessary solution that would fit this case. 

Yeah, `installer :manual` is a pain.

> So at that point I have decided, that holding up the cask indefinitely wouldn't be ok and was referencing those casks. I will change the tactic for this cases from now on.

You know what? On second thought, don’t hold them up. You made a judgement on this cask based on other casks, and I’d say you’re correct. I was under the impression we had `uninstall` in all `installer :manual` casks, [but we don’t](https://github.com/caskroom/homebrew-cask/issues/6872). We should strive to not make that list bigger, but it is true that finding `uninstall`s for these is a pain, so yeah, use your best judgement in these cases.

And thank you again for all the work you’ve been doing; it has been great.

**Comment by Ngrd** [comment]
The problem of manual installation and uninstallation processes discussed here earlier was solved in https://github.com/caskroom/homebrew-cask/pull/13066.

**Pull request closed without merging**
