### PR TITLE
Added Signal.app v1.0.34

### PR DESCRIPTION
**Pull request by Shourai**
Open Whisper Systems just released their dedicated app for Signal.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by Shourai** [comment]
Nevermind, see https://github.com/caskroom/homebrew-cask/pull/40201.
Created ~10 minutes ago.

**Comment by 0xadada** [comment]
@Shourai doh, same thing just happened to me. i made the cask, and then saw the other PR.

**Comment by Shourai** [comment]
@0xadada haha, I know right!
Just when I thought I could add my first contribution.
Good to know how to do it for future apps :)

**Comment by 0xadada** [comment]
@Shourai this repo is alot more stringent about their code-quality and commit mechanics. Next time :)

**Pull request closed without merging**
