### PR TITLE
crystalfetch: new cask

### PR DESCRIPTION
**Pull request by gmerlino**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by gmerlino** [comment]
brew audit --new-cask did not work successfully, as can be seen from the following output:

audit for crystalfetch: failed
 - GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
crystalfetch
  * line 5, col 2: GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
Error: 1 problem in 1 cask detected.

However, I would raise my objection to the repo being "not notable enough": it is a (very recent) package coming from the maintainers of UTM, and albeit a standalone app, it is meant as "helper" utility for UTM users. Obviously, it does not meet "notability" requirements (yet), but it will in next to no time. And I don't see a reason to let (homebrew cask + UTM) users wait for these requirements to be met. As a suggestion, maybe this bar could be lowered a bit by looking not just at the notability of the single project/package, but that of the organization/owner, first.

**Comment by razvanazamfirei** [comment]
Hi @gmerlino! Thank you for opening this. It looks like the repo is under [TuringSoftware](https://github.com/TuringSoftware) and not [UTM](https://github.com/utmapp). I agree that it could qualify for an exception if it was affiliated with UTM but that doesn't seem to be the case. Could you confirm?

**Comment by gmerlino** [comment]
> Hi @gmerlino! Thank you for opening this. It looks like the repo is under [TuringSoftware](https://github.com/TuringSoftware) and not [UTM](https://github.com/utmapp). I agree that it could qualify for an exception if it was affiliated with UTM but that doesn't seem to be the case. Could you confirm?

UTM has a different (e.g., dedicated) organization, but TuringSoftware it's actually from the same developers, and indeed the welcome dialog in UTM with the changelog now mentions Crystalfetch as helper app for UTM itself.

I would then confirm that it definitely qualifies.

**Comment by razvanazamfirei** [comment]
This makes sense. I see it referenced [here](https://docs.getutm.app/guides/windows/) as well.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
