### PR TITLE
Add InteractiveBrokers Trader Workstation stable online token

### PR DESCRIPTION
**Pull request by xel-arjona**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by miccal** [comment]
See https://github.com/Homebrew/homebrew-cask/pull/85476#issuecomment-654556945 for an explanation of how this differs from [the version that is already available](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/trader-workstation.rb)

**Comment by ran-dall** [comment]
`install: 10 (30 days), 34 (90 days), 86 (365 days)`

I don't think we need another cask for this when the original one doesn't see much action as-is.

**Comment by ran-dall** [comment]
@vitorgalvao I'll leave this to your decision.

**Comment by vitorgalvao** [comment]
> I don't think we need another cask for this when the original one doesn't see much action as-is.

Agreed.

Thank you anyway for the submission.

**Pull request closed without merging**
