### PR TITLE
Update vmware-horizon-client from 2106-8.3.0-18251973,CART22FQ2 to 2106.1-8.3.1-18641314,CART22FQ2

### PR DESCRIPTION
**Pull request by silverbios**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
@bevanjkay I have not been successful with coming up with a suitable `livecheck` here, mind having a look?

**Comment by bevanjkay** [comment]
@miccal Just committed something that works, but I think realistically we just need to do a `skip` block here?

**Comment by miccal** [comment]
Wow, that is a nasty one!

**Comment by miccal** [comment]
@bevanjay I will leave it for you to decide what to do here, in regards to keeping your `livecheck` or just `skip`ping it.

Great work, though :)

**Comment by bevanjkay** [comment]
@miccal We can try it out for a bit and if it stops working I'll revert it to a `skip` instead. I've added to to the list I regularly run `livecheck` for.

**Pull request merged**
