### PR TITLE
Update firefox from 109.0.1 to 110.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — DISMISSED** [review]

**Comment by p-linnane** [comment]
This is timing out trying to audit all the language options as it usually does nowadays. I've verified it locally, so merging.

**Comment by bevanjkay** [comment]
@p-linnane It will need to run with `ci-syntax-only` before you can merge - do we have data on whether the alternative languages get used in the cask very often?

**Comment by p-linnane** [comment]
Looks like that's no longer possible since we have a required check, so back to https://github.com/Homebrew/homebrew-cask/labels/ci-retry we go.

**Comment by p-linnane** [comment]
I do not believe we have data on the languages. This only happens with `firefox` and `thunderbird`.

**Review by miccal — APPROVED** [review]

**Pull request merged**
