### PR TITLE
staged.rb: check if paths exists in set_permissions set_ownership

### PR DESCRIPTION
**Pull request by vitorgalvao**
Closes https://github.com/caskroom/homebrew-cask/issues/15769.

### CODE REVIEW

**Comment by adityadalal924** [comment]
Looks like Travis threw up all sorts of funky errors.

**Comment by vitorgalvao** [comment]
@adityadalal924 Yeah, I’ve tried a few things but couldn’t fix it. It‘s not passing tests, but I think it should. Will need @jawshooah’s help with this one.

**Comment by jawshooah** [comment]
On the road right now, will take a look when I get home.

**Comment by jawshooah** [comment]
Ah, the problem is that with your changes, we now issue a command to set the ownership or permissions of each file individually, rather than all at once.

Here's a better way:

```rb
full_paths = Array(paths).map { |p| Pathname(p).expand_path }.select(&:exist?)
@command.run!(...)
```

**Comment by vitorgalvao** [comment]
Ah, I see. I tried something similar (but still with more steps) where I created a new array and added to that, but it still failed to pass the tests (and was ugly as hell, to boot). Much better like this. Thank you.

Still failed locally, though, again not sure why. Lets see what Travis says.

**Comment by jawshooah** [comment]
Had to do some mocking magic, but I got the tests running. Here are [my changes](https://github.com/jawshooah/homebrew-cask/commit/daf4ca33ef7d53fe57a951355d8237a348a5f108).

**Comment by jawshooah** [comment]
Blargh, forgot about `preflight_test` and `uninstall_preflight_test`. I'm not a fan of all this duplication; going to see if there is something similar to RSpec's shared examples for MiniTest.

**Comment by jawshooah** [comment]
Got it working! [Here you go](https://github.com/caskroom/homebrew-cask/compare/master...jawshooah:caskroom-file-exists). @vitorgalvao feel free to rebase my branch onto yours and force-push to update the PR.

**Comment by vitorgalvao** [comment]
Stellar work. Thank you for working on it!

Closing this one in favour of https://github.com/caskroom/homebrew-cask/pull/16026.

**Pull request closed without merging**
