### PR TITLE
Update adobe-acrobat-pro to 18

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
i had a previous pull request for adobe acrobat pro 2018, which didn't have have the right download, sorry.

this one should work.

**Comment by core-code** [comment]
can someone give me a clue whats happening here? the 2 launchctl jobs that the CI bot is complaining about 
                         'Adobe_Genuine_Software_Integrity_Service',
                         'com.adobe.AAM.Startup-1.0',
are already listed for uninstallation so i am not sure why its still complaining

**Comment by adidalal** [comment]
Travis logs seem to be lost in the migration, mind doing something to trigger a rebuild?
Squishing commits should technically work.

**Comment by adidalal** [comment]
Mind triggering a rebuild, logs seem to have been lost in the migration.
A squish should do the trick.

Thanks!

**Comment by adidalal** [comment]
```
/Applications/Adobe Acrobat DC/
==> Purging files for version 18 of Cask adobe-acrobat-pro
>>> Leftover: launchjob_install
> Adobe_Genuine_Software_Integrity_Service
> com.adobe.AAM.Startup-1.0
```

Ref: https://travis-ci.org/Homebrew/homebrew-cask/builds/380762276

**Comment by core-code** [comment]
does no-one have a clue why the travis bot fails?

**Comment by core-code** [comment]
is there anything i can do to get this un-stuck?

**Comment by vitorgalvao** [comment]
We’ve had so many changes recently, I’m restarting the build on this one.

**Comment by vitorgalvao** [comment]
Pinging @reitermarkus @commitay 

```
>>> Leftover: launchjob_install
> Adobe_Genuine_Software_Integrity_Service
> com.adobe.AAM.Startup-1.0
```

It keeps complaining of `launchd` jobs that should have been taken care of. Apart from the fact this is Adobe we’re talking about (why would a PDF app need helpers and multiple launchd jobs), is there an explanation on why our side is having trouble with it?

**Comment by reitermarkus** [comment]
> this is Adobe we’re talking about

```
$ cat /Library/LaunchAgents/com.adobe.AAM.Updater-1.0.plist 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
 <dict>
  <key>Label</key>
  <string>com.adobe.AAM.Startup-1.0</string>
  <key>Program</key>
  <string>/Library/Application Support/Adobe/OOBE/PDApp/UWA/UpdaterStartupUtility</string>
  <key>ProgramArguments</key>
  <array>
   <string>/Library/Application Support/Adobe/OOBE/PDApp/UWA/UpdaterStartupUtility</string>
   <string>-mode=logon</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>LaunchOnlyOnce</key>
  <true/>
 </dict>
</plist>
```

Of course they name their file different than their service …

**Comment by vitorgalvao** [comment]
> [Fix Adobe's mistakes.](https://github.com/Homebrew/homebrew-cask/pull/47367/commits/8547ff08a664dee0e4fe4cc4de1dcd886bd975c2)

When I go the email for that, I was going to comment “if only it were that simple”. And then:

> [Seriously Adobe, deal it down with the launch jobs.](https://github.com/Homebrew/homebrew-cask/pull/47367/commits/6c257310a3f3980b58a49fbe30e2fdaa40e01f63)

That made me laugh.

**Comment by reitermarkus** [comment]
It was bound to happen that “Fix Adobe's mistakes.” wouldn't be the last commit. 😂

**Comment by vitorgalvao** [comment]
Finally merged. Thank you @reitermarkus.

**Pull request merged**
