### PR TITLE
Update Caprine.app to version 0.1.1

### PR DESCRIPTION
**Pull request by vinkla**

### CODE REVIEW

**Comment by victorpopkov** [comment]
Thank you for the contribution. It was merged directly as 99ae881830a0747ad3a4531b27abca149746b5ae to keep commit history cleaner. Your contribution is still credited to you.

**Comment by vinkla** [comment]
Just curious, how do you handle these kind of merges? Is it one of @vitorgalvao magical scripts?

**Comment by victorpopkov** [comment]
> Is it one of @vitorgalvao magical scripts?

Yes.

**Comment by vinkla** [comment]
Which one? `prfixmaster`?

**Comment by victorpopkov** [comment]
Nope, using [fastmerge](https://github.com/vitorgalvao/tiny-scripts/blob/master/fastmerge) for the quick merge. The [prfixmaster](https://github.com/vitorgalvao/tiny-scripts/blob/master/prfixmaster) is used when  some additional fixes are needed before making the commit.

**Comment by vinkla** [comment]
Cool, thanks!

**Pull request closed without merging**
