### PR TITLE
Update eagle to 8.4.3

### PR DESCRIPTION
**Pull request by kosma**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by kosma** [comment]
A note about download URL: the official EAGLE website still points to the old 8.4.1 download. However, after installation, an update window pops up immediately, pointing to: https://eagle-updates.circuits.io/downloads/latest.html. The old URL doesn't work for 8.4.3 unfortunately.

**Comment by commitay** [comment]
We'll have to wait until the homepage has the correct version.

This comment can only be added when the download link can be verified by visiting the homepage.

> circuits.io was verified as official when first introduced to the cask

**Comment by commitay** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/41414

**Comment by kosma** [comment]
Thanks for sorting this out! :) 👍

**Pull request closed without merging**
