### PR TITLE
Update audiogridder from 1.1.1 to 1.2.0

### PR DESCRIPTION
**Pull request by apohl79**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Are there no more arch specific downloads?

**Comment by apohl79** [comment]
No, all archs supported via universal binaries now.

**Comment by SMillerDev** [comment]
```
Signature verification failed:
Package "33d5258c3b4c91fbe5d3063c256c8c09db5c282da7e415f8232ab9af5df12aff--AudioGridderServer_1.2.0_macOS-universal.pkg":
   Status: no signature

macOS on ARM requires applications to be signed.
Please contact the upstream developer to let them know they should sign their package.
```

Could you request this upstream?

**Review by SMillerDev — DISMISSED** [review]

**Comment by apohl79** [comment]
> ```
> Signature verification failed:
> Package "33d5258c3b4c91fbe5d3063c256c8c09db5c282da7e415f8232ab9af5df12aff--AudioGridderServer_1.2.0_macOS-universal.pkg":
>    Status: no signature
> 
> macOS on ARM requires applications to be signed.
> Please contact the upstream developer to let them know they should sign their package.
> ```
> 
> Could you request this upstream?

Need to see if thats possible. It's an open source project w/o funding, as signing pkg's requires an apple developer subscription.

Cheers

**Comment by miccal** [comment]
Thank you @apohl79.

**Review by miccal — APPROVED** [review]

**Pull request merged**
