### PR TITLE
updated yate (3.12)

### PR DESCRIPTION
**Pull request by ghost**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by adidalal** [comment]
```
audit for yate: failed
 - download not possible: sha256 mismatch
Expected: 7ffc7ce3d342485b9631849c3e074eddbfc3f6f3f702944c18fcf071cfb16367
Actual: 4811c6a1acb948a4ee6453ff82883f05b82e43920f96cabae8cac015bfca4fe5
```

**Comment by adidalal** [comment]
Still can't get a consistent `shasum`, using either the dmg or zip

**Comment by vitorgalvao** [comment]
What about with `user_agent: :fake`?

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/pull/21529

**Pull request closed without merging**
