### PR TITLE
add red lang

### PR DESCRIPTION
**Pull request by rcqls**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This seems to be a CLI-only open-source tool. Please submit it first to [Homebrew](https://github.com/Homebrew/homebrew-core) and only if they don’t accept it, submit here (linking back to the pull request where it was refused).

This policy is documented in [faq/rejected_casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/caskroom/homebrew-cask/issues/15603), submit it first to [Homebrew](https://github.com/Homebrew/homebrew). If it is rejected there, you may then try again in Homebrew-Cask (link us to the issue on Homebrew so we can see their reasoning for rejection).

**Comment by rcqls** [comment]
Homebrew did not accept it because it is a binary and they only accept source based install. That's why we sent the pull request here.

**Comment by vitorgalvao** [comment]
I’ve made several fixes to the cask. Merging after Travis passes.

**Comment by rcqls** [comment]
Thanks for making simpler the cask!

**Comment by vitorgalvao** [comment]
I still think this belongs as a formula, and HB hasn’t yet refused this. As such, this is on hold.

**Comment by rcqls** [comment]
Thanks for your support!

**Comment by rcqls** [comment]
By the way, do you mean that you are waiting for the final decision of HB? It is clear in their answer that they do not want to accept the PR except if you manage to convince them.

**Comment by vitorgalvao** [comment]
I’d say they’re [waiting for your reply](https://github.com/Homebrew/homebrew-core/pull/7190#discussion_r89533664). Otherwise the PR would be closed.

**Comment by rcqls** [comment]
Ok! They expect an installation from source but it is just impossible. I told them that you thought this PR as a formula better than a cask.

**Comment by MikeMcQuaid** [comment]
> I still think this belongs as a formula, and HB hasn’t yet refused this.

I agree. For what it's worth we're unlikely to "refuse" it as much as we need it to be built from source. I think it could be (someone is building this from source at some stage, it's not just appearing like mana from heaven...) so it shouldn't go into Homebrew Cask. Up to you, though.

**Comment by rcqls** [comment]
Do you know that red does not rely on C but on Rebol which is not an open source project. The goal of red among other goals is to become an open source version of Rebol. As I already told you, one day it would be feasible when would depend only on red itself but it not the case now.

**Comment by MikeMcQuaid** [comment]
@rcqls That's fine. We could have the formula download Rebol and build it from source.

**Comment by rcqls** [comment]
Sorry! You do not remember my previous comments. With only Rebol it is not possible. You need Rebol SDK  and this is currently no more available on the Rebol Website you only can download Rebol but not Rebol SDK even if we accept to pay it. As you understand, the author of red has a license for that and provide red as a binary. Soon I hope, `red` could compile its source.  Do you understand me?

**Comment by rcqls** [comment]
@vitorgalvao What is your point? I am pretty sure it is impossible to compile red from source because it depends on product that you cannot distribute for free. However, even if this is possible, I still not understand why you could not share it as a cask above all when it is clearly easier to share it using binary. Why do you share R as a cask ? You can install it from source. Certainly because it is easier to share it as a binary using the wonderful job made by the R team. The author of red creates a language that is very easy to share because like lua it is very lightweight. His intention is to share it in the Homebrew world because he thinks HB is a very good tool and also HB users can be interested in red. 
It was not my intention to do these PR. I did it because the author is really busy and to send the PR you need a MacOSX. At the beginning, I told him that HB was not the right tool since it is so easy to install red as an executable. However, HB allows easy installation completing download and installing it at the right place. HB maybe can also help by promoting good tools...

**Comment by MikeMcQuaid** [comment]
> I am pretty sure it is impossible to compile red from source because it depends on product that you cannot distribute for free.

Ok; it doesn't sounds particularly open-source to me if you need paid software to produce a binary for it. Like, I can view the source and submit changes but I can't really do anything with it.

> Why do you share R as a cask ?

It provides a GUI.

**Comment by rcqls** [comment]
@MikeMcQuaid I am so sorry to be definitely not clear and I apologize for that.  However, I did not know it was so difficult to share a so simple tools wit HB or HB Cask. That's why I was not so clear. So to clarify:
* Red as an open source project want to replace rebol since rebol is not an open source project. In some sense, it was the origin of the project: become an open source version of Rebol2, like R was a replacement of S/Splus (not open source project). 
* As you can guess, Red shares a lot of syntax with its ancestor Rebol that's why the compiler was first written in Rebol (no need to reinvent the wheel). When Red is ready, the compiler will be written directly in Red and will be a self-contained open source project with a beautiful formula in HB. That's the goal of the author of Red. The difference with R is that is both an interpreted and compiled language.
*  As an open project, with the Rebol free binary (not the paid Rebol SDK not anymore provided), you can compile  and cross-compile any source Red file to create binary executable.
*  However, it is much  easier to compile Red source file with the red binary (`red-061`) that the author want to share here with Homebrew PR and Homebrew Cask. And like I mentioned before, he asks me to do it because it has a deep respect of what you did even if for job consideration he has to work mostly on Windows. The ONLY point is that from now, the ONLY way to provide this software is to use the paid Rebol SDK. The license of the Rebol SDK, allows to create this executable (`red-061` and soon `red-062`) that you can distribute for free (like Rebol) and it is a good news. It then simplifies a lot the Red world since users do not have to  download Rebol to create executables from Red source files. To use Red as a REPL, you can use `red-061`.  By the way, Rebol was only an interpreted language. Fortunately, since Red team works hard they can provide REPL based on GUI stuff but on windows at first. MacGUI is coming soon. These REPL based on GUI can be compiled with Rebol2. But do not confuse, you still can't compile Red source with these REPL based on GUI (in the Rebol2/View spirit). You really need `red-061` now. 

Now, @MikeMcQuaid , let me know if you still think that Red is not an open source project. 
By the way, I am only interested in open-source project (R, ruby, julia, crystal, nodejs,...). I was really interested longtime ago with Rebol but I clearly was disappointed that this language (like mathematica for example) was not an open source project and I just gave up with a lot of regret because it was really impressive. Now, thanks to Red's author I can appreciate this (powerful) language since its primarily goal was to be an open source replacement of Rebol (actually Rebol2) from the beginning. Of course there is another open source projects with the same goal (like Rebol3) but Red is very active and its roadmap is really impressive.

About the R GUI,  you mean that you can't compile it from source. So how do you create the GUI? Is it depending on some paid software and you can't create a Formula? Do you mean that R is not an open source project. Even RStudio can be compiled from source but it is for sure time consuming to recompile it.

Many thanks for taking time and paying attention on the Red open source project.

**Comment by vitorgalvao** [comment]
> Why do you share R as a cask ? You can install it from source. Certainly because it is easier to share it as a binary using the wonderful job made by the R team.

> About the R GUI, you mean that you can't compile it from source. So how do you create the GUI? Is it depending on some paid software and you can't create a Formula? Do you mean that R is not an open source project. Even RStudio can be compiled from source but it is for sure time consuming to recompile it.

There’re some assumptions there and a misunderstanding of the places of both HB and HBC, and how we work together. Let’s not go there, as it is mostly irrelevant to the issue at hand. You can check https://github.com/caskroom/homebrew-cask/issues/15603 if you so wish for most of the context and evolution of these policies.

> Many thanks for taking time and paying attention on the Red open source project.

I will also add that I thank you for your respect in this whole conversation. Many users in your position would’ve (unfortunately) already thrown a tantrum and started calling us names and insulting our methods, when we work this way for various reasons that evolved as both projects did.

@MikeMcQuaid I’m fine with whatever you prefer, here. We can either:

+ Refuse this as a cask and work on the formula starting now.
+ Accept it now as a cask, refuse it as a formula, and when red has matured to be able to compile itself, remove the cask and make it a formula.

**Comment by rcqls** [comment]
As I already told you before, thanks @vitorgalvao for your supports. I really appreciate the hard work from HB and now from HB Caskroom. Thanks for the link, I 'll read it carefully.  BTW, I can't see the point to fight in the context of open-source projects where people spend a lot of time for sharing a lot of tools and most of the time for free.

**Comment by MikeMcQuaid** [comment]
> Refuse this as a cask and work on the formula starting now.
> Accept it now as a cask, refuse it as a formula, and when red has matured to be able to compile itself, remove the cask and make it a formula.

Either seems fine to me, I don't have a strong preference. I personally would probably pass on Red for both until it can self-bootstrap but I don't have strong feelings.

**Comment by rcqls** [comment]
Thanks @MikeMcQuaid too! I am waiting your final decision and inform then Red team.

**Comment by adidalal** [comment]
I;m leaning towards putting it in HBC only for now. After it becomes self-compilable, we can remove it from HBC, add it to HB, and add it to migrations.json to facilitate a smooth transition.

**Review by adidalal — APPROVED** [review]

**Comment by rcqls** [comment]
@vitorgalvao, @adidalal  After reading the link about deduplication, I fully understand your point now. Since `brew search r-app` (for example) redirects to the cask, I think that `brew search red` would redirect too and this is a good news.

**Comment by MikeMcQuaid** [comment]
Seems reasonable to me too then 👍

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by tekknolagi** [comment]
@rcqls how can I get started using Red/view and the rest of the GUI tools?

**Comment by rcqls** [comment]
@tekknolagi if you want to get started using Red/View you have to wait for the 0.6.3 version of red coming within a couple of months. The last release 0.6.2 contains only the Windows GUI.  There is also a MacOS branch in the red repository with Red/View. Very soon, it will be integrated in the master branch. If you want more accurate information go to the red website or visit Gitter red rooms which are very good  to ask question to the Red team and many advanced users.

**Pull request merged**
