### PR TITLE
Update GHDL 0.35

### PR DESCRIPTION
**Pull request by sww1235**
Wasn't able to audit or check style due to editing purely via github.

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by sww1235** [comment]
The GHDL project changed to a github organization, thus I could not use cask-repair. 

I am not certain exactly how to add the artifact stanza correctly.

Also a question. This application does not seem to fit in homebrew casks, as it does not provide a .app, it just provides binary files. This seems like a better fit now for normal homebrew.

**Comment by commitay** [comment]
> This application does not seem to fit in homebrew casks, as it does not provide a .app, it just provides binary files. This seems like a better fit now for normal homebrew.

Agreed. 

@vitorgalvao Should we remove this?

**Comment by vitorgalvao** [comment]
> This seems like a better fit now for normal homebrew.

That is correct. The policy is documented in [faq/rejected_casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/caskroom/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If it is rejected there, you may then try again in Homebrew-Cask (link us to the issue on Homebrew so we can see their reasoning for rejection).

> The GHDL project changed to a github organization, thus I could not use cask-repair.

What do you mean? `cask-repair` doesn‘t care.

> Should we remove this?

Yes. @sww1235 Will you submit to Homebrew/core?

**Comment by sww1235** [comment]
I am working on submitting to homebrew/core, but I believe I have discovered the reason why this is in homebrew-casks in the first place. 

GHDL is written almost entirely in Ada, which requires a special compiler from GCC. There is no similar support for LLVM/clang as far as I can tell. 

I have submitted a discourse post asking for assistance on using a specific compiler, and will keep this pull request updated with any further info I find.

**Comment by commitay** [comment]
https://discourse.brew.sh/t/creating-new-formula-for-code-in-ada/2086

**Comment by commitay** [comment]
Adding ada to gcc is possible but it's kind of niche and would further complicate an already complex (and popular) formula.

Cask can install the binaries but installing includes and libs probably isn't something we want to do.

I think the best way forward would be for this to removed from Cask in favour of a third-party formula that can perform a complete install of upstreams pre-built tarball.

**Comment by vitorgalvao** [comment]
Fine with removal.

**Comment by sww1235** [comment]
Thank you for working on this. I understand that it doesn't necessarily fit under cask or will work in core.

**Pull request closed without merging**
