### PR TITLE
Update droplr from 5.6.2,235 to 5.7.2,425

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
```
Error: Some packages are still installed, add them to uninstall pkgutil:
com.droplr.droplr-mac
Error: Some applications are still running, add them to uninstall quit:
com.droplr.droplr-mac
Error: Build failed.
```

**Comment by core-code** [comment]
i think its fine now but its hard to say because travis is acting up - again.

**Comment by core-code** [comment]
```
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Droplr572-425.pkg”.)

==> Purging files for version 5.7.2,425 of Cask droplr

Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=runner USER=runner USERNAME=runner /usr/sbin/installer -pkg /usr/local/Caskroom/droplr/5.7.2,425/Droplr572-425.pkg -target / -verboseR` exited with 1. Here's the output:

```

i don't think there is anything we can do.

**Comment by ran-dall** [comment]
@core-code What's your suggestion in terms of what to do then with this cask? If it's broken, I would imagine removal would be the only thing to do.

**Comment by core-code** [comment]
i don't think its broken i believe its just travis acting up. but i am not sure.

@vitorgalvao any ideas here?

**Comment by ran-dall** [comment]
@core-code When I try to install directly, I get this error...

```shell
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=randall USER=randall USERNAME=randall /usr/sbin/installer -pkg /usr/local/Caskroom/droplr/5.7.2,425/Droplr572
-425.pkg -target /` exited with 1. Here's the output:                                                                                                                               
installer: Package name is Droplr                                                                                                                                                   
installer: Installing at base path /                                                                                                                                                
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
```

**Comment by core-code** [comment]
thanks @randall for trying that out! that sounds bad

@suschizu i wonder why use the PKG at all. we can use the URL from the appcast which contains app: https://files.droplr.com/apps/mac/Droplr-572.dmg

**Comment by suschizu** [comment]
thanks @core-code & @ran-dall  - yes that's a much better idea - I close this pull and open a new one :)

**Comment by vitorgalvao** [comment]
> i don't think its broken i believe its just travis acting up. but i am not sure.

I’m unsure how much of the blame lays with the CI providers VS our own CI checks (in general).

Certainly Catalina doesn’t help, as some things outright stop working because we can’t [cancel or allow](https://youtu.be/8CwoluNRSSc), but things like suggesting `launchctl` or `quit` entries already present in the cask might be on us (e.g. maybe after removing a cask we’re checking for remnants too soon).

**Pull request closed without merging**
