### PR TITLE
Upgrade slack to v1.1.3

### PR DESCRIPTION
**Pull request by scribblemaniac**

### CODE REVIEW

**Comment by Ngrd** [comment]
Thank you for the contribution! However, the download link also needs to be replaced including the new sha256 checksum.

**Comment by scribblemaniac** [comment]
Oops, missed that. I will fix in a minute.

**Comment by scribblemaniac** [comment]
Fixed.

**Comment by Ngrd** [comment]
Quick as usual, thank you! But for version 1.1.3 the sha256 checksum should be `9b87c38c17e124b8753a5a2310de4d820fd023c025e938bbb3eb8b2062589ec6`.

**Comment by scribblemaniac** [comment]
Why can't I get this right! :angry:

The checksum has been updated.

**Comment by Ngrd** [comment]
> Why can't I get this right! :angry:

Yes, sometimes this happens. Thanks for the all the patience in correcting everything. You are very quick as usual.

Thank you for the contribution. It was merged directly as d6e7981ffe1b76f206dc773296679998a8bc5190 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by scribblemaniac** [comment]
Thanks for catching the issues!

**Pull request closed without merging**
