### PR TITLE
calibrite-profiler 1.3.3

### PR DESCRIPTION
**Pull request by MTCoster**
Also add a comment to the cask to explain the original intent and prevent the same mistaken change from being made again.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

---

Depends on https://github.com/Homebrew/brew/pull/18488; there's no way currently to describe an exception as "prerelease or stable is fine" in `github_prerelease_allowlist.json`.

### CODE REVIEW

**Review by samford — COMMENTED** [review]
The [first-party download page](https://calibrite.com/us/software-downloads/) links to the newest release on GitHub, so we can check that without having to worry about the pre-release issue. It's currently pointing to 1.3.3 despite it being "pre-release" on GitHub (as expected). I pushed a commit to update the `livecheck` block accordingly.

I converted this to a draft until the related brew PR is done, so this won't get merged prematurely.

**Comment by MTCoster** [comment]
> The [first-party download page](https://calibrite.com/us/software-downloads/) links to the newest release on GitHub, so we can check that without having to worry about the pre-release issue. It's currently pointing to 1.3.3 despite it being "pre-release" on GitHub (as expected). I pushed a commit to update the `livecheck` block accordingly.

That works too! You can go ahead and rewrite history here to replace my original revert commit with yours if you like.

With this change I guess we no longer depend on https://github.com/Homebrew/brew/pull/18488, but there's a separate discussion going on over there anyway so they can be independent now.

**Comment by samford** [comment]
I'm not very knowledgeable about the prerelease allowlist behavior for casks but I updated this to use `all`, as that may allow us to move this forward in the interim time. Our cask maintainers will have to confirm whether this is the appropriate way to handle this particular situation (i.e., allowing versions that are "pre-release" on GitHub, as we're tracking the first-party download page in the `livecheck` block) but it seems to work.

**Comment by MTCoster** [comment]
> I'm not very knowledgeable about the prerelease allowlist behavior for casks but I updated this to use `all`, [...]

Is the exception actually needed? From what I understand, it's only used for `:github_*` livechecks.

**Comment by samford** [comment]
> Is the exception actually needed? From what I understand, it's only used for `:github_*` livechecks.

Yes, formulae/casks using a GitHub tag/release in the `url` are audited to make sure that the release isn't marked as "pre-release" on GitHub (the modified code in the brew PR relates to the audit). `github_prerelease_allowlist.json` is used to add an exception to avoid this audit failure. Without that addition, `brew audit` will fail with `v1.3.3 is a GitHub pre-release`. [You can test this locally by removing the added line from the allowlist file and running `brew audit --strict --online calibrite-profiler`.]

That audit doesn't interact with `livecheck` blocks (i.e., the `livecheck` block URL/strategy isn't a factor) and it's just a coincidence that formulae/casks using a GitHub release asset often use the `GithubLatest`/`GithubReleases` strategies to identify versions.

**Review by p-linnane — APPROVED** [review]
Makes sense to me. Thanks!

**Pull request merged**
