### PR TITLE
Update gurps-character-sheet to 4.11.0,4.11

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> Error: It seems the App source '/usr/local/Caskroom/gurps-character-sheet/4.11.0,4.11/gcs-4.11.0,4.11-mac/GURPS Character Sheet.app' is not there.

**Comment by brianmorton** [comment]
I guess I can take a few tries at fixing that...

**Comment by brianmorton** [comment]
although this build is now passing, I did notice there is a "Library" folder beside the app (both in the version before the update and in the new version) that doesn't seem to be moved/copied/whatever.

image

How would I address this?

**Comment by vitorgalvao** [comment]
> How would I address this?

[Like so](https://github.com/Homebrew/homebrew-cask/pull/48639/files#diff-9d3c0e8729cd5c33a8f10d6bc1d78180R11). We copy the entire outer directory.

**Pull request merged**
