### PR TITLE
Upgrade Isolator version to 4.99beta

### PR DESCRIPTION
**Pull request by RaoOfPhysics**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` left no offenses.

This is the first time I've taken a look at caskroom code, and I'm not sure how to follow the second and third steps. Since I edited the cask info manually (the URL for `appcast` needed to be updated), I don't know how to go about testing that the cask has worked.

If someone can verify that the code works and -- even better -- can show me how to test it before my next PR, that would be great!

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Testing it is pretty easy. You just run those commands.

You run `brew cask audit --download <path_to_your_modified_cask>` and `brew cask style --fix <path_to_your_modified_cask>`. Those commands will take care of everything, and warn you of mistakes.

**Comment by RaoOfPhysics** [comment]
@vitorgalvao: Thanks! I presume the path refers to a URL?

**Comment by vitorgalvao** [comment]
> I presume the path refers to a URL?

No, it’s the file path to your modified `isolator.rb` (or whatever cask) file.

Also, for these small fixes, might as well run [`cask-repair`](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair). It can at once update the cask’s version (according to what you give it) taking care of updating both the cask’s `sha256` and the appcast’s `:checkpoint`, while still giving you the chance to perform other manual fixes.

You can easily install it with `brew install vitorgalvao/tiny-scripts/cask-repair`. `cask-repair --help` will show you some options, but as a whole the script will guide you through the update process.

**Comment by vitorgalvao** [comment]
This cask is actually updating to a beta, but it shouldn’t. Betas belong in [caskroom/versions](https://github.com/caskroom/homebrew-versions). The `appcast` should remain the old one, and the version changed to the stable `4.4`.

**Comment by RaoOfPhysics** [comment]
> This cask is actually updating to a beta, but it shouldn’t. Betas belong in caskroom/versions. The `appcast` should remain the old one, and the version changed to the stable `4.4`.

Hmm. The cask had previously pointed to `4.9beta` so I presumed I should continue on this track. The website also links to the beta: http://willmore.eu/software/isolator/ Let me know if I should change it, and I'll push a commit with the updates.

**Comment by vitorgalvao** [comment]
> The website also links to the beta: http://willmore.eu/software/isolator/

Ah, it’s fine then. See [Finding a Home For Your Cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) when in doubt. Here, the [But There Is No Stable Version!](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version) rule applies (emphasis added):

> When an App is only available as beta, development, or unstable versions, **or in cases where such a version is the general standard**, then said version can go into the main repo.

Since they are recommending the beta, that can be considered the standard.

**Pull request merged**
