### PR TITLE
Update SwitchResX from version 4.11.1 to 4.11.2

### PR DESCRIPTION
**Pull request by cpolish**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

As per website patch notes: https://www.madrau.com/srx_download/srx_download/history.php

### CODE REVIEW

**Comment by bevanjkay** [comment]
@cpolish We will need to wait until upstream update their side of things to show `4.11.2` as the latest version.
https://www.madrau.com/srx_download/download.html

**Comment by cpolish** [comment]
No problem

**Comment by bevanjkay** [comment]
@cpolish Can you please revert your last commit with the comment, and while you're there `strategy :page_match` is the standard livecheck strategy, so that line can be removed.

For future reference, please open PRs from a created branch on your fork (not your master branch), as maintainers are not able to push commits to the PR.

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/111318.

**Pull request closed without merging**
