### PR TITLE
removed gqrx.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
Can’t find a download link for the newest version on the [homepage](http://gqrx.dk/) and it uses a download url from a different host than the homepage. OS X downloads point to macports. Unless someone can point to where the direct download url lives, we should remove this.

### CODE REVIEW

**Comment by ndr-qef** [comment]
Vendor linked the sourceforge.net page in a [release log](http://gqrx.dk/news/gqrx-2-3-0-released).

**Comment by vitorgalvao** [comment]
> The source code is available through Github or Sourceforge. Ubuntu packages for Trusty and Utopic are in the PPA. Mac version is expected to be available through Macports soon.

That only links to the source, though, not the actual package (the current link doesn’t work).

**Comment by ndr-qef** [comment]
In the process of updating the cask to the current version, I realized that, indeed, the latest release is not prepackaged for Mac. The current `url` remains valid, but sourceforge.net appears to have been discontinued as a download provider. Should we consider that ground for removal?

**Comment by vitorgalvao** [comment]
I believe we should. Having a permanently old version while new versions are released is worse then it having been discontinued officially. I’ll reopen so you can merge if you agree.

**Comment by ndr-qef** [comment]
In principle, I agree. Qualifying casks as “latest release obtainable via our download mechanism”, while tempting, would arguably be a disservice.

**Pull request merged**
