### PR TITLE
Add caveat to OverSight to warn user about #32364

### PR DESCRIPTION
**Pull request by SConaway**
Add caveat to OverSight to warn user about #32364

### CODE REVIEW

**Comment by vitorgalvao** [comment]
I’d prefer if someone contacted upstream first to enquire about this.

**Comment by SConaway** [comment]
Done. I'll keep this issue posted.

**Comment by SConaway** [comment]
No response from upstream yet.

**Comment by vitorgalvao** [comment]
Let’s merge. Please let us know if upstream replies.

**Comment by SConaway** [comment]
No response yet, again. I'll try contacting again.

**Pull request merged**
