### PR TITLE
Delete perian.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
Refs https://github.com/caskroom/homebrew-cask/pull/17150.

### CODE REVIEW

**Comment by adidalal** [comment]
There is also another  perian that needs to be deleted

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/17169 (easier to do via web interface).

**Comment by adidalal** [comment]
:+1:

**Comment by adidalal** [comment]
Merged as 095ee6abb829ca678a747dd4f5254287e608419d.

**Pull request closed without merging**
