### PR TITLE
travis.yml: xcode9.3

### PR DESCRIPTION
**Pull request by commitay**
XCode 9.3 is on 10.13.

Casks with kexts will fail to install.

### CODE REVIEW

**Comment by commitay** [comment]
I was thinking of adding something to skip the install / uninstall step for Casks with kexts so the CI build doesn't always fail, but that would mean that we wouldn't be checking if the `install` is valid.

**Comment by commitay** [comment]
Opened an issue with Travis CI about disabling `kext-consent` for the 10.13 image.

https://github.com/travis-ci/travis-ci/issues/9377

**Comment by commitay** [comment]
@TravisBuddy stop

**Comment by commitay** [comment]
The Xcode 9.3 / 10.13 image has been released.
http://blog.travis-ci.com/2018-04-09-say-bonjour-to-xcode-93-and-macos-high-sierra

`kext-consent` is enabled.

**Comment by commitay** [comment]
@vitorgalvao I'm leaning towards merging this so don't have to manually check urls and checksums of Casks with conditionals or depends_on high_sierra. We'll still get a failed install for Casks with kexts so we'll know the install is valid at least.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
