### PR TITLE
texmacs 2.1.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by krehel — APPROVED** [review]

**Comment by ProfFan** [comment]
This broke `texmacs`:

```
==> Upgrading 1 outdated package:
texmacs 2.1.2 -> 2.1.4
==> Upgrading texmacs
==> Downloading https://ftp.texmacs.org/TeXmacs/tmftp/macos/TeXmacs-2.1.4-arm.dmg
######################################################################################################################################################### 100.0%
==> Purging files for version 2.1.4 of Cask texmacs
Error: texmacs: SHA256 mismatch
Expected: baf36986247c8df2b7301a47f773eba9556e36235d2bac062e68405e65316bff
  Actual: 71bd118626d78adaaeeb06bbe083b5e2702a5b1db433531b93d3d2211d229171
```

**Comment by krehel** [comment]
Sorry, but this was upstream changing the package long after this commit.  The question is - why did upstream re-release the package 9 days after this was committed?
texmacs-2 1 4

**Comment by ProfFan** [comment]
I don't know, let me try ask Joris on the mailing list

**Comment by krehel** [comment]
Thanks @ProfFan - appreciate that.  Heightened security these days when checksums change post-CI and merge.

**Comment by ProfFan** [comment]
The previously bumped package seems to be Joris uploading a test version to the FTP. 2.1.4 is not released until today.

https://lists.texmacs.org/wws/arc/texmacs-users/2024-04/msg00001.html

**Comment by krehel** [comment]
Thanks ProfFan!  I'll patch this up.

**Pull request merged**
