### PR TITLE
Add new Cask: hypercli

### PR DESCRIPTION
**Pull request by carmark**

### CODE REVIEW

**Comment by adidalal** [comment]
Where's the download link on the homepage?

I only see a "private beta"

**Comment by carmark** [comment]
@adidalal Thanks for your review.

The download link is in the [page](https://doc.hyper.sh/GettingStarted/install.html).

**Comment by vitorgalvao** [comment]
@carmark Are you in charge of that page? Because `brew upgrade` is absolutely unnecessary, there.

**Comment by carmark** [comment]
@vitorgalvao 

Thanks for your point this, I have updated the source of page, but it may talk a while to show the modification.

**Comment by adidalal** [comment]
For uninstall, shouldn't `opt/bin/static` and all subdirectories also get removed? Please add that / change uninstall accordingly

**Comment by vitorgalvao** [comment]
Also, for s complete `uninstall`, I’m guessing we could at least get a `pkgutil:`. We have [scripts](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md) to make as complete as possible.

**Comment by adidalal** [comment]
Package ID: `sh.hyper.hyper`

**Comment by adidalal** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 5dbd1136ebaa4ab9a5c2902f3fae0bbf9760771c. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
