### PR TITLE
fonts: remove all `desc` stanzas

### PR DESCRIPTION
**Pull request by miccal**
Since we do not require a `desc` stanza for fonts, and in the spirit of consistency, I propose we remove them all.

See https://github.com/Homebrew/homebrew-cask/pull/174976 for more context.

Note that there are currently 2,265 font Casks, and only these 585 currently have a `desc` stanza.

### CODE REVIEW

**Comment by SMillerDev** [comment]
I would argue the opposite: for consistency all casks should have a description including fonts. 

I don't really see a benefit in fonts not having one.

**Comment by bevanjkay** [comment]
Descriptions aren't often useful for fonts would be my additional thought here.

"Geometric sans-serif font" - doesn't say much.
Outside of these kind of descriptions it's mainly marketing blah blah.

**Comment by p-linnane** [comment]
I'm fine with removing these for the reasons stated above.

**Review by p-linnane — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @p-linnane.

**Pull request merged**
