### PR TITLE
orion 0.99,126.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@chenrui333 This needs to have the shasum values updated for each `on_{os}` block. You can check by doing `brew fetch --os=high_sierra` or `brew audit --online --os=high_sierra` etc...

**Comment by chenrui333** [comment]
> @chenrui333 This needs to have the shasum values updated for each `on_{os}` block. You can check by doing `brew fetch --os=high_sierra` or `brew audit --online --os=high_sierra` etc...

sorry about that, that looks like an opportunity on the `brew bump --open-pr` command

**Comment by chenrui333** [comment]
I think using CI to correct the shasum might be OK as well (although it has some delay)

**Comment by bevanjkay** [comment]
@chenrui333 I don't think CI checks the lower branches

**Comment by chenrui333** [comment]
oh, I see your point, updating them now

**Comment by chenrui333** [comment]
should be good now

**Review by bevanjkay — APPROVED** [review]

**Comment by chenrui333** [comment]
might also good to add `brew fetch --os=high_sierra` or `brew audit --online --os=high_sierra` checks in CI (if cask has the `on_ high_sierra` block), I will think about it.

**Pull request merged**
