### PR TITLE
Add pensela

### PR DESCRIPTION
**Pull request by connorads**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@connorads Thanks for your submission.
Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

**Comment by connorads** [comment]
Hey @bevanjkay

I tried creating a zap stanza but I haven't actually run this app and I presume settings files would be created at runtime 🤔
```
brew createzap pensela
No pensela settings found.
```

It's not my Macbook so I don't want to install unsigned software.
I'm just adding it to brew for fun 😅
image

**Comment by bevanjkay** [comment]
> It's not my Macbook so I don't want to install unsigned software. I'm just adding it to brew for fun 😅 image

Generally, we would want the contributor submitting the cask to be an active user of the application. Ensuring we get an accurate `zap` stanza is one of the reasons for this. Because it's far from ideal for maintainers to install every submitted app to create the zaps.

**Comment by connorads** [comment]
I've asked [here](https://github.com/weiameili/Pensela/pull/16#issuecomment-939276334).

**Comment by naveenkrdy** [comment]
here you go
```
zap trash: [
  "~/Library/Application Support/pensela",
  "~/Library/Preferences/com.wali.Pensela.plist",
  "~/Library/Saved Application State/com.wali.Pensela.savedState",
]
```

**Pull request merged**
