### PR TITLE
Fix for #14298

### PR DESCRIPTION
**Pull request by bdhess**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Wouldn’t it make more sense to put both under the same conditional?

**Comment by bdhess** [comment]
Cool-- didn't realize that nested arrays were allowed.

**Comment by vitorgalvao** [comment]
Have you confirmed it still works correctly, though? I don’t have my computer, so I can’t.

Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by bdhess** [comment]
Yup, I've confirmed that it works correctly.
Commits squashed.

**Comment by vitorgalvao** [comment]
Thank you for your work.

**Pull request merged**
