### PR TITLE
Update opencore-configurator from 2.31.0.0 to 2.32.0.0

### PR DESCRIPTION
**Pull request by i0ntempest**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by Misaka13514** [comment]
hmmm.... my installation failed

**Comment by i0ntempest** [comment]
Probably more download protection crap.

**Comment by miccal** [comment]
It appears that `curl` requests are being thwarted:
```
|-> curl -sLI https://mackie100projects.altervista.org/apps/opencoreconf/download-new-build.php?version=last
HTTP/2 302 
date: Thu, 01 Apr 2021 14:31:31 GMT
content-type: text/html; charset=UTF-8
set-cookie: __cfduid=d987ef18cd43aaa9ca1ca7a35502a09921617287490; expires=Sat, 01-May-21 14:31:30 GMT; path=/; domain=.mackie100projects.altervista.org; HttpOnly; SameSite=Lax
cache-control: no-cache, must-revalidate
expires: Sat, 26 Jul 1997 05:00:00 GMT
location: http://mackie100projects.altervista.org/download-opencore-configurator/
cf-cache-status: DYNAMIC
cf-request-id: 092f71c41c0000e9bf94922000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=Myt7T73ebcRRLyWcR0vHnQiPlp6vqkGaJ8G8bslGT9%2Bp2wAri6HzUFPWaqPibt%2FUroAmVrKOgt3M44hqDAiRsfmrjWPrIoAp%2Fi%2FPYgtgi83mxMYSJXrKxOGvUtpAGSE2qA%3D%3D"}],"max_age":604800,"group":"cf-nel"}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 639285802f93e9bf-BNE
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400

HTTP/1.1 301 Moved Permanently
Date: Thu, 01 Apr 2021 14:31:31 GMT
Content-Type: text/html; charset=iso-8859-1
Connection: keep-alive
Set-Cookie: __cfduid=dd2c801ef44fee4c01ceff71279c18c671617287491; expires=Sat, 01-May-21 14:31:31 GMT; path=/; domain=.mackie100projects.altervista.org; HttpOnly; SameSite=Lax
Location: https://mackie100projects.altervista.org/download-opencore-configurator/
CF-Cache-Status: DYNAMIC
cf-request-id: 092f71c735000032a1413a1000000001
Report-To: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=ALdwGGugglUY7nY9aBYgBAHNTBzXhvfA%2BA9OjD6nerSZhgZw5pW9sXsC%2FHA2233y1lqU4Nhx6YRIBzl6P7Bv1TNMJ6QalQyw6JRToWbDY5TAVw4Jhn3xeu9iBg01TqBPug%3D%3D"}]}
NEL: {"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 639285852afc32a1-BNE
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400

HTTP/2 200 
date: Thu, 01 Apr 2021 14:31:33 GMT
content-type: text/html; charset=UTF-8
set-cookie: __cfduid=d446664cf86a211e260f4162536e039811617287492; expires=Sat, 01-May-21 14:31:32 GMT; path=/; domain=.mackie100projects.altervista.org; HttpOnly; SameSite=Lax
content-security-policy: upgrade-insecure-requests
av-custom-post-type: page
link: <https://mackie100projects.altervista.org/wp-json/>; rel="https://api.w.org/"
link: <https://mackie100projects.altervista.org/wp-json/wp/v2/pages/819>; rel="alternate"; type="application/json"
link: <https://mackie100projects.altervista.org/?p=819>; rel=shortlink
vary: Accept-Encoding
cf-cache-status: DYNAMIC
cf-request-id: 092f71ca1c0000e9bf5bb4e000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=GTy4N4TNpBSJ7XhUFNQ%2BWFcNUtYW6nH%2FGd95TlD2oq1taDnNgnOr5uAokqBRKSvpihpcbJguaEvtj1TnzkMqK8Ooq3x9RhKshfKxVyv3yRZ2%2FyUrTFU84blxI3iAxJmD1g%3D%3D"}],"max_age":604800,"group":"cf-nel"}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 63928589cd00e9bf-BNE
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
```

**Review by reitermarkus — APPROVED** [review]

**Pull request merged**
