### PR TITLE
Add Yandex.Music Control v1.0.4

### PR DESCRIPTION
**Pull request by Ty3uK**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars)).

**Comment by Ty3uK** [comment]
@vitorgalvao Okay, but is the number of stars really the right metric to measure the program? Maybe [the number of downloads](https://www.somsubhra.com/github-release-stats/?username=Ty3uK&repository=YMC) is a better metric?

**Comment by vitorgalvao** [comment]
> but is the number of stars really the right metric to measure the program?

It’s *a* metric. We also care for number of downloads, but downloads through us.

Either way this is self-submitted, which represents your desire to have it as a cask, not the users’ desire.

**Comment by Ty3uK** [comment]
@vitorgalvao so if any other guy submit my program, everything's gonna be okay? That's strange, isn't it?

**Comment by vitorgalvao** [comment]
> so if any other guy submit my program, everything's gonna be okay?

No, because it still didn’t pass the 50 stars threshold. Why do you keep ignoring the rule that doesn’t suit your argument? You’ve done that to both of them, now.

> That's strange, isn't it?

No, it isn’t strange. If you couldn’t even get a user to submit your app for you, that would be representative of its lack of popularity amongst HBC users.

I’m not going to spend any more time on this. It’s not a perfect rule, it’s a *guideline*. I’m using it as a guide to make a decision. This has been in place for a long time, and on HB before that. If you wish to change it, I’d recommend you first read the issues where it was discussed, and offer reasoned alternatives. But it has served us well so far, so we’re unlikely to do so.

**Pull request closed without merging**
