### PR TITLE
Update zoomus 4.0.36452.0616 - sha256

### PR DESCRIPTION
**Pull request by modulusx**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t][version-checksum],  
      provide public confirmation by the developer: {{link}}

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by gobinathm** [comment]
[VirusTotal](https://www.virustotal.com/) seems to provide some concerning information about this update. I might be wrong, but need verification

**Comment by commitay** [comment]
`pkg` is signed but seems to have bundled malware. 
> https://www.virustotal.com/en/file/1a2128812a01dfbbc0b932461daa49a3ca6f7efcbc50b0916f7cabebece4a6d8/analysis/1500328763/

```
pkgutil --check-signature zoomus--4.0.36452.0616.pkg
Package "zoomus--4.0.36452.0616.pkg":
   Status: signed by a certificate trusted by Mac OS X
   Certificate Chain:
    1. Developer ID Installer: Zoom Video Communications, Inc. (BJ4HAAB9B3)
       SHA1 fingerprint: 0F 67 41 1B BA 55 79 0B 19 01 50 2C 09 E7 41 C2 A7 5C 7C B8
       -----------------------------------------------------------------------------
    2. Developer ID Certification Authority
       SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
       -----------------------------------------------------------------------------
    3. Apple Root CA
       SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
```

**Comment by commitay** [comment]
I've opened a support ticket with upstream.

**Comment by vitorgalvao** [comment]
Note that, either way, this PR is wrong. The actual sha256 is `1a2128812a01dfbbc0b932461daa49a3ca6f7efcbc50b0916f7cabebece4a6d8` (see VirusTotal).

`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` (the sha256 in this PR) is the sha256 for an empty string (we even check for it in multiple places in our `audit`).

**Comment by commitay** [comment]
Whoops, didn't notice that! I'll open a new PR. Thanks @vitorgalvao!


https://github.com/caskroom/homebrew-cask/pull/36692

**Pull request closed without merging**
