### PR TITLE
Update murus.rb zaps

### PR DESCRIPTION
**Pull request by daylightbrightledlight**
Fixes caskroom/homebrew-cask#37725

### CODE REVIEW

**Comment by daylightbrightledlight** [comment]
I have found more files in `/private/etc/murus/`.

**Comment by vitorgalvao** [comment]
@danielbayley Please make a PR or open a new issue.

**Comment by danielbayley** [comment]
@vitorgalvao Wrong @ I think…

**Comment by vitorgalvao** [comment]
@danielbayley It was. Apologies. Github’s @mention is usually so spot-on I didn’t even check.

**Pull request merged**
