### PR TITLE
Update cloudfoundry-cli to v6.15.0

### PR DESCRIPTION
**Pull request by squid314**
https://github.com/cloudfoundry/cli/releases

### CODE REVIEW

**Comment by vitorgalvao** [comment]
`pkg` will need to change as well, or the cask will break.

**Comment by vitorgalvao** [comment]
Thank you. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by vitorgalvao** [comment]
Please @mention me after you do, so I get an email to check back.

**Comment by squid314** [comment]
@vitorgalvao, just squashed. Thanks for the guidance.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 08d50156047efa77380a0943c6ed2a9ced656f5b to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
