### PR TITLE
Create a cask for Zeplin

### PR DESCRIPTION
**Pull request by nicolas-brousse**
I create a new cask for [Zeplin](https://zeplin.io/) app.

### CODE REVIEW

**Comment by scribblemaniac** [comment]
I don't think we will be able to accept this cask. The download appears to be walled and the download hostname differs from that of the homepage. Because of this, we are unable to verify the authenticity of the download link you have provided.

**Comment by vitorgalvao** [comment]
@nicolas-brousse See [this](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#unofficial-vendorless-and-walled-builds). It gives reasonings as to why we cannot accept the cask here, and an alternative repo where you can submit it.

**Comment by nicolas-brousse** [comment]
@vitorgalvao Okay I understand. I will contact them to have more information. Else I will publish it in `homebrew-unofficial`.

**Comment by guerrero** [comment]
@nicolas-brousse any news?

**Comment by adityadalal924** [comment]
@vitorgalvao Should be okay to add now. I see the download link at https://zeplin.io/support.html

**Comment by vitorgalvao** [comment]
Looks like we can do it, yes.

**Comment by nicolas-brousse** [comment]
@adityadalal924 I only saw the link for the Sketch plugin

**Comment by adityadalal924** [comment]
@nicolas-brousse See FAQ > 2. Where can I download the app?

**Comment by guerrero** [comment]
Great! Can I help in some way? It seems that #13841 is best suited for this purpose because it sets the license to `:freemium`.

**Comment by adityadalal924** [comment]
It would be best to make a new PR, with the added comment above the url (because the host names differ). Check out contributing.md for details

**Comment by guerrero** [comment]
@adityadalal924 done #15676, thanks for your support :)

**Pull request closed without merging**
