### PR TITLE
Update chromedriver from 97.0.4692.71 to 98.0.4758.48

### PR DESCRIPTION
**Pull request by natashadowse**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by natashadowse** [comment]
Hmm it looks like the `LATEST_RELEASE` path for the chromedriver api hasn't been updated for 98 - https://chromedriver.storage.googleapis.com/LATEST_RELEASE_98 has the latest version `98.0.4758.48`

**Comment by miccal** [comment]
Thank you @natashadowse but this version corresponds to the beta release, which is available from the `homebrew-cask-versions` repository.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask-versions/pull/13213

**Comment by natashadowse** [comment]
Ah thank you @miccal! I hadn't seen anything indicating it was beta & the chrome 98 version is stable so it hadn't occurred to me that the related chrome driver version would still be in Beta! Thanks :)

**Pull request closed without merging**
