### PR TITLE
Enable auto_updates for toggl-track

### PR DESCRIPTION
**Pull request by atreides322**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Review by reitermarkus — APPROVED** [review]

**Comment by atreides322** [comment]
I am unsure why CI/test is failing. I checked `brew cask audit toggl-track` before I committed and the test is still passing locally. There were not changes to the version number.

**Comment by reitermarkus** [comment]
Should be fixed when https://github.com/Homebrew/brew/pull/8713 is merged.

**Comment by reitermarkus** [comment]
CI runs `brew cask audit toggl-track --online`, which includes additional checks requiring a network connection.

**Comment by atreides322** [comment]
Oh! Thank you for the additional information.

**Pull request merged**
