### PR TITLE
Update fl-studio to 20.0.99.123

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> pkg source file not found: 'Install FL Studio.pkg'

**Comment by ran-dall** [comment]
@vitorgalvao Is there a reason we are removing the version? On the original download, it's part of the name.

**Comment by vitorgalvao** [comment]
> Is there a reason we are removing the version?

They don’t belong in `name`.

**Comment by core-code** [comment]
this is a beta version. please don't submit or merge beta versions. i've sent a PR to revert to stable: https://github.com/Homebrew/homebrew-cask/pull/55891

(hint: things with 99 in the version number are often betas, but even if there is no 99, the official download site needs to be checked in any case before submitting any PR)

**Pull request merged**
