### PR TITLE
Add miniforge

### LINKED ISSUE #93: Homebrew installer
It would be awesome if there were a Formula for homebrew so one can just run `brew install --cask miniforge` just like one can do `brew install --cask miniconda`.

### PR DESCRIPTION
**Pull request by domoritz**
Add https://github.com/conda-forge/miniforge. For now, only supports x86_64 because of https://github.com/Homebrew/homebrew-cask/issues/95776. 

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

Fixes https://github.com/conda-forge/miniforge/issues/93

### CODE REVIEW

**Comment by miccal** [comment]
Would this not conflict with [`miniconda`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/miniconda.rb), since they both install a binary called `conda`?

**Comment by domoritz** [comment]
It would, yes. People should install only one or the other. How do we indicate this potential conflict?

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @domoritz.

**Review by miccal — APPROVED** [review]

**Comment by domoritz** [comment]
Thank you for updating the formula.

**Pull request merged**
