### PR TITLE
Add eduVPN 1.1

### PR DESCRIPTION
**Pull request by bric3**
eduVPN formula was missing

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by 404NetworkError** [comment]
@bric3 According to this repo's [documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/all_stanzas.md#required-stanzas), you are missing the required`name` stanza.
Here are my suggestions for stanzas you should probably add: 
`name 'eduVPN'`
`appcast: 'https://raw.githubusercontent.com/eduvpn/macos/master/ChangeLog.md'`
`depends_on: '>= :sierra'`

**Comment by bric3** [comment]
@404NetworkError Thanks I will update the formula with your suggestions.

@vitorgalvao Indeed the project is quite young. What is the option, create a tap ?

**Comment by vitorgalvao** [comment]
> the github project is not an indicator of the obscurity of the app, it can be used well enough without users having to know about about the repo.

That is quite true. And it also happens that apps that I think are obscure have no repo to check for. The problem is we need *something* to use as a rule. Something users can check before making a submission and that we can apply consistently. We’re not robots and may sometimes decide to apply the rule differently either way, depending on the circumstance, but doing it exclusively on the basis of a maintainers opinion is not a strong method.

This is something I’ve briefly discussed with another maintainer recently. I’m open to new suggestions.

> Anyway what is the option, create a tap ?

For now, yes. You can also wait for it to get the 50 stars, or have the tap now and even resubmit here after the 50 stars are achieved.

**Comment by bric3** [comment]
@vitorgalvao That makes sense. I'll see with the authors first if they want to create a tap first.

@404NetworkError My new commits don't show up here, probably because this PR has been closed, anyway that's here https://github.com/bric3/homebrew-cask/tree/add-edu-vpn-11-formula

**Pull request closed without merging**
