### PR TITLE
Update auristor-client from 0.195 to 0.197.1

### PR DESCRIPTION
**Pull request by core-code**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
other SHAs not yet updated

**Comment by core-code** [comment]
i've removed sierra because it doesn't seem to exist anymore

**Comment by core-code** [comment]
i am unsure about this

```
  if MacOS.version <= :high_sierra
    pkg "Auristor-Lite.pkg"
  elsif MacOS.version <= :mojave
    pkg "Auristor-Lite.pkg"
  elsif MacOS.version <= :catalina
    pkg "Auristor-Lite.pkg"
  else
    pkg "Auristor.pkg"
  end
```

seems like the 'else' branch will actually never run, no?

**Comment by reitermarkus** [comment]
> seems like the 'else' branch will actually never run, no?

Theoretically it will run on `:big_sur`, not sure if that's right though.

**Comment by core-code** [comment]
> Theoretically it will run on `:big_sur`, not sure if that's right though.

nah, the 'depends_on macos' excludes that

**Review by reitermarkus — APPROVED** [review]

**Pull request merged**
