### PR TITLE
Add SoundflowerBed 2.0.0

### PR DESCRIPTION
**Pull request by kirb**
#### Adding a new cask
- [X] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [X] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [X] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [X] Commit message includes cask’s name.
- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` left no offenses.
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.

---

Soundflower, after being abandoned and [picked up](https://github.com/mattingalls/Soundflower) by someone else, no longer includes Soundflowerbed, a menu bar app for quick configuration of Soundflower. It has similarly been [picked up](https://github.com/mLupine/SoundflowerBed) by someone else, now with a capital B.

### CODE REVIEW

**Comment by adidalal** [comment]
Would you mind adding an appcast?

https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

**Comment by kirb** [comment]
Presumably using the GitHub releases feed? I don’t think there’s a proper appcast.

**Comment by adidalal** [comment]
Yep

**Comment by kirb** [comment]
Done.

**Comment by adidalal** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 4746f3968393f8a79677d7ba5a79d2ea2cfd6572. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by kirb** [comment]
No worries, cheers!

**Pull request closed without merging**
