### PR TITLE
Add pixelorama v0.8.1

### PR DESCRIPTION
**Pull request by karbassi**
**NOTE:** There is nothing to uninstall other than the app. No need to `zap` or `uninstall`.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md). See [`homebrew-createzap`](https://github.com/nrlquaker/homebrew-createzap) for an external project which can help.

**Review by vitorgalvao — APPROVED** [review]

**Comment by karbassi** [comment]
@vitorgalvao Thanks. Updated.

Is there a list of tools that I can use to create casks easier? I just learned about homebrew-createzap and know about vitorgalvao/tiny-scripts. 

I'm creating my casks by hand and following the main docs. It would be amazing to automate tasks as much as possible.

**Comment by vitorgalvao** [comment]
`brew cask create`, I guess.

**Review by vitorgalvao — APPROVED** [review]

**Comment by karbassi** [comment]
> `brew cask create`, I guess.

That's what I use. It would be great to have some a generator, tbh.

**Comment by vitorgalvao** [comment]
> It would be great to have some a generator, tbh.

That is a generator. Anything more particular than that would be super complicated and need to handle a bunch of edge cases. I don’t think that’s at all a priority. You’re unlikely to see something like that first-party anytime soon.

**Pull request merged**
