### PR TITLE
Add Vysor Latest

### PR DESCRIPTION
**Pull request by tskulbru**
Vysor was only available through Chrome app store, but a beta version
built on electron was published through a Google+ post from the author
(can be read here:
https://plus.google.com/110558071969009568835/posts/Ub7QKu2Pddu )

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by miccal** [comment]
Is this the same thing that is available at https://github.com/koush/vysor.io ?

**Comment by tskulbru** [comment]
oh! yes it is, I wasnt aware he had a public github repo for it. Should I change the cask to use the github repo instead perhaps?

**Comment by vitorgalvao** [comment]
@tskulbru Yes, please do. Use the [releases](https://github.com/koush/vysor.io/releases) URL, add a `version` and `sha256` and an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

**Comment by tskulbru** [comment]
Changed the source to its Github repo instead and followed the instructions you told me. Hopefully everything should be OK now

**Comment by miccal** [comment]
Thank you for your contribution.

**Pull request merged**
