### PR TITLE
fixed sha256 value for inkscape

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by adityadalal924** [comment]
I get a shasum of `66c9af880f87d5b64006391fc8dd2d3f546d93d6d91235eba7856deacba29862, mind checking again?

**Comment by jawshooah** [comment]
[Travis](https://travis-ci.org/caskroom/homebrew-cask/jobs/86417617#L2415) got the same as @adityadalal924.

**Comment by adityadalal924** [comment]
PR can be closed - no changes were made
https://github.com/caskroom/homebrew-cask/blob/master/Casks/inkscape.rb remains the same (shasum was always valid)

**Comment by julienlavergne** [comment]
however I get this issue:

Error: Execution of 'brew cask install inkscape' returned 1: Error: sha256 mismatch
Expected: 66c9af880f87d5b64006391fc8dd2d3f546d93d6d91235eba7856deacba29862
Actual: a9f6ec70d9fcd16ee2e5ac3539d0ba6daefc6a87923f1dc3c2dfb45b22d4720b
File: /Library/Caches/Homebrew/inkscape-0.91-1.dmg
To retry an incomplete download, remove the file above.
==> Satisfying dependencies
complete
==> Downloading https://inkscape.global.ssl.fastly.net/media/resources/file/Inkscape-0.91-1-x11-10.7-x86_64.dmg
Already downloaded: /Library/Caches/Homebrew/inkscape-0.91-1.dmg
==> Note: running "brew update" may fix sha256 checksum errors
Error: /Stage[main]/Main/Package[inkscape]/ensure: change from absent to present failed: Execution of 'brew cask install inkscape' returned 1: Error: sha256 mismatch
Expected: 66c9af880f87d5b64006391fc8dd2d3f546d93d6d91235eba7856deacba29862
Actual: a9f6ec70d9fcd16ee2e5ac3539d0ba6daefc6a87923f1dc3c2dfb45b22d4720b
File: /Library/Caches/Homebrew/inkscape-0.91-1.dmg
To retry an incomplete download, remove the file above.
==> Satisfying dependencies
complete
==> Downloading https://inkscape.global.ssl.fastly.net/media/resources/file/Inkscape-0.91-1-x11-10.7-x86_64.dmg
Already downloaded: /Library/Caches/Homebrew/inkscape-0.91-1.dmg
==> Note: running "brew update" may fix sha256 checksum errors

**Pull request closed without merging**
