### PR TITLE
Upgrade TeamDrive from v4.6.12 to v4.7.1

### PR DESCRIPTION
**Pull request by hschwentner**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Strange -- running `curl https://teamdrive.com/en/downloads/` outputs the page source as expected for me, but:
```
|-> curl -sLI https://teamdrive.com/en/downloads/
HTTP/1.1 403 Forbidden
Date: Mon, 16 Aug 2021 21:45:23 GMT
Server: Apache
Content-Type: text/html; charset=iso-8859-1
```
@bevanjkay any ideas here?

**Comment by bevanjkay** [comment]
@miccal This one passes audit locally, so must be denying access from the workflow?

We could try using the release notes feed - http://forum.teamdrive.net/viewforum.php?f=2&sid=a615fec956a2d333b4ece062fb22bbaf - but this is not ideal.

**Comment by miccal** [comment]
> @miccal This one passes audit locally, so must be denying access from the workflow?

Me too, so I will merge this and see how we go.

**Comment by miccal** [comment]
Thank you @hschwentner.

**Comment by miccal** [comment]
```
|-> brew livecheck teamdrive
teamdrive : 4.7.1.3011 ==> 4.7.1.3011
```

**Pull request merged**
