### PR TITLE
Update acquia-dev from 2.2020.08.10 to 2.2020.09.23

### PR DESCRIPTION
**Pull request by core-code**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
`  installer manual: "Acquia Dev Desktop Installer.app"
`

**Comment by core-code** [comment]
maybe just setting `--userEmail "" --userName ""` could work around the issue but i fear it might reset some user data for 'brew upgrade'

**Comment by miccal** [comment]
If you can wait ~12 hours, I can test the `uninstall` script on my other machine.

**Comment by core-code** [comment]
yes sure its not a popular app there is no rush, thanks.

**Review by miccal — APPROVED** [review]

**Pull request merged**
