### PR TITLE
Switch to HTTPS for 360 Casks

### PR DESCRIPTION
**Pull request by tsparber**
Every changed URL was:
- reachable using a valid HTTPS connection and
- 'curl head' returned a status code of 200.

I did not verify the whole download, as I'm currently on limited bandwidth. Some casks redirect from HTTPS to HTTP (e.q. sourceforge links) those are left with HTTP.

Should I add more verification?

The script used can be found at [cask-switch-https](https://github.com/tsparber/script-collection/blob/master/cask-switch-https). Does this script also fit somewhere into homebrew-cask? I would happily create a pull request.

Log testing all Casks with a http url/appcast/homepage: https://gist.github.com/tsparber/da281e1912fc0a1ced20

As usually there should be one PR per changed cask: Should I create 360 separate PRs?

### CODE REVIEW

**Comment by tsparber** [comment]
Hmm travis fails:
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```
So creating 362 PR is the way to go?

**Comment by jawshooah** [comment]
The tests failed before it ever got that far:

```
  1) Failure:
Hbc::CLI::Home#test_0001_opens the homepage for the specified Cask [/Users/travis/build/caskroom/homebrew-cask/test/cask/cli/home_test.rb:25]:
--- expected
+++ actual
@@ -1 +1 @@
-[["/usr/bin/open", "--", "http://www.alfredapp.com/"]]
+[["/usr/bin/open", "--", "https://www.alfredapp.com/"]]

  2) Failure:
Hbc::CLI::Home#test_0002_works for multiple Casks [/Users/travis/build/caskroom/homebrew-cask/test/cask/cli/home_test.rb:32]:
--- expected
+++ actual
@@ -1 +1 @@
-[["/usr/bin/open", "--", "http://www.alfredapp.com/"], ["/usr/bin/open", "--", "https://www.adium.im/"]]
+[["/usr/bin/open", "--", "https://www.alfredapp.com/"], ["/usr/bin/open", "--", "https://www.adium.im/"]]
```

**Comment by tsparber** [comment]
Fixed the test, at least the tests seem to work know. Audit is still running.

**Comment by vitorgalvao** [comment]
There are merge conflicts that need to be solved.

> Does this script also fit somewhere into homebrew-cask?

[`developer/bin`](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin). You don’t need to submit it there, though, we can just link to it from [maintaining.md](https://github.com/caskroom/homebrew-cask/blob/master/doc/maintaining.md), if you prefer, but it seems like a nice fit.

[I have a few scripts](https://github.com/caskroom/homebrew-cask/blob/master/doc/maintaining.md#handling-cask-update-prs) that are regularly used by some maintainers (and even users) here, but I keep them in my own repo for a few reasons. Some of them aren’t homebrew-cask specific and can easily benefit other projects and the one that is specific to us (`cask-repair`) isn’t really targeted for development, and can be used by users. I also very much like to keep them organised and even have formulas for them all all my others “tiny-scripts”. I never gave it any thought, really, but perhaps (at least `cask-repair`) could make sense here.

Up to you if you want to submit it here, but it seems like you do, and it could be a nice addition.

Looking through the script, I was amazed at how much our style for bash scripting is alike (even down to when to use `$var` vs `${var}`) though I see differences in other areas, but looking further into it it seems like you may have gotten a lot from my scripts directly.

No problem there, naturally, they are public domain, after all. But I wonder if it should duplicate so much functionality (like fetching casks), since it is non-essential functionality and it means the script will essentially have to “catch up” that part of the code to `cask-repair`.

Perhaps it should be more focused in checking the availability of `https`, and doing it for all casks. We can worry about that later, though. It also seems like something that would be nice to add to `cask-repair`, so perhaps it would make sense to have two scripts:

+ `cask-repair` for individual casks (with the added functionality of checking if `https` is available.
+ `cask-switch-https` that just checks for `https` urls (but always does it for all casks).

**Comment by jawshooah** [comment]
> Looking through the script, I was amazed at how much our style for bash scripting is alike

[That's no coincidence](https://github.com/tsparber/script-collection/blob/b35d0ff72417cf55a330aca9f6dd92c4e65966e5/cask-switch-https#L35) :wink:

**Comment by tsparber** [comment]
> There are merge conflicts that need to be solved.

Rebased.

> Up to you if you want to submit it here, but it seems like you do, and it could be a nice addition.

Great, I will then create a PR.

> Looking through the script, I was amazed at how much our style for bash scripting is alike (even down to when to use $var vs ${var}) though I see differences in other areas, but looking further into it it seems like you may have gotten a lot from my scripts directly.
> No problem there, naturally, they are public domain, after all.

Yes, this script is intentionally based on your `cask-repair` to keep things similar, thanks for the 'template' :smiley: 

> Perhaps it should be more focused in checking the availability of https, and doing it for all casks.

I cleaned the script to focus on https, by default it performs the verify now and runs on all casks (with the option to run an individual cask if provided).

**Comment by vitorgalvao** [comment]
Checked manually and everything seems to be fine. Nice going on also fixing references to alfred’s url on the documentation and tests.

For future reference, [github diffing limits](https://help.github.com/articles/what-are-the-limits-for-viewing-content-and-diffs-in-my-repository/). Seems like two PRs would’ve been enough, here, for us to at least be able to see all the files in the preview.

**Pull request merged**
