### PR TITLE
Update transcribe

### PR DESCRIPTION
**Pull request by core-code**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Automatically created and submitted by muUpdateStaticHomebrewCask

### CODE REVIEW

**Review by reitermarkus — APPROVED** [review]

**Comment by core-code** [comment]
sorry - no idea why this happened but i guess it is a cask-repair bug 

ping @vitorgalvao

**Comment by vitorgalvao** [comment]
Does the latest version of `bump-cask-pr` handle it correctly?

**Comment by core-code** [comment]
seems so https://github.com/Homebrew/homebrew-cask/pull/95616/files

**Comment by vitorgalvao** [comment]
I think I’ve found the issue. Did you run the command on Big Sur or under (guessing under)?

@reitermarkus Setting `MACOS_VERSION` in the shell no longer seems to work to force Homebrew to use a specific version. I grepped the code and found references to `HOMEBREW_MACOS_VERSION` and `HOMEBREW_MACOS_VERSION_NUMERIC`, but neither seems to do it.

**Comment by core-code** [comment]
the Mac running muUpdateStaticHomebrewCask is on 10.15

**Comment by vitorgalvao** [comment]
> the Mac running muUpdateStaticHomebrewCask is on 10.15

[This line](https://github.com/vitorgalvao/tiny-scripts/blob/d36ac0e809717c1e15335c9d6e27a1660d9b7a23/cask-repair#L4) (used to) force Hoembrew to act like the user was on the latest version of macOS, so commands consider that branch of the MacOS.version conditional.

In this case, `brew cask _stanza transcribe` should have returned `:no_check`, but because that variable [is no longer working](https://github.com/Homebrew/homebrew-cask/pull/95563#issuecomment-745573675), it’s using the macOS version of the machine, grabbing *that* checksum, which exists and therefore is not ignored. Additionally, the last `sha256` is always the one modified (because it assumes it to be the latest version).

Put it all together, and we get that specific bug. It will be fixed if the variable is.

**Comment by core-code** [comment]
cask-repair has never worked 'correctly' for me on anything but the latest macOS version (for casks that have relevant if/else) and i've assumed this was a known limitation.

**Comment by vitorgalvao** [comment]
> cask-repair has never worked 'correctly' for me on anything but the latest macOS version (for casks that have relevant if/else) and i've assumed this was a known limitation.

It was, until that variable was introduced to the script. Even then it would only update the latest version, but it would work correctly independently of your installed OS.

No idea when that variable stopped working.

**Pull request closed without merging**
