### PR TITLE
steelseries-gg 54.0.0

### PR DESCRIPTION
**Pull request by smudja**
steelseries-gg 54.0.0

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by krehel** [comment]
Duplicate of #164064

**Comment by bevanjkay** [comment]
Using this as a replacement PR for - https://github.com/Homebrew/homebrew-cask/pull/164064
Looks like you might have deleted your fork @chenrui333 

---

I think what's happening here is that the uninstaller is opening a browser.
I'm not sure there's much we can do besides ignore the error.

**Comment by bevanjkay** [comment]
The `pkg` installer opens a browser session once the install is completed, so I'm not sure there's anything we can do here for the failing test, other than look at adding an allowlist for CI, or skipping the audit.

**Comment by reitermarkus** [comment]
I don't think an allowlist is worth it as I am not sure there is a generic way this can work. We already ignore some other things though, so maybe we can ignore `org.mozilla.firefox` except when actually testing the `firefox` cask.

**Comment by bevanjkay** [comment]
Sounds like a reasonable solution, would require adding additionals if the default browser changes on the CI image.

**Comment by krehel** [comment]
Replacing with #165097

**Pull request closed without merging**
