### PR TITLE
sunvox 1.9b

### PR DESCRIPTION
**Pull request by andystanton**

### CODE REVIEW

**Comment by andystanton** [comment]
Travis error is:
```
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
audit for sunvox: failed
 - download not possible: Download failed on Cask 'sunvox' with message: Download failed: https://www.warmplace.ru/soft/sunvox/sunvox-1.9b.zip
Error: audit failed
```

Given I have no control over the server's certificate, would it be acceptable to change the URL from https to http?

**Comment by vitorgalvao** [comment]
@jawshooah Looks like your Travis changes are already proving useful.

@andystanton Yes, please do (@mention me after, so I know to come back). The download on the page is already changed to `http`, even.

**Comment by andystanton** [comment]
@vitorgalvao Changed made & squashed.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 458a64e939a8648f990e81a8c8aa95afa7899639 to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
