### PR TITLE
Create new prokaa-v0.2.3 cask

### PR DESCRIPTION
**Pull request by jainkuniya**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vladimyr** [comment]
Thank you for submitting it but unfortunately, [notability requirements](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md) are in the process of updating #81265 from a minimum of 50 stars:
> 
> * The Cask is too obscure. Examples:
>   
>   * A self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars).
>   * [Electronic Identification (eID) software](https://github.com/Homebrew/homebrew-cask/issues/59021). 

to new minimum of 75 stars:
>+ The Cask is for an app that is too obscure. Examples:
>
>   + A self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 30 forks, 30 watchers, and 75 stars).
>   + [Electronic Identification (eID) software](https://github.com/Homebrew/homebrew-cask/issues/59021).

**Comment by jainkuniya** [comment]
Hi @vladimyr thanks for the review.

- As per current norms, this Cask seems to be valid right?
- I am not sure, why such metrics are considered to evaluate a cask? Contributors might start faking it.
Also had few questions in mind, just curious to know
- why the problem being solved is not considered to evaluate? Why the usefulness of the application is not considered in the process?
- why creativity or uniqueness of a application is neglected?
- why a cask is not tried and discussed before commenting on it?
- also it says, self submitted app, so if one of his friends submit (or he only submits it from another account), will it get approved?

Please let me know your thoughts on this. :) 

Actually this is not yet publicized, so this metrics are not so great. We were waiting this to get merged before we do a public release.

**Comment by vladimyr** [comment]
> * As per current norms, this Cask seems to be valid right?

True, but maintainers hold the right to override audit verdict in marginal cases and this is a narrow victory just before rules are changing. I'm not a maintainer so this isn't my decision I'm just giving you some context regardless of final decision.

> * I am not sure, why such metrics are considered to evaluate a cask? Contributors might start faking it.
>   Also had few questions in mind, just curious to know
> * why the problem being solved is not considered to evaluate? Why the usefulness of the application is not considered in the process?
> * why creativity or uniqueness of a application is neglected?
> * why a cask is not tried and discussed before commenting on it?
> * also it says, self submitted app, so if one of his friends submit (or he only submits it from another account), will it get approved?
> * What if a cask is submitted from a web page, which doesn't even reveal the github repo. Then how popularity is considered? And it might be insecure app.

Well, I can give you only my personal opinions but keep in mind I'm not maintainer and can't discuss official policies. You are very much right and the system can get tricked easily, indeed, but on the other hand, some sort of rules need to exist. If you are interested in improving them you can create a separate issue here or create a topic on the official forum.
While I agree that not all applications belong in the same league how would you measure usefulness, creativity, or uniqueness? I would argue that those are highly subjective things unless you somehow come up with a set of clearly defined rules that would prevent discrimination.
Regarding trying and discussing applications prior to reviewing I simply don't see it as a viable practice. That requires **a lot** of resources and it is pretty much unreal to expect that from HBC volunteers. That is why HBC has rules in the first place. So time isn't spent on something that doesn't match entry criteria and maintainers can use that time for inspecting, running, and reviewing other things instead.

**Comment by vitorgalvao** [comment]
I was writing a reply, but @vladimyr pretty much covered it. But I should still point this out:

> Actually this is not yet publicized, so this metrics are not so great. We were waiting this to get merged before we do a public release.

That’s not how we work. We provide what users want to install, we don’t advertise apps that are being released. We’re [not a discoverability service](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md).

First do a public release and get users. If your metrics are indeed low because the app isn’t yet publicised, that means you’ll reach the targets in no time and be able to resubmit, at which point we’ll gladly take it!

Also, I’d say that tricking our checks is grounds for permanent banning of the tool’s author and all their apps, so I’d recommend against it.

**Comment by ran-dall** [comment]
@jainkuniya I'd also like to point out that you're more than welcome to still host this on a personal tap. It doesn't add much to the installation process, and if you were deadset of using HBC, it's a way of accomplishing the intended use. You're also more than welcome to resubmit it after your project meets notability requirements.

**Pull request closed without merging**
