### PR TITLE
Update daylite to 6.2

### PR DESCRIPTION
**Pull request by colindunn**
After making all changes to the cask:

- [x] \`brew cask audit --download {{cask_file}}\` is error-free.
- [x] \`brew cask style --fix {{cask_file}}\` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by colindunn** [comment]
I'm still not 100% sure I've managed to fully uninstall this one. Would appreciate help here as this one is painful.

**Comment by miccal** [comment]
Looks fine to me?

**Comment by colindunn** [comment]
Was having some real trouble getting `GR26KTJYTV.com.marketcircle.Daylite-Helper` to quit in particular. If it's working fine for you, I'd be happy :-)

**Comment by commitay** [comment]
This uninstall works fine for me with the app running.

Not sure if `GR26KTJYTV.com.marketcircle.Daylite-Helper` should maybe be changed to `*.com.marketcircle.Daylite-Helper`, as it might change with new versions?

These files could be added to a `zap`.

```
~/Library/Application Support/com.marketcircle.daylite
~/Library/Caches/com.marketcircle.daylite
~/Library/Caches/com.plausiblelabs.crashreporter.data/com.marketcircle.daylite
~/Library/Group Containers/GR26KTJYTV.com.marketcircle.daylite
~/Library/Preferences/com.marketcircle.daylite.plist
~/Library/Saved Application State/com.marketcircle.daylite.savedState
```

**Comment by colindunn** [comment]
Thanks @commitay 
Done

**Comment by colindunn** [comment]
Wildcarding the `GR26KTJYTV` also

**Review by vitorgalvao — APPROVED** [review]

**Review by victorpopkov — APPROVED** [review]

**Pull request merged**
