### PR TITLE
mplabx-ide 6.20

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
It seems the `url` no longer accepts `curl` requests:
```
|-> curl -sLI https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/MPLABX-v6.20-osx-installer.dmg
HTTP/1.1 302 Moved Temporarily
Server: AkamaiGHost
Content-Length: 0
Location: https://www.microchip.com/en-us/error/401.html?url=https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/MPLABX-v6.20-osx-installer.dmg
Date: Mon, 05 Feb 2024 07:56:59 GMT
Connection: keep-alive

HTTP/2 403 
server: AkamaiGHost
mime-version: 1.0
content-type: text/html
content-length: 308
expires: Mon, 05 Feb 2024 07:57:00 GMT
cache-control: max-age=0, no-cache, no-store
pragma: no-cache
date: Mon, 05 Feb 2024 07:57:00 GMT
x-akam-sw-version: 0.5.0
server-timing: ak_p; desc="1707119819584_1751253839_455467530_25_141890_37_587_15";dur=1
```

**Comment by p-linnane** [comment]
Not 100% sure what we are doing here. Are we removing this?

**Comment by bevanjkay** [comment]
I'm not sure if we have tried with a user agent, or if it needs a referer header?

Regardless, we should use `disable` before removal nowadays?

**Comment by p-linnane** [comment]
Yeah `disable`. Good call.

**Comment by krehel** [comment]
I got this to work locally by adding `referer`, let's see if it cooperates here.

**Review by p-linnane — APPROVED** [review]
Great work @krehel!

**Pull request merged**
