### PR TITLE
krisp 2.18.6

### PR DESCRIPTION
**Pull request by gabrielwhite**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by razvanazamfirei — APPROVED** [review]

**Review by razvanazamfirei — CHANGES_REQUESTED** [review]
Could you update this to the livecheck version? 
2.18.6

Edit: Nevermind. It looks like `2.x` is still in beta. We'll need to figure out a better livecheck for this.

**Comment by razvanazamfirei** [comment]
Nevermind. It looks like `2.x` is still in beta. We'll need to figure out a better livecheck for this.

**Comment by razvanazamfirei** [comment]
Sounds good! Thank you for checking! Is there an arm version? All I can find is `https://cdn.krisp.ai/mp/2.18.6/mac/x64/krisp_2.18.6_x64.pkg` which does not run on arm.

**Comment by gabrielwhite** [comment]
https://cdn.krisp.ai/mp/2.18.6/mac/arm64/krisp_2.18.6_arm64.pkg

**Comment by razvanazamfirei** [comment]
Thank you so much! Updated!

**Review by razvanazamfirei — DISMISSED** [review]

**Review by razvanazamfirei — DISMISSED** [review]

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
