### PR TITLE
Update bartender from 3.0.47 to 3.0.64

### PR DESCRIPTION
**Pull request by tiiiecherle**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@tiiiecherle There's a PR already for this update https://github.com/Homebrew/homebrew-cask/pull/62178

**Comment by tiiiecherle** [comment]
@ran-dall sorry, I don't see a second one, there is only [#62178](https://github.com/Homebrew/homebrew-cask/pull/62178)

**Comment by tiiiecherle** [comment]
oh, you meant [#62172](https://github.com/Homebrew/homebrew-cask/pull/62172)

**Comment by tiiiecherle** [comment]
feel free to close mine then, thanks

**Comment by ran-dall** [comment]
@tiiiecherle Would you mind closing it? I can't close it for you.

**Comment by tiiiecherle** [comment]
done ;)

**Pull request closed without merging**
