### PR TITLE
Update sling

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
i get the same 503 error in Safari, but the download works in Chrome

**Comment by core-code** [comment]
it also works in 'curl' so i am not sure what the issue is

**Comment by vitorgalvao** [comment]
Doesn’t work for me in Chrome, but neither does the previous one and the website is only available from the US.

I’m more inclined towards removal:

```
sling (added 1659 days ago)
30 days: 1 (#4842)
90 days: 5 (#4405)
365 days: 35 (#3697)
```

**Comment by core-code** [comment]
fine with me ;)

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/67879

**Pull request closed without merging**
