### PR TITLE
Update cisdem-document-reader from 4.5.0 to 5.0.0

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Extraneous commit again. It may be that you’re not starting `cask-repair` from `master`, or something else. I recommend `cask-repair --delete-branches`, followed by `git checkout master` and maybe `git branch` to see what else is there.

**Comment by vitorgalvao** [comment]
WAIT!

**Comment by vitorgalvao** [comment]
Forgot to warn that `cask-repair --delete-branches` will delete all local and remote branches named like `cask_repair_update-<word>`, meaning that it will also close open PRs if you have any at the time you run it.

**Comment by suschizu** [comment]
uff - again here - ok thanks - I'll delete the branches

**Pull request closed without merging**
