### PR TITLE
Adding drjava latest

### PR DESCRIPTION
**Pull request by darkmastermindz**
**adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [x] `brew cask install drjava` worked successfully.
- [x] `brew cask uninstall drjava` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to {{correct repo}}.

The token reference said drjavajar but it doesn't make sense since drjava is the official name of the IDE.

### CODE REVIEW

**Comment by ran-dall** [comment]
@darkmastermindz You're slightly off in the formula. Here's the corrected formula...

```ruby
cask 'drjava' do
  version '20160913-225446,beta'
  sha256 'e26b5ca518585ec3d9500d6709e4c1cd2ad41ea041606762cc66254af9c7f431'

  # downloads.sourceforge.net/drjava/ was verified as official when first introduced to the cask
  url "https://downloads.sourceforge.net/drjava/1.%20DrJava%20Stable%20Releases/drjava-#{version.after_comma}-#{version.before_comma}/drjava-#{version.after_comma}-#{version.before_comma}-osx.tar.gz"
  appcast 'https://sourceforge.net/projects/drjava/rss?path=/1.%20DrJava%20Stable%20Releases'
  name 'DrJava'
  homepage 'http://www.drjava.org/'

  app 'DrJava.app'
end

```

**Comment by darkmastermindz** [comment]
@ran-dall Thanks for helping me fix this. I also noticed that the naming scheme of this program is a bit weird since their "beta" is the current stable and their current stable version doesn't work on the latest macOS.

**Comment by darkmastermindz** [comment]
> @darkmastermindz 🤝No problem! Any time! Yea I noticed that too, but it's on the 'stable' appcast.

Hmm...it also seems like it would be better to use the jar version and require java 8, according to their [site](http://drjava.org/):

> The current stable release for DrJava is drjava-beta-20160913-225446. This version supports 7, and 8. You can read the release notes on the SourceForge download page. The Mac OS X app has been removed; it only worked for Apple Java, which ended with Java 6. Mac users should download the Jar file, open the Security and Privacy panel in the System Preferences app, and check the box stating that they want to open the DrJava Jar file, even though is was produced a developer unknown to (unregistered with) Apple. Then the Jar file can be run using the Oracle Java 7 or 8 JDK.

**Comment by ran-dall** [comment]
@darkmastermindz Thanks for the heads up. The problem I see with this is that we don't support apps that are _unregistered_ on the 'official' tap. But let me play around with the formula you had for the jar to see if I can make that work.

**Comment by darkmastermindz** [comment]
> @darkmastermindz Thanks for the heads up. The problem I see with this is that we don't support apps that are _unregistered_ on the 'official' tap. But let me play around with the formula you had for the jar to see if I can make that work.

This is what I got so far (based on #37921):

```ruby
cask 'drjava' do
  version '20160913-225446,beta'
  sha256 '701c3638049b99aa59cfcb2a9874493496d20ffb34370e67935bb6f64fa5ae91'

  # downloads.sourceforge.net/drjava/ was verified as official when first introduced to the cask
  url "https://downloads.sourceforge.net/projects/drjava/files/1.%20DrJava%20Stable%20Releases/drjava-#{version.after_comma}-#{version.before_comma}/drjava-#{version.after_comma}-#{version.before_comma}.jar"
  appcast 'https://sourceforge.net/projects/drjava/rss?path=/1.%20DrJava%20Stable%20Releases'
  name 'DrJava'
  homepage 'http://www.drjava.org/'
  depends_on java: ['6', '7']

  container type: :naked
  app "drjava-#{version.after_comma}-#{version.before_comma}/#{version.after_comma}-#{version.before_comma}.jar", target: 'DrJava.jar'
end
```
Although I can wget the url to get the jar, brew seems to be getting the webpage instead of the actual download.

**Comment by ran-dall** [comment]
@darkmastermindz Ok, I'm working on it. Good work on https://github.com/Homebrew/homebrew-cask/pull/55213#issuecomment-440910775. However, I don't think that having multiple Java's declared works.
```bash
Brew cask audit /Users/randall/Desktop/drjava.rb --download                                                                 
Error: Cask 'drjava' is unreadable: wrong number of arguments (given 2, expected 1)
```
Also, your link was wrong...

```
You had: `https://downloads.sourceforge.net/projects/drjava/files/1.%20DrJava%20Stable%20Releases/drjava-#{version.after_comma}-#{version.before_comma}/drjava-#{version.after_comma}-#{version.before_comma}.jar`
The right link is: `https://downloads.sourceforge.net/projects/drjava/1.%20DrJava%20Stable%20Releases/drjava-#{version.after_comma}-#{version.before_comma}/drjava-#{version.after_comma}-#{version.before_comma}.jar`

So here it is, corrected, with the right sha256, link, format, etc...
```ruby
cask 'drjava' do
  version '20160913-225446,beta'
  sha256 'fd4e24ac4901accbdc37644149ecbf54644b4a073b1963d344dd49520a44b430'

  # downloads.sourceforge.net/drjava/ was verified as official when first introduced to the cask
  url "https://downloads.sourceforge.net/projects/drjava/1.%20DrJava%20Stable%20Releases/drjava-#{version.after_comma}-#{version.before_comma}/drjava-#{version.after_comma}-#{version.before_comma}.jar"
  appcast 'https://sourceforge.net/projects/drjava/rss?path=/1.%20DrJava%20Stable%20Releases'
  name 'DrJava'
  homepage 'http://www.drjava.org/'

  depends_on java: ['7']
  container type: :naked

  app "drjava-#{version.after_comma}-#{version.before_comma}/#{version.after_comma}-#{version.before_comma}.jar", target: 'DrJava.jar'
end

```
That should give you this error...
`Error: It seems the App source '/usr/local/Caskroom/drjava/20160913-225446,beta/drjava-beta-20160913-225446/beta-20160913-225446.jar' is not there.`

Which is what I'm working on...

**Comment by darkmastermindz** [comment]
@ran-dall After looking into the url `https://downloads.sourceforge.net/projects/drjava/1.%20DrJava%20Stable%20Releases/drjava-#{version.after_comma}-#{version.before_comma}/drjava-#{version.after_comma}-#{version.before_comma}.jar` n [#55213 (comment)](https://github.com/Homebrew/homebrew-cask/pull/55213#issuecomment-440924330) and with the code provided:

I'm getting similar error on my side. Looking into it with TravisCI to verify, I see that it's downloading the html page `create` rather than the jar. It would seem that the [url `https://downloads.sourceforge.net/projects/drjava/1.%20DrJava%20Stable%20Releases/drjava-beta-20160913-225446/drjava-beta-20160913-225446.jar`](https://downloads.sourceforge.net/projects/drjava/1.%20DrJava%20Stable%20Releases/drjava-beta-20160913-225446/drjava-beta-20160913-225446.jar) is redirected to [https://sourceforge.net/create/](https://sourceforge.net/create/) which 

```
==> Downloading https://downloads.sourceforge.net/projects/drjava/1.%20DrJava%20
==> Downloading from https://sourceforge.net/create
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'drjava'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
audit for drjava: failed
 - download not possible: Checksum for Cask 'drjava' does not match.
Expected: fd4e24ac4901accbdc37644149ecbf54644b4a073b1963d344dd49520a44b430
Actual:   cc82526f3942f9b0e427de4e2ab8f005ccb66ae3ea13b5ee1857bb8d17cf87dc
File:     /Users/travis/Library/Caches/Homebrew/downloads/66a01d1f8b6f0e2e5926515f32dd994e4ddb35f375bda0b137559f1593c75096--create
``` 

However, when I wget the link, I'm able to get the jar just fine with it retrying a few times:
```
wget https://downloads.sourceforge.net/projects/drjava/1.%20DrJava%20Stable%20Releases/drjava-beta-20160913-225446/drjava-beta-20160913-225446.jar
--2018-11-22 11:26:41--  https://downloads.sourceforge.net/projects/drjava/1.%20DrJava%20Stable%20Releases/drjava-beta-20160913-225446/drjava-beta-20160913-225446.jar
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://sourceforge.net/downloads [following]
--2018-11-22 11:26:42--  https://sourceforge.net/downloads
Resolving sourceforge.net (sourceforge.net)... 216.105.38.13
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/publish [following]
--2018-11-22 11:26:42--  https://sourceforge.net/publish
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/publish/ [following]
--2018-11-22 11:26:43--  https://sourceforge.net/publish/
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/create [following]
--2018-11-22 11:26:44--  https://sourceforge.net/create
Reusing existing connection to sourceforge.net:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/create/ [following]
--2018-11-22 11:26:44--  https://sourceforge.net/create/
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 154762 (151K) [text/html]
Saving to: ‘drjava-beta-20160913-225446.jar’

drjava-beta-20160913-225446.jar     100%[==================================================================>] 151.13K   113KB/s    in 1.3s    

2018-11-22 11:26:46 (113 KB/s) - ‘drjava-beta-20160913-225446.jar’ saved [154762/154762]
```
So, I'm not sure if this issue is related to how brew gets files on sourceforge or if it's just contained to this one file on sourceforge giving 307 Temporary Redirects & 301 Moved Permanently. Wget seems to go to   https://sourceforge.net/create/ and still able to retrieve the file.

**Comment by ran-dall** [comment]
@darkmastermindz Sorry, the holidays got in the way. 🚧

Here's the thing, I'm not a really Java developer. However I've been exposed enough to it, you'd think I'd be an expert. I'll try to work on this some more but maybe someone with more Java experience might have better suggestions. 🤔

**Comment by darkmastermindz** [comment]
@ran-dall There isn't anything here that would require any java development. Looking into it, I believe the issue here is how homebrew is getting the the file from the URL for jar file, since it's not checking for it. I verified this with other applications that host jar applications on sourceforge.

**Comment by ran-dall** [comment]
@darkmastermindz Sorry that's what I was trying to say, I'm not that experienced working with .jar files.

**Comment by ran-dall** [comment]
@darkmastermindz Maybe we should just close this for now, until we can find the best way to make this happen?

**Comment by vitorgalvao** [comment]
Haven’t read all (just diagonally), but closing since [it was suggested and a thumbs up was given](https://github.com/Homebrew/homebrew-cask/pull/55213#issuecomment-443363542).

**Pull request closed without merging**
