### PR TITLE
Update aviatrix-vpn-client from latest to 2.10.8

### PR DESCRIPTION
**Pull request by vjeetje**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
if we are going to have a version number here, we also need a reliable appcast

https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

**Comment by core-code** [comment]
thanks there.  i think this one might be better though "https://docs.aviatrix.com/Downloads/samlclient.html"

**Comment by vjeetje** [comment]
The reason why I chose the changelog over the downloads page is that the changelog page is less likely to change due to non release changes.  If pointing to the downloads page is more conventional, I'm happy to change the PR.

**Comment by core-code** [comment]
thanks for thinking about this, i see your reasoning. in reality both of these are going to be "noisy" as they are HTML pages which will have many unrelated changes. 

the reason i consider "changelog" pages to be the worst choice is because they *also* contain the old version numbers. this means we cannot do an automated check if the current cask version is no longer contained in the appcast, and infer that there has to be an update. this is a check we run each day to find cask updates ( http://macupdater.net/cask-repair/appcast_containsversion-2020-05-25.txt ). which change-log pages this is impossible and we have to resort to other, less reliable checks.

**Comment by core-code** [comment]
if you are going to make sure this cask is always up-to-date yourself then it doesn't matter ;)

**Pull request merged**
