### PR TITLE
Update gpg-suite from 2021.1,105 to 2021.2

### PR DESCRIPTION
**Pull request by lebdron**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by samford** [comment]
The `appcast.xml` file used in the `livecheck` block doesn't include information for 2021.2 (yet?). Seeing as the appcast doesn't give us the correct latest version, it may be better to simply parse the version from the download link on the homepage:

```ruby
  livecheck do
    url :homepage
    regex(/href=.*?GPG_Suite[._-]v?(\d+(?:\.\d+)+)\.dmg/i)
  end
```

The `gpg-suite-pinentry` and `gpg-suite-no-mail` casks should be updated as well but I'll leave it up to our homebrew/cask maintainers whether we should do this altogether or in separate PRs. However that happens, the `livecheck` blocks in the variant casks can be updated as follows (since they use the same `url` as `gpg-suite` and `gpg-suite` is the canonical cask):

```ruby
  livecheck do
    cask "gpg-suite"
  end
```

This helps to ease our maintenance burden, as we only have to keep the `gpg-suite` `livecheck` block up to date and the others will automatically inherit any changes.

**Comment by lebdron** [comment]
@samford Thank you for the reply! Should we also handle an optional `after_comma` case, or that should be done only if it appears in the link again?

**Comment by miccal** [comment]
Let's update `gpg-suite-no-mail` and `gpg-suite-pinentry` in a separate PR.

**Comment by NSBrianWard** [comment]
For whatever reason, updating via brew didn't actually increment my gpg-suite version, despite seeing that I got the update in brew. I was still stuck on 2021.1 according to the gpg app itself (from the preferences pane). I had to uninstall/reinstall the cask to get the correct version. Unsure what happened there. It seems to be working now though!

**Pull request merged**
