### PR TITLE
Update webex-nbr-player to T31L

### PR DESCRIPTION
**Pull request by csi-adziahel**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by csi-adziahel** [comment]
OK, will this one do – https://www.virustotal.com/#/url/0cc43070f507f3019a6f366c37e5faaefdaf25e3b461611afccc2f4228ec7003/details ?

**Comment by csi-adziahel** [comment]
@vitorgalvao also https://www.cisco.com/c/en/us/td/docs/collaboration/CWMS/2_8/Release_Notes/cwms_b_release-notes-cwms-2-8.html#reference_91E0D3B891D309DEFD5A0012B03C1DB3 dated Apr 8

**Comment by vitorgalvao** [comment]
That won’t do, because it’s not signed.

**Comment by csi-adziahel** [comment]
Right. Is there anything else _I_ could do about the issue?

**Comment by vitorgalvao** [comment]
Yes. Contact them in a public way (eg. [via Twitter](https://twitter.com/webex))

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/50101

**Pull request closed without merging**
