### PR TITLE
zerotier-one 1.14.1

### PR DESCRIPTION
**Pull request by nevack**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by nevack** [comment]
Audit will fail because of livecheck

Indeed, https://download.zerotier.com/dist/ZeroTier%20One.pkg points to the https://download.zerotier.com/RELEASES/1.14.1/dist/ZeroTier%20One.pkg

So website is not updated, but release was published.

Also https://github.com/zerotier/ZeroTierOne/releases/tag/1.14.1

**Comment by nevack** [comment]
I can update livecheck.

Is it preferred to use
https://docs.brew.sh/Brew-Livecheck#version-directories
or Git/Github related strategies in this case?

**Comment by khipp** [comment]
@nevack The directory listing page would be preferable since releases are not directly published on the GitHub repository:

```rb
  livecheck do
    url "https://download.zerotier.com/RELEASES/"
    regex(%r{href=["']?v?(\d+(?:\.\d+)+)/?["' >]}i)
  end
```

**Review by khipp — APPROVED** [review]
Thank you!

**Pull request merged**
