### PR TITLE
sakura 3.1.2

### PR DESCRIPTION
**Pull request by adithyasunil26**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
I can only see 3.1.1 there

image

**Comment by adithyasunil26** [comment]
@chenrui333 that is strange

Screenshot 2024-06-30 at 8 52 23 PM

**Review by bevanjkay — APPROVED** [review]

**Comment by bevanjkay** [comment]
I'm also seeing 3.1.2 locally 🤷‍♂️ - I guess it will propagate globally at some point.

**Comment by p-linnane** [comment]
I tried a few different locations and it looks like only certain geographies are being served 3.1.2. Let's leave this open for a few more days and see what happens.

**Review by khipp — APPROVED** [review]

**Pull request merged**
