### PR TITLE
Update elan-avfx from 5.7 to 5.8

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@core-code `ditto: Couldn't read PKZip signature` I've never seen this on HBC

**Comment by core-code** [comment]
it is because it i not a ZIP

https://www.mpi.nl/tools/elan/ELAN_5-8-AVFX_mac.zip


does not actually download anything useful

**Comment by core-code** [comment]
try deleting '-AVFX' from the URL

**Comment by vitorgalvao** [comment]
> It seems the App source '/usr/local/Caskroom/elan-avfx/5.8/ELAN_5.8-AVFX.app' is not there.

**Pull request merged**
