### PR TITLE
Update retroarch-cg to 1.7.1

### PR DESCRIPTION
**Pull request by patsoffice**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
`sha256` only changes need to be verified. See [updating the `sha256`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256) for how to provide verification.
___
The `app` isn't signed so the developer will have to be contacted to confirm the `sha266` is legitmate.

https://github.com/libretro/RetroArch

**Comment by vitorgalvao** [comment]
@patsoffice Are you following the verification procedure?

**Comment by brianmorton** [comment]
Can probably close... https://github.com/caskroom/homebrew-cask/pull/46360

**Comment by commitay** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/46360

**Pull request closed without merging**
