### PR TITLE
Add auto_updates flag to notion 2.0.15

### PR DESCRIPTION
**Pull request by andreiborisov**
After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]

**Comment by jiaming-shi** [comment]
The notion client does not have the function of automatic update, it is the service embedded inside the client that will automatically upgrade, which is not the same.
image

**Comment by jiaming-shi** [comment]
This commit should be reverted.

**Comment by andreiborisov** [comment]
@jiaming-shi I've contacted Notion support regarding this. I'll post their answer here.

**Comment by andreiborisov** [comment]
@jiaming-shi 
CleanShot 2021-03-07 at 14 09 36@2x

It'll update itself

**Comment by jiaming-shi** [comment]
> @jiaming-shi
> CleanShot 2021-03-07 at 14 09 36@2x
> 
> It'll update itself

Thanks. It's a bit confusing that notion doesn't change the version number of the desktop client after upgrading.

**Pull request merged**
