### PR TITLE
Add todesk 4.2.2

### PR DESCRIPTION
**Pull request by wjlmelody**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@wjlmelody Why did you close this PR?

**Comment by wjlmelody** [comment]
> @wjlmelody Why did you close this PR?

**Comment by wjlmelody** [comment]
> @wjlmelody Why did you close this PR?

This PR has been reopened.

**Comment by bevanjkay** [comment]
@wjlmelody We just need to update the uninstall stanza with the results from the CI run. If you need help, let us know.

**Comment by bevanjkay** [comment]
Thank you @wjlmelody

**Comment by wjlmelody** [comment]
> Thank you @wjlmelody

You're welcome @bevanjkay

**Pull request merged**
