### PR TITLE
Fix Casks without default language.

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by miccal** [comment]
```
audit for adobe-animate-cc: failed
 - exception while auditing adobe-animate-cc: Cask 'adobe-animate-cc' definition is invalid: No default language specified.
==> Auditing language: 'cs'
audit for adobe-illustrator-cc: failed
 - exception while auditing adobe-illustrator-cc: Cask 'adobe-illustrator-cc' definition is invalid: No default language specified.
==> Auditing language: 'cs'
audit for adobe-indesign-cc: failed
 - exception while auditing adobe-indesign-cc: Cask 'adobe-indesign-cc' definition is invalid: No default language specified.
==> Auditing language: 'cs'
audit for adobe-photoshop-cc: failed
 - exception while auditing adobe-photoshop-cc: Cask 'adobe-photoshop-cc' definition is invalid: No default language specified.
```

**Comment by reitermarkus** [comment]
Weird.

**Comment by reitermarkus** [comment]
Ah, I know what's happening. It tries to compare it to the previous version, which of course was broken.

**Comment by NotAlexNoyle** [comment]
What's the status on this merge? I see it failed checks and hasn't been pushed.

**Comment by reitermarkus** [comment]
It was merged, but [we removed all Adobe CC Casks](https://github.com/caskroom/homebrew-cask/pull/39442).

**Comment by NotAlexNoyle** [comment]
Oh. I see. Thank you.

**Comment by Doko-Demo-Doa** [comment]
So, how can I remove the photoshop-cc casks now? I had one installed and I cannot remove it.

**Comment by vitorgalvao** [comment]
@Doko-Demo-Doa `brew cask uninstall --force {{cask_name}}`.

**Comment by Doko-Demo-Doa** [comment]
No effect. It says:

`Cask 'adobe-photoshop-cc' definition is invalid: No default language specified.`

Also I cannot run `brew cask update` anymore. Of course I can remove PTS CC manually, but the cask is still in registry.

**Comment by vitorgalvao** [comment]
`brew cask update` has been deprecated for quite a while. Run `brew update` instead.

Try `brew cask uninstall --force https://raw.githubusercontent.com/reitermarkus/homebrew-cask/3f491e160ec71b13ca984b35690f92f8e7bbdbd6/Casks/adobe-photoshop-cc.rb`.

**Comment by Doko-Demo-Doa** [comment]
Nice! Actually I tried to use `brew cask outdated` too, but same error. Your .rb helped me though. Thanks a lot.

**Comment by yoanmalie** [comment]
@vitorgalvao I got the same issues as @Doko-Demo-Doa with the error on the requested URL

**Comment by yoanmalie** [comment]
Not sure if it's the best way, but i "solved" my issue who give me the previous error when i use any `brew cask` commands.

Just delete apps :

`rm -rf /usr/local/Caskroom/adobe-illustrator-cc`
`rm -rf /usr/local/Caskroom/adobe-photoshop-cc`

**Comment by vitorgalvao** [comment]
> Just delete apps

That doesn’t delete the apps, it just removes the HBC reference. They’re still installed as before.

**Comment by yoanmalie** [comment]
@vitorgalvao Ah true. But how to delete them ? This is a quickfix i find to be able to use `brew cask` commands again without having these previous errors. (This is why i said ""solved"").

**Comment by vitorgalvao** [comment]
> But how to delete them ?

As a last resort, same way you’d delete them without HBC.

**Pull request merged**
