### PR TITLE
Update hubstaff to 1.4.4,556fe980

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
I think I already update this...https://github.com/Homebrew/homebrew-cask/pull/60283

**Comment by suschizu** [comment]
The download url was wrong here - I think the old url pointed to an older version inside the cask so there was no travis error

**Comment by ran-dall** [comment]
@suschizu Nice. ✊

Just a side note, would you mind updating the PR title to something like `Fix download URL on HubStaff 1.4.4,556fe980` just so that it's more evident of what this PR addresses?

**Comment by suschizu** [comment]
sure - no problem :)

**Comment by reitermarkus** [comment]
The part after the comma is not used.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
