### PR TITLE
Add FMOD Studio

### PR DESCRIPTION
**Pull request by lukeadams**
Audio mixing tool for game devs.

### CODE REVIEW

**Comment by fanquake** [comment]
Please squash your commits.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in fb39b526742492be9e532f05ed67e9456525eaa0. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by lukeadams** [comment]
@fanquake @vitorgalvao Thank you guys so much! Sorry about that – this is my first Cask.

**Comment by vitorgalvao** [comment]
@lukeadams Welcome! Don’t worry about it, it was a great one. Especially since there were no mistakes in the cask itself, that’s rare for newcomers.

**Pull request closed without merging**
