### PR TITLE
loupedeck 5.9.0.19176

### PR DESCRIPTION
**Pull request by bevanjkay**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@chenrui333 This regularly fails `brew bump` because the `url` changes.

**Comment by chenrui333** [comment]
> @chenrui333 This regularly fails `brew bump` because the `url` changes.

so you are suggesting this not quite autobump-able?

**Comment by bevanjkay** [comment]
I think I can fix it and then we can autobump.

**Comment by chenrui333** [comment]
damn XD
```
Error: Some applications are still running, add them to uninstall quit:
com.loupedeck.loupedeckconfig
```

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
