### PR TITLE
autobump: use `--no-fork`

### PR DESCRIPTION
**Pull request by chenrui333**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

- https://github.com/Homebrew/brew/pull/16740

### CODE REVIEW

**Comment by Bo98** [comment]
Are we sure only Homebrew maintainers use this?

**Comment by chenrui333** [comment]
I thought this is for the cask bump

**Comment by bevanjkay** [comment]
This will fail if a non-maintainer runs the command

**Comment by Bo98** [comment]
Cask autobump is powered by https://github.com/Homebrew/homebrew-cask/blob/master/.github/workflows/autobump.yml and there's https://github.com/Homebrew/actions/pull/495 for that.

**Comment by chenrui333** [comment]
I see, somehow I thought this is also the one used by brew bot. Closing it then.

**Pull request closed without merging**
