### PR TITLE
Upgrade CUDA to v8.0.51

### PR DESCRIPTION
**Pull request by Saklad5**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit —download {{cask_file}}` is error-free.
- [x] `brew cask style —fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

Fix URL in CUDA Cask

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Reverting in https://github.com/caskroom/homebrew-cask/pull/26754, in light of https://github.com/caskroom/homebrew-cask/issues/26752.

**Comment by Saklad5** [comment]
Sorry about that. The bizarre thing is that the Cask-installed CUDA on my computer updated itself to 8.0.51.

**Comment by Saklad5** [comment]
It looks like the CUDA Toolkit contains the CUDA driver, but for some reason the CUDA driver was updated and the CUDA Toolkit (and presumably the CUDA driver it contains) was not. I have no idea we should go about handling this.

Actually, why is this in homebrew-cask instead of homebrew-core in the first place? It isn’t really a GUI application.

**Comment by Saklad5** [comment]
By the way, [it appears the compiler portion of CUDA Toolkit 8 won’t work with Xcode 8](https://developer.nvidia.com/cuda-downloads). That will likely affect almost everyone downloading this.

**Comment by vitorgalvao** [comment]
> Actually, why is this in homebrew-cask instead of homebrew-core in the first place? It isn’t really a GUI application.

Is it open-source?

**Pull request merged**
