### PR TITLE
Update scrutiny from 9.8.0 to 9.8.1

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by suschizu** [comment]
hey @vitorgalvao  - do you perhaps have any idea why I'm 3 commits ahead in git?
it always happens after I make a unity family update :/
I tried to delete the unity branch but nothing changed - just happens when I use cask-repair 

```
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
work@Brigittes-MacBook-Pro homebrew-cask % git status         
On branch master
Your branch is ahead of 'origin/master' by 3 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

**Comment by vitorgalvao** [comment]
@suschizu What’s the output of `git log --graph --pretty=format":%h%d%s"`? That should give a clue to which commits are ahead, and to the problem.

**Comment by suschizu** [comment]
thanks @vitorgalvao - here are the first 10 lines of the output:

```
work@Brigittes-MacBook-Pro homebrew-cask % git log --graph --pretty=format":%h%d%s"
* 09dcba426e (HEAD -> master)Revert "Update unity-ios-support-for-editor from 2019.3.13f1,d4ddf0d95db9 to 2019.4.1f1,e6c045e14e4e"
* 067e810f1dUpdate unity-ios-support-for-editor from 2019.3.13f1,d4ddf0d95db9 to 2019.4.1f1,e6c045e14e4e
* bc305e384e (origin/master, origin/HEAD)Update fastrawviewer from 1.5.7.1636 to 1.6.0.1639 (#84911)
* 6640285e12Update brave-browser.rb (#84909)
* 197ed9aa8cUpdate 1password-cli from 1.1.0 to 1.1.1 (#84908)
* b66bec8081Update betterzip from 5.0 to 5.0.1 (#84905)
* 6a196b0b45Update podman fron 1.9.3 to 2.0.0 (#84858)
* bbf7bcb0a7Update hey from 1.0.5 to 1.0.6 (#84900)
* 65282ead3bUpdate integrity from 9.7.1 to 9.8.1 (#84894)
* 2e6b5f2b9dUpdate meteorologist from 3.3.4 to 3.4.0 (#84898)

```

**Comment by vitorgalvao** [comment]
Weird, the top commits are a change that was made and a revert t that change. Do you recognise the revert (i.e. was it something you did?).

**Comment by suschizu** [comment]
>  Do you recognise the revert
yes - this was a desperate attempt to get rid of this branch 😬 went wrong unfortunately

**Comment by vitorgalvao** [comment]
Doing `git reset origin/HEAD --hard` should bring you up to base.

**Comment by suschizu** [comment]
yeah - @vitorgalvao - cask-repair runs correctly 😁  
many thanks!

**Pull request merged**
