### PR TITLE
Update securesafe.rb to the latest version

### PR DESCRIPTION
**Pull request by dswiss-desktop-app**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by dswiss-desktop-app** [comment]
uninstall pkgutil updated with the new MacFUSE package names

**Comment by dswiss-desktop-app** [comment]
Added the missing Core pkg to the uninstall list

**Comment by dswiss-desktop-app** [comment]
added io.macfuse.installer.components.core to the uninstall list

**Comment by miccal** [comment]
Just trying something ...

**Comment by miccal** [comment]
Thank you @dswiss-desktop-app.

**Comment by dswiss-desktop-app** [comment]
Hi Miccal,

Yes, that seems to do the trick.

Thanks and regards,
Maciej

From: Miccal Matthews ***@***.***>
Reply to: Homebrew/homebrew-cask ***@***.***>
Date: Thursday, 22 July 2021 at 03:35
To: Homebrew/homebrew-cask ***@***.***>
Cc: Maciej Kwiatkowski ***@***.***>, Author ***@***.***>
Subject: Re: [Homebrew/homebrew-cask] Update securesafe.rb to the latest version (#108983)


Just trying something ...

**Pull request merged**
