### PR TITLE
Updated opera version to 40.0.2308.75

### PR DESCRIPTION
**Pull request by ananthulasrikar**
Updated from the older version of Opera 39.0.2256.48 to 40.0.2308.75

### CODE REVIEW

**Comment by vitorgalvao** [comment]
There was a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) when you submitted. It must be filled.

If you were not presented a template, you may have submitted via a CLI tool (likely [`hub`](https://hub.github.com/)). It that was the case, you may wish to see if the tool has a way to let you use the template (`hub` [is working on it](https://github.com/github/hub/issues/1118)).

In either case, please [refer to the template](https://raw.githubusercontent.com/caskroom/homebrew-cask/master/.github/PULL_REQUEST_TEMPLATE.md) and update your comment.

Also, this has merging conflicts.

**Comment by ananthulasrikar** [comment]
### Checklist

- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download opera` is error-free.
- [x] `brew cask style --fix opera` left no offenses.

Additionally, when **adding a new cask**:

- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install opera` worked successfully.
- [x] `brew cask uninstall opera` worked successfully.

**Comment by vitorgalvao** [comment]
You are not adding a new cask, don’t fill that section.

You’re also including changes to virtualbox that aren’t relevant. One cask per PR, please. Remove virtualbox for this.

**Comment by ananthulasrikar** [comment]
Can i please know how do i remove it ? Or shall i close this and send a new PR ?

**Comment by vitorgalvao** [comment]
You can do it on a new one. It’s fine.

**Comment by ananthulasrikar** [comment]
I see its already updated by some one.

**Pull request closed without merging**
