### PR TITLE
outfox 0.5.0-pre042,20231224 (new cask)

### PR DESCRIPTION
**Pull request by p-linnane**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by p-linnane** [comment]
Would appreciate your eyes on this livecheck @samford 🙏

**Comment by samford** [comment]
> Would appreciate your eyes on this livecheck

Hmm, there's quite a bit of variation in both the tag and filename between releases.

Recent tags are like: `OF5.0.0-042`, `OF4.19.0`, `OF4.9.9HF3`, `OF4.9.7GG` (also pre-release `OF4.8.0-Final` and `OF4.6.0-rc3`)

Recent filename prefixes: `OutFox-alpha`, `OutFox`, `OutFox-LTS`, `OutFox-5.3.0-alpha`, `StepManiaOutFox`, `Stepmania-Outfox-Alpha`, `Stepmania-Outfox-Alpha-NIGHTLY` (also a pre-release `OutFox-AlphaV`)

Recent filename versions: `0.5.0-pre042`, `0.4.19.LTS` (and `0.4.18.1.LTS`), `0.4.18`, `0.4.16.0HF2`, `0.4.14.1HF`, `4.9.9HF3b`, `4.9.7GG` (also a pre-release `4.6RC3`)

Recent filename middle parts: `MacOS-universal`, `MacOS`, `MacOS-HF1`, `MacOS-Intel`, `MacOS-M1`, `macOS-Universal`, `macOS-Universal-Serenity` (also a pre-release `MACOSX`)

Filename date suffixes all use a `date-20221026` format, at least.

-----

We can't reliably use the filename version (e.g., `0.5.0-pre042`) to generate the tag (e.g., `OF5.0.0-042`) since upstream isn't consistent about tag and filename formats (or consistency between the two for a given release), so I think we're going to have to include the tag in the `version` as well.

If we want this to even stand a chance of being `bump`able, we would seemingly have to include all the parts above where there's any variation, which means that we would basically include the tag and almost all of the filename without a few delimiters. Something like `version "0.5.0-pre042,OF5.0.0-042,OutFox-alpha,MacOS-universal-date-20231224"` (i.e., filename version, tag, filename prefix, filename suffix).

Thoughts on this? Once we decide on an approach, I can push some changes (if you would like).

**Comment by p-linnane** [comment]
>If we want this to even stand a chance of being bumpable, we would seemingly have to include all the parts above where there's any variation, which means that we would basically include the tag and almost all of the filename without a few delimiters. Something like version "0.5.0-pre042,OF5.0.0-042,OutFox-alpha,MacOS-universal-date-20231224" (i.e., filename version, tag, filename prefix, filename suffix).

Seems painful, but if it's the only way then it'll have to work. I'll keep an eye on it over time to see how the filename changes. If it ends up being consistent for a while, I'll simplify it..

**Comment by samford** [comment]
One other issue that I forgot to mention is that they previously used a 4.13.0 version format but then they switched to the current 0.4.14 format, so livecheck will treat the older releases as newer until they're pushed out of the API response. Until then, I had to restrict the JSON data to the first ten releases (that's the most we can check before running into an older version at the moment).

**Comment by p-linnane** [comment]
Thank you so much @samford! 🙇

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
