### PR TITLE
Update pyfa from 2.27.0 to 2.28.1

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
am i missing something? i thought when using the approve-workflow, it should always get merged?

**Comment by ran-dall** [comment]
> am i missing something? i thought when using the approve-workflow, it should always get merged?

I think if we `force-push` it throws things off, maybe? @reitermarkus

**Comment by vitorgalvao** [comment]
>  thought when using the approve-workflow, it should always get merged?

The self-approving workflow only allows you to approve your own PR.

After that, anyone can merge. If we wait a short while, the workflow that auto-merges accepted PRs kicks in. But if tests don’t pass, neither we nor the workflow can merge.

In this case, an unrelated cask was failing `audit`. The cask seems OK now, so I’ve retriggered the tests.

@claui @reitermarkus This is the second time today a cask with `url do` prevents other casks from being merged. I get wanting to `audit` every cask every time, but unless `audit` cuts some slack to `url do` casks, this might keep happening.

**Comment by core-code** [comment]
> I get wanting to audit every cask every time

whats the upshot here? sounds fine for code-changes but for cask-PRs i only see downsides

**Comment by vitorgalvao** [comment]
> whats the upshot here? sounds fine for code-changes but for cask-PRs i only see downsides

Thought more about it and agree. Considering merging is so restrictive now (hence harder for mistakes to get through), the downside is bigger, especially when it can happen by a temporary failure.

**Comment by core-code** [comment]
it is already resolved: https://github.com/Homebrew/homebrew-cask/pull/89182

**Pull request merged**
