### PR TITLE
Update aws-vault from 6.3.1 to 6.4.0

### PR DESCRIPTION
**Pull request by Moulick**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by Moulick** [comment]
Is aws-vault duplicated in cask and formula ? https://github.com/Homebrew/homebrew-core/pull/93347

**Comment by amadejpapez** [comment]
> Is aws-vault duplicated in cask and formula ? [Homebrew/homebrew-core#93347](https://github.com/Homebrew/homebrew-core/pull/93347)

After your comment, I was interested into seeing how many packages appear in both. Matching was done based on the file name and I assume most are actually installing different things in cask and in formula. So I do not know how useful this list may be, but as I already have it why not share it if anyone more familiar maybe spots something. :)

<details>
<summary>List</summary>

angband.rb
appium.rb
archiver.rb
atlantis.rb
aws-vault.rb
bee.rb
blitz.rb
brightness.rb
brook.rb
ckan.rb
cmake.rb
cocoapods.rb
crunch.rb
cutter.rb
dash.rb
datasette.rb
davmail.rb
docker.rb
dosbox-x.rb
dosbox.rb
dotnet.rb
doxygen.rb
emacs.rb
enigma.rb
fetch.rb
flow.rb
flume.rb
flux.rb
fontforge.rb
fs-uae.rb
gitup.rb
handbrake.rb
hey.rb
igv.rb
ipfs.rb
jasper.rb
julia.rb
jump.rb
jupyterlab.rb
kawa.rb
kite.rb
knock.rb
lab.rb
lepton.rb
lilypond.rb
lynx.rb
macvim.rb
mame.rb
marked.rb
megacmd.rb
metabase.rb
mgba.rb
mkvtoolnix.rb
mpv.rb
namebench.rb
nano.rb
neo4j.rb
nomad.rb
noti.rb
nzbget.rb
onedrive.rb
openmsx.rb
openrct2.rb
opensc.rb
openttd.rb
platypus.rb
ppsspp.rb
puzzles.rb
r.rb
rhino.rb
scummvm.rb
silicon.rb
singularity.rb
sip.rb
snappy.rb
spark.rb
squirrel.rb
stella.rb
subnetcalc.rb
svgcleaner.rb
swift.rb
swimat.rb
syncthing.rb
tag.rb
termius.rb
unison.rb
vapor.rb
volt.rb
widelands.rb
wireshark.rb
</details>

**Comment by bevanjkay** [comment]
@Moulick Yes it is, the primary reason being that `homebrew-cask` doesn't work on Linux, so the formula is required there. However, installing `aws-vault` on MacOS as a formula results in the binary not being codesigned.

**Comment by Moulick** [comment]
I see, thanks for the info

**Pull request merged**
