### PR TITLE
Add Kerio Connect.app v9.2.5.9920

### PR DESCRIPTION
**Pull request by ahousseini**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by ahousseini** [comment]
#57078

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Make this one `kerio-connect` and the other one `kerio-connect-server`.

**Comment by ahousseini** [comment]
Ok, I'll have to wait until this PR is approved: #57695

**Comment by vitorgalvao** [comment]
You can rename it now.

**Comment by ahousseini** [comment]
I'm not able to rename:
`A file with the same name already exists. Please choose a different name and try again.`
I tried this already [https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser](https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser)

**Comment by reitermarkus** [comment]
@ahousseini, you'll have to rebase your branch onto the current master.

**Comment by vitorgalvao** [comment]
Or close the PR and open a new one, if that’s easier.

**Pull request closed without merging**
