### PR TITLE
Update tweetbot from 3.3.3,4 to 3.4.0,4

### PR DESCRIPTION
**Pull request by jabenninghoff**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by jabenninghoff** [comment]
`https://tapbots.net/tweetbot4/Tweetbot.34000.zip` is the current version in the appcast.

**Comment by jabenninghoff** [comment]
I'd suggest version `3.40,4`

**Comment by jabenninghoff** [comment]
never mind, since it passed the tests...

**Comment by vitorgalvao** [comment]
This way is better than having a few zeroes hanging loose that have to be replaced on occasion.

**Pull request merged**
