### PR TITLE
Update adguard to 1.5.3

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by gtmgianni** [comment]
[App is validly signed.](https://www.virustotal.com/#/file/62bf4e6f3aba902a0418a69a42cd3e0debc8df59c2905f0cb466285e6ef74b4b/details)
screen shot 2018-01-03 at 16 36 14

**Review by commitay — DISMISSED** [review]

**Comment by commitay** [comment]
@gtmgianni The link and screen you've posted don't match the `sha256` in the Cask.

**Comment by gtmgianni** [comment]
@commitay I tried uploading the .dmg to VirusTotal, but it wouldn’t tell me if the application within the disk image was validly signed, so I had to upload the application bundle directly. That’s what has caused the discrepancy between the SHA256s.

(https://www.virustotal.com/#/file/02d40d8f039459515e8e596edbe591cec1c77703fe49797c9215b0e7363781b8/details)[Here’s the link to the .dmg file on VirusTotal.]

**Comment by commitay** [comment]
The `sha256`s need to match, if VirusTotal can't verify the container that the `app` is distributed in please ask a maintainer to verify it locally.

```
02d40d8f039459515e8e596edbe591cec1c77703fe49797c9215b0e7363781b8  adguard--1.5.3.dmg
```
```
Executable=/Volumes/Adguard-1.5.3.release/Adguard.app/Contents/MacOS/Adguard
Identifier=com.adguard.Adguard
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=33427 flags=0x0(none) hashes=1039+3 location=embedded
Signature size=8953
Authority=Developer ID Application: Performiks OOO (N33TQXN8C7)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=29 Dec 2017 at 19:15:30
Info.plist entries=29
TeamIdentifier=N33TQXN8C7
Sealed Resources version=2 rules=13 files=430
Internal requirements count=1 size=180

/Volumes/Adguard-1.5.3.release/Adguard.app: valid on disk
/Volumes/Adguard-1.5.3.release/Adguard.app: satisfies its Designated Requirement
```

**Review by commitay — APPROVED** [review]

**Pull request merged**
