### PR TITLE
fix sha256 sum for tuxera-ntfs

### PR DESCRIPTION
**Pull request by disenchant**
```
$ brew cask install tuxera-ntfs
==> Downloading https://www.tuxera.com/mac/tuxerantfs_2015.dmg
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 4bed675786cbec9b8e80a0af2f12b7fda381b16978bf103458bc1011c8a24934
Actual: de47cbbbcd9be8241a31a7924a6840a70215300154d352f28c31d8fbb2edbf2e
File: /Library/Caches/Homebrew/tuxera-ntfs-2015.dmg
To retry an incomplete download, remove the file above.
```

### CODE REVIEW

**Comment by jawshooah** [comment]
2015 doesn't appear to be a true version number for this software. Should be changed to `version :latest` and `sha256 :no_check`.

**Comment by disenchant** [comment]
@jawshooah thanks for the input. Done.

**Comment by jawshooah** [comment]
Thank you. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by jawshooah** [comment]
Something has gone wrong here. You've included a bunch of unrelated commits.

**Comment by jawshooah** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 97902c39bd1a09c83d138604a3cddbf2dd68bea9. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
