### PR TITLE
dymo-label: add livecheck

### PR DESCRIPTION
**Pull request by khipp**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by daeho-ro** [comment]
I have tried to rebase but mistakenly to merge, sorry for annoying notifications.
I thought the CI error might be temporary and so want to refresh this.

**Comment by khipp** [comment]
@daeho-ro No worries, thanks for trying to help! ❤️

**Comment by daeho-ro** [comment]
Well, intermediate certificate is expired for the download url.

https://www.sslshopper.com/ssl-checker.html#hostname=download.dymo.com

**Comment by khipp** [comment]
It seems the request is being redirected, but it works locally:

```console
$ brew livecheck --cask dymo-label
dymo-label: 1.4.6.60 ==> 1.4.6.60
```

I added a comment as we did for `yandex-cloud-cli`.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
