### PR TITLE
Add Adobe Photoshop CC 2015

### PR DESCRIPTION
**Pull request by cprecioso**

### CODE REVIEW

**Comment by cprecioso** [comment]
I can produce some more formulae for Adobe apps if it's ok

**Comment by vitorgalvao** [comment]
This requires and `uninstaller`. @zacs might be able to help you there.

**Comment by cprecioso** [comment]
This is quite difficult, as the user-facing uninstaller name is an alias with a localized name (e.g.: `/Applications/Utilities/Adobe Installers/Desinstalar Adobe Photoshop CC 2015` in Spanish), thus impractical to hard-code.

The actual uninstaller is located (in my system) at `/Library/Application Support/Adobe/Uninstall/{2614BC86-757D-4293-9E25-E4E16F370A9E}/{2614BC86-757D-4293-9E25-E4E16F370A9E}.app`, and I don't know if the GUID is specific for my machine, varies between languages or if it's shared among all Photoshop CC 2015 installations in the world.

Hence, I don't know how to approach this scripted uninstallation. I could just write the actual uninstaller path and hope no one reports an issue.

**Comment by vitorgalvao** [comment]
[Here’s one of the casks](https://github.com/caskroom/homebrew-versions/blob/master/Casks/adobe-photoshop-cs5.rb) devised by @zacs.

**Comment by cprecioso** [comment]
Does the uninstaller have to be silent?

**Comment by vitorgalvao** [comment]
It cannot call a GUI or require user input.

**Comment by zacs** [comment]
Not all Adobe uninstallers are created equal. It seems that the "Collections" all have an uninstall XML that can be called for silent operation (see the `uninstall_preflight` stanza in [the original Adobe formulae](https://github.com/caskroom/homebrew-versions/blob/master/Casks/adobe-design-standard-cs6.rb) for examples). This is the only way I've seen to uninstall silently.

**Comment by cprecioso** [comment]
Got it! The DMG comes with a folder named `Deployment`, that aptly contains a bunch of deployment files, one for each language. Each one of these can be used to trigger the installation in this way (example for Spanish install, `pwd` is the root of the dmg):

```sh
sudo "Adobe Photoshop CC 2015/Install.app/Contents/MacOS/Install" --mode=silent --deploymentFile="Adobe Photoshop CC 2015/Deployment/es_ES_Deployment.xml"
```

However, you can also use **this same installer** (not the uninstaller) to trigger the uninstallation, by simply feeding it this XML:

```xml
```

So, the course of action would be:

**Install**
1. Save the contents of the dmg
2. Run the installer in silent mode with a deployment file (English by default)

**Uninstall**
1. Locate deployment file and replace `install` for `remove`
2.

**Comment by cprecioso** [comment]
Got it! The DMG comes with a folder named `Deployment`, that aptly contains a bunch of deployment files, one for each language. Each one of these can be used to trigger the installation in this way (example for Spanish install, `pwd` is the root of the dmg):

```sh
sudo "Adobe Photoshop CC 2015/Install.app/Contents/MacOS/Install" --mode=silent --deploymentFile="Adobe Photoshop CC 2015/Deployment/es_ES_Deployment.xml"
```

However, you can also use **this same installer** (not the uninstaller) to trigger the uninstallation, by simply feeding it this XML, which is basically the same one as the included in the dmg, but with the properties changed to keep user preferences and the action set to `remove` instead of `install`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Deployment>
	<Properties>
		<Property name="removeUserPrefs">0</Property>
		<Property name="mediaSignature">{2614BC86-757D-4293-9E25-E4E16F370A9E}</Property>
	</Properties>
	<Payloads>
		<Payload adobeCode="{2614BC86-757D-4293-9E25-E4E16F370A9E}">
			<Action>remove</Action>
		</Payload>
	</Payloads>
</Deployment>
```

So, the course of action would be:

**Install**
1. Save the contents of the dmg
2. Run the installer in silent mode with a deployment file (English by default, which is `Adobe Photoshop CC 2015/Deployment/en_US_Deployment.xml`)

**Uninstall**
1. Write the uninstall XML to disk (it would have to be hard-coded 😕)
2. Feed it to the installer previously saved

Not very difficult, but I lack the necessary knowledge to make this work in both ruby and cask. Could somebody help?

**Comment by cprecioso** [comment]
I've updated the PR so cask uses the silent install and uninstall, but I don't know how to create the `uninstall.xml` file.

**Comment by zacs** [comment]
It seems like the `uninstall.xml` should be created during the install. I'm assuming that in brew-cask it should get saved to the app's Caskroom, so it can be easily called for uninstall later. @vitorgalvao is there precedent for creation of files like this (and where to save them to)?

**Comment by Ngrd** [comment]
The file itself could be created for example in `preflight` stanza like this:
```ruby
  preflight do
    file = File.open "#{staged_path}/uninstall.xml", 'w'
    file.puts '<?xml version="1.0" encoding="utf-8"?>
<Deployment>
    <Properties>
        <Property name="removeUserPrefs">0</Property>
        <Property name="mediaSignature">{2614BC86-757D-4293-9E25-E4E16F370A9E}</Property>
    </Properties>
    <Payloads>
        <Payload adobeCode="{2614BC86-757D-4293-9E25-E4E16F370A9E}">
            <Action>remove</Action>
        </Payload>
    </Payloads>
</Deployment>'
    file.close
  end
```
and call it during the uninstall:
```ruby
uninstall :script => 'Adobe Photoshop CC 2015/Install.app/Contents/MacOS/Install',
          :args => %w[--mode=silent --deploymentFile="#{staged_path}/uninstall.xml"]
```
Not the best solution though.

**Comment by cprecioso** [comment]
Why not in `uninstall_preflight`? It's not needed until then, why pollute the folder?

**Comment by Ngrd** [comment]
I fully agree, that `uninstall_preflight` could be used. I just suggested an example.

**Comment by cprecioso** [comment]
Also, just realized the name of the cask should really include the Photoshop version, i.e.: `adobe-photoshop-cc-2015`. If not, what would happen when Adobe releases PS 2016, the formula is updated and someone tries to uninstall their previously installed PS 2015 only to find that that uninstallation procedure has moved to `adobe-photoshop-cc-2015` and they're stuck with `adobe-photoshop-cc`, that uninstalls PS 2016?

**Comment by Ngrd** [comment]
In my opinion, there would be much better to avoid `installer :script` and `uninstall :script` in this case. Tha main reason is that `#{staged_path}` is not available there. At least if it even will work, the audit will always output warning messages. Those should be completely replaced by `preflight` and `uninstall_preflight`.

If considering how the user will be able to remove the previous version when it updates to 2016, then I'm thinking that it would much reasonable to use `version :latest` and `sha256 :no_check` instead of fixed ones. The problem will be solved at least from a perspective that the user won't be able to install the cask without uninstalling it first. However, he can always run the installation with the `--force` flag if he really wants to.

Additionally, I'm also thinking about the `mediaSignature` and `adobeCode` value. I don't like the idea that it's hardcoded in *uninstall.xml*. What happens if it changes? Of course, we could even extract it from `en_US_Deployment.xml` each time, but why to make thing more complicated? That is the reason why I'm thinking that the *uninstall.xml* file should be created during the installation. In this case, even if we update the cask with the hardcoded value, it won't affect the users who already have installed the cask before and can safely remove their current version even using the new updated cask with completely different hardcoded value.
```ruby
cask :v1 => 'adobe-photoshop-cc' do
  version :latest
  sha256 :no_check

  url 'http://trials3.adobe.com/AdobeProducts/PHSP/16/osx10/Photoshop_16_LS20.dmg',
    :user_agent => :fake,
    :cookies => { 'MM_TRIALS' => '1234' }
  name 'Adobe Photoshop CC 2015'
  homepage 'https://www.adobe.com/products/photoshop.html'
  license :commercial

  preflight do
    file = File.open "#{staged_path}/uninstall.xml", 'w'
    file.puts '<?xml version="1.0" encoding="utf-8"?>
<Deployment>
    <Properties>
        <Property name="removeUserPrefs">0</Property>
        <Property name="mediaSignature">{2614BC86-757D-4293-9E25-E4E16F370A9E}</Property>
    </Properties>
    <Payloads>
        <Payload adobeCode="{2614BC86-757D-4293-9E25-E4E16F370A9E}">
            <Action>remove</Action>
        </Payload>
    </Payloads>
</Deployment>'
    file.close

    system '/usr/bin/sudo', '-E', '--', "#{staged_path}/Adobe Photoshop CC 2015/Install.app/Contents/MacOS/Install", '--mode=silent', "--deploymentFile=#{staged_path}/Adobe\ Photoshop\ CC\ 2015/Deployment/en_US_Deployment.xml"
  end

  uninstall_preflight do
    system '/usr/bin/sudo', '-E', '--', "#{staged_path}/Adobe Photoshop CC 2015/Install.app/Contents/MacOS/Install", '--mode=silent', "--deploymentFile=#{staged_path}/uninstall.xml"
  end
end
```

**Comment by vitorgalvao** [comment]
> is there precedent for creation of files like this (and where to save them to)?

There is not.

I like the discussion and ideas, here, but in all honesty, and even though I don’t want to turn this into a rant, I wouldn’t be bothered if the whole Adobe family were absent from homebrew-cask (and from the whole graphic design industry as well, if I’m being honest, though that is not the point). Like in everything else they do, the (should be) simple matter of automating their install and uninstall processes is an obtuse, dumb, and suboptimal dance (not that doing it manually is pleasant, either), and is a thorn I’ve been faced with for too long.

@zacs did an amazing job with these in [caskroom/versions](https://github.com/caskroom/homebrew-versions), and I trust @Ngrd completely. I’ll support whatever solution you come up with (even if that means rejecting the cask and having someone else mount an Adobe-specific tap), as long as (if it stays in the main repos) the cask isn’t incomplete (i.e. missing `uninstall`).

**Comment by cprecioso** [comment]
Well, I agree with @Ngrd and copied his code. Tried it in my machine and both install and uninstall work just fine, totally silent. I wanted to add at least a couple more Adobe CC apps to cask as it's very practical, so it's up to @vitorgalvao if you want to merge this (and possibly more) into the main repo or if I should make a custom Adobe tap.

**Comment by vitorgalvao** [comment]
If they work, I have absolutely no quarrel with including them here. What kind of maintainer would I be if I let a personal quarrel be the sole reason to interfere with the experience of user?

@Ngrd Care to merge, if everything looks fine to you?

**Comment by Ngrd** [comment]
I think this can be merged for now. If some additional problems occur we can always make additional changes if required, but at the moment everything works quite fine.

**Comment by Ngrd** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 6a2604331f02fbd8c81c37b7146d810b95f0ba22. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
