### PR TITLE
add WeChat Work v2.7.0

### PR DESCRIPTION
**Pull request by plutotree**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Welcome.

Are you able to find an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md), like [`wechat` has](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/wechat.rb#L6)?

**Comment by plutotree** [comment]
> Welcome.
> 
> Are you able to find an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md), like [`wechat` has](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/wechat.rb#L6)?

I've tried, but not find.  The Release note is inside the homepage.

**Comment by vitorgalvao** [comment]
@plutotree Thank you for looking.

**Comment by core-code** [comment]
we already had a cask for this, named 'wxwork'. its exactly the same thing.

**Comment by vitorgalvao** [comment]
> we already had a cask for this, named 'wxwork'. its exactly the same thing.

Trouble with non-latin characters — they don’t adhere to the token reference!

We currently have more `wechat*` casks than `wx*`, so lets keep the former.

**Comment by core-code** [comment]
no problem, i think i'll be able to catch most of these cases ;)

**Pull request merged**
