### PR TITLE
Update musixmatch to 0.21.13

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
not especially happy to convert this to versioned, but the cask didn't work as it was anymore

**Comment by vitorgalvao** [comment]
Can’t even verify locally. Download is unbearably slow.

**Comment by core-code** [comment]
i had the 'freezing' problem only before the changes i've added. the cask repair only took half a minute

**Comment by core-code** [comment]
not sure what is going on here, the download takes 8 seconds here

**Comment by vitorgalvao** [comment]
Got it locally.

**Comment by core-code** [comment]
we could use this as an appcast but there has been some resistance to adding 'dependencies to external servers': 

http://www.corecode.io/cgi-bin/check_urls/check_url_filename.cgi?url=http://download-app.musixmatch.com/download/osx

**Pull request merged**
