### PR TITLE
Changed Boom version to latest

### PR DESCRIPTION
**Pull request by glimpsed**
Also added download for the latest version.

### CODE REVIEW

**Comment by fanquake** [comment]
Can you update the commit message to include the app being changed

**Comment by glimpsed** [comment]
Sorry, corrected the commit message.

**Comment by vitorgalvao** [comment]
@glimpsed What @fanquake meant was the commit message itself (i.e. [amending](http://stackoverflow.com/a/179147/1661012) it). What you did was change the title of the issue, which has no influence in the repo itself.

**Comment by glimpsed** [comment]
Everything should be OK now. Thanks for the explanation @vitorgalvao :)

**Comment by vitorgalvao** [comment]
Looks good. Thank you.

**Pull request merged**
