### PR TITLE
Update unity-standard-assets to 2018.1.9f2

### PR DESCRIPTION
**Pull request by taraspos**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Review by victorpopkov — APPROVED** [review]

**Comment by vitorgalvao** [comment]
Please remove the comment from this and other PRs.

People who typically update these already do them all at once, and the others never read the comments (we’ve had similar comments on other casks, in the past).

**Comment by Trane9991** [comment]
@vitorgalvao 
yeah, but currently they all are not the same version :( 
Are you sure it worth removing?

Also, what about the link https://public-cdn.cloud.unity3d.com/hub/prod/releases-darwin.json?
Reason why I mentioned it, is becuse it is not a public knowledge and I spent couple hours googling before I was able to find the valid infromation about versions and download links.

**Comment by vitorgalvao** [comment]
> Are you sure it worth removing?

Yes.

> Also, what about the link https://public-cdn.cloud.unity3d.com/hub/prod/releases-darwin.json?

That one is pretty good. You can replace the `appcast` link with it.

**Review by vitorgalvao — APPROVED** [review]
Changes for the other PRs should be of this form.

Thank you for the contribution and finding that JSON!

**Comment by Trane9991** [comment]
Done!

**Pull request merged**
