### PR TITLE
hookmark 5.1.1

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by krehel** [comment]
Suspect the issue causing failure is the same as #146223

**Comment by p-linnane** [comment]
@samford Is https://github.com/Homebrew/homebrew-cask/labels/ci-skip-livecheck not working in `homebrew-cask`?

**Comment by reitermarkus** [comment]
The URL reachability check is separate from `livecheck` audits.

**Comment by bevanjkay** [comment]
It's bundled up in the `audit_https_availability` check.

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
