### PR TITLE
Update protonmail-bridge from 1.3.3 to 1.2.7

### PR DESCRIPTION
**Pull request by sanpoChew**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by sanpoChew** [comment]
I'm a bit confused by the failures because it's the exact opposite of what I get locally
image
I wonder if they've released different versions in different regions or something?

**Comment by vitorgalvao** [comment]
It’s pretty confusing from that changelog what’s a beta and what’s not. Either way, the URL is static and always gets whatever they deem to be the latest, so whatever version we have written in the cask is informative and little else.

**Comment by sanpoChew** [comment]
but I'm getting checksum failures every time I run `brew upgrade` because they don't match when I download from the URL, and I ran `cask-repair` to generate this PR which generated a checksum which matches what I get from the URL.

Going here https://protonmail.com/bridge/install also says 1.2.7 is what is available for download.

**Comment by miccal** [comment]
> Going here https://protonmail.com/bridge/install also says 1.2.7 is what is available for download.

@sanpoChew for me it shown 1.3.3:

Screen Shot 2020-08-20 at 05 42 35

**Comment by sanpoChew** [comment]
@miccal oh well that's pretty weird, guess they release beta versions to a random group of users?

**Comment by rpsu** [comment]
the [JSON file](https://protonmail.com/download/current_version_darwin.json) gives me 1.3.3 regardless if I am logged in or not.

**Pull request closed without merging**
