### PR TITLE
Add MailSuite v2021.8.1

### PR DESCRIPTION
**Pull request by straxhaber**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

There are two issues I don't know how to resolve:

1. I get this error: `Version '2021.8.1' differs from '' retrieved by livecheck.`
2. I don't know how to automatically uninstall/install. This developer provides a welcome screen you use to install a Apple Mail plugin. This plugin is very widely used, so it should be included in Homebrew.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @straxhaber.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by straxhaber** [comment]
@miccal I am not sure how to do that. Do I just look for anything on the machine that it installs and list it?

**Comment by SMillerDev** [comment]
The linked documentation has this section: https://docs.brew.sh/Cask-Cookbook#zap-creation that might help

**Comment by neutric** [comment]
@straxhaber Would you like help?

**Comment by straxhaber** [comment]
Hi @neutric @miccal - yes, I'd appreciate the help. Sorry for the late reply. I was hoping to figure it out on my own but was unsuccessful.

**Comment by neutric** [comment]
```
  zap trash: [
    "~/Library/Application Support/com.smallcubed.suite",
    "~/Library/Caches/com.smallcubed.suite",
    "~/Library/Containers/com.smallcubed.mailsuite",
    "~/Library/HTTPStorages/com.smallcubed.suite",
    "~/Library/LaunchAgents/com.smallcubed.suite.helper.plist",
    "~/Library/Mail/Bundles/SmallCubed MailSuite.mailbundle",
    "~/Library/Preferences/com.smallcubed.suite.plist",
    "~/Library/WebKit/com.smallcubed.suite",
  ]
```

**Comment by straxhaber** [comment]
Hi @miccal I think I've got everything working on my latest commit. What do I need to do to get this issue reopened so the pull request can be merged?

**Comment by miccal** [comment]
@straxhaber for some reason I am not able to re-open this PR, so please just submit a new one.

**Pull request closed without merging**
