### PR TITLE
mixxx 2.4.1

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by krehel** [comment]
Going to push some updates

**Comment by samford** [comment]
> Going to push some updates

I was just about to push the same changes but you beat me to it 😆

**Comment by krehel** [comment]
Yeah, I picked the lowest macOS version for the `depends_on`.  It's going to be angry no matter what 😅

**Comment by samford** [comment]
Unless there's a reason not to, this is what I was using to address it locally:

```
  on_arm do
    depends_on macos: ">= :big_sur"
  end
  on_intel do
    depends_on macos: ">= :sierra"
  end
```

**Comment by krehel** [comment]
I'll add and push then.

**Review by samford — APPROVED** [review]

**Pull request merged**
