### PR TITLE
Add symlinks to AWS Session Manager cask

### PR DESCRIPTION
**Pull request by carlfugate**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @carlfugate.

**Review by miccal — APPROVED** [review]

**Comment by bevanjkay** [comment]
@miccal Should the `system` command be inside of a postflight install block here?

**Comment by miccal** [comment]
No, the `system` block is not necessary.

Both Intel and Arm packages install into `/usr/local` and having arch-specific downloads automatically solves the problem of the symlinks.

**Comment by carlfugate** [comment]
> @miccal Should the `system` command be inside of a postflight install block here? 

I must confess this was my very first time even working with formulas/casks and couldn't find a good example of how to do this.  I completely agree it should be a post install process. If you can help point me to an example I'm happy to change it.

**Comment by bevanjkay** [comment]
@miccal Oh I didn't see you had removed the `system` command. I must have been seeing a cached version of the file. Thanks!

**Comment by carlfugate** [comment]
First, thanks for all of the improvements @miccal as this is in much better shape.  I'm curious about the removal of the symlink creation (which was my whole initial purpose of the change) as well as leaving the binary install location to /usr/local instead of using the Homebrew prefix.

**Pull request merged**
