### PR TITLE
Upgrade Thunderbird.app to 78.0

### PR DESCRIPTION
**Pull request by kommtzeitkonrad**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by core-code** [comment]
where are you taking version number 78 from? the latest is 68.10.0:
https://www.thunderbird.net/en-US/thunderbird/releases/

**Comment by kommtzeitkonrad** [comment]
> where are you taking version number 78 from?

https://github.com/Homebrew/homebrew-cask/blob/0fee3bc4116335acdf1d7c552c9bc7889ed4ae9b/Casks/thunderbird.rb#L84

**Comment by core-code** [comment]
thanks but upload to ftp servers does not constitute an official release - we'll have to wait until the release is officially done.

**Comment by kommtzeitkonrad** [comment]
> thanks but upload to ftp servers does not constitute an official release - we'll have to wait until the release is officially done.

Well, it is [the official ftp from Mozilla](https://ftp.mozilla.org). The [directory is called `release`](https://ftp.mozilla.org/pub/thunderbird/releases/), neither is it called [`nightly`](https://ftp.mozilla.org/pub/thunderbird/nightly/) nor is it called [`candidates`](https://ftp.mozilla.org/pub/thunderbird/candidates/). It is also not marked as a [beta release](https://ftp.mozilla.org/pub/thunderbird/releases/78.0b4/).

**Comment by core-code** [comment]
i don't question that is from mozilla. but again, an upload does not constitute an official release. mozilla and other vendors have been known to re-roll their upload many times in the past, and there is no reason to believe that it won't happen again. 
its not official till its officially announced.

**Comment by kommtzeitkonrad** [comment]
> i don't question that is from mozilla. but again, an upload does not constitute an official release. mozilla and other vendors have been known to re-roll their upload many times in the past, and there is no reason to believe that it won't happen again.
> its not official till its officially announced.

Ok, I understand that. Will bump this when the release notes are out. Deal?!

**Comment by kommtzeitkonrad** [comment]
https://www.thunderbird.net/en-US/thunderbird/78.0/releasenotes/

**Comment by core-code** [comment]
thanks!

**Comment by ran-dall** [comment]
@core-code The website now defaults to `78.0`

**Comment by core-code** [comment]
thanks, good job

**Pull request merged**
