### PR TITLE
Remove phocus

### PR DESCRIPTION
**Pull request by commitay**
App download is behind a login page.

http://www.hasselblad.com/support/manuals/software-current/

### CODE REVIEW

**Review by victorpopkov — APPROVED** [review]

**Comment by vitorgalvao** [comment]
Note that the download link being behind a download page is only a problem when `homepage` and `url` have different domains. That is so a malicious actor can’t simply point the cask to a malicious source without users being able to verify with ease.

When they have the same domain, like in this case, it is fine. A user can look at the cask and be confident the `url` is legitimate (a malicious actor would have to target the upstream domain; which is harder to do and keep up).

**Comment by commitay** [comment]
Just for clarification: are we okay with making the app available to users who would otherwise have to register to download it?

**Comment by vitorgalvao** [comment]
Unless upstream objects, yes.

Naturally, if you disagree we can discuss it. I initially conceived the rule, but am not attached to it or anything. I could certainly be persuaded otherwise.

**Comment by commitay** [comment]
> Naturally, if you disagree we can discuss it. I initially conceived the rule, but am not attached to it or anything. I could certainly be persuaded otherwise.

No disagreement from me. Just wanted to clarify as I've already rejected a cask request for being behind a login/registration page. I'll take another look at it to see if it uses the same domain for `homepage` and `url`.

> Note that the download link being behind a download page is only a problem when `homepage` and `url` have different domains.

I'll add this to the docs somewhere.

____

After adding `anka-run` I realised it was behind a login page and removed it (https://github.com/caskroom/homebrew-cask/pull/35801), I'll re-add it.

**Comment by vitorgalvao** [comment]
> I'll add this to the docs somewhere.

It’s already in the docs. See “walled builds” in the “adding a cask” document.

As for `anka`, that one was also fine, as I recall, as you found a page with download links that was not behind registration.

**Comment by commitay** [comment]
> It’s already in the docs. See “walled builds” in the “adding a cask” document.

Oops, sorry  @vitorgalvao. Thank you for your explanations and patience, they are appreciated. 🥇

**Pull request closed without merging**
