### PR TITLE
netspot 4.0.4453

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by krehel** [comment]
The livecheck URL in the `Info.plist` does not appear to be active yet.

```
The livecheck URL https://cdn.netspotapp.com/download/Mac/netspot4-appcast.xml is not reachable (HTTP status code 404)
```

**Comment by daeho-ro** [comment]
`netspot3-appcast.xml` is updated but not exist `netspot4-appcast.xml`. Upstream may not change the url :)

**Comment by krehel** [comment]
Per my comment, the URL mentioned is the in the `Info.plist` of this version.

**Comment by bevanjkay** [comment]
@krehel I would be ok to use `skip-livecheck` here, hopefully the new appcast comes online soon, but we can unblock the release for now.

**Review by bevanjkay — APPROVED** [review]

**Comment by krehel** [comment]
Yeah that's fine. I figured I'd let it sit for a short while to see if it comes online. We may have to be aware that livecheck could be broken if this URL doesn't come online.

**Comment by bevanjkay** [comment]
@krehel I have put it on my watchlist, so I'll keep an eye on it for a bit.

**Pull request merged**
