### PR TITLE
Update daily-english-listening.rb from 9.1.6 to 9.1.7

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by suschizu** [comment]
```
audit for daily-english-listening: failed
 - download not possible: Download failed on Cask 'daily-english-listening' with message: Download failed: https://static.frdic.com/pkg/ting_en/ting_en.dmg
 - The URL https://static.frdic.com/pkg/ting_en/ting_en.dmg is not reachable
 - The URL https://static.frdic.com/pkg/ting_en/latest-mac.yml is not reachable
 - appcast at URL 'https://static.frdic.com/pkg/ting_en/latest-mac.yml' offline or looping
```

**Comment by ran-dall** [comment]
@suschizu Did you try to the local check?

**Comment by ran-dall** [comment]
@suschizu @core-code I'm getting this same error too with the local check; and I've fixed my local `cURL` already. So I don't think this the same SSL problem.

```shell
$ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/developer/bin/cask-pr-local-check https://github.com/Homebrew/homebrew-cask/pull/83897
==> Downloading https://static.frdic.com/pkg/ting_en/ting_en.dmg
curl: (22) The requested URL returned error: 404 Not Found

audit for daily-english-listening: failed
 - download not possible: Download failed on Cask 'daily-english-listening' with message: Download failed: https://static.frdic.com/pkg/ting_en/ting_en.dmg
 - The URL https://static.frdic.com/pkg/ting_en/ting_en.dmg is not reachable (HTTP status code 404)
 - The URL https://static.frdic.com/pkg/ting_en/latest-mac.yml is not reachable (HTTP status code 404)
Error: audit failed for casks: daily-english-listening

1 file inspected, no offenses detected
```

**Comment by core-code** [comment]
thanks for the analysis. i can confirm its a separate issue.

the *weird* thing is that that these URLs work completely fine in a browser (both Safari and Chrome) but return 404 in 'curl'

**Comment by suschizu** [comment]
thanks @ran-dall - I receive exactly the same output:

```
curl: (22) The requested URL returned error: 404 Not Found
audit for daily-english-listening: failed
 - download not possible: Download failed on Cask 'daily-english-listening' with message: Download failed: https://static.frdic.com/pkg/ting_en/ting_en.dmg
 - The URL https://static.frdic.com/pkg/ting_en/ting_en.dmg is not reachable (HTTP status code 404)
 - The URL https://static.frdic.com/pkg/ting_en/latest-mac.yml is not reachable (HTTP status code 404)
Error: audit failed for casks: daily-english-listening

1 file inspected, no offenses detected 
```
do you have any idea how to fix this problem?

**Comment by ran-dall** [comment]
> do you have any idea how to fix this problem?

@suschizu No, but I think the problem is upstream because I've haven't seen this before and it's returning a `404` error. Clearly the file exists, so maybe they're doing something to filter programs like `cURL`, but that should return a `403`, not a `404` causes the file exists.

**Comment by Chandler-Lu** [comment]
Hello, could you try it again? I can download it in China and my server in US now.

**Comment by suschizu** [comment]
thanks @ran-dall & @Chand

**Comment by suschizu** [comment]
thanks @ran-dall & @Chandler-Lu

**Comment by Chandler-Lu** [comment]
hmmm, it's really strange.

**Comment by core-code** [comment]
it seems to be an issue with the user-agent:

```
 ~ %/usr/local/Cellar/curl/7.71.1/bin/curl https://static.frdic.com/pkg/ting_en/ting_en.dmg
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.17.9</center>
</body>
</html>

 ~ % /usr/local/Cellar/curl/7.71.1/bin/curl -A 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15' https://static.frdic.com/pkg/ting_en/ting_en.dmg
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.

```


@suschizu can you try adding       `user_agent: :fake,`

**Comment by core-code** [comment]
i meant adding the user agent to the URL stanza and not the appcast stanza :p

**Comment by core-code** [comment]
i've made a new PR here to avoid the 'patch failed' errors over at https://github.com/Homebrew/homebrew-cask/pull/86942

@vitorgalvao is this good enough to merge or should we delete the cask?

**Comment by vitorgalvao** [comment]
Hard to make a case for keeping it around:

```
daily-english-listening
30 days: n/a
90 days: 1 (#6382)
365 days: 14 (#5502)
Age: 279 days (added 2019, October 28)
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/86961

**Pull request closed without merging**
