### PR TITLE
Community playcover

### PR DESCRIPTION
**Pull request by hayatofujii**
PlayCover's community forked their own version, fixed some stuff and
released a new version. It seems like the original version has been marked
as private, hence the sudden disappearance.

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online playcover` is error-free.
- [X] `brew style --fix playcover` reports no offenses.

**Adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask playcover` worked successfully.
```
audit for playcover: failed
 - GitHub repository too new (<30 days old)
```
- [X] `brew install --cask playcover` worked successfully.
- [X] `brew uninstall --cask playcover` worked successfully.

### CODE REVIEW

**Comment by p-linnane** [comment]
Originally removed in #127456.

This will require `ci-skip-install`.

**Comment by bevanjkay** [comment]
Interestingly, it looks like there may be a chance that the original version of playcover could be return (although this may not be likely).
If that is the case, then we would need to be able to distinguish between the two version. So perhaps the token for this should be `playcover-unofficial` or `playcover-community`

**Comment by hayatofujii** [comment]
Makes sense to me.

There is an "official" version floating around, although just available to Patreon donors.

<sub><sup>we might have to rethink migration strategies between me.playcover.* (official) and io.playcover.* (community) data... </sup></sub>

**Comment by Depal1** [comment]
The GitHub repository is now 30 days old.

**Review by miccal — APPROVED** [review]

**Comment by JounQin** [comment]
@miccal PlayCover community has its own homebrew-tap actually, see https://github.com/PlayCover/homebrew-playcover

**Pull request merged**
