### PR TITLE
Improved version handling for java

### PR DESCRIPTION
**Pull request by scribblemaniac**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but beta belong in [caskroom/versions](https://github.com/caskroom/homebrew-versions). There’s already a PR there for a later version, waiting review.

**Comment by scribblemaniac** [comment]
This isn't beta, it's the same version as the current cask.

**Comment by vitorgalvao** [comment]
Ah, I saw the `b` and thought it was a beta because of the format in the other cask. Apologies.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 71560a810b90d6696d5bb9261a7967fc3bb941ae to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
