### PR TITLE
Added SuperSlicer Stable to Homebrew

### PR DESCRIPTION
**Pull request by lbibass**
Created SuperSlicer.rb

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Welcome, and thank you. Please add a [`zap`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md). See [`homebrew-createzap`](https://github.com/nrlquaker/homebrew-createzap) for an external project which can help.

**Review by vitorgalvao — DISMISSED** [review]

**Comment by lbibass** [comment]
Any updates on getting this pulled into the master? No worries if it's a process that takes a few days, but I just wanted to check in.

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
This is a fork. It needs to use [the correct repository](https://github.com/prusa3d/PrusaSlicer).

**Comment by lbibass** [comment]
> This is a fork. It needs to use [the correct repository](https://github.com/prusa3d/PrusaSlicer).

It technically is a fork, but it varies enough from the base code that at this point, it's an entirely different app. 

image

I think it's worth adding it to the repository.

**Comment by vitorgalvao** [comment]
Then it needs to follow the rules for naming forks in the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md). It needs to be named `supermerill-superslicer`.

**Comment by lbibass** [comment]
Looking at the documentation, it appears that the name should generally be prepended if the name conflicts. That is not the case. If that naming scheme is to be followed, then PrusaSlicer should be called Prusa-PrusaSlicer, since it's a fork of Slic3r. That's just silly, so I don't think supermerril should be prepended.

**Comment by vitorgalvao** [comment]
> it appears that the name should generally be prepended if the name conflicts. That is not the case.

No, it should be prepended if it can be mistaken for the main one. Which in this case, it can.

Also, it doesn’t conflict *yet*. If someone adds the original, it would.

> If that naming scheme is to be followed, then PrusaSlicer should be called Prusa-PrusaSlicer, since it's a fork of Slic3r.

No, it shouldn’t, because *the app*, which regulates the cask’s token, is named differently.

Please do the rename. It won’t be merged otherwise.

**Comment by lbibass** [comment]
> 
> No, it should be prepended if it can be mistaken for the main one. Which in this case, it can.

Sorry, I'm confused. Are you saying that Superslicer can be confused for Prusaslicer, even though they have entirely different names?

> Also, it doesn’t conflict _yet_. If someone adds the original, it would.

Which original are you referring to? Are you referring to PrusaSlicer? It is already in homebrew-cask. 

> > If that naming scheme is to be followed, then PrusaSlicer should be called Prusa-PrusaSlicer, since it's a fork of Slic3r.
> 
> No, it shouldn’t, because _the app_, which regulates the cask’s token, is named differently.

The app is also named differently between superslicer and prusaslicer. 

> Please do the rename. It won’t be merged otherwise.


I guess I'm just really confused as to why exactly this needs to be renamed, as there are zero conflicts with any other application in Homebrew-Casks.

**Comment by vitorgalvao** [comment]
I was the one confused; I could swear the original was named SuperSlicer as well because I was misled by the `audit`’s error.

This is fine. Thank you.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
