### PR TITLE
Renamed ubersicht to uebersicht

### PR DESCRIPTION
**Pull request by zerrot**
Developer documented changes to project to remove the üfrom the app name for compatability. The issue can be followed at https://github.com/felixhageloh/uebersicht/issues/77

### CODE REVIEW

**Comment by vitorgalvao** [comment]
We have [strict naming rules](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_token_reference.md) (for various reasons, including fighting duplicates), and the cask’s token (you also need to change the first line, or it breaks) is dependent on the name of the app bundle, so until there is a new release the name must remain, and change only then.

**Comment by zerrot** [comment]
Sorry about that. So the app download is currently named Uebersicht-0.4.15.app.zip, the project has been renamed Uebersicht, the only thing that hasn't changed is the .app file. It is still Übersicht.app. Which is different from the cask because of the unicode umlaut over the 'U' in the name of the app and the cask is missing the umlaut. Can I rename the cask file and update the first line now? or wait until another .app is pushed?

**Comment by vitorgalvao** [comment]
We should wait until a new version is pushed. I’ve seen instances of apps that plan on changing their names but then end up never doing it, or taking a long time before releasing the new version with such a change.

One small note, though, it seems like the app may end up being called `Ubersicht`, and not `Uebersicht` (last line of original comment), which would leave the cask as is. That’s an extra reason to wait and see.

On an unrelated note, thank you for all the recent contributions.

**Comment by zerrot** [comment]
No problem. I'll keep my eye on it and when the app updates I'll resubmit it.

**Comment by deizel** [comment]
@zerrot - 0.5 is out.

**Comment by vitorgalvao** [comment]
The app’s name seems to be unchanged, though, so it stays the same.

**Pull request closed without merging**
