### PR TITLE
various: fix miscellaneous typos

### PR DESCRIPTION
**Pull request by p-linnane**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Are you doing this in preparation of an audit? Something like https://til.codeinthehole.com/posts/about-the-typos-source-code-spell-checker/

**Comment by p-linnane** [comment]
That's what I use. I check our repos every few months.

**Comment by krehel** [comment]
This is good, thanks @p-linnane!  We should do this quarterly maybe, shouldn't be that intensive of an exercise I suspect...

**Review by krehel — APPROVED** [review]

**Comment by SMillerDev** [comment]
Or we make it automated... 😁

**Comment by krehel** [comment]
Also that!  I don't know what the false positive rate would be or how badly / frequently it would fail in the CI, maybe something worth testing.

**Comment by p-linnane** [comment]
If we use `typos` you can write a config file that excludes things. For example, mine ignores "Sur" due to Big Sur. Otherwise it wants it to be "Big Sure" 😅

**Pull request merged**
