### PR TITLE
Update teamviewer from 15.19.4 to 15.20.3

### PR DESCRIPTION
**Pull request by LanikSJ**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@LanikSJ Upstream is still reporting the previous version `15.19.4`.

**Comment by LanikSJ** [comment]
Internal updater shows new version.

**Comment by bevanjkay** [comment]
@LanikSJ In that case it is most likely a staged release, as my in-app updater is showing `15.9.4` as the most recent. What version of MacOS are you running?

**Comment by LanikSJ** [comment]
Big Sur

**Comment by bevanjkay** [comment]
@LanikSJ ARM or Intel processor?

**Comment by LanikSJ** [comment]
Intel

**Comment by bevanjkay** [comment]
@LanikSJ The only way that I can see version `15.20.3` in-app is if I change my updated channel to `Public Beta` in the Teamviewer preferences, advanced tab. If yours is still set to the release channel I would assume it is a staged release where Teamviewer have placed you in a small subset of users to receive the update early, but generally `15.19.4` is the common version.

**Comment by LanikSJ** [comment]
Yeah I have on beta my bad 😒  sorry to waste your time.

**Pull request closed without merging**
