### PR TITLE
Update objectivesharpie to latest

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
https://developer.xamarin.com/guides/cross-platform/macios/binding/objective-sharpie/releases/

https://dl.xamarin.com/objective-sharpie/ObjectiveSharpie-3.4.0.pkg

**Comment by brianmorton** [comment]
Unsure what your comments mean... I know the URL pattern for `3.4.0` will still work with the current pattern, however via the website it points the DL to this new url.

https://developer.xamarin.com/guides/cross-platform/macios/binding/objective-sharpie/getting-started/

image

**Comment by commitay** [comment]
The release notes have a versioned download.

**Comment by brianmorton** [comment]
Use #43488 instead I guess!

**Comment by commitay** [comment]
Lots of Casks have an unversioned download on the homepage but have versioned downloads "hidden" in the release notes or appcast.

**Pull request closed without merging**
