### PR TITLE
Update min (1.2.2)

### PR DESCRIPTION
**Pull request by cakuki**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

This changes also update moved repository urls.

### CODE REVIEW

**Comment by adidalal** [comment]
URL comment needs to be changed

**Comment by cakuki** [comment]
@adidalal do you mean this commit message?

> Also updates moved repository urls.

Should I remove it or what?

**Comment by adidalal** [comment]
Thank you for the contribution. It needed some fixes, so they were made in b0062e0bd3f1c0ce0e474566cdc388c2c0c85de9. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by cakuki** [comment]
Oh sorry, I just saw the commented line that was obvious, thanks for changing commit and fixing it @adidalal!

**Pull request closed without merging**
