### PR TITLE
Add IPSecuritas 4.7

### PR DESCRIPTION
**Pull request by aguynamedryan**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This app has an uninstaller, which suggests it requires an [`uninstall`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md).

screen shot 2017-02-09 at 01 00 57

**Comment by miccal** [comment]
@vitorgalvao I have had a peek at the uninstall `app`; there are no scripts inside and it is not clear what the uninstaller does.

@aguynamedryan if you are familiar with this `app`, are you able to elaborate on what exactly the uninstall `app` does?

**Comment by vitorgalvao** [comment]
Pinging @aguynamedryan. If we can’t get a proper uninstall for the app, we’ll have to refuse it.

**Comment by miccal** [comment]
Closing due to lack of response.

**Pull request closed without merging**
