### PR TITLE
Fix Google Music Manager (music-manager) pref pane

### PR DESCRIPTION
**Pull request by tjanson**
The app will copy the pref pane itself on first run (if it does not already exist), but then `brew uninstall` will not remove it.
By letting brew symlink the pref pane, it uninstalls properly.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
There was a PR template that you needed to fill out. Please try again and fill it.

**Comment by vitorgalvao** [comment]
You may do so in this PR or a new one. Whatever you prefer.

**Comment by tjanson** [comment]
Sorry, I commited and set the PR from the command using hub, so I did not see a template …

I took your hint though, the style issue is corrected.

----

- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

**Comment by tjanson** [comment]
Where is that PR template file located though, for future reference?

**Comment by vitorgalvao** [comment]
Located [here](https://github.com/caskroom/homebrew-cask/blob/master/.github/PULL_REQUEST_TEMPLATE.md). It should appear automatically, though.

It doesn’t appear now due to `hub`, but I think they are working on it.

**Pull request merged**
