### PR TITLE
Update DEVONthink to version 3.0

### PR DESCRIPTION
**Pull request by luispuerto**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]

**Comment by core-code** [comment]
this means the 'devonthink-pro' and 'devonthink-pro-office' casks can be deleted, since as-far-as-i-can-determine those have been merged into the main edition now

**Comment by vitorgalvao** [comment]
Looks like the new [editions](https://www.devontechnologies.com/apps/devonthink/editions) are `pro` and `server`, but maybe it’s the same app with unlocked features rather than three different apps.

**Comment by core-code** [comment]
i believe they are just unlockable from the same binary, but since there is no need to be quick here, we can wait for a while to confirm that. i'll have a look in a week.

**Comment by luispuerto** [comment]
Guys, I can confirm that now it's just one app and you unlock capabilities in relation to your license. 

You can check it [here](https://www.devontechnologies.com/apps/devonthink/new) under "Product Line".

**Comment by core-code** [comment]
thanks for the confirmation, so i'll send the two delete requests now

**Pull request merged**
