### PR TITLE
Add TouchOSC Editor v 1.7.0

### PR DESCRIPTION
**Pull request by danielbayley**
TouchOSC layout editor.

Signed-off-by: Daniel Bayley daniel.bayley@me.com

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Can you buy this from outside the Mac App Store?

**Comment by danielbayley** [comment]
It's completely free, but isn't in the App Store. Not sure what the exact license is.

Same applies to #11613.

**Comment by vitorgalvao** [comment]
License is `:gratis`, then.

What about the two commented lines?

**Comment by danielbayley** [comment]
Ah ok cool.

> What about the two commented lines?

When you download the DMG it unzips into a `touchosc-editor-#{version}-osx` folder containing the `.app` which gets linked to `/Applications` as normal, but also contains a `layouts` folder which ideally would be moved/linked to `~/Library/Application Support/TouchOSCEditor/layouts` but I can't figure out how to do that. Is this possible?

The `suite` line can probably just be deleted, especially if the above will work.

**Comment by vitorgalvao** [comment]
`artifact "touchosc-editor-#{version}-osx/layouts", :target => '~/Library/Application Support/TouchOSCEditor/layouts'`.

**Comment by danielbayley** [comment]
> `artifact "touchosc-editor-#{version}-osx/layouts", :target => '~/Library/Application Support/TouchOSCEditor/layouts'`

Strangely, this just creates `/Applications/~/Library/Application Support/TouchOSCEditor/layouts`. Is there any way around that?

**Comment by vitorgalvao** [comment]
[postflight](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#postflight-stanza-details).

**Comment by danielbayley** [comment]
So I can achieve this with something like the following? (replacing the `artifact` declaration?) Sorry, haven't done much Ruby.

```ruby
post flight do
  File.rename "touchosc-editor-#{version}-osx/layouts",'~/Library/Application Support/TouchOSCEditor/layouts'
end
```

**Pull request closed without merging**
