### PR TITLE
Update zerotier-one from 1.8.9 to 1.10.0

### PR DESCRIPTION
**Pull request by zer0pwned**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by zer0pwned** [comment]
Seems zerotier is not tagging release 1.10.0 on github so livecheck is failed. Neither were 1.8.10. Not sure what should do to meet the livecheck requirement at this moment.

**Comment by zer0pwned** [comment]
Under this https://github.com/zerotier/ZeroTierOne/issues/1668 circumstance, maybe we shouldn't use git to perform livecheck for zerotier. Perhaps release page with version directory livecheck strategy is a better idea. 

http://download.zerotier.com/RELEASES/

**Review by miccal — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @zer0pwned.

**Comment by zer0pwned** [comment]
Thanks a lot for the livecheck update!

**Pull request merged**
