### PR TITLE
Update clover-configurator.rb from 5.4.5.0 to 5.5.0.0

### PR DESCRIPTION
**Pull request by suschizu**
update app

### CODE REVIEW

**Comment by ran-dall** [comment]
@suschizu This hasn't been working for a minute

`Error: Download failed on Cask 'clover-configurator' with message: Download failed: https://mackie100projects.altervista.org/apps/cloverconf/CCG/builds-data-ccg/CCG.zip                       `

**Comment by vitorgalvao** [comment]
@ran-dall `brew cask fetch clover-configurator` succeeds for me.

**Comment by ran-dall** [comment]
Well, it should because your fetching...

Try to ’curl’ the download link, the ML has reported this several days in a row, and I get an unexpected EOF.

**Comment by vitorgalvao** [comment]
@ran-dall `fetch` uses `curl` on the background, though it’s not *just* `curl <URL>`, it has extra options. Perhaps one of those is essential here, you might want to check the core code.

**Comment by ran-dall** [comment]
@vitorgalvao LOL 🤪 I know how `fetch` works...

I'm a little confused by what you're objective here is though. The ML wouldn't be pushing back errors there are no errors; especially of this nature. It simply tried pulling the cask to analyze it (like it's supposed to when it doesn't perform the update) and hasn't been able to in ~12 days. I tried to manually do it on my machine and couldn't either. That would be two different machines, in two different locations, with different versions of macOS that couldn't pull the cask. My objective in reporting it was simply to like @suschizu know that it's causing a nag on the ML because it wants to fix it. In the past, we've had problems before with this cask that were like this; so I try to avoid force fixing this by reporting it so @suschizu can investigate.

**Comment by minhphuc429** [comment]
```
brew cask install clover-configurator
==> Satisfying dependencies
==> Downloading https://mackie100projects.altervista.org/apps/cloverconf/CCG/builds-data-ccg/CCG.zip
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Error: Download failed on Cask 'clover-configurator' with message: Download failed: https://mackie100projects.altervista.org/apps/cloverconf/CCG/builds-data-ccg/CCG.zip
```
How to fix this error?

**Comment by ran-dall** [comment]
@minhphuc429 Sorry, my bad! I haven't had the time to look into this and I guess @suschizu hasn't either. Give me a few and I'll try to post a fix for this shortly. 🧐

**Comment by ran-dall** [comment]
@vitorgalvao `fetch` is failing now too...

```bash
$brew cask fetch clover-configurator
                                                                                                                                                                                                 
==> Downloading external files for Cask clover-configurator                                                                                                                                      
==> Downloading https://mackie100projects.altervista.org/apps/cloverconf/CCG/builds-data-ccg/CCG.zip                                                                                             
######################################################################## 100.0%                                                                                                                  
curl: (56) Unexpected EOF                                                                                                                                                                        
Error: Download failed on Cask 'clover-configurator' with message: Download failed: https://mackie100projects.altervista.org/apps/cloverconf/CCG/builds-data-ccg/CCG.zip
```

**Comment by ran-dall** [comment]
@vitorgalvao Ok! So I found that using `--http 1.1` sovles this for me, using `curl`

```bash
$curl -v -O https://mackie100projects.altervista.org/apps/cloverconf/CCG/builds-data-ccg/CCG.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                  
                                 Dload  Upload   Total   Spent    Left  Speed                                                                                                                    
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 136.243.133.23...                                                                                       
* TCP_NODELAY set                                                                                                                                                                                
* Connected to mackie100projects.altervista.org (136.243.133.23) port 443 (#0)                                                                                                                   
* ALPN, offering h2                                                                                                                                                                              
* ALPN, offering http/1.1                                                                                                                                                                        
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH                                                                                                                   
* successfully set certificate verify locations:                                                                                                                                                 
*   CAfile: /etc/ssl/cert.pem                                                                                                                                                                    
  CApath: none                                                                                                                                                                                   
* TLSv1.2 (OUT), TLS handshake, Client hello (1):                                                                                                                                                
} [512 bytes data]                                                                                                                                                                               
* TLSv1.2 (IN), TLS handshake, Server hello (2):                                                                                                                                                 
{ [102 bytes data]                                                                                                                                                                               
* TLSv1.2 (IN), TLS handshake, Certificate (11):                                                                                                                                                 
{ [2667 bytes data]                                                                                                                                                                              
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):                                                                                                                                         
{ [333 bytes data]                                                                                                                                                                               
* TLSv1.2 (IN), TLS handshake, Server finished (14):                                                                                                                                             
{ [4 bytes data]                                                                                                                                                                                 
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):                                                                                                                                        
} [70 bytes data]                                                                                                                                                                                
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):                                                                                                                                            
} [1 bytes data]                                                                                                                                                                                 
* TLSv1.2 (OUT), TLS handshake, Finished (20):                                                                                                                                                   
} [16 bytes data]                                                                                                                                                                                
* TLSv1.2 (IN), TLS change cipher, Client hello (1):                                                                                                                                             
{ [1 bytes data]                                                                                                                                                                                 
* TLSv1.2 (IN), TLS handshake, Finished (20):                                                                                                                                                    
{ [16 bytes data]                                                                                                                                                                                
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384                                                                                                                                     
* ALPN, server accepted to use h2                                                                                                                                                                
* Server certificate:                                                                                                                                                                            
*  subject: CN=mackie100projects.altervista.org                                                                                                                                                  
*  start date: Jul 21 23:07:24 2019 GMT                                                                                                                                                          
*  expire date: Oct 19 23:07:24 2019 GMT                                                                                                                                                         
*  subjectAltName: host "mackie100projects.altervista.org" matched cert's "mackie100projects.altervista.org"                                                                                     
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3                                                                                                                                  
*  SSL certificate verify ok.                                                                                                                                                                    
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Using HTTP2, server supports multi-use                                                                           
* Connection state changed (HTTP/2 confirmed)                                                                                                                                                    
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0                                                                                                                 
* Using Stream ID: 1 (easy handle 0x7fd89f80e800)                                                                                                                                                
> GET /apps/cloverconf/CCG/builds-data-ccg/CCG.zip HTTP/2                                                                                                                                        
> Host: mackie100projects.altervista.org                                                                                                                                                         
> User-Agent: curl/7.54.0                                                                                                                                                                        
> Accept: */*                                                                                                                                                                                    
>                                                                                                                                                                                                
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!                                                                                                                                     
< HTTP/2 200                                                                                                                                                                                     
< date: Sat, 14 Sep 2019 23:56:48 GMT                                                                                                                                                            
< server: Apache                                                                                                                                                                                 
< etag: "13ebe20-54c8ee-590b5015e7080"                                                                                                                                                           
< last-modified: Thu, 22 Aug 2019 13:52:50 GMT                                                                                                                                                   
< content-length: 5556462                                                                                                                                                                        
< content-type: application/zip                                                                                                                                                                  
< x-varnish: 311501655 315919481                                                                                                                                                                 
< age: 7329                                                                                                                                                                                      
< via: 1.1 varnish (Varnish/6.1)                                                                                                                                                                 
< wpvarnish-cache: HIT:14                                                                                                                                                                        
< accept-ranges: bytes                                                                                                                                                                           
<                                                                                                                                                                                                
{ [16054 bytes data]                                                                                                                                                                             
* 79 data bytes written                                                                                                                                                                          
{ [79 bytes data]                                                                                                                                                                                
 98 5426k   98 5356k    0     0   319k      0  0:00:16  0:00:16 --:--:--  355k* TLSv1.2 (IN), TLS alert, Client hello (1):                                                                       
{ [2 bytes data]                                                                                                                                                                                 
* Unexpected EOF                                                                                                                                                                                 
100 5426k  100 5426k    0     0   320k      0  0:00:16  0:00:16 --:--:--  358k                                                                                                                   
* Closing connection 0                                                                                                                                                                           
* TLSv1.2 (OUT), TLS alert, Client hello (1):                                                                                                                                                    
} [2 bytes data]                                                                                                                                                                                 
curl: (56) Unexpected EOF  
```

```
$curl -v -O --http1.1 https://mackie100projects.altervista.org/apps/cloverconf/CCG/builds-data-ccg/CCG.zip 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                  
                                 Dload  Upload   Total   Spent    Left  Speed                                                                                                                    
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 136.243.144.171...                                                                                      
* TCP_NODELAY set                                                                                                                                                                                
* Connected to mackie100projects.altervista.org (136.243.144.171) port 443 (#0)                                                                                                                  
* ALPN, offering http/1.1                                                                                                                                                                        
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH                                                                                                                   
* successfully set certificate verify locations:                                                                                                                                                 
*   CAfile: /etc/ssl/cert.pem                                                                                                                                                                    
  CApath: none                                                                                                                                                                                   
* TLSv1.2 (OUT), TLS handshake, Client hello (1):                                                                                                                                                
} [512 bytes data]                                                                                                                                                                               
* TLSv1.2 (IN), TLS handshake, Server hello (2):                                                                                                                                                 
{ [108 bytes data]                                                                                                                                                                               
* TLSv1.2 (IN), TLS handshake, Certificate (11):                                                                                                                                                 
{ [2667 bytes data]                                                                                                                                                                              
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):                                                                                                                                         
{ [333 bytes data]                                                                                                                                                                               
* TLSv1.2 (IN), TLS handshake, Server finished (14):                                                                                                                                             
{ [4 bytes data]                                                                                                                                                                                 
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):                                                                                                                                        
} [70 bytes data]                                                                                                                                                                                
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):                                                                                                                                            
} [1 bytes data]                                                                                                                                                                                 
* TLSv1.2 (OUT), TLS handshake, Finished (20):                                                                                                                                                   
} [16 bytes data]                                                                                                                                                                                
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0* TLSv1.2 (IN), TLS change cipher, Client hello (1):                                                               
{ [1 bytes data]                                                                                                                                                                                 
* TLSv1.2 (IN), TLS handshake, Finished (20):                                                                                                                                                    
{ [16 bytes data]                                                                                                                                                                                
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384                                                                                                                                     
* ALPN, server accepted to use http/1.1                                                                                                                                                          
* Server certificate:                                                                                                                                                                            
*  subject: CN=mackie100projects.altervista.org                                                                                                                                                  
*  start date: Jul 21 23:07:24 2019 GMT                                                                                                                                                          
*  expire date: Oct 19 23:07:24 2019 GMT                                                                                                                                                         
*  subjectAltName: host "mackie100projects.altervista.org" matched cert's "mackie100projects.altervista.org"                                                                                     
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3                                                                                                                                  
*  SSL certificate verify ok.                                                                                                                                                                    
> GET /apps/cloverconf/CCG/builds-data-ccg/CCG.zip HTTP/1.1                                                                                                                                      
> Host: mackie100projects.altervista.org                                                                                                                                                         
> User-Agent: curl/7.54.0                                                                                                                                                                        
> Accept: */*                                                                                                                                                                                    
>                                                                                                                                                                                                
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0< HTTP/1.1 200 OK                                                                                                  
< Date: Sun, 15 Sep 2019 01:44:19 GMT                                                                                                                                                            
< Server: Apache                                                                                                                                                                                 
< ETag: "13ebe20-54c8ee-590b5015e7080"                                                                                                                                                           
< Last-Modified: Thu, 22 Aug 2019 13:52:50 GMT                                                                                                                                                   
< Content-Length: 5556462                                                                                                                                                                        
< Content-Type: application/zip                                                                                                                                                                  
< X-Varnish: 209561037 201926395                                                                                                                                                                 
< Age: 666                                                                                                                                                                                       
< Via: 1.1 varnish (Varnish/6.1)                                                                                                                                                                 
< WPVarnish-Cache: HIT:3                                                                                                                                                                         
< Connection: close                                                                                                                                                                              
< Accept-Ranges: bytes                                                                                                                                                                           
<                                                                                                                                                                                                
{ [16033 bytes data]                                                                                                                                                                             
100 5426k  100 5426k    0     0   299k      0  0:00:18  0:00:18 --:--:--  364k                                                                                                                   
* Closing connection 0                                                                                                                                                                           
* TLSv1.2 (OUT), TLS alert, Client hello (1):                                                                                                                                                    
} [2 bytes data]                                                                                                                                                                                 
```

**Comment by reitermarkus** [comment]
Can't reproduce this. Works for me with and without `--http1.1`.

**Comment by vitorgalvao** [comment]
Now if I `fetch`, it always fails with `curl: (22) The requested URL returned error: 416`.

If I `curl` with `--http1.1` it always succeeds; without `--http1.1` it sometimes succeeds and sometimes fails with `curl: (56) Unexpected EOF`.

**Pull request merged**
