### PR TITLE
update kindaVim to stable 2.0.0

### PR DESCRIPTION
**Pull request by godbout**
- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by godbout** [comment]
hmm. when kV was in beta the `1b25,0.9.25` version didn't cause any issue. now that it's stable, `1,1.0.0` is causing an issue, and Homebrew just seems to care about the `1.0.0`. anything i'm missing? thanks.

**Comment by SMillerDev** [comment]
The appcast reports the version as `1.0.0` so the fact that the `version` defines it as `1,1.0.0` is causing the issue.

**Comment by godbout** [comment]
hey @SMillerDev thanks for the quick answer.

in the past this would work:
appcast:
```
            <sparkle:version>0.9.25</sparkle:version>
            <sparkle:shortVersionString>1b25</sparkle:shortVersionString>
```
homebrew:
```
version: 1b25,0.9.25
```

now this doesn't work:
appcast:
```
            <sparkle:version>1.0.0</sparkle:version>
            <sparkle:shortVersionString>1</sparkle:shortVersionString>
```
homebrew:
```
version: 1,1.0.0
```

i can't notice the difference.

**Comment by godbout** [comment]
for internal version numbering i follow semver; for "marketing" version numbering i'm just going 1 2 3++.

**Comment by SMillerDev** [comment]
Since we don't use the short version anywhere, why not just do `version "1.0.0"`?

**Comment by godbout** [comment]
> Since we don't use the short version anywhere, why not just do `version "1.0.0"`?

so is there any way to just show `1`? or do i have to go through the `1.0.0`? thanks.

**Comment by godbout** [comment]
or can i use `lastest`? that may work well too. the point is that it's a subscription. people always get the latest version. there's no "license" for v1 and not for v2 etc... just one, latest version.

**Comment by godbout** [comment]
ultimately i've removed the livecheck. i'm not really sure what does that mean for end users. like how does Homebrew know it needs to download or not the app. does the app gets downloaded each time users do a `brew update`? i guess i'll know when i'll get pinged.

**Comment by SMillerDev** [comment]
The livecheck is a check to see if a new version is live. 

If you set the version to latest it doesn't have any use since homebrew won't be able to keep track of updates anyways.

**Pull request merged**
