### PR TITLE
updated framer-studio (63)

### PR DESCRIPTION
**Pull request by weihanglo**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Needs to be renamed to `framer`.

**Comment by weihanglo** [comment]
Should I rename it and push again?

**Comment by vitorgalvao** [comment]
Yes, please.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/21243.

**Pull request closed without merging**
