### PR TITLE
Update cocoapods (1.0.0.beta.5)

### PR DESCRIPTION
**Pull request by Jerzerak**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by adidalal** [comment]
This was reverted as it's a beta release.

**Comment by Jerzerak** [comment]
It's the new recommended version by the cocoapods website...shouldn't that be the version in homebrew-cask and any unrecommended version be in homebrew-versions? Or am I completely off base here?

**Comment by adidalal** [comment]
@vitorgalvao Seems like a good case for having this version in mainline homebrew-cask

https://github.com/caskroom/homebrew-cask/issues/20290

**Comment by vitorgalvao** [comment]
Yes, if this is indeed the recommended (by the vendor) version, [it’s the one that should be in the main tap](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Pinging @m8x.

**Comment by Jerzerak** [comment]
@adidalal [Here is the url](https://cocoapods.org/app) scroll to the bottom of the page to the downloads section

**Pull request merged**
