### PR TITLE
simply-fortran 3.33.4066

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Review by reitermarkus — DISMISSED** [review]

**Comment by krehel** [comment]
FYI this is still returning the new version for me locally.

simply-fortran: 3.32.4016 ==> 3.33.4066

**Comment by reitermarkus** [comment]
Also returning 3.33.4066 for me locally.

**Comment by bevanjkay** [comment]
The version is actually different from intel / arm
https://simplyfortran.com/download/

**Comment by bevanjkay** [comment]
It could be an A/B test or staggered rollout though.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
