### PR TITLE
Update intel-power-gadget to 3.5.3,655065

### PR DESCRIPTION
**Pull request by Jahhein**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by Jahhein** [comment]
Cask-repair made the request even when it failed.

**Comment by vitorgalvao** [comment]
> Cask-repair made the request even when it failed.

What was the command you used?

**Comment by Jahhein** [comment]
`cask-repair -e -i formula`

**Comment by Jahhein** [comment]
It has never asked me. It only asks if the formula file is correct. I already closed it.

**Comment by vitorgalvao** [comment]
> It only asks if the formula file is correct.

That’s the trigger. If you say everything is correct, it submits (the point of `cask-repair` is quick edits submitted fast).

Small note: In this case they’re casks, not formulae (built differently and provide different software in different ways).

**Pull request closed without merging**
