### PR TITLE
Add "auto_updates true" for ableton-live-suite

### PR DESCRIPTION
**Pull request by nvmker**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ran-dall** [comment]
@navymaker I believe this is `true` for all `ableton*` casks, correct?

**Comment by navymaker** [comment]
Yes, that's correct.

**Comment by ran-dall** [comment]
@vitorgalvao Is there a way I can add `auto_update`	to all the `ableton*` casks? Or is that something you could do? I'd feel better if we had consistency. 😉

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/86184

**Pull request merged**
