### PR TITLE
capcut 3.0.0.1015 (new cask)

### PR DESCRIPTION
**Pull request by rternavskyi**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Review by samford — COMMENTED** [review]
Hmm, I honestly have no idea why livecheck isn't working on CI here. The check works as expected locally and I haven't found any reason why it wouldn't work the same on CI.

**Comment by miccal** [comment]
> Hmm, I honestly have no idea why livecheck isn't working on CI here. The check works as expected locally and I haven't found any reason why it wouldn't work the same on CI.

Thanks @samford; it is working locally for me also.

**Comment by bevanjkay** [comment]
I have run out of time to get this sorted myself right now, so just dropping some findings here.

1. We can find the version that the installer is downloading through this API call (I'm not sure which params can be thinned out yet) - will allow us to directly download the `.app`
`https://editor-api-sg.capcut.com/service/settings/v3/?app=1&aid=359289&arch_info=arm64&device_id=2398670469&device_platform=mac&from_aid=359289&from_channel=capcutpc_0&from_version=0.0.0&local_info=en_AU&version_code=0.0.0`

2. This should let us avoid using the installer, and use an `app` stanza instead

3. The version will align with the app itself, not the installer.


Current stable download url - https://lf16-capcut.faceulv.com/obj/capcutpc-packages-sg/packages/CapCut_3_0_0_1015_capcutpc_0_creatortool.dmg

**Comment by bevanjkay** [comment]
I am not certain if the `aid=####` part of the `livecheck` url will remain static moving forward, but time will tell.
This install method is much preferred, as I noticed with the installer that there is a GUI that is opened which required a language selection to proceed. This doesn't seem to block the install as it passed CI using the same method, however it is not the expected UX for Homebrew.

**Comment by bevanjkay** [comment]
@rternavskyi Can you please confirm that this installs similarly to how it did when you originally submitted the PR?

**Comment by p-linnane** [comment]
Closing due to lack of response.

**Pull request closed without merging**
