### PR TITLE
Rename fm-fw-installer to flymaster-firmware, update other fields

### PR DESCRIPTION
**Pull request by jawshooah**
Refs #9330.

`Firmware Installer.app` is an application to install firmware (not included) on a Flymaster instrument.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
If it’s an installer, shouldn’t it be `installer :manual`?

**Comment by jawshooah** [comment]
I don't think so. The installer _is_ the application; it's a tool to install firmware to connected Flymaster devices.

**Comment by vitorgalvao** [comment]
But does it do anything after the installation? As in, will you open it anytime after the initial installation?

**Comment by jawshooah** [comment]
Sure, you can use it to update the firmware on any number of devices any number of times.

**Pull request merged**
