### PR TITLE
Update caprine to 2.14.0

### PR DESCRIPTION
**Pull request by janosorcsik**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by ubuntux** [comment]
Please update to 2.14.2... There has been a reported bug about [Caprine window brought to front whenever a message is read or received](https://github.com/sindresorhus/caprine/issues/483), which has been fixed on the mentioned version.

**Comment by commitay** [comment]
@ubuntux You can submit an update for it yourself:

> [Updating a Cask](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask)
```
# install and setup script - only needed once
brew install vitorgalvao/tiny-scripts/cask-repair
cask-repair --help
```
```
cask-repair --cask-version 2.14.2 caprine
```

**Comment by janosorcsik** [comment]
@ubuntux  Done https://github.com/Homebrew/homebrew-cask/pull/48283

**Comment by ubuntux** [comment]
@commitay, will do that next time.
@janosorcsik, thanks!

**Pull request merged**
