### PR TITLE
Couchbase Server 4.0.0 released

### PR DESCRIPTION
**Pull request by brianshumate**
This PR also adds separate packages for El Capitan.

### CODE REVIEW

**Comment by victorpopkov** [comment]
Thank you for the contribution. However, there is no need to create separate casks for El Capitan. You can simply verify the Mac OS release in cask itself and serve the right download URL. For example for `couchbase-server-community.rb` you could use:
```ruby
cask :v1 => 'couchbase-server-community' do
  version '4.0.0'

  if MacOS.release <= :el_capitan
    sha256 '26edea946d845a96e21e887348f853dff0a632b7bf6d42e9d559b647855648f6'
    url "http://packages.couchbase.com/releases/#{version}/couchbase-server-enterprise_#{version}-elcapitan_x86_64.zip"
  else
    sha256 'ff994c89abf2efcc7dafa6753cfc25c821f3cc24935dccb7a979d170ced56162'
    url "http://packages.couchbase.com/releases/#{version}/couchbase-server-community_#{version}-macos_x86_64.zip"
  end
...
```

**Comment by brianshumate** [comment]
This is a good point and thank you. I'll fix it up and recommit.

**Comment by brianshumate** [comment]
For some reason, after downloading the packages and manually verifying the SHA checksums, they were different which is why I updated them. I will fix the appcast and try again.

**Comment by brianshumate** [comment]
I am just going to try this as a new PR again later.

**Pull request closed without merging**
