### PR TITLE
Update wizard101 to 1.13

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
`sha256`-only change.

**Comment by commitay** [comment]
I think we're still waiting for them to respond to https://github.com/caskroom/homebrew-cask/pull/33570

**Comment by brianmorton** [comment]
FWIW it seems another update in place has happened since this PR was opened, as the sha256 has changed again:
```
$ brew cask audit --download wizard101
==> Downloading http://versionec.us.wizard101.com/Wizard101.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask wizard101
==> Note: running "brew update" may fix sha256 checksum errors
audit for wizard101: failed
 - download not possible: Checksum for Cask 'wizard101' does not match.

Expected: e994b59a6b53f2255168316b832962415b899260244ae36dfd4ba0aba201fcb9
Actual:   0b904601c058683fe435ac68e7e541d0cdca3abd8b6263e8d55fcd9bb392cdab
File:     /Users/brian/Library/Caches/Homebrew/Cask/wizard101--1.13.dmg

To retry an incomplete download, remove the file above.
Error: audit failed for casks: wizard101
```

**Comment by vitorgalvao** [comment]
Looks like no one really cares much about this cask. Let’s remove it.

**Pull request closed without merging**
