### PR TITLE
firefox@nightly: updates

### PR DESCRIPTION
**Pull request by krehel**
* Add livecheck to get latest release

* Replace version :latest version with version number

* Replace sha256 :no_check with a sha256 by language like main Firefox cask

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

---

### CODE REVIEW

**Comment by Bo98** [comment]
The URL would need changing to something more stable. Just realised we didn't do this for `firefox@developer-edition`.

For developer edition see https://download-installer.cdn.mozilla.net/pub/devedition/releases/.
For nightly see https://download-installer.cdn.mozilla.net/pub/firefox/nightly/.
Stable and beta use https://download-installer.cdn.mozilla.net/pub/firefox/releases/.

For nightly specifically, the same version number (`XXXa1`) is attributed to multiple releases so they use timestamps for nightlies.

**Comment by krehel** [comment]
Yep you're right.  The standard `firefox` Cask is using the CDN.  I'll make some updates to the `url`!

**Comment by krehel** [comment]
I need to do some additional work on this and figure out the appropriate way to handle livechecks.  Do not merge please.

**Comment by krehel** [comment]
Going to close this until I work out a solution.

**Pull request closed without merging**
