### PR TITLE
Add Ears.app 1.2.2

### PR DESCRIPTION
**Pull request by lucassaldanha**
Creating cask for Ears app

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by lucassaldanha** [comment]
I'm not sure what is different between my local run of `brew audit` and the execution on CircleCI. I followed all the instruction [found here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#testing-your-new-cask).

I'll wait for some guidance on what to do.

**Comment by cho-m** [comment]
@lucassaldanha I fixed some of the audit failures.

When you have a chance, please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some methods to create one.

**Comment by lucassaldanha** [comment]
> I fixed some of the audit failures.

Thanks @cho-m! Any idea why I didn't get any of these failures locally? Is it possible that the documentation on how to perform an audit needs to be updated?

> When you have a chance, please try to add a zap stanza.

Ok. I'll try to get to it later today!

**Comment by lucassaldanha** [comment]
@cho-m I've done the changes with the uninstall/zap stuff 👍

**Review by cho-m — APPROVED** [review]
Thanks, @lucassaldanha

**Pull request merged**
