### PR TITLE
Update microsoft-teams from 1.3.00.15561 to 1.3.00.9271

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ran-dall** [comment]
```shell
$ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/developer/bin/cask-pr-local-check https://github.com/Homebrew/homebrew-cask/pull/84243
==> Downloading https://statics.teams.microsoft.com/production-osx/1.3.00.9271
Already downloaded: /Users/randall/Library/Caches/Homebrew/downloads/b2b9e99d37deb77ad54bfb9492d52f4640f68c2c7a3fc2ae58e70381bebbbe80--Teams_osx.pkg
==> Verifying SHA-256 checksum for Cask 'microsoft-teams'.
audit for microsoft-teams: passed

1 file inspected, no offenses detected
```

**Comment by miccal** [comment]
[This was a downgrade.](https://github.com/Homebrew/homebrew-cask/pull/84252)

**Comment by ran-dall** [comment]
@miccal `https://statics.teams.cdn.office.net/production-osx/1.3.00.9271/Teams_osx.pkg` is what's listed on the `appcast`. Perhaps we need a new `appcast`?

**Comment by miccal** [comment]
@ran-dall how about
```
https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://go.microsoft.com/fwlink/p/?linkid=869428c
```

**Comment by ran-dall** [comment]
@miccal This is all I get.

```html
<html>
<head><title></title></head>
<body>
  https://www.microsoft.com/de-de/?ref=go

</body>
</html>

```

**Comment by miccal** [comment]
Strange, I get
```
https://statics.teams.cdn.office.net/production-osx/1.3.00.15561/Teams_osx.pkg
```

**Comment by miccal** [comment]
If you go to the `homepage`, what link do you get from the `Download Teams` button -- for example, I get
```
https://go.microsoft.com/fwlink/p/?linkid=869428&clcid=0xc09&culture=en-au&country=au&lm=deeplink&lmsrc=groupchatmarketingpageweb&cmpid=directdownloadmac
```

**Comment by miccal** [comment]
@ran-dall how about instead
```
https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://aka.ms/teamsmac
```

**Comment by ran-dall** [comment]
@miccal Good call. I'll push the update on #84252.

**Pull request merged**
