### PR TITLE
Update djl-bench from 0.14.0 to 0.14.1

### PR DESCRIPTION
**Pull request by frankfliu**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by frankfliu** [comment]
livecheck failed due to djl 0.14.1 has not been published to github yet. The full DJL release will take a couple of weeks.

djl-bench is affected by log4j CVE, but DJL library is not. What's the recommended way to rollout djl-bench without a new DJL release?

**Comment by bevanjkay** [comment]
@frankfliu `livecheck` looks for the current version as reported upstream (in this case the github repo). It looks like the [download page](https://djl.ai/extensions/benchmark/) is also currently reporting the previous version so we can't check there (I image this page is automatically generated when there's a new release?).

We could potentially merge this as an exception, however we may see PRs to revert the change as livecheck will still return the older version. And it is better for the current version to be user-verifiable from your website also.

**Comment by frankfliu** [comment]
@bevanjkay 
We have a [0.14.1 tag](https://github.com/deepjavalibrary/djl/tree/v0.14.1) in github repo for djl-bench. Is there a way to just check if the tag exists?

However, we don't have a plan to release 0.14.1 on github:
1. there is no changes in DJL library between 0.14.0 and 0.14.1, only djl-bench is impacted, release a 0.14.1 will cause confusion
2. A full DJL release takes quite a lot of work (a week+ man days), and we like to rollout djl-bench quickly.

**Comment by bevanjkay** [comment]
@frankfliu I have updated the `livecheck` so that it will uses the latest tag available in the repo. My concern would still be that [this page](https://djl.ai/extensions/benchmark/) is still referencing `0.14.0` and could lead to confusion.

**Comment by frankfliu** [comment]
@bevanjkay 
The document website is built based on out githhub readme file: https://github.com/deepjavalibrary/djl/tree/master/extensions/benchmark

The docs update weekly, I will trigger a build once this is merged.

**Comment by bevanjkay** [comment]
Thank you @frankfliu

**Pull request merged**
