### PR TITLE
Upgrade to Java 8 Update 40

### PR DESCRIPTION
**Pull request by joschi**
Release notes: http://www.oracle.com/technetwork/java/javase/8u40-relnotes-2389089.html

### CODE REVIEW

**Comment by jeroenj** [comment]
Does this also install the Ask.com toolbar? http://www.macrumors.com/2015/03/05/ask-adware-java-mac/

If so we might look to get rid of it (optionally?) during installation.

**Comment by joschi** [comment]
> Does this also install the Ask.com toolbar?

No.

**Comment by jeroenj** [comment]
Thanks. Just confirmed it too. :) :+1:

**Comment by radeksimko** [comment]
@jeroenj I think the next version by default does install the adware, I was just looking into it yesterday, they also package it differently, feel free to jump in:
https://github.com/caskroom/homebrew-versions/issues/831

It will become a bigger issue when it gets "stable" sticker, so probably better to solve it for the beta version.

**Pull request merged**
