### PR TITLE
bilibili: move from bilibili-official

### PR DESCRIPTION
**Pull request by i0ntempest**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by i0ntempest** [comment]
A lot of discussions was already done in https://github.com/Homebrew/homebrew-cask/pull/124073. I think it's about the time we move this.

**Review by miccal — APPROVED** [review]

**Comment by undancer** [comment]
https://github.com/typcn/bilibili-mac-client/

这款软件的作者由于不可抗因素已经无法更新了。
即使移除官方app也不应该把它再添加回来，因为它早已经不能正常工作了。
The author of this software has been unable to update due to irresistible factors.
Even if you remove the official app, you should not add it back, because it can't work normally for a long time.

**Comment by i0ntempest** [comment]
> https://github.com/typcn/bilibili-mac-client/
> 
> 这款软件的作者由于不可抗因素已经无法更新了。 即使移除官方app也不应该把它再添加回来，因为它早已经不能正常工作了。 The author of this software has been unable to update due to irresistible factors. Even if you remove the official app, you should not add it back, because it can't work normally for a long time.

我没有移除任何东西，只是把原来的bilibili-official改成了bilibili而已。如果需要移除typcn那个app的话你可以另开个PR

**Comment by undancer** [comment]
> > https://github.com/typcn/bilibili-mac-client/
> > 这款软件的作者由于不可抗因素已经无法更新了。 即使移除官方app也不应该把它再添加回来，因为它早已经不能正常工作了。 The author of this software has been unable to update due to irresistible factors. Even if you remove the official app, you should not add it back, because it can't work normally for a long time.
> 
> 我没有移除任何东西，只是把原来的bilibili-official改成了bilibili而已。如果需要移除typcn那个app的话你可以另开个PR

那抱歉，我没有看提交记录。

Updated 4 taps (homebrew/cask-versions, homebrew/core, homebrew/cask and homebrew/cask-fonts).
==> New Formulae
pyyaml
==> New Casks
font-lxgw-bright-gb        languagetool               typcn-bilibili
font-lxgw-bright-tc        parallels17
==> Deleted Casks
bilibili-official ✘

这个更新内容让我误以为你删除了官方并新增了typcn

**Pull request merged**
