### PR TITLE
Add Tuist CLI version 3.18.0

### PR DESCRIPTION
**Pull request by danibachar**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions)
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by danibachar** [comment]
I found several cask without zap. So I'm not sure if adding a zap is mandatory.
This cask just downloads a binary which is removed on uninstall, so I don't see how a `zap` will help.
If I miss understand please advise on what to do.

**Comment by miccal** [comment]
Thank you @danibachar.

**Review by miccal — APPROVED** [review]

**Comment by carlocab** [comment]
Note that this is open-source and CLI-only. https://docs.brew.sh/Acceptable-Casks#rejected-casks

**Comment by miccal** [comment]
https://github.com/orgs/Homebrew/discussions/4439

**Comment by carlocab** [comment]
Yes. That doesn't mean it would be rejected if it were built from source, no?

**Comment by danibachar** [comment]
Thanks @carlocab - I opened a [discussion](https://github.com/orgs/Homebrew/discussions/4439) before the PR for this cask. And as Tuist is a pre-build universal binary I understood it would not get accepted to the homebrew/core repo. (it does not pass the validations) - Do you think it is still worth PR to homebrew/core?

I know I can have my own tap repo with formula, but prefer to have the installation as part of an official homebrew cask/core-formula.

What would you suggest to do?

**Pull request merged**
