### PR TITLE
Update java to 1.8.0_121-b13,e9e7ea248e2c4826b92b3f075a80e441

### PR DESCRIPTION
**Pull request by kurtrwall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you, but it seems the original `sha256` was correct.

**Comment by kurtrwall** [comment]
screen shot 2017-02-15 at 4 50 59 pm
According to this, the sha256 proposed seems to be what it's expecting.

**Comment by miccal** [comment]
@kurtrwall I cannot reproduce:
```
-bash-4.4.12- /Users/miccal [> brew cask fetch --verbose java
==> Downloading external files for Cask java
==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-macosx-x64.dmg
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.1.10-2-gec27b69b (Macintosh; Intel macOS 10.12.3) curl/7.51.0 --fail http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-macosx-x64.dmg -C 32186368 -o /Users/miccal/Library/Caches/Homebrew/Cask/java--1.8.0_121-b13,e9e7ea248e2c4826b92b3f075a80e441.dmg.incomplete -b oraclelicense=accept-securebackup-cookie
** Resuming transfer from byte position 32186368
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   527  100   527    0     0    830      0 --:--:-- --:--:-- --:--:--   830
100  192M  100  192M    0     0   198k      0  0:16:32  0:16:32 --:--:-- 45390
==> Verifying checksum for Cask java
==> Success! Downloaded to -> /Users/miccal/Library/Caches/Homebrew/Cask/java--1.8.0_121-b13,e9e7ea248e2c4826b92b3f075a80e441.dmg
```
```
-bash-4.4.12- /Users/miccal [> shasum -a 256 /Users/miccal/Library/Caches/Homebrew/Cask/java--1.8.0_121-b13\,e9e7ea248e2c4826b92b3f075a80e441.dmg 
82ff2493cd4b9ebdaeb9135abaffc9a37b71d341b007a83f73aa6ff3df1b6a3a  /Users/miccal/Library/Caches/Homebrew/Cask/java--1.8.0_121-b13,e9e7ea248e2c4826b92b3f075a80e441.dmg
```

**Comment by miccal** [comment]
@kurtrwall please run `brew cask cleanup` and try installing again.

**Comment by kurtrwall** [comment]
Thanks for the help, but that didn't seem to help. I've run `brew update` as per the suggestion in the error output as well.

**Comment by miccal** [comment]
@kurtrwall can you please post the output of `brew cask doctor`.

**Comment by kurtrwall** [comment]
```zsh
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.1.10
caskroom/homebrew-cask (git revision ac634; last commit 2017-02-16)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3553 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (38 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid (7 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1110 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
PATH="~/.virtualenvs/runway/bin:~/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/cask/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by miccal** [comment]
Very strange!

Can you please download `http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-macosx-x64.dmg` manually, and then run the command `shasum -a 256 <downloaded file>` and report what `sha256` value is reported?

**Comment by miccal** [comment]
For example, I get:
```
-bash-4.4.12- /Users/miccal [> shasum -a 256 /Users/miccal/Downloads/jdk-8u121-macosx-x64.dmg
82ff2493cd4b9ebdaeb9135abaffc9a37b71d341b007a83f73aa6ff3df1b6a3a  /Users/miccal/Downloads/jdk-8u121-macosx-x64.dmg
```

**Comment by kurtrwall** [comment]
I get the same: `82ff2493cd4b9ebdaeb9135abaffc9a37b71d341b007a83f73aa6ff3df1b6a3a  /Users/kurtwall/Downloads/jdk-8u121-macosx-x64.dmg`.

**Pull request closed without merging**
