### PR TITLE
hapigo 2.11.1,230 (new cask)

### PR DESCRIPTION
**Pull request by zzsqwq**
HapiGo is a application launcher and productivity software

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
We can use this for `livecheck` so that we can avoid `extract_plist`, but it doesn't look like there's versioned download links available. Will check again on the next update.

```ruby
  livecheck do
    url "https://hapigo.com/update/cast.plist"
    regex(%r{<key>version</key>\s*\n\s*<string>(\d+(?:\.\d+)+)</string>}i)
  end
```

**Comment by zzsqwq** [comment]
> We can use this for `livecheck` so that we can avoid `extract_plist`, but it doesn't look like there's versioned download links available. Will check again on the next update.
> 
> ```ruby
>   livecheck do
>     url "https://hapigo.com/update/cast.plist"
>     regex(%r{<key>version</key>\s*\n\s*<string>(\d+(?:\.\d+)+)</string>}i)
>   end
> ```

Now I have switched to using feed and regex for livecheck. Could you please help me check again? Also, since I am not the developer of this software, I currently cannot change the content in the feed. However, I will try to communicate with them later.

By the way, may I ask how you found the links related to updates? I did not find them in Info.plist.

**Comment by bevanjkay** [comment]
I used an application called Proxyman to intercept the requests the app makes when it checks for updates.

**Comment by zzsqwq** [comment]
> I used an application called Proxyman to intercept the requests the app makes when it checks for updates.

CleanShot 2023-12-02 at 16 33 57@2x

Oh, right. I forgot that I can use it to capture the request for checking updates. Thank you!

**Comment by bevanjkay** [comment]
When there is an update next it will be worth seeing if it points to a versioned download or just the same static 'latest' version.

**Comment by miccal** [comment]
Thank you @zzsqwq.

**Review by miccal — APPROVED** [review]

**Pull request merged**
