### PR TITLE
Fix MAMP 4.4.1 checksum

### PR DESCRIPTION
**Pull request by vvasilev-**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by stephenwade** [comment]
New SHA-256 is shown on the downloads page (https://www.mamp.info/en/downloads/).

screenshot of MAMP downloads page showing new SHA-256 value

**Comment by vitorgalvao** [comment]
@stephenwade The download URL and the homepage are on the same domain (and presumably server). If someone compromised the former, compromising the latter is child’s play; it’s just a string of characters on an HTML page.

**Comment by vvasilev-** [comment]
MAMP is too big to upload in VirusTotal.com so I ran a local check. Here is the result, I hope it's enough to confirm the signature.

```
$ openssl dgst -sha256 ./MAMP_MAMP_PRO_4.4.1.pkg
SHA256(./MAMP_MAMP_PRO_4.4.1.pkg)= 5eab5e3bcca0e7c9641d4cf21c7ee4a5698fa0c2ed798                                                                                                                                                                                               0cdb6a728de7857084b
```

**Pull request merged**
