### PR TITLE
Rename winbox to joshaven-winbox

### PR DESCRIPTION
**Pull request by nrlquaker**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Renamed as stated [here](https://github.com/caskroom/homebrew-cask/issues/39739).

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
What's the other winbox this could be mistaken for?

**Comment by nrlquaker** [comment]
[This one](https://mikrotik.com/download). The one in PR is just the MikroTik's with wine.

**Comment by commitay** [comment]
It looks like it doesn't run on mac so I don't think this is needed.

**Comment by nrlquaker** [comment]
But its the unofficial app with official-looking name, doesn't it?

**Comment by commitay** [comment]
Yeah, I suppose as upstream is repackaging the app.

**Review by commitay — APPROVED** [review]

**Pull request merged**
