### PR TITLE
Add Neo4j Desktop (latest: v1.0.14)

### PR DESCRIPTION
**Pull request by javatarz**
After making all changes to the cask:

- [x] `brew cask audit --download neo4j-desktop` is error-free.
- [x] `brew cask style --fix neo4j-desktop` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install neo4j-desktop` worked successfully.
- [x] `brew cask uninstall neo4j-desktop` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Review by commitay — APPROVED** [review]

**Comment by commitay** [comment]
@vitorgalvao Removing `-desktop` causes a conflict with the formula, should we keep `-desktop` rather than suffixing `-app`?

**Comment by vitorgalvao** [comment]
@commitay I’d rather we stay consistent. Keep in mind conflicting a name with a formula isn’t an issue if they are different things, even if related different things (`transmission` is a good example).

I’m not familiar with this app. Is it something different than the formula (no suffix), or just a thin wrapper around the CLI (`-app`)?

**Comment by javatarz** [comment]
Neo4j is a graph database. It comes as a binary that you can run as a service. The desktop app manages the service and provides a UI for quick local development. I'd expect "neo4j" to be *just* the database. Based on the document outlining naming schemes, if the installed app is called "Neo4j Desktop" then the cask should be named "neo4j-desktop".

**Comment by vitorgalvao** [comment]
> Based on the document outlining naming schemes, if the installed app is called "Neo4j Desktop" then the cask should be named "neo4j-desktop".

[Nope](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md#simplified-names-of-apps).

> Remove from the end: strings such as “Desktop”, “for Desktop”.

**Comment by javatarz** [comment]
Is there an override/exception that we can provide for the new name (neo4j)?

> I’m not familiar with this app. Is it something different than the formula (no suffix), or just a thin wrapper around the CLI (-app)?
The app available in homebrew-core is the neo4j binary for the database. This one includes the binary and has a GUI on top used for local development.

The reasoning for the changes @commitay added make sense but the CI review has failed. Does this need to be approved manually and merged or is there an expected change?

**Pull request merged**
