### PR TITLE
Update eudic.rb from 2020-04-27,3.9.6 to 3.9.9,2020-08-07

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by suschizu** [comment]
> Version decreased from `2020-04-27,3.9.6` to `2020-08-07,3.9.9`.

changed it to 3.9.9,2020-08-07 - i think this is the better notation in this case

**Review by reitermarkus — DISMISSED** [review]

**Comment by core-code** [comment]
it was the other way on purpose - otherwise we need 
`must_contain: version.after_comma`
but that would be fine too.

**Comment by suschizu** [comment]
> must_contain: version.after_comma

additionally to user_agent: fake ?
I think its better to go back to the former notation

**Comment by core-code** [comment]
well, no. user_agent is on the 'url' while must_contain would have to be on the 'appcast'

**Review by core-code — APPROVED** [review]

**Pull request merged**
