### PR TITLE
Upgrade Sage to version 7.1

### PR DESCRIPTION
**Pull request by feigaoxyz**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by feigaochn** [comment]
@vitorgalvao 
Thanks for your advice.
Anyway I can squash commits within github web interface?

**Comment by vitorgalvao** [comment]
> Anyway I can squash commits within github web interface?

No, the CLI id required for that. I’ll do it for you, then.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 2bfa792c6f64f7645d9a83322a643023dfeda206. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
