### PR TITLE
Update intellij-idea to 2017.3,173.3727.127

### PR DESCRIPTION
**Pull request by jollytoad**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by commitay — APPROVED** [review]
Verified locally.

**Comment by commitay** [comment]
Thanks for the PR!

**Comment by pgg** [comment]
Is it just me or is the checksum failing?

**Comment by bplommer** [comment]
@pgg No, same for me:
```
Error: Checksum for Cask 'intellij-idea' does not match.

Expected: 27dccf32fedde0b417af64ea3188bc34f9675403049fdb6c4edb891c14b5fc46
Actual:   affb3b7285cd82fe96a4cc63889b106aa2283d7537d0a8f0aee10353da5813c8
File:     /Users/ben/Library/Caches/Homebrew/Cask/intellij-idea--2017.3,173.3727.127.dmg
```
(`brew update` doesn't fix it, `brew doctor` reports no issues)

**Pull request merged**
