### PR TITLE
Update koodo-reader from 1.2.6 to 1.2.7

### PR DESCRIPTION
**Pull request by singularitti**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by singularitti** [comment]
Why is this not merged?

**Comment by cho-m** [comment]
@singularitti Probably no-one has gotten around to reviewing it yet.

May want to add ARM DMG too:
https://github.com/troyeguo/koodo-reader/releases/download/v1.2.7/Koodo-Reader-1.2.7-arm64.dmg

**Comment by singularitti** [comment]
> May want to add ARM DMG too:

How to write url with more than one architecture?

**Comment by cho-m** [comment]
> How to write `url` with more than one architecture?

You will want to use `if Hardware::CPU.intel? ... else ... end` logic.
Take a look at casks like [`intellij-idea`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/intellij-idea.rb), [`brave-browser`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/brave-browser.rb), etc as examples.

Once added, `brew bump-cask-pr` will update both branches.

**Review by cho-m — APPROVED** [review]
Thanks, @singularitti

**Pull request merged**
