### PR TITLE
Update mini-program-studio from 2.5.6,6d3b92d2-548c-4af2-a9fb-036b2d176e88 to 2.5.6,6d3b92d2-548c-4af2-a9fb-036b2d176e88

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
Redoing the accidentally undone correct part of https://github.com/Homebrew/homebrew-cask/pull/115257. @warmwinter Looking at https://opendocs.alipay.com/api/content/006l6m: are 2.7.x beta versions, 2.5.x stable versions and 2.3.x legacy versions (or whatever you want to call it)? If so, `livecheck` could maybe always pick 2.5.x?

**Comment by neutric** [comment]
@bevanjkay Would you mind slapping on a "awaiting user reply" or "in progress" label until we hear from @warmwinter on this one?

**Comment by neutric** [comment]
@miccal There are indeed three version tiers as suspected above: beta, stable and legacy.

Lifecheck currently does:
```
Matched Versions:
2.7.2,1073c5f0-0f2c-43f1-b3cb-6b701612b514 => #<Version:0x00007f9e1e9c55b8 @version="2.7.2,1073c5f0-0f2c-43f1-b3cb-6b701612b514", @detected_from_url=false>
2.5.6,6d3b92d2-548c-4af2-a9fb-036b2d176e88 => #<Version:0x00007f9e1e9c5568 @version="2.5.6,6d3b92d2-548c-4af2-a9fb-036b2d176e88", @detected_from_url=false>
2.3.8,fe8cec27-a3bc-45b2-a3db-ad8581e60687 => #<Version:0x00007f9e1e9c5518 @version="2.3.8,fe8cec27-a3bc-45b2-a3db-ad8581e60687", @detected_from_url=false>
mini-program-studio : 2.5.3,eff9a8c7-aead-4196-b9df-4559129a9709 ==> 2.7.2,1073c5f0-0f2c-43f1-b3cb-6b701612b514
```

How can I tell it to pick the second-highest version of the result set?

**Comment by bevanjkay** [comment]
@neutric I setup a livecheck with a two part match. We grab the `major_minor` of the stable branch first and then get the whole version.

**Comment by neutric** [comment]
Fine with me, although simply changing the regex to
```
regex(%r{稳定版.*?/([a-z\d-]+)/MiniProgramStudio[._-]v?(\d+(?:\.\d+)+)\.dmg}im)
```
would achieve the same result.

**Comment by bevanjkay** [comment]
@neutric That should work, but I think that the current solution should work a bit more accurately.

**Comment by neutric** [comment]
> @neutric That should work, but I think that the current solution will work a bit more accurately.

It is more flexible, that's for sure. As I said, I'm 👍.

**Pull request merged**
