### PR TITLE
Update FileZilla to v3.39.0

### PR DESCRIPTION
**Pull request by ghostwriter**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by ran-dall** [comment]
@nathane When I tried to audit this for you. I got this error...

```fish
brew cask audit filezilla --download                                                                                                              
==> Downloading https://download.filezilla-project.org/client/FileZilla_3.39.0_macosx-x86.app.tar.bz2
######################################################################## 100.0%
curl: (16) Error in the HTTP2 framing layer
audit for filezilla: failed
 - download not possible: Download failed on Cask 'filezilla' with message: Download failed: https://download.filezilla-project.org/client/FileZilla_3.39.0_macosx-x86.app.tar.bz2
Error: audit failed for casks: filezilla
```

**Comment by nathane** [comment]
@ran-dall this commit is not the issues. Similar to #52149 #53634 ... It doesn't matter, looks like it's getting removed. #55583

**Comment by ran-dall** [comment]
@nathane Good info BTW. Thank you 🙏

I would just close this if it's getting deleted.

**Comment by ran-dall** [comment]
Closed in favor of https://github.com/Homebrew/homebrew-cask/pull/55583

**Comment by LanikSJ** [comment]
I was able to download just fine:
```
○ → wget https://download.filezilla-project.org/client/FileZilla_3.39.0_macosx-x86.app.tar.bz2
--2018-11-30 18:18:17--  https://download.filezilla-project.org/client/FileZilla_3.39.0_macosx-x86.app.tar.bz2
Resolving download.filezilla-project.org (download.filezilla-project.org)... 136.243.154.86
Connecting to download.filezilla-project.org (download.filezilla-project.org)|136.243.154.86|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10507520 (10M) [application/x-bzip2]
Saving to: ‘FileZilla_3.39.0_macosx-x86.app.tar.bz2’

FileZilla_3.39.0_macosx-x86.app.tar.bz2                        100%[==================================================================================================================================================>]  10.02M  4.17MB/s    in 2.4s

2018-11-30 18:18:20 (4.17 MB/s) - ‘FileZilla_3.39.0_macosx-x86.app.tar.bz2’ saved [10507520/10507520]
```

**Comment by ran-dall** [comment]
@LanikSJ Good. Regardless I think the best course-of-action is to remove the cask; as @suschizu has done in #55583. 👈

**Pull request closed without merging**
