### PR TITLE
Add TipTyper.app v2.6.4

### PR DESCRIPTION
**Pull request by Jerzerak**
#### Adding a new cask
- [x] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Commit message includes cask’s name.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by adidalal** [comment]
```
==> 1 modified cask: tiptyper
==> Downloading https://www.brunophilipe.com/software/tiptyper/getfile.php?versi
######################################################################## 100.0%
==> Verifying checksum for Cask tiptyper
==> Note: running "brew update" may fix sha256 checksum errors
audit for tiptyper: failed
 - download not possible: sha256 mismatch
Expected: a09d958bce89dd458f03a6b941fa65816bffc5fce4031f9d3d6902f1c80947e0
Actual: d454304ed57b4672306159baff22dfd4344b0a64cb86a8de3d3fcc93151bcaed
File: /Library/Caches/Homebrew/tiptyper-2.6.4.4&token=5f828bbf797d4ad6
To retry an incomplete download, remove the file above.
Error: audit failed for 1 cask: tiptyper
```

**Comment by Jerzerak** [comment]
The sha256 on the download here seems to be outputting 2 different values...this happened when I was testing this as well but `brew cask audit --download tiptyper` passed 4/5 times using the current committed value, so that's the one I went with.

**Comment by adidalal** [comment]
@Jerzerak use `https://www.brunophilipe.com/software/tiptyper/releases/releasen-2.6.4.zip` (add in the version interpolation, also)

**Comment by Jerzerak** [comment]
@adidalal Mind if I ask how you came up with that url?

**Comment by adidalal** [comment]
@Jerzerak Sure, it's in the appcast.php (under the enclosure/url xml tag)

**Comment by Jerzerak** [comment]
Ok now I feel stupid, don't know how I missed that one...squashing the new url right now

**Comment by adidalal** [comment]
No worries, and thanks again for the contribution! 👍

**Pull request merged**
