### PR TITLE
update most jetbrains casks to include build number

### PR DESCRIPTION
**Pull request by leipert**
Recently we had to update the casks intellij-idea (https://github.com/caskroom/homebrew-cask/pull/31190) and intellij-idea-ce (https://github.com/caskroom/homebrew-cask/pull/31209), because jetbrains swapped out the `2017.1` with another build.

This commit adds the `build` number to the version string. The `build` number is publicly announced at the app casts, for example here for clion: https://data.services.jetbrains.com/products/releases?code=CL&latest=true&type=release

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by miccal** [comment]
If every one of these Casks uses `#{version.before_comma}` only in the interpolation, then what is the purpose of the `version` after the comma?

**Comment by leipert** [comment]
The purpose of it is being a bit more verbose if a background swap of binaries by jetbrains happens (See linked merge requests in initial comment).

The ` #{version.after_comma}` could actually be used in the appcast url for example:

https://data.services.jetbrains.com/products/releases?code=AC&build=163.13906.24

instead of 

https://data.services.jetbrains.com/products/releases?code=AC&latest=true&type=release

I do not know if the appcast url should contain a version number or not

**Review by victorpopkov — APPROVED** [review]

**Comment by miccal** [comment]
@leipert are you able to fix the merge conflicts?

**Comment by leipert** [comment]
done 👍 
Do you think, we should update the app cask urls to contain the build number?

**Comment by reitermarkus** [comment]
> Do you think, we should update the app cask urls to contain the build number?

Does the appcast change if the build number is given as a parameter, or does it just show this build number's release notes? It should always change if there is a new version.

**Comment by leipert** [comment]
> It should always change if there is a new version.

Then the cast url should remain as they are

**Comment by leipert** [comment]
So what do the maintainers think? Do we want do this change or not?

**Comment by leipert** [comment]
👍 

Updated @jcbot to 1.1.0 for automatic updates including build number:
https://github.com/leipert/jetbrains-cask-bot/releases/tag/v1.1.0

**Pull request merged**
