### PR TITLE
Add Nike+ Connect Latest

### PR DESCRIPTION
**Pull request by FredLackeyOfficial**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t][version-checksum],  
      provide public confirmation by the developer: {{link}}

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
Already exists in `caskroom/drivers`: [nike-plus-connect](https://github.com/caskroom/homebrew-drivers/blob/master/Casks/nike-plus-connect.rb)

**Comment by FredLackeyOfficial** [comment]
Ugh.  That sucks.  What's the best way to search for an existing cask?  Is there one mechanism that'll cover drivers, unofficial, etc.?

**Comment by commitay** [comment]
Won't work with `unofficial` but `brew search` (not `brew cask search`) will check the caskroom repos even if they are untapped. 
```
$ brew untap caskroom/drivers
Untapping caskroom/drivers... (146 files, 170.4KB)
Untapped 0 formulae

$ brew search nike
caskroom/drivers/nike-plus-connect
```

Usually I just search the github [caskroom organisation](https://github.com/caskroom) as it will show casks that have been moved or deleted.

**Comment by FredLackeyOfficial** [comment]
Good to know... thanks.  👍

**Pull request closed without merging**
