### PR TITLE
Update real-vnc to 6.0.1

### PR DESCRIPTION
**Pull request by colindunn**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by colindunn** [comment]
Not sure of the process for multiple uninstall scripts (this cask installs two separate applications) so have used /bin/sh to accomplish that. Couldn't see a better way in the docs, so let me know if there is a better method.

**Comment by miccal** [comment]
See the Cask for [ransomwhere](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ransomwhere.rb) for an example.

**Comment by vitorgalvao** [comment]
Try `script:` twice. That might work.

Also, judging by the `caveat` you might need [`must_suceed: false`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#summary-of-keys) on one of them.

**Comment by colindunn** [comment]
That was the first thing I tried, but unfortunately it doesn't work it just uses the last entry specified. The scripts still succeed correctly despite the error message, so I didn't add the must_succeed.

**Comment by vitorgalvao** [comment]
Is it possible to add a `pkgutil:` as well?

**Comment by colindunn** [comment]
The uninstallers take care of that. I haven't used app and pkg removal because the uninstallers should take care of the application through version changes, as well as remove registered services etc.

Package installed:

```
> pkgutil --pkgs|grep vnc
com.realvnc.vncserver.pkg
com.realvnc.vncviewer.pkg
```

Removal and result:

```
> brew cask uninstall real-vnc
==> Running uninstall process for real-vnc; your password may be necessary
==> Running uninstall script /bin/sh
==> ls: /Applications/RealVNC/Advanced.localized: No such file or directory
==> /Applications/RealVNC/Uninstall VNC Server.app/Contents/Resources/uninstallCommon.sh: line 27: /Applications/RealVNC/Uninstall VNC Server.app/Contents/Resources/removeFwExc.sh: No such file or directory
==> No receipt for 'com.realvnc.VNCServer.pkg' found at '/'.
==> Forgot package 'com.realvnc.vncserver.pkg' on '/'.
==> ls: /Applications/RealVNC/Advanced.localized: No such file or directory
==> No receipt for 'com.realvnc.VNCViewer.pkg' found at '/'.
==> Forgot package 'com.realvnc.vncviewer.pkg' on '/'.
 > pkgutil --pkgs|grep vnc
```

**Comment by vitorgalvao** [comment]
I have no doubt the installers do it, but we usually prefer not to trust the installer scripts *only*, and also add out own uninstallation to make sure everything is done.

**Comment by colindunn** [comment]
Put this one on hold and I'll update it to do removal via cask options

**Comment by colindunn** [comment]
Changes made. Seems to work OK as far as I can tell and remove everything.

**Review by adidalal — APPROVED** [review]

**Comment by vitorgalvao** [comment]
Oh, I meant adding `pkgutil:` **in addition to**. The point is to make really sure.

**Comment by miccal** [comment]
Sorry @vitorgalvao, I saw the approval and just merged after a quick check.

**Comment by vitorgalvao** [comment]
@miccal Not a problem.

@colindunn Would it be alright for you to please add it back? The more I think about, the more I’m unsure `script:` is the right place. We are indeed calling a script from the app, but using `bin/sh` to do it seems weird. Perhaps an `uninstall_preflight` would be more appropriate. And perhaps even redirect the error message, so we can get rid of the caveat.

**Comment by miccal** [comment]
Can you have two `executable:`'s in an `uninstall script:`, like two of [these](https://github.com/caskroom/homebrew-cask/blob/master/Casks/ezeep.rb#L12#L14)?

**Comment by colindunn** [comment]
Sorry missed these comments in my email. I will have another go at this later today when I get the chance, no worries.

**Pull request merged**
