### PR TITLE
Added KeeWeb.app v1.0

### PR DESCRIPTION
**Pull request by antelle**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 080a1eafdd90591595252693aa70cf7b8f51e47f. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by antelle** [comment]
Thanks! I'm new to cask, it was not clear for me that I had to run `brew cask style Casks/keeweb.rb` before push, I've just checked if audit passed, now I see my mistake.

**Comment by adidalal** [comment]
@antelle Thanks for the PR! You can find beginner documentation [here](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md) (linked from CONTRIBUTING)- is there anything we could do to make this clearer for first-time contributors?

**Comment by vitorgalvao** [comment]
@antelle I also added [a required (in this case) comment](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment), whose [rules are being refined](https://github.com/caskroom/homebrew-cask/pull/18051).

**Pull request closed without merging**
