### PR TITLE
Update yourkit-java-profiler.rb from 2019.8,b142 to 2020.7,b369

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by core-code** [comment]
download protection, try `curl 'https://www.yourkit.com/download/YourKit-JavaProfiler-2020.7-b369.dmg'`

maybe faking the user-agent helps

**Comment by core-code** [comment]
it seems failures aren't really connected to the user-agent but random. it works every third time or so. but the problem isn't related to the update, it is the same for the current version.

**Comment by core-code** [comment]
@vitorgalvao should we delete this?
```

% brew cask fetch yourkit-java-profiler 

==> Downloading external files for Cask yourkit-java-profiler
==> Downloading https://www.yourkit.com/download/YourKit-JavaProfiler-2019.8-b142.dmg
##O#- #                                                                       
curl: (22) The requested URL returned error: 429 
Error: Download failed on Cask 'yourkit-java-profiler' with message: Download failed: https://www.yourkit.com/download/YourKit-JavaProfiler-2019.8-b142.dmg

```

**Comment by miccal** [comment]
It appears that the `url` has rate-limiting:
```
|-> curl -sLI https://www.yourkit.com/download/YourKit-JavaProfiler-2019.8-b142.dmg
HTTP/1.1 429 Too Many Requests
```

**Comment by vitorgalvao** [comment]
Can’t even download it locally, so that’s a problem. We may indeed be forced to remove it.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/87163

**Comment by vladimirkondratyev** [comment]
The URL is functional, but rate limited by IP.

**Comment by core-code** [comment]
if the rate limiting is *this* bad it is effectively a non-functional URL

**Comment by bcalmac** [comment]
Linking to the conversation from the YourKit forum: https://www.yourkit.com/forum/viewtopic.php?f=3&t=41627

**Comment by vladimirkondratyev** [comment]
Rate is configured now 5 downloads per minute per IP.  Just checked that curl https://www.yourkit.com/download/YourKit-JavaProfiler-2020.7-b376.dmg works.

**Comment by core-code** [comment]
feel free to send a pull request to revert the deletion. i'm sure it will be considered.

**Comment by mpolden** [comment]
The rate limit no longer seems to be a problem in practice, but Homebrew still triggers the rate limit. This because Homebrew tries to discover if the URL is a redirect by running `curl --location --silent --head --request GET <url>` before doing the actual download. So the two requests together triggers the rate limit.

I don't see a way to work around it.

**Pull request closed without merging**
