### PR TITLE
Add RapidMiner Studio 7.2.3

### PR DESCRIPTION
**Pull request by longstone**
_If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so._

After making all changes to the cask:
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:
- [x] Named the cask according to the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [1] Checked that the cask was not already refused in [closed issues](https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed).

1 -> https://github.com/caskroom/homebrew-cask/pull/10419 - I'm not sure...

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This is still a walled build, so still will not be accepted.

**Comment by longstone** [comment]
where should i put it - hombrew-unofficial is not existing anymore?

**Comment by reitermarkus** [comment]
Use a personal tap.

**Comment by vitorgalvao** [comment]
`unofficial` still exits, it’s just under our sister org, [alehouse](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#unofficial-vendorless-and-walled-builds).

**Pull request closed without merging**
