### PR TITLE
Add Micronaut CLI 2.0.0.M3

### PR DESCRIPTION
**Pull request by alvarosanchez**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by alvarosanchez** [comment]
Note that [there is a `micronaut` formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/micronaut.rb) that is intended to be used for 1.x versions.

From 2.x onwards, we are also shipping pre-compiled native executables built with GraalVM, which is what this cask installs.

**Comment by vitorgalvao** [comment]
This should continue to be a formula, upgrading the one that‘s there. Why isn’t it?

Having v1 of a software as a formula and v2 as a cask is confusing to a point I don’t think we want to pursue.

**Comment by alvarosanchez** [comment]
I agree it should be a formula, and that was my initial approach.

However, the `audit` command failed saying:

```
https://github.com/micronaut-projects/micronaut-starter/releases/download/v/mn-darwin-amd64-v.zip looks like a binary package, not a source archive; homebrew/core is source-only.
```

That led me to create a cask instead.

**Comment by vitorgalvao** [comment]
Well, yes, but if v1 can be built from source as a formula, why can’t v2?

**Comment by alvarosanchez** [comment]
v1 isn't built from source either. The zip contains a pre-copmiled JAR file and a startup script that does `java -jar` under the hood. I believe this is the common approach for Java-based applications. 

Note that we (the Micronaut team) didn't create the original formula, but is our plan to keep it up-to-date automatically going forward.

**Comment by vitorgalvao** [comment]
> Having v1 of a software as a formula and v2 as a cask is confusing to a point I don’t think we want to pursue.

You haven’t addressed that. Why have both?

**Comment by alvarosanchez** [comment]
No reason why. I don't want to pursue having both either. Happy to contribute an upgrade of the existing formula, but like I said, the audit fails.

**Comment by vitorgalvao** [comment]
> I don't want to pursue having both either.

Then we should only have one. You should first submit a PR to [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core) to remove v1, and when that’s accepted (alternatively, that part of the team may be able to get it to compile from source as a formula) we can merge the cask.

**Comment by alvarosanchez** [comment]
https://github.com/Homebrew/homebrew-core/pull/56440

**Pull request closed without merging**
