### PR TITLE
Update gloomhaven-helper from 8.4.4 to 8.4.5

### PR DESCRIPTION
**Pull request by samuelmurray**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by core-code** [comment]
```
==> Verifying SHA-256 checksum for Cask 'gloomhaven-helper'.
audit for gloomhaven-helper: failed
 - https://esotericsoftware.com/gloomhaven-helper permanently redirects to http://esotericsoftware.com/gloomhaven-helper
```
not sure if changing to http will actually be better

**Comment by samuelmurray** [comment]
I tried changing 'url' and 'homepage' to http, but then running `brew cask audit --download Casks/gloomhaven-helper.rb` resulted in
```
==> Downloading http://esotericsoftware.com/files/ghh/GloomhavenHelper-8.4.6.zip
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'gloomhaven-helper'.
audit for gloomhaven-helper: failed
 - The URL http://esotericsoftware.com/files/ghh/GloomhavenHelper-8.4.6.zip should use HTTPS rather than HTTP
Error: audit failed for casks: gloomhaven-helper
```
I guess 'homepage' could be changed to http and keep url as https to please the audit check. What do you think?

**Comment by core-code** [comment]
i'm deferring to higher powers. @vitorgalvao whats your opinion?

**Comment by vitorgalvao** [comment]
It’s already merged, so no need to change now. We can change it on the next update if the homepage’s HTTPS issue isn’t yet solved by then.

**Pull request merged**
