### PR TITLE
Remove Travis CI

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
GitHub Actions is now used instead.

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]
I agree with only having one CI and making it GitHub’s, but I’ll point out that lately it has been the more unreliable of the two, in case someone has experienced the same and wants to comment on it / knows why / has a solution.

**Comment by core-code** [comment]
i don't have any hard numbers but i think i can confirm that the Github Actions are even more (!) unreliable than Travis.

however since currently CI fails if *any* of the checks fails, we are still better off even if we remove the more reliable one.

**Comment by MikeMcQuaid** [comment]
> I agree with only having one CI and making it GitHub’s
> however since currently CI fails if _any_ of the checks fails, we are still better off even if we remove the more reliable one.

👍🏻 Merging given this for now.

**Comment by reitermarkus** [comment]
Reverting this since this broke CI and `automerge` still relies on Travis.

**Pull request merged**
