### PR TITLE
Initial commit for OpenBoardView

### PR DESCRIPTION
**Pull request by byassine52**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
I see that the website links to the `inflex` fork. But why? Is that website official?

**Comment by inflex** [comment]
Evening all, thanks for tagging me.

Interesting coincidence because I was just running around trying to get brew to do various things on my macOS machines for more development.

The reason for the binary being built off my fork was we found for some reason that travis-ci wouldn't deploy to an organisation in github, so subsequently we just built off one of the user forks and uploaded manually.

I'd suggest that https://github.com/piernov ( @piernov ) probably be engaged in this as he handles most of the technical deployment/compile/integration work.

**Comment by byassine52** [comment]
@pierno could you please help in choosing the right binary download link for OpenBoardView?
We need your confirmation to close this issue.

**Comment by reitermarkus** [comment]
Merging this now since the website is indeed pointing to @inflex's fork.

**Pull request merged**
