### PR TITLE
Add JazzUp.app latest

### PR DESCRIPTION
**Pull request by goranmoomin**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Website is down since yesterday. Leaving on hold.

**Comment by pcr910303** [comment]
@vitorgalvao Wow, that's a jarring coincidence :-( Looks like the (newly running) tests would fail then :-(

**Comment by pcr910303** [comment]
@vitorgalvao Looks like the webpage is back again.
@BrewTestBot please test this

**Comment by pcr910303** [comment]
@vitorgalvao Looks like the webpage is back again.
@BrewTestBot test this please

**Comment by vitorgalvao** [comment]
> Just triggered the tests by rebasing/force-pushing without any changes!

Closing and reopening the PR should also work.

Found and added an appcast. Please change `url` to link in it, as well as adding `version` and `sha256`.

**Pull request merged**
