### PR TITLE
Update JOSM caveats

### PR DESCRIPTION
**Pull request by sjparkinson**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [ ] ~The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).~

---

* Updates the Java caveat to include support for the latest version of Java.
* Adds a text caveat to suggest running `spctl --add /Applications/JOSM.app` so that users don't have to right click the app when opening it for the first time.

The install output now looks like...

```
$ brew cask reinstall josm
==> Caveats
You will need to add josm as an exception to your security settings with

  spctl --add /Applications/JOSM.app

josm requires Java 8+. You can install the latest version with

  brew cask install java

==> Satisfying dependencies
==> Downloading https://josm.openstreetmap.de/download/macosx/josm-macosx-14824.zip
Already downloaded: /Users/samuel/Library/Caches/Homebrew/downloads/526c2e576191dbb6dc15e2b67e89a4cf90d7cdbd69f03c6c65a85d1bb208cecb--josm-macosx-14824.zip
==> Verifying SHA-256 checksum for Cask 'josm'.
==> Uninstalling Cask josm
==> Backing App 'JOSM.app' up to '/usr/local/Caskroom/josm/14824/JOSM.app'.
==> Removing App '/Applications/JOSM.app'.
==> Purging files for version 14824 of Cask josm
==> Installing Cask josm
==> Moving App 'JOSM.app' to '/Applications/JOSM.app'.
🍺  josm was successfully installed!
```

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by sjparkinson** [comment]
The support for the latest Java versions relates to changes made as part of https://josm.openstreetmap.de/ticket/17278.

**Comment by sjparkinson** [comment]
https://github.com/Homebrew/homebrew-cask/pull/59787/commits/1628f5195e7474be7f5a658e5700372cb0039d87 could also include a command for `xattr -d com.apple.quarantine /Applications/JOSM.app`. Worth adding?

https://stackoverflow.com/a/4833168

**Comment by sjparkinson** [comment]
> [1628f51](https://github.com/Homebrew/homebrew-cask/commit/1628f5195e7474be7f5a658e5700372cb0039d87) could also include a command for `xattr -d com.apple.quarantine /Applications/JOSM.app`. Worth adding?
> 
> https://stackoverflow.com/a/4833168

Don't think I like this though, it deletes the attribute, rather than it being modified when you accept the warning dialogue.

**Comment by vitorgalvao** [comment]
> * Adds a text caveat to suggest running `spctl --add /Applications/JOSM.app` so that users don't have to right click the app when opening it for the first time.

That’s a feature, not a bug. We want users to be security-conscious, not bypass. We *added* quarantining on purpose, by default we didn’t have it.

**Pull request merged**
