### PR TITLE
odrive 7441

### PR DESCRIPTION
**Pull request by khipp**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
audit for odrive: failed
 - Version '7441' differs from '' retrieved by livecheck.
 - Version '7441' differs from '' retrieved by livecheck.
```

**Comment by p-linnane** [comment]
`curl` is returning a 405 error. Paging @samford to see if they have any ideas.

**Review by samford — COMMENTED** [review]
Thanks for flagging this. The `livecheck` block URL returns a 405 if `HEAD` is used but returns the expected 302 response (with the `location` header we want) if `GET` is used. The curl exit code is 56 (failure in receiving network data), which is another one that I've been seeing in failing `HeaderMatch` checks recently.

I have some stashed work to add 56 to the curl exit codes that `#curl_header` will automatically retry with `GET` and that will allow this (and a few others) to work for the time being. I'll create a brew PR for it in a bit (edit: https://github.com/Homebrew/brew/pull/18279).

**Review by samford — APPROVED** [review]
The related brew PR is merged and this passes CI now 👍

**Pull request merged**
