### PR TITLE
Update file-juicer to 4.66

### PR DESCRIPTION
**Pull request by zorae**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by commitay** [comment]
@vitorgalvao This is another case of VirusTotal rejecting the signature but it passes locally.

https://www.virustotal.com/#/file/34ba205e5ac834cda950821ef4508f5b6d20f9a54b38c94eec961d62838831ce/details

```
Executable=/Users/commitay/File Juicer.app/Contents/MacOS/File Juicer
Identifier=com.echoone.FileJuicer
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=7766 flags=0x0(none) hashes=237+3 location=embedded
Signature size=8917
Authority=Developer ID Application: Henrik Dalgaard (HCFWG8346D)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=4 Apr 2018 at 23:58:05
Info.plist entries=38
TeamIdentifier=HCFWG8346D
Sealed Resources version=2 rules=13 files=82
Internal requirements count=1 size=184

File Juicer.app: valid on disk
File Juicer.app: satisfies its Designated Requirement
```

**Comment by vitorgalvao** [comment]
Either they have a bug, or they know something we don’t. Either way, we probably should contact them about it.

**Comment by commitay** [comment]
I've sent them an email.

**Comment by commitay** [comment]
Got an email back, they aren't sure and are investigating.

**Comment by commitay** [comment]
Another email:

> Upon testing it seems we apply the tag upon first analysis, but if further analysis yield different results, then the tag still applies. 

> Not sure if it's a feature or a bug, i can see how it may be useful, but let me circle this back to our engineers to make sure this is the intended behavior or we need to file as a bug!

**Comment by commitay** [comment]
Another `sha256` change but it passes VirusTotal.

> https://www.virustotal.com/#/file/716f38251ed389a9cf6faedd10bf5f2028a8344b6c0dba0f47d9945aac7cb540/details

```
Executable=/Users/commitay/File Juicer.app/Contents/MacOS/File Juicer
Identifier=com.echoone.FileJuicer
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=7766 flags=0x0(none) hashes=237+3 location=embedded
Signature size=8918
Authority=Developer ID Application: Henrik Dalgaard (HCFWG8346D)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=9 Apr 2018 at 23:58:17
Info.plist entries=38
TeamIdentifier=HCFWG8346D
Sealed Resources version=2 rules=13 files=82
Internal requirements count=1 size=184

File Juicer.app: valid on disk
File Juicer.app: satisfies its Designated Requirement
```

**Review by commitay — APPROVED** [review]

**Pull request merged**
