### PR TITLE
feat(docker): add m1 support

### PR DESCRIPTION
**Pull request by dalisoft**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

Related issue: #103448 
I am **not sure** it is correct or not, it's my first contribution

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, and welcome.

Looks good. The one thing you need to take care when editing from the web interface is make sure there isn’t trailing whitespace (typically empty lines).

**Review by vitorgalvao — DISMISSED** [review]

**Comment by dalisoft** [comment]
I now trying get sha256 sums, i'll try fix as soon as i can get, seems i forgot. Thanks

**Comment by dalisoft** [comment]
@vitorgalvao Thanks for help and update. I updated checksum and i think it can be merged once all CI passes, right?

**Comment by vitorgalvao** [comment]
> @vitorgalvao Thanks for help and update. I updated checksum and i think it can be merged once all CI passes, right?

Right. Which is right now! Thank you again for the contribution.

**Review by vitorgalvao — DISMISSED** [review]

**Comment by ykursadkaya** [comment]
FYI there are 2 appcasts for AMD64 and ARM64 respectively.

AMD64: [https://desktop.docker.com/mac/stable/amd64/appcast.xml](https://desktop.docker.com/mac/stable/amd64/appcast.xml)
ARM64: [https://desktop.docker.com/mac/stable/arm64/appcast.xml](https://desktop.docker.com/mac/stable/arm64/appcast.xml)

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
