### PR TITLE
Update adguard to 1.5.3

### PR DESCRIPTION
**Pull request by vityevato**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Welcome and thank you, @Stillness-2.

Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by Stillness-2** [comment]
@vitorgalvao I am developer of the Adguard :)
https://github.com/AdguardTeam/AdguardForMac/releases/tag/v1.5.3.438
https://github.com/AdguardTeam/AdguardForMac/issues/288

**Comment by Stillness-2** [comment]
We released a hot fix without changing version number

**Comment by vitorgalvao** [comment]
Thank you! Merging.

**Pull request merged**
