### PR TITLE
add hp-connectivity-kit version 20181016

### PR DESCRIPTION
**Pull request by mircomacrelli**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
What exactly is this? Is this software to interact with a calculator?

**Comment by mircomacrelli** [comment]
Yes. Its an interface that gives access to the calculator content and an editor to write programs without using the keyboard on the device.

**Comment by vitorgalvao** [comment]
Would you ever want this if you don’t have the physical calculator?

**Comment by mircomacrelli** [comment]
Personally no. I know It's useful in classrooms to control remotely students' calculators but I don't care about these features.

**Comment by vitorgalvao** [comment]
To clarify, I’m not asking about you specifically. I want to know if the software is useful without the physical calculator. Because if it is not, it belongs [in another repo](https://github.com/Homebrew/homebrew-cask-drivers). That is why I’m making the same questions in both PRs, in case one is and the other isn’t.

**Comment by vitorgalvao** [comment]
According to https://github.com/Homebrew/homebrew-cask/pull/60803#issuecomment-475971884, please submit this one to the other repo and I’ll merge it there.

**Pull request closed without merging**
