### PR TITLE
mounty 2.0

### PR DESCRIPTION
**Pull request by uwehollatz**
Thank you very much for your efforts!
I have added dependencies to Mounty - especially a formulae which is only available after tapping. Can you please check if it's sufficient? Cheers.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ x] `brew audit --cask --online <cask>` is error-free.
- [ x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@uwehollatz Is there any documentation that shows the dependency requirements?

**Comment by miccal** [comment]
From the `homepage`:

Screenshot 2023-03-13 at 06 30 14

`ntfs-3g-mac` is from a tap, namely `gromgit/homebrew-fuse`, and we cannot depend on a Formula or Cask from an external tap.

Will this not work with `ntfs-3g` Formula from `homebrew-core`?

**Comment by uwehollatz** [comment]
Am 12.03.2023 um 23:32 schrieb Miccal Matthews ***@***.***>:
> ntfs-3g-mac is from a tap, namely gromgit/homebrew-fuse, and we cannot depend on a Formula or Cask from an external tap.
> 
> Will this not work with ntfs-3g Formula from homebrew-core?
> 
Thanks much, this is what I thought … let me check the Formula from Tuxera, if it might be sufficient. I'll update my pull request then.

—Uwe

**Comment by miccal** [comment]
Ping @gromgit for their thoughts.

**Comment by gromgit** [comment]
I agree with @miccal's concerns here. Nothing in core Homebrew should depend on stuff outside Homebrew's control, since that leads to issues that `homebrew/cask` maintainers are responsible for (the cask is hosted by Homebrew) but are unable to resolve (the real problem is with a third-party dependency).

Much as I'd hate to say this, if `mounty` now depends on my work, then it should be moved to a third-party tap. That said, I'd be happy to host it under `gromgit/fuse`, then the logical place to file issues is also the project that actually has a chance of resolving it. (I just hope I don't regret this down the line. :grinning: )

However, since I've only now been looped into this PR, I have to ask: what tests failed with [the previous commit that had declared dependencies](https://github.com/Homebrew/homebrew-cask/pull/142939/commits/c4f1618173aed297d7af200c3e238decc1928c77)?

**Comment by uwehollatz** [comment]
@gromgit I think the install test failed (because of that dependency not working)
Mounty is a cask by itself, so it's available as an image file (dmg), no open source to host on GitHub currently.
I am not sure but can we now go ahead? I have already removed ntfs-3g-mac as dependency. It needs to be added manually - before or after Mounty installation :)

**Comment by gromgit** [comment]
Note that I'm a Homebrew _member_ but not a _maintainer_, so it's not up to me to merge or reject this PR.

All I can confirm is:
* the original PR (with the `ntfs-3g-mac` dependency) passes audit, and correctly triggers the installation of `ntfs-3g-mac` on my Monterey M1 Mac
* if this PR is rejected, I'm willing to "adopt" it on my existing tap (`gromgit/fuse`), just as I adopted all existing FUSE formulae for macOS when Homebrew originally disabled them
* if MacFUSE resolves the licensing issue that made the macOS FUSE migration necessary, _and_ upgrades macOS `libfuse` to v3, I'll work to merge everything back to Homebrew core (the latter condition is why some formulae are stuck on old versions in my tap)

**Comment by miccal** [comment]
> * the original PR (with the `ntfs-3g-mac` dependency) passes audit, and correctly triggers the installation of `ntfs-3g-mac` on my Monterey M1 Mac

It did not pass our CI tests:
```
/usr/local/Homebrew/Library/Homebrew/formulary.rb:579:in `get_formula': No available formula with the name "ntfs-3g-mac". Did you mean ntfs-3g? (FormulaUnavailableError)
```

**Comment by miccal** [comment]
> * if this PR is rejected, I'm willing to "adopt" it on my existing tap (`gromgit/fuse`), just as I adopted all existing FUSE formulae for macOS when Homebrew originally disabled them

Since we cannot depend on a Formula or Cask from an external tap, I would suggest that we remove this from `homebrew-cask` and take up @gromgit's offer to host this in their tap.

We could also keep version 1.x in `homebrew-cask` and add a `caveat` explaining that version 2.x is available via an external tap, provided version 1.x will continue to be updated and maintained.

**Comment by uwehollatz** [comment]
> Sorry, I misread the original commit. I actually added:
> 
> ```
> depends_on "gromgit/fuse/ntfs-3g-mac"
> ```
> 
> on my copy of `mounty.rb` in `gromgit/fuse`, which didn't have any issues.

I've added 

depends_on formula: "gromgit/fuse/ntfs-3g-mac"

but still failing with:

/usr/local/Homebrew/Library/Homebrew/formulary.rb:392:in `load_file': No available formula with the name "gromgit/fuse/ntfs-3g-mac". (TapFormulaUnavailableError)
[49](https://github.com/Homebrew/homebrew-cask/actions/runs/4414261720/jobs/7735758628#step:12:50)
Please tap it and then try again: brew tap gromgit/fuse

I would agree with @gromgit 's offer and the caveat, thanks much @gromgit and @miccal for your support here. Please let me know what I need to do now ... much appreciated :)

**Comment by uwehollatz** [comment]
> I've [committed `gromgit/fuse/mounty`](https://github.com/gromgit/homebrew-fuse/blob/main/Casks/mounty.rb), so installing Mounty is a one-step `brew install gromgit/fuse/mounty` for both 1.x and 2.x. I think that makes more sense going forward, than trying to split the difference with core.

Cool thanks, one remark: I've tried to install with that one-liner but got exception about MacFuse:

ntfs-3g-mac: This formula requires macFUSE. Please run `brew install --cask macfuse` first.
Error: An unsatisfied requirement failed this build.

Any way to cascade this dependency?

**Pull request closed without merging**
