### PR TITLE
created cask for Network Radar

### PR DESCRIPTION
**Pull request by guydebros**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by miccal** [comment]
[This may be suitable for an `appcast`.](https://www.witt-software.com/releasenotes/?app=networkradar)

**Comment by guydebros** [comment]
@miccal thanks, do you just have to search for them or is it common among developers to publish something like that?

**Comment by miccal** [comment]
The [`appcast` documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md) explains how to find them.

Since there is an `appcast` you will also need to set the `version` and `sha256` values.

**Comment by ran-dall** [comment]
> @miccal thanks, do you just have to search for them or is it common among developers to publish something like that?

@guydebros We have a `find-appcast` script in the `/developer` directory, but that doesn't always work. [Proxyman](https://proxyman.io/) is another simple tool you can use to intercept where exactly the update feed is. If all else fails, you can a `release notes` feed of some sort.

**Comment by guydebros** [comment]
Thanks for the helpful info! I made the requested changes.

**Pull request merged**
