### PR TITLE
Create review-sherlock.rb

### PR DESCRIPTION
**Pull request by Rbcafe**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You appear to be the author of this software.

* Why do we need to fake the user agent, if you presumably have access to the server and are approving of direct downloads by submitting this?
* Do you not have an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md) we can use?
* What about a versioned download? We really prefer not having unversioned tools.

**Comment by Rbcafe** [comment]
Greetings,

You appear to be the author of this software. :

Yes 

Why do we need to fake the user agent, if you presumably have access to the server and are approving of direct downloads by submitting this : 

- Because my server is behind Clouflare. 
- It was the only solution to make the download works.

Do you not have an appcast we can use? : 

- Actually no.

What about a versioned download? We really prefer not having unversioned tools. : 

- Because it wasn't designed for this version. 
- Maybe for the next update.

Best regards
@Rbcafe

**Comment by vitorgalvao** [comment]
Thank you for the submission, but that being the case, I worry this cask will be more trouble than it’s worth. I’ll refuse it this once under [the notability rule](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> + The Cask is too obscure. Examples:
>   + A self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars).
>   + [Electronic Identification (eID) software](https://github.com/Homebrew/homebrew-cask/issues/59021).

**Comment by Rbcafe** [comment]
Thanks for the information.

Best regards.

@Rbcafe

**Pull request closed without merging**
