### PR TITLE
Add ELECOM Mouse Assistant v5.2.13.000

### PR DESCRIPTION
**Pull request by yyolk**
Add new cask ELECOM Mouse Assistant @ v.5.2.13.000. It configures mouse options for ELECOM mice. It was previously part of homebrew-cask-drivers, but that project is deprecated and this cask was never migrated. The reason for not migrating seemed to be it was missing a `zap` stanza, which is unecessary if there's an uninstall stanza. I recreated this cask formula following the cookbook. I also confirmed the uninstall stanza is configured correctly for this latest version of the package, which happens to be the same as before.

The cask formula from homebrew-cask-drivers which was referenced in part can be viewed here: https://github.com/Homebrew/homebrew-cask-drivers/blob/c6ba38948541587b2b3634fd0acb1c9bd6257e1a/Casks/elecom-mouse-assistant.rb

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [X] `brew audit --cask --new <cask>` worked successfully.
- [X] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @yyolk.

I have changed the token name to `elecom-mouse-util` to follow our [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference) as the `app` bundle inside the `pkg` is called `ELECOM_Mouse_Util.app`

**Review by miccal — APPROVED** [review]

**Comment by bevanjkay** [comment]
Did you try to add a zap stanza, or just assume it isn't necessary? There's likely preference and cache files that can be cleaned up. 

The docs provides some examples for how to create one - https://docs.brew.sh/Cask-Cookbook#stanza-zap

**Review by bevanjkay — CHANGES_REQUESTED** [review]
Confirm there is no case for a `zap` stanza

**Comment by yyolk** [comment]
@bevanjkay 

I ran through the zap creation steps [detailed here](https://docs.brew.sh/Cask-Cookbook#stanza-zap):


prior to a `brew uninstall ...` I ran `nrlquaker/createzap` and it found one item:

```
% brew createzap elecom
zap trash: "/Library/PreferencePanes/ELECOMMousePanel.prefPane"
```

after a `brew uninstall ...` I ran `nrlquaker/createzap` again and it doesn't find anything:

```
% brew createzap elecom
No elecom settings found
```

This would confirm that the `uninstall` stanza is sufficient and the `"/Library/PreferencePanes/ELECOMMousePanel.prefPane"` is covered by https://github.com/Homebrew/homebrew-cask/blob/7a48ff0269b3167ff999fabc438c6ff2364f656d/Casks/e/elecom-mouse-util.rb#L23-L23


I also ran through the manual `zap` stanza creation steps, [detailed in the same spot](https://docs.brew.sh/Cask-Cookbook#stanza-zap), inspecting the output of `sudo find / -iname "*elecom*"`, both prior to `brew uninstall` and after `brew uninstall`.
image


Nothing was found in the "usual paths" that wasn't removed after `brew uninstall ...`, with just the `uninstall` stanza.

As a result I am confident that the `zap` stanza is unnecessary. 
 
* * *

Apologies for not confirming this throughly, my mistake was assuming any `*.pkg` install didn't require a `zap` stanza, based on seeing the one example.

Let me know if I should dive deeper anywhere else.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
