### PR TITLE
updated harvest (2.0.0)

### PR DESCRIPTION
**Pull request by reitermarkus**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by reitermarkus** [comment]
@caskroom/maintainers, this is also working locally for me.

**Comment by adidalal** [comment]
Yep, I can confirm locally

**Comment by jawshooah** [comment]
Strange, I'm getting the same thing as Travis for this one.

<details><summary>Output of `brew cask audit --download`</summary>
```
$ brew cask audit --download https://raw.githubusercontent.com/caskroom/homebrew-cask/474ec936fb1c564eb54299ea574ec861a8cac771/Casks/harvest.rb
==> Downloading https://raw.githubusercontent.com/caskroom/homebrew-cask/474ec936fb1c564eb54299ea574ec861a8cac771/Casks/harvest.rb
######################################################################## 100.0%
==> Downloading https://www.getharvest.com/harvest/mac/Harvest.2.0.0.zip
######################################################################## 100.0%
==> Verifying checksum for Cask harvest
audit for harvest: warning
 - appcast checkpoint mismatch
Expected: 3e11300e8e201435d008737ca6f03a43229b90446d2318e5fe22f2575e4a6bc6
Actual: 9c3d1ecd1f3b13864a293b08d9d946d25422124343523c6a4516faaafa72186b
Error: audit failed for casks: harvest
```
</details>

<details><summary>Body of appcast</summary>
```xml

<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle"  xmlns:dc="http://purl.org/dc/elements/1.1/">
   <channel>
      <title>Harvest for Mac</title>
      <link>https://www.getharvest.com/harvest/mac/appcast.xml</link>
      <description>Most recent changes with links to updates.</description>
      <language>en</language>
      <item>
        <title>Version 0.2.7</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.0.2.7.html</sparkle:releaseNotesLink>
        <pubDate>Tue, 04 Oct 2011 15:24:14 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.0.2.7.zip"
          sparkle:version="0.2.7"
          sparkle:dsaSignature="MC0CFFcKYByVvjS/RDqmue3lO5JbCcGGAhUA6WhrDFUdxhORZse+H4GhMC6QfWA="
          length="2104263"
          type="application/octet-stream" />
      </item>
      <item>
        <title>Version 0.2.6</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.0.2.6.html</sparkle:releaseNotesLink>
        <pubDate>Mon, 26 Sep 2011 21:52:27 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.0.2.6.zip"
          sparkle:version="0.2.6"
          sparkle:dsaSignature="MC4CFQCp+eDR035Vnrcio/rOTK91xqiGDQIVAIB+z2mnR29w7nHwOKTcOELYLGzW"
          length="1976967"
          type="application/octet-stream" />
      </item>
      <item>
        <title>Version 0.2.5</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.0.2.5.html</sparkle:releaseNotesLink>
        <pubDate>Mon, 26 Sep 2011 17:25:46 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.0.2.5.zip"
          sparkle:version="0.2.5"
          sparkle:dsaSignature="MC0CFQC8Yj76WvurhEsk672L8DRpJ16FqgIUGChEGXzuYvOM0foAKZXfQS0njKE="
          length="1977181"
          type="application/octet-stream" />
      </item>
      <item>
        <title>Version 0.2.4</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.0.2.4.html</sparkle:releaseNotesLink>
        <pubDate>Fri, 16 Sep 2011 18:05:25 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.0.2.4.zip"
          sparkle:version="0.2.4"
          sparkle:dsaSignature="MC0CFQCs3feoAxoc1yy6spWZhmDdn7byAgIUacTQo8yr0qHP8zkwPYc7kfvJs24="
          length="2102867"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 0.2.3</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.0.2.3.html</sparkle:releaseNotesLink>
        <pubDate>Thu, 15 Sep 2011 21:04:44 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.0.2.3.zip"
          sparkle:version="0.2.3"
          sparkle:dsaSignature="MC0CFQDOEc9stDxY3fA91CvOM4tGKlpTywIUfTfqMNlRQPKWxlhN5VmOYfqLFoY="
          length="2102126"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 0.2.2</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.0.2.2.html</sparkle:releaseNotesLink>
        <pubDate>Wed, 07 Sep 2011 21:10:20 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.0.2.2.zip"
          sparkle:version="0.2.2"
          sparkle:dsaSignature="MC4CFQCP0IyTeDvjrLmbwKmerSjJ/8eskAIVAO+3Osoa4aywINwGATIO+LBgD2b/"
          length="2097170"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 0.2.1</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.0.2.1.html</sparkle:releaseNotesLink>
        <pubDate>Wed, 07 Sep 2011 19:24:54 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.0.2.1.zip"
          sparkle:version="0.2.1"
          sparkle:dsaSignature="MC4CFQDqvxlwtYPOTN3SYmfmdtDF0ommJwIVAKw/vmSt8FWX5adrT32ZpAVVQxp1"
          length="2097090"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 0.2</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.0.2.html</sparkle:releaseNotesLink>
        <pubDate>Wed, 07 Sep 2011 15:05:13 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.0.2.zip"
          sparkle:version="0.2"
          sparkle:dsaSignature="MC4CFQCrYUEjn2+s7ikL1TE2LasuWqjB6gIVANfMbeUlLONKQ913APJNRcxzwoO6"
          length="2096782"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 0.3</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.0.3.html</sparkle:releaseNotesLink>
        <pubDate>Wed, 22 Feb 2012 21:36:51 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.0.3.zip"
          sparkle:version="0.3"
          sparkle:dsaSignature="MCwCFBBDRHOLWCWhEm36wdXaBcDBhXnBAhRNFkIm1JwDF6dgWaxQTIeeCk+YfA=="
          length="2006298"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.0</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.1.0.html</sparkle:releaseNotesLink>
        <pubDate>Mon, 27 Feb 2012 23:47:13 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.1.0.zip"
          sparkle:version="1.0"
          sparkle:dsaSignature="MCwCFEnJizUc6RAxCKp890BZVV4g9UiIAhQHgsLgzYSENdPrwlpaAiHcydqJVg=="
          length="2005476"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.0.1</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.1.0.1.html</sparkle:releaseNotesLink>
        <pubDate>Tue, 28 Feb 2012 16:45:26 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.1.0.1.zip"
          sparkle:version="1.0.1"
          sparkle:dsaSignature="MCwCFCF4Sc8IPsod6OzkK+vnGkjAdZLkAhR2aEvBJNGig+DsMZX50ETdwhyDsg=="
          length="2134955"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.0.2</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.1.0.2.html</sparkle:releaseNotesLink>
        <pubDate>Mon, 05 Mar 2012 23:23:10 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.1.0.2.zip"
          sparkle:version="1.0.2"
          sparkle:dsaSignature="MC4CFQCpMVLCz6ZRd9fHVRfetTEDT5dmTQIVAOOF+eBnIDTCMcy6WkoO04LEPCmA"
          length="2145554"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.0.3</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.1.0.3.html</sparkle:releaseNotesLink>
        <pubDate>Thu, 08 Mar 2012 00:31:14 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.1.0.3.zip"
          sparkle:version="1.0.3"
          sparkle:dsaSignature="MC4CFQCSTB/2vOtqvaN1wXXTNARgy/bqAgIVAPqMJqWE0qfHvsUdRe25DiOSlDbS"
          length="2155639"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.0.4</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.1.0.4.html</sparkle:releaseNotesLink>
        <pubDate>Wed, 14 Mar 2012 20:40:24 -0700</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.1.0.4.zip"
          sparkle:version="1.0.4"
          sparkle:dsaSignature="MC4CFQDPkHMKRT85Pd3uoEHfmgNqWR3QkwIVAPKQPtmdmw98606dXfH7rVwMLnNH"
          length="2158112"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.0.6</title>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.1.0.6.html</sparkle:releaseNotesLink>
        <pubDate>Tue, 17 Apr 2012 19:56:12 +0000</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.1.0.6.zip"
          sparkle:version="1.0.6"
          sparkle:dsaSignature="MC0CFQDSVp4vN0r7N1omXXq+TK4dnn//ewIUKEJeH6UAesHZ4qLGE5a0v9aSXPg="
          length="2162334"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.0.8</title>
        <sparkle:minimumSystemVersion>10.7.0</sparkle:minimumSystemVersion>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.1.0.8.html</sparkle:releaseNotesLink>
        <pubDate>Fri, 07 Jun 2013 19:22:47 +0000</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.1.0.8.zip"
          sparkle:version="9"
          sparkle:shortVersionString="1.0.8"
          sparkle:dsaSignature="MCwCFHNRSqobqLbed0GM80zMkZBQQJ3VAhRbjJwgQgj7LfEl8hmAx+h4Ml1aXw=="
          length="5524702"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.0.9</title>
        <sparkle:minimumSystemVersion>10.7.0</sparkle:minimumSystemVersion>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.1.0.9.html</sparkle:releaseNotesLink>
        <pubDate>Wed, 19 Jun 2013 23:55:26 +0000</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.1.0.9.zip"
          sparkle:version="10"
          sparkle:shortVersionString="1.0.9"
          sparkle:dsaSignature="MC0CFQC4miL9NCxINbhqG7vtWkoUOESU/AIUfOVE36RmVe8aLFRIizPDp2jcavc="
          length="5529413"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.1</title>
        <sparkle:minimumSystemVersion>10.7.0</sparkle:minimumSystemVersion>
        <sparkle:releaseNotesLink>https://www.getharvest.com/harvest/mac/release_notes.1.1.html</sparkle:releaseNotesLink>
        <pubDate>Fri, 12 Jul 2013 17:26:43 +0000</pubDate>
        <enclosure url="https://www.getharvest.com/harvest/mac/Harvest.1.1.zip"
          sparkle:version="11"
          sparkle:shortVersionString="1.1"
          sparkle:dsaSignature="MCwCFCgWFdmE2A1PS8JaxCSuWrKRdo5ZAhR954A3un5BtrKBEV6ndJpIbuBIYA=="
          length="6641490"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.2</title>
        <sparkle:minimumSystemVersion>10.8.0</sparkle:minimumSystemVersion>
        <sparkle:releaseNotesLink>https://www.getharvest.com//harvest/mac/release_notes.1.2.html</sparkle:releaseNotesLink>
        <pubDate>Fri, 22 Nov 2013 19:54:46 +0000</pubDate>
        <enclosure url="https://www.getharvest.com//harvest/mac/Harvest.1.2.zip"
          sparkle:version="18"
          sparkle:shortVersionString="1.2"
          sparkle:dsaSignature="MCwCFH49+/bEm0Gg5IRLFy4hkNSnyHNSAhRutFLx2xyHP7FS4DPgNUrQrBV/VA=="
          length="3296469"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.3.1</title>
        <sparkle:minimumSystemVersion>10.8.0</sparkle:minimumSystemVersion>
        <sparkle:releaseNotesLink>https://www.getharvest.com//harvest/mac/release_notes.1.3.1.html</sparkle:releaseNotesLink>
        <pubDate>Wed, 11 Dec 2013 17:50:37 +0000</pubDate>
        <enclosure url="https://www.getharvest.com//harvest/mac/Harvest.1.3.1.zip"
          sparkle:version="20"
          sparkle:shortVersionString="1.3.1"
          sparkle:dsaSignature="MC0CFHbeXvO/gidinxDvQD+emmk6qrBOAhUAm7wnWpeWsWCCFM7/btZ/edDzU+g="
          length="3345913"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.4.0</title>
        <sparkle:minimumSystemVersion>10.9</sparkle:minimumSystemVersion>
        <sparkle:releaseNotesLink>https://www.getharvest.com//harvest/mac/release_notes.1.4.0.html</sparkle:releaseNotesLink>
        <pubDate>Thu, 26 Feb 2015 19:47:57 +0000</pubDate>
        <enclosure url="https://www.getharvest.com//harvest/mac/Harvest.1.4.0.zip"
          sparkle:version="33"
          sparkle:shortVersionString="1.4.0"
          sparkle:dsaSignature="MC0CFQChtHd+BmMD8CKAxygBYJqhY0xtogIUTZ7286raNbyV5ZMybGqDhdvCPvs="
          length="4242195"
          type="application/octet-stream" />
      </item>


      <item>
        <title>Version 1.4.1</title>
        <sparkle:minimumSystemVersion>10.9</sparkle:minimumSystemVersion>
        <sparkle:releaseNotesLink>https://www.getharvest.com//harvest/mac/release_notes.1.4.1.html</sparkle:releaseNotesLink>
        <pubDate>Mon, 23 Mar 2015 00:00:00 +0000</pubDate>
        <enclosure url="https://www.getharvest.com//harvest/mac/Harvest.1.4.1.zip"
          sparkle:version="36"
          sparkle:shortVersionString="1.4.1"
          sparkle:dsaSignature="MC4CFQDGQY+iXH2ThHhU+OYq6AFYNSPbzQIVANLPUsDRGapzshxkjy3KDx9jgYQw"
          length="4309481"
          type="application/octet-stream" />
      </item>


      <item>
        <title>Version 1.4.2</title>
        <sparkle:minimumSystemVersion>10.9</sparkle:minimumSystemVersion>
        <sparkle:releaseNotesLink>https://www.getharvest.com//harvest/mac/release_notes.1.4.2.html</sparkle:releaseNotesLink>
        <pubDate>Mon, 27 Apr 2015 00:00:00 +0000</pubDate>
        <enclosure url="https://www.getharvest.com//harvest/mac/Harvest.1.4.2.zip"
          sparkle:version="40"
          sparkle:shortVersionString="1.4.2"
          sparkle:dsaSignature="MCwCFCAoX2wzFkNmSWNqxTdVpN2O/C2kAhQkhmcDGfBDZXjna2Ed+vI1+vkhNg=="
          length="4366401"
          type="application/octet-stream" />
      </item>


      <item>
        <title>Version 1.4.4</title>
        <sparkle:minimumSystemVersion>10.9</sparkle:minimumSystemVersion>
        <sparkle:releaseNotesLink>https://www.getharvest.com//harvest/mac/release_notes.1.4.4.html</sparkle:releaseNotesLink>
        <pubDate>Mon, 24 Aug 2015 13:53:28 +0000</pubDate>
        <enclosure url="https://www.getharvest.com//harvest/mac/Harvest.1.4.4.zip"
          sparkle:version="51"
          sparkle:shortVersionString="1.4.4"
          sparkle:dsaSignature="MC4CFQC8Pa11CsKONFCWWWf/9NQR+xXH2AIVAMOKTfzFAhc30iWGOQlJaytcQxXp"
          length="4208523"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.5.0</title>
        <sparkle:minimumSystemVersion>10.9</sparkle:minimumSystemVersion>
        <sparkle:releaseNotesLink>https://www.getharvest.com//harvest/mac/release_notes.1.5.0.html</sparkle:releaseNotesLink>
        <pubDate>Thu, 14 Jan 2016 19:23:04 +0000</pubDate>
        <enclosure url="https://www.getharvest.com//harvest/mac/Harvest.1.5.0.zip"
          sparkle:version="65"
          sparkle:shortVersionString="1.5.0"
          sparkle:dsaSignature="MCwCFEOBi4RqaaAlsRLqCxUKpFX4l6TEAhQR4dtlaCXzQorCU2B+HYs9/UPkTQ=="
          length="5182456"
          type="application/octet-stream" />
      </item>

      <item>
        <title>Version 1.5.1</title>
        <sparkle:minimumSystemVersion>10.9</sparkle:minimumSystemVersion>
        <sparkle:releaseNotesLink>https://www.getharvest.com//harvest/mac/release_notes.1.5.1.html</sparkle:releaseNotesLink>
        <pubDate>Tue, 23 Feb 2016 19:40:50 +0000</pubDate>
        <enclosure url="https://www.getharvest.com//harvest/mac/Harvest.1.5.1.zip"
          sparkle:version="67"
          sparkle:shortVersionString="1.5.1"
          sparkle:dsaSignature="MCwCFCswP7YSqK1scFabUAmab7fxixJqAhQt/RUjLKaTaqDvJSo6rMC0PhKEJQ=="
          length="5185874"
          type="application/octet-stream" />
      </item>
  </channel>
</rss>
```
</details>

@reitermarkus @adidalal The most recent version listed in the appcast I'm getting is `1.5.1`, so maybe you're getting an updated version somehow.

**Comment by adidalal** [comment]
The download site gives me v2.0.0
I can sniff the new appcast URL this weekend

**Comment by vitorgalvao** [comment]
Also getting the same as @reitermarkus (and version `2.0.0`). Merging as is. Seems like some issue with caching, depending on location/servers.

**Pull request merged**
