### PR TITLE
Update qq to 6.2.0

### PR DESCRIPTION
**Pull request by icpz**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by lcdtyph** [comment]
QQ has replaced the dmg file without changing the version...

**Comment by vitorgalvao** [comment]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by lcdtyph** [comment]
Sorry.. but Tencent will not reply to this change, because I'm nobody... And the app isn't codesigned.
I think it's better to wait for the next release now...

**Comment by athrunsun** [comment]
@lcdtyph Does that mean we will keep getting sha256 mismatch until then?
```
$ brew cask install qq
==> Satisfying dependencies
==> Downloading https://dldir1.qq.com/qqfile/QQforMac/QQ_V6.2.0.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask qq
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'qq' does not match.

Expected: 1d38bd11fe8723adc7b3dd0e312c9d7dea8a63f04c427fc21a8671df4be8a533
Actual:   057a0508331d831ee6670e50cf3775abffe2c30b57eea3c4a812b784baebecee
File:     /Users/bruce.sun/Library/Caches/Homebrew/Cask/qq--6.2.0.dmg
```

**Comment by commitay** [comment]
The app is codesigned.

```
Executable=/Volumes/QQ/QQ.app/Contents/MacOS/QQ
Identifier=com.tencent.qq
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=235150 flags=0x0(none) hashes=7341+5 location=embedded
Signature size=4656
Authority=Developer ID Application: Tencent Technology (Shanghai) Co., Ltd (FN2V63AD2J)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Signed Time=18 Dec 2017 at 19:40:26
Info.plist entries=30
TeamIdentifier=FN2V63AD2J
Sealed Resources version=2 rules=13 files=3480
Internal requirements count=1 size=208

/Volumes/QQ/QQ.app: valid on disk
/Volumes/QQ/QQ.app: satisfies its Designated Requirement
```

**Review by commitay — APPROVED** [review]

**Comment by lcdtyph** [comment]
My bad... I've only checked the ```.dmg``` file instead of ```.app``` file, so I thought it's not codesigned...

**Pull request merged**
