### PR TITLE
Update a-better-finder-rename to 10.31

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
```
Expected: b4135907cb54514add2fd95993918d9d51cc0f937984fb09dc4972fa89fca3e4
Actual:   6d1a29d63a3275664cedcef13b8c8c046bd89d94ba90302fb1c5761d57e21fc1
File:     /Users/travis/Library/Caches/Homebrew/Cask/a-better-finder-rename--10.31.dmg
```

since they seem to be doing updates-in-place, I don't know if you guys want to chill on this for a day or two and then rerun the shasum to see if they stopped?

**Comment by brianmorton** [comment]
I don't think this should have been merged, and especially not right away. It is now definitely broken:
```
$ brew cask audit --download a-better-finder-rename
==> Downloading http://www.publicspace.net/download/ABFRX10.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask a-better-finder-rename
==> Note: running "brew update" may fix sha256 checksum errors
audit for a-better-finder-rename: failed
 - download not possible: Checksum for Cask 'a-better-finder-rename' does not match.

Expected: b4135907cb54514add2fd95993918d9d51cc0f937984fb09dc4972fa89fca3e4
Actual:   6d1a29d63a3275664cedcef13b8c8c046bd89d94ba90302fb1c5761d57e21fc1
File:     /Users/brian/Library/Caches/Homebrew/Cask/a-better-finder-rename--10.31.dmg

To retry an incomplete download, remove the file above.
Error: audit failed for casks: a-better-finder-rename
```

I was asking if we should WAIT on merging the PR because it didn't pass the checksum on travis, indicating the developer has done an update-in-place since I submitted the PR, so maybe we should hang on for a day or two to see if the updates-in-place stop.

cc @vitorgalvao @commitay

**Comment by victorpopkov** [comment]
For maintainers, in case of the further investigation.

The latest version on the homepage was:

http://d3k6s0oeufjjjn.cloudfront.net/download0_773ef2e86b2d1/ABFRX10.dmg (v10.31)
`b4135907cb54514add2fd95993918d9d51cc0f937984fb09dc4972fa89fca3e4`

The one that is pointed in the appcast:

http://d3k6s0oeufjjjn.cloudfront.net/download0_773ef2e86b2d1/signedABFRX10.zip (v10.31)
`ca387dd1c1ee8e10f34c6ba013729e54d15289f94d6a83eb56b7b5dfedf8cf1f`

If you unpack both `.dmg` and `.zip` and compare both `.app` directories recursively file by file you can find that those are completely identical. Of course, that is not a concrete evidence and doesn't prove much. But at least this can give some extra tiny bit of information that might be useful.

**Comment by vitorgalvao** [comment]
Given the situation, if you want to submit the correction, @brianmorton, we can merge it without going through the procedure.

**Comment by brianmorton** [comment]
@vitorgalvao I looked into it, but everything seems to be in order now?

```
$ rm /Users/brian/Library/Caches/Homebrew/Cask/a-better-finder-rename--10.31.dmg

$ brew cask audit --download a-better-finder-rename
==> Downloading http://www.publicspace.net/download/ABFRX10.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask a-better-finder-rename
audit for a-better-finder-rename: passed
```

**Pull request merged**
