### PR TITLE
add qlImageSize.qlgenerator v1.6.0

### PR DESCRIPTION
**Pull request by L1cardo**
After making all changes to the cask:

- [yes ] `brew cask audit --download {{cask_file}}` is error-free.
- [yes ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [yes ] The commit message includes the cask’s name and version.
- [yes ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [yes ] Named the cask according to the [token reference].
- [yes ] `brew cask install {{cask_file}}` worked successfully.
- [yes ] `brew cask uninstall {{cask_file}}` worked successfully.
- [yes ] Checked there are no [open pull requests] for the same cask.
- [yes ] Checked the cask was not [already refused].
- [yes ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by L1cardo** [comment]
we have discussed this before #57212 and I have made some fixes, please have a look

**Comment by vitorgalvao** [comment]
This is *better*, but it’s still not above 50 stars (and there was no interest in accepting it below that), and still not named as a fork.

**Comment by L1cardo** [comment]
I am not a developer and know little about coding. I just want it convenient for others to use this plugin.
This plugin once was in the cask, I don't know why the origin developer removed it . Now the origin developer has closed all issues and don't allow people to discusse about it . 
Sad about you having no interest.
Sorry to bother, I will not pull a request anymore. I will not working on it anymore.

**Comment by vitorgalvao** [comment]
> I will not working on it anymore.

That is, naturally, your choice. But I’d recommend you do.

Homebrew isn’t the only way to get software. Why not allow your users to get it manually, like they can now? If enough trust you (and star the repo), we can include it.

**Pull request closed without merging**
