### PR TITLE
Updated Alcatraz to 1.1.15

### PR DESCRIPTION
**Pull request by Keloran**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please [squash your commits](http://davidwalsh.name/squash-commits-git).

**Comment by adityadalal924** [comment]
Thank you for the contribution. It needed some fixes, so they were made in a356d8f403a6bf0986c0709b976757b818f9a7e2. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by Keloran** [comment]
what changes did you make, so that from now on they can be done before submit

thanks

**Comment by vitorgalvao** [comment]
He squashed the commits.

**Comment by adityadalal924** [comment]
@Keloran `git rebase -i origin/master` and squash commits is all I did

**Pull request closed without merging**
