### PR TITLE
Fallback for audacity URL timeout.

### PR DESCRIPTION
**Pull request by reitermarkus**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

---

This of course only silences the audit error, but doesn't actually fix the URL. FossHub seems to be using JavaScript to generate the actual download link now.

### CODE REVIEW

**Comment by jawshooah** [comment]
Looks like the new behavior is part of their remediation after [this recent hack](http://www.theregister.co.uk/2016/08/04/classicshell_audicity_infection/).

**Comment by reitermarkus** [comment]
@jawshooah, just added an overkill solution to scrape the url. 😄

**Comment by vitorgalvao** [comment]
That is *way* overkill. I’d rather just remove audacity or revert to the old `oldfoss` behaviour than require `phantomjs`.

Even excluding we’re adding such overhead for a single cask, it’s not completely installing `phantomjs` will be a sane choice down the line. Recently there was a long period of time where we couldn’t install `phantomjs` on El Capitan due to a problem with the new version that took a good while to fix.

If an app is that difficult to get, then let it not be gettable. I vote to remove the cask altogether, if we can’t get it in a sane manner.

**Comment by reitermarkus** [comment]
> If an app is that difficult to get, then let it not be gettable. I vote to remove the cask altogether, if we can’t get it in a sane manner.

I agree. This “solution” was more of an exercise than anything else.

**Comment by rgoldberg** [comment]
More importantly, `brew cask audit` should not exit when one cask fails audit.  It should output error, then continue to audit the subsequent casks.

**Comment by jawshooah** [comment]
@rgoldberg The problem is that this was an unexpected and uncaught exception, not a failed audit. Normally we do exactly what you suggest and report errors and warnings after all casks have been audited.

**Comment by rgoldberg** [comment]
So, just catch all exceptions in the cask audit loop so this won't happen again.

**Comment by jawshooah** [comment]
Yup, cooking up a PR to do just that.

Out of curiosity, why are you running `brew cask audit` on all casks? There's not much point unless you're a maintainer.

**Comment by jawshooah** [comment]
Closing, as the existing `url` block seems to be working now. No need to remove the cask unless it starts acting up again.

**Pull request closed without merging**
