### PR TITLE
Update bitwarden to use the universal binary on Apple silicon

### PR DESCRIPTION
**Pull request by danielkean**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
If it's universal, why not use it on Intel?

**Comment by danielkean** [comment]
Yeah I wasn't sure whether it would be better to keep the smaller .zip file on the intel architecture whilst it exists, or to switch both to use the universal. Do you think it would be better to change it for both?

**Review by carlocab — DISMISSED** [review]

**Comment by SMillerDev** [comment]
I think if it's a universal app it'll be easier to rely on that.

**Comment by danielkean** [comment]
@SMillerDev Hmm strange, when changed to use the universal binary for both architectures, it fails the tests. Any ideas?

**Comment by neutric** [comment]
@danielkean "Error: It seems the App source '/usr/local/Caskroom/bitwarden/1.28.3/Bitwarden.app' is not there." You have to replace the app stanza in L18 with a [pkg stanza](https://docs.brew.sh/Cask-Cookbook#stanza-pkg) as you are no longer just unpacking a dmg.

**Comment by danielkean** [comment]
@neutric Thanks for the help, I changed it to a pkg stanza as well as the uninstall to pkgutil, so the tests are now passing. It's my first time contributing to homebrew-cask so I would have been surprised if it went smoothly the first time hahaha.

**Comment by miccal** [comment]
Thank you @danielkean.

**Comment by danielkean** [comment]
@miccal Hi there, once installed, there seems to be an issue when running the application as can be seen in the first screenshot. Do you think this is something "pkg allow_untrusted:" would fix? I'm not sure why the tests didn't catch this problem.

I also wanted to make sure that the install location seems correct to you (It does from what I can see as it appears in the Applications folder), as I've never seen it say "Installing at base path /" , which can be seen in the second screenshot. Unless that's something specific to pkg files?

image


image

**Comment by danielkean** [comment]
@miccal I've just submitted the issue to the Bitwarden/Desktop repo which can be found here:
https://github.com/bitwarden/desktop/issues/1090

**Pull request merged**
