### PR TITLE
Add ChatWork Latest

### PR DESCRIPTION
**Pull request by lohn**

### CODE REVIEW

**Comment by adidalal** [comment]
How did you make a PR, such that the template doesn't show up?

**Comment by m8x** [comment]
I used `hub pull-request` command thus the template did not show up.

Following is the checklist:

- [x] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same change.
- [x] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Commit message includes cask’s name.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

**Comment by adidalal** [comment]
Ah, good to know, and thanks for editing it in!
@vitorgalvao This explains it

**Comment by adidalal** [comment]
I'll poke around to see if I can find and appcast, and if not, LGTM

**Comment by adidalal** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 4a10bc5d491c114eec544189fc89c249ca2a73c9. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
