### PR TITLE
Delete x48.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
https://github.com/Homebrew/homebrew-cask/issues/86110. Tried it on a Mojave VM and was unable to run it.

```
x48
30 days: 3 (#4274)
90 days: 19 (#3536)
365 days: 86 (#3306)
Age: 2458 days (added 2013, October 24)
```

### CODE REVIEW

**Comment by core-code** [comment]
do *any* apps requiring X11 / XQuartz run on 10.15?

**Comment by vitorgalvao** [comment]
> do _any_ apps requiring X11 / XQuartz run on 10.15?

No idea, but I was also thinking it might be a good idea to review/remove those.

**Comment by steakknife** [comment]
There's tons of ye olden apps that use xquartz/x11. Dia, povray, x48, mplayer, dosbox-x and a bunch more.

Going around removing apps _you_ don't like because they're "old" isn't very community-oriented or helpful if they're just sitting there and work. It just eliminates value and convenience, defeating the whole point of brew. 

xquartz/x11 references (not including third-party)
```
homebrew-cask/doc/cask_language_reference/stanzas/depends_on.md
homebrew-cask/Casks/wine-stable.rb
homebrew-cask/Casks/brl-cad-mged.rb
homebrew-cask/Casks/ncar-ncl.rb
homebrew-cask/Casks/dia.rb
homebrew-cask/Casks/ealeksandrov-cd-to.rb
homebrew-cask/Casks/xquartz.rb
homebrew-cask/Casks/x48.rb
homebrew-cask/Casks/x2goclient.rb
homebrew-cask/Casks/gtkwave.rb
homebrew-core/Formula/pangomm.rb
homebrew-core/Formula/console_bridge.rb
homebrew-core/Formula/povray.rb
homebrew-core/Formula/ldc.rb
homebrew-core/Formula/pari.rb
homebrew-core/Formula/pacvim.rb
homebrew-core/Formula/percona-xtrabackup.rb
homebrew-core/Formula/mapnik.rb
homebrew-core/Formula/wordnet.rb
homebrew-core/Formula/stone-soup.rb
homebrew-core/Formula/dynare.rb
homebrew-core/Formula/znc.rb
homebrew-core/Formula/grace.rb
homebrew-core/Formula/libcaca.rb
homebrew-core/Formula/libcdr.rb
homebrew-core/Formula/id3lib.rb
homebrew-core/Formula/xdotool.rb
homebrew-core/Formula/morse.rb
homebrew-core/Formula/supertux.rb
homebrew-core/Formula/btfs.rb
homebrew-core/Formula/spdlog.rb
homebrew-core/Formula/binaryen.rb
homebrew-core/Formula/jnethack.rb
homebrew-core/Formula/corectl.rb
homebrew-core/Formula/libpointing.rb
homebrew-core/Formula/atkmm.rb
homebrew-core/Formula/gdcm.rb
homebrew-core/Formula/gstreamermm.rb
homebrew-core/Formula/simple-mtpfs.rb
homebrew-core/Formula/visp.rb
homebrew-core/Formula/robot-framework.rb
homebrew-core/Formula/nghttp2.rb
homebrew-core/Formula/mplayer.rb
homebrew-core/Formula/ledger.rb
homebrew-core/Formula/wmctrl.rb
homebrew-core/Formula/spatialindex.rb
homebrew-core/Formula/zbackup.rb
homebrew-core/Formula/opencv.rb
homebrew-core/Formula/log4cplus.rb
homebrew-core/Formula/jsonnet.rb
homebrew-core/Formula/opensaml.rb
homebrew-core/Formula/re2.rb
homebrew-core/Formula/quill.rb
homebrew-core/Formula/zxcc.rb
homebrew-core/Formula/vowpal-wabbit.rb
homebrew-core/Formula/caffe.rb
homebrew-core/Formula/protobuf-c.rb
homebrew-core/Formula/dspdfviewer.rb
homebrew-core/Formula/rdesktop.rb
homebrew-core/Formula/xlispstat.rb
homebrew-core/Formula/xsd.rb
homebrew-core/Formula/xml-tooling-c.rb
homebrew-core/Formula/gtksourceviewmm3.rb
homebrew-core/Formula/libsigc++.rb
homebrew-core/Formula/shogun.rb
homebrew-core/Formula/hfstospell.rb
homebrew-core/Formula/poppler.rb
homebrew-core/Formula/field3d.rb
homebrew-core/Formula/aria2.rb
homebrew-core/Formula/urdfdom_headers.rb
homebrew-core/Formula/v8@3.15.rb
homebrew-core/Formula/dwm.rb
homebrew-core/Formula/thrift@0.9.rb
homebrew-core/Formula/mkvtoolnix.rb
homebrew-core/Formula/startup-notification.rb
homebrew-core/Formula/libphonenumber.rb
homebrew-core/Formula/imake.rb
homebrew-core/Formula/prefixsuffix.rb
homebrew-core/Formula/ncmpcpp.rb
homebrew-core/Formula/gobby.rb
homebrew-core/Formula/osquery.rb
homebrew-core/Formula/rtptools.rb
homebrew-core/Formula/xpa.rb
homebrew-core/Formula/cppcheck.rb
homebrew-core/Formula/rxvt-unicode.rb
homebrew-core/Formula/gabedit.rb
homebrew-core/Formula/tesseract.rb
homebrew-core/Formula/tgif.rb
homebrew-core/Formula/opencv@2.rb
homebrew-core/Formula/gdk-pixbuf.rb
homebrew-core/Formula/nedit.rb
homebrew-core/Formula/pdfgrep.rb
homebrew-core/Formula/zmqpp.rb
homebrew-core/Formula/mosh.rb
homebrew-core/Formula/open-mesh.rb
homebrew-core/Formula/libsass.rb
homebrew-core/Formula/liblas.rb
homebrew-core/Formula/xqilla.rb
homebrew-core/Formula/ncview.rb
homebrew-core/Formula/gsmartcontrol.rb
homebrew-core/Formula/opencv@3.rb
homebrew-core/Formula/encfs.rb
homebrew-core/Formula/fizmo.rb
homebrew-core/Formula/libspnav.rb
homebrew-core/Formula/html2text.rb
homebrew-core/Formula/efl.rb
homebrew-core/Formula/fceux.rb
homebrew-core/Formula/nzbget.rb
homebrew-core/Formula/x11vnc.rb
homebrew-core/Formula/boost-mpi.rb
homebrew-core/Formula/amqp-cpp.rb
homebrew-core/Formula/xalan-c.rb
homebrew-core/Formula/ocp.rb
homebrew-core/Formula/diff-pdf.rb
homebrew-core/Formula/mupdf-tools.rb
homebrew-core/Formula/emscripten.rb
homebrew-core/Formula/points2grid.rb
homebrew-core/Formula/gnuplot.rb
homebrew-core/Formula/fswatch.rb
homebrew-core/Formula/libsigc++@2.rb
homebrew-core/Formula/duc.rb
homebrew-core/Formula/gtk+.rb
homebrew-core/Formula/tmux-mem-cpu-load.rb
homebrew-core/Formula/openmotif.rb
homebrew-core/Formula/mapcrafter.rb
homebrew-core/Formula/ctl.rb
homebrew-core/Formula/gl2ps.rb
homebrew-core/Formula/vifm.rb
homebrew-core/Formula/pagmo.rb
homebrew-core/Formula/zorba.rb
homebrew-core/Formula/gtk+3.rb
homebrew-core/Formula/libxkbcommon.rb
homebrew-core/Formula/gpsbabel.rb
homebrew-core/Formula/mapserver.rb
homebrew-core/Formula/angband.rb
homebrew-core/Formula/quasi88.rb
homebrew-core/Formula/trafficserver.rb
homebrew-core/Formula/fastbit.rb
homebrew-core/Formula/libcec.rb
homebrew-core/Formula/widelands.rb
homebrew-core/Formula/sng.rb
homebrew-core/Formula/freerdp.rb
homebrew-core/Formula/asio.rb
homebrew-core/Formula/jigdo.rb
homebrew-core/Formula/pulseaudio.rb
homebrew-core/Formula/hyperkit.rb
homebrew-core/Formula/lesstif.rb
homebrew-core/Formula/openclonk.rb
homebrew-core/Formula/botan.rb
homebrew-core/Formula/vc4asm.rb
homebrew-core/Formula/djvulibre.rb
homebrew-core/Formula/php@7.3.rb
homebrew-core/Formula/cairomm.rb
homebrew-core/Formula/arm-linux-gnueabihf-binutils.rb
homebrew-core/Formula/metashell.rb
homebrew-core/Formula/pdf2image.rb
homebrew-core/Formula/protobuf@3.6.rb
homebrew-core/Formula/cppcms.rb
homebrew-core/Formula/pgplot.rb
homebrew-core/Formula/libqalculate.rb
homebrew-core/Formula/libxml++.rb
homebrew-core/Formula/gtkmm3.rb
homebrew-core/Formula/ponyc.rb
homebrew-core/Formula/glbinding.rb
homebrew-core/Formula/fox.rb
homebrew-core/Formula/thrift.rb
homebrew-core/Formula/open-scene-graph.rb
homebrew-core/Formula/ddd.rb
homebrew-core/Formula/xclip.rb
homebrew-core/Formula/xml-security-c.rb
homebrew-core/Formula/globjects.rb
homebrew-core/Formula/gecode.rb
homebrew-core/Formula/gbdfed.rb
homebrew-core/Formula/mesos.rb
homebrew-core/Formula/ibex.rb
homebrew-core/Formula/protobuf-swift.rb
homebrew-core/Formula/dmenu.rb
homebrew-core/Formula/harbour.rb
homebrew-core/Formula/rawtoaces.rb
homebrew-core/Formula/libglademm.rb
homebrew-core/Formula/xerces-c.rb
homebrew-core/Formula/chezscheme.rb
homebrew-core/Formula/rocksdb.rb
homebrew-core/Formula/ht.rb
homebrew-core/Formula/geomview.rb
homebrew-core/Formula/curlpp.rb
homebrew-core/Formula/php@7.2.rb
homebrew-core/Formula/pioneer.rb
homebrew-core/Formula/imlib2.rb
homebrew-core/Formula/mesalib-glw.rb
homebrew-core/Formula/pdnsrec.rb
homebrew-core/Formula/blahtexml.rb
homebrew-core/Formula/protobuf@3.7.rb
homebrew-core/Formula/enigma.rb
homebrew-core/Formula/mupdf.rb
homebrew-core/Formula/sxiv.rb
homebrew-core/Formula/qjackctl.rb
homebrew-core/Formula/shibboleth-sp.rb
homebrew-core/Formula/dbxml.rb
homebrew-core/Formula/apache-arrow.rb
homebrew-core/Formula/protobuf.rb
homebrew-core/Formula/guichan.rb
homebrew-core/Formula/tiger-vnc.rb
homebrew-core/Formula/libgnomecanvasmm.rb
homebrew-core/Formula/glibmm.rb
homebrew-core/Formula/google-benchmark.rb
homebrew-core/Formula/libxml++3.rb
homebrew-core/Formula/qhull.rb
homebrew-core/Formula/gtkmm.rb
homebrew-core/Formula/bsdmake.rb
homebrew-core/Formula/termshark.rb
homebrew-core/Formula/gtksourceviewmm.rb
homebrew-core/Formula/feh.rb
homebrew-core/Formula/cxxopts.rb
homebrew-core/Formula/opencc.rb
homebrew-core/Formula/osm-pbf.rb
homebrew-core/Formula/mono-libgdiplus.rb
homebrew-core/Formula/curlftpfs.rb
homebrew-core/Formula/dosbox-x.rb
homebrew-core/Formula/pdftoipe.rb
homebrew-core/Formula/dartsim.rb
homebrew-core/Formula/open-mpi.rb
homebrew-core/Formula/freeglut.rb
homebrew-core/Formula/fcl.rb
homebrew-core/Formula/gjs.rb
homebrew-core/Formula/dar.rb
homebrew-core/Formula/gpsim.rb
homebrew-core/Formula/ompl.rb
homebrew-core/Formula/gpac.rb
homebrew-core/Formula/pstoedit.rb
homebrew-core/Formula/cgoban.rb
homebrew-core/Formula/clutter.rb
homebrew-core/Formula/bde.rb
homebrew-core/Formula/dlib.rb
homebrew-core/Formula/fmsx.rb
homebrew-core/Formula/synfig.rb
homebrew-core/Formula/go-bindata.rb
homebrew-core/Formula/mit-scheme.rb
homebrew-core/Formula/urdfdom.rb
homebrew-core/Formula/tectonic.rb
homebrew-core/Formula/xshogi.rb
```

**Comment by steakknife** [comment]
> #86110. Tried it on a Mojave VM and was unable to run it.
> 
> ```
> x48
> 30 days: 3 (#4274)
> 90 days: 19 (#3536)
> 365 days: 86 (#3306)
> Age: 2458 days (added 2013, October 24)
> ```

And I fixed it in the same issue. It works just fine with a simple fix.

image

**Comment by ran-dall** [comment]
@steakknife As much as I (and I'm sure everyone on HBC) appreciates your point-of-view, I think you shouldn't base your opinions on erroneous assumptions.

**Comment by steakknife** [comment]
What facts are you talking about? Popularity != value. If it were, OSes and
compiler would be written in JS and PHP, and deciding MQTT servers and
Synopsys' 3D silicon compiler were useless because "nobody uses them." Also
consider the vast, unknowable number of people who turn analytics off for
privacy reasons. Maybe you were projecting unintentionally?

Also, since we're apparently dispensing with mutual respect and refraining
from unsolicited advice, perhaps consider speaking on behalf of others
comes off as arrogant.

Thanks so much for your expedience, lack of genuine concern, and absolute
lack of humanity.

**Comment by vitorgalvao** [comment]
@steakknife Please watch your tone. No one was disrespectful to you and you’re expected to extend the same courtesy. Comparing removing a piece of software to “lack of genuine concern and absolute lack of humanity” is absurd and hyperbolic at best. The sarcasm also isn’t appreciated. You don’t get the right to insult us with exaggerated and wrong assumptions because you don’t like a decision.

Nobody suggested removing casks we don’t like because they’re old. No one even expressed wether they “liked” the apps or not, and the removal of *a single one* (which is all this is so far) was prompted by it not working and being unpopular.

The number of people who turn off analytics live with the tradeoff. The point of analytics is to make informed decisions; if we’re going to ignore them because some people turn them off, there would be no point in having them.

You did not “fix” the problem. You made a suggestion and reasonably (or so it looked at the time) conceded it might not be appropriate. It was indeed unsuitable, because on the cask side we go to great lengths to not change the installed software.

Your xquartz references do not apply, because the vast majority are formulae are we’re only referring to casks, which are no more than a handful. The “not including third-party” comment is nonsensical, because we have no control over other people’s repos and are not going to remove those. Finally, we can’t trust your list because it caught documentation files, which means it’s inflated.

Again, please moderate your tone or you will be banned. We’re not spending our volunteer time to be the target of false accusations and verbal abuse.

**Comment by vitorgalvao** [comment]
I’ll leave a final note that you don’t need to be disrespectful and get personal to disagree. You *thought* you were being disrespected to; I can confidently say was not the case, having interacted extensively with everyone else on this issue. That doesn’t mean you have to be disrespectful back. Notice how on my post I responded to your points, and despite being assertive haven’t resorted to commenting on your as a person, because that’s neither necessary nor helpful. 

Removing this one for now. If anyone is able to resubmit a working version that does not alter the software (e.g. a new release by upstream), we’ll gladly reconsider and review it.

As for the other relevant xquartz casks from the list above, here are their analytics for reference. No need to touch them now, we can deal with those as it becomes relevant.

```
wine-stable
30 days: 5,754 (#17)
90 days: 22,267 (#45)
365 days: 59,144 (#55)
Age: 1203 days (added 2017, April 02)

brl-cad-mged
30 days: 6 (#2953)
90 days: 20 (#3324)
365 days: 62 (#3850)
Age: 1299 days (added 2016, December 27)

ncar-ncl
30 days: 33 (#1326)
90 days: 94 (#1759)
365 days: 349 (#1809)
Age: 1872 days (added 2015, June 03)

ealeksandrov-cd-to
30 days: 2 (#4265)
90 days: 5 (#5231)
365 days: 35 (#4738)
Age: 1335 days (added 2016, November 21)

x2goclient
30 days: 105 (#663)
90 days: 364 (#966)
365 days: 1,626 (#914)
Age: 2325 days (added 2014, March 07)

gtkwave
30 days: 244 (#376)
90 days: 760 (#709)
365 days: 2,445 (#784)
Age: 1273 days (added 2017, January 22)
```

**Comment by ran-dall** [comment]
@vitorgalvao Don't you just love it when some people get salty for no apparent reason? This is why I still take time out of my busy schedule to play video games.

@steakknife I'm sorry if I offended you, that wasn't my intention. Frankly, my intention was for you to read the docs and figure out what HBC's position is on these types of situations. Fortunately @vitorgalvao was kind enough to take time to explain all that, so it isn't required; but as he said in his messages 'no one was trying to disrespect you', we just respectfully disagree with you from a "fundamentals" stand point.

**Pull request merged**
