### PR TITLE
Update x2goclient from 4.1.2.1 to 4.1.2.2

### PR DESCRIPTION
**Pull request by thorstenk**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by core-code** [comment]
can you try re-starting travis by closing and re-opening the PR? i don't think the travis failure with X11 makes much sense as it didn't occur the last times and the dependency is noted in the caskfile

**Comment by thorstenk** [comment]
Thanks for the hint! I'ltt try that.

**Comment by core-code** [comment]
ok thanks, no idea why it is still failing

@reitermarkus any ideas here?

**Comment by vitorgalvao** [comment]
CIs fail often enough that if *either* GitHub CI or Travis passes (note GitHub separates `style` and `audit` checks), consider it good.

**Pull request merged**
