### PR TITLE
Update horos to 3.1.1

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
@core-code where did you find this, good sir? the website download is behind an email wall, and the appcast (github) still has 3.1.0. I know you sometimes have ways of finding these things that others do not ;)

**Comment by core-code** [comment]
hey brian. actually i submitted a pull request (  #491029 ) to 3.1.0 as this is the newest version thats on their github site (see appcast). it was commitay's idea that 3.1.1 is available, although neither website nor github reference it. sure enough, just filling in the version number using cask-repair yielded a valid download.

**Comment by commitay** [comment]
The download page is public. https://github.com/Homebrew/homebrew-cask/pull/49219

**Comment by brianmorton** [comment]
thanks gents!

**Pull request merged**
