### PR TITLE
Update epic-games to 7.9.2

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by jlaw** [comment]
Please change the URL to `https://download-dynamic.epicgames.com/Builds/UnrealEngineLauncher/Installers/EpicInstaller-#{version}.dmg"`. It is faster.

**Comment by brianmorton** [comment]
@jlaw If you would care to share how you came to know that, I would consider doing it :)

**Comment by jlaw** [comment]
The link to download from official website is download-dynamic.*. I only
investigated because it was taking forever to download. I suspect the
download-dynamic URL finds the closest mirror.

**Comment by vitorgalvao** [comment]
`download-dynamic`, from the download page, is working fine for me and downloads `7.9.2`.

**Review by vitorgalvao — APPROVED** [review]

**Comment by vitorgalvao** [comment]
The website is offering me `7.9.2`.

https://www.epicgames.com/unrealtournament/download

**Comment by brianmorton** [comment]
It seems they have updated the redirects since this PR was opened yesterday, as I can also verify they are serving `7.9.2` from the same link that I used yesterday:
```
$ wget https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncher.dmg
[...]
--2018-05-03 09:38:37--  https://download-dynamic.epicgames.com/Builds/UnrealEngineLauncher/Installers/EpicInstaller-7.9.2.dmg
```

**Pull request merged**
