### PR TITLE
Add Hush.app v1.0

### PR DESCRIPTION
**Pull request by sebdanielsson**
Hush - Block nags to accept cookies and privacy invasive tracking in Safari

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [X] `brew audit --new-cask <cask>` worked successfully.
- [X] `brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

**Comment by SebDanielsson** [comment]
> Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

First time doing this. Did I fix it?

**Comment by bevanjkay** [comment]
@SebDanielsson that looks good for the zap. 

Can you run 'brew style --fix hush` and push a new commit with the style fixed.

**Comment by SebDanielsson** [comment]
> @SebDanielsson that looks good for the zap. 
> 
> Can you run `brew style --fix hush` and push a new commit with the style fixed?

Should be fixed now☺️

**Comment by miccal** [comment]
Thank you @SebDanielsson.

**Pull request merged**
