### PR TITLE
updated hipchat (4.0.5-574)

### PR DESCRIPTION
**Pull request by cliffcotino**

### CODE REVIEW

**Comment by adidalal** [comment]
Thank you for the contribution. It was merged directly as b2423c2253934ffe94001a2033155562646a629c to keep commit history cleaner. Your contribution is still credited to you.

**Comment by adidalal** [comment]
appcast looks dead, do you see any other sources?

**Comment by cliffcotino** [comment]
I don't see any other sources for appcast.
Better to clean up the app cast + checkpoint?

**Comment by vitorgalvao** [comment]
[Previous conversation regarding the appcast](https://github.com/caskroom/homebrew-cask/pull/19153#issuecomment-187980585).

**Comment by cliffcotino** [comment]
Thanks for the info.

**Pull request closed without merging**
