### PR TITLE
1password-cli: generate and link shell completion

### PR DESCRIPTION
**Pull request by rrotter**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by rrotter** [comment]
This won't pass `brew audit --cask --online 1password-cli` because the completion scripts (which are marked as binaries) don't exist until after `preflight` runs.

This does work if I change the completion scripts from `binary` to `artifact`. Would that be an acceptable solution? Looking around the repo it appears that completion scripts are always marked as `binary`.

**Comment by rrotter** [comment]
To be clear, I'm just trying to accomplish the same thing that `generate_completions_from_executable` does in a Formula, but that doesn't appear to be available in Cask.

**Comment by bevanjkay** [comment]
Thank you for your contribution @rrotter 
There is no real precedent for this kind of addition in `homebrew-cask`, we would generally only include completions if they are pre-generated and shipped with the binary.
As the command is included as a separate step in the upstream docs, I'm not sure this is something we should do automatically.

**Comment by krehel** [comment]
Thanks for the PR!  Mixed feelings here, inclined to agree with @bevanjkay.

Appreciate the intent, think this is probably a net positive to the user experience, but not something we typically do as we want to stay close to the equivalent of installing from upstream.

There's a potential slippery slope of leading down customizations or the proliferation of preflight/postflight blocks which I think should be avoided.

If this does go through, I would think it's better served as a DSL block like `generate_completions_from_executable` and not arbitrary Ruby code.

**Comment by p-linnane** [comment]
Passing on this for the reasons above.

**Pull request closed without merging**
