### PR TITLE
Update aptanastudio to 3.6.1

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by gtmgianni** [comment]
The file is not code-signed, and the developer's Twitter and Facebook feeds haven't been active since 2014. However, there have been commits made to the [Github repository](github.com/aptana/studio3) recently.

Should this cask be removed, or is it worth trying to verify that the change to its `sha256` is legitimate?

**Comment by vitorgalvao** [comment]
Since there have been recent commits, the repo is a good place to ask for confirmation.

**Comment by gtmgianni** [comment]
The developer said that they [updated the download files, and will soon increment the version number](https://github.com/aptana/studio3/issues/459#issuecomment-381220131). For now, should this pull request be closed, or shall we put it on hold until the developer releases the next version of the application?

**Comment by vitorgalvao** [comment]
Since the developer confirmed the change is legitimate, we can merge. Thank you for opening the issue with them.

**Pull request merged**
