### PR TITLE
Update appcast and homepage in  tcl.rb

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by suschizu** [comment]
```
audit for tcl: failed
 - The URL https://downloads.activestate.com/ActiveTcl/releases/8.6.9.0/ActiveTcl-8.6.9.8609.2-macosx10.9-x86_64.pkg is not reachable
```
strange behaviour: says 443: Connection refused 
but one second later the download begins …

**Comment by ran-dall** [comment]
@suschizu This is strange.

```shell
$ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/developer/bin/cask-pr-local-check https://github.com/Homebrew/homebrew-cask/pull/83366
==> Downloading https://downloads.activestate.com/ActiveTcl/releases/8.6.9.0/Act
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'tcl'.
audit for tcl: failed
 - The URL https://downloads.activestate.com/ActiveTcl/releases/8.6.9.0/ActiveTcl-8.6.9.8609.2-macosx10.9-x86_64.pkg is not reachable
Error: audit failed for casks: tcl

1 file inspected, no offenses detected
```

```shell
$ http -d https://downloads.activestate.com/ActiveTcl/releases/8.6.9.0/ActiveTcl-8.6.9.8609.2-macosx10.9-x86_64.pkg

HTTP/2 200 b'OK'


http: error: PermissionError: [Errno 13] Permission denied: 'ActiveTcl-8.6.9.8609.2-macosx10.9-x86_64.pkg'
```

This makes me think it's a server error.

That said, I can complete the download with `curl` if I send a `User-Agent` even if it's an empty one...

```shell
curl -A '' -H 'User-Agent;' -o ~/Downloads/ActiveTcl-8.6.9.8609.2-macosx10.9-x86_64.pkg https://downloads.activestate.com/ActiveTcl/releases/8.6.9.0/ActiveTcl-8.6.9.8609.2-macosx10.9-x86_64.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.5M  100 17.5M    0     0  2871k      0  0:00:06  0:00:06 --:--:-- 2990k
```

**Comment by vitorgalvao** [comment]
> That said, I can complete the download with `curl` if I send a `User-Agent` even if it's an empty one...

Does adding it [as a parameter](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#additional-https-url-parameters) work?

**Comment by vitorgalvao** [comment]
Should be related to https://github.com/Homebrew/homebrew-cask/issues/83481.

**Pull request merged**
