### PR TITLE
Update arq from 5.17.3 to 6.1.6

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
note that they have an electron appcast now but i've been unable to find it

**Comment by core-code** [comment]
no idea about that failure. travis is becoming more and more erratic over the past few days.

**Comment by suschizu** [comment]
what about: 

`  uninstall quit:   'com.haystacksoftware.Arq',
            launchctl: [
                         'com.haystacksoftware.ArqMonitor',
                         'com.haystacksoftware.arqagent',
                       ]`

**Comment by core-code** [comment]
thanks good suggestion! :) picky mr travis still aint happy though

**Comment by core-code** [comment]
its green! good job @suschizu

**Pull request merged**
