### PR TITLE
add manasecurity.com: macOS vulnerability management for individuals

### PR DESCRIPTION
**Pull request by yugoslavskiy**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @yugoslavskiy.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by yugoslavskiy** [comment]
Hello @miccal ! Thank you for quick response. I've done it (:

**Comment by danmanasecurity** [comment]
@miccal is there anything else I should to do with it? (:

**Comment by yugoslavskiy** [comment]
Fixed all the issues 🙏

**Comment by bevanjkay** [comment]
@yugoslavskiy The `com.apple.systemevents` is a CI error and shouldn't be quit on uninstall. I'll fix it up, everything else should be ready to go now. Thanks.

**Comment by bevanjkay** [comment]
@miccal This one looks good to go, CI just can't seem to run without picking up `com.apple.systemevents`

**Comment by miccal** [comment]
Thank you @yugoslavskiy.

**Comment by miccal** [comment]
Thank you @yugoslavskiy.

**Pull request merged**
