### PR TITLE
various: add rosetta caveats [n-r]

### PR DESCRIPTION
**Pull request by wickles**
Partial test/followup for https://github.com/Homebrew/homebrew-cask/pull/177913 (part 4)

### CODE REVIEW

**Comment by wickles** [comment]
reverting...

- false positive x64 url: qt-creator, qt-creator@dev
- disabled: operator
- installer fails on arm: osxfuse

**Comment by wickles** [comment]
Only errors are transient timeouts.

**Comment by bevanjkay** [comment]
Tests all passed except for an unrelated livecheck issue, let's get this merged before it falls further behind.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
