### PR TITLE
Update bunq to 0.9.0 and rename to bunqcommunity-bunq

### PR DESCRIPTION
**Pull request by Crecket**
Due to a name change I renamed the bunq cask to bunqDesktop  to match the official project name. I was told when we first submitted the cask that 'desktop' wasn't allowed but I recently noticed it is allowed if it is a part of the actual project name. 

Since that is the case for our project I've decided to rename the cask and I added the additional checks required for a new cask

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
> Due to a name change

What name change?

> I recently noticed it is allowed if it is a part of the actual project name.

I don't understand what you mean by this. https://github.com/Homebrew/homebrew-cask/pull/45208#issuecomment-376010269 still applies.

**Comment by Crecket** [comment]
We changed the project's name from BunqDesktop to bunqDesktop to match the company which this project was built for. 

The main reason to change it though is that I was told that project names ending in desktop weren't allowed and only recently I found out it was okay in certain situations.

This is just a opensource project for their API so just to be safe I'd like to rename it to ensure it is clear that this isn't the official bunq application

**Comment by commitay** [comment]
> The main reason to change it though is that I was told that project names ending in desktop weren't allowed and only recently I found out it was okay in certain situations.

I still don't understand where you are getting "okay in certain situations" from?

From our point of view `BunqDesktop` and  `bunqDesktop` are the same thing. The cask token should be `bunq`.

**Comment by Crecket** [comment]
BunqDesktop and bunqDesktop are the same project. 'bunq' is not a correct cask token for it and it was only used since I was told that the project name couldn't end in 'desktop'. bunqDesktop is the actual project name and thus should be named so which seems to follow the guidelines. There is no bunqWeb or something similar. It is the official project name just like you'd say Chrome or Github.

The official bunq app is not related to this project which is why I don't want to use their official name for the cask. Both to let users know this isn't an official 'bunq' release and for potential legal reasons

**Comment by commitay** [comment]
> The official bunq app is not related to this project which is why I don't want to use their official name for the cask. Both to let users know this isn't an official 'bunq' release and for potential legal reasons

If this is an unofficial app calling it `bunq` or `bunqdesktop` is insufficient disambiguation.

Per the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md):

> If the token for a piece of unofficial software that interacts with a popular service would make it look official and the vendor is not authorised to use the name, a prefix must be added for disambiguation.

> Remove from the end: strings such as “Desktop”, “for Desktop”.

Please rename this cask to `bunqcommunity-bunq`

**Comment by Crecket** [comment]
We have explicit permission to use that name for almost a year now and bunqDesktop is the actual name. There is no bunqWeb or whatever, it's part of the actual software name and something people use to recognize it by

Honestly I find it a bit odd that when I try to change the name myself it is now a big deal whereas originally when another user added the project under the actual official company name it was no problem.

**Comment by OGKevin** [comment]
> Please rename this cask to bunqcommunity-bunq

Is still not a correct name for the actual project. bunq is the company/app name. The project, which allows you use bunq’s services on your desktop, is called bunqDesktop for a reason. Calling it bunq is ambiguous. Because: 

1. it’s not an official app, made by the company bunq, in the AppStore.
2. it’s a third party app that allows users to use the bunq services on their desktop.

Calling it bunq on hombrew was a mistake to begin with and this PR is fixing that mistake. Ultimately the hombrew project can be named `bunqcommunity-bunqDesktop` either way, the project is called bunqDesktop and should be reflected in the hombrew project name. 

By naming it the way I suggested above will also fix:

> If this is an unofficial app calling it bunq or bunqdesktop is insufficient disambiguation.

**Comment by commitay** [comment]
> Honestly I find it a bit odd that when I try to change the name myself it is now a big deal

Because the cask name that you want to use contradicts the token reference.

**Comment by Crecket** [comment]
> The name `bunq` would confuse me because it makes me think it'll install a version of their API or a cli interface.

Just to clarify, @OGKevin agress that using `bunq` would be confusing and incorrect.

I'd be fine with using `bunqcommunity-bunqdesktop` if using just `bunqdesktop` is suddenly considered too confusing whereas we are litteraly using THE ACTUAL COMPANY NAME right now as the token name.  `bunqcommunity-bunq` or `bunq` is just straight up incorrect

**Comment by OGKevin** [comment]
@Mechazawa could you please elaborate why you thumbed down my comment ? As it seems that your comment is excatly what I’m saying... 🤔

**Comment by commitay** [comment]
> Then why are `readytalk-desktop`, `telegram-desktop` or `qdesktop` allowed? 

Because `readytalk` already exists, `telegram` has multiple versions and `qdesktop` was a specific exemption.

> bunqDesktop is the actual product name and people in the community recognize it by that name.

`GitHub Desktop` is the actual product name and it's token is `github`. `TogglDesktop` is the actual product name and it's token is `toggl`.

**Comment by Crecket** [comment]
Would `bunqcommunity` as a token name be allowed? I understand that we're not getting this approved with desktop at the end so if bunqcommunity isn't allowed then we'll have to think of something else.

The point of the rename is to prevent confusion and `bunq` is the official company name so I'd like to move away from that.

**Comment by commitay** [comment]
> Would bunqcommunity as a token name be allowed?

No, as it does not follow the token reference.

> I understand that we're not getting this approved with desktop at the end so if bunqcommunity isn't allowed then we'll have to think of something else.

Just to be clear: the token reference is a list of rules that we follow for consistent naming of casks, suggesting alternatives isn't an option.

Unless you are willing you rename the actual app bundle itself so the cask can have a different token there isn't anything more to discuss here.

Please rename it to `bunqcommunity-bunq`.

**Comment by Crecket** [comment]
I renamed the cask, everything should be fine now

**Pull request merged**
