### PR TITLE
Update a-better-finder-attributes to 6.03

### PR DESCRIPTION
**Pull request by colindunn**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by colindunn** [comment]
This cask raises a question I've had for a while but keep forgetting to ask.

The appcast is valid, but each time the app updates the cask breaks because the download checksum fails because there aren't versioned links.

I can find all their older versions [here](http://www.publicspace.net/download/), but the latest doesn't have a versioned download.

Should all the ones like this I find be changed to latest?
Should those with static links also be changed to latest when found?

**Comment by miccal** [comment]
Ping @vitorgalvao, who will be able to provide a better and more detailed answer than I can.

**Comment by vitorgalvao** [comment]
This cask is correct. As long as it has an appcast it must be versioned, even if the URL isn’t.

Appcasts exist precisely so we can detect when said changes happen (more scripts to do it are in the works).

**Comment by colindunn** [comment]
Thanks @vitorgalvao. I'll just move to latest those I find with no appcast and an unversioned link

**Comment by vitorgalvao** [comment]
> Thanks @vitorgalvao. I'll just move to latest those I find with no appcast and an unversioned link

No rush, though. If they aren’t broken, no need to do it. The only reason some casks need `:latest` and `:no_check` is otherwise they break constantly. If there’s an app that is so rarely updated it never breaks even with a version and an unversioned url, no point in weakening it.

**Pull request merged**
