### PR TITLE
Update netbeans to 11.1

### PR DESCRIPTION
**Pull request by core-code**
this is not ready to merge yet. i don't have time to work much on this yet, but this PR serves as a reminder that there are now official NetBeans Mac binaries again. maybe someone can help get this cask updated.

### CODE REVIEW

**Comment by core-code** [comment]
travis seems to be happy already ;)

remaining issues:
• why didn't it work with the proper mirror selection URL? other casks have this just fine.
• is the uninstall stanza really correct?

**Comment by core-code** [comment]
ok the installed pkg is
`org.netbeans.ide.nbide.11.1
`
and the app is installed
`/Applications/NetBeans/Apache\ NetBeans\ 11.1.app 
`
so the current uninstall stanza seems fine.

unless someone wants to work on the mirror-selection problem, i guess this already good-to-merge

**Comment by core-code** [comment]
what about those? should i sell delete requests?

```
netbeans-cpp
netbeans-html
netbeans-java-ee
netbeans-java-se
netbeans-php
```

**Comment by vitorgalvao** [comment]
> what about those? should i send delete requests?

Are they no longer distributed/developed?

For reference:

```
netbeans-cpp
30 days: 13 (#2035)
90 days: 35 (#2135)
365 days: 140 (#2048)

netbeans-html
30 days: 2 (#4151)
90 days: 4 (#4647)
365 days: 31 (#3838)

netbeans-java-ee
30 days: 15 (#1919)
90 days: 80 (#1382)
365 days: 381 (#1223)

netbeans-java-se
30 days: 15 (#1920)
90 days: 71 (#1491)
365 days: 306 (#1391)

netbeans-php
30 days: 12 (#2096)
90 days: 34 (#2162)
365 days: 171 (#1867)
```

**Comment by core-code** [comment]
i am not an expert on netbeans but i couldn't find any reference to any additional or alternative packages for cpp/php/etc

**Pull request merged**
