### PR TITLE
Using DNS host for Cloudflare WARP

### PR DESCRIPTION
**Pull request by fedotov-as**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@miccal There may not be much benefit in enabling livecheck on this cask. But extract_plist would work, albeit with a ~35mb fetch.

**Comment by miccal** [comment]
@bevanjkay I do not believe it will work in this case as the `.app` is buried in a `.pkg`.

**Comment by bevanjkay** [comment]
@miccal 

```livecheck do
    url :url
    strategy :extract_plist
end
```

returns
> cloudflare-warp : 1.5.294.0,20210701.2 ==> 1.5.207.0,20210616.5

**Comment by miccal** [comment]
Oh really? I dod not think it would work! Please feel free to open a new PR to add this, thanks :)

**Pull request merged**
