### PR TITLE
datadog-agent: various updates

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
This may need to change to an `installer manual:` as it requires a user to grant access to `System Events.app` a few times during the install phase.

**NOTE:** To completely uninstall, follow the instructions [here](https://docs.datadoghq.com/agent/faq/how-do-i-uninstall-the-agent/?tab=agentv6v7#mac-os) and also:
```
rm ~/Library/LaunchAgents/com.datadoghq.agent.plist
rm -r ~/.datadog-agent
sudo pkgutil --forget com.datadoghq.agent
```

**Comment by miccal** [comment]
I have changed this to an `installer manual:` and tested, all good:
```
-> brew install datadog-agent
==> Caveats
You will need to update /opt/datadog-agent/etc/datadog.yaml and replace APIKEY with your api key

If you ever want to start/stop the Agent, please use the Datadog Agent App or datadog-agent command.
It will start automatically at login, if you want to enable it at startup, run these commands:

sudo cp '/opt/datadog-agent/etc/com.datadoghq.agent.plist.example' /Library/LaunchDaemons/com.datadoghq.agent.plist
sudo launchctl load -w /Library/LaunchDaemons/com.datadoghq.agent.plist

==> Downloading https://dd-agent.s3.amazonaws.com/datadog-agent-7.23.0-1.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'datadog-agent'.
==> Installing Cask datadog-agent
Warning: macOS's Gatekeeper has been disabled for this Cask
To complete the installation of Cask datadog-agent, you must also
run the installer at:
  '/usr/local/Caskroom/datadog-agent/7.23.0-1/datadog-agent-7.23.0-1.pkg'
🍺  datadog-agent was successfully installed!
```
&nbsp;
Installing manually is fine:
```
bash 5.0.18   /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/casks   3680
|-> open /usr/local/Caskroom/datadog-agent/7.23.0-1/datadog-agent-7.23.0-1.pkg
```
&nbsp;
`uninstall` and `zap` works fine and completely removes all traces of everything, although `pkgutil` _does_ take about a minute to successfully complete:
```
|-> brew cask zap datadog-agent
==> Implied "brew cask uninstall datadog-agent"
==> Removing launchctl service com.datadoghq.agent
Password:
==> Quitting application 'com.datadoghq.agent'...
Application 'com.datadoghq.agent' quit successfully.
==> Uninstalling packages:
com.datadoghq.agent
==> Removing files:
/Applications/Datadog Agent.app
/opt/datadog-agent
/usr/local/bin/datadog-agent
==> Dispatching zap stanza
==> Trashing files:
~/.datadog-agent
~/Library/LaunchAgents/com.datadoghq.agent.plist
==> Removing all staged versions of Cask 'datadog-agent'
```

**Comment by albertvaka** [comment]
Hi! Datadog employee here. We have found an issue with the Mac version of Agent 7.23 that causes it to crash after a while and we are going to remove it from the bucket. We will fix it on a future release. For now, 7.22.0 is going to be the latest build available for Mac.

**Comment by miccal** [comment]
Thank you for letting us know @albertvaka.

**Review by miccal — APPROVED** [review]

**Pull request merged**
