### PR TITLE
Update messenger from 97.11.116,283083801 to 110.0.0.7.119,300301816

### PR DESCRIPTION
**Pull request by thehowieee**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@thehowieee The link on the download page is directing me to the previous version - https://www.messenger.com/desktop
Was this update triggered by an in-app update for you, or did you find the version published somewhere online?

**Comment by thehowieee** [comment]
In-app update for me.

On Jun 23, 2021, at 6:49 PM, Bevan Kay ***@***.***> wrote:

﻿

@thehowieee<https://github.com/thehowieee> The link on the download page is directing me to the previous version - https://www.messenger.com/desktop
Was this update triggered by an in-app update for you, or did you find the version published somewhere online?

**Comment by bevanjkay** [comment]
It seems like this could be a staged release, as the website is still showing the previous version, and I haven't been prompted for an update on my install of 97.x as yet.

@thehowieee Do you have the 'more frequent updates' option turned on in the app settings?

**Comment by thehowieee** [comment]
> It seems like this could be a staged release, as the website is still showing the previous version, and I haven't been prompted for an update on my install of 97.x as yet.
> 
> @thehowieee Do you have the 'more frequent updates' option turned on in the app settings?

I don't have that option. Under Preferences > General I have "Opt in to the beta", however, it is not selected.

messenger

**Comment by cho-m** [comment]
We are probably going to have to wait until the update shows up on main website or via `livecheck` URL.

The Cask `livecheck` should be related to auto-updater, but I am not familiar with details on Electron-builder app updates:
```console
❯ cat Messenger.app/Contents/Resources/app-update.yml
provider: generic
url: 'https://www.facebook.com/messenger/desktop/update/'
updaterCacheDirName: messenger-updater
```

**Comment by thehowieee** [comment]
> We are probably going to have to wait until the update shows up on main website or via `livecheck` URL.
> 
> The Cask `livecheck` should be related to auto-updater, but I am not familiar with details on Electron-builder app updates:
> 
> ```
> ❯ cat Messenger.app/Contents/Resources/app-update.yml
> provider: generic
> url: 'https://www.facebook.com/messenger/desktop/update/'
> updaterCacheDirName: messenger-updater
> ```

got it - I'll close this out.

**Pull request closed without merging**
