### PR TITLE
updated Zulip app to v1.4.0

### PR DESCRIPTION
**Pull request by akashnimare**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] `sha256` changed but `version` stayed the same ([what is this?][version-checksum]).  
      I’m providing public confirmation below.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
@akashnimare It looks like the `sha256` has changed.
```
audit for zulip: failed
 - download not possible: Checksum for Cask 'zulip' does not match.

Expected: 3e24cb4c20990e48ce1797b79726a52dee8db4d1c9b3819f59a1ca1f4f05bc73
Actual:   43468572eb05071adddeae820884c503b97a787fb6fd0e21d6b1d7f11a79ac9b
```

**Comment by akashnimare** [comment]
@commitay what do to here?

**Comment by commitay** [comment]
Please update the `sha256`.

**Comment by akashnimare** [comment]
Okay so the correct `sha256` is `3e24cb4c20990e48ce1797b79726a52dee8db4d1c9b3819f59a1ca1f4f05bc73`, right?

**Comment by commitay** [comment]
```
sha -a 256 Zulip-1.4.0-mac.zip
43468572eb05071adddeae820884c503b97a787fb6fd0e21d6b1d7f11a79ac9b  Zulip-1.4.0-mac.zip
```

**Comment by commitay** [comment]
```
audit for zulip: failed
 - download not possible: Checksum for Cask 'zulip' does not match.

Expected: cd7116017493537ad3cb11558fd9f585360ae51a99093e8cf114045728771f09
Actual:   43468572eb05071adddeae820884c503b97a787fb6fd0e21d6b1d7f11a79ac9b
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38406

**Pull request closed without merging**
