### PR TITLE
Add nautilus 1.3.1

### PR DESCRIPTION
**Pull request by DocLM**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vladimyr** [comment]
This is the first public release, right? That would explain why the appcast is empty: https://github.com/oslabs-beta/nautilus/releases.atom

**Comment by ran-dall** [comment]
> This is the first public release, right? That would explain why the appcast is empty: https://github.com/oslabs-beta/nautilus/releases.atom

@vladimyr There's also: https://github.com/nautilusapp/nautilus; which I think is the correct one.

**Comment by vladimyr** [comment]
@ran-dall Don't know 🤷 The thing I noticed comparing them is that latter one is probably behind in terms of commits because readme lacks download links. And unfortunately, it offers no benefit due to empty appcast too https://github.com/nautilusapp/nautilus/releases.atom

**Comment by ran-dall** [comment]
> @ran-dall Don't know 🤷 The thing I noticed comparing them is that latter one is probably behind in terms of commits because readme lacks download links. And unfortunately, it offers no benefit due to empty appcast too https://github.com/nautilusapp/nautilus/releases.atom

@vladimyr This is true, I saw that too. As I said, I dunno the difference and which one is supposed to be the offical one. Maybe @core-code might have a preference.

**Comment by core-code** [comment]
lets use this one` https://github.com/oslabs-beta/nautilus/releases.atom`

seems to be up to version 1.3 now

**Comment by ran-dall** [comment]
@core-code `https://github.com/oslabs-beta/nautilus/releases` seems to have been cleared? Maybe @jdnordy can help us out with figuring out what the best `appcast` would be.

**Comment by vitorgalvao** [comment]
@ran-dall @core-code Leaving this for one of you to merge whenever you’re comfortable with the state of the cask.

**Comment by vitorgalvao** [comment]
(The closing was a mistake)

**Comment by ran-dall** [comment]
@core-code I think the version number matches and everything seem GTM. 👍

**Comment by core-code** [comment]
thanks, looks good :)

**Pull request merged**
