### PR TITLE
Add uninstaller and zap to Casks/dbvisualizer.rb

### PR DESCRIPTION
**Pull request by sparhomenko**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we can’t accept this. Your `postflight` block calls a GUI, and we avoid that.

`app` is also being used wrong, as it’s meant to link an app bundle that comes with the download package (which doesn’t happen, in this case).

`zap` and `uninstall` are welcome, though, but are you sure `uninstall` needs `:signal` and couldn’t achieve the result with `quit`?

If you make the changes and [squash your commits](http://davidwalsh.name/squash-commits-git), we can merge this in.

**Comment by sparhomenko** [comment]
GUI appearing looks like an installer bug - I am using install4j unattended mode (`-q`), which is supposed to suppress GUI. It properly does so in the previous DbVisualizer version (9.1.11), but does not in the current version (9.2). I'll try to ask around on the DbVisualizer forums.

I tried to find a way to perform the installation directly to the Homebrew Cask Applications directory, but didn't find a method for that in the documentation. So I went with installing to the `${staged_path}` and using `app` to symlink to the proper appdir. There's also an option of not specifying target installation directory and going with the one chosen by the installer, which some casks do, but using `app` seemed a rather harmless way to achieve proper rather directory. Can you recommend a better way, or do you see some harmful consequences of such approach that I don't? 

`uninstall :quit` didn't close the application for me - no idea why, but sending TERM signal worked.

To be honest, main purpose of the PR was to automate the installation itself - there's not much use of a Cask that still requires a manual install. If you prefer to merge `uninstall` / `zap` without waiting for a reply from the guys behind DbVisualizer about a way to fully suppress GUI - let me know, I'll update this PR and create another one for the automated installation later if necessary.

**Comment by vitorgalvao** [comment]
>  I'll try to ask around on the DbVisualizer forums.

Thank you for the initiative.

> there's not much use of a Cask that still requires a manual install.

You don’t have to go to the website and get it, which is one of the most boring steps.

>  If you prefer to merge `uninstall` / `zap` without waiting for a reply from the guys behind DbVisualizer about a way to fully suppress GUI - let me know, I'll update this PR and create another one for the automated installation later if necessary.

That sounds good. They may need to fix something internally that could be holding up the PR a while for nothing. With your suggestion we can already merge what can be done and take care of the rest later.

Your approach is good, and although we don’t usually do things like that, I don’t necessarily see it as an issue, if it works. When the time comes (i.e. when the issue of it calling a GUI is resolved and you make the new submission) we can discuss it more in depth and bring more maintainers into the discussion.

`uninstall` should also be improved to remove whatever else the installer dumps on the system. There are [scripts](https://github.com/phinze/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/phinze/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#uninstall-stanza-details) geared for that, if you feel like taking a stab at it.

**Comment by sparhomenko** [comment]
I've updated the PR to only contain `uninstall` and `zap` parts. It is still a single commit.

> `uninstall` should also be improved to remove whatever else the installer dumps on the system.

The only other thing is `DbVisualizer.app` itself, but if the installation is not automated there's no way to determine which folder user selected while manually running the installer - `~/Applications`, `/Applications`, or something else entirely. We can come back to this in the automated installation PR; if it would be done with `app` the removal of symlink in the Applications directory is done automatically.

**Comment by vitorgalvao** [comment]
> The only other thing is `DbVisualizer.app` itself

So the only thing the installer does is move the app bundle somewhere? It doesn’t installing anything more?

> but if the installation is not automated there's no way to determine which folder user selected while manually running the installer

You are correct. [Working on it](https://github.com/caskroom/homebrew-cask/pull/8210).

**Comment by sparhomenko** [comment]
> So the only thing the installer does is move the app bundle somewhere? It doesn’t installing anything more?

As far as I can see - yes, there are no other files or directories being created. Thanks for merging!

**Pull request merged**
