### PR TITLE
Update soundcloud-downloader to 2.7.7

### PR DESCRIPTION
**Pull request by gobinathm**
- App Cast changed
- Old appcast return 'HTTP response code was returned (302).'

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You forgot the confirmation link.

**Comment by giannitm** [comment]
@gobinathm The appcast says that version 2.7.7 is released?

**Comment by giannitm** [comment]
@vitorgalvao I don't think this needs a confirmation link.

**Comment by gobinathm** [comment]
@victorpopkov as mentioned by @giannitm there is no need for confirmation. As this is a version bump now.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
