### PR TITLE
docker: increase minimum required macos version

### PR DESCRIPTION
**Pull request by ddelange**
image

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
https://docs.docker.com/desktop/install/mac-install/

> macOS must be version 11 or newer. That is Big Sur (11), Monterey (12), or Ventura (13).

**Comment by bevanjkay** [comment]
The issue with the appcast should be reported upstream, as their in-app updater would be providing version updates to unsupported version also if the docs are correct.

**Comment by ddelange** [comment]
aha, do you know where I can report that (and subsequently close this one?)

**Comment by bevanjkay** [comment]
@ddelange Looks like there's already a bug tracking this upstream here - https://github.com/docker/for-mac/issues/6732
So add your +1 there. Because the in-app updater is also sending people to the latest version, we would be best finding the version that is the oldest that supports `10.15` and splitting this cask with `on_{system}` conditionals.

**Comment by ddelange** [comment]
@bevanjkay agreed with this PR being 'useless' (will close): could I ask you to take over the conditional idea?

just checked the [history](https://github.com/Homebrew/homebrew-cask/commits/master/Casks/docker.rb):
- [4.15.0,93002](https://github.com/Homebrew/homebrew-cask/commit/1a83f3469ab57b01c0312aa70503058f7a27bd1d) is still compatible with 10.15
- [4.16.0,95345](https://github.com/Homebrew/homebrew-cask/commit/02421bac7e7dd752b65ce5058168021fad6e8bd8) is not

image

**Pull request closed without merging**
