### PR TITLE
Update podman from 1.4.2 to 1.5.0

### PR DESCRIPTION
**Pull request by ashley-cui**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ashley-cui** [comment]
Wanted to get the app in without documentation first. If anyone could help me with other parts, that would be great. (See #67491)

**Comment by reitermarkus** [comment]
This seems to be open-source and CLI-only, so it should be a formula, not a cask.

**Comment by ashley-cui** [comment]
@reitermarkus https://github.com/Homebrew/homebrew-cask/pull/64042#issuecomment-496993261

**Comment by reitermarkus** [comment]
Thanks, @ashley-cui!

**Pull request merged**
