### PR TITLE
Replace some artifacts with manpage

### PR DESCRIPTION
**Pull request by timfjord**
This is a follow-up PR for https://github.com/Homebrew/brew/pull/6629 where `manpage` has been added.

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by timsly** [comment]
There is one file left https://github.com/Homebrew/homebrew-cask/blob/master/Casks/podman.rb#L12-L27 with explicit manpage manipulations.
I am just not sure whether `manpage` helper is available in the context of the `postflight` block

**Comment by reitermarkus** [comment]
I think `podman` should actually be a formula since it is open-source and CLI only.

**Comment by timsly** [comment]
Cool. So I am leaving it as it is then and might convert it to formula later

Another problem is that CI wants me to prepare a PR for each updated cask. Ss there a way to bypass that or the only to run CI is to create a PR for each cask?

**Comment by reitermarkus** [comment]
> the only way to run CI is to create a PR for each cask?

Yes, please create a separate PR for each cask.

**Comment by timsly** [comment]
Closing in favour of
- https://github.com/Homebrew/homebrew-cask/pull/73080
- https://github.com/Homebrew/homebrew-cask/pull/73081
- https://github.com/Homebrew/homebrew-cask/pull/73082
- https://github.com/Homebrew/homebrew-cask/pull/73083
- https://github.com/Homebrew/homebrew-cask/pull/73084
- https://github.com/Homebrew/homebrew-cask/pull/73085
- https://github.com/Homebrew/homebrew-cask/pull/73086

**Pull request closed without merging**
