### PR TITLE
Update arq-cloud-backup to 1.2.2 - checksum

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
in this case the pull request is wrong. the SHA has changed because now it is version 1.2.2.

so, you should just update the version too as keeping it at 1.2.1 would be wrong anyway.

**Comment by core-code** [comment]
for other cases where the version was not updated and it really was a SHA-only change i guess you could either provide proof of valid signature, or if its unsigned just wait until this is merged and the rules have been relaxed: https://github.com/Homebrew/brew/pull/5371

**Comment by vitorgalvao** [comment]
Technically, this one should be `:latest`/`:no_check`. But if it doesn’t cause problems as is, no harm done.

**Review by vitorgalvao — APPROVED** [review]

**Comment by core-code** [comment]
we could use this as 

> Technically, this one should be `:latest`/`:no_check`. But if it doesn’t cause problems as is, no harm done.

we could use this as an appcast:
https://www.arqbackup.com/download/arqcloudbackup/arqcloudbackup_release_notes.html

**Comment by ran-dall** [comment]
> btw, you can use 'Suspicious Package' (or 'Pacifist') to look into packages without actually installing them.

@ core-code Yea, this is what I normally do, I use Pacifist.

**Pull request merged**
