### PR TITLE
feat: add devtools-x

### PR DESCRIPTION
**Pull request by Hacksore**
i used the gh cli and grief this PR body 😂

tracking issue upstream: https://github.com/fosslife/devtools-x/issues/63

### CODE REVIEW

**Comment by krehel** [comment]
Thank you for your submission, but we cannot accept it at this time because it does not pass our signature verification check that are a requirement for new submissions:

> macOS on ARM requires software to be signed. Please contact the upstream developer to let them know they should sign and notarize their software.

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).

Additionally, regarding the PR template -- it contains a number of checkboxes for how to use `brew` tools to fix style and audit errors before pushing to GitHub.

**Comment by Hacksore** [comment]
@krehel yup understood, my hands are tied here but if something changes upstream ill open a new one.

thanks!

**Comment by krehel** [comment]
No worries @Hacksore! Do recommend using the local tooling the `brew` team has developed - it'll save you a lot of time and headache!

**Comment by Hacksore** [comment]
@krehel absolutely, but i had ran `gh pr create --fill --draft` which will yeet the template.

Next time ill use the template though!

**Comment by krehel** [comment]
@Hacksore That's fair, but I am referring to running `brew style `and `brew audit` locally.  CI is going to run them and fail.  You can run them locally and fix issues before pushing commits, is my point.

**Pull request closed without merging**
