### PR TITLE
Add PrintNode latest

### PR DESCRIPTION
**Pull request by timlo**
Add PrintNode client software

### CODE REVIEW

**Comment by adityadalal924** [comment]
I found a versioned URL: app.printnode.com/bundles/printnodemain/downloads/printnode/4.8.0/PrintNode-4.8.0+dd7.dmg 

So, the cask should be
```
  version '4.8.0'
  sha256 '3c8203d7200de76deeb0274b7ff69b54fd21e91a7140210c1459fd46f78b04fa'

  url "app.printnode.com/bundles/printnodemain/downloads/printnode/#{version}/PrintNode-#{version}+dd7.dmg"
```

Probably also want to add for the sake of completeness

```
depends_on :macos => '>= :mountain_lion'
```

**Comment by timlo** [comment]
There's definitely a versioned URL, but I was inferring from everything in the contributing doc that if there's a vendor link for a "latest" stable release that it would be preferred?

**Comment by jawshooah** [comment]
@timlo We actually prefer versioned URLs (see #1021), though the documentation is a bit outdated in that regard.

**Comment by timlo** [comment]
Great, thanks for all the feedback @adityadalal924 & @jawshooah updated the cask.

**Comment by jawshooah** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 03ce5aff490697d0ae7f9d84d56ef816ec20496f. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
