### PR TITLE
Update mamp from 5.6 to 5.5

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
mamp has been downgraded to 5.5

**Comment by core-code** [comment]
hm...maybe try restarting travis?

**Comment by suschizu** [comment]
`installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)`

**Comment by core-code** [comment]
@vitorgalvao any ideas here? since version 5.6 has been pulled by upstream it is probably quite buggy and we should follow suit...

**Comment by vitorgalvao** [comment]
Agreed. As for the error, since it’s a downgrade I’ll assume for now that CI is the one causing issues (as it happens often with PKGs) and will revisit if we get user complaints.

**Comment by core-code** [comment]
thanks!

**Pull request merged**
