### PR TITLE
greenery 0.9.3 (New Cask Submission)

### PR DESCRIPTION
**Pull request by tmrdev**
This is the initial commit and PR for Greenery. A cryptocurrency bookkeeping and accounting wallet.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your submission @tmrdev, but we cannot accept it at this time because it does not meet our [minimum notability requirements](https://docs.brew.sh/Acceptable-Casks#rejected-casks):

> + The Cask is for an app that is too obscure. Examples:
>   + An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars).

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if it gets notable enough we would then be happy to consider adding this to `homebrew-cask`.

**Comment by tmrdev** [comment]
> Thank you for your submission @tmrdev, but we cannot accept it at this time because it does not meet our [minimum notability requirements](https://docs.brew.sh/Acceptable-Casks#rejected-casks):
> 
> > * The Cask is for an app that is too obscure. Examples:
> >   
> >   * An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars).
> 
> Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if it gets notable enough we would then be happy to consider adding this to `homebrew-cask`.

Remote hosting for the Greenery Tap has been created and works well.  However Greenery is a binary release, so do forks not apply in this instance?  Are download metrics collected when users install remotely like this:

brew install GreenfireInc/homebrew-greenery/greenery

Thank you for your time.

**Comment by bevanjkay** [comment]
@tmrdev Because the repository only hosts the binaries and not the source files, the minimum notability requirement check may be able to be skipped.
Is there a reason why you are pointing the `homebrew-greenery` repository instead of what looks like the general release repository? https://github.com/GreenfireInc/Releases.Greenery

**Comment by tmrdev** [comment]
> @tmrdev Because the repository only hosts the binaries and not the source files, the minimum notability requirement check may be able to be skipped.

The PR was rejected for not being Notable. So since this is a binary release are Forks, Watchers and Stars skipped in this instance or just Forks?

As for the download count is that counting every download when I execute the remote install command from the Casks directory for homebrew-greenery?

Our team is discussing moving the Greenery Release to Releases.Greenery.

**Comment by bevanjkay** [comment]
>  The PR was rejected for not being Notable. So since this is a binary release are Forks, Watchers and Stars skipped in this instance or just Forks?
Yes we could skip the notability check because the source code is not hosted in the repository.

> As for the download count is that counting every download when I execute the remote install command from the Casks directory for homebrew-greenery?
Yes every download will be counted unless the user has opted out of analytics.

> Our team is discussing moving the Greenery Release to Releases.Greenery.
This is ideal, as we don't usually grab the binaries from another Homebrew tap.

**Pull request closed without merging**
