### PR TITLE
Add HX Edit v2.82

### PR DESCRIPTION
**Pull request by kevinhwang**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but this looks to be a [walled build](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) so [we will not accept it](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#unofficial-vendorless-and-walled-builds).

**Comment by kevinhwang** [comment]
> Thank you, but this looks to be a [walled build](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) so [we will not accept it](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#unofficial-vendorless-and-walled-builds).

@vitorgalvao, Why is this a walled build? `l6c-acdn2.line6.net` looks like a reasonable CDN for https://line6.com. Just because the download host is different in the TLD (`.net` vs `.com`) shouldn't automatically disqualify a cask—lots of sites host their download on separate hosts dedicated to content.

**Comment by vitorgalvao** [comment]
> `l6c-acdn2.line6.net` looks like a reasonable CDN for https://line6.com.

“Looks like” is not good enough. This policy is to protect from malicious actors, and malicious actors would also use something that looks like it’s legitimate. We need verifiability.

> Just because the download host is different in the TLD (.net vs .com) shouldn't automatically disqualify a cask

It doesn’t. It only does so if the authors prevent us from reaching the download link through a login wall or similar.

> lots of sites host their download on separate hosts dedicated to content.

They do. And most of them don’t prevent us from verifying the URL is legitimate. The ones that do, we don’t allow.

> I'd ask you please reconsider.

No. This policy has been in place for a long time and has served us well. There’s nothing about this cask that would warrant an exception. If you need it, I recommend you host your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

**Comment by kevinhwang** [comment]
> [...] We need verifiability.

Okay, it sounds like you're saying that if we could verify that host as a legitimate CDN serving content on behalf of `line6.com`, this cask would pass that rule. That sounds like fair criteria.

If you go to https://line6.com and inspect the network requests being made, you'll see stylesheets, JavaScript, and other assets are being served from https://l6c-acdn2.line6.net. It's actually there in the HTML source. Is that sufficient verification?

**Comment by vitorgalvao** [comment]
> Is that sufficient verification?

No. Verification needs to be simple, in a way that a regular user can do it with little effort, and directly connected to the download URL.

This cask doesn’t even seem to be submitted to the correct repo, as it appears to be a case for [homebrew/cask-drivers](https://github.com/Homebrew/homebrew-cask-drivers). I don’t expect this to be a popular cask.

**Comment by kevinhwang** [comment]
> No. Verification needs to be simple, in a way that a regular user can do it with little effort, and directly connected to the download URL.

Very well. I'll circle back if they ever make the direct download link obviously visible on their site.

> This cask doesn’t even seem to be submitted to the correct repo, as it appears to be a case for [homebrew/cask-drivers](https://github.com/Homebrew/homebrew-cask-drivers).

It's not a driver. It's an app to edit patches (presets / snapshots) on Line 6's line of multi-effects units. It's an editor for electric guitar pedals.

> I don’t expect this to be a popular cask.

I don't know enough to dispute that with any confidence, but I'm pretty sure the number of musicians, and in particular, guitarists who use multi-effects pedals like Line 6s' is larger than that of some of the  really random stuff that's hosted by Homebrew Cask.

**Comment by vitorgalvao** [comment]
> It's not a driver. (…) It's an editor for electric guitar pedals.

Which makes it useless without extra hardware, which makes it a case for `homebrew/cask-drivers`. That’s covered in the links I sent you previously.

> but I'm pretty sure the number of musicians, and in particular, guitarists who use multi-effects pedals like Line 6s' is larger than that of some of the really random stuff that's hosted by Homebrew Cask.

That is only relevant to us if said musicians also use Homebrew Cask, which is where my doubt lies.

**Pull request closed without merging**
