### PR TITLE
Boonzi cask version 42.4

### PR DESCRIPTION
**Pull request by joaovrb**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This is interesting. Is the app any good? Or, since this submission is your only github contribution of the year I’ll ask first “is the app yours?”.

I’m Portuguese as well, hence the interest.

**Comment by joaovrb** [comment]
Olá :)

A app não é minha, sou apenas um user.
Na altura despertou-me atenção, porque era uma app portuguesa para um nicho
interessante. Comprei-a e tenho usado com satisfação.

Tenho andado a 'migrar' as minhas apps para o Cask e há umas quantas que
uso que não estão lá. Decidi adiciona-las. Esta foi a primeira (espero que
tenha feito tudo bem!), mas queria submeter mais umas 2 ou 3 :)

Cheers!

**Comment by vitorgalvao** [comment]
Everything was fine, yes. I ask that we speak in english even with each other tough, for the benefit of the other users and maintainers.

For reference, the previous post mentions he’s not the developer, simply a satisfied user. He has been migrating his apps with homebrew-cask and found some apps aren’t here yet, so will be adding them and this was the first.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 639271e38b5f92cd44da728111deb03d55d5e605 to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
