### PR TITLE
Add Audacity.app v2.2.2

### PR DESCRIPTION
**Pull request by tjt263**
Initial commit.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by tjt263** [comment]
Does this look okay? 
I'm still trying to get the hang of this thing.
Is there more to do; or am I finished?

**Comment by vitorgalvao** [comment]
Thank you, but [we don’t allow Audacity in this repo](https://github.com/caskroom/homebrew-cask/pull/27517).

**Comment by tjt263** [comment]
Respectfully, that's bullshit. 
I read about all the over-complicated methods people have tried in the past.
This is a plain and simple solution that delivers exactly what everyone wants.
It's the current version, and it's straight from the archives of the official hosts.
People want it. You don't have to commit any time / effort to it. It simply works.
All you have to do is let it through for the rest of us. Just think about it. Thanks.

**Comment by vitorgalvao** [comment]
> Respectfully, that's bullshit.

Watch your tone.

This is not the first time oldfoss has been used on that cask. Those “over-complicated methods” were a necessity of the time; you haven’t discovered a silver bullet no one has thought about before.

Everything else aside, [the Audacity team has good reasons to keep using fosshub](https://github.com/caskroom/homebrew-cask/pull/27517#issuecomment-266047079) and I see no motive to go against their wishes.

If you want it so bad as a cask, make a tap. No one is chaining you to this repo.

It’s always the users who never contributed that come in guns blazing with that attitude, and frankly we don’t have to stand for it. If you don’t tone it down next time, you’ll be blocked from repo.

**Pull request closed without merging**
