### PR TITLE
Update josm to 17428

### PR DESCRIPTION
**Pull request by simon04**
Ref: https://josm.openstreetmap.de/wiki/Changelog

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

cc: @grischard

### CODE REVIEW

**Comment by grischard** [comment]
Please don't merge this for now - this isn't marked as a proper release.

**Comment by grischard** [comment]
https://github.com/grischard/josm/releases/download/17428-tested/JOSM-macOS-java15.zip has been created, unfortunately I can't amend this PR.

**Comment by simon04** [comment]
I've updated the PR…

**Pull request merged**
