### PR TITLE
mplab-xc32 4.40

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
The same error as seen in https://github.com/Homebrew/homebrew-cask/pull/154311 and https://github.com/Homebrew/homebrew-cask/pull/145808 I believe:
```
The current OS X version is not supported
```

Contents of the `installbuilder.sh` script for reference:
```
#!/bin/sh

runtimes_dir=$(cd "$(dirname "${0}")" && pwd)
os_version=`uname -r`
machine_platform=`uname -p`
machine_arch=`uname -m`
if [ "${os_version:0:1}" == "6" ];then
    executable="none"
elif [ "${machine_platform}" == "arm" ];then

  runtimes="osx-arm64 osx-x86_64"
  executable=none
  for r in ${runtimes} ; do
    if [ -f "${runtimes_dir}/${r}" ]; then
      executable=${r}
      break
    fi
  done

elif [ "${machine_platform}" == "i386" ];then
  executable=osx-x86_64
else
    executable="none"
fi

if [ "$executable" == "none" ]; then
    echo "The current OS X version is not supported"
    exit 1
fi
            
        
if [ "${1}" == --help ] || [ "`id -u 2>/dev/null`" == "0" ];then
    "`dirname \"${0}\"`/$executable" "$@"
else
    "`dirname \"${0}\"`/MPLAB XC8 C Compiler" $executable "$@"
fi
                
```

**Comment by krehel** [comment]
The initial install script has a hard check for x86_64 (or i386) and on ARM processors causes the check to fail.

For now, I've marked this as `depends_on arch: :x86_64`, but I am close to having this working on ARM by calling the installer directly.  Just a couple small things to sort I think.

**Comment by miccal** [comment]
> The initial install script has a hard check for x86_64 (or i386) and on ARM processors causes the check to fail.
> 
> For now, I've marked this as `depends_on arch: :x86_64`, but I am close to having this working on ARM by calling the installer directly. Just a couple small things to sort I think.

Thank you for looking into this @krehel.

**Comment by krehel** [comment]
I think we can merge this.  I'll open a separate PR for my fixes apart from the version bump.  I'll also try to fit them to `mplab-xc8` and `mplab-xc16` as well.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
