### PR TITLE
Add Karabiner-Elements 11.6 for <= :el_capitan users

### PR DESCRIPTION
**Pull request by adamkiss**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by gtmgianni** [comment]
@adamkiss Travis returned this:

```
>>> Leftover: kexts
> org.pqrs.driver.Karabiner.VirtualHIDDevice.v060600
```

**Comment by vitorgalvao** [comment]
@gtmgianni https://github.com/adamkiss/homebrew-cask/blob/3fa279378267127f8f352f206313fd574f37a54e/Casks/karabiner-elements.rb#L32

**Comment by adamkiss** [comment]
@gtmgianni as Vitor linked, It was purposefully removed from 'uninstall' list.

I am also preparing new commit to fix `depends_on`

**Comment by adamkiss** [comment]
@gtmgianni @vitorgalvao Could you please look at this? I've fixed everything now, it's only "failing" on the leftover kext.

Thank you.

**Pull request merged**
