### PR TITLE
updated blast2go (3.1)

### PR DESCRIPTION
**Pull request by alebcay**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
As soon as I saw this new flood of fixes from you, my immediate though: “must’ve ran `cask-tasting` again”. Yep.

**Comment by vitorgalvao** [comment]
Merged as c7ea640b5bdd658c1bddae8692619cbe6c9df015.

**Comment by alebcay** [comment]
Indeed. I also gave your `cask-repair` script a try and was thinking, "This is so easy it's almost addictive."

**Comment by vitorgalvao** [comment]
I agree it is a bit addictive, yes, particularly when used with `cask-tasting`, which is actually a big part of it.

Back when you ran `cask-tasting` more regularly, I used to check back almost every day and loop through the file of checksum errors, running `cask-repair` on each of them.

**Comment by alebcay** [comment]
Moved my computer around the house a bit and found that I can get about 4x as fast connection speeds as before, so I can probably run checks more frequently now.

**Pull request closed without merging**
