### PR TITLE
Fixed the FreeCAD Cask to the latest stable

### PR DESCRIPTION
**Pull request by Foadsf**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by slokhorst** [comment]
Why revert this? Upstream [says](https://github.com/FreeCAD/FreeCAD/releases/tag/0.18.3):

> NOTE: For OSX it is recommended to use the 0.19_dev builds. https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre
> FreeCAD 0.19.x has been ported to QT5.9 and QTWebEngine which solves some OSX specific issues.

**Comment by Foadsf** [comment]
@slokhorst because it is not a stable release yet. We could have a freecad_pre formula as the HomeBrew Cask policies imply.

**Comment by brainstorm** [comment]
@slokhorst I'm also against reverting back to 0.18, @Foadsf, can you put together the 0.19 cask too, please?

**Comment by Foadsf** [comment]
@brainstorm sure, if I could figure out how I can add a cask to the [homebrew-cask-versions](https://github.com/Homebrew/homebrew-cask-versions) as instructed [here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#unofficial-vendorless-and-walled-builds).

**Comment by brainstorm** [comment]
@Foadsf Luckily there's prior art on that cask!:

https://github.com/Homebrew/homebrew-cask-versions/pull/7047

Could you please get 0.19 in place? I'm trying to reproduce a bug I reported upstream and would need newer 0.19.x versions:

https://github.com/FreeCAD/FreeCAD/pull/2430#issuecomment-546614741

Thanks in advance Foad!

**Pull request merged**
