### PR TITLE
Update pgweb to 0.9.5

### PR DESCRIPTION
**Pull request by sosedoff**
Updates pgweb to latest release: 0.9.5
Release notes: https://github.com/sosedoff/pgweb/releases/tag/v0.9.5

### CODE REVIEW

**Comment by adidalal** [comment]
Also, check out `cask-repair`, it makes Cask updates like this quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

**Comment by sosedoff** [comment]
Thanks, i noticed the `cask-repair` but i dont use `hub` tool so for me this manual change was pretty easy

**Comment by adidalal** [comment]
hub just makes the initial fork dead easy, if you're comfortable adding in a remote url pointing to your manually forked copy of HBC (directions should be right under the automated update directions), it'll work just fine.

**Comment by sosedoff** [comment]
Cool, will try that next time i have an update to pgweb!

**Pull request merged**
