### PR TITLE
Add Firestorm viewer for OpenSim v6.0.2.56680

### PR DESCRIPTION
**Pull request by kiendang**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

This version has support for OpenSim while the existing one in homebrew-cask only has support for Second Life. Tried submitting to cask-versions but was told to submit here instead homebrew/homebrew-cask-versions#8922.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> This version has support for OpenSim while the existing one in homebrew-cask only has support for Second Life.

So this one has support for both, while the one present only has support for one, yet this one is an earlier version?

**Comment by kiendang** [comment]
Sorry my bad this one only has support for OpenSim while the existing one only has support for Second Life.
https://www.firestormviewer.org/choose-your-platform/
https://www.firestormviewer.org/second-life-opensim-are-no-longer-joined-at-the-hip/

**Comment by vitorgalvao** [comment]
And the only thing that changes between them is the version? That’s absurd, confusing, and doesn’t fit at all into our naming model. Considering the lack of popularity of this software, I’m more inclined to remove the cask we have than include a new one.

```
firestorm
30 days: 12 (#2777)
90 days: 31 (#2782)
365 days: 92 (#3028)
Age: 272 days (added 2019, July 17)
```

**Comment by kiendang** [comment]
If I understand correctly, they are maintaining two releases separately, 1 for OpenSim, 1 for SL. Doesn't mean the OpenSim version is just and older version of the SL version. The download urls are different too, Phoenix-**FirestormOS**-Releasex64_... vs Phoenix-**Firestorm**-Releasex64_. Doesn't seem confusing to me but I understand decision's yours.

**Comment by vitorgalvao** [comment]
The issue is that this isn’t following the token reference.

**Review by vitorgalvao — APPROVED** [review]

**Comment by kiendang** [comment]
ah my bad. sorry for that.

**Pull request merged**
