### PR TITLE
updated 1password (6.1)

### PR DESCRIPTION
**Pull request by JeffreyBytes**

### CODE REVIEW

**Comment by cameronmalek** [comment]
Wow! Beat me to it by 10 seconds! Thanks.

**Comment by spaz926** [comment]
@cameronmalek haha. I just got the update notification on the app. Would have gotten the pull request even sooner if I knew how to use the damn cask-repair without reading through instructions. :stuck_out_tongue:

**Comment by vitorgalvao** [comment]
> Would have gotten the pull request even sooner if I knew how to use the damn cask-repair without reading through instructions.

If you feel like anything specifically could be improved in that regard, please let us know.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 042dd96774f93e8781d56bad751a9f4a760b100f to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
