### PR TITLE
Update cleanmymac to 4.0.1,1536142248

### PR DESCRIPTION
**Pull request by toonetown**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Review by vitorgalvao — COMMENTED** [review]
`uninstall` uses `version.major` extensively. It’s likely to require a revamp.

**Comment by toonetown** [comment]
In my testing, all the files that get written to `/Library/` are named with version "4"...only the app name itself is changed to be named `CleanMyMac X.app` instead of `version.major`

**Comment by toonetown** [comment]
Also, it is my understanding this is an update to the current "CleanMyMac" product...I don't know that the cask should be renamed...

**Comment by core-code** [comment]
not sure on the re-naming either. its a version number, not the product name. also the real version number is 4, the 'X' is just a marketing thing.

**Comment by reitermarkus** [comment]
> the 'X' is just a marketing thing.

They should also have added a notch to their new icon while they were at it.

**Comment by core-code** [comment]
@reitermarkus ha, how true. i've actually launched that thing and was quite appalled. fascinating that this seems to be in spot 10 of the most-used mac apps (i've got some stats there).

**Comment by toonetown** [comment]
So - is there something still waiting on me for this?

**Comment by fantasticfears** [comment]
It's a new version and needs a new license. The BOM indicates the version 4. I think two casks for now would be much better.

**Comment by fantasticfears** [comment]
Good idea. For ref: https://github.com/Homebrew/homebrew-cask-versions/pull/6262

**Pull request merged**
