### PR TITLE
Meshlab: bugfixes and version bump

### PR DESCRIPTION
**Pull request by psibre**

### CODE REVIEW

**Comment by psibre** [comment]
Incidentally, I would have expected the CI server to catch this, assuming it uses the default, case-insensitive filesystem. Is it possible that Travis *doesn't actually test installing* the cask(s) modified by a pull request?

**Comment by rolandwalker** [comment]
Hi!  Thanks!

Yes, intensive testing for the currently-modified Cask is a wishlist item.  Travis is not really designed to do that: it runs the complete test suite, and is not aware of *which* Cask just got updated.  The naive approach will not work, because Travis would need to install every Cask just to complete testing.

There ought to be a way to hack such functionality reasonably well by reading the git history, but nobody has worked on it.

Your changes look good – care to squash before we merge?

**Comment by psibre** [comment]
@rolandwalker thanks, here you go!

**Comment by rolandwalker** [comment]
Much appreciated!

**Pull request merged**
