### PR TITLE
Update canary to 0.975.310,244

### PR DESCRIPTION
**Pull request by gobinathm**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as fbf39febc600bb85cf0fded4f60798fe9f876ea1. Your contribution is still credited to you.

**Comment by OranShuster** [comment]
i think the sha is wrong

`
==> Downloading https://rink.hockeyapp.net/api/2/apps/b36ac4a380ea4907940c2054f6163050/app_versions/244?format=zip
######################################################################## 100.0%
==> Verifying checksum for Cask canary
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 068bda1f98ec4b63e443c2e98352c42940b00dbab7987e8056902869bbce32bf
Actual: 3402070118f5c6cfb7c9776e602a380102a18d0b471bdd855d3aa873ead091a2
File: /Users/oranshuster/Library/Caches/Homebrew/Cask/canary--0.975.310,244
To retry an incomplete download, remove the file above.
`

**Comment by OranShuster** [comment]
i think the sha is wrong
`
[oranshuster:~] $ brew cask install canary
==> Satisfying dependencies
complete
==> Downloading https://rink.hockeyapp.net/api/2/apps/b36ac4a380ea4907940c2054f6163050/app_versions/244?format=zip
######################################################################## 100.0%
==> Verifying checksum for Cask canary
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 068bda1f98ec4b63e443c2e98352c42940b00dbab7987e8056902869bbce32bf
Actual: 3402070118f5c6cfb7c9776e602a380102a18d0b471bdd855d3aa873ead091a2
File: /Users/oranshuster/Library/Caches/Homebrew/Cask/canary--0.975.310,244
To retry an incomplete download, remove the file above.
`

**Comment by gobinathm** [comment]
Seems they have rolled back the update.  About 2-3 hrs back the version was 0.975.310,244 but now its back to the earlier one

**Comment by gobinathm** [comment]
@vitorgalvao should we roll it back ?

Ref: #33805

**Pull request closed without merging**
