### PR TITLE
Add Noise Machine formula

### PR DESCRIPTION
**Pull request by ffung**

### CODE REVIEW

**Comment by fanquake** [comment]
Can you please squash your commits

**Comment by ffung** [comment]
done

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in the below referenced pull request. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by ffung** [comment]
@vitorgalvao no problem, thanks for cleaning it up

**Pull request closed without merging**
