### PR TITLE
anytype 0.33.3

### PR DESCRIPTION
**Pull request by piijai**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by razvanazamfirei — APPROVED** [review]

**Comment by piijai** [comment]
Could the reason for the failure of the livecheck be, that the linked "latest-mac.yml" file contains sha512 hashes and not sha256 hashes?

```yaml
version: 0.33.3
files:
  - url: Anytype-0.33.3-mac-x64.zip
    sha512: SltFtNSo5D0S00QdJF5pYYsy+6bA12bkVsZI8WOsR1WvU7fbtKzuf75FhBYunwUAidts4mv499pVD+pdwDITdw==
    size: 277958462
  - url: Anytype-0.33.3-mac-arm64.zip
    sha512: H7silbl/lnjOhzkhtzNrU2xIEmw/wW13vylBKFjdRxpRDNKtrVrnnuwBSLoVLyhq5nRNZ1HSyJQxoGd9OvaXaA==
    size: 268454138
  - url: Anytype-0.33.3-mac-arm64.zip
    sha512: H7silbl/lnjOhzkhtzNrU2xIEmw/wW13vylBKFjdRxpRDNKtrVrnnuwBSLoVLyhq5nRNZ1HSyJQxoGd9OvaXaA==
    size: 268454138
  - url: Anytype-0.33.3-mac-arm64.zip
    sha512: H7silbl/lnjOhzkhtzNrU2xIEmw/wW13vylBKFjdRxpRDNKtrVrnnuwBSLoVLyhq5nRNZ1HSyJQxoGd9OvaXaA==
    size: 268454138
  - url: Anytype-0.33.3-mac-x64.dmg
    sha512: x7QzEd8hBu3GBKNq+PnYhNhhkoTza8Sw7rhxEpnLv4gB0Beoqy4tXBE6UU59QWCQ9I95HLe4XoVz336wph+r5g==
    size: 282009606
  - url: Anytype-0.33.3-mac-x64.dmg
    sha512: x7QzEd8hBu3GBKNq+PnYhNhhkoTza8Sw7rhxEpnLv4gB0Beoqy4tXBE6UU59QWCQ9I95HLe4XoVz336wph+r5g==
    size: 282009606
  - url: Anytype-0.33.3-mac-x64.dmg
    sha512: x7QzEd8hBu3GBKNq+PnYhNhhkoTza8Sw7rhxEpnLv4gB0Beoqy4tXBE6UU59QWCQ9I95HLe4XoVz336wph+r5g==
    size: 282009606
  - url: Anytype-0.33.3-mac-arm64.dmg
    sha512: l4upHUUlFpuGfHZe4LpDNXXvX1NEXmeNdhE86rGnZIXD0kisGyCoymA6C8uRSb1MxIwIq5idRczazTJlqWXbAQ==
    size: 272504179
  - url: Anytype-0.33.3-mac-arm64.dmg
    sha512: l4upHUUlFpuGfHZe4LpDNXXvX1NEXmeNdhE86rGnZIXD0kisGyCoymA6C8uRSb1MxIwIq5idRczazTJlqWXbAQ==
    size: 272504179
  - url: Anytype-0.33.3-mac-arm64.dmg
    sha512: l4upHUUlFpuGfHZe4LpDNXXvX1NEXmeNdhE86rGnZIXD0kisGyCoymA6C8uRSb1MxIwIq5idRczazTJlqWXbAQ==
    size: 272504179
path: Anytype-0.33.3-mac-x64.zip
sha512: SltFtNSo5D0S00QdJF5pYYsy+6bA12bkVsZI8WOsR1WvU7fbtKzuf75FhBYunwUAidts4mv499pVD+pdwDITdw==
releaseDate: '2023-07-19T08:26:27.633Z'
```

**Comment by krehel** [comment]
`sha512` shouldn't matter. 

It's possible the latest `.yml` file hasn't been fully distributed across their CDN.  For example when I open the link locally, I receive a `latest-mac.yml` file with version `0.33.2`, which is the same thing happening here in CI.

**Comment by piijai** [comment]
Thanks, that sounds plausible. But in this case, there is nothing we can do, to make the tests work. Actually locally I receive the latest-mac.yml with version 0.33.3.

**Comment by krehel** [comment]
I am still pulling `0.33.2` locally

**Pull request merged**
