### PR TITLE
Update hand-mirror from 1.1.2 to 1.3.1

### PR DESCRIPTION
**Pull request by tedski**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
according to the homepage this only exists in the Mac App Store now. where does the link to version 1.3.1 come from?

**Comment by tedski** [comment]
> according to the homepage this only exists in the Mac App Store now. where does the link to version 1.3.1 come from?

I reached out to the developer and asked if he could start hosting the latest versions on his site so we can properly upgrade.  I'm still working with him to provide the version number on the site so we can use appcast, but he said he will upload new versions to the same site.

**Comment by vitorgalvao** [comment]
> To be clear, the appcast stuff will be handled in a future PR.

I’d rather it be done now.

From experience, this is the kind of thing the developer will either drag on or forget to do. Without an appcast or a page to download there’s no way for us to know when the app is updated (checking the MAS is not a reasonable solution, especially if those aren’t updated in tandem).

The cask isn’t particularly popular now, so if we’re going to remove it, it should be sooner rather than later.

Let’s give it a month to avoid disruption. If the situation hasn’t changed by then, removing the cask will be sensible. That doesn’t mean it will be removed forever; if the problem gets correct after it’s removed, it can be resubmitted.

I’ve merged this for now since it’s an update, but [the removal PR is ready](https://github.com/Homebrew/homebrew-cask/pull/88059).

```
hand-mirror
30 days: 8 (#2698)
90 days: 31 (#2491)
365 days: 73 (#3544)
Age: 154 days (added 2020, March 23)
```

**Comment by tedski** [comment]
Thanks, @vitorgalvao.  I feel that's a perfectly reasonable path forward.  I will contact the developer and set the appropriate sense of urgency.

**Comment by vitorgalvao** [comment]
One day early, but I doubt it makes a difference. [Removing it](https://github.com/Homebrew/homebrew-cask/pull/89712).

**Comment by tedski** [comment]
Agreed, @vitorgalvao.  I appreciate you following up with @rafaelconde about this.  It's unfortunate we weren't able to get the appcast stuff figured out.  I apologize for the inconvenience and toil here.

**Comment by vitorgalvao** [comment]
> I appreciate you following up with @rafaelconde about this.

[Credit for that](https://github.com/Homebrew/homebrew-cask/pull/88059#issuecomment-695771157) goes to @core-code.

> I apologize for the inconvenience and toil here.

Nothing to apologise for, you were an exemplary contributor. Thank you for reaching out upstream and working with us on this.

**Pull request merged**
