### PR TITLE
Add kubenav.app v3.5.0

### PR DESCRIPTION
**Pull request by tuxpeople**
New cask for kubenav.app

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [X] `brew audit --new-cask <cask>` worked successfully.
- [X] `brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
This will need a zap stanza.

**Comment by tuxpeople** [comment]
@SMillerDev thanks for your fast feedback!

My understanding was, that the zap stanza is for removing file which are beeing created by the app while using it? Eg. caches, settings etc. But this app has no such files. At least as far as I can tell. It's just the `kubenav.app` and that one gets removed when uninstalling the cask. But I can add a zap stanza including the `kubenav.app`, no problem.

**Comment by tuxpeople** [comment]
@SMillerDev I now also tried the createzap-Tool:

```
$ brew createzap kubenav
No kubenav settings found.
```

Please confirm the App-Bundle itself must also be added to the zap stanza.

**Comment by SMillerDev** [comment]
> Please confirm the App-Bundle itself must also be added to the zap stanza.

It shouldn't so this version is fine then

**Comment by tuxpeople** [comment]
@SMillerDev thanks! Another question: They also have a mac arm binary. Is there already a way to add casks for arm macs?

**Comment by SMillerDev** [comment]
> They also have a mac arm binary. Is there already a way to add casks for arm macs?

Yes, see https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/figma.rb for an example

**Review by cho-m — APPROVED** [review]
Thanks for your contribution, @tuxpeople

**Pull request merged**
