### PR TITLE
Add Cozy Drive cask v3.7.10

### PR DESCRIPTION
**Pull request by slaanesh**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[closed issues]: https://github.com/Homebrew/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Welcome and thank you.

**Comment by slaanesh** [comment]
👍

**Comment by ramet** [comment]
could you update the checksum please ?
```
Error: Checksum for Cask 'cozy-drive' does not match.

Expected: 6b4804c033ef74b1b12cef0b46ca2df51d793ad669ae050a228f41619c245fd7
Actual:   a3243c970d48bbceed55f2c3b207129ee21bc4c47d89b93061b7afdf616c863a
File:     /Users/ramet/Library/Caches/Homebrew/Cask/cozy-drive--3.7.10
```

**Comment by slaanesh** [comment]
fixed with #49393

**Pull request merged**
