### PR TITLE
Update forticlient from 6.4.2.1305 to 6.4.3.1325

### PR DESCRIPTION
**Pull request by oaoit**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Review by vitorgalvao — DISMISSED** [review]

**Comment by oaoit** [comment]
I found uninstall forticlient need 'killall -9 FortiClientAgent' before,I have not idea to do.Is anybody can do this?

**Comment by miccal** [comment]
> I found uninstall forticlient need 'killall -9 FortiClientAgent' before,I have not idea to do.Is anybody can do this?

It seems that this is not the problem:
```
==> Quitting application 'com.fortinet.FortiClientAgent'...
Application 'com.fortinet.FortiClientAgent' quit successfully.
```
The problem is:
```
==> Removing files:
/Applications/FortiClient.app
rm: /Applications/FortiClient.app/Contents: Operation not permitted
rm: /Applications/FortiClient.app: Operation not permitted
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --` exited with 1. Here's the output:
rm: /Applications/FortiClient.app/Contents: Operation not permitted
rm: /Applications/FortiClient.app: Operation not permitted
```

**Comment by oaoit** [comment]
> > I found uninstall forticlient need 'killall -9 FortiClientAgent' before,I have not idea to do.Is anybody can do this?
> 
> It seems that this is not the problem:
> 
> ```
> ==> Quitting application 'com.fortinet.FortiClientAgent'...
> Application 'com.fortinet.FortiClientAgent' quit successfully.
> ```
> 
> The problem is:
> 
> ```
> ==> Removing files:
> /Applications/FortiClient.app
> rm: /Applications/FortiClient.app/Contents: Operation not permitted
> rm: /Applications/FortiClient.app: Operation not permitted
> Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/xargs -0 -- /bin/rm -r -f --` exited with 1. Here's the output:
> rm: /Applications/FortiClient.app/Contents: Operation not permitted
> rm: /Applications/FortiClient.app: Operation not permitted
> ```

The operation can’t be completed because the item “FortiClient.app” is locked.

**Comment by miccal** [comment]
Finally :)

**Review by miccal — APPROVED** [review]

**Pull request merged**
