### PR TITLE
Update busycontacts

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@suschizu @core-code is the `sha` consistently changing on this?

**Comment by core-code** [comment]
yes, thats why we had the bundle version in the version stanza but this was removed by @Revisor01 in https://github.com/Homebrew/homebrew-cask/pull/71220 ;-(

**Comment by ran-dall** [comment]
Can you submit a PR and re-add it? I think it's going to have to be required for this cask.

**Comment by core-code** [comment]
sure no problem

Submitted (https://github.com/Homebrew/homebrew-cask/pull/75299)

**Pull request merged**
