### PR TITLE
Update dbeaver-enterprise appcast

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
The old appcast has `5.1.0` as the latest ( https://dbeaver.com/product/version.xml ).

**Comment by vitorgalvao** [comment]
I’d rather wait a few more days to see if it’s updated, structured document appcasts are more reliable to parse.

**Comment by commitay** [comment]
The current appcast is correct, seems they reverted to 5.1.0.

```
$ curl -I https://dbeaver.com/files/dbeaver-ee-latest-macos.dmg
HTTP/1.1 302 Found
Date: Wed, 20 Jun 2018 21:35:47 GMT
Server: Apache/2.4.18 (Ubuntu)
Location: https://dbeaver.com/files/5.1.0/dbeaver-ee-5.1.0-macos.dmg
Content-Type: text/html; charset=iso-8859-1
```

**Comment by brianmorton** [comment]
To be fair, it may be correct now (I just checked and indeed it is now offering `5.1.0` as latest) however earlier it was `5.1.1` and the appcast was either outdated or reverted sooner than the site - hard to say which without contacting them.

**Comment by commitay** [comment]
Reverted to `5.1.0` https://github.com/Homebrew/homebrew-cask/pull/48754

Thanks for bringing this to our attention @brianmorton!

**Comment by vitorgalvao** [comment]
This means we can still trust the current appcast, which is good news.

**Pull request closed without merging**
