### PR TITLE
Update cisdem-document-reader from 5.1.0 to 5.0.0

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
[What changed](https://github.com/Homebrew/homebrew-cask/pull/75564#issuecomment-575178672)?

**Comment by core-code** [comment]
sorry. i forgot it is the same cask.

**Comment by core-code** [comment]
still, its weird i *still* get another checksum here.

**Comment by vitorgalvao** [comment]
Just rechecked and I continue to get the current one.

My bet would be on a CDN mistake. I remember we once had a cask (Visual Studio Code, if I recall correctly) whose URL would consistently give different shasums (one of two) to different people. Someone contacted them and the issue was with having different builds (not on purpose) on different data centres.

**Pull request closed without merging**
