### PR TITLE
Update opensc from 0.19.0 to 0.20.0

### PR DESCRIPTION
**Pull request by liamdawson**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by liamdawson** [comment]
There are macOS installer related changes, but I'm trusting that the default behaviour is desirable.

From the release notes:

```
macOS installer

    Add installer option to deselect tokend (#1607)
    Make OpenSCToken available on 10.12+ and the default on 10.15+ (2017626)
```

**Comment by vitorgalvao** [comment]
The uninstaller script seems to no longer be enough to uninstall the app. Is there anything else?

**Comment by liamdawson** [comment]
Yeah, some changes around those new services in the logs, seems odd that they weren't cleaned up. (I'm not familiar with the project proper)

Would it be sufficient to add the references the `ci` step suggests?

**Comment by vitorgalvao** [comment]
> Would it be sufficient to add the references the `ci` step suggests?

Yes, but it’d be wise to check the uninstall script they provide. Perhaps it has changed location.

**Comment by liamdawson** [comment]
Script is in the expected location, looks like it wasn't updated for this release. References a package that used to be installed, but isn't any more, among the other build errors. Will open an issue upstream.

**Comment by vitorgalvao** [comment]
> Will open an issue upstream.

Thank you, I appreciate it. That’s the correct approach.

**Comment by liamdawson** [comment]
https://github.com/OpenSC/OpenSC/issues/1898

**Comment by frankmorgner** [comment]
homebrew has all the dependencies, why don't you build it from source?

**Comment by core-code** [comment]
is there any progress here?

**Comment by core-code** [comment]
an opensc update to 0.20.0 has already been merged

https://github.com/Homebrew/homebrew-cask/pull/78228

can we close this or is there still anything to improve?

**Comment by vitorgalvao** [comment]
> can we close this or is there still anything to improve?

I’d say we can close this one.

**Pull request closed without merging**
