### PR TITLE
endnote 21

### PR DESCRIPTION
**Pull request by BastianZim**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@BastianZim Unfortunately we aren't able to effectively use `livecheck` from the support URL because the page is hydrated with javascript. This means that the version served to `curl` doesn't include the version data. So we would need to find another livecheck source.

**Comment by BastianZim** [comment]
Hmm, this is the official site for downloads according to their help documents so that might be more difficult. 
I assume, leaving it out is not an option?

**Comment by razvanazamfirei** [comment]
This is a livecheck url for Endnote 20: `https://download.endnote.com/updates/20.0/EN20MacUpdates.xml` 
Version 21 is wrong as the actual version from the installer is `21.0.0.19023`
The Endnote 21 url will likely be similar and can be captured when the app checks for updates, but I haven't upgraded yet.

**Comment by BastianZim** [comment]
Thanks for investigating this. So I guess best way forward is wait until that is released?

**Comment by razvanazamfirei** [comment]
This should work for now, but once Endnote21 starts receiving updates, the url will need to change.

**Review by razvanazamfirei — APPROVED** [review]

**Comment by BastianZim** [comment]
Thanks!

**Pull request merged**
