### PR TITLE
Add Rewind

### PR DESCRIPTION
**Pull request by nihaals**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by nihaals** [comment]
Failed due to being Apple silicon only

**Comment by miccal** [comment]
> Failed due to being Apple silicon only

The `.app` is a Universal binary, so it is not arm-only.

Screenshot 2023-03-16 at 11 09 46

**Comment by nihaals** [comment]
> > Failed due to being Apple silicon only
> 
> The `.app` is a Universal binary, so it is not arm-only.
> 
> Screenshot 2023-03-16 at 11 09 46

I noticed the same thing but they [officially and explicitly say](https://help.rewind.ai/en/articles/6705951-what-hardware-is-required-to-run-rewind) they only support Apple silicon and I've seen screenshots of the pkg failing on Intel Macs (although this was on old versions and I haven't been able to test the cask myself on an Intel Mac).

**Comment by miccal** [comment]
The version has changed five times since you opened this PR!

**Comment by bevanjkay** [comment]
The `sparkle` feed provides a versioned download URL - https://updates.rewind.ai/builds/main/b8514.1-main-e1b1c5a.zip - which contains the `.app` instead of the `.pkg`.
I'm not sure if the `.pkg` affords any extra that the versioned does not. But if they result in the same files installed, then the versioned download would be preferred.

**Comment by nihaals** [comment]
> The version has changed five times since you opened this PR!

That was something I wanted to mention, should this be `:latest`? They seem to deploy every time there's a commit to `main` and some days there can be a lot of updates, I would definitely say it's unreasonable to expect Homebrew to stay up to date based on the update rate I've seen for the past few months.

> The `sparkle` feed provides a versioned download URL - https://updates.rewind.ai/builds/main/b8514.1-main-e1b1c5a.zip - which contains the `.app` instead of the `.pkg`.
> 
> I'm not sure if the `.pkg` affords any extra that the versioned does not. But if they result in the same files installed, then the versioned download would be preferred.

I had a similar thought but assumed the pkg would be preferred due to being the official installation method (and could be updated in the future). There is a postinstall script but when I looked at it I was only checking it opening after install. I'm not very experienced with pkgs so it would be good to get someone else's thoughts on what the pkg does other than copying and opening the app. The main thing I would be weary of is the pkg getting updated in the future, but right now I can't think of anything the app does which would require a pkg over a simple app.

**Comment by p-linnane** [comment]
We have historically dropped support for these kinds of casks that update with every commit (see https://github.com/Homebrew/homebrew-cask/pull/135413). If that is how this application operates, I am not in favor of adding it to `homebrew-cask`.

**Comment by nihaals** [comment]
Wouldn't this cask be fairly stable with `:latest` and match the example in the cookbook of "for example, [`chromium.rb`](https://github.com/Homebrew/homebrew-cask/blob/f3e9de24ba57d7b1d949132504e581759725d0c5/Casks/chromium.rb#L4) releases multiple versions a day"? What would be the disadvantage of having the cask in the repo? Since the cask is `auto_updates` it feels like having it in the repo would still provide the value of easy install/uninstall and `--zap` while not needing many changes over time.

**Comment by bevanjkay** [comment]
If this cask is to be added, `:latest` would be the best option. It is worth noting that the behaviour for `:latest` has changed in the last few months, when installed, a `shasum` is recorded, and then if `--greedy` is passed to `brew upgrade` the cask will be downloaded and the `shasum` compared with the installed version.

For the cask to have `:latest` as version, we would need to also utilise an unversioned url.

**Comment by razvanazamfirei** [comment]
The download link has changed to `https://download.rewind.ai/Rewind.dmg`. I've updated the cask and it passes local audits on arm. My questions is if the uninstall stanza is still required.

**Comment by razvanazamfirei** [comment]
For checks without the arch limitations: https://github.com/Homebrew/homebrew-cask/pull/144244/checks

**Comment by SMillerDev** [comment]
This looks to me like it's changing way too fast to be maintainable here. Maybe a tap would be a better fit. Especially the changing download location is a big red flag to me.

**Comment by razvanazamfirei** [comment]
Agreed, @SMillerDev. @nihaals, Thank you for opening the PR and your work on this. As it stands, the unpredictability in development, as well as the potential maintenance effort required to address the changes suggest that perhaps now is not the best time for the cask to be included. Putting aside the frequent version changes, silently changing the download link and format in which the app is delivered are red flags (they lead to signature verification failures in the past).

If the development trajectory becomes more predictable, we're more than happy to take another look. In the meantime, you can consider creating a [tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap). The cask will require minimal modifications.

Thank you again for your contribution!

**Comment by nihaals** [comment]
And thanks for spotting the switch to a dmg, I wouldn't have noticed and it feels much nicer than using a pkg.

**Comment by nihaals** [comment]
@unitof I did make a [tap](https://github.com/nihaals/homebrew-rewind), although I didn't try to make it as user-friendly and public as possible and am mostly using it for personal use. I knew about the appcast and we spoke about it above. Now that Rewind uses a dmg, using the URLs in the appcast would be fine, but it wouldn't be viable to keep it up to date in Homwbrew (sometimes they merge multiple times in an hour) and I wanted to keep it as close to a Homebrew cask as possible (so avoiding things like using GitHub Actions to automatically update it every x minutes). It sounds like Rewind is currently working towards 1.0 which could reduce the number of releases and make it more maintainable though so I think it would be best to see what happens.

**Comment by unitof** [comment]
@nihaals Ah! My bad, missed you'd had the appcast earlier. Makes sense, thanks!

**Pull request closed without merging**
