### PR TITLE
add valid sparkle appcasts for casks with missing appcasts

### PR DESCRIPTION
**Pull request by core-code**
as per "discussion" (well, just me talking;) here ( https://github.com/Homebrew/homebrew-cask/issues/47351 ) there are a lot of casts that have no 'appcast' stanza although there is a valid sparkle appcast for them. i've tried to add them all at once.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Many of these require an update to `version` and `sha256` (no longer `:latest` and `:no_check`).

**Comment by core-code** [comment]
well, the appcasts don't hurt even if you don't have a version ;)

**Comment by core-code** [comment]
also, feel free to merge just those that are currently versioned

**Comment by vitorgalvao** [comment]
> well, the appcasts don't hurt even if you don't have a version

True, but I’d prefer to have everything done right from the start. Otherwise we’ll eventually get bad submissions that’ll use some of these we haven’t updated yet as a base.

**Comment by core-code** [comment]
of course i also prefer things to be done right, but, well, sorry but i wont update 60 casks to be versioned.

i'd recommend to either merge all of them (so that the appcasts are there once they are upgraded)
or merge just those that already are versioned to comply with current rules ;)

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/issues/54811

**Comment by core-code** [comment]
thanks ;) i will see if i can do some of  those when i have a few minutes

**Pull request merged**
