### PR TITLE
virtualbox: add conflict with virtualbox-beta

### PR DESCRIPTION
**Pull request by yurikoles**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by yurikoles** [comment]
Seems to be some problem with CI. I see that uninstall tool is there and it works fine locally. `/usr/local/Caskroom/virtualbox/5.2.18,124319/VirtualBox_Uninstall.tool`

**Comment by yurikoles** [comment]
I had tried to specify full path via `executable: "#{staged_path}/VirtualBox_Uninstall.tool",`, but CI still can't find it, I give up. 

Should I rise a ticket for this?

**Comment by commitay** [comment]
No, it's a CI issue with installing kexts. Please revert the changes to `uninstall`.

**Comment by yurikoles** [comment]
@commitay done

**Pull request merged**
