### PR TITLE
font-ibm-plex-*: 1.0.0 (new casks)

### PR DESCRIPTION
**Pull request by valentinegb**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

The upstream recently changed how it organizes its releases, this pull request reflects that.

### CODE REVIEW

**Comment by valentinegb** [comment]
If I'm not mistaken, IBM Plex has some ligatures, so would it be better to install the OTF files which support ligatures instead of  the TTF files which don't?

**Comment by bevanjkay** [comment]
Fonts from the Google Fonts repository are managed automatically by a script, to ease the maintenance burden of having many many fonts in `homebrew-cask`. Is there a specific reason these changes are necessary?

**Comment by valentinegb** [comment]
I was not aware of this, sorry. However, these casks were previously unversioned when downloading from Google Fonts and I feel that being versioned is generally better than not. (Plus the added integrity of having a sha256.) Also, font-ibm-plex previously *was* downloading from GitHub, I was only continuing this while reacting to the fact that each font variation was given separate releases.

**Comment by bevanjkay** [comment]
Ok, I think I'm okay with merging this and using the vendor as the source. My primary concern is that users with the `font-ibm-plex` cask installed will no longer be able to manage the install with Homebrew, however I'm not sure that migrating to a specific variant makes sense either. 

A change that's required across the board here is that we don't use `url :stable` for `livecheck` in `homebrew-cask`. Instead `url :url` should be used.

**Comment by valentinegb** [comment]
> A change that's required across the board here is that we don't use `url :stable` for `livecheck` in `homebrew-cask`. Instead `url :url` should be used.

Oh whoops, okay that's been fixed

**Comment by valentinegb** [comment]
> My primary concern is that users with the `font-ibm-plex` cask installed will no longer be able to manage the install with Homebrew, however I'm not sure that migrating to a specific variant makes sense either.

Yeah I'm not really sure how to go about that either. `font-ibm-plex` pretty much has to go since the upstream simply doesn't distribute all variants together anymore, although I suppose maybe we could just have it depend on all the other casks and then do nothing? I'm not sure if that's at all normal for a cask, though.

**Comment by bevanjkay** [comment]
I think in the case of `font-ibm-plex` let's keep it but deprecate it with a reason like "is now distributed with the font variants as individual packages"

**Comment by valentinegb** [comment]
Since the versioning scheme changed, `font-ibm-plex`'s `livecheck` doesn't work anymore. Should it just be removed, since it's not expected for there to *be* any new versions?

**Comment by bevanjkay** [comment]
Yeah it can be removed.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
