### PR TITLE
Update Firefox from 95.0.2 to 96.0

### PR DESCRIPTION
**Pull request by brianvanburken**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by brianvanburken** [comment]
It seems I'm a bit too early with this PR. The [changelog](https://www.mozilla.org/en-US/firefox/96.0/releasenotes/) hasn't been updated yet. Also, locally all steps succeed, but the CI `livecheck` fails.

**Comment by bevanjkay** [comment]
@brianvanburken We will need to wait until the livecheck passes, you can check this locally with `brew livecheck firefox` or by including `--online` when you run `brew audit firefox --online` (this is what CI uses) - but in this instance it will download all the files in the update (which may be cached for you), so may not be very economical.

**Comment by brianvanburken** [comment]
@bevanjkay Thank you for the information.  I updated the cask using `update_multilangual_casks` and ran the steps mentioned in the PR template. 

I guess, we will have to wait a bit before trying again with the CI step.

**Comment by bevanjkay** [comment]
@brianvanburken Firefox is on my livecheck watchlist so if I notice that `96.0` goes live I'll restart CI.

**Comment by default50** [comment]
I think it's live: https://hg.mozilla.org/releases/mozilla-release/rev/8fae7cc94cfb

😄

**Comment by brianvanburken** [comment]
Yes, it is finally live. I checked, and the hashes are still correct. The PR is ready to be merged 🎉

**Pull request merged**
