### PR TITLE
Add Crunch v0.9.0

### PR DESCRIPTION
**Pull request by chrissimpkins**
#### Adding a new cask
- [X] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [X] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [X] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [X] Commit message includes cask’s name.
- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` left no offenses.
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 69ba7565052b11d72eb6d9d22a61dc7a198c017a. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by chrissimpkins** [comment]
Thank you very much Vítor!  I really appreciate it.  With the version replacement string in the URL I can now simply update the version field and the SHA 256 hash field anytime there is an update?

**Comment by adidalal** [comment]
@chrissimpkins Correct.

Check out `cask-repair`, it makes Cask updates like that quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

ie. After you release a new version, simply run `cask-repair -v {{new_version} crunch`, and it'll automatically make the changes, create the PR, and fill out the template for you!

**Comment by chrissimpkins** [comment]
@adidalal 👍  thank you very much for all of the help!!

**Comment by chrissimpkins** [comment]
https://github.com/vitorgalvao/tiny-scripts/issues/124

**Pull request closed without merging**
