### PR TITLE
Angband updated to 4.0.1 

### PR DESCRIPTION
**Pull request by stevehedrick**
Updating the Angband cask to 4.0.1 from 4.0.0.  

URL pathing changed again, so had to modify that as well.

### CODE REVIEW

**Comment by stevehedrick** [comment]
Changed as requested.

**Comment by Ngrd** [comment]
Looks good, then. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git) and @mention me after?

**Comment by stevehedrick** [comment]
@Ngrd All squashed.  Let me know if there's anything else needing changed.

**Comment by Ngrd** [comment]
Everything looks good, thank you! :+1:

It was merged directly as c0724cd8815efed92944a74724327b4b05177d7a to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
