### PR TITLE
Added HappyMac

### PR DESCRIPTION
**Pull request by youngcm2**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by miccal** [comment]
@reitermarkus sorry to bother you, but this should be a warning, not an error, [should it not?](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/audit.rb#L401)
```
Error: audit failed for casks: happymac
audit for happymac: failed
 - cask token mentions platform
Error: cask token mentions platform
```

**Comment by reitermarkus** [comment]
It's an error for new casks, since `--new-cask` implies `--strict`, which treats warnings as errors.

**Comment by miccal** [comment]
> It's an error for new casks, since `--new-cask` implies `--strict`, which treats warnings as errors.

Ah, thank you for the explanation.

**Comment by miccal** [comment]
So what would be the best way forward regarding the `audit --strict` error, perhaps adding an `ALLOWLIST` to [`shared_audits.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/shared_audits.rb)?

**Comment by claui** [comment]
> perhaps adding an `ALLOWLIST` to [`shared_audits.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/shared_audits.rb)?

@miccal If the error appears only in new-cask audits, what effect would an allowlist entry even have?

**Comment by miccal** [comment]
> > perhaps adding an `ALLOWLIST` to [`shared_audits.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/shared_audits.rb)?
> 
> @miccal If the error appears only in new-cask audits, what effect would an allowlist entry even have?

Good point.

**Comment by miccal** [comment]
Thank you @youngcm2.

**Review by miccal — APPROVED** [review]

**Pull request merged**
