### PR TITLE
Add Nifty.app v3.15.2

### PR DESCRIPTION
**Pull request by s3i7h**
The official macOS app for https://niftypm.com

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by miccal** [comment]
@ran-dall and @core-code you two are _nifty_ (get it :wink:) with `appcast`'s, I have not seen the following output before:
```
-bash-5.0.17- /Users/miccal (29) [> "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/developer/bin/find-appcast" /Users/miccal/Downloads/Nifty.app 
Looking for Sparkle appcast… Not found.
Looking for electron-builder appcast… Not found.

An "app-update.yml" file was found, but we could not parse it.
Please report this on https://github.com/Homebrew/homebrew-cask/
Provide this info:

owner: creative360
repo: nifty-website
provider: github
updaterCacheDirName: nifty-updater
```

**Comment by core-code** [comment]
i think @vitorgalvao can help best here since he has written “find-appcast”

**Comment by miccal** [comment]
Ah, looking at the code there is an `appcast` in the `app` that points to `https://github.com/creative360/nifty-website/`, which does not exist (but probably did before, looking at `https://github.com/creative360`).

**Comment by core-code** [comment]
thats what i guessed too, find-appcast did find out the correct URL but discarded it because the file has been removed and is no longer online

**Comment by miccal** [comment]
@yu-ichiro since the `url` is un-versioned and there is no suitable `appcast` this Cask should use `version :latest` and `sha256 :no_check`.

**Comment by yu-ichiro** [comment]
@miccal got it! will fix it

**Comment by vitorgalvao** [comment]
> Ah, looking at the code there is an `appcast` in the `app` that points to `https://github.com/creative360/nifty-website`

Were you able to find that just by inspecting the app? If so, what specifically have you done?

We’re not entirely sure how `electron-builder` puts together the information in `app-update.yml`, we just know that it does (and it even makes the file if the app hasn’t implemented any auto-update functionality).

So the way `find-appcast` works for those is by [making guesses](https://github.com/Homebrew/homebrew-cask/blob/master/developer/bin/find-appcast#L58L68) and check if any of those exists online. If any does, it’s returned; if none do, it may be there’s a pattern we’re not yet familiar with, hence output the message you saw.

**Comment by miccal** [comment]
> Were you able to find that just by inspecting the app? If so, what specifically have you done?

I meant I looked at the `find-appcast` code, in particular:
```
[SNIP]
  owner = data['owner']
[SNIP]
  repo = data['repo']
[SNIP]
    "https://github.com/#{owner}/#{repo}/releases.atom",
[SNIP]
```

**Comment by vitorgalvao** [comment]
> so I thought that something inside the `app` _possibly_ points to `https://github.com/creative360/nifty-website`, which _may_ have existed as some stage since `https://github.com/creative360` shows the Nifty logo.

I think there’s a possibility it exists but is a private repo.

**Pull request merged**
