### PR TITLE
Add opentx companion

### PR DESCRIPTION
**Pull request by alxrey**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @alxrey.

@vitorgalvao should this be in `homebrew-cask-drivers`?

**Comment by alxrey** [comment]
> Thank you for your contribution to `homebrew-cask` @alxrey.

You're welcome. To be honest, I was astonished to see that it didn't already exist.

> @vitorgalvao should this be in `homebrew-cask-drivers`?

I asked myself the question during a long time. It's a little bit like an IDE for microcontroller programmation. It's usable without the peripheral (programme creation, simulation, adjustment of settings, ...). But finally it's destined to be implemented in a peripheral. So ... I let you see.

**Comment by vitorgalvao** [comment]
> It's usable without the peripheral

But is it *useful* without it? [That’s the question we ask](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Casks.md#finding-a-home-for-your-cask).

Seems like this should be in the drivers repo, yes. But the cask already looks good, so it’s just a matter of submitting it there and merging.

Thank you, and welcome!

**Comment by alxrey** [comment]
@vitorgalvao Is it wanted that you closed the PR without merge it ?

**Comment by vitorgalvao** [comment]
Yes. Please submit to [homebrew/cask-drivers](https://github.com/Homebrew/homebrew-cask-drivers).

**Comment by alxrey** [comment]
👍  okay sorry, I didn't understand.

**Pull request closed without merging**
