### PR TITLE
Update google-earth-pro from 7.3.2.5776 to 7.3.3.7673

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@core-code @suschizu Do you understand why Travis is failing?

**Comment by core-code** [comment]
no idea sorry

**Comment by suschizu** [comment]
not sure if travis is missing these two entries(?) … but I've never seen brackets in uninstall launchctl 
com.google.keystone.agent (com.google.keystone.system.agent)
com.google.keystone.xpcservice (com.google.keystone.system.xpcservice)

**Comment by ran-dall** [comment]
@suschizu I put them separately because I saw `com.google.keystone.agent` and `com.google.keystone.system.agent`where already in there but separated.

@vitorgalvao I am missing something?

**Comment by vitorgalvao** [comment]
Tested in a VM, and those seem to be correct. CI has never been too reliable regarding launchd jobs, I’m afraid. No idea why.

**Pull request merged**
