### PR TITLE
Fixed puppet cask

### PR DESCRIPTION
**Pull request by bcomnes**
Puppet was crashing when it couldn't find facter.  This fixes the dep chain.

### CODE REVIEW

**Comment by ndr-qef** [comment]
Is Facter always required for Puppet to work, or does it depend on setup? I seem unable to confirm the former case.

**Comment by vitorgalvao** [comment]
@ndr-qef Did a quick test on a VM, and it seems to be needed for launching at all.

@bcomnes Please set `depends_on` as the last line (before `end`, naturally). You’re also updating an old version of the cask, hence the merge conflict.

**Comment by bcomnes** [comment]
Its not needed for installation, but running `puppet` errors out without facter.  Make `facter` a recommended dependency might be better instead.  

Sorry about the conflict, drove a little to fast on this drive by PR.  Fixing.

**Comment by vitorgalvao** [comment]
> Make `facter` a recommended dependency

We can’t, as we don’t support that.

However, what good does it do for it to install if it can’t be ran afterwards? I see no issue with having the installation of one depending on the other, for this purpose.

**Comment by bcomnes** [comment]
Ok I think that clears things up.

**Comment by ndr-qef** [comment]
Thanks for clarifying.

**Pull request merged**
