### PR TITLE
Add Zappy.app 1.3.1

### PR DESCRIPTION
**Pull request by saschabratton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

### CODE REVIEW

**Comment by vladimyr** [comment]
Please merge this first: https://github.com/saschabratton/homebrew-cask/pull/1

**Comment by saschabratton** [comment]
@vladimyr I merged your commit, but seems to fail on CI check.

**Comment by vladimyr** [comment]
Github actions CI _chokes_ on merge commits but Travis gave it green light. I guess if you really want to turn it all green you'll need to remove merge commit and cherry-pick it instead 🤔

**Comment by saschabratton** [comment]
@vladimyr Okay, that makes sense. I kind of figured the PR gets squashed on merge so it wouldn't really matter. I just forced the merge commit off the branch. Is there anything else needed to see this merged?

**Pull request merged**
