### PR TITLE
Update accurics from 1.0.22 to 1.0.23

### PR DESCRIPTION
**Pull request by williepaul**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by williepaul** [comment]
The homepage URL https://www.accurics.com/ is not reachable (HTTP status code 403)
- Failure due to cloudflare bot protection

However, I'm unsure what this error is about?
"exception while auditing accurics: no implicit conversion of nil into String"

I used brew bump-cask-pr for this PR, and the diff looks similar to previous ones... Is there a new requirement that we're missing?

Thanks,
-Willie

**Comment by miccal** [comment]
> However, I'm unsure what this error is about?
> "exception while auditing accurics: no implicit conversion of nil into String"

The `url` used by `livecheck` is also not reachable:
```
|-> curl -sLI https://downloads.accurics.com/cli/latest/accurics-cli.yml
HTTP/2 403 
content-type: application/xml
date: Fri, 13 Aug 2021 03:02:49 GMT
server: AmazonS3
x-cache: Error from cloudfront
via: 1.1 70b0c022caf458423e58ecbec40508f0.cloudfront.net (CloudFront)
x-amz-cf-pop: YVR50-C1
x-amz-cf-id: HALH891qq0upQmAgSdS6MgLFDQzHkkhIiYBIrmigH-hjVwRP2pUWZQ==

bash 5.1.8   /Users/miccal   37
|-> curl https://downloads.accurics.com/cli/latest/accurics-cli.yml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>T2E395FZ1FGRE60M</RequestId><HostId>IRApk0VtWoOvuSOsmRHb5J7uDUHrAr2TNd2llot3tpf7HV6V6BY7KyxeplMFiuP/pe3/MLQGgps=</HostId></Error>
```

@bevanjkay I cannot find an alternative `url` for `livecheck`, perhaps you can?

**Comment by williepaul** [comment]
OK the "exception while auditing accurics: no implicit conversion of nil into String" went away after I invalidated the cache for the latest folder, so all looks good there.

So it's just the usual "The homepage URL https://www.accurics.com/ is not reachable (HTTP status code 403)" being blocked due to our use of cloudflare bot protection.

**Comment by bevanjkay** [comment]
Thanks @williepaul It looks like livecheck is succeeding now.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
