### PR TITLE
openshot-video-editor: add postflight

### PR DESCRIPTION
**Pull request by miccal**
See https://github.com/OpenShot/openshot-qt/pull/4586 and https://github.com/Homebrew/discussions/discussions/2793

### CODE REVIEW

**Comment by miccal** [comment]
@hmijail are you able to confirm that this change fixes the issues you are seeing?

**Comment by hmijail** [comment]
Sorry, doesn't work. I did `brew update`, which showed the cask being updated, and `brew install openshot-video-editor`. But the resulting app still fails in the same way as before.

**Comment by neutric** [comment]
Same here, app crashes without displaying GUI.

**Comment by miccal** [comment]
Thank you both.

I have now tested this myself and tried many ways to get this to work, but all were unsuccessful.

Are you both on Monterey?

**Comment by neutric** [comment]
> Are you both on Monterey?

Yes, I am on `12.1` and @hmijail said in the discussion thread

> the installed app is broken in (at least) MacOS 12.0 and 12.1

so he most likely is, too.

**Comment by neutric** [comment]
Daily releases are [here](https://www.openshot.org/download/) and the links seem to not expire for a loooooooong time as the asset count is at 5000+, should we consider using a pre-release in this case.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask-versions/pull/13057

**Comment by miccal** [comment]
@hmijail the daily build of this which works on Monetery has been added the the `homebrew-cask-versions` repository as `openshot-video-editor-daily`.

**Comment by hmijail** [comment]
It works, thank you.
However, maybe the non-daily cask should be stopped from installing in Monterey? (no idea if it works elsewhere either)

**Comment by miccal** [comment]
@hmijail we go by what upstream does -- until they officially state that the version they provide is not compatible with Monterey, we keep this as-is.

**Pull request merged**
