### PR TITLE
Update utm from 3.0.4-2 to 3.1.0

### PR DESCRIPTION
**Pull request by tiiiecherle**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
Only stable versions, please. Your livecheck that filters out prereleases was removed in the meantime.

**Comment by tiiiecherle** [comment]
@miccal 
I don't know why the livecheck was removed.
It would be nice to have it back to avoid beta versions reacting to the livecheck on github.

**Comment by tiiiecherle** [comment]
[https://github.com/Homebrew/homebrew-cask/commit/600c9f76d421869f4dd9325a742a962a4d3967cb](https://github.com/Homebrew/homebrew-cask/commit/600c9f76d421869f4dd9325a742a962a4d3967cb)

```
 livecheck do
     url :url
     strategy :github_latest
   end
```

**Comment by neutric** [comment]
Removing the `livecheck` was probably an oversight. Please feel free to reinstate it!

**Pull request merged**
