### PR TITLE
Pandora

### PR DESCRIPTION
**Pull request by OranguTech**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].
- [x] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> * [x]  `brew cask style --fix {{cask_file}}` reports no offenses.

Can you please show the output of this command? If it did work for you with no offenses, you have a seriously broken `style` check and we need to look into it.

**Comment by OranguTech** [comment]
> > * [x]   `brew cask style --fix {{cask_file}}` reports no offenses.
> 
> Can you please show the output of this command? If it did work for you with no offenses, you have a seriously broken `style` check and we need to look into it.

Okay, I thought I had, but it's not in my command history, and after running it now, it's obvious I didn't. :/ (I know I was tired at the time, but not that bad...)

Sorry for the extra work, and thanks for fixing it up (esp. the versioned URL). I'm surprised macupdater.net is considered a valid app cast source?

**Comment by vitorgalvao** [comment]
> I'm surprised macupdater.net is considered a valid app cast source?

In case you’re thinking of https://www.macupdate.com/, note http://www.macupdater.net/ is a different thing.

The latter are our friends and work with us, providing us with the majority of quick cask updates. Take a closer look at the appcast URL — it’s a script they host and let us take advantage of that uses the upstream download as a source to always get up-to-date information.

**Comment by vitorgalvao** [comment]
> which doesn't mention anything about about a 3rd party version aggregater

In part to stave off abuse from their system. But if it makes you feel more secure:

* I trust them. They’re prolific, respectful contributors who never disappoint.
* Appcasts don’t really *do* anything. They’re hooks for external tools to grab on to, so even if they pointed to a malware domain, you wouldn’t be affected when using `brew cask` commands.

**Pull request merged**
