### PR TITLE
Bump BlueJ to version 3.1.6

### PR DESCRIPTION
**Pull request by fuadsaud**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You’re supposed to take the `shasum -a 256` of the downloaded package. Not sure what you’re doing, but you got it wrong on both PRs.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in a4144a155598ce32c83f0a332e18fa521d93b58b. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by fuadsaud** [comment]
That's weird

screen shot 2015-10-24 at 8 20 46 pm

**Comment by vitorgalvao** [comment]
> But the other PR seems correct

Nope, both were wrong. Confirmed by Travis and myself.

**Pull request closed without merging**
