### PR TITLE
Update vmware-fusion.rb

### PR DESCRIPTION
**Pull request by fuzzyroddis**
### Checklist
- [ ] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by adidalal** [comment]
There was a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) when you submitted. It must be filled.

If you were not presented a template, you may have submitted via a CLI tool (likely [`hub`](https://hub.github.com/)). It that was the case, you may wish to see if the tool has a way to let you use the template (`hub` [is working on it](https://github.com/github/hub/issues/1118)).

In either case, please [refer to the template](https://raw.githubusercontent.com/caskroom/homebrew-cask/master/.github/PULL_REQUEST_TEMPLATE.md) and update your comment.

----

Also, check out `cask-repair`, it makes Cask updates like this quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

**Comment by fuzzyroddis** [comment]
I don't feel comfortable with my PR given all the `Binary` entries.

**Comment by adidalal** [comment]
You can open up an issue and a maintainer will look at it as time permits.

**Comment by fuzzyroddis** [comment]
Thanks, that sounds like a much better idea.

**Pull request closed without merging**
