### PR TITLE
Link binary for electron, librewolf, firefox, keka, launchcontrol, obs

### PR DESCRIPTION
**Pull request by BingoKingo**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by p-linnane** [comment]
What is the rationale for this?

**Comment by BingoKingo** [comment]
Link binary for cli usage:

Electron:
```
To run a local app, execute the following on the command line:
electron path-to-app

Usage: electron [options] [path]

A path to an Electron app may be specified. It must be one of the following:
  - index.js file.
  - Folder containing a package.json file.
  - Folder containing an index.js file.
  - .html/.htm file.
  - http://, https://, or file:// URL.

Options:
  -i, --interactive     Open a REPL to the main process.
  -r, --require         Module to preload (option can be repeated).
  -v, --version         Print the version.
  -a, --abi             Print the Node ABI version.
```

Librewolf / Firefox:
```
Usage: firefox [ options ... ] [URL]
       where options include:
  --g-fatal-warnings Make all warnings fatal

Firefox options
  -h or --help       Print this message.
  -v or --version    Print Firefox version.
  --full-version     Print Firefox version, build and platform build ids.
  -P <profile>       Start with <profile>.
  --profile <path>   Start with profile at <path>.
  --migration        Start with migration wizard.
  --ProfileManager   Start with ProfileManager.
  --no-remote        Do not accept or send remote commands; implies
                     --new-instance.
  --new-instance     Open new instance, not a new window in running instance.
  --safe-mode        Disables extensions and themes for this session.
  --allow-downgrade  Allows downgrading a profile.
  --MOZ_LOG=<modules> Treated as MOZ_LOG=<modules> environment variable,
                     overrides it.
  --MOZ_LOG_FILE=<file> Treated as MOZ_LOG_FILE=<file> environment variable,
                     overrides it. If MOZ_LOG_FILE is not specified as an
                     argument or as an environment variable, logging will be
                     written to stdout.
  --headless         Run without a GUI.
  --jsdebugger [<path>] Open the Browser Toolbox. Defaults to the local build
                     but can be overridden by a firefox path.
  --wait-for-jsdebugger Spin event loop until JS debugger connects.
                     Enables debugging (some) application startup code paths.
                     Only has an effect when `--jsdebugger` is also supplied.
  --start-debugger-server [ws:][ <port> | <path> ] Start the devtools server on
                     a TCP port or Unix domain socket path. Defaults to TCP port
                     6000. Use WebSocket protocol if ws: prefix is specified.
  --browser          Open a browser window.
  --new-window <url> Open <url> in a new window.
  --new-tab <url>    Open <url> in a new tab.
  --private-window <url> Open <url> in a new private window.
  --preferences      Open Preferences dialog.
  --screenshot [<path>] Save screenshot to <path> or in working directory.
  --window-size width[,height] Width and optionally height of screenshot.
  --search <term>    Search <term> with your default search engine.
  --setDefaultBrowser Set this app as the default browser.
  --first-startup    Run post-install actions before opening a new window.
  --kiosk            Start the browser in kiosk mode.
  --disable-pinch    Disable touch-screen and touch-pad pinch gestures.
  --jsconsole        Open the Browser Console.
  --jsdebugger [<path>] Open the Browser Toolbox. Defaults to the local build
                     but can be overridden by a firefox path.
  --wait-for-jsdebugger Spin event loop until JS debugger connects.
                     Enables debugging (some) application startup code paths.
                     Only has an effect when `--jsdebugger` is also supplied.
  --devtools         Open DevTools on initial load.
  --start-debugger-server [ws:][ <port> | <path> ] Start the devtools server on
                     a TCP port or Unix domain socket path. Defaults to TCP port
                     6000. Use WebSocket protocol if ws: prefix is specified.
  --marionette       Enable remote control server.
  --remote-debugging-port [<port>] Start the Firefox Remote Agent,
                     which is a low-level remote debugging interface used for WebDriver
                     BiDi and CDP. Defaults to port 9222.
  --remote-allow-hosts <hosts> Values of the Host header to allow for incoming requests.
                     Please read security guidelines at https://firefox-source-docs.mozilla.org/remote/Security.html
  --remote-allow-origins <origins> Values of the Origin header to allow for incoming requests.
                     Please read security guidelines at https://firefox-source-docs.mozilla.org/remote/Security.html
```

OBS:
```
Usage:
--help, -h: Get list of available commands.

--startstreaming: Automatically start streaming.
--startrecording: Automatically start recording.
--startreplaybuffer: Start replay buffer.
--startvirtualcam: Start virtual camera (if available).

--collection <string>: Use specific scene collection.
--profile <string>: Use specific profile.
--scene <string>: Start with specific scene.

--studio-mode: Enable studio mode.
--minimize-to-tray: Minimize to system tray.
--multi, -m: Don't warn when launching multiple instances.

--verbose: Make log more verbose.
--always-on-top: Start in 'always on top' mode.

--unfiltered_log: Make log unfiltered.

--disable-updater: Disable built-in updater (Windows/Mac only)

--disable-missing-files-check: Disable the missing files dialog which can appear on startup.

--version, -V: Get current version.
```

LauchControl
```
Usage: fdautil SUBCOMMAND [PROGRAM [ARGUMENT ...]]

Subcommands:
    list
        List programs and arguments that may be executed via fdautil
    exec PROGRAM [ARGUMENT ...]
        Execute program with optional arguments
    set (agent|daemon) LABEL PROGRAM [ARGUMENT ...]
        Enable specified job to execute a program via fdautil.
        Requires root privileges.
    remove (agent|daemon) LABEL
        Remove record for specified job. Requires root privileges.
    rename (agent|daemon) FROM-LABEL TO-LABEL
        Change the label of a given job. Requires root privileges.
    test [(agent|daemon) LABEL PROGRAM [ARGUMENT ...]]
        Test whether Full Disk Access is enabled for fdautil or if the
        specified job may execute the program.
```

Keka:
```
Usage: Keka [options] --cli [binary] [binary specific options ...]

Run Keka as a command-line interface process.

You should run Keka with the --cli option followed by the binary to use.
Any other Keka option should go before the --cli argument.
Example: Keka --ignore-file-access --cli tar -cf file.tar folder

Options:
  -h, --help                     show this help message and exit
  --version                      show the Keka version
  -v, --verbose                  show verbose logging output
  --cli                          run Keka as a command-line interface process
  --ignore-file-access           ignore the File Access warning and try the operation anyway

To see each binary options just run --cli [binary] --help.
Example: Keka --cli 7z --help

Binaries:
  7z
  7zz
  brotli
  kwet
  lbzip2
  lrzip
  lzip
  pbzip2
  pigz
  plzip
  tar
  unar
  unrar
  xz
  zstd
```

**Comment by BingoKingo** [comment]
Can someone give me a reply or approve it?

**Comment by p-linnane** [comment]
I don't have any issues with this unless @miccal or @bevanjkay do.

**Comment by bevanjkay** [comment]
Looks good to me 👍🏻

**Comment by bevanjkay** [comment]
CI syntax only to allow Firefox to pass. (It times out on CI)

**Review by bevanjkay — DISMISSED** [review]

**Review by miccal — APPROVED** [review]

**Pull request merged**
