### PR TITLE
Update textmate to 2.0-rc.19

### PR DESCRIPTION
**Pull request by schwedenmut**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by core-code** [comment]
i think we should actually revert to rc10 since it is the one linked on their download page AND the "latest release" on github - all others are marked as "prerelease":

**Comment by schwedenmut** [comment]
Hmmm, actually sounds good and conform to stable-rule. Thought there was an exception to the stable-rule.

**Comment by core-code** [comment]
well, lets see what the powers-that-be think ;)

in any case, thanks for your PR!

**Comment by reitermarkus** [comment]
> Thought there was an exception to the stable-rule.

Yeah, I'd say this is an exception because the homepage isn't really consistent with the GitHub releases. The `rc.10` is indeed not marked as a pre-release, but this seem's quite arbitrary. Also the homepage links to `beta.10`, despite there being a `beta.12.33`.

Maybe @sorbits can clear things up, but for now let's continue with using the latest `rc` release regardless.

**Comment by core-code** [comment]
> Yeah, I'd say this is an exception because the homepage 
> isn't really consistent with the GitHub releases. 

it seems fully consistent. both claim rc10 is the latest 'stable'

> The rc.10 is indeed not marked as a pre-release, but this seem's quite arbitrary. 

the fact that this release is also linked from the download page as the latest one makes it seem 'not arbitrary' to me

but i may be interpreting the facts wrong....


in any case the developer seems completely nuts and doesn't seem to understand what an 'rc' actually is.

**Pull request merged**
