### PR TITLE
Update badlion-client from 2.15.2 to 2.16.1

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
false positive on homepage not reachable, even curl can reach it.

**Comment by reitermarkus** [comment]
> Self-approved by @core-code.

Was that intentional? If it's not your PR you can just approve it regularly.

**Comment by reitermarkus** [comment]
The homepage is protected by CloudFlare it seems.

**Comment by core-code** [comment]
ah ok. i thought i could merge *any* pr that way, thanks for pointing this out

**Review by core-code — APPROVED** [review]

**Comment by core-code** [comment]
normal approving doesn't seem to work either though

**Comment by core-code** [comment]
> protected by CloudFlare

<ramble> we could call it *crippled* by CloudFlare </ramble>

**Comment by reitermarkus** [comment]
> normal approving doesn't seem to work either though

It only merges if CI is passing.

**Comment by reitermarkus** [comment]
Should be working once https://github.com/Homebrew/brew/pull/8711 is merged.

**Comment by core-code** [comment]
> It only merges if CI is passing.

so there is no way to merge something if CI is failing - unless its only due to the appcast or the install?

**Comment by reitermarkus** [comment]
> so there is no way to merge something if CI is failing - unless its only due to the appcast or the install?

Correct. If CI is failing, it needs to be fixed. Are there other common issues apart from appcast and install which should be skippable on CI?

**Comment by core-code** [comment]
> Correct. If CI is failing, it needs to be fixed. 

ok thanks for the confirmation. 

i see cask PRs as 'urgent' and CI fixes as 'whenever someone qualified and interested has time' so for me letting one hold up the other doesn't make sense.  but i know others disagree so there is no point for further discussion. lets just wait and see how it works out.

> Are there other common issues apart from appcast and install which should be skippable on CI?

well, lets just see what comes up, i guess we'll have a good idea here in two weeks. 
the 'unrelated cask suddenly fails' did pose a bit of an issue today.

**Comment by reitermarkus** [comment]
> whenever someone qualified and interested has time

That someone is mostly me at the moment, so by not enforcing CI to be passing the problem only gets worse because there would be absolutely no incentive to fix it.

**Comment by core-code** [comment]
well, if it works out like planned, and we have trouble-free and reliable CI at some point then thats definitely great. i see many improvements have already been made, so thanks there!

**Pull request merged**
