### PR TITLE
Add PlaygroundMDImporter 0.1.0

### PR DESCRIPTION
**Pull request by norio-nomura**
#### Adding a new cask
- [x] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Commit message includes cask’s name.
- [x] `brew cask audit --download playgroundmdimporter` is error-free.
- [x] `brew cask style --fix playgroundmdimporter` left no offenses.
- [x] `brew cask install playgroundmdimporter` worked successfully.
- [x] `brew cask uninstall playgroundmdimporter` worked successfully.

### CODE REVIEW

**Comment by norio-nomura** [comment]
What is failing on Travis CI?

**Comment by vitorgalvao** [comment]
We’re not sure yet. Unrelated error.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in b53cc73f42561a89ddce9ce0c522fe70f725e3c9. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by norio-nomura** [comment]
Thanks! 🙏

**Pull request closed without merging**
