### PR TITLE
Add webrecorder-player 1.0.4

### PR DESCRIPTION
**Pull request by commitay**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t][version-checksum],  
      provide public confirmation by the developer: {{link}}

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

https://github.com/caskroom/homebrew-cask/issues/35901

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by Saklad5** [comment]
This isn’t quite a drop in replacement for `webarchiveplayer`. Are you sure it is a good idea to outright delete that?

**Comment by commitay** [comment]
> This is an overhaul of an existing Cask, webarchiveplayer, which was deprecated in favor of this

So `webarchiveplayer` *isn't* deprecated?

**Comment by Saklad5** [comment]
> NOTE: This project is no longer being actively developed.. Check out Webrecorder Player for the latest player. https://github.com/webrecorder/webrecorderplayer-electron) (Legacy: Desktop application for browsing web archives (WARC and ARC)
That’s the header of `webarchiveplayer`’s homepage. The replacement, however, operates differently. Rather than opening a local proxy and pointing a browser to it to browse WARC files, it launches an Electron-based dedicated client to view the contents.

It is not inconceivable that some people would prefer to stick to the older version, and the Legacy tap seems to be intended for exactly this sort of thing.

**Comment by commitay** [comment]
> the Legacy tap seems to be intended for exactly this sort of thing.

We don't have a Legacy tap.

**Comment by Saklad5** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

**Comment by commitay** [comment]
> It’s in the list.

Apologies, I misunderstood. `caskroom/versions` does contain some legacy versions.

> https://github.com/caskroom/homebrew-versions#acceptable-casks
> caskroom/versions is not intended to be used for all and any old versions you personally require for xyz project; casks submitted here should be expected to be used by a reasonable number of people and supported by contributors long-term.

**Pull request merged**
