### PR TITLE
Maxon App

### PR DESCRIPTION
**Pull request by rternavskyi**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by rternavskyi** [comment]
Hi, this is my first script and I'm not sure about its operation and correct spelling. Could you please refactor it?

**Comment by rternavskyi** [comment]
Also I'm not sure which folders I chose to delete. Maybe I chose too much

**Comment by miccal** [comment]
@vitorgalvao I am thinking that this should be submitted to `hombrew-cask-drivers`?

**Comment by bevanjkay** [comment]
@miccal One other consideration is that the manual download is behind a login wall. This may not be an issue as the download URL is publicly accessible.

**Comment by miccal** [comment]
> @miccal One other consideration is that the manual download is behind a login wall. This may not be an issue as the download URL is publicly accessible.

Another good point :)

**Comment by rternavskyi** [comment]
#{staged_path}/#{token} do not need

**Comment by vitorgalvao** [comment]
> @vitorgalvao I am thinking that this should be submitted to `hombrew-cask-drivers`?

I’m not seeing any associated hardware, what am I missing?

**Comment by miccal** [comment]
> > @vitorgalvao I am thinking that this should be submitted to `hombrew-cask-drivers`?
> 
> I’m not seeing any associated hardware, what am I missing?

@vitorgalvao I was mistaken, sorry for the trouble.

**Pull request merged**
