### PR TITLE
standard-notes 3.150.53

### PR DESCRIPTION
**Pull request by stenowtf**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Their website links to the `3.150.53` version. Skipping repo checks.

**Comment by reitermarkus** [comment]
I don't think pre-releases are part of the `repository` audit. This needs to be added to `audit_exceptions/github_prerelease_allowlist.json` instead.

**Comment by razvanazamfirei** [comment]
\rebase

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
