### PR TITLE
scrolla 2828.14.0

### PR DESCRIPTION
**Pull request by godbout**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by godbout** [comment]
thank you!

**Comment by godbout** [comment]
oooooooh. failed. ☹️

**Comment by p-linnane** [comment]
GitHub is having an incident right now. A rerun fixed it.

**Review by p-linnane — APPROVED** [review]

**Comment by godbout** [comment]
🍠️🍠️🍠️

**Pull request merged**
