### PR TITLE
boot2docker is not a dependency of docker-machine

### PR DESCRIPTION
**Pull request by visualphoenix**

### CODE REVIEW

**Comment by radeksimko** [comment]
Being the original author of https://github.com/Homebrew/homebrew-devel-only/blob/master/Formula/docker-machine.rb I must admit that you're most likely right here.

What was the reason for that dependency here, @kirillseva ?

**Comment by kirillseva** [comment]
At the moment I wasn't familiar with how docker-machine works. You're right, this dependency should be removed. Instead, I'd add a dependency on ```docker``` brew formula.

**Comment by visualphoenix** [comment]
done. how does it look now? acceptable?

**Comment by kirillseva** [comment]
:+1:

**Pull request merged**
