### PR TITLE
Add Meld for OSX v3.16.0 (r1)

### PR DESCRIPTION
**Pull request by lucasmezencio**
### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download meld` is error-free.
- [x] `brew cask style --fix meld` left no offenses.

Additionally, when **adding a new cask**:
- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install meld` worked successfully.
- [x] `brew cask uninstall meld` worked successfully.

### CODE REVIEW

**Comment by fanquake** [comment]
```
==> 1 modified cask: meld
==> Downloading https://github.com/yousseb/meld/releases/download/osx-9/meldmerg
==> Verifying checksum for Cask meld
audit for meld: passed
>>> brew cask style Casks/meld.rb
== Casks/meld.rb ==
C: 13:  1: 1 trailing blank lines detected.
1 file inspected, 1 offense detected
Error: style check failed
```

**Comment by fanquake** [comment]
We'll need to do something about the version stanza. Looking at the site ` Version 3.16.0 (r1)`
is the actual version of the software, but `osx-9` is used as the version in the URL
@adidalal thoughts?

**Comment by lucasmezencio** [comment]
@fanquake fixed the trailing line error.
Sorry about the version stanza, I did not understood this session completely.

**Comment by jawshooah** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 5261554cf0295adc8ceea929f5ad313762eb90d5. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by lucasmezencio** [comment]
Thanks a lot, @jawshooah! 😃

**Pull request closed without merging**
