### PR TITLE
Upgrade Manico to 2.0

### PR DESCRIPTION
**Pull request by JiajunW**

### CODE REVIEW

**Comment by adityadalal924** [comment]
New appcast URL is `http://manico.im/static/manico-official-appcast.xml`
Please update accordingly.

**Comment by JiajunW** [comment]
Added. Thanks :)

@adityadalal924 I am also curious if there are some easy way to lookup the appcast url for an application? I just used tcpdump to find the same url.

**Comment by vitorgalvao** [comment]
> I am also curious if there are some easy way to lookup the appcast url for an application?

More often than not, “Show package contents” and then look at `Info.plist`.

Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by adityadalal924** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 147bb869cc3cf8fb29794ddf093a3f389a19da5f. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by adityadalal924** [comment]
@JiajunW Look at `Manico.app/Contents/Info.plist`

```xml
	<string>NSApplication</string>
	<key>SUFeedURL</key>
	<string>http://manico.im/static/manico-official-appcast.xml</string>
```

**Pull request closed without merging**
