### PR TITLE
Add BlockBlock.app Cask

### PR DESCRIPTION
**Pull request by ghost**
Added a Cask for BlockBlock, an app that alerts you when something is persistently installed.
When installed using a Cask, it does show up under Applications, but when you first run it you still have to click install and enter a password. Is this an issue? (I think this is just the way the app was designed. Something like Little Snitch has a similar "post-install" install.)

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> when you first run it you still have to click install and enter a password. Is this an issue?

A bit. It means more stuff is needed. It needs [`installer :manual`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#installer-manual) and an [`uninstall`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#uninstall-stanza-details).

**Comment by Gloomy-Mammoth** [comment]
I tried implementing what you suggested, but am running into some problems.

First, the app that is installed is BlockBlock.app, not some installer application which then copies BlockBlock.app to `/Applications`. So using `installer: manual` places BlockBlock.app in `/opt/homebrew-cask/Caskroom/blockblock/0.9.3/BlockBlock.app`.

Second, concerning the uninstall. On the [developer website](https://objective-see.com/products/blockblock.html) it says that to manually uninstall BlockBlock you need to: 
* unload `'/Library/LaunchDaemons/com.objectiveSee.blockblock.plist'` and `'~/Library/LaunchAgents/com.objectiveSee.blockblock.plist'`
* remove (rm -rf) `'/Library/LaunchDaemons/com/objectiveSee.blockblock.plist'`, `'~/Library/LaunchAgents/com.objectiveSee.blockblock.plist'` and `'/Applications/BlockBlock.app'`

However, trying to do that using the :delete stanza (I tried uninstalling using :pkgutil but that didn't work.) gives a permission denied error when trying to delete `'/Library/LaunchDaemons/com/objectiveSee.blockblock.plist'`.

Please advise.

**Comment by vitorgalvao** [comment]
> First, the app that is installed is BlockBlock.app, not some installer application which then copies BlockBlock.app to `/Applications`.

It looks like that is exactly what it is, from what I just tried. That app seems to only be an installer/uninstaller without any other purpose. It even puts a new `BlockBlock.app` inside `/Applications`.

As for unloading, use [`:launchctl`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#summary-of-keys):

```ruby
:launchctl => [
               com.objectiveSee.blockblock.agent,
               com.objectiveSee.blockblock.daemon
              ]   
```

**Comment by Gloomy-Mammoth** [comment]
Oh boy. I was pretty stubborn. You were right, BlockBlock does copy to `/Applications`. It just wouldn't show up in Launchpad for me for some reason so I thought it didn't copy.

I've added a new version that does the install right, but I am still having some issues with the uninstall. Like I mentioned, I get a permission error when trying to remove '/Library/LaunchDaemons/com/objectiveSee.blockblock.plist`.

**Comment by vitorgalvao** [comment]
You can try [`uninstall_preflight` with `set_permissions` or `set_ownership`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#flight-stanzas-details).

**Comment by vitorgalvao** [comment]
@Gloomy-Mammoth Is there still something you’re having trouble with?

**Comment by Gloomy-Mammoth** [comment]
Yes, I tried both `set_permissions` and `set_ownership` in `uninstall_preflight`, but I keep getting permission errors when trying to delete `/Library/LaunchDaemons/com.objectiveSee.blockblock.plist`.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 43f0c096d17f44e21d60769f1a9127f0d4bc77e1. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by vitorgalvao** [comment]
Tested and working, on a clean VM.

**Comment by Gloomy-Mammoth** [comment]
Great, thank you. Was it just a question of properly exiting the program before trying to delete its components (as you added the `:quit` stanza)?

**Comment by vitorgalvao** [comment]
Not sure. Quitting wasn’t really mandatory, though (worked fine without it), just added it to be thorough.

**Comment by Gloomy-Mammoth** [comment]
All right. Thanks again for all the help.

**Pull request closed without merging**
