### PR TITLE
Update vmware-horizon-client from 5.4.3-16499473,CART21FQ1 to 2006-8.0.0-16531451,CART21FQ2

### PR DESCRIPTION
**Pull request by beargle**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
hm, it does have a built-in update check but i was unable to determine the URL they use

**Comment by beargle** [comment]
Closest thing to an update URL so far, but requires the `CART`-prefixed version/string/whatever to be manually supplied

https://my.vmware.com/channel/public/api/v1.0/dlg/details?locale=en_US&downloadGroup=CART21FQ2_MAC_800&productId=1027&rPId=48989

**Comment by core-code** [comment]
thanks that one definitely looks better than nothing at all

> CART-prefixed version/string/whatever to be manually supplied

ok whats the actual significance here. will we habe to update it on the next major version? every minor version?


btw how did you obtain the URL? ;)

**Comment by core-code** [comment]
thanks that one definitely looks better than nothing at all

> CART-prefixed version/string/whatever to be manually supplied

ok whats the actual significance here. will we habe to update it on the next major version? every minor version?


btw how did you obtain the URL? ;)

**Comment by beargle** [comment]
> ok whats the actual significance here? will we habe to update it on the next major version? every minor version?

Looks like the URL will need to be changed for every major version for sure. Likely every minor version (which is consistent with previous releases), but not sure what we'll be getting in future - especially considering this is the first release using some calver/semver hybrid.

> btw how did you obtain the URL? ;)

Poking around in browser developer tools for XHR activity on the [download page](https://my.vmware.com/en/web/vmware/downloads/details?downloadGroup=CART21FQ2_MAC_800&productId=1027&rPId=48989), good bit of info buried in there.

image

Let me know if you find something more useful. Thanks!

**Comment by core-code** [comment]
ok thanks for the explanation! lets try this for an appcast and lets see where it leads us.

**Comment by core-code** [comment]
> Let me know if you find something more useful. Thanks!

of course. i did try to find out the URL contact by the update-check built into the app, but since it ignored the system proxy (bah!) and also ignored the http_proxy variable, 'sniffing' it wasn't possible. i gave up after a few minutes...

**Pull request merged**
