### PR TITLE
Update pocketcasts to 1.2.1

### PR DESCRIPTION
**Pull request by cr0**
see https://github.com/mortenjust/PocketCastsOSX/releases/tag/1.2.1

(old one is broken due to a 404 error)

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please submit different PRs for different casks. `pocketcasks` is still broken, thus preventing the merging of the other cask.

**Comment by cr0** [comment]
I added that second pr by accident. Sorry about that.

However, both patches should work now

**Comment by vitorgalvao** [comment]
Please squash your pocketcaskts commits. Otherwise looks good.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 2adf9bc6228c520947f7f9679cdb67a07859ff82. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
