### PR TITLE
Add Rubick 2.0.4

### PR DESCRIPTION
**Pull request by zhongjun96**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
@miccal this can't be automerged since the file was renamed so the label should stay

**Comment by zhongjun96** [comment]
😳 What kind of changes do I need to make this merge?

**Comment by bevanjkay** [comment]
@zhongjun96 The cask is failing the CI audit because the application is not `codesigned`. You would need to ask the upstream developer if they can `codesign` the application, as this issue will cause it to not run on ARM-based machines.

**Comment by miccal** [comment]
Thank you for your submission @zhongjun96, but we cannot accept it at this time because it does not pass our signature verification check:

> macOS on ARM requires applications to be signed. Please contact the upstream developer to let them know they should sign their app.

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if the developers sign their app in the future we would then be happy to consider adding this to `homebrew-cask`.

**Pull request closed without merging**
