### PR TITLE
Adding shimscript for IntelliJ IDEA

### PR DESCRIPTION
**Pull request by zuisong**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is this something upstream actually supports/recommends?

**Comment by zuisong** [comment]
> Is this something upstream actually supports/recommends?

https://www.jetbrains.com/help/idea/working-with-the-ide-features-from-command-line.html
Use IntelliJ IDEA features from the command line: open files and projects, view diffs, merge files, apply code style formatting, and inspect the source code.


The shell scripts generated by the Toolbox App﻿

**Comment by SMillerDev** [comment]
It says the script is normally generated by the toolbox. I don't think we should maintain a copy in the casks. It easily becomes outdated and if Jetbrains wanted to make this available for all apps they would have packaged it with the app.

**Comment by zuisong** [comment]
> It says the script is normally generated by the toolbox. I don't think we should maintain a copy in the casks. It easily becomes outdated and if Jetbrains wanted to make this available for all apps they would have packaged it with the app.


```bash
#!/bin/sh

open -na "IntelliJ IDEA.app" --args "$@"

```

This script is not generated by the toolbox. 

And the script is easy to use.
No matter who use IntelliJ IDEA will love it.

**Comment by bevanjkay** [comment]
@SMillerDev I agree. I don't think this should be included in the cask, as far as I'm aware we don't include extras or add-ons for any other casks.

**Comment by miccal** [comment]
Agreed.

Thank you @zuisong, but unless the script itself is packaged within the `.app` bundle, we should not be adding a `shimscript`.

**Pull request closed without merging**
