### PR TITLE
Update across-lite to 2.4.4

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
There are multiple versions of Across Lite depending on the MacOS version your running. The formula should be updated, so that install the right version depending on the `MacOS.verison;` as outlined in the ['token_reference.md'](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md ) document.

```ruby
cask 'across-lite' do
  if MacOS.version >= :mavericks && MacOS.version <= :mojave
    version '2.4.4,2442'
    sha256 '71e1b174415ea2582642f4861c0ae748b8afa1232c53adac5acddf5d5ea3a39b'

    url "http://www.litsoft.com/across/alite/download/download.php/al#{version.after_comma}osx.dmg?os=macosx"

  elsif MacOS.version <= :mountain_lion && MacOS.version >= :snow_leopard
    version '2.4.4,2441'
    sha256 'c2b2c4ff7721c6568703f78535bc3d1ea9521d4d3d4ad6fba94b2eccb756e776'

    url "http://www.litsoft.com/across/alite/download/download.php/al#{version.after_comma}osx.dmg?os=macosxold"
  end

  name 'Across Lite'
  homepage 'http://www.litsoft.com/across/alite/download/'

  app 'Across Lite.app'
end

```

**Comment by vitorgalvao** [comment]
@suschizu

> It seems the App source '/usr/local/Caskroom/across-lite/2.4.4/Across Lite.app' is not there.

[How to fix](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#source-is-not-there-error).

**Comment by suschizu** [comment]
The link now uses the bundle version for the direct download instead of the short version string - I've overseen that - sorry

**Comment by ran-dall** [comment]
@vitorgalvao Noted! Thanks!

**Pull request merged**
