### PR TITLE
Update rancher from 0.7.1 to 1.0.0

### PR DESCRIPTION
**Pull request by dasmfm**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by Amorymeltzer** [comment]
See also #118206

**Comment by jhcook** [comment]
This will not work. Please close this PR.

**Comment by neutric** [comment]
> This will not work. Please close this PR.

@jhcook Please be more specific next time. And it'd be easier to follow your progress of work if you limited yourself to one PR. Your first PR is referenced here but you closed it without comment. Interested parties, trying to figure out what is going on, have to study several other PRs, some of them closed, to extract all relevant information. That is unnecessary overhead, imho, especially for the maintainers who have to chew through dozens and dozens of PRs every day.

Not sure why you needed to start with a fresh PR several times, but you can reopen a previously closed PR, undeleted a previously deleted branch and add more commits to an already pushed branch. Just in case those were blockers...

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/118217

**Pull request closed without merging**
