### PR TITLE
Update bbedit

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ran-dall** [comment]
`high sierra fail`

ping @suschizu

**Comment by chrisfinazzo** [comment]
Sigh...

I was going to send a PR from my branch to update until I saw this. Unfortunately, I do not have a machine with 10.13 to test.

**Comment by ErikMinekus** [comment]
Mojave failed, not High Sierra. The checksum was the same as 12.6.7, so maybe they uploaded the wrong file.

Seems to be fixed now: #86055

**Comment by chrisfinazzo** [comment]
Huh.

I tested w/ `audit` and `style` in my branch before I commented above and it passed on Mojave.

I’ve upgraded to 13.1.2 and all seems to be well.

Carry on.

**Pull request closed without merging**
