### PR TITLE
Update fastlane to 1.8

### PR DESCRIPTION
**Pull request by tschafer**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by tschafer** [comment]
The fastlane cask was traditionally versioned by the casklane bundle_version. The last commit broke that tradition.

fastlane uses both a version and a "bundle version." Minor updates increment the version and do not require a reinstall of fastlane (the fastlane_update command is used instead). Major updates increment the bundle version as well and do require a reinstall of fastlane.

**Comment by miccal** [comment]
You will need to change the `executable: "#{staged_path}/install"` to `executable: "#{staged_path}/bundle-#{version}/install" in the `installer script:`, and a similar change in the `uninstall script:`.

**Comment by tschafer** [comment]
With the changes you describe, "brew cask install fastlane" fails with the output below. It succeeds with the commit as is. Am I missing another change that needs to be made?

==> Downloading https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/bundle-1.8.zip
######################################################################## 100.0%
==> Verifying checksum for Cask fastlane
==> Running installer script /usr/local/Caskroom/fastlane/1.8/bundle-1.8/install
Error: No such file or directory - /usr/local/Caskroom/fastlane/1.8/bundle-1.8/install
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:211:in `spawn'
...

**Comment by aksswami** [comment]
@miccal @tschafer The problem is not with the version or the link. It is not able to locate the installer file after downloading the package. I am not sure how the paths are determined. Here is the output from my machine.

```brew cask install fastlane
==> Downloading https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/fastlane.zip
Already downloaded: /Users/mb/Library/Caches/Homebrew/Cask/fastlane--2.28.4.zip
==> Verifying checksum for Cask fastlane
==> Installing Cask fastlane
==> Running installer script /usr/local/Caskroom/fastlane/2.28.4/install
==>
==> fastlane is already installed at /Users/mb/.fastlane/bin
==> The installer will now run the uninstall script to remove your existing fastlane bundle...
==>
==>
==> You can now remove fastlane from your search path by editing your ~/.zshrc file.
==> fastlane was uninstalled successfully!
==>
==> Done uninstalling, your regular installation will now commence. 🚕 💨
==>
==> Installing fastlane to /Users/mb/.fastlane/bin... this might take a few seconds
==>
==>
==> Successfully copied fastlane to /Users/mb/.fastlane/bin
==>
==>
Error: Command failed to execute!

==> Failed command:
#<Pathname:/usr/local/Caskroom/fastlane/2.28.4/install> -p -u -b

==> Standard Output of failed command:
fastlane is already installed at /Users/mb/.fastlane/bin
The installer will now run the uninstall script to remove your existing fastlane bundle...
You can now remove fastlane from your search path by editing your ~/.zshrc file.
fastlane was uninstalled successfully!
Done uninstalling, your regular installation will now commence. 🚕 💨
Installing fastlane to /Users/mb/.fastlane/bin... this might take a few seconds
Successfully copied fastlane to /Users/mb/.fastlane/bin



==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 18925 SIGPIPE (signal 13)>
Error: nothing to install```

I am not sure where is the package get's downloaded and how to correct the path in `fastlane.rb`.

**Comment by aksswami** [comment]
@miccal @tschafer Please check https://github.com/caskroom/homebrew-cask/pull/33047 
As fast lane bundles are now not stored using version number, so we can change version to latest.

**Comment by aksswami** [comment]
After some debugging, I was able to find out that the issue is with fast lane installer script. Script is broken for brew install. I have raised a bug for the same on fastlane repo. https://github.com/fastlane/fastlane/issues/9013

**Comment by miccal** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/33047.

**Pull request closed without merging**
