### PR TITLE
Add conflicts_with intellij-idea-eap stanza to intellij-idea

### PR DESCRIPTION
**Pull request by metyl**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

RC build of Intellij IDEA 2016.2 and the current version of
IntelliJ IDEA both have the same app name.

See also caskroom/homebrew-versions#2302.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
So is there a conflict [or not](https://github.com/caskroom/homebrew-cask/pull/22104/files)?

**Comment by vitorgalvao** [comment]
So in this case, the `conflicts_with` should not be removed again. It makes no sense to keep removing and readding.

**Comment by metyl** [comment]
@vitorgalvao it depends, with release of Intellij IDEA 2016.2 RC, they changed the app name from `IntelliJ IDEA 2016.2 EAP.app` to `IntelliJ IDEA.app` and now we have a conflict.
 Then they start EAP for next version - `2016.3` probably the app name will be changed to `IntelliJ IDEA 2016.3 EAP.app` and there won't be any conflict.

We can:
* keep `conflicts_with` stanza here but it will not always be true (most of the time it won't be true and will be misleading)
* remove `conflicts_with` stanza and get conflict from time to time - short time just before release (user will have to install with `--force` to replace currently installed version)
* maintain it (keep removing and readding `conflicts_with` stanza) based on what are the app names of current and next version.

**Comment by vitorgalvao** [comment]
`conflicts_with` doesn’t even work yet, and this has never been a problem. If the conflict only happens occasionally, then yes, lets remove it.

A conflict happens when apps clash. If these clash only in the sense they share a name, it’s not really a clash.

**Comment by metyl** [comment]
ok, so You can revert this pull request and I will made one in  [caskroom/homebrew-versions](http://github.com/caskroom/homebrew-versions) to also remove `conflicts_with` stanza.

**Comment by vitorgalvao** [comment]
Sounds like the best option. Please do.

**Comment by metyl** [comment]
@vitorgalvao To complete this task will You revert this merge or should I make PR for this?

**Comment by vitorgalvao** [comment]
I can revert.

**Pull request merged**
