### PR TITLE
Update passenger to 4.6.1

### PR DESCRIPTION
**Pull request by ahousseini**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ahousseini** [comment]
https://www.virustotal.com/#/file/860af97614dd12a751b132f0cf7d88110462ad88151a96f7e2dfacd6d2c3c8b2/detection

**Comment by vitorgalvao** [comment]
There’s no signing info. We’ll need dev confirmation.

**Comment by core-code** [comment]
i don't agree with virustotal, it IS signed properly:

`
___________

spctl

/Volumes/Passenger 4/Passenger/Passenger.app: accepted
source=Developer ID
___________

codesign

--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/AppearancePakCocoa.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/AppearancePakCocoa.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/EHBase64.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/EHBase64.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/EHEncrypt.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/EHEncrypt.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/InternetEncodings.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/InternetEncodings.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Compression_Zip_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Compression_Zip_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacBase_NSAttributedString_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacBase_NSAttributedString_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacBase_NSColor_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacBase_NSColor_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacBase_NSImage_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacBase_NSImage_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacBase_NSNotification_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacBase_NSNotification_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacBase_NSScreen_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacBase_NSScreen_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCF_CarbonEvents_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCF_CarbonEvents_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCF_CF_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCF_CF_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCF_CFDictionaryArray_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCF_CFDictionaryArray_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacClassic_MacTT_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacClassic_MacTT_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCloud_WindowLion_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCloud_WindowLion_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCocoa_NSAppleScript_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCocoa_NSAppleScript_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCocoa_NSProcessInfo_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCocoa_NSProcessInfo_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCocoa_NSWorkspace_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacCocoa_NSWorkspace_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacExtras_SparkleCocoa_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacExtras_SparkleCocoa_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacOSX_MacOSX_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_MacOSX_MacOSX_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Main_NSBase_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Main_NSBase_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Main_Registration_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Main_Registration_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Picture_Icon_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Picture_Icon_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Util_DirectorySize_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Util_DirectorySize_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Util_Folderitems_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Util_Folderitems_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Util_Main_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Util_Main_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Util_OpenDialog_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Util_OpenDialog_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Util_SystemInformation_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Util_SystemInformation_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Util_Window_Plugin_19646.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/MBS_Util_Window_Plugin_19646.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/Shell.dylib
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/Shell.dylib
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--prepared:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/XojoFramework.framework/Versions/Current/.
--validated:/Volumes/Passenger 4/Passenger/Passenger.app/Contents/Frameworks/XojoFramework.framework/Versions/Current/.
/Volumes/Passenger 4/Passenger/Passenger.app: valid on disk
/Volumes/Passenger 4/Passenger/Passenger.app: satisfies its Designated Requirement

`

screenshot 2018-09-22 at 18 52 00

**Comment by core-code** [comment]
since pr #53021 was merged, i think we can close this

@ahousseini thanks anyway ;)

**Pull request closed without merging**
