### PR TITLE
mercury-browser 129.0.2 (new cask)

### PR DESCRIPTION
**Pull request by zwu7**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [X] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

---

This is a fork of Firefox that works very well and stable. First time learning how to create a cask in homebrew community. Thanks for any feedback and improve tips for better!

### CODE REVIEW

**Comment by daeho-ro** [comment]
Thank you for the PR, @zwu7 !

It looks like the app does not signed.

```
  * line 8, col 2: Signature verification failed:
    /private/tmp/cask-audit20241109-9037-i1xlu2/Mercury.app: code has no resources but signature indicates they must be present
    
    macOS on ARM requires software to be signed.
    Please contact the upstream developer to let them know they should sign and notarize their software.
```

Please check the documentation,
- https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask

**Comment by khipp** [comment]
Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if the developers sign their app in the future we would then be happy to consider adding this to `homebrew-cask`.

**Comment by zwu7** [comment]
Thank you so much Klaus for this tip, I'll look into it today and learn how
to host my own Tap!

Klaus Hipp ***@***.***> 于2024年11月10日周日 02:29写道：

**Comment by zwu7** [comment]
Thank you for the reply Daeho. Since this is an App I found on Github that
is very sweet for me, I thought it might be helpful for someone else as
well. I'll look into hosting my own Tap as Klaus suggested. As I'm a newbie
on this, I appreciate any feedback you guys provided.

Daeho Ro ***@***.***> 于2024年11月10日周日 00:47写道：

**Pull request closed without merging**
