### PR TITLE
Allow rerunning CI in debug mode.

### PR DESCRIPTION
**Pull request by reitermarkus**
Set `HOMEBREW_DEBUG` and `HOMEBREW_VERBOSE` when rerunning CI in debug mode.

### CODE REVIEW

**Review by miccal — APPROVED** [review]

**Comment by bevanjkay** [comment]
@reitermarkus I assume this will be activated with a label?

**Comment by reitermarkus** [comment]
No, it's activated by using the GitHub UI to rerun a workflow and checking the checkbox. See https://github.blog/changelog/2022-05-24-github-actions-re-run-jobs-with-debug-logging/.

Shouldn't be needed normally, but wanted to have this for cases like https://github.com/Homebrew/homebrew-cask-drivers/pull/3329 where we might want to investigate further with debug output.

**Comment by bevanjkay** [comment]
Thanks for the clarification. This will be handy! :)

**Comment by SMillerDev** [comment]
Could you make a pull request for this in Homebrew core too?

**Pull request merged**
