### PR TITLE
Update birdfont from 3.30.4 to 3.30.6

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
`curl: (56) Unexpected EOF
177audit for birdfont: failed
178 - download not possible: Download failed on Cask 'birdfont' with message: Download failed: https://birdfont.org/download/birdfont-3.30.6-free.dmg`
… as usual

**Comment by core-code** [comment]
maybe we should just remove casks of vendors that can't even set up a working HTTP server?

**Comment by ran-dall** [comment]
> maybe we should just remove casks of vendors that can't even set up a working HTTP server?

@core-code I **REALLY** like that idea but might be a bit rash. @vitorgalvao Suggested looking into the `curl` options before when this happened in the `clover-configurator` cask.

**Comment by core-code** [comment]
@randall i agree it might be too rash. i've looked into curl a bit

```
> GET /download/birdfont-3.30.6-free.dmg HTTP/2
> Host: birdfont.org
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Wed, 25 Sep 2019 09:41:39 GMT
< server: Apache
< last-modified: Mon, 23 Sep 2019 19:06:01 GMT
< etag: "d2f18d-5933d1c5544e4"
< content-length: 13824397
< content-type: application/x-apple-diskimage
< x-varnish: 949881613
< age: 0
< via: 1.1 varnish (Varnish/6.2)
< accept-ranges: bytes
< 
{ [16375 bytes data]
 98 13.1M   98 13.0M    0     0   360k      0  0:00:37  0:00:37 --:--:--  380k* TLSv1.2 (IN), TLS alert, Client hello (1):
{ [2 bytes data]
* Unexpected EOF
100 13.1M  100 13.1M    0     0   361k      0  0:00:37  0:00:37 --:--:--  376k
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
curl: (56) Unexpected EOF
```
problem seems to be the connection is closed when 2 bytes are still missing - weirdly the download is still fully intact

adding '--http1.1' to the curl flags seems to fix it:

```
> Host: birdfont.org
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 25 Sep 2019 09:41:39 GMT
< Server: Apache
< Last-Modified: Mon, 23 Sep 2019 19:06:01 GMT
< ETag: "d2f18d-5933d1c5544e4"
< Content-Length: 13824397
< Content-Type: application/x-apple-diskimage
< X-Varnish: 944279155 912860281
< Age: 188
< Via: 1.1 varnish (Varnish/6.2)
< Accept-Ranges: bytes
< Connection: keep-alive
< 
{ [16045 bytes data]
100 13.1M  100 13.1M    0     0   384k      0  0:00:35  0:00:35 --:--:--  369k
* Connection #0 to host birdfont.org left intact

```

**Comment by reitermarkus** [comment]
Seems like this is the issue: https://github.com/curl/curl/issues/1618

Using the `curl-openssl` formula, it works without error while using HTTP 2.

**Comment by core-code** [comment]
awesome, thanks!

i regularly fetch all casks, and there are some other common errors (i think mainly 'error in http framing' and 'http error 416'). i'll have a look into this next time, maybe they are solvable too.

**Pull request merged**
