### PR TITLE
Update slack to 2.3.4

### PR DESCRIPTION
**Pull request by timsutton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by timsutton** [comment]
One other point: Slack hasn't used the Hockeyapp feed since they moved to the 2.3.x releases (a major refactor that moved to Electron). I'm not actually sure whether the app even contains references to the appcast anymore, as they've moved to Squirrel for their auto-updating.

**Comment by timsutton** [comment]
I just checked and there's no references to Hockey, Sparkle or the appcast feed in the current Slack app. I just removed the appcast stanza from this cask.

**Comment by miccal** [comment]
Perhaps `https://slack-files.com/T12KS1G65-F2R3TN3FS-89e821ddb7` can be used as an `appcast`?

Ping @vitorgalvao.

**Comment by timsutton** [comment]
@miccal This seems to just be a public release notes listing, not a Sparkle appcast feed - unless I'm missing something..

**Comment by miccal** [comment]
True, but we use this sort of thing in other Casks.

**Comment by timsutton** [comment]
Oh, ok. I didn't realize that `appcast` is also used for such things when it's not actually a Sparkle feed.

**Comment by miccal** [comment]
I am not 100 % sure about what can and cannot be used for an `appcast` though, hence why I pinged the expert!

**Comment by adidalal** [comment]
@miccal Technically any HTML file will work, however that specific example is probably not a good appcast source (HTML styling/caches files will change the app cast pretty much every time its queried). Think more along the lines of a plain .txt for .xml file. See https://github.com/caskroom/homebrew-cask/issues/19103 for my general process.

Slack is probably OK without an appcast if we can't find one. It's online-only and auto_updates.

**Comment by miccal** [comment]
Thanks for the information @adidalal.

**Comment by timsutton** [comment]
Thanks @adidalal!

**Pull request merged**
