### PR TITLE
microsoft-excel 16.75.23071901

### PR DESCRIPTION
**Pull request by redhatnick**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by redhatnick** [comment]
Installer for Microsoft Excel 16.75.23071901 released July 24, 2023 
[](https://learn.microsoft.com/en-us/officeupdates/update-history-office-for-mac)

**Comment by bevanjkay** [comment]
@redhatnick It looks like we should be able to use the URL that you have provided for livecheck as curl returns the page, including the download links.

@miccal Do you know if there is a reason we should use the other link instead?

**Comment by redhatnick** [comment]
Thanks @bevanjkay. Not sure what the Homebrew protocol would be here, but Microsoft has provided an installer package 

https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Excel_16.75.23071901_Installer.pkg 

and a update package 

https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/Microsoft_Excel_16.75.23071901_Updater.pkg 

both bearing the same version number. The PR is linking to the full installer package.

**Comment by bevanjkay** [comment]
@redhatnick We could change the livecheck to use the page you linked earlier, however we would need to be confident that every version added to that page receives a full installer and never just an upgrade package. Livecheck is currently using Microsoft's link to download the latest version of the installer, which is out of sync with the page you have linked.

**Pull request closed without merging**
