### PR TITLE
README.md: no longer needed to specifcally install homebrew-cask, to use it

### PR DESCRIPTION
**Pull request by vitorgalvao**
See https://github.com/Homebrew/homebrew/pull/45773.

### CODE REVIEW

**Comment by jawshooah** [comment]
:tada:

**Comment by victorpopkov** [comment]
Nice! Really good news. :+1:

**Comment by fanquake** [comment]
Awesome

**Comment by vitorgalvao** [comment]
Merged as 758f7a5feef9f6cf9e5dbe46360d40af810cd541.

**Pull request merged**
