### PR TITLE
Update foobar2000

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
@vitorgalvao the cask is broken again. it is definitely download-protection. do you see a way around this? if not, i'll send a PR to delete it.

**Comment by vitorgalvao** [comment]
We could use a [`url do`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#using-a-block-to-defer-code-execution) block, but I question if it’d be worth it. In my experience, if a vendor is adamant about download protection, it’s not worth our time to fight it because they can just change their method. This cask is still young and has few users, so removal wouldn’t be problematic.

If you think it’s worth a try (you might have better numbers on how widespread this software is), we may try, in order (1 and 2 can be switched):

1. Add `url do`.
2. Ask them if they would provide a stable URL.
3. Remove the cask.

**Comment by core-code** [comment]
personally i'd just remove it. its unpopular and i agree that fighting the developer's wishes doesn't make sense in most cases.

maybe previous contributors may want to give the 'url block' method a try or contact the vendor for a stable url. ping @icpz @kiendang @mjsteinbaugh

**Comment by kiendang** [comment]
I'm ok with removing it.

**Comment by mjsteinbaugh** [comment]
I’m OK with removal if this continues to be a problem

**Comment by icpz** [comment]
I'm ok with removal, too.

**Pull request merged**
