### PR TITLE
Update xoctave to latest

### PR DESCRIPTION
**Pull request by vitorgalvao**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by sebma** [comment]
The pb. here is not related to the URL of the latest version of xoctave but to the user agent because it is containing "curl", therefore the download does not work :

```
$ curl -#OA "curl" --fail "http://www.xoctave.com/demo/xoctave%20demo.dmg"

curl: (22) The requested URL returned error: 406 Not Acceptable
$ curl -#OA "Homebrew" --fail "http://www.xoctave.com/demo/xoctave%20demo.dmg"
######################################################################## 100.0%
$
```

**Comment by vitorgalvao** [comment]
And that’s exactly what this PR fixes. It fakes the user agent.

**Comment by sebma** [comment]
Great :)

**Comment by sebma** [comment]
Strange, I don't see anything in `Casks/xoctave.rb` that is faking the user agent

**Comment by vitorgalvao** [comment]
`brew update`

**Comment by sebma** [comment]
Ok, I'll do it tomorrow morning when I get back to work.

**Comment by sebma** [comment]
Works great, thanks a lot :)

**Pull request merged**
