### PR TITLE
Update OpenInTerminal from 2.3.6 to 2.3.7

### PR DESCRIPTION
**Pull request by Ji4n1ng**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by djerfy** [comment]
Hi @Ji4n1ng, I just created 2 PR for OpenInTerminal (#163303) and OpenInTerminal-Lite (#163304)

**Comment by Ji4n1ng** [comment]
@djerfy  Thank you. I'm wondering if you're creating a PR for OpenInEditor-Lite. If not, I will do it.

**Comment by Ji4n1ng** [comment]
I'll close this PR, since you've done.

**Comment by Ji4n1ng** [comment]
@djerfy Hi, I've created a PR for OpenInEditor-Lite.

**Pull request closed without merging**
