### PR TITLE
ci: add ability to manually audit a list of casks

### PR DESCRIPTION
**Pull request by bevanjkay**
This PR adds the ability for us to manually audit a list of casks with a workflow dispatch.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
I'm not comfortable enough with the CI workflows to review this, but hopefully someone else can chime in.

**Comment by p-linnane** [comment]
@Bo98 & @carlocab are the ones most familiar with GitHub Actions AFAIK.

**Comment by bevanjkay** [comment]
For additional context, the idea here is to be able to pass a list of casks to run audits on CI manually to check existing casks for issues with downloads, mismatches etc.. without having to run locally for maintainers. 

May need an additional option to run "stricter" tests by optionally passing `--new-cask`

**Comment by krehel** [comment]
This is a key addition towards being able to move away from unsigned Casks as well.  Auditing "the world" locally is a pretty tedious and network-intensive process.

We can also catch a fair number of issues with stricter checking on version bump, but obviously doesn't encapsulate all Casks and avoids during-PR issues.

**Comment by Bo98** [comment]
Would be good to combine `cmd/lib/manual-generate-matrix.rb` with `cmd/lib/generate-matrix.rb` more. Bit too much copy-pasting between the two I reckon.

**Comment by bevanjkay** [comment]
I'll do a refactor hopefully tomorrow

**Comment by bevanjkay** [comment]
@bo98 I have had a go at a refactor.

**Comment by Bo98** [comment]
Thanks!

Workflow also looks like a copy-paste job. It looks like the only differences are the addition of `workflow_dispatch` and a different `generate-matrix` line.

Could you instead add `workflow_dispatch` to `ci.yml` and then in the `generate-matrix` step you can chose which args to pass via:
```bash
if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]
then
  # ...
else
  # ...
fi
```

**Comment by bevanjkay** [comment]
@Bo98 I think I have done this correctly, and thank you for your guidance to clean this up 🙇‍♂️

**Review by Bo98 — APPROVED** [review]
Thanks!

**Pull request merged**
