### PR TITLE
Update fork to 1.0.71.1

### PR DESCRIPTION
**Pull request by vimkat**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by nilsweb** [comment]
For some reason, the SHA-256 checksum wasn't correct. I downloaded the app manually from the website and verified it myself. The new one should work now!

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by nilsweb** [comment]
No problem! Here's the link to VirusTotal: https://www.virustotal.com/#/file/8c52adaf64dc4a2b3d30d0ecc9e19f0249e6982590845da89ff25e9a96796547/details

**Comment by nilsweb** [comment]
I've also just spotted that @princescar fixed this in #53554 about 10 minutes ago. Installing it with `brew cask install fork` now seems to be working again, so this could be closed.

**Pull request closed without merging**
