### PR TITLE
jellyfin-media-player 1.10.0

### PR DESCRIPTION
**Pull request by jakobzudrell**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `jellyfin-media-player` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.
---

NOTE: I was only able to test AppleSilicon, so if someone could confirm this for Intel that'd be great, so the pull request can be merged :)

### CODE REVIEW

**Review by bevanjkay — APPROVED** [review]
Thank you @jakobzudrell

**Comment by privacymatters1** [comment]
I had problems installing the update on a 2019 Intel MacBook Pro 16 with MacOS 14.4.1

==> Moving App 'Jellyfin Media Player.app' to '/Applications/Jellyfin Media Player.app'
<unknown>:0: error: invalid Darwin version number: macosx14
<unknown>:0: error: invalid version number in '--target=x86_64-apple-macosx14'
==> Purging files for version 1.10.0 of Cask jellyfin-media-player
==> Purging files for version 1.10.0 of Cask jellyfin-media-player
Warning: Reverting upgrade for Cask jellyfin-media-player
==> Purging files for version 1.9.1 of Cask jellyfin-media-player
Error: jellyfin-media-player: It seems there is already an App at '/Applications/Jellyfin Media Player.app'.

after that error it was not possible to open Jellyfin-Media-Player

**Comment by jakobzudrell** [comment]
Hey @privacymatters1 ,

my experience with homebrew is limited but I'll do my best to help.. Can you post the exact command which resulted in this error?
Do you think this might be related to jellyfin/jellyfin-media-player/#623 ?

**Comment by privacymatters1** [comment]
sure, my command was just "brew upgrade".

I'm not a developer, but I tried a little and got to the conclusion that homebrew is not the problem.

I deinstalled Jellyfin-Media-Player und reinstalled it with homebrew again and the installation in homebrew was no problem, but opening got me to the same error as many others are experiencing. like the screenshot in https://github.com/jellyfin/jellyfin-media-player/issues/623#issuecomment-2111983921 and also installing the app manual from jellyfin-github got me the same error, so I think the problem has nothing to do with hombrew.

Nevertheless, thank you for answering.

**Comment by jakobzudrell** [comment]
Yeah, I think that is an already known issue with their current build. There is already a PR open that should fix this, all we can do now is wait for that to happen :)

**Pull request merged**
