### PR TITLE
Update osxfuse from 3.11.2 to 4.0.5

### PR DESCRIPTION
**Pull request by kmutahar**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @kmutahar, but this version is a now available as [`macfuse`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/macfuse.rb).

**Comment by kmutahar** [comment]
@miccal Oops I didn't notice that they changed the name. 

Questions

1. If the name has been changed why not move this to https://github.com/homebrew/homebrew-cask-versions or have it as an alias to the new cask
2. Should one change other cask that are depended on this program such as https://github.com/Homebrew/homebrew-cask/blob/master/Casks/ntfstool.rb to the new cask name, since at the end its the same program.

**Comment by miccal** [comment]
@kmutahar the original name `osxfuse` is used both in `hombrew-core` and `homebrew-cask`, and the transition is taking some time.

**Comment by kmutahar** [comment]
@miccal Okay if help is needed in the transition let me know. Again thank you for the help

**Pull request closed without merging**
