### PR TITLE
Upgrade Go from 1.4.2 to 1.5

### PR DESCRIPTION
**Pull request by denpatin**
PS. From the v1.5, the minimum OS X version is 10.8.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please don’t remove the conditional. Adapt the cask to it.

**Comment by denpatin** [comment]
@vitorgalvao You mean the line `if MacOS.release <= :mountain_lion` should be there without any `else` condition? Hm...

**Comment by vitorgalvao** [comment]
No, I mean there should be a new intermediary condition. The latest version always remains on the `else`.

**Comment by denpatin** [comment]
@vitorgalvao Frankly, I don't get what you're trying to say :cry:

**Comment by vitorgalvao** [comment]
I mean [not undoing what works, but adding to it](https://github.com/caskroom/homebrew-cask/pull/13587/files).

Thank you anyway for your work.

**Comment by denpatin** [comment]
@vitorgalvao Ach so, now I get your point. Wow. However, this seems rather weird to me. Anyway, thanks for help!

**Comment by vitorgalvao** [comment]
> However, this seems rather weird to me.

Why? Many other casks follow this solution.

**Comment by denpatin** [comment]
@vitorgalvao When there's a newer app version and a vendor for it has constricted the number of supported OS versions, it's no accident. What is more, I don't understand why some things are to entirely be rewritten and for the rest we should leave the mentioning of the previous versions. The old version is the old version, and, to my mind, it must be everywhere either kept or removed. But maybe I don't merely see the real advantage :rooster:

**Comment by vitorgalvao** [comment]
If we did it the way you suggest, than anyone with an OS X version under Mountain Lion would be left in the dust and wouldn’t be able to get Go from the cask. This way, everyone get the latest version available for their OS. There is no downside to users with this method, but there would be with yours.

**Comment by denpatin** [comment]
@vitorgalvao Yep, but I still see no difference in whether these users of the old OS X versions cannot upgrade Go themselves because the vendor didn't make it possible, or it won't be accessible through the Cask. However, I partly agree with you that if there's a temporary way out, why not.

**Pull request closed without merging**
