### PR TITLE
Update betterzip from 5.0.2 to 5.0.3

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Review by reitermarkus — DISMISSED** [review]

**Comment by core-code** [comment]
https://macitbetter.com/BetterZip5.rss

=> it does have version 5.0.3 now.

not happy about changing the appcast to a HTML page that makes it hard to detect new versions. version histores are *especially* bad since they also contain the old versions

**Comment by core-code** [comment]
thanks ;)

> audit for betterzip: failed
> - The URL https://macitbetter.com/BetterZip5.rss is not reachable

not true

> - The URL https://macitbetter.com/ is not reachable

not true

> - appcast at URL 'https://macitbetter.com/BetterZip5.rss' does not contain the version number '5.0.3':

not true


maybe related to this:


```
curl https://macitbetter.com/BetterZip5.rss           
curl: (16) Error in the HTTP2 framing layer
```

specifying the '--http1.1' option for 'curl' seems to be a functioning workaround

**Comment by reitermarkus** [comment]
> specifying the '--http1.1' option for 'curl' seems to be a functioning workaround

Yep also found this, see https://github.com/Homebrew/brew/pull/8618.

**Comment by core-code** [comment]
thanks great to see that a fix is forthcoming. i've also seen the HTTP2 error in some actual brew downloads.

**Review by reitermarkus — APPROVED** [review]

**Pull request merged**
