### PR TITLE
Add Rippling 3.6.2

### PR DESCRIPTION
**Pull request by johnpitchko**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by johnpitchko** [comment]
The app is versioned but the version number is not present on the installer page. Rather, clicking on the `Download` button runs a JS script to redirect the browser to the file for download. How do you manage versions/`livecheck` in that situation?

**Comment by razvanazamfirei** [comment]
Hi, @johnpitchko! Thank you for submitting this. I haven't been able to find the installer page. If there are other pages where the software version is mentioned (e.g, release notes), we can also use that.

**Comment by johnpitchko** [comment]
Hello @razvanazamfirei! Here is the URL with the download link: https://app.rippling.com/downloads/hardware-management.

**Comment by bevanjkay** [comment]
@johnpitchko Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
