### PR TITLE
Add Accurics CLI

### PR DESCRIPTION
**Pull request by ws-accurics**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by ran-dall** [comment]
@ws-accurics By chance, is it possible to add an `appcast` and a `zap` stanza?

**Comment by ws-accurics** [comment]
Hi Randall,

Sure thing--zap will be easy, but appcast may be later today or perhaps by Monday. I'm on the apps team, and the team that manages the website might be a little picky about what info is displayed, how it's displayed, etc. But hopefully, all goes smooth. Appreciate you taking a look!

Regards,
-Willie

**Comment by ran-dall** [comment]
@ws-accurics NP. I know you said the `zap` was easy, but if you want to automate the zap, you can check out @nrlquaker's `createzap` project here: https://github.com/nrlquaker/homebrew-createzap.

**Comment by miccal** [comment]
@ran-dall this is a binary-only Cask, and hence there will be nothing to `zap`.

**Comment by ran-dall** [comment]
> @ran-dall this is a binary-only Cask, and hence there will be nothing to zap.

@miccal Is it? I didn't test it locally and it wasn't noted on the PR.

**Comment by ws-accurics** [comment]
Hello @ran-dall, @miccal,

Correct, it is a binary-only Cask that just includes just the binary + readme in the notarized DMG. I did run createzap anyway just to make sure there weren't any metadata files unknowingly created by the OS (or us) that I missed. I did add a zap clause because the configuration for this application will store metadata under ~/.accurics-cli, so it was a good suggestion.

As for the appcast, I have added a latest-mac.yml-style file to pull from on the website. I'll submit the PR soon, just running a few more tests.

Thanks!
-Willie

**Comment by ran-dall** [comment]
@ws-accurics Thank you, Willie! You're the best! Thanks for understanding and the clarification.

**Comment by ws-accurics** [comment]
@ran-dall not a problem. The way I see it, you folks are doing all of us a huge favor providing a more frictionless download/install experience for end-users, so I really don't mind the extra requirements. Lemme know if there is anything else I can help with.

All the best,
-Willie

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
