### PR TITLE
Update majsoul-plus to 1.11.1

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
i think it is another case of a ZIP file thats incompatible with the command-line 'unzip' tool and a few GUI unarchivers, as we've seen with a few other casks recently. there may be nothing we can do except file a bug with them.

**Comment by ran-dall** [comment]
> there may be nothing we can do except file a bug with them.
@core-code did you want to do that?

**Comment by ran-dall** [comment]
>

**Comment by core-code** [comment]
i‘ll do it, no problem

**Comment by core-code** [comment]
since the problem seems to be fixed already in their latest pre-release and we can switch to the .DMG download i did not file a bug report yet. i have submitted https://github.com/Homebrew/homebrew-cask/pull/60152 to switch over to the DMG

**Comment by ran-dall** [comment]
Closed in favor of https://github.com/Homebrew/homebrew-cask/pull/60152

**Comment by ran-dall** [comment]
> since the problem seems to be fixed already in their latest pre-release and we can switch to the .DMG download i did not file a bug report yet. i have submitted #60152 to switch over to the DMG

Thank you! ✊

**Comment by ran-dall** [comment]
Closed in favor of #60152

**Pull request closed without merging**
