### PR TITLE
update tencent-meeting from 2.7.5.434 to 2.8.8.403

### PR DESCRIPTION
**Pull request by shikiroot**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Please add the following `livecheck` block so that the CI passes, like in the Cask for [`wechat`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/wechat.rb):
```
  livecheck do
    skip
  end
```

**Comment by reitermarkus** [comment]
@miccal, when using `skip`, we should also always specify a reason.

**Comment by miccal** [comment]
> @miccal, when using `skip`, we should also always specify a reason.

Ok, thanks.

> Also, don't just add `skip` to please CI. We want people to try to find an appcast, and if the URL is versioned, there is likely a website pointing to it.

I tried to find one already.

**Comment by reitermarkus** [comment]
```
curl 'https://meeting.tencent.com/wemeet-webapi/v2/config/query-download-info' --data '[{"instance":"mac","type":"0300000000"}]'
```

Seems like it needs a `POST` request.

**Comment by shikiroot** [comment]
> ```
> curl 'https://meeting.tencent.com/wemeet-webapi/v2/config/query-download-info' \
>   --data '[{"instance":"mac","type":"0300000000"}]'
> ```
> 
> Seems like it needs a `POST` request.

Looks like it just returned data for x86_64.
```
{"code":0,"message":"success","nonce":"605d377e3f2db","timestamp":1616721790,"data":[{"md5":"59b6424ee3fb1f46a1c4e617425ec179","url":"https://updatecdn.meeting.qq.com/59b6424ee3fb1f46a1c4e617425ec179/TencentMeeting_0300000000_2.8.8.403.publish.x86_64.dmg","size":93700265,"version":"2.8.8.403","instance":"mac","channel":"0300000000","sub_date":"2021-03-19"}]}
```

**Comment by reitermarkus** [comment]
`mac_arm64` instead of `macos` returns the ARM URL.

**Comment by shikiroot** [comment]
> `mac_arm64` instead of `macos` returns the ARM URL.

OK, thanks. So how should it be used? Sorry but I am not good at Ruby.

**Pull request closed without merging**
