### PR TITLE
Add Kompose v0.1.2

### PR DESCRIPTION
**Pull request by adamcstephens**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

### CODE REVIEW

**Comment by miccal** [comment]
I _think_ this should be submitted to [homebrew](https://github.com/Homebrew/homebrew-core) - see a previous PR [here](https://github.com/Homebrew/homebrew-core/pull/5276).

**Comment by adamcstephens** [comment]
I opened it here, because [minikube](https://github.com/caskroom/homebrew-cask/blob/b53752d76f719a4831ed711d8e20dcf4ea1dcf07/Casks/minikube.rb) for example is a binary under cask. [kubernetes-cli](https://github.com/Homebrew/homebrew-core/blob/7b1a7ff784860503e42cc98057c0ae2933384b7f/Formula/kubernetes-cli.rb) on the other hand is compiled during install.

I can change it to homebrew if that's the consensus.

**Comment by vitorgalvao** [comment]
> I opened it here because [minikube](https://github.com/caskroom/homebrew-cask/blob/b53752d76f719a4831ed711d8e20dcf4ea1dcf07/Casks/minikube.rb), for example, is a binary under cask.

Follow the rules, not the examples. If there’s something in place that goes against the rules, than either:

* The rule as written is outdated to what we agreed on later on (rare, don’t count on it).
* The thing in place happened before the rule was in place and as such wasn’t fixed yet.
* The thing in place is an exception, and hence not to be followed.

See https://github.com/caskroom/homebrew-cask/pull/24260 for an issue that perfectly fits with this one.

In sum, yes, please submit first to HB.

**Comment by adamcstephens** [comment]
I'll work on a PR against homebrew.

What rule did I violate by opening this against cask? I'm pretty sure I read all the contributing docs, etc, and I saw nothing about how this would violate any rules. I'll happily help update this documentation if needed.

**Comment by vitorgalvao** [comment]
The policy is documented in [faq/rejected_casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/caskroom/homebrew-cask/issues/15603), submit it first to [Homebrew](https://github.com/Homebrew/homebrew). If it is rejected there, you may then try again in Homebrew-Cask (link us to the issue on Homebrew so we can see their reasoning for rejection).

**Pull request closed without merging**
