### PR TITLE
Update idisplay to latest

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
sorry i have no clue why the check is failing

**Comment by alebcay** [comment]
Looks like the installer `.pkg` is hanging on `installer:PHASE:Running package scripts…`.

**Comment by core-code** [comment]
i think the installer is just broken

**Comment by adidalal** [comment]
I would be OK just removing the app, in such a case - no need to keep broken Casks around

**Comment by commitay** [comment]
Needs to be checked to see if it installs via GUI, it could be changed to installer manual.

**Comment by core-code** [comment]
the installer script promts the user to go to systempreferences to unblock the kext, maybe that doesn't work in travis:

        SURETY="$(osascript -e 'display dialog "Please open \"System Preferences -> Security & Privacy\" by using the button below and allow system software from developer \"SHAPE GmbH\" to be used on your Mac." buttons {"Go to System Preferences"} default button "Go to System Preferences"')"

**Comment by commitay** [comment]
No, kexts can't be approved except by the user actually clicking the button. no osascript/screen sharing, etc.

**Pull request merged**
