### PR TITLE
Add iterm.app test

### PR DESCRIPTION
**Pull request by wonkyungup**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by wonkyungup** [comment]
It's a test. Is this the right way to ask?

**Comment by SMillerDev** [comment]
> It's a test. Is this the right way to ask?

What are you asking?

**Comment by wonkyungup** [comment]
This is the file upload request process.

**Comment by wonkyungup** [comment]
I am sorry that I am not good at English, so I may not be able to communicate well because I used a translator.

**Comment by wonkyungup** [comment]
What I'm curious about is the process of requesting homebrew distribution

**Comment by SMillerDev** [comment]
> What I'm curious about is the process of requesting homebrew distribution

Making a pull request, as you did, is the correct way to request something to be distributed through Homebrew.

https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request describes this process
https://docs.brew.sh/Acceptable-Casks describes which software is allowed
https://docs.brew.sh/Cask-Cookbook describes the different parts of a cask (homebrew's name for such distribution files)

**Comment by wonkyungup** [comment]
Thank you.

**Pull request closed without merging**
