### PR TITLE
Fix weird versions

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Remove some weird characters in versions in favour of moving them into the URLs.

### CODE REVIEW

**Comment by terrywang** [comment]
This change actually broke my on macOS 10.15.7 today. I created the initial goldendict cask with some help from Ruby veterans regarding versions.

The justification makes sense to me but breaking what has been working (`brew-cask-upgrade`) since it was added is not acceptable.

```bash
$  brew cu -a
==> Options
Include auto-update (-a): true
Include latest (-f): false
==> Updating Homebrew
Already up-to-date.
Error: 1.5.0-RC2,372-gc3ff15f%28Qt_5121%29 contains invalid characters: %!
/usr/local/Homebrew/Library/Homebrew/cask/dsl/version.rb:73:in `initialize'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:15:in `new'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:15:in `block in installed_apps'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:13:in `map'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:13:in `installed_apps'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:21:in `process'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:20:in `process'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:70:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/utils.rb:91:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:91:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
```

Ask: have you tested the change on at least 2 target systems (Big Sur, and Catalina)? Currently I cannot even uninstall this particular cask. Not sure if this is specific to `brew-cask-upgrade` users ONLY, I should not be the only one.

**Comment by dalugm** [comment]
Ah, same problem here, can we revert this?

**Comment by woj-tek** [comment]
I'm just banging my head with the same problem. I was trying to upgrade one app and got:
```
Error: Cask 'goldendict' definition is invalid: 'version' stanza failed with: 1.5.0-RC2,372-gc3ff15f%28Qt_5121%29 contains invalid characters: %!
```

Now whatever I try to do with brew cask i fails completely (so I can't update anything).

I tried renaming `/usr/local/Caskroom/goldendict/1.5.0-RC2,372-gc3ff15f%28Qt_5121%29` to `/usr/local/Caskroom/goldendict/1.5.0-RC2` but still nothing. I can't even uninstall it as it throws the same error:

```
wojtek@atlantiscity.local /usr/local/Caskroom/goldendict $ brew uninstall goldendict --force
Error: Cask 'goldendict' definition is invalid: 'version' stanza failed with: 1.5.0-RC2,372-gc3ff15f%28Qt_5121%29 contains invalid characters: %!
```

Funnily enough, I don't even use this application so any way to remove it (and get brew cask working again) would be highly appreciated.

**Comment by MikeMcQuaid** [comment]
> can we revert this?

No. This is a fix for a security issue, sorry.

**Comment by terrywang** [comment]
For those who have `goldendict` installed and impacted by this recent change, simply remove the
- `rm -rf $(brew --prefix)/Caskroom/goldendict`
- remove the app `rm -rf /Application/GoldenDict.app`
- `brew cleanup -s`

Do you usual business, should work.

**Pull request merged**
