### PR TITLE
Refactor Hbc::Download and Hbc::Verify

### PR DESCRIPTION
**Pull request by jawshooah**
These changes are forward-looking, improving modularity and testability for download and verification.

### CODE REVIEW

**Comment by jawshooah** [comment]
One small UI note: this introduces a new line of output to notify the user that we're either verifying the checksum or skipping it, building on #16042. See below:

```
$ brew cask install tor-messenger
==> Downloading https://dist.torproject.org/tormessenger/0.1.0b4/TorMessenger-0.1.0b4-osx64_en-US.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask tor-messenger
==> Symlinking App 'Tor Messenger.app' to '/Applications/Tor Messenger.app'
🍺  tor-messenger staged at '/opt/homebrew-cask/Caskroom/tor-messenger/0.1.0b4' (1839 files, 122M)

$ brew cask install kibako
==> Downloading https://updates.kibakoapp.com/download/latest
######################################################################## 100.0%
==> Skipping checksum for Cask kibako
==> Symlinking App 'Kibako.app' to '/Applications/Kibako.app'
🍺  kibako staged at '/opt/homebrew-cask/Caskroom/kibako/latest' (217 files, 7.2M)
```

**Comment by jawshooah** [comment]
Gonna merge this now so I can start integrating @ndr-qef's GPG implementation in #8749.

**Comment by adityadalal924** [comment]
Maybe something like "Checksum not available, skipping verification for Cask cask_name"
It a bit more verbose, but also more clear, IMO.

(Still not as clear as I'd like - I could see people opening issues about either line at the moment)

**Comment by jawshooah** [comment]
@adityadalal924 sorry, should have waited for feedback a bit longer before merging. Feel free to open a PR to improve the phrasing.

**Comment by Amorymeltzer** [comment]
No checksum available for Cask cask_name, skipping verification
No applicable checksum
Checksum not applicable for cask, skipping verification
No checksum provided for cask name, skipping verification

**Pull request merged**
