### PR TITLE
Update itraffic from 0.1.3 to 0.1.4

### PR DESCRIPTION
**Pull request by foamzou**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by foamzou** [comment]
Just a suggest。
If create an automation which can auto merge the `brew bump-cask-pr` PR, it would save the maintainers time.

The automation just need to check some points modified, if the tool can handle safe, let it merge, else check by persons.

**Review by Rylan12 — APPROVED** [review]
Thanks, @foamzou!

**Comment by Rylan12** [comment]
> Just a suggest。
> If create an automation which can auto merge the `brew bump-cask-pr` PR, it would save the maintainers time.
> 
> The automation just need to check some points modified, if the tool can handle safe, let it merge, else check by persons.

We used to have something like this but recently disabled it because of the reasons explained [here](https://brew.sh/2021/04/21/security-incident-disclosure/)

**Comment by foamzou** [comment]
Thanks the explain link, @Rylan12 
I got the reason about bug of `git_diff`, but we can just use other diff to check it.

Most of the pr just modify a version and a hash code. It would be simple and safe if just check the 2 points.  Maybe it  
 can cover 90% PRs.

Or maybe you guys would find the better way to do that.
Anyway, thanks all your guys times to maintain the project. : )

**Comment by Rylan12** [comment]
> I got the reason about bug of `git_diff`, but we can just use other diff to check it.

We can, yes, but regardless of which `diff` library we use (whether first-party or third-party), we need to put full trust into that library which is too much of a risk. Any tool (including one that we make ourselves) can have a similar or worse vulnerability. We got unlucky that the one that we chose happened to have such an occurrence, but it is no less likely for something like that to happen on any of the other options. Since there are potentially severe consequences for huge numbers of users if this goes wrong, it's not worth the risk for the benefit of saving some time. It's a bit tedious, but because it's such a simple thing it doesn't really take that long. We have enough maintainers that it isn't a huge problem for us at the moment.

> Anyway, thanks all your guys times to maintain the project. : )

Thanks ❤️! Appreciate the kind words!

**Pull request merged**
