### PR TITLE
Update microsoft-office to 16.17.18090901

### PR DESCRIPTION
**Pull request by textandrewk**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ryanturcotte** [comment]
Microsoft Office 16.17 is the version that begins Office 2019 support. Could/should a new cask be setup for Office 2019?

**Comment by textandrewk** [comment]
@ryanturcotte I think it's ideal to have the microsoft-office updated to the latest, and create a new cask "microsoft-office-2016" for previous version. What do you think? If you agree, how should I go about this?

**Comment by ryanturcotte** [comment]
> @ryanturcotte I think it's ideal to have the microsoft-office updated to the latest, and create a new cask "microsoft-office-2016" for previous version. What do you think? If you agree, how should I go about this?

This should be fine? I'm not a homebrew admin however, just somebody using it for computer installs.

**Comment by sscotth** [comment]
#54464 is more up to date

**Comment by andrewtaehoon** [comment]
This can be closed. Looks like #54464 is addressing this issue.

**Pull request closed without merging**
