### PR TITLE
Update fs-uae and create fs-uae-launcher

### PR DESCRIPTION
**Pull request by Kreeblah**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

This submission is a bit unusual.  The FS-UAE project split up what used to be included in a single DMG into two tarballs, per https://fs-uae.net/download.  The old URL that used to reflect stable updates stopped being updated at some point as well.

So, this submission splits the old cask into two that depend on each other.  That doesn't feel ideal, but given that the applications need to be installed together, it was the only thing that came to mind.  Additionally, the FS-UAE project is also providing ARM builds now, so I added logic to select those when applicable.

### CODE REVIEW

**Comment by Kreeblah** [comment]
It looks like the CI piece failed because of the cyclic dependency.  During my tests locally, I commented out the dependency since I was installing casks from a tree checked out from my cloned repo, and the existing cask installed an app bundle that conflicted with one of these.

So, I missed that check.  Are there any suggestions for how to better approach this?  I don't think Homebrew has a notion of metacasks or some such, which is what my first impulse would have been.

**Comment by miccal** [comment]
I think if we just add `depends_on cask: "fs-uae-launcher"` to the original `fs-uae` Cask then this should be fine.

**Comment by bevanjkay** [comment]
@miccal CI is failing on this because of `launcher` in the token. This may be a special case, as the cask needs to be split in two. 

@Kreeblah Is the launcher required to be able to use the emulator? If so then they probably should depend on each other, if the launcher isn't required then the current is okay.

**Comment by Kreeblah** [comment]
@bevanjkay - It . . . depends.  The launcher is what's typically used to generate config files for the emulator (the emulator itself doesn't have the ability to do that), which are required to use it.  It's possible (if tedious and error-prone) to write them by hand, though, so I see valid arguments either way on whether the launcher is considered required for the emulator to function.

**Comment by miccal** [comment]
> @miccal CI is failing on this because of `launcher` in the token. This may be a special case, as the cask needs to be split in two.

Yes it is a special case -- same thing happens in the `eve-launcher` Cask:
```
|-> brew audit --cask --appcast --online --new-cask eve-launcher
==> Downloading https://binaries.eveonline.com/EveLauncher-1952584.dmg
######################################################################## 100.0%
audit for eve-launcher: failed
 - cask token mentions launcher
Error: 1 problem in 1 cask detected
```

**Comment by miccal** [comment]
I am going to merge this and see how we go.

Thanks @Kreeblah.

**Pull request merged**
