### PR TITLE
hstracker: add livecheck

### PR DESCRIPTION
**Pull request by moonfruit**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by moonfruit** [comment]
Thanks, @miccal !

**Review by miccal — APPROVED** [review]

**Comment by reitermarkus** [comment]
@moonfruit, can you review the GitHub livechecks you added so far to check if it is possible to use the `:git` strategy? Also please limit any new livecheck submissions for now to non-GitHub ones since all GitHub ones are already worked on in https://github.com/Homebrew/homebrew-cask/pull/95419.

**Comment by moonfruit** [comment]
OK, I will look into it. @reitermarkus

**Comment by moonfruit** [comment]
for:
```ruby
livecheck do
  url :url
  strategy :git
end
```
`brew livecheck -d hstracker` output:
```
Cask:             hstracker
Livecheckable?:   No

URL:              https://github.com/HearthSim/HSTracker/releases/download/1.7.8/HSTracker.app.zip
URL (processed):  https://github.com/HearthSim/HSTracker.git
Strategy:         Git

Matched Versions:
0.1.7, 0.10.177, 0.10.179, 0.10.183, 0.10.194, 0.11.235, 0.11.246, 0.11.248, 0.11.257, 0.11.264, 0.12.292, 0.12.297, 0.12.300, 0.12.305, 0.12.315, 0.12.321, 0.12.347, 0.12.348, 0.12.360, 0.12.365, 0.13.428, 0.13.436, 0.13.448, 0.13.466, 0.13.474, 0.14, 0.14.1, 0.16, 0.16.1, 0.16.10, 0.16.11, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.16.7, 0.16.8, 0.16.9, 0.17, 0.17.2, 0.17.3, 0.17.4, 0.17.4.1, 0.18, 0.18.0.1243, 0.18.1.1274, 0.18.2, 0.18.2.1326, 0.18.3.1327, 0.18.4.1340, 0.18.5.1367, 0.19, 0.19.1, 0.19.2, 0.19.3, 0.2.17, 0.2.18, 0.20, 0.20.1, 0.3.24, 0.3.26, 0.3.27, 0.3.35, 0.3.40, 0.3.50, 0.4.58, 0.5.76, 0.6.106, 0.6.111, 0.6.113, 0.7.121, 0.7.123, 0.7.124, 0.8.134, 0.8.144, 0.9.145, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.5.0, 1.5.1, 1.5.1b, 1.5.1c, 1.5.2, 1.5.2a, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.6.0, 1.6.1, 1.6.10, 1.6.11, 1.6.13, 1.6.14, 1.6.15, 1.6.16, 1.6.17, 1.6.18, 1.6.19, 1.6.2, 1.6.21, 1.6.22, 1.6.23, 1.6.24, 1.6.25, 1.6.27, 1.6.28, 1.6.29, 1.6.3, 1.6.30, 1.6.31, 1.6.32, 1.6.33, 1.6.34, 1.6.35, 1.6.36, 1.6.37, 1.6.38, 1.6.4, 1.6.6, 1.6.7, 1.6.9, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 6b350eea272b791b4fb5
hstracker : 1.7.8 ==> 6b350eea272b791b4fb5
```

So if to use `:git` strategy, I must add `regex(/^(\d+(?:\.\d+)*)$/)` to the livecheck block.

**Comment by moonfruit** [comment]
Add the `livecheck`s which I added recently, they all not worked well with the default `:git` strategy.

**Comment by reitermarkus** [comment]
> So if to use `:git` strategy, I must add `regex(/^(\d+(?:\.\d+)*)$/)` to the livecheck block.

Yes, exactly.

> But `:github_latest` worked well.

Most of the time it will work fine, but we currently prefer `:git` to avoid hitting rate limits due to too many HTTP calls to `github.com`.

**Comment by moonfruit** [comment]
OK, I will make another pull request to use `:git` strategy.

**Pull request merged**
