### PR TITLE
Update r from 4.1.0 to 4.1.1

### PR DESCRIPTION
**Pull request by luispuerto**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by gwbrck** [comment]
I get an SHA256 mismatch with updating to 4.1.1 
Am I doing something wrong?

**Comment by luispuerto** [comment]
I have no idea what you are doing… 😝 Anyhow, after the merge, I was able to update without an issue. 
Screen Shot 2021-08-13 at 09 01 05

**Comment by luispuerto** [comment]
I just tried to reinstall, and you're right, there is a sha256 mismatch. Perhaps they re-uploaded the file?

**Comment by luispuerto** [comment]
I just did a pull request #109791

**Comment by luispuerto** [comment]
Screen Shot 2021-08-13 at 09 14 34

Yes, rebuild & re-uploaded the file after we updated the formula.

**Pull request merged**
