### PR TITLE
Update macx-dvd-ripper-pro to 6.2.0,20190116

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Merged this one by mistake. Reverting. Why change the version? It looks correct.

**Comment by ran-dall** [comment]
@vitorgalvao Either way if fine with me...

screen shot 2019-01-26 at 9 47 50 am

**Comment by vitorgalvao** [comment]
I downloaded it as well and it showed the previous version. Must be something on their end, then.

But if the shasum hasn’t changed, it’s best to not change the version so as to not get a shasaum-only PR later on.

**Comment by ran-dall** [comment]
> But if the shasum hasn’t changed, it’s best to not change the version so as to not get a shasaum-only PR later on.

Noted. Thanks.

**Comment by vitorgalvao** [comment]
Not a hard and fast rule, though, just *preferable*.

**Pull request merged**
