### PR TITLE
Add shim script for copyq 3.0.2

### PR DESCRIPTION
**Pull request by hluk**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> Hmm, the commit message not correct -- I used `cask-repair -e ...` -- it should be something like `Add shim script for copyq`.

`-e` does not change the commit message, it only opens the cask for editing before checkign everything else. You can’t change the commit message with `cask-repair` (and I don’t intend to add the feature).

**Comment by vitorgalvao** [comment]
Why is this change necessary? I don’t see a difference.

**Comment by hluk** [comment]
Symlinks doesn't work with Qt apps - when the symlink is executed the target app doesn't search the correct directories with libraries and in this specific case fails to load Cocoa Qt plugin.

**Comment by hluk** [comment]
BTW, I fixed the commit message.

**Comment by vitorgalvao** [comment]
Are you sure the `exec` is necessary? Also, use `/bin/bash`, that’s what `sh` is on macOS, anyway.

**Comment by gibfahn** [comment]
I can confirm that this fixes the error we were seeing before (e.g. https://github.com/hluk/CopyQ/issues/719#issuecomment-306408808).

Thanks @hluk

**Comment by hluk** [comment]
OK, I replaced `/bin/sh` with `/bin/bash`.

The `exec` is not needed but it replaces the bash process and probably saves a bit of memory.

**Review by vitorgalvao — APPROVED** [review]
Everything looks fine. Good to go when Travis passes.

**Pull request merged**
