### PR TITLE
Update intel-haxm from 7.5.1 to 7.5.2

### PR DESCRIPTION
**Pull request by robertleeblairjr**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by robertleeblairjr** [comment]
Not sure how to approach this without more information from the log for the silent installer. Passed test and install on my local machine. If this were just a hiccup in the Travis check, then I'll resubmit. Of course, I don't exactly recall but I believe I was told this fails quite often in Travis and has to be force pushed. But, I'll do some research to confirm.

**Comment by robertleeblairjr** [comment]
Close and reopen to start check. If it fails again, then I'll just toss it up to a maintainer needing to look and force if applicable.

**Comment by robertleeblairjr** [comment]
Adding the dependency for macOS and android-sdk which were specified in the prerequisites for Intel-HAXM wasn't the solution. I'll assume some environment permissions problem.

> Failure while executing; `/usr/bin/sudo -E -- env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/bin:/Users/travis/.gem/ruby/2.3.0/bin:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/intel-haxm/7.5.2/silent_install.sh` exited with 1. Here's the output: Silent installation failed, please see /private/tmp/haxm_silent_run.log for details!

**Comment by yurikoles** [comment]
Travis always fail to install this cask, just check the PRs history. The reason is that `haxm` requires hardware virtualization support, which is unavailable in Travis, since it runs check in a VM itself.

**Comment by yurikoles** [comment]
So depending on android SDK maybe unnecessary, since it worked before without it. You just need Android SDK to actually use it, but a lot of people install Android SDK trough Android Studio.

**Comment by yurikoles** [comment]
@vitorgalvao,
Could you please look into this PR?
Thanks in advance!

**Comment by robertleeblairjr** [comment]
> Travis always fail to install this cask, just check the PRs history. The reason is that `haxm` requires hardware virtualization support, which is unavailable in Travis, since it runs check in a VM itself.

Thanks. Yep, I thought that I recalled reading Travis failed with this cask but I didn't do any research on older closed PRs. I just left the dependency since it was a prerequisite, even though, I did recall that HAXM would fail to start if the SDK wasn't present. I know some people don't install Studio though. But, it would be redundant and the cask had installed previously without having the SDK present. Appreciate the assistance and corrections to it.

**Pull request merged**
