### PR TITLE
beaker: update to version 1.3-0-g7f23794

### PR DESCRIPTION
**Pull request by FranklinChen**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 85a6ae785deff38c013717e105fbaf4646cfef2c to keep commit history cleaner. Your contribution is still credited to you.

**Comment by FranklinChen** [comment]
Ah, I just realized... is this because I accidentally reused an old branch of mine? I will clean up unused branches now to avoid this in the future.

**Comment by vitorgalvao** [comment]
No, your contribution was spot on, absolutely nothing wrong with it. It’s just that using the merge button makes history a bit of a mess, with a ton on merge commits. Doing it this way makes history cleaner.

**Comment by FranklinChen** [comment]
OK. I removed my unused branches anyway, as good practice.

**Pull request closed without merging**
