### PR TITLE
Update Swiftcord to v0.4.3

### PR DESCRIPTION
**Pull request by cryptoAlgorithm**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you rebase your branch on master? It seems to be very far behind.

**Comment by cryptoAlgorithm** [comment]
Screenshot 2022-07-11 at 7 48 33 PM

@SMillerDev I actually did it right before submitting this PR, don't know why the branch is still behind...

**Comment by SMillerDev** [comment]
Merging isn't the same as rebasing though. Rebasing would allow you to drop any commits that exist in master already while merging master into your branch just adds the commits from master (and blocks CI from automatically merging your PR).

**Comment by cryptoAlgorithm** [comment]
Is there any way to rebase from the gh website? or do I have to use some git command?

**Comment by cryptoAlgorithm** [comment]
@SMillerDev I've just rebased my branch onto master. Now there's only one commit in this PR :)

**Review by SMillerDev — APPROVED** [review]
Thanks @cryptoAlgorithm  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by SMillerDev** [comment]
Well, any review needs approval to be merged. But if your pull request has a merge commit it will need manual action from a maintainer even after it has been approved.

**Pull request closed without merging**
