### PR TITLE
Add micromamba cask

### PR DESCRIPTION
**Pull request by YYYasin19**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by YYYasin19** [comment]
👋 Hey

Currently the only thing missing is `brew audit --cask micromamba` which returns
```
audit for micromamba: failed
 - exception while auditing micromamba: undefined method `downcase' for nil:NilClass
Error: 1 problem in 1 cask detected
```

How would I go about successfully debugging this? I am also new to the Ruby world, so hints are strongly appreciated.

**Comment by aaronliu0130** [comment]
I think you lied when you said brew style --fix reports no offenses. I ran your file through the command.
<details>
   <summary> Here are your offenses. </summary>
   <pre>
micromamba.rb:1:1: C: [Corrected] Magic comments should be in the following order: encoding, typed, warn_indent, frozen_string_literal.
# frozen_string_literal: true
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
micromamba.rb:1:1: C: [Corrected] No Sorbet sigil found in file. Try a typed: false to start (you can also use rubocop -a to automatically add this).
cask "micromamba" do
^^^^
micromamba.rb:1:1: C: [Corrected] Missing frozen string literal comment.
cask "micromamba" do
^
micromamba.rb:2:1: C: [Corrected] Magic comments should be in the following order: encoding, typed, warn_indent, frozen_string_literal.
# typed: false
^^^^^^^^^^^^^^
micromamba.rb:3:1: C: [Corrected] Add an empty line after magic comments.
cask "micromamba" do
^
micromamba.rb:4:1: C: [Corrected] Use 2 (not 3) spaces for indentation.
   version "0.25.1"
^^^
micromamba.rb:7:4: C: [Corrected] Inconsistent indentation detected.
   arch = Hardware::CPU.intel? ? "osx-64" : "osx-arm64"
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
micromamba.rb:8:4: C: [Corrected] Inconsistent indentation detected.
   if arch == "osx-64" ...
   ^^^^^^^^^^^^^^^^^^^
micromamba.rb:14:4: C: [Corrected] Inconsistent indentation detected.
   url "https://micro.mamba.pm/api/micromamba/#{arch}/#{version}"
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
micromamba.rb:15:4: C: [Corrected] Inconsistent indentation detected.
   name "micromamba"
   ^^^^^^^^^^^^^^^^^
micromamba.rb:16:4: C: [Corrected] Inconsistent indentation detected.
   desc "Tiny Version of Mamba: The Fast Cross-Platform Package Manager"
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
micromamba.rb:17:4: C: [Corrected] Inconsistent indentation detected.
   homepage "www.github.com/mamba-org/mamba"
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
micromamba.rb:19:4: C: [Corrected] Inconsistent indentation detected.
   binary "bin/micromamba"
   ^^^^^^^^^^^^^^^^^^^^^^^
micromamba.rb:21:4: C: [Corrected] Inconsistent indentation detected.
   uninstall delete: "$(brew --prefix)/bin/micromamba"
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
micromamba.rb:23:4: C: [Corrected] Inconsistent indentation detected.
   caveats <<~EOS
   ^^^^^^^^^^^^^^
micromamba.rb:24:1: C: [Corrected] Use 2 spaces for indentation in a heredoc.
micromamba.rb:31:2: C: [Corrected] end at 31, 1 is not aligned with cask "micromamba" do at 1, 0.
 end
 ^^^
micromamba.rb:33:1: C: [Corrected] EOS is not aligned with caveats <<~EOS or beginning of method definition.
   EOS
^^^^^^

1 file inspected, 18 offenses detected, 18 offenses corrected
   </pre>
</details>
Here's the cask with correct styling:
```rb
# typed: false
# frozen_string_literal: true

cask "micromamba" do
  version "0.25.1"

  arch = Hardware::CPU.intel? ? "osx-64" : "osx-arm64"
  if arch == "osx-64"
    sha256 "bd80ed9cb39748a40ae7dfd124aa18e453bf4793e281daf687710c81272e8be1"
  else
    sha256 "b39fb2f9f2bed41c5ad885f41f49ba751a4ba5ee01ee96ca8293a84aa603d1b2"
  end

  url "https://micro.mamba.pm/api/micromamba/#{arch}/#{version}"
  name "micromamba"
  desc "Tiny Version of Mamba: The Fast Cross-Platform Package Manager"
  homepage "www.github.com/mamba-org/mamba"

  binary "bin/micromamba"

  uninstall delete: "$(brew --prefix)/bin/micromamba"

  caveats <<~EOS

    Please run the following to setup your shell:
      micromamba shell init -s <your-shell> -p ~/micromamba
    and restart your terminal.


    For more information, see:#{" "}
      https://mamba.readthedocs.io/en/latest/installation.html#micromamba

  EOS
end
```

**Comment by aaronliu0130** [comment]
Also, this appears to be open-source and cli-only, so this would be a better fit for homebrew-core.

**Comment by YYYasin19** [comment]
Hey @aaronliu0130, thanks for the feedback.
I'm somewhat confused because I certainly ran style fixing and when I run it again in the root folder of the repo with `brew style --fix Casks/micromamba.rb` I still get no offenses and no changes.

And yes, I was initially going to include it in homebrew-core, but had problems with translating the build process and then found mambaforge here as well.

**Comment by aaronliu0130** [comment]
You could just run `brew style --fix micromamba`. The command accepts cask/formula arguments.

Could you commit the correct styling and then let the CI try again?

**Comment by YYYasin19** [comment]
Running `brew style --fix micromamba` does not change anything for me and I therefore can't commit any changes.
I have `Homebrew 3.5.8-28-gea981ad` running

**Comment by aaronliu0130** [comment]
just replace the file with the one i sent you here

> I think you lied when you said brew style --fix reports no offenses. I ran your file through the command.
> 
>  Here are your offenses.
> Here's the cask with correct styling:
> ```ruby
> # typed: false
> # frozen_string_literal: true
> 
> cask "micromamba" do
>   version "0.25.1"
> 
>   arch = Hardware::CPU.intel? ? "osx-64" : "osx-arm64"
>   if arch == "osx-64"
>     sha256 "bd80ed9cb39748a40ae7dfd124aa18e453bf4793e281daf687710c81272e8be1"
>   else
>     sha256 "b39fb2f9f2bed41c5ad885f41f49ba751a4ba5ee01ee96ca8293a84aa603d1b2"
>   end
> 
>   url "https://micro.mamba.pm/api/micromamba/#{arch}/#{version}"
>   name "micromamba"
>   desc "Tiny Version of Mamba: The Fast Cross-Platform Package Manager"
>   homepage "www.github.com/mamba-org/mamba"
> 
>   binary "bin/micromamba"
> 
>   uninstall delete: "$(brew --prefix)/bin/micromamba"
> 
>   caveats <<~EOS
> 
>     Please run the following to setup your shell:
>       micromamba shell init -s <your-shell> -p ~/micromamba
>     and restart your terminal.
> 
> 
>     For more information, see:#{" "}
>       https://mamba.readthedocs.io/en/latest/installation.html#micromamba
> 
>   EOS
> end
> ```

**Comment by YYYasin19** [comment]
I just applied your comment to the file directly. The only missing thing seems to be the newline at the end, though I would've guessed that it is correct _with_ newline at the end.

**Comment by miccal** [comment]
Thank you @YYYasin19.

**Review by miccal — APPROVED** [review]

**Comment by YYYasin19** [comment]
@miccal Thanks for the changes, didn't know about the `on_intel` syntax! 🎉 

Two questions:

- What was the solution of the error I encountered with the audit command? 
```undefined method `downcase' for nil:NilClass```

- What do you think about extended cleanup on install to help setup a clean environment? This could be, for example, a `zap` stanza so that users who want a clean environment can remove everything
```rb
zap trash: ["$MAMBA_ROOT_PREFIX"]
```
Alternatively, the `uninstall_preflight` stanze could include `micromamba shell deinit` or atleast a `micromamba clean`.

**Comment by miccal** [comment]
> @miccal Thanks for the changes, didn't know about the `on_intel` syntax! 🎉
> 
> Two questions:
> 
> * What was the solution of the error I encountered with the audit command?
>   `` undefined method `downcase' for nil:NilClass ``

I believe it was because you were missing the `https://` fro the `homepage`.

> * What do you think about extended cleanup on install to help setup a clean environment? This could be, for example, a `zap` stanza so that users who want a clean environment can remove everything
> 
> ```ruby
> zap trash: ["$MAMBA_ROOT_PREFIX"]
> ```
> 
> Alternatively, the `uninstall_preflight` stanze could include `micromamba shell deinit` or atleast a `micromamba clean`.

This would be best in a `zap`.

**Comment by YYYasin19** [comment]
How would you get environment variables inside the `zap` stanza?
```zap trash: ["$MAMBA_ROOT_PREFIX"]``` does not seem to work

**Comment by miccal** [comment]
> How would you get environment variables inside the `zap` stanza?
> `zap trash: ["$MAMBA_ROOT_PREFIX"]` does not seem to work

I am not too sure -- perhaps @carlocab may be able to suggest a way?

**Comment by carlocab** [comment]
You can use `ENV["FOO"]`, but that environment variable will probably get sanitised by `brew`. Is it meant to be something a user sets?

**Comment by carlocab** [comment]
> Also, this appears to be open-source and cli-only, so this would be a better fit for homebrew-core.
> 
> 
> 
> From [Acceptable Casks](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask):
> 
> > * The app is both open-source and CLI-only (i.e. it only uses the binary artifact). In that case, and [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core) as a formula that builds from source. If it is rejected, you may then try again as a cask (link us to the issue so we can see the discussion and reasoning for rejection).

I agree with this, FWIW.

**Comment by YYYasin19** [comment]
> You can use ENV["FOO"], but that environment variable will probably get sanitised by brew. Is it meant to be something a user sets?

That would have been my solution as well; from what I've understood $MAMBA_ROOT_PREFIX points to where the configuration is, i.e. all the environments and caches etc.

**Comment by jonashaag** [comment]
Just tried this cask, it works great but I need to manually allow the third-party binary in System Preferences -> Security & Privacy. Is that expected?

**Comment by YYYasin19** [comment]
Good question!
Using `--no-quarantine` which, temporarily, disables macOS's gatekeeper hook and should allow one to use the binary directly.

Maybe this should be noted during the installation instructions of `micromamba` at the official documentation, though I guess its more of a brew issue / knowledge.

**Comment by vvzen** [comment]
Hi @YYYasin19 ,

sorry to bump into this thread, but I' trying to install micromamba via `brew` and I'm getting a sha256 mismatch:
```bash
$ brew install --cask micromamba
Error: Cask 'micromamba' definition is invalid: invalid 'sha256' value: {:arm=>"b39fb2f9f2bed41c5ad885f41f49ba751a4ba5ee01ee96ca8293a84aa603d1b2", :intel=>"bd80ed9cb39748a40ae7dfd124aa18e453bf4793e281daf687710c81272e8be1"}
```

is this a known mismatch and if so, what would be the fix ? The formula is here: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/micromamba.rb 
Thanks!

**Pull request merged**
