### PR TITLE
Update noxappplayer from 3.0.1.0,20200414:e34827a24f3b4c16b3d61a88eda7fc43 to 3.0.2.0,20200422:02062aa2192b4490aa121f60ba82cf3b

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
bah this is now an installer. when will they learn?

@vitorgalvao is there a way to just extract the ZIP in NoxAppPlayerInstaller.app/Contents/MacOS/NoxAppPlayer.zip?

**Comment by suschizu** [comment]
yes - I've seen it :(

**Comment by vitorgalvao** [comment]
> @vitorgalvao is there a way to just extract the ZIP in NoxAppPlayerInstaller.app/Contents/MacOS/NoxAppPlayer.zip?

Yes. We’d need to write the code ourselves in a `preflight` block.

**Comment by core-code** [comment]
it seems `container nested `works too :)

**Comment by vitorgalvao** [comment]
> it seems `container nested `works too :)

Smart!

**Pull request merged**
