### PR TITLE
Fix `url` stanza's comments.

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by adidalal** [comment]
Went through changes, all look great. Thanks for everything!

**Comment by adidalal** [comment]
@reitermarkus Didn't see that you had more changes - would you mind adding them in a new PR? (everything after `Fix `url` stanza comment for epub-2-pdf.`)

**Comment by reitermarkus** [comment]
@adidalal, I don't think I had any more changes after `epub-2-pdf`.

**Comment by adidalal** [comment]
Excellent, then with the 3 fixes I just pushed, https://github.com/caskroom/rubocop-cask/pull/26 should now be good to go

**Pull request merged**
