### PR TITLE
Update doomsday-engine to 2.0.3 (rollback to stable)

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by claui** [comment]
Thanks @brianmorton!

[The upstream page says 2.1.0 is a nightly, unstable version.](http://dengine.net/macos) Shouldn’t this Cask be downgraded to 2.0.3 instead? And have the nightly 2.1.0 builds over on homebrew-cask-versions?

**Comment by brianmorton** [comment]
the appcast `https://sourceforge.net/projects/deng/rss` didn't indicate anything about nightlies vs stables... so maybe we should roll this back to `2.0.3` AND update the appcast to be http://dengine.net/macos

Thoughts?

**Comment by claui** [comment]
> the appcast `https://sourceforge.net/projects/deng/rss` didn't indicate anything about nightlies vs stables

There’s [a second feed](http://api.dengine.net/1/builds/feed). The summary element contains a (somewhat) parseable stable/unstable status but our appcast feature can’t select elements, or can it?

> update the appcast to be http://dengine.net/macos

I’m worried that the site is updated far too often (see the `time` elements in the page source).

Given the (sometimes) year-long hiatus between stable releases, maybe we should drop the appcast.

**Comment by brianmorton** [comment]
I would prefer to update to the second appcast you listed. "We" (being HBC) don't do anything really with the appcasts, by on my side for the automation I do extensive stuff with them... with the eventuality being automatic updates (customized to each cask).

**Comment by vitorgalvao** [comment]
> but our appcast feature can’t select elements, or can it?

Nope. It’s basically just a string.

**Comment by claui** [comment]
Thanks @brianmorton and @vitorgalvao!

**Pull request merged**
