### PR TITLE
Update wechat from 2.4.2.18 to 2.5.0.17

### PR DESCRIPTION
**Pull request by linbo0518**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
seems another case of different download in different countries. should we try to use a country-code stanza to work around the issue?

**Comment by vitorgalvao** [comment]
> seems another case of different download in different countries. should we try to use a country-code stanza to work around the issue?

Let’s try anything that might fix it. This cask has the same issue every single release.

**Comment by core-code** [comment]
ok lets try that the next time, but i think the update should be available globally now

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/90308.

**Pull request closed without merging**
