### PR TITLE
dosbox-x: use sdl2 version instead of the outdated sdl1 version

### PR DESCRIPTION
**Pull request by CarterLi**
As SDL1 is in maintainance mode, SDL2 version [is more actively tested and bug free](https://github.com/joncampbell123/dosbox-x/issues/4515).

---

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Ping @mistydemeo

**Comment by mistydemeo** [comment]
While I agree the SDL2 version seems a bit better right now, the official wiki does recommend the SDL1 version as the default: https://github.com/joncampbell123/dosbox-x/blob/master/INSTALL.md#macos-packages-portable

In casual use, the SDL2 version works a bit better in some senses, like the bug you highlighted, but does have a strange lag on exit the SDL1 version is missing. We should probably ask the author which version they feel is best to expose as the default.

**Comment by miccal** [comment]
Ping @joncampbell123 for there thoughts.

**Comment by CarterLi** [comment]
unstale

**Comment by SMillerDev** [comment]
Closing since it's against upstreams recommendation.

**Pull request closed without merging**
