### PR TITLE
jslegendre-themeengine 1.0.0,118 (new cask)

### PR DESCRIPTION
**Pull request by SoCuul**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

~~Additionally, **if adding a new cask**:~~

~~- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).~~
~~- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).~~
~~- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).~~
~~- [ ] `brew audit --cask --new <cask>` worked successfully.~~
~~- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.~~
~~- [ ] `brew uninstall --cask <cask>` worked successfully.~~

---

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Thanks for opening this, which of the following [criteria](https://docs.brew.sh/Acceptable-Casks#forks-and-apps-with-conflicting-names) does this cask meet?

> Forks must have the vendor’s name as a prefix on the cask’s filename and token. If the original software is discontinued, forks still need to follow this rule so as to not be surprising to the user. There are two exceptions which allow the fork to replace the main cask:
> 
> The original discontinued software recommends that fork.
> The fork is so overwhelmingly popular that it surpasses the original and is now the de facto project when people think of the name.
> For unrelated apps that share a name, the most popular one (usually the one already present) stays unprefixed. Since this can be subjective, if you disagree with a decision, open an issue and make your case to the maintainers.
>

**Comment by SoCuul** [comment]
I think it would fall under the `The fork is so overwhelmingly popular that it surpasses the original and is now the de facto project when people think of the name` case, but I'm not sure.

The [original repo](https://github.com/jslegendre/ThemeEngine) has more stars and forks than the fork, but it has not been maintained for over 4 years. Looking into issues people tell you to navigate to the new fork. This new fork has less stars/forks but is a version of this software that is actively maintained and used by individuals.

**Comment by SMillerDev** [comment]
Let's add it with a vendor name, and we can direct people to consider that from the old cask

**Comment by SoCuul** [comment]
> Let's add it with a vendor name, and we can direct people to consider that from the old cask

I was under the assumption that discontinued casks were not allowed to exist on the repo. Did I misread the docs?

**Comment by SMillerDev** [comment]
> I was under the assumption that discontinued casks were not allowed to exist on the repo. Did I misread the docs?

If it's actively discontinued, yes. If it's not maintained actively... we can deprecate it. 

We also don't want to install a version of software people were not expecting, so we should only replace a cask source if it is abundantly clear that nobody could possibly want the original source.

**Comment by SoCuul** [comment]
> If it's actively discontinued, yes. If it's not maintained actively... we can deprecate it.

The [last release](https://github.com/alexzielenski/ThemeEngine/releases/tag/1.0.0(111)) was 6 years ago, and the last commit was over 4 years ago.

**Comment by SMillerDev** [comment]
> The [last release](https://github.com/alexzielenski/ThemeEngine/releases/tag/1.0.0(111)) was 6 years ago, and the last commit was over 4 years ago.

And yet, it is not explicitly discontinued so deprecating as `:unmaintained` is the clearest signal to users of the status of it.

**Comment by SoCuul** [comment]
> > The [last release](https://github.com/alexzielenski/ThemeEngine/releases/tag/1.0.0(111)) was 6 years ago, and the last commit was over 4 years ago.
> 
> And yet, it is not explicitly discontinued so deprecating as `:unmaintained` is the clearest signal to users of the status of it.

Sorry for the late reply! I see what you're saying, sounds good.

**Comment by SoCuul** [comment]
I've changed the formula to include the fork author's name. Would this meet the requirements? @SMillerDev

**Comment by bevanjkay** [comment]
@SoCuul It's close, the fork author should be first in the token.

**Comment by SoCuul** [comment]
> @SoCuul It's close, the fork author should be first in the token.

Does this look good?

**Comment by SoCuul** [comment]
@SMillerDev is anything else needed?

**Comment by SMillerDev** [comment]
It needs to pass CI, so there are still some adjustments needed

**Review by p-linnane — APPROVED** [review]

**Comment by SoCuul** [comment]
Thanks!

**Comment by SoCuul** [comment]
@SMillerDev fixed the naming

**Review by miccal — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @SoCuul.

**Pull request merged**
