### PR TITLE
Update wwdc to 5.0.3

### PR DESCRIPTION
**Pull request by jpsim**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
There was a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) when you submitted. It contains [steps that must be followed](https://raw.githubusercontent.com/caskroom/homebrew-cask/master/.github/PULL_REQUEST_TEMPLATE.md).

If you were not presented a template, you may have submitted via a CLI tool (likely [`hub`](https://hub.github.com/)). If that was the case, you may wish to see if the tool has a way to let you use the template (`hub` [seems to have already implemented it](https://github.com/github/hub/issues/1118), so you may be using an old version).

Alternatively, you may wish to [use `cask-repair`](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask). It takes care of all of this for you.

Everything seems fine with this submission so I’ll go ahead and merge it, but do please fill the template next time.

**Comment by vitorgalvao** [comment]
Travis CI detected errors that should have been caught by `audit` and `style --fix` commands. I’ve already fixed them.

Next time you make a submission, please double check those before ticking the boxes. We need to know if the error messages aren’t clear enough — which made you miss them — and we need to improve them. Alternatively, if no error messages were shown it means there’s something wrong we need to fix.

It’s important to ensure those commands work, as they save both CI time and maintainer time.

Thank you for the contribution!

**Comment by jpsim** [comment]
Thanks! And actually I didn't tick those boxes, the `cask-repair` tool that's referenced in you CONTRIBUTING.md file did that automatically.

**Comment by vitorgalvao** [comment]
`cask-repair` makes those checks and warns you about what you need to fix as well.

**Comment by jpsim** [comment]
I'll be sure to check that next time. If `cask-repair` makes the checks, why does it still check the boxes when filing the PR if the checks presumably failed? Is there an issue tracking that?

**Comment by vitorgalvao** [comment]
Because in the end it asked you if everything was alright and you answered “yes”.

`cask-repair` is simply a script; a tool to make your work easier. It holds your hand but there are legitimate cases where you can override it. It’s the responsibility of the user to read the warnings it gives and act accordingly; it only automates what it can.

**Comment by jpsim** [comment]
All right then I'll be more cautious in the future

**Pull request merged**
