### PR TITLE
Update teamviewer from 15.26.5 to 15.27.3

### PR DESCRIPTION
**Pull request by tiiiecherle**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
```
Some packages are still installed, add them to uninstall pkgutil:
com.teamviewer.AuthorizationPlugin
```

**Comment by tiiiecherle** [comment]
@bevanjkay Thanks, I updated the commit.

**Comment by bevanjkay** [comment]
Thank you @tiiiecherle

**Comment by LeeBinder** [comment]
Hi @bevanjkay Not sure if this only occurs in Catalina: I had installed Teamviewer via brew a long time ago and always kept it updated via `brew upgrade --cask teamviewer` in my `update apps` script. Some weeks ago I realized that that would only download the latest updater to `/usr/local/Caskroom/teamviewer/##.##.#/Install TeamViewer.app`. This already happened at least with the previous update #118326.

I uninstalled completely, reinstalled via **brew install --cask teamviewer** - same thing.

Latest Xcode command line tools for Catalina. All other apps upgrade fine, only Teamviewer misbehaves.

Any idea?

**Comment by bevanjkay** [comment]
@LeeBinder If you have a look at this issue here - https://github.com/Homebrew/homebrew-cask/issues/118316 - we have had to set Teamviewer to manually install and uninstall on Catalina.

**Comment by LeeBinder** [comment]
Oh OK - I've seen the uninstall issue but wasn't aware that it led to also blocking install - thanks for the pointer.

Highly odd. Wonder which left-over module exactly is causing this issue.

**Comment by bevanjkay** [comment]
@LeeBinder Homebrew will download the new installer for you, but you will need to run it manually.

```bash
open "/usr/local/Caskroom/teamviewer/15.27.3/Install TeamViewer.app/Contents/Resources/Install TeamViewer.pkg"
```

**Comment by LeeBinder** [comment]
Yes, I've seen it in the install log. What I meant is if it's knows which left-over file(s) from brew uninstall is causing Catalina to not boot anymore then.

**Pull request merged**
