### PR TITLE
Remove openclonk

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Also, I renamed the file.

### CODE REVIEW

**Comment by commitay** [comment]
Weird that the duplicate warning didn't occur with the first build.

**Comment by brianmorton** [comment]
I would actually probably chill on this, as there is an upstream issue with `8.0` not working at all on macOS right now.

**Comment by commitay** [comment]
@brianmorton Can you post a link please?

**Comment by vitorgalvao** [comment]
@brianmorton Please revert the name. It followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).

**Comment by commitay** [comment]
@vitorgalvao `openclonk-darwin-amd64-clang`?

**Comment by vitorgalvao** [comment]
Let’s remove that cruft, on second thought. Seems like we consistently do (though it’s not in the reference). But the `app` needs to go, since we have a very specific rule for that suffix.

**Comment by brianmorton** [comment]
https://github.com/openclonk/openclonk/issues/63 **8.0 build failure on macOS**

It seems they build the macOS binary on Linux but nobody checked that it actually worked. I just tried it and it crashes after launch.

**Comment by brianmorton** [comment]
@vitorgalvao it was not immediately clear to me on your token reference page why naming this cask "openclonk" is a bad idea or invalid in some way... so I'm more inclined to just delete the PR and if anybody cares they can sort it out rather than going through all of your rules to try and find a name you like :)

**Comment by vitorgalvao** [comment]
I’ve already fixed the name.

The reasons the strict rules exist are [enumerated at the top of the document](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md#purpose). We had a serious duplicates problem in the past, and the token reference solved that. It continues to this day to prevent duplicates.

**Comment by brianmorton** [comment]
I understand that, but there was seemingly no issue with it being called `openclonk` which is what I renamed it to... and your commit on the PR now supports that so you can hopefully understand why I'm confused. You requested I rename a file in a PR, and then you added a commit to the PR setting the name to what I had originally set it to...

You may have "strict rules" about a bunch of things, but this is open source. I will do my best to help, but if contributing becomes a big PITA over simple stuff likes names, I probably just won't send the PR.

**Comment by vitorgalvao** [comment]
> `openclonk` which is what I renamed it to...

No, you renamed it to `openclonk-app`. [The `-app` suffix is reserved for a very specific case](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md#with-a-formula) so I removed it.

> and your commit on the PR now supports that

Like I said, “[on second thought](https://github.com/caskroom/homebrew-cask/pull/43678#issuecomment-363261571)”.

> but if contributing becomes a big PITA over simple stuff likes names

It may look simple to you, but it’s not for the people who have to maintain the project day in and day out. Again, not caring about the tokens brought us a lot of inconsistency and extra work in the past. It may seem frivolous to you, but I went through it and know it is not.

> I will do my best to help

And do know we all greatly appreciate your PRs. Our contributors are highly valued.

> but this is open source

Open-source doesn’t mean “take what I’ve done and be glad I even contributed”. I’m reminded of [the puppy analogy](https://twitter.com/ncoghlan_dev/status/598146064508538880). If a user submits PRs that are not up to the standards, open-source contributors are in no obligation to merge them. I’d rather have less users submitting good PRs than more users submitting sloppy PRs. The former makes a project go forward, while the latter makes it untenable.

Consistency and clear rules make projects stronger. This is open, not a free-for-all.

And once more, your contributions are valued. Like every other contributor, if you stick with us, the rules eventually become second-nature and make sense.

**Comment by vitorgalvao** [comment]
> `openclonk` which is what I renamed it to...

No, you renamed it to `openclonk-app`. [The `-app` suffix is reserved for a very specific case](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md#with-a-formula) so I removed it. I didn’t notice this already existed in HB and the rule was in fact correctly applied.

Which leads to the question: is there any point in having this in HBC, even?

> and your commit on the PR now supports that

Like I said, “[on second thought](https://github.com/caskroom/homebrew-cask/pull/43678#issuecomment-363261571)”.

> but if contributing becomes a big PITA over simple stuff likes names

It may look simple to you, but it’s not for the people who have to maintain the project day in and day out. Again, not caring about the tokens brought us a lot of inconsistency and extra work in the past. It may seem frivolous to you, but I went through it and know it is not.

> I will do my best to help

And do know we all greatly appreciate your PRs. Our contributors are highly valued.

> but this is open source

Open-source doesn’t mean “take what I’ve done and be glad I even contributed”. I’m reminded of [the puppy analogy](https://twitter.com/ncoghlan_dev/status/598146064508538880). If a user submits PRs that are not up to the standards, open-source contributors are in no obligation to merge them. I’d rather have less users submitting good PRs than more users submitting sloppy PRs. The former makes a project go forward, while the latter makes it untenable.

Consistency and clear rules make projects stronger. This is open, not a free-for-all.

And once more, your contributions are valued and well done. Like every other contributor, if you stick with us, the rules eventually become second-nature and make sense, or you may help us change the ones that don’t.

**Comment by commitay** [comment]
> No, you renamed it to openclonk-app

That was me.

**Comment by vitorgalvao** [comment]
> That was me.

Ah, I stand corrected! I thought it was weird that @brianmorton by chance got the rule right (which I initially though it was wrong).

Apologies on that front, @brianmorton. That explains that particular confusion.

**Comment by commitay** [comment]
> Which leads to the question: is there any point in having this in HBC, even?

The formula builds the app by default so not really. Remove it and see if anyone complains?

**Comment by vitorgalvao** [comment]
> Remove it and see if anyone complains?

Sounds good.

**Pull request merged**
