### PR TITLE
Update postman from 9.19.0 to 9.19.3

### PR DESCRIPTION
**Pull request by moonfruit**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by miccal** [comment]
I am going to go ahead and merge this, even though the internal version remains at `9.19.0`. We will need to keep an eye on this, though.

**Review by miccal — APPROVED** [review]

**Comment by bevanjkay** [comment]
@miccal It looks like it could be a bug upstream to me though, as we're now moving away from a versioned url to a non-versioned url with no benefit other than livecheck matching (despite the application not being updated).

**Comment by p-linnane** [comment]
@miccal @bevanjkay I've reached out to Postman support to inquire what's going on with this. Will update when I hear back.

**Comment by bevanjkay** [comment]
@p-linnane Thanks

I'll keep my local copy with the versioned url, and see if it comes back with future updates.

**Pull request merged**
