### PR TITLE
Update cleanshot from 3.4.2 to 3.4.3

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
@vitorgalvao seems walled now. we might have to remove it.

**Comment by vitorgalvao** [comment]
> seems walled now. we might have to remove it.

[Confirmed](https://github.com/Homebrew/homebrew-cask/pull/92596).

**Comment by vitorgalvao** [comment]
It came back alive, including the appcast.

https://twitter.com/CleanShot_app/status/1327161279707033600.

**Review by vitorgalvao — DISMISSED** [review]

**Review by miccal — APPROVED** [review]

**Pull request merged**
