### PR TITLE
Update camo-studio from 1.3.6,4830 to 1.3.7,5038

### PR DESCRIPTION
**Pull request by jane-remover**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Ping @aydenp -- has something changed in the installer script that you added in https://github.com/Homebrew/homebrew-cask/pull/100248?

**Comment by jamiebishop** [comment]
Hey! I'm a team member on Camo's Apple team. Ayden is taking a break from Camo work for the next month, but we've ticketed this installer script regression internally & will update you once a fix is identified.

**Comment by su-thomas** [comment]
@miccal can an `in progress` label be added? thanks

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/109735

**Pull request closed without merging**
