### PR TITLE
Update unity from 2020.1.17f1,9957aee8edc2 to 2021.1.3f1,4bef613afd59

### PR DESCRIPTION
**Pull request by exgphe**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Review by reitermarkus — DISMISSED** [review]

**Comment by cho-m** [comment]
May need to also update `unity-...` casks that `depends_on cask: "unity"`
```console
❯ rg 'depends_on.*unity' --files-with-matches
unity-webgl-support-for-editor.rb
unity-lumin-support-for-editor.rb
unity-linux-support-for-editor.rb
unity-macos-il2cpp-support-for-editor.rb
unity-android-support-for-editor.rb
unity-windows-support-for-editor.rb
unity-linux-il2cpp-support-for-editor.rb
unity-ios-support-for-editor.rb
unity-appletv-support-for-editor.rb
```

---

Livecheck regex pattern is going to be a bit more complicated.
`page.match` probably won't work since releases are ordered from old to new.
`page.scan` can work, but will also require fixing regex pattern.

Example 1: scan
```rb
    strategy :page_match do |page|
      page.scan(%r{/download_unity/(\h+)/MacEditorInstaller/Unity-(\d+(?:\.\d+)*[a-z]*\d*)\.pkg}i).map do |match|
        "#{match[1]},#{match[0]}"
      end
    end
```

Example 2: JSON.parse and regex match
```rb
    strategy :page_match do |page|
      JSON.parse(page)["official"].map do |release|
        "#{release["version"]},#{release["downloadUrl"][%r{/(\h+)/MacEditorInstaller/}, 1]}"
      end
    end
```

**Comment by cho-m** [comment]
Odd failure for CI that I don't see on macOS 11.3 running the same `audit` command.
```console
❯ brew audit --cask --appcast --online './Casks/unity.rb'
==> Downloading https://download.unity3d.com/download_unity/3737af19df53/MacEditorInstaller/Unity-2021.1.5f1.pkg
Already downloaded: /Users/cho-m/Library/Caches/Homebrew/downloads/677c53214dc9791a50373f36de44861769de271bab9adb6900889ab740933265--Unity-2021.1.5f1.pkg
audit for unity: passed
```
Will try another rebase to see if it helps.

**Review by miccal — APPROVED** [review]

**Pull request merged**
