### PR TITLE
Add new cask ```samplebrain```

### PR DESCRIPTION
**Pull request by sata1000000**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
>  brew audit --new-cask <cask> worked successfully.

It didn't, please fix the errors

**Comment by sq1000000** [comment]
> > brew audit --new-cask  worked successfully.
> 
> It didn't, please fix the errors

Any idea how to fix the error:
 ```macOS on ARM requires applications to be signed. Please contact the upstream developer to let them know they should sign their app.``` ? 
 I can't seem to find any documentation on it

**Comment by miccal** [comment]
Thank you for your submission @sq1000000, but we cannot accept it at this time because it does not pass our signature verification check:

> macOS on ARM requires applications to be signed. Please contact the upstream developer to let them know they should sign their app.

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if the developers sign their app in the future we would then be happy to consider adding this to `homebrew-cask`.

**Comment by SMillerDev** [comment]
> macOS on ARM requires applications to be signed. Please contact the upstream developer to let them know they should sign their app. ?
> I can't seem to find any documentation on it

What would you like documentation on? The message tells you exactly what to do and why.

**Pull request closed without merging**
