### PR TITLE
Update etcher to 1.0.0-beta.16

### PR DESCRIPTION
**Pull request by qiwenmin**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by jviotti** [comment]
Hi @qiwenmin ,

Etcher maintainer here! Thanks so much for adding Etcher to `brew cask`, I was just looking into it and found you've added it already.

Is there something we can do from our side to make updates more automatic? (so you don't have to create a PR changing `version` and `sha256` every time).

Also, Etcher has a built-in auto-update dialog that pops up when there is an update available, redirecting users to the website. How does this play with Cask? Do you think we should disable those auto-updates check if the app was installed as Cask?

**Comment by qiwenmin** [comment]
Hi @jviotti ,

I noticed google-chrome and evernote can upgrade themselves smoothly. And their casks' version is "latest". If Etcher can upgrade itself like them - without manually downloading, mounting .dmg image, dragging and dropping, maybe its cask can use the same way.

Many Apps do the auto-updates checking with the brew-cask upgrading. So auto-updates checking is OK, I think.

I don't know if there is a better way. I want to know also.

**Comment by jviotti** [comment]
Hi @qiwenmin ,

Thank you for your response! We plan to have auto-updates in Etcher at some point (other priorities pushed that aside for now) (see https://github.com/resin-io/etcher/issues/336), but definitely sounds like the way to go.

I guess the best way forward is to keep updating the Cask ourselves for now, and move to `latest` once we have auto-updates up and running.

Thanks a lot!

**Comment by qiwenmin** [comment]
@jviotti You are welcome!

**Pull request merged**
