### PR TITLE
Upgrade puppet-agent to 5.4.0-1

### PR DESCRIPTION
**Pull request by PeterFaiman**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by commitay — CHANGES_REQUESTED** [review]
Please restore the comments above the URLs

**Comment by PeterFaiman** [comment]
I had added /etc/puppetlabs to zap, but I removed it because it caused travis to fail.

What's the normal approach for removing root-owned config dirs?

**Comment by commitay** [comment]
`zap` is fine, the travis failure can be ignored.

**Comment by PeterFaiman** [comment]
I will add it back then.

**Comment by PeterFaiman** [comment]
I also restored the comments.

**Review by commitay — APPROVED** [review]

**Comment by commitay** [comment]
Thanks for the PR!

**Pull request merged**
