### PR TITLE
bananas 0.0.11

### PR DESCRIPTION
**Pull request by bobbymannino**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by khipp** [comment]
Thank you for your submission, @bobbymannino. We are unable to accept it at this time because it does not pass Homebrew's signature verification check:

> macOS on ARM requires applications to be signed. Please contact the upstream developer to let them know they should sign their app.

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if the developers sign their app in the future we would be happy to consider adding this to `homebrew-cask`.

**Comment by krehel** [comment]
Closed for same reason as #193571
---

Thank you for your submission, but we cannot accept it at this time because it does not pass our signature verification check that are a requirement for new submissions:

> macOS on ARM requires software to be signed. Please contact the upstream developer to let them know they should sign and notarize their software.

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if the developers sign their app in the future we would then be happy to consider adding this to homebrew-cask.

**Comment by gorillamoe** [comment]
Do you guys @khipp or @krehel know a way of doing that reliable in a CI? I worked on this yesterday, but seem to run into the same problem as some other users.

Notarizing can take up to 3 days, one user even reported it took them 14 days. So my idea is to fork the current notarizing package I'm using and then making it async and pass a webhook.

Once the webhook receives a successful response it would trigger another pipeline which then downloads the version, staples it and uploads it back to the according release.

Idk if this is possible, or of there is something easier to use for this, but I can't have a runner running on MacOS for 3 days (even if money wouldn't matter, I think the longest a GH runner can run is 24h or so).

**Comment by gorillamoe** [comment]
This approach would also mean, that I would mark the release as pre-release until the stapled version arrives..

**Comment by gorillamoe** [comment]
Okay, I think I figured out a workaround, v0.0.12 and notarized (in queue), but not stapled. Does that suffice?

**Pull request closed without merging**
