### PR TITLE
Add app "privatus" 6.3

### PR DESCRIPTION
**Pull request by singularitti**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by singularitti** [comment]
`brew audit` failed because
```
audit for privatus: failed
 - sweetpproductions.com does not match privatusapp.com, a `verified` parameter of the `url` has to be added.  See https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-verified
```
But I think I have followed the advice. Don't know what does that mean?

**Comment by singularitti** [comment]
Can this be merged?

**Review by vitorgalvao — APPROVED** [review]

**Comment by n-h** [comment]
Getting an error, that may be related?

On OSX Catalina:

Multiple errors, but the first one, for me, shows as
```
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/privatus.rb
Cask 'privatus' definition is invalid: 'url' stanza failed with: unknown keyword: verified
```

```
$ brew cask doctor
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 575225 (delta 1), reused 2 (delta 0), pack-reused 575215
Receiving objects: 100% (575225/575225), 240.94 MiB | 3.00 MiB/s, done.
Resolving deltas: 100% (409314/409314), done.
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/privatus.rb
Cask 'privatus' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/zeitgeist.rb
Cask 'zeitgeist' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/anka-build-cloud-registry.rb
Cask 'anka-build-cloud-registry' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/packetsender.rb
Cask 'packetsender' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/shotcut.rb
Cask 'shotcut' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/pdf-expert.rb
Cask 'pdf-expert' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/knockknock.rb
Cask 'knockknock' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/0-ad.rb
Cask '0-ad' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/daedalus-mainnet.rb
Cask 'daedalus-mainnet' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/recordit.rb
Cask 'recordit' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/spyder.rb
Cask 'spyder' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/videofusion.rb
Cask 'videofusion' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/runjs.rb
Cask 'runjs' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/stashcat.rb
Cask 'stashcat' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/stand.rb
Cask 'stand' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/gqrx.rb
Cask 'gqrx' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/oversight.rb
Cask 'oversight' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/anka-build-cloud-controller-and-registry.rb
Cask 'anka-build-cloud-controller-and-registry' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/anka-virtualization.rb
Cask 'anka-virtualization' definition is invalid: 'url' stanza failed with: unknown keyword: verified
Error: Cannot tap homebrew/cask: invalid syntax in tap!
$ 
```

**Comment by n-h** [comment]
It may, be related to this PR – not sure https://github.com/Homebrew/brew/pull/7772.

**Comment by singularitti** [comment]
I've seen your comments hidden, is your question solved? @n-h

**Comment by vitorgalvao** [comment]
> I've seen your comments hidden, is your question solved? @n-h

[Yes](https://github.com/Homebrew/brew/pull/7772#issuecomment-739323106). The questions are duplicates and have been resolved in the appropriate issue, which is why I hid them. It’s weird that Github requires you give a reason to hide a post, but then doesn’t show what the reason is.

**Pull request merged**
