### PR TITLE
Xamarin Mac 3.4.0.33 added as new cask

### PR DESCRIPTION
**Pull request by jacano**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not already refused in [closed issues].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Review by miccal — APPROVED** [review]

**Comment by commitay** [comment]
This requires `mono-mdk`

```
installer: Error - Xamarin.Mac requires the Mono framework to be installed (3.2 or later).
```

**Comment by vitorgalvao** [comment]
Isn’t this a new version of https://github.com/caskroom/homebrew-cask/blob/master/Casks/xamarin.rb?

**Comment by jacano** [comment]
No, it's a different product from xamarin. (https://developer.xamarin.com/guides/mac/)
I use it to develop OSX apps using C#

**Comment by jacano** [comment]
I also forget the mono-mdk dep. Thanks again for the catch @commitay

**Review by vitorgalvao — APPROVED** [review]

**Review by gtmgianni — CHANGES_REQUESTED** [review]
Appcast checkpoint has changed again.

**Comment by vitorgalvao** [comment]
Where are you getting `3.4.0.33` from? The latest in the appcast is `3.4.0.21`.

**Comment by commitay** [comment]
> Where are you getting `3.4.0.33` from?

https://releases.xamarin.com/stable-release-15-2/

The `appcast` is not showing any of the current versions for `mono-mdk`, `visual-studio`, etc.

**Comment by jacano** [comment]
I got this version from the previous appcast. Maybe, there was a downgrade in the stable version. Sounds weird but who knows ¯\_(ツ)_/¯

**Pull request merged**
