### PR TITLE
Added acrobat font pack

### PR DESCRIPTION
**Pull request by henryhchchc**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by henryhchchc** [comment]
Hi maintainers, I found that the pkg installation will work only if `adobe-acrobat-pro` or `adobe-acrobat-reader` is installed. Is it possible to make it depends on **either of the two packages**?

**Comment by bevanjkay** [comment]
@henryhchchc Thank you for your contribution. A couple of things to note here. This cask should be within the [`homebrew-cask-fonts`](https://github.com/Homebrew/homebrew-cask-fonts/) repository, and regarding the `depends_on`, the challenge there is that it will install the depended upon casks if this cask is installed - perhaps a caveat could be used instead.

**Comment by henryhchchc** [comment]
Thanks for the suggestions and I have the following concerns.
> This cask should be within the [`homebrew-cask-fonts`](https://github.com/Homebrew/homebrew-cask-fonts/) repository,

The casks in `homebrew-cask-fonts` are purely fonts (i.e., they install nothing but fonts). However this package will install some text processing plugins to Acrobat in addition to fonts. So I suggest keeping it at the `homebrew-casks` repository.

> and regarding the `depends_on`, the challenge there is that it will install the depended upon casks if this cask is installed - perhaps a caveat could be used instead.

I do agree that using a caveat is good, but not including the dependencies will fall the Homebrew CI (and this is the reason why the CI is failing now). I am wondering if there a workaround for it.

**Comment by miccal** [comment]
@henryhchchc we cannot add a conditional `depends_on cask` for `adobe-acrobat-pro` or `adobe-acrobat-reader`, so a `caveat` would be best here.

**Comment by miccal** [comment]
Looking at this further, it appears that you also need to install a specific version depending on the version of Adobe Reader one has installed.

Thank you @henryhchchc, but I am afraid that this is not suitable for inclusion as a Cask.

**Comment by henryhchchc** [comment]
Thank you for the information.

**Pull request closed without merging**
