### PR TITLE
Update local from 3.3.0 to 5.0.4

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
this looks like the same travis fuckup as in #68929

i don't think there is really anything wrong with the cask

**Comment by reitermarkus** [comment]
Rebasing onto master should fix the CI failure.

**Comment by reitermarkus** [comment]
Actually no, this needs to be merged first: https://github.com/Homebrew/homebrew-cask/pull/69014

**Comment by reitermarkus** [comment]
This should also be renamed to `local`.

**Pull request merged**
