### PR TITLE
Add ausweisapp2 formula

### PR DESCRIPTION
**Pull request by swsnr**
AusweisApp2 is the client application for electronic passports in
Germany, and supports passport logins to a variety of services such as
insurances.
### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:
- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by adidalal** [comment]
Should be in eid tap

**Comment by lunaryorn** [comment]
@adidalal Sorry, what?

**Comment by reitermarkus** [comment]
https://github.com/caskroom/homebrew-eid/

**Comment by lunaryorn** [comment]
I'm sorry, but what am I supposed to do now?  Shall I make a pull request against the repository?

**Comment by reitermarkus** [comment]
Yes, just submit it to the https://github.com/caskroom/homebrew-eid/ repo instead of this one.

**Comment by adidalal** [comment]
Rename it to `eid-de` (eid-country abbreviation)

**Comment by lunaryorn** [comment]
😒, see caskroom/homebrew-eid#13

**Comment by lunaryorn** [comment]
Uhm, will anyone take a look at the pull request?

**Pull request closed without merging**
