### PR TITLE
hma-vpn: rename from `hma-pro-vpn`

### PR DESCRIPTION
**Pull request by daeho-ro**
It seems that the pro version is not supported anymore.
https://github.com/Homebrew/homebrew-cask/blob/8166f6d33303cf75a0105c44bc46dce96729987a/Casks/h/hma-pro-vpn.rb

So, I add the generic version of hma-vpn.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [v] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [v] `brew audit --cask --online <cask>` is error-free.
- [v] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [v] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [v] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [v] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [v] `brew audit --cask --new <cask>` worked successfully.
- [v] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [v] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by bevanjkay** [comment]
Is this the same product, but renamed?

**Comment by bevanjkay** [comment]
I can see that in 2018 there is reference on the same download page to `HMA Pro VPN`, so I think it is safe to assume that this is the same app, just with a different name.
https://web.archive.org/web/20180929092636/https://www.hidemyass.com/en-au/download-vpn-mac

**Comment by daeho-ro** [comment]
Then should I update the existing one not add the new one, right? I am ready, just confirm please.

**Comment by krehel** [comment]
I would agree with the rename, not new.

**Comment by daeho-ro** [comment]
@krehel , Is this correct way to rename a package? I am not sure about this.

**Comment by krehel** [comment]
The goal is to update and rename `hma-pro-vpn` to `hma-vpn`?  If so, then the changes I've pushed should address that.

**Comment by daeho-ro** [comment]
That is right. I missed that!

**Comment by krehel** [comment]
No worries @daeho-ro - happy to help.  Thanks for taking the initiative to open this and get it moving forward.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
