### PR TITLE
Update postman from 9.12.2 to 9.13.0

### PR DESCRIPTION
**Pull request by ykursadkaya**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by ykursadkaya** [comment]
Version 9.13.0 appears on [Postman Release Notes](https://www.postman.com/downloads/release-notes/), and livecheck shows 9.12.2 and 9.13.0 from time to time. Postman's download URLs and release notes are really inconsistent, so it will pass  livecheck in 1 or 2 days.
You can close this MR or wait and re-run the CI.

**Comment by dalisoft** [comment]
Duplicate of #118687, @Homebrew does not merge until live check does not show latest version

**Comment by ykursadkaya** [comment]
> Duplicate of #118687, @Homebrew does not merge until live check does not show latest version

At the time between running the `brew livecheck` and `brew bump-cask-pr` command on my machine livecheck results are differ. It is really inconsistent

**Comment by dalisoft** [comment]
@ykursadkaya I think it is Postman team issue, not Homebrew

**Comment by ykursadkaya** [comment]
> @ykursadkaya I think it is Postman team issue, not Homebrew

@dalisoft oh yes, I mean Postman's download URLs, appcast APIs and release notes page are inconsistent even in the context. Release notes page shows one version download URL shows other :D

**Pull request closed without merging**
