### PR TITLE
Add Lightform.app v2.0.6.920

### PR DESCRIPTION
**Pull request by rarefakt**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @fakeaintreal.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

**Comment by fakeaintreal** [comment]
Added zap stanza.

[homebrew-createzap docs](https://github.com/nrlquaker/homebrew-createzap/blob/master/README.md) say to run `brew cask createzap ...`, but this seems to no longer work since `brew cask` is no longer a thing. I ended up just digging up the underlying bash script and running it. I couldn't work out how to run the external command another way. Is there a better way to do this? Are there documentation updates I could make?

**Comment by miccal** [comment]
Thank you @fakeaintreal, and we will have a look at the `brew cask createzap` issue.

Ping @vitorgalvao.

**Review by miccal — APPROVED** [review]

**Comment by vitorgalvao** [comment]
I’ve never used that command, so any documentation update you can work so we can walk through it is fine.

**Comment by nrlquaker** [comment]
@fakeaintreal I've updated the script to reflect latest changes in `homebrew`.
Now its `brew createzap` instead of `brew cask createzap`.

**Comment by fakeaintreal** [comment]
Thanks @nrlquaker!

**Pull request merged**
