### PR TITLE
Update disk-drill to 3.5.890

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
@reitermarkus Rebase and merge is failing for me as well.

**Comment by reitermarkus** [comment]
I'll contact GitHub support about this, since this seems to be a very weird bug.

**Comment by reitermarkus** [comment]
I got a response from GitHub support. This is caused because the author email is missing. 

You can see at https://github.com/Homebrew/homebrew-cask/commit/b5cfaaab3ede73586fb3b272ec42cb96459278bf.patch that the author is missing: `From: Work <>`

@suschizu, please check your Git configuration and make sure the author email is set correctly.

**Comment by suschizu** [comment]
@reitermarkus sorry for that! config file is fixed

**Pull request merged**
