### PR TITLE
Add RemotePlayInstaller.pkg.

### PR DESCRIPTION
**Pull request by jpcercal**
Add the latest version of the "PS4 Remote Play" for the console Sony PlayStation 4 from the official source.

### CODE REVIEW

**Comment by gtmgianni** [comment]
@jpcercal 

```
# remoteplay.dl.playstation.net/remoteplay/module/mac was verified as official when first introduced to the cask
```

Something like that would suffice (you don't need the `https://` prefix).

**Comment by vitorgalvao** [comment]
@jpcercal Thank you and welcome.

1. Please give provide the download page, so we can verify the download URL.
2. Next time, please complete the template.

**Comment by jpcercal** [comment]
Hey @vitorgalvao, I didn't understand what's missing there from the template.

The download page is this one:
https://remoteplay.dl.playstation.net/remoteplay/lang/en/index.html

**Comment by vitorgalvao** [comment]
> I didn't understand what's missing there from the template.

The whole template. It has checkboxes ro mark the steps you need to go through.

**Comment by vitorgalvao** [comment]
Since this is useless without a PS4, it’s [considered a driver](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask):

> If the software is useless without the peripheral, it’s considered a driver.

Please submit it to [caskroom/drivers](https://github.com/caskroom/homebrew-drivers) and include the steps of how to get from playstation.com to that download page (since the download page is already on playstation.net).

**Comment by jpcercal** [comment]
Thank you @vitorgalvao, I created a new merge request there https://github.com/caskroom/homebrew-drivers/pull/410.

**Pull request closed without merging**
