### PR TITLE
Update gog-galaxy from 2.0.43.66 to 2.0.43.66a

### PR DESCRIPTION
**Pull request by neutric**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

Undoing #111977 where the edits to make all CI checks pass took a wrong turn.

### CODE REVIEW

**Comment by gdams** [comment]
@neutric shasum issue

**Comment by neutric** [comment]
@gdams No idea why, I double checked by downloading again from my German ISP and a US-based VPS and both give me the same sha256.

```
$  wget https://cdn.gog.com/open/galaxy/client/2.0.43.66/galaxy_client_2.0.43.66a.pkg
--2021-10-05 14:24:44--  https://cdn.gog.com/open/galaxy/client/2.0.43.66/galaxy_client_2.0.43.66a.pkg
Resolving cdn.gog.com (cdn.gog.com)... 192.229.210.97
Connecting to cdn.gog.com (cdn.gog.com)|192.229.210.97|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 244679658 (233M) [application/octet-stream]
Saving to: 'galaxy_client_2.0.43.66a.pkg'

100%[==============================================================================================================================================================>] 244,679,658  138MB/s   in 1.7s   

2021-10-05 14:24:46 (138 MB/s) - 'galaxy_client_2.0.43.66a.pkg' saved [244679658/244679658]
$  sha256sum galaxy_client_2.0.43.66a.pkg 
349e9c0e8fc3c3ac582c1ac2d43066bcfb7eeac9362d0baf3ed05e7dc5aa49d5  galaxy_client_2.0.43.66a.pkg
```

**Comment by gdams** [comment]
How weird (on my end):

```output
➜  ~ wget https://cdn.gog.com/open/galaxy/client/2.0.43.66/galaxy_client_2.0.43.66a.pkg
--2021-10-05 19:44:36--  https://cdn.gog.com/open/galaxy/client/2.0.43.66/galaxy_client_2.0.43.66a.pkg
Resolving cdn.gog.com (cdn.gog.com)... 192.229.220.97
Connecting to cdn.gog.com (cdn.gog.com)|192.229.220.97|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8388608 (8.0M) [application/octet-stream]
Saving to: ‘galaxy_client_2.0.43.66a.pkg’

galaxy_client_2.0.43.66a.pkg              100%[=====================================================================================>]   8.00M  --.-KB/s    in 0.1s    

2021-10-05 19:44:37 (71.2 MB/s) - ‘galaxy_client_2.0.43.66a.pkg’ saved [8388608/8388608]

➜  ~ sha256sum galaxy_client_2.0.43.66a.pkg 
1548bb5bf007098f5acaf6fa62dd321bc31e6c3ca986bdbd90a16e8cd76bb5ab  galaxy_client_2.0.43.66a.pkg
```

**Comment by gdams** [comment]
> @gdams The file you got is much smaller, does it open fine?

No it doesn't... could it be a CDN issue?

Screenshot 2021-10-05 at 19 55 16

**Comment by neutric** [comment]
That's what I would guess. My file executes fine.

**Comment by gdams** [comment]
@neutric are you happy to raise a bug at their support site?

**Comment by neutric** [comment]
Will do so later tonight.

**Comment by miccal** [comment]
Looks fine now.

**Comment by neutric** [comment]
They indeed had problems with one of their CDNs. @miccal Thanks for the clean-up!

**Pull request merged**
