### PR TITLE
Update pdf-expert from 2.4.26,634 to 2.4.27,635

### PR DESCRIPTION
**Pull request by singularitti**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by singularitti** [comment]
Is there anybody to merge this commit? I cannot make a further update if this is not closed.

**Comment by robertleeblairjr** [comment]
Is your "further update" another version that's released? If so, then it may be better to just close this one yourself and make another pull request for the update you're talking about.

**Comment by m01i0ng** [comment]
Or you can just force push to your fork branch the new version

**Comment by singularitti** [comment]
> Is your "further update" another version that's released? If so, then it may be better to just close this one yourself and make another pull request for the update you're talking about.

Yes, it is. But I am wondering should we keep track of every version of an app in case that people wants to "pin" an app to a certain version?

**Comment by robertleeblairjr** [comment]
> > Is your "further update" another version that's released? If so, then it may be better to just close this one yourself and make another pull request for the update you're talking about.
> 
> Yes, it is. But I am wondering should we keep track of every version of an app in case that people wants to "pin" an app to a certain version?
 That's something to consider. I don't believe for this project concerning casks that it may really matter. However, a maintainer/moderator could better answer this.

**Comment by vitorgalvao** [comment]
> But I am wondering should we keep track of every version of an app in case that people wants to "pin" an app to a certain version?

There’s no such thing as pinning in casks. Please submit the new PR with the new version.

**Pull request closed without merging**
