### PR TITLE
Update cmake from 3.18.1 to 3.18.2

### PR DESCRIPTION
**Pull request by yurikoles**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by yurikoles** [comment]
Syntax CI error is unrelated and for `fing-desktop`

**Comment by miccal** [comment]
`brew cask style` error will be fixed by https://github.com/Homebrew/homebrew-cask/pull/87883.

**Comment by yurikoles** [comment]
>It seems there already exists a Binary at '/usr/local/bin/cmake'; not overwriting.

It seems that `cmake` formula is already installed on CI machine.

**Comment by miccal** [comment]
> > It seems there already exists a Binary at '/usr/local/bin/cmake'; not overwriting.
> 
> It seems that `cmake` formula is already installed on CI machine.

This failure is a result of changes made in https://github.com/Homebrew/brew/pull/8370.

**Pull request closed without merging**
