### PR TITLE
Update origin to latest

### PR DESCRIPTION
**Pull request by yuusharo**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by yuusharo** [comment]
What is the reason for adding a shasum check when the download url doesn't change? I can't install or reinstall Origin whenever the client updates server side due to a failed hash check.

Is this necessary?

**Comment by yuusharo** [comment]
It appears Origin does offer versioned downloads. Closing this PR, submitting a new PR with an updated versioned URL.

**Comment by yuusharo** [comment]
Sorry, the versioned URL is only for updates, not for client downloads. Reopening PR.

**Comment by core-code** [comment]
i don't think the cask is broken this often. its updated every few weeks and i have a script to observe it so it gets repaired quickly.

btw, the version downloads are identically to the full downloads, except they only contains the 'contents' of the app. all that would be necessary to use them is to create a script to create the enclosing 'Origin.app' folder.

**Pull request closed without merging**
