### PR TITLE
Update onyx to 3.3.0

### PR DESCRIPTION
**Pull request by grettir**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] `sha256` changed but `version` stayed the same ([what is this?](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256)).
      I’m providing public confirmation below.

### CODE REVIEW

**Comment by commitay** [comment]
Thanks @grettir! Could you reverse the order of the versions so it is oldest to newest release please?

**Comment by grettir** [comment]
I apologize for the confusion. The initial pull request was accidental.

Also, just FYI, these changes are based on the casks for [Maintenance](https://github.com/caskroom/homebrew-cask/blob/master/Casks/maintenance.rb) and [Deeper](https://github.com/caskroom/homebrew-cask/blob/master/Casks/deeper.rb), which are made by the same developer and have the same unique requirements.

**Review by commitay — APPROVED** [review]

**Comment by ChristianKraemer** [comment]
I get an error:

`Cask onyx depends on macOS release being one of [10.6, 10.7, 10.8, 10.9, 10.10, 10.11, 10.12], but you are running release 10.13.`

Needs an ":high_sierra" in "depends_on macos"?

**Comment by commitay** [comment]
@ChristianKraemer `onyx` doesn't have a 10.13 release yet.

> https://www.titanium-software.fr/en/onyx.html
> OnyX for macOS High Sierra 10.13 is not yet available. Please wait for the new version to be completed.

**Comment by gythialy** [comment]
@grettir OnyX for macOS High Sierra is available.  Could you update it, please?

**Comment by commitay** [comment]
@gythialy https://github.com/caskroom/homebrew-cask/pull/39419

**Pull request merged**
