### PR TITLE
zui: new cask

### PR DESCRIPTION
**Pull request by graelo**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by graelo** [comment]
In case you're wondering, the description was taken from the homepage, but it's not very descriptive of what the app actually does: it analyzes network traffic and hands over filtered conversations to Wireshark. Here is a demo: https://www.youtube.com/watch?v=InT-7WZ5Y2Y. The name of the app was changed from Brim to Zui two years ago, as explained in the docs.

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @graelo.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by graelo** [comment]
Sure, here it is. I tracked the files using a couple of tools.

By the way, Is there a canonical way of hunting down these kind of files?

**Comment by miccal** [comment]
Thank you @graelo.

**Review by miccal — APPROVED** [review]

**Comment by graelo** [comment]
Thanks a lot for your help @miccal

**Pull request merged**
