### PR TITLE
Upgrade iTerm2 to 3.4.5

### PR DESCRIPTION
**Pull request by weichenw**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by Ry0taK** [comment]
@weichenw
It looks like you accidentally pasted your GitHub API Token.
You should revoke it as soon as possible: https://github.com/settings/tokens

**Comment by cho-m** [comment]
Duplicate of existing PR #104019

**Comment by weichenw** [comment]
Aiks. didnt notice that. Thanks.

**Comment by vitorgalvao** [comment]
> Hmm I check my clipboard history,doesn't looked like I copied it

If you copied it from a secure field (likely, due to its nature), it’s likely your clipboard manager ignored it (for security reasons).

**Comment by weichenw** [comment]
> > Hmm I check my clipboard history,doesn't looked like I copied it
> 
> If you copied it from a secure field (likely, due to its nature), it’s likely your clipboard manager ignored it (for security reasons).

The worrying part is that I don't remember copying it from anywhere at all. I wasn't setting up anything at all. Been scratching my head how it got there.

**Pull request closed without merging**
