### PR TITLE
Update Feishu from 5.17.6 to 5.18.5

### PR DESCRIPTION
**Pull request by chunheisiu**
* Update Feishu from 5.17.6 to 5.18.5
* Fix version differences between arch

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by chunheisiu** [comment]
I'm not certain why but the result of the live check endpoint through the browser differs:

```
{"versions":{"Android":{"download_link":"https://zlink.toutiao.com/kG12?apk=1","qr_link":"https://www.feishu.cn/download","version_number":"Android@V5.18.4","weight":0,"hash":"2304da903d1e9777947e9c6be67316ea","release_time":"1659525663"},"MacOS":{"download_link":"https://sf3-cn.feishucdn.com/obj/ee-appcenter/8cf977/Feishu-darwin_x64-5.18.5-signed.dmg","qr_link":"","version_number":"MacOS-Intel@V5.18.5","weight":0,"hash":"8cf97781fc1f9c8bf28245d068ee8d6e","release_time":"1659515174"},"MacOS_m1":{"download_link":"https://sf3-cn.feishucdn.com/obj/ee-appcenter/976ebf/Feishu-darwin_arm64-5.18.5-signed.dmg","qr_link":"","version_number":"MacOS-Apple@V5.18.5","weight":0,"hash":"976ebfc2c45e4142abf7397ef2650044","release_time":"1659515158"},"Windows":{"download_link":"https://sf3-cn.feishucdn.com/obj/ee-appcenter/b78084/Feishu-win32_ia32-5.18.5-signed.exe","qr_link":"","version_number":"Windows-32@V5.18.5","weight":0,"hash":"b78084646df0b061405c3c659e6e4b69","release_time":"1659515190"},"iOS":{"download_link":"https://zlink.toutiao.com/h2Sw","qr_link":"https://zlink.toutiao.com/h2Sw","version_number":"iOS@V5.18.3","weight":0,"hash":"","release_time":"1659515380"},"iOS_extra":{"download_link":"https://itunes.apple.com/us/app/lark-collaboration-tool/id1452166623","qr_link":"","version_number":"iOS@V5.18.3","weight":0,"hash":"","release_time":""},"Linux_deb_x64":{"download_link":"https://sf3-cn.feishucdn.com/obj/ee-appcenter/5db94058d7ad/Feishu-linux_x64-5.9.18.deb","qr_link":"","version_number":"","weight":0,"hash":"f2b9377c9fd3b2070cbd68e779d92a9d","release_time":""},"Linux_deb_arm":{"download_link":"https://sf3-cn.feishucdn.com/obj/ee-appcenter/5db94058d7ad/Feishu-linux_arm64-5.9.18.deb","qr_link":"","version_number":"","weight":0,"hash":"be10f317a5b1e792b42a399faf7c1db3","release_time":""},"Linux_deb_mips64el":{"download_link":"https://sf3-cn.feishucdn.com/obj/ee-appcenter/5db94058d7ad/Feishu-linux_mips64el-5.9.18.deb","qr_link":"","version_number":"","weight":0,"hash":"e26250725b41de9b5f536c49524e3387","release_time":""},"Linux_rpm_x64":{"download_link":"https://sf3-cn.feishucdn.com/obj/ee-appcenter/5db94058d7ad/Feishu-linux_x64-5.9.18.rpm","qr_link":"","version_number":"","weight":0,"hash":"0b886f14e37e0a2013659b175d32b870","release_time":""},"Linux_rpm_arm":{"download_link":"https://sf3-cn.feishucdn.com/obj/ee-appcenter/5db94058d7ad/Feishu-linux_arm64-5.9.18.rpm","qr_link":"","version_number":"","weight":0,"hash":"d116f75db5174c878ea0c6e6171b7887","release_time":""},"Linux_rpm_mips64el":{"download_link":"https://sf3-cn.feishucdn.com/obj/ee-appcenter/5db94058d7ad/Feishu-linux_mips64el-5.9.18.rpm","qr_link":"","version_number":"","weight":0,"hash":"edcdbd85d7580898843b2877fff2dc1c","release_time":""}}}
```

**Comment by chunheisiu** [comment]
It seems like 5.18.5 from the livecheck page is only available to logged in users, as I have tried curl-ing the page with cookie headers and it returned different results.

**Review by reitermarkus — APPROVED** [review]

**Comment by miccal** [comment]
This appears to be already up-to-date:
```
==> feishu
Current cask version   :  5.17.6,1a2b3c4d
Latest livecheck version: 5.17.6,1a2b3c4d
Latest Repology version:  5.17.6
```

**Comment by chunheisiu** [comment]
> This appears to be already up-to-date:
> 
> ```
> ==> feishu
> Current cask version   :  5.17.6,1a2b3c4d
> Latest livecheck version: 5.17.6,1a2b3c4d
> Latest Repology version:  5.17.6
> ```

It seems to be the case if you are not a logged in user. On my end, if I supply cookies in the request, I'm getting a new version, as well as through the auto update feature of the application

**Pull request closed without merging**
