### PR TITLE
Add BusyCal

### PR DESCRIPTION
**Pull request by star-szr**
How does this look? [The trial version now functions as the full version](https://support.busymac.com/help/24535-how-to-install-busycal#license) (see also #5779).

### CODE REVIEW

**Comment by ndr-qef** [comment]
Looks perfect. Thanks you.

**Comment by Cottser** [comment]
@ndr-qef, my pleasure. I'm just trying to figure out why Installer.app is still running after install. Just ran this on a different machine and noticed. I don't think I've seen this behaviour in any other casks I've installed, would this be something with a known workaround?

**Comment by Cottser** [comment]
Also after running `brew cask uninstall busycal` I'm still seeing some kind of busted BusyCal.app in /Applications. Maybe this needs some special treatment for both install and uninstall.

**Comment by ndr-qef** [comment]
You are right; I can reproduce the behavior in a Mavericks VM. Moreover, the pkg installer opens a Finder window at /Applications, which is likely undesirable from our perspective.

**Comment by Cottser** [comment]
I didn't notice the Finder window, I see it now as well. That must be part of the installer scripts because I'm seeing it when running the installer manually. When running the installer manually it does exit Installer.app at the end.

**Pull request merged**
