### PR TITLE
Wiso steuer 2024

### PR DESCRIPTION
**Pull request by piijai**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@krehel This discussion has come up before, and I believe it is common for people to require access to the apps for previous years.

**Comment by krehel** [comment]
@bevanjkay - fair enough!  Wanted to pose the question.

**Comment by bevanjkay** [comment]
How many years we should keep is probably a good question though.
@piijai Do you have any thoughts here?

**Comment by piijai** [comment]
Hi,
your previous point @bevanjkay is correct.

Like it says in the description, WISO Steuer is a software to create your tax declaration. Maybe we could also add, that it is only for the tax declaration for Germany, because it only supports the German tax declaration. 
And yes, every version only supports the tax declaration for the year before. So the current WISO Steuer 2024 only supports the tax declaration for the fiscal year 2023. If you want to create your tax declaration for the fiscal year 2022 you can't do that with WISO Steuer 2024, you have to use WISO Steuer 2023. 

In Germany you can declare your taxes up to 4 years back. So this year, you can still declare your taxes for the year 2019.
But yes, I assume only a few people will use the older versions like 2 years back, or more. As far as I know Buhl, the software company, supports the older versions with security and bug fixes for those 4 years.

Currently the audit is failing, because the livecheck retrieves an empty version string. I looked in the dmg file and the Info.plist file has the same structure as WISO Steuer 2023. So I have no idea, why the livecheck retrieves an empty version string.

I hope with those insights help you, how to handle the casks for WISO Steuer in the future.

**Comment by bevanjkay** [comment]
@piijai The `livecheck` was failing because the `app` is named differently in shell to finder, so the app was not being found.

**Review by miccal — APPROVED** [review]

**Pull request merged**
