### PR TITLE
Migrate minishift to homebrew/core

### PR DESCRIPTION
**Pull request by commitay**
https://github.com/Homebrew/homebrew-core/pull/14819

### CODE REVIEW

**Comment by gastaldi** [comment]
+1 to this PR

**Comment by gastaldi** [comment]
Hi @commitay, what else is needed to merge this PR?

**Comment by commitay** [comment]
@gastaldi We need a Homebrew maintainer to approve https://github.com/Homebrew/homebrew-core/pull/14819 before we merge this.

**Comment by commitay** [comment]
Merge conflict. New PR: https://github.com/caskroom/homebrew-cask/pull/36012

**Pull request closed without merging**
