### PR TITLE
Update minecraft-server from 1.16.5,1b557e7b033b583cd9f66746b7a9ab1ec1673ced to 1.17,0a269b5f2c5b93b1712d0f5dc43b6182b9ab254e

### PR DESCRIPTION
**Pull request by cho-m**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
https://minecraft.fandom.com/wiki/Server/Requirements

**Comment by cho-m** [comment]
Looks like they compiled on JDK 16 (class version 60.0):
```
Error: LinkageError occurred while loading main class net.minecraft.server.Main
	java.lang.UnsupportedClassVersionError: net/minecraft/server/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 58.0
```

The CI JRE seems to be only able to run up to JDK 14 (class version 58.0).

Not sure if this was intentional, but looks like we may need JRE 16 to test.

**Comment by cho-m** [comment]
https://minecraft.fandom.com/wiki/Tutorials/Update_Java
> Since Java Edition 1.17(21w19a), Minecraft requires Java 16 or newer.

https://www.minecraft.net/en-us/article/minecraft-snapshot-21w19a
> If you are using a custom Java setup or a third-party launcher, you will need to ensure that your Java installation is version 16 or above.

**Comment by cho-m** [comment]
Based on https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md, I see that the current failure is probably due to max Java 14 in default environment:
| Version              | Vendor        | Environment Variable |
| -------------------- | ------------- | -------------------- |
| 8.0.292+10 (default) | Adopt OpenJDK | JAVA_HOME_8_X64      |
| 11.0.11+9            | Adopt OpenJDK | JAVA_HOME_11_X64     |
| 12.0.2+10.3          | Adopt OpenJDK | JAVA_HOME_12_X64     |
| 13.0.2+8.1           | Adopt OpenJDK | JAVA_HOME_13_X64     |
| 14.0.2+12            | Adopt OpenJDK | JAVA_HOME_14_X64     |


To get past CI failure, may need to add another step that installs Java 16 (maybe dependent on caveat value).

**Comment by cho-m** [comment]
For now, just skipping install as this requires CI changes to support testing on JDK 16

**Pull request merged**
