### PR TITLE
Update anki

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Already at 2.1.21.

**Comment by ran-dall** [comment]
> Already at 2.1.21.

@vitorgalvao I was updating the `appcast` to the `url` redirected on the page.

**Comment by vitorgalvao** [comment]
Right you are! Apologies.

**Comment by vitorgalvao** [comment]
But even that page won’t work (see the source).

**Pull request merged**
