### PR TITLE
Remove support for Mavericks

### PR DESCRIPTION
**Pull request by claui**
With https://github.com/Homebrew/brew/pull/7716 and https://github.com/Homebrew/brew/pull/7698 now merged, Homebrew no longer runs on Mavericks, and support for the `:mavericks` symbol has been removed.

This causes `brew cask install` and `brew cask uninstall` to fail with the following error message:

```
Error: Cask 'deeper' definition is invalid: invalid 'depends_on macos' value: :mavericks
```

This PR fixes the issue by removing all references to `:mavericks`.

Please mind that **CI will fail** because this is a single PR for all 39 casks (albeit multiple commits).

___

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free. **Audit fails for 3 out of 39 casks: for `adobe-dng-converter`, the server keeps killing the connection; `geekbench` and `time-out` suffer from the [TLS issue](https://github.com/Homebrew/brew/issues/7667) but are fine otherwise. All other casks pass the audit.**
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Merging fast before there are merge conflicts.

Though this will be problematic now, because every installed cask with `mavericks` will fail, giving rise to bug reports that necessitated https://github.com/Homebrew/homebrew-cask/issues/58046.

We really need to fix that problem.

**Comment by claui** [comment]
Thanks @vitorgalvao!

**Comment by vitorgalvao** [comment]
Thank *you*!

**Comment by MikeMcQuaid** [comment]
> Though this will be problematic now, because every installed cask with `mavericks` will fail, giving rise to bug reports that necessitated #58046.

@vitorgalvao if you can provide some reproduction steps for this I can give it a go at digging into the cask code and fixing it once and for all.

**Comment by danielbayley** [comment]
So should `depends_on macos: '>= :mavericks'` in existing Casks not now be replaced with `depends_on macos: '>= :yosemite'`, rather than removing the line altogether?

**Comment by MikeMcQuaid** [comment]
@danielbayley I don't think so because `brew cask` can no longer be run on pre-yosemite.

**Comment by danielbayley** [comment]
Ah ok, so really only `depends_on macos: '>= :el_capitan'` would be used with `>=` in practice…

**Comment by claui** [comment]
@MikeMcQuaid @vitorgalvao Here’s a simple, self-contained snippet to reproduce the issue:

**(Make a backup before running the following Bash script. It will mess with your installation!)**

```bash
(
    set -ex -o pipefail;

    # Forcibly remove mpv if present, even in case cask is not loadable
    rm -rf 2>/dev/null \
        "$(brew --prefix)/Caskroom/mpv" \
        '/Applications/mpv.app' \
        | true
    # Restore pristine state of `version.rb`
    git -C "$(brew --repository)" checkout -- \
        'Library/Homebrew/os/mac/version.rb'

    # Install cask that depends on Yosemite
    brew cask install mpv

    # Simulate upstream dropping Yosemite support
    sed -i '' -e '/yosemite/d' \
        "$(brew --repository)/Library/Homebrew/os/mac/version.rb"

    # Try to do something with the installed cask
    brew cask info mpv
    echo 'Success'  # this line is never reached
)
```

**Comment by vitorgalvao** [comment]
Building on @claui’s code, a self-contained version that won’t touch your local installation of either `mpv` or `brew`.

```bash
# Temporary directories
brew_tmp_dir="$(mktemp -d)"
mpv_tmp_dir="$(mktemp -d)"

# Clone upstream Homebrew/brew
git clone 'https://github.com/Homebrew/brew.git' "${brew_tmp_dir}"

# When calling brew, use the one from the temporary directory
# Closing the shell is all you need to do to get back to normal
alias brew="${brew_tmp_dir}/bin/brew"

# Install mpv to temporary directory
brew cask install --appdir="${mpv_tmp_dir}" mpv

# Simulate upstream dropping Yosemite support
sed -i '' -e '/yosemite/d' "${brew_tmp_dir}/Library/Homebrew/os/mac/version.rb"

# Try to do something with the installed cask
brew cask info mpv && echo 'Success'

```

**Pull request merged**
