### PR TITLE
Add cask for Unclutter.app (latest version)

### PR DESCRIPTION
**Pull request by smammy**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
This is a demo that does not seem to have a way to unlock the full version of the app.

@smammy Is there a way to unlock/activate the full version from within the demo?

**Comment by smammy** [comment]
Yes, in the menu bar menu there's a purchase option. (I don't remember the exact text of the menu item and I'm not in front of my machine at the moment.)

**Comment by commitay** [comment]
> Yes, in the menu bar menu there's a purchase option.

This opens a web page, is there a way to actually upgrade the `app` to the full version?

**Comment by smammy** [comment]
I'll check and get back to you. Thanks.

**Comment by smammy** [comment]
It turns out I don't like this app enough to buy it, so I can't verify that re-downloading is not required after purchase. Feel free to reject this PR if you don't want to take the chance.

**Comment by commitay** [comment]
Thank you for your PR and for checking to see if the `app` can be upgraded. Going to pass on this as it is a time limited demo.

**Pull request closed without merging**
