### PR TITLE
Update riverdesign-sparkle to latest

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by adidalal** [comment]
Mind adding an [appcast](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md)?

Appcast is at `https://sparkleapp.com/update/appcast.php?lang=en` and version looks to be `3.6.1`

**Comment by core-code** [comment]
i am not sure if an appcast is beneficial if we have version latest, but thanks, i've added it

**Comment by vitorgalvao** [comment]
When using an appcast, even if `url` in unversioned, we add a version. This is because with an appcast we can detect updates faster and it won’t break as much.

**Review by vitorgalvao — APPROVED** [review]

**Comment by core-code** [comment]
thanks for the info. is there actually an automated system in place to find outdated apps with appcasts? (because it seems to remember submitting updates for a lot of those)

**Comment by vitorgalvao** [comment]
> is there actually an automated system in place to find outdated apps with appcasts? 

Several. See https://github.com/Homebrew/homebrew-cask/issues/48051.

**Pull request merged**
