### PR TITLE
Update tor-browser from 9.0.4 to 9.0.5

### PR DESCRIPTION
**Pull request by miccal**
`/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/developer/bin/update_multilangual_casks /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/tor-browser.rb 9.0.5`

### CODE REVIEW

**Comment by core-code** [comment]
@vitorgalvao can we switch to a more sane appcast here? the 9.0.5 version is available neither on their official download website nor via the built-in update check.

**Comment by vitorgalvao** [comment]
@core-code Sure, I have no issue with changing appcasts for the better. That said, I do see `9.0.5` on the website and I think this situation has happened before, so if that appcast is early (in relation to the website and the built-in updater) it seems to be by less than a day, which doesn’t seem problematic.

**Comment by core-code** [comment]
> That said, I do see 9.0.5 on the website and I think this situation has happened before, so if that appcast is early (in relation to the website and the built-in updater) it seems to be by less than a day, which doesn’t seem problematic.

yes it seems to be have been around a day. in principle, we should avoid jumping the gun and post things just because found them on the download server.  in practice, i agree, it may not make much difference in /most/ cases and certainly didn't here.

i didn't find anything better than 'https://www.torproject.org/download/' to use. should i send a PR?

**Comment by vitorgalvao** [comment]
> i didn't find anything better than 'https://www.torproject.org/download/' to use. should i send a PR?

I don’t have strong feelings on it, so I’m fine with the change.

**Pull request merged**
