### PR TITLE
godspeed 1.0.2 (new cask)

### PR DESCRIPTION
**Pull request by Kreeblah**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

Edit: So, I apprently missed the `--new` parameter when I ran the audit on this.  I'm assuming that's why there's an error returned here.  The web site indicates that Monterey is required for this application (which is why I used that in the cask), so would it be best to reach out to the author and have them correct things so it's consistent?

### CODE REVIEW

**Comment by SMillerDev** [comment]
> so would it be best to reach out to the author and have them correct things so it's consistent?

Yeah, that sounds best

**Comment by bevanjkay** [comment]
The audit is checking the app's `info.plist` file for the supported version. So the app will technically "run" on anything after Catalina even if it doesn't "work".

Can you try to find a `livecheck`?

**Comment by Kreeblah** [comment]
I took a look at what it's doing for its update check, and was able to get a link to a versioned binary from that, but I'm not quite sure how to write it as a livecheck.  What it's doing is making a GET request to `https://api.godspeedapp.com/update-check/1.0.0` (or whatever other version) and if there's an update available (such as, say, if version 0.9 is passed instead), a JSON payload is retuned with a link to a ZIP file containing the updated app bundle.  If it's up to date, however, the body of the payload is empty.

Would something like that be usable?  If so, what would be a reasonable way to do that as a livecheck in a cask here?

**Comment by krehel** [comment]
@Kreeblah does this app download and install the update (auto_update) or just check for updates? 

I think that's about the last thing...

**Comment by Kreeblah** [comment]
@krehel - I was about to say I wasn't sure, but it turns out they have a version 0.9.0 ZIP at the same location.  I was able to check with that, and it did auto-update to 1.0.0.  So, I added the `auto_updates` property and set it to `true`.

**Review by SMillerDev — APPROVED** [review]

**Review by bevanjkay — CHANGES_REQUESTED** [review]

**Review by bevanjkay — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
🚢

**Pull request merged**
