### PR TITLE
Update tex-live-utility to 1.19, new hosting

### PR DESCRIPTION
**Pull request by rpls**
The author switched to github for newer versions.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Could you update the homepage to the github repo as well?

**Comment by dasricht** [comment]
Whoops, forgot that.

**Comment by vitorgalvao** [comment]
Tank you, could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by dasricht** [comment]
Thanks! Learned something new today =)

**Comment by fanquake** [comment]
:+1:

**Pull request merged**
