### PR TITLE
various casks: update depends_on

### PR DESCRIPTION
**Pull request by AlternateRT**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

---
These browsers are now based on Chromium 129 (or later), and as such [require macOS 11 or later](https://support.google.com/chrome/answer/95346?visit_id=638271258484999533-1844643546&p=unsupported_mac&rd=1#sysreq_mac&zippy=%2Cmac); this updates the `depends_on` stanza (and adds it to the microsoft-edge casks, where it was missing).

### CODE REVIEW

**Comment by bevanjkay** [comment]
We generally get this information from each app's `info.plist` file as this determines if an app can be run by the system.

It looks like not all the apps have been updated by the vendor to reflect this. Only the `google-chrome-*` seem to have been updated.

**Comment by AlternateRT** [comment]
> It looks like not all the apps have been updated by the vendor to reflect this. Only the google-chrome-* seem to have been updated.

@bevanjkay I was not aware of this. In any case, none of them will run of macOS 10.15 and all of them have announced elsewhere that macOS 11 is the new minimum requirement:
* Brave: [Changes to macOS desktop browser requirements](https://support.brave.com/hc/en-us/articles/18347246446733-Changes-to-macOS-desktop-browser-requirements)
* Microsoft Edge: [Microsoft Edge supported Operating Systems](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems#macos)

**Comment by AlternateRT** [comment]
Hmm, I just had a look in each app's `info.plist` plist file, and they all had `LSMinimumSystemVersion` set to 11.0. Are you certain it was only the google-chrome-* apps? It looks to me like all vendors did in fact update it.

**Review by bevanjkay — APPROVED** [review]

**Comment by AlternateRT** [comment]
Is something wrong? There is a "syntax (macOS-15)" check, but it doesn't seem to be progressing at all.

**Comment by bevanjkay** [comment]
Ahh the required checks were updated as we've moved to a newer CI image. I just need to rerun the suite.

**Pull request merged**
