### PR TITLE
Add CLion 1.0 with bundled JDK 1.8

### PR DESCRIPTION
**Pull request by andystanton**

### CODE REVIEW

**Comment by andystanton** [comment]
Any feedback @fanquake?

**Comment by vitorgalvao** [comment]
Pinging @radeksimko and @sebroeder for input (not sure how this affects https://github.com/caskroom/homebrew-versions/issues/879).

**Comment by sebroeder** [comment]
Thanks for your contribution @andystanton. If we want to be consistent, than this cask should go into the caskroom/homebrew-versions repository named `clion-bundled-jdk`. Would you mind having a look at caskroom/homebrew-versions#879 and adjust the cask accordingly (mostly adding the `zap` stanza)?

Good idea including `conflicts_with`, I will add this to caskroom/homebrew-versions#879.

Did you test installing the cask on a OS X version < 10.10 (without the `conflicts_with` stanza)?  The download pages says

> Using OS X 10 Yosemite? Get CLion 1.0 with JDK 1.8

but I would guess it can still be installed on older versions (background: the problems with the Oracle JDK are worst on Yosemite so this might be the reason why JetBrains pushes  the bundled JDK version for Yosemite). If my guess is true we should not restrict the cask to Yosemite.

**Comment by andystanton** [comment]
Hi @sebroeder,

I've now raised caskroom/homebrew-versions#944 with the following changes:

* Renamed to ```clion-bundled-jdk```.
* Add ```zap``` stanza with appropriate folders locations.
* Removed the ```depends_on``` - I tested on osx 10.9.5 with one of my projects and you were correct - there were no obvious problems.

As for the ```conflicts_with``` I can't take credit for that - I modified the EAP version which I believe was the work of @denpatin.

Closing this PR - any further discussion can happen in caskroom/homebrew-versions#944.

**Pull request closed without merging**
