### PR TITLE
Add miniconda.rb

### PR DESCRIPTION
**Pull request by drzax**
Adds miniconda3 by Continuum Analytics. The full anaconda install is massive and often uneccesary. This is a supported and valid alternative.

### CODE REVIEW

**Comment by adidalal** [comment]
Use a versions url, check the anaconda cask for an example

**Comment by drzax** [comment]
It appears to be impossible to get the most up to date version from a versioned URL. Indeed, the latest version mentioned in the appcast changelog at the URL suggested (3.19.1) is not available from the distribution repo.

Will this cause problems with the way appcast functions? I also think this will make it impossible for me to create the required checkpoint parameter?

Happy to submit an update if these aren't problems.

**Comment by adidalal** [comment]
Took a closer look; agreed on above points. It's not ideal but AFAIK conda is basically able to update itself with `conda update conda` so it's not a big deal.

**Comment by adidalal** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 0154744e1574604f704dde83cea6fdd97d6ba7e3. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by drzax** [comment]
Thanks.

**Pull request closed without merging**
