### PR TITLE
added Deeper for Mojave v2.3.5

### PR DESCRIPTION
**Pull request by tinhkyaw**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by commitay** [comment]
`2.3.5` is already the current version on mojave and `2.3.6` hasn't been released yet.

Thanks for the PR nonetheless!

**Comment by tinhkyaw** [comment]
need to update the SHA

**Comment by commitay** [comment]
Okay, please change this to update only the `sha256`.

**Comment by tinhkyaw** [comment]
I just followed the convention of how it was done initially - which is to put the latest SHA in the else branch.  Why keep the else on an older SHA?

**Comment by commitay** [comment]
The version newer than mojave that will be uninstallable and has not been released yet. Please update only the `2.3.5` checksum.

**Review by commitay — APPROVED** [review]
https://www.virustotal.com/#/file/8a8a6dec420ec7dd04eedec6400b5a2b40f4db60da628e817b61322761b91f08/details

**Pull request merged**
