### PR TITLE
Use correct URL for Mudlet

### PR DESCRIPTION
**Pull request by vadi2**
After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].
- [ ] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

### CODE REVIEW

**Comment by vadi2** [comment]
I don't use macOS so I'm not able to test the changes, but the URL in the cask file was incorrect and goes away on an update. I've fixed it to use the correct URL that's always valid.

**Comment by ran-dall** [comment]
@suschizu or @core-code Could you guys check this, please? 🙏

**Comment by vadi2** [comment]
You can see a directory of all releases at https://www.mudlet.org/wp-content/files/?C=M;O=D

**Comment by demonnic** [comment]
Also, is there a recommended method for automatically updating the cask when Mudlet is released?

**Comment by core-code** [comment]
the changes look OK to me

> Also, is there a recommended method for automatically
> updating the cask when Mudlet is released?

there is no such thing as "fully automatic" but we usually update all casks that have 'good' appcasts within a day. GitHub feeds should be well supported. the 4.1.1 release was probably not picked up because it isn't marked as "Latest Release" in GitHub,

**Comment by ran-dall** [comment]
@vadi2 I'm going to integrate your changes to the update created by the ML this morning so that we don't lose any of the analyzation and tracking information for the cask. Would you mind closing this?

**Comment by ran-dall** [comment]
https://github.com/Homebrew/homebrew-cask/pull/68871

**Pull request closed without merging**
