### PR TITLE
Updated Checksum for Clockify version 2.1.6_35

### PR DESCRIPTION
**Pull request by space-otter**
Updated  Checksum for Clockify version 2.1.6_35.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please **carefully** [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

Notice how the instructions underline **if there is no *Signature Info* section, VirusTotal verification is not enough.** If there’s no such section and you post a VirusTotal link instead of asking for developer confirmation, your pull request will be closed without further comment.

**Comment by space-otter** [comment]
I contacted the developers of Clockify and checked the file with VirusTotal.
They confirmed changes and the changed checksum. I asked them to announce it publicly.

**Comment by DamirDjozicCoing** [comment]
Hi,
as an iOS developer for Clockify, I confirm changes and changed checksum. 
Hope this helps!

**Comment by space-otter** [comment]
@vitorgalvao i hope you can now accept my pull request.

**Comment by vitorgalvao** [comment]
I’ll merge the PR because I verified locally the app is codesigned. @DamirDjozicCoing’s confirmation would be insufficient, as I can find no proof he’s a Clockify developer. Simply claiming to be one is not enough — anyone could say it — some proof would be necessary.

**Comment by DamirDjozicCoing** [comment]
You can view our official website https://coingdevelopment.com/team and find me, and you can see in the AppStore that Coing is the "developer" of the app. Hope this helps.

P.S. new version is out, so you won't have this kind of problem anymore.

Cheers!

**Comment by space-otter** [comment]
@DamirDjozicCoing Thank you for your help!

**Pull request merged**
