### PR TITLE
Update sonarr from 3.0.6.1196 to 3.0.6.1266

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
It looks like the version on homepage (**3.0.6.1265**) doesn't align with any git tag (**3.0.6.1266**, **3.0.6.1264**, ...).

For homepage:
- Homepage downloads are https://sonarr.tv/#downloads-v3-macos
- which has a link for https://services.sonarr.tv/v1/download/main/latest?version=3&os=macos&installer=true 
- which redirects to https://download.sonarr.tv/v3/main/3.0.6.1265/Sonarr.main.3.0.6.1265.macos.zip

Not sure if there is any issue with using app included in source code zip from git tag.

**Comment by bevanjkay** [comment]
@cho-m At the time this PR was created, livecheck was showing (3.0.6.1265) as the current version. Perhaps it would be better to use the download links from the website instead of Github? If you think this is the best action I can update the cask.

**Comment by cho-m** [comment]
The website may be more accurate given that the GitHub page (https://github.com/Sonarr/Sonarr#getting-started) Download/Installation link sends you to the homepage. It also lines up with the docker version https://hub.docker.com/r/linuxserver/sonarr/tags?page=1&ordering=last_updated

In which case,
- the livecheck could be done on `https://services.sonarr.tv/v1/download/main/latest?version=#{version.major}&os=macos&installer=true`, though it cannot detect major version updates.
- the download could be done on `https://download.sonarr.tv/v#{version.major}/main/#{version}/Sonarr.main.#{version}.macos.zip`

The zip structure is also different, so `app` stanza will need to be changed accordingly.

**Comment by bevanjkay** [comment]
@cho-m I could update the livecheck to use the directory for the V3 releases as above. The only thing to note is that it is still showing a newer build than where the website links to.

**Pull request merged**
