### PR TITLE
llamachat 1.2.0 (new cask)

### PR DESCRIPTION
**Pull request by fwcd**
[LlamaChat](https://llamachat.app/) is a neat little open-source GUI for locally running LLaMA-style language models.

---

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Hi @fwcd, 

Thank you for submitting this! Looks great! 👍

Do you happen to know if the app autoupdates? It looked to me like there was a Sparkle feed.

**Comment by fwcd** [comment]
It seems to offer a `Check for Updates...` menu entry, so most likely it's Sparkle, yes.

**Review by razvanazamfirei — APPROVED** [review]

**Comment by razvanazamfirei** [comment]
Thanks so much!

**Comment by alexrozanski** [comment]
@fwcd @razvanazamfirei thanks for adding! fyi if you need the appcast URL it's https://llamachat.app/appcast.xml

**Comment by razvanazamfirei** [comment]
Hi @alexrozanski, thanks for letting me know. Right now we use the Github tags for our livecheck. Happy to change the livecheck to the appcast URL if that is more reliable.

**Comment by alexrozanski** [comment]
@razvanazamfirei I’ll be releasing both tagged releases and through the appcast so happy to leave as is!

**Pull request merged**
