### PR TITLE
Update visual-studio from 8.10.23.7 to 17.0.0.314

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Review by bevanjkay — APPROVED** [review]
Thank you @yurikoles 

I have had a look and it seems that using `installer manual` will be the only way to install visual studio moving forward.

**Comment by ejhg** [comment]
@bevanjkay @yurikoles Thank you for maintaining this.

This change is very unfortunate.  I relied on brew to do headless installs of Visual Studio in CI builds.  Any tips or workarounds?

**Comment by bevanjkay** [comment]
@ejhg Unfortunately not unless you can find a method that allows headless installation. Upstream are only providing an interactive installer from what I can see.

**Comment by ejhg** [comment]
@bevanjkay Thanks for the reply.

(Fortunately, for now, I found that the mono-mdk cask has what I need, and I don't need to install VS anymore to get the latest language features.)

**Pull request closed without merging**
