### PR TITLE
Add Vimac cask

### PR DESCRIPTION
**Pull request by aymanbagabas**
https://vimacapp.com/

Related: https://github.com/dexterleng/vimac/issues/152, https://github.com/Homebrew/homebrew-cask/issues/100551

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by aymanbagabas** [comment]
I've used [Arbitrary method](https://github.com/Homebrew/homebrew-cask/tree/master/doc/cask_language_reference#arbitrary-ruby-methods) but the style audit keeps failing even though this is defined in the docs. Also I can't seem to find how to add `verified:` param to `url do` blocks.

**Comment by miccal** [comment]
Thank you @aymanbagabas, but unfortunately we cannot accept this since [appcenter URL's are unstable](https://github.com/Homebrew/homebrew-cask/pull/79549#issuecomment-605668146).

**Comment by aymanbagabas** [comment]
@miccal this is using their api I don't see how it would be unstable

**Comment by aymanbagabas** [comment]
@vitorgalvao could you please elaborate on this?

**Comment by vitorgalvao** [comment]
> @vitorgalvao could you please elaborate on this?

The issue @miccal linked to already explains the problem:

> appcenter URLs are a pain to maintain and break all the time.

At one point there was someone who worked on appcenter who said they’d try to do something about it, but nothing came of it.

> this is using their api

Which we specifically do not want in casks in the main repo. Just to get the version and download URL you needed over 20 lines and 2 `require`. For something that’s typically 2 lines. That’s the problem with these: they’re not worth the complexity.

**Pull request closed without merging**
