### PR TITLE
p4: Updated sha256 for 2016.2.1457671

### PR DESCRIPTION
**Pull request by bbudzon**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

### CODE REVIEW

**Comment by mdouglass** [comment]
Minor nitpick, this version of the binary is now 1468155, not 1457671.

**Comment by vitorgalvao** [comment]
@mdouglass Thank you. Fixed.

**Review by vitorgalvao — APPROVED** [review]

**Comment by neybis** [comment]
ahh, thank you for nit picking @mdouglass! hahaahh If you don't tell me I won't learn ;) I'll make sure to double check this in the future.

**Comment by neybis** [comment]
(complete github noob, I'll figure out this system sooner or later. reopening the PR since I closed it before it was merged)

**Pull request merged**
