### PR TITLE
samsung-magician 8.0.0.900 (new cask)

### PR DESCRIPTION
**Pull request by breckwagner**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

Used samsung-portable-ssd-t7 Cask as model because of similarities.

### CODE REVIEW

**Comment by breckwagner** [comment]
I'm pretty sure the install step is failing. in the github action because the installer prompts for GDPR and EULA.  I'm not sure how to handle it?

**Comment by bevanjkay** [comment]
Thanks @breckwagner - we require that all software in `homebrew-cask` be able to be installed without further intervention (entirely headlessly).
The option are to find a way to suppress the warnings, or using [`installer manual`](https://docs.brew.sh/Cask-Cookbook#installer-manual) may be the only option.

**Comment by breckwagner** [comment]
Would something like this be acceptable?

```ruby
   # ...

  #pkg "Samsung_Magician_installer_Official_#{version}.pkg"
  pkg "Samsung_Magician_installer_Official_#{version}_modified.pkg"

  preflight do
    system "pkgutil", "--expand", "#{staged_path}/Samsung_Magician_installer_Official_#{version}.pkg", "#{staged_path}/Package_Content"
    system("sed -i -e '/ PRIVACY POLICY NOTICE\\/AGREEMENT /,/#\\*/ s/^/#/g' #{staged_path}/Package_Content/SamsungMagicianSVC.pkg/Scripts/preinstall")
    system "pkgutil", "--flatten", "#{staged_path}/Package_Content", "#{staged_path}/Samsung_Magician_installer_Official_#{version}_modified.pkg"
  end

   # ...
```

**Comment by bevanjkay** [comment]
I don't think we should be modifying the installer. There's an expectation that when installing a cask we simply automate installing the software as provided by upstream.

**Comment by breckwagner** [comment]
I agree. It would be annoying to maintain. The pkg contains a preinstall script which contains calls to `osascript` to display alerts and dialogs. I don't know how to suppress them.

**Pull request closed without merging**
