### PR TITLE
Update cleanmymac from 4.6.2,1586337770 to 4.6.2

### LINKED ISSUE #81815: CleanMyMac X downloaded app fail to open, because of the link
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ ] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The download link is not right, https://dl.devmate.com/com.macpaw.CleanMyMac4/CleanMyMacX.dmg is the right link, and current link, the app fails to open

#### Command that failed

```
Downloading https://dl.devmate.com/com.macpaw.CleanMyMac4/4.6.2/1586337770/CleanMyMacX-4.6.2.zip
```

#### Output of command with `--force --verbose --debug`

```
{{replace this}}
```

#### Output of `brew cask doctor`

```
{{replace this}}
```

#### Output of `brew tap`

```
{{replace this}}
```

### PR DESCRIPTION
**Pull request by miccal**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

Closes https://github.com/Homebrew/homebrew-cask/issues/81815

### CODE REVIEW

**Comment by public-accounts** [comment]
I am not sure why whenever I use homebrew install cleanmymac even with the correct link, it still fails to open

**Comment by miccal** [comment]
@public-accounts what if you use the command `brew cask install cleanmymac --no-quarantine`?

**Comment by public-accounts** [comment]
still not working

**Comment by public-accounts** [comment]
screenshot

**Comment by vitorgalvao** [comment]
@public-accounts If the installation works and you’ve done it with `--no-quarantine`, the issue is on your setup, not HBC. That’s strengthened by the fact you seem to be the only one facing issues on a popular cask:

```
cleanmymac
30 days: 911 (#474)
90 days: 1,869 (#534)
365 days: 5,850 (#562)
Age: 2367 days (added 2013, November 09)
```

Wherever the issue lies, it’s likely on your side, so you’ll have to fix it yourself.

On another note, please don’t post screenshots or your terminal, certainly not gigantic ones with mostly empty space.

**Pull request merged**
