### PR TITLE
HOLD: Update Filezilla.app: Snow Leopard compatible

### PR DESCRIPTION
**Pull request by bashu**
3.8.1 is a last one that works on 10.6

### CODE REVIEW

**Comment by ndr-qef** [comment]
If the SourceForge URLs are bundling other software, the issue must be addressed separately — and with greater priority.

Adding a Snow Leopard–compatible version is fine, but download mirrors of unknown reliability must be avoided. In this case, the original SourceForge URL appears to be still available, and is preferred.

**Comment by bashu** [comment]
Yeah, here it is http://sourceforge.net/projects/filezilla/files/FileZilla_Client/3.8.1/FileZilla_3.8.1_macosx-x86.app.tar.bz2/download when you download it, you get "SourceForge Installer" instead, which will not run on SL
screen shot 2015-01-07 at 9 35 16 am

**Comment by bashu** [comment]
can we use "http://heanet.dl.sourceforge.net/project/filezilla/FileZilla_Client/3.8.1/FileZilla_3.8.1_macosx-x86.app.tar.bz2" instead?

**Comment by ndr-qef** [comment]
It seems SourceForge is serving the proper, unbundled application to curl clients. (Were we served the pkg bundle, `brew cask install filezilla` would fail, because the only declared artifact is `FileZilla.app`.)

It should be safe to use the same `url` for both releases.

**Comment by bashu** [comment]
fixed (and tested) as @ndr-qef suggested

**Comment by ndr-qef** [comment]
Thanks. Merged as a11eb68, with the following changes:
- removed trailing whitespace;
- removed vestigial commit messages.

**Pull request closed without merging**
