### PR TITLE
Add Dyalog APL

### PR DESCRIPTION
**Pull request by heyajulia**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by heyajulia** [comment]
I'm aware of at least three problems:

`brew install --cask --verbose ./dyalog-apl.rb` inexplicably returns:

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from d89a2c1a1 to 2424e58b9.
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 1 cask.

==> Caveats
The vendor offers a free license for dyalog-apl at:
  https://www.dyalog.com/download-zone.htm

Installing dyalog-apl means you have AGREED to the license at:
  https://www.dyalog.com/uploads/documents/Developer_Software_Licence.pdf

==> Downloading https://www.dyalog.com/uploads/php/download.dyalog.com/download.php?file=18.0/mac_64_18.0.39712_unicode.pkg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.7.0-78-g2424e58\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://www.dyalog.com/uploads/php/download.dyalog.com/download.php\?file=18.0/mac_64_18.0.39712_unicode.pkg
Already downloaded: /Users/julia/Library/Caches/Homebrew/downloads/e11f11bd506f1268eac8a4bb0b44dda118e3acd4c33a9fb2ffd1b006bb67e193--mac_64_18.0.39712_unicode.pkg
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
/usr/bin/xattr -p com.apple.quarantine /Users/julia/Library/Caches/Homebrew/downloads/e11f11bd506f1268eac8a4bb0b44dda118e3acd4c33a9fb2ffd1b006bb67e193--mac_64_18.0.39712_unicode.pkg
==> Verifying checksum for cask 'dyalog-apl'.
hdiutil imageinfo -format /Users/julia/Library/Caches/Homebrew/downloads/e11f11bd506f1268eac8a4bb0b44dda118e3acd4c33a9fb2ffd1b006bb67e193--mac_64_18.0.39712_unicode.pkg
==> Installing Cask dyalog-apl
cp -p /Users/julia/Library/Caches/Homebrew/downloads/e11f11bd506f1268eac8a4bb0b44dda118e3acd4c33a9fb2ffd1b006bb67e193--mac_64_18.0.39712_unicode.pkg /usr/local/Caskroom/dyalog-apl/18.0.39712/mac_64_18.0.39712_unicode.pkg
/usr/bin/xattr -p com.apple.quarantine /Users/julia/Library/Caches/Homebrew/downloads/e11f11bd506f1268eac8a4bb0b44dda118e3acd4c33a9fb2ffd1b006bb67e193--mac_64_18.0.39712_unicode.pkg
/usr/bin/xattr -p com.apple.quarantine /Users/julia/Library/Caches/Homebrew/downloads/e11f11bd506f1268eac8a4bb0b44dda118e3acd4c33a9fb2ffd1b006bb67e193--mac_64_18.0.39712_unicode.pkg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5fe4d7d3\;Homebrew\\x20Cask\;B2AD7D78-FEBF-438A-B240-3153F76BC45A
==> Running installer for dyalog-apl; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
/usr/bin/sudo -E -- /usr/bin/env LOGNAME=julia USER=julia USERNAME=julia /usr/sbin/installer -pkg /usr/local/Caskroom/dyalog-apl/18.0.39712/mac_64_18.0.39712_unicode.pkg -target / -verboseR
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
installer: Package name is mac_64_18.0.39712_unicode
installer: Upgrading at base path /
installer:PHASE:Installatie voorbereiden…
installer:PHASE:Schijf voorbereiden…
installer:PHASE:mac_64_18.0.39712_unicode voorbereiden…
installer:PHASE:Wachten totdat andere installaties zijn voltooid…
installer:PHASE:Installatie configureren…
installer:STATUS:
installer:%2.200000
installer:PHASE:Geldigheid van pakketten valideren…
installer:%4.415075
installer:PHASE:Bestanden schrijven…
installer:%11.407923
installer:PHASE:Bestanden schrijven…
installer:%26.288822
installer:PHASE:Bestanden schrijven…
installer:%42.409796
installer:PHASE:Bestanden schrijven…
installer:%52.330396
installer:PHASE:Bestanden schrijven…
installer:%58.530770
installer:PHASE:Bestanden schrijven…
installer:PHASE:Bestanden schrijven…
installer:PHASE:Bestanden schrijven…
installer:%59.770845
installer:PHASE:Bestanden schrijven…
installer:%62.250995
installer:PHASE:Bestanden schrijven…
installer:%67.211295
installer:PHASE:Bestanden schrijven…
installer:%76.973963
installer:PHASE:Oude bestanden verwijderen…
installer:%96.530112
installer:PHASE:Opschonen…
installer:PHASE:Geldigheid van pakketten valideren…
installer:%97.750000
installer:STATUS:
installer:PHASE:Installatie voltooien…
installer:STATUS:
installer:%100.000000
installer:PHASE:De installatie is geslaagd.
installer: The upgrade was successful.
==> Purging files for version 18.0.39712 of Cask dyalog-apl
Error: It seems there is already an App at '/Applications/Dyalog-18.0.app'.
```

Uninstalling also does not work:

```
❯ brew uninstall --cask --verbose ./dyalog-apl.rb
Error: Cask 'dyalog-apl' is not installed.
```

I think it did work before, though.

Additionally, `brew style ./dyalog-apl.rb` returns:

```
dyalog-apl.rb:7:9: C: Description shouldn't start with an article.
  desc "The tool of thought for software solutions"
        ^^^

1 file inspected, 1 offense detected, 1 offense auto-correctable
```

This turns "The tool of thought for software solutions" into the ungrammatical "Tool of thought for software solutions".

If you can help me with those three problems, that'd be great.

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @heyajulia.

**Review by miccal — APPROVED** [review]

**Comment by heyajulia** [comment]
Hi @miccal, the CI also returned some other failures, and I would still like to fix them. Can I still do that?

**Comment by miccal** [comment]
@heyajulia I had already fixed the failures and our CI system passed, which is necessary for merging, so there is no need.

**Comment by heyajulia** [comment]
That's great to hear, thank you! 

Yesterday, I saw something about "Dyalog GPU Helper.app" (I don't remember the exact name) which my script apparently forgot to uninstall. Was that a false positive?

**Comment by miccal** [comment]
> That's great to hear, thank you!
> 
> Yesterday, I saw something about "Dyalog GPU Helper.app" (I don't remember the exact name) which my script apparently forgot to uninstall. Was that a false positive?

Yes, because there was an issue with the `uninstall` which is now fixed.

**Pull request merged**
