### PR TITLE
Update reaper from 5.97.800 to 5.97.900

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
@vitorgalvao the changed versionnumber has caused major havoc on our side ;/ any possibility to revert this?

**Comment by vitorgalvao** [comment]
@core-code Do you need the trailing zeros, or would this suffice as `5.97.9`?

**Comment by core-code** [comment]
thanks for your quick reply. i've had a look but sadly i see no easy way to make due without those zeroes (they are in the CFBundleVersion and trying to remove things won't work on older versions of that app).
if its a problem on your end, i can always fork the cask.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/commit/004b18f3a191d966d179bb58af9e0e0b6a8485c5

**Pull request merged**
