### PR TITLE
Upgrade iStat Menus.app to v5.11.

### PR DESCRIPTION
**Pull request by mwek**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 8ae1b9b01182e413c33db1addf91cc3d03fae766 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by ykelvis** [comment]
Sorry if this is not proper place to append.
I got sha256 mismatch when install.

Error message:
~$ brew cask install istat-menus
==> Downloading https://s3.amazonaws.com/bjango/files/istatmenus5/istatmenus5.11.zip
######################################################################## 100.0%
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: cb02606a90e1cf4a9b771b6e0418c1e37233e4d736be285d03e7f5f2f9d6d5c4
Actual: 720782256c427808669cef16bdb01cd7953c22d6f8a78d10a796f7e0fbcacf3e
File: /Library/Caches/Homebrew/istat-menus-5.11.zip
To retry an incomplete download, remove the file above.

**Comment by mwek** [comment]
ykelvis: looks that the downloaded file has changed - the new one has different checksum. The questions "why?" and "is the new file safe?" remain open.

**Comment by vitorgalvao** [comment]
> ykelvis: looks that the downloaded file has changed - the new one has different checksum. The questions "why?" and "is the new file safe?" remain open.

Unfortunately, it’s not uncommon for developers to update the app in place, invalidating the old checksum.

**Pull request closed without merging**
