### PR TITLE
Update subutaicontrolcenter to 7.2.2

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
It’s the `preflight` that’s failing. Since you changed the `url`, it might no longer be needed.

**Comment by core-code** [comment]
this was my first idea too, so actually i tried it without the preflight in the second commit. it didn't seem to change a thing

**Comment by vitorgalvao** [comment]
Now it’s `pkg source file not found: 'subutai-control-center.pkg'`.

**Comment by reitermarkus** [comment]
Could use an `url do` block and build the URL with the output of `https://bazaar.subutai.io/rest/v1/cdn/raw?name=subutai-control-center.pkg&latest`.

**Comment by reitermarkus** [comment]
> they look like they could be temporary

```
https://bazaar.subutai.io/rest/v1/cdn/raw?name=subutai-control-center.pkg&latest
```

```json
{
  "id" : "QmesUxiXFf2LsJpRaDLmQafQmb7miCez1jMCQRSzbXpcuH",
  "filename" : "subutai-control-center.pkg",
  "upload_date" : "2018-10-27T10:35:00",
  "raw_details" : [ {
    "owner" : "jenkins",
    "md5" : "2d1331ee950df28dc9996aebd3e0dd3b",
    "digest" : "2d1331ee950df28dc9996aebd3e0dd3b",
    "size" : 17671526,
    "type" : "RAW",
    "owner-id" : 14,
    "digest-method" : "md5",
    "change-date" : "2018-10-27T10:35:00"
  } ],
  "upload_timestamp" : 1540636500784
}
```

```
https://ipfs.subutai.io/ipfs/QmesUxiXFf2LsJpRaDLmQafQmb7miCez1jMCQRSzbXpcuH/subutai-control-center.pkg
```

It's an ID, so it doesn't seem temporary. Anyways, this is better than having the `preflight` hack.

**Pull request merged**
