### PR TITLE
Update parallels to 14.1.1-45476

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Isn’t this the version that gave errors even when tried manually?

**Comment by core-code** [comment]
its the next one released yesterday or so

but the error is the same

should i close this?

**Comment by vitorgalvao** [comment]
If we can’t get this to work, might as well keep the version we have for now. Maybe a Parallels user will eventually find a solution. The cask is `#249` over the last 90 days, according to analytics.

But it reminds me. @reitermarkus You’re a Parallels user. Have you not encountered this issue?

**Comment by reitermarkus** [comment]
> Have you not encountered this issue?

No, since I'm still using Parallels 13.

**Pull request closed without merging**
