### PR TITLE
Netgear switch discovery tool

### PR DESCRIPTION
**Pull request by ericpardee**
After making all changes to the cask:

- [ x] `brew cask audit --download {{cask_file}}` is error-free.
- [x ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x ] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] **I verified this change is legitimate**<sup>[how do I do that?][version-checksum]</sup>. I did so because `sha256` was altered, but `version` was not. I’m providing confirmation below, [as instructed by the guide][version-checksum].

Additionally, if **adding a new cask**:

- [x ] Named the cask according to the [token reference].
- [x ] `brew cask install {{cask_file}}` worked successfully.
- [x ] `brew cask uninstall {{cask_file}}` worked successfully.
- [x ] Checked there are no [open pull requests] for the same cask.
- [x ] Checked the cask was not already refused in [closed issues].
- [x ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
Please submit this to [`caskroom/drivers`](https://github.com/caskroom/homebrew-drivers)

**Comment by ericpardee** [comment]
It's not a driver, it's a utility. Are you sure?

**Comment by commitay** [comment]
As it is hardware specific it belongs in `drivers`.

**Comment by ericpardee** [comment]
👍🏼

**Pull request closed without merging**
