### PR TITLE
Update baiduhi

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
@otakustay @nerddan @haha1903 can you please verify that this is the same app despite the name change?

**Comment by otakustay** [comment]
Yes, this is only a name change

**Comment by core-code** [comment]
@otakustay thanks for the confirmation!

**Comment by core-code** [comment]
@vitorgalvao do we need to rename the cask? are 4 name stanzas OK?

**Comment by vitorgalvao** [comment]
Yes, I guess we should rename it. No problem with the four names, even if unconventional.

**Comment by core-code** [comment]
> Yes, I guess we should rename it.

if you tell me the new name i can send a PR

**Comment by vitorgalvao** [comment]
@otakustay Does `ruliu` make sense as the name for this?

**Comment by otakustay** [comment]
@vitorgalvao  The official english name should be "infoflow", I have asked our product manager to ensure this.

**Comment by core-code** [comment]
thanks there.

i've done the re-name to 'infoflow' now. 

unfortunately i've missed that button again and did a direct commit instead of sending a PR :(

**Pull request merged**
