### PR TITLE
Update adobe-creative-cloud to v4.7.0.400

### PR DESCRIPTION
**Pull request by ahousseini**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ahousseini** [comment]
I was not sure how to write the `uninstall ` stanza. There is a `Creative Cloud Uninstaller.app` bundle, but I was not able to run it silently.

**Comment by vitorgalvao** [comment]
Considering the Travis error, looks like this didn’t work.

We don’t really care for Adobe apps. They have given us enough headaches to last a lifetime, which is why we removed the others. If you’re able to write correct code for this, we’ll merge it, but I doubt any maintainer wants to keep banging their head on a such a user-hostile company.

**Comment by ran-dall** [comment]
> such a user-hostile company.

@vitorgalvao **WELL SAID** ✊

**Comment by vitorgalvao** [comment]
Lets leave as is for now. We can revisit if https://github.com/Homebrew/homebrew-cask/issues/24377 ever comes to light.

**Pull request closed without merging**
