### PR TITLE
Added Pfiddlesoft UI Browser 2.5.0

### LINKED ISSUE #12003: Cask request: UI Browser
[Website](http://pfiddlesoft.com/uibrowser/).

If anyone feels inclined to do it before I get to it, so much the better. It is a `pkg`, so some time needs to be spent on uninstallation.

### PR DESCRIPTION
**Pull request by SeanSith**
Closes #12003

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in eb84197ac44ed92f5b1032c1109498f4a3680c82. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by SeanSith** [comment]
Probably the tabs that I removed on a subsequent push? Sorry about that.

**Comment by vitorgalvao** [comment]
Bit more complex than that:
+ Remove the comment (not needed)
+ Simplifying substitution in `#{version}` (no need for regex).
+ Fixed `name` (it should be written as it is by the vendor).
+ Small cosmetic changes.

**Comment by vitorgalvao** [comment]
Bit more complex than that:
+ Removed the comment (not needed)
+ Simplifying substitution in `#{version}` (no need for regex).
+ Fixed `name` (it should be written as it is by the vendor).
+ Small cosmetic changes.
+ Fixed cask token (`ui-browser` is closer to the name).

**Pull request closed without merging**
