### PR TITLE
dehelper: update livecheck and revert to 4.5.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — CHANGES_REQUESTED** [review]
Find a different way to do livecheck

**Comment by chenrui333** [comment]
This should work better now.

**Comment by bevanjkay** [comment]
Can we confirm that changing the build in the url fetches a different version of the application?

**Comment by chenrui333** [comment]
> Can we confirm that changing the build in the url fetches a different version of the application?

can you elaborate a bit?

**Comment by bevanjkay** [comment]
I just want to ensure that changing the `version.csv.second` value does download a different binary. I'm checking now.

**Comment by chenrui333** [comment]
this is my check


```
# 4.5.4
$ curl -sL https://static.frdic.com/pkg/dhmac.dmg?v=1120 | shasum -a 256
e20a93c9f00fae04038a9efe157563e084ccbcfa69b97265c8cbfdf241c612d7  -

$ curl -sL https://static.frdic.com/pkg/dhmac.dmg?v=2023-11-15 | shasum -a 256
e20a93c9f00fae04038a9efe157563e084ccbcfa69b97265c8cbfdf241c612d7  -

#4.6.1
$ curl -sL https://static.frdic.com/pkg/dhmac.dmg?v=1145 | shasum -a 256
e20a93c9f00fae04038a9efe157563e084ccbcfa69b97265c8cbfdf241c612d7  -

$ curl -sL https://static.frdic.com/pkg/dhmac.dmg?v=2024-01-09 | shasum -a 256
e20a93c9f00fae04038a9efe157563e084ccbcfa69b97265c8cbfdf241c612d7
```

**Comment by bevanjkay** [comment]
In that case I guess doing a non-versioned url with no checksum is the only option.

**Comment by chenrui333** [comment]
cc @FischLu for thoughts.

**Comment by FischLu** [comment]
I think a non-versioned url with no checksum is ok in such case @chenrui333

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
