### PR TITLE
Update vscodium from 1.34.0 to 1.35.0

### PR DESCRIPTION
**Pull request by optikfluffel**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by jrappen** [comment]
@optikfluffel The path for binary has changed with 1.35.0 and should point to the binary `codium` as per the release notes, compare vscodium/vscodium#176

**Comment by jrappen** [comment]
@optikfluffel I take that back. It didn’t change on macOS.

**Comment by stripedpajamas** [comment]
Looks good as is 👍

**Pull request merged**
