### PR TITLE
yandex-cloud-cli 0.116.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Livecheck is working for me locally. Any ideas @samford?

**Review by krehel — APPROVED** [review]

**Comment by samford** [comment]
> Livecheck is working for me locally. Any ideas @samford?

I pushed a temporary `strategy` block for debugging (to print the `page` contents) and it looks like we're encountering a CAPTCHA page on CI: https://github.com/Homebrew/homebrew-cask/actions/runs/7718069184/job/21038949043?pr=165615

This certainly isn't the first time I've seen a check that works locally and fails on CI. There's value in keeping the `livecheck` block since it works locally but the consistent CI failure is an issue.

If there aren't any alternative sources of version information that don't involve a CAPTCHA, it seems like our options are to either add an explanatory comment before the `livecheck` block (accepting that it will fail on CI) or remove the `livecheck` block entirely (so it will pass CI).

**Comment by p-linnane** [comment]
I think adding a comment, and using the `skip-livecheck` label for CI makes the most sense.

**Comment by p-linnane** [comment]
Thank you @samford! 🙏

**Review by miccal — APPROVED** [review]

**Pull request merged**
