### PR TITLE
Add flymaster-designer (new cask)

### PR DESCRIPTION
**Pull request by jawshooah**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Why that token? It should be `b2designer`.

**Comment by jawshooah** [comment]
For consistency. The application refers to itself as `Flymaster Designer` internally, on the [product page](http://www.flymaster-avionics.com/products/designer) and in the [docs](http://downloads.flymaster.net/Flymaster%20Designer.pdf).

**Comment by jawshooah** [comment]
I actually think it might be prudent to add 
```ruby
# Renamed for clarity: app name is inconsistent with its branding.
# Original discussion: https://github.com/caskroom/homebrew-cask/pull/9334
app 'B2designer.app', :target => 'Flymaster Designer.app'

**Comment by vitorgalvao** [comment]
Sounds good. Here’s an image for reference, if someone follows the link.

**Comment by jawshooah** [comment]
Done.

**Comment by ndr-qef** [comment]
Excellent, thanks.

**Pull request merged**
