### PR TITLE
Add Nanobox Bundle Cask

### PR DESCRIPTION
**Pull request by liljenstolpe**
This installs the nanobox binary as well as Vagrant and VirtualBox (using nanobox's package), if necessary.  See https://www.nanobox.io/

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please check other casks. There are multiple issues with this. For starters, all the comments at the start must go, especially your name and email. No cask has a credit to who submitted. If that is important to you, then you should not be submitting here.

The rest of the cask also has information and structure problems, that can be observed by looking at other casks. On a first phase, the cask should look like:

```ruby
cask :v1 => 'nanobox-bundle' do
  version :latest
  sha256 :no_check

  # amazonaws.com is the official download host per the vendor homepage
  url 'https://s3.amazonaws.com/tools.nanobox.io/installers/mac/nanobox-bundle.dmg'
  name 'nanobox-bundle'
  homepage 'http://www.nanobox.io/'
  license :oss

  pkg 'nanobox.pkg'

  binary '/opt/nanobox/bin/nanobox'
end
```

But even then that are things to fix. Can’t you be more specific with the license? Also, where does `binary` come from? Are you saying the `nanobox.pkg` package installs a `nanobox` binary under `/opt/nanobox/bin/`?

Finally, it’s missing `uninstall`. There are [scripts](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#uninstall-stanza-details) geared for that.

**Comment by liljenstolpe** [comment]
Yes, the package installs a binary in /opt/nanobox/bin/nanobox.

**Comment by liljenstolpe** [comment]
Ok, will fix.  The pkg just installs a binary in /opt/nanobox/bin, as you surmise.

**Comment by liljenstolpe** [comment]
fixed all issues you mentioned.

**Comment by fanquake** [comment]
Same here. Please amend the commit message to something like "Add Nanobox cask", and remove everything else from the commit description.

**Comment by liljenstolpe** [comment]
Ok.

**Comment by liljenstolpe** [comment]
done

**Comment by fanquake** [comment]
No worries, thanks :beers:

**Comment by liljenstolpe** [comment]
A branching error just pushed a bunch into this pull request.  I'm fixing.  Will re-pull when cleaned up

**Pull request closed without merging**
