### PR TITLE
ghostty 1.0.1

### PR DESCRIPTION
**Pull request by Uzaaft**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Review by krehel — APPROVED** [review]

**Comment by Uzaaft** [comment]
dayum thats fast

**Comment by Uzaaft** [comment]
Oh wait, oversight from my part. 2s

**Comment by krehel** [comment]
We'll add this to our autobump list so updates will automatically be checked for every ~3 hours.

We also make tools for doing updates - you should use `brew bump` instead of manually editing files.  It will handle most of the tasks for you.

**Comment by krehel** [comment]
@Uzaaft please squash commits and force push to help keep the history clean.  Thanks!

**Comment by Uzaaft** [comment]
> We'll add this to our autobump list so updates will automatically be checked for every ~3 hours.
> 
> We also make tools for doing updates - you should use `brew bump` instead of manually editing files. It will handle most of the tasks for you.

Amazing! Great to know

**Review by krehel — APPROVED** [review]

**Pull request merged**
