### PR TITLE
Add livecheck to ui.rb

### PR DESCRIPTION
**Pull request by nilsstreedain**
This is the first livecheck I've added to a Cask so I apologize if my style needs correction beyond what is detected by the automations. Here are the changes:
- Updated to unversioned URL for livecheck
- Set sha256 to no check for unversioned URL
- Merged version array into single version for livecheck
- Added live check
- Opened package using new version

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why move to the unversioned download though?

**Comment by nilsstreedain** [comment]
> Why move to the unversioned download though?

I did that because it has the version for livecheck in the location header. I'm new to this so I'm happy to receive feedback, is there a preferred implementation?

**Comment by SMillerDev** [comment]
Unversioned downloads are much worse to maintain (they can change without notice) and to use (you don't know which version you're actually using). If you need a specific url in the livecheck block, specify it using `url "some-url"`

**Comment by nilsstreedain** [comment]
I've switched back to a versioned URL and updated the cask to the latest version but I have a question about builds within versions. It appears UI desktop often has later builds released using the same version number, for example `UI 0.56.3 (51)` and `UI 0.56.3 (58)`. However the version numbering appears differently in the URL such as `98a0-macOS-0.56.3-79aba98f601b49818f3dae0e3d34b754` and `b755-macOS-0.56.3-b2d6dcc1ca1b470db93a710da52de392`. Should the Cask and livecheck be updated for just the version `0.56.3` or for the individual build?

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
