### PR TITLE
Update plex-media-server to 1.13.5.5332-21ab172de

### PR DESCRIPTION
**Pull request by MindTooth**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
This isn't the current version of the homepage?

**Comment by MindTooth** [comment]
screen shot 2018-08-23 at 14 04 45
But I have this inside Plex.
screen shot 2018-08-23 at 14 06 28

**Comment by commitay** [comment]
https://www.plex.tv/media-server-downloads/#plex-media-server
screen shot 2018-08-23 at 22 08 35

https://plex.tv/api/downloads/1.json has `1.13.5.5332-21ab172de`

**Comment by MindTooth** [comment]
Updated.  Had beta channel activated.

**Pull request merged**
