### PR TITLE
Update julia from 1.7.2 to 1.7.3

### PR DESCRIPTION
**Pull request by singularitti**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by singularitti** [comment]
There is no binary release for Apple Silicon because Julia 1.7 on Apple Silicon was very broken: https://github.com/JuliaLang/julia/issues/45457

**Review by bevanjkay — DISMISSED** [review]

**Comment by miccal** [comment]
I have no idea why the CI machines are running `brew uninstall --cask --zap julia` before installing.

**Comment by bevanjkay** [comment]
@miccal The CI machines have julia installed on them in their default image, so it gets uninstalled to clean up the machine before CI runs.

**Review by bevanjkay — APPROVED** [review]

**Pull request closed without merging**
