### PR TITLE
Add Lunacy.app v8.6.0

### PR DESCRIPTION
**Pull request by avunix**
Add new cask Icons8 Lunacy app

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by p-linnane** [comment]
Thank you for your contribution to `homebrew-cask` @avunix. Please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask.

**Comment by p-linnane** [comment]
@miccal You beat me adding the versioned link & livecheck by like 30 seconds 😆

**Comment by avunix** [comment]
Thank you! added

**Comment by miccal** [comment]
Thank you @avunix.

**Review by miccal — APPROVED** [review]

**Pull request merged**
