### PR TITLE
Update cookie from 5.10 to 6.0.1

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
failure expected:
`macOS Mojave or newer is required.
`

**Comment by core-code** [comment]
with 'Catalina' around the corner, are there any plans to update Travis to a newer OS?

**Comment by reitermarkus** [comment]
We have GitHub Actions running on 10.14, but for some reason it isn't triggered sometimes, like in this PR, not sure what's up with that.

**Comment by reitermarkus** [comment]
I suspect it has to to with the fork not being up-to-date with `master`, but I couldn't reproduce it when I tried before.

**Comment by core-code** [comment]
is there anything that prevents this being merged?

**Pull request merged**
