### PR TITLE
windterm: remove exec attribute from formula

### PR DESCRIPTION
**Pull request by vszakats**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by vszakats** [comment]
Titillium CI fail complains about a livecheck issue. This commit changed the homepage, where both HTTPS and HTTP works the same. HTTPS version has some mixed-content issues with a few GIF/PNG images. Is there a way this can affect livecheck?

**Comment by bevanjkay** [comment]
I think we just disable `font-titillium` - there's no official distribution of it from the author that I can find, but Google Fonts distribute a slightly different package already in `homebrew-cask` as `font-titillium-web` that is probably a drop in replacement.

**Comment by vszakats** [comment]
@bevanjkay: Sounds reasonable. Shall I delete this commit? Or would you prefer to merge this, then delete it?

**Comment by bevanjkay** [comment]
Drop that commit and we can open another PR to disable. I can do that if you'd like, just let me know either way.

**Review by bevanjkay — APPROVED** [review]

**Comment by vszakats** [comment]
Dropped it. Please do the PR to disable, I'm not familiar with the process.

**Pull request merged**
