### PR TITLE
virtualbox 4.3.40-110317, 5.0.30-112061

### PR DESCRIPTION
**Pull request by yurikoles**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by yurikoles** [comment]
I haven't checked it old macOS, I just have good assumption that they don't drop OS support in minor releases.

**Comment by colindunn** [comment]
Should [virtualbox-extension-pack.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/virtualbox-extension-pack.rb) also be updated along with this cask?

**Comment by miccal** [comment]
@yurikoles would you mind updating [virtualbox-extension-pack.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/virtualbox-extension-pack.rb) also?

**Comment by neutric** [comment]
@yurikoles Thanks for completing the update. That was on my list of things to do still. :) I also have no way of checking, but based on [this](https://www.virtualbox.org/manual/ch01.html#hostossupport), your assumption most likely is correct. I went ahead and updated the extension pack in #28138.

**Pull request merged**
