### PR TITLE
Microsoft Office 16.80.23121017

### PR DESCRIPTION
**Pull request by unshare**
Standalone applications installers are updated as well.
Microsoft Auto Updater is already updated.

Passing audit depends on merging a workaround into Homebrew itself
(https://github.com/Homebrew/brew/pull/16349).
The only issue is homepage availability check. Otherwise, the update
just works.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @unshare, but we are already updating these in https://github.com/Homebrew/homebrew-cask/pull/162498 and https://github.com/Homebrew/homebrew-cask/pull/162477

**Comment by unshare** [comment]
@miccal That doesn't resolve audit errors, but whatever.

**Comment by miccal** [comment]
Apologies @unshare, I did not see the corresponding PR in `homebrew/brew`.

**Comment by unshare** [comment]
@miccal, please take another look.
The related PR into [Homebrew/brew](https://github.com/Homebrew/brew) is merged, audit is all green.

**Comment by krehel** [comment]
Thanks @unshare for taking it upon yourself to address the broader issue and fix this for the community as a whole.  Very helpful and appreciated!

**Review by krehel — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @unshare.

**Pull request merged**
