### PR TITLE
Update gemini to 2.4.3

### PR DESCRIPTION
**Pull request by cameronmalek**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by cameronmalek** [comment]
I noticed that the checksum has been invalid for a few weeks now, and this updates it.

TravisCI:

```
audit for gemini: failed
 - only sha256 changed (see: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md)
Error: audit failed for 1 cask: gemini
```

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by cameronmalek** [comment]
Evidence of SHA256 change in download package:

1. When running `brew cask install gemini` it results in an error presently and tells you that `c3c2ef623bee5fc43c845ad5537cba4f3eb518d881db25db1e5a09ea69d5508e` is the correct SHA at this moment in time (see diff for this PR, and it matches).
2. When running `curl -LO 'https://dl.devmate.com/com.macpaw.site.Gemini2/Gemini2.dmg'  && shasum -a 256 Gemini2.dmg` it returns with `c3c2ef623bee5fc43c845ad5537cba4f3eb518d881db25db1e5a09ea69d5508e  Gemini2.dmg`, which matches the SHA in my PR.
3. When uploading the file from point #2 to **VirusTotal,** `c3c2ef623bee5fc43c845ad5537cba4f3eb518d881db25db1e5a09ea69d5508e` is the SHA256 it reports, as seen at **https://www.virustotal.com/#/file/c3c2ef623bee5fc43c845ad5537cba4f3eb518d881db25db1e5a09ea69d5508e/detection**

NOTE: VirusTotal does not show the SHA256 for this download with the URL, only with the uploaded file. See: https://www.virustotal.com/#/url/48c89c57896803f1db0d73347d097e8de640e5ec029c6645cf899e8d8a758615/details

Additionally, no public statement was found from MacPaw, the publisher of Gemini, that the file has changed or any posting of checksums.

**Comment by commitay** [comment]
> https://www.virustotal.com/#/file/c3c2ef623bee5fc43c845ad5537cba4f3eb518d881db25db1e5a09ea69d5508e/details

**Review by commitay — APPROVED** [review]
Valid signature.

**Comment by vitorgalvao** [comment]
@cameronmalek We don’t need evidence of the file having been changed. We can see it changed. What we need is proof that the change is legitimate and not the result of a malicious actor, hence why we have the specific verification steps.

**Pull request merged**
