### PR TITLE
Miniforge support ARM

### LINKED ISSUE #95776: How to create a cask with different binaries for intel / M1
I would like to create a cask that uses different binaries (i.e. URLs) for Intel and M1 processors. Unfortunately the app is not available (yet) as a universal binary. What is the recommend way to do this?  Or better: is it possible at all?

### PR DESCRIPTION
**Pull request by domoritz**
fixes https://github.com/Homebrew/homebrew-cask/issues/95776

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Because the script’s name changes, `installer script` will also need to be inside the conditional.

**Comment by domoritz** [comment]
Good catch. Updated.

**Comment by domoritz** [comment]
Would it make sense to instead of putting the whole property into the conditional to use a ternary and change the strings (similar to the version)?

**Comment by vitorgalvao** [comment]
This way is more consistent with other casks. It’s not that much code, so the small amount of repetition isn’t problematic and will make fixes easier if they ever diverge.

**Comment by domoritz** [comment]
I updated the formula with what I meant. Let me know what you think.

**Comment by vitorgalvao** [comment]
Clever, but the way you had it is better because it’s simpler for others to understand. Those are lines that should seldom need to be revisited (due to the interpolation), so clarity is more important than brevity.

**Comment by domoritz** [comment]
I like the current version and think it's quite readable (note, I am not a ruby developer and I was able to write this by just guessing). If you disagree, I am happy to revert 073cf7db3991cedb446f460f381b1c1e32129a83.

**Comment by domoritz** [comment]
Reverted to the explicit version.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
