### PR TITLE
Update oxygen-xml-editor from 24.0,2021121518 to 24.0,2022012607

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by joewiz** [comment]
@neutric Thank you!

I wonder why the livecheck added in https://github.com/Homebrew/homebrew-cask/pull/115747 didn't catch this and other recent releases? The definition is at https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/oxygen-xml-editor.rb#L12-L21.

**Comment by neutric** [comment]
@joewiz I only knew about this because of `livecheck`. If you saw other versions but `livecheck` didn't then https://www.oxygenxml.com/rssBuildID.xml must not publish all of them. Maybe ping me again when this issue pops up again and we'll try to find a better source for `livecheck`?

**Comment by joewiz** [comment]
@neutric Ah! I thought livecheck happened automatically and meant we wouldn't need to submit PRs. How do you trigger a livecheck report?

**Comment by neutric** [comment]
@joewiz With `brew livecheck <list>` where `<list>` is a list of formulae/casks (separated by whitespace) that you care about. Alternatively, if no formula or cask argument is passed, the list of formulae and casks to check is taken from `HOMEBREW_LIVECHECK_WATCHLIST` or `~/.brew_livecheck_watchlist`.

**Pull request merged**
