### PR TITLE
Update Julia to v0.6.4

### PR DESCRIPTION
**Pull request by ararslan**
After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

I haven't run the `brew` commands as I'm on Linux currently. Any help with those would be much appreciated.

### CODE REVIEW

**Comment by commitay** [comment]
Thanks for the PR!

**Comment by W4anD0eR96** [comment]
@ararslan could you please show me how to generate the `sha256` part so that I can help to bring new version of Julia to homebrew-cask?

**Comment by ararslan** [comment]
The SHA for each of the downloads is available on the [downloads page](https://julialang.org/downloads), where it says checksums in MD5 and SHA256 format. I happened to have it handy though, since I had to generate those checksum files. 🙂

**Comment by W4anD0eR96** [comment]
Get it!

**Pull request merged**
