### PR TITLE
Update endnote to latest

### PR DESCRIPTION
**Pull request by mjsteinbaugh**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by miccal** [comment]
I believe this is now a `manual` install, as the latest version downloads a `dmg` with `Install EndNote X8.app` inside?

**Comment by mjsteinbaugh** [comment]
Oh geez you're right, sorry about that. I didn't realize Clarivate Analytics changed the installer format. Is there anything we can add in the recipe to automate this step?

**Comment by commitay** [comment]
PR with updated `install` https://github.com/caskroom/homebrew-cask/pull/33535

**Comment by miccal** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/33535.

**Pull request closed without merging**
