### PR TITLE
updated codekit (2.9)

### PR DESCRIPTION
**Pull request by toonetown**
- [X] The commit message includes the cask’s name and version.
- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]
Can be merged as is if Travis passes, if there are no changes after this approval.

**Comment by vitorgalvao** [comment]
Why close? What’s the issue with it?

**Comment by toonetown** [comment]
Because I deleted the branch because I thought it was merged 😠

**Comment by vitorgalvao** [comment]
> Because I deleted the branch because I thought it was merged 😠 

Apologies. It happens so many times that I have to review a cask twice (because the first time) Travis hadn’t finished yet, thought of trying to approval system to let myself and other maintainers know it had already been reviewed.

**Comment by toonetown** [comment]
> Apologies. It happens so many times that I have to review a cask twice (because the first time Travis hadn’t finished yet), thought of trying the approval system to let myself and other maintainers know it had already been reviewed.

Don't apologize.  It was my own fault for not actually reading the status update that you posted.  You were very clear on it.

**Pull request merged**
