### PR TITLE
doc: update OSDN URL rules

### PR DESCRIPTION
**Pull request by vszakats**
Ref: https://github.com/Homebrew/brew/pull/5052

Affected Casks:
- letterfix
- miditrail
- nndd

### CODE REVIEW

**Comment by commitay** [comment]
Can you add the affected casks as well to please?

**Comment by commitay** [comment]
Not sure what to change this to:

http://osdn.dl.osdn.jp/users/8/8642/genjyuugothic-20150607.zip

The homepage has this URL:
https://osdn.jp/downloads/users/8/8644/genjyuugothic-x-20150607.zip

but the `audit` doesn't like it.

**Comment by vszakats** [comment]
This is the closest URL I could find:
https://osdn.net/downloads/users/8/8644/genjyuugothic-x-20150607.zip/
(via <https://osdn.net/users/mm-rounded/pf/genshin/files/?id=8632>)

One solution is to also allow `/downloads/` instead of `/dl/`.

**Comment by commitay** [comment]
Whoops. I copied the wrong URL from the homepage, updated my comment above.

> One solution is to also allow /downloads/ instead of /dl/.

This seems like the easist option. 👍

**Comment by vszakats** [comment]
It looks like these are files associated with a specific username, not with a project, hence the different URL scheme.

**Comment by commitay** [comment]
> Can you add the affected casks as well to please?

Sorry, I meant add the actual casks to this PR.

**Comment by vszakats** [comment]
There you go.

**Comment by commitay** [comment]
Thanks!

**Pull request closed without merging**
