### PR TITLE
Update controllermate to 4.11.1

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
help pls
```
==> Uninstalling packages:
com.orderedbytes.controllermate.com.orderedbytes.ControllerMateHelper.pkg
Permission denied @ dir_initialize - /private/tmp/com.orderedbytes.controllermate.install
```

**Comment by brianmorton** [comment]
cc @vitorgalvao @commitay

**Comment by core-code** [comment]
perhaps @reitermarkus can help ;)

**Comment by core-code** [comment]
while we are at it, can you add a depends_on, as this cask requires 10.13 now?

ideally we'd link these versions for older releases:

ControllerMate v4.10.4 can be used with macOS 10.12
ControllerMate v4.9.10 can be used with Mac OS X 10.8 — 10.11

**Comment by brianmorton** [comment]
@core-code just open a new PR... I don't like keeping stale PRs open so I'm closing this.

**Comment by core-code** [comment]
will do, thanks for your effort.

**Pull request closed without merging**
