### PR TITLE
faxbot: Remove cask

### PR DESCRIPTION
**Pull request by p-linnane**
Website has been 404ing for a few days. Also has a low install count.

```
==> Analytics
install: 3 (30 days), 5 (90 days), 23 (365 days)
```

### CODE REVIEW

**Review by miccal — APPROVED** [review]

**Comment by tcurdt** [comment]
The owner wasn't aware his website was down. What's the process to get this re-added?

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Adding-Software-to-Homebrew#casks

**Comment by tcurdt** [comment]
@SMillerDev Thanks, but that only covers adding a new cask - not restoring a previous one.
Does that mean starting from scratch (despite the previous formula) is the way to go?

**Comment by p-linnane** [comment]
@tcurdt It looks like the last update to the application was in June 2021, and the download numbers from `brew` were quite low. I'm not sure if this is worth readding. It might be better hosting it in your own [tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#creating-a-tap).

**Comment by tcurdt** [comment]
TBH that does not feel that particular old for a cask.
As I am not the author, hosting a tap for it feels a bit odd.
But if download numbers matter - it is what it is.

**Comment by p-linnane** [comment]
[Acceptable Casks](https://docs.brew.sh/Acceptable-Casks#rejected-casks) defines an application that has not had a release in the last year as an "unmaintained app".

Also, is it not required to be the author to host your own tap. You can even host it privately, brew is just `git` underneath. 

If there is a strong need for it to be in the core repos, I can open a PR to readd it. But I will defer to @SMillerDev on the odds of it getting merged given all this information.

**Comment by kortenkamp** [comment]
There is at least one other person (me) who would like to see this re-added. I wasn't aware that this has been removed, and when I just used `brew bundle` to install a new machine it was missing Faxbot. So, @p-linnane , I would be glad if you could open that PR. Otherwise I will try by adding it again.

Regarding the term "unmaintained app" – well, Faxbot is rather stable and feature complete, so there is no real need to update it every few months.

**Comment by SMillerDev** [comment]
If it works I'm fine with it being resubmitted. But if it 404s again it will most likely be removed again.

**Comment by p-linnane** [comment]
Readded in https://github.com/Homebrew/homebrew-cask/pull/136371.

**Comment by kortenkamp** [comment]
Thank you!

**Pull request merged**
