### PR TITLE
Add Soulver CLI

### PR DESCRIPTION
**Pull request by zcohan**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask (soulver), verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask** (soulver-cli):

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
-  [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
` - GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)`
I'm the developer of Soulver, which is fairly well known and has been on the Mac since 2005. There already exists a cask for the main GUI Soulver.app. This is a new standalone command line interface to it, which was only just released. I'd like to have homebrew support out of the box for easier installation.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]
Looks like an open source CLI tool to me, so it would have to be a formula not a cask.

**Comment by zcohan** [comment]
> Looks like an open source CLI tool to me, so it would have to be a formula not a cask.

No, it's a closed source binary.

**Comment by p-linnane** [comment]
Thank you for your submission @zcohan. We are unable to accept it at this time because it does not pass Homebrew's notability check:

>GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if the app becomes more popular in the future we would be happy to consider adding this to `homebrew-cask`.

**Comment by zcohan** [comment]
> Thank you for your submission @zcohan. We are unable to accept it at this time because it does not pass Homebrew's notability check:
> 
> > GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
> 
> Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if the app becomes more popular in the future we would be happy to consider adding this to `homebrew-cask`.

According to the [Homebrew documentation](https://docs.brew.sh/Acceptable-Casks#exceptions-to-the-notability-threshold) an exception can be made to the notability rule in the case that:

`A popular app that has its own website but the developers use GitHub for hosting the binaries. That repository won’t be notable but the app may be.`

[Soulver](https://soulver.app) is a popular app, and we're using Github for hosting the CLI binary version of it. The CLI tool is really just a pre-built wrapper around the [SoulverCore](https://github.com/soulverteam/SoulverCore) framework, which does meet the cask notability requirement.

**Review by miccal — APPROVED** [review]

**Pull request merged**
