### PR TITLE
Creating BirdFont 1.0 Cask

### PR DESCRIPTION
**Pull request by yell0wghost**

### CODE REVIEW

**Comment by rolandwalker** [comment]
Hi!  Thanks!

Travis is failing because it wants the last word of the file to say `end` (this is missing the "d").

**Comment by kodejn** [comment]
Hi, thanks for info. I got it. It's my first Github commit. I had small problem with environment, but actually I think I'm in!

**Comment by rolandwalker** [comment]
Welcome!

Can you [squash](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#squashing) these?

**Comment by ndr-qef** [comment]
Thanks. Merged as c7d5f0e.

**Pull request closed without merging**
