### PR TITLE
Update katrain from 1.11.1 to 1.11.2

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by chatdesk** [comment]
@neutric Can you update to the latest tag, the build had an error

**Comment by sanderland** [comment]
@neutric can you update this to the latest tag with the fixed binary? thanks!

**Comment by neutric** [comment]
@sanderland Will do! Would it be possible to remove the tag "[v1.11.2fixmac](https://github.com/sanderland/katrain/releases/tag/v1.11.2fixmac)"? `brew livecheck` detects this one as most recent version and I'd like to avoid a manual override if easily possible.

**Comment by chatdesk** [comment]
> @sanderland Will do! Would it be possible to remove the tag "[v1.11.2fixmac](https://github.com/sanderland/katrain/releases/tag/v1.11.2fixmac)"? `brew livecheck` detects this one as most recent version and I'd like to avoid a manual override if easily possible.

I think I managed now!

**Comment by neutric** [comment]
> @neutric can you update this to the latest tag with the fixed binary? thanks!

See #126535.

**Pull request closed without merging**
