### PR TITLE
Update metasploit from 6.0.2,20200820102910 to latest

### PR DESCRIPTION
**Pull request by mojotx**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by mojoTX** [comment]
This is a work-in-progress. The metasploit packages change so quickly that we need to either just use the "latest" URL, or else automate the process to update the cask based on the latest URL and SHA256.

**Comment by mojoTX** [comment]
This seems to work, if we want to grab the latest version. Ideally we would validate the PGP signature of the package, by downloading from https://osx.metasploit.com/metasploitframework-latest.pkg.asc and using `gpg --verify metasploitframework-latest.pkg.asc metasploitframework-latest.pkg`. 

However, that would also create a dependency on gpg, unless there's a better way to do it.

**Comment by reitermarkus** [comment]
> or else automate the process to update the cask based on the latest URL and SHA256.

That's exactly why we prefer versioned URLs with an `appcast`. There's no official tool for this yet but some contributors are already using this to generate automatic update PRs.

**Comment by vitorgalvao** [comment]
Please revert this to how it was, updating only the `version` and `shasum`. The cask is built as intended.

**Comment by ran-dall** [comment]
@mojoTX As FTR, our ML system does a pretty good job of picking up the `metasploit` updates within 24hrs in the past. If we didn't have coverage on this cask, then I would say that you're solution could be considered; but if we have coverage, then as @vitorgalvao said...

> The cask is built as intended.

**Comment by mojoTX** [comment]
I will close the MR, but it seems to be a common problem where the cask falls behind the nightly releases.

**Pull request closed without merging**
