### PR TITLE
Delete opencore-configurator 2.7.1.0, fixes #85770

### PR DESCRIPTION
**Pull request by yurikoles**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

As said in in #85770 there is definetly some download protection, but it seems to be either selective or random. E.g. some past PRs test failed on one CI but succeeded on another.

I see this on my machine:
```
brew cask upgrade -v 
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 1 outdated package:
opencore-configurator 2.7.0.1 -> 2.7.1.0
==> Upgrading opencore-configurator
==> Downloading https://mackie100projects.altervista.org/apps/opencoreconf/download-new-build.php?version=last
Already downloaded: /Users/yurikoles/Library/Caches/Homebrew/downloads/ddf69e251974e47e9cc539b7df35ebacbff80effab193a3109c2bfdf469c307e--download-opencore-configurator
==> Verifying SHA-256 checksum for Cask 'opencore-configurator'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
==> Purging files for version 2.7.1.0 of Cask opencore-configurator
Error: Checksum for Cask 'opencore-configurator' does not match.
Expected: 33adeb8d5badff1ad4e276fc9696067d62c6ed0f3aad5d2010666930ce200531
  Actual: 9c0c67b0598d28750c247e9b1b507e44885766c0b3f409fff18f6ae4bdfc7858
    File: /Users/yurikoles/Library/Caches/Homebrew/downloads/ddf69e251974e47e9cc539b7df35ebacbff80effab193a3109c2bfdf469c307e--download-opencore-configurator
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/HEAD/doc/reporting_bugs/checksum_does_not_match_error.md
```

Where `download-opencore-configurator` is homepage subpath.

### CODE REVIEW

**Comment by ran-dall** [comment]
@yurikoles This is strange, but I can't reproduce on either the ML or my personal machine. I do think the `appcast` needs to be updated to `https://mackie100projects.altervista.org/download-opencore-configurator/` but I don't see anything else wrong with it.

**Comment by ran-dall** [comment]
ping @miccal @core-code

**Comment by miccal** [comment]
@ran-dall the `sha256` seems to randomly change for the same `version`. Since the `url` is un-vsersioned I would suggest either removing the `appcast` and changing this to:
```
version :latest
sha256 :no_check
```
or removing this cask.

**Comment by ran-dall** [comment]
@miccal Thanks for the suggestion, we might have to do that. What bothers me though is that we don't seem to have this problem with `clover-configurator` and (if I'm not mistaken) it has the same setup.

**Comment by miccal** [comment]
@ran-dall `clover-configurator` suffers the same issue:
```
-bash-5.0.18- /Users/miccal (29) [> brew cask fetch clover-configurator

==> Downloading external files for Cask clover-configurator
==> Downloading https://mackie100projects.altervista.org/apps/cloverconf/download-new-build.php?version=global
==> Downloading from https://mackie100projects.altervista.org/download-clover-configurator/
##=O#- #                                                                      
==> Verifying SHA-256 checksum for Cask 'clover-configurator'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'clover-configurator' does not match.
Expected: 75c6f622a7e04ab7ae9ef839397fe8b93478cb9aeee8e0e923eee1bb00f67fb4
  Actual: c1c97d761b9f352fcac815c3d5073b1228a8022e5985ba9208a9f65168ee362c
    File: /Users/miccal/Library/Caches/Homebrew/downloads/17928f17fb009f491134a5d6af86e1d0579ef8b50c21621e375a3874f34d2d67--download-clover-configurator
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/HEAD/doc/reporting_bugs/checksum_does_not_match_error.md
```

**Comment by core-code** [comment]
i can't confirm the problem with 'clover-configurator':

```
% brew cask fetch clover-configurator

==> Downloading external files for Cask clover-configurator
==> Downloading https://mackie100projects.altervista.org/apps/cloverconf/download-new-build.php?version=global
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'clover-configurator'.
==> Success! Downloaded to -> /Users/julian/Library/Caches/Homebrew/downloads/17928f17fb009f491134a5d6af86e1d0579ef8b50c21621e375a3874f34d2d67--CCG.zip
```

**Comment by ran-dall** [comment]
@core-code @vitorgalvao @miccal I think the best way to fix this is going `:latest`, which I know probably will cause some eye rolls but I think both of these should stay. Thoughts?

**Comment by miccal** [comment]
@ran-dall agreed -- the `sha256` changes based on location, fetch method (browser, curl, wget, etc.) and which way the wind is blowing.

**Comment by vitorgalvao** [comment]
> I think the best way to fix this is going `:latest`

Fine with me.

**Comment by core-code** [comment]
Submitted (https://github.com/Homebrew/homebrew-cask/pull/86188)

**Comment by ran-dall** [comment]
@core-code Can you also submit the one for `clover-configurator`? I won't be around for another hour or so.

**Comment by core-code** [comment]
> @core-code Can you also submit the one for `clover-configurator`? I won't be around for another hour or so.

@ran-dall sure thing. Submitted (https://github.com/Homebrew/homebrew-cask/pull/86189)

**Pull request closed without merging**
