### PR TITLE
updated clementine (1.3.1)

### PR DESCRIPTION
**Pull request by sanyer**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You’re using an old version of `cask-repair`.

**Comment by sanyer** [comment]
@vitorgalvao oops, just did today `brew update`

**Comment by vitorgalvao** [comment]
It’s not a big deal, but it is necessary to update.

The reason I know your version is old is that the PR template wasn’t submitted (which newer versions do).

**Comment by adidalal** [comment]
`brew reinstall cask-repair` does the trick

**Pull request merged**
