### PR TITLE
Remove Linn Kinsky

### PR DESCRIPTION
**Pull request by jmcvaughn**
After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].
- [ ] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

Linn Kinsky is now end-of-life (since some time in 2016): https://docs.linn.co.uk/wiki/index.php/Kinsky

Linn Kazoo, its replacement, is distributed exclusively through the Mac App Store: https://itunes.apple.com/gb/app/linn-kazoo/id848937349

### CODE REVIEW

**Comment by vitorgalvao** [comment]
@core-code This cask is unpopular for us

```
exitkinsky (added 1790 days ago)
30 days: n/a
90 days: 1 (#5407)
365 days: 17 (#4735)
```

but it wasn’t removed in the last purge because it’s included in the `casks-without-feed-and-more-than-10-users`. However, seeing as it’s been unmaintained for three years and there’s a replacement (that we can’t offer), it looks safe for removal.

**Comment by core-code** [comment]
@vitorgalvao thanks for the heads-up there. please go ahead and remove it.

• please feel free to switch to the 'casks-without-feed-and-more-than-30-users' list for this purpose - this should be more than good enough for us.
• btw, i've started to continually increase the actual number-of-users used to generate these files to adjust for popularity increases on our side (yeah ;) - the filenames will stay the same though
• if you want to delete anything on the list just go ahead - a short heads-up like in this case is enough - if i want to keep the cask i'll just fork it - thanks!

**Comment by vitorgalvao** [comment]
> please feel free to switch to the 'casks-without-feed-and-more-than-30-users' list for this purpose

Thank you. Will do.

> btw, i've started to continually increase the actual number-of-users used to generate these files to adjust for popularity increases on our side

If you wish, instead of hardcoding the number in the file make an `unpopular-casks-without-feed.txt` (or another name, no preference there) where you can adjust the number at will. I trust you to pick reasonable numbers.

**Comment by core-code** [comment]
thanks. i've thought about renaming but could not come up with anything sensible. lets just keep the filenames as they are for the time being - we can always revisit this later ;-)

**Pull request merged**
