### PR TITLE
Update evernote to v10

### PR DESCRIPTION
**Pull request by core-code**

### CODE REVIEW

**Comment by core-code** [comment]
things would be easier if 'brew cask style' worked on Big Sur

**Comment by core-code** [comment]
@miccal @vitorgalvao should we drop the old OS versions to simplify?

**Comment by vitorgalvao** [comment]
> should we drop the old OS versions to simplify?

Fine with me. Anything below High Sierra isn’t officially supported by Homebrew in general anyway.

**Comment by core-code** [comment]
well it works now so i don't really see a reason to remove something that could be useful to someone

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
