### PR TITLE
aldente: update livecheck

### PR DESCRIPTION
**Pull request by khipp**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

Related to https://github.com/Homebrew/homebrew-cask/issues/171006.

### CODE REVIEW

**Comment by krehel** [comment]
Please see #156395 for when these changes before were undone.  Are the versions being served from Github the same as the upstream Pro source?

**Comment by khipp** [comment]
@krehel The author in your linked PR only updated the `livecheck` to use the pro version. The versioned `url` was still for the free one, as indicated by the `sha256` not changing.

**Comment by khipp** [comment]
I just verified that the pro version can be used without entering a license key. Should we fix the original `url` or leave it as is for easier versioning?

**Comment by bevanjkay** [comment]
If it is possible we should probably download and install the "pro" version here, regardless of if it is versioned on not, it is probably the correct file to serve.

**Comment by khipp** [comment]
I compared the pro and GitHub versions, and the checksums match. The GitHub version can also unlock pro features by entering a license key.
It seems like the original PR's intended change was unnecessary, and we can keep the versioned `url` after all.

**Comment by krehel** [comment]
No need to apologize.  I think we have right goal here with serving the Pro version and versioned URL, especially if the "free" version is the same as Pro without a license key.

Happy to ✅ this.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
