### PR TITLE
removed mcedit.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
Can’t find a download link on the homepage (only Windows versions) and it uses a download url from a different host than the homepage. Unless someone can point to where the download url lives, we should remove this.

### CODE REVIEW

**Comment by Amorymeltzer** [comment]
There are two things happening here, as far as I can determine.  mcedit, as our cask currently points to, is actually now mcedit2 (at https://github.com/mcedit/mcedit2) and is indeed currently windows only.  It is apparently under active development (the version for download is named as a demo) and from the readme in the repo, it appears they *intend* to add support for OSX, but haven't gotten there yet.

mcedit2 is the next version of the now-no-longer-developed https://github.com/mcedit/mcedit mcedit/mcedit which has been picked up under a different name, https://github.com/Khroki/MCEdit-Unified.  [MCEdit-Unified](https://khroki.github.io/MCEdit-Unified/) appears to be both Mac compatible and under development.

So with all that in mind, I suppose this should be done away with, a replacement `mcedit-unified` added, and if `mcedit2` adds support that can be added at a later date.

**Comment by vitorgalvao** [comment]
Everything sounds good. I’ll merge this in, then. Would you care to add `mcedit-unified` or would you prefer I do it?

**Comment by Amorymeltzer** [comment]
Sorry, could you?  I'm mobile for a while.


~A

**Comment by vitorgalvao** [comment]
Sure thing.

**Pull request merged**
