### PR TITLE
Update v2rayx to 0.7.9

### PR DESCRIPTION
**Pull request by specter119**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by specter119** [comment]
I don't know why the check failed, I have tested the installation on my laptop, it works well.

**Comment by commitay** [comment]
@miccal The `uninstall script` doesn't exist until the `app` is run, the original `delete` is correct.

**Comment by commitay** [comment]
The original `uninstall` is correct, it just fails on travis.

**Comment by commitay** [comment]
```
brew cask uninstall v2rayx.rb 
==> Uninstalling Cask v2rayx
Password:

==> Running uninstall process for v2rayx; your password may be necessary
==> Removing launchctl service v2rayproject.v2rayx.v2ray-core
==> Signalling 'TERM' to application ID 'cenmrev.V2RayX'
==> Running uninstall script /Library/Application Support/V2RayX/v2rayx_sysconf
==> proxy set to off
==> Removing files:
/Library/Application Support/V2RayX
==> Removing App '/Applications/V2RayX.app'.
commitays-Mac:~ commitay$ 

```

**Comment by commitay** [comment]
Needs to be ` /Library/Application Support/V2RayX/v2rayx_sysconf`

**Comment by specter119** [comment]
@commitay I'm working on restore it to original. I update it through `cask-repair`, and I have not modified the uninstall part. I don't know why it changes.

**Comment by miccal** [comment]
It is fine:
```
>>> brew cask uninstall --verbose Casks/v2rayx.rb
==> Uninstalling Cask v2rayx
==> Running uninstall process for v2rayx; your password may be necessary
==> Removing launchctl service v2rayproject.v2rayx.v2ray-core
==> Signalling 'TERM' to application ID 'cenmrev.V2RayX'
==> Running uninstall script /Applications/V2RayX.app/Contents/Resources/v2rayx_sysconf
==> proxy set to off
==> Removing files:
/Library/Application Support/V2RayX
==> Removing App '/Applications/V2RayX.app'.
```

**Comment by miccal** [comment]
Thanks for the PR @specter119.

**Comment by specter119** [comment]
@miccal Thanks.

**Pull request merged**
