### PR TITLE
Minor style corrections for RuboCop

### PR DESCRIPTION
**Pull request by jawshooah**
Each commit corresponds to fixes for a different cop (rule). This takes care of a lot of the low-hanging fruit mentioned in #9921.

### CODE REVIEW

**Comment by fanquake** [comment]
Can you squash some of these together? It's a lot of commits just to fix mostly whitespace/formatting.

**Comment by jawshooah** [comment]
Sure thing, I'll squash the formatting changes together and leave the semantic and configuration changes separate.

**Comment by jawshooah** [comment]
@fanquake Done. Is this still too granular?

**Comment by fanquake** [comment]
@jawshooah Thanks.

**Pull request merged**
