### PR TITLE
Update osu from 2022.719.0 to 2022.723.0

### PR DESCRIPTION
**Pull request by JacksonChen666**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by p-linnane** [comment]
Dupliate of #128460

**Comment by JacksonChen666** [comment]
how did `brew bump` completely miss 1 other open PR?

**Comment by p-linnane** [comment]
This PR was opened 6 hours ago, while #128460 was merged 8 hours ago. So it wasn't open at the time.

**Comment by JacksonChen666** [comment]
makes sense, probably didn't do an update before bumping.

**Pull request closed without merging**
