### PR TITLE
Update bettertouchtool url

### PR DESCRIPTION
**Pull request by miccal**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
we've had *many* problems with this app here previously so i am not really happy to revert to the status quo here.

**Comment by core-code** [comment]
i can change the cronjob that generates the appcast to run more than once daily if that is desired though

**Comment by miccal** [comment]
I think we should try using the `url` from the `homepage` -- if it turns out this link points to non-stable releases, we can revert these changes.

**Comment by miccal** [comment]
@core-code perhaps you could change your cronjob to download from `https://folivora.ai/releases/BetterTouchTool.zip` and monitor the `version` that way?

**Comment by core-code** [comment]
> @core-code perhaps you could change your cronjob to download from

this is what is already done. here is the source: https://textbin.net/LsFiK2qiTu

> I think we should try using the url from the homepage -- if it turns out this link points to non-stable releases

well, any release linked from the homepage is by definition 'stable'.


i want to avoid a situation like we had before. we had 'https://folivora.ai/releases/' as appcast and people would submit *any* version listed there, which were often newer than the one in the homepage download *and* newer than in the default update check. i.e. these were beta releases listed only in their "alpha update check". 


switching to the unversioned download will have one possible downside. in case the download from the homepage lags the download from the update check we won't have the flexibility to just submit the newer version from the update check without changing back to the versioned download. i am not sure what we gain on the other hand. but i am fine with the change since the downside is pretty hyptothetical in this particular case.

however i don't think we should change the appcast here. their release notes are notoriously outdated to the point of uselessness. as mentioned i'll increase frequency of the cronjob instead so that necessary updates can go through sooner.

**Comment by core-code** [comment]
> as mentioned i'll increase frequency of the cronjob instead so that necessary updates can go through sooner.

i've had a look and this already runs every two hours

**Comment by miccal** [comment]
I have restored the original `appcast`.

**Comment by core-code** [comment]
thanks

**Pull request merged**
