### PR TITLE
Update duet from 2.4.2.2 to 2.4.2.4

### PR DESCRIPTION
**Pull request by nicerloop**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by miccal — DISMISSED** [review]

**Review by bevanjkay — APPROVED** [review]

**Comment by bevanjkay** [comment]
Looks like this is most likely still propagating a CDN network, or staggered release. The tag will retry CI every few hours and it should pass soon.

**Comment by bevanjkay** [comment]
@SMillerDev This PR was merged by the automated workflow even though CI had failing checks. Could it be because we don't have required checks turned on for merging? Or perhaps the retry workflow had started a new run and therefore was showing as green at the time because "generate-matrix" was yet to start.

**Comment by SMillerDev** [comment]
I think that might be the case indeed. Calling in @Homebrew/ops  with the hopes they can verify  that though.

**Comment by Bo98** [comment]
> Or perhaps the retry workflow had started a new run and therefore was showing as green at the time because "generate-matrix" was yet to start.

This is what I would've thought. Automerge is done by searching for `status:success`. We don't have this issue in homebrew-core, since merging can't happen without the bottle artefacts.

I'm not sure how it happened in this particular case though since the latest attempt looks like it completed half an hour before merge.

**Pull request closed without merging**
