### PR TITLE
Update nozbe from 3.13.0 to 3.19.0

### PR DESCRIPTION
**Pull request by mlewak-equinix**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by mlewak** [comment]
please instruct how to headway with passing checks, version 3.19.0 works fine at my end (unfortunately not the newer 3.20.1)

**Comment by miccal** [comment]
Possible `livecheck` `url`:
```
|-> curl -sLI https://nozbe.com/mac
HTTP/2 301 
cache-control: public, max-age=0, must-revalidate
content-length: 67
content-type: text/plain; charset=utf-8
date: Fri, 20 Aug 2021 11:28:23 GMT
x-nf-request-id: 01FDHN3Q2N1EP9GT1DPPG38X22
age: 11
location: https://files2.nozbe.com/3201/release/Nozbe.app.zip
x-frame-options: DENY
server: Netlify

HTTP/2 200 
content-type: application/zip
content-length: 10580576
date: Fri, 20 Aug 2021 11:28:36 GMT
last-modified: Thu, 19 Aug 2021 10:00:39 GMT
x-amz-version-id: YYk4yhEE_ZLkm1Gkgb2KwCNTYqZ0ETSz
etag: "3633a6325c09d64636cc9ee12a01d524"
server: AmazonS3
x-cache: Miss from cloudfront
via: 1.1 8d56f074f7efb65829086cd5907d3786.cloudfront.net (CloudFront)
x-amz-cf-pop: PER50-C1
x-amz-cf-id: bn18rql4pnidqm3Bx-Kg6CHa1Mfg0eCRsG4MiRnmeD3wwfMpC1FZjw==
```

**Comment by miccal** [comment]
> please instruct how to headway with passing checks, version 3.19.0 works fine at my end (unfortunately not the newer 3.20.1)

What is the issue with version 3.20.1?

**Comment by mlewak** [comment]
>What is the issue with version 
> 3.20.1?

with nozbe version 3.20.1 I was not able to finish the audit on my workstation for some reason, but it passed with 3.19.0

**Comment by mlewak** [comment]
closing this pull request, will come back with a livecheck update

**Pull request closed without merging**
