### PR TITLE
j 9.5.2

### PR DESCRIPTION
**Pull request by secwang**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Is there any confirmation available from upstream as to why the checksum has changed? It can indicate that the binary has been compromised.

**Comment by secwang** [comment]
> Is there any confirmation available from upstream as to why the checksum has changed? It can indicate that the binary has been compromised.
They update binary file in this position.
https://www.jsoftware.com/download/j9.5/install/
I think they made a small version upgrade, but it's still 9.5.
New checksum can be found at https://www.jsoftware.com/download/j9.5/install/sha256sums

**Comment by miccal** [comment]
@samford the latest version here is actually `9.5.2` and the file is located at https://www.jsoftware.com/download/j9.5/install/j9.5.2_mac64.zip.

The not-beta release 9.5 is shown on the current `livecheck` `url` at https://code.jsoftware.com/wiki/System/Installation.

This page https://www.jsoftware.com/download/j9.5/install/ states `The current version is J9.5.2.`, while this page https://www.jsoftware.com/download/j9.6/install/ states `The current version is J9.6.0-beta5.`.

Can you think of a way such that `livecheck` can check `https://www.jsoftware.com/download/j#{version.major_minor}/install/`
the current non-beta version and then produce `https://www.jsoftware.com/download/j#{version.major_minor}/install/j#{version}_mac64.zip`?

I have not had any luck so far.

Thanks!

**Comment by samford** [comment]
> Can you think of a way such that `livecheck` can check `https://www.jsoftware.com/download/j#{version.major_minor}/install/` for the current non-beta version and then produce `https://www.jsoftware.com/download/j#{version.major_minor}/install/j#{version}_mac64.zip`?

Looking at the available sources (thanks for the links), this appears to be one of those situations where we have to check two pages. In this case, we have to fetch the release version from the [Installation page](https://code.jsoftware.com/wiki/System/Installation) (e.g., 9.5) and then use that to generate the versioned download page URL (https://www.jsoftware.com/download/j9.5/install/), as you suggested. [To be clear, we can't check https://www.jsoftware.com/download to identify release version directories because there's no way to distinguish between stable versions (e.g., 9.5) and unstable versions (e.g., 9.6), since they both use a stable version format.]

I'll push a commit in a moment to rework the `livecheck` block and update this to 9.5.2.

**Comment by samford** [comment]
@secwang When creating PRs in the future, please create a new branch on your fork (e.g., `j-update-checksum`) instead of making the commit(s) on the `master` branch. That makes it a little easier for maintainers to check out your PR branch and make commits to it (if necessary).

**Comment by secwang** [comment]
> @secwang When creating PRs in the future, please create a new branch on your fork (e.g., `j-update-checksum`) instead of making the commit(s) on the `master` branch. That makes it a little easier for maintainers to check out your PR branch and make commits to it (if necessary).

Okay

**Comment by miccal** [comment]
Thank you very much @samford.

**Review by miccal — APPROVED** [review]

**Pull request merged**
