### PR TITLE
add zap add conflicts to appcode

### PR DESCRIPTION
**Pull request by yurikoles**

### CODE REVIEW

**Comment by fanquake** [comment]
Same comment as https://github.com/caskroom/homebrew-versions/pull/1269

The EAP is only available bundled. You are adding a cask that is identical, except for adding a Java caveat?

**Comment by yurikoles** [comment]
@fanquake I don't add a new cask, I do improve existing one.

**Comment by fanquake** [comment]
Sorry, I meant that you don't need to add this line
```
'appcode-eap-bundled-jdk',
```

That cask, which you've preposed to add to the versions repo, doesn't exist. The EAP is bundled by default, and there is no alternative, so it's just appcode-eap

**Comment by yurikoles** [comment]
The file you have mentioned has nothing to do with this PR.

**Comment by yurikoles** [comment]
Consider situation when someone has appcode-eap-bundled-jdk already installed. As I know cask does not report if some installed cask was removed from repository.

**Comment by vitorgalvao** [comment]
@fanquake What’s the correct course of action, here, as you see it?

**Comment by fanquake** [comment]
I think we should drop appcode-eap-bundled-jdk & merge. Besides the fact that anyone who has already installed/been using an EAP release is going to be aware of conflicts, I don't think we want to start adding conflicts stanzas for every cask that may have existed at some point.

**Comment by vitorgalvao** [comment]
Sounds good.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 825461cb8b2d5588632516cbc4c0d72a5fca8e04. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
