### PR TITLE
add Garmin VIRB Edit

### PR DESCRIPTION
**Pull request by jconley**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
It’s missing `uninstall`. There are [scripts](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md) geared for that.

**Comment by jconley** [comment]
@vitorgalvao updated...

**Comment by vitorgalvao** [comment]
To make Travis pass and fix the build, do `brew cask style --fix {{your_cask}}`.

**Comment by jconley** [comment]
@vitorgalvao resolved

**Pull request merged**
