### PR TITLE
Update shutter-encoder from 14.4 to 14.6

### PR DESCRIPTION
**Pull request by cesarcoatl**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by thecesrom** [comment]
```bash
Error: Some applications are still installed, add them to uninstall delete:
/Applications/Shutter Encoder.app
```

That's why I added the `uninstall` stanza.

**Review by cesarcoatl — COMMENTED** [review]
Could we use these changes which already passed all CI tests?

**Comment by miccal** [comment]
@reitermarkus and @vitorgalvao this Cask is failing with the following error:
```
Run brew uninstall --cask './Casks/shutter-encoder.rb'
==> Uninstalling Cask shutter-encoder
==> Backing App 'Shutter Encoder.app' up to '/usr/local/Caskroom/shutter-encoder/14.6/Shutter Encoder.app'.
==> Removing App '/Applications/Shutter Encoder.app'.
Error: Directory not empty @ dir_s_rmdir - /Applications/Shutter Encoder.app
Error: Process completed with exit code 1.
```
Adding:
```
uninstall delete: "/Applications/Shutter Encoder.app"
```
makes the CI pass, however.

Thoughts?

**Comment by thecesrom** [comment]
I have installed the app using the ZIP file and there's nothing to `zap`, so `uninstall` seems to be the only way to uninstall this Cask.

Is it not allowed?

**Comment by miccal** [comment]
> Is it not allowed?

It should not be necessary, that is why I have asked the other maintainers for their advice.

**Comment by thecesrom** [comment]
Thanks, @miccal.

**Comment by vitorgalvao** [comment]
Perhaps a permissions issue that `uninstall` isn’t facing the but the regular method is? Try a [`set_ownership`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/flight.md#flight-mini-dsl).

**Comment by thecesrom** [comment]
> Perhaps a permissions issue that `uninstall` isn’t facing the but the regular method is? Try a [`set_ownership`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/flight.md#flight-mini-dsl).

Something like [`ivpn.rb`](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/ivpn.rb)?

```ruby
  uninstall_preflight do
    set_ownership "#{appdir}/Shutter Encoder.app"
  end

  uninstall delete: "#{appdir}/Shutter Encoder.app"
```

**Comment by vitorgalvao** [comment]
> Something like [`ivpn.rb`](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/ivpn.rb)?

Correct.

> Or is there no need for `uninstall delete`?

Also correct (no need for it—or so we’re testing).

**Comment by thecesrom** [comment]
Negative. Same issue.

```bash
==> Uninstalling Cask shutter-encoder
==> Changing ownership of paths required by shutter-encoder; your password may be necessary
==> Backing App 'Shutter Encoder.app' up to '/usr/local/Caskroom/shutter-encoder/14.6/Shutter Encoder.app'.
==> Removing App '/Applications/Shutter Encoder.app'.
Error: Directory not empty @ dir_s_rmdir - /Applications/Shutter Encoder.app
Error: Process completed with exit code 1.
```

**Comment by thecesrom** [comment]
Are there any other suggestions?

Because it seems like the only way to have this PR approved is to include `uninstall delete: "#{appdir}/Shutter Encoder.app"`.

**Comment by vitorgalvao** [comment]
> Are there any other suggestions?

[`set_permissions`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/flight.md#flight-mini-dsl), which was what I meant to type in the previous reply.

**Comment by thecesrom** [comment]
Which was added on

> [`set_permissions`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/flight.md#flight-mini-dsl), which was what I meant to type in the previous reply.

Which was added to my latest commit:

```ruby
  uninstall_preflight do
    set_ownership "#{appdir}/Shutter Encoder.app"
  end
```

**Comment by vitorgalvao** [comment]
> Which was added to my latest commit

That was `set_ownership`, not `set_permissions`.

**Comment by thecesrom** [comment]
> That was `set_ownership`, not `set_permissions`.

My apologies. I read that as `set_ownership`.

**Comment by vitorgalvao** [comment]
> My apologies. I read that as `set_ownership`.

Understandably! Glad to see that did the trick.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
