### PR TITLE
Update BBEdit to 13.0

### PR DESCRIPTION
**Pull request by chrisfinazzo**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by chrisfinazzo** [comment]
Release notes say this will only run on Mojave and later, thinking we should update the Cask's conditional as well.

Thoughts?

**Comment by brucehs** [comment]
@chrisfinazzo I submitted a pull request (#70102) to update the conditional.

I also noticed that Bare Bones breaks compatibility within major versions of macOS (BBEdit 13.0 won't run on versions of Mojave prior to 10.14.2) and opened an issue (#70103) about it.

**Comment by chrisfinazzo** [comment]
@brucehs, Looks good, just what I was thinking.

When Mojave is released, it _might_ make sense to remove references to 10.11 and 10.12 if Apple is no longer providing security updates for these releases.

However, if @MikeMcQuaid and the Core team have an official policy re compatibility, I'll obviously defer to them on this one.

**Comment by MikeMcQuaid** [comment]
We support the most recent stable and previous two macOS version.

**Comment by MikeMcQuaid** [comment]
@chrisfinazzo Apologies if my comment above caused confusion here.

**Pull request merged**
