### PR TITLE
Update hype to 3.6.3

### PR DESCRIPTION
**Pull request by gaastonsr**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] `sha256` changed but `version` stayed the same ([what is this?](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256)).
      I’m providing public confirmation below.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Not sure why you decided to make this change, but this is exactly as intended. Your change would make the cask less resilient to updates.

Thank you anyway, but we’ll refuse it.

**Comment by gaastonsr** [comment]
I just realized this is wrong. Sorry for submitting.

I'm trying to debug the following error

```
$ brew cask install hype
==> Satisfying dependencies
==> Downloading https://tumult.com/hype/download/Hype.zip
Already downloaded: /Users/gsanchez/Library/Caches/Homebrew/Cask/hype--3.6.3.zip
==> Verifying checksum for Cask hype
==> Installing Cask hype
Error: It seems the App source '/usr/local/Caskroom/hype/3.6.3/Hype 3.app' is not there.
Error: Install incomplete.
```

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#source-is-not-there-error

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/38199

**Comment by gaastonsr** [comment]
Amazed at the speed of response here 👏🏽👏🏽👏🏽

Thanks, @commitay for fixing!

**Pull request closed without merging**
