### PR TITLE
font-monaspace: remove non-variable versions

### PR DESCRIPTION
**Pull request by adamrothman**
After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

It shouldn't be necessary to install both static and variable versions of the font.

### CODE REVIEW

**Review by bevanjkay — APPROVED** [review]

**Comment by georgepstaylor** [comment]
Hi, I managed to track down this PR after experiencing issues installing the Monaspace font using the brew instructions provided at https://github.com/githubnext/monaspace

Unfortunately, it's my experience that since the removal of the explicit installation of the static varieties only the variable fonts are installed. 

After running `brew install --cask font-monaspace` I am only able to use the `Monaspace ____ Var` fonts. Is this the expected behaviour, or should I still be able to use the static fonts too?

**Comment by bevanjkay** [comment]
@georgepstaylor Thanks for commenting. Yes, we should probably revert the change here.

**Comment by adamrothman** [comment]
Is there a standard or best practice when it comes to font casks? For example, `font-source-code-pro` only installs the variable versions of that font, while static versions of the font are available from https://github.com/adobe-fonts/source-code-pro.

@georgepstaylor only being able to use the variable version was the intended outcome of this PR – do you have use cases that require the static versions?

**Comment by adamrothman** [comment]
Interesting! I haven't tried mixing fonts at all but anecdotally I can report that VSCode appears to handle variable fonts just fine – I'm using one right now.

**Comment by bevanjkay** [comment]
@adamrothman there's not really a standard practice at the moment, other than including them when they're available. 

Some fonts in the past have not worked well when both static and variable versions were installed together. 

But we generally include both as some users prefer using static and some prefer variable.

**Comment by adamrothman** [comment]
Revert is here: https://github.com/Homebrew/homebrew-cask/pull/189066

**Comment by singularitti** [comment]
Hey guys @adamrothman @georgepstaylor, I believe this problem will be fixed by PR #224797. Please have a look!

**Pull request merged**
