### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by bukzor**
use editable repo url as remote

### CODE REVIEW

**Comment by ndr-qef** [comment]
Using SSH provides a better workflow, but I worry that occasional GitHub users may not have keys associated to their account, leading to confusing errors at the CLI. Experienced users presumably recognize the difference and diverge from the guide accordingly.

**Comment by vitorgalvao** [comment]
I have no opinion on the matter, @ndr-qef, so I trust your decision to either merge or close.

**Comment by bukzor** [comment]
This is what the current directions yields if I try to push to said remote:

```
$ git push bukzor HEAD
Username for 'https://github.com': bukzor
Password for 'https://bukzor@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/bukzor/homebrew-cask/'
```

There's no password that will cause this to succeed, which is a much more confusing failure mode.
This is why I updated the directions. The scenario you're worried about (no ssh keys enabled/active) gives a more familiar and more googlable failure mode.

```
$ ssh-add -D
All identities removed.

$ git remote show -n buck
* remote buck
  Push  URL: git@github.com:bukzor/homebrew-cask.git

$ git push buck HEAD
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by ndr-qef** [comment]
GitHub should grant write access when you login with your account credentials ([ref.](https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-recommended)). Perhaps there is a problem on your end?

**Comment by bukzor** [comment]
Enabling 2FA means that a simple password doesn't work:
https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-recommended

According to that blog though, you're doing it right. https is the recommended clone url, apparently.

**Comment by vitorgalvao** [comment]
Should we close this, then, since we’re doing it the recommend way?

**Comment by ndr-qef** [comment]
Yes. The segment being discussed is written with a particular concern for beginners (“fork with the ‘Fork’ button”), and I feel comfortable assuming that contributors with a working GitHub setup will ignore it.

@bukzor, while we should leave the current procedure intact, I feel that there is room for expanding it to cover SSH urls as you recommed. We will follow up if someone else raises the issue here or over IRC.

**Pull request closed without merging**
