### PR TITLE
Update unity to 5.6.0f3,497a0f351392

### PR DESCRIPTION
**Pull request by xuleman**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by numbermaniac** [comment]
(to whichever maintainer looks at this): is there a reason why the `uninstall` stanza doesn't use `#{version.major}` instead of just `5`?

**Comment by victorpopkov** [comment]
> (to whichever maintainer looks at this): is there a reason why the `uninstall` stanza doesn't use `#{version.major}` instead of `5`?

Nope, there is no reason.

**Comment by mubeeniqbal** [comment]
The build is failing on Travis although the only change is the version and the checksum which I believe should be the case. Is there a specific reason as to why is this happening on Travis?

**Comment by victorpopkov** [comment]
> The build is failing on Travis although the only change is the version and the checksum which I believe should be the case. Is there a specific reason as to why is this happening on Travis?

Nope, there is no specific reason here. At the moment, Travis CI results in fail even when there is nothing wrong with the changes in approximately 30% of cases. Build restart usually helps.

Why exactly it happens? I, personally, don't know. It needs some digging to find out the core reason behind that.

**Comment by victorpopkov** [comment]
Closed in favour of https://github.com/caskroom/homebrew-cask/pull/32052 since it was made 1 hour earlier.

Thank you for all your contribution. We really appreciate them!

**Pull request closed without merging**
