### PR TITLE
{Verification in-Progress} Update wizard101 to 1.11

### PR DESCRIPTION
**Pull request by gobinathm**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] `sha256` was updated, but `version` remained the same.
      [Post a link to a public confirmation by the developer.][version-checksum]: 

Verification Requested from developer: https://twitter.com/gobinathm/status/861663757084356610

### CODE REVIEW

**Comment by vitorgalvao** [comment]
These now have to be confirmed. Please see https://github.com/caskroom/homebrew-cask/pull/33538.

**Comment by gobinathm** [comment]
Ref: https://twitter.com/gobinathm/status/861663757084356610

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/Wizard101">@Wizard101</a> sha256 seems to be updated for Wizard101.dmg. can you confirm if this is legit ?<br><br>cc/ <a href="https://twitter.com/homebrewcask">@homebrewcask</a></p>&mdash; gobinathm (@gobinathm) <a href="https://twitter.com/gobinathm/status/861663757084356610">May 8, 2017</a></blockquote>

**Comment by giannitm** [comment]
Verified the app bundle's code signature:

```
$ codesign -dv --verbose=4 /Volumes/Wizard101/Wizard101.app 
Executable=/Volumes/Wizard101/Wizard101.app/Contents/MacOS/Wizard101
Identifier=com.kingsisle.wizard101
Format=app bundle with Mach-O thin (i386)
CodeDirectory v=20200 size=1087 flags=0x0(none) hashes=47+3 location=embedded
Hash type=sha1 size=20
CandidateCDHash sha1=c01f5ee51e1475b9c8646e8da16b46de7cc5b5dd
Hash choices=sha1
Page size=4096
CDHash=c01f5ee51e1475b9c8646e8da16b46de7cc5b5dd
Signature size=8543
Authority=Developer ID Application: KingsIsle Entertainment, Inc.
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=12 Apr 2017, 01:12:31
Info.plist entries=29
TeamIdentifier=2C6PJVJ4XC
Sealed Resources version=2 rules=12 files=2314
Internal requirements count=1 size=184
```

**Comment by commitay** [comment]
> Verified the app bundle's code signature:

Don't know if this helps or if it can be used as verification but [virustotal](https://www.virustotal.com/en/file/006a832ef8a3741cfb4394bb5ea5d08a60ba381bced7fb1615f51334ffab7c8b/analysis/) will also verify codesigning.

**Comment by giannitm** [comment]
@commitay Didn't realise VirusTotal could do all that. I'll use that in future!

**Comment by vitorgalvao** [comment]
@commitay @giannitm I like that. Anyone up to adding the virustotal method to [the documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256)? With that method, if the user shares the link we can at once verify the `sha256` and the identifier.

**Comment by vitorgalvao** [comment]
On second thought, scratch that. See in virustotal [handbrake’s infected dmg](https://virustotal.com/en/file/013623e5e50449bbdf6943549d8224a122aa6c42bd3300a1bd2b743b01ae6793/analysis/) vs [the legitimate one](https://www.virustotal.com/en/file/3cd2e6228da211349574dcd44a0f67a3c76e5bd54ba8ad61070c21b852ef89e2/analysis/1493488076/).

How do you even identify the infected one there as being infected, from the File Details? Because I’m not seeing it. We can’t rely on the Analysis tab since at the time of the infection this showed the infected file as clean.

**Comment by commitay** [comment]
`handbrake` doesn't seem to be codesigned at all, but this PR and https://github.com/caskroom/homebrew-cask/pull/33826 are codesigned.

Not suggesting virustotal as a way of proving it to be clear of infection, as it can take 48 hours (or longer) for a positive to appear. 

Virustotal also caps file size and has other limits, only making it useful in certain circumstances. 

Just thought it might be useful as a way of verifying codesigning (if supported.)

**Comment by vitorgalvao** [comment]
@commitay You are correct. I had the right idea initially, and then on closer look got the wrong one. I take back my take back.

I’m not suggesting virustotal’s `Analysis` as the way to prove clear of infection; I’m suggesting its `File Detail` to verify the signature. It’s what prompted me to [make this comment](https://github.com/caskroom/homebrew-cask/issues/16339#issuecomment-301330269).

If we keep an accurate list of bundle IDs why the casks, when we need to verify these cases, a user needs only verify the bundle ID from the cask matches the one from the update. If they do so and link us to the virus total page, we can verify it as accurate (by comparing virustotal’s sha256 with the one in the updated cask).

**Comment by commitay** [comment]
Just an idle thought for cases where we need the developer to confirm an `sha` update, is it better to confirm that a specific `sha256` is 🆗 rather than just confirming that it has been updated in place?

**Comment by vitorgalvao** [comment]
It’s better to confirm the `sha256`, but no harm in just confirming it changed.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/34374#issuecomment-302897674

**Pull request merged**
