### PR TITLE
Upgrade G Desktop Suite to v0.3.1

### PR DESCRIPTION
**Pull request by alexkim205**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ran-dall** [comment]
@alexkim205 This is supposed to be a future update, right? Cause only 0.3.0 is availible in your repo.

**Comment by alexkim205** [comment]
Yup, I made this pull request a bit prematurely, but this will be for a future release being released today.

**Comment by ran-dall** [comment]
@alexkim205 Ok, I could be wrong but I think we'd ("we" being HBC as a whole) prefer if you made the update on HBC after you release the target version.

**Comment by alexkim205** [comment]
@ran-dall Sorry for the inconvenience! I can close this PR now and reopen a new one once the release is out.

**Comment by ran-dall** [comment]
@alexkim205 NP, thank you for your understanding. ☺️

**Pull request closed without merging**
