### PR TITLE
added saltstack last version which compiles and runs on OSX Yosemite

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, @julienlavergne, but wrong project. What you want is [homebrew](https://github.com/Homebrew/homebrew).

**Comment by julienlavergne** [comment]
It’s done

-- 
Julien Lavergne
Sent with Airmail

On April 13, 2015 at 9:08:40 PM, Vítor Galvão (notifications@github.com) wrote:

Thank you, @julienlavergne, but wrong project. What you want is homebrew.

**Comment by vitorgalvao** [comment]
We’re actually different projects with different maintainers, so no need to report back here. You homebrew submission will be handled by a different team.

**Comment by julienlavergne** [comment]
That’s cool. Thank you.

-- 
Julien Lavergne
Sent with Airmail

On April 13, 2015 at 9:29:45 PM, Vítor Galvão (notifications@github.com) wrote:

We’re actually different projects with different maintainers, so no need to report back here. You homebrew submission will be handled by a different team.

**Pull request closed without merging**
