### PR TITLE
kicad 6.0.0-0

### PR DESCRIPTION
**Pull request by pthariensflame**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by miccal** [comment]
@pthariensflame can you please confirm that the changes I have made here work as intended, thanks.

**Comment by pthariensflame** [comment]
@miccal It seems to work beautifully now!  :D

**Comment by tkornack** [comment]
This seems to require sudo because of the installation of demos. Would you be open to not installing the demos? Is there a way to make it an option?

**Comment by pthariensflame** [comment]
I’m not sure!  I’d be open to that but don’t think it’s my decision to make. @miccal?

**Comment by miccal** [comment]
@tkornack and @pthariensflame would either of you know what exactly upstream recommends a user does/puts the `demos` folder?

**Comment by pthariensflame** [comment]
I don't know that, sadly; I haven't ever done anything with them.

**Comment by tkornack** [comment]
They are just a pile of example projects. Totally unnecessary for normal use. Maybe useful, though, for training.

**Pull request merged**
