### PR TITLE
Update soundtoys 5.2.4.13665

### PR DESCRIPTION
**Pull request by yutarody**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by yutarody** [comment]
I do not know the cause of fail ... The local test is successful

**Comment by vitorgalvao** [comment]
It’s failing because you’re changing a bunch of useful broad stuff to be specific and not catch everything.

**Comment by vitorgalvao** [comment]
It’s failing because you’re changing a bunch of useful broad stuff to be specific and not catch everything. Don’t replace the `*`. Also, keep the comma logic, `split` is harder to understand.

Either way, this now seems to be a walled build (they ask for an email and host on a different domain) so we’ll have to remove it.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/49399

**Pull request closed without merging**
