### PR TITLE
updated framer-studio (latest)

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Comment by adidalal** [comment]
There should be an appcast - I'll take a look when I get a chance.

**Comment by vitorgalvao** [comment]
Trouble with the previous `appcast` is it’s no longer being updated (stopped at `48`). `find_sparkle_appcast` doesn’t find one here.

**Comment by adidalal** [comment]
Use `https://updates.devmate.com/com.motif.framer.xml`

**Comment by vitorgalvao** [comment]
Thank you. Is that a common pattern for `devmate`-hosted apps?

**Comment by adidalal** [comment]
Not sure, just sniffed it with Charles.

**Comment by adidalal** [comment]
Nope, not a common pattern - depends entirely on how much the dev wants to use devmate. It's a full service app distribution service, but people still use sparkle, hockeyapp, etc..

**Pull request closed without merging**
