### PR TITLE
Update cycling74-max to 7.3.4_170530 (new build silently released at old URL)

### PR DESCRIPTION
**Pull request by LouisStAmour**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by LouisStAmour** [comment]
The DMG window after downloading and validation now says `Max7_170608_de5a74a` but the version in the URL remains `7.3.4_170530` and there's no mention on the website, but this isn't the first time they've done this. :)

**Comment by LouisStAmour** [comment]
The failing check above was the "only SHA256 changed" check. I wasn't sure if I should modify the URL to use the old version number, or just leave it alone. So I left it alone. Technically the version changed from build `170530` to `170608` but the URL did not.

**Comment by LouisStAmour** [comment]
Found official confirmation: https://cycling74.com/forums/max-7·3·4-released#reply-5939dba350213013aac58152

**Comment by miccal** [comment]
Thank you for your contribution.

**Pull request merged**
