### PR TITLE
Add Tether.app version 1.2.0

### PR DESCRIPTION
**Pull request by vinkla**
Tether will lock your Mac when you're not there and spring it back to life whenever you return. It's that simple! http://hellotether.com/

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/master/Casks/acorn.rb).

**Comment by vinkla** [comment]
Ahh okay. I thought since the version number is in the application name it should be checked. I'll fix I asap.

**Comment by vitorgalvao** [comment]
Ah, right, that is a good point.

**Comment by vinkla** [comment]
Thanks.

**Pull request merged**
