### PR TITLE
FileBot 4.8.2 (r5724)

### PR DESCRIPTION
**Pull request by rednoah**
After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[closed issues]: https://github.com/Homebrew/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
The appcast has `4.8` revision `5280`?

**Comment by rednoah** [comment]
`update.xml` won't be updated until there's a final stable release.

**Comment by commitay** [comment]
It would be helpful for us if the file wasn't updated in-place, e.g. by including the build number in the file name `FileBot_4.8.2_5724.app.tar.xz`

**Comment by rednoah** [comment]
Since each release is GPG signed anyway, would it make sense to remove `sha256` and replace it with something like `:LATEST`?

**Comment by commitay** [comment]
GPG verification isn't implemented yet (their is a PR open for it) and it will only work if `gnupg` is installed.

**Comment by rednoah** [comment]
I see. I'll make sure to exclude the `app` package from weekly builds. The `sha256` will still change one more time in the future for the final release though.

**Pull request merged**
