### PR TITLE
Update horos from 3.3.6 to 4.0.0

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by hamiltont** [comment]
@vitorgalvao FYI, you advised against using 4.0.0 a few days ago, because the 4.X line is still a release candidate line not a stable line. See https://github.com/Homebrew/homebrew-cask/pull/78916#issuecomment-601357920 

In #78936, we rolled back from 4.0.0 to the 3.x line because of this

**Comment by vitorgalvao** [comment]
Reverted. Thank you @hamiltont.

@ran-dall Could you tweak the ML on this one? The cask is now using github releases, so it should be able to detect pre-releases.

**Comment by hamiltont** [comment]
Sure thing. I think this one is tricky because 4.0.0 is not marked RC1. seems like upstream forgot to add that to the version number. I only caught it b/c I was doing the upgrade to RC3

**Comment by vitorgalvao** [comment]
> I think this one is tricky because 4.0.0 is not marked RC1

As long as it’s marked as a pre-release, it’s detectable:
image

**Comment by ran-dall** [comment]
@vitorgalvao I'm looking into it. It's happened a couple of times in the last few days.

**Comment by ran-dall** [comment]
@vitorgalvao I made some adjustmusts last night. Pretty sure it should be better now.

**Comment by vitorgalvao** [comment]
> @vitorgalvao I made some adjustmusts last night. Pretty sure it should be better now.

Thank you for the fast turnaround (and the submissions!).

**Pull request merged**
