### PR TITLE
Update 1password to 6.6.1

### PR DESCRIPTION
**Pull request by berndkrannich**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by jprokos** [comment]
educate me. when trying to contribute a fix for this issue I followed directions to install the cask repair script but ran into an error using it. I tried to track down the error but had no luck.

`iMac132:/ admin$ cask-repair 1password
Updating taps… Already up-to-date.
`origin` is pointing to an incorrect remote (https://github.com/Caskroom/homebrew-cask). Its beginning must match (https://|git@)github.com[/:]caskroom/.`

**Comment by berndkrannich** [comment]
@jprokos: I'm guessing that

```bash
cd $(brew --repository)/Library/Taps/caskroom/homebrew-cask
git remote -v
```

will return
```bash
origin https://github.com/Caskroom/homebrew-cask ...
```

for you whereas according to https://github.com/vitorgalvao/tiny-scripts/blob/0db5758c328c8b1f07146e2bb5ad3d77a6c28fea/cask-repair#L7 the Github org should read ```caskroom``` with a lower-case ```c``` (which it does for me).

Not sure how you came into this situation, though. You might want to try and see if https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md repairs this (run at your own risk) or open an issue at https://github.com/vitorgalvao/tiny-scripts/issues.

**Comment by jprokos** [comment]
@berndkrannich: Thanks. I didn't see that. I have no idea why but this is the result. Is there a git  configuration file that can be edited?

`$ git remote -v`
`origin	https://github.com/Caskroom/homebrew-cask (fetch)`
`origin	https://github.com/Caskroom/homebrew-cask (push)`

**Comment by berndkrannich** [comment]
Closing this one in favor of the earlier #30339

**Pull request closed without merging**
