### PR TITLE
Add Octave GUI

### PR DESCRIPTION
**Pull request by abcsds**
Add Octave GUI 4.0.3

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] `sha256` changed but `version` stayed the same ([what is this?][version-checksum]).  
      I’m providing public confirmation below.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by abcsds** [comment]
Thanks @commitay I hadn't understood the appcast.

**Comment by commitay** [comment]
Please complete all the steps in the PR template.

**Review by commitay — APPROVED** [review]

**Comment by miccal** [comment]
Does this conflict with the Homebrew formula for [Ocatve](https://github.com/Homebrew/homebrew-core/blob/master/Formula/octave.rb)?

**Comment by abcsds** [comment]
Hi, checklist ready. This is not an update to a cask, so sha hasn't changed.

**Comment by abcsds** [comment]
@miccal I installed it and have no problem on running both the app, and the brew formula.

**Comment by vitorgalvao** [comment]
The original has an `--without-qt` flag. Doesn’t that mean it gets built with a GUI by default? What does this cask offer over the formula?

**Comment by commitay** [comment]
> The original has an `--without-qt` flag. Doesn’t that mean it gets built with a GUI by default?

It looks like this option was removed when `octave` migrated from `science` to `core`.

https://github.com/Homebrew/homebrew-core/pull/15909, https://github.com/Homebrew/homebrew-core/issues/15986

**Comment by vitorgalvao** [comment]
`--without-qt` is still there (`brew cat octave`). But even if it were `--with-qt`, is there anything we gain by this duplication that the formula can’t provide?

**Comment by abcsds** [comment]
The current options for installing the octave formula are:
```
--with-java
	Build with java support
--HEAD
	Install HEAD version
```
as described by `brew info octave`. If building octave with the --with-qt flag would install the drop-in replacement for Matlab that the Octave app is, then this cask would add nothing to that, but it's not currently the case. The GUI doesn't even start by force(`--force-gui`) after building with qt.

**Comment by ilovezfs** [comment]
The point of removing the Qt option was that upstream has not fixed the option so that it works with the current version of Qt. Merging this cask isn't exactly helping with the goal of encouraging them to fix that.

**Comment by vitorgalvao** [comment]
@ilovezfs Was unaware of that. https://github.com/caskroom/homebrew-cask/pull/38549

**Pull request merged**
