### PR TITLE
Update fluid to 2.1

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by lkoujiu** [comment]
Excuse me, My error:

Error: Checksum for Cask 'fluid' does not match.

Expected: aa99e0218d8de548a292751f2e3145f299ddb7d6acf929b9d05b8d88db86e8e5
Actual:   17d1621d691cfdfb3f3442352ffe541cc86b4036790bd6ebd1b5e283551b372d


And I downloaded this app by web and checked it by using "openssl dgst -sha256 Fluid_2.1.zip" .

SHA256(Fluid_2.1.zip)= 17d1621d691cfdfb3f3442352ffe541cc86b4036790bd6ebd1b5e283551b372d

Is it a error by network proxy , or something ?

Please check it.
Thank you.

**Comment by exalted** [comment]
Not sure… I have the problem.

**Comment by brianmorton** [comment]
This usually happens when a developer does an update-in-place without bumping the version after we have already added a cask.

**Comment by exalted** [comment]
I guess one should download from the original site and update the checksum?

**Comment by vitorgalvao** [comment]
Anyone with this issue should open a new issue *and follow thd guide*. It specially covers this.

**Pull request merged**
