### PR TITLE
tableau 2024.2.2

### PR DESCRIPTION
**Pull request by okkymabruri**
Hi @krehel please review, 

just edit to Apple Silicon native
tableau 2024.2.2 Mac (Apple Silicon)
https://downloads.tableau.com/esdalt/2024.2.2/TableauDesktop-2024-2-2-arm64.dmg

### CODE REVIEW

**Comment by daeho-ro** [comment]
It seems that the livecheck url is not updated yet.

**Comment by krehel** [comment]
This looks like the Intel version was removed from the PR?

Please make this usable on Intel and Apple Silicon.

Thanks

**Comment by okkymabruri** [comment]
> This looks like the Intel version was removed from the PR?
> 
> Please make this usable on Intel and Apple Silicon.
> 
> Thanks

Hope the last commit works. 😁

**Review by p-linnane — APPROVED** [review]

**Comment by krehel** [comment]
Don't like skipping these, but looks like this version has hit my local machine so I have a bit more confidence it's available for wider audience.

**Review by krehel — APPROVED** [review]

**Review by krehel — APPROVED** [review]

**Pull request merged**
