### PR TITLE
Add gPodder.app v3.8.3

### PR DESCRIPTION
**Pull request by Parent5446**
Added new cask for gPodder, which is byte-compiled
and bundled specifically for OS X.

### CODE REVIEW

**Comment by ndr-qef** [comment]
Looks good. One small thing: could you use single quotes in strings where interpolation is not needed?

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It will be merged in [a different pull request](https://github.com/caskroom/homebrew-cask/pull/8808) due to the alteration pointed out by @ndr-qef. Your contribution is still included (and still credited to you), with the appropriate modifications, when applicable.

**Comment by Parent5446** [comment]
Thanks. Sorry for not fixing earlier. I was too busy this weekend.

**Comment by vitorgalvao** [comment]
Don’t worry about it. Thank you for the contribution, and have a nice weekend.

**Pull request closed without merging**
