### PR TITLE
Add auto_updates to Tresorit

### PR DESCRIPTION
**Pull request by Cyberbeni**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

See discussion in #94816

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please run the `style` command (or consult another cask). This will fail because `auto_updates` is in the wrong place.

**Comment by Cyberbeni** [comment]
Ah, totally forgot that the positioning for these matters. I'm only in browser ATM, so I can't run the command but fixed it based on other casks.

**Review by vitorgalvao — APPROVED** [review]

**Comment by Cyberbeni** [comment]
```
Casks with `version :latest` should not use `auto_updates`
```

**Comment by Cyberbeni** [comment]
-> https://github.com/Homebrew/homebrew-cask/pull/95183

**Pull request closed without merging**
