### PR TITLE
Update skype-for-business to 16.22.0.170

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
`
string contains null byte
`

no idea, sorry

**Comment by vitorgalvao** [comment]
> `string contains null byte`

@reitermarkus This seems to happen on Microsoft software (Office as well) and only on Travis.

**Comment by core-code** [comment]
if we know its a travis only issue, we can merge this, right? ;)

**Comment by vitorgalvao** [comment]
Good point.

**Pull request merged**
