### PR TITLE
update nomachine from 6.4.6_1 to 6.5.6_8

### PR DESCRIPTION
**Pull request by schifferl**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by schifferl** [comment]
Sorry to use Travis CI rather than RuboCop, but the last build should succeed and be ready for squashing/merging.

**Comment by reitermarkus** [comment]
Is this a different `launchctl` job from the one mentioned in the comment?

**Comment by schifferl** [comment]
Nope, copied from Travis CI verbatim.

**Comment by reitermarkus** [comment]
The comment says the `launchctl` job runs and removes `/Library/Application Support/NoMachine/nxuninstall.sh`.

**Comment by schifferl** [comment]
Sorry, I misunderstood the previous comment. I am not sure which `launchctl` job the comment refers too (I just left the comment there). The `launchctl` job I added was one that the Travis CI build system warned me about. Hope that helps and perhaps it would be worthwhile to remove the comment – just ping me if you want it done.

**Comment by reitermarkus** [comment]
I assume that a `uninstall pkgutil:` is needed now to fully uninstall everything.

**Comment by suschizu** [comment]
would it also be possible to add the 
appcast 'https://www.nomachine.com/download/download&id=7'? 
thanks :)

**Comment by schifferl** [comment]
Per the NoMachine documentation (https://www.nomachine.com/AR12K00767) it seems like running the uninstall script after deleting the `.app` file is the correct way to go. I will have to get to this later and add the appcast too. I am going to close this for now and submit another PR later.

**Pull request closed without merging**
