### PR TITLE
CloudNet 1.36.2.8

### PR DESCRIPTION
**Pull request by dayunet2009**
CloudNet

### CODE REVIEW

**Comment by miccal** [comment]
@dayunet2009 please stop sending PR's to update this Cask with changes beyond just updating the `version` and `sha256`.

**Comment by dayunet2009** [comment]
Hello, can you give me some help and tips on how I can improve? Thank you for your help.

**Comment by dayunet2009** [comment]
sha256 :no_check , but if the version number is empty, it will give me an error, what should I do?

**Comment by bevanjkay** [comment]
@dayunet2009 Miccal is referring to the additional changes to the `zap` and `uninstall` that you are committing in each PR. They are not correct changes so need to be reverted. 

The changes to the `version` and `sha256` are correct.

**Comment by dayunet2009** [comment]
I see, and I apologize for my misunderstanding. Thank you.

**Comment by dayunet2009** [comment]
Hello, I've reverted the changes. Please review.

**Comment by miccal** [comment]
Thank you @dayunet2009.

**Review by miccal — APPROVED** [review]

**Pull request merged**
