### PR TITLE
Rename douyin to douyin.rb

### PR DESCRIPTION
**Pull request by miccal**
Accidentally merged https://github.com/Homebrew/homebrew-cask/pull/131027 before realising it was missing the `.rb` extension.

### CODE REVIEW

**Comment by miccal** [comment]
@Homebrew/cask can someone please approve and merge this ASAP, thanks.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
We should have a CI check for this.

**Comment by bevanjkay** [comment]
@carlocab I think at one point we required the 'test' CI to check before passing. But it may have prevented BrewTestBot from merging.

**Comment by carlocab** [comment]
In what cases does it prevent merges that we want? We should fix those instead, or implement something like https://github.com/Homebrew/brew/pull/13767.

I guess at minimum, the tap syntax check (which seems to have run in https://github.com/Homebrew/homebrew-cask/pull/131027) should at least check that all files in `Casks` are `.rb` files.

**Pull request merged**
