### PR TITLE
Update blast2go to 5.1.1

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by CryoTheRenegade — CHANGES_REQUESTED** [review]
Needs to uninstall Applications/Blast2GO/Blast2GO.app

**Review by gtmgianni — CHANGES_REQUESTED** [review]
Travis is failing with:
```
>>> Leftover: apps
> /Applications/Blast2GO/Blast2GO.app
```

The `uninstall delete` stanza needs to be modified to remove the app bundle.

**Comment by core-code** [comment]
i already had that in here, didn't work: https://github.com/Homebrew/homebrew-cask/pull/47270/commits/bb75d629a8498124b1c0a43971179ff3a03df038

**Comment by gtmgianni** [comment]
@core-code Perhaps try using the `uninstall rmdir` stanza for the app bundle? Don't know if that'll make any difference, I'm just thinking that the app bundle (which is technically a directory) may be empty, so it's worth giving `rmdir` a shot.

**Comment by commitay** [comment]
The leftover app seems to be a CI issue I can't reproduce locally. Bumping the pause before it starts the leftover checks doesn't help.

**Review by adidalal — DISMISSED** [review]
CI-only issue

**Comment by core-code** [comment]
tried again with an update to 5.1.13, same issue.

**Comment by core-code** [comment]
is there anything i can do to get this un-stuck?

**Comment by vitorgalvao** [comment]
Rerunning Travis.

**Review by vitorgalvao — APPROVED** [review]
Failure seems to be a CI-only issue.

**Pull request merged**
