### PR TITLE
Update review-sherlock.rb

### PR DESCRIPTION
**Pull request by Rbcafe**
##### Instructions
- Look for and complete the section relevant to your submission. Delete the others, including these `Instructions`.
- `{{cask_file}}` represents the cask file you’re submitting/editing (if applicable).
- If there’s a checkbox you can’t complete for any reason, that’s OK. Just explain in detail why you weren’t able to do so.
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by Rbcafe** [comment]
https > http

**Comment by jawshooah** [comment]
Thanks. Out of curiosity, why don't you serve assets via HTTPS? Considering your site is dedicated to crypto software, I'm a bit surprised.

**Comment by Rbcafe** [comment]
Because of disclosure of domains. (**Let's encrypt**)

**Comment by jawshooah** [comment]
I don't follow, but it's irrelevant to this PR. Thanks again!

**Comment by Rbcafe** [comment]
@jawshooah  : why don't you serve assets via HTTPS?

@Rbcafe : Because of disclosure of domains. ("Let's encrypt")

HTTPS using ("Let's encrypt") is not secure regarding the confidentiality of domains.

**Pull request merged**
