### PR TITLE
Add Infra.app 0.46.0

### PR DESCRIPTION
**Pull request by lingrino**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by lingrino** [comment]
The failure is that livecheck cannot find the latest version. In that case should I prefer to download from `-latest`?

**Comment by bevanjkay** [comment]
@lingrino Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

I will have a look at the livecheck for you now

**Comment by lingrino** [comment]
The latest commit has a zap stanza that I made with https://github.com/nrlquaker/homebrew-createzap

**Comment by bevanjkay** [comment]
I'm not 100% satisfied with the livecheck solution here, @miccal do you have any better ideas? Would prefer not to use `extract_plist` here because the download is ~330mb

**Comment by miccal** [comment]
> I'm not 100% satisfied with the livecheck solution here (because it is passing a fake version number into the updater API - works for now?), @miccal do you have any better ideas? Would prefer not to use `extract_plist` here because the download is ~330mb

I have not been able to find a suitable alternative besides `:extract_plist`, I am afraid :(

**Comment by bevanjkay** [comment]
We could ask upstream to see if there's another option, otherwise, I think the solution I provided should work.. it is just more susceptible to breaking than other methods.

**Comment by miccal** [comment]
> We could ask upstream to see if there's another option, otherwise, I think the solution I provided should work.. it is just more susceptible to breaking than other methods.

Let's just use your idea, and see how it goes :)

**Comment by bevanjkay** [comment]
Thanks @lingrino 👍🏻

**Comment by lingrino** [comment]
Thank you all very much!

**Pull request merged**
