### PR TITLE
Update the-unarchiver to 3.11.1

### PR DESCRIPTION
**Pull request by jota3**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256),
      provide public confirmation by the developer: {{link}}

### CODE REVIEW

**Comment by commitay** [comment]
No `appcast` currently available for this.

**Comment by vitorgalvao** [comment]
I think for this one we can add a version and an appcast. It gets updated so rarely (because it’s stable and feature-complete) it’s unlikely we’ll have (many, if any) breakages from the unversioned URL.

**Comment by commitay** [comment]
```
codesign -vv The\ Unarchiver.app
The Unarchiver.app: valid on disk
The Unarchiver.app: satisfies its Designated Requirement
```
```
codesign -dvv The\ Unarchiver.app
Executable=/Users/commitay/Downloads/The Unarchiver.app/Contents/MacOS/The Unarchiver
Identifier=cx.c3.theunarchiver
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=1235 flags=0x0(none) hashes=31+5 location=embedded
Signature size=8892
Authority=Developer ID Application: Dag Agren
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=21 May 2016, 04:32:55
Info.plist entries=29
TeamIdentifier=M9KXCWYWYR
Sealed Resources version=2 rules=12 files=203
Internal requirements count=1 size=212
```

**Review by commitay — APPROVED** [review]
Codesigning verified locally.

**Pull request merged**
