### PR TITLE
update dotnet-sdk to 2.1.300

### PR DESCRIPTION
**Pull request by dasMulli**
According to https://github.com/dotnet/core/blob/master/release-notes/releases.json

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by adidalal** [comment]
Release page is not yet updated
https://www.microsoft.com/net/download/macOS/build

**Comment by qayshp** [comment]
https://github.com/dotnet/core/pull/1610 and https://github.com/dotnet/core/pull/1609 and others at https://github.com/dotnet/core/pulls?q=is%3Apr+2.1+is%3Aopen would need to be merged first, and a release tag be created in that repository before the release is official.

**Comment by qayshp** [comment]
It has now been officially released :)

and 2.1.300 is up at https://www.microsoft.com/net/download/macOS/build

**Comment by dasMulli** [comment]
Next time I'll add a hold warning, wanted to prepare early to make sure CI run passes but wasn't clear about it in the message.

**Pull request merged**
