### PR TITLE
tehmaspc update hashi nomad

### PR DESCRIPTION
**Pull request by tehmaspc**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please [squash your commits](http://davidwalsh.name/squash-commits-git).

**Comment by adityadalal924** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/15552

@vitorgalvao is there an easy way to squash commits for a PR? I just end up using cask-repair and then fastmerge on the new PR, but I'm sure there's a more elegant solution.

**Comment by tehmaspc** [comment]
will do next time; thanks.

**Comment by vitorgalvao** [comment]
@adityadalal924 When I do it, I `prfixmaster` and squash them myself there.

**Pull request closed without merging**
