### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by vitorgalvao**
As suggested in https://github.com/caskroom/homebrew-fonts/pull/391#issuecomment-141640776.

If there are no objections, might as well add it to every repo.

### CODE REVIEW

**Comment by jawshooah** [comment]
Need to add `.gitattributes` to [`test/layout_test.rb`](https://github.com/caskroom/homebrew-cask/blob/master/test/layout_test.rb#L38).

**Comment by vitorgalvao** [comment]
Thank you. Added.

**Comment by alebcay** [comment]
Any reason on this not being merged yet?

**Comment by vitorgalvao** [comment]
No, just that I forgot about it. Thank you for the bump.

**Pull request merged**
