### PR TITLE
Update kid3 from 3.9.0 to 3.9.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
Download works now, at least locally.

**Comment by jenhsun** [comment]
@Porkepix @neutric Download failed
`curl: (35) error:06FFF089:digital envelope routines:CRYPTO_internal:bad key length`

**Comment by miccal** [comment]
@jenhsun try again, as it is working for me:
```
|-> brew fetch kid3
==> Downloading https://downloads.sourceforge.net/kid3/kid3-3.9.1-Darwin.dmg
==> Downloading from https://telkomuniversity.dl.sourceforge.net/project/kid3/kid3/3.9.1/kid3-3.9.1-Darwin.dmg
######################################################################## 100.0%
Downloaded to: /Users/miccal/Library/Caches/Homebrew/downloads/23b4c4302c5c524e6fbc0f86635d04f271d8127a8d3b22b8961bf414171bb7b9--kid3-3.9.1-Darwin.dmg
SHA256: 7228e15373e5f3c58d928bd0267dc51bc2f505b64ba86fddd627c6631b7bab37
```

**Comment by jenhsun** [comment]
@miccal Thanks, it works while my VPN enabled. I guess it might be my network problem.

**Pull request merged**
