### PR TITLE
Update cpumeter to latest

### PR DESCRIPTION
**Pull request by yusukeshib**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
First line of the cask and its name also need to update.

**Comment by yusukeshibata** [comment]
Thanks! I updated first line of the cask.

**Comment by miccal** [comment]
You also need to change the filename to `cpuinfo.rb`.

**Comment by yusukeshibata** [comment]
I changed. Thank you.

**Pull request merged**
