### PR TITLE
Add CurseForge latest

### PR DESCRIPTION
**Pull request by dbergey**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you 

Ping @vitorgalvao -- I have changed the `url` to their GitHub page that I found while hunting for an `appcast`, and (I am guessing) that it is not easy to find and therefore not really notable:
```
audit for curseforge: failed
 - GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

**Comment by dbergey** [comment]
I explored using the appcast and GitHub link, but ran into that message during the audit state as well, so ended up using the :latest strategy similar to the Spotify cask.

Additionally, the next-to-last release on the GitHub page (from 3 days ago) notes "This will be the last version released on github" so I'm not sure using the appcast is a good long-term solution for this cask.

**Comment by dbergey** [comment]
Also: the vendor isn't really publishing the GitHub repo as download location, and it's a fairly new repository since this app's functionality was split out of the official Twitch app. So that might account for why the GitHub repository isn't forked/starred/watched very much.

**Comment by miccal** [comment]
Thanks @dbergey -- I have reverted my changes.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
