### PR TITLE
Add SoapUI.app version 5.1.3

### PR DESCRIPTION
**Pull request by vinkla**
SoapUI is a free and open source cross-platform Functional Testing solution. http://www.soapui.org/

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Can you build an `uninstall` for this?

**Comment by vitorgalvao** [comment]
@vinkla Can you build an `uninstall` for this?

@radeksimko Would it be better to just merge this with `installer :manual` and forget the issues in #4939 for now? Either way that submission is now terribly outdated.

**Comment by vinkla** [comment]
@vitorgalvao Sure. I'll look into it.

**Comment by vinkla** [comment]
On other hand. This application is very buggy. It fails every time I try to open it on Yosemite. This is be a bad experience for the users. What do you think @vitorgalvao?

**Comment by vitorgalvao** [comment]
I have no quarrel with not including it. There were already a bunch of issues with this from #4939. Since @radeksimko worked the most on making this work, at the time, we’ll go with what he prefers.

**Comment by radeksimko** [comment]
If we can resolve at least the problem with installation automation, I'd be :+1: for including it with some conditionals for specific OSX versions where this actually works.

That said, @vinkla have a look at [this comment](https://github.com/caskroom/homebrew-cask/pull/4939#issuecomment-51690346) in particular, it may need a PR into the soapui project so it can be automated. Once it's sorted out in upstream and we know it can be silently installed, I will be happy to merge that cask in.

Generally I'm :-1: for any more casks w/ `installer :manual` as it IMO goes a bit against the [philosophy](https://github.com/caskroom/homebrew-cask/blob/master/doc/hacking.md#goals-design-and-philosophy) of this project:

> All functionality should be accessible from the CLI. The user should be freed (freed!) from interacting with a GUI.

**Comment by vinkla** [comment]
Have you tried to run it on your system? It seems broken. I can't even interact with the UI before it breaks. Maybe it works better on older systems. I don't know.

Then I'll close this for now and we can reopen it if someone ever needs it in the future and when the silent issue has been fixed in the installation process.

Closed.

**Comment by radeksimko** [comment]
> It seems broken.

I remember it was working on Mavericks, I haven't tried it on Yosemite yet.

**Pull request closed without merging**
