### PR TITLE
Update RapidWeaver to use latest version. Closes Issue #37403

### PR DESCRIPTION
**Pull request by SConaway**
Update RapidWeaver to use latest version (7.4.1 as of 8-5-17). Closes Issue #37403 .

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [NA] If the `sha256` changed but the `version` didn’t,  
      provide public confirmation ([How?][version-checksum]): {{link}}

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by reitermarkus** [comment]
There is still a versioned URL available:

`https://dl.devmate.com/com.realmacsoftware.rapidweaver/18708/1496675639/RapidWeaver-18708.zip`

**Comment by SConaway** [comment]
I am confused on why we don't use `:latest` when possible.

**Comment by reitermarkus** [comment]
It is preferable to have a checksum, which is only possible for versioned URLs.

**Comment by SConaway** [comment]
Ok. I will update for versioned URL.

**Comment by SConaway** [comment]
Better?

**Comment by barchard** [comment]
FYI, the script says 'leopard' or later. 7.x requires `El Capitan`

https://kb.realmacsoftware.com/article/53-rapidweaver-system-compatibility-notes

**Pull request merged**
