### PR TITLE
updated mactex (20160604)

### PR DESCRIPTION
**Pull request by miccal**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by miccal** [comment]
Something is wrong, but I am not sure what?

**Comment by arbourd** [comment]
@miccal It's a `shasum` mismatch. Tests ran on your code (you can see by clicking details and then a build, or [right here](https://travis-ci.org/caskroom/homebrew-cask/jobs/135493847)).

Try running `brew audit --download mactex` again locally, because the test suite is getting a different `shasum`

**Comment by miccal** [comment]
Thanks for the advice, but running `brew cask audit --download mactex` tries to download the older version, which now does not exist. I might leave this for someone more knowledgable.

**Comment by arbourd** [comment]
@miccal it looks like the mirror for the change isn't up yet: http://tug.org/cgi-bin/mactex-download/MacTeX.pkg

```
mactex-download: Failed to retrieve MacTeX.pkg
via: http://mirror.ctan.org/systems/mac/mactex/mactex-20160603.pkg
tried: http://ctan.mirror.rafal.ca/systems/mac/mactex/mactex-20160603.pkg

Most likely this means the file has not made its way to the CTAN mirrors yet, and the best remedy is simply to wait a day or two.
```
I would try again tomorrow or the day after. It looks like a bunch of the mirrors aren't updated (http://ctan.math.ca/tex-archive/systems/mac/mactex/)

**Comment by miccal** [comment]
Thanks @arbourd.

**Pull request closed without merging**
