### PR TITLE
Delete rcdefaultapp

### PR DESCRIPTION
**Pull request by miccal**
`homepage` and `url` appear dead:
```
-bash-5.0.16- /Users/miccal (32) [> brew cask fetch rcdefaultapp

==> Downloading external files for Cask rcdefaultapp
==> Downloading http://www.rubicode.com/Downloads/RCDefaultApp-2.1.X.dmg
curl: (28) Failed to connect to www.rubicode.com port 80: Operation timed out 
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
curl: (28) Failed to connect to www.rubicode.com port 80: Operation timed out 
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
curl: (28) Failed to connect to www.rubicode.com port 80: Operation timed out 
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
curl: (28) Failed to connect to www.rubicode.com port 80: Operation timed out 

Error: Download failed on Cask 'rcdefaultapp' with message: Download failed: http://www.rubicode.com/Downloads/RCDefaultApp-2.1.X.dmg
```
Ping @vitorgalvao for confirmation.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Might be temporary. Let’s give it one or two weeks.

```
rcdefaultapp
30 days: 37 (#1671)
90 days: 159 (#1356)
365 days: 665 (#1279)
Age: 2323 days (added 2013, November 20)
```

**Comment by vladimyr** [comment]
FWIW both RCDefualtApp & RCWebColorPicker .dmg-s can be downloaded from the following snapshot https://web.archive.org/web/20190908113330/http://www.rubicode.com/Software/Bundles.html

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/79702#issuecomment-609829658

**Comment by colindean** [comment]
If you wind up here after running a dormant `Brewfile` like I did, note that https://github.com/Lord-Kamina/SwiftDefaultApps is the new hotness and it's in casks as `swiftdefaultappsprefpane`

```ruby
cask 'swiftdefaultappsprefpane'
```

**Pull request merged**
