### PR TITLE
Delete intel-power-gadget.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
https://github.com/Homebrew/homebrew-cask/issues/65484

### CODE REVIEW

**Comment by core-code** [comment]
can we have a look if updating the URL to the newest one 

https://software.intel.com/sites/default/files/managed/34/fb/Intel®%20Power%20Gadget.dmg

helps with the certificate problem before removing it?

**Comment by vitorgalvao** [comment]
Sure. I missed there was a new URL.

**Comment by core-code** [comment]
> Sure. I missed there was a new URL.

should i send a PR?

**Comment by vitorgalvao** [comment]
> should i send a PR?

Yes, please.

**Comment by core-code** [comment]
Submitted (https://github.com/Homebrew/homebrew-cask/pull/65513)

**Pull request closed without merging**
