### PR TITLE
Update scidavis to 1.23.4

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> installer: Error the package path specified was invalid: '/usr/local/Caskroom/scidavis/1.23.4/scidavis-1.23.4.pkg'.

**Comment by brianmorton** [comment]
non-stop problems with this cask... i'll have a look

**Comment by brianmorton** [comment]
There is an actual problem with the installer:
image

**Comment by brianmorton** [comment]
Through some research I think this is actually a beta so I'll just close the PR.

**Pull request closed without merging**
