### PR TITLE
lookingglassbridge 2.2.0

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — APPROVED** [review]

**Comment by krehel** [comment]
I was able to look into this a bit more (finally!) and being able to run this in a sandbox environment yields the following -

From version `2.1.0` to `2.2.0`, there is an additional `postinstall` script which opens up a prompt using `osascript` that requires user input, and that's causing the hangup here in CI.

I'm going to investigate if there's a switch that can be applied to bypass this or reach out to the upstream vendor to determine a way forward.  Ideally this prompt can run at first launch instead of install time.

If there's not a good solution, we may need to simply remove this Cask as the install cannot be fully unattended.

**Comment by krehel** [comment]
FYI I've reached out to the vendor to let them know about the issue.  This may take some time to resolve, so I'll mark this as draft for now.

**Comment by krehel** [comment]
Closing this PR.  Was able to speak with upstream.  They will look into the prompt preventing unattended install and look into releasing an update in the near future to address.  Until then this Cask will be blocked on `2.1.0` version.

**Pull request closed without merging**
