### PR TITLE
calibre: add comment to avoid changing URL

### PR DESCRIPTION
**Pull request by p-linnane**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

---
Resolves https://github.com/orgs/Homebrew/discussions/5576.

### CODE REVIEW

**Comment by krehel** [comment]
There have been issues with this in the past, fyi -

https://github.com/Homebrew/homebrew-cask/issues/104814
https://github.com/Homebrew/homebrew-cask/issues/10039

I know it goes back a few years, but unless anything has changed, we'll need to revisit.

Seems like every few months we get the asme issue with the same verbiage about it being slow.

**Comment by p-linnane** [comment]
More inclined to remove this cask instead if this is a multi-year issue with an uncooperative and dismissive upstream. cc @Homebrew/cask

**Comment by bevanjkay** [comment]
I have personally never experienced issues with Calibre's downloads being excessively slow. The cask gets 24k installs per year and we don't receive regular complaints about it. Even in the case that it is slow, we just distribute from upstream, so I don't think it's a good enough reason for removal.

**Comment by krehel** [comment]
Yeah I agree. It could be interesting to know the geographic distribution of where it is slow but we couldn't do anything with that information anyway.

Ultimately no matter what happens something is either slow or breaks -- if I have to choose I take slow for a limited population.

**Comment by p-linnane** [comment]
I've pivoted this PR to add a comment explaining our stance so this doesn't happen again.

**Review by krehel — APPROVED** [review]

**Comment by krehel** [comment]
Gets a ✅ from me - thank you @p-linnane!

**Comment by exactmultiple3425** [comment]
> I have personally never experienced issues with Calibre's downloads being excessively slow. The cask gets 24k installs per year and we don't receive regular complaints about it. Even in the case that it is slow, we just distribute from upstream, so I don't think it's a good enough reason for removal.

Most users, like myself, who encounter slowness may not report it, as there is little that Homebrew can do to address the issue. However, this does not imply that the problem is nonexistent. This comment conveys a strong "It works on my end" sentiment.

**Pull request merged**
