### PR TITLE
Update eloston-chromium to 69.0.3497.100-1

### PR DESCRIPTION
**Pull request by chase9**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Welcome and thank you but according to the page this is the development page, not the stable. This repo is for stable versions.

**Comment by chase9** [comment]
Apologies, I submitted this using ```cask-repair``` which submitted here. I'll find my way to the dev repo.

**Comment by vitorgalvao** [comment]
> I submitted this using `cask-repair` which submitted here.

We don’t have casks with repeated names in the main repos. `cask-repair` always submits to the correct one according to the name.

> I'll find my way to the dev repo.

It’s [caskroom/versions](https://github.com/caskroom/homebrew-versions), but please don’t. I see you’re part of the team, but no user is really asking for a development version of this as a cask. I imagine it gets updated quite often, which will make it a maintenance burden for no gain.

**Comment by chase9** [comment]
Understandable. I had already put in a pull but I'll remove it now.

**Comment by vitorgalvao** [comment]
@chase9 Thank you. If user interest in that versions pikes up, we’ll gladly consider it.

**Pull request closed without merging**
