### PR TITLE
find-appcast: new case with endpoint

### PR DESCRIPTION
**Pull request by vitorgalvao**
Found via https://github.com/Homebrew/homebrew-cask/pull/80793.

### CODE REVIEW

**Comment by core-code** [comment]
FYI on cask 'front':

```
An "app-update.yml" file was found, but we could not parse it.
Please report this on https://github.com/Homebrew/homebrew-cask/
Provide this info:

provider: generic
url: 'https://dl.frontapp.com/desktop'
updaterCacheDirName: front-updater
```

**Comment by core-code** [comment]
=> 
https://dl.frontapp.com/desktop/updates/latest/mac/latest-mac.yml

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/82088

**Comment by vitorgalvao** [comment]
Also https://github.com/Homebrew/homebrew-cask/pull/82089.

**Pull request merged**
