### PR TITLE
Update termius from 4.7.2 to 4.9.2

### PR DESCRIPTION
**Pull request by core-code**

### CODE REVIEW

**Comment by ran-dall** [comment]
@core-code Could I ask why the downgrade? `4.9.2` is the latest version downloaded.

Screen Shot 2019-07-17 at 9 23 21 AM

**Comment by core-code** [comment]
huh? the PR updates from 4.7.2 to 4.9.2. i am not sure why you call it a downgrade.

**Comment by ran-dall** [comment]
> huh? the PR updates from 4.7.2 to 4.9.2. i am not sure why you call it a downgrade.

👉 My bad, I read it wrong and I was under the impression the ML updated this because I had gotten the `info.plist`.

**Comment by core-code** [comment]
i've adjusted the PR title for clarity ;)

**Pull request merged**
