### PR TITLE
Update snippet-edit to 1.2.1

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
see: https://cocoaholic.com/snippet_edit/

**Comment by vitorgalvao** [comment]
Considering the current state of the site, I’d say it’s a matter of time before they get rid of the download link. Removal.

**Comment by vitorgalvao** [comment]
Also, thank you for the links. They’re making it really easy for me to evaluate the cases.

**Comment by suschizu** [comment]
you're welcome :)

**Pull request closed without merging**
