### PR TITLE
Update neat to 4.5.0.99

### PR DESCRIPTION
**Pull request by qayshp**
After making all changes to the cask:

- [x] `brew cask audit --download neat` is error-free.
- [x] `brew cask style --fix neat` reports no offenses.
- [x] The commit message includes the cask’s name and version.

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by qayshp** [comment]
Note that the domain used to host the file has also changed, but as far as I can tell, this is the official URL.
That said, I may need to split this off into an older version and newer one, as the 4.X series is now discontinued (with 4.5.0.99 being the latest) and they have a newer one with a different feature set.

**Comment by commitay** [comment]
> as the 4.X series is now discontinued (with 4.5.0.99 being the latest) and they have a newer one with a different feature set.

We should update to the current version or delete this Cask.

**Comment by qayshp** [comment]
I was debating moving this cask to [caskroom/homebrew-versions](https://github.com/caskroom/homebrew-versions/). My main concern was that licenses from 4.X do not carry forward, so the upgrade experience would be bad. But now looking at some other versioned casks, this seems to be expected. When I get a chance, I'll update this to the latest and create a PR in versions.

(An example I looked at was [homebrew-versions/istat-menus5](https://github.com/caskroom/homebrew-versions/blob/master/Casks/istat-menus5.rb) vs. [homebrew-cask/istat-menus](https://github.com/caskroom/homebrew-cask/blob/master/Casks/istat-menus.rb) )

**Comment by commitay** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/44963

**Pull request closed without merging**
