### PR TITLE
copyq 8.0.0

### PR DESCRIPTION
**Pull request by Moulick**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free. **Note: Locally I has to audit with `--no-signing`.**
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

Ref: https://github.com/hluk/CopyQ/issues/1884

### CODE REVIEW

**Comment by p-linnane** [comment]
Why'd we drop the version for older macOS versions?

**Comment by hluk** [comment]
> Why'd we drop the version for older macOS versions?

Which versions? CopyQ has supported macOS 10.15+ for a long time.

**Comment by Moulick** [comment]
CopyQ has not been updated on brew for a long time due to various reasons. Also, doesnt brew itself only officially support 12+?

**Comment by p-linnane** [comment]
I'm referring to the `on_catalina :or_older` block. Though we only support Monterey+, Homebrew runs on machines all the way back to El Capitan. For casks, there's no issue with offering a legacy version for older OS's. [`onyx`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/o/onyx.rb) is an example of this.

If there's no older version available for pre-Catalina, that's fine. Just trying to clarify.

**Comment by Moulick** [comment]
I guess we can add `on_mojave :or_older` as the current 8.0.0 supports Catalina. @hluk do you know which version of copyq last supported Mojave?

**Comment by hluk** [comment]
> do you know which version of copyq last supported Mojave?

No idea. I'm not familiar with the code names.

The CMake build has `CMAKE_OSX_DEPLOYMENT_TARGET` set to 10.15 since CopyQ 6.1.0. Before that it was not set - it used some default (I think this was based on the build host).

**Comment by hluk** [comment]
Looking at what [Qt 6.6 supports](https://doc.qt.io/qt-6.6/macos.html#supported-versions): macOS 11, 12, 13

So I'm not sure if the app works on anything older.

**Comment by Moulick** [comment]
I can add back `version "5.0.0"` for 10.14 and older, maybe that was built with older Qt versions.

**Review by krehel — APPROVED** [review]

**Comment by Moulick** [comment]
@krehel Is there any place where I can find how often the API syncs to the git repo? As the brew api https://formulae.brew.sh/api/cask/copyq.json still returns 7.1.0 🤔

**Comment by krehel** [comment]
@Moulick - it's updated.  Also to answer - about every 15 minutes.

**Comment by p-linnane** [comment]
Thanks for all the research here everyone.

@Moulick This is the job that regenerates the API: https://github.com/Homebrew/formulae.brew.sh/actions/workflows/scheduled.yml

**Comment by gibfahn** [comment]
Not sure why this is necessary, but after updating to this version I had to run the commands in  https://github.com/hluk/CopyQ/issues/2637#issuecomment-2004117038 to stop CopyQ crashing on launch:

```
xattr -d com.apple.quarantine /Applications/CopyQ.app
codesign --force --deep --sign - /Applications/CopyQ.app
```

I thought homebrew did ad-hoc codesigning automatically, but maybe that's only for formulae not for casks.

**Comment by p-linnane** [comment]
> I thought homebrew did ad-hoc codesigning automatically, but maybe that's only for formulae not for casks.

Casks are just pointers to upstreams binaries. They'd need to start signing their releases to avoid this.

**Comment by gibfahn** [comment]
>Casks are just pointers to upstreams binaries. They'd need to start signing their releases to avoid this.

Makes sense (although unlikely given https://github.com/hluk/CopyQ/issues/1884#issuecomment-1999313311), will use the workaround for now at least.

**Pull request merged**
