### PR TITLE
Add ka-lite 0.17.3

### PR DESCRIPTION
**Pull request by SConaway**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by SConaway** [comment]
I need help with the uninstall. I can manually script it or somehow has yes twice to the provided script.

**Comment by commitay** [comment]
Thanks for the PR! I'll take a look at the `uninstall`.

**Comment by SConaway** [comment]
Ok Thanks.

**Comment by commitay** [comment]
This depends on python 2.7.12 but because of https://github.com/Homebrew/homebrew-core/pull/14408, it doesn't recognise brew `python`

**Comment by SConaway** [comment]
I know. Will that cause this not to work? I thought I could add it to the caveats.

**Comment by commitay** [comment]
The `la-lite` `pkg` install fails without the correct python, we can't depend on the Brew `python` formula and installing the python `pkg` will probably cause conflicts with Homebrew.

**Comment by SConaway** [comment]
I tried it, and it doesn't seem to conflict.

**Comment by commitay** [comment]
The `pkg` installer overwrites the Brew `python` symlinks in `/usr/local/bin`

**Comment by commitay** [comment]
> Is there anyway to fix this? Maybe mention having python2 installed in a caveat?

No, the `ka-lite` `pkg` install fails if it can't find `/usr/local/bin/python`. A caveat would have to be an instruction to install the bundled python but this will then conflict with Brew `python`.

Upstream has instructions for installing this with Brew `python` but they are outdated since https://github.com/Homebrew/homebrew-core/pull/14408. Upstream needs to change the installer to look for `python2` instead of `python` in `/usr/local/bin`.

I'll contact them and see if they can update the installer.

**Comment by SConaway** [comment]
Is that the solution to uninstalling ka-lite?

**Comment by SConaway** [comment]
Any news?

**Comment by commitay** [comment]
No, waiting for upstream.

**Comment by SConaway** [comment]
Oh OK.

**Comment by commitay** [comment]
Upstream has merged the `python2` fix, just need to wait for a new release.

**Comment by commitay** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/41785

Thank you for the contribution. Your contribution is still credited to you.

**Pull request closed without merging**
