### PR TITLE
Add Casks/ncar-ncl.rb

### PR DESCRIPTION
**Pull request by ryanpavlick**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
All your `url` point to the same place. How can they have different checksums?

**Comment by jawshooah** [comment]
@vitorgalvao Not quite. Check the first segment of the `logicalFileId` param in each `url`.

**Comment by vitorgalvao** [comment]
Ah, thank you @jawshooah, I see it.

@rpavlick There’s trailing whitespace that needs to be removed.

**Comment by rpavlick** [comment]
@vitorgalvao I removed the whitespace. Thanks.

**Pull request merged**
