### PR TITLE
Removing duplicate cask 'origami'.

### PR DESCRIPTION
**Pull request by justinhaaheim**
Removing duplicate cask 'origami'. The cask 'origami-studio' installs the same application and appears to be more up-to-date, and uses the correct application name and web address.

As far as I can tell, none of the checkboxes below are relevant to removing a duplicate cask.

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> As far as I can tell, none of the checkboxes below are relevant to removing a duplicate cask.

You are correct.

It seems that [at one point they were indeed different things](https://github.com/facebookarchive/origami#origami-for-quartz-composer-is-deprecated-check-out-origami-studio--a-native-mac-app-built-for-modern-interface-design-by-facebook).

Thank you for the contribution. And welcome.

**Comment by justinhaaheim** [comment]
Sure thing. Thanks for the work you do, Vitor.

**Comment by justinhaaheim** [comment]
BTW, just to check: is there something to be done so that folks who installed origami via this now-deleted package are linked to the current package? Or would that not be desirable, and people will just need to uninstall origami and install origami-studio?

**Comment by vitorgalvao** [comment]
For all intents and purposes they are different apps, and [users are responsible to know about the apps they use](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md).

It’s not our place to warn them of this deprecation, nor to impose this alternate app on them.

**Comment by justinhaaheim** [comment]
Got it -- thanks for clarifying.

**Pull request merged**
