### PR TITLE
android-messages: deprecate

### PR DESCRIPTION
**Pull request by sonique6784**
this version is not maintained anymore, but a fork as emerged and is available with brew.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by sonique6784** [comment]
Should we consider pulling from orangedrangon directly instead of deprecating?

**Comment by razvanazamfirei** [comment]
I don't think this meets the [criteria](https://docs.brew.sh/Acceptable-Casks#forks-and-apps-with-conflicting-names) for using the fork. 
> Forks and apps with conflicting names
Forks must have the vendor’s name as a prefix on the cask’s filename and token. If the original software is discontinued, forks still need to follow this rule so as to not be surprising to the user. There are two exceptions which allow the fork to replace the main cask:
> 1. The original discontinued software recommends that fork.
> 2. The fork is so overwhelmingly popular that it surpasses the original and is now the de facto project when people think of the name.

**Comment by sonique6784** [comment]
thanks @razvanazamfirei, then let's go ahead with deprecation for now. The original project is totally abandoned since 2019, and the app doesn't work as expected anymore, but it the owner didn't recommend the fork, and the fork is not yet "overwhelmingly popular".

**Comment by razvanazamfirei** [comment]
Sounds good! 👍 Thanks so much for your first contribution, @sonique6784! Without contributions like yours, it'd be impossible to keep our project going.

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
