### PR TITLE
parallels-virtualization-sdk 18.3.2-53621

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by krehel** [comment]
@Homebrew/cask 

Could this be failing due to recent changes whereby this `livecheck` is failing?

Does it make sense to add `depends_on cask: parallels` seeing as we are already coupling version matching?

**Comment by bevanjkay** [comment]
@samford I'm not sure if this is a `livecheck` or a CI related issue, but the `livecheck` will succeed when the block is copied from `parallels`, but it won't work when it is referenced with

```ruby
livecheck do
  cask "parallels"
end
```

**Comment by krehel** [comment]
Thanks @bevanjkay! Appreciate the input.  Looking back through history it seems this livecheck has existed in this way for a while, so I started thinking if this wasn't specific to this cask... which led me to wonder if some of the more recent `brew` changes could be underpinning this.

But @samford your inputs would be helpful here, as noted.  Perhaps @carlocab or @Bo98 could have some insights as well.

**Comment by bevanjkay** [comment]
@krehel The livecheck is working locally, so that would suggest a CI related concern. I'm going to rerun CI in debug mode and it might print some additional output on the failure.

**Comment by bevanjkay** [comment]
With the recent changes to CI, `HOMEBREW_NO_INSTALL_FROM_API` is no longer set during the `brew audit` stage which is causing the livecheck to fail when referencing another cask's livecheck (because livecheck is not included in the API).

@Bo98 should `NO_INSTALL_FROM_API` be unset in the CI run after the initial setup? it seems like something is unsettling the variable despite it being passed in to the `env` at initiation.

**Comment by Bo98** [comment]
Potentially. But equally `brew audit` does have [code to implicitly bypass the API](https://github.com/Homebrew/brew/blob/5b30de880d3c937b121dcc036582143dc4548b4f/Library/Homebrew/dev-cmd/audit.rb#L121) anyway (otherwise _any_ audit wouldn't work properly rather than just those that reference another formula), so we should just fix that to cover livechecks properly. I will look into this in the afternoon.

**Comment by Bo98** [comment]
This should be fixed now.

You are right that we should probably adjust setup-homebrew as well to be safe, but this was still a bug in `brew livecheck` anyway that would've affected local usage as that command supports implicit no-api handling.

Three casks that might(?) still have issues are winzip, smultron and redquits. They use `CaskLoader` for some reason when they really shouldn't be.

**Review by Bo98 — APPROVED** [review]

**Comment by krehel** [comment]
Thanks @Bo98!  This looks good now.  I'll check out the other casks you mentioned.

**Pull request merged**
