### PR TITLE
Add HMA! Pro VPN.app v. 3.2.11.2

### PR DESCRIPTION
**Pull request by rqelibari**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

### CODE REVIEW

**Comment by vitorgalvao** [comment]
It’s missing `uninstall`. There are [scripts](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md) geared for that.

**Comment by rqelibari** [comment]
That is what I thought initially. But the [little-snitch](https://github.com/caskroom/homebrew-cask/blob/master/Casks/little-snitch.rb) task has no uninstall neither.

So what is the reason it is needed here?

**Comment by miccal** [comment]
Little Snitch missing an uninstall was an oversight that has now been [fixed](https://github.com/caskroom/homebrew-cask/pull/27185).

**Comment by vitorgalvao** [comment]
Little Snitch [also needs it](https://github.com/caskroom/homebrew-cask/issues/6872). It’s just unfortunate it was merged before we started enforcing the rule.

**Comment by rqelibari** [comment]
Actually having uninstalled enforced is good idea!
So I added all the files. The only file I don't know how to handle is the BootCache File in

```
/private/var/db/BootCaches/<SOME_ID_HERE>/app.com.privax.hmaprovpn.playlist
```

Does anyone know if it is ok to just remove this one?

**Comment by rqelibari** [comment]
Thank you @vitorgalvao. Should have thought of formatting according to documentation!

**Comment by vitorgalvao** [comment]
Thank you.

**Pull request merged**
