### PR TITLE
Create macos-mojave-patcher 1.3.7

### PR DESCRIPTION
**Pull request by ghost**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by ran-dall** [comment]
@gottabeleGIT What does this do?

**Comment by gottabeleGIT** [comment]
Several things, but mainly the patching of a macOS Mojave installer to be able to be installed on a Mac that does not natively support Mojave.

**Comment by gottabeleGIT** [comment]
Nevermind, closing this PR as this application might be illegal: https://www.reddit.com/r/MacOS/comments/b2a8ij/is_mojave_patcher_legal/

**Comment by gottabeleGIT** [comment]
Nevermind, closing this PR as this application might be illegal: https://www.reddit.com/r/MacOS/comments/b2a8ij/is_mojave_patcher_legal/

**Comment by ran-dall** [comment]
@gottabeleGIT No problem, you might want to submit it [Hacker's Brew](https://github.com/open-arsenal/homebrew-hackers-brew) which is a tap I made for stuff like this, of questionable legality. I haven't had much chance to work on it lately but I should be getting around to it in the coming months. There's some other casks on here that also that I don't think are a fit for the main tap, that I intend to move over.

**Comment by gottabeleGIT** [comment]
Thanks, I'll have a look. Truthfully, I was debating the legality of this application before I submitted it, I thought I might give it a try since similar Hackintosh-type tools exist on Homebrew Cask (e.g. Clover Configurator) but in the end, I just didn't want to take the risk.

**Pull request closed without merging**
