### PR TITLE
Update spek.rb, add the withmorten/spek-alternative forked version

### PR DESCRIPTION
**Pull request by maboloshi**
The original author may suspend maintenance, here add the [withmorten/spek-alternative](https://github.com/withmorten/spek-alternative) forked version for Mojave.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].
- [ ] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

### CODE REVIEW

**Comment by vitorgalvao** [comment]
* The `else` version is behind the `<= :sierra`.
* We’re not going to add a fork in one of the conditionals; that would be surprising to users.
* We have specific documented rules regarding forks, we’re not going to add any random one. It needs to either be extremely popular (more than the original) or officially sanctioned by the original authors.

**Comment by maboloshi** [comment]
@vitorgalvao  alexkay/spek#160, alexkay/spek#162, alexkay/spek#180 etc. The original version cannot run on 10.3.3 or higher.

**Comment by maboloshi** [comment]
Can I create a `spek-alternative.rb` setting `conflicts_with cask: spek` ?

**Comment by maboloshi** [comment]
Thank you , and I agree that there is no need to follow up on the unpopular cask.

**Pull request closed without merging**
