### PR TITLE
Update subsurface from 5.0.4 to 5.0.5

### PR DESCRIPTION
**Pull request by tpak**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by tpak** [comment]
Originally created with `brew bump-cask-pr`. 
That failed because subsurface has moved it's downloads from GitHub to: `https://subsurface-divelog.org/downloads/ ` so I went ahead and updated the livecheck.

**Comment by neutric** [comment]
> Originally created with `brew bump-cask-pr`. That failed because subsurface has moved it's downloads from GitHub to: `https://subsurface-divelog.org/downloads/` so I went ahead and updated the livecheck.

The previous `url` is still fine for livecheck purposes. It failed because the regex, which you accidentally (?) deleted entirely, needed updating to account for the new file name. I tweaked it some more to bring it in line with current "best practices" in this repo. Please reinstate the previous `url` and this `regex`:
```
regex(/href=.*?Subsurface-(\d+(?:\.\d+)+)\.dmg/i)
```

Please also address the style issues that cause checks to fail.

**Comment by tpak** [comment]
@neutric thanks - I will give that a try. This is my first go at this and I appreciate your help. 
I'll take care of the style as well. I had to step away for a bit but will take care of this.

**Comment by neutric** [comment]
Good job so far. `brew style --fix subsurface` should take care of most, if not all, of the style nits.

**Comment by miccal** [comment]
Thank you @tpak.

**Comment by tpak** [comment]
@miccal thanks for doing that! 
@neutric thanks for your patience with me. I wandered in thinking this would be a 5-minute fix, lol, no such thing some days. 

i very much appreciate all you guys do with Homebrew!

**Comment by neutric** [comment]
@tpak All good, thanks for helping keep `Homebrew` up to date!

**Pull request merged**
