### PR TITLE
The sha was wrong (all caps)

### PR DESCRIPTION
**Pull request by danielgomezrico**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
There are merge conflicts that need fixing.

**Comment by danielgomezrico** [comment]
@vitorgalvao ready

**Comment by vitorgalvao** [comment]
You pulled a bunch of unrelated commits. Need help to fix?

**Comment by danielgomezrico** [comment]
Opa, I made merge with the, thought  that was the problem, then what should I do?

**Comment by vitorgalvao** [comment]
Do an [interactive rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-reflog) and remove the offending commits. You should always be working on a new branch prior to submitting PRs, though.

**Comment by vitorgalvao** [comment]
Please submit a new PR with the fix.

**Pull request closed without merging**
