### PR TITLE
Add Itraffic.app Latest

### PR DESCRIPTION
**Pull request by foamzou**
create the Itraffic.app in brew cask

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Review by SMillerDev — COMMENTED** [review]
Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

**Comment by foamzou** [comment]
@SMillerDev 
I have appended the zap.

BTW, Ask a question. I don't understand the meaning of livecheck. If I must modify the version when update the app. Then what is the meaning of livecheck.

I thought, as long as livecheck is set, then I only need to upload the app to the specified url with the version code, no need to modify the rb file. But I see that many prs do not seem to be like this. They have set up livecheck, but they are still modifying the version.

**Comment by bevanjkay** [comment]
@foamzou

Livecheck is used to test what the current latest version is from upstream. Where Github is used as the download URL, livecheck can automatically find the version in most cases.

Livecheck is ran as a test when a cask's version is updated to ensure it is being updated to the correct version, and can be run in your terminal to check if a newer version is available.

**Comment by foamzou** [comment]
Thanks @bevanjkay 
I think I know the works of livecheck. So, after I release a new version on github in the future, even if I don’t update the version number of the rb file, can users still update to the latest version through brew update?

**Comment by bevanjkay** [comment]
@foamzou The cask would need to be updated for users to receive the latest version. A PR can be created easily using the `brew bump-cask-pr` command - https://docs.brew.sh/Manpage#bump-cask-pr-options-cask

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
