### PR TITLE
Add Screen v1.0.16

### PR DESCRIPTION
**Pull request by dzhlobo**
https://screen.so

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by dzhlobo** [comment]
I don't understand the CI error 🤔.

Screen Shot 2020-03-25 at 13 36 09

**Comment by jlucktay** [comment]
Looking at [the Travis output](https://travis-ci.com/github/Homebrew/homebrew-cask/jobs/302477356) it seems like `brew cask audit screen` on L322 is the issue, not `uninstall`.

**Comment by dzhlobo** [comment]
I don't mind to rename it. Does it mean that we should never have such duplications between homebrew-cask and homebrew-core? Should we have the same warning when we run `brew cask audit screen` locally?

**Comment by jlucktay** [comment]
> Does it mean that we should never have such duplications between homebrew-cask and homebrew-core?

That seems to be the point of this audit failure, yeah, to not end up with cores and casks having overlapping names.

> Should we have the same warning when we run `brew cask audit screen` locally?

Agree; it absolutely should, yes.

**Comment by jgarber623** [comment]
On the Cask's name, prior art might be [the Zoom Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/zoomus.rb) using the format `zoomus`.

I'd also hastily put together a Cask for this before seeing the PR:

```rb
cask 'screenso' do
  version '1.0.16'
  sha256 '9be3cb84f9e6dad6bb4a8b7a1afb2fac3723542fff4f659491a7cb33b58da759'

  url "https://download.screen.so/desktop-app/darwin/#{version}/Screen.dmg"
  name 'Screen'
  homepage 'https://screen.so'

  app 'Screen.app'

  zap trash: [
    '~/Library/Application Support/Screen',
    '~/Library/Preferences/so.screen.screen.app.plist'
  ]
end
```

**Comment by vitorgalvao** [comment]
> I don't mind to rename it.

We do. Following the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) is paramount to avoid duplicates (huge problem in the past).

> Does it mean that we should never have such duplications between homebrew-cask and homebrew-core?

No.

> That seems to be the point of this audit failure, yeah, to not end up with cores and casks having overlapping names.

The point is that when a collision happens, we’ll be more alert and verify *if it’s the same software* because we don’t want to duplicate efforts. This policy is documented in [faq/rejected_casks](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603), (…)

There are plenty of name overlaps between casks and formulae.

> > Should we have the same warning when we run `brew cask audit screen` locally?
> 
> Agree; it absolutely should, yes.

There’s already a flag to do it, which CI uses. It’s not on by default precisely because we don’t want to encourage wrong renames or dissuade people from contributing.

> On the Cask's name, prior art might be [the Zoom Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/zoomus.rb) using the format `zoomus`.

That’s because *the app bundle* installed by the package is called Zoom.us. That’s also covered in the token reference linked above.

If this were to be renamed due to a conflict with a cask, the correct way to go about it would be to prepped the vendor’s name to the token (again, covered in the reference).

@dzhlobo Since you’ve opened it first, do you want to add the enhancements in https://github.com/Homebrew/homebrew-cask/pull/79400/, or do you prefer I ask @joschi to rename theirs?

@core-code This a good reference: an uncommon case for which we already have rules in place.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/79400#pullrequestreview-383349986, which was already fixed.

Thank you for the contribution.

**Comment by dzhlobo** [comment]
Thank you everyone for quick responses. Glad it's in the repo now ❤️.

**Pull request closed without merging**
