### PR TITLE
istat-menus 7.0.2

### PR DESCRIPTION
**Pull request by jamesdh**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by samford — COMMENTED** [review]
The `livecheck` block was returning the latest 6.x version, as the new download URL is versioned (https://download.bjango.com/istatmenus7/). I pushed a commit to update the `livecheck` block URL accordingly, so that should help this to pass CI.

I also added a commit to create an `istat-menus@6` cask since this is a major version update and we already have a similar `istat-menus@5` cask.

Edit: Updated `depends_on macos` to address the audit error (`Upstream defined :big_sur as the minimum OS version but the cask declared :high_sierra`).

**Review by p-linnane — APPROVED** [review]

**Comment by jamesdh** [comment]
@samford thanks for the help! Maybe an obvious question, but what's required for this change to appear in homebrew? I tried `brew update` but it's still showing the old version. Curious what the workflow/pipeline is for this.

**Comment by p-linnane** [comment]
The API regenerates every 15 minutes. It's working on it now: https://github.com/Homebrew/formulae.brew.sh/actions/workflows/tests.yml

**Comment by jamesdh** [comment]
Thanks @p-linnane!

**Pull request merged**
