### PR TITLE
Update virtualbox to 6.0.0,127566

### PR DESCRIPTION
**Pull request by epsimatic**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by externl** [comment]
```
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
uninstall
21.59s==> brew cask uninstall virtualbox ✘
==> Uninstalling Cask virtualbox
==> Running uninstall process for virtualbox; your password may be necessary
==> Running uninstall script VirtualBox_Uninstall.tool
uninstall script VirtualBox_Uninstall.tool does not exist.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:254:in `uninstall_script'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:60:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:56:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:56:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:429:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:425:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:380:in `uninstall'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd/brewcask-ci.rb:66:in `block (2 levels) in run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd/brewcask-ci.rb:114:in `block (2 levels) in step'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd/lib/capture.rb:13:in `block (2 levels) in capture'
Error: Some applications are still installed, add them to uninstall delete:
/Applications/VirtualBox.app
/Applications/VirtualBox.app/Contents/Resources/VirtualBoxVM.app
/Applications/VirtualBox.app/Contents/Resources/vmstarter.app
Error: Some launch jobs are still installed, add them to uninstall launchctl:
org.virtualbox.startup
Error: Build failed.
```

**Comment by RobberPhex** [comment]
@externl 
After `brew cask reinstall ./Casks/virtualbox.rb`, I tried `brew cask uninstall ./Casks/virtualbox.rb`, it did works for me.

**Comment by externl** [comment]
@RobberPhex I just copied from Travis CI.

**Comment by epsimatic** [comment]
Need to say this cask installed for me just fine. Didn't try to uninstall though.

I *guess, maybe* uninstall script needs some changes on this new major version. Or not. Or it's just some weirdness with Virtualbox itself.

Maybe it needs a reboot after (un-)install

**Comment by externl** [comment]
It sounds like VBox 6 does not ship with the `VirtualBox_Uninstall.tool` script anymore

**Comment by epsimatic** [comment]
It's still here:

```
➜ ls -la /usr/local/Caskroom/virtualbox/6.0.0,127566
drwxr-xr-x 5 decker       160 дек 19 01:32 .
drwxr-xr-x 4 decker       128 дек 19 01:32 ..
-rwxr-xr-x 1 decker   3744294 дек 18 17:38 UserManual.pdf
-rw-r--r-- 1 decker 155171864 дек 18 17:38 VirtualBox.pkg
-rwxr-xr-x 1 decker     13356 дек 18 17:38 VirtualBox_Uninstall.tool
```

**Comment by externl** [comment]
Yeah, you're right. Weird. Ship it!?

**Comment by epsimatic** [comment]
Also, when I try to remove it:

```
➜ brew cask rm --force virtualbox
==> Uninstalling Cask virtualbox
==> Running uninstall process for virtualbox; your password may be necessary
==> Running uninstall script VirtualBox_Uninstall.tool
Password:

Welcome to the VirtualBox uninstaller script.

The following files and directories (bundles) will be removed:
    /Users/decker/Library/LaunchAgents/org.virtualbox.vboxwebsrv.plist
    /usr/local/bin/VirtualBox
    /usr/local/bin/VBoxManage
    /usr/local/bin/VBoxVRDP
    /usr/local/bin/VBoxHeadless
    /usr/local/bin/vboxwebsrv
    /usr/local/bin/VBoxBugReport
    /usr/local/bin/VBoxBalloonCtrl
    /usr/local/bin/VBoxAutostart
    /usr/local/bin/VBoxDTrace
    /usr/local/bin/vbox-img
    /Library/LaunchDaemons/org.virtualbox.startup.plist
    /Library/Python/2.7/site-packages/vboxapi/VirtualBox_constants.py
    /Library/Python/2.7/site-packages/vboxapi/VirtualBox_constants.pyc
    /Library/Python/2.7/site-packages/vboxapi/__init__.py
    /Library/Python/2.7/site-packages/vboxapi/__init__.pyc
    /Library/Python/2.7/site-packages/vboxapi-1.0-py2.7.egg-info
    /Library/Application Support/VirtualBox/LaunchDaemons/
    /Library/Application Support/VirtualBox/VBoxDrv.kext/
    /Library/Application Support/VirtualBox/VBoxUSB.kext/
    /Library/Application Support/VirtualBox/VBoxNetFlt.kext/
    /Library/Application Support/VirtualBox/VBoxNetAdp.kext/
    /Applications/VirtualBox.app/
    /Library/Python/2.7/site-packages/vboxapi/

And the following KEXTs will be unloaded:
    org.virtualbox.kext.VBoxUSB
    org.virtualbox.kext.VBoxNetFlt
    org.virtualbox.kext.VBoxNetAdp
    org.virtualbox.kext.VBoxDrv

And the traces of following packages will be removed:
    org.virtualbox.pkg.vboxkexts
    org.virtualbox.pkg.virtualbox
    org.virtualbox.pkg.virtualboxcli

The uninstallation processes requires administrative privileges
because some of the installed files cannot be removed by a normal
user. You may be prompted for your password now...

unloading org.virtualbox.kext.VBoxUSB
unloading org.virtualbox.kext.VBoxNetFlt
unloading org.virtualbox.kext.VBoxNetAdp
unloading org.virtualbox.kext.VBoxDrv
Successfully unloaded VirtualBox kernel extensions.
Forgot package 'org.virtualbox.pkg.vboxkexts' on '/'.
Forgot package 'org.virtualbox.pkg.virtualbox' on '/'.
Forgot package 'org.virtualbox.pkg.virtualboxcli' on '/'.
Done.
==> Uninstalling packages:
==> Purging files for version 6.0.0,127566 of Cask virtualbox
1,06s user 1,09s system 23% cpu 9,298s total
```

**Comment by externl** [comment]
Can we make travis run it again? Or can a maintainer just merge it?

**Comment by epsimatic** [comment]
Running again won't help, because all the duplicate requests trigger the same error, so it looks reproducible.

If you're asking me, I have no idea if it's safe to ship to everybody, and my voice doesn't mean much here.

Works for me. It *might* be some issue with CI triggered by this cask / binary installer, or with the binary installer itself.  

*Feci quod potui, faciant meliora potentes*

**Comment by epsimatic** [comment]
Related to #56316, should be merged together because they need the same versions of each other

**Comment by reitermarkus** [comment]
Virtualbox always fails on Travis, because it needs kext consent.

**Comment by timsutton** [comment]
Does Travis CI offer a config with SIP disabled? If so it's probably possible to automate the kext consent via manipulation of the sqlite db.

**Pull request merged**
