### PR TITLE
Update stattransfer to 14

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
its up to version 14.1 now but they update it in-place

**Comment by reitermarkus** [comment]
Since there is no appcast, this should be `latest`.

**Comment by reitermarkus** [comment]
> It needs a version for the pkg install.

I don't think that should be a reason to use `version`. There is no `appcast` and the `url` is unversioned.

**Comment by vitorgalvao** [comment]
> > It needs a version for the pkg install.
> 
> I don't think that should be a reason to use `version`.

We have precedent. Other casks in this situation have it like this one is.

**Pull request merged**
