### PR TITLE
Remove apps behing registration wall

### PR DESCRIPTION
**Pull request by vitorgalvao**
Pending discussion in https://github.com/caskroom/homebrew-cask/issues/8664.

### CODE REVIEW

**Comment by rolandwalker** [comment]
You are right that mismatched domains are more of a problem.  We can't easily check them, though I see that we may have in the past, because of the download-domain comment.

The thought that these are unverified AWS urls makes me uncomfortable.  I'd rather merge now and discuss later.  Assuming that you are boneyarding these & that we can bring them back if verified.

**Comment by vitorgalvao** [comment]
`radbeacon` and `titanium-desktop` were verified today by me. They are (currently) official. `gamesalad` is weird in the sense that what I got when trying to download it was `0.12 (beta)` with the url starting as `gs.releases.x.s3`) while we currently have `0.14 (beta)` (with url starting as `gs.releases.s3`, not the missing `.x`). It was [added by @alebcay](https://github.com/caskroom/homebrew-cask/pull/2960), though, which is why I didn’t worry much, and was intending to pose the question later.

**Comment by rolandwalker** [comment]
Ah.  Sorry I jumped the gun, thought I was being prudent.

**Comment by rolandwalker** [comment]
Argh.  I reverted, but then this can't be reopened.

**Comment by vitorgalvao** [comment]
Not to worry; easily recreated as #8681.

**Pull request merged**
