### PR TITLE
Update sha in lrtimelapse 5.5.0

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by suschizu** [comment]
developer talks about a version 5.5.1_b1 on the website - but it doesn't exist (https://lrtimelapse.com/download/)

**Comment by reitermarkus** [comment]
Seems to exist now.

**Review by reitermarkus — APPROVED** [review]

**Comment by suschizu** [comment]
@reitermarkus - the download still contains 5.5.0 and the download token just contains version.major so I perhaps it's a bit confusing using this 5.5.1_b1 version here (?)

**Comment by reitermarkus** [comment]
Hmm, I think I actually downloaded from an URL with the full version to check.

**Comment by reitermarkus** [comment]
Oh, that was the file name I remembered: `LRTimelapse5.5.1_b1.mac.dmg`

So it seems correct.

**Pull request merged**
