### PR TITLE
Update duet from 2.3.3.2 to 2.3.3.3

### PR DESCRIPTION
**Pull request by jabenninghoff**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by jabenninghoff** [comment]
According to MacUpdater, duet 2.3.3.3 is currently being rolled out in a staged fashion - livecheck does return 2.3.3.3 on my system, but apparently not globally.

**Review by Rylan12 — DISMISSED** [review]
`https://updates.duetdisplay.com/latestMac` still points to `2.3.3.2` for me as well (hence the live check failure).

```console
❯ curl -I https://updates.duetdisplay.com/latestMac
HTTP/1.1 302 Found
Server: Cowboy
Date: Sat, 08 May 2021 14:34:26 GMT
Connection: keep-alive
X-Frame-Options:
Location: https://duet.nyc3.cdn.digitaloceanspaces.com/Mac/2_3/duet-2-3-3-2.zip
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
X-Request-Id: d67a9b79-e6ba-46e5-9cad-cd7c26c67245
X-Runtime: 0.059711
Via: 1.1 vegur
```

And downloading the file at that URL redirects to the `2.3.3.2` version (with the same checksum).

Edit: ah, I see your second comment. Let me see what other maintainers think should be done.

**Comment by Rylan12** [comment]
Once our CI is able to detect the newer version this can be merged.

**Comment by cho-m** [comment]
Depending on timing of CI, it may end up passing.
For me, the `livecheck` URL shows both 2.3.3.2 and 2.3.3.3 when run back-to-back:
```console
❯ curl https://updates.duetdisplay.com/latestMac
<html><body>You are being <a href="https://duet.nyc3.cdn.digitaloceanspaces.com/Mac/2_3/duet-2-3-3-2.zip">redirected</a>.</body></html>%

❯ curl https://updates.duetdisplay.com/latestMac
<html><body>You are being <a href="https://duet.nyc3.cdn.digitaloceanspaces.com/Mac/2_3/duet-2-3-3-3.zip">redirected</a>.</body></html>%

❯ curl https://updates.duetdisplay.com/latestMac
<html><body>You are being <a href="https://duet.nyc3.cdn.digitaloceanspaces.com/Mac/2_3/duet-2-3-3-3.zip">redirected</a>.</body></html>%

❯ curl https://updates.duetdisplay.com/latestMac
<html><body>You are being <a href="https://duet.nyc3.cdn.digitaloceanspaces.com/Mac/2_3/duet-2-3-3-2.zip">redirected</a>.</body></html>%
```

Can either retry a few more times, or just wait until upstream sets single redirect.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
