### PR TITLE
Fix sha256 checksum for MAMP 4.4

### PR DESCRIPTION
**Pull request by lead0r**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by lead0r** [comment]
The correct checksum can be found at the developer's website: https://www.mamp.info/en/downloads/

The file is too big to upload it to VirusTotal and I do not know if it works with .pkg files

**Review by commitay — APPROVED** [review]
Matches public `sha256`
https://www.mamp.info/en/downloads/
```
MAMP & MAMP PRO 4.4 (macOS)
Published: 2018-02-07
SHA-256: 9a86de2f1321851693bbf24f96c0aaca29fe7fb4d9b3c887aa464d41c36eed9c
```

**Comment by vitorgalvao** [comment]
I’m not sure that in this case we can trust the public shasum without contacting the developer.

Both the download and the page with the shasum are on the same domain, and presumably on the same server. A malicious third-party that tampers with the first can easily tamper with the second (it’s just a tiny string of characters in an HTML page).

**Comment by lead0r** [comment]
@vitorgalvao I agree with you, and even with the new checksum I got the following error: https://github.com/caskroom/homebrew-cask/issues/43859

**Pull request merged**
