### PR TITLE
Update metasploit from 6.1.25,20220112112908 to 6.1.25,20220113112934

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
@miccal Does your [comment](https://github.com/Homebrew/homebrew-cask/pull/99341#issuecomment-773684726) on the bump frequency of constantly out of date casks still apply? Metasploit seems to be updated almost daily at the moment.

**Comment by miccal** [comment]
> @miccal Does your [comment](https://github.com/Homebrew/homebrew-cask/pull/99341#issuecomment-773684726) on the bump frequency of constantly out of date casks still apply? Metasploit seems to be updated almost daily at the moment.

@neutric ideally yes -- @Porkepix please try to limit the bumping of Casks that have frequent releases -- generally a weekly version bump is enough.

**Comment by neutric** [comment]
As indicated by https://osx.metasploit.com/, bumping weekly might be cutting it close as they are expiring previous version's URLs rather quickly. The last dozen or so were good for a bit more than 7d. Not sure if they have a time-based trigger or doing last-n-versions.

**Comment by carlocab** [comment]
We could just do
```ruby
version :latest
```
here and link to https://osx.metasploit.com/metasploitframework-latest.pkg

**Comment by neutric** [comment]
@carlocab True.

https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers says

> Installers are built nightly for macOS

and

> the last 10 builds archived at https://osx.metasploit.com/

That number seems to be 8 now.

```
==> Analytics
install: 627 (30 days), 1,593 (90 days), 5,766 (365 days)
```

This might help decide whether bumping once a week in order to preserve version information and checksums is worth it.

https://formulae.brew.sh/analytics/ says these are "cask install events". Those are fresh installs, or is upgrading an outdated cask also counted in that number?

**Pull request merged**
