### PR TITLE
Update signal to 1.23.1

### PR DESCRIPTION
**Pull request by ahousseini**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
these damaged zip files are becoming more common. i had the idea of fixing them in a 'preflight' stanza (search for 0x06054b50 and remove the additional bytes), but it seems 'preflight' is run after decompression...

**Comment by vitorgalvao** [comment]
@core-code Maybe switching to something other than `unzip` (like `ditto`) will work.

**Comment by core-code** [comment]
@vitorgalvao i can confirm that using 'ditto -xk' to extract 'signal-desktop-mac-1.23.1.zip' works and produces a launchable app that is bit-for-bit identical with the one that the macOS GUI unarchiver produces.

**Comment by vitorgalvao** [comment]
@reitermarkus How about changing the unzipping strategy to use `ditto`? What stops us, if anything?

**Comment by reitermarkus** [comment]
The problem is some things fail with `ditto` and some fail with `unzip`. We already use `ditto` as a fallback for a specific type of error.

**Comment by core-code** [comment]
it seems upstream doesn't want to fix this, so we need a solution or a workaround in HBC.

i propose a workaround by adding
  
```
container type: :naked
…
preflight do
	    system_command '/usr/bin/ditto', args: ['-xk', staged_path.join(filename), staged_path]
end
```

see  #61140 for my try to get signal working this way.

**Comment by vitorgalvao** [comment]
> it seems upstream doesn't want to fix this, so we need a solution or a workaround in HBC.

https://github.com/Homebrew/brew/pull/5954

**Comment by core-code** [comment]
sorry didn't see that a real solution was already in-progress

**Pull request merged**
