### PR TITLE
added qucs-s@nightly.rb (new-cask)

### PR DESCRIPTION
**Pull request by dsm**
Hi, this PR added qucs-s-nightly to brew, thanks.

### CODE REVIEW

**Comment by khipp** [comment]
Thank you for your submission @dsm! Unfortunately, since the binaries are not signed and notarized, the application does not yet meet the requirements for inclusion in `Homebrew/homebrew-cask`:
> macOS on ARM requires software to be signed.
> Please contact the upstream developer to let them know they should sign and notarize their software.

Feel free to re-submit your PR once the binaries are signed, and consider [hosting the application in your own tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) in the meantime.

Hint: You can fix style-related issues automatically by running `brew style --fix qucs-s@nightly.rb`.

**Comment by dsm** [comment]
I don't think anybody on the dev team can afford the apple developer fee but thanks to hint.

**Comment by khipp** [comment]
@dsm Then you still have the option to create your own tap (see link above). Users adding your tap can install the cask like any other included in `Homebrew/homebrew-cask`.

Here is an [example repository](https://github.com/bevanjkay/homebrew-tap) by one of our maintainers.

**Comment by dsm** [comment]
Thanks we try this method

**Pull request closed without merging**
