### PR TITLE
figma@beta: migrate from `homebrew/cask-versions`

### PR DESCRIPTION
**Pull request by cho-m**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

Experimenting https://github.com/Homebrew/homebrew-cask-versions/issues/19665

Simpler one as no conflicts to modify

### CODE REVIEW

**Review by razvanazamfirei — APPROVED** [review]
Approving both this and https://github.com/Homebrew/homebrew-cask-versions/pull/20185. Feel free to merge whenever ready.

**Review by reitermarkus — APPROVED** [review]

**Comment by reitermarkus** [comment]
I'd say let's merge and then check if the following works:

- With taps reset to old commits:
  - `brew install homebrew/cask-versions/figma-beta`
  - `brew update` (should migrate to the new name)

- With taps reset to old commits:
  - `brew install homebrew/cask-versions/figma-beta`
  - `brew update-reset`
  - `brew migrate figma-beta`

- With and without API:
  - `brew install figma-beta` (should show migration warning)
  - `brew install homebrew/cask-versions/figma-beta` (should show migration warning)
  - `brew install homebrew/cask-versions/figma@beta` (should fail)
  - `brew install figma@beta` (should not show migration warning)
  - `brew install homebrew/cask/figma@beta` (should not show migration warning)
  - `brew install homebrew/cask/figma-beta` (should fail)

**Comment by cho-m** [comment]
I had `figma-beta` installed for testing. After merge, via repo tap:
```console
❯ brew update
==> Updating Homebrew...
==> Updated Homebrew from 0bb104d6e1 to 5e027bffd6.
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> New Casks
figma@beta
==> Deleted Installed Casks
figma-beta ✘
==> Migrating cask figma-beta to figma@beta
```

**Comment by cho-m** [comment]
> * With and without API:
>   
>   ...
>   * [ ]  `brew install homebrew/cask-versions/figma-beta` (should show migration warning)

This doesn't show a migration warning. Probably not a blocker as essential behavior seems to work.

**Pull request merged**
