### PR TITLE
Created roblox.rb

### PR DESCRIPTION
**Pull request by chobotnice007**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
@chobotnice007 please run the commands in the issue template for adding a new Cask to fix all of the `audit` and `style` errors.

**Comment by ran-dall** [comment]
@chobotnice007 @miccal Just an FYI, Roblox was removed from `cask` a while ago because their installer doesn't work when it is install with `brew`. So unless something has changed (which it doesn't seem like when I ran this `pr`), this shouldn't be merged.

**Comment by miccal** [comment]
Thanks @ran-dall, closing after looking at the previous PR's for this Cask.

**Comment by chobotnice007** [comment]
> @chobotnice007 @miccal Just an FYI, `Roblox` was removed from `cask` a while ago because their installer doesn't work when it is install with `brew`. So unless something has changed (which it doesn't seem like when I ran this `pr`), this shouldn't be merged.

Why it doesn't work? It only download zip, extract it and copy Roblox.app to Applications folder.

**Pull request closed without merging**
