### PR TITLE
Update youdaonote from 3.6.2 to 3.6.3

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by ran-dall** [comment]
This is a downgrade but it's showing `3.6.3` on the `appcast`

**Comment by core-code** [comment]
if the SHA didn't change, we shouldn't change the version either. it definitely does not contain version 3.6.3 regardless of what the appcast says

**Comment by core-code** [comment]
```
svs: 3.6.2
bv: 6371
```

**Comment by ran-dall** [comment]
@core-code Great, can we do something about flagging this for the MLv1? Also `wordpresscom` has a similar problem.

**Comment by core-code** [comment]
i think it  just needs to add this specific version  to the 'fp.cask.appcastcontains.blacklist' file so it doesn't show up anymore. 

@suschizu can you do that? similar for `wordpresscom`?

**Comment by ran-dall** [comment]
Maybe said blacklist can reset every 30 days or something?

**Comment by core-code** [comment]
the idea there is that by only putting specific versions on it, it kind of has a reset anyway. but i agree that basically most lists ideally need some reset or expiration

**Pull request closed without merging**
