### PR TITLE
Add Scrub.app v1.0b2

### PR DESCRIPTION
**Pull request by themediapot**
After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by sticklerm3** [comment]
I'm currently working on a [private tap](https://github.com/sticklerm3/homebrew-pourhouse) of casks specifically for apps found at EclecticLight if your particular formula doesn't cut it here, or you wanna use someone else's work :)

**Comment by themediapot** [comment]
That’s awesome!

Happy to use your work mate :)

Can I ask though why have you decided to have a private tap rather than committing these to homebrew core?

Thanks.

Regards,
Kevin


 

On 16 February 2019 at 1:27:46 pm, Matt (notifications@github.com) wrote:

I'm currently working on a private tap of casks specifically for apps found at EclecticLight if your particular formula doesn't cut it here, or you wanna use someone else's work :)

**Comment by sticklerm3** [comment]
body {
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	padding:1em;
	margin:auto;
	background:#fefefe;
}

h1, h2, h3, h4, h5, h6 {
	font-weight: bold;
}

h1 {
	color: #000000;
	font-size: 28pt;
}

h2 {
	border-bottom: 1px solid #CCCCCC;
	color: #000000;
	font-size: 24px;
}

h3 {
	font-size: 18px;
}

h4 {
	font-size: 16px;
}

h5 {
	font-size: 14px;
}

h6 {
	color: #777777;
	background-color: inherit;
	font-size: 14px;
}

hr {
	height: 0.2em;
	border: 0;
	color: #CCCCCC;
	background-color: #CCCCCC;
    display: inherit;
}

p, blockquote, ul, ol, dl, li, table, pre {
	margin: 15px 0;
}

a, a:visited {
	color: #4183C4;
	background-color: inherit;
	text-decoration: none;
}

#message {
	border-radius: 6px;
	border: 1px solid #ccc;
	display:block;
	width:100%;
	height:60px;
	margin:6px 0px;
}

button, #ws {
	font-size: 12 pt;
	padding: 4px 6px;
	border-radius: 5px;
	border: 1px solid #bbb;
	background-color: #eee;
}

code, pre, #ws, #message {
	font-family: Monaco;
	font-size: 10pt;
	border-radius: 3px;
	background-color: #F8F8F8;
	color: inherit;
}

code {
	border: 1px solid #EAEAEA;
	margin: 0 2px;
	padding: 0 5px;
}

pre {
	border: 1px solid #CCCCCC;
	overflow: auto;
	padding: 4px 8px;
}

pre > code {
	border: 0;
	margin: 0;
	padding: 0;
}

#ws { background-color: #f8f8f8; }


.bloop_markdown table {
border-collapse: collapse;  
font-family: Helvetica, arial, freesans, clean, sans-serif;  
color: rgb(51, 51, 51);  
font-size: 15px; line-height: 25px;
padding: 0; }

.bloop_markdown table tr {
border-top: 1px solid #cccccc;
background-color: white;
margin: 0;
padding: 0; }
     
.bloop_markdown table tr:nth-child(2n) {
background-color: #f8f8f8; }

.bloop_markdown table tr th {
font-weight: bold;
border: 1px solid #cccccc;
margin: 0;
padding: 6px 13px; }

.bloop_markdown table tr td {
border: 1px solid #cccccc;
margin: 0;
padding: 6px 13px; }

.bloop_markdown table tr th :first-child, table tr td :first-child {
margin-top: 0; }

.bloop_markdown table tr th :last-child, table tr td :last-child {
margin-bottom: 0; }

.bloop_markdown blockquote{
  border-left: 4px solid #dddddd;
  padding: 0 15px;
  color: #777777; }
  blockquote > :first-child {
    margin-top: 0; }
  blockquote > :last-child {
    margin-bottom: 0; }

code, pre, #ws, #message {
    word-break: normal;
    word-wrap: normal;
}

hr {
    display: inherit;
}

.bloop_markdown :first-child {
    -webkit-margin-before: 0;
}

code, pre, #ws, #message {
    font-family: Menlo, Consolas, Liberation Mono, Courier, monospace;
}


.send { color:#77bb77; }
.server { color:#7799bb; }
.error { color:#AA0000; }Frankly, eventually I was going to submit a few… I just figured some wouldnt qualify either though as theyre in beta according to their version number, lack of pages for individual apps and so on! 

body{font-family:Space Mono,Arial;font-size:13px}  Matthew | SticklerSticklerm3@me.com On February 16, 2019 at 12:15:13 AM, Kevin Lee (notifications@github.com) wrote: 





That’s awesome!

Happy to use your work mate :)

Can I ask though why have you decided to have a private tap rather
than committing these to homebrew core?

Thanks.

Regards,
Kevin


 

On 16 February 2019 at 1:27:46 pm, Matt (notifications@github.com)
wrote:

I'm currently working on a private tap of casks specifically for
apps found at EclecticLight if your particular formula doesn't cut
it here, or you wanna use someone else's work :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the
thread.
—
You are receiving this because you commented.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by vitorgalvao** [comment]
> I just figured some wouldnt qualify either though as theyre in beta according to their version number

[They wouldn’t be refused because of that](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

But if you have a repo for eclecticlight casks, I’d rather defer those to you. We only have one other app by them which isn’t very popular, so I’ll refuse this one with the [not notable enough rule](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars)).

Thank you anyway, @themediapot, even though I will ask that next time you follow the PR template.

@sticklerm3 If you reply to this, please do so on the web interface, as your email reply was full of CSS rules.

**Pull request closed without merging**
