### PR TITLE
trezor-suite 24.6.1

### PR DESCRIPTION
**Pull request by nekofar**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by nekofar** [comment]
Looks like a new version dropped a couple of days ago, but since it's not marked as the latest, livecheck isn't picking it up.

https://github.com/trezor/trezor-suite/releases/tag/v24.6.1

**Comment by krehel** [comment]
It is probably worthwhile to ask upstream to mark it as latest, and determine if there is a reason why not.  Do you mind doing that?

There are many pre-releases listed so I don't think we want to change the GitHub strategy unless there's a strong reason to begin accepting all releases and move off current state.

**Comment by nekofar** [comment]
Got it, I'll ask upstream to mark v24.6.1 as the latest and check if there's a reason it hasn't been done.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
