### PR TITLE
Add Apogee Duet

### PR DESCRIPTION
**Pull request by nerab**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by nerab** [comment]
Done

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as b75039454fd4c534548c1c0a373c1af9e8cb5d18 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by nerab** [comment]
Thank you!

**Pull request closed without merging**
