### PR TITLE
Analytics cask purge

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Review by suschizu — COMMENTED** [review]
@vitorgalvao - this cask is part of the 'dcpomatic' family - could we perhaps keep it? Thanks :)
`dcp-o-matic-kdm-creator: removed for too few downloads`

**Comment by vitorgalvao** [comment]
@suschizu Sure. Submit a PR?

**Comment by suschizu** [comment]
great - is it possible to revert a delete?

**Comment by vitorgalvao** [comment]
I think the revert needs to be done on the whole PR, so in this case it’s a matter of copying the code and readding the file.

**Comment by suschizu** [comment]
ok - I'll do it 👍

**Comment by winkelsdorf** [comment]
@vitorgalvao Same here, I recently reinstalled and notices `Instasizer` and `yabumi` were removed, which are quite useful for me. May I re-add them with PRs?

**Comment by vitorgalvao** [comment]
> May I re-add them with PRs?

Yes.

**Comment by winkelsdorf** [comment]
Ok, thanks 👍

**Pull request merged**
