### PR TITLE
Update fl-studio to 20.1.0.161

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
Travis 🤷‍♂️

**Comment by ran-dall** [comment]
@vitorgalvao It's there, pal; so I don't really know why it's thorwing that error. 😊

screen shot 2018-12-15 at 10 41 45 am
screen shot 2018-12-15 at 10 41 41 am

**Comment by vitorgalvao** [comment]
Tip: it’s not the problem here (problem is that it’s downloading the HTML page), but when checking for this, throw the package into a Terminal, to see it’s name. The name for something may be different in the Terminal and in the Finder (localisation strings, and whatnot).

**Comment by ran-dall** [comment]
@vitorgalvao Can `cask-repair` have those types of mess-ups? Maybe it has something to do with the `user agent: :fake`, I haven't seen that before. Would you also mind pointing me somewhere were I could read more about that?

**Comment by vitorgalvao** [comment]
> Can `cask-repair` have those types of mess-ups?

There’s no mess up. `cask-repair` uses `brew cask` commands to do its thing. If it can’t download something, than neither can `brew cask`.

> Would you also mind pointing me somewhere were I could read more about that?

https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#additional-https-url-parameters

**Pull request merged**
