### PR TITLE
Update icollections from 6.6,66012 to 6.7,67008

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
this is another bogus update. can you disable any PR that only updates the version number but not the SHA? they seem to be always wrong

**Comment by core-code** [comment]
@vitorgalvao is there any way to make travis not auto-merge these?

**Comment by vitorgalvao** [comment]
> is there any way to make travis not auto-merge these?

Haven’t looked into it, but it should be on [the review action](https://github.com/Homebrew/actions/blob/master/review-cask-pr/review.rb).

**Comment by reitermarkus** [comment]
> they seem to be always wrong

All of them, or just the ones where the URL is unversioned?

**Comment by core-code** [comment]
> All of them, or just the ones where the URL is unversioned?

i've had a look at the last few cases where the problem happened, it was in 

```
macx-dvd-ripper-pro
naver-whale
nvidia-geforce-now
```

the first two are static downloads just like `icollections` but `nvidia-geforce-now` is not - and with this cask the problem even happened twice in the last 30 days.

so i'd prefer if 'version number only' updates would never get automerged - regardless of the URL being versioned or not.

i guess this should only apply to casks that actually have a SHA though.

**Pull request merged**
