### PR TITLE
Update java

### PR DESCRIPTION
**Pull request by lemeb**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by lemeb** [comment]
resolves #62503

**Comment by vitorgalvao** [comment]
Thank you for the fast turnaround and fixes, @lemeb!

Unfortunately, they were a bit too fast and need some modifications, pointed out in the other PRs. Specifically, they need either an upstream fix (preferred), or a new homepage that directly links to the download URL. As it is, the comment above `url` is not accurate to its rules, and we need to take that seriously, as it’s a security measure.

Thank you again. I’ll close this PR, but another one that fixes the problem with the requested solution is acceptable.

**Review by vitorgalvao — APPROVED** [review]

**Comment by vitorgalvao** [comment]
Working now. Thank you again for the fast turnaround.

If you find a homepage for the beta, we can (re)change that cask. Virtualbox will be trickier.

**Comment by lemeb** [comment]
thanks for everything, @vitorgalvao! didn’t want to break the standards of cask in any way :)

It’s very puzzling to see oracle do such a change on a saturday morning... especially since the normal webpage didn’t direct to the right url either.

**Pull request merged**
