### PR TITLE
Add Centered.app v3.3.1

### PR DESCRIPTION
**Pull request by rpowis**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by rpowis** [comment]
Haha. That's how I had it initially but thought I'd make it more dynamic 🤦 Thanks @miccal

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @rpowis.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by rpowis** [comment]
Sure thing

**Comment by neutric** [comment]
```
zap trash: [
  "~/Library/Application Support/Centered",
  "~/Library/Preferences/app.centered.mac.prod.plist",
  "~/Library/Saved Application State/app.centered.mac.prod.savedState",
]
```

**Comment by rpowis** [comment]
thanks @neutric !! i had that ready to push (except for the path for `Saved Application State`) and got distracted. then forgot 🤦 thanks for the nudge!

**Comment by rpowis** [comment]
Gah! They released a new version over the weekend 😂 Bumped and pushed

**Comment by rpowis** [comment]
Of course, that means the SHA changed. Doing too many things at once!

**Comment by neutric** [comment]
All good, take your time! Commits are free of charge today! ;)

**Comment by rpowis** [comment]
Haha. Ok, 5th time's a charm! 🤞

**Comment by rpowis** [comment]
Ayyyyy 💪

**Comment by miccal** [comment]
Thank you @rpowis.

**Pull request merged**
