### PR TITLE
updated bettertouchtool (1.5b)

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Comment by TheoBr** [comment]
Is it preferred to use the official BetterTouchTool.com download source, as it is https?

**Comment by vitorgalvao** [comment]
We prefer it to be versioned (there’s still some modicum of security in checking its checksum). But more importantly, it is available from the appcast.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as d989a85ca4077ec99f546db62c502771a9d952a2 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by TheoBr** [comment]
Thank you for the clarification @vitorgalvao

**Pull request closed without merging**
