### PR TITLE
added DCP-o-matic 2 Apps Version 2.12.6

### PR DESCRIPTION
**Pull request by DerMolly**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
Please submit these as separate PRs.

They need to be changed to follow the [token_reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md) and the caveats need to be removed.

**Comment by DerUser** [comment]
the cask really should be named `dcp-o-matic`  `dcp-o-matic2-batch-converter` etc.?
This seems overly complicted and inconsistent in it self.

Why should the caveats be removed? You normally can't download these Applications without the seeing a donation page. So I thought it would only be fitting to put that in the cask.

**Comment by commitay** [comment]
> the cask really should be named dcp-o-matic dcp-o-matic2-batch-converter etc.?

Yes, also the version number should not be in the cask name.

> Why should the caveats be removed? 

https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md
> caveats should be used sparingly and exclusively for installation-related matters

**Comment by DerUser** [comment]
> Yes, also the version number should not be in the cask name.
Okay. So I should manually change the generate_cask_token output?

**Pull request closed without merging**
