### PR TITLE
Add Goofy.app latest version.

### PR DESCRIPTION
**Pull request by vinkla**
Never lose your chat window among all the other open browser windows and get notified about new messages http://www.goofyapp.com/

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you as usual. Will be merged in #8914 due to small note pointing out the download host is officially different from the project’s home. Your contribution is still included (and still credited to you), as expected.

**Comment by vinkla** [comment]
Thanks. So this is required when the download host and the project's home are different? Just want to know for future PRs.

**Comment by vitorgalvao** [comment]
Yes. A maintainer will always have to confirm it, but adding the comment there when submitting is perfectly acceptable.

There are likely many casks missing the warning, from before we implemented the rule, but those should be found and corrected.

**Comment by vinkla** [comment]
Okay. Then I know. That would be a great feature when running the audit test. Like `homepage and url match: true` or something similar. Though, people might get confused when creating new casks trying to find out why the urls differs.

**Pull request closed without merging**
