### PR TITLE
segger-jlink: update the sha256

### PR DESCRIPTION
**Pull request by quad**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Hi, @quad! Thank you for opening this. When I'm downloading this file, I still have the old checksum. How did you find this new checksum?

**Comment by quad** [comment]
I wonder if something is up with their side. I've downloaded multiple times and got a different shasum irregularly. 😕

**Comment by razvanazamfirei** [comment]
Were you downloading with `brew fetch` or just `curl https://www.segger.com/downloads/jlink/JLink_MacOSX_V788b_universal.pkg`?

The link has a license page. We have to use a post request to get around it.

**Comment by quad** [comment]
brew fetch! I had to delete the cache to get brew to progress.

**Comment by razvanazamfirei** [comment]
Hi @quad! We're getting the old checksum, both locally and on CI. Closing this for now, but if at any point in the future it changes please let us know!

**Pull request closed without merging**
