### PR TITLE
Update skype from 8.48.0.51 to 8.49.0.49

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
their update-check config file is notoriously lagging the download from the homepage

i wonder if we should use this instead
`
https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://go.skype.com/skype.download&user_agent=Mozilla/5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_14_4)`

**Comment by vitorgalvao** [comment]
Seems to be up-to-date now.

**Comment by core-code** [comment]
if its just a day behind i don’t think there is much point in changing the appcast

**Comment by vitorgalvao** [comment]
Especially since the build will always fail anyway (`string contains null byte`).

**Pull request merged**
