### PR TITLE
Update pacifist from 3.6.2,29642 to 4.0,65083

### PR DESCRIPTION
**Pull request by robertleeblairjr**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
The Quick Look Plugin is now handled automatically via `Pacifist.app/Contents/PlugIns/Pacifist\ QuickLook\ Extension.appex`.

**Comment by justinkb** [comment]
this major version update requires a new license, is pacifist 3 anywhere in some versions cask repo?

**Comment by miccal** [comment]
@justinkb feel free to open a PR for `pacifist3` in the [`homebrew-cask-versions`](https://github.com/Homebrew/homebrew-cask-versions) repository.

**Comment by justinkb** [comment]
Thanks for pointing me to that. For some reason I couldn't find the exact repo

**Pull request merged**
