### PR TITLE
Update hubstaff from 1.4.10,1235 to 1.4.11,1268

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> Error: It seems the App source '/usr/local/Caskroom/hubstaff/1.4.11,1300/Hubstaff.app' is not there.

**Comment by ran-dall** [comment]
@vitorgalvao I think it's there...or am I missing something?
Screen Shot 2019-09-17 at 11 24 39 AM

**Comment by vitorgalvao** [comment]
> I think it's there...or am I missing something?

Throw it in a Terminal. Sometimes they localise the app bundle and the name we see in the Finder is not the real name.

**Comment by ran-dall** [comment]
@vitorgalvao When I dragged it I got `/Volumes/Hubstaff/Hubstaff.app` so I updated to `Hubstaff/Hubstaff.app` but it still can't find it...

**Comment by vitorgalvao** [comment]
Is the `fetch` working for you? `curl`ing the new URL is downloading an `.exe` for me.

**Comment by ran-dall** [comment]
**So when I `fetch` from master; I get...**
```bash
$ brew cask fetch hubstaff

==> Downloading external files for Cask hubstaff
==> Downloading https://app.hubstaff.com/download/1235-mac-os-x-1-4-10-release
==> Downloading from https://app.hubstaff.com/download
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'hubstaff'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'hubstaff' does not match.
Expected: de6b22f850df6c8e306e78f12d289df6d0de5a1232a1d484f331e5290bd54b15
  Actual: ab1279ba178a970091551d510918b8f8884ebe4d931aca890e4f6eabbd4919a1
    File: /Users/draque/Library/Caches/Homebrew/downloads/8b2381c016d240ad0717e83da2761a65c1c2d7d2bc56802d03c074da7648f8c0--download
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
```

---
When I fetch from this branch, I also get the `.exe`...
```
==> Downloading external files for Cask hubstaff
==> Downloading https://app.hubstaff.com/download/1300-mac-os-x-1-4-11-release
==> Downloading from https://hubstaff-production.s3.amazonaws.com/downloads/HubstaffClient/Builds/Release/1.4.11-a12e5bad/Hubstaff-1.4.11-a12e5bad.exe
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'hubstaff'.
==> Success! Downloaded to -> /Users/draque/Library/Caches/Homebrew/downloads/93901f288b0d1d32909c3fcf86dfa209c8eb0de7a9110d08c489d245e5131326--Hubstaff-1.4.11-a12e5bad.exe
```
---
When I `curl -O https://app.hubstaff.com/download/1268-mac-os-x-1-4-11-release`; I get a file named `1268-mac-os-x-1-4-11-release` which contains...
```html
<html><body>You are being <a href="https://hubstaff-production.s3.amazonaws.com/downloads/HubstaffClient/Builds/Release/1.4.11-a12e5bad/Hubstaff-1.4.11-a12e5bad.dmg">redirected</a>.</body></html>
```

**Comment by ran-dall** [comment]
@vitorgalvao @core-code I figured it out. The `version` number was wrong on the output and then for the ML or any of our other checks didn't catch it, because it technically exists so I guess it checked out until Travis tried installing it.

**Review by ran-dall — COMMENTED** [review]
@vitorgalvao Thanks! forgot about that!

**Pull request merged**
