### PR TITLE
[WIP] Upgrade GPG Sync to 0.3.1

### PR DESCRIPTION
**Pull request by micahflee**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by micahflee** [comment]
I'm the upstream developer of GPG Sync.

I'm not sure why the install failed in Travis, however I bet it's related to the `preinstall` and `postinstall` scripts. This new version closes GPG Sync before installing, and then re-opens it after: https://github.com/firstlookmedia/gpgsync/tree/develop/install/macos-packaging/scripts

Maybe these scripts aren't working in the Travis osx environment?

**Comment by reitermarkus** [comment]
Given your the upstream developer, I'd suggest one of the following fixes:

- Only re-open if it was open before.
- Never automatically open it.
- Allow opening to fail.

**Comment by micahflee** [comment]
Don't merge yet, I'm pushing a commit with a development package to see if the Travis test passes this time.

**Comment by micahflee** [comment]
I've made a new PR that upgrades to 0.3.2 final #59514

**Pull request merged**
