### PR TITLE
datasette-desktop 0.2.1 (new formula)

### LINKED ISSUE #128: Create `brew install --cask datasette-app` for macOS
There is already a `brew install datasette` for the command line tool.

@simonw - is the app version cross-platform or macOS only?

### PR DESCRIPTION
**Pull request by drewda**
A macOS GUI application powered by the datasette library

closes https://github.com/simonw/datasette-app/issues/128

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by drewda** [comment]
I have addressed all the audit issues with the exception of:

```
audit for datasette-desktop: failed
 - cask token mentions desktop
 - GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
Error: 2 problems in 1 cask detected
```

I believe the first issue is not relevant, since this application is called "Datasette Desktop" on its marketing page. It is also meant to differentiate from https://github.com/Homebrew/homebrew-core/blob/master/Formula/datasette.rb

Re the second issue, this particular repo doesn't meet the popularity threshold. But the overall Datasette project (led by the same maintainer, @simonw) is very popular. Can a homebrew moderator advise on if this is sufficient? Thank you.

**Comment by bevanjkay** [comment]
Thank you for your contribution @drewda
Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

**Comment by drewda** [comment]
Thanks for reviewing, @bevanjkay. I've added a `zap` stanza. If there are any other changes that are worth making, feel free to let me know any time.

**Comment by bevanjkay** [comment]
> I believe the first issue is not relevant, since this application is called "Datasette Desktop" on its marketing page. It is also meant to differentiate from https://github.com/Homebrew/homebrew-core/blob/master/Formula/datasette.rb

@drewda I have renamed the cask to `datasette` - the above is not seen as a valid reason to provide an exemption to the `token` rules. An example of a popular cask/formula with the same situation is `docker`.

**Comment by miccal** [comment]
Thank you @drewda.

**Comment by drewda** [comment]
Thank you, @bevanjkay and @miccal!

**Pull request merged**
