### PR TITLE
archi: update livecheck with git

### PR DESCRIPTION
**Pull request by dz85**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
@vitorgalvao we may have to remove this Cask as the `url` is constantly changing. 

See discussion here: https://aur.archlinux.org/packages/archi/

**Comment by vitorgalvao** [comment]
> we may have to remove this Cask as the `url` is constantly changing.

In general, that shouldn’t be a problem as long as the old `url` keeps working. It would just mean that whoever updates the version has to update the `url` as well.

But I’ll trust your decision. The cask is still young, so if we want to remove it due to that reason, we should do it soon.

```
archi
30 days: 5 (#3441)
90 days: 72 (#1730)
365 days: 91 (#3290)
Age: 79 days (added 2020, November 10)
```

**Comment by miccal** [comment]
The old `url` is also not working:
```
|-> brew fetch archi
==> Downloading https://www.archimatetool.com/downloads/anusol480/Archi-Mac-4.8.0.zip
curl: (22) The requested URL returned error: 404                              

Error: Download failed on Cask 'archi' with message: Download failed: https://www.archimatetool.com/downloads/anusol480/Archi-Mac-4.8.0.zip
```

**Comment by vitorgalvao** [comment]
So they keep changing the URL format *and* breaking old URLs? That does suck and makes it more obtuse to support.

**Comment by miccal** [comment]
> So they keep changing the URL format _and_ breaking old URLs? That does suck and makes it more obtuse to support.

It seems that way, yes -- [other package managers](https://repology.org/project/archi/versions) are reporting the same thing; the `url` is unstable.

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/99003.

**Pull request closed without merging**
