### PR TITLE
Update cytoscape from 3.8.0 to 3.8.1

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by suschizu** [comment]
installation failed:

**Comment by core-code** [comment]
```
Error: Failure while executing; `/usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/cytoscape/3.8.1/Cytoscape\ Installer.app/Contents/MacOS/JavaApplicationStub -q` exited with 1. Here's the output:
The installation directory has been set to /Applications/Cytoscape_v3.8.1.
An error occurred:
java.lang.UnsatisfiedLinkError: could not load i4jinst from true, /usr/local/Caskroom/cytoscape/3.8.1/Cytoscape Installer.app/Contents/Resources/app/libi4jinst.dylib, /usr/local/Caskroom/cytoscape/3.8.1/Cytoscape Installer.app/Contents/Resources/app/libi4jinst.dylib
Error log: /usr/local/Caskroom/cytoscape/3.8.1/install4jError13202007279791589512.log
java.lang.UnsatisfiedLinkError: could not load i4jinst from true, /usr/local/Caskroom/cytoscape/3.8.1/Cytoscape Installer.app/Contents/Resources/app/libi4jinst.dylib, /usr/local/Caskroom/cytoscape/3.8.1/Cytoscape Installer.app/Contents/Resources/app/libi4jinst.dylib

	at com.install4j.runtime.installer.platform.win32.Common.loadNonDebug(Common.java:72)

	at com.install4j.runtime.installer.platform.win32.Common.init(Common.java:54)

	at com.install4j.runtime.installer.platform.win32.Common.init(Common.java:29)

	at com.install4j.runtime.installer.platform.win32.FolderInfo.<clinit>(FolderInfo.java:46)

	at com.install4j.runtime.installer.config.InstallerConfig.setInstallationDirectory(InstallerConfig.java:290)

	at com.install4j.runtime.installer.InstallerContextImpl.setInstallationDirectory(InstallerContextImpl.java:464)

	at com.install4j.runtime.installer.InstallerContextImpl.setInstallationDirectory(InstallerContextImpl.java:449)

	at com.install4j.runtime.beans.screens.components.InstallationDirectorySelector.handleUnattended(InstallationDirectorySelector.java:373)

	at com.install4j.runtime.beans.formcomponents.InstallationDirectoryChooserComponent.handleUnattended(InstallationDirectoryChooserComponent.java:119)

	at com.install4j.runtime.installer.frontend.FormPanel.handleUnattended(FormPanel.java:149)

	at com.install4j.runtime.installer.frontend.headless.UnattendedScreenExecutor.handleScreen(UnattendedScreenExecutor.java:91)

	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.execute(AbstractHeadlessScreenExecutor.java:96)

	at com.install4j.runtime.installer.controller.Controller$1.run(Controller.java:164)

	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)

	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
```

**Comment by core-code** [comment]
@reitermarkus any ideas about this one?

**Comment by reitermarkus** [comment]
No idea.

**Comment by miccal** [comment]
[It seems that `cytoscape` needs Java 11:](https://raw.githubusercontent.com/cytoscape/cytoscape-scripts/master/system-checker/mac.sh)
```
# Supported Java verisons
SUPPORTED_JAVA_VERSIONS=("11")
```
so the `caveats` should be changed to:
```
caveats do
  depends_on_java "11"
end
```

**Review by core-code — DISMISSED** [review]

**Review by reitermarkus — APPROVED** [review]

**Comment by core-code** [comment]
i've verified the installation now and it works just fine. must a CI thing.

**Pull request merged**
