### PR TITLE
Removed disablemonitor cask

### PR DESCRIPTION
**Pull request by adithyasunil26**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [ ] `brew audit --cask {{cask_file}}` is error-free.
- [ ] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Review by reitermarkus — DISMISSED** [review]

**Comment by miccal** [comment]
```
audit for disablemonitor: failed
 - GitHub repo is archived
```

Might be best to remove this:

Screen Shot 2021-01-11 at 01 38 11

**Comment by adithyasunil26** [comment]
@miccal I wasn't aware that disablemonitor had such an issue. Considering the warning, I second your idea of removing the cask.

**Comment by miccal** [comment]
@adithyasunil26 would you mind updating this PR to delete this Cask?

**Comment by adithyasunil26** [comment]
@miccal Updated the PR to remove the disablemonitor cask

**Review by miccal — APPROVED** [review]

**Pull request merged**
