### PR TITLE
Update undercover cask to version 6.6

### PR DESCRIPTION
**Pull request by kyleniemeyer**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by adidalal** [comment]
```
==> Purging files for version 6.6 of Cask undercover
Error: Some launch jobs were not unloaded, add them to uninstall launchctl:
com.orbicule.UCAgent
com.orbicule.uc
```

**Comment by kyleniemeyer** [comment]
@adidalal not sure why that happened, I changed nothing but the version number and sha256

**Comment by adidalal** [comment]
Could be any number of reasons, but we do like a clean uninstall. Docs on exact syntax can be found [here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md)

**Comment by kyleniemeyer** [comment]
@adidalal ok, this should be good to go now.

**Comment by kyawthura18115** [comment]
Automobileengineeringservices@googlemail.com

**Pull request merged**
