### PR TITLE
Update nomachine to 6.5.6_8

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
should I delete those comments and add the uninstall launchctl that travis proposes?

**Comment by core-code** [comment]
can you add this?

  appcast 'https://www.nomachine.com/download/download&id=7'

**Comment by core-code** [comment]
it seems there is another PR here
https://github.com/Homebrew/homebrew-cask/pull/59385

**Comment by suschizu** [comment]
oke - closed

**Pull request closed without merging**
