### PR TITLE
Update mmex

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
@guanlisheng can you explain the difference between the 'Darwin' and 'macos10.9-wx3.0.4' version? thanks!

**Comment by guanlisheng** [comment]
hey @core-code, 
'Darwin' is just a default value to represent it's mac os while macos10.9-wx3.0.4 is more meanful.

- 10.9 means its minimal mac os version would be running
- wx3.0.4 means it's based on wxWidgets v3.0.4. also we have some distributios based on wxWidgets 3.0.5 or 3.1.x

**Comment by core-code** [comment]
thanks there! so, which is the default version for most users that should be available in Homebrew Cask? :)

**Comment by core-code** [comment]
merging now because the old URL is dead, we can always change to the other version later...

**Pull request merged**
