### PR TITLE
Java 11+28:  Clarify cask caveats.  

### PR DESCRIPTION
**Pull request by RandomDSdevel**
After making all changes to the cask:  

- [x] `brew cask audit --download {{cask_file}}` is error-free.  
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.  
- [x] The commit message includes the cask’s name and version.  
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).  

~~Additionally, if **adding a new cask**:~~  

- [ ] ~~Named the cask according to the [token reference].~~  
- [ ] ~~`brew cask install {{cask_file}}` worked successfully.~~  
- [ ] ~~`brew cask uninstall {{cask_file}}` worked successfully.~~  
- [ ] ~~Checked there are no [open pull requests] for the same cask.~~  
- [ ] ~~Checked the cask was not [already refused].~~  
- [ ] ~~Checked the cask is submitted to [the correct repo].~~

(N/A; not submitting a new cask.)  

[token reference]:  https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]:  https://github.com/Homebrew/homebrew-cask/pulls
[already refused]:  https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]:  https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]:  https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

---

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tangential to any further pull request(s) that may also be submitted as a result of discussion on Discourse, namely from [this thread](https://discourse.brew.sh/t/homebrew-cask-java-packaging-puzzlement/3085).  I'll collapse the caveats down to just include the new, comment-reference–qualified links if desired, and additional formatting suggestions are welcome.

### CODE REVIEW

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Note that I'm keeping this PR's staging branch rebased against `master` locally, but won't force-push-with-lease (which I prefer over plain-old brute force-push) unless that is explicitly requested so as to avoid spamming CI.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(Ignore that; I thought I'd add two spaces for sentence spacing at the end of this PR's name, but forgot that GitHub trims trailing space.)

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'Bump' @commitay, as you appear to be the maintainer with the most contributions to the Java cask relatively recently.

**Comment by commitay** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/52605

**Comment by RandomDSdevel** [comment]
@commitay:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This was meant to be an interim measure that could have been merged faster, but fair enough.

**Pull request closed without merging**
