### PR TITLE
Skyfonts binary updates

### PR DESCRIPTION
**Pull request by nathanielvarona**
Changes on subversion and binary sha256 sum

### CODE REVIEW

**Comment by adityadalal924** [comment]
Please [squash](http://davidwalsh.name/squash-commits-git) your commits. Thanks!

**Comment by vitorgalvao** [comment]
They still aren’t squashed, @nathanielvarona, even though it seems like you tried to. I’d do it myself, but I won’t have access to my computer for a good while.

**Comment by jawshooah** [comment]
@nathanielvarona You should never create a pull request from your master branch. In the future, always create a separate feature branch, make your commits there, then create the pull request from that.

**Comment by jawshooah** [comment]
Thank you for the contribution. It was merged directly as 9a343c1b6d445550efce82572ef9bbdd63549180 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by nathanielvarona** [comment]
Thanks for reminding guys, I also lately notice the contributing guidelines and I'll never do that again for the next pull request I'll make.

**Pull request closed without merging**
