### PR TITLE
Update 7777 from 1.0.5 to 1.0.7

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@mnapoli I haven't been able to find anywhere online that has the latest version number of 7777 published. It would be greate to be able to add a livecheck to the cask, which ensure that version bumps update to the latest version, and also allow `brew livecheck 7777` to return any newer version that is available. Is there a update feed available that could be used to find the latest version?

**Comment by mnapoli** [comment]
Hi @bevanjkay, there is this URL that returns the latest version: https://releases.port7777.com/latest/version.txt

Would that work?

**Comment by bevanjkay** [comment]
> Hi @bevanjkay, there is this URL that returns the latest version: https://releases.port7777.com/latest/version.txt
> 
> Would that work?

@mnapoli Perfect!

**Review by bevanjkay — APPROVED** [review]
Thank you @SeekingMeaning!

**Pull request merged**
