### PR TITLE
meld-studio: new cask

### PR DESCRIPTION
**Pull request by mattpolito**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by mattpolito** [comment]
While reading the docs it was my understanding that this had to be submitted to `homebrew-cask-versions` so I had a [PR](https://github.com/Homebrew/homebrew-cask-versions/pull/17697) there. However was told to submit here.

**Comment by razvanazamfirei** [comment]
@mattpolito, thank you for your first contribution!!! 

Is there a way we could add a livecheck block? It seems like they're mentioning versions here https://blog.meldstudio.co/release-notes/, but is there a more robust place we could get the version from?

**Comment by mattpolito** [comment]
@razvanazamfirei currently no, but it will be going to 1.0 very soon so that may change. I can talk to the devs about that.

**Comment by miccal** [comment]
Thank you @mattpolito.

**Review by miccal — APPROVED** [review]

**Pull request merged**
