### PR TITLE
Update scrivener to 2.81.2,106

### PR DESCRIPTION
**Pull request by colindunn**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by colindunn** [comment]
I really don't like how I've done the version interpretation on this one. The current version is 2.8.1.2 but take a look through the version download links on the appcast here: https://www.literatureandlatte.com/downloads/scrivener-2.xml

Can someone else see a better way to do this? I'm trying to nicely remove the middle dot.

**Comment by miccal** [comment]
W would change the `version` to `2.8-1.2,106` and the `url` to `http://scrivener.s3.amazonaws.com/mac_updates/Scrivener_#{version.after_comma}_#{version.before_comma.no_hyphens}.zip`.

**Comment by colindunn** [comment]
Done. I just liked getting the full proper version there, but fair enough does make it a lot simpler.

**Comment by vitorgalvao** [comment]
I don’t see why not just `version '2.81.2_106'` and `#{version}` in `url`. We don’t parse `appcast` automatically, it’s more of a warning for when casks are updated.

**Pull request merged**
