### PR TITLE
Update free-download-manager from 6.13.0 to 6.13.1

### PR DESCRIPTION
**Pull request by i0ntempest**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by i0ntempest** [comment]
6.13.1 is not shown on the download page yet but the download button points to 6.13.1.

**Comment by i0ntempest** [comment]
@miccal Can you please take a look at this please?

**Comment by miccal** [comment]
I get version `6.13.1` as well, but it has not been updated on their website yet.

**Comment by i0ntempest** [comment]
So we're not merging this until they update their website?

**Pull request merged**
