### PR TITLE
Update teamviewer to 13

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by muescha** [comment]
why this cask is updated to a beta version? 

current Version is v12.0.88438

**Comment by gtmgianni** [comment]
@muescha You’re right, I’ll create a pull request to revert the changes.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/41345

**Comment by gtmgianni** [comment]
Thanks @commitay

**Pull request merged**
