### PR TITLE
document depends_on :cask

### PR DESCRIPTION
**Pull request by rolandwalker**
cc @ndr-qef

### CODE REVIEW

**Comment by ndr-qef** [comment]
Perhaps we should avoid the word “name”, given our general desire to avoid confusion between names and tokens.

**Comment by rolandwalker** [comment]
Good point, addressed.

**Comment by ndr-qef** [comment]
Merging. (That `depends_on :cask` is, strictly speaking, unreleased should not be a practical concern, given the low number of Casks with dependencies.)

**Comment by rolandwalker** [comment]
Right, and since there's a stub, at least it is a noop.  There was actually already a `depends_on :cask` in the versions repo [`scansnap-manager-v22l16.rb`](https://github.com/caskroom/homebrew-versions/blob/master/Casks/scansnap-manager-v22l16.rb).

Still, I hope to do a release in a day or two.

**Pull request merged**
