### PR TITLE
Add Upspin Latest

### PR DESCRIPTION
**Pull request by mkraft**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This seems to be a CLI-only open-source tool. Please submit it first to [Homebrew/core](https://github.com/homebrew/homebrew-core) and only if not accepted, submit here (linking back to the pull request where it was refused).

This policy is documented in [faq/rejected_casks](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core) as a formula. If it is rejected, you may then try again as a cask (link us to the issue so we can see the discussion and reasoning for rejection).

**Comment by fxcoudert** [comment]
@vitorgalvao not suitable for Homebrew core, given that the formula submitted does not build from source, and more importantly the software is not released in stable, numbered versions.

**Comment by vitorgalvao** [comment]
I’ll need to improve the standard message.

@mkraft When I meant submitting first to the core, was as a formula that built from source, otherwise it’s just a cask in a formula skin, and there’s no advantage/point to that.

**Comment by mkraft** [comment]
@vitorgalvao It seems that the advantage of "a cask in a formula skin" is pretty much the same as a cask: non-GUI installation with easy upgrades? Or am I misunderstanding? Perhaps I'm not the only person who would take advantage of the added convenience. However I completely understand if the added administrative burden of supporting pre-built binaries is not feasible or some such. I'm just seeking to understand. Thanks.

**Comment by vitorgalvao** [comment]
> It seems that the advantage of "a cask in a formula skin" is pretty much the same as a cask

What I meant was there’s no advantage *over the cask*.

**Comment by mkraft** [comment]
> What I meant was there’s no advantage over the cask.

I see, yes I agree.

**Pull request closed without merging**
