### PR TITLE
Update minecraft-server from 1.15.2 to 1.16.3

### PR DESCRIPTION
**Pull request by Blacktiger**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by Blacktiger** [comment]
It looks like the ci build couldn't reach https://minecraft.net/ for some reason.

**Comment by reitermarkus** [comment]
Weird that only the homepage fails and the appcast doesn't.

**Comment by Blacktiger** [comment]
Perhaps it's related to the homepage doing a 302 redirect to https://minecraft.net/en-us?

**Comment by core-code** [comment]
> Weird that only the homepage fails and the appcast doesn't.

i think i've requested a re-run here, and before the re-run the appcast check did also have an error because it did not contain the version number ...instead it contained HTML about some 'security protection'

hypothesis: all URLs are queried in short succession, triggering some defence on the server. if the appcast check runs before the others, it might still be OK while later reachability checks only get either 'defence html' or just some bad status code

**Comment by reitermarkus** [comment]
The homepage failure is because of this: https://github.com/Homebrew/brew/pull/8730

**Comment by core-code** [comment]
wow. must be a Microsoft server.

**Comment by reitermarkus** [comment]
You'd think it would work in a Microsoft CI environment. 😄

**Pull request merged**
