### PR TITLE
update unity to 5.1.1

### PR DESCRIPTION
**Pull request by exherb**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
If it has an installer, it still need an `uninstall`. A new one must be devised.

**Comment by exherb** [comment]
@vitorgalvao "com.unity.UnityWebPlayer"(conflict with [unity-web-player](https://github.com/caskroom/homebrew-cask/blob/master/Casks/unity-web-player.rb)) will also be installed if user selected Web Player. Should I uninstall it or not? Is there anyway to determine if unity-web-player is installed?

**Comment by vitorgalvao** [comment]
> Should we uninstall it or not?

No, because

> Is there anyway to determine weather unity-web-player is installed or not?

We have no reliable way of figuring that out, especially since it might’ve been installed separately, without homebrew-cask, and the user might still want that.

Are you sure the `uninstall :pkgutil` line still works, now that it uses an app for installation?

**Comment by exherb** [comment]
@vitorgalvao yes, the app is just a tool for downloading app pkgs.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 8997d920a6b12227b5cb581dfddab4d8cbf5fe21 to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
