### PR TITLE
Add Capacities.app v1.21.10

### PR DESCRIPTION
**Pull request by alejgr**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Review by bevanjkay — CHANGES_REQUESTED** [review]
I have added a working `livecheck` stanza and removed the `auto_updates false`stanza as it is the default.

@alejgarciarodriguez Can you try to rework the `desc` stanza to fit the guidelines? https://docs.brew.sh/Cask-Cookbook#stanza-desc

**Comment by alejgarciarodriguez** [comment]
Thanks @bevanjkay. I was reading the documentation about livecheck strategies 😅

**Comment by bevanjkay** [comment]
@alejgarciarodriguez The urls can be a bit tricky to unearth if you're not sure what you're looking for. When an app is built on electron, replacing the download's filename with `latest-mac.yml` in the URL often finds the feed.

**Review by bevanjkay — APPROVED** [review]

**Comment by razvanazamfirei** [comment]
Thanks @alejgarciarodriguez! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request merged**
