### PR TITLE
roblox studio (new cask)

### PR DESCRIPTION
**Pull request by x13a**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

Kudos to @optimisticside

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]
Thanks @x13a!

**Comment by p-linnane** [comment]
Ah, @bevanjkay caught that this should actually be `robloxstudio` and not `roblox-studio`. I've opened https://github.com/Homebrew/homebrew-cask/pull/180566 to correct this.

**Comment by x13a** [comment]
> this should actually be `robloxstudio` and not `roblox-studio`

The app is named `RobloxStudio`, but.. 

Screenshot 2024-07-25 at 11 01 28
Screenshot 2024-07-25 at 11 04 43

**Comment by bevanjkay** [comment]
Thanks @x13a - The token always follow the `app` formatting.
https://docs.brew.sh/Cask-Cookbook#token-reference

**Pull request merged**
