### PR TITLE
Update qiyimedia from 20191019,5.14.11-145 to 20191031,5.15.6-180

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
great - a new error here:
`Error: uninitialized constant Cask::Cmd::Ci::CaskDependencies`

and this like always: 
```
audit for qiyimedia: warning
 - appcast at URL 'https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://mbdapp.iqiyi.com/j/ot/iQIYIMedia_000.dmg' does not contain the version number: '20191031'
```

**Comment by reitermarkus** [comment]
> this like always

If the appcast is always wrong, we should remove it or find a better one.

**Comment by suschizu** [comment]
sorry for the bad explanation 😬
the appcast is ok and also shows the version (before_comma):
`  http://120.192.64.25/cdn/pcclient/20191031/14/59/iQIYIMedia_000.dmg?dis_k=26b85c6253972245c01739893e579a5d4&amp;dis_t=1572714895&amp;dis_dz=OVERSEA-DE&amp;dis_st=36
`
but travis doesn't find it  - i'm not sure why

**Comment by reitermarkus** [comment]
Weird.

**Comment by core-code** [comment]
i've had the same problem but just closing and re-opening the pull request did let it succeed. i /think/ the problem is that connections to chinese servers are just very unreliable and fail every second time.

**Review by core-code — APPROVED** [review]

**Pull request closed without merging**
