### PR TITLE
Update nordvpn from 5.5.7 to 5.6.0

### PR DESCRIPTION
**Pull request by cdelledonne**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ran-dall** [comment]
```
Error: Checksum for Cask 'nordvpn' does not match.
Expected: ad5fe01c4cfa11a147b86b6b2d0b218037ed1831367936c976541e4d8a3e5141
  Actual: d0e47883f78f171dcf9a6f6e7460f940598f5b265d191c1a83750c9ae4a49da2
```

That means there isn't an update on the URL

**Comment by cdelledonne** [comment]
@ran-dall I believe there is. If I do
```sh
$ wget https://downloads.nordcdn.com/apps/macos/generic/NordVPN-OpenVPN/latest/NordVPN.pkg
$ sha256sum NordVPN.pkg
```
I get
```
ad5fe01c4cfa11a147b86b6b2d0b218037ed1831367936c976541e4d8a3e5141  NordVPN.pkg
```

Moreover, if I try to
```sh
$ mkdir NordVPN && xar -xf NordVPN.pkg -C NordVPN
$ cat NordVPN/Distribution | grep version
```
this is what I get
```
<?xml version="1.0" standalone="yes"?>
        <bundle-version>
        </bundle-version>
    <pkg-ref id="com.nordvpn.osx" version="5.6.0" onConclusion="none" installKBytes="106001">#com.nordvpn.osx.pkg</pkg-ref>
    <product id="com.nordvpn.osx" version="5.6.0"/>
```

That is, the URL points to version 5.6.0 at the moment. Could it be that `brew` on the CI server is not downloading the new package because it finds one in the cache coming from the same URL?

**Comment by ran-dall** [comment]
@cdelledonne My sincerest apologies! I didn't see this till just now. This might been an glitch on the CIs' side cause the ML merged it shortly after I closed this in #85534.

**Comment by cdelledonne** [comment]
@ran-dall no problem at all :)

**Pull request closed without merging**
