### PR TITLE
freecad 1.0.0

### PR DESCRIPTION
**Pull request by jmb**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by ulab** [comment]
You beat me by 6 minutes :-) 

How did you manage to use bump-cask-pr with the extra changes that were required?

**Comment by jmb** [comment]
> You beat me by 6 minutes :-)
> 
> How did you manage to use bump-cask-pr with the extra changes that were required?

I edited the formula file with the change to the arch format for intel and the url before running the bump command (after a couple of tries tweaking some git settings). Not entirely sure if it's the right way of doing it!

**Comment by samrjack** [comment]
I'm excited for this to be merged in! I just saw the news that 1.0 was released and I'm so happy that brew is already on the way to having it available. Thank you for jumping onto this!

**Review by khipp — APPROVED** [review]
Thank you for your first contribution to `homebrew-cask`, @jmb! 🎉

**Pull request merged**
