### PR TITLE
Update kafka-tool from 2.0.7 to 2.0.8

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
The path to the executable has changed from:
```
executable: "Kafka Tool #{version.major} Installer.app/Contents/MacOS/JavaApplicationStub",
```
to
```
executable: "Kafka Tool #{version.major}.app/Contents/MacOS/JavaApplicationStub",
```

**Comment by miccal** [comment]
```
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
WARNING: GL pipe is running in software mode (Renderer ID=0x1020400)
```

[As in the earlier PR](https://github.com/Homebrew/homebrew-cask/pull/86632#issuecomment-669148329) I suspect this _may_ have something to do with the CI machines having Java pre-installed, which can interfere with anything that bundles its own JRE.

**Comment by reitermarkus** [comment]
Tried debugging this here again: https://github.com/Homebrew/homebrew-cask/pull/88301

Uninstalled all Java versions on CI and it's still not working.

**Comment by miccal** [comment]
> #88301



> Tried debugging this here again: #88301
> 
> Uninstalled all Java versions on CI and it's still not working.

@reitermarkus this particular error message did not occur for version 2.0.7 of `kafka-tool`, so perhaps this is a different issue not related to Java -- I was guessing.

Perhaps you could test what you were doing in https://github.com/Homebrew/homebrew-cask/pull/88301 on version 2.0.7?

**Comment by reitermarkus** [comment]
I'm pretty sure it's the same error, it just wasn't showing up with the old CI config because it wouldn't show any output unless it completed.

**Comment by reitermarkus** [comment]
@BrewTestBot rebase

**Pull request merged**
