### PR TITLE
Update aqua-data-studio from 20.6.0-4 to 20.6.1-1

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by reitermarkus** [comment]
@BrewTestBot rebase

**Comment by core-code** [comment]
the version doesn't seem available on the homepage and there doesn't seem to be a an update function in the app itself

**Comment by ran-dall** [comment]
@core-code If it's over a day old, I'd rather you just close. I can't see anything further back than 24hrs. Furthermore, there might be some `bad-updates` over the next little bit as I'm heavily modifying the ML so that the new changes are understood.

**Comment by core-code** [comment]
ok will do

**Pull request closed without merging**
