### PR TITLE
Add Reactotron.app v1.0.0

### PR DESCRIPTION
**Pull request by jsynowiec**
Add Reactotron.app v1.0.0

Reactotron is an OS X application for inspecting your React JS and React Native apps.
- [x] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Commit message includes cask’s name.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by jsynowiec** [comment]
By mistake I've deleted my remote branch and this PR was closed.

**Comment by adidalal** [comment]
Also, mind adding an [appcast](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md)?

**Comment by jsynowiec** [comment]
I've already mentioned this appcast in this thread: https://github.com/reactotron/reactotron/issues/163 Currently not all releases of this application has the OS X application archive. I'm not sure how brew will behave when there is a newer version available in the feed but the application binary is not.

**Comment by adidalal** [comment]
We don't use the appcast for anything except a few internal scripts yet - so no harm in adding it. Appcast updates with no app update isn't a huge deal at this point - we have have some apps that tag betas so the appcast changes (but we don't push those as Cask updates)

**Comment by jsynowiec** [comment]
Ok. I thought it's used for some sort of update mechanics and missing archive will break something. I'm updating my PR.

**Pull request merged**
