### PR TITLE
Add Rectangle.app v0.1.1

### PR DESCRIPTION
**Pull request by rxhanson**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars)).

**Comment by ran-dall** [comment]
@rxhanson I added it to my repo, as I find your app interesting and would like to keep an eye on it. 👍 https://github.com/ran-dall/homebrew-repo/commit/116358a10d76d6bd86f1d7447cb3110df17d90ae

**Comment by rxhanson** [comment]
@ran-dall thanks! Apologies for making the pull request before it accumulated enough interest on GitHub.

**Comment by vitorgalvao** [comment]
@rxhanson No need for apologies. It was still a nicely done PR, so I thank you for that.

**Comment by ran-dall** [comment]
> @rxhanson No need for apologies. It was still a nicely done PR, so I thank you for that.

Agreed, and it's worth considering once it's gotten more popular (which I don't think would take long).

@rxhanson 🤝 I'll do my best to keep it up to date on my tap; and once it has gathered more interest, I'll resubmit it for you.

**Comment by reidcooper** [comment]
It should be 50 stars now.

**Comment by rxhanson** [comment]
@reidcooper thanks!! 
@ran-dall I'll go ahead and build a new PR for the latest version of Rectangle.

**Comment by ran-dall** [comment]
@rxhanson I'll remove it from my tap.

**Pull request closed without merging**
