### PR TITLE
various casks: fix macOS version requirements

### PR DESCRIPTION
**Pull request by EricFromCanada**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.
---
- removes minimum macOS version requirements that were preventing installations on older versions
- consolidates on_system-specific macOS version requirements to a single declaration for the cask, allowing its formulae.brew.sh entry to display all available versions

### CODE REVIEW

**Comment by bevanjkay** [comment]
> consolidates on_system-specific macOS version requirements to a single declaration for the cask, allowing its formulae.brew.sh entry to display all available versions

I'm not sure how well this will work thinking future-forward. There is an audit that is currently for new casks only (or with the `--strict`) flag that compares the app's `info.plist` file with what we have, so these will likely fail the audit if there is a mismatch.

**Comment by bevanjkay** [comment]
```
brew audit --online airfoil --new

audit for airfoil: failed
 - Upstream defined :sonoma as the minimum OS version and the cask defined :big_sur
 ```

**Comment by Bo98** [comment]
> these will likely fail the audit

That's definitely an audit bug/shortcoming. It should be smarter and check if it's in an `on_os` block.

**Comment by EricFromCanada** [comment]
With https://github.com/Homebrew/brew/pull/17548 merged, cask/audit.rb now prioritizes on_os block declarations over `depends_on`, which should address the above concerns.

**Comment by krehel** [comment]
Makes a lot of sense @EricFromCanada.  Thanks for taking this on and doing some heavy lifting.  I'm good here!

**Review by krehel — APPROVED** [review]

**Pull request merged**
