### PR TITLE
caveat: MS Remote Desktop Conn. work new mswin?

### PR DESCRIPTION
**Pull request by dwlf**

### CODE REVIEW

**Comment by fanquake** [comment]
@vitorgalvao Any thoughts here?

**Comment by vitorgalvao** [comment]
I don’t think we should add the message. It’s not the caveats place to inform about every single issue the application might have. This seems like an upstream problem.

Thank you for the contribution nonetheless, @lloydde, and apologies for the time it took.

**Comment by lloydde** [comment]
@vitorgalvao "inform about every single issue"? remote-desktop-connection is broken for many use cases. I'd suggest removing it from the official repository then.

**Comment by vitorgalvao** [comment]
As you’d expect, or so I thought, I was speaking in a general sense.

Your argument to remove this from the repo makes no sense. As has been stated numerous times, we’re not a discoverability service, and in part what this implies is that to a certain extent you should know what you’re getting into when installing something. This is an upstream problem — an issue that happens if you install it the “regular way”, not due to installing it via homebrew-cask. Punishing users that know what they’re doing and that want this app installed easily is nonsensical.

**Comment by lloydde** [comment]
The factors here include:

* The name is close to what people likely mean to install -- not caskroom fault, but still your problem.
* It's unsupported software, "Microsoft Remote Desktop Connection Client for Mac (version 2.1.1) is not supported for use with Mac OS X v10.7 (Lion) or later."

**Comment by vitorgalvao** [comment]
> It's unsupported software, "Microsoft Remote Desktop Connection Client for Mac (version 2.1.1) is **not supported for use with Mac OS X v10.7 (Lion) or later**."

[emphasis mine]

Now **that** is a different matter altogether, and not at all what your caveat addressed. You change addressed versions of Windows, and what you’re talking about now are versions of OS X. That is indeed our problem, and something [we’re well capable of dealing with](https://github.com/caskroom/homebrew-cask/pull/11179).

**Comment by lloydde** [comment]
OK, thank you for your patience.

**Comment by vitorgalvao** [comment]
Thank you for researching the issue and bringing it to our attention.

**Pull request closed without merging**
