### PR TITLE
Delete roblox.rb

### PR DESCRIPTION
**Pull request by core-code**
the cask does not work as-is. someone would need to spend the time to change this to an installer stanza so we can keep it: https://github.com/Homebrew/homebrew-cask/pull/71440#issuecomment-619403707

### CODE REVIEW

**Comment by ran-dall** [comment]
@core-code If I have a second tomorrow for personal entertainment; I'll fix it and let you know...otherwise, feel free to merge.

**Comment by core-code** [comment]
thanks there, looking forward to a fix :) i wont merge my own delete requests anyway so it would be up to other maintainers there...

**Comment by ran-dall** [comment]
> thanks there, looking forward to a fix :) i wont merge my own delete requests anyway so it would be up to other maintainers there...

@core-code Cool, I'll merge this I can fix it.

**Comment by vitorgalvao** [comment]
The assignment is for organisational purposes only. You’re still free to fix or merge, however you see fit.

**Comment by ran-dall** [comment]
Still working on it...

**Comment by ran-dall** [comment]
Frankly, unless we get really creative with this, I don't think there's a way of making it work, so I'm going to go ahead and merge this...

**Comment by theLMGN** [comment]
In which way? The site downloads a DMG with a executable in it, are GUIs opening a no-go for casks? (I'd see why)

**Comment by ran-dall** [comment]
@theLMGN Well if my memory serves correctly, the installation process didn't have a way of really work together with the HBC. Some GUI-based installers do.

**Comment by core-code** [comment]
> In which way? The site downloads a DMG with a executable in it, are GUIs opening a no-go for casks? (I'd see why)

its not an 'executable' in the sense of a runnable app, but it is an installer. we'd need an 'installer manual' stanza to make it work. PRs are welcome.

**Comment by ran-dall** [comment]
FWIW `installer manual` is the only solution to this, which isn't very elegant IMO.

**Comment by vitorgalvao** [comment]
> are GUIs opening a no-go for casks?

Correct. As @core-code and @ran-dall mentioned, it would need to be an [`installer manual:`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/installer.md#installer-manual). But [we’d like to change that](https://github.com/Homebrew/homebrew-cask/issues/24377).

**Pull request merged**
