### PR TITLE
Update eudic from 4.1.5 to 4.1.8

### PR DESCRIPTION
**Pull request by singularitti**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by singularitti** [comment]
The livecheck version is severely behind the downloadable version.

**Comment by SMillerDev** [comment]
That just means that the livecheck is outdated. Could you check for a better way to find the downloadable version?

**Comment by singularitti** [comment]
@SMillerDev How about now?

**Comment by singularitti** [comment]
in progress

**Pull request closed without merging**
