### PR TITLE
Add PlugData.app v0.6.1

### PR DESCRIPTION
**Pull request by 2gn**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by 2gn** [comment]
```shell.sh
[130] brokenkb@clamshell> brew audit --new-cask PlugData
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
==> Downloading https://github.com/timothyschoen/PlugData/releases/download/v0.6.1/PlugData-MacOS-Universal.zip
Already downloaded: /Users/sapi0l/Library/Caches/Homebrew/downloads/708271ebf24bc5484b879f9740d6d3414c34194a1eef4aca5b4d0d09ecfb5935--PlugData-MacOS-Universal.zip
==> Downloading https://github.com/timothyschoen/PlugData/releases/download/v0.6.1/PlugData-MacOS-Universal.zip
Already downloaded: /Users/sapi0l/Library/Caches/Homebrew/downloads/708271ebf24bc5484b879f9740d6d3414c34194a1eef4aca5b4d0d09ecfb5935--PlugData-MacOS-Universal.zip
audit for plugdata: failed
 - Signature verification failed:
/usr/local/Caskroom/plugdata/0.6.1/PlugData-MacOS-Universal.pkg: code object is not signed at all

macOS on ARM requires applications to be signed. Please contact the upstream developer to let them know they should sign their app.
 - v0.6.1 is a GitHub pre-release.
Error: 2 problems in 1 cask detected
```

**Comment by p-linnane** [comment]
Thank you for your submission @2gn, but it cannot be accepted at this time because it does not pass Homebrew's signature verification check:

>macOS on ARM requires applications to be signed. Please contact the upstream developer to let them know they should sign their app.

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if the developers sign their app in the future we would then be happy to consider adding this to `homebrew-cask`.

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @2gn.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by miccal** [comment]
Thank you @2gn.

**Review by miccal — APPROVED** [review]

**Pull request merged**
