### PR TITLE
paw: Rename to rapidapi, bump to 4.0.0

### PR DESCRIPTION
**Pull request by p-linnane**
Paw has [undergone a rebranding](https://twitter.com/luckymarmot/status/1592625527109857280) to RapidAPI. Requesting input from @Homebrew/cask due to the analytics numbers for this cask.

```
==> Analytics
install: 286 (30 days), 801 (90 days), 4,184 (365 days)
```

### CODE REVIEW

**Comment by bevanjkay** [comment]
Until we have a way of handling aliases/renames, for popular casks what we have done is to keep the existing cask but make it `discontinued` with a `caveat` to install the new cask. And then add the new cask separately. The only to watch for is that we don't do it too often, and ideally have a mechanism to remove the old casks at a certain point.

**Review by bevanjkay — DISMISSED** [review]

**Comment by p-linnane** [comment]
@bevanjkay I'm going to copy the `zoomus`/`zoom` method here.

**Comment by bevanjkay** [comment]
The other option is to handle it the same way we with `betterdummy/betterdisplay` which doesn't automatically install the updated version.
https://github.com/Homebrew/homebrew-cask/pull/126036

**Comment by p-linnane** [comment]
Should be good now

**Comment by bevanjkay** [comment]
@p-linnane Let's leave this open for a day or so to see if there's some more maintainer feedback before making a decision. I'm happy with either the Zoom method or the current method, but I would mean lightly toward the current example.

**Review by miccal — APPROVED** [review]

**Pull request merged**
