### PR TITLE
Update freesmug-chromium to 54.0.2840.71

### PR DESCRIPTION
**Pull request by ngquerol**
After making all changes to the cask:
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by miccal** [comment]
You also need to update the [checkpoint](https://github.com/caskroom/homebrew-cask/blob/c023b005d66d4cdcb3a714f7f803833bdd86eff1/doc/cask_language_reference/stanzas/appcast.md).

**Comment by vitorgalvao** [comment]
Weird that it failed, since it seems to have been created with `cask-repair`, meaning it was automatic. Must be one of those uncommon cases where depending on where you are the feed appears to have some differences.

**Comment by vitorgalvao** [comment]
Did a test with cask repair and it seems to have worked as expected: https://github.com/caskroom/homebrew-cask/pull/26069/

Thank you for the contribution, @ngquerol. This time I’m going to merge the other simply due to convenience.

**Comment by ngquerol** [comment]
Thanks, didn't catch that one (trusted the script a bit too much 😀)

**Comment by vitorgalvao** [comment]
You’re supposed to trust the script. People do it every day. I did the exact same thing as you.

The script itself checks for errors independently. If you had run its commands manually, it’s almost certain you would have gotten the same results.

**Comment by ngquerol** [comment]
Didn't want to imply the script is bad at all! Thank you very much for fixing this pull request @vitorgalvao 😄

**Comment by vitorgalvao** [comment]
> Didn't want to imply the script is bad at all!

Oh, I know, no offence taken. My point was that you shouldn’t have to worry about if your submission is correct when using the script: that’s the point of it.

In this particular case, it was something external that caused the issue, and even if you had double-checked, you would likely have gotten the same result.

**Comment by ngquerol** [comment]
Ah yes, didn't want to imply the script is bad at all! Thank you very much for fixing this anyway. :smile:

**Pull request closed without merging**
