### PR TITLE
Update celestia.rb

### PR DESCRIPTION
**Pull request by core-code**
do not merge.

download of 'celestia' hasn't been working for me for months. is it just me? anyone know a workaround?

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> download of 'celestia' hasn't been working for me for months. is it just me?

Same here:

```
$ brew cask fetch celestia

==> Downloading external files for Cask celestia
==> Downloading https://celestia.space/files/celestia/1.6.1/celestia-osx-1.6.1.dmg
Warning: Transient problem: HTTP error Will retry in 1 seconds. 3 retries
Warning: left.
Warning: Transient problem: HTTP error Will retry in 2 seconds. 2 retries
Warning: left.
Warning: Transient problem: HTTP error Will retry in 4 seconds. 1 retries
Warning: left.

curl: (22) The requested URL returned error: 503
Error: Download failed on Cask 'celestia' with message: Download failed: https://celestia.space/files/celestia/1.6.1/celestia-osx-1.6.1.dmg
```

> anyone know a workaround?

[`user_agent: :fake`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#additional-https-url-parameters) might work.

**Comment by core-code** [comment]
doesn't seem to work:

`curl -A "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15" "https://celestia.space/files/celestia/1.6.1/celestia-osx-1.6.1.dmg"
`

=>


```
<!DOCTYPE HTML>
<html lang="en-US">
<head>
...
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
...

```

**Comment by vitorgalvao** [comment]
I tried a few of the others as well, including `cookies` and `referer`, and got nowhere. I see their website has Cloudflare DDoS protection (can’t even access it without JavaScript), so that might be the cause. Let’s remove it.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/79594

**Comment by core-code** [comment]
thanks!

**Comment by xxyzz** [comment]
Hi @vitorgalvao , their github release download link works: https://github.com/CelestiaProject/Celestia/releases, can we use these links?

**Comment by xxyzz** [comment]
That release page only has two beta release download link...

**Comment by core-code** [comment]
@xxyzz don't think this is an option since there are only beta releases there. but i think it would be worthwhile to send a bug report to their github page asking for a proper way to download their releases. e.g. by posting them on github

**Comment by vitorgalvao** [comment]
@xxyzz What @core-code mentioned is correct. We need stable links to reinstate the cask.

**Pull request closed without merging**
