### PR TITLE
various casks: use artifact stanza

### PR DESCRIPTION
**Pull request by khipp**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

This PR updates casks for apps distributed as `.jar` files to use the `artifact` stanza.

Follow-up to #185453.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Where does the `artifact` stanza put the files without `target`? I'm not sure if the stanza would respect the `appdir` flag, but it definitely won't if we hardcode the path.

**Comment by khipp** [comment]
@bevanjkay The `artifact` stanza does not have a [default directory](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/artifact/artifact.rb#L30) and [requires a target](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/artifact/artifact.rb#L22). When using a relative target, the artifact will be moved to the current directory.

**Comment by bevanjkay** [comment]
Makes sense. Can you pass `#{appdir}` to target? I've never tried.

**Comment by khipp** [comment]
@bevanjkay Thanks, that worked! I went ahead and replaced the hardcoded path of `electricbinary` as well.

**Review by SMillerDev — APPROVED** [review]

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
