### PR TITLE
Add pe-client-tools v19.1.1

### PR DESCRIPTION
**Pull request by fvoges**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Welcome, and thank you for the contribution.

Please take a look at our other casks with conditionals. You’ll see this one is really atypically. Please follow the conventions in the others. Namely use `if`, not `case`; don’t make non-standard comments; don’t add loose variables.

**Comment by fvoges** [comment]
@vitorgalvao thanks for the feedback. Can you be more specific about the loose variables bit?

**Comment by vitorgalvao** [comment]
> Can you be more specific about the loose variables bit?

Lines 4, 5, 9, 10, 15. Don’t do that.

**Comment by cdenneen** [comment]
@fvoges 6,7,11,12 are missing `=` I'm guessing and `case` should be `if` according to @vitorgalvao  I would be interested in seeing this cask completed.

**Comment by vitorgalvao** [comment]
> 6,7,11,12 are missing `=` I'm guessing

They’re not. Reference other casks and you’ll see those are correct. The lines *with* `=` are the incorrect ones.

> I would be interested in seeing this cask completed

This PR was closed six months ago for lack of reply. If you want to see it advance, you’ll need to submit your own.

**Pull request closed without merging**
