### PR TITLE
[CI] Respect `depends_on macos:`

### LINKED ISSUE #107570: [CI] Make `CiMatrix` respect `depends_on macos:` when choosing runners
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

`depends_on macos:` specifies the versions of macOS that are supported for a cask. When `CiMatrix` determines the runners a cask should be tested on without considering whether the runner actually is a macOS version supported the cask, causing checks to fail on environments that the user can't install/run the cask on themselves, and that the developer hasn't designed the cask for. 

Required for Homebrew/homebrew-cask-versions#11231

### Command that failed

`brew ruby -- "$(brew --repository homebrew/cask)/cmd/lib/generate-matrix.rb" "https://api.github.com/repos/Homebrew/homebrew-cask-versions/pulls/11231"`

### Output of command with `--verbose --debug`

*Unchanged from standard output: (https://github.com/Homebrew/homebrew-cask-versions/pull/11231/checks?check_run_id=2882107148)*

<details><summary>Click to expand</summary><pre><code>[
  {
    "name": "syntax (ubuntu-latest)",
    "tap": "homebrew/cask-versions",
    "runner": "ubuntu-latest",
    "skip_audit": true
  },
  {
    "name": "test safari-technology-preview (macos-10.15)",
    "tap": "homebrew/cask-versions",
    "cask": {
      "token": "safari-technology-preview",
      "path": "./Casks/safari-technology-preview.rb"
    },
    "audit_args": [
      "--appcast",
      "--online"
    ],
    "skip_install": false,
    "runner": "macos-10.15"
  },
  {
    "name": "test safari-technology-preview (macos-11.0)",
    "tap": "homebrew/cask-versions",
    "cask": {
      "token": "safari-technology-preview",
      "path": "./Casks/safari-technology-preview.rb"
    },
    "audit_args": [
      "--appcast",
      "--online"
    ],
    "skip_install": false,
    "runner": "macos-11.0"
  }
]::set-output name=matrix::[{"name":"syntax (ubuntu-latest)","tap":"homebrew/cask-versions","runner":"ubuntu-latest","skip_audit":true},{"name":"test safari-technology-preview (macos-10.15)","tap":"homebrew/cask-versions","cask":{"token":"safari-technology-preview","path":"./Casks/safari-technology-preview.rb"},"audit_args":["--appcast","--online"],"skip_install":false,"runner":"macos-10.15"},{"name":"test safari-technology-preview (macos-11.0)","tap":"homebrew/cask-versions","cask":{"token":"safari-technology-preview","path":"./Casks/safari-technology-preview.rb"},"audit_args":["--appcast","--online"],"skip_install":false,"runner":"macos-11.0"}]
</code></pre></details>

### Output of `brew doctor --verbose`

N/A: CI environment

Example output: https://github.com/Homebrew/homebrew-cask-versions/pull/11231/checks?check_run_id=2882107148

### Output of `brew tap`

N/A: CI environment

Example output: https://github.com/Homebrew/homebrew-cask-versions/pull/11231/checks?check_run_id=2882107148

### PR DESCRIPTION
**Pull request by mostpinkest**
Accounts for `depends_on macOS:` when determining runners for CI.

Fixes #107570

When reviewing, just double check I haven't made any obvious mistakes and if any changes are needed for style or a regex.

### CODE REVIEW

**Comment by Logicer16** [comment]
I’ll fix style in the morning.

**Comment by bevanjkay** [comment]
@Logicer16 Will wait for @reitermarkus for review.

But just letting you know that you can run the style checks locally with 
brew style 'cmd/lib'

**Comment by SMillerDev** [comment]
Is there no way to use the same code that `brew` uses here?

**Comment by Logicer16** [comment]
> Is there no way to use the same code that `brew` uses here?

By the looks of it, calling the code that brew uses will preform the comparison itself with the version of the host machine, preventing each available runner version from being compared with the version in the `depends_on macos:` field.

**Comment by Logicer16** [comment]
Just had a thought, what should happen if a cask can't run on any of the runners? (e.g. `depends_on macos: "<= :mojave"`)

**Review by SMillerDev — DISMISSED** [review]
I'm okay with this one, I'll leave it to some other maintainer to merge to make sure there's some more eyes on this.

**Comment by Logicer16** [comment]
Just want to point out that 22 casks have a `depends_on macos:` where the required version is not compatible with one of the runners, which will result in an exception being raised from the new code. So, seen as these casks are compatible with macOS versions support by Homebrew (e.g. `depends_on macos: <= :mojave`), and the casks may not be able to pass CI on an unsupported macOS version, how should the CI be preformed on these casks?

**Comment by carlocab** [comment]
Can we ignore the `depends_on` for those Casks and just test them as they would have been before the changes here?

**Review by carlocab — APPROVED** [review]
Thanks, @Logicer16! Let's give this a try.

**Pull request merged**
