### PR TITLE
Propose new version of MPS with JDK bundled

### PR DESCRIPTION
**Pull request by Crocmagnon**

### CODE REVIEW

**Comment by adityadalal924** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 4a51e6865fc62aedd7fb40d8f2cadf8a6fe403e1. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by adityadalal924** [comment]
@vitorgalvao I left `zap` alone - are the new `version` methods also supported there?

**Comment by vitorgalvao** [comment]
> I left `zap` alone - are the new `version` methods also supported there?

Yes, they should be supported everywhere.

**Comment by Crocmagnon** [comment]
Thank you for your quickness, and for the corrections! I have to admit I totally ignored there were new methods for version numbers.

**Comment by vitorgalvao** [comment]
> I have to admit I totally ignored there were new methods for version numbers.

They’re pretty recent.

**Pull request closed without merging**
