### PR TITLE
Add Receitanet v1.07

### PR DESCRIPTION
**Pull request by fpg1503**
Add the Receitanet App

### CODE REVIEW

**Comment by fpg1503** [comment]
Travis timed out, can you please run it again? I don't wanna push a new commit or close and open the PR and I don't have write access to the repo to restart the build.
The cask passes `audit` and `style` here so it most likely won't fail.

**Comment by adidalal** [comment]
Restarted

**Comment by adidalal** [comment]
Travis seems to be bugging out - I will manually verify and merge later tonight.

**Comment by adidalal** [comment]
On second thought, is this an eID program?
If so, it should go in homebrew-eid.

**Comment by fpg1503** [comment]
It is a program to transfer IRS tax declarations, I don't think it falls under eID, does it?

**Comment by adidalal** [comment]
No, should be fine in HBC

**Pull request merged**
