### PR TITLE
Add Audacity.app v3.0

### PR DESCRIPTION
**Pull request by thomassth**
Continuing #12972

By audacity 3.0.0, released 17 Mar 2021, all compiled packages are listed on Github as releases.

[https://github.com/audacity/audacity/releases](https://github.com/audacity/audacity/releases)

Since `brew audit` is hard coded to refuse Audacity on any grounds, I can't complete all checkboxes, neither does the automated review bots. Nonetheless, I think the rule "audacity is not allowed: Audacity was removed because it is too difficult to download programmatically." (#27517) should no longer apply. It's just as easy as other Github releases.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [!] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- See above
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by nopeinomicon** [comment]
Looks good, gets my +1, considering that the issue with hosting is fixed with Audacity being on Github, this should be merged.

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @thomassth.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

**Comment by thomassth** [comment]
Done

**Comment by thomassth** [comment]
Since the hard block at [brew](https://github.com/Homebrew/brew/pull/11000) is lifted, the cask can now be deployed without issues.

**Review by reitermarkus — APPROVED** [review]

**Pull request merged**
