### PR TITLE
Update firefox to 60.0.1

### PR DESCRIPTION
**Pull request by paescuj**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by puffdad — COMMENTED** [review]
Please refrain from moving zh in front of zh-TW. This will force Traditional Chinese users install Simplified Chinese version.

**Comment by paescuj** [comment]
@puffdad I'm sorry, does the order of the language matter?

**Comment by vitorgalvao** [comment]
@paescuj [Yes](https://github.com/Homebrew/homebrew-cask/issues/42755). It’s a bug.

**Comment by paescuj** [comment]
Okay, thanks! Fixed in #47746

**Pull request merged**
