### PR TITLE
Add KryoFlux v2.62

### PR DESCRIPTION
**Pull request by theGrue**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

This installs the command-line `dtc` utility and support library to interface with [KryoFlux](https://www.kryoflux.com/) hardware and the disk images it creates. There is also a GUI available, it seems like the appropriate thing to do will be to submit that as a future cask (i.e. `kryoflux-gui`) that depends_on this cask, rather than install everything in a single cask.

### CODE REVIEW

**Comment by miccal** [comment]
> This installs the command-line `dtc` utility and support library to interface with [KryoFlux](https://www.kryoflux.com/) hardware and the disk images it creates. There is also a GUI available, it seems like the appropriate thing to do will be to submit that as a future cask (i.e. `kryoflux-gui`) that depends_on this cask, rather than install everything in a single cask.

Is the GUI also installed via the same `pkg`?

**Comment by theGrue** [comment]
> Is the GUI also installed via the same `pkg`?

Yes, it is. Should this only be a single cask, then? I was following along with the docs for the pkg Stanza at https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/pkg.md#pkg-choices which shows breaking up the same wireshark pkg into separate casks. (Excellent docs here, btw!)

**Comment by miccal** [comment]
> > Is the GUI also installed via the same `pkg`?
> 
> Yes, it is. Should this only be a single cask, then? I was following along with the docs for the pkg Stanza at https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/pkg.md#pkg-choices which shows breaking up the same wireshark pkg into separate casks. (Excellent docs here, btw!)

Yes, I thing it would be best to have this all as a single Cask, thank you.

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @theGrue.

**Review by miccal — APPROVED** [review]

**Pull request merged**
