### PR TITLE
Delete mtmr.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
Apparently they’re not making later versions publicly available anymore.

https://github.com/Homebrew/homebrew-cask/issues/55289
https://github.com/Toxblh/MTMR/issues/128

### CODE REVIEW

**Review by victorpopkov — APPROVED** [review]

**Comment by core-code** [comment]
i am not sure about this, 0.19 is still publicly available, just not on the github site:

the appcast
https://mtmr.app/appcast.xml
links to
https://mtmr.app/MTMR%200.19.dmg

and the download works just fine

**Comment by Toxblh** [comment]
Wow! Did you can ask me before do it?

**Comment by vitorgalvao** [comment]
> Can you next double check with me before doing it?

[I did](https://github.com/Toxblh/MTMR/issues/128#issuecomment-441127136).

Maybe I I haven’t waited for a reply foras long as you needed, but I’ve waited a reasonable amount of time considering:

* You had made your plans known.
* This is easily reversible.
* We have to move fast, because we get a metric crapton of issues and PRs daily and it’s easy for things to get buried.
* It’s not uncommon for maintainers to leave comments unanswered.

Even @core-code, a user unrelated to this particular software, noticed it before you did (sorry, missed your comment).

So i’s not reasonable of you to ask us to wait indefinitely for a reply to a question we didn’t even need to ask. You had indicated your intentions. My comment there was a courtesy *precisely to give you the chance to stop or fix this in case my understanding of the situation was incorrect*.

We’re all fellow open-source maintainers. I’ll happily give leeway, but I also need to move the project I’m maintaining.

I’ll gladly take a PR to reinstate this, if it that hasn’t happened already (that’s how many contributions we get a day: I can’t even be sure it wasn’t already resubmitted and that I haven’t merged it myself, even).

**Comment by Toxblh** [comment]
Yes, I miss the message.
I created the PR for revert the changes. 
Thanks

**Pull request merged**
