### PR TITLE
updated nicecast (1.11.7)

### PR DESCRIPTION
**Pull request by cicloid**

### CODE REVIEW

**Comment by adidalal** [comment]
Please don't delete the appcast.

Use `http://rogueamoeba.net/ping/versionCheck.cgi?format=sparkle&bundleid=com.rogueamoeba.Nicecast&system=10113&platform=osx` for the new appcast (and update the checkpoint accordingly).

`http://rogueamoeba.com/nicecast/download.php` is fine for URL, though

Feel free to close this PR and make a new one if it's easier.

**Comment by cicloid** [comment]
Closing for #19138

**Comment by cicloid** [comment]
@adidalal Quick question. How did you get the appcast url? I had trouble getting that address Where can I learn more about the process?

**Comment by adidalal** [comment]
Thanks for the update. 

I'll point you to https://github.com/caskroom/homebrew-cask/issues/19103, where I describe the process in an abbreviated form - please ask there if you have questions; I'll try to eventually write up the process as actual documentation.

**Pull request closed without merging**
