### PR TITLE
qt-creator 13.0.1

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
qt-creator
  * The livecheck URL https://download.qt.io/official_releases/qtcreator/?C=M;O=D is not reachable
```

**Comment by krehel** [comment]
@chenrui333 does this work for you locally?  I am having mixed results of success

**Comment by miccal** [comment]
> @chenrui333 does this work for you locally? I am having mixed results of success

Working for me:
```
|-> brew livecheck --debug qt-creator
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading qt-creator
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromNameLoader): loading qt-creator

Cask:             qt-creator
Livecheckable?:   Yes

URL:              https://download.qt.io/official_releases/qtcreator/?C=M;O=D
Strategy:         PageMatch
Regex:            /href=["']?v?(\d+(?:\.\d+)+)\/?["' >]/i

Matched Versions:
13.0.1, 13.0.0

qt-creator: 13.0.0 ==> 13.0.1
```

**Comment by krehel** [comment]
I'll take it.  Thanks @miccal.

**Comment by chenrui333** [comment]
> @chenrui333 does this work for you locally? I am having mixed results of success


```
$ brew livecheck qt-creator
qt-creator: 13.0.0 ==> 13.0.1
```

---

sorry about late reply.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
