### PR TITLE
font-departure-mono 1.422

### PR DESCRIPTION
**Pull request by daeho-ro**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by khipp** [comment]
@daeho-ro It seems like updates to the `goneovim` cask were accidentally included.

**Comment by daeho-ro** [comment]
@khipp Oh... I will fix that.

**Review by khipp — APPROVED** [review]
Thank you!

**Comment by khipp** [comment]
@daeho-ro You are welcome to create a new PR for the updates you made to `goneovim` in commit https://github.com/Homebrew/homebrew-cask/commit/31fb73173ef90ae5d5cdd47a3afe8ef534472fd7. They have not been merged yet.

**Pull request merged**
