### PR TITLE
Update plexamp from 3.9.1 to 4.0.0

### PR DESCRIPTION
**Pull request by marcus-crane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @marcus-crane  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by StormPooper** [comment]
Feel bad reporting an error after such a nice comment, but I'm getting a different sha256 hash:

```bash
Error: plexamp: SHA256 mismatch
Expected: 5aa900de0dc7c6f0081bea5c56f0fae0a220e886076a56ed2e650defe80a4edd
  Actual: 872435af0b97bc9dff6195413a0874ce8a70d1a762a5fbbdf1707d1770d819f7
```

Could be they've stealth-replaced the file since this PR was created.

**Comment by marcus-crane** [comment]
@StormPooper They have indeed switched out the installers. I've still got the old ones from when I created this PR on my desktop!

CleanShot 2022-02-16 at 22 57 39@2x

**Comment by marcus-crane** [comment]
@StormPooper https://github.com/Homebrew/homebrew-cask/pull/119260 Definitely odd. The electron builder manifest hasn't changed (https://plexamp.plex.tv/plexamp.plex.tv/desktop/latest-mac.yml) but the dmgs definitely have. I can see the hash for the electron asar bundle has changed inside the `Info.plist`

**Pull request merged**
