### PR TITLE
Update anki from 2.1.28 to 2.1.29

### PR DESCRIPTION
**Pull request by desimaniac**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by desimaniac** [comment]
I used the latest cask-repair (v. 0.40.22) from https://github.com/vitorgalvao/tiny-scripts/cask-repair to make this PR. This script used single quotes but the CI is checking for double quotes.

**Comment by miccal** [comment]
@desimaniac the changed style is relatively new, so there is bound to be some issues during the transition.

**Comment by desimaniac** [comment]
@miccal Oh ok, thanks! Should I then make the changes the CI is reporting?

**Comment by miccal** [comment]
Yes please.

**Comment by reitermarkus** [comment]
Seems like the same change was already auto-merged now.

**Pull request closed without merging**
