### PR TITLE
Update github from 2.8.1-717be06b to 2.8.2-4423bb9d

### PR DESCRIPTION
**Pull request by jabenninghoff**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by ylht** [comment]
It is worth noting that the community provides support for apple silicon in this release, so simply upgrading the version number is not enough.

**Review by ylht — CHANGES_REQUESTED** [review]
Add support to install the app for silicon

**Comment by jabenninghoff** [comment]
> It is worth noting that the community provides support for apple silicon in this release, so simply upgrading the version number is not enough.

I'm confused, is there something I need to change with this PR?

**Comment by jabenninghoff** [comment]
> Add support to install the app for silicon

Ah... I see... I was not aware of the change. I don't have time to add support for this now, can I suggest this PR be merged in order to provide an update for people on intel and the support added as a separate PR? Thanks.

**Comment by ylht** [comment]
> > Add support to install the app for silicon
> 
> Ah... I see... I was not aware of the change. I don't have time to add support for this now, can I suggest this PR be merged in order to provide an update for people on intel and the support added as a separate PR? Thanks.

I have no problem with that.

**Review by ylht — APPROVED** [review]

**Pull request merged**
