### PR TITLE
deezer 6.0.80

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
 - exception while auditing deezer: Failure while executing; `/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/homebrew-dmg20240308-7122-50g1ca /private/tmp/homebrew-dmg20240308-7122-50g1ca/38f6a3760441f5cfb197851b8fa86077f6da6aa51c36d051d82c010be4a3578b--DeezerDesktop_6.0.80.cdr` exited with 1. Here's the output:
hdiutil: attach failed - no mountable file systems
```

**Comment by krehel** [comment]
Local disk image is also corrupt when auditing.  Manually opening the `dmg` produces errors and cannot be mounted.

Tagging this as an upstream problem.

**Comment by krehel** [comment]
Opened a ticket with the upstream vendor for the DMG file being corrupted.  Awaiting response.

**Comment by krehel** [comment]
(Deezer Support)
13 Mar 2024, 14:18 GMT

We appreciate your response, Justin.
 
Upon receiving the information, we have conducted a regression to version 6.0.70, and we are excited to announce that version 6.0.90 will be released in the upcoming days. 😊️

**Pull request closed without merging**
