### PR TITLE
Visit 2.9.2

### PR DESCRIPTION
**Pull request by goxberry**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
No one has given a satisfactory answer yet, so I’ll ask again. @goxberry what is it about that comment that makes it seem like it should be removed? Absolutely honest and serious question, I truly want to know what compels people to remove that comment. Reading it should make it obvious it is correct and why it’s there, but apparently isn’t, so I’d like to know how to make it better.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 0dfea184255fde5d1b2d5cbfb339928a4109430e. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by goxberry** [comment]
@vitorgalvao Sorry, I didn't realize the comment should be kept!

I think there were a few reasons I deleted the comment. Whenever I write a comment in all lowercase, it's usually a throwaway comment, like a note to myself. With some of the software I use, downloading the source code from a different hostname than the homepage is pretty common, so I didn't think much of it.

In light of your question, I looked at https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md and https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#url-stanza-details again, to see if I missed something. I couldn't find any mention of commenting when the download URL has a different hostname than the homepage in either location. To enforce this policy in the future, it might be worth noting it in the documentation. I've added a pull request (https://github.com/caskroom/homebrew-cask/pull/13038) to this effect.

**Comment by vitorgalvao** [comment]
Ah, I see. Thank you for the explanation. The reason it is undocumented is simple: it shouldn’t really be the user to add the comment, but a maintainer. The comment is there to certify that a maintainer verified it as being trustworthy.

That said, some users do add the comment themselves (we still verify them) and those will only grow. It should also be obvious when the comment was added, as a clue for the maintainer to verify it.

**Pull request closed without merging**
