### PR TITLE
Update Librewolf form 89.0.1-1 to 89.0.2

### PR DESCRIPTION
**Pull request by brightly-salty**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by fxbrit** [comment]
something is wrong with this PR, I don't see the commits but I'm pretty sure it was lacking a "-1". my question is: why does it show as merged if it's not? am I missing something? 😮

**Comment by cho-m** [comment]
@fxbrit It looks like a no-change PR probably due to a combination of using `master` branch in fork along with an auto-update bot https://github.com/apps/pull

The Cask update will need a new PR.

**Comment by brightly-salty** [comment]
I'm pretty sure I made the change (adding -1) before pull force-pushed, but I'll make a new PR on a new branch if that's what's the needed.

**Comment by fxbrit** [comment]
thanks to both of you!

**Pull request merged**
