### PR TITLE
Update musicbrainz-picard to 2.0.2

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/pull/50239

also, you may want to check out the tool I use for scanning (it will let you know if a PR is already open): https://github.com/brianmorton/cask-automation/

**Comment by core-code** [comment]
thanks, sounds like a great tool, will have a look.

it would be nice if cask-repair could detect open PRs to prevent duplicates.

**Comment by brianmorton** [comment]
a few people have mentioned that about `cask-repair`, I'll see if I can workout a PR/fork.

**Comment by core-code** [comment]
@brianmorton: that would be quite cool ;) however, if things are moving into a direction of more automatisation and less manual cask-repair to keep the casks up-to-date anyway it may not be worth it anymore though.

**Comment by brianmorton** [comment]
even the automated systems will need to check if there is an existing PR :)

**Pull request closed without merging**
