### PR TITLE
- Add Sparkplate.app v1.0.0

### PR DESCRIPTION
**Pull request by tmrdev**
- submitting Sparkplate.app v1.0.0 for review

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Thank you for your submission @tmrdev, but we cannot accept it at this time because it does not pass our signature verification check that are a requirement for new submissions:

> macOS on ARM requires software to be signed. Please contact the upstream developer to let them know they should sign and notarize their software.

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if the developers sign their app in the future we would then be happy to consider adding this to `homebrew-cask`.

**Comment by tmrdev** [comment]
The Sparkplate.app has been Signed and Notarized for M1/M2 hardware and the older Intel hardware.  It is a Universal build for all hardware.  Can we re-open this PR?  I need to update sha256 checksum as it has changed. Also how do I go about re-submitting this PR?  I have updated the Casks/sparkplate.rb but when I do audit checks it states the file needs be in:

/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/s/sparkplate.rb

I am not sure why it is expecting it in the s directory.  Please let me know how to proceed.

**Comment by bevanjkay** [comment]
@tmrdev We have recently "sharded" repository (moved some files into subdirectories) to help with git performance. The `sparkplate.rb` files just needs to be moved into the `/s/` subdirectory.

**Comment by bevanjkay** [comment]
@tmrdev Please also try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

**Comment by bevanjkay** [comment]
@tmrdev Closing this for now. Feel free to open a new PR when you're ready.

**Pull request closed without merging**
