### PR TITLE
Update sha256 for ngrok

### PR DESCRIPTION
**Pull request by amowu**
### Instructions

Update SHA256
### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:
- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [ ] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You are not adding a new cask. As such, you are not supposed to edit the bottom part.

The instructions seem very clear to me. However, we still get this mistakes fairly regularly. Mind telling us what was unclear about the message, so we might improve it?

**Comment by vitorgalvao** [comment]
Why close it? The submission itself was fine, I was only asking to improve our checklist.

**Comment by amowu** [comment]
@vitorgalvao Sorry, I would have thought this SHA256 had a mistake, but when I run `brew update`, it's work!

**Comment by zomars** [comment]
I'm actually having this exact same issue.

**Comment by pcreux** [comment]
@zomars Fixing in https://github.com/caskroom/homebrew-cask/pull/26134

**Comment by adidalal** [comment]
Version actually did update, not just the shasum
https://dl.equinox.io/ngrok/ngrok/stable

Fixed now, though.

**Pull request closed without merging**
