### PR TITLE
fix devtunnel sha number

### PR DESCRIPTION
**Pull request by setaskin**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@setaskin It looks like the previous shasum is correct as per what is being downloaded by the CI run.

**Comment by setaskin** [comment]
> @setaskin It looks like the previous shasum is correct as per what is being downloaded by the CI run.

@bevanjkay , I closed the Pr but actually on my local the sha numbers I used in this Pr seems correct. It is weird. I install dev tunnel via homebrew and during installation it shows correct version number but when I use dev tunnel it still points to previous version .

**Comment by setaskin** [comment]
these seems to be the correct sha numbers. I don't understand why checks still looks for old sha numbers. Can one of the maintainers help me ?

**Comment by setaskin** [comment]
these seems to be the correct sha numbers. I don't understand why checks still looks for old sha numbers. Can one of the maintainers help me ?

**Comment by p-linnane** [comment]
I just pulled down both binaries. The existing shasums are correct.

**Comment by setaskin** [comment]
@p-linnane  . please see below screen shot. I will re-open the Pr as Draft please don't close it until we understand the issue. It is not possible that it points to the current sha numbers cause they belong to a previous version.  I double checked the cask everything is correct except the sha numbers . Also,  when I do "brew audit" it asks for a new sha number. It fails in audit brew and I don;t understand how it still looks for the old sha numbers in the pr. Please help me to fix it. 

image

**Pull request closed without merging**
