### PR TITLE
Test coverage reporting with Coveralls

### PR DESCRIPTION
**Pull request by jawshooah**
This PR builds on #7797 to add test coverage with SimpleCov and report results to [coveralls.io](https://coveralls.io/r/caskroom/homebrew-cask).

### CODE REVIEW

**Comment by phinze** [comment]
Nice! I tried to get this working over a year ago, but we were still supporting Ruby 1.8 which made coveralls sad.

**Comment by vitorgalvao** [comment]
Is there a way to make coveralls messages less obtrusive (like Travis, which integrates nicely)?

Coveralls is spammy as hell when trying to review a PR, and actually annoying when contributing. Perhaps just to me, but everytime I contribute to a project and almost immeditally get an email reply that is just a coveralls reply to said PR, I get a bit more inclined to not contribute again (“why is my inbox getting spammed with automated replies I have noninterest in, after trying to make the projec better?”).

**Comment by vitorgalvao** [comment]
Is there a way to make coveralls messages less obtrusive (like Travis, which integrates nicely)?

Coveralls is spammy as hell when trying to review a PR, and actually annoying when contributing. Perhaps just to me, but every time I contribute to a project and almost immediately get an email that is just a coveralls replying to said PR, I get a bit more inclined to not contribute again (“why is my inbox getting spammed with automated replies I have no interest in, after trying to make the project better?”).

It also spams you with replies even after you have already merged something (and I mean things we merge from other contributors), and obscures the real contributors when looking at Github notifications.

Does no other @caskroom/maintainers feel an intense dislike for how coveralls works?

**Comment by ndr-qef** [comment]
Silencing Coveralls in non-core PRs was the purpose of #10109, but I have clearly missed something.

**Comment by Amorymeltzer** [comment]
Yeah, absolutely agree @vitorgalvao.  I didn't see much in their docs, but then again it was a cursory look.  Can the owners block someone from commenting?  That would at least be a stopgap.

**Comment by phinze** [comment]
Yeah agreed that comments are _no bueno_ - I think I found the setting to fix it!

caskroom_homebrew-cask___coveralls_-_test_coverage_history___statistics

**Comment by phinze** [comment]
p.s. All maintainers _I think_ should have access to change the settings by doing the Github OAuth dance with https://coveralls.io/r/caskroom/homebrew-cask?branch=master

Leaving this open until we can confirm it's silenced the comments. :+1:

**Comment by vitorgalvao** [comment]
Thank you! I truly appreciate it.

**Comment by fanquake** [comment]
Great :thumbsup:

**Comment by Amorymeltzer** [comment]
:kiss: :heart:
Owners-only afaict

**Comment by radeksimko** [comment]
:+1:

**Pull request merged**
