### PR TITLE
Update feishu from 4.9.5,5a774e to 4.9.6,53c059

### PR DESCRIPTION
**Pull request by zuisong**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by gdams** [comment]
I've pushed a minor change to simplify the multi architecture logic.

**Review by gdams — DISMISSED** [review]

**Comment by bevanjkay** [comment]
@gdams the versioning is slightly different between the intel and arm variant. So we will need to keep the urls in if blocks. We need to be particularly careful with arm related details at the moment because CI doesn't complete any checks. 

@zuisong Because the livecheck is returning different values for intel and arm, it would be better to keep the livecheck and version stanzas separate within the if blocks for now.

**Comment by bevanjkay** [comment]
@gdams I found a combination of the logic that cleans it up and should work well for the cask.

**Comment by zuisong** [comment]
> @gdams the versioning is slightly different between the intel and arm variant. So we will need to keep the urls in if blocks. We need to be particularly careful with arm related details at the moment because CI doesn't complete any checks.
> 
> @zuisong Because the livecheck is returning different values for intel and arm, it would be better to keep the livecheck and version stanzas separate within the if blocks for now.

👌

**Review by gdams — APPROVED** [review]

**Pull request merged**
