### PR TITLE
Add CloudApp v4.2.1

### PR DESCRIPTION
**Pull request by malthejorgensen**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by malthejorgensen** [comment]
When you download from https://www.getcloudapp.com you get version 4.2.1.
However, as soon as you install you're prompted to update to 4.2.2 – even so, because it's the officially downloadable version I believe this belongs in `stable`.

**Comment by miccal** [comment]
[Already available.](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cloud.rb)

**Comment by malthejorgensen** [comment]
Sorry about that. It's cause I did `brew cask search cloudapp` and got nothing – we should probably have an alias or rename the recipe to `cloudapp`? 🙃

**Comment by vitorgalvao** [comment]
> we should probably have an alias or rename the recipe to `cloudapp`?

No. [Token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).

**Comment by malthejorgensen** [comment]
You misunderstand – the name of the product (and the company) is literally
CloudApp – not Cloud. I don't think the intention of that part of the Token
reference is to remove App from CloudApp (or WhatsApp for that matter), but
rather remove app from generic names like "Wireless Transfer App.app" or
superfluous usage like "PomoDoneApp.app"

**Comment by vitorgalvao** [comment]
> You misunderstand – the name of the product (and the company) is literally CloudApp – not Cloud.

Yes, I know. I’m familiar with the app.

> I don't think the intention of that part of the Token reference

I wrote most of the token reference, and the parts I didn’t write had my input, so I’m pretty sure I know its intentions.

**However**, [having said that](http://youtu.be/ENHVQ2gslp8), I do concede this one has already caused an inordinate amount of confusion, so I proposed we make it an exception. Will do so shortly, with a note.

**Comment by malthejorgensen** [comment]
Sorry for being a bit stubborn – just trying to make it easier for the next "homebrewer" stumbling on the same problem 😊  Would it make sense to expand the `brew cask search` to also search the `name` of the recipe? (I would be happy to make a PR)

Thank you @vitorgalvao!

**Comment by malthejorgensen** [comment]
Ok, I can see that there's already some work done on that (#17323) – ignore that.

Once again – thank you for the great work! 👍

**Comment by vitorgalvao** [comment]
> Would it make sense to expand the `brew cask search` to also search the `name` of the recipe? (I would be happy to make a PR)

It’s an actively desirable feature. Please do!

> Ok, I can see that there's already some work done on that (#17323)

That work is from 2014. Much/most of it is no longer applicable with the current codebase. Feel free to work on it.

**Pull request closed without merging**
