### PR TITLE
Delete Carthage formula

### PR DESCRIPTION
**Pull request by jspahrsummers**
Keeping it here is a recipe for outdatedness, since there's an up-to-date formula in Homebrew proper: https://github.com/Homebrew/homebrew/blob/20f4ba664dc1739dd2cbbba492fbe376eb68585c/Library/Formula/carthage.rb

### CODE REVIEW

**Comment by vitorgalvao** [comment]
What do you mean? They seem to both be at the same version. We don’t keep packages out because they exist in homebrew. Many users prefer to install via homebrew-cask, and there are many packages we update sooner.

**Comment by jspahrsummers** [comment]
As a maintainer of Carthage, it's quite frustrating to me to get bug reports from users that are running older versions of the tool.

In a couple of cases, this has been because they installed from `homebrew-cask`, which was significantly out of date (multiple big releases behind) until https://github.com/caskroom/homebrew-cask/pull/9289.

> Many users prefer to install via homebrew-cask, and there are many packages we update sooner.

I myself ensure that Homebrew has the latest version for its formula, as soon as we release a new version. I guarantee that it will have the newest update sooner.

Besides that, I don't know why there would be a preference for `homebrew-cask` in this case. It's not a GUI application, and Homebrew provides a bottle, so there's no building from source necessary.

**Comment by ndr-qef** [comment]
Hello @jspahrsummers. First, let me thank you for taking an active interest in the cask for Carthage.

We are not in principle opposed to removing a cask upon request, but I should like to emphasize that Homebrew and homebrew-cask are different projects, with fairly different use cases. Similarly, the overlap of users is significant, but not complete. We generally avoid removing casks for reasons of duplication, on the basis that some users may prefer one system to the other.

Have your users experienced issues with installing Carthage via homebrew-cask? Perhaps you have noticed outdated bug reports, or similia? If the cask is not cared for sufficiently, and causes problems upstream, we are most definitely available to remove it.

**Comment by Palleas** [comment]
I haven't experienced issues per-se but I was in the situation mentioned by @jspahrsummers earlier (building with 0.3x while the most current version was 0.52), hence the PR. I actually went to the trouble of installing homebrew cask before I saw it was available directly via homebrew.

I'm +1 on removing it from cask :)

**Comment by ndr-qef** [comment]
> Besides that, I don't know why there would be a preference for homebrew-cask in this case. It's not a GUI application—and Homebrew provides a bottle, so there's no building from source necessary.

Our general approach is to be inclusive, and we try to be open to unusual setups. For example, it is not exceptionally rare to only keep a minimal Homebrew installation for the purpose of using homebrew-cask.

I would like to wait for the opinion of other @caskroom/maintainers, but if you feel confident that the cask will serve too few users and represent a maintenance burden, I am in favor of merging this PR.

**Comment by jspahrsummers** [comment]
Even aside from the Homebrew up-to-date-ness, [Carthage](https://github.com/github/Mac/issues/3717#issuecomment-71904050) is a developer-focused tool with no GUI (command-line only)—which seems quite different from kind of app that homebrew-cask means to help with.

**Comment by vitorgalvao** [comment]
> which seems quite different from kind of app that homebrew-cask means to help with.

It is not, as we have a bunch of CLI-only casks, even ones that are not distributed as `pkg`s but only as compiled binaries. For the latter we usually [directed users to homebrew/homebrew-binary](https://github.com/caskroom/homebrew-cask/pull/4228) but eventually stopped doing it *because users kept submitting those apps; they expected them to be present here*.

Your understanding of the scope of apps provided by homebrew-cask is limited in that regard — If it can be installed without compilation, we allow it (not just apps, even). Examples include [rust](https://github.com/caskroom/homebrew-cask/blob/master/Casks/rust.rb), [iojs](https://github.com/caskroom/homebrew-cask/blob/master/Casks/iojs.rb), and many others. That particular argument isn’t at all basis for removal. Receiving bug reports due to old versions is a concern, though, and one [that we can feel as well](https://github.com/caskroom/homebrew-cask/issues?q=label%3Aduplicate+is%3Aissue+is%3Aclosed).

> For example, it is not exceptionally rare to only keep a minimal Homebrew installation for the purpose of using homebrew-cask.

This is an important point, and will only become more relevant if we separate from homebrew, which is a possibility outlined in an open issue.

The solution to this issue is not remove the cask, but to keep it updated<sup>1</sup>. That is the case with every cask, though, and we do the best we can to keep up. I believe we shouldn’t remove it. However, I also believe we should cater to the developers’ wishes when it makes sense, and if @jspahrsummers wishes to not have his work distributed by homebrew-cask, we should honor that<sup>2</sup>.

---

<sup>1</sup> Were there a way to do it automatically, such as an appcast or watching the repo *only for* releases, I’d even do it myself. There [seems to be a way](http://gh-release-watch.com/) but I’d rather have an official way that gave me a notification, not send an email

<sup>2</sup> I do hope, however, it is now clear why some of the original reasoning is wrong, and that if the opinion stands it is with that in consideration.

**Comment by ndr-qef** [comment]
> Even aside from the Homebrew up-to-date-ness, Carthage is a developer-focused tool with no GUI (command-line only)—which seems quite different from kind of app that homebrew-cask means to help with.

I appreciate your concern, but scope would not be an issue. We welcome CLI software, from the [very popular](https://github.com/caskroom/homebrew-cask/blob/master/Casks/vagrant.rb) to the [rather less so](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cryptol.rb).

**Comment by rolandwalker** [comment]
Hi @jspahrsummers !

A vendor request for withdrawal has happened twice before, and we have honored it both times.

We appreciate your input and are sorry to see you go.

It is likely that someone will re-submit this Cask at some point.  We will try to remember your request when that happens: we are just starting a doc to store that sort of thing.

**Comment by jspahrsummers** [comment]
Thanks @rolandwalker!

**Pull request merged**
