### PR TITLE
osxfuse 4.1.2

### PR DESCRIPTION
**Pull request by getong**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you but as per the `caveats`:
```
==> Caveats
`osxfuse` has been succeeded by `macfuse` as of version 4.0.0.
```

**Comment by cho-m** [comment]
@miccal @vitorgalvao Do we want to consider adding the complicated `rename/depends_on` logic like `google-drive-file-stream`?

I had added the basic caveat text to hopefully direct people to renamed version.
Not too sure how many people pay attention to it though.

**Comment by miccal** [comment]
@cho-m I think that `osxfuse` may still be required across certain taps and elsewhere, so I would not recommend messing with it too much at this stage. We just need to hope that users read the `caveats` and be diligent that this one is not updated to version 4 by mistake.

**Comment by vitorgalvao** [comment]
> Do we want to consider adding the complicated `rename/depends_on` logic like `google-drive-file-stream`?

I never want to repeat that process. It’s plenty of work for a flimsy solution. Either we implement `cask_renames` or I’d rather break cask names as always.

**Pull request closed without merging**
