### PR TITLE
Add CoreLocationCLI v2.2.0

### PR DESCRIPTION
**Pull request by fulldecent**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

---

Previously this was in Homebrew main. This is a CLI open source app. BUT it requires signing because it uses CoreLocation and it no longer works in Homebrew main. That is why I am submitting to Homebrew Cask.

Discussion:

https://github.com/fulldecent/corelocationcli/issues/14

### CODE REVIEW

**Comment by miccal** [comment]
```
audit for corelocationcli: warning
 - possible duplicate, cask token conflicts with Homebrew core formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/corelocationcli.rb
```

Ping @vitorgalvao for review.

**Comment by numbermaniac** [comment]
It still exists in Homebrew - are you planning on removing it there first?

**Comment by vitorgalvao** [comment]
This is a CLI-only open-source tool. As stated, it belongs in [Homebrew/core](https://github.com/Homebrew/homebrew-core).

This policy is documented in [faq/rejected_casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/caskroom/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core). If it is rejected there, you may then try again in Homebrew-Cask (link us to the issue on Homebrew so we can see their reasoning for rejection).

It may only be added here if it’s remove from there, for some reason.

**Comment by fulldecent** [comment]
Removing, please see https://github.com/Homebrew/homebrew-core/pull/12109

**Review by vitorgalvao — APPROVED** [review]

**Comment by fulldecent** [comment]
Please note: audit failed per note above. This is ready for merge.

**Comment by vitorgalvao** [comment]
@fulldecent It’s only ready to merge after it’s removed from the core.

**Comment by ilovezfs** [comment]
@vitorgalvao :+1: from core for the migration.

**Comment by vitorgalvao** [comment]
Thank you, @ilovezfs.

**Comment by ilovezfs** [comment]
@vitorgalvao no problem. Core PR is merged! https://github.com/Homebrew/homebrew-core/pull/12109

**Pull request merged**
