### PR TITLE
updated flux (37.5)

### PR DESCRIPTION
**Pull request by reitermarkus**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by reitermarkus** [comment]
@caskroom/maintainers, this is working locally for me. Could someone verify?

**Comment by victorpopkov** [comment]
I'm getting the same latest appcast checkpoint as Travis audit suggests:
```
88362ca7fb6d733961d819c9ae2285678c060f91605179b4d536df6367816f10
```

**Comment by jawshooah** [comment]
I'm getting the same thing as @reitermarkus. Not sure what the issue is here.

**Comment by vitorgalvao** [comment]
I also get the same as in this PR.

**Comment by victorpopkov** [comment]
Tried getting it from Germany and I also get the same that was suggested in this PR that has `a83636ef44a20631d8a58ed06cbd8078b8349a15339bbe20dfd7d719a918bf89` checkpoint:
```xml
      <pubDate>Thu, 8 Aug 2016 10:00:00 +0000</pubDate>
      <enclosure url="https://justgetflux.com/mac/Flux37.5.zip"
               sparkle:version="37.5"
                   type="application/octet-stream" />
```
However, from my internet provider in Estonia, I get the same value that Travis does which has a checkpoint: `88362ca7fb6d733961d819c9ae2285678c060f91605179b4d536df6367816f10`.  This should be wrong, since even if download URL points to v37.5, the `sparkle:version` attribute still points to 37.2:
```xml
      <pubDate>Thu, 20 Jul 2016 10:00:00 +0000</pubDate>
      <enclosure url="https://justgetflux.com/mac/Flux37.5.zip"
               sparkle:version="37.2"
                   type="application/octet-stream" />
```
I suppose Travis check should be ignored in this case.

**Comment by adidalal** [comment]
Getting the same as @reitermarkus and @jawshooah locally

**Pull request merged**
