### PR TITLE
updated teamviewer (11.0.59131)

### PR DESCRIPTION
**Pull request by enavarrocu**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by adidalal** [comment]
Unless you can find an appcast url, this needs to stay unversioned

**Comment by enavarrocu** [comment]
What exactly that means?

**Comment by adidalal** [comment]
version and shasum will break when teamviewer updates, because there's no way to detect that. Thus, with an unversioned url, we use latest and don't check the checksum

**Comment by enavarrocu** [comment]
I see. The problem is when there is a new version you should use the --force flag to be able to install it.

**Comment by adidalal** [comment]
Yes, that is correct

**Pull request closed without merging**
