### PR TITLE
Create zoomus.rb interim solution

### PR DESCRIPTION
**Pull request by vitorgalvao**
**This is untested**. If you want to help, please test it and report back if it works for you.

It’s an interim workaround for https://github.com/Homebrew/homebrew-cask/pull/93802.

### CODE REVIEW

**Comment by miccal** [comment]
Should we also include instructions on how to handle the migratuioin manually:
```
rm -r /usr/local/Caskroom/zoomus; brew install --force zoom
```

**Comment by vitorgalvao** [comment]
If no user has tested by tomorrow, maybe we can merge this and go from there.

**Comment by sgerrand** [comment]
This broke for me, but using the nuclear option of `brew uninstall zoom zoomus ; brew install zoom` worked.

**Comment by vitorgalvao** [comment]
> This broke for me

Can you be more specific? We can’t consider a fix with no information.

**Comment by sgerrand** [comment]
Fair enough, apologies. Zoom disappeared from my installed applications. As
I mentioned earlier, I uninstalled both casks and installed the zoom call
to resolve the issue.

**Comment by MatisseHack** [comment]
Zoom disappeared from my Applications folder as well. Uninstalling and reinstalling it did fixed the issue.

**Pull request merged**
