### PR TITLE
Update skype to 8.9.0.1

### PR DESCRIPTION
**Pull request by commitay**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ondrejfuhrer** [comment]
@commitay Hey I just have a question regarding this PR. It is nice, that we have the version and sha check, but shouldn't it be visible (i.e. in the name), that this is a "Preview" version? The official download still gives version 7.*

**Comment by ondrejfuhrer** [comment]
Actualy even this version is old since now the Preview version is on 8.10.76.2 (the Preview versions get updated quite often)

**Comment by commitay** [comment]
`8.9.0.1` was the stable release yesterday. Currently I'm getting the old `7.59.37` version again, I think it might have been reverted to the old version. 

`skype-preview` is in versions: 
https://github.com/caskroom/homebrew-versions/blob/master/Casks/skype-preview.rb

**Comment by ondrejfuhrer** [comment]
Ah, ok, makes sense. I was cnfused since I was getting the version 7 today, I was not aware of the `skype-preview` version 👍

**Comment by commitay** [comment]
`8.9.0.1` can be downloaded from this page. 
https://www.skype.com/en/get-skype/

Blog post announcing the new release. 
https://blogs.skype.com/news/2017/10/30/the-new-skype-for-desktop-is-here/

It's strange that the skype.com landing page downloads the older version but this isn't a "preview" release.

Thank you anyway for checking, it's good to have people inspecting Casks!

**Pull request merged**
