### PR TITLE
Update CUDA to 7.5.18

### PR DESCRIPTION
**Pull request by pthariensflame**
Split from #13842.  This now includes a proper `uninstall` stanza.

### CODE REVIEW

**Comment by pthariensflame** [comment]
I'm not sure why this seems to fail still.  Can anyone help?

**Comment by victorpopkov** [comment]
I think that this cask installation can be automated by using the `installer :script`:
```ruby
  installer :script => "CUDAMacOSXInstaller.app/Contents/MacOS/CUDAMacOSXInstaller",
            :args => [ '--accept-eula', '--silent' ]
```
The source: http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-mac-os-x/#install

**Comment by pthariensflame** [comment]
Thanks!  I'll make that change as soon as I get back to my machine.  :)

**Comment by pthariensflame** [comment]
It still seems to be failing for no apparent reason.  D:

**Comment by victorpopkov** [comment]
Thank you for the contribution. It was merged directly as 24d6cb64114f80ca1b264a3c0b610b87d81aa160 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by pthariensflame** [comment]
Thanks!  :)

**Pull request closed without merging**
