### PR TITLE
Require macOS Sonoma for Whisky

### PR DESCRIPTION
**Pull request by IsaacMarovitz**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Hi @IsaacMarovitz, 

Thank you for opening this! Sonoma has not been officially released yet. Happy to merge it, but I want to make sure this is accurate.

**Comment by IsaacMarovitz** [comment]
> Thank you for opening this! Sonoma has not been officially released yet. Happy to merge it, but I want to make sure this is accurate.

Hiya, Whisky relies on GPTK which only runs on macOS Sonoma so this is accurate, thanks for checking!

**Comment by SMillerDev** [comment]
How can this require a OS bump without a version bump?

**Comment by razvanazamfirei** [comment]
Thanks for clarifying. I think it makes most sense for us to wait until `brew` officially supports Sonoma.

**Comment by IsaacMarovitz** [comment]
> How can this require a OS bump without a version bump?

It's been required since Whisky 1.2.0, I tried in that PR to simply do `> :ventura` but that didn't work so I assumed that brew didn't yet support specifying Sonoma as a requirement. I found that variable yesterday.

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
