### PR TITLE
Update chirp to 20170126 and rename to chirp-daily

### PR DESCRIPTION
**Pull request by colindunn**
* according to the [download](http://chirp.danplanet.com/projects/chirp/wiki/Download) page the versioning has moved to a daily build model (only on days there are changes) and versioning is now date based
* renamed to chirp-daily as per naming rules based on new application name

---

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]

**Comment by adidalal** [comment]
Do renames fall under tap_migrations/renames.json?

**Comment by colindunn** [comment]
I wasn't aware that HBC had one @adidalal ?

**Comment by adidalal** [comment]
Hmm, could have sworn we got that "for free" when we merge with Homebrew. Does that ring a bell, @vitorgalvao?

ie, a `formula_renames.json` should be handled by https://github.com/Homebrew/brew/blob/aaf70eb69656ab9f64a70c8daea4581c270766a6/Library/Homebrew/tap.rb#L451

IDK, now that you bring it up, actually. Always assumed we had it but never bothered to use it. Figured it would be good to start so as to stop "breaking" installs on renames.

**Comment by miccal** [comment]
Oh dear - I have renamed several Casks over my short time here, and never thought about this.

**Comment by colindunn** [comment]
Me too @miccal!

OK so I messed with it and can't get it to work.

Created a `formula_renames.json` file with just this:
```
{
  "chirp": "chirp-daily"
}
```

Reinstall:
```
> brew cask reinstall chirp
Error: undefined method `latest?' for nil:NilClass
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md

If this doesn’t fix the problem, please report this bug:
  https://github.com/caskroom/homebrew-cask#reporting-bugs

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:36:in `clear_cache'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:14:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:101:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:15:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:6:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:10:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:111:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:150:in `process'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/brew-cask.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

Removed it and attempted to install by name:
```
> brew cask install chirp
Error: No available Cask for chirp. Did you mean one of:
caskroom/cask/chirp-daily
caskroom/cask/chirp-daily
Error: nothing to install
```

Do you want me to add a comment about this to #29301 or start a new issue rather than continue here?

**Comment by adidalal** [comment]
Mind creating a new issue? (just reference this thread) & copy/paste should be fine to get the discussion rolling.

And @miccal not a problem - I think it's just something that's slipped off the radar but would be nice as the project matures

**Comment by colindunn** [comment]
Done @adidalal

**Pull request merged**
