### PR TITLE
handbrakecli: Move handbrakecli to homebrew

### PR DESCRIPTION
**Pull request by JMoVS**
related to https://github.com/Homebrew/homebrew-core/pull/8064

@ilovezfs 

**Please DON'T merge yet as the homebrew version isn't live yet!**

### CODE REVIEW

**Comment by ilovezfs** [comment]
:tada:

**Comment by sashkab** [comment]
I'm confused: handbrakecli was removed from casks, but was not added to the Homebrew. (PR Homebrew/homebrew-core#8064 was closed). What is the plan here now?

Thanks.

**Comment by ilovezfs** [comment]
8064 was merged.

**Comment by ilovezfs** [comment]
Specifically,
https://github.com/Homebrew/homebrew-core/commit/b69e72e563c9f804474d1e6719918d81dd3d415b
https://github.com/Homebrew/homebrew-core/commit/ebf0526fd808266593f6704b95e7eccb2176d9e0

**Comment by sashkab** [comment]
@ilovezfs thanks -- was still looking for the handbrakecli in homebrew, didn't notice it was named handbrake. :)

**Pull request merged**
