### PR TITLE
Update vesta to 3.4.4

### PR DESCRIPTION
**Pull request by singularitti**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by singularitti** [comment]
Before this the sha256 of cask `vesta` is outdated, and impedes user installation.

**Comment by commitay** [comment]
`sha256` only changes need to be verified. See [updating the `sha256`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256) for how to provide verification.

**Comment by singularitti** [comment]
If I understand correctly, the details of verification is [available here](https://www.virustotal.com/#/file/bd41a8863d4dc75d4e511bb4f5588c548740767781b4a1cfcea3dd5ca9465f1e/details). The `version` is still 3.4.4 according to [official website](http://jp-minerals.org/vesta/en/download.html).

**Comment by commitay** [comment]
The app isn't codesigned, the developers will need to confirm that the sha256 change is legimate.

**Comment by singularitti** [comment]
What shall I do? Do I need to contact the developers?

**Comment by brianmorton** [comment]
@singularitti they have forums that you may be able to contact the developer on: http://jp-minerals.org/vesta/en/forum.html

**Comment by singularitti** [comment]
@brianmorton Thanks for pointing out. I have sent to `vesta.dev@gmail.com` an email on June 15th 2018. But did not get a reply. I will try to post on the forum.

**Comment by singularitti** [comment]
@brianmorton The developer has replied me today. Unfortunately it does not appear on the mailing list. Here is the message:
gitscout-image-from-clipboard-1

**Comment by brianmorton** [comment]
@commitay would have to weigh in, but generally if the change isn't confirmed in public it isn't considered valid (since it would be conceivable that some people could fabricate it).

**Comment by vitorgalvao** [comment]
> but generally if the change isn't confirmed in public it isn't considered valid (since it would be conceivable that some people could fabricate it).

That is correct. The instructions specify that.

**Comment by brianmorton** [comment]
@vitorgalvao if you look through the thread, the dev did confirm that they did an update-in-place of the binary. Is that enough for the checksum to be updated here, or does the dev have to explicitly confirm the new checksum?

**Comment by singularitti** [comment]
I have no idea why the developer's reply did not appear on the list. And I am just wondering why it is not possible for you to download the app yourselves and run `shasum` even you have already known its official website?

**Comment by vitorgalvao** [comment]
> if you look through the thread, the dev did confirm that they did an update-in-place of the binary. Is that enough for the checksum to be updated here

In light of https://github.com/Homebrew/homebrew-cask/issues/48862, I’d say so.

> And I am just wondering why it is not possible for you to download the app yourselves and run `shasum` even you have already known its official website?

I don’t understand the question.

**Pull request merged**
