### PR TITLE
Update reaper to 5.97.300

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
thanks for the flood or PRs ;)

can we stick to the previous version number format on this one? i.e. '5.97.300'

**Comment by ran-dall** [comment]
> can we stick to the previous version number format on this one? i.e. '5.97.300'

It really makes to little difference to me, now that I'm aware of this particular one having the version number run this way. I can update it on my side.

**Comment by core-code** [comment]
thanks!

**Comment by ran-dall** [comment]
Also, just as a side-note, I'm trying to make this the first thing I do every day; so the flood of PRs happens early and we're not dragging PRs all day and/or I get distracted with something. I would appreciate if you guys (@core-code and @suschizu) keep getting the lists to me early (thank you BTW 👏) so I can continue the flood 🌊.

**Pull request merged**
