### PR TITLE
Add appcast and update URLs for ZeroTier One Cask

### PR DESCRIPTION
**Pull request by ProbablyRusty**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

For ZeroTier One (latest) CasK:

- Add appcast and checkpoint
- Update url
- Update homepage
- Make pkg id explicit (no wildcard)

### CODE REVIEW

**Comment by consultantRR** [comment]
As of this PR, the ZeroTier One.pkg version is 1.1.14.

**Comment by vitorgalvao** [comment]
Add a `version` and an `sha256`. Unversioned casks with `appcasts` still have them.

**Comment by consultantRR** [comment]
The pkg download url for `ZeroTier One.pkg` is unversioned. What is preferable? Remove `appcast` or make `version` explicit in the formula?

**Comment by vitorgalvao** [comment]
*Add* the `version` and `sha256`. Leave the `appcast`.

**Comment by consultantRR** [comment]
732588923acba241b5e32478976ed58384c47e17

**Pull request merged**
