### PR TITLE
Update LaTeXiT to 2.8.1

### PR DESCRIPTION
**Pull request by reitermarkus**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by fanquake** [comment]
You need to update the appcast
```
 - appcast checkpoint mismatch
Expected: b2acb7c6fa3a029c8711308da5b2bc6835fb878cfa1ec374159c4d7e2e69f3f2
Actual: 333bb3345415572bfd428d12d56afa026820c2bf13d3510160994911818962cc
```

**Comment by reitermarkus** [comment]
Well, `audit --download` was working for me with the checksum.

```
 - appcast checkpoint mismatch
Expected: 333bb3345415572bfd428d12d56afa026820c2bf13d3510160994911818962cc
Actual: b2acb7c6fa3a029c8711308da5b2bc6835fb878cfa1ec374159c4d7e2e69f3f2
```

**Comment by jawshooah** [comment]
@reitermarkus I recently fixed how `audit` calculates the checkpoint, `brew update` and try again locally.

**Comment by reitermarkus** [comment]
Did a rebase, didn't change anything.

**Comment by jawshooah** [comment]
Ah, it's because we're getting a 403 (Forbidden) HTTP return code:

```
audit for latexit: warning
 - unexpected HTTP response code retrieving appcast: 403
 - appcast checkpoint mismatch
Expected: b2acb7c6fa3a029c8711308da5b2bc6835fb878cfa1ec374159c4d7e2e69f3f2
Actual: 333bb3345415572bfd428d12d56afa026820c2bf13d3510160994911818962cc
```

And the actual text returned:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /latexit/downloads/latexit-sparkle-en.rss
on this server.</p>
</body></html>
```

Could this be a User-Agent issue? I'm able to view the RSS in the browser.

**Comment by reitermarkus** [comment]
Stand-alone `curl` works for me:

```
$ curl -sI 'http://pierre.chachatelier.fr/latexit/downloads/latexit-sparkle-en.rss'
HTTP/1.1 200 OK
Date: Wed, 13 Jul 2016 12:26:37 GMT
Content-Type: application/rss+xml
Content-Length: 29909
Server: Apache
Last-Modified: Mon, 07 Sep 2015 21:20:41 GMT
Accept-Ranges: bytes
Age: 106043
Warning: 113 localhost (squid/3.5.12) This cache hit is still fresh and more than 1 day old
X-Cache: HIT from localhost
X-Cache-Lookup: HIT from localhost:3129
Via: 1.1 localhost (squid/3.5.12)
Connection: keep-alive
```

**Comment by reitermarkus** [comment]
Yes, directly on my router I also get:

```
HTTP/1.1 403 Forbidden
Set-Cookie: mailplanBAK=R2555566638; path=/; expires=Thu, 14-Jul-2016 19:14:20 GMT
Date: Thu, 14 Jul 2016 17:56:34 GMT
Content-Type: text/html; charset=iso-8859-1
Set-Cookie: mailplan=R1919058564; path=/; expires=Thu, 14-Jul-2016 19:07:09 GMT
Server: Apache
Vary: Accept-Encoding

```

**Comment by jawshooah** [comment]
Yup, same for me:

```
$ curl -sI 'http://pierre.chachatelier.fr/latexit/downloads/latexit-sparkle-en.rss'
HTTP/1.1 403 Forbidden
Set-Cookie: mailplanBAK=R2555562282; path=/; expires=Thu, 14-Jul-2016 19:14:02 GMT
Date: Thu, 14 Jul 2016 17:55:29 GMT
Content-Type: text/html; charset=iso-8859-1
Set-Cookie: mailplan=R1919058564; path=/; expires=Thu, 14-Jul-2016 19:09:34 GMT
Server: Apache
Vary: Accept-Encoding
```

Not really sure what's going on there.

**Comment by jawshooah** [comment]
On a different note, please use `https` for the `url` and `appcast`.

**Comment by reitermarkus** [comment]
We could try using this url `https://pierre.chachatelier.fr/latexit/downloads/latexit-version-current`, which is really nice of the developer to provide. =)

**Comment by reitermarkus** [comment]
Ok, so we would need to be able to set `:user_agent` on an `appcast` stanza.

**Comment by vitorgalvao** [comment]
We don’t need `user_agent:` on `appcast`. That’s be useless since `appcast` isn’t directly interacted with, you’re supposed act on it via external means, so `user_agent:` would do nothing.

The only thing we need if for `audit` itself to fake the user agent. This porblem as surfaced before, and the correct command to calculate `checkpoint` does indeed include browser headers (see [`find_sparkle_appcast`](https://github.com/caskroom/homebrew-cask/blob/9ac460b3b4ddf6a04b82590f72bb9ac9be06ed40/developer/bin/find_sparkle_appcast#L57) and [`cask-repair`](https://github.com/vitorgalvao/tiny-scripts/blob/b4cdb219f63b8eaff983affa5d89f7a4c37d565b/cask-repair#L177)). Likely what happened is just that I forgot to update the documentation after fixing it in those scripts.

**Comment by vitorgalvao** [comment]
Verified locally as correct and passing.

**Pull request merged**
