### PR TITLE
Remove old Coriolis Systems software.

### PR DESCRIPTION
**Pull request by al45tair**
I'd prefer that this only be distributed through the https://coriolis-systems.com website directly. That way people get to read what's written there, whereas installing using Homebrew doesn't do that.

To be clear, I'm not 100% opposed to Homebrew being able to install it, but if it's going to do that it should probably fetch the appropriate license file and install that at the same time, and it would be nice if it also told people they should read about it on the website.

(It would also have been nice had whoever added it in the first place actually asked whether it was OK, or even mentioned it at all. I realise Homebrew is just downloading it and isn't doing anything wrong by doing that, but it would still have been nice had someone got in touch.)

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> To be clear, I'm not 100% opposed to Homebrew being able to install it, but if it's going to do that it should probably fetch the appropriate license file and install that at the same time, and it would be nice if it also told people they should read about it on the website.

Is anything that Homebrew or our users are doing here in violation of the license? What part do you want people to have read and why?

> (It would also have been nice had whoever added it in the first place actually asked whether it was OK, or even mentioned it at all. I realise Homebrew is just downloading it and isn't doing anything wrong by doing that, but it would still have been nice had someone got in touch.)

Sorry, this isn't a terribly practical ask. It doesn't scale. 

---

I feel like there's a missing subtext here with the problem you're experiencing due to this being in Homebrew Cask. Can you elaborate a bit?

**Comment by al45tair** [comment]
> > To be clear, I'm not 100% opposed to Homebrew being able to install it, but if it's going to do that it should probably fetch the appropriate license file and install that at the same time, and it would be nice if it also told people they should read about it on the website.
> 
> Is anything that Homebrew or our users are doing here in violation of the license? What part do you want people to have read and why?

Strictly speaking, no, as in fact I indicated fairly clearly in the following paragraph. However, this isn't about the license. The reason the software is still available is that I'm paying — personally — to host it, which I did largely for the benefit of customers who had bought it, though it also benefits people who didn't purchase it and people who are interested in using older systems for whatever reason.

If you visit the website, you'll find that it talks a bit about the history of the software and mentions some of the people responsible for creating it and supporting it. I don't think it's much to ask that they get a bit of credit, particularly where people who didn't purchase the product when it was on sale are downloading it, and I honestly think that automating the install through Homebrew removes that.

That's not the only objection I have, either. The Homebrew casks download the software but not the associated license file. The upshot is that I now have people asking me to support their use of the Homebrew cask (the website, on the other hand, makes clear there is no support available, and puts the license file links clearly below the product links themselves).

Much of that is _potentially_ fixable in the cask file, _but I can't contribute fixes to the cask files because of my employer's policies on Open Source_. What I _can_ do is ask for them to be removed for now, which is what I've done.

> > (It would also have been nice had whoever added it in the first place actually asked whether it was OK, or even mentioned it at all. I realise Homebrew is just downloading it and isn't doing anything wrong by doing that, but it would still have been nice had someone got in touch.)
> 
> Sorry, this isn't a terribly practical ask. It doesn't scale.

It scales at least as well as writing the cask in the first place.

> I feel like there's a missing subtext here with the problem you're experiencing due to this being in Homebrew Cask. Can you elaborate a bit?

There's no missing subtext. The software is, in fact, my property, and was created by me and by others working for me. It's being downloaded from a website that is also my property and that I pay for. I don't think I'm being at all unreasonable here. I'm not stopping anyone downloading it — I would just like them to do so by actually visiting the website.

**Comment by MikeMcQuaid** [comment]
> The upshot is that I now have people asking me to support their use of the Homebrew cask (the website, on the other hand, makes clear there is no support available, and puts the license file links clearly below the product links themselves).

This is a reasonable thing to request and I agree this should be addressed in the casks 👍🏻 

> Much of that is _potentially_ fixable in the cask file, _but I can't contribute fixes to the cask files because of my employer's policies on Open Source_.

I find it surprising that your employer would be happy with a pull request deleting these files but not one fixing these files.

Relatedly, I'd hope that your employer doesn't use any open source if they are unwilling to allow their employees to contribute fixes to it.

> I'm not stopping anyone downloading it — I would just like them to do so by actually visiting the website

Sure, you've made that clear. Those people who use it though Homebrew Cask, though, would seemingly rather not do that and, from our analytics, there's still people using these casks: https://formulae.brew.sh/analytics/cask-install/365d/

I think the options here are:
1) you block Homebrew from downloading these files. Our user-agent is not user-customisable specifically to give you the ability to do this. I can provide guidance on what this string is if desired. This will stop Homebrew Cask users from installing this software through Homebrew and will result in them being deleted, breaking their workflows.
2) we merge this PR. This will stop Homebrew Cask users from installing this software through Homebrew and will result in them being deleted, breaking their workflows.
3) someone (not me or you, it sounds like) fixes these casks to install the license files. This will allow Homebrew Cask users to continue to install this software using their existing workflows. 
4) something else I haven't thought of

If we showed zero installs in our analytics, I'd agree that 2) is the best option. As-is, though, I feel we as Homebrew maintainers shouldn't really do that to our users. 1) is entirely in your court, I'm neither going to encourage nor discourage you from doing so.

3) sounds like the best bet here.

**Comment by al45tair** [comment]
> I find it surprising that your employer would be happy with a pull request deleting these files but not one fixing these files.

I'm not going to be drawn into a discussion about our policies on Open Source contributions, other than to say that I think it's possible to spin "please just delete these two files" as "not a contribution", but writing cask files would very much not be.

> 1. you block Homebrew from downloading these files. Our user-agent is not user-customisable specifically to give you the ability to do this. I can provide guidance on what this string is if desired. This will stop Homebrew Cask users from installing this software through Homebrew and will result in them being deleted, breaking their workflows.
> 2. we merge this PR. This will stop Homebrew Cask users from installing this software through Homebrew and will result in them being deleted, breaking their workflows.

It's a shame that deleting the casks causes Homebrew to delete things. I agree, FWIW, that that is undesirable.

> 3. someone (not me or you, it sounds like) fixes these casks to install the license files. This will allow Homebrew Cask users to continue to install this software using their existing workflows.
> 4. something else I haven't thought of
> 
> If we showed zero installs in our analytics, I'd agree that 2) is the best option. As-is, though, I feel we as Homebrew maintainers shouldn't really do that to our users. 1) is entirely in your court, I'm neither going to encourage nor discourage you from doing so.
> 
> 3. sounds like the best bet here.

That would be idea, but I doubt anyone has any motivation to do the work. I would, but I can't.

I'll have a think about what to do; there might be some other option that we haven't thought of yet. In the meantime I'll close this PR.

**Comment by MikeMcQuaid** [comment]
thanks @al45tair, appreciate it ❤️

**Comment by bevanjkay** [comment]
Just to add a small point to the conversation here, there is mini-dsl for the caveats stanza prompting the user to follow a link to download a free license on install.
Screen Shot 2022-02-18 at 9 27 26 am

https://docs.brew.sh/Cask-Cookbook#caveats-mini-dsl

```ruby
  caveats do
    free_license "https://coriolis-systems.com/"
  end
```

**Pull request closed without merging**
