### PR TITLE
QSyncthingTray: depends on the cask

### PR DESCRIPTION
**Pull request by MoOx**
Following https://github.com/caskroom/homebrew-cask/pull/17290

For now you have a cask recipe, [which provide a better UX](https://github.com/caskroom/homebrew-cask/pull/17290#issuecomment-172554059), so we should depend on that one [for now](https://github.com/caskroom/homebrew-cask/pull/17290#issuecomment-172693448).

### CODE REVIEW

**Comment by adidalal** [comment]
Thank you for the contribution. It was merged directly as 22a9e0bbb69610fce1bc0b953483e5a8f62b7553 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by MoOx** [comment]
Thanks (ps I don't care about the credit ^^)
Btw, I guess you have a easy command to merge PR this way? Could you share?

**Comment by adidalal** [comment]
[`fastmerge`](https://github.com/vitorgalvao/tiny-scripts/blob/master/fastmerge): Install via `brew install vitorgalvao/tiny-scripts/fastmerge`

See also: `prfixmaster`/`prfixbranch`and `cask-repair` in the same repo

**Comment by MoOx** [comment]
Thanks!

**Comment by adidalal** [comment]
e.g. FYI #17533 could have been mostly automated with `cask-repair`

https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask

**Comment by MoOx** [comment]
I just saw that. Thanks again.

**Pull request closed without merging**
