### PR TITLE
Update postman from 8.11.1 to 8.12.0

### PR DESCRIPTION
**Pull request by ykursadkaya**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Thanks @ykursadkaya

**Comment by vitorgalvao** [comment]
This is not the version listed on the website, or returned by `livecheck`. This seems to be a beta. Reverting in https://github.com/Homebrew/homebrew-cask/pull/110970.

**Comment by bevanjkay** [comment]
@vitorgalvao It's been a shocking week for releases being unpublished. Thanks for fixing it up 👍🏻

**Comment by Moulick** [comment]
I think I remember postman itself asking to update to 8.12 a few days ago, did they revert the update ?

**Comment by vitorgalvao** [comment]
> did they revert the update ?

You’ll have to ask them. Unless they provide us with their appcast, we’ll follow what’s on the homepage.

**Pull request merged**
