### PR TITLE
Add microsoft-remote-desktop v10.1.7

### PR DESCRIPTION
**Pull request by ahousseini**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by ahousseini** [comment]
From here: https://macadmins.software

**Comment by commitay** [comment]
We've had PRs with URLs from that site submitted previously that we have had to refuse, see https://github.com/caskroom/homebrew-cask/pull/41092

**Comment by ahousseini** [comment]
This site is running by a few employees from Microsoft: https://macadmins.software/slack.html. The site is not providing the installers, just the direct links. These guys are running this site just for supporting all Mac Admins. But I can understand if you don't accept this pull request.

**Comment by commitay** [comment]
Closing as without a suitable homepage the URL cannot be verified as official.

Thanks for the PR nonetheless!

**Pull request closed without merging**
