### PR TITLE
orka: add zap

### PR DESCRIPTION
**Pull request by jazelly**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]
Thank you for your first contribution to Homebrew @jazelly!

**Comment by bevanjkay** [comment]
@jazelly Are you sure that these files are related to `orka`, from what I can see they are cache files for Apple Music images.

**Comment by p-linnane** [comment]
@bevanjkay You are right. I mixed up some tabs when reviewing this 🤦‍♂️

**Comment by p-linnane** [comment]
https://github.com/Homebrew/homebrew-cask/pull/145765

**Comment by jazelly** [comment]
You are right. Sorry, I'll check closely and update the PR

**Pull request merged**
