### PR TITLE
Add LG Dual Controller

### PR DESCRIPTION
**Pull request by rioriost**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by miccal** [comment]
I think this will need to be submitted to [homebrew-cask-drivers](https://github.com/Homebrew/homebrew-cask-drivers).

**Comment by rioriost** [comment]
Sorry, I'm not sure whether the package should be classified into cask-drivers or not.
I listed all the files included in the packages consisting of Dual Controller. It doesn't seem to include kext or something.

```
% for pkg in `pkgutil --pkgs | grep lge`; do pkgutil --only-files --files $pkg; done | sed 's/^.*\.\([^\.]*\)$/\1/' | sort -u 
app/Contents/MacOS/Dual Controller
app/Contents/PkgInfo
app/Contents/_CodeSignature/CodeResources
bmp
car
css
dylib
h
html
icns
jpg
js
mom
nib
omo
plist
png
rtf
strings
ttf
unInstall
```

**Comment by miccal** [comment]
@rioriost the term `driver` is taken to mean: [if the software is useless without the peripheral, it’s considered a driver](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask)

**Comment by rioriost** [comment]
@miccal san, Thanks! I understand the policy that I need to obey for Homebrew cask. I'll submit it to cask-driver later.

**Pull request closed without merging**
