### PR TITLE
rio 0.0.32

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by krehel** [comment]
Hi @raphamorim - 

Error: It seems the symlink source '/usr/local/Caskroom/rio/0.0.32/Rio.app/Contents/Resources/72/rio' is not there.

Is this intentional in the latest release?  We link this into TERMINFO.

**Comment by raphamorim** [comment]
Hmmm, isn't intentional will cut another version. Sorry about it @krehel

**Comment by krehel** [comment]
No worries @raphamorim - thought you might want to know in case it was accidental on your side! 😄 Happy to help

**Comment by raphamorim** [comment]
Not sure what happened, I built again with same code and the terminfo was included this time. I've updated the same release artifact with the terminfo

Screenshot 2023-12-13 at 16 05 58

> No worries @raphamorim - thought you might want to know in case it was accidental on your side! 😄 Happy to help

Thank you!! 🙏

**Comment by krehel** [comment]
Looks great now @raphamorim!  Thank you for your help!

**Comment by raphamorim** [comment]
Thank you for the heads up! @krehel 🙏

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
