### PR TITLE
Update retroarch-metal from 1.10.1 to 1.10.2

### PR DESCRIPTION
**Pull request by ianrobrien**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by krestaino** [comment]
I'm getting the following error while trying to update to `1.10.2`.

```
Error: retroarch-metal: SHA256 mismatch
Expected: 36b1efd95f3a113146b2af00da6a71638aa9cca5ea869c18e461158dc2d236d9
  Actual: 25b374df1009b27d89c97892ac1df69ec2f4cd78b99183ee5395b1acefca7fcc
    File: /Users/Kevin/Library/Caches/Homebrew/downloads/60de44ad39a58b3047a600fe9d3780c183d52819ea041ce83c22f0271456dc3c--RetroArch_Metal.dmg
```

Manually downloading the file and comparing the hash I see it's `25b374df1009b27d89c97892ac1df69ec2f4cd78b99183ee5395b1acefca7fcc`.

**Comment by ianrobrien** [comment]
I see this happen a lot with retroarch-metal but I haven't yet figured out why this happens. I just manually downloaded from the link [Download Stable (Metal)](https://buildbot.libretro.com/stable/1.10.2/apple/osx/universal/RetroArch_Metal.dmg) and got the same hash from this file.

`brew upgrade` also ran successfully with the expected hash here. (`36b1efd95f3a113146b2af00da6a71638aa9cca5ea869c18e461158dc2d236d9`)

Can you try again and see if you have the same issue?

**Comment by krestaino** [comment]
Yeah it works now, strange. Thanks!

**Comment by pwatk** [comment]
This is still broken.

If I download [RetroArch_Metal.dmg](https://buildbot.libretro.com/stable/1.10.2/apple/osx/universal/RetroArch_Metal.dmg) I get this sha256 checksum: `c2580e719094dd1ef97ac0965e5a167616373981a0620b21893261122a78ce29` which is the same checksum I'm getting from brew:
```
Error: retroarch-metal: SHA256 mismatch
Expected: 36b1efd95f3a113146b2af00da6a71638aa9cca5ea869c18e461158dc2d236d9
  Actual: c2580e719094dd1ef97ac0965e5a167616373981a0620b21893261122a78ce29
```

**Comment by BountyChocolate123456** [comment]
I also get c2580e719094dd1ef97ac0965e5a167616373981a0620b21893261122a78ce29, so I've raised a PR

https://github.com/Homebrew/homebrew-cask/pull/121598/files

**Comment by pwatk** [comment]
Thank you

**Pull request merged**
