### PR TITLE
Update setapp to 1.18.1,1539860348

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
We still need an `uninstall`.

**Comment by brianmorton** [comment]
Well that didn't go as I thought it would. I thought if I put something nonsensical in the `uninstall` that travis would tell me what actually needed to be installed... instead it passed. What would you like to do now?

**Comment by commitay** [comment]
It's `installer manual`, the script doesn't exist on Travis but it will for users?

**Comment by brianmorton** [comment]
@commitay when I unpacked it manually it didn't exist

**Comment by commitay** [comment]
The script does exist after running the installer.

@Homebrew/cask I think we might need to come up with a way to get casks that will always fail install/uninstall to play nice on CI, maybe blacklisting stuff like this, `virtualbox`, etc so it only checks audit and style.

**Comment by brianmorton** [comment]
So do you want to update this PR (restore it maybe) to what it should be and open a separate issue for blacklisting these type of casks from travis?

**Pull request merged**
