### PR TITLE
Update wechat to 2.3.26.17

### PR DESCRIPTION
**Pull request by ElfSundae**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by fanvinga** [comment]
As a suggestion, I think it is more appropriate to update the content of the zap operation to the following content.
```
  zap trash: [
               '~/Library/Application Scripts/com.tencent.xinWeChat',
               '~/Library/Containers/com.tencent.xinWeChat',
               '~/Library/Preferences/com.tencent.xinWeChat.plist',
               '~/Library/Cookies/com.tencent.xinWeChat.binarycookies',
               '~/Library/Group Containers/$(TeamIdentifierPrefix)com.tencent.xinWeChat',
             ]
```

**Comment by fanvinga** [comment]
https://github.com/fanvinga/homebrew-cask/commit/99d2edc9215a5892bdefcc637c3bab4ace8f3674

**Comment by ElfSundae** [comment]
@fanvinga Yeah, also `~/Library/Caches/com.tencent.xinWeChat`

**Comment by fanvinga** [comment]
@ElfSubdae App-Cleaner is a fantastic app :-)
```
brew cask install app-cleaner
```

**Comment by ElfSundae** [comment]
https://github.com/Homebrew/homebrew-cask/pull/66784

**Comment by ElfSundae** [comment]
@fanvinga I have been using [AppCleaner](http://freemacsoft.net/appcleaner/) for years, which is totally free 😄

**Comment by vitorgalvao** [comment]
Download is failing.

**Comment by fanvinga** [comment]
@vitorgalva I think the reason for the download failure may be Travis' own network problem. I tested it in the environment of multiple network providers such as Azure/Vultr/DigitalOcean and can download it normally, and I can find that the file uses Akamai as the CDN provider.
image

**Comment by fanvinga** [comment]
It is also possible that the download was affected by the CDN cache.

**Comment by ElfSundae** [comment]
Can we restart the CI task?

**Comment by core-code** [comment]
according to the version number embedded into the app this is still version 2.3.25 ;/

**Pull request merged**
