### PR TITLE
Also display installed versions in brew-cask info

### PR DESCRIPTION
**Pull request by bgandon**
Because brew-cask info does not always display installed versions,
this code runs throught versions in metadata and displays info
about them.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Pinging @ndr-qef @radeksimko.

**Comment by vitorgalvao** [comment]
We’ll be having some changes in the future that should render this unecessary, but I’ll keep it open for now.

**Comment by bgandon** [comment]
Interesting! Do you have any link to IRC log, blog post, mailing list or any resource describing those future changes?

**Comment by vitorgalvao** [comment]
Not yet. Should be out this week, though, with a link to the document form the README.

**Comment by vitorgalvao** [comment]
Here are the news: #13201. Thank you for working on this, but it will no longer be needed.

**Pull request closed without merging**
