### PR TITLE
Add TidGi.app v0.6.6

### PR DESCRIPTION
**Pull request by linonetwo**
https://github.com/tiddly-gittly/TidGi-Desktop

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@linonetwo because the URL is versioned, we can't use `:no_check`. Can you please add the correct value and also run `brew style <token> --fix` to correct the style offences. 

Thank you!

**Comment by linonetwo** [comment]
Wow, I have just create a new file, why will there be conflict?

**Comment by bevanjkay** [comment]
@linonetwo We are running into an ocassional bug on this repo where it will incorrectly flag conflicts, it should be okay now. Regarding the `style` fix, the CI run only checks the style but it doesn't fix it.

**Comment by bevanjkay** [comment]
Thank you @linonetwo  🎉

**Pull request merged**
