### PR TITLE
little-snitch@5 5.8

### PR DESCRIPTION
**Pull request by holser**
5.8 is compatible with MacOS 15.0 Sequioia

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ x ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ x  ] `brew audit --cask --online <cask>` is error-free.
- [ x  ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ x  ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ x  ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ x ] `brew audit --cask --new <cask>` worked successfully.
- [ x ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ x ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by holser** [comment]
CI won't pass as cask checks the version in [plist](https://sw-update.obdev.at/update-feeds/littlesnitch5.plist) and fails as it gets version mismatch

**Comment by p-linnane** [comment]
This release is specific to Sequoia only, which is probably why the plist hasn't been updated to point everyone to it.

**Comment by holser** [comment]
I guess we should check https://sw-update.obdev.at/products/littlesnitch/releasenotes-swu-5.html instead of plist. Alternatively I can disable plist verification in Cask

**Comment by p-linnane** [comment]
The cask needs to be reworked to offer 5.8 on macOS Sequoia, and 5.7.6 for other macOS versions. Perhaps @samford can provide some insight on the best way to handle this. We should not remove the plist check simply because it is not working for this limited release.

**Review by samford — COMMENTED** [review]
Checking the plist file aligns with what the app checks but it's not clear why they haven't added 5.8. The first-party [download page for old releases](https://www.obdev.at/products/littlesnitch/download-previous-versions.html) and [release notes for v5](https://www.obdev.at/products/littlesnitch/releasenotes5.html) both reference 5.8 but explain that it's only for Sequoia.

How we approach this depends on if upstream is going to continue creating 5.7.x versions for macOS versions lower than Sequoia or if 5.7.6 is the last pre-Sequoia release and new versions will all be 5.8+. Looking at the [release notes for v4](https://www.obdev.at/products/littlesnitch/releasenotes4.html), they didn't release any 4.5.x versions after 4.6 introduced a Catalina requirement. The language is a bit different for 5.8 but it may be reasonable to assume that 5.7.6 is the last pre-Sequoia version and they will simply continue on from 5.8.

With that in mind, we can use a similar approach as `little-snitch@4`, where we use a `skip` `livecheck` block in the older macOS block. The tricky part here is that the plist file doesn't list 5.8 yet (only 5.7.6 and an old nightly). It may just be that they haven't updated the file yet but we can check the download page for older releases for the time being.

I'll push a commit in a moment to handle the version setup for older macOS versions.

**Review by khipp — APPROVED** [review]
Thank you!

**Pull request merged**
