### PR TITLE
Add tamarin-prover 1.0.0

### PR DESCRIPTION
**Pull request by mpdehnel**
### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:
- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but since this is an open-source CLI-only tool, it should first be submitted to Homebrew. Only if not accepted there should it be submitted here.

**Comment by mpdehnel** [comment]
Hi, thanks for your response.

Due to various issues with compilation of certain versions with the latest version of Mac OS X, it's not currently possible to submit to Homebrew. My aim is to submit it to Homebrew once we've sorted those issues out, but I have no idea when that will be (up to 1-2 years potentially). As such, so that people can use and install Tamarin Prover more easily, we hoped that it would get accepted in to Cask.

If you could accept this PR I would be very grateful. Please do ask if you require any more details.

Thanks,

Martin

**Comment by vitorgalvao** [comment]
Very well, then.

**Comment by mpdehnel** [comment]
Many thanks, I really appreciate it!

Martin

**Pull request merged**
