### PR TITLE
cosmosdb-dmt 2.1.4 (new cask)

### PR DESCRIPTION
**Pull request by crpietschmann**
The Azure Cosmos DB Desktop Data Migration Tool is an open-source project containing a command-line application that provides import and export functionality for Azure Cosmos DB.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by crpietschmann** [comment]
FYI, I am a Developer on the Azure Cosmos DB Data Migration Tool project (https://github.com/AzureCosmosDB/data-migration-desktop-tool). I may need to follow up with getting the binary signed with Apple for macOS installation, if there's no workaround to get this cask committed to Homebrew.

Is there a flag to get the Cask submitted without the Apple binary signing?

**Comment by krehel** [comment]
> FYI, I am a Developer on the Azure Cosmos DB Data Migration Tool project ([AzureCosmosDB/data-migration-desktop-tool](https://github.com/AzureCosmosDB/data-migration-desktop-tool)). I may need to follow up with getting the binary signed with Apple for macOS installation, if there's no workaround to get this cask committed to Homebrew.
> 
> Is there a flag to get the Cask submitted without the Apple binary signing?

We cannot accept it at this time because it does not pass our signature verification check that is a requirement for new submissions.  The binary should be signed and notarized for acceptance.

**Comment by crpietschmann** [comment]
> > FYI, I am a Developer on the Azure Cosmos DB Data Migration Tool project ([AzureCosmosDB/data-migration-desktop-tool](https://github.com/AzureCosmosDB/data-migration-desktop-tool)). I may need to follow up with getting the binary signed with Apple for macOS installation, if there's no workaround to get this cask committed to Homebrew.
> > Is there a flag to get the Cask submitted without the Apple binary signing?
> 
> We cannot accept it at this time because it does not pass our signature verification check that is a requirement for new submissions. The binary should be signed and notarized for acceptance.

Thanks for clarification. I'm going to close this PR for now then. We'll have to circle back to this accordingly in the future.

**Comment by krehel** [comment]
@crpietschmann - can this be built entirely from source and is a CLI app?  If so it probably would be better as a Formula in homebrew-core instead of a Cask.

**Pull request closed without merging**
