### PR TITLE
Update nestopia to 1.4.2

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
i've updated the cask because it fails to install because the download now contains a folder with the version number. i'm not sure if there is a way to support that without introducing the version number into the cask.

**Comment by adidalal** [comment]
The cask will break on update immediately - is there an appcast that can be monitored so we can minimize that time?

**Comment by core-code** [comment]
didn't find any. btw nestopia 1.4.2 now seems to require 10.11, should the cask be updated to note that?

**Comment by vitorgalvao** [comment]
> btw nestopia 1.4.2 now seems to require 10.11, should the cask be updated to note that?

Yes, please.

**Pull request merged**
