### PR TITLE
Update 1password to 6.6.1

### PR DESCRIPTION
**Pull request by kpearson**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by fincle** [comment]
This one was already submitted over 19 hours ago.

**Comment by giannitm** [comment]
There are at least 3 pull requests for 1password at the moment? (can tell that it's a popular application)

**Comment by fincle** [comment]
It could also be that they hit a road bump this week with some certificates issues: https://blog.agilebits.com/2017/02/19/1password-for-mac-6-5-5-manual-update-required/

Everything seized up and there have been a flurry of updates for versions of the software that were downloaded directly from their website (that includes homebrewers).

**Comment by vitorgalvao** [comment]
#30359.

**Pull request closed without merging**
