### PR TITLE
Update cpumeter url

### PR DESCRIPTION
**Pull request by yusukeshib**

### CODE REVIEW

**Comment by adidalal** [comment]
Thank you for the contribution. It was merged directly as 26a14c4b78e6b959e02e07a00968803ff12b4e1c to keep commit history cleaner. Your contribution is still credited to you.

**Comment by adidalal** [comment]
Thank you for the contribution. It was merged directly as 1fed864ed5a4e9f4ceed4897722f529d7f9e053f to keep commit history cleaner. Your contribution is still credited to you.

**Comment by adidalal** [comment]
Poor internet connection - will merge later

**Comment by vitorgalvao** [comment]
Having some problem doing it with `fastmerge`, will do a regular one.

**Pull request merged**
