### PR TITLE
Update kerio-connect to 9.2.7-4117,p2

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
not sure about the launchctl, thought i did it

**Comment by amyspark** [comment]
Perhaps it needs a lazy unload?  e.g. the `private-eye` Cask. Try adding an `early-script` with `launchctl unload KerioConnect`.

**Comment by core-code** [comment]
true dat. i've filed a bug report with them:
https://github.com/dawnlabs/alchemy/issues/45

**Review by amyspark — COMMENTED** [review]
Requesting review from @Homebrew/cask for this last nit. How to get 'KerioConnect' to exit properly in CI?

**Review by victorpopkov — APPROVED** [review]

**Pull request merged**
