### PR TITLE
Add youku.app v1.0.4.4121

### PR DESCRIPTION
**Pull request by Awezome**

### CODE REVIEW

**Comment by Awesomez** [comment]
added youku.rb

**Comment by Awesomez** [comment]
added youku.rb

**Comment by vitorgalvao** [comment]
There was a PR template when you first opened the PR. You need to fill it.

**Comment by Awesomez** [comment]
Adding a new cask

- [x]  Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x]  Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x]  When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x]  Commit message includes cask’s name.
- [x] ` brew cask audit --download {{cask_file}} is error-free.`
- [x] ` brew cask style --fix {{cask_file}} left no offenses.`
- [x] ` brew cask install {{cask_file}} worked successfully.`
- [x] ` brew cask uninstall {{cask_file}} worked successfully.`

**Pull request merged**
