### PR TITLE
Add midi-monitor v1.3.2

### PR DESCRIPTION
**Pull request by Dremora**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/master/Casks/acorn.rb).

**Comment by jawshooah** [comment]
A couple of other things:
- According to the homepage, this app requires 10.7 or later. So you should add 
```ruby
depends_on :macos => '>= :lion'
```
- Not necessary, but it's always nice to add the app bundle ids for `uninstall :quit`. In this case:
```ruby
uninstall :quit => [
                    'com.snoize.MIDIMonitor',
                    'com.snoize.MIDIMonitorDriver',
                    'com.snoize.MIDISpyFramework',
                    'com.snoize.SnoizeMIDI'
                   ]

**Comment by jawshooah** [comment]
One last thing: this app has a Sparkle appcast, so you can add
```ruby
appcast 'http://www.snoize.com/MIDIMonitor/MIDIMonitor.xml'
```

**Comment by Dremora** [comment]
Thanks for the comments! PR updated.

**Pull request merged**
