### PR TITLE
Add notion-calendar Latest

### PR DESCRIPTION
**Pull request by BastianZim**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by krehel** [comment]
Thanks @BastianZim!

This appears to be the same application as [Cron Calendar](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/c/cron.rb).

The live check in Cron Calendar contains information for what is now named Notion Calendar.

I will open a separate PR for a rename.  I'll close this once that other PR is created.

**Comment by BastianZim** [comment]
Oh yes you are correct: https://cron.com/blog

Thank you!

**Comment by krehel** [comment]
Replaced by #164787, thanks again @BastianZim!

**Comment by BastianZim** [comment]
Thank you as well!

**Pull request closed without merging**
