### PR TITLE
Update jd-gui

### PR DESCRIPTION
**Pull request by vladimyr**
### ⚠️ **DO NOT MERGE**

Add `jd-gui` binary & shimscript.

Depends on https://github.com/java-decompiler/jd-gui/pull/304

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Comment by core-code** [comment]
whats the plan here? :)

**Comment by vladimyr** [comment]
> whats the plan here? :)

Why did you assume there is a plan behind my stuff? 🤣

I was trying to achieve the following. I'm using JD-GUI frequently and what I'm forced to do every time is open it and then navigate to jar archive or drag n drop it inside it. Instead, I wanted to simply invoke it inside the terminal and pass target jar but even though there is support for command-line invocation parameters aren't correctly passed. So I started the chain of events:
1. Raised PR on upstream to fix parameter passing
2. Prepared HBC PR that adds binary/shim script

As you can see former is still without any reaction from upstream so the latter also hangs becoming _sticky_ part of our PR list...
Frankly, I can either close this ATM or we can continue waiting together for upstream to consider my PR. So no plans, but let's hear your opinion/whishes 😉

**Comment by vladimyr** [comment]
Also, note that the last commit to the upstream master is 6mo old. :shrug:

**Comment by core-code** [comment]
ah ok, thanks for the explanation here :)

i'd vote closing this now - we can reopen it anyway iff upstream reacts.

**Pull request closed without merging**
