### PR TITLE
Update stockbarjp.rb

### PR DESCRIPTION
**Pull request by miccal**
Update `homepage`.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Not sure if we should keep this if you can't even find it on the homepage.

**Comment by miccal** [comment]
I thought that myself but `brew cask fetch` is working, and the name of the app is at least on the homepage (although the link is not).

Happy to remove, though.

**Comment by reitermarkus** [comment]
Seems like it was initially added by the app author. @midnightSuyama, is this application still supported?

**Comment by midnightSuyama** [comment]
StockBarJP is still supported. However, I changed the article.
Please change to `homepage 'http://midnightsuyama.org/'`.

Thanks.

**Comment by miccal** [comment]
@midnightSuyama that is what I have already done - the issue here is there is no link from there to actually download the `zip`?

**Comment by midnightSuyama** [comment]
@miccal I got it. Please wait for renovation in progress.

**Comment by vitorgalvao** [comment]
@midnightSuyama You’re linking the app to https://caskroom.github.io/, which makes no sense.

**Comment by midnightSuyama** [comment]
Just improved. I changed the download link to `zip`.

**Comment by vitorgalvao** [comment]
Thank you @midnightSuyama.

**Pull request merged**
