### PR TITLE
Update dingtalk to 3.5.6.1

### PR DESCRIPTION
**Pull request by shiquanwang**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
Why downgrade to `3.5.6.1`?

**Comment by shiquanwang** [comment]
Current version 4.2.10 is beta. If it's a practice to get the latest version, just ignore this pull request.

**Review by commitay — APPROVED** [review]
Revert to current stable.

**Comment by commitay** [comment]
Thanks for the PR!

**Pull request merged**
