### PR TITLE
Update java to iansjava

### PR DESCRIPTION
**Pull request by ianleon**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ianleon** [comment]
Im pretty sure I didn't do this right but the java installer should use the link from java.com not oracle's complicated site that requires a cookie

**Comment by vitorgalvao** [comment]
This looks strictly worse then what it was. For this to be merged, you need to further explain hat this change means and why should we accept it.

**Comment by ianleon** [comment]
Please don't merge this. I'm just trying to bring

**Comment by ianleon** [comment]
I'm just trying to bring attention to the fact that the current source doesn't work

**Comment by vitorgalvao** [comment]
Then open an issue, please, not a PR.

**Pull request closed without merging**
