### PR TITLE
Update borgbackup to 1.1.12

### PR DESCRIPTION
**Pull request by brownj**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by core-code** [comment]
@vitorgalvao a few casks have been failing with this false-positive today. do you know any recent changes to the appcast audit code? 
`- appcast at URL 'https://github.com/borgbackup/borg/releases.atom' offline or looping`

**Comment by core-code** [comment]
@brownj this is marked as a "pre-release" in the github release page while "1.1.11" is still marked as the 'Latest Release'. therefore this release is not suited for inclusion in HBC. i'd recommend asking upstream if they did mark this as a pre-release by accident.

**Comment by core-code** [comment]
maybe @ThomasWaldmann can shed some light here

**Comment by brownj** [comment]
I misread the label on the releases page. 1.1.11 is the latest.

Sorry!

**Comment by core-code** [comment]
no problem!

**Comment by ThomasWaldmann** [comment]
1.1.12 is broken due to generating code with a cython version that is not py38 compatible (that is why i downgraded it to pre-release and added a comment).

1.1.13 will be out today / tomorrow.

**Comment by core-code** [comment]
@ThomasWaldmann thanks for the explanation. we'll add 1.1.13 tomorrow.

**Comment by ThomasWaldmann** [comment]
1.1.13 is out. :-)

**Comment by core-code** [comment]
thanks, i've sent a PR

**Comment by vitorgalvao** [comment]
> do you know any recent changes to the appcast audit code?

[Yes](https://github.com/Homebrew/brew/pull/7427), though that doesn’t seem like it would be the source (pinging @SMillerDev just in case).

From the timing, I’d say something like https://github.com/Homebrew/homebrew-cask/issues/83481 might be the cause.

**Comment by SMillerDev** [comment]
Unless it throws warnings about notability it's not my PR. That one is very forgiving, if something fails it'll not complain about it.

**Pull request closed without merging**
