### PR TITLE
Update accurics from 1.0.18 to 1.0.19

### PR DESCRIPTION
**Pull request by williepaul**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by williepaul** [comment]
Hi folks,

The failure on the build is happening due to the cloudflare bot protection on https://www.accurics.com.

Regards,
-Willie

**Comment by cho-m** [comment]
That is fine. We can skip that check for merge.

On side note, is there a latest yml rather than the version-specific
`https://downloads.accurics.com/cli/#{version}/accurics-cli.yml`?

This would help us switch from old `appcast` to newer `livecheck` stanza.

**Comment by williepaul** [comment]
Thanks!

Currently, there isn't a "latest" yml, but I went ahead and made a copy into a "latest" folder, as in: https://downloads.accurics.com/cli/latest/accurics-cli.yml

The contents of the file:

version: 1.0.19
files:
  - url: 'https://downloads.accurics.com/cli/#{version}/accurics-cli.dmg'
    sha256: 24826e0d048d09250f35643cdbc5070700632ac975d1b80631ca60ffcdcdb07d
releaseDate: '2021-06-14T18:54:52.000Z'

Does the URL clause also have to point to a "latest" location as well? Or would this file work fine?

**Comment by cho-m** [comment]
The URL in file doesn't matter.

It would be nice to automatically update the file on a new release.
The version in file format is detectable by our `electron_builder` strategy, so something like:
```rb
  livecheck do
    url "https://downloads.accurics.com/cli/latest/accurics-cli.yml"
    strategy :electron_builder
  end
```

This would allow proper detection of latest release via `brew livecheck --cask accurics`

---

Just a consideration similar to what we requested from Wolfram in https://github.com/Homebrew/homebrew-cask/issues/106909#issuecomment-858199078

**Comment by williepaul** [comment]
Yep, I'll update our makefile and internal process docs. I went ahead and pushed the change to remove appcast and add the livecheck section.

**Review by cho-m — APPROVED** [review]

**Pull request merged**
