### PR TITLE
android-ndk 27c

### PR DESCRIPTION
**Pull request by marcograss**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Perhaps the uninstall postflight block can be moved to `uninstall delete`

**Review by p-linnane — APPROVED** [review]

**Comment by bevanjkay** [comment]
@Bo98 I think this is another side-effect of adding the `brew test-bot --cleanup` step to CI, it looks like the path `/opt/homebrew/share` gets removed?

**Comment by Bo98** [comment]
To put it in another similar example: does `brew uninstall` usually break if someone manually deletes an app?

**Comment by Bo98** [comment]
`rmdir` won't work here because it's a symlink. `delete` might work?

**Comment by bevanjkay** [comment]
@Bo98 The issue is with the install. My assumption is the the `brew cleanup --prune-prefix` step (or something peripheral), is removing the `/opt/homebrew/share` folder, which causes the symlink to fail to be created.

I added a debug to the caskfile `puts system ls "#{HOMEBREW_PREFIX/share"
and it returned - `ls: /opt/homebrew/share: No such file or directory`

We could solve this by creating the directory if it doesn't exist, but I don't think is the appropriate place to do it?

**Comment by Bo98** [comment]
In formulae, we have code that creates these directories prior to install.

For casks however, this code has never existed (unless the cask installs a formula as a dependency) so this has always been broken under that scenario. We should run `mkpath` on `HOMEBREW_PREFIX/share` etc, though I guess it's debatable what is responsible for doing that - this cask or `brew`.

In the longer term, it would be great to be able to delete the postinstall entirely by adding better DSL.

**Comment by p-linnane** [comment]
I've added the `mkpath` we need to unblock this. I agree it's worth adding DSL for this though.

**Review by p-linnane — APPROVED** [review]

**Review by khipp — APPROVED** [review]

**Pull request merged**
