### PR TITLE
Add Audio Unit and VST plugin folder artifiacts

### PR DESCRIPTION
**Pull request by joshka**
This is an updated version of the PR for this feature that works properly

### CODE REVIEW

**Comment by adityadalal924** [comment]
@vitorgalvao This will require a bump in Cask DSL version, correct? ie. cask 1_2.
A new release will also need to be cut before the new stanzas can be used, afaik.

**Comment by adityadalal924** [comment]
@jawshooah This looks ready to merge.

[`cask_language_deltas.md`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_deltas.md) will also need to be updated, but as you said, incrementing the version doesn't do anything at this point, so it's up to you.

**Comment by jawshooah** [comment]
Waiting on #15381 (which is in turn waiting on Homebrew/homebrew#46795) so we don't have to push a new release for this to work.

**Comment by adityadalal924** [comment]
@joshka As the previously blocking PR is now merged, would you mind adding the two stanzas to https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_deltas.md (under the All Supported Stanzas (1.0) section)?

That way we can keep this PR self-contained and also go ahead and merge it.

**Comment by joshka** [comment]
Sure - will do so a little later tonight

**Comment by adityadalal924** [comment]
@jawshooah Do we need cask_language_deltas anymore?

Updating that seems to be the only blocker for this merge, (and I don't mind adding it in if does need to be updated - it's like a two line fix)

**Comment by joshka** [comment]
I got busy and forgot to get around to this. My biggest hassle was understanding how you're versioning the DSL. Happy for you to update this @adityadalal924

**Comment by jawshooah** [comment]
@adityadalal924 Please do go ahead and add those lines after merging. We likely don't need cask_language_deltas anymore, but I'd like for it to remain up-to-date until we remove it, along with any code relating to DSL versioning.

**Comment by adityadalal924** [comment]
@joshka Will merge and update documentation accordingly. I'll put a message over in https://github.com/caskroom/homebrew-cask/pull/15644 once everything is done so you can update that PR accordingly as well.

**Pull request merged**
