### PR TITLE
Added CyberGhost VPN

### PR DESCRIPTION
**Pull request by julionc**
CyberGhost VPN is a free and simple Internet security, access to content from all over the world.
Main URL: http://www.cyberghostvpn.com/

### CODE REVIEW

**Comment by vitorgalvao** [comment]
[Are you sure this is `:freemium` and not `:gratis`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#license-stanza-details)?

> a free app to access a paid service is still `:gratis`, not `:freemium`

**Comment by julionc** [comment]
My bad. Updated license.

**Comment by vitorgalvao** [comment]
Thank you, could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by julionc** [comment]
Update it and CI pass.

**Pull request merged**
