### PR TITLE
temurin 22.0.2

### PR DESCRIPTION
**Pull request by khipp**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> Downloading https://github.com/adoptium/temurin22-binaries/releases/download/jdk-22.0.2%2B9/OpenJDK22U-jdk_x64_mac_hotspot_22.0.2_9.pkg
curl: (22) The requested URL returned error: 404
Error: Download failed on Cask 'temurin' with message: Download failed: https://github.com/adoptium/temurin22-binaries/releases/download/jdk-22.0.2%2B9/OpenJDK22U-jdk_x64_mac_hotspot_22.0.2_9.pkg
```

**Comment by khipp** [comment]
Intel binaries are still missing. They were added within three days after the last release.

**Comment by samford** [comment]
Intel binaries are part of the release now, so I updated the Intel `sha256`.

**Comment by khipp** [comment]
@samford Oh, I didn't notice you had already pushed an update. ❤️

**Review by samford — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
