### PR TITLE
libreoffice-language-pack 6.4.5

### PR DESCRIPTION
**Pull request by miccal**
```
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/developer/bin/update_multilangual_casks /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/libreoffice-language-pack.rb 6.4.5
```

### CODE REVIEW

**Comment by miccal** [comment]
```
audit for libreoffice-language-pack: failed
 - locale ast, brx, ca-valencia, dgo, dsb, gug, hsb, kab, kmr-Latn, kok, mai, mni, nso, sat, sid, sr-Latn, szl, vec are invalid
```
I only added four of these -- the other have been there all along ...

**Comment by vitorgalvao** [comment]
Either we fix the cask to conform to the audit, or we change the audit. The solution is probably somewhere in the middle, as we should be able to make this closer to the audit but then might need to have it support three letter codes.

We could also remove every language that doesn’t conform and add them correctly one by one as they are needed. I doubt all of this are in use.

**Comment by miccal** [comment]
@vitorgalvao this is the only Cask using three-character locale codes, so I have just removed them all -- some of them are not even listed as valid [ISO 639-2](https://en.wikipedia.org/wiki/ISO_639-2) codes.

I think we should also remove the reference to the ISO 639-2 codes in [language.md](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/language.md), and change the opening sentence to:
```
The `language` stanza can match [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) language codes, ...
```

**Comment by vitorgalvao** [comment]
You’re right, I forgot about that documentation, which is now wrong. Care to open a PR (or just an issue so we don’t forget) on it?

Also, from the `audit` the languages need to be of the form `sw-TZ`, `pt-PT`, now.

**Comment by miccal** [comment]
> Care to open a PR

Sure.

> Also, from the `audit` the languages need to be of the form `sw-TZ`, `pt-PT`, now.

I don't follow, they are already ... ?

**Comment by vitorgalvao** [comment]
> I don't follow, they are already ... ?

My mistake. What I meant was that `pt-PT` was valid and `pt` wouldn’t be. But I just looked at the code and both are indeed valid.

**Comment by miccal** [comment]
The [LibreOffice mirrors](https://download.documentfoundation.org/mirmon/) are acting up a bit at the moment, hence the CI failures -- I had a bit of trouble with them when I updated my [personal tap version of LibreOffice](https://github.com/miccal/homebrew-miccal/blob/master/Casks/m-libreoffice.rb).

**Pull request merged**
