### PR TITLE
Update gloomhaven-helper from 8.4.5 to 8.4.6

### PR DESCRIPTION
**Pull request by samuelmurray**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by samuelmurray** [comment]
I see similar build errors on other PRs - is it some temporary bug in brew/cask or is there something I need to fix?

**Comment by core-code** [comment]
is it some temporary bug in brew/cask

**Comment by core-code** [comment]
we should probably add an appcast here too. the homepage can be used as i don't think there is anything else

**Comment by samuelmurray** [comment]
Opened #86736 for adding appcast

**Pull request merged**
