### PR TITLE
Update yt-music to 1.0.4,5:1530537206

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
per this conversation:
https://github.com/steve228uk/YouTube-Music/issues/17

Seems like the github releases page is less reliable at having the latest release than devmate / new appcast.

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
From the conversation, this seems like a momentary lapse rather than something that’ll keep occurring. I’d rather keep it as it is currently. The less we need the `was verified as official when first introduced to the cask` comment, the better.

**Comment by brianmorton** [comment]
@vitorgalvao I understand.

I will say that since I started the automated appcast based scanning, I have noticed that a lot of developers tend to treat the github releases page as secondary/tertiary (or an after thought), which is why I subbed this PR - because of this feeling if there is another release channel I would tend to prefer it, even though I like the uniformity provided by having a lot of casks using a github appcast.

**Comment by vitorgalvao** [comment]
@brianmorton Is this something your system would notice if it happens again? I say this in the sense of: keep this cask with the github release, but if it happens again let’s change it.

**Comment by brianmorton** [comment]
Not in an automated way - when this stuff happens I usually open an issue asking about a macOS binary for the latest release. The issues that get attention the result is usually that the dev forgot to upload the release to github. Had I never inquired I'm not sure if or when they would have noticed.

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/pull/49243

**Pull request closed without merging**
