### PR TITLE
Migrate rar 5.4.0 from homebrew-binary

### PR DESCRIPTION
**Pull request by miccal**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked that the cask was not already refused in [closed issues].

Ping @adidalal RE https://github.com/caskroom/homebrew-cask/issues/23938 for help about what else needs to be done for these migrations.

### CODE REVIEW

**Comment by adidalal** [comment]
Add it to the migrations json

**Comment by miccal** [comment]
@adidalal is there a simple way to do that, or to I have to go through the whole fork/git remote add process? You wouldn't have that set up already would you?

**Comment by miccal** [comment]
@adidalal Done.

Another question: I notice that the formula in homebrew/binary includes the following:
```
  def install
    bin.install "rar", "unrar"
    lib.install "default.sfx"
    etc.install "rarfiles.lst"
    doc.install "acknow.txt", "order.htm", "rar.txt", "whatsnew.txt"
    man1.install resource("man")
  end
```

The files included in the downloaded archive are:

screen shot 2017-01-10 at 22 36 53

I don't see a file to create a `man` page - am I missing something? Should I worry about any of these files via an `artifact ... target:`?

**Comment by adidalal** [comment]
It's been a while but you may also need to copy over that .sfx (using artifact)

Not sure about the man pages, people can always do rar help though

**Comment by miccal** [comment]
> It's been a while but you may also need to copy over that .sfx (using artifact)

To where?

> Not sure about the man pages, people can always do rar help though.

No, `rar --help` is not valid, according to the `rar.txt` file:
```
 Switches (used in conjunction with a command):

-?     Display help on commands and switches. The same as when none
         or an illegal command line option is entered.
```

**Comment by MikeMcQuaid** [comment]
Sorry, I'm not sure about what to do about manages. I'd suggest we could add it without if need be.

**Comment by miccal** [comment]
@MikeMcQuaid no problem, but could you explain where the commands `lib.install` and `etc.install` move the files to?

**Comment by MikeMcQuaid** [comment]
As far as Cask is concerned: `/usr/local/lib` and `/usr/local/etc`

**Comment by miccal** [comment]
Thanks @MikeMcQuaid.

Ping @adidalal for final review.

**Comment by adidalal** [comment]
Typo in caveats but otherwise looks :+1

**Comment by miccal** [comment]
Fixed, thanks @adidalal.

**Review by adidalal — APPROVED** [review]

**Pull request merged**
