### PR TITLE
Add new cask: orbstack

### PR DESCRIPTION
**Pull request by TheCoolBlackCat**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by TheCoolBlackCat** [comment]
I'm not happy with the `version :latest` stuff, but I'm not sure how to write a livecheck that will allow for a vX.Y.Z_build, and support two URL that redirect to the latest DMG.

**Comment by miccal** [comment]
Thank you @TheCoolBlackCat.

**Review by miccal — APPROVED** [review]

**Comment by unitof** [comment]
The hardcoded `amd64` in `url` needs to be `#{arch}`—right now Apple Silicon gets 404 errors.

Submitting PR momentarily.

(Don't we run arm64 tests machines though that would have caught that?)

**Comment by unitof** [comment]
Thanks for being the reason I found out about OrbStack though! Just saw it in the `git log` while working on another cask.

**Comment by TheCoolBlackCat** [comment]
> Thanks for being the reason I found out about OrbStack though @TheCoolBlackCat! Just saw it in the `git log` while working on another cask.

Glad to introduce you! I only found out about it recently but it's been great so far.

**Pull request merged**
