### PR TITLE
Update exodus to 1.59.0

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by claui — DISMISSED** [review]
According to [upstream release notes](https://www.exodus.io/releases/#1-59-0), this cask should now have `auto_updates true`.

**Comment by brianmorton** [comment]
Good catch, thank you @claui

**Comment by claui** [comment]
It’s just a convoluted way to say “pls remove two spaces in line 12”.

**Comment by brianmorton** [comment]
Pro tip there form @claui !!!

**Comment by claui** [comment]
Thanks @brianmorton!

**Pull request merged**
