### PR TITLE
Update navicat-premium-essentials to 12.0.28

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
@commitay may find it interesting that this cask (the only navicat with the "old" style appcast) was the only one which triggered as new/updated for me in automated scanning - the new appcasts all seem to use on-page-OS-detection which does not play nicely with my scanning currently, and thus did not detect any change on the page.

**Comment by commitay** [comment]
Was this one left with the "old" appcast for a reason?

**Comment by brianmorton** [comment]
There is now equivalent "new" appcast that I could find - it didn't seem to map to anything on their [products page](https://www.navicat.com/en/products) so I assumed (based on the name) that maybe it was a privileged download or something.

**Comment by commitay** [comment]
Ah, I'd forgotten there was one navicat cask that originally didn't have an appcast, thanks!

**Pull request merged**
