### PR TITLE
eudic: update livecheck and revert to 4.5.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
This current strategy isn't working. The url changes but the checksum does not.

**Review by bevanjkay — CHANGES_REQUESTED** [review]
Find a different way to do livecheck.

**Comment by bevanjkay** [comment]
Need to unversion the url and remove the checksum if we do this change

**Comment by chenrui333** [comment]
actually, the livecheck works as expected, it is more of an issue that upstream did not update the sha, but simply changed the artifact version

image

**Comment by chenrui333** [comment]
more or less, same as https://github.com/Homebrew/homebrew-cask/pull/166526

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
