### PR TITLE
new cask: crystax-ndk 10.3.1

### PR DESCRIPTION
**Pull request by yurikoles**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by miccal** [comment]
```
audit for crystax-ndk: warning
 - possible duplicate, cask token conflicts with Homebrew core formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/crystax-ndk.rb
```

**Comment by yurikoles** [comment]
@miccal it's a migration https://github.com/Homebrew/homebrew-core/pull/11811

**Comment by yurikoles** [comment]
@miccal why on hold? homebrew maintainers are waiting for us to implement this cask. The cask script is mostly the same as android-ndk, except some branding change.

**Comment by miccal** [comment]
@yurikoles it is on hold until it is removed from Homebrew Core.

**Comment by ilovezfs** [comment]
@miccal I have now shipped the removal from core.

**Comment by miccal** [comment]
Verified locally:
```
-bash-4.4.12- /Users/miccal [> brew cask fetch https://raw.githubusercontent.com/yurikoles/homebrew-cask/75d6da6ba9d62e62b3f805ff75a5ae142b59c73c/Casks/crystax-ndk.rb
==> Downloading external files for Cask https://raw.githubusercontent.com/yurikoles/homebrew-cask/75d6da6ba9d62e62b3f805ff75a5ae142b59c73c/Casks/crystax-ndk.rb
==> Downloading https://raw.githubusercontent.com/yurikoles/homebrew-cask/75d6da6ba9d62e62b3f805ff75a5ae142b59c73c/Casks/crystax-ndk.rb.
######################################################################## 100.0%
==> Downloading https://www.crystax.net/download/crystax-ndk-10.3.1-darwin-x86_64.tar.xz
######################################################################## 100.0%
==> Verifying checksum for Cask crystax-ndk
==> Success! Downloaded to -> /Users/miccal/Library/Caches/Homebrew/Cask/crystax-ndk--10.3.1.tar.xz
```

**Comment by yurikoles** [comment]
@miccal I have bad luck with huge casks :)

**Review by victorpopkov — APPROVED** [review]

**Pull request merged**
