### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by daylightbrightledlight**
Comment out a part so that it wouldn't be submitted

This is an updated template so that the comment can be seen when writing the issue, but it will not be previewed because it becomes repetitive to appear in every request.

### CODE REVIEW

**Comment by daylightbrightledlight** [comment]
I hope you like the edit. Let me know what you think. I think it will clean up some stuff.

**Review by vitorgalvao — APPROVED** [review]
Didn’t know we could do this. Yes, if you find other documentation that would benefit, please add it as well.

**Review by commitay — APPROVED** [review]

**Comment by vitorgalvao** [comment]
Alright, now there are too many changes. Making some parts comments is fine, but all the rest was carefully worded and exactly as intended after many iterations. Please revert everything except making the comments.

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Please revert every change you made but making the comments (`<!-- -->`)

**Review by commitay — APPROVED** [review]
Other changes reverted.

**Pull request merged**
