### PR TITLE
Add postman-cli

### PR DESCRIPTION
**Pull request by thundron**
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzothunder.ambrosi@gmail.com>

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by p-linnane** [comment]
I've added some suggestions that will get this into a working state from a cask perspective. The server itself redirects the x64 binary to the arm64, but I can't help with that.

**Comment by p-linnane** [comment]
I've added some suggestions that will get this into a working state from a cask perspective. The server itself redirects the x64 binary to the arm64, but I can't help with that.

**Comment by p-linnane** [comment]
It was suggestions for the structure of the cask, livecheck, etc. You might want to just take a look, but it will be better to implement once final links and whatnot are ready.

**Comment by miccal** [comment]
Thank you @thundron.

**Review by miccal — APPROVED** [review]

**Comment by thundron** [comment]
> It was suggestions for the structure of the cask, livecheck, etc. You might want to just take a look, but it will be better to implement once final links and whatnot are ready.

then I haven't seen any of the suggestions actually 🤔  maybe they were deleted after force-pushing?

**Comment by RaisinTen** [comment]
Maybe you forgot to click on "Submit Review"? :P

**Pull request merged**
