### PR TITLE
Update qgis from 3.18.1 to 3.18.3

### PR DESCRIPTION
**Pull request by luispuerto**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by luispuerto** [comment]
The livecheck is wrong… as you can see on the main site of qgis and they are two minor versions ahead

**Comment by SMillerDev** [comment]
It seems they stopped updating the checksum. Could you contact upstream to ask?

**Comment by luispuerto** [comment]
To be honest, I don't know where or to whom I should ask.

**Comment by cho-m** [comment]
Previously, we saw the problem that the version on main site doesn't match the DMG: https://github.com/Homebrew/homebrew-cask/pull/104468#issuecomment-825282141

Now the SHA checksum file also doesn't match the DMG.

You can see this based on timestamps of files.
All three versions (DMG, Checksum, Latest[3.18.3]) are out-of-sync:
 | | | |
| --- | --- | --- | 
| qgis-macos-pr.deps | 19-Mar-2021 21:17 | 5.4K | 
| **qgis-macos-pr.dmg** | **27-Apr-2021 03:56** | 1.2G | 
| qgis-macos-pr.latest.log | 17-May-2021 23:16 | 5.9M | 
| **qgis-macos-pr.latest.png** | **17-May-2021 23:16** | 1.5K | 
| **qgis-macos-pr.sha256sum** | **19-Mar-2021 21:17** | 145 | 

The DMG is most likely not **3.18.3** as that build failed according to qgis-macos-pr.latest.png:


On other hand, the DMG is newer than the sha256sum file.
The SHA file shows **3.18.1**, so that is probably not the correct version either.

I think the DMG is currently on **3.18.2**.
That is also the newest DMG available in the build directory:
https://qgis.org/downloads/macos/pr/qgis_pr_final-3_18_2_20210426_125925.dmg

And can be confirmed by downloading both DMG and doing a SHA comparison:
```console
❯ curl -OL https://qgis.org/downloads/macos/qgis-macos-pr.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1181M  100 1181M    0     0  6766k      0  0:02:58  0:02:58 --:--:-- 6878k

❯ curl -OL https://qgis.org/downloads/macos/pr/qgis_pr_final-3_18_2_20210426_125925.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1181M  100 1181M    0     0  5568k      0  0:03:37  0:03:37 --:--:-- 5844k

❯ sha256sum *dmg
7ea45e11aa394acb7bbec5b13ed7aca44c877b87d644d4b8fbfc9e03f51ca041  qgis-macos-pr.dmg
7ea45e11aa394acb7bbec5b13ed7aca44c877b87d644d4b8fbfc9e03f51ca041  qgis_pr_final-3_18_2_20210426_125925.dmg
```

---

The problem is there isn't a good way to livecheck this.
- based on last few bump attempts, using the website version will lead to the wrong version number
- based on this attempt, the SHA file is currently not sync'd, which may be an upstream CI failure.
- changing livecheck to something like `extract_plist` is a bad idea given that the upstream server is very slow and download takes ~3min on my wifi (~500/500Mbps wifi connection via gigabit service)
- using build directory is probably also bad since there is no way to tell if DMG is actually stable (e.g. 3.18.2 has 3 DMGs built over 4/24, 4/25, and 4/26).

**Comment by luispuerto** [comment]
You are pretty much right. I just installed the version from the web and it's true it's not the 3.18.3 but 3.18.2. I've asked what is going on on the official QGIS mailing list and I don't know if we should rise the issue on the official repo on https://github.com/qgis/QGIS since the issues there seems to be focus on development.

**Review by carlocab — DISMISSED** [review]

**Pull request closed without merging**
