### PR TITLE
Upgrade Mono to 3.12.0

### PR DESCRIPTION
**Pull request by denpatin**
- Upgrade Mono MRE to 3.12.0
- Upgrade Mono MDK to 3.12.0

### CODE REVIEW

**Comment by ndr-qef** [comment]
Mono MDK is known to release updated packages at a single URL, which is why `sha256` was set to `:no_check`. Has this changed? If not, please amend the commit to reinstate `:no_check`.

**Comment by denpatin** [comment]
As I get it, the URL gets changed when the version changes. As you can see, the URLs for each version are different because of the inline `#{}` construction; moreover the sha256-s are different as well. So for me it was a bit weird that there was a `:no_check` parameter when there wasn't a single URL.

**Comment by ndr-qef** [comment]
Normally, you would be right, but Mono MDK is an exception: the visible version works normally with interpolation, but the vendor updates all build releases (3.12.0.n) at the same URL, causing the checksum to break frequently.

**Comment by denpatin** [comment]
@ndr-qef So you mean that for the major and minor versions the URL changes but for patches don't? And only because of this we shouldn't check sha256 at all? Ok, I'll change this line back, but still it's really a bit weird :)

**Comment by vitorgalvao** [comment]
@denpatin Please don’t remove the comment. It’s there so users know this cask is this way for a specific reason.

**Comment by denpatin** [comment]
@vitorgalvao Done! And many thanks in particular for telling me about the `rebase` functionality in git, that's amazing and exceedingly useful!

**Comment by kitsuyui** [comment]
Currently I found that MRE's download link is not active.
MDK seems to be OK.
http://download.mono-project.com/archive/3.12.0/macos-10-x86/

**Pull request merged**
