### PR TITLE
Re-Add Bitlord.app 2.4.6,348

### PR DESCRIPTION
**Pull request by aaronliu0130**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues). Bitlord was removed due to the latest version installer being adware. However, the bitlord installer for the newest macOS version is now clean, and I think Bitlord deserves a re-add.
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by core-code** [comment]
we've deleted bitlord because they distribute malware / adware. is there anything that has changed here since?

**Comment by miccal** [comment]
See https://github.com/Homebrew/homebrew-cask/pull/56325 for background.

**Comment by aaronliu0130** [comment]
> we've deleted bitlord because they distribute malware / adware. is there anything that has changed here since?

Short Answer: Yes.
Long Answer:

> Checked the cask was not already refused. Bitlord was removed due to the latest version installer being adware. However, the bitlord installer for the newest macOS version is now clean, and I think Bitlord deserves a re-add.

**Comment by core-code** [comment]
it seems the versions they offer for download now are 'clean' as far as a cursory examination can tell. so i wouldn't be against re-adding it in principle. 

what i find troubling is the complete lack of any transparency from them about this very serious issue. 

i don't see any information when they stopped tainting their downloads with the adware installer and i don't see any pledge not to infect the Macs of their users anymore. seems to me like they want to predend this never happened and want to keep open the option to 'go evil' again at any time in the future. thats not a way to build trust.

**Comment by claui** [comment]
> seems to me like they want to pretend this never happened and want to keep open the option to 'go evil' again at any time in the future. thats not a way to build trust.

@core-code Their [privacy policy](https://www.bitlord.com/privacy.html) even suggests they still reserve that right:

> We may also include offers from third parties as part of the installation process for our software.

**Comment by vitorgalvao** [comment]
I’m also for refusal. Torrent downloaders are prime apps for infecting users, and I don’t see any reason these developers should be trusted again. That privacy policy is no accident; it sounds like the only reason they’re clean now is because no one is paying them to include the adware.

**Pull request closed without merging**
