### PR TITLE
Add go 1.8

### PR DESCRIPTION
**Pull request by chulkilee**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

----

Note that `brew cask uninstall go` does not remove `/usr/local/go`. Should it remove that directory?

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but this is a language, so it belongs in Homebrew.

Additionally, `pkg` casks require an `uninstall` to be accepted.

**Comment by chulkilee** [comment]
I know `brew` has it (https://github.com/Homebrew/homebrew-core/blob/master/Formula/go.rb) but it compiles (or uses bottle for custom build, I guess), not using the official package installer. I believe they have their own merits - so why can't we have go in both brew and brew cask?

Note that go from brew cask can "coexist" with go from brew, since it installs binaries on `/usr/local/go/bin` while brew version installs binaries to `/usr/local/bin`

Added `uninstall` stanza - now uninstall works.

**Comment by vitorgalvao** [comment]
> so why can't we have go in both brew and brew cask?

https://github.com/caskroom/homebrew-cask/issues/15603

Because it took a lot of people time to reduce duplicated efforts between the projects, and we don’t want to undo that.

**Comment by chulkilee** [comment]
Thanks for the link! I ended up with https://github.com/chulkilee/homebrew-alt

**Pull request closed without merging**
