### PR TITLE
Add Engine Prime v1.1.1

### PR DESCRIPTION
**Pull request by ErikMinekus**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
Walled build.

> When the download URL is both behind a login/registration form and from a host that differs from the homepage.

**Comment by ErikMinekus** [comment]
You don't have to enter a valid email address to get to the download link, so I figured it was OK. And as you can see on www.inmusicbrands.com, they own the Denon DJ brand, so it's an official host.

**Comment by vitorgalvao** [comment]
> You don't have to enter a valid email address to get to the download link

A user directly faced with it will not know that, so it’s effectively the same as requiring a real email, in this case. We had a discussion on that previously.

> And as you can see on www.inmusicbrands.com, they own the Denon DJ brand

Again, for someone auditing this, that might as well be a fake website made to look like they own it. The website where the download link is located must make the situation clear.

Thank you anyway.

**Comment by ErikMinekus** [comment]
Alright, thank you for the clarification.

**Pull request closed without merging**
