### PR TITLE
clip-studio-paint 2.3.4

### PR DESCRIPTION
**Pull request by iivusly**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by p-linnane — CHANGES_REQUESTED** [review]
Looks like only the checksum changed, but not the version number? If that's the case, we need to understand why that happened in order to rule out anything malicious.

**Comment by krehel** [comment]
Not only that, but this version was released in January 2023.  So it's been one year.  When did it change?  Has it just been wrong this entire time?  Analytics do not point to this being installed much.

```
> cask-analytics clip-studio-paint
clip-studio-paint
30 days: n/a
90 days: 1 (#7434)
365 days: 4 (#7785)
```

**Comment by iivusly** [comment]
Clip studio separated their products, thus they must have did an update behind the scenes when they separated v1 from v2. There are two separate programs because they require different licenses, should I keep the cask at v1 or update everything to v2? I could also create separate casks for v1, v2, and soon v3.Le 20 févr. 2024 à 14:11, Justin Krehel ***@***.***> a écrit :﻿
Not only that, but this version was released in January 2023.  So it's been one year.  When did it change?  Has it just been wrong this entire time?  Analytics do not point to this being installed much.
> cask-analytics clip-studio-paint
clip-studio-paint
30 days: n/a
90 days: 1 (#7434)
365 days: 4 (#7785)

**Comment by gnought** [comment]
Checked with `brew fetch --cask clip-studio-paint`, the old `b1cbf25b35f0f3ee11b2dd621b0dd6b023133cb21c76de8220ceceac4a0352c8` is for v1.13.2

I suggest to rename the `clip-studio-paint` to `clip-studio-paint@1`, and create a new `clip-studio-paint` for v2 in this case.

**Comment by iivusly** [comment]
> Checked with `brew fetch --cask clip-studio-paint`, the old `b1cbf25b35f0f3ee11b2dd621b0dd6b023133cb21c76de8220ceceac4a0352c8` is for v1.13.2

Yeah the new hash is for v1, the only thing I am trying to figure out is why the hash changed for the same version. The version number did not change but the checksum did....

**Comment by bevanjkay** [comment]
This repo (`homebrew-cask`) should always ship the latest stable version, which in this case means updating the cask to version 3.
For a versioned option it should be added to `homebrew-cask-versions`, which will soon be deprecated. So it may be best to wait until the migration is completed and then just add the versioned cask here.

**Pull request closed without merging**
