### PR TITLE
java 9.0.4 link MacOS

### PR DESCRIPTION
**Pull request by tduehr**
Adds MacOS link to /Library/Java

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
> Adds MacOS link to /Library/Java

Why?

**Comment by commitay** [comment]
On hold pending CI fix in https://github.com/caskroom/homebrew-cask/pull/43426

**Comment by tduehr** [comment]
So you can point applications generated by `javapackager` at it and `/Library/Java/Home` to keep the Java install they use up to date without delinking them every new install.

**Review by commitay — APPROVED** [review]
Verified install locally.

**Pull request merged**
