### PR TITLE
Update rescuetime from 2.16.3.1 to 2.16.4.2

### PR DESCRIPTION
**Pull request by thebengeu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
This version _is_ listed in the [release notes.](https://www.rescuetime.com/release-notes/mac)

**Comment by core-code** [comment]
since we have a static URL here it basically doesn't matter if it is mentioned anywhere, it matters whether the version is actually contained in the file at https://www.rescuetime.com/installers/RescueTimeInstaller.pkg

i wish it was possible to teach travis about that

**Comment by miccal** [comment]
From the `Info.plist` file inside the `RescueTime.app` inside the `RescueTimeInstaller.pkg`:
```
<key>CFBundleShortVersionString</key>
<string>2.16.4.2</string>
<key>CFBundleVersion</key>
<string>2.16.4.2</string>
```

**Comment by core-code** [comment]
> Might be possible to automate this for .pkg's that contain .app's.

PKGs are definitely complicated but supporting this for plain apps should be simpler.

**Comment by rafaelmagu** [comment]
The SHA256 for this cask appears to be incorrect. I've deleted and re-downloaded this file multiple times, and keep getting the same checksum: `ac9650230c820a2e270cd05c65e6e1d16c03f24a4fcbbf0b8b6434980f523723`

I get this checksum through `shasum -a 256 RescueTimeInstaller.pkg` in the terminal on my Mac.

```
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 1 outdated package:
rescuetime latest -> 2.16.4.2
==> Upgrading rescuetime
==> Downloading https://www.rescuetime.com/installers/RescueTimeInstaller.pkg
                           -=O=-                        #    #    #   #
==> Verifying SHA-256 checksum for Cask 'rescuetime'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
==> Purging files for version 2.16.4.2 of Cask rescuetime
Error: Checksum for Cask 'rescuetime' does not match.
Expected: 41f0f340ec75b8296756e4129f6df8743279ddfd77f581d825839c7d7725088f
  Actual: ac9650230c820a2e270cd05c65e6e1d16c03f24a4fcbbf0b8b6434980f523723
    File: /Users/rafael/Library/Caches/Homebrew/downloads/6c16425385932119cb691c50100bf4fe56fbd2c9979a4db3433801a155ebf112--RescueTimeInstaller.pkg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/HEAD/doc/reporting_bugs/checksum_does_not_match_error.md
```

**Pull request merged**
