### PR TITLE
updated aquaskk (4.3.4)

### PR DESCRIPTION
**Pull request by elim**

### CODE REVIEW

**Comment by adityadalal924** [comment]
This needs an appcast added, see https://github.com/caskroom/homebrew-cask/issues/16689 for directions, temporarily

**Comment by elim** [comment]
@adityadalal924 Thank you for your helpful explanation! I added that.

**Comment by adityadalal924** [comment]
Thank you for the contribution. It was merged directly as c7df0b4161633942679f5aac453ff858a2105e6e to keep commit history cleaner. Your contribution is still credited to you.

**Comment by elim** [comment]
Thanks :octocat:

**Pull request closed without merging**
