### PR TITLE
Update deepl from 1.13.1,115943 to 1.12.0,1120000

### PR DESCRIPTION
**Pull request by core-code**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

Automatically created and submitted by muUpdateStaticHomebrewCask

### CODE REVIEW

**Comment by core-code** [comment]
@vitorgalvao @reitermarkus it seems 'cask-repair' automatically re-adds checksums to casks with :no_check. what shall we do?

**Comment by vitorgalvao** [comment]
> it seems 'cask-repair' automatically re-adds checksums to casks with :no_check. what shall we do?

Not when `# required as upstream package is updated in-place` is used, which these don’t. I’m not entirely convinced leaving that comment out is the right choice, because its absence might incentivise contributors to (again) start submitting versioned cask with versioned URLs and `:no_check`.

I’ve pushed a change to `cask-repair` to not update the checksum if it already was `:no_check` and the cask is versioned. This won’t be optimal in very specific use cases, like an unversioned cask becoming versioned with a new URL, but handling that as well is introducing even more complexity to a script that should be deprecated and phased out—it’s orders of magnitude more complex than it was when I introduced it and the use cases it’s serving are different from the original goals.

`bump-cask-pr` needs to be fixed to properly handle the needs of casks as they *are*, not treat them like formula.

**Comment by core-code** [comment]
thanks for the quick fix, 'cask-repair' has the best customer support!

**Pull request merged**
