### PR TITLE
Add new cask Pieces

### PR DESCRIPTION
**Pull request by connor-oleary-pieces**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by p-linnane** [comment]
Thank you for your contribution to `homebrew-cask` @connor-oleary-pieces. Please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask.

**Comment by connor-oleary-pieces** [comment]
> Thank you for your contribution to `homebrew-cask` @connor-oleary-pieces. Please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask.

Can do! Can I ask what for? I thought the `zap` stanza was optional, and this is only the CLI binary being installed.

**Comment by p-linnane** [comment]
The intent of `zap` is to remove any configuration files or user-specific items left behind on uninstall. If this binary doesn't leave any behind, then we should be good to go without a `zap` stanza.

**Comment by miccal** [comment]
@connor-oleary-pieces how does one find the download link for this from the `homepage`? I can only see an option to download the installer `Pieces.pkg`, which installs an `app`.

**Comment by connor-oleary-pieces** [comment]
> @connor-oleary-pieces how does one find the download link for this from the `homepage`? I can only see an option to download the installer `Pieces.pkg`, which installs an `app`.

@miccal We currently don't list downloading the .tgz on our site. If we were to list it (which i think we will soon), it would go under the 'Plugins' section. Should we have a direct download link?

**Comment by miccal** [comment]
> > @connor-oleary-pieces how does one find the download link for this from the `homepage`? I can only see an option to download the installer `Pieces.pkg`, which installs an `app`.
> 
> @miccal We currently don't list downloading the .tgz on our site. If we were to list it (which i think we will soon), it would go under the 'Plugins' section. Should we have a direct download link?

Yes, we will need a direct download link to accept this Cask.

**Comment by connor-oleary-pieces** [comment]
@miccal Our site is now updated and has a [direct download link](https://code.pieces.app/plugins). If you scroll to the bottom of that page, it has a section for CLI.

**Comment by miccal** [comment]
Thank you @connor-oleary-pieces.

**Review by miccal — APPROVED** [review]

**Pull request merged**
