### PR TITLE
updated sha256 of sigil.rb due to updated binary

### PR DESCRIPTION
**Pull request by shorshe**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please [amend](http://stackoverflow.com/a/179147/1661012) the commit message to include the name of the updated cask.

**Comment by shorshe** [comment]
I'm using the github web frontend. Hope I did the right thing.

**Comment by vitorgalvao** [comment]
You can’t do it with the web interface. Don’t worry, I can do it for you in a different PR, still maintaining your contribution.

**Comment by shorshe** [comment]
ok, thanks.
How do I do this right next time. Is there a place in the documentation I should read?

**Comment by vitorgalvao** [comment]
Yes, the link I pointed you to in the first reply.

**Comment by vitorgalvao** [comment]
Just include the name of the cask anyway. We usually prefer something of the form `filename: change made to it`.

**Comment by shorshe** [comment]
Thanks, that's what i meant.

**Pull request closed without merging**
