### PR TITLE
Remove tags

### PR DESCRIPTION
**Pull request by vitorgalvao**
Closes https://github.com/caskroom/homebrew-cask/issues/15971.

### CODE REVIEW

**Comment by adityadalal924** [comment]
Vendor tags need to be prepended to name, otherwise we lose that data!

**Comment by vitorgalvao** [comment]
Ah, right, had a note to do that and forgot.

**Comment by vitorgalvao** [comment]
Fixed `name`s.

**Comment by vitorgalvao** [comment]
Merging now as I’d like to make other changes that might conflict.

**Pull request merged**
