### PR TITLE
Update krita to 3.1.2

### PR DESCRIPTION
**Pull request by neutric**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by eMerzh** [comment]
@neutric you should be able to drop the ".0" from the download url 
i asked upstream to make a symlink bewteen the 3.1.2 and 3.1.2.0

**Comment by miccal** [comment]
The download link from [here](https://krita.org/en/download/krita-desktop/) seems to have an extra ".0":
```
http://download.kde.org/stable/krita/3.1.2/krita-3.1.2.0.dmg
```
and it is not obvious it is part of the `version`.

**Comment by eMerzh** [comment]
@miccal 
http://download.kde.org/stable/krita/3.1.2/krita-3.1.2.dmg also work (it the same file)
the .0/.1 was added because of a compilation issue.
so to me it would be better to keep the "version" part in the `#{version}` variable no ?

**Comment by miccal** [comment]
@eMerzh `http://download.kde.org/stable/krita/3.1.2/krita-3.1.2.dmg` redirects to `http://download.kde.org/stable/krita/3.1.2/krita-3.1.2.0.dmg`, so for now it is best to leave it as @neutric has it, and hopefully this will be rectified in the next release.

**Comment by vitorgalvao** [comment]
If the `.0` is being added to the cask now and will need to be removed on the next update *and* not having the `.0` works the same, why bother adding it now?

**Comment by miccal** [comment]
@eMerzh can you provide a link to your suggestion that the `.0` was added in error?

**Comment by eMerzh** [comment]
I have no link  like that but on IRC they said it was to fix a build issue in Windows. 
And they've added the symlink.
 
So .0 and without zero are the same file and so, 

I'm also in favor of removing the 0 as it will make next update "harder"  but I'll be fine if it stays there

**Comment by miccal** [comment]
@eMerzh done - thank you for your help.

**Comment by neutric** [comment]
Thanks and sorry, wasn't at the computer all day...

**Comment by vitorgalvao** [comment]
Verified locally due to Travis delays.

**Pull request merged**
