### PR TITLE
Use BetterTouchTool vendors appcast, not a third-party one

### PR DESCRIPTION
**Pull request by tomtastic**
Problem : 
www.corecode.io/macupdater is a paid app, and frequently carries incorrect appcast information in it's feed (https://www.corecode.io/macupdater/appcasts), we shouldn't rely on this, and it was incorrect at the time of committing this change.

Solution :
The vendors appcast should be used : https://updates.folivora.ai/appcast_manual.xml

Reasoning :
BetterTouchTool developer discussion here : https://community.folivora.ai/t/appcast-wrong-current-version/19605/3

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> Problem :
> www.corecode.io/macupdater is a paid app

That’s neither a problem nor related to the situation. Quite the contrary, HBC is in way better shape and cask updates happen faster because of MacUpdater. You need only search for contributions by @core-code and @suschizu (who are HBC maintainers!) to see what I mean.

> and frequently carries incorrect appcast information in it's feed (https://www.corecode.io/macupdater/appcasts), we shouldn't rely on this, and it was incorrect at the time of committing this change.

That specific appcast is unique in its solution. See https://github.com/Homebrew/homebrew-cask/pull/75004 as to why and how it was implemented. While imperfect—and we knew it would be because it’s dependent on when and how often [its creation script is run](https://github.com/Homebrew/homebrew-cask/pull/75004#issuecomment-570617349)—it was a vast improvement over what we had before and a 100% HBC official solution which just so happened to be hosted on that server.

> Solution :
> The vendors appcast should be used : https://updates.folivora.ai/appcast_manual.xml

That is the correct solution, yes. The only reason we hadn’t done it before is that we didn’t know about that appcast and were working with the best we could under the circumstances.

Thank you for the update.

@core-code Good news, that script and appcast can be retired!

**Review by vitorgalvao — APPROVED** [review]

**Comment by core-code** [comment]
>  frequently carries incorrect appcast information in it's feed 

not really true. the information is correct but the script to generate the appcast runs only every 2 hours. so there is a window of up  to two hours when the information might be 'old'


>  The only reason we hadn’t done it before is that we didn’t know about that appcast and were working with the best we could under the circumstances.

we've used the official appcasts for BetterTouchTool before but decided against using it because it is very very very frequently out-of-sync with the version offered for download for the homepage. creating an appcast that specifically tracks the version on their hompage was our solution to this problem.

**Comment by vitorgalvao** [comment]
Because we’ve never (that I recall) had this specific appcast and it’s [recommended by the developer](https://community.folivora.ai/t/appcast-wrong-current-version/19605/2), I’m cautiously optimistic. We should be able to know soon if this one finally fixes our problems.

**Comment by tomtastic** [comment]
> > frequently carries incorrect appcast information in it's feed
> 
> not really true. the information is correct but the script to generate the appcast runs only every 2 hours. so there is a window of up to two hours when the information might be 'old'

I stand corrected, thank you for the explanation. 👍

**Comment by vitorgalvao** [comment]
@tomtastic The new appcast isn’t good either. Since you’ve already initiated a conversation with the developer, do you mind enquiring as to why that’s the case? Specifically: **why is there no appcast that is kept in sync with the download offered on the homepage**? Seems like a weird oversight; this should be automated on the developer’s side.

**Comment by core-code** [comment]
i don't think we need to ask this question. developers almost never have appcasts that are in sync with the homepage download. we don't have either. it is a standard procedure to use the homepage download as kind of 'beta test light' and only bring over existing users once no new user which has downloaded from the homepage complains.

**Comment by tomtastic** [comment]
> @tomtastic The new appcast isn’t good either. Since you’ve already initiated a conversation with the developer, do you mind enquiring as to why that’s the case? Specifically: **why is there no appcast that is kept in sync with the download offered on the homepage**? Seems like a weird oversight; this should be automated on the developer’s side.

Developer response :

> Sorry I really don't want to maintain more appcasts :slight_smile:
> The manual one is the one you should use, everything else is irrelevant.

**Pull request merged**
