### PR TITLE
dosbox-x ARM support

### PR DESCRIPTION
**Pull request by lucyllewy**
Note that the version is slightly different for the ARM version vs the x86_64 version for the same release after the comma.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by diddledan** [comment]
I'm confused. The sha256sums are coming out different on my system.

**Comment by diddledan** [comment]
The commit d57e4da uses the sha256sums gained from using `curl | sha256sum` - saving the files first seems to be giving me different sha256sum than the `curl | sha256sum`.

**Comment by carlocab** [comment]
That's because the URL redirects you elsewhere, but `curl` doesn't follow redirects automatically.

Try `curl -L <URL> | sha256sum`. Dropping the `-L` will just give you the checksum of the page marking a redirect.

**Comment by diddledan** [comment]
aha. Thanks for the pointer. I completely forgot that GitHub downloads are redirected, and that curl doesn't automatically follow by default.

**Comment by diddledan** [comment]
that's better. I can actually install it locally now. Sorry about the commit noise :-(

**Comment by diddledan** [comment]
Hmm, but the installed app is reported as "broken, and you should move it to the bin" by macOS. (I'm on arm on this machine)

**Comment by carlocab** [comment]
Isn't that just the new "unidentified developer" message?

**Comment by diddledan** [comment]
Yes, it seems it's the unsigned app message - very helpful of apple to explain in the dialog what it means (I joke): joncampbell123/dosbox-x#2163

**Review by reitermarkus — APPROVED** [review]

**Pull request merged**
