### PR TITLE
Delete impactor.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
[Suspected of malware](https://github.com/Homebrew/homebrew-cask/issues/56223#issuecomment-551698790).

```
impactor (added 1169 days ago)
30 days: 49 (#1083)
90 days: 184 (#907)
365 days: 734 (#853)
```

### CODE REVIEW

**Comment by cristian-calin** [comment]
it's not malware. it's a legit app created by [Jay Freeman](https://en.wikipedia.org/wiki/Jay_Freeman). not all things reported by virustotal are malware, many are false-positives.

**Comment by jakeajames** [comment]
This is a false positive. And not just that but whomever made that comment i'll quote in a moment is very misinformed

> is an old jailbreaking tool to sideload things into your iOS device

Impactor is only a sideloading tool, not a jailbreaking tool. Also, it's not that old, it came out like 3 or 4 years ago.

> I don't know if it's even maintained anymore

All you need to do is some simple research, it's constantly updated, saurik literally tweeted about it a few days ago.

> as Cydia kinda went defunct

No it didn't. Cydia still gets updates, although it's not on the hands of saurik anymore.

> BUT, I would argue that it probably doesn't have any legitimate purposes anymore

That's a stupid thing to say considering a ton of people use Impactor all the time (well maybe not right now as a server-side change by Apple broke it, but you get the point)

**Comment by Brandon-T** [comment]
How can you guys even delete it without checking. Lol.

**Comment by bermudalocket** [comment]
I'm disappointed and quite frankly a little shocked at how easily this PR was accepted and merged.

**Comment by RexSonic** [comment]
The Homebrew project has really gone to shit lately

**Comment by Gangster8192** [comment]
I smell Apple.

**Comment by ran-dall** [comment]
@jakeajames Thanks for clarifying those points. I understand and can appreciate your points. I have no real opinion on this and support both the delete and re-addition, as whatever the HBC maintainers see fit. However, let me clarify a few things.

The only sort of [acceptable `appcast`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md) I was able to dig up was [here on Saurik's site](https://git.saurik.com/wxWidgets.git); which would support that this tool hasn't been worked on since 2016 (and has been around for a lot longer than "3 or 4 years.")  I understand that new information was posted a few days ago, but when I posted that comment (https://github.com/Homebrew/homebrew-cask/issues/56223#issuecomment-551976570) it was Nov. 8, so there was no new credible information available. Same goes for Nov. 12 when @vitorgalvao pushed this PR. Contrary to popular belief, I did do a Google search, and I updated my comment with what I thought was the most reliable information; so that all angles could be considered.

I'm not trying to start an argument, but simply state the facts from an `HBC` standpoint. HBC really does try its best to maintain all the software well-groomed and up-to-date. But remember, if you don't agree with the decisions taken by HBC, [you can always make your own `tap`](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) and host whatever software you see fit. HBC tries to stay as agnostic as possible (ref. `java`) while also keeping the HBC user in mind. That said, HBC is made up of volunteers that are usually not experts in every piece of software that's maintained. 

That said, as one of the more 'prolific' contributors to HBC, I welcome all constructive criticisms and concerns that I can help solve on my end. But, as HBC users, let's keep in mind the [Homebrew Code of Conduct](https://github.com/Homebrew/.github/blob/master/CODE_OF_CONDUCT.md#code-of-conduct).

Thanks again @jakeajames 🙏

**Comment by vitorgalvao** [comment]
All the users being disrespectful on this issue are welcome to stop using Homebrew. It takes a special kind of entitlement to complain and insult maintainers and collaborators—**volunteers working for free**—without having ever contributed to the project.

If you disagree with a decision, make a PR and don’t be condescending.

You will be banned on the next offence.

**Pull request merged**
