### PR TITLE
Update itch from 1.17.0 to 1.18.0

### PR DESCRIPTION
**Pull request by tangestani**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ran-dall** [comment]
@tangestani Where did you find `1.18.0`? I can't verify the update.

**Comment by tangestani** [comment]
@ran-dall It's on the project's release page: https://github.com/itchio/itch-setup/releases

**Comment by tangestani** [comment]
I'm actually having issues installing the client using that version of itch-setup. Might be a server issue but I'm gonna try 1.17.0 just in case.

**Comment by ran-dall** [comment]
@tangestani Ok, let me know if you keep having problems, or if I need to test this locally. I did go ahead and updated that `appcast`. Thanks for getting back to you me.

**Comment by tangestani** [comment]
@ran-dall It sorted itself out. Was successfully able to install the latest client (25.4.0) using itch-setup 1.18.0 👍

**Pull request merged**
