### PR TITLE
moom 4.0.1

### PR DESCRIPTION
**Pull request by sashkab**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by sashkab** [comment]
I don't know how to workaround this audit check failure.  Url is expecting version 4.0.0, while live check reports version 4.0. 

```
==> Downloading https://manytricks.com/download/_do_not_hotlink_/moom400.dmg
########################################################################################################################################################################## 100.0%
==> Downloading and extracting artifacts
==> Downloading https://manytricks.com/download/_do_not_hotlink_/moom400.dmg
Already downloaded: /Users/b/Library/Caches/Homebrew/downloads/8817094d2523e2a0c5aaeb4e6f28e92cd25129e75e15e393c93f5451e1e23e77--moom400.dmg
audit for moom: failed
 - Version '4.0.0' differs from '4.0' retrieved by livecheck.
 - Version '4.0.0' differs from '4.0' retrieved by livecheck.
moom
  * Version '4.0.0' differs from '4.0' retrieved by livecheck.
Error: 1 problem in 1 cask detected.
```

**Comment by daeho-ro** [comment]
The livecheck url clearly indicates that the next version is `4.0`.

```
<item>
			<title>Moom 4.0</title>
			<sparkle:minimumsystemversion>10.13</sparkle:minimumsystemversion>
			<sparkle:releasenoteslink>https://manytricks.com/moom/releasenotes/?rref=appcast</sparkle:releasenoteslink>
			<sparkle:thresholdtimestamp>1718841600</sparkle:thresholdtimestamp>
			<sparkle:learnmorelink>https://manytricks.com/moom/?learn=more</sparkle:learnmorelink>
			<pubdate>Wed, 21 Aug 2024 00:00:00 +0000</pubdate>
			<enclosure url="https://manytricks.com/download/_do_not_hotlink_/moom400.1.dmg" sparkle:version="4044" sparkle:shortversionstring="4.0" sparkle:dsasignature="MCwCFHdAcKBZOVxXW09rTAdsuvuDb4SDAhReh6iG7iGTpAcNOFnP3Eb3p3rXUA==" length="8079678" type="application/octet-stream">
		</enclosure>
</item>
```

**Review by samford — COMMENTED** [review]
Upstream reworked the most recent release while I was working on a solution (thankfully). Before, the most recent dmg was `moom400.1.dmg` but now they've created a proper 4.0.1 release (using `moom401.dmg`) and 4.0 is back to a reasonable filename (`moom400.dmg`).

One moment and I'll push a commit to update this to 4.0.1 and modify the `livecheck` block to handle a mismatch between the dotless version in the filename and the `shortVersion`. This will allow us to continue using `version.no_dots` in the `url` and it will also handle omitted numbers that aren't 0 (unlike the `ljust(3, "0")` approach).

This will handle a mismatch where the filename version is longer than the `shortVersion` but it won't handle the reverse. I've simply left a `TODO` comment, as handling that situation is less straightforward and not currently necessary.

**Review by p-linnane — APPROVED** [review]
Thank you @samford!

**Pull request merged**
