### PR TITLE
Update xamarin-ios from 13.8.1.17 to 13.14.1.30

### PR DESCRIPTION
**Pull request by robertleeblairjr**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Page shows 13.10.

**Comment by robertleeblairjr** [comment]
> Page shows 13.10.

Yep. I had tried to update with stable version but download links were broken. This current cask version is preview release channel, as well. Funnily, it seems like the stable versions download links are quite hidden and are only offered in the VS studio app release. I can look for stable channel versions. But, since the preview release versions in the cask were quite old, then I just went with it's merely updating a preview channel version with a newer preview channel version.

**Comment by vitorgalvao** [comment]
> Funnily, it seems like the stable versions download links are quite hidden and are only offered in the VS studio app release.

How is that process? Does the app bundle those versions? Do they link you to a page to download? Our goal here should be to figure out a working system.

**Comment by robertleeblairjr** [comment]
> > Funnily, it seems like the stable versions download links are quite hidden and are only offered in the VS studio app release.
> 
> How is that process? Does the app bundle those versions? Do they link you to a page to download? Our goal here should be to figure out a working system.

This like the other Xamarin software bundles are downloaded from Microsoft's servers for the update. Visual Studio downloads the updates and I'll try to capture the servers its pulling from to see if they're the same for all Xamarin. It seems like MS doesn't update the webpage to reflect updates but I'll look into something more uniform across the Xamarin builds to submit a PR. I agree it's a little bit all over the place with versions/channels and I realize these should be stable channel. Thanks for replying.

**Comment by robertleeblairjr** [comment]
Have some free time and will look for the Xamarin stable channel versions to update this one from 13.8 preview release.

**Pull request closed without merging**
