### PR TITLE
virtualbox: add arm64 version

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by p-linnane** [comment]
This should be submitted to `homebrew-cask-versions` since it is a beta.

**Comment by yurikoles** [comment]
>But There Is No Stable Version!
>When software is only available as a beta, development, or unstable version, its cask can go in the main repo. When >stable versions become available, only those will be accepted as subsequent updates.

There is no stable version of VirtualBox for ARM64 macOS.

**Comment by p-linnane** [comment]
Correct, but I don't think we should mix a beta arm64 version with a stable x86_64 version.

**Comment by yurikoles** [comment]
> Correct, but I don't think we should mix a beta arm64 version with a stable x86_64 version.

Because why? And alternative is to create a beta ARM64-only cask, that will be eventually silently deleted and users will need to figure out themselves that it's time to switch to back to stable cask?

**Comment by p-linnane** [comment]
My position is that I do not think it's wise to mix stable and beta in a cask. You can open a PR to update the one in `homebrew-cask-versions`. There is no more productive conversation to be had on this matter, so I'll be locking this.

**Pull request closed without merging**
