### PR TITLE
Update librewolf from 95.0-2 to 95.0.1

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
Copied from https://github.com/Homebrew/homebrew-cask/pull/116051#issuecomment-997313441

```
Matched Versions:
95.0.1,1,5bb6190211fa0013084409c1ae2bffcd => #<Version:0x00007fdb5b305ed8 @version="95.0.1,1,5bb6190211fa0013084409c1ae2bffcd", @detected_from_url=false>
95.0,2,7972ac43891a576a17b90753be3694a0 => #<Version:0x00007fdb5b305e60 @version="95.0,2,7972ac43891a576a17b90753be3694a0", @detected_from_url=false>
[...]
librewolf : 95.0-2,7972ac43891a576a17b90753be3694a0 ==> 95.0.1,1,5bb6190211fa0013084409c1ae2bffcd
```
`livecheck` matches the newest version as well but ends up picking the wrong one.

**Comment by bevanjkay** [comment]
@neutric
On arm livecheck is returning a different version.

```
brew livecheck librewolf
librewolf : 95.0-2,eeb57ce10660d7e33a18898609873bcb ==> 95.0-2,eeb57ce10660d7e33a18898609873bcb
```

**Comment by neutric** [comment]
@bevanjkay One moment, I am fixing.

**Comment by bevanjkay** [comment]
Good solution! Thanks @neutric

**Pull request merged**
