### PR TITLE
Updates to CleanMyMac version, download URL and some uninstall/zap file paths

### PR DESCRIPTION
**Pull request by MitchellCash**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by core-code** [comment]
this seems like a beta version. 

the official download from the website leads to version 4.5.1
the update-check in the app itself claims that version 4.5.1 is the latest one
and the release notes from the website say that version 4.5.1 is the latest one

we have 3 pieces of evidence that the version submitted here is not official, so i will send a PR to revert this.

**Comment by core-code** [comment]
Submitted (https://github.com/Homebrew/homebrew-cask/pull/73824)

**Comment by MitchellCash** [comment]
@core-code very odd! I just grabbed the latest version from their home page when I made this PR which showed 4.5.4.3.

If you go to the home page (https://macpaw.com/cleanmymac) it actually shows 4.5.4.4 as the downloadable version right now if you inspect the ‘Free Download’ URL.

Either way happy for you to drop the version back if you see fit!

**Comment by core-code** [comment]
hm ok thank you there. the weird thing is that the download here
https://macpaw.com/cleanmymac/whats-new#whatsnext
still leads the old version

**Comment by core-code** [comment]
but i guess if its linked at ANY place from the homepage it is ok, so sorry for the noise. still i wonder if its not better to stick to the version in the feed.

**Comment by vitorgalvao** [comment]
I noticed both things before merging. CI gave the “appcast at URL does not contain the version number” and when I checked the homepage the “Free Download” link pointed to (and still does) to 4.5.4.4. But when I viewed the page’s source, they were still referencing 4.5.1 in other places.

> but i guess if its linked at ANY place from the homepage it is ok

What made me decide to merge, given the information, is that it was the main link on the page that pointed to it. We’ve always sided with the homepage as the ultimate source of truth above appcasts (which are often behind). Not doing so only leads to more PRs for which closing is difficult to justify.

**Comment by core-code** [comment]
thanks. i wouldn't have said anything if i found the link both of you have seen first. for some weird reason they have a download link on their release notes site that links to the old version. i didn't consider that they might have a different download link on their front page. my bad. sorry for the noise.

**Comment by core-code** [comment]
sorry to followup again. it seems the 4.5.4.3 version was removed now from their website for real. i'll send a PR to downgrade.

**Pull request merged**
