### PR TITLE
Update monolingual to 1.7.6

### PR DESCRIPTION
**Pull request by ghost**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by neutric** [comment]
Thanks for catching and fixing this! `cask-repair` must not like Casks catering to different OS releases...

**Comment by neutric** [comment]
...or the problem more likely is that I am on 10.11 still and thus `cask-repair` downloaded and checksummed the version for 10.11.

**Comment by vitorgalvao** [comment]
> ...or the problem more likely is that I am on 10.11 still and thus `cask-repair` downloaded and checksummed the version for 10.11.

Yep. `cask-repair` uses bash and a bunch of trickery. It always replaces the last `sha256`, but at the same time uses `fetch`, so it downloads according to your macOS version.

Will fix that shortly to always `fetch` for the latest macOS.

**Comment by neutric** [comment]
I encountered the same thing a while ago, just forgot about it... looking forward to the new shiny.

**Comment by vitorgalvao** [comment]
https://github.com/vitorgalvao/tiny-scripts/commit/ba00020f0b876e258114ed6cb25f78c630b826d3.

Thank you for the notice, @neutric.

**Comment by neutric** [comment]
Thanks for the swift fix, @vitorgalvao!

**Pull request merged**
