### PR TITLE
Update telegram to 4.0-130816

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by RJHsiao** [comment]
Upgrade failed with error message below: 
```
Error: Checksum for Cask 'telegram' does not match.

Expected: b44c0ddd864ec7e78f7ad2a758029c0a0693cf94494fc04cc4680d7f56e1fab8
Actual:   1c497eeeae8146434a1fbc04e7c7c82de5fd152431e3c6cb376c284563e0a75d
```

**Comment by brianmorton** [comment]
@RJHsiao 
```
$ brew cask audit --download telegram
==> Downloading https://osx.telegram.org/updates/Telegram-4.0-130638.app.zip
######################################################################## 100.0%
==> Verifying checksum for Cask telegram
audit for telegram: passed
```

So while I don't doubt that you are having an issue, it seems irreproducible to me.

**Comment by brianmorton** [comment]
@vitorgalvao @commitay what can we do here? do we have to do a virustotal/contact the devs thing or can this just get an updated checksum?

**Comment by commitay** [comment]
VirusTotal: https://github.com/Homebrew/homebrew-cask/pull/48752#issuecomment-398907864

**Pull request merged**
