### PR TITLE
gateblu: replace the app stanza with a pkg stanza

### LINKED ISSUE #15440: Gateblu won't symlink after being downloaded
I'm not sure why this is happening but here it is.

Homebrew 0.9.5 (git revision 8f39d; last commit 2015-11-25)

```bash
dylson-macosx:~ n370$ brew cask install gateblu
==> Downloading https://s3-us-west-2.amazonaws.com/gateblu/gateblu-ui/latest/Gateblu.d
######################################################################## 100.0%
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/gateblu/latest/Gateblu.app'
```

```bash
dylson-macosx:~ n370$ brew cask install gateblu --vebose
==> Downloading https://s3-us-west-2.amazonaws.com/gateblu/gateblu-ui/latest/Gateblu.d
Already downloaded: /Library/Caches/Homebrew/gateblu-latest.dmg
==> hdiutil: mount failed - Resource busy
Error: Empty plist input
```

I finally installed it manually using the downloaded DMG

```bash
dylson-macosx:~ n370$ open /Library/Caches/Homebrew/gateblu-latest.dmg 
```

Then I searched for help a little bit more but still got the issue.

```bash
dylson-macosx:~ n370$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Already up-to-date.
Error: caskroom/cask/brew-cask 0.59.0 already installed
dylson-macosx:~ n370$ brew cask install --verbose gateblu
==> Downloading https://s3-us-west-2.amazonaws.com/gateblu/gateblu-ui/latest/Gateblu.dmg
Already downloaded: /Library/Caches/Homebrew/gateblu-latest.dmg
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/gateblu/latest/Gateblu.app'
dylson-macosx:~ n370$ brew -v
Homebrew 0.9.5 (git revision 82f27; last commit 2015-11-26)
dylson-macosx:~ n370$ 
```

I'm going to try to use the the gateblu I installed from the downloaded binary which is now on Service Version: 5.0.6, UI Version: 3.4.8

### PR DESCRIPTION
**Pull request by n370**
@adityadalal924 I still have to set up an uninstall and a zap stanza.  However, before I update this PR with it can you please point me out how to test the current modifications? Thank you!

### CODE REVIEW

**Comment by adityadalal924** [comment]
You can check your Cask with `brew cask audit gateblu.rb --download` and `rubocop gateblu.rb`

You can test if you need the `allow_untrusted` by removing it and trying to `brew cask install gateblu`

For adding the uninstall stanza, use the packageID of  `com.octoblu.*` (and testing by doing `brew cask uninstall gateblu`)

**Comment by n370** [comment]
I'm not sure why an empty app remains on my /Applications directory.

screen shot 2015-11-30 at 11 18 12

```bash
dylson-macosx:homebrew-cask n370$ ./developer/bin/list_pkg_ids_by_regexp 'com.octoblu.*'
No match.
dylson-macosx:homebrew-cask n370$ 
```

And I'm not sure if a zap stanza is necessary at all, look.

```bash
dylson-macosx:homebrew-cask n370$ sudo find / -type f -iname 'gateblu'
Password:
find: /dev/fd/3: Not a directory
find: /dev/fd/4: Not a directory
/Users/n370/Projects/Forks/homebrew-cask/.git/logs/refs/heads/gateblu
/Users/n370/Projects/Forks/homebrew-cask/.git/logs/refs/remotes/origin/gateblu
/Users/n370/Projects/Forks/homebrew-cask/.git/refs/heads/gateblu
/Users/n370/Projects/Forks/homebrew-cask/.git/refs/remotes/origin/gateblu
dylson-macosx:homebrew-cask n370$
```

**Comment by adityadalal924** [comment]
Yep, looks like a zap stanza is not needed (and that's okay).

Add in an `:delete => '/Applications/Gateblu.app'` to the `uninstall` stanza to take care of the errant file left over. Also you should add an empty line between stanzas.

See [`gog-galaxy.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/gog-galaxy.rb) for an example.

**Comment by vitorgalvao** [comment]
Also, when making the final changes, please [squash your commits](http://davidwalsh.name/squash-commits-git) and [amend](http://stackoverflow.com/a/179147/1661012) the commit message to include the name of the updated cask.

**Comment by n370** [comment]
Guys let me know if you need me to take any further action.

**Comment by adityadalal924** [comment]
Thank you for the contribution. It was merged directly as 0fd1d6b775d6f5e7a28d9cb03685d3f2ad945946 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by n370** [comment]
Thank you @adityadalal924. I'll look forward to contribute more as long as I can.

**Pull request closed without merging**
