### PR TITLE
Rename pomodone to roundpie, update to 1.5.1558

### PR DESCRIPTION
**Pull request by samford**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

-----

This renames the `pomodone` cask to `roundpie`, updating the URLs and `livecheck` block in the process. The app name is still `PomoDoneApp.app` in the current RoundPie dmg file but that may be something that changes on the next release (i.e., this is still the same version as before the rename, so they may have simply recycled the existing dmg).

### CODE REVIEW

**Comment by bevanjkay** [comment]
@samford Usually the token follows the app name in casks, regardless of what name is used elsewhere.

**Comment by samford** [comment]
> Usually the token follows the app name in casks, regardless of what name is used elsewhere.

Ah, thanks for the heads up (my cask knowledge is always lacking).

While reworking this, I saw that upstream released a new 1.5.1558 version today that renames the app to `RoundPie.app`, so I think we should be able to go forward with the rename now. I've updated `roundpie.rb` accordingly (and added a `zap` stanza in the process), so we'll see how this does.

**Comment by samford** [comment]
`RoundPie.app` isn't signed, so that's the main problem now:

```
audit for roundpie: failed
 - Signature verification failed:
/private/tmp/d20231226-11572-l48tlv/RoundPie.app: rejected

macOS on ARM requires software to be signed.
```

**Comment by bevanjkay** [comment]
The signing check pnly applies to new casks at the moment. CI is just seeing the rename as an added file. So we can potentially ignore the error. In future the audit will apply everywhere.

**Review by miccal — APPROVED** [review]

**Pull request merged**
