### PR TITLE
plugdata 0.8.2

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by jipumarino** [comment]
Hi @krehel I'm getting a SHA256 mismatch when trying to install. Manually downloading the .pkg file also gives me a different digest: 9507f316d36593f5ca13b15eda26640279b71dd2bd383030d0a18b4fa9120864.

**Comment by krehel** [comment]
@jipumarino - thanks.

I've opened #160822.  Feel free to open a PR in the future - we welcome (and need!) community contributions. 😄 

Looks like upstream reuploaded the files after this was merged (per their comment on the Releases page), hence the mismatch.

**Comment by jipumarino** [comment]
@krehel thanks! It's my first time here and wasn't sure if I was missing something (I didn't notice the release re-upload), I'll make sure to open a PR next time :)

**Comment by krehel** [comment]
No worries @jipumarino - appreciated all the same!  We'll get it addressed.

**Pull request merged**
