### PR TITLE
Update perforce from 20.1,1953492 to 19.2,1960190

### PR DESCRIPTION
**Pull request by dscho**
After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

This PR was generated by [a script](https://github.com/gitgitgadget/keep-homebrew-perforce-up-to-date/blob/master/run.sh) running in [an Azure Pipeline](https://dev.azure.com/gitgitgadget/git/_build?definitionId=11&_a=summary).

### CODE REVIEW

**Comment by core-code** [comment]
why the downgrade? according to 
https://www.perforce.com/perforce/doc.current/user/p4vnotes.txt
the 20.1 version is the newest

**Comment by dscho** [comment]
This is an automated script that downloads the newest file from the recorded URL... maybe that URL is now wrong?

Will take a look as soon as I'm on a computer.

**Comment by dscho** [comment]
> Will take a look as soon as I'm on a computer.

I fixed the PR and force-pushed.

Now I will fix the automated script to _not_ override the version.

**Comment by dscho** [comment]
Never mind, the URL the script looked at _hardcoded_ the version. Will close this here PR.

**Comment by dscho** [comment]
Funny thing: r20.1 was updated last on Fri, 24 Apr 2020 22:00:20 GMT, while r19.2 was updated last on Wed, 13 May 2020 17:18:31 GMT, i.e. two-and-a-half weeks _later_. Whatever.

**Comment by core-code** [comment]
thanks! :)

**Pull request closed without merging**
