### PR TITLE
Update postman from 8.7.0 to 8.8.0

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by cho-m — APPROVED** [review]

**Comment by vladimyr** [comment]
Maybe this was too fast 🤔 

In-app update check returns:
image

and their changelog still doesn't have 8.8.0 entry: https://www.postman.com/downloads/release-notes/

**Comment by bevanjkay** [comment]
@vladimyr If you download the Postman app from their downloads page they will give you 8.8.0
https://www.postman.com/downloads/

It also says 8.8.0 is the latest version in-app.

**Comment by vladimyr** [comment]
> @vladimyr If you download the Postman app from their downloads page they will give you 8.8.0
> [postman.com/downloads](https://www.postman.com/downloads/)

Saw that one. That is exactly why I said too fast. It seems to me that they updated the download link but haven't updated anything else (changelog, update feed).

> It also says 8.8.0 is the latest version in-app.

That happens because their update API returns status code 204 if the queried version is latest or _higher_.
https://dl.pstmn.io/update/status?channel=stable&currentVersion=8.8.0&arch=64&platform=osx

Try switching `currentVersion` with 8.7.0 or obviously non-existent 9.0.0 and you'll see the same result. But if you do:
```
$ curl -s 'https://dl.pstmn.io/update/status?channel=stable&currentVersion=8.6.9&arch=64&platform=osx' | jq -r '.version'
```
you'll get 8.7.0 back.

**Comment by bevanjkay** [comment]
@vladimyr I would say that we should be serving the same version the user would receive if they downloaded it manually from upstream.

**Comment by vladimyr** [comment]
@bevanjkay Fully agree! My only suggestion is to wait a few hrs/days to give Postman folks the time to update their feed and changelog because I firmly believe this whole _situation_ won't exist in few days.

**Pull request merged**
