### PR TITLE
yandex 23.5.4

### PR DESCRIPTION
**Pull request by razvanazamfirei**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by krehel — DISMISSED** [review]

**Review by samford — COMMENTED** [review]
Hmm, the existing `livecheck` block works fine for me locally (regardless of the presence/absence of the `arch` parameter). Not sure why it doesn't work on CI, though.

We have some logic in `Strategy#page_headers` that automatically retries with the `:browser` user agent if `:default` doesn't work, so I don't imagine that's the issue. Can anyone replicate this issue outside of CI?

**Comment by miccal** [comment]
> Hmm, the existing `livecheck` block works fine for me locally (regardless of the presence/absence of the `arch` parameter). Not sure why it doesn't work on CI, though.
> 
> We have some logic in `Strategy#page_headers` that automatically retries with the `:browser` user agent if `:default` doesn't work, so I don't imagine that's the issue. Can anyone replicate this issue outside of CI?

It is working locally for me.

**Comment by bevanjkay** [comment]
Yes this is failing for me locally. Make sure you are testing with `brew audit --cask --online <token>` and not just running `brew livecheck` because audit can have some small differences in how it tests the livecheck.

**Comment by bevanjkay** [comment]
I'm being served a captcha.

https://browser.yandex.ru/showcaptcha?cc=1&mt=D7ADCD4B1FC0A40D636F8CB5561639ADF5BA7F80596EA059991410783C210CA853C98E282BA5B91A6DF37E5011748BE5FCCA24E347E40B21ECC2EED0B7458266B689990F938EFD9AE68000EB4ADDAB5290CB2F3A6239474CFDBDC096&retpath=aHR0cHM6Ly9icm93c2VyLnlhbmRleC5ydS9kb3dubG9hZD9vcz1tYWMmYXJjaD1hcm02NCZmdWxsPTE%2C_d77eedc09092c31d3a9fbe1b1a35c17e&t=2/1689154449/4319d11688b475a24189034dad346975&u=6762afaa-a8e015ac-da344f2c-eb3b5a84&s=fb19d878ffc4018f294d2a875838a19b

**Comment by razvanazamfirei** [comment]
My `livecheck` change was only for style purposes.

Both versions work locally with both `brew livecheck` and `brew audit`. Below are the headers I'm getting.

```fish
❯ http --print h 'https://browser.yandex.ru/download/?os=mac&full=1'
HTTP/1.1 302 Found
Accept-CH: Sec-CH-UA, Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version, Sec-CH-UA-Platform-Version, Sec-CH-UA-WoW64
Content-Length: 270
Content-Type: text/plain; charset=utf-8
Critical-CH: Sec-CH-UA, Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version, Sec-CH-UA-Platform-Version, Sec-CH-UA-WoW64
Date: Wed, 12 Jul 2023 10:28:41 GMT
Location: https://download.cdn.yandex.net/browser/yandex/23_5_4_696_46114/ru/Yandex.dmg?vup=1&browser=NA/32/NA&pps=installID%3D6788360351689157721_1689157721733&yandexuid=6788360351689157721&hash=9084ace5170cce80a3d7257448ecae38&download_date=1689157721&.exe
Set-Cookie: _yasc=cWPE27qFe3vzxxZciVECo8CU4d+md/UeC0m/btC21Ky9jsvy8B7xeRuW7IA6; domain=.yandex.ru; path=/; expires=Sat, 09 Jul 2033 10:28:41 GMT; secure
Set-Cookie: i=oFYOk+xMzaOQ35RNzKE375c/q0Z8ta6997InJAq1N/Jfj/P5UHYhQpfqF8IMBKGlM8GeIJ5B5liHDk7clsAeaHWRYtU=; Expires=Fri, 11-Jul-2025 10:28:41 GMT; Domain=.yandex.ru; Path=/; Secure; HttpOnly
Set-Cookie: yandexuid=6788360351689157721; Expires=Fri, 11-Jul-2025 10:28:41 GMT; Domain=.yandex.ru; Path=/; Secure
Strict-Transport-Security: max-age=31536000
Vary: Accept
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

❯ http --print h 'https://browser.yandex.ru/download/?os=mac&arch=arm64&full=1'
HTTP/1.1 302 Found
Accept-CH: Sec-CH-UA, Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version, Sec-CH-UA-Platform-Version, Sec-CH-UA-WoW64
Content-Length: 270
Content-Type: text/plain; charset=utf-8
Critical-CH: Sec-CH-UA, Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version, Sec-CH-UA-Platform-Version, Sec-CH-UA-WoW64
Date: Wed, 12 Jul 2023 10:29:12 GMT
Location: https://download.cdn.yandex.net/browser/yandex/23_5_4_679_46093/ru/Yandex.dmg?vup=1&browser=NA/32/NA&pps=installID%3D4435562101689157752_1689157752443&yandexuid=4435562101689157752&hash=21e1c2f5c1c7523d58aa05a4288c48da&download_date=1689157752&.exe
Set-Cookie: _yasc=XhP7BWs3m7Cjz4f0HJSgPWJIwUWUMZhD7yMZL4+WWoSECI2cEs6UmQueFKc=; domain=.yandex.ru; path=/; expires=Sat, 09 Jul 2033 10:29:12 GMT; secure
Set-Cookie: i=fdVsTVE3++3uSfI8QN6/xApFpQ/tiAibbwRfDtEPYtp2vsq7cdq+xiVun75HRrg8+H8u6gYdkdzEMt+bjVsVR6DVGKY=; Expires=Fri, 11-Jul-2025 10:29:12 GMT; Domain=.yandex.ru; Path=/; Secure; HttpOnly
Set-Cookie: yandexuid=4435562101689157752; Expires=Fri, 11-Jul-2025 10:29:12 GMT; Domain=.yandex.ru; Path=/; Secure
Strict-Transport-Security: max-age=31536000
Vary: Accept
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```

**Comment by bevanjkay** [comment]
It did work for me just now.

**Review by miccal — APPROVED** [review]

**Pull request merged**
