### PR TITLE
standard-notes 3.152.0

### PR DESCRIPTION
**Pull request by razvanazamfirei**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — DISMISSED** [review]

**Comment by reitermarkus** [comment]
@amanharwara, your commit at https://github.com/standardnotes/app/commit/37854c00b201a4748d0888daf7d974a685f5a009 marks all releases as pre-release, yet the website links to these. So are these actually pre-releases or stable releases?

**Comment by reitermarkus** [comment]
That commit doesn't seem like it does anything for the desktop app, but the desktop releases also seem to be hard-coded to pre-releases: 

https://github.com/standardnotes/app/blob/decb94f6e5f64ea1b5f6ef274e16bd3997b97db1/.github/workflows/desktop.release.test.yml#L59

**Comment by amanharwara** [comment]
@reitermarkus Hi, we do mark every release as pre-release by default, but almost every release can be considered stable. We mark them as pre-release and selectively unmark them for the auto-updater.

**Comment by SMillerDev** [comment]
Shouldn't we use the unmarked ones too then?

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
