### PR TITLE
Update korean-spelling-checker to 1.4.1

### PR DESCRIPTION
**Pull request by buo**

### CODE REVIEW

**Comment by adityadalal924** [comment]
The download URL per the homepage is `http://appletree.or.kr/automator/korean-spelling-checker-workflow.zip`

I don't speak Korean - is the github one more updated, or are they the same?

**Comment by buo** [comment]
I just compared those two versions, and they are the same
except the one from the homepage has QuickLook directory which is in .gitignore file.

The github repository is maintained by the same person who maintains the homepage,
so I think they should be always the same.

**Comment by buo** [comment]
As discussed in issue #2264, the service with `.workflow` doesn't work unless users install it manually via Service Installer.
Hardlinking it didn't work for me, so `cp -r` is used instead to copy the `.workflow` to the `~/Library/Services/` directory.

**Comment by adityadalal924** [comment]
It looks like the only two Casks that use the service stanza are this and `markdown-service-tools.rb`, but this seems like a band-aid rather than an actual fix.

As I'm not sure what do do in this case, I'll leave it up to @caskroom/maintainers

**Comment by vitorgalvao** [comment]
Seeing as `service`s aren’t used much and we have https://github.com/caskroom/homebrew-cask/issues/13201 that automatically fixes this, this solution is not great. We also have `app`s that would benefit from such a solution, yet we don’t fix them in this manner. In this case, we’re sure to forget about this once the good solution is introduced.

The cask should be left as is regarding its installation (broken), with [an added `caveat`](https://github.com/caskroom/homebrew-cask/blob/012d03a2e0008b8f49cd7d2dc3bbbd8fcac3fea6/Casks/megasync.rb#L13L20).

**Comment by buo** [comment]
I added caveats and squashed commits.

**Comment by adityadalal924** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 1aa866c6393adc8269cf2edd13a8a68da3a48276. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
