### PR TITLE
Update syntax-highlight from 1.0.b24 to 1.0.b22

### PR DESCRIPTION
**Pull request by sbarex**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by i0ntempest** [comment]
This is done by the ML system too?

**Comment by ran-dall** [comment]
@sbarex Is the author of the software.

**Comment by sbarex** [comment]
sorry, I don't know well cask and I don't know how this pull request was created... I use cask-repair

**Comment by i0ntempest** [comment]
I use that too, just make sure to check existing update PR/current version before using it

**Pull request merged**
