### PR TITLE
Update android-platform-tools from 30.0.0 to 30.0.5

### PR DESCRIPTION
**Pull request by zhangyoufu**
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

```
% brew livecheck --debug android-platform-tools

Cask:             android-platform-tools
Livecheckable?:   Yes

URL:              https://dl.google.com/android/repository/platform-tools-latest-darwin.zip
Strategy:         HeaderMatch

Matched Versions:
30.0.5,eabcd8b4b7ab518c6af9c941af8494072f17ec4b
android-platform-tools : 30.0.5,eabcd8b4b7ab518c6af9c941af8494072f17ec4b ==> 30.0.5,eabcd8b4b7ab518c6af9c941af8494072f17ec4b
```

### CODE REVIEW

**Comment by zhangyoufu** [comment]
I have no idea why `brew audit` reports that `The URL https://developer.android.com/studio/releases/platform-tools is not reachable`.

**Comment by miccal** [comment]
> `brew audit` passed on my machine. I have no idea why `brew audit` in CI environment reports that
> 
> > The URL https://developer.android.com/studio/releases/platform-tools is not reachable.

This is a common error for these Casks.

**Comment by miccal** [comment]
Thank you @zhangyoufu.

**Review by miccal — APPROVED** [review]

**Pull request merged**
