### PR TITLE
Update gotomeeting.rb from 10.12.0 to 10.13.1

### PR DESCRIPTION
**Pull request by iMonZ**
Updated to 10.13.1

### CODE REVIEW

**Comment by iMonZ** [comment]
The change log is outdated
the last two updates are missing...
LogMein just doesn't like change logs

**Comment by vitorgalvao** [comment]
If I go to the website and [the download page](https://support.goto.com/meeting), I still get on the latest URL (https://link.gotomeeting.com/latest-dmg) `10.13.1.18705`.

**Comment by iMonZ** [comment]
And if you try to download this from the link inside the cask?
Because this is not the latest version!

**Comment by vitorgalvao** [comment]
> And if you try to download this from the link inside the cask?

The link inside the cask is relative to the version, so that doesn’t help. I believe you that the version you’ve submitted is the latest, but is it the latest *stable* version? Because that’s what matters.

**Comment by iMonZ** [comment]
Yes this is the latest stable version!
If you curious you can install this application and press on update!

**Comment by vitorgalvao** [comment]
> If you curious

Not in the slightest. I dislike this company and their practices. Yet, I still need to verify it. There’s an amount of due diligence that has to be taken, and that you also benefit from.

> you can install this application and press on update!

I see no way to update on the installed application.

**Comment by iMonZ** [comment]
> > If you curious
> 
> Not in the slightest. I dislike this company and their practices. Yet, I still need to verify it. There’s an amount of due diligence that has to be done, and that you also benefit from.
> 
> > you can install this application and press on update!
> 
> I see no way to update on the installed application.

That’s right this application is horrible from the technical view still I’m forced to use it :(

You can update this tool from the menu bar

**Comment by vitorgalvao** [comment]
> You can update this tool from the menu bar

That’s where I’m looking. Can you be more specific or show a screenshot?

**Comment by iMonZ** [comment]
Oh the update button is gone 
https://ibb.co/TYCwS2N

**Comment by vitorgalvao** [comment]
> Then you get an error message that your version is too old to join the meeting with an update message.

Alright, that worked. *But* I also know from past research on other GoTo apps that they want people on the exact same versions of interacting software. GoToAssist will even upgrade or downgrade itself for version parity. So that isn’t conclusive evidence that this is the stable version. We need to rely on *something* from upstream. So we have two choices:

1. Change this cask to `version :latest`, `sha256 :no_check`, and `url "https://link.gotomeeting.com/latest-dmg"`.
2. Leave as is and upgrade to `10.13.1,18705`.

**2** seems more sensible to me. We rely on upstream and don’t lose `appcast` functionality.

Ping @Homebrew/cask.

**Comment by iMonZ** [comment]
> > Then you get an error message that your version is too old to join the meeting with an update message.
> 
> Alright, that worked. _But_ I also know from past research on other GoTo apps that they want people on the exact same versions of interacting software. GoToAssist will even upgrade or downgrade itself for version parity. So that isn’t conclusive evidence that this is the stable version. We need to rely on _something_ from upstream. So we have two choices:
> 
> 1. Change this cask to `version :latest`, `sha256 :no_check`, and `url "https://link.gotomeeting.com/latest-dmg"`.
> 2. Leave as is and upgrade to `10.13.1,18705` (#92006).
> 
> **2** seems more sensible to me. We rely on upstream and don’t lose `appcast` functionality.
> 
> Ping @Homebrew/cask.

If there are only two choices I would recommend the first one, cause 10.14.0,18962 is definitely the latest stable version.

**Comment by vitorgalvao** [comment]
> cause 10.14.0,18962 is definitely the latest stable version.

No, not _definitely_. Not according to upstream’s website. If you’re sure, we need proof. As stated, the software wanting to update itself when joining a specific meeting is not enough, due to the way they do things.

**Comment by core-code** [comment]
personally i'd just use 'version :latest' in this case. we've even ignored the app from MacUpdater because tracking version numbers for this just doesn't make sense

**Comment by iMonZ** [comment]
I will contact the LogMein support to ask them which version is the latest and if they can update the change log on there website.

**Comment by iMonZ** [comment]
Okay I have contacted the support and they told me that the 10.14 is not out yet and this is an bug!
I will change my commit to 10.13.1

**Comment by vitorgalvao** [comment]
> Okay I have contacted the support and they told me that the 10.14 is not out yet and this is an bug!

Thank you for checking! Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/92006 which also has other fixes.

Still open to changing this to `version :latest` in the future if it’s justified.

**Pull request closed without merging**
