### PR TITLE
Add HighTop.app v1.2.11

### PR DESCRIPTION
**Pull request by sbibauw**
HighTop is a small utility app for provide quick access to some favorite
files and folders via the menu bar.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @sbibauw.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by sbibauw** [comment]
Thanks, @miccal! I didn't know that was usually recommended for a new cask (did not see it on the docs, but might have missed it). But done, with pleasure :-)

**Review by SMillerDev — DISMISSED** [review]

**Comment by unitof** [comment]
@miccal loves his zaps! (And I love @miccal for it.)

**Review by cho-m — APPROVED** [review]
Thank you, @sbibauw

**Pull request merged**
