### PR TITLE
Add MultiDeco v4.14.0

### PR DESCRIPTION
**Pull request by rkoch**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

**One question however remains:** For the download to work consistently I had to change the timestamp in the URL to 2 minutes in the past. Is this acceptable or is there a better solution?

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> For the download to work consistently I had to change the timestamp in the URL to 2 minutes in the past. Is this acceptable or is there a better solution?

That’s certainly unorthodox. Not entirely comfortable accepting the cask, but not seeing a strong reason to refuse it, either.

I removed the caveat since it does not pertain to the installation itself.

**Comment by commitay** [comment]
Checksum has changed.

```
==> Verifying checksum for Cask multideco
==> Note: running "brew update" may fix sha256 checksum errors
audit for multideco: failed
 - download not possible: Checksum for Cask 'multideco' does not match.

Expected: 697321e2448e06d60d1029d5421164c5a83b5bb560c2d549d08b6ba67697ca25
Actual:   3e4e607e4355ebedcc84ce603ad7f90463a82c608451ce9a39ed9635adda934d
File:     /Users/travis/Library/Caches/Homebrew/Cask/multideco--4.14.0.dmg&keytag=1538541&qwerty=1501390035&os=mac_intel
```

**Comment by vitorgalvao** [comment]
The `keytag` number also changes.

Seems to me like this website is going through a whole lot of trouble to making the download non-`curl`able.

I think we need to refuse it for now. @rkoch If you’re willing to talk to upstream and they give a better solution, we can try again. Thank you for the contribution.

**Comment by rkoch** [comment]
I will try to find a better solution and reopen if is stable enough.

Thank you for your support and sorry for the troubles :)

**Pull request closed without merging**
