### PR TITLE
Updated Graphviz homepage

### PR DESCRIPTION
**Pull request by cafferata**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download graphviz` is error-free.
- [x] `brew cask style --fix graphviz` left no offenses.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You deleted the page.

**Comment by cafferata** [comment]
I deleted the homepage because the webpage is not responding.

**Comment by vitorgalvao** [comment]
If you delete the page, the cask breaks and `audit` fails. The mandatpry commands tell you that.

You either find a replacement and change it to that, or you remove the cask, as appropriate.

Just please don’t check all the boxes when you haven't actually followed the instructions. It’s particularly bad when you submit such a barrage of PRs.

**Comment by cafferata** [comment]
> If you delete the page, the cask breaks and audit fails. The mandatpry commands tell you that.

That is not true, the audit doesn't fail if the homepage is empty.

**Comment by vitorgalvao** [comment]
Looks like you’re right. Though it does fail in Travis. Weird. Will have to look into that.

**Pull request closed without merging**
