### PR TITLE
surfshark: update livecheck to Sparkle, set `auto_updates true`

### PR DESCRIPTION
**Pull request by nevack**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

image

### CODE REVIEW

**Comment by krehel** [comment]
Thanks for this PR - if the app is using Sparkle we can likely update the livecheck to use it instead of `:extract_plist`

**Comment by nevack** [comment]
> Thanks for this PR - if the app is using Sparkle we can likely update the livecheck to use it instead of `:extract_plist`

I would gladly apply your suggestion here, but is there any way to test it locally with `brew`?

**Comment by krehel** [comment]
No worries @nevack - I've got it 😄

**Comment by nevack** [comment]
> No worries @nevack - I've got it 😄

One thing worries me - I've got no luck with:
```sh
"$(brew --repository homebrew/cask)/developer/bin/find-appcast" /Applications/Surfshark.app
Looking for Sparkle appcast… curl: option : blank argument where content is expected
curl: try 'curl --help' or 'curl --manual' for more information
Not found.
Looking for electron-builder appcast… Not found.
```

Also:
```sh
grep -R 'SUFeedURL' /Applications/Surfshark.app
Binary file /Applications/Surfshark.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle matches
```

**Comment by krehel** [comment]
I tend to use [Proxyman](https://proxyman.io/) and inspect intercepted traffic when running an update with the software in question.

**Comment by nevack** [comment]
> I tend to use [Proxyman](https://proxyman.io/) and inspect intercepted traffic when running an update with the software in question (and how I found the appcast url).

Yup, can confirm it is located at https://downloads.surfshark.com/macOS/stable/appcast.xml
Thanks for pointing out a way to find this info in the future!

**Review by bevanjkay — APPROVED** [review]

**Comment by krehel** [comment]
Thanks @miccal , got sidetracked and forgot this key step!

**Review by krehel — APPROVED** [review]

**Pull request merged**
