### PR TITLE
Add Yandex.Radio v1.5.7(126)

### PR DESCRIPTION
**Pull request by remarkov**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[closed issues]: https://github.com/Homebrew/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by core-code** [comment]
@vitorgalvao i question whether any 'yandex' stuff should be allowed within homebrew-cask.

i've installed the yandex browser (caskname 'yandex') for testing. 

without asking, it has changed search engines and homepages of Safari, Chrome and Firefox to their Yandex page. it has taken me considerable time to find all those adware plugins it has installed for other browsers.

even after i found and de-installed all those adware plugins (and the yandex browser itself), my Mac was still continiously contacting the yandex server, as verified by a Proxy. 

i deem everything connected to 'yandex' adware and malware. i doubt they should receive any help distributing this shit.

**Comment by vitorgalvao** [comment]
@core-code Due to [the onus of knowing the application falling on the user](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md) and some users wanting apps that others would consider malware (utorrent), we devised [a process for dealing with malware apps](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/apps_with_malware.md).

**Comment by core-code** [comment]
i see, thanks

**Comment by remarkov** [comment]
@core-code @vitorgalvao Actually the app in question, Yandex.Radio is not from Yandex itself. It is a brilliant application which gives user a perfect native UI for the Yandex music service which is available only through web. I guess the most users of the app will be Russians since Yandex offers free radio streams within Russia through their music service.
As for the native Yandex apps - I agree with @core-code - most of them a full of bloatware, however all those add-ons can be disabled during the installation afaik. I personally don't use them anyway.

**Pull request merged**
