### PR TITLE
Add Yack! - Beta.app v50.0.154

### PR DESCRIPTION
**Pull request by goranmoomin**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by pcr910303** [comment]
The version info (v50.0.154) comes from the app info screen, as the website doesn't mentions any versions.

스크린샷 2019-08-21 오후 3 47 54

**Comment by core-code** [comment]
if 
1.) we have no way to keep this version up-to-date with an 'appcast' and
2.) this is fixed download URL anyway,
shouldn't this have version: latest?

**Comment by pcr910303** [comment]
@core-code Removed version number from cask formula.

**Comment by vitorgalvao** [comment]
Thank you, but this is a [walled build](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) so [we will not accept it](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#unofficial-vendorless-and-walled-builds).

**Comment by pcr910303** [comment]
@vitorgalvao The [download page](https://yack.io/download/) contains a link to the download and is searchable from Google. Is this considered walled?

The problem is that the [main site](https://yack.io) doesn't have a link to the download one. However the download page is on the same host with the site, so according to [the page](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) it isn't walled, right?

**Comment by vitorgalvao** [comment]
It somewhat falls under the same category of websites that require an email for you to download the app but that work if you give a fake email — how’s a user auditing the cask supposed to know they can give a fake email (or in this case, do a web search for the download page) to verify the link? It may be a weak wall, but the vendor has still erected it.

There are eight calls to action on that page, and they all ask for a “beta signup” email. If you do give them an email, they give you another link. They may have a download page, but clearly they don’t want you to use it. Perhaps they’ll improve that once the app is out of beta.

**Comment by pcr910303** [comment]
@vitorgalvao Okay, I'll make a new PR when they get out of beta. Thanks for the clarification!

**Pull request closed without merging**
