### PR TITLE
Update netron to 2.0.2

### PR DESCRIPTION
**Pull request by lutzroeder**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
> It seems the App source '/usr/local/Caskroom/netron/2.0.2/Netron.app' is not there.

**Comment by commitay** [comment]
Can you check that this is fixed before submitting another PR please?

**Comment by lutzroeder** [comment]
Trying... any insights what is causing this to fail? Ran the same automated script as always.

**Comment by commitay** [comment]
The app is inside a directory. https://github.com/Homebrew/homebrew-cask/pull/50985#issuecomment-414031107

**Comment by lutzroeder** [comment]
Thank you. Looks like a recent `electron-builder` regression.

**Pull request closed without merging**
