### PR TITLE
Update intellij-idea-ce.rb

### PR DESCRIPTION
**Pull request by yogendra**
Replacing uninstall 'delete:' key 'script:'
`/usr/local/bin/idea` file is not installed as part of this package.
This file is created by a user action in the application. As a result it could be present anywhere on path.
`uninstall delete:` key requires sudo, which may not be available.
Using uninstall script seems a better option.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
`uninstall script` is for uninstallation scripts the apps provide. Use `postflight` instead. Also verify first if `idea` exists and only then try to delete it.

Finally, shouldn’t the other Intellij casks benefit from this as well?

> `uninstall delete:` key requires sudo, which may not be available.

That true of any app, so it’s not a valid argument here.

**Comment by yogendra** [comment]
Thanks for that. Let me check post flight. 

Is there a preferred way of checking for a file? Any existing cask I could check?

As per sudo part, I agree it could be a common problem. But, when we install the launcher from gui, we do not need sudo. In case of uninstall delete: there is no way to avoid sudo. Am I missing something?

Once this cask is fixed I will fix other intellj casks, including once that do not have this.

**Comment by vitorgalvao** [comment]
I’ll do the first one and you do the others.

https://github.com/caskroom/homebrew-cask/pull/31867.

**Comment by yogendra** [comment]
Ok. Thanks

**Comment by vitorgalvao** [comment]
Ignore the failing test in that PR. It is correct, it’s just Travis that is having issues. I’m trying to fix those now. You can go ahead.

**Comment by yogendra** [comment]
In #31870 , `File.rm(file)` wasn't working on my machine. I am using macOS system ruby 2.0.0. So, I changed it to `File.delete(file)`. 
Made changes to all 10 tools.

**Pull request closed without merging**
