### PR TITLE
updated sony-ericsson-bridge (4.3)

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Comment by adityadalal924** [comment]
Merged as 8c7a35f310ebcd5ba6ae10c635a74e7f1cdae678.

**Comment by vitorgalvao** [comment]
Merged as d30abb1c9fcad1673a1eacb623fae50e7c74935e.

**Comment by adityadalal924** [comment]
Wow, terrible timing - hopefully this hasn't messed anything up.

Will stop fastmerging now

**Comment by vitorgalvao** [comment]
Wondered the same. Looked at the commit history and everything seems fine.

**Comment by adityadalal924** [comment]
Hooray for protected branches!

**Comment by vitorgalvao** [comment]
> Hooray for protected branches!

It doesn’t force push, so even if we didn’t use protected branches, it’s likely it wouldn’t have made a mess.

**Pull request closed without merging**
