### PR TITLE
Update onlyoffice from 7.1.1 to 7.2.0

### PR DESCRIPTION
**Pull request by Amorymeltzer**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by Amorymeltzer** [comment]
Not sure I understand the error, looks like the livecheck failed somehow?

**Comment by p-linnane** [comment]
The issue is that there is only an arm64 binary on the release page. The CI machines are x86_64, so it's not finding anything when it attempts its check.

**Comment by Amorymeltzer** [comment]
The x84_64 is there, but it is hidden behind "show all 14 assets."  Perhaps the livecheck method can't see behind that?

**Comment by p-linnane** [comment]
Correct. GitHub has recently made some changes to how the assets are served for performance reasons. This is affecting livecheck (see https://github.com/Homebrew/brew/issues/13853). I've been working to remedy the known affected casks (I have a tracking post in that issue), but have not made it around to this one yet.

**Review by samford — COMMENTED** [review]
Unfortunately it looks like upstream isn't 100% consistent about release files (e.g., some are missing certain file types) but, as was mentioned, we can't easily match versions from filenames on the release page anymore (without making additional requests for each release to fetch the assets list HTML).

For the time being, I've pushed a commit to update the `livecheck` block to simply use the `GithubLatest` strategy and match the version from the tag. This may surface a version for a release that doesn't have the dmg files we want but hopefully anyone updating the cask will notice this before creating a PR.

**Review by samford — APPROVED** [review]

**Comment by Amorymeltzer** [comment]
If it works it works, thanks!  I noticed the downloads page from the website homepage lists the version and provides both links, but it would require changing the URL scheme to an unversioned URL, and it seemed harder (and always a drag) to get the regex to work on the html.

**Pull request closed without merging**
