### PR TITLE
fix bilibili sha256 mismatch

### PR DESCRIPTION
**Pull request by exherb**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download bilibili` is error-free.
- [x] `brew cask style --fix bilibili` left no offenses.

Fix bilibili sha256 mismatch

### CODE REVIEW

**Comment by adidalal** [comment]
Was there a re-tag? shasum shouldn't change without a corresponding version bump, generally

**Comment by adidalal** [comment]
Updating the `:checkpoint` value in `appcast` is required. You can find it with `curl --silent --compressed "{{appcast_url}}" | sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256 | awk '{ print $1 }'`.

Alternatively, you may wish to use [`cask-repair`](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair). It can at once update the cask’s version (according to what you give it) taking care of updating both the cask’s `sha256` and the appcast’s `:checkpoint`, while still giving you the chance to perform other manual fixes.

You can easily install it with `brew install vitorgalvao/tiny-scripts/cask-repair`. `cask-repair --help` will show you some options, but as a whole the script will guide you through the update process.

**Comment by adidalal** [comment]
Verified and fixed in https://github.com/caskroom/homebrew-cask/pull/20544

**Comment by exherb** [comment]
thanks.

**Pull request closed without merging**
