### PR TITLE
Add cask for pac-man

### PR DESCRIPTION
**Pull request by pacman-admin**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [Y ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [Y ] `brew audit --cask --online <cask>` is error-free.
- [Y ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ Y] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [Y ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [Y ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [Y ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by pacman-admin** [comment]
Does anyone know why this happens? ->
Error: It seems the App source '/usr/local/Caskroom/pac-man/10.31/Pac-Man.app' is not there.

**Comment by bevanjkay** [comment]
Is the app file contained inside the `zip` or is it nested in a folder inside the `zip`?

**Comment by pacman-admin** [comment]
Ohhhh.....
I think it is in a folder!!
Thanks for mentioning that.

<Oops!>

That answers that question.

**Comment by pacman-admin** [comment]
Do I need to include README.txt, LISCENCE.txt, and COPYING.txt?
I use GPL 3.

**Comment by pacman-admin** [comment]
Should I use .bzip2?

**Comment by pacman-admin** [comment]
I fixed it!

**Comment by pacman-admin** [comment]
Everything passed except the signing because I'm not gonna pay $99 for an apple developer certificate.
Is there some other way?

**Comment by pacman-admin** [comment]
brew audit and brew style just broke on my mac so I can't test my cask any more.

**Comment by krehel** [comment]
Thank you for your submission, but we cannot accept it because it does not pass our signature verification check that are a requirement for new submissions:

> macOS on ARM requires software to be signed. Please contact the upstream developer to let them know they should sign and notarize their software.

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap)

**Comment by pacman-admin** [comment]
How do I notarize my software?

**Pull request closed without merging**
