### PR TITLE
latest Discord version

### PR DESCRIPTION
**Pull request by corbt**

### CODE REVIEW

**Comment by adityadalal924** [comment]
Thank you for the contribution. It needed some fixes, so they were made in aa67befb44cadb2a5b7a7f78867b529665d30291. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by corbt** [comment]
@adityadalal924 A visual inspection doesn't reveal any differences between this PR and `aa67bef`. For my own future reference, what changed?

**Comment by adityadalal924** [comment]
@corbt I just changed the commit message to provide a version number. (ie. git commit --amend)

**Comment by corbt** [comment]
Ok, thanks for the clarification!

**Pull request closed without merging**
