### PR TITLE
free-telly 16.1

### PR DESCRIPTION
**Pull request by emanresusername**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

### CODE REVIEW

**Comment by miccal** [comment]
Tested successfully for me.

**Comment by adidalal** [comment]
This is a slippery road...will leave it open for further discussion though. I feel it's closer to Audacity's case, where were fighting against the DL host to get a link.

**Comment by miccal** [comment]
Good point @adidalal - these kind of site deliberately make it difficult not to use a web browser due to ads that pay for the bandwidth.

Perhaos @emanresusername could contact [the website](https://www.tvaddons.ag/contact-us/) and ask if bypassing AFH like this is allowed?

**Comment by emanresusername** [comment]
assuming `AFH` = `androidfilehost.com` 😅 
can do
that being said, even though i did do a little net-panel sleuthing to get at the url used here, it does seem like they are in favor of [programatic access](https://www.androidfilehost.com/api/docs/)

**Comment by miccal** [comment]
> assuming AFH = androidfilehost.com

Yes. 

See the PR [here](https://github.com/caskroom/homebrew-cask/pull/27517) as to the reason for the use of caution on our part.

**Comment by emanresusername** [comment]
👍 submitting the contact form now, will report back when they do

**Comment by emanresusername** [comment]
responsiveness disclaimer
idk if they'll get back to me, but i also included a link to this pr, so guess we just wait and see

**Comment by emanresusername** [comment]
contact established, conversations to continue tomorrow, i'll keep this updated with the latest

**Comment by emanresusername** [comment]
@miccal got the 👍 to "do whatever i want" 😄 
AFH is purely cause they don't want to host it on there servers, no ad revenue concerns or anything like that

**Comment by miccal** [comment]
Thanks for letting us know @emanresusername.

**Review by miccal — APPROVED** [review]

**Pull request merged**
