### PR TITLE
pull_request_template: add signature verification language

### PR DESCRIPTION
**Pull request by razvanazamfirei**
This is a proposed update to the PR template in response to the number of new casks submissions that fail signature verification.

### CODE REVIEW

**Comment by SMillerDev** [comment]
I think all this "double verified" isn't helping. It would be better IMHO to get rid of the language suggesting you don't actually need to do these steps.

**Comment by reitermarkus** [comment]
> language suggesting you don't actually need to do these steps

Where do we suggest that the steps aren't needed?

**Comment by SMillerDev** [comment]
> Important: Do not tick a checkbox if you haven’t performed its action. Honesty is indispensable for a smooth review process.

This suggests to me that you don't actually have to perform them. I remember other messages to this extend but I can't find them right now.

**Comment by razvanazamfirei** [comment]
Some of our [documentation](https://docs.brew.sh/Cask-Cookbook#stanza-uninstall) suggests submitting even if not all checkboxes are ticked:
>If you cannot design a working uninstall stanza, please submit your cask anyway. The maintainers can help you write an uninstall stanza, just ask!

I'm not attached to any specific language. This version was modeled after Issue template:
>- [ ] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

Overall, I just think we need a better way to get across the fact that we no longer accept unsigned applications.

**Comment by SMillerDev** [comment]
Do we already specify it in https://docs.brew.sh/Acceptable-Casks?

**Comment by razvanazamfirei** [comment]
It's the last bullet under Rejected Casks:
> Common reasons to reject a cask entirely:
> [...]
> * App fails with GateKeeper enabled on Homebrew supported macOS versions and platforms (e.g. unsigned apps fail on Macs with Apple silicon/ARM).

As of late, signing and notability issues are the main reasons casks get rejected. If you think we should rework the documentation instead, I think they need to be signaled better in the documentation.

**Pull request closed without merging**
