### PR TITLE
Update broken binary in MacVim 8.0.129

### PR DESCRIPTION
**Pull request by tinhkyaw**
- [x] brew cask audit --download {{cask_file}} is error-free.
- [x] brew cask style --fix {{cask_file}} left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by lifepillar** [comment]
I have tried this, but running `mvim` results in

```
/usr/local/bin/mvim: line 86: /usr/local/bin/../../../MacVim.app/Contents/MacOS/Vim: No such file or directory
/usr/local/bin/mvim: line 86: exec: /usr/local/bin/../../../MacVim.app/Contents/MacOS/Vim: cannot execute: No such file or directory
```

Also, this cask should create links for `mvimdiff`, `mview`, and possibly `gview`, `gvim`, `gvimdiff` (but *not* `view` and `vimdiff`). Although they are all symlinks to `mvim`, they behave differently (e.g., `mview` opens a file in read-only mode).

**Comment by fedde-s** [comment]
Is this related to issue #31178?

**Comment by lifepillar** [comment]
@fedde-s Yes, this pull request aims at addressing that issue.

**Comment by fedde-s** [comment]
Thanks! About the symlinks, they seem to have been removed in an attempt to solve an unrelated issue in pull request #30955.

**Comment by tinhkyaw** [comment]
Thanks for updating this.  I just knew it was broken and I only looked back 1 PR before it was broken.  Should have looked further :-).

**Comment by 13k** [comment]
@lifepillar that shell script error seems to be a bug from upstream. For some reason the `mvim` shell script in the app package sets the vim application directory by using a rather naive method:

```
VIM_APP_DIR=`dirname "$0"`/../../..
```

When dealing with symlinks, this will most certainly break, which is almost 100% of the cases when using macvim. What's odd, though, is that that file in [macvim's repository](https://github.com/macvim-dev/macvim/blob/snapshot-128/src/MacVim/mvim#L14) doesn't set `VIM_APP_DIR` and if you check file history, it was never changed in that way. Only the shipped file within the app package is setting that variable.

**Comment by miccal** [comment]
I have updated this to version 8.0.129 - @lifepillar can you test this?

**Comment by miccal** [comment]
Tested locally - seems to be working now.

**Comment by lifepillar** [comment]
@miccal No, it's not fixed yet. Please note:

- snapshot-129 has moved binaries into `MacVim.app/Contents/bin/`, not `MacVim.app/Contents/MacOS`.
- you shouldn't link `MacVim` and `Vim`.

@13k How about creating a shim script that sets `$VIM_APP_DIR$`, instead of symlinking?

**Comment by lifepillar** [comment]
Ok, this is what works for me:
https://gist.github.com/lifepillar/5540d93b197308b0b8820ce746b1415a

**Comment by miccal** [comment]
https://github.com/caskroom/homebrew-cask/pull/31217

**Comment by lifepillar** [comment]
@miccal That looks fine.

Is there a reason why the other links cannot be reinstated, as in my gist above? I cannot reproduce https://github.com/caskroom/homebrew-cask/issues/30953 (which seems the reason why they were removed in the first place) and, according to https://github.com/caskroom/homebrew-cask/pull/30955, that issue should have been fixed by https://github.com/Homebrew/brew/pull/2347.

Having `mview`, `mvimdiff` etc… would be useful.

**Comment by miccal** [comment]
@lifepillar you are welcome to open a PR yourself if you like.

**Comment by 13k** [comment]
@lifepillar answering your question directed to me: Despite installers being probably the best place where to configure paths, since they know the concrete installation paths, I don't think we need. MacVim seems to do a pretty good job at guessing the paths already.

**Comment by lifepillar** [comment]
@13k In fact, with the latest snapshot MacVim's scripts work just fine. I have opened a [PR](https://github.com/caskroom/homebrew-cask/pull/31218) as suggested by @miccal to create the necessary symlinks.

**Comment by 13k** [comment]
:+1:

**Pull request merged**
