### PR TITLE
Add SwiftPlantUMLApp.app v1.2

### PR DESCRIPTION
**Pull request by MarcoEidinger**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [X] `brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by MarcoEidinger** [comment]
I am unable to run `brew audit` or `brew style` due to issues on my local machine but as the CI checks are passing I hope PR is good to go to be merged :)

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @MarcoEidinger.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by miccal** [comment]
Note: https://github.com/Homebrew/homebrew-core/pull/88865

**Comment by MarcoEidinger** [comment]
@miccal thank you for correcting the formatting! Anythig else to do or is this PR good to go to get merged?

**Comment by miccal** [comment]
Thank you @MarcoEidinger.

**Comment by MarcoEidinger** [comment]
Thank you!! :)

**Pull request merged**
