### PR TITLE
Update hubstaff from 1.5.15,2652 to 1.5.16,2850

### PR DESCRIPTION
**Pull request by JeffreyBytes**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by spaz926** [comment]
The `livecheck` is failing. I'm not sure why. The regex looks right, but it isn't getting the build number from the url.
Checked it here: https://rubular.com/r/lKNHnN9DqbQ7Zc

**Comment by reitermarkus** [comment]
Seems like the sparkle appcast also contains releases for other platforms, I didn't even know that was a thing.

They all have the same version though, so I think we can change `mac-os-x` to `.*?`.

**Comment by reitermarkus** [comment]
No we can't actually, since the download ID is different for each platform.

**Pull request merged**
