### PR TITLE
Add IINA-danmaku.app v1.0.7

### PR DESCRIPTION
**Pull request by liby**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

Also of note: `iina-plus` and `iina-danmaku` are two completely different kinds of cask.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This has already been refused. You’re aware of that and still ticked the box saying it wasn’t. I didn’t refuse the other submission because you made a mistake on a URL, that would be absurd-

It’s not `iina-danmaku`, at best it would be `xjbeta-iina` to follow the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md). In addition, it has an [invalid use of `target:`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md#target-should-only-be-used-in-select-cases). Finally, it doesn’t even pass our [notability requirements](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md) (the forks are for the original).

What even is the purpose of this fork? It doesn’t describe why it’s needed, and we don’t want to start shoving every fork in here. We already have `iina-plus`, which indeed does something different.

**Comment by liby** [comment]
> This has already been refused. You’re aware of that and still ticked the box saying it wasn’t. I didn’t refuse the other submission because you made a mistake on a URL, that would be nonsensical.

I ticked because this is a new submission. I didn't realize that at all. OK?

> It’s not iina-danmaku, at best it would be xjbeta-iina to follow the token reference. In addition, it has an invalid use of target:. Finally, it doesn’t even pass our notability requirements (the forks are for the original).

If you don't understand, it is recommended not to define it. OK?

> What even is the purpose of this fork? It doesn’t describe why it’s needed, and we don’t want to start shoving every fork in here. We already have iina-plus, which indeed does something different.

As I said, `iina-danmaku` is doing something different. I won't be bored enough to submit content that already exists.

> You’re mixing up two different repos in the cask

And what I want to say is that, in [#87070](https://github.com/Homebrew/homebrew-cask/pull/87070), What you said made me very confused, so I submitted it again. 
I don't think you need to say these unimportant things at all.

Just like in [#87098](https://github.com/Homebrew/homebrew-cask/pull/87098), where it does not meet the requirements, post it directly, so that it is simple and clear, and it will not make people feel confused.

**It is clear at a glance where the requirements are not met and where the requirements are specified.**

**Comment by liby** [comment]
The emoji you posted is childish and ridiculous. It's funny. I hope you can be a man. 
Besides, do you want me to step on this one for you?
@vitorgalvao

**Comment by vitorgalvao** [comment]
> The emoji you posted is childish and ridiculous.

I have no idea what you’re talking about. I haven’t used a single emoji. Also, you tagged the wrong person.

> Can you communicate like a man?

Again, no idea what that means. You’re either asking me to be more aggressive (as I perceive your post to be), which is wildly counter-productive, or you’re insinuating a woman’s (or non-binary person) method of communication has something wrong or inefficient with it, which is flat-out wrong, stereotypical, an insulting to a majority of the population.

> Besides, do you want me to step on this one for you?

Once again, no clue.

Locking the conversation before it degrades any further. I ask that you watch your tone, or we’ll be forced to block you.

**Pull request closed without merging**
