### PR TITLE
Update chromium from 909619 to 909622

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
@bevanjkay we may need to keep an eye on this change :)

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/109546#issuecomment-894638589

**Comment by bevanjkay** [comment]
@miccal Does CI get cranky if the versions are the same inside the if blocks?

**Comment by miccal** [comment]
> @miccal Does CI get cranky if the versions are the same inside the if blocks?

Yes, as I just discovered!

**Pull request merged**
