### PR TITLE
Revert "Update protonvpn to 1.5.1"

### PR DESCRIPTION
**Pull request by suschizu**
Reverts Homebrew/homebrew-cask#59703
I cannot find v1.5.1 anywhere - where did you find this version-download @flaviocamilo ?

### CODE REVIEW

**Comment by flaviocamilo** [comment]
ProtonVPN itself tried to update to this version.

**Comment by vitorgalvao** [comment]
> ProtonVPN itself tried to update to this version.

image

Can’t reproduce that. Are you using a beta version?

**Comment by suschizu** [comment]
me too … I also get 1.4.2 as latest version

**Comment by flaviocamilo** [comment]
Sorry, guys. Now I see that I have the option `Early Access` enabled. Will pay attention to this on future updates.
screen shot 2019-03-04 at 19 43 43

**Pull request merged**
