### PR TITLE
Cache Homebrew kegs and casks along with Ruby gems

### PR DESCRIPTION
**Pull request by jawshooah**

### CODE REVIEW

**Comment by adidalal** [comment]
According to Travis support `/usr/local` should definitely not be cached - looks like build times jumped from 2 minutes -> 15 after this change as well, as the cacher times out.

Not sure of the impact of caching `/opt/homebrew-cask/Caskroom`

**Comment by jawshooah** [comment]
What about `/usr/local/Cellar`?

**Comment by adidalal** [comment]
Worth a shot, but it seemed to be okay without caching any of it - not sure exactly what needs to be cached but just going the gems should be enough

**Comment by jawshooah** [comment]
Was thinking of caching the Cellar and Caskroom since we install some kegs
and casks during the build, but that doesn't take very long so it's
probably not worth it.

**Pull request merged**
