### PR TITLE
Update synergy to 1.8.8,25a8cb2

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
actually the 2.0.x versions are beta as can be confirmed here 
https://symless.com/blog/synergy-1-recommended-version
and is also obvious from the url that has been used and contained 'beta'

actually we should downgrade to 1.10.0 as this is the most recent stable version. however, since i aint a customer i don't have the link to this version. so i am submitting a downgrade to the last stable version that we've had

@anothernode @winkey728 @alias-mac @ndobbs would you by any chance have the link to the 1.10.0 version?

**Comment by ndobbs** [comment]
@core-code Here you go: https://binaries.symless.com/synergy/v1-core-standard/v1.10.0-stable-275cdc1c/synergy_1.10.0-stable_b39-275cdc1c_macos.dmg

**Comment by core-code** [comment]
@ndobbs: thanks, awesome! no need to submit a PR, i just pushed an update

**Review by victorpopkov — APPROVED** [review]

**Comment by anothernode** [comment]
Hm, did you notice that there already was a [discussion](https://github.com/Homebrew/homebrew-cask/pull/47465) about this and everyone there agreed to stick to the 2.x branch, including @commitay and @vitorgalvao?

The Synergy developers decided to relabel the 2.x.x versions as "beta" six months after having released 2.0.0 as stable and the current 2.0.12 version is working fine for me.

Anyway, I don't care that much about it, I can always install Synergy 2 by downloading it manually, of course. I just wanted to point out that it was a deliberate decision at some point to stick to the version 2 "beta".

**Comment by core-code** [comment]
@anothernode: sorry i didn't know that. i submitted the downgrade because i was under the impression that beta versions shouldn't be here. i can submit a revert.

**Comment by anothernode** [comment]
@core-code: Don't worry, we are probably dealing with a rather unusual special case here.

I don't really have a strong opinion on what to do know. I expressed before that I would vote for having the 2.x "beta" version in the Cask repository. But I'm not passionate about it, so I would also be fine with now leaving it this way until Symless removes the "beta" label from the 2.x version again.

**Comment by ndobbs** [comment]
I personally would like to stay on the `v1` branch until v2 comes out of beta. I'm a full 'Pro' version paying customer and the v2 beta version of this software removes those paid features (for the time being). I will pay for the upgrade once V2 comes out of beta but for now, this is my reasoning. 

screen shot 2018-07-27 at 9 39 48 am

**Comment by vitorgalvao** [comment]
The [rule stated previously stands](https://github.com/Homebrew/homebrew-cask/pull/47465#discussion_r190187273):

> When an App is only available as beta, development, or unstable versions, **or in cases where such a version is the general standard**, then said version can go into the main repo.

So whatever the devs recommend one uses is what belongs in this repo. It seems [that right now they recommend version 1](https://symless.com/blog/synergy-1-recommended-version), so let’s keep it as that.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-versions/pull/6012 is available to those who want the beta now.

**Comment by ShiroiKuma** [comment]
It would be nice if users already on synergy2 were given notice that a downgrade would be classed as an upgrade. It was quite a shock to see 1.x as an update to 2.x when checking for new versions with brew cask outdated.

**Comment by vitorgalvao** [comment]
@ShiroiKuma Apologies for the inconvenience. This is a rare occurrence so we don’t have neither a strategy nor the resources for it.

**Pull request merged**
