### PR TITLE
Update nanobox to 2.3.0

### PR DESCRIPTION
**Pull request by aericson**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by aericson** [comment]
The version did not change but the sha256 of the official source changed.

**Comment by vitorgalvao** [comment]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by aericson** [comment]
@vitorgalvao There is no public information of the sha256 nor it is signed. AFAIK the only way to verify is by downloading it from https://dashboard.nanobox.io/download "Use Docker Native" option.

**Comment by commitay** [comment]
```
19298f958d56856061d1a93750f01c3ff36a12f3e113b9839704810753684200  nanobox--2.3.0.pkg

Package "nanobox--2.3.0.pkg":
   Status: signed by a certificate trusted by Mac OS X
   Certificate Chain:
    1. Developer ID Installer: Eric Graybill (R6JH5QLWZ5)
       SHA1 fingerprint: 40 88 3F 7B 54 0A 90 7A B2 90 1D 64 EE FA 72 1C AA D2 6F DC
       -----------------------------------------------------------------------------
    2. Developer ID Certification Authority
       SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
       -----------------------------------------------------------------------------
    3. Apple Root CA
       SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
```

**Review by commitay — APPROVED** [review]

**Comment by vitorgalvao** [comment]
> There is no public information of the sha256

From the document:
image

It can be asked for.

**Pull request merged**
