### PR TITLE
Added pdftk 2.02

### PR DESCRIPTION
**Pull request by winkelsdorf**
Cask for pdftk 2.02 package with uninstall and zap methods

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This cask was [removed due to some problems](https://github.com/caskroom/homebrew-cask/issues/7707). Are those fixed, here?

**Comment by winkelsdorf** [comment]
Doing some tests with a fresh VM snapshot right now. I'll let you know.

**Comment by winkelsdorf** [comment]
Hmm, my test looks good so far, but brew doctor still fails. I have no clue why, as the permissions look good (see comparison at the very bottom).

```
Tests-MacBook-Pro:opt test$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. Some versions of the
"InstantOn" component of Airfoil are known to do this.

You should probably change the ownership and permissions of /usr/local
back to your user account.
```

My Testcase: setup a clean VM and did a manual package install (without Homebrew/Cask) and a cask install with another fresh snapshot.

Nothing messed up with /usr, /usr/local or /usr/local/bin from what I can see.

***Test 1: /usr Permissions in clean VM (no /usr/local yet)***
```

Tests-MacBook-Pro:usr test$ ls -ll
total 8
drwxr-xr-x     5 root  wheel    170 Sep  9  2014 X11
lrwxr-xr-x     1 root  wheel      3 May 22 11:26 X11R6 -> X11
drwxr-xr-x  1053 root  wheel  35802 May 22 11:34 bin
drwxr-xr-x   250 root  wheel   8500 May 22 11:25 lib
drwxr-xr-x   170 root  wheel   5780 May 22 15:26 libexec
drwxr-xr-x   244 root  wheel   8296 May 22 11:25 sbin
drwxr-xr-x    43 root  wheel   1462 May 22 11:25 share
drwxr-xr-x     4 root  wheel    136 May 22 11:20 standalone
```

***Installing Homebrew & Cask***
```
Tests-MacBook-Pro:usr test$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/man/man1/brew.1

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir /usr/local
Password:
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local
==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Counting objects: 3586, done.
remote: Compressing objects: 100% (3431/3431), done.
remote: Total 3586 (delta 35), reused 1535 (delta 19), pack-reused 0
Receiving objects: 100% (3586/3586), 2.77 MiB | 1.74 MiB/s, done.
Resolving deltas: 100% (35/35), done.
From https://github.com/Homebrew/homebrew
 * [new branch]      master     -> origin/master
HEAD is now at 1f2c606 slimerjs: fix head build
==> Installation successful!
==> Next steps
Run `brew help` to get started
Tests-MacBook-Pro:usr test$ brew 
Tests-MacBook-Pro:usr test$ brew install caskroom/cask/brew-cask
==> Tapping caskroom/cask
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 2925, done.
remote: Compressing objects: 100% (2810/2810), done.
remote: Total 2925 (delta 131), reused 760 (delta 99), pack-reused 0
Receiving objects: 100% (2925/2925), 5.70 MiB | 3.08 MiB/s, done.
Resolving deltas: 100% (131/131), done.
Checking connectivity... done.
Tapped 1 formula (2904 files, 23M)
==> Installing brew-cask from caskroom/homebrew-cask
==> Cloning https://github.com/caskroom/homebrew-cask.git
Cloning into '/Library/Caches/Homebrew/brew-cask--git'...
remote: Counting objects: 2902, done.
remote: Compressing objects: 100% (2786/2786), done.
remote: Total 2902 (delta 133), reused 747 (delta 100), pack-reused 0
Receiving objects: 100% (2902/2902), 5.69 MiB | 3.01 MiB/s, done.
Resolving deltas: 100% (133/133), done.
Checking connectivity... done.
Note: checking out 'a952b872918e94314878891482f7b8876c4a99cf'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

==> Checking out tag v0.54.0
🍺  /usr/local/Cellar/brew-cask/0.54.0: 2634 files, 10M, built in 7 seconds
```

***Test 2: Permissions after Installing Homebrew & Cask***
```
/usr:

Tests-MacBook-Pro:usr test$ ls -ll
total 8
drwxr-xr-x     5 root  wheel    170 Sep  9  2014 X11
lrwxr-xr-x     1 root  wheel      3 May 22 11:26 X11R6 -> X11
drwxr-xr-x  1053 root  wheel  35802 May 22 11:34 bin
drwxr-xr-x   257 root  wheel   8738 May 24 15:09 include
drwxr-xr-x   271 root  wheel   9214 May 24 15:09 lib
drwxr-xr-x   170 root  wheel   5780 May 22 15:26 libexec
drwxrwxr-x    15 root  admin    510 May 24 15:11 local
drwxr-xr-x   244 root  wheel   8296 May 22 11:25 sbin
drwxr-xr-x    44 root  wheel   1496 May 24 15:09 share
drwxr-xr-x     4 root  wheel    136 May 22 11:20 standalone

Note: /usr/bin is still root:wheel and /usr/local was added with root:admin by Homebrew. 

and /usr/local: 

Tests-MacBook-Pro:local test$ ls -ll
total 80
-rw-r--r--   1 test  admin   3161 May 24 15:10 CODEOFCONDUCT.md
-rw-r--r--   1 test  admin   1103 May 24 15:10 CONTRIBUTING.md
drwxr-xr-x   3 test  admin    102 May 24 15:11 Cellar
-rw-r--r--   1 test  admin   1241 May 24 15:10 LICENSE.txt
drwxr-xr-x  11 test  admin    374 May 24 15:11 Library
-rw-r--r--   1 test  admin   2064 May 24 15:10 README.md
-rw-r--r--   1 test  admin  23801 May 24 15:10 SUPPORTERS.md
drwxr-xr-x   4 test  admin    136 May 24 15:11 bin
drwxr-xr-x   3 test  admin    102 May 24 15:11 opt
drwxr-xr-x   4 test  admin    136 May 24 15:10 share
```

***Installing pdftk***
```
Tests-MacBook-Pro:local test$ brew tap winkelsdorf/custom
==> Tapping winkelsdorf/custom
Cloning into '/usr/local/Library/Taps/winkelsdorf/homebrew-custom'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Checking connectivity... done.
Tapped 0 formulae (32 files, 132K)

Tests-MacBook-Pro:local test$ brew cask install pdftk
==> Downloading https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/pdftk_server-2.02-mac_osx-10.6-setup.pkg
######################################################################## 100.0%
==> Running installer for pdftk; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is PDFtk Server - The PDF Toolkit for the Terminal
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  pdftk staged at '/opt/homebrew-cask/Caskroom/pdftk/2.02' (16M)
```

***Test 3: Permissions after Installing pdftk***

```
/usr:

Tests-MacBook-Pro:usr test$ ls -ll
total 8
drwxr-xr-x     5 root  wheel    170 Sep  9  2014 X11
lrwxr-xr-x     1 root  wheel      3 May 22 11:26 X11R6 -> X11
drwxr-xr-x  1053 root  wheel  35802 May 22 11:34 bin
drwxr-xr-x   257 root  wheel   8738 May 24 15:09 include
drwxr-xr-x   271 root  wheel   9214 May 24 15:09 lib
drwxr-xr-x   170 root  wheel   5780 May 22 15:26 libexec
drwxr-xr-x    15 root  admin    510 May 24 15:11 local
drwxr-xr-x   244 root  wheel   8296 May 22 11:25 sbin
drwxr-xr-x    44 root  wheel   1496 May 24 15:09 share
drwxr-xr-x     4 root  wheel    136 May 22 11:20 standalone

Result: /usr/local is still root:admin

and inside /usr/local: 

Tests-MacBook-Pro:local test$ ls -ll
total 80
-rw-r--r--   1 test  admin   3161 May 24 15:10 CODEOFCONDUCT.md
-rw-r--r--   1 test  admin   1103 May 24 15:10 CONTRIBUTING.md
drwxr-xr-x   3 test  admin    102 May 24 15:11 Cellar
-rw-r--r--   1 test  admin   1241 May 24 15:10 LICENSE.txt
drwxr-xr-x  11 test  admin    374 May 24 15:11 Library
-rw-r--r--   1 test  admin   2064 May 24 15:10 README.md
-rw-r--r--   1 test  admin  23801 May 24 15:10 SUPPORTERS.md
drwxr-xr-x   5 test  admin    170 May 24 15:14 bin
drwxr-xr-x   3 test  admin    102 May 24 15:11 opt
drwxr-xr-x   4 test  admin    136 May 24 15:10 share

finally inside /usr/local/bin:

Tests-MacBook-Pro:bin test$ ls -ll
total 24
-rwxr-xr-x  1 test  admin  791 May 24 15:10 brew
lrwxr-xr-x  1 test  admin   40 May 24 15:11 brew-cask -> ../Cellar/brew-cask/0.54.0/bin/brew-cask
lrwxr-xr-x  1 root  admin   28 May 24 15:14 pdftk -> /opt/pdflabs/pdftk/bin/pdftk

root:admin for pdftk symlink is fine, /opt/pdflabs has the same permissions and doesn't mess with the cask cellar:

Tests-MacBook-Pro:opt test$ ls -ll
total 0
drwxr-xr-x  3 test  staff  102 May 24 15:14 homebrew-cask
drwxr-xr-x  3 root  wheel  102 May 24 15:14 pdflabs

```

To sum it up

***Comparision before/after permissions***

```
/usr - before
drwxr-xr-x  1053 root  wheel  35802 May 22 11:34 bin
drwxrwxr-x    15 root  admin    510 May 24 15:11 local

/usr - after
drwxr-xr-x  1053 root  wheel  35802 May 22 11:34 bin
drwxr-xr-x    15 root  admin    510 May 24 15:11 local

/usr/local - before
total 80
-rw-r--r--   1 test  admin   3161 May 24 15:10 CODEOFCONDUCT.md
-rw-r--r--   1 test  admin   1103 May 24 15:10 CONTRIBUTING.md
drwxr-xr-x   3 test  admin    102 May 24 15:11 Cellar
-rw-r--r--   1 test  admin   1241 May 24 15:10 LICENSE.txt
drwxr-xr-x  11 test  admin    374 May 24 15:11 Library
-rw-r--r--   1 test  admin   2064 May 24 15:10 README.md
-rw-r--r--   1 test  admin  23801 May 24 15:10 SUPPORTERS.md
drwxr-xr-x   4 test  admin    136 May 24 15:11 bin
drwxr-xr-x   3 test  admin    102 May 24 15:11 opt
drwxr-xr-x   4 test  admin    136 May 24 15:10 share

/usr/local - after
total 80
-rw-r--r--   1 test  admin   3161 May 24 15:10 CODEOFCONDUCT.md
-rw-r--r--   1 test  admin   1103 May 24 15:10 CONTRIBUTING.md
drwxr-xr-x   3 test  admin    102 May 24 15:11 Cellar
-rw-r--r--   1 test  admin   1241 May 24 15:10 LICENSE.txt
drwxr-xr-x  11 test  admin    374 May 24 15:11 Library
-rw-r--r--   1 test  admin   2064 May 24 15:10 README.md
-rw-r--r--   1 test  admin  23801 May 24 15:10 SUPPORTERS.md
drwxr-xr-x   5 test  admin    170 May 24 15:14 bin
drwxr-xr-x   3 test  admin    102 May 24 15:11 opt
drwxr-xr-x   4 test  admin    136 May 24 15:10 share

Inside /usr/local/bin - after
Tests-MacBook-Pro:bin test$ ls -ll
total 24
-rwxr-xr-x  1 test  admin  791 May 24 15:10 brew
lrwxr-xr-x  1 test  admin   40 May 24 15:11 brew-cask -> ../Cellar/brew-cask/0.54.0/bin/brew-cask
lrwxr-xr-x  1 root  admin   28 May 24 15:14 pdftk -> /opt/pdflabs/pdftk/bin/pdftk

```

Hope this helps :)

**Comment by vitorgalvao** [comment]
@albcorp @jvenator @evils @michelschinz @jawshooah @rusterholz Any of you care to test it?

**Comment by winkelsdorf** [comment]
Found the difference, ls -ll is not sufficient to show:
/usr/local loses admin write privilege. Files/Folders inside are still correct. 

(sorry for GH not resizing the screenshots properly)

screen shot 2015-05-24 at 15 46 11 - before
screen shot 2015-05-24 at 15 32 56 - after
screen shot 2015-05-24 at 15 46 22 - before
screen shot 2015-05-24 at 15 33 11 - after

**Comment by winkelsdorf** [comment]
Update: Not forgotten, but unfortunately still no feedback from developer.

**Comment by vitorgalvao** [comment]
Not forgotten, but it appears the developer really isn’t interested in this issue. Thank you for all the work, @winkelsdorf.

**Comment by winkelsdorf** [comment]
@vitorgalvao Right, the developer does not seem to to interested at all. You're welcome!

**Comment by youtux** [comment]
I have created a pdftk formula that does not mess up the ownerships at https://github.com/Homebrew/homebrew-binary/pull/344, but the repository is deprecated. Do you have any suggestion about how to make it a Cask?

**Comment by winkelsdorf** [comment]
Sounds great! 

Hmm, rethinking the pdftk cask I created a while back I wonder if it's not better to make it a formula like you already did. Casks are usually for Applications, I think I recreated the above cask because it existed at some point before..

Would you mind proposing your formula to the Homebrew Core project itself? This should be here: 
https://github.com/Homebrew/homebrew-core/

And their contributing FAQ is here:
https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md

But this is just my personal opinion. I am not part of the team.

Would love to see your formula included 👍 

Cheers,
Frederik

**Comment by youtux** [comment]
I think that it will be insta-rejected, since it's a binary only formula.

**Comment by winkelsdorf** [comment]
Yikes, I see. Let's wait if someone is able to rewrite this formula to a cask, that should really do the trick.

+1 for your solution!

**Pull request closed without merging**
