### PR TITLE
Update epic-games to 7.9.4

### PR DESCRIPTION
**Pull request by warmwinter**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
FWIW @vitorgalvao https://www.epicgames.com/unrealtournament/download is still offering `7.9.2`

**Comment by vitorgalvao** [comment]
@brianmorton Thank you.

@warmwinter Where did you get the version from?

**Comment by reitermarkus** [comment]
7.9.4 is available from within the app, which also shows a link to the release notes: https://forums.unrealengine.com/unreal-engine/announcements-and-releases/1928-latest-launcher-release-notes?1809-Latest-Launcher-Release-Notes=

**Comment by warmwinter** [comment]
@vitorgalvao auto update to this version

**Comment by brianmorton** [comment]
Maybe we can use `https://forums.unrealengine.com/unreal-engine/announcements-and-releases/1928-latest-launcher-release-notes?1809-Latest-Launcher-Release-Notes=` as the appcast?

**Comment by commitay** [comment]
The forum URL is unstable so we can't use it as an appcast.

**Pull request merged**
