### PR TITLE
Link Zsh completion for Docker CLI

### PR DESCRIPTION
**Pull request by FranklinYu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Version is not included because this does not involve a new version. It only installs completions to proper location.

If this looks good then I may also update `docker-edge`.

### CODE REVIEW

**Comment by commitay** [comment]
This is already provided by the docker competition formulas.

```
docker-completion
docker-compose-completion
docker-machine-completion
```

Thanks for the PR nonetheless.

**Comment by franklinyu** [comment]
Sorry, I didn't know that. But why do we maintain another three formula when Docker.app comes with the completion already? The approach feels like more work to do… I guess there might have been some discussion about it?

**Comment by commitay** [comment]
The formulas have a better way of installing completions and work with all Docker Casks.

```
  def install
    bash_completion.install "components/cli/contrib/completion/bash/docker"
    fish_completion.install "components/cli/contrib/completion/fish/docker.fish"
    zsh_completion.install "components/cli/contrib/completion/zsh/_docker"
  end
```

**Comment by franklinyu** [comment]
Just curious, is there any Docker Casks besides `docker` and `docker-edge`?

**Pull request closed without merging**
