### PR TITLE
Update skype to 8.37.0.98

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
Verified Latest @ https://support.skype.com/en/faq/FA34778/release-notes-for-skype-for-windows-mac-and-linux

That look right to you? @core-code

**Comment by core-code** [comment]
well, its listed in the release notes, but the default download on the homepage AND the appcast still point to 8.34. 

since we've had problems with updating this too early in the past, i'd advocate holding off until either one of that changes.

**Comment by ran-dall** [comment]
I don’t have a problem with that

**Comment by vitorgalvao** [comment]
Yes, let’s wait a bit.

**Comment by ran-dall** [comment]
Test

**Pull request closed without merging**
