### PR TITLE
Update itunes-volume-control from 1.5.2 to 1.5.3

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
you can update the appcast to 
http://quantum-technologies.iap.uni-bonn.de/alberti/iTunesVolumeControl/iTunesVolumeControlCast.xml.php?version=1.5

**Comment by suschizu** [comment]
I would rather propose this as appcast: 
https://github.com/alberti42/iTunes-Volume-Control#versions 
although its the homepage - but he just lists the new version (incl. download) in this section … 
unfortunately the releases doesn't contain the new version

**Comment by core-code** [comment]
you are right, the suggested sparkle feed is not up-to-date (i thought the "?version=1.5" parameter did help things)

**Review by vitorgalvao — APPROVED** [review]

**Comment by suschizu** [comment]
just added a depends on Mojave - regarding to the travis error :)

**Pull request merged**
