### PR TITLE
Fix hash for vuescan 9.6.16 (again)

### PR DESCRIPTION
**Pull request by durka**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by durka** [comment]
The SHA is the only thing that changed. It looks like this already happened a few days ago #52001. I sent the developer an email asking why they are doing this and will let you know if I get a reply. Here is the [VirusTotal scan](https://www.virustotal.com/#/file/b25a8f9af06ed10365370f04ba12072805f5b48fbb8cf3694707fc8c09df86b9/details) but there is no signature info.

**Comment by vitorgalvao** [comment]
> Here is the [VirusTotal scan](https://www.virustotal.com/#/file/b25a8f9af06ed10365370f04ba12072805f5b48fbb8cf3694707fc8c09df86b9/details) but there is no signature info.

Look again. There is indeed.

**Comment by durka** [comment]
Here is the response I got from the developer.

```
Yes, I do this all the time (often a few times per day)

Regards,
Ed Hamrick

-----Original Message-----
From: VueScan Problem Report <no-reply@hamrick.com>
Sent: Tuesday, September 18, 2018 3:59 PM
To: support@hamrick.com
Subject: VueScan Problem Report from vuescan@alexburka.com

Email: vuescan@alexburka.com
Model: Canon MF3240
OS: Mac-10.13
Problem: I tried to install VueScan through Homebrew and the checksum didn't match,
indicating that the file contents has changed. I noticed that this happened a few 
days ago as well (https://github.com/Homebrew/homebrew-cask/pull/52001). I am just 
wondering if you have been uploading new builds without changing the version number? 
If so, that makes it really difficult for systems like Homebrew which care about 
checking file integrity. Thanks!

```

**Comment by lantrix** [comment]
Hmm as I though, he generates a new build daily or more of the same versions. His workflow must publish that to S3.

**Comment by durka** [comment]
Does brew-cask have any way to deal with that? Or do we just have to ask him to change his ways or remove the formula?

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/52199

**Pull request merged**
