### PR TITLE
Upgrade LoginputMac to v2.1.3

### PR DESCRIPTION
**Pull request by erickguan**
The developer has offered a new set of URLs and pkg for installation.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by fantasticfears** [comment]
Contacted the owner, fixed an upstream problem.

**Comment by reitermarkus** [comment]
The appcast shows a versioned URL: `https://loginput-mac2.content-delivery.top/LogInputMac2.app8771.zip`

**Comment by fantasticfears** [comment]
Author (@R0uter) claims the appcast is for indicating updates, but not where to get the package.

**Comment by vitorgalvao** [comment]
> Author (@R0uter) claims the appcast is for indicating updates, but not where to get the package.

Doesn’t matter if it still works. It’s common practice for casks. It certainly beats having the cask break because the package was updated in place.

**Comment by fantasticfears** [comment]
@R0uter maybe you can find a better way for appcast.

> An appcast can be any URL hosted by the app’s developer that changes every time a new release is out (e.g. a changelog HTML page). (Example: razorsql.rb)

https://github.com/Homebrew/homebrew-cask/blob/645dbb8228ec2f1f217ed1431e188687aac13ca5/Casks/razorsql.rb#L6

This also works and correct. And you don't have to post updates to the new package and the cask will still work.

**Review by vitorgalvao — APPROVED** [review]

**Comment by R0uter** [comment]
> Seeing as @R0uter gave a thumbs up to [this comment](https://github.com/Homebrew/homebrew-cask/pull/57251#issuecomment-453602735), I’ll assume this change is fine.

This app is a inputmethod for macOS, it **can not** be installed in to the `Application` directory, hence it must be a `pkg` installer.  

the `appcast2.xml` is use for sparkle, the in-app update framework, it use `.zip` file to update app itself.

However, I will try to create a new appcast for brew cast later.

**Comment by fantasticfears** [comment]
I think how the cask works is under @R0uter's discretion not by his figurative words.

**Comment by vitorgalvao** [comment]
@fantasticfears 

> I think how the cask works is under @R0uter's discretion not by his figurative words.

How the cask works is under *our* discretion, because we’re the ones that have to maintain it. We do respect the developer’s wishes, but only to the point they don’t make it harder for us.

We are perfectly free to say (and have) “we need the cask to work this way, for it to be maintainable. Either it stays in the manner we need, or it doesn’t stay at all”. And the developer is perfectly free to say “then I don’t want it distributed by HBC”, and we’ll comply.

Make no mistake, maintaining any part of this project is an insane amount of work and no one cask is indispensable. I’m more than happy to get rid of problematic casks. Removing casks is as beneficial to the long term health of the project as including them.

---

@R0uter Understood. Thank you for the explanation, I’ll revert appropriately.

> It seems cast do support zip cast with a pkg installer, but there is no any pkg link in file?

I don’t understand what this means.

**Review by vitorgalvao — APPROVED** [review]

**Comment by fantasticfears** [comment]
The source requires a pkg installation which is not in the zip file. The package is distributed with the URL in the first commit.

I presumed that an in-place update can be done by cask. But I can't be sure.
> Author (@R0uter) claims the appcast is for indicating updates, but not where to get the package.
The author told me the status, and I brought the PR here.

I understand versionized URL is a common practice as I submitted many of them. But it doesn't work for an update for this cask where cask can't find the pkg file.

Then I even suggested him not to use the disguised appcast which is not related with this particular cask. [This comment](https://github.com/Homebrew/homebrew-cask/pull/57251#issuecomment-453602735) is really confusing for me to know how to update the commit.

**Comment by vitorgalvao** [comment]
Thank you for the submission.

**Pull request merged**
