### PR TITLE
Update choose-wisely

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
false positive, the site is not available via HTTPS

**Comment by vitorgalvao** [comment]
> false positive, the site is not available via HTTPS

How do you mean? Seems fine to me.

**Comment by core-code** [comment]
hmmmmm weird:

```
==> Downloading external files for Cask choose-wisely
==> Downloading https://tigion.de/projekte/software/choose-wisely_0-5.zip

curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
Error: Download failed on Cask 'choose-wisely' with message: Download failed: https://tigion.de/projekte/software/choose-wisely_0-5.zip

```

**Comment by core-code** [comment]
Screenshot 2019-05-28 at 15 13 49

**Comment by core-code** [comment]
i'm fine with just closing the PR if its just me

**Comment by core-code** [comment]
ah ok, sorry didn't get the fact that the blog is still available

**Comment by vitorgalvao** [comment]
Seems like the download has the issue and the page works fine.

```
$ curl --head 'https://blog.tigion.de/2010/02/16/software-choose-wisely/'
HTTP/2 200
date: Tue, 28 May 2019 13:19:06 GMT
server: Apache/2.4.39
x-powered-by: PHP/5.6.34
link: <https://blog.tigion.de/wp-json/>; rel="https://api.w.org/", <https://blog.tigion.de/?p=1093>; rel=shortlink
content-type: text/html; charset=UTF-8

$ curl --head 'https://tigion.de/projekte/software/choose-wisely_0-5.zip'
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
