### PR TITLE
Added bitcoin-xt

### PR DESCRIPTION
**Pull request by vitorgalvao**
`curl` is having an awful lot of trouble downloading this, not yet sure why.

### CODE REVIEW

**Comment by adityadalal924** [comment]
curl does't work for me either, but wget does...odd

**Comment by vitorgalvao** [comment]
It’s just a github releases URL, and not a particularly big app. I wonder what’s special about it.

**Comment by jawshooah** [comment]
It resolves to an Amazon S3 host, not sure why there are so many redirects
though.

**Comment by vitorgalvao** [comment]
> It resolves to an Amazon S3 host

All github releases URLs do that, though (as far as I’m aware).

**Comment by vitorgalvao** [comment]
Tried a bunch of other solutions and it doesn’t seem to want to work. Will close this for now, perhaps future versions will work.

If there’s any interest in the future, the interested user should have a solution/reasoning so we can work on making this function.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/20090.

**Pull request closed without merging**
