### PR TITLE
updated displaycal (3.1.4.0)

### PR DESCRIPTION
**Pull request by shonjir**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by shonjir** [comment]
Travis appears to be hanging on 'brew cask audit' step.  It appears this happens when executing manually also, but worked when executed from cask-repair.

**Comment by adidalal** [comment]
I can restart Travis and see if it helps

**Comment by reitermarkus** [comment]
@adidalal, already restarted it two times. Also tried locally, doesn't work either.

**Comment by shonjir** [comment]
I suspect this isn't going to work.  It looks like brew cask audit is hanging at the appcast check.  A spot check of other casks shows that it works for most, but not with sourceforge appcasts that contain uri request parameters (?path=...)

A quick search gives me the following casks that seem to exhibit this behavior:

animated-gif-quicklook.rb
displaycal.rb
freesmug-chromium.rb
grandperspective.rb
grisbi.rb
klatexformula.rb
qbittorrent.rb
seashore.rb
squirrelsql.rb
supertuxkart.rb

It's odd because cask audit just sets up a curl request that works fine when executed manually.

**Comment by shonjir** [comment]
Fixed by #23050

**Comment by reitermarkus** [comment]
Thank you for the contribution. It was merged directly as 2a342b789d88bcf917760474f8c7e597e486bc0d to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
