### PR TITLE
Add Delta.Chat.app v1.2.0

### PR DESCRIPTION
**Pull request by witsch**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars)).

**Comment by witsch** [comment]
Hi Vítor,

in the meantime Delta Chat has received funding from the Open Technology Fund.  It's mentioned in their monthly report for September, https://www.opentech.fund/news/september-2018-monthly-report/ (third paragraph from the top under "Notable accomplishments").  Also, the repository has 37 stars by now.  Not quite 50 yet, but please take into account that this is just the repository for the desktop version, the core library has 181 (https://github.com/deltachat/deltachat-core) and the Android app 263 (https://github.com/deltachat/deltachat-android) at the moment.

Would you reconsider a new pull request? :)

Best wishes,


Andi

**Comment by vitorgalvao** [comment]
> but please take into account that this is just the repository for the desktop version, the core library

But you’re not submitting the core library. You’re submitting the desktop version, and so far that one hasn’t revealed enough interest. Under 300 stars for the others is no indication this is wanted enough.

> Would you reconsider a new pull request?

Yes, once this fills the prerequisites. If your assessment is correct, that should happen soon.

**Comment by witsch** [comment]
> Yes, once this fills the prerequisites. If your assessment is correct, that should happen soon.

Ok, fair enough… 🙂

**Pull request closed without merging**
