### PR TITLE
Update silnite from 5 to 6

### PR DESCRIPTION
**Pull request by bmironer**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bmironer** [comment]
First time using bump-cask-pr (for a very trivial version update). Not sure what went wrong...

**Comment by bevanjkay** [comment]
@bmironer Thanks for your contribution to `homebrew-cask`. Your PR looks fine, we are currently experiencing some intermittent issues with degraded performance on this repo, when it is resolved we will be able to restart the checks and all should be okay.

**Comment by bevanjkay** [comment]
Thank you @bmironer

**Pull request merged**
