### PR TITLE
Update busycontacts from 1.4.11,141102 to 1.4.11,2020-11-15-03-25

### PR DESCRIPTION
**Pull request by bootlegcheeseburger**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by atlgc** [comment]
I believe the version numbering scheme here is inaccurate. To match BusyCal's scheme, we should use
1.4.11-2020-11-15-03-25
I bumped the existing version up one to try and force this bump to accept a version number increase.

**Comment by core-code** [comment]
modelling after @miccals recent changes to busycal

**Comment by core-code** [comment]
@reitermarkus what is the value of following the redirect for the URL stanza here?

**Review by core-code — APPROVED** [review]

**Comment by reitermarkus** [comment]
> what is the value of following the redirect for the URL stanza here?

That way the checksum will not break if the redirect changes to a new version.

**Comment by core-code** [comment]
> That way the checksum will not break if the redirect changes to a new version.

ok sounds good i'll make the same change to busycal

**Pull request merged**
