### PR TITLE
Update media-center to 28.00.79

### PR DESCRIPTION
**Pull request by nrlquaker**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by nrlquaker** [comment]
closes #114454

**Comment by nrlquaker** [comment]
`livecheck` fails. Seems like its because of the version I used is not listed on the download page. Only on forum. That's why its failing. Any ideas how to fix it?

**Comment by bevanjkay** [comment]
@nrlquaker According to the downloads page, version `28.00.79` is the latest universal binary. We can bump to this for now?

**Comment by nrlquaker** [comment]
@bevanjkay I think, yes.
I remembered that forum releases are not super stable. They do some user testing and post stable one to the download page.

**Pull request merged**
