### PR TITLE
Add zap stanza to boxy-suite

### PR DESCRIPTION
**Pull request by unitof**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @unitof.

**Review by miccal — APPROVED** [review]

**Comment by unitof** [comment]
@miccal Do you know why the `brew uninstall --cask --zap boxy-suite` Actions test was skipped?

https://github.com/Homebrew/homebrew-cask/pull/98082/checks?check_run_id=1692819212

image

**Comment by miccal** [comment]
That part of the CI tests is only run if the Cask is already installed on the CI machines (very rare, I think) -- in general, only the `uninstall` is run:

Screen Shot 2021-01-13 at 14 29 02

**Comment by unitof** [comment]
Ah! Got it.

I thought there was a CI task which installed any new or modified cask on a fresh machine, took a disk snapshot, then ran `brew uninstall --cask --zap [cask-name]` and took another snapshot, then compared.

The goal is writing the `zap` stanza so that the snapshots are identical.

But maybe I dreamed that!

If I did: is that possible?

**Comment by miccal** [comment]
Not really -- the `zap` stanza needs the Cask to be run to be effectively tested, which the CI machines cannot do.

**Pull request merged**
