### PR TITLE
Re-added archi 4.6.0 with corrected url

### PR DESCRIPTION
**Pull request by jeichhorn**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Are you sure the previous issues will no longer happen?

On another note, use `x` in checklists (no spaces inside the brackets) and [Github will make them clickable](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments).

**Comment by jeichhorn** [comment]
> Are you sure the previous issues will no longer happen?

I cannot guarantee, that the previous issues with changed download urls won't happen again. I just hope that the url will be stable per release.

**Comment by vitorgalvao** [comment]
Let’s try again, but we’ll remove at the sign of (the same) trouble.

cc @core-code.

**Comment by core-code** [comment]
thanks lets see what happens

**Comment by jeichhorn** [comment]
The download URL changed again from https://www.archimatetool.com/downloads/74a43a6b4f295fe0d/Archi-Mac-4.6.0.zip to https://www.archimatetool.com/downloads/75a43a6b4f295fe0f/Archi-Mac-4.6.0.zip .

Seems there is some algorithm which changes the url periodically.
So it would be better to remove the cask.

**Comment by vitorgalvao** [comment]
Deleted.

**Pull request merged**
