### PR TITLE
Rename screen to pop

### PR DESCRIPTION
**Pull request by wendorf**
Screen was just renamed to Pop. https://pop.com/screenhero has the
story.

~I couldn't determine an appropriate livecheck stanza, and the appcast
stanza was rejected by brew audit, so I have removed it.~ I was able to
determine an appropriate stanza, so have included it.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by reitermarkus** [comment]
> I couldn't determine an appropriate livecheck stanza

What was the problem? Please try adding it even if it doesn't work, we'll go from there.

**Comment by averred** [comment]
https://pop.com/download/mac

The website uses [webpack](https://github.com/webpack/webpack)/[Ionic](https://ionicframework.com) to load content. As far as I understand, we would need to assemble the DOM and then scrape the resulting HTML in order to get version info/download URL.

Not sure if this is in scope for livecheck?

**Comment by wendorf** [comment]
> > I couldn't determine an appropriate livecheck stanza
> 
> What was the problem? Please try adding it even if it doesn't work, we'll go from there.

I didn't realize that the page_match strategy with regex would find all matches and pick the highest match, so I thought there wasn't an appropriate strategy. After looking at some other examples, I realized that the strategy would work for pop, so I've pushed a new version of this PR with a livecheck stanza and bumped to the latest release of Pop.

**Review by reitermarkus — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @wendorf.

**Pull request merged**
