### PR TITLE
upscayl 2.9.8 (new cask)

### PR DESCRIPTION
**Pull request by aaronliu0130**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
  * Thought it would be included in --new, but the CI has reported something.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
  * Was refused due to missing a signature, which the app now has.
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by aaronliu0130** [comment]
>  Upstream defined :catalina as the minimum OS version and the cask defined :monterey

But the minimum version is Monterey, see https://github.com/upscayl/upscayl/wiki/Compatibility-List. How can I fix this? Where does it pull the upstream definition from?

**Comment by krehel** [comment]
The information is pulled from the application `Info.plist` where it has been specified with 10.15 (Catalina) as the LSMinimumSystemVersion.

```
    <key>LSMinimumSystemVersion</key>
    <string>10.15</string>
```

Style errors can be fixed automatically with `brew style --fix <cask>`

**Comment by aaronliu0130** [comment]
Thanks. I know how to fix style errors.

Do we have to have upstream change the plist, or can we override that?

**Comment by bevanjkay** [comment]
It should be corrected upstream, as their current allows the app to be run on Catalina, even if it doesn't work as intended.

**Comment by aaronliu0130** [comment]
Welp, we'd have to wait for the next release.

**Pull request closed without merging**
