### PR TITLE
Update traktable to 0.6-alpha1,a

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by giannitm** [comment]
Is there a better way of implementing this? The way I've done it looks a bit messy in my opinion.

**Comment by colindunn** [comment]
Only other way I can think of is to truncate the version on the first entry which is just as ugly. Or if this is a rare one, then don't bother at all and just add the `a` into the download url to be removed later because you'll be in the same position later when it gets removed and you have to remove the comma because there isn't anything after the 1.

Having said that, if this is an alpha, should it even be updated to that version?

**Comment by vitorgalvao** [comment]
> Having said that, if this is an alpha, should it even be updated to that version?

Latest stable is over three years old, and this alpha is over two years old and [reportedly does not have many changes](https://github.com/yo-han/Traktable/releases/tag/0.6-alpha1). I guess this falls into the [unstable being the standard rule](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

I agree the current `version`/`url` is a bit messy, but I also doubt this app will get any updates soon (or at all). We can deal with it when it happens.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as efb1a2c33a450909ec78d39444906cea09197c13. Your contribution is still credited to you.

**Pull request closed without merging**
