### PR TITLE
Delete wire.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
```
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
```

Meaning we’ll have to [remove the cask](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/pkg.md#pkg-allow_untrusted). Giving it a while in case this is fixed.

```
wire (added 784 days ago)
30 days: 40 (#1124)
90 days: 135 (#1041)
365 days: 431 (#1165)
```

### CODE REVIEW

**Review by victorpopkov — APPROVED** [review]

**Comment by vitorgalvao** [comment]
Pinging @core-code to inform of the removal.

**Comment by core-code** [comment]
thanks for the ping. did anyone inform upstream?

https://github.com/wireapp/wire-desktop/issues

**Comment by vitorgalvao** [comment]
> thanks for the ping. did anyone inform upstream?

Not that I know of, only a [small note on Twitter](https://twitter.com/homebrewcask/status/1181527977890328576).

**Comment by core-code** [comment]
i've opened a rudimentary bug report over at their github project

**Comment by ffflorian** [comment]
We just released a new version with an updated certificate: [v3.12.3490](https://github.com/wireapp/wire-desktop/releases/tag/macos/3.12.3490).

**Comment by core-code** [comment]
thanks for the heads-up @ffflorian i've sent a PR to re-add and update 'wire'

**Pull request merged**
