### PR TITLE
dehelper 4.6.0

### PR DESCRIPTION
**Pull request by bevanjkay**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Review by razvanazamfirei — APPROVED** [review]

**Comment by Oscaner** [comment]
Hi bevanjkay,

I also encountered this issue, the `noCache=true` not working for me. Do you have any solution?

**Comment by bevanjkay** [comment]
@Oscaner 
That was just an attempt to see if providing a query string cleared the cache.
Could you reach out to the vendor to see if they have any ideas why the appcast is returning a cached version on some requests?

**Comment by Oscaner** [comment]
@bevanjkay 
Okay, understand. Let me contact the vendor.

**Comment by Oscaner** [comment]
Hi @bevanjkay,

Replay from vendor:

```
Hello,
Thanks for your feedback. This is because the addresses were updated recently.
https://static.eudic.net/pkg/dehelper_mac.xml
https://static.eudic.net/pkg/eshelper_mac.xml
https://static.eudic.net/pkg/frhelper_mac.xml
https://static.eudic.net/pkg/eudic_mac.xml
```

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
