### PR TITLE
Update linein to 2.3.0

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by giannitm** [comment]
Not sure if this should be moved to caskroom/homebrew-versions.

**Comment by reitermarkus** [comment]
This implies that it is discontinued.

```ruby
  caveats do
    discontinued
  end

```

**Comment by reitermarkus** [comment]
I think there was another app by RogueAmoeba that you updated with the legacy link. Could you add the caveat there as well? Thanks!

**Comment by reitermarkus** [comment]
I think there was another app by RogueAmoeba that you updated with the legacy link. Could you add the caveat there as well? Thanks!

**Pull request merged**
