### PR TITLE
removed droplr.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
Seems to only be available on the MAS.

### CODE REVIEW

**Comment by matthewbarram** [comment]
I had a look and it looks like you are right. No download links anymore. :-(

**Comment by vitorgalvao** [comment]
Merged as eb6ac1f758f636c9c2dcb27cd33fc2a33e77780c.

**Comment by agh** [comment]
I e-mailed Droplr Support and received the following response today:

```
Hi Alex,
I apologize for the delay in getting back to you. Here is the link to the direct download for the Mac App https://d.pr/download/mac_direct

Cheers,

Leah
```

Seems like they are supporting independent installation again after feedback. /cc @matthewbarram @vitorgalvao

**Comment by matthewbarram** [comment]
I checked and the final URL for that is `http://files.droplr.com.s3.amazonaws.com/apps/mac/Droplr+77.zip`

**Comment by vitorgalvao** [comment]
They don’t publicise those links on the website, and they are hosted on a different domain than the homepage, which means we can’t use them anyway. Even if we could, not being upfront and public about them just tells me they’ll forget and stop updating anyway when they forget/stop caring.

Unless any of that changes, we won’t be adding them back.

**Comment by agh** [comment]
Well the d.pr domain is their standard short-linking domain, and instead of [A-Z,0-9] (the standard format) they've created something custom in terms of /download/mac_direct. 

They're using their own service in order to provide a friendly link to an AWS S3 bucket which contains the  software installer. I'd hardly call that unexpected, or particularly problematic?

Not having it on their website isn't ideal, I will concede.

**Comment by vitorgalvao** [comment]
> Well the d.pr domain is their standard short-linking domain

Yes, I know that is the case, but that doesn’t mean every user will, and [we have clear rules for this](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#when-url-and-homepage-hostnames-differ-add-a-comment). Allowing users to quickly and efficiently audit casks is a must for security issues is a must, and I no special technical knowledge should be required. You should be able to confirm a cask is good just by reading it, and if anything jumps at you, should be able to confirm it with a visit to its homepage.

**Pull request closed without merging**
