### PR TITLE
Add Emacs man pages

### PR DESCRIPTION
**Pull request by xxyzz**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Review by miccal — APPROVED** [review]

**Comment by Vynce** [comment]
Hi, this appears to have broken cask installation (?):
```
% brew install wine-stable
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 562580 (delta 18), reused 35 (delta 13), pack-reused 562538
Receiving objects: 100% (562580/562580), 248.78 MiB | 22.39 MiB/s, done.
Resolving deltas: 100% (397360/397360), done.
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/emacs.rb
Cask ''/Applications/Emacs.app/Contents/Resources/man/man1/ebrowse.1.gz' is not a valid man page name' definition is invalid.
Error: Cannot tap homebrew/cask: invalid syntax in tap!
```

**Comment by xxyzz** [comment]
I send this pr after https://github.com/Homebrew/brew/pull/11041 get merged, maybe this commit should applied again after next brew release?

**Comment by miccal** [comment]
> I send this pr after [Homebrew/brew#11041](https://github.com/Homebrew/brew/pull/11041) get merged, maybe this commit should applied again after next brew release?

Yes please @xxyzz, thanks.

**Comment by Kyonru** [comment]
I'm still getting a similar issue to @Vynce, not sure if I'm doing something wrong here.

```bash
#!/bin/bash --login -eo pipefail
HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew tap homebrew/cask >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils >/dev/null
HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask android-sdk >/dev/null
touch .watchmanconfig
node -v
```

Output:

```bash
==> Tapping wix/brew
Cloning into '/usr/local/Homebrew/Library/Taps/wix/homebrew-brew'...
remote: Enumerating objects: 78, done.        
remote: Counting objects: 100% (78/78), done.        
remote: Compressing objects: 100% (44/44), done.        
remote: Total 622 (delta 41), reused 58 (delta 22), pack-reused 544        
Receiving objects: 100% (622/622), 1.58 MiB | 9.14 MiB/s, done.
Resolving deltas: 100% (328/328), done.
Tapped 1 cask and 1 formula (31 files, 1.6MB).
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 373, done.        
remote: Counting objects: 100% (373/373), done.        
remote: Compressing objects: 100% (222/222), done.        
remote: Total 563812 (delta 194), reused 290 (delta 151), pack-reused 563439        
Receiving objects: 100% (563812/563812), 248.93 MiB | 15.03 MiB/s, done.
Resolving deltas: 100% (398150/398150), done.
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/emacs.rb
Cask ''/Applications/Emacs.app/Contents/Resources/man/man1/ebrowse.1.gz' is not a valid man page name' definition is invalid.
Error: Cannot tap homebrew/cask: invalid syntax in tap!
```

```
Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by carlocab** [comment]
You're likely running an outdated version of `brew`. Can you still reproduce this on `brew 3.1.1`?

**Comment by Kyonru** [comment]
@carlocab You're right. The brew version in the CircleCI macOS executor was outdated.  It works with `brew 3.1.1` thanks.

**Pull request merged**
