### PR TITLE
Update 9 `jetbrains` casks - remove EAP `conflicts_with`

### PR DESCRIPTION
**Pull request by commitay**
After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Removed `conflicts_with` EAP `versions`

Add `auto_updates` to `mps`

### CODE REVIEW

**Comment by leipert** [comment]
LGTM 👍

**Comment by leipert** [comment]
Looking over the changes, would you mind adding `auto_updates true` to mps? I know that is not the purpose of this merge request, but maybe we can smuggle that in. I just checked and MPS does support auto-updates.

**Comment by commitay** [comment]
> adding auto_updates true to mps

Done. 👍

**Comment by miccal** [comment]
Thank you @commitay and @leipert.

**Pull request merged**
