### PR TITLE
Add parts-library caveats to Fritzing 0.9.3b

### PR DESCRIPTION
**Pull request by ELLIOTTCABLE**
(No checkboxes; didn't change anything but a caveats clause.)

### CODE REVIEW

**Comment by commitay** [comment]
We don't have version specific caveats. Asking upstream to make a release that we can upgrade the Cask to would solve this problem.

**Comment by ELLIOTTCABLE** [comment]
@commitay The problem is that there are going to be no moer upstream releases (the maintainers have been working on a full rewrite for a few years, and have ignored requests for a release including bugfixes like these. `)=`

Given,

1. This isn't going to be fixed upstream,
2. it's a popular, necessary project for particular tasks, despite the unmaintained status of the (supposedly-legacy?) Qt codebase,
3. the problem in question *is* technically install-related (it's the first-time-launch self-setup behaviour that's broken),
4. and finally, that a Cask user is *already* staring at their Terminal, right after installing the app, and is presumably about to launch the app for the first time …

I dunno. It's your call! But it really seems like a worthwhile tip, to save the user of all the trouble of launching it the normal way, Googling the resulting errors, and finding they have to entirely uninstall and re-install the app to proceed …

I know it's technically against policy, but I *really* urge you to consider this a special case. `(=`

**Comment by vitorgalvao** [comment]
There’s no point in making the caveat version specific — users of a previous version wouldn’t see it anyway.

This message seems acceptable to me; I can see the point to saying it’s installation-specific.

**Review by vitorgalvao — APPROVED** [review]

**Comment by vitorgalvao** [comment]
@ELLIOTTCABLE And that Travis error is exactly why you *always* need to run the commands in the boxes, even if you think your changes don’t warrant it. They do.

**Comment by ELLIOTTCABLE** [comment]
@vitorgalvao I ran them, but they both passed on my local machine! Yikes.

Cool! Let me know if there's anything else I can do. 😊

**Pull request merged**
