### PR TITLE
Add AVTouchBar v3.0.7

### PR DESCRIPTION
**Pull request by viking1304**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @viking1304.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by miccal** [comment]
Ping @bevanjkay for a quick look at my `livecheck` block here.

**Comment by bevanjkay** [comment]
@miccal It looks good to me. It might be better to use a `.` instead of a `:` in the versioning for the `after_comma` part.

At least that is how we are doing it for `hook` which also has a WordPress date folders - https://github.com/Homebrew/homebrew-cask/blob/11319d444397ccd155ba78e7fbc84e2c23c84d8d/Casks/hook.rb

**Comment by miccal** [comment]
Thanks @bevanjkay, much nicer :)

**Comment by viking1304** [comment]
> Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

Zap added. https://github.com/Homebrew/homebrew-cask/commit/2021c124c74e529ca179f66a0990d0be6c373657

**Comment by miccal** [comment]
Thank you @viking1304.

**Comment by viking1304** [comment]
@miccal it's 3am here and i am very tiered, so I missed the trailing slash. Sorry. But you saw it and remove it. Thanks.

**Comment by miccal** [comment]
No problem @viking1304, it is only 10 am for me :)

**Pull request merged**
