### PR TITLE
Fix Casks using `gpg`.

### PR DESCRIPTION
**Pull request by reitermarkus**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
Mixing version bumps in with other changes isn't great as the CI install/uninstall step isn't run.

**Comment by reitermarkus** [comment]
> the CI install/uninstall step isn't run.

Why not? 

> `>>> More than 3 Casks modified, skipping install`

We should just let CI fail then, instead of skipping it.

**Comment by commitay** [comment]
CI builds that try to install all the Casks modified in a PR will run until they timeout which impacts the whole organisation queue.

**Comment by reitermarkus** [comment]
Then maybe let's fail if there is more than one Cask updated. 3 is an arbitrary number, updating `mactex` and `mactex-no-gui` at the same time would probably time out too, despite being only two.

**Comment by commitay** [comment]
> Then maybe let's fail if there is more than one Cask updated.

Why? Mass edits shouldn't fail, we just don't want to run the install.

**Comment by reitermarkus** [comment]
But if mass edits don't fail, how am I supposed to know I should split them up in *this* case?

Basically, if you argue that “mixing version bumps in with other changes isn't great”, I argue that CI should fail and suggest to split them up.

**Comment by commitay** [comment]
Are you proposing:

1) CI fails if more than one Cask is modified?

2) CI fails if more than one Cask is modified _and_ one of those Casks is version bumped?

**Comment by reitermarkus** [comment]
For now, I would suggest 1, since for 2, we would basically have to rewrite the Travis script in Ruby in order to properly check if the version (or rather url, since that is what the installation really depends on) has changed.

**Comment by reitermarkus** [comment]
> I'm not sure I understand how 1 would would help in _this_ case

It would fail, hence I would have to split it up, hence the installation would be tested.

**Pull request merged**
