### PR TITLE
add qsyncthingtray 0.2.7

### PR DESCRIPTION
**Pull request by adidalal**
Ref: https://github.com/caskroom/homebrew-cask/pull/15921 and https://github.com/caskroom/homebrew-cask/issues/15921

### CODE REVIEW

**Comment by adityadalal924** [comment]
`uninstall :quit => 'QSyncthingTray'` does not quit the app

**Comment by epsimatic** [comment]
> I saw your earlier PR which was then closed for some reason

I totally missed the DSL removal, and all my pending casks got badly broken.

Thanks for fixing & accepting them, you're super friendly and responsive!

**Comment by vitorgalvao** [comment]
> `uninstall :quit => 'QSyncthingTray'` does not quit the app

`uninstall :quit` only works on bundle IDs. Looks like that app may not have one.

**Comment by adityadalal924** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 4fc4df40da4e7cdf6303edf5a8df01111e5ecbc9. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
