### PR TITLE
Add IINA+ 0.4.12

### PR DESCRIPTION
**Pull request by uetcis**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
I’ll merge the cask when CI passes. But what does the app do?

**Comment by ran-dall** [comment]
@vitorgalvao It's a plugin for IINA of sorts (if I'm not mistaken) specifically to display a wall of text. I've never heard of it myself (as an IINA user) and was curious when it came in...

68747470733a2f2f692e6c6f6c692e6e65742f323031382f31302f33302f356264383361373935323433372e676966

**Comment by vitorgalvao** [comment]
> specifically to display a wall of text

But why? And where does the text come from? I saw the screenshot but don’t understand what’s going on.

**Comment by ran-dall** [comment]
> But why? And where does the text come from?

🤷‍♂️ I didn't get that either.

**Comment by xjbeta** [comment]
This software provides additional support for watching live video in mainland China using IINA.
Using IINA's fork at the same time can show danmaku in the video.

[What is danmaku](https://en.wikipedia.org/wiki/Bilibili#Features)

**Comment by vitorgalvao** [comment]
Thank you for the clarification, @xjbeta!

**Pull request merged**
