### PR TITLE
Update shotcut from 20.07.11 to 20.09.01

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by core-code** [comment]
this is a pre-release and marked as such here https://github.com/mltframework/shotcut/releases/

@SMillerDev any idea how the new pre-release check didn't catch this one?

i'm sending a PR to revert

**Comment by SMillerDev** [comment]
What does brew audit say for you?

**Comment by core-code** [comment]
```
$ brew cask audit shotcut
audit for shotcut: passed
```

shouldn't be possible, no?

**Comment by SMillerDev** [comment]
`v20.09.01` is a pre-release. `20.09.01` doesn't exist as a tag. That's why it fails to detect it. I'm not sure how we would be able to prevent these situations.

PS: without `--online` or `--strict` the check won't run at all

**Comment by core-code** [comment]
thanks for your analysis here! i am assuming the tag is always equal to the URL component after /download/? if not, please disregard the parts below.

i've looked at all casks and it seems 

• we have 380 casks where we use the full tag as #{version}

• but we have 609 casks where we omit the leading 'v' 

therefore it would be best to always check with a 'v' prepended to version additionally. 
else the check only works in 1/3 of cases. i don't think prepending a 'v' could lead to false-positives.

this would be a quick solution that works in most cases.

what about cases where the tag is something else entirely? it seems we have around 50 casks where this simple fix won't work. if we want a perfect solution here too i guess it could be done:

• replace #{version} the URL stanza. and then extract the part that is after '/releases/download/' and before the next slash. this should always be the real tag

**Comment by reitermarkus** [comment]
Yeah, I think it currently checks the cask version instead of the version in the URL.

**Pull request merged**
