### PR TITLE
Add zap stanza to koko

### PR DESCRIPTION
**Pull request by nrlquaker**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by nrlquaker** [comment]
Why to remove dir from `/tmp/` ?

**Comment by nrlquaker** [comment]
@commitay can you explani about tmp folder please?

**Comment by reitermarkus** [comment]
`/tmp` is emptied on reboot, so it doesn't need to be removed.

**Comment by nrlquaker** [comment]
Thanks,

**Pull request merged**
