### PR TITLE
Delete awareness.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
Seems to no longer exist.

### CODE REVIEW

**Comment by adityadalal924** [comment]
Found a git repo at https://github.com/dvdsgl/awareness but seems like source only, probably safe to tombstone

**Comment by vitorgalvao** [comment]
Yep, seems like they must’ve open-sourced it before giving up on the domain, or something.

**Comment by adityadalal924** [comment]
Thank you for the contribution. It was merged directly as 3fbfd117fa7505a43fa6bea1ad1afe7866bb8b09 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by winkelsdorf** [comment]
Huh? Just saw the exclamation mark, I am actually using this tool from time to time to keep in mind to get away from keyboard ;)

The website is up and running: http://iamfutureproof.com/tools/awareness/

Please have a 2nd look at this.

**Comment by vitorgalvao** [comment]
@winkelsdorf Good to know. This appeared to be completely dead, before (I also used it).

**Comment by winkelsdorf** [comment]
@vitorgalvao You're welcome! Haha, I noticed before that we have a lot in common. btw love your Alfred workflows, too. Small world ^^

**Comment by vitorgalvao** [comment]
Thank you. Always good to hear (well, read) from people who use them.

**Pull request closed without merging**
