### PR TITLE
Feature/java8u40 b27

### PR DESCRIPTION
**Pull request by franklouwers**
Java8u40 build 25 (which is what master currently downloads) includes a nasty bug involving text input on OSX. Oracle fixed this in 8u40_b27. See https://bugs.openjdk.java.net/browse/JDK-8074668 for the official bug.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
There’s a lot of garbage mixed; please [squash your commits](http://davidwalsh.name/squash-commits-git).

**Comment by franklouwers** [comment]
wow that shouldn’t have happened. Crazy git. Sorry! 
> On 13 Apr 2015, at 17:49, Vítor Galvão <notifications@github.com> wrote:
> 
> There’s a lot of garbage mixed; please squash your commits <http://davidwalsh.name/squash-commits-git>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/caskroom/homebrew-cask/pull/10583#issuecomment-92408587>.
> 


Frank Louwers
Openminds bvba

Tel: +32 9 225 82 91

PS: Linux sysadmin-guru (in wording) gezocht: http://www.openminds.be/nl/vacatures/vacature-linux-system-engineer

**Comment by vitorgalvao** [comment]
No problem. Please @mention me after squashing, so I can merge this.

**Comment by franklouwers** [comment]
created pull request https://github.com/caskroom/homebrew-cask/pull/10584

**Pull request closed without merging**
