### PR TITLE
Add Red Eye.app v1.0

### PR DESCRIPTION
**Pull request by brtdv**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].
- [X] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

### CODE REVIEW

**Comment by vitorgalvao** [comment]
I don’t understand the need for so many apps that do the same thing with the same interface. Does this one do something different?

**Comment by brtdv** [comment]
> I don’t understand the need for so many apps that do the same thing with the same interface. Does this one do something different?

I'm not sure if you're [joking or not](https://mjtsai.com/blog/2019/09/03/red-eye-rejected-from-the-mac-app-store/) :-)

The same reasoning was used to not allow the app to be published on the app store. 
I'm just trying it to add it to `brew cask` so I can install it through the cli.

**Comment by vitorgalvao** [comment]
> I'm not sure if you're [joking or not](https://mjtsai.com/blog/2019/09/03/red-eye-rejected-from-the-mac-app-store/) :-)

I wasn’t joking, but I was also not aware the app had been rejected from the MAS (this is the first I’m hearing of it).

> The same reasoning was used to not allow the app to be published on the app store.

The difference is we’re not going to outright reject it, but that doesn’t mean I don’t have an opinion on the value to maintenance burden ration of this cask. It (apparently) does nothing different to tons of other apps, has an unversioned URL and no (official) appcast (that I could find).

My question was genuine.

**Comment by suschizu** [comment]
@brtdv - there seems to be a problem with the download:
`curl: (22) The requested URL returned error: 416
Error: Download failed on Cask 'red-eye' with message: Download failed: https://www.hexedbits.com/downloads/redeye.zip`
not sure if this is a general download-fail or just my connection

**Comment by vitorgalvao** [comment]
@suschizu Download works for me.

**Comment by suschizu** [comment]
ok great thanks :) 
and does the download works here for you too coincidentally 😬
https://github.com/Homebrew/homebrew-cask/pull/68105#issuecomment-527983779

**Comment by vitorgalvao** [comment]
> and does the download works here for you too coincidentally

Yes.

**Comment by suschizu** [comment]
great artwork btw :)

**Comment by vitorgalvao** [comment]
> great artwork btw :)

Thank you. Decided to take a break from the other image. It’s wall vinyl, about 2 meters in diameter and 3 meters above ground.

That was almost a decade ago. I’d do it again in a heartbeat.

**Comment by suschizu** [comment]
Reminds me of Fred Sandback or Lawrence Weiner - reduced forms that offer a lot of interpretation.
I like conceptual art

**Pull request merged**
