### PR TITLE
Update bettertouchtool to 2.605

### PR DESCRIPTION
**Pull request by shoichiaizawa**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/pull/51235

**Comment by shoichiaizawa** [comment]
?

**Comment by vitorgalvao** [comment]
> ?

He means this is a duplicate.

**Comment by shoichiaizawa** [comment]
> He means this is a duplicate.
Is it a duplicate? The version number is different 🤔

**Comment by vitorgalvao** [comment]
> Is it a duplicate? The version number is different

You’re right. Though your version seems like it’s not stable one. The appcast lists `.4` as the latest.

**Comment by brianmorton** [comment]
Apologies to both of you - I could have been more helpful than just posting that link to the other PR.

**Pull request closed without merging**
