### PR TITLE
Add DelayedLauncher.app v2.2

### PR DESCRIPTION
**Pull request by jaredsampson**

### CODE REVIEW

**Comment by jaredsampson** [comment]
Is it preferred that I squash these into a single commit?

**Comment by vitorgalvao** [comment]
> Is it preferred that I squash these into a single commit?

Yes.

However, seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/master/Casks/acorn.rb).

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 28ceba6b6337e1e101ab85065d737b43e861c7c4. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by jaredsampson** [comment]
Thank you for the corrections, I'll make sure to use that approach for version-less URLs in the future.

**Pull request closed without merging**
