### PR TITLE
minecraft 1.8.2

### PR DESCRIPTION
**Pull request by ykursadkaya**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by ykursadkaya** [comment]
curl and downloading directly on my computer gives differrent results
curl -> version 1.8.2
download from browser -> version 1.1.26

**Comment by ykursadkaya** [comment]
Seems fixed retrying

**Comment by ykursadkaya** [comment]
Nope, I am getting same versions (1.8.2) from browser and curl, but CI machine still getting old versions

**Comment by ykursadkaya** [comment]
Finally it's giving correct version info, IDK if this is about a rolling update or a known issue. I didn't encounter anything like this for this cask before

**Comment by bevanjkay** [comment]
The tricky thing here is that because the download is versioned, if the rollout is staged, there's no guarantee that anyone updating the cask receives the updated version.
In saying that, I'm seeing `1.8.2` now locally (I wasn't last week), so I think we're ok to merge.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
