### PR TITLE
Update TorBrowser to 5.0.7

### PR DESCRIPTION
**Pull request by cedwardsmedia**
Updated TorBrowser from 5.0.6 to 5.0.7.

### CODE REVIEW

**Comment by victorpopkov** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 5f6959a34aeac2e3570ddd138734906f1427008a. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by cedwardsmedia** [comment]
Thanks. I don't see any changes. Can you tell me what corrections were needed? That way I can be aware of them the next time I contribute.

Thanks again.

**Comment by vitorgalvao** [comment]
@cedwardsmedia Your extraneous lines at the end were removed.

**Comment by cedwardsmedia** [comment]
Gotcha. Thanks for pointing it out.

**Pull request closed without merging**
