### PR TITLE
Update Eclipse Installer to Mars.1

### PR DESCRIPTION
**Pull request by flaviocamilo**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 27e5880e1ac2e53f96cae59ba74950345a023d2d to keep commit history cleaner. Your contribution is still credited to you.

**Comment by flaviocamilo** [comment]
Hi @vitorgalvao, have you really merged this? ;)

**Comment by vitorgalvao** [comment]
Looks like something went wrong, thanks for the notice. Will fix shortly.

**Comment by flaviocamilo** [comment]
Thanks for merging!

To keep history: the new commit id is 8fc41f265c9983325cda7cc1d5db65dec61d141d.

**Pull request closed without merging**
