### PR TITLE
Update reaper from 6.28.0,6.28 to 6.29.0,6.29

### PR DESCRIPTION
**Pull request by hannesbraun**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
I wonder if we can remove the version part before the comma.
I don't see if ever being used since introduced: https://github.com/Homebrew/homebrew-cask/commit/aaea6c195ea52f99ab5b54c6c78a0aa5b4082b55

---

If we remove it, it should be possible to update old `appcast` stanza into a `livecheck`.

**Comment by hannesbraun** [comment]
The version of the app bundle is `6.29.0`. Everywhere else (website, about dialog, ...), only the version part after the comma is used. I think that was the reason for introducing the part before the comma. (See also #79581)

**Comment by cho-m** [comment]
I guess if that is what is still preferred, we can keep it.
I will let the long-term Cask maintainers chime in.

---

Personally, I think a `livecheck`-able version format is better for continued maintenance.
The current format won't work as it requires running two different strategies:
- use `:page_match` to grab URL format
- use `:extract_plist` to grab bundle version.

**Comment by vitorgalvao** [comment]
Does the version always end in `.0`? If so, we can have both worlds.

**Comment by cho-m** [comment]
I am more worried about the previous **minor version numbers**, e.g.
- `6.20.0,6.02`
- ...
- `6.90.0,6.09`
- `6.10.0,6.10`
- ...
- `6.19.0,6.19`
- `6.20.0,6.20`

The version numbers before `6.10` were quite odd.
Just looking at the _before-comma version_, there is a duplicate between `6.2` and `6.20`

**Comment by hannesbraun** [comment]
> Does the version always end in `.0`? If so, we can have both worlds.

Since version `6.0`, yes. The last time I've seen an exception to this was with version `5.987`  (the app bundle version was `5.98.700`) in November 2019.

**Comment by hannesbraun** [comment]
So what's going to happen with this? I think we could even cut off the trailing `.0` (assuming the CI and the Homebrew Cask "guidelines" are accepting that). If there isn't a trailing `.0` in a future version, the current state would also break. But I'm fine with other solutions too :)

**Comment by cho-m** [comment]
@Homebrew/cask for opinions between:
1. just the easily livecheck-able version (`6.29`) vs.
2. tracking the "full" version including app bundle version (`6.29.0,6.29`. Note that bundle version has previously used some odd numbers like `bundle version 6.50.0 == website version 6.05`).

---

The former can be livechecked on multiple websites. Some examples:
<details>
<summary>https://www.cockos.com/reaper/latestversion/?p=osx_64</summary>

```rb
  livecheck do
    url "https://www.cockos.com/reaper/latestversion/?p=osx_64"
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end
```
</details>

<details>
<summary>https://www.reaper.fm/</summary>

```rb
  livecheck do
    url :homepage
    regex(/>\s*VERSION\s*(\d+(?:\.\d+)+)/i)
  end
```
</details>

<details>
<summary>https://www.reaper.fm/download.php</summary>

```rb
  livecheck do
    url "https://www.reaper.fm/download.php"
    regex(/>\s*Version\s*(\d+(?:\.\d+)+)/i)
  end
```
</details>

---

Not sure if latter is possible to livecheck as the bundle version only appears to be available in the DMG.
The strategy that supports this (`:extract_plist`) needs an unversioned URL.

Also, the bundle version format has at least changed once:
`6.09 (bundle version 6.90.0) --> 6.10 (bundle version 6.10.0)`.

To properly confirm the version number, maintainers may need to manually check the version from downloaded DMG.

**Comment by vitorgalvao** [comment]
> just the easily livecheck-able version (`6.29`)

You prefer that one, right? Then let’s do that. I don’t think any current maintainer has a strong preference either way, that one is good enough, and it’s easier to maintain.

**Review by cho-m — APPROVED** [review]

**Pull request merged**
