### PR TITLE
Add Port Map.app v2.0.1

### PR DESCRIPTION
**Pull request by mrmachine**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

This cask was previously deleted because it was hosted on googlecode. Now it is hosted on GitHub, so I am re-adding it with the latest version.

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by ran-dall** [comment]
Thank you 🙏, but this will be rejected this on account of [it not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is not notable enough (under 50 stars)).

**Comment by mrmachine** [comment]
@ran-dall Is that decision final?

It's not self-submitted (I have nothing to do with the project or its developers), and it was previously part of homebrew-core (removed because it was originally hosted on googlecode). I searched for another reason why it was removed, but could not find one. Here's the PR where it was removed: https://github.com/Homebrew/homebrew-cask/pull/17271

The GitHub project does not have a lot of stars, but it may not have been on GitHub for that long (moved from googlecode), is stable and so doesn't need much actual development (so little need for developers to interact on GitHub other than downloading a release).

The app itself has been around for a long time and is still maintained (updated for Mojave). Here's the main web site: https://codingmonkeys.de/portmap/

MacUpdate says it has been downloaded over 70k times: https://www.macupdate.com/app/mac/27342/port-map

**Comment by ran-dall** [comment]
@mrmachine **No**, it's really taken on a cask by cask basis. ✊ So it still has to go under consideration. At the end of the day, it's just a matter of making sure that there are enough people that use it in order for us to maintain a cask for it. So maybe it will go up for a vote to see exactly how many people use it.

**Comment by mrmachine** [comment]
@ran-dall thanks for the added context in that link. I don't think this is quite the same scenario as this is not my app, and it has been around for quite a while with a decent number of downloads from other sites, and was previously in homebrew-core. But if you decide to uphold the rejection, I understand.

**Comment by ran-dall** [comment]
@mrmachine I think we’re on the same page. I think this is a different context.👍

**Comment by vitorgalvao** [comment]
Nope, still rejecting this.

The app doesn’t have to be self-submitted — that’s an example. 10 stars really is low. If we had a ton of users asking for the app it would’ve been one thing, but we don’t. The app has existed longer than Homebrew Cask is only no is being submitted. That doesn’t scream “popular”, to me.

Having been in Homebrew doesn’t really move the needle in this case.

Thank you anyway.

**Pull request closed without merging**
