### PR TITLE
xscreensaver: various updates

### LINKED ISSUE #117629: improve `Casks/xscreensaver.rb` to also install its `XScreenSaverUpdater.app`?
### Provide a detailed description of the proposed feature

Improve the `Casks/xscreensaver.rb` script to install XScreenSaver's `XScreenSaverUpdater.app` so it can check for newer versions at jwz.org.

### What is the motivation for the feature?

As it is installed now, the screensavers don't allow the user to select the "Automatically check for updates" option.  Instead, it shows the message "XScreenSaverUpdater.app is not installed!  Unable to check for updates."

### Example use case

Although it's best to use `brew` commands to install a newer version of XScreenSaver, it would be helpful to know that there is a newer version of it ready to be installed.

### PR DESCRIPTION
**Pull request by miccal**
Closes https://github.com/Homebrew/homebrew-cask/issues/117629 and https://github.com/Homebrew/homebrew-cask/issues/117630

### CODE REVIEW

**Comment by miccal** [comment]
```
Some applications are still installed, add them to uninstall delete:
/Applications/Apple2.app
/Applications/Phosphor.app
```
I can find no reference to these in the original `dmg` or `pkg` -- I half-expected to see `XScreenSaverUpdater.app` as per https://github.com/Homebrew/homebrew-cask/issues/117629, but not these.

@lsloan can you shed any light on this?

**Comment by miccal** [comment]
For `Apple2.app` see https://osxdaily.com/2012/04/17/celebrate-the-apple-iis-35th-birthday-with-an-apple-ii-simulator-for-mac-os-x/

**Comment by neutric** [comment]
> I can find no reference to these in the original `dmg` or `pkg`

> phosphor and apple2 can now be run as standalone terminal emulator applications on macOS.

and
>Fixed modifier key handing in Apple2.app and Phosphor.app on macOS. 

says https://www.jwz.org/xscreensaver/changelog.html

**Comment by miccal** [comment]
> > I can find no reference to these in the original `dmg` or `pkg`
> 
> > phosphor and apple2 can now be run as standalone terminal emulator applications on macOS.
> 
> and
> 
> > Fixed modifier key handing in Apple2.app and Phosphor.app on macOS.
> 
> says https://www.jwz.org/xscreensaver/changelog.html

Should have looked there first :)

**Comment by neutric** [comment]
> I half-expected to see `XScreenSaverUpdater.app`

Without checking myself: is this one installed by `Install Everything.pkg`?

**Comment by miccal** [comment]
> > I half-expected to see `XScreenSaverUpdater.app`
> 
> Without checking myself: is this one installed by `Install Everything.pkg`?

I assume so, but I am not sure.

@lsloan can you please confirm?

**Review by carlocab — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
👏

**Comment by carlocab** [comment]
Oops. Missed the thread above. Shame. This would be very nice

**Comment by miccal** [comment]
This seems to be working, so merging.

**Pull request merged**
