### PR TITLE
Delete couleurs.rb

### PR DESCRIPTION
**Pull request by core-code**
they have been offline for 2 months (expired SSL). whats our official threshold how long a project needs to be offline to be removed?

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> whats our official threshold how long a project needs to be offline to be removed?

There isn’t one; let’s go by (lack of) popularity:

```
couleurs (added 1656 days ago)
30 days: n/a
90 days: 3 (#4837)
365 days: 74 (#2393)
```

**Comment by core-code** [comment]
ok thanks. there are about 5 others with expired certificate but i will wait until they are expired for 2 month before sending a delete PR.

**Comment by AESM** [comment]
It appears [couleurs](https://couleursapp.com/) is online again and that the app [is downloadable](https://couleursapp.com/couleurs-1.2.zip).

Should I create a PR for getting this back in, or leave it based on the stats posted by @vitorgalvao?

**Comment by core-code** [comment]
if you want to bring it back, i can click the 'revert' button in this pull request here.

**Pull request merged**
