### PR TITLE
tiptoi-manager 5.2

### PR DESCRIPTION
**Pull request by adithyasunil26**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> Downloading https://cdn.ravensburger.de/db/Installer/tiptoi_Manager_Installer.pkg
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
Error: Download failed on Cask 'tiptoi-manager' with message: Download failed: https://cdn.ravensburger.de/db/Installer/tiptoi_Manager_Installer.pkg
```

**Comment by joh-klein** [comment]
Can you try again? I don't have any problems locally when I do `curl https://cdn.ravensburger.de/db/Installer/tiptoi_Manager_Installer.pkg -O`

**Comment by adithyasunil26** [comment]
@joh-klein I was able to curl it locally as well. `brew audit` was also running for me. I think it could have been a CDN issue. 

@chenrui333 Can we reopen this or should I make a new PR?

**Comment by joh-klein** [comment]
@adithyasunil26 Can you make a new PR and maybe reference this one?

**Comment by adithyasunil26** [comment]
@joh-klein New PR at #172849 but the error given by the CI seems to be persistent.

**Pull request closed without merging**
