### PR TITLE
Update unison from 2.51.2 to 2.51.4_rc2

### PR DESCRIPTION
**Pull request by gmerlino**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
This shouldn't be updated to a pre-release

**Comment by vitorgalvao** [comment]
Reopening because you may wish to update to `2.51.3`.

**Comment by gmerlino** [comment]
I opened it for 2.51.4_rc2 straight, instead of 2.51.3 because the (official) 2.51.3 archive does not include the .app (due to buggy, at the time, CI/CD yaml on GH). What would you suggest to do in a case like this?
________________________________

**Comment by vitorgalvao** [comment]
We wait for the new non-RC stable version to be released or for them to correctly add the previous one.

**Pull request closed without merging**
