### PR TITLE
Added Cask for Now Desktop

### PR DESCRIPTION
**Pull request by leo**
My team at @zeit and I decided to add the application [nevertheless](https://github.com/caskroom/homebrew-cask/pull/27397).

When looking over this PR, please keep in mind that the download isn't versioned and we're also not distributing over tools like Github Releases, so I also left the appcast away.

I carefully read the documentation and made sure to align with it.

---

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Everything from https://github.com/caskroom/homebrew-cask/pull/27397 still applies. Please make this versioned and add the appcast.

**Comment by vitorgalvao** [comment]
Please understand this: HBC is not your (or any single developer’s) personal distribution channel. We exist for the users, and users overwhelmingly (the ones that made their voices heard, at least) prefer versioned downloads for security reasons.

You cannot bend the rules to fit your case.

**I prefer `:latest`** and have made that clear when we were discussing this at the time. But even being the oldest active maintainer in HBC, I surrender to the evidence and **let my preferences aside**. In the end, HBC is for users.

You’re more than free and welcome to maintain your own tap for this software, and direct your users there. Taps are by far my favourite feature of HB, as they make sure you aren’t confined to our rules for specific repos. You can make your own rules, and taps are incredibly easy to setup!

But if you want your apps in the official main repos, I ask that you follow our rules. They’re what keeps our sanity and project consistency amongst the flood of PRs we get everyday.

If you do change your mind, please do let us know. As it is, I see no difference between this and #27397.

**Comment by vitorgalvao** [comment]
And as [I said before](https://github.com/caskroom/homebrew-cask/pull/27397#issuecomment-265215170), if you as the maintainer are unwilling to add `cask-repair -v {new_version} now` to your build steps **which does everything automatically, including submitting the PR**, then I don’t want the submission to come from you as that signifies the cask will be left abandoned.

**Comment by vitorgalvao** [comment]
Lastly, please do not open repeated PRs when one gets rejected. Keep the discussion in the original one so we can solve the problem. Closing does not prevent further posting.

**Comment by leo** [comment]
Okay. I'm submitting a versioned one! 😊 

Just explain [this](https://github.com/caskroom/homebrew-cask/blob/master/Casks/airtable.rb) please. There are hundreds of these in the repo!

**Comment by vitorgalvao** [comment]
> Just explain [this](https://github.com/caskroom/homebrew-cask/blob/master/Casks/airtable.rb) please. There are hundreds of these in the repo.

That one doesn’t have an `auto_updates`. As far as we know, it doesn’t auto update. It also may not have an appcast.

Or it may have both of those **but** we didn’t know it at the time. Maybe https://github.com/caskroom/homebrew-cask/issues/6872 makes it clearer. You see, we do not accept casks that use an `installer` or `pkg` and that do not provide an `uninstall`. We require the latter to be present as well, for the cask to go through.

Now, those casks in that issue did go through at the time, and are indeed present, so what gives? Well, the answer is simple: they were added before the rule that would prevent them from being added was implemented. So that means we need to fix those *and* we don’t let anymore in to not exacerbate the problem.

This is the same thing.

Casks with such errors are usually fixed when they are discovered (just take a look at the recente excellent work by @colindunn to [add missing appcasts](https://github.com/caskroom/homebrew-cask/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20Add%20discovered%20appcasts%20to%2010%20casks)).

Every time a rule is implemented, we can’t automatically fix all the present casks that disobeyed it. But we can be vigilant to the new ones, and fix the old ones as time permits. Not letting more errors creep through makes sure the task of fixing the old ones is a finite one, and that is paramount.

**Pull request closed without merging**
