### PR TITLE
Update beyond-compare from 4.3.5.24893 to 4.3.6.25063

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/89864

**Comment by ran-dall** [comment]
@miccal Please don't forget to add an tag to the PRs you close from the ML; otherwise, it creates a problem on the backend. If anything, just leave them open and I or @core-code will take care of them.

`bad-update`

**Comment by ran-dall** [comment]
`skip-version`

**Comment by miccal** [comment]
What are the tags?

**Comment by ran-dall** [comment]
I’ll send them all of them to you when I get home.

**Comment by ran-dall** [comment]
@miccal Ok, so these are the main ones that we've been using...

- `bad-update` - makes the analysis drop the PR from it's record. Because it was unsucessful, it may re-submit the PR again.
- `build-failed` - marks the PR as correct but the failure was located elsewhere in the PR. These are usally forwared to @suschizu 
- `missedMLupdate` - this should have been a PR the ML created but for whatever reason didn't.
- `skip-version` - this is a new one. This makes it skip the submitted version of a cask.

Lately we've been using `bad-update` for most of the PRs it fail; as I probably won't be updating the ML v1 as I've already started working on a v2 which is Ruby-based. Also, the feedback from the CIs we have is broken on v1.

**Pull request closed without merging**
