### PR TITLE
Rename rancher to rancher-desktop

### PR DESCRIPTION
**Pull request by bashofmann**
The application is called "Rancher Desktop" not "Rancher", see https://rancherdesktop.io/.

"Rancher" is a different product, multi-cluster Kubernetes Management Solution and not a desktop app (https://rancher.com/products/rancher/).

The cask was just added a few days ago. Are any other steps necessary apart from renaming the file and the token?

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by commitay** [comment]
> Named the cask according to the token reference.

> https://docs.brew.sh/Cask-Cookbook#token-reference
> Remove from the end: strings such as “Desktop”, “for Desktop”.

**Comment by bashofmann** [comment]
I think that naming scheme does not really fit in this case as "rancher" and "rancher-desktop" both exist but are different products. Naming the cask "rancher" when it installs "rancher-desktop" will lead to all kinds of confusion.

**Comment by bevanjkay** [comment]
Ping @vitorgalvao

**Comment by jandubois** [comment]
> I think that naming scheme does not really fit in this case as "rancher" and "rancher-desktop" both exist but are different products. Naming the cask "rancher" when it installs "rancher-desktop" will lead to all kinds of confusion.

I think part of the confusion is that "Rancher" is both a company name (now part of SUSE), and the name of a product/project.

The separate project "Rancher Desktop" is not the "Rancher" project running on the desktop, but a tool for container runtimes on the desktop, made by Rancher, the company.

"Rancher", the project is not related to "Rancher Desktop", except by being produced by the same company.

Calling "Rancher Desktop" just "Rancher" would be like calling "Microsoft Office" just "Microsoft".

**Comment by commitay** [comment]
> https://docs.brew.sh/Cask-Cookbook#token-reference
> By enforcing strict naming conventions we aim to:
>
> * Prevent duplicate submissions
> * Minimize renaming events
> * Unambiguously boil down the name of the software into a unique identifier
>
> Details of software names and brands will inevitably be lost in the conversion to a minimal token.

Also see https://github.com/Homebrew/homebrew-cask/issues/39741 were existing casks e.g. `github-desktop`, `parallels-desktop`, etc had the `-desktop` suffix removed.

**Comment by bashofmann** [comment]
I understand the reasoning, but I still think this does not apply there. "rancher" as a product exists and is completely different to "rancher-desktop". You could even create a formula called "rancher" that installs the Rancher Management Server locally. Then you would have a formula and a cask that are both called "rancher" and install completely different products. And the only thing in common would be the vendor that created and maintains them.

**Comment by vitorgalvao** [comment]
> Then you would have a formula and a cask that are both called "rancher"

Exactly like `docker` and a few others which cause no issue.

> I understand the reasoning, but I still think this does not apply there.

And we understand *your* reasoning and are explaining *it* doesn’t apply. @commitay is a former maintainer.

Until we have a way to rename casks properly (PR welcome), doing so is cumbersome and bad for everyone.

This in particular wouldn’t have passed if the cask were being submitted now; even worse if it’s renaming with no benefit or mitigation to the renaming.

**Comment by AkihiroSuda** [comment]
> Exactly like docker and a few others which cause no issue.

The situation seems different.
Docker Desktop contains "Docker", but Rancher Desktop does not seem to contain "Rancher" (https://github.com/rancher/rancher) as of Rancher Desktop v0.5.0.

Also, I think Rancher/SUSE's opinion on the package name should be respected, as "Rancher" is a registered trademark in several countries. (IANAL, and I do not work for Rancher/SUSE.)

**Comment by vitorgalvao** [comment]
> The situation seems different.

It’s not.

> Docker Desktop contains "Docker", but Rancher Desktop does not seem to contain "Rancher" (https://github.com/rancher/rancher) as of Rancher Desktop v0.5.0.

I have no idea of what you’re referring to.  That’s not the repo the casks uses and what matters is the name of the app.

> Also, I think Rancher/SUSE's opinion on the package name should be respected, as "Rancher" is a registered trademark in several countries. (IANAL, and I do not work for Rancher/SUSE.)

From my non-lawyer knowledge, that’s not how trademarks work. If they dislike the casks’s name, they can rename the app or ask us to not carry it. But we’ll not change casks to arbitrary names picked by vendors—the rules exist for Homebrew’s community and so we can keep consistent naming without duplicates.

I’m certainly open to changing our rules, but this does not warrant an exception. This case isn’t special.

**Pull request closed without merging**
