### PR TITLE
Add u-he Zebra2 cask

### PR DESCRIPTION
**Pull request by Schroedingers-Cat**
After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free. 
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully. 
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

Regarding the name of this cask: it's likely that users will be confused by the already existing "zebra" package, which is a completely different software. Also, additional software from the company of this new cask has names that will likely cause confusion in the future. Maybe it would be appropriate to prefix this and future u-he packages with the company's name `u-he`? Something like `u-he-zebra2` or `uhe-zebra2` would seem fine to me.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by Schroedingers-Cat** [comment]
Any opinion on the possibly confusing situation for users regarding this package's very similar name? https://formulae.brew.sh/formula/zebra#default

**Comment by bevanjkay** [comment]
Ping @vitorgalvao - any thoughts on the token here?

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @Schroedingers-Cat.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by Schroedingers-Cat** [comment]
> Thank you for your contribution to `homebrew-cask` @Schroedingers-Cat.
> 
> Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

Will do.  

What about my suggestion to prefix the token with the company‘s name to avoid confusion?

**Comment by Schroedingers-Cat** [comment]
@miccal the zap stanza example from the documentation you linked to contains style offenses: https://github.com/Homebrew/homebrew-cask/blob/31cd96cc0e00dab1bff74d622e32d816bafd1f6f/Casks/dropbox.rb#L17-L35  
You might want to replace this in the docs with this link: https://github.com/Homebrew/homebrew-cask/blob/723a9d72ec40a478dec79f52d57c3e50cbee1aa4/Casks/dropbox.rb#L27-L48

**Comment by SMillerDev** [comment]
I think the token is fine, one is a cask and the other a formula.

**Review by bevanjkay — APPROVED** [review]

**Comment by bevanjkay** [comment]
Thank you @Schroedingers-Cat

**Pull request merged**
