### PR TITLE
cmake: Add CLI binaries

### PR DESCRIPTION
**Pull request by jawshooah**

### CODE REVIEW

**Comment by DomT4** [comment]
Is there any way to make this optional? I was kinda hoping to allow people to use the GUI alongside the CLI if they wished, especially since Homebrew ruled out shipping the GUI because of circular dependencies and the issues that can cause. Some people are happy using the Brew formula primarily, but want to use the GUI at times. This forces people back into an either/or situation :crying_cat_face:.

**Comment by vitorgalvao** [comment]
Yes there is, [with the --no-binaries flag](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options).

**Comment by jawshooah** [comment]
Also I'm fairly sure that if a binary with the same name already exists in `binarydir`, by default it won't be overwritten.

**Comment by jawshooah** [comment]
Well, not necessarily. We could only overwrite existing symlinks on upgrade or reinstall.

**Pull request merged**
