### PR TITLE
Updating perforce version to 19.2,1908095. Updated sha256 and url to match.

### PR DESCRIPTION
**Pull request by someposer**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by dscho** [comment]
👍 This will unbreak Git's PR/CI builds again.

**Comment by vitorgalvao** [comment]
Why? There’s no appcast, so what’s the point of the extra information?

**Comment by someposer** [comment]
I had two reasons.

1. I wanted to provide more information to the user when the cask is updated. 
2. This change brings the perforce cask inline with the p4v cask.

**Comment by dscho** [comment]
@someposer even @EXPEphall agrees with this approach, would you update this here PR (i.e. rebase)? I am _very much_ in favor of the `.before_comma` approach, avoiding multiple payloads for the _very same_ version number of the `perforce` Homebrew package.

**Pull request merged**
