### PR TITLE
Add GameMaker v2022.6.1.26

### PR DESCRIPTION
**Pull request by matchai**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by matchai** [comment]
It appears this failure is due to GameMaker launching once the pkg finishes installing.
Is there a standard way to prevent the application from launching?

**Comment by p-linnane** [comment]
You'll want to use `uninstall quit:`. Details can be found [here](https://docs.brew.sh/Cask-Cookbook#stanza-uninstall).

**Comment by matchai** [comment]
The cause of the previous failed run was due to the application auto-launching after installation. I've gone ahead and killed the process as postflight, in the same way [zoom does](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/zoom.rb#L23).

Should `uninstall quit:` still be added if it isn't necessary?

I've gone ahead and added a `zap` stanza.

**Comment by p-linnane** [comment]
That should work fine if that was the issue. Just run a `brew style --fix gamemaker`.

**Comment by miccal** [comment]
Thank you @matchai.

**Review by miccal — APPROVED** [review]

**Pull request merged**
