### PR TITLE
qgis: Add gdal-framework, matplotlib Cask dependencies

### PR DESCRIPTION
**Pull request by jawshooah**
Per discussion in #8492.

### CODE REVIEW

**Comment by ndr-qef** [comment]
Sorry, I need to revert this. We cannot remove the caveat until `depends_on :cask` functionality is available in the stable release.

**Comment by jawshooah** [comment]
Ah, my apologies. I figured that these changes would be included in the first stable release to feature the new functionality.

**Comment by ndr-qef** [comment]
Unfortunately that is not the case, which can be confusing: Casks (i.e. the definition files) are updated independently of the actual `brew cask` command functionality.

**Comment by vitorgalvao** [comment]
Apologies for my haste in merging these, @ndr-qef; it didn’t cross my mind to check if the changes were already deployed. Shouldn’t [sshfs.rb](https://github.com/caskroom/homebrew-cask/blob/78fd86c5bf9d8984d72db2a367f07305fcea5e3f/Casks/sshfs.rb) be reverted as well?

**Comment by ndr-qef** [comment]
Not to worry; I was largely absent after #8491 and neglected to provide adequate explanation of the follow-ups.

The patch to sshfs needs not be reverted: `depends_on :cask` has been present in the DSL for quite a while. However, because the `depends_on :cask` is inoperative until the next release, caveats must include instructions to manually install dependencies.

**Pull request merged**
