### PR TITLE
Update blockblock from 0.9.9.4 to 1.0.1

### PR DESCRIPTION
**Pull request by benmontour-wf**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by benmontour-wf** [comment]
With this update, since this version requires MacOS 10.15 Catalina. Will the older version 0.9.9.4 stay available as the latest download for those running < 10.15?

**Comment by core-code** [comment]
only if you create the necessary if/else code to support this

**Comment by benmontour-wf** [comment]
> only if you create the necessary if/else code to support this

I will work on this. Looks like after testing locally I need to update the executable path that's contained within the .app file as well. Withdrawing this PR and fixing.

**Comment by core-code** [comment]
it might be difficult to adapt the 'installer script' stanza to work both with the old and the new version :(

**Comment by benmontour-wf** [comment]
> it might be difficult to adapt the 'installer script' stanza to work both with the old and the new version :(

Could I put my first IF first thing in the stanza based on MacOS.version <= :mojave
and then reference the current installations. Then an ELSE below that with the new stanza?

**Comment by core-code** [comment]
@vitorgalvao any ideas here?

**Pull request closed without merging**
