### PR TITLE
Add Helium by Jaden Geller

### PR DESCRIPTION
**Pull request by EmilFrom**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [x ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ x] `brew install --cask <cask>` worked successfully.
- [x ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by EmilFrom** [comment]
This does not clear the audit because the GitHub repo is archived but I stil think this is a valuable and useful app. It works perfectly on Monterey.
If it stops working it should be removed but for now it's a great app.

**Comment by neutric** [comment]
This was [removed](https://github.com/Homebrew/homebrew-cask/pull/53952) in 2018 because it went MAS only. Also, a free, current fork exists on the MAS.

This is most likely not going to be accepted because the app is [discontinued/unmaintained](https://docs.brew.sh/Acceptable-Casks#rejected-casks):

> The Cask is for an unmaintained app (no releases in the last year, or explicitly discontinued).

Please consider hosting this in [your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).

**Comment by bevanjkay** [comment]
@EmilFrom Thank you for your contribution, however as @neutric has mentioned we will be unable to accept it at this time, as the project is now discontinued upstream.

Please consider hosting this in [your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).

**Comment by EmilFrom** [comment]
Makes a lot of sense. Thank you both for responding. 
I will definitely look into hosting my own tap.

**Pull request closed without merging**
