### PR TITLE
coqide: rename to `coq-platform`, update

### PR DESCRIPTION
**Pull request by krehel**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

---

* Renames the cask from `coqide` to `coq-platform`

* Adds the latest version for both ARM and Intel

* Update URL and livecheck

This update renames the cask and provides many updates.  I noticed that `coqide` had not received an update for many years, and the current repository location was only doing source releases.

There is another repository under the `coq` organization that is doing binary releases under `coq-platform` that contains the same IDE with a new name.  Therefore a rename has been performed and all Cask aspects updated to account for this.

Currently ARM and Intel versions are out of sync, which requires the `on_#{arch}` blocks to account for versions.

I'm not an expert on the Coq ecosystem, but this seems like it is equivalent in what is provided.

### CODE REVIEW

**Comment by krehel** [comment]
Currently this is failing the signature verification check, but since this is technically an existing Cask we should override.

**Comment by khipp** [comment]
I'm fine with overriding the audit for the reasons stated above.

However, I think we should invert the version components to put the IDE version first.

**Comment by krehel** [comment]
Possibly.  I put it this way because `version.csv.first` is the platform release version, `version.csv.second` is the Coq language version included in the platform. This seemed like a natural order.

Overall both should be incrementing version numbers so I don't think it'll break either way.

**Review by daeho-ro — APPROVED** [review]

**Comment by khipp** [comment]
From the release notes for version 2024.10.0:

> The MacOS installer is now not only signed, but also notarized.
> Note: the MacOS intel installer is work in progress

This should pass the audit once the Intel version has been bumped as well.

On a side note, since the ARM version is signed, do we expect the signing audit to also run for the Intel version?

**Comment by krehel** [comment]
Hi @Homebrew/cask is there something else I should do here?  I think this is good to go.  This replaces an outdated version and the version updates are not consistent so I don't think we should wait on an Intel version.

**Pull request merged**
