### PR TITLE
Update joplin from 2.0.11 to 2.1.7

### PR DESCRIPTION
**Pull request by jzafran**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by Kriechi** [comment]
Any specific reason why you updated joplin to a pre-release (non-stable) version?
This has caused some problems in the past and should IMO be avoided.
https://github.com/Homebrew/homebrew-cask/pull/88554#issuecomment-685992718

**Comment by cho-m** [comment]
@Kriechi The `joplin` cask currently determines the latest stable release via the GitHub latest page: https://github.com/laurent22/joplin/releases/latest

If this is not accurate, then the `livecheck` should be updated to detect releases based on a different resource.

**Comment by Kriechi** [comment]
@cho-m oh, I could have sworn that 2.1.7 was marked as pre-release earlier today...
Now it is marked as stable-release, so all good. Move along. Nothing to see here. 😄

**Comment by Kriechi** [comment]
https://discourse.joplinapp.org/t/introducing-joplin-cloud-beta-program/18014/25 indicates I was not dreaming...

So, bumping this cask to a pre-release (at the time of bumping) was IMO not correct and could have lead to another major data corruption as we had in the past.

**Comment by carlocab** [comment]
The `livecheck` block usees `:github_latest`:

https://github.com/Homebrew/homebrew-cask/blob/84116180e9658365a29f6636ef66d49a26d4f3a0/Casks/joplin.rb#L11-L14

This means that CI fails any `joplin` PR that updates it to a version that isn't registered as the latest release on GitHub.

**Pull request merged**
