### PR TITLE
geekbench: convert to `on_system` blocks

### PR DESCRIPTION
**Pull request by Rylan12**
Convert to `on_system` blocks

See #137512

### CODE REVIEW

**Comment by bevanjkay** [comment]
@Rylan12 All these are going to fail due to a CI issue, if you've seen it and can update all good. But I can take a look if you're not already onto it.

**Comment by Rylan12** [comment]
Thanks! Should be fixed by https://github.com/Homebrew/homebrew-cask/pull/138591

**Comment by Rylan12** [comment]
Oops, think I pushed over you on some of these, sorry! 😅

**Review by p-linnane — DISMISSED** [review]

**Review by miccal — APPROVED** [review]

**Pull request merged**
