### PR TITLE
keyman 16.0.140

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by krehel** [comment]
When I downloaded the dmg locally, macOS told me it was damaged.

I don't have the time at the moment to look into this, so if someone else is able to that would be great.  Else, I'll pick it up later today.

**Comment by p-linnane** [comment]
The released a broken binary. We can either reach out to upstream or wait until there is a new release.

**Comment by krehel** [comment]
Thanks. That was also my first thought but didn't have time to deep dive. I'll reach out to upstream.

**Comment by mcdurdin** [comment]
For anyone who may stumble on this in the future, 16.0.140 was broken due to nested installer .app folders (which happened due to subtle differences in BSD vs GNU `cp -R`). I fixed this early in 17.0-alpha but I forgot to back-port the fix to 16.0-stable.

16.0.141 fixes this with https://github.com/keymanapp/keyman/pull/9332.

Sadly we do not currently have tests in Keyman's CI for launching the .dmg. Many thanks to @krehel for reaching out!

**Pull request closed without merging**
