### PR TITLE
Update minergate to latest

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
After looking a bit more into this, it seems that many AV programs classify cryptocurrency miners as malware, since other software may be installing miners without user consent.

That said, I’ve also found some sources questioning Minergate’s honesty specifically.

**Comment by commitay** [comment]
I'm fine with removing anything that Chrome would otherwise block.

[minergate-cli](https://github.com/caskroom/homebrew-cask/blob/master/Casks/minergate-cli.rb) is also blocked

minergate-cli

**Comment by brianmorton** [comment]
I'll submit a new PR removing both this and `minergate-cli` then...

**Comment by brianmorton** [comment]
https://github.com/caskroom/homebrew-cask/pull/45671

**Pull request closed without merging**
