### PR TITLE
Audit: add checks for name and appcast stanzas

### PR DESCRIPTION
**Pull request by jawshooah**
Also fix some style nits in `audit.rb`.

### CODE REVIEW

**Comment by jawshooah** [comment]
Looks like it's working; the new checks found some casks that slipped through with no `name` or `appcast :sha256`.

**Comment by adityadalal924** [comment]
:+1:

Also closes https://github.com/caskroom/homebrew-cask/issues/10997

**Comment by adityadalal924** [comment]
Missing name:
[`au-wifi-connect`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/au-wifi-connect.rb)
[`with-suite`](https://github.com/caskroom/homebrew-cask/blob/master/test/support/Casks/with-suite.rb)
[`bassjump`]()

Missings appcast shasum:
[`shimo.rb`]()

**Comment by vitorgalvao** [comment]
`shimo` wasn’t supposed to have an `appcast` (not working). For some my fix to that didn’t stick (was doing a lot of them at once). Will fix now.

**Comment by vitorgalvao** [comment]
Documentation for these changed on https://github.com/caskroom/homebrew-cask/pull/16163.

**Comment by Amorymeltzer** [comment]
Good to see these getting some love :100:

**Comment by vitorgalvao** [comment]
Casks fixed. Travis restarted. Everything green, now.

**Pull request merged**
