### PR TITLE
Update intel-power-gadget from 3.6.0 to 3.7.0,b7b1b3e1dffd9b20

### PR DESCRIPTION
**Pull request by core-code**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
since this may ( https://github.com/Homebrew/homebrew-cask/pull/82479 ) we had to switch to a super old version of 'intel-power-gadget' because although they still talk about version 3.7 (and even 3.6.2) on their homepage, the only version you can actually download is version 3.6 back from october 2019

switching to the versions provided in their built-in update check would prevent this issue and allow us to have the latest version 3.7 again

however i'd like some confirmation that this is really what we want there


@miccal @vitorgalvao @ran-dall thoughts?


```
cask-analytics intel-power-gadget
intel-power-gadget
30 days: 456 (#240)
90 days: 1,384 (#237)
365 days: 5,595 (#582)
Traceback (most recent call last):
	3: from /usr/local/bin/cask-analytics:43:in `<main>'
	2: from /usr/local/bin/cask-analytics:43:in `each'
	1: from /usr/local/bin/cask-analytics:80:in `block in <main>'
/usr/local/bin/cask-analytics:80:in `system': no implicit conversion of Pathname into String (TypeError)
```

**Comment by core-code** [comment]
> installer: Error - Intel® Power Gadget does not currently support systems with more than one CPU package.
 
i think this CI error always happens with this package

**Comment by miccal** [comment]
According to the `Info.plist` file inside the `Intel Power Gadget.app` from the `.pkg` provided by the updated `url`:
```
<key>CFBundleShortVersionString</key>
<string>3.7.0</string>
<key>CFBundleVersion</key>
<string>3.7.0</string>
```

**Comment by core-code** [comment]
yes, i checked that of course

**Comment by vitorgalvao** [comment]
> thoughts?

I’m fine with this change.

> ```
> Traceback (most recent call last):
> 	3: from /usr/local/bin/cask-analytics:43:in `<main>'
> 	2: from /usr/local/bin/cask-analytics:43:in `each'
> 	1: from /usr/local/bin/cask-analytics:80:in `block in <main>'
> /usr/local/bin/cask-analytics:80:in `system': no implicit conversion of Pathname into String (TypeError)
> ```

I was unaware of that error. Just pushed a fix.

> i think this CI error always happens with this package

It does, yes.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
