### PR TITLE
Update gitkraken

### PR DESCRIPTION
**Pull request by YSaxon**
Just bumping up the version for GitKraken

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- (The following errors are raised but I presume them to be unrelated)

```

  * audit_exceptions/versioned_dependencies_conflicts_allowlist.json references
    formulae or casks that are not found in the homebrew/core tap.
    Invalid formulae or casks: predictionio
  * pypi_formula_mappings.json references
    formulae or casks that are not found in the homebrew/core tap.
    Invalid formulae or casks: rtv
```
- [X] `brew style --fix <cask>` reports no offenses.
- - `1 file inspected, no offenses detected`

### CODE REVIEW

**Comment by krehel** [comment]
Hi @YSaxon - this 9.1.0 is a very old version relative to what is the current version.  There have been many updates since.  (See below).  Is your local `homebrew-cask` up to date?  Thanks.

```
fd68bdde33 gitkraken 9.5.1
7baf352c67 gitkraken 9.5.0
e5f9278fbd gitkraken 9.4.0 (#146752)
628eba3a16 gitkraken 9.3.0 (#144659)
742994eef2 Update gitkraken from 9.2.0 to 9.2.1 (#143002)
2051a842ae Update gitkraken from 9.1.1 to 9.2.0 (#142561)
0cd7411375 Update gitkraken from 9.1.0 to 9.1.1 (#141378)
```

**Comment by miccal** [comment]
Duplicate of https://github.com/Homebrew/homebrew-cask/pull/149000

**Comment by YSaxon** [comment]
Interesting, I guess it must have somehow not been updated (though I’m not sure exactly how not, since brew auto updates these days, and everything else in my brew is up to date as far as I know)

**Comment by krehel** [comment]
@YSaxon - understood.  There have been some ongoing issues over the past few days being worked through with GitHub.  Recommend running `brew upgrade` at the very least to ensure fully up to date.

Check issue #150243 and https://github.com/Homebrew/brew/issues/15616

**Pull request closed without merging**
