### PR TITLE
Add Zero Brane Studio

### PR DESCRIPTION
**Pull request by iggyvolz**
See http://studio.zerobrane.com/.

I'm fairly certain that this is compliant with #8664.  The download page asks for a donation, but gives an option not to donate.  The code is available under the MIT license.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
It is. To be clear, that rule applies only to cases where you’d have to make an account, or otherwise be blocked from seeing the download link. Either way, it wouldn’t affect this case, as the rule is also only concerned with cases where the download url is on a different domain than the homepage.

It does, however, have the wrong token and file name. It should be `zerobranestudio`.

**Comment by iggyvolz** [comment]
Okay - done.

I'll squash once I get the final OK, because I usually end up making numerous changes to casks before they're merged.

**Comment by vitorgalvao** [comment]
It’s good, you can squash.

**Comment by iggyvolz** [comment]
All good - squashed and rebased onto master.

**Comment by vitorgalvao** [comment]
Thank you. Merged.

**Pull request merged**
