### PR TITLE
Update version, URL, OS dependency, zap paths for paragon-extfs

### PR DESCRIPTION
**Pull request by p-linnane**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by p-linnane** [comment]
@miccal RE: livecheck: Paragon Software publishes version information on pages that require sign in. I am going to reach out and see if they can publish this information on the public page.

**Comment by miccal** [comment]
Thanks @p-linnane.

Ping @samford for their insight.

**Comment by samford** [comment]
I looked around and didn't find any public source for version information either. The application also requires you to sign in to check for updates. I also searched the app's strings and came up empty handed.

The installer's `Info.plist` contains the current version but `UnversionedCaskChecker` doesn't appear to handle this situation as-is, so I agree with skipping this unless/until upstream starts publishing public version information in some fashion. I was in the process of adding a `skip` suggestion but Bevan committed exactly what I was going to suggest seconds before 😄

Seeing as there's no available version information, is it still appropriate to switch this from `version :latest` to a version string?

**Comment by bevanjkay** [comment]
@samford Given that we are now hash checking `version :latest` artifacts for changes, I feel it's probably more beneficial to change it back.

Particularly, because there's no livecheck we will only know of any update if a user bumps the version after checking it manually. Where `version :latest` would at least check the download for differences if `brew upgrade --greedy` or `brew upgrade --greedy-latest` is used. Additionally, there's no easy way for a maintainer to verify an updated version is correct.

**Comment by p-linnane** [comment]
Thank you all for the input and collaboration on this. This has been a solid learning experience for me!

**Review by miccal — APPROVED** [review]

**Pull request merged**
