### PR TITLE
Update superduper from 3.3,120 to 3.3.1,121

### PR DESCRIPTION
**Pull request by chohner**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by chohner** [comment]
Any assistance why the style check seems to fail? Seems like a trivial version change...

Style check also passes on my machine™:
```
 ~ ❯ brew cask style --fix superduper

1 file inspected, no offenses detected
```

**Comment by ran-dall** [comment]
ping @core-code @suschizu

**Comment by core-code** [comment]
thanks for the heads-up @ran-dall 
actually unsure there, it seems like a part of homebrew itself is failing
ping @reitermarkus

**Comment by ran-dall** [comment]
@core-code @reitermarkus May it have something to do with https://github.com/Homebrew/homebrew-bundle/pull/593?

**Comment by core-code** [comment]
@ran-dall i suspect you are right this could be the culprit

**Pull request merged**
