### PR TITLE
ultdata: update livecheck, use versioned url

### PR DESCRIPTION
**Pull request by khipp**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

Related to https://github.com/Homebrew/homebrew-cask/issues/171006.

### CODE REVIEW

**Review by samford — COMMENTED** [review]
Looking in the app, it appears that 1053 is the product ID (there are strings like `"ProductURL" = "http://cbs.tenorshare.com/go?pid=1053&a=dp"`), so this approach may not be any more versioned than the existing URL.

If 1053 was a number that would change (e.g., a build number, etc.), I'm still not sure where we stand on using a `version` that doesn't include the app version. Usually we would use something like `9.7.27,1053` (or `9.7.27.12,1053`) and `version.csv.second` in the `url` but that's not feasible since we can only identify the version using `ExtractPlist`.

It would be good for someone else to check my work but that's what I'm seeing from a quick look.

**Comment by krehel** [comment]
Agreed with @samford.  Read this yesterday, forgot to comment.  I'm not in favor of this, sorry.

**Comment by khipp** [comment]
Agreed, I will close this one then. Thanks anyway!

**Comment by krehel** [comment]
No worries @khipp - it happens! Thanks for the contribution. ❤️

**Pull request closed without merging**
