### PR TITLE
Update coconutbattery to 3.7

### PR DESCRIPTION
**Pull request by tiiiecherle**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by tiiiecherle** [comment]
Just downloaded from the dev website

```
shasum --algorithm 256 /Users/tom/Desktop/files/coconutBattery_3.7.zip
0993860896d498ffc4bf9c6b6f25d724bfa0a967b19fb211eb347547118f3a2e  /Users/tom/Desktop/files/coconutBattery_3.7.zip
```

I don`t know why the checksum changed.

**Comment by tiiiecherle** [comment]
> The release is signed, so it seems to be legit. Mind contacting them about the malware?

done ;)

**Comment by vitorgalvao** [comment]
Thank you. Since it’s signed, it can be merged.

**Pull request merged**
