### PR TITLE
Revert #66826

### PR DESCRIPTION
**Pull request by core-code**

### CODE REVIEW

**Comment by core-code** [comment]
@BrewTestBot where are you when we need you?

**Comment by core-code** [comment]
@vitorgalvao sorry to be annoying yet again ;/ can you merge this?

**Comment by reitermarkus** [comment]
> @BrewTestBot where are you when we need you?

Version decreases aren't auto-merged.

**Comment by core-code** [comment]
thanks. i'll try to find a better appcast for wireshark so this future reverts won't be necessary

**Pull request merged**
