### PR TITLE
Add cydownload.app Latest

### PR DESCRIPTION
**Pull request by StevenSeiden**
After making all changes to the cask:

- [*] `brew cask audit --download {{cask_file}}` is error-free.
- [*] `brew cask style --fix {{cask_file}}` reports no offenses.
- [*] The commit message includes the cask’s name and version.
- [*] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [*] Named the cask according to the [token reference].
- [*] `brew cask install {{cask_file}}` worked successfully.
- [*] `brew cask uninstall {{cask_file}}` worked successfully.
- [*] Checked there are no [open pull requests] for the same cask.
- [*] Checked the cask was not [already refused].
- [*] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This [has already been refused with a justification](https://github.com/Homebrew/homebrew-cask/pull/77081#issuecomment-586330005). Nothing has changed since then. Please don’t resubmit.

**Comment by StevenSeiden** [comment]
I fixed the issue that the first pull request declined for.

**Comment by vitorgalvao** [comment]
> I believe that I did fix the issue that the first pull request declined for, as per the "Fixed homepage" commit within this request.

That was a note for future submissions. The refusal reason is in the comment.

> Please let me know if there is something else that I would need to do.

There isn’t. The issue is in the software itself.

**Comment by StevenSeiden** [comment]
Alright thank you!

**Comment by vitorgalvao** [comment]
> Thank you for letting me know, and sorry about the confusion!

No problem. On technical terms, your submission was good (the missing `homepage` was a minor issue) and I hope to see more from you in the future (hence why I made the remark on what needed fixing).

Have a nice day.

**Pull request closed without merging**
