### PR TITLE
Add protonmail-unofficial 0.5.2

### PR DESCRIPTION
**Pull request by neilbartley**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution.

Next time please don’t collapse the checkboxes. Keeping the template as was makes it easier to parse what you ticked.

**Review by vitorgalvao — APPROVED** [review]

**Comment by vitorgalvao** [comment]
On hold for https://github.com/caskroom/homebrew-cask/pull/39708.

**Comment by commitay** [comment]
@vitorgalvao As this is an unofficial app I'm not sure about calling this just `protonmail`.

I'm not forgetting "not a discoverability service", but it would be easy to mistake this as an offical app if you only inspect the Cask (brew cask cat). 

Protonmail also has a Github https://github.com/protonmail and an app https://github.com/ProtonMail/WebClient (has to be built)

Normally I would say it's not an issue but as this is an app for an encrypted email service I feel that explicitly calling this unofficial would be appropriate.

**Comment by vitorgalvao** [comment]
@commitay That’s a good point. It actually falls into a new rule I had been thinking about today due to https://github.com/caskroom/homebrew-cask/pull/39706.

I was thinking that every unofficial app that uses the official name unofficially (i.e. without permission from the developers) should mandatorily have the fork name prefix, regardless of it there is another app with its name or not.

**Comment by commitay** [comment]
> I was thinking that every unofficial app that uses the official name unofficially (i.e. without permission from the developers) should mandatorily have the fork name prefix, regardless of it there is another app with its name or not.

I think this is a good idea that should cover most cases but sometimes the fork / Github org name duplicates the `app` name or would otherwise give the appearance of being official. When this occurs (this Cask) I'd suggest adding an `-unoffical` suffix.

**Comment by vitorgalvao** [comment]
Let’s make it on hold again for https://github.com/caskroom/homebrew-cask/issues/39739.

**Review by commitay — APPROVED** [review]

**Pull request merged**
