### PR TITLE
Update java from 12.0.1,69cfe15208a647278a19ef0990eea691 to 12.0.2,10:e482c34c86bd4bf8b56c0b35558996b9

### PR DESCRIPTION
**Pull request by robertleeblairjr**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by robertleeblairjr** [comment]
I was updating my jdk and decided to make some pulls for the other casks. It wouldn't be as confusing if some of the cask names were renamed to better help differentiate between them. Those openjdk distributions that already have a tap, such as adoptopenjdk, could be dropped or only offering the most recent distribution release. This cask 'java' could be renamed to 'oracle-openjdk' since the commercial version is 'oracle-jdk'. Drop the other 'java{#}' casks since they point to outdated versions. The others could be renamed to indicate '*-openjdk{#}'. The openjdk distributions could be reduced to those offered by oracle (oracle-openjdk), azul (zulu-openjdk{7, 8, 11, 12}), adoptopenjdk (via tap), and amazon (corretto-openjdk{8, 11}). Reducing these further to just the homebrew-cask tap would only be the latest offered by each distribution. Any other casks with dependencies requiring non-latest stable or developmental versions could be referred via caveats to homebrew-cask-versions tap. It would at least clean up the differentiation between current standing casks and remove those not being developed.

**Comment by ykursadkaya** [comment]
This topic is still under discussion in #57387 and causing errors like AdoptOpenJDK/homebrew-openjdk#106, Homebrew/brew#6112

I believe [Homebrew/brew](https://github.com/Homebrew/brew) and [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask) team is working on cleanup system and naming conventions.

**Comment by vitorgalvao** [comment]
Closing due to the reason given by @ykursadkaya.

**Comment by robertleeblairjr** [comment]
> This topic is still under discussion in #57387 and causing errors like [AdoptOpenJDK/homebrew-openjdk#106](https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/106), [Homebrew/brew#6112](https://github.com/Homebrew/brew/issues/6112)
> 
> I believe [Homebrew/brew](https://github.com/Homebrew/brew) and [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask) team is working on cleanup system and naming conventions.

Thanks for those links. I haven't read all of them and posted in a couple of others. Yes, the naming schemes and some casks for jdk should be cleaned up to avoid confusion and conflict. I'd like to think if the distribution of openjdk has a tap, then just removing the cask from homebrew taps would be better, such as adopt-openjdk. I would think only latest,stable could be a cask on homebrew/cask tap and any other (LTS, development, beta) on homebrew/cask-versions tap or distributions tap. Something like, {distribution identifer}-openjdk{# development, LTS, beta}. Either way, I suppose they'll figure it out.

**Comment by robertleeblairjr** [comment]
> Closing due to the reason given by @ykursadkaya.

Are you just removing the 'java' cask or renaming it?

**Comment by vitorgalvao** [comment]
> Are you just removing the 'java' cask or renaming it?

@claui has carte blanche to deal with these. When all decisions are made, we’re meant to build a document explaining the rationale.

**Comment by robertleeblairjr** [comment]
> > Are you just removing the 'java' cask or renaming it?
> 
> @claui has carte blanche to deal with these. When all decisions are made, we’re meant to build a document explaining the rationale.

Okay. As of right now, this cask is broken, which was why I made a pull request to update it to a valid url for the oracle openjdk version 12. This pull request wasn't made just to rename or remove. I was merely making a comment concerning whether it could be renamed or removed.

**Comment by robertleeblairjr** [comment]
@vitorgalvao Thank you.

**Comment by bondolo** [comment]
At minimum the cask should be renamed openjdk as it is distributing the GPL-licensed Oracle OpenJDK distribution not the non-opensource licensed "Java SE Development Kit" distribution. Oracle provides both but under different licenses and the license terms are substantially different. Since most users have no accepted the "Oracle Technology Network License Agreement for Oracle Java SE" and/or don't have a commercial license the OpenJDK is generally a better choice.

**Comment by cdaller** [comment]
please split up the discussion of naming and the update to latest openjdk, so the update is not blocked by the naming discussion - openjdk 12.0.1 has some security bugs and therefore we are waiting for the 12.0.2 version!

**Comment by bondolo** [comment]
From what I can tell it doesn't appear anything is happening anywhere on this issue. I also submitted a cask-repair PR for the java 12.0.2 update and it was also closed. Please correct me if I am wrong by pointing me at the active discussion.

**Comment by vitorgalvao** [comment]
> Please correct me if I am wrong by pointing me at the active discussion.

https://github.com/Homebrew/homebrew-cask/pull/66328#issuecomment-512242960

**Comment by bondolo** [comment]
> > Please correct me if I am wrong by pointing me at the active discussion.
> 
> [#66328 (comment)](https://github.com/Homebrew/homebrew-cask/pull/66328#issuecomment-512242960)

Unfortunately all of the referenced discussions seem to have stalled with the newest messages being weeks ago. (Which is, of course, in no way your fault).

**Comment by bondolo** [comment]
fwiw, the Oracle BCL-licensed Java JDK is available as oracle-jdk. Be aware this not the GPL2 licensed OpenJDK build.

**Comment by cdaller** [comment]
What is blocking this issue? Who is able to unblock it? 

At the moment all homebrew users are forced to use the old openjdk version 12.0.1 that has some security leaks.

Why not merge this change so we can update to 12.0.2 and then in a separate discussion/PR change the name to openjdk (including all packages that depend on "java").

**Comment by reitermarkus** [comment]
Merging this now due to the points made by @cdaller.

The discussion regarding renaming should be continued here: https://github.com/Homebrew/homebrew-cask/issues/57387

**Pull request merged**
