### PR TITLE
Update serviio to 1.9.2

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by gtmgianni** [comment]
@suschizu Travis returned this:
```
>>> Leftover: launchjob_load
> org.serviio.server
```

**Review by vitorgalvao — APPROVED** [review]

**Comment by reitermarkus** [comment]
I can never merge PRs by @suschizu, I am always getting “You can’t perform that action at this time.”, does this happen to anyone else?

It works when I use “Squash and merge”, but not with my default “Rebase and merge”.

**Comment by alebcay** [comment]
> I can never merge PRs by @suschizu, I am always getting “You can’t perform that action at this time.”, does this happen to anyone else?

On #47660 and #47661, I see a merge conflict (the button is completely greyed out). The button on this PR is green for me with both squash and rebase (although I haven't actually clicked through to try it).

**Comment by vitorgalvao** [comment]
@reitermarkus I think we were both merging PRs at the same time, earlier. Can’t attest for the others, but I see you made your comment slightly after I pushed changes to the PR, so that message may have come from there (updated since you were viewing). Will try to merge this one now.

**Comment by reitermarkus** [comment]
No, it was definitely not because we were merging at the same time. This has happened with every PR by @suschizu for me so far, which is very weird.

**Comment by reitermarkus** [comment]
> Will try to merge this one now.

Did you use squash or rebase?

**Comment by vitorgalvao** [comment]
> Did you use squash or rebase?

Crap, squash.

**Pull request merged**
