### PR TITLE
Update eclipse-cpp from 4.14.0,2019-12:R to 4.15.0,2020-03:R

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
`hdiutil: convert failed - image not recognized`
not sure what to do here …

**Comment by vitorgalvao** [comment]
> `hdiutil: convert failed - image not recognized`
> not sure what to do here …

That indicates a bad DMG, which is a bother because it needs to be fixed upstream.

**Comment by suschizu** [comment]
hm - so we can't do anything here? … thats annoying 
should I close the pull requests - or does it make sense to wait if something changes?

**Comment by vitorgalvao** [comment]
Let’s close and try again later.

**Pull request closed without merging**
