### PR TITLE
Cask/zecwallet

### PR DESCRIPTION
**Pull request by BlurryRoots**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> + The Cask is too obscure. Examples:
>   + A self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 30 forks, 30 watchers, and 75 stars).
>   + [Electronic Identification (eID) software](https://github.com/Homebrew/homebrew-cask/issues/59021).

**Comment by BlurryRoots** [comment]
Appreciate the quick turn around time. How is this a self submitted app though? I am just a user who both likes homebrew and the app. It's a lite version of the zCash wallet. And it is endorsed on the offical page https://z.cash/wallets/

**Comment by ran-dall** [comment]
> How is this a self submitted app though?

@BlurryRoots It doesn't actually have to be self-submitted for the notiablity requirements to apply. You're more then welcome to keep it in a personal tap though.

**Comment by f33rx** [comment]
> Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):
> 
> > * The Cask is too obscure. Examples:
> >   
> >   * A self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 30 forks, 30 watchers, and 75 stars).
> >   * [Electronic Identification (eID) software](https://github.com/Homebrew/homebrew-cask/issues/59021).

On what basis is notability determined?

**Comment by f33rx** [comment]
> Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):
> 
> > * The Cask is too obscure. Examples:
> >   
> >   * A self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 30 forks, 30 watchers, and 75 stars).
> >   * [Electronic Identification (eID) software](https://github.com/Homebrew/homebrew-cask/issues/59021).

The notability guidelines are a skosh flimsy. This is not a side project that the PR owner created.  https://www.crunchbase.com/organization/zcash

**Comment by vitorgalvao** [comment]
> The notability guidelines are a skosh flimsy.

We agree, but it’s the best we have. [We want to make them better](https://github.com/Homebrew/homebrew-cask/issues/78675) but we have to start somewhere.

> This is not a side project that the PR owner created.

Now was that the claim or reason for refusal.

**Comment by BlurryRoots** [comment]
In case someone is looking for this cask, I've created a tap at https://github.com/BlurryRoots/homebrew-zecwallet-lite

**Pull request closed without merging**
