### PR TITLE
Update sitesucker-pro from 4.1 to 4.1.1

### PR DESCRIPTION
**Pull request by eloyaldea**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @eloyaldea !

**Comment by eloyaldea** [comment]
For what? Hahahaha, happy to contribute :)

**Comment by SMillerDev** [comment]
For doing the thing 😄

**Comment by eloyaldea** [comment]
Np :)

**Pull request merged**
