### PR TITLE
Update integrity to :latest

### PR DESCRIPTION
**Pull request by sscotth**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by sscotth** [comment]
Would `:latest` & `:no_check` be preferred here?

**Comment by sscotth** [comment]
I updated the PR just in case

**Review by vitorgalvao — APPROVED** [review]
Reinstated appcast, since it still works.

**Comment by sscotth** [comment]
I got an audit warning not to use appcast with `:latest`

```
• audit for integrity: warning
 - Casks with an appcast should not use version :latest
```

https://github.com/Homebrew/brew/blob/ca86f0703982e243e3940b03b32fc91f4a8b7fb8/Library/Homebrew/cask/audit.rb#L213

**Comment by vitorgalvao** [comment]
> I got an audit warning not to use appcast with `:latest`

The cask is not using `:latest`. I think I see where your confusion is coming from, so I’ll clarify. The rule is: if a cask’s `url` is unversioned, it requires `:latest`/`:no_check` (because we can’t know when it changes upstream) *unless* it has an `appcast`, in which case it must have a set `version` and `sha256` (because we can use the `appcast` to know when there are changes upstream).

**Pull request merged**
