### PR TITLE
puzzles 20230403

### PR DESCRIPTION
**Pull request by TsanBoi**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
The app updates _very_ frequently (possibly every git commit or so) with relatively few downloads. I would suggest moving this to `version :latest`, unless someone feels more strongly about removing.
Downloads: `0/18/119`

**Comment by Vulxan** [comment]
Ok, the version has been set to `"`:latest`.

**Comment by reitermarkus** [comment]
Previous throttling workaround: https://github.com/Homebrew/homebrew-cask/pull/142173

**Comment by reitermarkus** [comment]
Ideally we will incorporate throttling into `bump-cask-pr` instead, though.

**Comment by reitermarkus** [comment]
The version contains a date, so we should be able to throttle it based on that.

**Comment by p-linnane** [comment]
We update this pretty much daily in `homebrew-core` as well. I have no strong feelings on what we do with it here.

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
