### PR TITLE
Anaconda auto updates

### PR DESCRIPTION
**Pull request by domoritz**
After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
@domoritz Does this "auto update" i.e prompt for updates / silently install updates or do you need to run a `conda update` command?

**Comment by domoritz** [comment]
Good point. I run `conda update --all` from time to time and so my anaconda is up to date even though cask thinks it is not. I don't think anaconda auto updates in the background (it might pop up a dialog, but not sure).

So what's the right setting for a cask that does not auto update in the background but that does have an update mechanism?

**Comment by commitay** [comment]
> So what's the right setting for a cask that does not auto update in the background but that does have an update mechanism?

We don't have a setting to cover this case. 

We have a few command line Casks that can self update but because this requires an explicit `update` / `upgrade` command we don't set `auto_update`. Most of our users depend on Cask to handle the updates.

**Comment by domoritz** [comment]
Thanks for the explanation. I have to check whether anaconda shows a popup or not. I will close this PR until then.

**Pull request closed without merging**
