### PR TITLE
Remove Etcher spyware application

### PR DESCRIPTION
**Pull request by sneak**
Wikipedia defines spyware as:

> Spyware is a software that aims to gather information about a person or organization, sometimes without their knowledge, and send such information to another entity without the consumer's consent. 

Etcher has done *precisely this* for some time.  The developers' excuse for not changing this behavior is that they don't believe that they are breaking the law, as the data is anonymous (to them).  However, it includes IP address and timestamp information, which is more than sufficient to identify a user (and perhaps even their physical location), if not to them, then to the other people who gain access to this data, such as analytics providers, network hosts, interchange points, ISPs, and intelligence services.

Regardless, this is not about what data is collected, simply that data is collected silently *without user consent or interaction*.  There is a setting to disable it, but by the time you can even get to the setting, the software has already leaked your data, and in normal operation the setting is *never displayed to the user*.

Etcher is **spyware**.  Please do not ship spyware in caskroom.

### CODE REVIEW

**Comment by sneak** [comment]
You can see their refusal to act to remedy this here: https://github.com/balena-io/etcher/issues/2057

(Despite the issue being erroneously closed, this issue is still present in the current version.)

**Comment by ran-dall** [comment]
@sneak Thanks for the heads up. Definitely looks like they may be doing something suspicious here. I don't use the software, so I don't really have much of a opinion...but maybe @commitay  (who has updated this cask extensively in the past) may have an opinion of what should be done?

**Comment by core-code** [comment]
making a network connection without your consent is not "spyware". 

all (TCP-IP) network connections, by definition, use an ip-address. 

it is not nice if the etcher people use analytics without your consent, but unless they are stealing actual private data, this is not spyware. 

you are confusing 'tracking' with 'spyware'.

**Comment by sneak** [comment]
Let's be very objective and specific here.  

# The Definition

Wikipedia defines spyware as:

> Spyware is a software that aims to gather information about a person or organization, sometimes without their knowledge, and send such information to another entity without the consumer's consent. 

# Required Elements

1. is software :white_check_mark: etcher is software
1. gather information about a person :white_check_mark: information: that the user is launching etcher
1. without their knowledge :white_check_mark: no indication is displayed at any time that this is happening
1. send information to another entity :white_check_mark: information is transmitted to LAN, ISP, interchange points, hosting provider, national government (via cable taps), and hundreds of others
1. without consent :white_check_mark: no consent is asked for or given (and indeed, none exists)

I don't know how it's *not* spyware, honestly.  The fact that I opened Etcher at 2:47PM is private data.  It's transmitting that out of my computer without my consent to many different people and organizations, despite a TLS connection (the packet contains my IP, happens at a point in time (timestamp), and contains the TLS SNI hostname of the vendor).

It is entirely nonessential to the functionality of the software.  It benefits the vendor, at the expense of my privacy.  It is user-hostile.  It does so silently, without warning or notice.

**Comment by ran-dall** [comment]
@sneak I think what @core-code is trying to say is that the use of analytics is somewhat standard for software. Typically, vendors should ask for your permission, but in this situation, they aren't; however, that doesn't really make them 'spyware.' It's more of a misuse of a standard. Don't get me wrong, it's a violation of a user's privacy, but I think HBC's position is for the end-sure to decide what's best for them. REF: 

> We’ve always been straightforward that the user is the last line of defense, and have been explicit that you shouldn’t fall into a false sense of security and think “because it’s on HBC, it’s safe”. We do what we can, but malicious-software-hunting is not a core goal. Though we welcome @core-code’s malware checks.

**Comment by sneak** [comment]
> I think what @core-code is trying to say is that the use of analytics is somewhat standard for software

That's not the case, and you shouldn't think it's the case.  It's somewhat standard for *remote websites*, where merely requesting them *necessarily* leaks some of your information, but it is *absolutely* not standard for locally installed software.  Software that does that is an *outlier*.

I can list two dozen applications that I have installed on my computer that don't spy on me (or even ask to), but there are fewer than a half-dozen that wish to (and almost all of them are unethical in that they send information before I've had a chance to opt out).

>  Don't get me wrong, it's a violation of a user's privacy, but I think HBC's position is for the end-sure to decide what's best for them.

The way we keep it from becoming a standard is by not shipping or promoting or recommending software that takes this user-hostile stance of entitlement to a user's data and internet connection.  More software packages are trying this nonsense now because they're getting away with it and not getting enough pushback.  If users knew what they were doing, they'd never use it, but they do it silently!

If you *know* the software is violating the user's privacy, why on Earth would you continue to ship it?  That's irresponsible.

You're already removing malicious software.  This is simply one more instance.  Remove it.

**Comment by ran-dall** [comment]
@sneak Just so you know, I and @core-code don't really have any authority to remove the software. We're merely trying to clarify HBC's position. For a piece of software to be removed, it must be done by one of the maintainers, and usually, they consider several points-of-view and positions. I'm solely trying to facilitate a discussion. Considering there have been `2,384` installs in the last 30 days; I feel like there should be a discussion.

That said, you bring up **lots** of good points, and from a personal level, I'd probably agree with you (but I don't use the software). As for HBC, HBC is not an app store; therefore, HBC tries to stay as agnostic and non-opinionated, as possible. HBC doesn't promote, ship, or recommend for-or-against anything.

Also, just to clarify, neither of us is saying that a violation of a user's right to privacy isn't grounds for removal. I'm pretty sure @core-code is just trying to make sure that "we call a spade, a spade".

**Comment by core-code** [comment]
@sneak i don't like tracking either, but using a different definition for 'spyware' than the rest of the world doesn't help your case. 99.9% of all websites, 99% of all iPhone apps and 80% of all mac apps do tracking. if we removed 'etcher' either because it makes a network connection without asking, we'd have to remove a few thousand other apps too. 

in any case, i am sure a maintainer will give an official response here in the next few days.

**Comment by vitorgalvao** [comment]
@sneak Thank you for making this report, but please check your tone. It’s escalating to the point you’re making assumptions about us and giving orders. I don’t know you and we don’t owe you anything. You’ve never contributed before and we have little more than your word to go on, so please be patient. No one is being disrespectful.

I care deeply about user privacy, and I’m confident @core-code and @ran-dall do too. **We’re all on the same side**, here. But a project of this size can’t be run on personal opinion; every change is a potential source of contention.

Taking your report as truth, I wouldn’t use the software. But I also wouldn’t use [Zoom](https://zoom.us/) and [made a criticism similar to yours](https://twitter.com/vhgalvao/status/1159490330334511105) in that situation. Yet the cask remains because a significant amount of people—even the ones who understand the situation—make the choice to keep using the software. I don’t agree with their choice, but I’m also not going to take it away because of personal ideology. It would be different if *the community* as a whole had made that decision or the software were immediately dangerous.

I’m going to leave the PR open for a bit and label it as a `discussion`, but so far I’m inclined to leave the cask be. You might want to look into opening a formal GDPR complaint.

**Comment by sneak** [comment]
> *Considering there have been 2,384 installs in the last 30 days; I feel like there should be a discussion*

The discussion should be about how the lack of action here has facilitated over two thousand people being spied on without their knowledge via this spyware.

> but using a different definition for 'spyware' than the rest of the world doesn't help your case

I'm using the definition from wikipedia.  Please let me know where you think I've gone wrong.

> 99.9% of all websites, 99% of all iPhone apps and 80% of all mac apps do tracking

These numbers are not accurate, you just made them up, and they are not supported by data.

**Comment by vitorgalvao** [comment]
> The discussion should be about how the lack of action here has facilitated over two thousand people being spied on without their knowledge via this spyware.

You’re arguing that a lack of action *since yesterday* when you opened this PR has facilitated people being spied on for the last thirty days.

> These numbers are not accurate, you just made them up, and they are not supported by data.

You don’t know that.

I’ll ask once more that you keep your tone in check. You clearly feel strongly on this issue, so much so that I’m beginning to question if you’re *for privacy* or *against Etcher*. We’re not the venue for your personal vendetta. When we make a decision, we’ll do so in the context of what’s best for this community. I’ve already argued that everyone on this issue agrees on principle that tracking users is wrong, and no one here is your enemy.

You’re not thinking of others. Homebrew Cask is used by thousands, and you don’t know if they share your opinion.

You can either wait and see if there’s any development (i.e. anyone cares enough about to comment further), or you can keep escalating and force me to lock the issue and/or ban you and leave everything else as is. I’d like to not have to resort to the latter.

**Comment by sneak** [comment]
I am against spyware and spyware developers, and etcher is spyware developer by spyware developers, so yes, I am against etcher and those unethical people who make it.

**Pull request closed without merging**
