### PR TITLE
new app: Nucleo

### PR DESCRIPTION
**Pull request by yurikoles**
#### Adding a new cask
- [✓] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [✓] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [✓] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [✓] Commit message includes cask’s name.
- [✓] `brew cask audit --download {{cask_file}}` is error-free.
- [✓] `brew cask style --fix {{cask_file}}` left no offenses.
- [✓] `brew cask install {{cask_file}}` worked successfully.
- [✓] `brew cask uninstall {{cask_file}}` worked successfully.

As requested in #23707

### CODE REVIEW

**Comment by adidalal** [comment]
Appcast at `https://updates.devmate.com/co.ambercreative.Nucleoapp.xml`

url `https://dl.devmate.com/co.ambercreative.Nucleoapp/26/1467733372/Nucleo-26.zip`, version displayed in app is `1.0.3` - feel free to format in whatever way works best.

**Comment by yurikoles** [comment]
Why do specific versions if it just works with as `:lastest`/`:no_check`?

**Comment by adidalal** [comment]
Versioned URLs are preferred - with the appcast `checkpoint` we can also detect updates automatically, creating a basis for upgrade functionality

See a third-party implementation that works right now (I use it) at https://github.com/buo/homebrew-cask-upgrade

**Comment by yurikoles** [comment]
@adidalal done

**Comment by jawshooah** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 82582c4e5e3209b9338d423f0ffa5f5e75aaae4c. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
