### PR TITLE
veracrypt-fuse-t 1.26.14 (new cask)

### PR DESCRIPTION
**Pull request by ghost**
This is specifically for the `fuse-t` version of Veracrypt for Mac detailed as "FUSE-T compatible version is recommanded for Mac computers with Apple silicon" on the Veracrypt downloads page: https://www.veracrypt.fr/en/Downloads.html

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [X] `brew audit --cask --new <cask>` worked successfully.
- [X] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [X] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by vodium-vastro** [comment]
The `fuse-t` dependency requires a tap: `brew tap macos-fuse-t/homebrew-cask`. What is the process to allow this in the cask file?

See https://www.fuse-t.org/ -> `Installing from brew`

**Comment by daeho-ro** [comment]
I think than the `fuse-t` add first here and after that `veracrypt-fuse-t`.

**Comment by krehel** [comment]
Users should not be required to tap a 3rd party to use an application in Cask IMHO. It is not a good precedent.

**Comment by p-linnane** [comment]
We do not support depending on third-party taps in this repository.

**Pull request closed without merging**
