### PR TITLE
Update dockertoolbox to 1.9.1h

### PR DESCRIPTION
**Pull request by 0xdevalias**

### CODE REVIEW

**Comment by adityadalal924** [comment]
`appcast` also needs to be updated. Use `cask-repair` (see CONTRIBUTING.md) or follow directions in https://github.com/caskroom/homebrew-cask/issues/16689 to update appcast manually.

**Comment by alias1** [comment]
Fixed appcast with repair :)

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in de535441d44401f3df1c8dea715bd61a81c9cc3c. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by alias1** [comment]
No worries, thanks :)

Sent from Outlook Mobile




On Mon, Jan 11, 2016 at 5:12 AM -0800, "Vítor Galvão" <notifications@github.com> wrote:












Thank you for the contribution. It needed some fixes, so they were made in de53544. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
