### PR TITLE
Update the kite .dmg url

### PR DESCRIPTION
**Pull request by vidhanio**
After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by SMillerDev** [comment]
The website actually says it's not available for download

**Comment by vidhanio** [comment]
It says that but then after filling out the form downloads it nonetheless. This URL was where the download was from.

**Comment by vidhanio** [comment]
UPDATE: nvm, I just realized I clicked a link that downloaded it, and I forgot that that was the one that started the download.

[https://release.kite.com/dls/mac/current](https://release.kite.com/dls/mac/current) redirects to the [https://kitedownloadss.b-cdn.net/mac/0.20210610.0/Kite.dmg](https://kitedownloadss.b-cdn.net/mac/0.20210610.0/Kite.dmg) link i posted.

**Comment by miccal** [comment]
Thank you @vidhanio.

**Comment by vidhanio** [comment]
no problem! :)

**Pull request merged**
