### PR TITLE
Cinder v0.9.0

### PR DESCRIPTION
**Pull request by kyeshmz**
_If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so._

Sorry for the complications that happened last time. 
This pull should work as I carefully went through all the steps.

After making all changes to the cask:
- [x ] `brew cask audit --download {{cask_file}}` is error-free.
- [ x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:
- [ x] Named the cask according to the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x ] `brew cask install {{cask_file}}` worked successfully.
- [x ] `brew cask uninstall {{cask_file}}` worked successfully.
- [x ] Checked there are no [open pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [ x] Checked that the cask was not already refused in [closed issues](https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed).

### CODE REVIEW

**Comment by miccal** [comment]
You need to add a [comment](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment) above the `url` stanza.

**Comment by miccal** [comment]
Apologies - the comment above the `url` is not required since the URL and homepage hostnames are the same.

**Comment by jawshooah** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 7df84d855d3fcd77208cd7215c98c2e0acb62776. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by kkshmz** [comment]
I get the unnecessary url line, can I ask what was the "missing line"?

**Comment by jawshooah** [comment]
> can I ask what was the "missing line"?

It needed an empty line between `sha256` and `url` to conform to `brew cask style`.

**Comment by kkshmz** [comment]
Noted. Thank you.

**Pull request closed without merging**
