### PR TITLE
Add Synth1 Audio Unit and VST

### PR DESCRIPTION
**Pull request by joshka**
Includes the new artifacts to represent a symlink to the ~/Library/Audio/Plug-Ins/{VST,Components} folders.

### CODE REVIEW

**Comment by adityadalal924** [comment]
Please make this PR just the synth1 plugins (this can wait until #15643 is merged), as once https://github.com/caskroom/homebrew-cask/pull/15643 is merged, we'll likely cut a new release and bump the cask DSL version so that the features are available.

**Comment by joshka** [comment]
Gotcha - thanks.

**Comment by adityadalal924** [comment]
@joshka https://github.com/caskroom/homebrew-cask/issues/15643 is now merged and the documentation updated accordingly.

Please either rebase or make a new PR with only the two Cask files - `synth1-au.rb` and `synth1-vst.rb`.

Additionally, please change the cask header line to be be of version `1_2`, to be consistent with the documentation.
Example: `cask :v1_2 => 'dropbox' do`

**Comment by jawshooah** [comment]
Thank you for the contribution. It needed some fixes, so they were made in abe5fa7096a26950b71eb53d567739ee58f0bf62. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by joshka** [comment]
Thanks guys

**Pull request closed without merging**
