### PR TITLE
Add livecheck for classroom-assistant

### PR DESCRIPTION
**Pull request by Misaka13514**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
It’s not necessary. This uses a GitHub releases URL, so if you try `livecheck` now it already works.

**Comment by Misaka13514** [comment]
```
╰─>$ brew livecheck classroom-assistant
classroom-assistant : 2.0.3 ==> 2.0.4
```

but `2.0.4` is a pre-release @vitorgalvao 

- #103069
- #102668

After my commit 581a8a , livecheck works normally.

Should I open an issue?

**Comment by samford** [comment]
@vitorgalvao It's true that we only add a `livecheck` block when the default check isn't sufficient but it's necessary for `classroom-assistant`.

The default check uses the `Git` strategy and reports `2.0.4` as newest but this is currently [marked as pre-release](https://github.com/education/classroom-assistant/releases). The "latest" release on GitHub is `2.0.3` and this is what we should be using. In this case, the newest Git tag isn't correct and it's necessary to use the `GithubLatest` strategy to obtain the correct latest version.

We [only use `GithubLatest` when it's necessary](https://docs.brew.sh/Brew-Livecheck#general-guidelines) (i.e., the `Git` strategy doesn't provide the correct latest version) but this particular situation is one of the intended use cases for the strategy. The `livecheck` block in this PR correctly addresses this issue, so this should be reopened and merged in my view.

**Comment by vitorgalvao** [comment]
You’re right. I did not check if it was a prerelease. Thank you.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
