### PR TITLE
Update java to 1.8.0_121-b13,e9e7ea248e2c4826b92b3f075a80e441

### PR DESCRIPTION
**Pull request by colindunn**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by colindunn** [comment]
They had added a hash value into the download link which is a bit painful, so I've adjusted accordingly. Also added a java_update value into the cask body to try to make it a bit more obvious what's going on so let me know if that's OK too.

**Comment by colindunn** [comment]
Hey maintainers, any feedback for this one?

**Comment by vitorgalvao** [comment]
As long as we’re adding a new variable to this mess (freaking java), we might as well add one for each `split` case.

**Comment by colindunn** [comment]
Thanks @vitorgalvao

**Pull request merged**
