### PR TITLE
Add bin path to binary of scilab

### PR DESCRIPTION
**Pull request by ricglz**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by reitermarkus** [comment]
`binary` does not work with directories.

**Comment by reitermarkus** [comment]
`binary` does not work with directories.

**Comment by ricglz0201** [comment]
Then why does casks like [Atom](https://github.com/Homebrew/homebrew-cask/blob/c9cbc7f60555893167735bc96c19ea6206846920/Casks/atom.rb) has a binary to path?

**Comment by vitorgalvao** [comment]
> Then why does casks like [Atom](https://github.com/Homebrew/homebrew-cask/blob/c9cbc7f60555893167735bc96c19ea6206846920/Casks/atom.rb) has a binary to path?

Atom’s `binary`s are pointing to files, not directories.

**Comment by ricglz0201** [comment]
Ok, I fix those mistakes and instead of pointing to the folder now is pointing to the files. Also I fixed an error with the SHA-256 checksum

**Comment by vitorgalvao** [comment]
@ricglz0201 Looks good. Thank you.

**Pull request merged**
