### PR TITLE
Update calibre from 5.16.1 to 5.17.0

### PR DESCRIPTION
**Pull request by xxyzz**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Comment by jtbayly** [comment]
Ugh... so the cask is broken until this get approved, huh? I guess this happens regularly, but I've never had it bite me in my continuous integration until tonight.

**Review by jtbayly — APPROVED** [review]
Can I approve this and fix the cask so I can get back to work? Not sure, but I'm going to try.

**Comment by xxyzz** [comment]
How could this pr break your brew cask? What's the error message? You don't have the write access of this repo so your approve won't merge it.

**Review by miccal — APPROVED** [review]

**Comment by jtbayly** [comment]
Thanks everybody for your work. Seriously. Thank you.

**Pull request merged**
