### PR TITLE
removed aerofs.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
I see no direct link to the app on [the website](https://www.aerofs.com/). If someone can point me to where it is officially said that is a valid link, we then need to add a `# cloudfront.net is the official download host per the vendor homepage` comment above `url`; otherwise, the cask should be moved to [caskroom/unofficial](https://github.com/caskroom/homebrew-unofficial).

### CODE REVIEW

**Comment by rolandwalker** [comment]
I have previously verified this URL, and just did so again.  The download is only visible when you have a login.

**Comment by vitorgalvao** [comment]
I just noticed my initial comment is wrong (I’ve copied it from a previous similar submission and didn’t alter everything). Since the link is from a different host than the homepage and behind a registration wall, [we should move it to caskroom/unofficial](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#unofficial-vendorless-or-walled-builds).

Not sure you caught [the relevant PR](https://github.com/caskroom/homebrew-cask/pull/8748) and [consensus](https://github.com/caskroom/homebrew-cask/issues/8664#issuecomment-69212133). Do you feel these cases should be handled differently?

**Comment by rolandwalker** [comment]
Since you ask, I *feel* that if a maintainer verifies it, then it could stay here.  But that's just feeling or intuition.

I haven't followed all the relevant PRs nor analyzed all the Casks as you have been doing, and will happily defer to your informed decision.

**Comment by vitorgalvao** [comment]
Thank you. In that case I’ll do it as in the (new) documentation since it got some support, but will still try to distill some of my reasoning.

One of my reasons behind [the original idea](https://github.com/caskroom/homebrew-cask/issues/8664#issuecomment-69212133) was

> On the other hand, we should not pick and chose based on if a maintainer felt like creating a dummy account or happens to use the software; we should be consistent.

As small note here is that, for contributors, this means they immediately know where to submit a cask. The home of each cask is clear and dependent on its origin, not on us as maintainers which is a much foggier metric.

On to the bigger point, the validity of “[playing favourites](https://github.com/caskroom/homebrew-cask/pull/8840)” aside, the idea of holding a maintainer to such responsibility and burden makes me a bit uneasy. A cask such as this one could technically keep being updated without a problem (since it uses `#{version}`), but one like [`radbeacon`](https://github.com/caskroom/homebrew-cask/blob/f9353f51edbdfe6a97d1359b39442b8eb553f26a/Casks/radbeacon.rb) would need to be rechecked every time. There’s also the consideration that a third-party CDN link could possibly be taken by malicious people if upstream stops using it. That’s unlikely and shouldn’t cause much damage<sup>1</sup>, though. It could also very well happen to casks whose url isn’t behind a registration wall, but those that are behind one are way harder (more laborious) to detect and as such place a much higher load on the responsibility of [that little comment](https://github.com/caskroom/homebrew-cask/blob/9e75fb5569afd3d969fb20ef5eb44f540d2b26fd/Casks/eve.rb#L5).

Yesterday night I started going through all the casks that lack such a comment and whose `url` and `homepage` are on different hosts<sup>2</sup>. There are still 421 to go, and I was able to check only about 12 (it was getting late). Of those twelve, [one was removed](https://github.com/caskroom/homebrew-cask/pull/8927) for an unrelated reason and two had download urls fixed. One of them being [aliedit](https://github.com/caskroom/homebrew-cask/pull/8925/files), and the other [even had its version downgraded](https://github.com/caskroom/homebrew-cask/pull/8924/files) (I have no idea where the other, higher version, came from). This is a relatively small sample and nothing guarantees those links didn’t change since first introduced, having been the official ones at the time, but even if they were, these corrections were possible because the links are public. Were they not, the burden would’ve been mostly on a single maintainer to verify them, and I’m guessing none of us wants to periodically do that. Now, having the aforementioned comment on casks with public download links also brings some responsibility with it, but I feel the bar is way lower because all users can keep it in check, meaning *they don’t even have to trust us*, and that idea I really like.

---

<sup>1</sup>Going back to the “we’re not a discoverability service” idea.
<sup>2</sup>A small script made the initial passage erring on the side of inclusion, and then a manual one was made to remove cases that did not belong.

**Pull request merged**
