### PR TITLE
Update aria2d from 1.3.6 to 1.3.7

### PR DESCRIPTION
**Pull request by henryhchchc**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by henryhchchc** [comment]
Looks like the author did not update the AppCast xml file.

**Comment by henryhchchc** [comment]
Should we switch this cask to using GitHub releases for `livecheck` or I close this PR for now?

**Comment by bevanjkay** [comment]
@henryhchchc The app's in-app updating system follows the appcast, so we should wait for it to update because it could be intentional.

**Comment by henryhchchc** [comment]
Thanks for the advice. Let me close the PR for now.

**Pull request closed without merging**
