### PR TITLE
Add auto_updates stanza to Keybase

### PR DESCRIPTION
**Pull request by xtian**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Forget this should also have an `appcast`. @adidalal Want to take a look?

**Comment by adidalal** [comment]
Well the appcast *should* be at `https://keybase-app.s3.amazonaws.com/appcast.xml` but I can't seem to get that URL

Found it from https://github.com/keybase/client/blob/master/osx/Scripts/Updater/site/appcast.xml if it helps.

**Comment by vitorgalvao** [comment]
They publish releases on the github repo. We might as well use that appcast and those releases, since they are versioned.

**Comment by vitorgalvao** [comment]
[Asked them about it](https://github.com/keybase/client/issues/3898).

**Pull request merged**
