### PR TITLE
Update teampaper-snap to 2.1.1,8919:2017-06-26_10-33-18

### PR DESCRIPTION
**Pull request by colindunn**
After making all changes to the cask:

- [x] \`brew cask audit --download {{cask_file}}\` is error-free.
- [x] \`brew cask style --fix {{cask_file}}\` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by colindunn** [comment]
This is horrid versioning due to the way they have structured the files in the zip. Fully open to suggestions!

**Comment by commitay** [comment]
This looks like its moved to MAS. https://www.teampaper.me/sparkle/sparkle.xml

The homepage only has a MAS link.

**Comment by colindunn** [comment]
I see what you mean, the latest is 2.2.1 iTunes. Will I submit a removal then?

**Comment by commitay** [comment]
> Will I submit a removal then?

Yes, thanks!

**Comment by colindunn** [comment]
Closed in favour of #40956

**Pull request closed without merging**
