### PR TITLE
PyCharm: Add Command Line Tool

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This is smart. And it definitely threads [shim script territory](https://github.com/caskroom/homebrew-cask/issues/9203).

It’s my understanding these tools will actually guide you through the process of making such CLI executable on first run, isn’t that so? In that case, I see this as a potential source for conflict (we should assume that if the tool is asking it, the user will assume we didn’t make such executable).

**Comment by adityadalal924** [comment]
See also https://github.com/caskroom/homebrew-cask/issues/12028 for previous discussion.

**Comment by vitorgalvao** [comment]
Thank you for that link, @adityadalal924. Had forgotten about that discussion.

I’m more inclined to follow [this comment](https://github.com/caskroom/homebrew-cask/issues/12028#issuecomment-142387133) and close this issue and that one.

**Comment by reitermarkus** [comment]
The main issue here is of course that you would have to update it manually every time you update the application because the cask directory will have a new version number. Anyway, I don't think this will be an issue anymore once the new installation behaviour is implemented as the path will stay the same.

**Comment by adityadalal924** [comment]
@reitermarkus You're correct on both.

In that case, both this PR and the older issue should be closed, as we'll try to keep working towards the best long-term solution rather than adding in short-term fixes that end up making things difficult in the long run.

**Pull request closed without merging**
