### PR TITLE
Update dbeaver-community from 7.1.1 to 7.1.2

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by zubieta** [comment]
Hi @ran-dall, I see you merged #85467 thanks. Just out of curiosity, do you know why did the build fail and why was it needed to launch it again?

**Comment by ran-dall** [comment]
Duplicate of #85467

**Comment by ran-dall** [comment]
@zubieta I don't. Sometimes it does this on certain casks.

**Comment by zubieta** [comment]
I see. Thanks!

**Pull request closed without merging**
