### PR TITLE
double-commander: Discontinued

### PR DESCRIPTION
**Pull request by p-linnane**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by p-linnane** [comment]
Development on macOS seems to have stopped. This appears to be the final release.

**Comment by bevanjkay** [comment]
@p-linnane We can instead add a discontinued caveat block and remove the livecheck. 

https://docs.brew.sh/Cask-Cookbook#caveats-mini-dsl

**Comment by p-linnane** [comment]
@bevanjkay Updated with the discontinued caveat.

**Comment by bevanjkay** [comment]
@samford Is the current failure on the CI run an issue in the livecheck logic? Having a `discontinued` caveat should mean the livecheck block can (and should) be omitted, but the audit is failing because the Sourceforge URL requires a livecheck?

**Comment by samford** [comment]
> Is the current failure on the CI run an issue in the livecheck logic? Having a `discontinued` caveat should mean the livecheck block can (and should) be omitted, but the audit is failing because the Sourceforge URL requires a livecheck?

I didn't create the livecheck-related cask audits but, as you discovered, this is a shortcoming in the `Cask::Audit#check_hosting_with_livecheck` logic and I agree with the brew PR 👍

**Review by bevanjkay — APPROVED** [review]

**Comment by decadent** [comment]
BTW, Double Commander can actually be compiled on OSX—dunno what's Homebrew's policy in regard to compiling apps, as opposed to console stuff.

**Comment by p-linnane** [comment]
@decadent I believe that would fit better in the core tap. Per the [Rejected Casks](https://docs.brew.sh/Acceptable-Casks#rejected-casks) section under docs:

> The app is open-source and has a GUI but no compiled versions (or only old ones) are provided. It’s better to have them in [Homebrew/core](https://github.com/Homebrew/homebrew-core) so users don’t get perpetually outdated versions. See [gedit](https://github.com/Homebrew/homebrew-cask/pull/23360) for example.

**Pull request closed without merging**
