### PR TITLE
Update licenses for 41 casks

### PR DESCRIPTION
**Pull request by Amorymeltzer**
Most of these are pretty straightforward, any rationales are in the commit message.  I would, however, greatly appreciate double-check of `intel-power-gadget`, since I can't actually install it on my machine.  I believe it's `:gratis` but a second eye from someone who can even install it would be nice.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Seems like you’re correct regarding `intel-power-gadget`. Also can’t install on my machine, though.

Calling on @ahbeng, @brendanjerwin, and @halilim for confirmation.

**Comment by halilim** [comment]
Seems `:gratis` to me: https://gist.github.com/halilim/c319e12d5ff3e1e0786b (copied from the install dialog) :+1:

**Comment by Amorymeltzer** [comment]
Thanks @halilim!

**Comment by ndr-qef** [comment]
Excellent, thanks.

**Pull request merged**
