### PR TITLE
Add Tinkerwell.app v2.6.0

### PR DESCRIPTION
**Pull request by owenvoke**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vitorgalvao** [comment]
@core-code New Electron appcast:

```
provider: spaces
name: tinkerwell
region: fra1
channel: latest
path: /tinkerwell
acl: public-read
updaterCacheDirName: tinkerwell-updater
```

**Comment by vladimyr** [comment]
Additional changes proposed: https://github.com/owenvoke/homebrew-cask/pull/1

**Comment by vitorgalvao** [comment]
@vladimyr If you make those changes as suggestions in this PR, I can merge them is directly.

**Comment by vladimyr** [comment]
@vitorgalvao Yeah, I know that. Thing is that requires me to do it through GitHub's UI while in most cases I do those from the terminal. I need to find a _git_ way of creating suggestions 🤔

**Comment by Gummibeer** [comment]
@vladimyr have you tried the new GH CLI? I have no idea but it's really powerful, primary if it gets to PRs, merging and so on.

**Comment by vladimyr** [comment]
@Gummibeer Thanks for your suggestion. I need to try it. I'm a long time `hub` user and wasn't really thrilled when `gh` cli came out.

**Comment by owenvoke** [comment]
Thanks, I've merged those changes in. Let me know if there is anything else that's needed. :+1:

**Review by vladimyr — APPROVED** [review]

**Pull request merged**
