### PR TITLE
Update airmedia from 3.1.12 to 3.1.29

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@core-code Could you please troubleshoot this? I'm away from my computer tonight.

**Comment by core-code** [comment]
no problem, please try

url 'https://www.crestron.com/Crestron/media/Crestron/WidenResources/Web%20Miscellaneous/airmedia_osx_#{version.dots_to_underscores}_guest.zip'

**Comment by core-code** [comment]
aaaand the checksum should be '95585254f8d82e16229af9f89da0806f0c5ff8f927d2b21efcdeefd88b912b52' ;)

**Comment by ran-dall** [comment]
👌 Teamwork!

**Pull request merged**
