### PR TITLE
Update zoc to 7.11.2

### PR DESCRIPTION
**Pull request by SentinelWarren**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by miccal** [comment]
Please remove the `arduino` Cask from your PR.

**Comment by SentinelWarren** [comment]
@miccal done,sorry it was a mistake

**Comment by SentinelWarren** [comment]
@miccal i think i have define (outdated_cask=arduino.rb),how to i undefined this cause it keeps on returning the same issue with other commits.

**Comment by miccal** [comment]
@SentinelWarren I do not know what you mean?

**Comment by SentinelWarren** [comment]
i used [This guide](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask) ,,so i assigned `outdated_cask` to `arduino.rb` ,and now i have to do a rebase to any new pull request i make because arduino update is included since it is still assigned to `outdated_cask`. Am asking how to stop this from happening?

**Comment by miccal** [comment]
Try running the command `unset outdated_cask` in bash; if it works and you run `echo $outdated_cask` it should return nothing.

**Pull request merged**
