### PR TITLE
hexcore-link: migrate

### PR DESCRIPTION
**Pull request by razvanazamfirei**
There's a curl SSL issue with this cask, so I moved it to a separate PR.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Looks like their CA `TrustAsia RSA DV TLS CA G2` is not trusted. I don't feel strongly about migrating this and doubt it will get resolved soon. Feel free to close.

**Comment by reitermarkus** [comment]
It actually works for me locally without any certificate issues.

**Comment by reitermarkus** [comment]
Maybe untrusted on Ventura? I am running Monterey.

**Comment by bevanjkay** [comment]
I'm seeing the untrusted error on Ventura.

**Comment by reitermarkus** [comment]
Let's just remove it then.

**Pull request closed without merging**
