### PR TITLE
multipass 1.14.0

### PR DESCRIPTION
**Pull request by khipp**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by khipp** [comment]
The application installs and runs without issues on my M1. Were there changes to the CI between the last two versions that could be related?

I will create an issue in the upstream repository tomorrow.

**Comment by cho-m** [comment]
It sounds like the installer has been checking for `kern.hv_support` for a while (e.g. https://github.com/canonical/multipass/issues/1397).

However, Hypervisor.framework isn't supported on GitHub runner (e.g. https://github.com/actions/runner-images/issues/9460).

**Comment by ZelnickB** [comment]
Can someone with permission please add the `in progress` tag so that this doesn't get closed?

**Comment by krehel** [comment]
Fine to ✅ this as I don't think the CI issues are going to be resolved anytime soon, nor are they ours to fix.

**Review by bevanjkay — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
