### PR TITLE
font-meslo-for-powerline: Update to latest version

### PR DESCRIPTION
**Pull request by segevfiner**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by bevanjkay** [comment]
This should be pinned to a release of some sort, rather than just tracking master.

**Comment by segevfiner** [comment]
No release was made in ages, other casks from this repo seem to point to latest...

**Comment by SMillerDev** [comment]
Since there is a repo, can you ask for a release?

**Comment by segevfiner** [comment]
I asked https://github.com/powerline/fonts/issues/402, but I'm not sure it is likely to happen and the rest of the fonts from that repo point to master as well.

**Comment by p-linnane** [comment]
Agreed that this does not seem likely. Closing.

**Pull request closed without merging**
