### PR TITLE
Demoted "To install, drag this icon" from readme header.

### PR DESCRIPTION
**Pull request by bcomnes**
I always found the wording of the header in the readme confusing.  e.g. Did homebrew cask used be installed by icon dragging?  Do I install cask by dragging? Oh wait, its referring to what cask enables.

Care if we change the header to something more conventional and just include the concept as a pull quote?

### CODE REVIEW

**Comment by vitorgalvao** [comment]
I never had a problem with the header, but I wouldn’t be opposed to switching it (it’s @phinze’s decision as the originator, I’d say).

However, I’ll say I find the pull quote logic flawed as it is. It should be

```
> “To install, drag this icon…”

No more!
```

We’re quoting what most apps say, and then replying to it. Also took the chance to correct the quotes and ellipsis.

**Comment by bcomnes** [comment]
I was thinking the whole phrase was more of a tagline to the project, but honestly whatever you all want to do.

**Comment by vitorgalvao** [comment]
Well, yes, but the way you have it now (everything inside the pull quote) makes no sense. “No more!” isn’t a quote, and having it there would be more confusing.

**Comment by bcomnes** [comment]
Just removed the pull quote all together and left it as plain text under the header.  Thoughts?

**Comment by Amorymeltzer** [comment]
I (personally) like this new style better.  It always struck me as odd that the first thing item you saw was the "slogan", not the name.  Maybe a sub-heading style could be used so the tagline is more prominent?  Either way, this styling brings it into agreement with the header on http://caskroom.io/

**Comment by phinze** [comment]
+1 here - good example of an arbitrary early decision that never had much thought put in it - until now! :grinning: 

I might play with tossing it in italics, but I'll merge this as-is first.

**Comment by Amorymeltzer** [comment]
@phinze +1 for italics

**Comment by phinze** [comment]
Done; also bumped badges down. :+1: 

caskroom_homebrew-cask

**Comment by bcomnes** [comment]
:+1: Looks great!

**Pull request merged**
