### PR TITLE
quaternion 0.0.96

### PR DESCRIPTION
**Pull request by aaronraimist**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
https://github.com/quotient-im/Quaternion/issues/894

**Comment by aaronraimist** [comment]
Not sure if you would prefer I add the change here or in a new PR but I have added the `zap` stanza and fixed `depends_on`.

**Comment by bevanjkay** [comment]
@aaronraimist Thank you. Here is fine

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
