### PR TITLE
Update asana from 1.8.0 to 1.9.0

### PR DESCRIPTION
**Pull request by LanikSJ**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by LanikSJ** [comment]
I don't know why this fails livecheck when you install this app you get a prompt to update and you get `1.9.0`.

**Comment by p-linnane** [comment]
@LanikSJ Livecheck is failing because the file Homebrew is pulling is `https://desktop-downloads.asana.com/darwin_universal/prod/latest/Asana.dmg` which is currently version `1.8.0`. Asana still needs to update that file to `1.9.0`. A maintainer will most likely add a `ci-retry` tag to this PR to have it keep trying until it succeeds.

**Comment by LanikSJ** [comment]
Either close this or wait is fine by me. 🙂

**Comment by MrCoBalt** [comment]
FYI I filed a ticket with Asana and they fixed their Universal app download link, so `https://desktop-downloads.asana.com/darwin_universal/prod/latest/Asana.dmg` now has the `1.9.0` version same as their per-architecture downloads at `https://desktop-downloads.asana.com/darwin_x64/prod/latest/Asana.dmg` and `https://desktop-downloads.asana.com/darwin_arm64/prod/latest/Asana.dmg`

**Comment by LanikSJ** [comment]
I don't see an option to reopen this one so I'll just open a new one.

**Comment by LanikSJ** [comment]
#129232

**Pull request closed without merging**
