### PR TITLE
Add kubebuilder 1.0.8

### PR DESCRIPTION
**Pull request by stevemcquaid**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by stevemcquaid** [comment]
How do i get around the travis error for double quotes? https://travis-ci.org/Homebrew/homebrew-cask/builds/535493767#L331

[Binary stanza needs double quotes for string interpolation of the version in the binary name](https://github.com/Homebrew/homebrew-cask/pull/63639/files#diff-5b84d7c987b711b9c0605a4e9c6adb9aR10)

**Comment by vitorgalvao** [comment]
Welcome, and thank you for the contribution.

Unfortunately, this seems to be a CLI-only open-source tool. Please submit it first to [Homebrew/core](https://github.com/homebrew/homebrew-core) as a formula. Return here if not accepted (linking back to the pull request where it was refused).

This policy is documented in [faq/rejected_casks](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core) as a formula that builds from source. If it is rejected, you may then try again as a cask (link us to the issue so we can see the discussion and reasoning for rejection).

**Comment by stevemcquaid** [comment]
REF: https://github.com/Homebrew/homebrew-core/pull/40186

**Comment by stevemcquaid** [comment]
@vitorgalvao Not accepted by core. Thoughts?

https://github.com/Homebrew/homebrew-core/pull/40186#discussion_r286754850

**Comment by vitorgalvao** [comment]
> Not accepted by core.

That’s not a rejection, it’s a “might be better to submit later”.

**Comment by vitorgalvao** [comment]
> Not accepted by core.

That’s not a rejection, it’s a “might be better to submit later”. It’s not the same thing; the correct repo in the Homebrew context still seems to be that one.

**Comment by stevemcquaid** [comment]
> That’s not a rejection, it’s a “might be better to submit later”. It’s not the same thing; the correct repo in the Homebrew context still seems to be that one.

Fair enough :) Thanks for the clarification!

I just found out one other issue here: https://github.com/kubernetes-sigs/kubebuilder/issues/326

Basically kubebuilder is not expecting to be instaleld from source. Is this something that might be able to be submitted to homebrew-cask once it reaches a stable version?

**Comment by vitorgalvao** [comment]
> Is this something that might be able to be submitted to homebrew-cask once it reaches a stable version?

We may discuss it again after it reaches that point, yes.

**Pull request closed without merging**
