### PR TITLE
thinkorswim: (un)installation automated

### PR DESCRIPTION
**Pull request by radeksimko**
This depends on #10291

### CODE REVIEW

**Comment by radeksimko** [comment]
Java is apparently bundled with the installation package.

**Comment by radeksimko** [comment]
@vitorgalvao For the future, if a cask depends on a particular cask codebase version, it's better to release the cask core change first, wait a few weeks and then release the actual cask change - this way we can make sure people won't see errors trying to uninstall `thinkorswim` using older cask core codebase.

**Comment by vitorgalvao** [comment]
Ah, apologies, I just missed (skipped) your “[t]his depends on” comment. I looked at it and thought “why isn’t this merged yet? Oh, right, @radeksimko has voiced in the past that he doesn’t like to merge his own PRs”, so I thought you were just waiting for someone to do it.

When a PR depends on another, I usually prepend something like `[HOLD until #0000]` to the title, so I don’t keep checking it.

**Comment by radeksimko** [comment]
> I thought you were just waiting for someone to do it.

Well I was, but when I've seen you merging this PR, the best thing I could do at that point was to merge the dependency, to reduce the potential harm for users. More importantly I've seen the "LGTM" from @phinze so I didn't feel bad when merging it.

It's not about not merging my own PRs, it's more about merging these without any feedback. I don't mind merging my own PRs if I know that someone else have seen that and was OK with that.

> When a PR depends on another, I usually prepend something like [HOLD until #0000] to the title, so I don’t keep checking it.

OK, good to know, I will try to remember and use that convention. Maybe we could use a label for this instead?

**Comment by vitorgalvao** [comment]
> it's more about merging these without any feedback.

Yeah, I guess sometimes we (I know I do it) see a small PR where everything looks fine, and don’t actually reply because we don’t realise it’s waiting for feedback, when it isn’t tagged, so it just stands there, when in actuality it could’ve already been merged.

> Maybe we could use a label for this instead?

Agreed. Done.

**Pull request merged**
