### PR TITLE
Delete rejected_casks.md

### PR DESCRIPTION
**Pull request by vitorgalvao**
Continuation of https://github.com/Homebrew/brew/pull/10577.

### CODE REVIEW

**Comment by j-f1** [comment]
Should this keep a single-line file that points to the new location so people with old links don’t hit a 404?

**Comment by vitorgalvao** [comment]
> Should this keep a single-line file that points to the new location so people with old links don’t hit a 404?

I can’t imagine a lot of people have links saved to this file. Do you?

**Comment by j-f1** [comment]
Good point — I personally don’t know of anything specific but there could quite possibly be links to this or the other removed files in issue comments or other places online.

**Comment by vitorgalvao** [comment]
It’s not like this is mission critical information, and it isn’t lost forever, so I don’t think it’s justifiable.

**Review by reitermarkus — APPROVED** [review]

**Pull request merged**
