### PR TITLE
Add GitDock.app v0.1.11

### PR DESCRIPTION
**Pull request by kgoossens**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Not sure what the issue is here:
```
Error: exception while auditing gitdock: undefined method `<' for nil:NilClass
```

**Comment by miccal** [comment]
Did not work -- the problem must be in the `url`.

While we investigate this further @kgoossens, could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by miccal** [comment]
> @miccal It is because the `url` uses the `api/v4` syntax, so the audit for the repo is trying to navigate to `https://gitlab.com/api/v4/projects/api/v4` which returns a 404.

Yes I get that, but I am not 100 % sure that is the problem because both `cura-lulzbot` and `librewolf` _do not_ do that, but  `brew audit --online --new-cask` fails for them with the same error.

**Comment by kgoossens** [comment]
I've added the `zap`-stanza but the brew audit failed again in the CI pipeline.
I'm checking with @MvRemmerden to see if we can create a permalink to the release artefacts which might be a workaround for the failure 🤞

**Pull request merged**
