### PR TITLE
remove license from all casks

### PR DESCRIPTION
**Pull request by vitorgalvao**
Finally happening.

cc @caskroom/maintainers.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Could you wait for https://github.com/caskroom/homebrew-cask/pull/24343? I don't want do resolve merge conflicts for the tenth time. 😄

**Comment by vitorgalvao** [comment]
Sure thing! Marking `on hold` until then. Will also leave [caskroom/versions](https://github.com/caskroom/homebrew-versions) alone. Will just remove from `eid` and `fonts`.

**Comment by reitermarkus** [comment]
Thanks!

**Comment by vitorgalvao** [comment]
Didn’t know you were going to do it so soon. So can I fix and merge this one now?

**Comment by reitermarkus** [comment]
> Didn’t know you were going to do it so soon. So can I fix and merge this one now?

I was just waiting for that one last Travis run to finish. You can go ahead now. 👍

**Comment by vitorgalvao** [comment]
Thank you. Will close this one and open a new one (faster than fixing conflicts).

**Pull request closed without merging**
