### PR TITLE
Add CellProfiler

### PR DESCRIPTION
**Pull request by mike-u**
#### Adding a new cask

I fixed the version number to :latest and added the url comment. I closed the last PR because I made some mistakes trying to use git and I have no idea how to fix them nor the patience

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You need to `brew cask --style {{cask_file}}`. The build will fail because you don’t have the correct spacing between lines.

**Comment by mike-u** [comment]
I've made the changes.

**Comment by vitorgalvao** [comment]
Not fixed yet. You have trailing whitespace on some lines.

**Comment by mike-u** [comment]
reopened to retry the Travis build.

**Comment by mike-u** [comment]
@vitorgalvao I believe this is correct now. I don't see a link to the Travis results since github went back up though.

**Comment by adidalal** [comment]
Thank you for the contribution. It needed some fixes, so they were made in ab51ae774c7801b548c15526be17bc161d10fcc9. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
