### PR TITLE
Add pCloud drive cask version 3.7.9

### PR DESCRIPTION
**Pull request by tomgross**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by tomgross** [comment]
There was an refused cask in https://github.com/Homebrew/homebrew-cask/pull/51552 because the download URL was volatile. This no longer seems to be the case.

**Comment by tomgross** [comment]
Everything except uninstall on travis works now. After installation an instance of pcloud _(com.pcloud.pcloud.macos)_ is running. It needs to be killed before uninstalling. Any help appreciated.

**Comment by vitorgalvao** [comment]
I understand their reason for doing it, but it’s incompatible with our system. URLs with changing tokens exist to make it hard to perform automomated downloads, and are nor worth the hassle for us.

**Comment by tomgross** [comment]
OK I understand. If this is useful for someone else I created a gist for installing pCloud drive on a Mac via homebrew cask: https://gist.github.com/tomgross/bae4f30023272d8c8c0d920b62720c6b

**Comment by vitorgalvao** [comment]
Instead of a gist, consider a [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) for it.

**Pull request closed without merging**
