### PR TITLE
parallels 18.3.0-53606

### PR DESCRIPTION
**Pull request by owine**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by p-linnane — DISMISSED** [review]

**Comment by owine** [comment]
`livecheck` appears to be parsing `18.3-53606` instead of `18.3.0-53606` on https://kb.parallels.com/129060. I am no regex ninja so I am not sure how to fix.

**Comment by razvanazamfirei** [comment]
https://github.com/Homebrew/homebrew-cask/blob/7d583b7cdd06c9471423aa7ab433cf241cec38fd/Casks/parallels.rb#L13
Changing `(?:\s*|&nbsp;)` back to `&nbsp;` fixes the livecheck, but I'm sure there was a reason for the change.

**Review by razvanazamfirei — APPROVED** [review]

**Review by samford — COMMENTED** [review]
Not at all surprised that inconsistency in the content on a Parallels page is causing issues with one of the checks. The source of the problem is that the release text of the newest versions (18.2.0 and 18.3.0) contains version text like `18.3 (53606)` (instead of `18.3.0 (53606)` in the heading) and the regex matches any version on the page with a trailing number in parentheses.

This was fine when the version in the release text used the same full version but now we have to restrict matching to either the `h2` heading text or the links in the sidebar. I pushed a commit that updates the regex to restrict matching to the `h2` headings, which will fix the check.

Past that, I've also updated the `livecheck` block to address a couple issues. Namely, it should use `#regex` (and pass the regex into the `strategy` block) and the standard `page.scan` approach (i.e., we use `#scan` to match all versions unless the content only contains one version or we specifically need to match only the first version because matching more would return something other than the newest version).

**Comment by razvanazamfirei** [comment]
Thank you, @samford! I noticed the inclusion of the regex into the strategy block before in a few casks. I'll try to run through the existing ones and fix them!

**Comment by samford** [comment]
@razvanazamfirei Yes, any that only use one regex (like this) should be modified to use `#regex`, add `regex` to the `strategy` block arguments, etc. However, there are also some that use more than one regex and those should be left as-is for now.

One of my forthcoming PRs will add support for a hash argument to `#regex`, which will allow us to also update `strategy` blocks using more than one regex. It'll be a little bit before I get to that PR (I have some others ahead of it) but I figured I would give you a heads up anyway.

**Pull request merged**
