### PR TITLE
Retina DisplayMenu 0.2

### PR DESCRIPTION
**Pull request by zzamboni**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This a [vendorless app, so it does not belong in this repo](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#unofficial-vendorless-or-walled-builds). Please submit it to [caskroom/unofficial](https://github.com/caskroom/homebrew-unofficial).

**Comment by vitorgalvao** [comment]
In addition, per the [cask token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_token_reference.md), it needs to be called `rdm`, instead of `retina-display-menu`.

**Comment by zzamboni** [comment]
Thanks for the feedback. I will resubmit to unofficial.

About the name, unfortunately there is already a Cask named `rdm`, that's why I chose a different name:

```
$ brew cask info rdm
rdm: 0.7.6.8
rdm
http://redisdesktop.com
Not installed
https://github.com/caskroom/homebrew-cask/blob/master/Casks/rdm.rb
==> Contents
  rdm.app (app)
```

What do do in this case?

**Comment by vitorgalvao** [comment]
I noticed that, but since they'll exist in different repos they shouldn’t conflict (some disambiguation might be needed at install time).

The solution in these cases is to [prepend the vendor name](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#cask-token-details), which is a problem in this case, because it the newer (less known) cask doesn’t have one.

**Comment by jawshooah** [comment]
Shouldn't they? What happens if you `brew tap caskroom/unofficial && brew cask install rdm`?

**Comment by zzamboni** [comment]
@vitorgalvao I have submitted under unofficial at https://github.com/caskroom/homebrew-unofficial/pull/37

@jawshooah It seems that `brew cask install rdm` installs the cask from the main repo. To get the one from unofficial you have to explicitly specify `brew cask install caskroom/unofficial/rdm`.

**Comment by vitorgalvao** [comment]
> To get the one from unofficial you have to explicitly specify `brew cask install caskroom/unofficial/rdm`.

That is correct. One of the reasons that is such a non-issue in this case is [caskroom/unofficial](https://github.com/caskroom/homebrew-unofficial) is our “install at your own risk” repo, and in that sense we plan to make it so that you can only install from it when using its repo prefix (so you don’t install anything from it by mistake).

That functionality was briefly discussed in an issue, but now that I think about it I’m not sure we have a single issue dedicated to it. I should look.

**Pull request closed without merging**
