### PR TITLE
Update litecoin to 0.16.0

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by joernroeder** [comment]
i've experienced a shasum mismatch error and according to the release notes of their blog the given checksum is not correct. https://blog.litecoin.org/litecoin-core-v0-16-0-release-5bf9b732b069#1d66

**Comment by adidalal** [comment]
Flagging for @vitorgalvao @commitay 

It looks like the .dmg has been updated in-place.

**Comment by joernroeder** [comment]
We should check official website, gpg signature and creation date of the public key.

**Comment by joernroeder** [comment]
a download from the official site with valid gpg signature gives me `e33fab8afa3c03eabcd958f4f7c2a4fdfdaf1f65eff7a861135e19fbc68423ad` as sha 256

**Comment by vitorgalvao** [comment]
Is this supposed to be mining software? https://www.virustotal.com/#/file/e33fab8afa3c03eabcd958f4f7c2a4fdfdaf1f65eff7a861135e19fbc68423ad/detection

**Comment by joernroeder** [comment]
@vitorgalvao it's the wallet software of lightcoin. i think it includes a solo miner. @losh11 @thrasher- published/taged the release on https://github.com/litecoin-project/litecoin/releases/

**Comment by losh11** [comment]
Looks like this should've never been merged. When Core 0.16 was released macOS builds were broken (issue with codesigning). This was promptly fixed within 1-2 hours.

Here's the sha256sums for the fixed dmg & the broken dmg:
```
e33fab8afa3c03eabcd958f4f7c2a4fdfdaf1f65eff7a861135e19fbc68423ad  litecoin-0.16.0-osx.dmg
93b451d180b2c60495595df00c303de6b8e135187d0d77bd542b9df917f50286  litecoin-0.16.0-osx.dmg.old
```


Would someone mind creating a PR with `e33fab8afa3c03eabcd958f4f7c2a4fdfdaf1f65eff7a861135e19fbc68423ad` as the sha256sum?

**Comment by brianmorton** [comment]
@losh11 saying it should have never been merged is going a bit far - we have no control over devs that like to do update-in-place after they release something.

Really I think the dev should either release a new version with patch versioning (eg. 0.16.1) or HBC should allow a ~2 day window after PRs are merged to modify checksums without requiring all the rigmarole that happens now.

**Comment by brianmorton** [comment]
@joernroeder that is exactly the current HBC protocol - confirmation from the dev of the hash change.

If you want to avoid these kind of problems, just change the version if you are going to change the binary...

**Comment by vitorgalvao** [comment]
> without requiring all the rigmarole that happens now.

https://github.com/Homebrew/homebrew-cask/issues/48862

**Pull request merged**
