### PR TITLE
mooinfo

### PR DESCRIPTION
**Pull request by hjhgitw**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by hjhgitw** [comment]
again test :)

**Review by hjhgitw — COMMENTED** [review]
hope it works

**Comment by hjhgitw** [comment]
again

**Comment by hjhgitw** [comment]
again test :)

**Comment by bevanjkay** [comment]
Thanks @hjhgitw, but we cannot accept it because it does not pass our signature verification check that are a requirement for new submissions:

> macOS on ARM requires software to be signed. Please contact the upstream developer to let them know they should sign and notarize their software

**Comment by bevanjkay** [comment]
You may consider hosting this in your own tap. 

https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by hjhgitw** [comment]
Thank you so much for your valuable input!
I'm impressed by the depth of your input. Thank you for sharing your expertise.

We would try to sign it : https://blog.dgunia.de/2020/02/12/signed-macos-programs-with-java-14/

**Pull request closed without merging**
