### PR TITLE
eudic 4.6.0

### PR DESCRIPTION
**Pull request by lethefrost**
Correct the version value used in URL string interpolation to download v4.6.0. Previously, URL with v=1144 will download v4.5.9 and cause sha256 mismatch (b152c1d9998094bafcc3ec4cd042f2d0402dffe1d16ccfa529b2972a41131311 instead of b46f41ddf1a9ff18fc296c56ef7e9c949e5537e0603a2eed5b878c388ac232f2).

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
The rebase was to fix an unrelated issue with CI @lethefrost

**Review by samford — COMMENTED** [review]
The date isn't available in the appcast, so we also have to check the [download page](https://www.eudic.net/v4/en/app/download) to get that information. I pushed an updated `livecheck` block that uses this approach.

The current date on the download page seems to be 2023-12-30, so we may need to update the `version`. I would do it myself but I'm not sure if the `sha256` has changed, as it's taking a very long time to download the file (and I'm off to bed).

-----

For what it's worth, please create a new branch in your fork when opening a PR. Using the `master` branch of your fork makes things a little harder for maintainers to work with (if/when we need to push changes).

**Review by samford — COMMENTED** [review]
I wasn't ever able to get the download to complete locally (I haven't been able to connect to www.eudic.net at all today) but it seems fine on CI after updating the date in the version.

After testing this some more, it seems like the date doesn't make much of a difference, so long as it's newer than some unspecified recent date. 2023-12-29 and 2023-12-30 both return the same file (identical file size and `sha256`). The same is true if we use the `pubDate` value from the appcast (2024-01-29), at least right now.

If upstream updates the date on the download page without changing the dmg file, we may end up with useless version bumps (i.e., PRs that update the date in the `version` but the `sha256` remains the same). If that becomes a recurring issue, we can potentially use the `pubDate` value for the latest version in the appcast (since this should stay the same) but I'm not sure if that would cause issues. It's an unusual situation but unfortunately not surprising when it comes to casks.

That said, this is probably fine for now and we can always revisit this situation in the future as needed. I'll leave final review up to someone else, so this goes past another set of eyes.

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
👋 after the livecheck change in this PR, the cask version updates often resulted with no checksum change, it it desired upstream behavior or should we revert the livecheck change (to avoid multiple updates for the cask)?

- #165706 (no checksum change)
- #165725 (no checksum change)
- #165879 (no checksum change)
- #165981 (only checksum change)
- #166011 (version the same, date changed and checksum changed)
- #166201 (no checksum change)
- #166375 (no checksum change)
- #166454 (no checksum change)

**Comment by bevanjkay** [comment]
The URL provided is the in versioned `url` that we are already using. It's just a static link that always points to the whatever the latest version is. Which means that we cannot use the checksum. 

We would need a url that includes the version number, and also assurance that older versions are retained for some time.

**Comment by bevanjkay** [comment]
When the url is unversioned, if we have a checksum, every time the binary is updated by the vendor the cask will break for users due to a checksum mismatch (until an update is merged here and propagated through the Homebrew API). 

When a versioned download is available this isn't an issue, as users continue receiving the older version until Homebrew is updated.

**Comment by bevanjkay** [comment]
We will just have to leave it how it is now. Unversioned url with no checksum.

**Pull request merged**
