### PR TITLE
java 9.0.1,11

### PR DESCRIPTION
**Pull request by makigumo**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
Thanks for the PR!

**Comment by douglarek** [comment]
Java `9.0.1` brokes homebrew requirements guess:

```
→ brew info gradle
gradle: stable 4.2.1
Build system based on the Groovy language
https://www.gradle.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gradle.rb
==> Requirements
Required: java >= 1.7 ✘
==> Options
--with-all
	Installs Javadoc, examples, and source in addition to the binaries
```

**Comment by miccal** [comment]
@douglarek please report this to https://github.com/Homebrew/homebrew-core/

**Comment by commitay** [comment]
@douglarek https://github.com/Homebrew/brew/pull/3333

**Comment by douglarek** [comment]
@commitay @miccal thanks

**Pull request merged**
