### PR TITLE
osxfuse: rename to macfuse

### PR DESCRIPTION
**Pull request by miccal**
Continuation of https://github.com/Homebrew/homebrew-cask/pull/94187.

### CODE REVIEW

**Review by core-code — DISMISSED** [review]

**Comment by miccal** [comment]
@reitermarkus is this safe to merge yet, or is there still things that need to be done in `brew` and/or `homebrew-core` first?

**Comment by nehalecky** [comment]
Hi @miccal! Happy New Year! 

To support the many issues Keybase users are having (e.g., https://github.com/keybase/client/issues/24366), I was also about to open a PR to update the case to the most recent macfuse [4.0.5 version](https://github.com/osxfuse/osxfuse/releases/tag/macfuse-4.0.5), which came out a few days ago, which includes improves support for Apple silicon and macOS 11.

Can this PR be updated to point to it, or should I submit an additional one?

Also, what else is needed to move this forward (as mentioned in your comment to @reitermarkus), that the community can help out on?

Thanks much!

**Comment by reitermarkus** [comment]
> is this safe to merge yet, or is there still things that need to be done in `brew` 

I don't think anyone has opened a PR making the corresponding changes in `brew` yet.

**Comment by miccal** [comment]
Updated to `4.0.5`.

**Comment by nehalecky** [comment]
@miccal, thanks for the update!

@reitermarkus, are you familiar with the changes needed in `brew` to inform a PR there? 

Also, is it possible to keep the package name the same for now, and update in a future effort?

Thanks all. :)

**Comment by reitermarkus** [comment]
I think we will need to only add `macfuse` here and delete `osxfuse` in a separate PR.

**Pull request closed without merging**
