### PR TITLE
Update Librewolf to v95.0.1-1

### PR DESCRIPTION
**Pull request by fxbrit**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by neutric** [comment]
```
Matched Versions:
95.0.1,1,5bb6190211fa0013084409c1ae2bffcd => #<Version:0x00007fdb5b305ed8 @version="95.0.1,1,5bb6190211fa0013084409c1ae2bffcd", @detected_from_url=false>
95.0,2,7972ac43891a576a17b90753be3694a0 => #<Version:0x00007fdb5b305e60 @version="95.0,2,7972ac43891a576a17b90753be3694a0", @detected_from_url=false>
[...]
librewolf : 95.0-2,7972ac43891a576a17b90753be3694a0 ==> 95.0.1,1,5bb6190211fa0013084409c1ae2bffcd
```
`livecheck` matches the newest version as well but ends up picking the wrong one.

Fix:

```
livecheck do
  url "https://gitlab.com/api/v4/projects/13853965/releases"
  regex(%r{/(\w+)/librewolf[._-](\d+(?:\.\d+)+)-(\d+)#{arch}\.dmg}i)
  strategy :page_match do |page, regex|
    page.scan(regex).map do |match|
      "#{match[1]},#{match[2]},#{match[0]}"
    end
  end
end
```
and

```
url "https://gitlab.com/librewolf-community/browser/macos/uploads/#{version.csv.third}/librewolf-#{version.csv.first}-#{version.csv.second}#{arch}.dmg",
```

**Comment by fxbrit** [comment]
closed in favor of #116063

**Comment by neutric** [comment]
Why did you close it? The other PR is missing the same steps as yours and usually the earlier PR gets the go ahead.

**Comment by fxbrit** [comment]
@neutric my bad, I was from mobile and I didn't properly check. thanks for taking care of it in your PR btw.

**Comment by neutric** [comment]
@fxbrit No problem!

**Pull request closed without merging**
