### PR TITLE
mysql-utilities-1.6.4

### PR DESCRIPTION
**Pull request by mengesb**
### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- Addresses caskroom/homebrew-cask#24076

### CODE REVIEW

**Comment by mengesb** [comment]
Well; I thought that it was working however there seems to be an installer issue once again.

https://bugs.mysql.com/bug.php?id=82749

**Comment by adidalal** [comment]
Can you try installing the pkg manually, and see if that succeeds?

**Comment by adidalal** [comment]
Is this OK to merge, @mengesb?

**Comment by mengesb** [comment]
Sorry @adidalal ; I did try and install it manually but it didn't install manually or via the generated command line... seems there might be another issue (hence the bug i filed)

**Comment by fanquake** [comment]
Looks like the bug opened by @mengesb has been marked as a duplicate of https://bugs.mysql.com/bug.php?id=81048, which has been open since April.

**Comment by mengesb** [comment]
Yes it has... And I'm not seeing any updates unfortunately

**Comment by vitorgalvao** [comment]
Marking as an upstream issue.

**Comment by vitorgalvao** [comment]
Will remove the cask, since it has been broken upstream for a good while. If/when a fix is released, we can readd it.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/25061.

**Pull request closed without merging**
