### PR TITLE
Update and fix url vagrant to 1.9.3

### PR DESCRIPTION
**Pull request by commitay**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by AlJohri** [comment]
@miccal @commitay

I think something messed up here:

cleanup
```
Als-MacBook-Air ~ # brew cask cleanup vagrant
==> Removing cached downloads for vagrant
/Users/johria/Library/Caches/Homebrew/Cask/vagrant--1.9.3.dmg
==> This operation has freed approximately 80.1MB of disk space.
```

install
```
Als-MacBook-Air ~ # brew cask install vagrant
==> Downloading https://releases.hashicorp.com/vagrant/1.9.3/vagrant_1.9.3_x86_64.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask vagrant
==> Running installer for vagrant; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Error: pkg source file not found: '/usr/local/Caskroom/vagrant/1.9.3/Vagrant.pkg'
Error: nothing to install
```

**Comment by AlJohri** [comment]
Oh it's now `vagrant.pkg` with a lowercase "v". I'll make a pull request.

**Comment by commitay** [comment]
Works fine for me. The .pkg inside the .dmg is still lowercase.

screen shot 2017-03-23 at 05 51 37


```
$ brew cask reinstall vagrant
==> Downloading https://releases.hashicorp.com/vagrant/1.9.3/vagrant_1.9.3_x86_6
######################################################################## 100.0%
==> Verifying checksum for Cask vagrant
==> Running uninstall process for vagrant; your password may be necessary
==> Running uninstall script uninstall.tool
==> The following files and directories will be removed:
==>     /opt/vagrant
==>     /usr/local/bin/vagrant
==>
==> Do you wish to uninstall Vagrant (Yes/No)?
==> The uninstallation process requires administrative privileges
==> because some of the installed files cannot be removed by a
==> normal user. You may now be prompted for a password...
==>
==>
==> Successfully uninstalled Vagrant.
==> Done.
==> Press any key to exit.
==> Uninstalling packages:
com.vagrant.vagrant
Password:
==> Running installer for vagrant; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
==> installer: Package name is Vagrant
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  vagrant was successfully installed!
```

**Comment by AlJohri** [comment]
It changed to lowercase I think. The code on git has it has uppercase.

Get Outlook for iOS




On Wed, Mar 22, 2017 at 3:53 PM -0400, "commitay" <notifications@github.com> wrote:












Works fine for me. The .pkg inside the .dmg is still lowercase.



$ brew cask reinstall vagrant
==> Downloading https://releases.hashicorp.com/vagrant/1.9.3/vagrant_1.9.3_x86_6
######################################################################## 100.0%
==> Verifying checksum for Cask vagrant
==> Running uninstall process for vagrant; your password may be necessary
==> Running uninstall script uninstall.tool
==> The following files and directories will be removed:
==>     /opt/vagrant
==>     /usr/local/bin/vagrant
==>
==> Do you wish to uninstall Vagrant (Yes/No)?
==> The uninstallation process requires administrative privileges
==> because some of the installed files cannot be removed by a
==> normal user. You may now be prompted for a password...
==>
==>
==> Successfully uninstalled Vagrant.
==> Done.
==> Press any key to exit.
==> Uninstalling packages:
com.vagrant.vagrant
Password:
==> Running installer for vagrant; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
==> installer: Package name is Vagrant
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  vagrant was successfully installed!

**Pull request merged**
