### PR TITLE
Update output-factory from 2.4.56 to 2.4.60

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Looks like the audit needs to be fixed here, as it probably shouldn't be failing casks that have no `livecheck`.

**Comment by carlocab** [comment]
@reitermarkus should the cask `audit` possibly return instead of fail here when `latest_version` is an empty string?

I suppose another solution here would be for `version` to just be `:latest`, but then users don't get the benefit of updates when someone else is kind enough to update the version here.

**Comment by SMillerDev** [comment]
I think `:latest` is more accurate though since it's an unversioned download.

**Comment by SMillerDev** [comment]
Otherwise https://zevrix.com/download/ has the version information

**Comment by carlocab** [comment]
Ah, here's what I think you need to do to fix the audit error, @bevanjkay:

https://github.com/Homebrew/homebrew-cask/blob/44d719b77c38ebd8f2d7928f924330d3f0be333e/Casks/spotify.rb#L11-L13

**Comment by reitermarkus** [comment]
It should actually fail for all casks, until all have a `livecheck`. If we can absolutely not find an appcast, we can use `skip`.

**Comment by reitermarkus** [comment]
Also, an explicit `version` is always preferred over `:latest`, as long as there is a working `livecheck`.

**Review by reitermarkus — APPROVED** [review]

**Pull request merged**
