### PR TITLE
update upic from v0.21.0 to v0.21.1

### PR DESCRIPTION
**Pull request by gee1k**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Comment by core-code** [comment]
>  binary "#{appdir}/uPic.app/Contents/MacOS/uPic", target: "upic"

why was this removed?

**Comment by gee1k** [comment]
Tested must be executed through the full path to run properly, no solution has been found yet, so first remove the

**Comment by miccal** [comment]
> Tested must be executed through the full path to run properly, no solution has been found yet, so first remove the

Please elaborate -- what is the error you are experiencing?

**Comment by reitermarkus** [comment]
> must be executed through the full path to run properly

This is a common problem. Add a shim script instead.

**Comment by gee1k** [comment]
> > must be executed through the full path to run properly
> 
> This is a common problem. Add a shim script instead.

What is the shim script you are talking about?

could u show me an example?

**Comment by gee1k** [comment]
Is it possible to add a script that calls the app via an absolute path and then link to that script?

**Comment by gee1k** [comment]
Like this?

image

**Comment by gee1k** [comment]
Thanks for the reminder, I've solved the problem using shims script in the new PR #95315

**Pull request closed without merging**
