### PR TITLE
Add command-line launcher to JetBrains IDEs

### PR DESCRIPTION
**Pull request by moonfruit**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

---

The Jetbrains IDEs now use their binary executables as command line launchers instead of the bash scripts created by the IDE. So we just need to create a binary link to these executables. And remove the outdated cleaning codes from the cask.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Does this create any conflicts with the JetBrains Toolbox configuration?

image

**Comment by moonfruit** [comment]
Jetbrains Toolsbox now creates scripts in the directory `~/Library/Application Support/JetBrains/Toolbox/scripts` by default. So there's generally no conflict. The generated script looks like this. So the original code that cleaned up the script will no longer work.

```bash
#!/bin/bash
#Generated by JetBrains Toolbox 2.1.3.18901 at 2024-01-09T09:22:09.568921

declare -a intellij_args=()
declare -- wait=""

for o in "$@"; do
  if [[ "$o" = "--wait" || "$o" = "-w" ]]; then
    wait="-W"
    o="--wait"
  fi
  if [[ "$o" =~ " " ]]; then
    intellij_args+=("\"$o\"")
  else
    intellij_args+=("$o")
  fi
done

open -na "/Applications/IntelliJ IDEA.app/Contents/MacOS/idea" $wait --args "${intellij_args[@]}"%
```

**Comment by miccal** [comment]
@moonfruit please remove the changes made to `android-studio`, thank you.

**Comment by moonfruit** [comment]
Android Studio can also use command line launcher. Why should it revert?

**Comment by miccal** [comment]
> Android Studio can also use command line launcher. Why should it revert?

So that this PR can be focused on just the JetBrains Casks. Please submit a separate PR for `android-studio`, thank you.

**Comment by moonfruit** [comment]
OK, I move `android-studio` to another pr #164128.

**Comment by miccal** [comment]
Thank you @moonfruit.

**Review by miccal — APPROVED** [review]

**Pull request merged**
