### PR TITLE
Remove borgbackup Cask (moved to homebrew-core)

### PR DESCRIPTION
**Pull request by m3nu**
Due to [issues](https://github.com/borgbackup/borg/issues/5185) with pre-built Borg binaries, we are moving Borg Backup to a [Python-based Homebrew formula](https://github.com/Homebrew/homebrew-core/pull/59717). To avoid confusion, the Cask formula with the same name should be removed.

Hope removing the formula here is the correct process.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Please also add this to `tap_migrations.json`.

**Comment by m3nu** [comment]
Added to `tap_migrations.json`.

- Old Cask formula: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/borgbackup.rb
- New Core formula: https://github.com/Homebrew/homebrew-core/pull/59717

**Comment by m3nu** [comment]
New formula was already [merged](https://github.com/Homebrew/homebrew-core/pull/59717).

**Comment by reitermarkus** [comment]
Thanks, @m3nu!

**Pull request merged**
