### PR TITLE
Update switchresx from 4.12.1 to 4.12.2

### PR DESCRIPTION
**Pull request by i0ntempest**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by i0ntempest** [comment]
bump

**Comment by VikalpRusia** [comment]
as per the site - https://www.madrau.com/srx_download/download.html
latest release is 4.12.1
Screenshot 2022-10-31 at 1 10 45 AM

**Comment by i0ntempest** [comment]
But 4.12.2 is downloadable and is not a beta

**Comment by VikalpRusia** [comment]
It's in beta please check- https://www.madrau.com/srx_download/srx_download/srx_beta.html

**Comment by i0ntempest** [comment]
image
No, the one in beta is not the same with the stable 4.12.2

**Comment by i0ntempest** [comment]
bump

**Comment by p-linnane** [comment]
Please reach out to to the developer about updating their site. Once `livecheck` can grab the new version we can bump this.

**Pull request closed without merging**
