### PR TITLE
Update qt-creator version to 4.5.0

### PR DESCRIPTION
**Pull request by sp-1234**
√    `brew cask audit --download {{cask_file}}` is error-free.
√    `brew cask style --fix {{cask_file}}` left no offenses.
√    The commit message includes the cask’s name and version.

Update qt-creator version to 4.5.0 and use https for downloading

Version and hash taken from https://download.qt.io/official_releases/qtcreator/4.5/4.5.0/qt-creator-opensource-mac-x86_64-4.5.0.dmg.mirrorlist
HTTPS link checked and it works

P.S.: I don't know why but Github didn't insert the template message here and I don't know how to do these square checkbox thing, I hope it's readable enough like it is.

### CODE REVIEW

**Comment by commitay** [comment]
> HTTPS link checked and it works

It downgrades to HTTP

**Comment by sp-1234** [comment]
Well it may stop doing that in the future. And from my address it redirected to another `https` url, so maybe it depends.

**Comment by sp-1234** [comment]
kind of funny that the tool doesn't agree with that
>  - The URL http://download.qt.io/official_releases/qtcreator/4.5/4.5.0/qt-creator-opensource-mac-x86_64-4.5.0.dmg should use HTTPS rather than HTTP

from Travis log at https://travis-ci.org/caskroom/homebrew-cask/builds/313411266

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/issues/41735

**Comment by vitorgalvao** [comment]
> Well it may stop doing that in the future.

We don’t typically make changes to casks based on conjecture.

It’s important to us to not have HTTPS URLs that redirect to HTTP because it gives users a false sense of security.

**Comment by sp-1234** [comment]
@victorpopkov as long as redirects are allowed, **all** HTTPS URLs are false sense of security. Because the host may start behaving differently at any moment, especially if it uses redirecting to serve from mirrors and they can be configured very differently.

Until there's no option to automatically and surely forbid redirects to plaintext connections or forbid  installation of formulas without sha256, I don't see how it makes any significant difference. And last time I checked these 2 things were true.

**Comment by vitorgalvao** [comment]
> as long as https->http redirects are allowed, **all** HTTPS URLs are false sense of security.

Which is why they aren’t. Those casks now should fail audit, which is the whole point.

> Until there's no option to (…) forbid installation of formulas without sha256

There is. It’s [`--require-sha`](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options).

This is not a discussion. All the points you mentioned have already been extensively discussed and decided upon in the past. They’re either implemented or on the list. We’re not arguing with you about what the best method is — we’re telling you what we already concluded.

If you want to add to those decisions, you’ll need to research the old issues and the documentation and make your arguments based on that. Respectfully, we don’t want to start to explain everything from scratch.

---

Two extra small notes:

+ You @mentioned the wrong person. It’s a common mistake, don’t worry about it. But I have missed points made to me in the past due to it.
+ We call them “casks”, not “formulas”. They are different things and behave differently. They do not share features.

**Review by commitay — APPROVED** [review]
Verified locally. Disregarding the new `audit` false positive.

**Pull request merged**
