### PR TITLE
Added scroll, renamed hookshot to rectangle-pro, and updated middle to 1.6.6

### PR DESCRIPTION
**Pull request by Aaron-Rumpler**
Also includes miscellaneous improvements for `rectangle`, `rectangle-pro`, `multitouch`, `middle`, `hightop`, and `hyperkey`.

Livecheck for `hyperkey` is only returning the short version (i.e. `0.11`) instead of both the short version and version (i.e. `0.11,11`), whereas the other casks return both. Is this due to the version matching the short version's minor version number?

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by neutric** [comment]
Can you please at least separate the rename and the addition of a cask into their own pull requests? The remaining ones ideally also get their own pull request unless what you change is related somehow.

**Comment by Aaron-Rumpler** [comment]
The relation is that they're all from the same developer. Should I still separate out the changes to `hightop`, `hyperkey`, `multitouch` and `rectangle` into separate PRs?

**Comment by Aaron-Rumpler** [comment]
`middle`: #117446
`scroll`: #117447
`rectangle-pro`: #117448

**Comment by neutric** [comment]
> The relation is that they're all from the same developer. Should I still separate out the changes to `hightop`, `hyperkey`, `multitouch` and `rectangle` into separate PRs?

That'd be nice. With related I mean something like https://github.com/Homebrew/homebrew-cask/pull/117256. Being from the same developer does not qualify in this case. In other cases, it would, e.g. if multiple casks needed a change of `url` scheme because they all are on the same domain and that domain changed.

**Pull request closed without merging**
