### PR TITLE
Update Cocktail to version 9.1 for El Capitan

### PR DESCRIPTION
**Pull request by phillipmcmahon**

### CODE REVIEW

**Comment by fanquake** [comment]
Please include the name of the cask in the commit message.

**Comment by phillipmcmahon** [comment]
thanks for the amendment.

**Comment by fanquake** [comment]
@phillipmcmahon You'll still need to change the actual commit message, that is only the name of the Pull Request.

**Comment by phillipmcmahon** [comment]
@fanquake can i do that in the commit comments? i see no way in the web gui to amend the title. apologies.

**Comment by fanquake** [comment]
@phillipmcmahon Ok. It can be fixed during merge by a maintainer.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 98ae38a914cbc3b8a8eda8339d839bb7dde21308. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
