### PR TITLE
macvim 7.4.97

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Updating the `:checkpoint` value in `appcast` is required. You can find it with `curl --silent --compressed "{{appcast_url}}" | sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256 | awk '{ print $1 }'`.

Alternatively, you may wish to use [`cask-repair`](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair). It can at once update the cask’s version (according to what you give it) taking care of updating both the cask’s `sha256` and the appcast’s `:checkpoint`, while still giving you the chance to perform other manual fixes.

You can easily install it with `brew install vitorgalvao/tiny-scripts/cask-repair`. `cask-repair --help` will show you some options, but as a whole the script will guide you through the update process.

**Comment by sjackman** [comment]
I've updated the `appcast` SHA. The `sed` didn't seem to be necessary in this case as the `atom` file didn't contain the string `pubDate`. I used:
```sh
curl https://github.com/macvim-dev/macvim/releases.atom |gsha256sum
bcc7df81b062d308bfa87c8b13b89c618ab02c9af288bbaa3382a2a6e71a1628
```

**Comment by sjackman** [comment]
What is the purpose of the `appcast`?

**Comment by vitorgalvao** [comment]
>  The `sed` didn't seem to be necessary in this case as the `atom` file didn't contain the string `pubDate`.

It isn’t, but that command covers all cases.

> What is the purpose of the `appcast`?

It’s used by maintainers (we’re ramping up usage) to quickly gather which casks are out of date. It gives us a more consistent way to update casks.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 258f361d1f112aaf70de8056a0101c8c192b00af to keep commit history cleaner. Your contribution is still credited to you.

**Comment by sjackman** [comment]
Thanks, Vítor.

**Pull request closed without merging**
