### PR TITLE
Add Millie v2.14

### PR DESCRIPTION
**Pull request by ghost**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Thank you for your contribution to `homebrew-cask` @leejongyoung .

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by leejongyoung** [comment]
Okay, I'll read the guide and post it again. 👍🏻

**Comment by bevanjkay** [comment]
@leejongyoung  [please enable the checkbox](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) that allows edits from maintainers.

**Comment by leejongyoung** [comment]
Screen Shot 2021-07-13 at 11 03 17 AM

it's already checked

**Comment by bevanjkay** [comment]
@leejongyoung Sorry, I think the Git workflow broke because the PR was opened from the master branch in your fork. Can you try to open a PR from a branch instead?

**Comment by leejongyoung** [comment]
@bevanjkay
yeah i understand what you mean
I'll let you do that

**Pull request closed without merging**
