### PR TITLE
Update dash to 4.0.2

### PR DESCRIPTION
**Pull request by Saklad5**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/30511

**Comment by Saklad5** [comment]
Would it be possible for the `cask-repair` script to check for identical pull requests before submitting?

**Comment by vitorgalvao** [comment]
> Would it be possible for the `cask-repair` script to check for identical pull requests before submitting?

Yes. However, having done similar things in other scripts (also for HBC), it is not worth it. Requires more network requests, makes everything slower, and isn’t foolproof. Considering repetition isn’t a constant problem, there’s no point to it.

**Comment by Saklad5** [comment]
Understood.

**Pull request closed without merging**
