### PR TITLE
Update surge from 4.2.3 to 4.2.4

### PR DESCRIPTION
**Pull request by FnControlOption**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@samford Can you please check this livecheck also? In my mind this change adds more failure points, however I'm interested in your thoughts.

**Review by samford — COMMENTED** [review]
I'm not an expert when it comes to casks but is there a purpose behind the `version` changes (e.g., standardizing the `version` format across casks), considering the original `version` string (from the appcast) was used in the `url` without modification?

Simply from glancing at other casks, it seems like `version` delimiters (comma(s)/colon) are commonly used when it's necessary to separate the `version` parts while interpolating them into the `url` (e.g., `#{version.after_comma.before_colon}`, etc.) but that isn't the case here.

I'll defer to the cask maintainers when it comes to the appropriateness of the `version` change and we can update the `livecheck` block once that's settled.

---

Regarding the `livecheck` block, the regex could use some changes either way.

If we don't modify the version to use commas, I would suggest `/Surge[._-](\d+(?:\.\d+)+.*?)\.zip/i`, which is looser about the version format and would accommodate certain changes without breaking. The explicitness of the existing regex doesn't benefit us in this particular context (i.e., a URL string) if we don't need to separate the parts of the version using capture groups.

If we do modify the version, I would suggest `/Surge[._-](\d+(?:\.\d+)+)[._-](\d+)[._-]([0-9a-f]+)\.zip/i`. Though Ruby regexes support `\h` for hex values, it's unique to Ruby and `\h` matches horizontal whitespace in other engines. I generally opt for `[0-9a-f]+` [in a case-insensitive regex], as it may help to make the regexes more comprehensible to folks who don't have a strong Ruby background while also potentially allowing them to be somewhat portable outside of Ruby (e.g., if anyone ever uses `livecheck` block data in a different context).

Both suggestions use `Surge[._-]` before the leading numeric version, to bring it more in line with common regex patterns for matching the version from a filename.

**Comment by FnControlOption** [comment]
> I'm not an expert when it comes to casks but is there a purpose behind the `version` changes (e.g., standardizing the `version` format across casks), considering the original `version` string (from the appcast) was used in the `url` without modification?

Using commas allows `bump-cask-pr` to shorten the commit message, in this case from: 

```
Update surge from 4.2.3-1357-0803594c82248360a95722089650f7f7 to 4.2.4-1399-4f3c53abfe45fce5646d84af11e589c4
```

to `Update surge from 4.2.3 to 4.2.4` (This feature was added in https://github.com/Homebrew/brew/pull/12404)

There are cases where a cask's version string includes a hyphen before a comma, so shortening hyphenated version strings on the fly would be more complex than just updating applicable casks to use commas. However, I agree that this makes livecheck blocks and `#{version}` interpolation more complex than if we kept the hyphens.

**Comment by samford** [comment]
Thanks for the explanation. I can get behind the idea of modifying the `version`, as I agree that the hyphenated version is quite lengthy and it would also bring a small number of outliers in line with how most `version`s are handled. The `livecheck` block would simply use an already-established `strategy` block pattern for versions that include multiple parts separated by delimiters, so this isn't a problem from that perspective.

My main concern is the multiple-comma `version` format in this PR. From what I'm seeing, there appear to only be three casks at the moment that use multiple commas in the `version`, whereas there are a larger number (48) that use a comma for the first delimiter and a colon for the second. There's maybe something to be said for converting some of the casks with multiple commas (`aptible`, `connectiq`) to the comma-colon format (e.g., `1.2.3,456,78` to `1.2.3,456:78`) and updating the related open PRs, for the sake of better standardization.

The sole outlier appears to be `xiami`, which uses multiple commas and a colon (`7.5.8,7058,30b52410ba8955c21df3c3555fa75f6c:a916a2565fc172a83bc0106f1f4c23d5`). It seems inevitable that there's going to be a `version` with more than three parts and this `version` was introduced by a maintainer, so we could just leave that one alone and aim for 99.97% compliance, ahah.

That said, I'll defer to the cask maintainers about whether this is the appropriate course of action, as I'm not familiar with cask norms. Once that's settled, I'll add a proper suggestion in the `livecheck` block.

**Comment by cho-m** [comment]
> My main concern is the multiple-comma `version` format in this PR. From what I'm seeing, there appear to only be three casks at the moment that use multiple commas in the `version`, whereas there are a larger number (48) that use a comma for the first delimiter and a colon for the second.

The comma-colon `version` is the original approach for 3-parts and is currently recommended in documentation https://docs.brew.sh/Cask-Cookbook#version-methods (last paragraph).

#95207 plans to remove this in favor of multiple-comma `version`; however, the migration depends on some brew changes to avoid the confusing combinations of `.before_comma` & `.after_comma`.

This seems to have caused some inconsistency in version format. It may be easier to keep using comma-colon until the necessary infra is available to support `.csv[i]` syntax.

---

No real stance here on whether this is better or worse.

I guess some advantages are:
- commas & colons are properly understood by Homebrew to be delimiters and it is able to properly sort & detect updates. I think I saw hyphens cause lexical sorting to think the livechecked version was a downgrade and not show up if using `--newer-only`.
- it is more in-line with other Sparkle versioning. Ignoring the 3rd part with some hash (commit?), the first 2 parts is how default Sparkle would appear (`4.2.4,1399`).

Disadvantage is obviously the extra logic required that may break in future.

**Pull request merged**
