### PR TITLE
Update go-agent from 19.1.0-8469 to 19.6.0-9515

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
`.app` no longer available

**Comment by core-code** [comment]
i am not sure if this a reason to drop this update. can you re-open this and the corresponding go-server PR? i think @vitorgalvao should decide how we want to proceed with these casks.

**Comment by ran-dall** [comment]
> i am not sure if this a reason to drop this update. can you re-open this and the corresponding go-server PR? i think @vitorgalvao should decide how we want to proceed with these casks.

@core-code I closed it because I think it would be a better fit for HB as opposed to HBC at this point. I really hate to open these with 32 PRs outstanding, but I'll do it just for you. 😉

**Comment by core-code** [comment]
thanks! if its a problem just let me know and i'll open a similar PR. 

i agree it might be a better fit for HB now. lets see what the maintainers think.

**Comment by vitorgalvao** [comment]
Is this now a CLI-only open-source tool that can be built from source and doesn’t depend on signed binaries? If so, HB.

**Comment by ran-dall** [comment]
> thanks! if its a problem just let me know and i'll open a similar PR.

I didn't mean it like that. I meant to point out that I hated the feeling of further clogging the PR log, not that it matters. lol.

> Is this now a CLI-only open-source tool that can be built from source and doesn’t depend on signed binaries? If so, HB.

I don't think it requires to be built but I do believe it's a CLI-only tool. https://docs.gocd.org/current/installation/install/agent/osx.html

**Comment by vitorgalvao** [comment]
> I don't think it requires

Not *require*, but *can* it be done easily? Otherwise it won’t fit in HB. I suggest you still make the HB PR, and we’ll continue from there.

**Comment by ran-dall** [comment]
> Not require, but can it be done easily? Otherwise it won’t fit in HB. I suggest you still make the HB PR, and we’ll continue from there.

You got it!

**Pull request closed without merging**
