### PR TITLE
Add Balena Etcher builds for Apple Silicon

### PR DESCRIPTION
**Pull request by nilsstreedain**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ x] `brew audit --cask <cask>` is error-free.
- [ x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@nilsstreedain Thank you for your submissions but we should not be distributing a community build to users expecting to receive the application from the actual authors.

**Comment by nilsstreedain** [comment]
> @nilsstreedain Thank you for your submission but we should not be distributing a community build to users expecting to receive the application from the actual authors.

This is built using the codebase of BalenaEtcher (just recompiled for Apple Silicon) which is written to support Apple Silicon and is specifically referenced by BalenaEtcher maintainers in [balena/etcher#3595](https://github.com/balena-io/etcher/issues/3593). They went this route because they do not currently have an Apple Silicon Mac in their build pipeline.

**Comment by bevanjkay** [comment]
@nilsstreedain I do understand that, but `homebrew-cask` should not be distributing a community build in a cask where a user would be expecting to receive the vendor build.


See this note from upstream's issue: https://github.com/balena-io/etcher/issues/3714

>     Note: These versions are not built, maintained, or supervised by balena, so proceed with caution.

**Comment by nilsstreedain** [comment]
It has been pointed to by Balena maintainers as what to use while they determine how to move forward with their build structure but I understand. Would it be reasonable for me to create a separate balenaetcher-community cask in the meantime?

**Pull request closed without merging**
