### PR TITLE
Update managenameext to 1.6.5

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
this is a SHA only change but the checksum matches what the developer states:

http://tom.25.free.fr/prg/SHA-256_Checksum/ManageNameExt_c-cs.txt

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
We can’t trust that checksum because a malicious third-party might have changed that as well. That’s why we still require developer confirmation.

**Comment by core-code** [comment]
i've sent an e-mail to the developer

**Comment by core-code** [comment]
i've already got a response from the developer stating the change is legit. but AFAIK the confirmation needs to be public. so should i
• either ask him to confirm it here on this thread or
• since he also said he replaces files all the time for minor changes without bumping the version number, shouldn't be just convert the cask to no-SHA?

**Comment by vitorgalvao** [comment]
You’ve shown yourself to be trustworthy and this is an `app` (meaning quarantine will remove the need for verifications), so post a screenshot of the email (for other users) and we’re good.

Pinging @Homebrew/cask in case anyone disagrees with the decision. Feel free to email me in private if you prefer. If a single maintainer disagrees, I’ll revert the decision and there’s no need to share who the maintainer is.

**Comment by core-code** [comment]
thanks attached is a screenshot of the e-mail including headers

screen shot 2018-10-03 at 15 49 36

**Pull request merged**
