### PR TITLE
Update forticlient-vpn from 6.4 to 7.0.0.22

### PR DESCRIPTION
**Pull request by StormPooper**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by StormPooper** [comment]
Thanks @SMillerDev, added.

**Comment by StormPooper** [comment]
Annoyingly it is failing the audit on CI but passing locally. Any suggestions for tweaks to the livecheck are welcome.

**Comment by cho-m** [comment]
The CI audit is run with `--online` flag that compares with livecheck output.

The issue with `livecheck` is that you don't have a capture group, i.e. `(...)` section

Personally, I think it might be easier to do a header match, e.g.
```rb
livecheck do
  url "https://links.fortinet.com/forticlient/mac/vpnagent"
  strategy :header_match
end
```

Header match will detect the redirect in `location: https://filestore.fortinet.com/forticlient/downloads/FortiClientVPN_7.0.0.22_OnlineInstaller.dmg` and try to detect the version number using common patterns. In this case, it works as is without any special regex pattern.

**Comment by StormPooper** [comment]
Appreciate the feedback, @cho-m. The header match made more sense so I went with it, but appreciate the clarification on the regex, since the `livecheck` and `audit` had passed locally I'd assumed it didn't need a capture group.

**Review by cho-m — APPROVED** [review]

**Pull request merged**
