### PR TITLE
Update podman from 2.0.2 to 2.0.3

### PR DESCRIPTION
**Pull request by crunchtime-ali**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by miccal** [comment]
It looks like this version has removed the `#{staged_path}/containers.conf` file.

**Comment by crunchtime-ali** [comment]
> It looks like this version has removed the `#{staged_path}/containers.conf` file.

I couldn't find anything pointing to it in the release notes. I simply removed the line :D

**Comment by miccal** [comment]
Please also remove the line `FileUtils.mkdir_p "#{ENV['HOME']}/.config/containers"`, thanks.

**Comment by crunchtime-ali** [comment]
> Please also remove the line `FileUtils.mkdir_p "#{ENV['HOME']}/.config/containers"`, thanks.

Done

**Pull request merged**
