### PR TITLE
Oracle sqlcl

### PR DESCRIPTION
**Pull request by krisrice**
Oracle SQLcl is the modern command-line interface to the Oracle database.

The initial addition of this cask will be updated quarterly with new releases.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask sqlcl` is error-free.
- [x] `brew style --fix sqlcl` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask sqlcl` worked successfully.
- [x] `brew install --cask sqlcl` worked successfully.
- [ x `brew uninstall --cask sqlcl` worked successfully.

### CODE REVIEW

**Review by gdams — DISMISSED** [review]

**Comment by krisrice** [comment]
> ```
> To use sqlcl, you may need to add the /usr/local/Caskroom/sqlcl/21.3.1.281.1748/sqlcl/bin directory
> to your PATH environment variable, e.g. (for Bash shell):
>   export PATH=/usr/local/Caskroom/sqlcl/21.3.1.281.1748/sqlcl/bin:"$PATH"
> ```
> 
> Is there no better way to install this?

I tried the binary option for /usr/local/bin/sql but got an error that already exists. So I did this route to modify the path as our binary is named 'sql' . Open to other ideas

**Comment by bevanjkay** [comment]
> > ```
> > To use sqlcl, you may need to add the /usr/local/Caskroom/sqlcl/21.3.1.281.1748/sqlcl/bin directory
> > to your PATH environment variable, e.g. (for Bash shell):
> >   export PATH=/usr/local/Caskroom/sqlcl/21.3.1.281.1748/sqlcl/bin:"$PATH"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is there no better way to install this?
> 
> I tried the binary option for /usr/local/bin/sql but got an error that already exists. So I did this route to modify the path as our binary is named 'sql' . Open to other ideas

We could use the `target` parameter on `binary` to rename to `sqlcl`?

**Comment by miccal** [comment]
Screen Shot 2021-10-20 at 08 56 34
Screen Shot 2021-10-20 at 08 56 52

**Comment by krisrice** [comment]
@miccal yeah it figures it all out relative from there

**Review by miccal — DISMISSED** [review]

**Comment by arnetkachev** [comment]
> `/usr/local/Caskroom/`
@krisrice @miccal 
1. Caskroom paths may differ in different os. We may use `#{staged_path}/sqlcl/bin/sql` here.
2. It seems `binary "#{staged_path}/sqlcl/bin/sql"` works fine for me (i can launch console after install via command `sql`)

**Review by krisrice — COMMENTED** [review]
thanks

**Review by miccal — APPROVED** [review]

**Pull request merged**
