### PR TITLE
coconutbattery 3.7.1: fix checksum

### LINKED ISSUE #53558: Checksum for Cask 'coconutbattery' does not match (once again)
The checksum for `coconutbattery` has changed once again ([1](https://github.com/Homebrew/homebrew-cask/issues/29938), [2](https://github.com/Homebrew/homebrew-cask/issues/52377)).
Should we simply ignore this and update the checksum? This is the third time now that a version was released multiple times under the same version number.

```
==> Satisfying dependencies
==> Downloading https://www.coconut-flavour.com/downloads/coconutBattery_3.7.1.zip
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'coconutbattery'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
Error: Checksum for Cask 'coconutbattery' does not match.

Expected: cfa524513346d6a0ea096a39b3dd3955df4a04af65bbb191d3989b17e81f8bf8
Actual:   1be9b3052b730521a5fe242c59cc0b9c26494e442c5f0a1c6d8c78b0945f30a2
```

### PR DESCRIPTION
**Pull request by leonklingele**
Fixes #53558.

### CODE REVIEW

**Comment by leonklingele** [comment]
VirusTotal scan: https://www.virustotal.com/#/url/fc639f7caac2b57342fbda22e6b57c46693173e0a8c2ff346df33567c39ca38c/detection

**Comment by leonklingele** [comment]
They provide a SHA256 hash of the file which matches the one of this PR.

**Comment by vitorgalvao** [comment]
That is not sufficient. If an attacker could change the file on a server, changing a string on a webpage would be even easier.

**Comment by leonklingele** [comment]
Don't understand the problem, but there you go: https://www.virustotal.com/#/file/1be9b3052b730521a5fe242c59cc0b9c26494e442c5f0a1c6d8c78b0945f30a2/detection

**Comment by vitorgalvao** [comment]
The problem is that shasums are insufficient to discard tampering. An attacker that has server access and can change a downloadable resource can also change whatever shasum is posted to match the one of their infected download.

**Comment by leonklingele** [comment]
I was referring to VirusTotal showing the SHAsum of the file, not the developer website, of course.
bildschirmfoto 2018-10-13 um 17 30 38

**Comment by vitorgalvao** [comment]
@leonklingele Because what we care about is the signing info, and when you give VirusTotal a URL (instead of uploading) it doesn’t show it.

**Pull request merged**
