### PR TITLE
Update nvidia-geforce-now from 2.0.8.85,3AB74C to 2.0.10.71,350E76

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
we would basically need a way to insert the previous cask version into the appcast.

**Comment by vitorgalvao** [comment]
We don’t need the previous version, only the current one. While there isn’t a new one, the result of the appcast is `[]`.

**Comment by core-code** [comment]
> We don’t need the previous version, only the current one. 
> While there isn’t a new one, the result of the appcast is [].

isn't that the point? if we insert the current one the result is [] (no update) which makes the CI check fail. and if we add configuration: no_check, *anything* will pass....

hmmmm maybe if we add 'configuration: "[]" it will look for the expected result (no update) and this is exactly what we need? ;)

**Comment by core-code** [comment]
it was meant more as a joke than as a serious suggestion, but if it works, cool
;)

**Pull request merged**
