### PR TITLE
Add UJAM Finisher series

### PR DESCRIPTION
**Pull request by aaronk6**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @aaronk6 -- please submit these as three separate PR's to the [`homebrew-cask-drivers`](https://github.com/Homebrew/homebrew-cask-drivers) repository, thanks.

**Comment by aaronk6** [comment]
Hi @miccal! Thanks for the quick response. Happy to submit them as separate PRs. Can you explain why they should go in to homebrew-cask-drivers? I submitted Finisher FLUXX recently and it was merged into the main repo (see https://github.com/Homebrew/homebrew-cask/pull/100986), so I’m wondering what’s the difference here.

**Comment by miccal** [comment]
Oh, I may have made a mistake here -- are these stand-alone `app`'s or do they require a hardware peripheral to function?

**Comment by aaronk6** [comment]
@miccal, no worries! These are VST/AU audio effect plugins that don’t require any hardware peripheral to function. However, strictly speaking, they aren’t stand-alone apps either because they need a software host to run in (such as Logic, Ableton Live, Cubase, etc.) But they’re definitely not drivers, and there are also other VST plugins in the main repo. Hope that clarifies it 😊

**Pull request closed without merging**
