### PR TITLE
Updated HackHands to 1.4.11

### PR DESCRIPTION
**Pull request by sergiopvilar**

### CODE REVIEW

**Comment by sergiovilar** [comment]
I'm triyng to automate these PRs via Hub, please let me know if I need to improve or fix anything.
Thanks!

**Comment by Ngrd** [comment]
Thank you for your contribution. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by sergiovilar** [comment]
@Ngrd Done!

**Comment by Ngrd** [comment]
Thank you for the contribution. It was merged directly as 56c5c0bcabd0e63efd4cc7f428d7e7a848e16026 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by sergiovilar** [comment]
@Ngrd thank you.

**Pull request closed without merging**
