### PR TITLE
Update rwts-pdfwriter from 2.0 to 2.0.3

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Install hangs forever. I've opened an issue upstream: https://github.com/rodyager/RWTS-PDFwriter/issues/26.

**Comment by p-linnane** [comment]
There's a utility that pops up at install you need to interact with, so setting this to a manual install.

**Comment by bevanjkay** [comment]
@p-linnane It looks like the issue will be resolved with the next update?

**Comment by p-linnane** [comment]
v2.0.3 is the next update. The behavior is the same.

**Review by miccal — APPROVED** [review]

**Pull request merged**
