### PR TITLE
ilspy: add arm version

### PR DESCRIPTION
**Pull request by benediktwerner**

### CODE REVIEW

**Comment by benediktwerner** [comment]
The `/usr/bin/xattr -rd com.apple.quarantine /Applications/ILSpy.app` call is required for some reason, otherwise MacOS reports the app as broken and suggests moving it to the trash: https://github.com/icsharpcode/AvaloniaILSpy/issues/63

The `chmod` suggested in the issue wasn't necessary for me though.

**Comment by bevanjkay** [comment]
@benediktwerner We do not support the removal of the quarantine attributes. In fact, we have gone to great lengths to support it as it is a valuable security feature. 

If the application is not functional without we may need to reject the addition of the cask at this stage.

**Comment by benediktwerner** [comment]
Hm, I see, I removed that part again but it's definitely not functional without it. I realized later, that there is a `--no-quarantine` flag which also makes it work. Is that fine or does it need to work without that?

**Comment by SMillerDev** [comment]
If it doesn't work without it it means the app is not properly signed and will cause issues on ARM.

**Review by miccal — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @benediktwerner.

**Pull request merged**
