### PR TITLE
Update nextcloud from 3.3.6 to 3.4.0

### PR DESCRIPTION
**Pull request by tiiiecherle**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by papodaca** [comment]
@tiiiecherle @bevanjkay  Perhaps this was merged prematurely or this release was removed? Getting 404 on that current release from the nextcloud project.

**Comment by Topslakr** [comment]
Agree. 3.4.0 is not yet out. It's still an RC.

The previous 3.3.6 version was correct. This should be rolled back, if possible, until the new client is released.

**Comment by bevanjkay** [comment]
@papodaca @Topslakr The release would have been removed upstream, as CI would not have passed unless `3.4.0` was marked as the latest stable version upstream.

**Comment by Topslakr** [comment]
Thanks @bevanjkay. I had no reason to doubt you, but was curious. They did indeed pull the 3.4.0 update 5 days ago. Appears to have been re-syncing all files.

Thanks for getting the process for rolling this back going.

**Comment by Topslakr** [comment]
Thanks @bevanjkay! All set. I was just able to install 3.3.6 on my Mac.

**Pull request merged**
