### PR TITLE
migrate wine-devel to cask/versions

### PR DESCRIPTION
**Pull request by yurikoles**
https://github.com/caskroom/homebrew-versions/pull/3567

### CODE REVIEW

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/30079

**Comment by vitorgalvao** [comment]
Can’t reopen, for some reason. Mind resubmitting?

**Comment by vitorgalvao** [comment]
Ah, I see you already did. Thank you.

**Comment by yurikoles** [comment]
@vitorgalvao #31775

**Pull request closed without merging**
