### PR TITLE
Treat --version like a positional argument in subcommand

### LINKED ISSUE #16265: Can optparse handle --verSIONs?
This is a weird one, but I think the issue is with `OptionParser` in [/lib/hbc/cli.rb#L149](https://github.com/caskroom/homebrew-cask/blob/71e3cdd201d59f5c4b82b42d7b7cba571bdf4f07/lib/hbc/cli.rb#L149).  Basically (`list` is just an example, every command behaves the same way):
````shell
$ brew cask list --v
Error: There is more than one possible option that starts with '--v' (expected output)

$ brew cask list --ve
$ brew cask list --ver
(list of casks, many columns) (expected output)

$ brew cask list --vers
$ brew cask list --versi
$ brew cask list --versio
$ brew cask list --version
brew Version (unexpected output)

$ brew cask list --versions
(list of casks, one column, with versions) (expected output)
````

AFAICT, it's in the `OptionParser` call that this happens (please, correct me if I'm wrong; I haven't looked into the optparse.rb source yet).  Is this a bug on their part?  I'd love someone to confirm, the presence of `brew` in the output makes me shaky.  If so, then perhaps another way of handling options is required.

---
I should add I'm on Mavericks (10.9), system ruby is `2.0.0p481`

### PR DESCRIPTION
**Pull request by jawshooah**
Closes #16265

### CODE REVIEW

**Comment by jawshooah** [comment]
@Amorymeltzer @adityadalal924 ping

**Comment by adityadalal924** [comment]
LGTM

**Comment by Amorymeltzer** [comment]
@jawshooah Curious, is `brew cask <cmd> --help` a similar issue?
````
Usage: brew [options]
        --caskroom=MANDATORY
        --appdir=MANDATORY
        --colorpickerdir=MANDATORY
        --prefpanedir=MANDATORY
        --qlplugindir=MANDATORY
        --fontdir=MANDATORY
        --servicedir=MANDATORY
        --binarydir=MANDATORY
        --input_methoddir=MANDATORY
        --internet_plugindir=MANDATORY
        --audio_unit_plugindir=MANDATORY
        --vst_plugindir=MANDATORY
        --screen_saverdir=MANDATORY
        --no-binaries
        --debug
        --verbose
        --outdated
        --version
````

**Comment by jawshooah** [comment]
@Amorymeltzer Yup, looks like `OptionParser` is trying to be smart and auto-generate help output.

**Comment by jawshooah** [comment]
@Amorymeltzer fixed in #17279.

**Pull request merged**
