### PR TITLE
Updated Vectr (latest)

### PR DESCRIPTION
**Pull request by pm5**

### CODE REVIEW

**Comment by adidalal** [comment]
No, keep the versioning.
https://github.com/caskroom/homebrew-cask/pull/20543

**Comment by pm5** [comment]
Any reason we should keep the versioning? Pardon me if I'm ignorant to previous discussions as I'm a newcomer.

**Comment by adidalal** [comment]
We prefer versioned URLs, mentioned in https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

------

Also, check out `cask-repair`, it makes Cask updates like this quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

**Comment by vitorgalvao** [comment]
@pm5 It was decided a while ago. The majority of users prefer versioned downloads because it means we can have a `sha256`. Amongst other things, it provides some extra security.

**Pull request closed without merging**
