### PR TITLE
Update screens to 4.3.3,11180

### PR DESCRIPTION
**Pull request by commitay**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
@emay3700 Please stop approving PRs, you not a maintainer so it doesn't make any difference and it won't get the PR merged any quicker.

**Comment by commitay** [comment]
@vitorgalvao Can we block this user from the organization please? The approval notifications are spammy.

**Comment by vitorgalvao** [comment]
@commitay Done. Looks like a bot, anyway.

**Comment by commitay** [comment]
Thank you!

**Comment by commitay** [comment]
It's followed me to `homebrew/core`: https://github.com/Homebrew/homebrew-core/pull/21214#pullrequestreview-80367329

**Pull request merged**
