### PR TITLE
Upgrade HipChat to 4.0.4-539

### PR DESCRIPTION
**Pull request by varju**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Updating the `:checkpoint` value in `appcast` is required. You can find it with `curl --silent --compressed "{{appcast_url}}" | sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256 | awk '{ print $1 }'`.

Alternatively, you may wish to use [`cask-repair`](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair). It can at once update the cask’s version (according to what you give it) taking care of updating both the cask’s `sha256` and the appcast’s `:checkpoint`, while still giving you the chance to perform other manual fixes.

You can easily install it with `brew install vitorgalvao/tiny-scripts/cask-repair`. `cask-repair --help` will show you some options, but as a whole the script will guide you through the update process.

**Comment by varju** [comment]
Atlassian hasn't been updating their Appcast feed.  https://www.hipchat.com/release_notes/appcast/mac still shows 3.3.7 as the latest version.

My proposed change follows the same pattern as other recent updates to this cask (eff2281, fa22e5f, c1dc294)

**Comment by vitorgalvao** [comment]
@varju Does the app itself still ask you to update, though?

**Comment by varju** [comment]
No.  If you check for updates it says there are none available: 
image

I'm not sure why they haven't started pushing their 4.0.x release out to people, except perhaps because they consider the 4.0 branch to be semi-beta.

Their release notes at https://www.hipchat.com/release_notes/mac do not list any previous 4.0.x releases, even though they do release older 3.3.x releases.  Each time they release a new 4.0.x build they edit the release notes to change the version number listed.

**Comment by vitorgalvao** [comment]
That’s valuable information, thank you. It means we shouldn’t yet be removing the appcast.

Merging, then. Thank you for the contribution.

**Pull request merged**
