### PR TITLE
Improve MS Teams ZAP

### PR DESCRIPTION
**Pull request by kiblik**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by krehel** [comment]
I am marking this as draft because it would be valuable to go through the `zap` items and ensure the only items being captured are from the "New" Teams, so there is not accidentally breakage of the other version.

**Comment by miccal** [comment]
@samford the versions for the new Microsoft Teams (and the classic one also) are listed here:

https://learn.microsoft.com/en-us/officeupdates/teams-app-versioning

Any chance you can work your `livecheck` magic and use this link instead of the current `:extract_plist` strategy?

FYI: I also maintain this in my tap and use a different `livecheck`: https://github.com/miccal/homebrew-miccal/blob/master/Casks/m-microsoft-teams.rb#L9-L12

**Comment by samford** [comment]
> Any chance you can work your `livecheck` magic and use this link instead of the current `:extract_plist` strategy?

Thanks for the information. It may be a little tricky to manually parse the HTML tables (i.e., we don't use `nokogiri` in brew, since it uses native gem extensions) but I'm always glad when we can avoid `ExtractPlist`. I've run out of time today but I'll try to take a pass at it tomorrow.

**Comment by Bo98** [comment]
There's also https://config.teams.microsoft.com/config/v1/MicrosoftTeams/1415_1.0.0.0?environment=prod&audienceGroup=general&teamsRing=general&agent=TeamsBuilds

**Comment by bevanjkay** [comment]
@Bo98 Is there any significance to the `1415_1.0.0.0` in the URL?

**Comment by Bo98** [comment]
Combination of client versions I believe. The API is used for more than update checking. It seems that bit doesn't really matter for this, but must be something numerical.

**Comment by samford** [comment]
> It seems that bit doesn't really matter for this, but must be something numerical. Can probably check what the actual client uses.

It would be good to know what the client does but I can at least say that using the cask version in the URL seems to work fine:

```ruby
  livecheck do
    url "https://config.teams.microsoft.com/config/v1/MicrosoftTeams/#{version}?environment=prod&audienceGroup=general&teamsRing=general&agent=TeamsBuilds"
    strategy :json do |json|
      json.dig("BuildSettings", "WebView2", "macOS", "latestVersion")
    end
  end
```

The response seems to provide the latest version information regardless of what version you use in the URL, so that seems promising. If we agree on this approach, I'll push a commit in the morning.

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/159807

**Pull request closed without merging**
