### PR TITLE
Update ocrkit to 18.4.19,cf4278314ef8e4b996e1b798d8eb92cf

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
sorry they are up to 

18.6.11,cf4278314ef8e4b996e1b798d8eb92cf

already

**Comment by vitorgalvao** [comment]
This looks like a walled build. Can we find the download link without giving them a name/email?

**Comment by core-code** [comment]
some of the mailinator aliases work for getting a download link from the homepage ( https://gist.github.com/nocturnalgeek/1b8fa44283314544c487 )

also, the download links from the appcast i found are obviously obtainable without e-mail

**Comment by vitorgalvao** [comment]
But the appcast is from a different hostname as well. Even if we can get to the download with a fake email, it still counts as a walled build. We’ll have to remove this.

**Comment by core-code** [comment]
can you merge the original pull-request ( 841799a ) as that one is on the 'same hostname'?

**Pull request closed without merging**
