### PR TITLE
Added mpv version 0.18.1

### PR DESCRIPTION
**Pull request by ghost**
- [x] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Commit message includes cask’s name.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by fanquake** [comment]
This was removed from this repository in #20483 as it is available via homebrew.

Also, as far as I can tell, `https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-0.18.1.tar.gz` is not the official URL, the homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb) uses `https://github.com/mpv-player/mpv/archive/v0.18.1.tar.gz`

**Comment by socksdev** [comment]
homebrew installs the CLI version, this installs the GUI version. Additionally, [https://mpv.io/installation/](https://mpv.io/installation/) lists the source, so while I suppose it is not the 'official' distribution, it is trusted.

While the policy from #22698 indicates that this would not be allowed because it is only semi-official, I don't see an official build being made any time soon, and these builds do work especially well.

**Comment by Eitot** [comment]
Can you restore the old formula, with the additional stanzas?

**Comment by vitorgalvao** [comment]
This will not be accepted again. Homebrew also install the GUI, give it the `--with-bundle` flag on installation.

**Pull request closed without merging**
