### PR TITLE
Update homepage in thunderbird.rb

### PR DESCRIPTION
**Pull request by mahori**
After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by miccal** [comment]
@mahori would you mind making the same change in the [thunderbird-beta](https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/thunderbird-beta.rb) cask?

**Comment by mahori** [comment]
@miccal Yes, please. The URL is https://www.thunderbird.net/en-US/thunderbird/beta/all/.

**Comment by miccal** [comment]
@mahori do you want to take care of it, or would you like me to do it?

**Comment by mahori** [comment]
@miccal I think it is better that you send a pull request as a contributor, as you have been suggested in the thunderbird-beta cask.

**Pull request merged**
