### PR TITLE
prey: Remove cask

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Needs `ci-skip-install` due to API key requirement.

**Comment by SMillerDev** [comment]
I don't think this should be in Homebrew/cask then

**Comment by p-linnane** [comment]
@SMillerDev This cask has been around for 9 years now, but install numbers are pretty low. I have no strong feelings regarding removal, but there is a caveat explaining the API key situation.

```
==> Analytics
install: 5 (30 days), 33 (90 days), 118 (365 days)

**Comment by SMillerDev** [comment]
Let's remove it, since homebrew really doesn't provide much benefits here.

**Comment by p-linnane** [comment]
Updated to remove the cask.

**Review by SMillerDev — DISMISSED** [review]

**Review by bevanjkay — DISMISSED** [review]

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
