### PR TITLE
teleport-tsh: add new cask

### PR DESCRIPTION
**Pull request by jaredallard**
Adding a `teleport-tsh` cask to install Teleport tsh through their recommended instructions. I realize that `teleport` (the formula) is a good option as well, but given the vendor is advising _against_ using it, I'd like to have the option to install it through the package through brew as well.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference). 
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @jaredallard.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by jaredallard** [comment]
> Thank you for your contribution to `homebrew-cask` @jaredallard.
> 
> Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

The only state I can find is `~/.tsh` which is created after `tsh login`. Does that count as something we'd want to remove with zap?

**Comment by jaredallard** [comment]
> Thank you for your contribution to `homebrew-cask` @jaredallard.
> 
> Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

The only state I can find is `~/.tsh` which is created after `tsh login`. Does that count as something we'd want to remove with zap? @miccal

**Comment by miccal** [comment]
> > Thank you for your contribution to `homebrew-cask` @jaredallard.
> > Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.
> 
> The only state I can find is `~/.tsh` which is created after `tsh login`. Does that count as something we'd want to remove with zap? @miccal

Yes please @jaredallard.

**Comment by jaredallard** [comment]
> > The only state I can find is `~/.tsh` which is created after `tsh login`. Does that count as something we'd want to remove with zap? @miccal
> 
> Yes please @jaredallard.

Added!

**Review by miccal — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @jaredallard.

**Pull request merged**
