### PR TITLE
Run `brew style` instead of `brew cask style`.

### PR DESCRIPTION
**Pull request by reitermarkus**
So we can eventually deprecate `brew cask style`.

### CODE REVIEW

**Comment by miccal** [comment]
FYI: https://github.com/Homebrew/homebrew-cask-versions/pull/9667

**Comment by reitermarkus** [comment]
Thanks @miccal. I have opened https://github.com/Homebrew/brew/pull/8806 to prevent this in the future.

**Comment by miccal** [comment]
You're welcome @reitermarkus.

**Pull request merged**
