### PR TITLE
Add Cask for WorkFlowy 0.0.1

### PR DESCRIPTION
**Pull request by dandorman**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by miccal** [comment]
[Unfortunately we cannot accept this Cask.](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md)

**Comment by kachkaev** [comment]
@dandorman looks like the stable version has been just announced:
https://blog.workflowy.com/2017/10/19/the-workflowy-desktop-app-has-arrived/

Would you like to submit a new PR for WorkFlowy?

@miccal will you be happy to merge that new PR? Or was the issue for rejection not v0.0.1?

**Comment by dandorman** [comment]
I don’t mind, but I’ll wait to see if @miccal has any objections.

**Comment by miccal** [comment]
I do not mind, please feel free to submit a new PR - it was rejected initially because the GitHub repository was not notable enough, but it meets our guidelines now.

**Comment by kachkaev** [comment]
Many thanks for submitting a new PR @dandorman and @miccal thanks for approving it! Just for those who are here from search, it's https://github.com/caskroom/homebrew-cask/pull/39873 🎉   

Running `brew cask install workflowy` worked for me like a charm!

done

**Pull request closed without merging**
