### PR TITLE
remove cask sublime

### PR DESCRIPTION
**Pull request by jrappen**
reasons:

- dead link
- sketchy tool to trick users into donations

compare discussion at:

- https://discourse.brew.sh/t/reporting-potential-abuse/4744/7

related to #15865

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> sketchy tool to trick users into donations

It’s a subtitle downloader. Just because they have a donation link it doesn’t mean they’re trying to trick you.

https://github.com/Homebrew/homebrew-cask/issues/69966

**Comment by jrappen** [comment]
@vitorgalvao the link is still dead though

**Comment by vitorgalvao** [comment]
Yes, the homepage link is dead and that would normally be grounds for removal, but the download link is very much alive and popular.

```
sublime (added 1393 days ago)
30 days: 800 (#154)
90 days: 2,352 (#147)
365 days: 8,230 (#154)
```

@core-code Do you have usage numbers for this app? If they’re drastically lower than our download count, it means people are indeed getting it by mistake, and we’ll remove.

**Comment by core-code** [comment]
i think i can confirm that they get it by mistake. according to our numbers it is only spot 6333 of all installed apps. i'd vote for removal.

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/70443

**Pull request closed without merging**
