### PR TITLE
Added jdownloader.rb

### PR DESCRIPTION
**Pull request by winkelsdorf**
Readded jdownloader.rb with new download-urls, fixes
https://github.com/caskroom/homebrew-cask/issues/19544

### CODE REVIEW

**Comment by adidalal** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 372f173ebc83d5355cc3a618c1d9278c333d27d0. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by winkelsdorf** [comment]
Ah I see, missed the ```user_agent``` indentation.

You're welcome, thank you for merging!

**Comment by adidalal** [comment]
@winkelsdorf `brew cask style jdownloader --fix` :) (It's also in our new PR template :D)

**Comment by winkelsdorf** [comment]
Haha, caught me :D My excuse: I created the final PR in GH Desktop, which does not show the templates ;)

I'll keep ```style``` next to ```audit``` in my mind. Thanks for the hint!

Cheers,
Frederik

**Pull request closed without merging**
