### PR TITLE
dvanalyzer-app 1.4.2

### PR DESCRIPTION
**Pull request by g-maxime**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-core/pull/18619

**Comment by commitay** [comment]
Labelling these as on hold for now as if the formulas are refused from `homebrew/core` the Casks will need to be renamed without the `-app` suffix.

Based on the Github pages these aren't notable enough to be included in Caskroom. One is also a fork of another project.

**Comment by commitay** [comment]
I'm 👎  on all 3 of these PRs because they are self submitted apps and they aren't notable enough to be included based on the Github pages.

**Comment by vitorgalvao** [comment]
I agree with @commitay. And these have and even lower chance of getting into HB, as their acceptance rules are stricter than ours.

**Comment by miccal** [comment]
@g-maxine thank you for your contribution, but we cannot accept this Cask at this time.

**Pull request closed without merging**
