### PR TITLE
Update veraview from 3.0.2 to 3.0.4

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
This is a duplicate of https://github.com/Homebrew/homebrew-cask/pull/69488

@core-code did you just want to take care of it? I can close mine.

**Comment by core-code** [comment]
sorry i am with *extremely* limited connection and didn't see yours. i'm fine either way. i'll close this now but can reopen if you want

**Comment by ran-dall** [comment]
Ok, I'll leave mine open, I guess. Should we report to the developer? I think it's an internal fail.

**Comment by core-code** [comment]
not sure there, can't say anything until i am on a connection that will allow me to actually download it ^^

**Comment by ran-dall** [comment]
Let me know on the other PR. Please 🙏

**Pull request closed without merging**
