### PR TITLE
New cask neat reader

### PR DESCRIPTION
**Pull request by bingtsingw**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by bingtsingw** [comment]
Hi, I have some problems adding livecheck, Could you please help me solve it?

The livecheck url is here: `https://www.neat-reader.com/download/start-download?target=mac`
But it uses javascript to generate the download link, and it seems not easy to split the version name.
```
  let target = $('input[name="deviceType"]').val();
  let versionTag = $('input[name="deviceVersion"]').val();
  let versionArray = ['6.0.8', '6.0.8'];
  let version = versionTag ? versionArray[0] : versionArray[1];
  let downloadLinkList = [
      {device: 'windows', link:`https://neat-reader-release.oss-cn-hongkong.aliyuncs.com/NeatReader%20Setup%20${version}.exe`},
      {device: 'mac', link:`https://neat-reader-release.oss-cn-hongkong.aliyuncs.com/NeatReader-${version}.dmg`}
  ];
```

There are another way to fetch the download url.
This software have a [Chinese site](https://www.neat-reader.cn/downloads/mac), which shows the download link directly, but it have a different domain and download link, how to handle this scenario.

English site domain: https://www.neat-reader.com/
Chinese site domain: https://www.neat-reader.cn/

English site download link: https://neat-reader-release.oss-cn-hongkong.aliyuncs.com/NeatReader-6.0.8.dmg
Chinese site download link: https://neat-reader-app-release.oss-cn-beijing.aliyuncs.com/NeatReader-6.0.8.dmg
I've checked They are the same hash.

**Comment by vitorgalvao** [comment]
> The livecheck url is here: `https://www.neat-reader.com/download/start-download?target=mac`
> But it uses javascript to generate the download link, and it seems not easy to split the version name.

This should work: `let versionArray = \['(\d+(?:\.\d+)*)`.

> This software has a [Chinese site](https://www.neat-reader.cn/downloads/mac), which shows the download link directly, but it have a different domain and download link. 

That’s not a problem. `livecheck` is only looking for a number, not downloading anything.

> How to handle this scenario? Should I change the homepage and download link to its Chinese site version?

You’d only need to set `url "https://www.neat-reader.cn/"` on `livecheck`.

**Comment by bingtsingw** [comment]
@vitorgalvao Thank you very much for your detailed explanation, I have added `livecheck` by Chinese site url.

**Comment by miccal** [comment]
Thank you @bingtsingw.

**Review by miccal — APPROVED** [review]

**Pull request merged**
