### PR TITLE
various casks: add conflicts_with

### PR DESCRIPTION
**Pull request by khipp**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

This PR adds missing `conflicts_with` stanzas to casks that are referenced by their counterparts.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]
We should implement the same check we have in Homebrew/core to ensure the conflicts match. Thoughts @Homebrew/maintainers?

**Comment by EricFromCanada** [comment]
> We should implement the same check we have in Homebrew/core to ensure the conflicts match.

Looks like we [already do](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_auditor.rb#L440).

**Comment by p-linnane** [comment]
Right, but that's just for formulae, unless I'm not understanding something.

**Comment by EricFromCanada** [comment]
Never mind, I read your comment as "…implement the same check in…", which inverts the meaning entirely 😅

**Pull request merged**
