### PR TITLE
Update openzfs - uninstall_preflight

### PR DESCRIPTION
**Pull request by commitay**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
___

- [x] `brew cask uninstall {{cask_file}}` worked successfully.

Uses ruby instead of `sed` to edit the `uninstall script`

### CODE REVIEW

**Comment by miccal** [comment]
> Uses ruby instead of sed to edit the uninstall script

Why?

**Comment by commitay** [comment]
I thought ruby methods were preferred over `system_command`?

**Comment by miccal** [comment]
Ping @vitorgalvao - I am not sure myself which is preferred.

**Comment by vitorgalvao** [comment]
Ruby is preferred because casks are themselves ruby code. The only times we should use `system_command` is when we can’t do something with ruby alone.

**Comment by miccal** [comment]
Thanks for the clarification @vitorgalvao.

PS. I like your new avatar, but I think I will miss the  broccoli and pumpkin!

**Comment by vitorgalvao** [comment]
> PS. I like your new avatar

Thank you.

> but I think I will miss the broccoli and pumpkin!

So will I. This one is quite busier and doesn’t compress as well to a tiny avatar, but it’s part of a later series I’ve been working on that I think ended quite well. Video of one of the processes (heavily compressed by twitter, unfortunately): https://twitter.com/vhgalvao/status/897984999743410176

**Pull request merged**
