### PR TITLE
Update stellarium to 0.16.1.2

### PR DESCRIPTION
**Pull request by sanyer**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by sanyer** [comment]
This app seems to be a bit tricky in setting up for cask.
VirusTotal can't check the links from sourceforge and uploaded .dmg file doesn't give any SHA-256 information (there is no Signature Info section): https://www.virustotal.com/#/file/273da715fad8752ca3d15911d95eade984bd277321d55dfda69fd9f4abf35d62/details

**Comment by commitay** [comment]
The current checksum seems to be correct.

```
273da715fad8752ca3d15911d95eade984bd277321d55dfda69fd9f4abf35d62  stellarium--0.16.1.2.dmg
```

**Comment by commitay** [comment]
Current checksum is correct.

```
 - download not possible: Checksum for Cask 'stellarium' does not match.


Expected: 52115eee624de8e3a4be5bf017004cef3c2252aa18b70d1cdcb31b1362fb4e7a

Actual:   273da715fad8752ca3d15911d95eade984bd277321d55dfda69fd9f4abf35d62

File:     /Users/travis/Library/Caches/Homebrew/Cask/stellarium--0.16.1.2.dmg
```

**Comment by sanyer** [comment]
hm, ok
After second look I see that file being downloaded by cask is only 127K in size.

**Pull request closed without merging**
