### PR TITLE
Fixes wrong SHA256 in #31161

### PR DESCRIPTION
**Pull request by jarne**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by cchacin** [comment]
@jarne ❤️

**Review by cchacin — APPROVED** [review]

**Comment by leipert** [comment]
It seems like jetbrains swapped out the release artifact since #31161 had been merged :(

I updated the @jcbot to handle same versions - different sha256 sums better.

**Comment by metyl** [comment]
Previous "release" had different build number what's why sha265 had changed.
Maybe build number should be added to the `version` stanza just to keep track of it.

**Comment by leipert** [comment]
Good idea. I will update the @jcbot to do that 👍

**Comment by metyl** [comment]
Consider also adding build number to branch name in @jcbot.
Take a look at my comment leipert/jetbrains-cask-bot@51f97767883cbf17ec3bb6b5897f2ad2b74f96d2

**Pull request merged**
