### PR TITLE
Update psychopy to 1.90.1

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by gtmgianni** [comment]
There are two "flavours" of this application – one for Python 2 and one for Python 3. Which should be used for this cask?

**Comment by vitorgalvao** [comment]
Whenever we can, let’s go with the future (python 3).

**Comment by vitorgalvao** [comment]
Whenever we can, let’s go with the future (python 3). But if there are two different apps with different names, we may also include both.

**Comment by vitorgalvao** [comment]
Whenever we can, let’s go with the future (python 3). But if there are two different apps with different names, we may also include both.

**Pull request merged**
