### PR TITLE
Add EdgeView.app v0.970

### PR DESCRIPTION
**Pull request by andromedarabbit**
EdgeView is a free comic viewer.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in f7bffd55c6c9d78eeb578dd28299b4f5115b7ead. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by vitorgalvao** [comment]
Looking further into it, it looks like a capable app. Do you know if the author will open-source it?

**Comment by andromedarabbit** [comment]
Frankly, I have no idea. I am trying to make a contact with him to let him know this new recipe and ask him what plans he has.

**Comment by vitorgalvao** [comment]
If you succeed and remember to, I’d appreciate updates. It does seem like the kind of app that would benefit from being open-source (and from a dedicated website).

**Pull request closed without merging**
