### PR TITLE
Ensure that /Library/Java/JavaVirtualMachines/ exists -- java.rb -- 11.0.1,13

### PR DESCRIPTION
**Pull request by darakian**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
Can you provide some more information as to why this is needed?

**Comment by darakian** [comment]
Well, when I went to install java I didn't have this directory and the script failed.

**Comment by commitay** [comment]
Can you post the output of `brew cask doctor`? Mostly interested in macOS version, etc as this directory already exists on a clean of 10.12 and 10.13.

**Comment by darakian** [comment]
Os version of the machine in question is Mojave (10.14 iirc). It's not a clean install though and probably the directory got removed if it was there to begin with.

**Comment by gdams** [comment]
I've never come across a version of macOS without `/Library/Java/JavaVirtualMachines/` already created. It's where the default system JRE is stored. What is the output of `/usr/libexec/java_home -V`?

**Comment by darakian** [comment]
```
Matching Java Virtual Machines (1):
    1.8.0_191, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home
```

Again, the directory may have been removed by some non-brew script.

**Comment by vitorgalvao** [comment]
Closing, as it’s starting to seem likely it isn’t needed. If it is, eventually we’ll get a bug report.

**Pull request closed without merging**
