### PR TITLE
smooze-pro: added conflicts_with "smooze"

### PR DESCRIPTION
**Pull request by cawaltrip**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by cawaltrip** [comment]
This installs Smooze Pro, not Smooze.  They are two distinct applications.

**Comment by reitermarkus** [comment]
Yes, so why does it conflict with `smooze`?

**Comment by cawaltrip** [comment]
Running one of the programs kills the other.  I guess there's nothing that technically prevents you from having both installed, but only one of them can be used at a time.  Since that's the case, should I go ahead and close this request?

**Comment by reitermarkus** [comment]
> should I go ahead and close this request?

Yes, as long as they don't install the same stuff, we don't need to mark it as a conflict.

**Pull request closed without merging**
