### PR TITLE
Update beyerdynamicvs to 1.011

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by giannitm** [comment]
This isn't actually an appcast, it seems: https://north-america.beyerdynamic.com/virtual-studio.html

**Comment by colindunn** [comment]
HTML pages that remain static are considered OK @giannitm

**Comment by vitorgalvao** [comment]
> HTML pages that remain static are considered OK @giannitm 

Yep.

**Comment by giannitm** [comment]
What I mean is that the page has no version information whatsoever on it, I think. @vitorgalvao

**Comment by giannitm** [comment]
@vitorgalvao I don't think this should be used as an appcast because it doesn't look like it changes whenever new versions of the cask application are released.

**Comment by giannitm** [comment]
That makes sense, thank you @vitorgalvao.

**Pull request closed without merging**
