### PR TITLE
Update openzfs from 1.9.0,18 to 1.9.3,88

### PR DESCRIPTION
**Pull request by chase9**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by chase9** [comment]
Any ideas why Travis CI failed? What what I can tell `org.openzfsonosx.zed` should already be unloaded in the uninstall scripts.

**Review by whizzrd — CHANGES_REQUESTED** [review]
The 1.9.3 DMG does not contain pkg for mavericks and yosemite

**Comment by chase9** [comment]
Unfortunately, that didn't fix the issue.

**Comment by vitorgalvao** [comment]
Thank you, but already working on https://github.com/Homebrew/homebrew-cask/pull/71861, which as submitted first.

**Pull request closed without merging**
