### PR TITLE
touch-bar-simulator: convert to on_system blocks

### PR DESCRIPTION
**Pull request by viking1304**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@viking1304 Thanks! This one needs to keep the `url` in the different blocks because the formatting is different on the pre-mojave version.

**Comment by viking1304** [comment]
> @viking1304 Thanks! This one needs to keep the `url` in the different blocks because the formatting is different on the pre-mojave version.

Oooops! Now I see the difference in the URL. Thank you very much for pointing that out.

**Comment by bevanjkay** [comment]
@viking1304 We've been adding the `livecheck skip` blocks where necessary, to make sure `brew bump` and `brew livecheck` wouldn't return incorrect versions when on older hardware. Sometimes an actual livecheck block can be used, but not often.

**Comment by viking1304** [comment]
> @viking1304 We've been adding the `livecheck skip` blocks where necessary, to make sure `brew bump` and `brew livecheck` wouldn't return incorrect versions when on older hardware. Sometimes an actual livecheck block can be used, but not often.

Make sense. Thanks for the explanation.

**Review by bevanjkay — APPROVED** [review]

**Pull request closed without merging**
