### PR TITLE
various: add rosetta caveats [d-f]

### PR DESCRIPTION
**Pull request by wickles**
Partial test/followup for #177913 (part 2)

### CODE REVIEW

**Comment by wickles** [comment]
```
audit for firestorm: failed
 - exception while auditing firestorm: key not found: :latest
firestorm
  * exception while auditing firestorm: key not found: :latest
Error: 1 problem in 1 cask detected.
Error: 1 problem in 1 cask detected.
Error: exception while auditing firestorm: key not found: :latest
Error: Process completed with exit code 1.
```

I do not understand this error message. Looks like it is unsigned, is that the cause of this?

**Comment by wickles** [comment]
reverting

- false positive x64 url: douyin-chat, dropbox-dash, favro
- expired web cert: denemo
- unsigned: firestorm

**Comment by wickles** [comment]
```
audit for fastclicker: failed
Error: 2 problems in 1 cask detected.
 - No binaries in App: /opt/homebrew/Caskroom/fastclicker/1.1/FastClicker.app
Error: 2 problems in 1 cask detected.
 - exception while auditing fastclicker: undefined method `to_str' for nil
fastclicker
  * line 5, col 2: No binaries in App: /opt/homebrew/Caskroom/fastclicker/1.1/FastClicker.app
  * exception while auditing fastclicker: undefined method `to_str' for nil
Error: No binaries in App: /opt/homebrew/Caskroom/fastclicker/1.1/FastClicker.app
Error: exception while auditing fastclicker: undefined method `to_str' for nil
Error: Process completed with exit code 1.
```

Not sure what this means and I cannot reproduce locally.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
