### PR TITLE
Update LibreWolf from v97.0.2-1 to v98.0-1

### PR DESCRIPTION
**Pull request by fxbrit**
After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by fxbrit** [comment]
```
Version '98.0,1,c3f59ce3926026cd1786008fcf09f69f' differs from '98.0,1,2f0c54ab84702298b77baa7c09c250db' retrieved by livecheck.
```

mmh I'm kinda lost since:

audit cleaned

**Comment by bevanjkay** [comment]
@fxbrit CI uses `brew audit <token> --online`

**Comment by neutric** [comment]
`livecheck` seems to pick up the wrong url 
```
[...]/uploads/2f0c54ab84702298b77baa7c09c250db/librewolf-98.0-1.en-US.mac.x86_64.dmg.sha256sum
``` 
judging by the third part of the `version` string it generates. Try restricting the `livecheck` regex to
```
regex(%r{/(\w+)/librewolf[._-](\d+(?:\.\d+)+)-(\d+)\.en-US\.mac\.#{arch}\.dmg[\s"]}i)
```
and see if that works.

**Comment by fxbrit** [comment]
@neutric thanks that fixed it!

@bevanjkay good to know, many thanks to you as well :-)

**Pull request merged**
