### PR TITLE
Update if/else, depend_on stanzas to match BBEdit's Cask requirements

### PR DESCRIPTION
**Pull request by chrisfinazzo**
Complement to #70099 and #70102. No change to the version number.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by core-code** [comment]
as far as i can see you aren't fixing anything, just removing support for 10.11 and 10.12

**Comment by chrisfinazzo** [comment]
> as far as i can see you aren't fixing anything, just removing support for 10.11 and 10.12

🙄 Anyways...

See @MikeMcQuaid’s comment re Cask’s policy on compatibility.

**Comment by core-code** [comment]
i see that we aren't trying to add support for such old systems, but why remove it? bbedit is quite popular and 10.12 is still in use.

**Comment by chrisfinazzo** [comment]
Yes, however Mike’s comment in the original PR is self explanatory. In addition to Apple dropping support for these versions, Catalina has shipped, hence change.

**Comment by core-code** [comment]
as far as i know, the "we support" means we don't actively add support via if/else for old systems unless there are good reasons in a particular case. 

i don't think it means that we should actively go out and make popular casks worse. but thats just my opinion and how i understood the "rules" so far. 

@vitorgalvao is there consensus that we should really change all casks to actively drop support for sierra and lower?

**Comment by MikeMcQuaid** [comment]
> as far as i know, the "we support" means we don't actively add support via if/else for old systems unless there are good reasons in a particular case.

I'm not a Homebrew Cask maintainer but: yes, that's what I think too. It means we'll close bug reports for those systems and remove dead code but we won't remove code that's working fine. 

You will note Homebrew/homebrew-core still has code that's only run on Mavericks.

> 🙄 Anyways...

@chrisfinazzo Not sure the eye rolling emoji was really necessary or helpful there. Let's try to all stay civil, please.

**Comment by vitorgalvao** [comment]
What @core-code and @MikeMcQuaid said is correct. Thank you anyway, @chrisfinazzo.

**Pull request closed without merging**
