### PR TITLE
Add JIRA Client.app 3.6.2

### PR DESCRIPTION
**Pull request by guylabs**
Hi,

it would be nice if you could merge this pull request as I want to move all apps that I need to homebrew cask.

Thanks and regards,

Guy

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> it would be nice if you could merge this pull request as I want to move all apps that I need to homebrew cask.

Keep in mind you don’t need us for that. You can always create a personal [tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md) or even just give a file as an argument to `brew cask install` and it will understand it.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 4391979e45d67dd0de1c3bb372a55c0b95b856a1. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by guylabs** [comment]
Hi Vítor,

yes you are right about the own tap and the file option. And thanks for adding the version replacement. Will this now be merged to the master? Or what is the procedure here?

Thanks for the quick answer and actions!

**Comment by vitorgalvao** [comment]
It has already been merged. Just `brew update` and it’s ready to use.

**Pull request closed without merging**
