### PR TITLE
Update unity to 2018.1.7f1,4cb482063d12

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
Why is this cask OK with travis but the other ones seem to always fail?

**Comment by vitorgalvao** [comment]
Not sure why the others fail. Let me restart Travis and see.

**Comment by commitay** [comment]
This needs to be merged first as some of the other unity casks depend on it.

**Comment by commitay** [comment]
They seem to be failing for another reason this time. 😆 

> installer:%97.750000

Usually they fail earlier.

**Pull request merged**
