### PR TITLE
Upgrade Appium Desktop to v1.1.1 & github hosting

### PR DESCRIPTION
**Pull request by jshreynolds**
Appium has migrated their code to github. The version
in the current caskroom points to an old binary
hosted on bitbucket.

The project is now
hosted and distributed on github.

I've also changed the cask token name to avoid
confusion between 'appium', the server for mobile
automation, and 'Appium Desktop' the desktop client
that allows for access and interaction with an
appium server.

I've also deleted the outdated cask. This exact situation
wasn't covered in the CONTRIBUTING.md, but seemed like
the right way to go.

Token: appium-desktop
Version: 1.1.1

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ X] `brew cask audit --download {{cask_file}}` is error-free.
- [ X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ X] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t][version-checksum],  
      provide public confirmation by the developer: {{link}}

Additionally, if **adding a new cask**:

- [ X] Named the cask according to the [token reference].
   See comment regarding disambiguation.
- [ X] `brew cask install {{cask_file}}` worked successfully.
- [ X] `brew cask uninstall {{cask_file}}` worked successfully.
- [ X] Checked there are no [open pull requests] for the same cask.
- [ X] Checked the cask was not already refused in [closed issues].
- [ X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
> I've also changed the cask token name to avoid
confusion between 'appium', the server for mobile
automation, and 'Appium Desktop' the desktop client
that allows for access and interaction with an
appium server.

Has the `appium` server been discontinued?

**Comment by jshreynolds** [comment]
Nope.  

I think I may have conflated to requirements, though.

Just to be clear, Appium distributes two "products".

Appium Desktop (a GUI that has a bundled Appium server and some tooling to help configure/discover testing commands.  distributed via releases on GitHub.)

appium (the standalone server, distributed via npm).  

This is sort of documented on their home page, but the project itself doesn't make a huge distinction. 

That being said, It makes sense to keep the token reference as is.  I'll update and push.

**Comment by jshreynolds** [comment]
Will do.

**Review by commitay — APPROVED** [review]

**Comment by miccal** [comment]
Thank you for your contribution.

**Pull request merged**
