### PR TITLE
Added Jahshaka v2.0

### PR DESCRIPTION
**Pull request by sheharyarn**
Added a Cask for the Jahshaka Video Editing Tool pkg

### CODE REVIEW

**Comment by ndr-qef** [comment]
Thanks for adding a new cask. Since the package uses an installer, we should add an [`uninstall` stanza](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#uninstall-stanza-details) before merging; the [scripts](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin) described in the docs should facilitate the process. Let me know if you need anything.

**Comment by sheharyarn** [comment]
Okay, working on it.

**Comment by sheharyarn** [comment]
Okay, I've added the `uninstall` stanza and tested it. Please review it.

**Comment by vitorgalvao** [comment]
The syntax is wrong. It should be `uninstall :script => '/usr/bin/jahshaka-uninstall'`. In addition, `:script` should be used in addition to other solutions, not in detriment of them; `:pkgutil` being the preferred one. Did the `list_recent_pkg_ids` script yield no results?

**Comment by sheharyarn** [comment]
No, the `list_recent_pkg_ids` script doesn't list any ids corresponding to jahshaka. I think the uninstall script automatically handles everything. Here's the output of `uninstall`:

```bash
± % brew cask uninstall jahshaka                                                                                                                        !5454
==> Running uninstall process for jahshaka; your password may be necessary
==> Removing...
==> /Library/Preferences/com.jahshaka.jahshaka.plist
==> /usr/bin/jahshaka.app/
==> /usr/bin/jahuserinstall
==> /usr/bin/jahshaka-uninstall
==> /usr/share/jahshaka/
==> /usr/lib/libopengpulib.dylib
==> /usr/lib/libopengpulib.1.dylib
==> /usr/lib/libopengpulib.1.0.dylib
==> /usr/lib/libopengpulib.1.0.0.dylib
==> /usr/lib/libopenassetlib.a
==> /usr/lib/libopencorelib.a
==> /usr/lib/libopenimagelib.a
==> /usr/lib/libopennetworklib.a
==> /usr/lib/libopenobjectlib.a
==> /usr/lib/libmediaobject.a
==> /usr/lib/libformats.a
==> /Applications/jahshaka.app
==> /usr/olib/
==> Done.
```

**Comment by ndr-qef** [comment]
Indeed, Jahshaka appears to rely entirely on the script.

I merged your PR as dc47bda. Thanks.

**Pull request closed without merging**
