### PR TITLE
chatmate-for-facebook: remove

### PR DESCRIPTION
**Pull request by chenrui333**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

```
$ curl -I https://chatmate.io/mac/facebook/
HTTP/2 404
server: nginx/1.25.2
date: Mon, 15 Jan 2024 22:04:04 GMT
content-type: text/html; charset=iso-8859-1
strict-transport-security: max-age=31536000
```

https://apps.apple.com/us/app/chatmate-for-facebook/id1249947725?mt=12

image

### CODE REVIEW

**Comment by krehel** [comment]
We haven't to my knowledge used archive.org links for downloads in Cask.  If the file is now only available in the App Store, I would vote for removal.

From the Cask cookbook -

> Similarly (and trickier to spot), the app has moved to the Mac App Store but still provides old versions via direct download. We reject these in all official repositories so users don’t get stuck using an old version, wrongly thinking they’re using the most up-to-date one (which, amongst other things, might be a security risk).

**Comment by chenrui333** [comment]
> We haven't to my knowledge used archive.org links for downloads in Cask. Is this something we are going to start doing?

trying to bypass the homepage errors, it is already some practice in core though

**Comment by krehel** [comment]
> > We haven't to my knowledge used archive.org links for downloads in Cask. Is this something we are going to start doing?
> 
> trying to bypass the homepage errors, it is already some practice in core though

True, but those are built from source and can be patched as needed.  To establish if there's a desire to use archive.org is a good question, though.  Eventually any legacy software will have issues (not unlike the PPC binaries of yesteryear).

**Comment by bevanjkay** [comment]
There's about to be an audit to potentially remove wayback machine items from `homebrew-core`.

https://github.com/Homebrew/brew/pull/16476

But does potentially allow for its use in `deprecated` casks.

**Comment by chenrui333** [comment]
it is transitional thing (as the interarchive formula/cask can be just deprecated)

**Comment by razvanazamfirei** [comment]
> If the file is now only available in the App Store, I would vote for removal

I'm also in favor of removing this.

```
chatmate-for-facebook
30 days: 5 (#3932)
90 days: 15 (#4008)
365 days: 60 (#3749)
```

**Comment by chenrui333** [comment]
I can remove it then. :)

**Review by krehel — APPROVED** [review]

**Pull request merged**
