### PR TITLE
Update qq.rb (sha256 checksum changed)

### PR DESCRIPTION
**Pull request by qinxin0720**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by bevanjkay** [comment]
A change of checksum without a version bump is a concern, as it can indicate that the binaries have been compromised.
Can you reach out to the vendor to check that the version was updated without a change of version number?

**Comment by qinxin0720** [comment]
> A change of checksum without a version bump is a concern, as it can indicate that the binaries have been compromised. Can you reach out to the vendor to check that the version was updated without a change of version number?

Sorry, I couldn't find a feedback channel for this application, but i downloaded the package via the browser and manually installed it, and it works well.

**Comment by p-linnane** [comment]
If we can't contact upstream, then we will need to wait for the next release.

**Comment by lijinglin3** [comment]
image

**Comment by almas1992** [comment]
> image

Run `brew edit qq` 
change `version` to `6.9.52_240808_01`
change `sha256` to `766bd497c15e95537c1c7aa2e75ff1f3ce7a2b22bf2eff0acfba05aa1a8fbc03`
Then run `brew install /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/q/qq.rb`

**Pull request closed without merging**
