### PR TITLE
coteditor: convert to `on_system` blocks

### PR DESCRIPTION
**Pull request by p-linnane**
https://github.com/Homebrew/homebrew-cask/issues/137512

### CODE REVIEW

**Comment by p-linnane** [comment]
@Rylan12 @bevanjkay This feels kind of weird. There is a version for El Capitan, and a version for Sierra through Mojave. I thought `on_mojave :or_older` would account for 10.12 through 10.14 by reading top down, but that's not the case. I had to put in conditionals for Sierra, High Sierra, and Mojave seperately.

**Comment by bevanjkay** [comment]
@p-linnane I had made a similar assumption. It may be too much of an edge case, but it could be useful to target multiple systems at once `on_sierra, on_high_sierra, on_mojave do`

**Comment by Rylan12** [comment]
If we find enough[^1] cases where such a thing would be useful, it's probably worth implementing. I don't think it would be very difficult, we just have to decide on the best DSL to use that's consistent, clear, and easy to use

[^1]: Not sure what the threshold is, though, and I'm not sure we're there yet

**Review by bevanjkay — APPROVED** [review]

**Comment by p-linnane** [comment]
Agreed that we are not there yet. Will continue to monitor as we progress through the rest of the casks.

**Pull request closed without merging**
