### PR TITLE
New cask virtual-ii (Virtual ][, an Apple II emulator)

### PR DESCRIPTION
**Pull request by L2G**
Is this still an appropriate idiom for doing a conditional install based on Mac OS version?

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Yes, but we prefer them to be inclusive, and mention them by symbol (i.e. `<= :leopard).

In addition, seeing as `url` in the `else` doesn’t point to a specific version, it should use `version :latest` and `sha256 :no_check`.

**Comment by L2G** [comment]
Oh, I thought that was for cases where there was no definitive version number to be found anywhere, not just the filename.

**Comment by vitorgalvao** [comment]
We need it for cases where the `url` isn’t versioned, or else the cask will simply break when the binary is updated upstream.

**Comment by L2G** [comment]
I need a little more help with this.

This app is meant to be run in its own folder, so it seems like a `suite` stanza is in order. However, there is no subdirectory in the DMG; the root _is_ the folder. I tried `suite '.'`, but that gave me a link with the name "latest" (i.e., the cask version). Now I'm stuck.

**Comment by vitorgalvao** [comment]
What we can do is create the directory and move the everything there, then call `suite` on that directory.

```ruby
preflight do
  system '/bin/mkdir', '--', staged_path.join('Virtual ][')
  ['Virtual ][.app', 'Readme.rtf', 'Welcome tape.cass', 'ADT'].each do |file|
    system '/bin/mv', '--', staged_path.join(file), staged_path.join('Virtual ][')
  end
end

suite 'Virtual ]['
```

If we can improve the `each` to something different, that would be readable and expand all of them at once in the command, it would even be better. Not that it makes any meaningful impact, here, but running the command once instead of three times would be more efficient.

We could also just move everything at once ( `*`), but OS X would give an error saying `Virtual ][` couldn’t be moved inside itself, but successfully move everything else, and accomplish what we want. Using a command that will knowingly output a error, even if it had no effect and we wouldn’t see it just seems wrong, though.

**Comment by L2G** [comment]
I don't suppose we could use [FileUtils](http://www.ruby-doc.org/stdlib-1.9.3/libdoc/fileutils/rdoc/FileUtils.html)?

As for the `*` move, we could name the directory something else before the move, then rename it after the move.

**Comment by vitorgalvao** [comment]
I guess we could, though we never do (not sure why). It wouldn’t help us much in this case, though. We could remove the `each` by just including every path in the line, naturally, but repeating `staged_path.join(…)` seems wasteful in space (as opposed to speed, that won’t even be noticeable).

Naming the directory something else before the move wouldn’t help, because the underlying problem with the `*` solution is we’re creating a directory next to all the other files. We could create it somewhere else and move it, but then we’re just creating even more commands, which makes even less sense. The current solution is relatively short and works.

**Comment by L2G** [comment]
Oh, I just discovered this. What about using `artifact` instead of `suite`? We could eliminate the whole `preflight` stanza and just use this:

```ruby
artifact '.', :target => 'Virtual ]['
```

I know the documentation says that `artifact` "is only for unusual cases," but I think this qualifies. :smile_cat:

**Comment by vitorgalvao** [comment]
Ah of course, forgot about that. Let’s use `suite` still, but instead say `suite '.', :target => 'Virtual ]['`. It’ll work exactly the same, but more correct.

**Comment by L2G** [comment]
One last thing: The app is free, but slightly crippled until a license is purchased. Is `:freemium` an appropriate license tag for that?

**Comment by vitorgalvao** [comment]
Yes.

**Comment by vitorgalvao** [comment]
Everything is looking great. Thank you for all your work.

**Pull request merged**
