### PR TITLE
Update wechat from 2.5.0.17 to 2.5.0.18

### PR DESCRIPTION
**Pull request by rickygao**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by rickygao** [comment]
#86564

**Comment by miccal** [comment]
This Cask is always a problem -- changing this to use `version :latest` and `sha256 :no_check`.

**Comment by vitorgalvao** [comment]
I agree we should get rid of the `appcast`. It doesn’t have a terrible delay, but multiple people always submit the new version before it’s updated. But I don’t think we should get rid of the `version` and `sha256` just yet. Considering how quickly this gets news submissions and that it can be auto-merged, it’s worth giving it a try for a bit.

**Review by vitorgalvao — DISMISSED** [review]

**Comment by vitorgalvao** [comment]
Pinging @Homebrew/cask on the changes to this cask.

**Comment by core-code** [comment]
i  don't think the appcast is the problem, the problem is that chinese (?) users get the update earlier than the rest of the world.

**Comment by rickygao** [comment]
> i don't think the appcast is the problem, the problem is that chinese (?) users get the update earlier than the rest of the world.

It seems updated anywhere now, thus I modify `version` and `sha256` again. But should `appcast` removal be involved?

**Review by miccal — APPROVED** [review]

**Comment by miccal** [comment]
@vitorgalvao the `sha256` change has already been reverted in https://github.com/Homebrew/homebrew-cask/pull/91003.

This Cask really needs to be changed to use `version :latest` and `sha256 :no_check`.

**Comment by core-code** [comment]
the only alternative i see is trying a country code stanza

**Comment by vitorgalvao** [comment]
Alright, I’m fine with whatever solution makes this cask manageable. Feel free to change and experiment at will.

**Pull request merged**
