### PR TITLE
Add mmhmm desktop 1.0.3

### PR DESCRIPTION
**Pull request by nihaals**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

- [ ] Uninstall system extension
- [x] `desktop` in token

### CODE REVIEW

**Comment by nihaals** [comment]
mmhmm renamed "mmhmm" to "mmhmm Studio" (currently `mmhmm`) and released "mmhmm desktop". Should the old cask be renamed and this be called `mmhmm`?

**Comment by nihaals** [comment]
mmhmm desktop also includes a system extension which currently isn't uninstalled and the process is still running (`app.mmhmm.hybrid.extension`). What's the best way of handling this?

**Comment by SMillerDev** [comment]
What's the difference between the two?

**Comment by nihaals** [comment]
> What's the difference between the two?

- https://www.mmhmm.app/blog/download-the-new-mmhmm-desktop-app
- https://help.mmhmm.app/hc/en-us/articles/1500012239201

I'm not sure if they plan on replacing the older one with the new one, but the way they're presented on the download page makes it seem like if they are, it won't be in the near future and there are reasons for each.

**Review by miccal — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @nihaals.

**Comment by nihaals** [comment]
How is Homebrew expected to interact with the installed system extension?

**Pull request merged**
