### PR TITLE
Update blue-jeans from 2.13.1.17 to 2.14.1.114

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [X] `brew cask audit --download --appcast --token-conflicts {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ran-dall** [comment]
Screen Shot 2019-07-09 at 11 40 32 AM

**Comment by core-code** [comment]
this is a beta version that is not available from their downloads page ( https://www.bluejeans.com/downloads ) 

i'll send a PR to 2.14.0.487 instead which is the latest official one

**Comment by core-code** [comment]
Submitted (https://github.com/Homebrew/homebrew-cask/pull/66023)

**Comment by ran-dall** [comment]
@core-code 👉 The ML wouldn't have pulled a beta if it wasn't being hosted on the link provided; it's not that smart. Could this be a regional thing?

**Comment by core-code** [comment]
it IS being hosted on the provided URL, but since its not linked from the downloads page ( https://www.bluejeans.com/downloads ) it isn't an official release

**Comment by core-code** [comment]
i've removed this cask from the database check so it shouldn't occur again

**Comment by ran-dall** [comment]
@core-code Sound good. Let's go with yours then... 👍 While we're here though there have been loads of repats and invalid updates the last few days. I'd appreciate if you can take a look. I double-check all the fails and its time consuming to check the same check over and over again.

**Pull request closed without merging**
