### PR TITLE
Update teamviewer, teamviewer-host: remove uninstall

### PR DESCRIPTION
**Pull request by commitay**
Fixes https://github.com/caskroom/homebrew-cask/issues/15322#issuecomment-379603267

Different issue than originally reported in https://github.com/caskroom/homebrew-cask/issues/15322

### CODE REVIEW

**Comment by commitay** [comment]
@TravisBuddy stop

**Comment by commitay** [comment]
@vitorgalvao https://github.com/caskroom/homebrew-cask/pull/45718/commits/55ae7b059228a21a41d9dfd3ba8a93d1c34d5820 fixes the issue but any upstream changes to the pkgs (i.e. the files within `com.teamviewer.teamviewer13AuthPlugin` are added to a `pkg` id that we `uninstall`) will cause further issues. I think removing the `uninstall` altogether is the safest option.

**Comment by vitorgalvao** [comment]
> I think removing the `uninstall` altogether is the safest option.

Agreed.

**Comment by vitorgalvao** [comment]
Added both casks to https://github.com/caskroom/homebrew-cask/issues/24377.

**Pull request merged**
