### PR TITLE
Update megasync from 4.1.0 to 4.1.1

### PR DESCRIPTION
**Pull request by robertleeblairjr**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by robertleeblairjr** [comment]
Screen Shot 2019-06-04 at 5 59 19 AM

**Comment by MTCoster** [comment]
@robertleeblairjr the checksum has changed too:
```
--- Casks/megasync.rb	2019-06-04 18:58:14.000000000 +0100
+++ Casks/megasync.rb	2019-06-04 19:11:40.000000000 +0100
@@ -1,6 +1,6 @@
 cask 'megasync' do
   version '4.1.1'
-  sha256 'e02dd282b63e140dc7ead0a11a5057f8ec59f2a5c18bf4b766a80ef9005293c1'
+  sha256 '2d261437650dad496b073bf13bfd5026e3770674bb5de7380aa6aa9e0da13016'
 
   url 'https://mega.nz/MEGAsyncSetup.dmg'
   appcast 'https://github.com/meganz/MEGAsync/releases.atom'
```

**Comment by robertleeblairjr** [comment]
I uninstalled, downloaded a fresh copy of the *.dmg file, to compare to the download by cask-repair. The sha256 is still calculated by the script and from shasum command as the same value 'e02dd282b63e140dc7ead0a11a5057f8ec59f2a5c18bf4b766a80ef9005293c1'.
I thought the checksum is the value of the *.dmg file and not the app.

Screen Shot 2019-06-04 at 1 42 53 PM

**Comment by vitorgalvao** [comment]
> I thought the checksum is the value of the *.dmg file

It is.

> the checksum has changed too

That’s an old checksum, you may be getting an old version.

This version isn’t yet in the appcast, but we seem to have its checksum. There’s some confusion here. The app doesn’t open for me, and Get Info isn’t showing the version. The version number isn’t important considering the rest, and there’s something weird going on with this software. Let’s update when they update the appcast.

**Comment by vitorgalvao** [comment]
> I thought the checksum is the value of the *.dmg file

It is.

> the checksum has changed too

That’s an old checksum, you may be getting an old cached version.

This version isn’t yet in the appcast, but we seem to have its checksum. The app doesn’t open for me, and Get Info isn’t showing the version. The version number isn’t important considering the rest, and there’s something weird going on with this software. Let’s update when they update the appcast.

**Comment by robertleeblairjr** [comment]
You got me but it wasn't an old checksum. Just downloaded and checked the same *.dmg file from the url. Same checksum and version is 4.1.1 (30853f9). So, not sure about the appcast 256 being different but it's probably not this file. Thanks.
Screen Shot 2019-06-04 at 2 27 00 PM

**Pull request closed without merging**
