### PR TITLE
Update mindjet-mindmanager from 12.1.190 to 13.0.181

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
```
audit for mindjet-mindmanager: warning
 - appcast at URL 'https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://www.mindjet.com/latest-release-notes-mac-english' does not contain the version number '13_0_181':
```
yes true but I dont think its good to change it to
`configuration: version.major`
because this was a major release and perhaps they change it back in future releases (?)

**Comment by core-code** [comment]
true

**Comment by core-code** [comment]
however, all 3 tests failed with

`Error: It seems the App source '/usr/local/Caskroom/mindjet-mindmanager/13.0.181/Mindjet MindManager.app' is not there.
`

**Comment by core-code** [comment]
np!

**Pull request merged**
