### PR TITLE
Update navicat-data-modeler-essentials from 2.1.21 to 3.0.3

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@suschizu I don't know why Travis has trouble connecting.

**Comment by vitorgalvao** [comment]
Also having trouble connecting on this one.

**Comment by ran-dall** [comment]
https://www.navicat.com/en/download/direct-download?product=modeleress_en.dmg&location=1

**Comment by suschizu** [comment]
https://github.com/Homebrew/homebrew-cask/pull/73507

**Pull request closed without merging**
