### PR TITLE
get-api 1.0.9

### PR DESCRIPTION
**Pull request by ikurek**
After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by ikurek** [comment]
I was not sure how to handle the versioning in this case - the URL is unversioned but it's possible to do `brew livecheck` with plist file, so I set the version to currently available one with the livecheck enabled

**Comment by krehel** [comment]
There is a Sparkle feed, but it appears to return a 403 unless some custom headers are provided (at least for me.)  It's fronted by Cloudflare.

Tagging @samford for his inputs

**Comment by ikurek** [comment]
It seems that https://getapi.io/osx/version.xml url is for internal use only, I wasn't able to access it (the same 403 error). I've also added `auto_updates true` in https://github.com/Homebrew/homebrew-cask/pull/175582/commits/0d268473e17a96af4d77f8d1443d21da2a21edd9 since there is a built-in option to install an update

**Review by samford — COMMENTED** [review]
The unversioned `cask` URL (https://getapi.io/release/osx/getapi_latest) redirects to a versioned URL (https://files.getapi.io/macos/1.0.8/Get%20API.dmg) but only if you use a `GET` request.

`Utils::Curl#curl_headers` (which livecheck uses) contains some logic to retry a failing request using `GET` (instead of `HEAD`) but it doesn't work with the resulting response because the exit status is 8 ("weird server reply"). If we treat that as a usable response (like we do with 22), then we can use `strategy :header_match` here instead.

I was looking into this issue recently as I've seen ~22 other casks where `HeaderMatch` isn't working for the same reason. I created a tentative fix but I needed to finish going through the others before creating a PR. I just finished a minute ago, so here's the brew PR: https://github.com/Homebrew/brew/pull/17412

If/when that's merged, we can update this PR to use `strategy :header_match` instead. Unless there's a reason not to, we may want to try using the versioned dmg URL as well.

**Review by samford — COMMENTED** [review]
I pushed a commit to use the versioned dmg URL (from the `getapi_latest` redirection) and to update this to 1.0.9.

The brew PR to allow `Utils::Curl#curl_headers` to handle an `8` exist status ("weird server reply") has been merged, so I've updated the `livecheck` block to use the `getapi_latest` URL with the `HeaderMatch` strategy.

**Review by miccal — APPROVED** [review]

**Review by krehel — APPROVED** [review]

**Pull request merged**
