### PR TITLE
Add iShowU Instant.app and iShowU Studio.app Latest

### PR DESCRIPTION
**Pull request by DanielGibbsNZ**
- [x] Checked there aren’t open pull requests for the same cask.
- [x] Checked there aren’t closed issues where that cask was already refused.
- [x] When naming the cask, followed the token reference.
- [x] Commit message includes cask’s name.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

Add iShowU Instant and iShowU Studio  screen recording apps.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
These belong in [caskroom/versions](https://github.com/caskroom/homebrew-versions).

**Comment by DanielGibbsNZ** [comment]
Why?

**Comment by vitorgalvao** [comment]
> Why?

Throughly [explained in the target repo](https://github.com/caskroom/homebrew-versions#acceptable-casks) and [in the documentation on adding casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask), and [the FAQ](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected-casks.md).

`ishowu-hd` in the main repo is a mistake, and needs to be moved.

**Comment by DanielGibbsNZ** [comment]
iShowU, iShowU HD, iShowU Studio, and iShowU Instant are all completely separate products (not alternative versions) so belong in this repository. They share the same prefix as they are from the same *family* of products, in the same way that Adobe Photoshop, Adobe Illustrator, and Adobe Lightroom are from the same family but are different apps.

**Comment by vitorgalvao** [comment]
Reading their website, they all seem to do the same thing (screen recording), with more or less features tacked on. They discuss similarities:

image

And they even have comparison charts detailing all the apps:

image

However, looking at the screenshots, they do indeed seem different. Reopening.

All that said, in the future, please submit separate pull requests for each cask, as more often than not this type of pull request brings problems with one or more of them, and it halts the inclusion of the other ones.

Also, didn’t you get a template to fill out when opening the PR? That is necessary.

**Comment by DanielGibbsNZ** [comment]
I've updated the original comment with the checklist. I read the template and it said to delete everything so I did after reading the checklist, whoops.

Regarding multiple pull requests, noted. I thought it would be ok because the docs say "it is fine for a pull request to contain multiple commits when there is a logical reason for the separation." but I can see how things would be easier with separate ones so will do that in the future.

**Comment by vitorgalvao** [comment]
> I read the template and it said to delete everything so I did after reading the checklist, whoops.

Not the first person to do that. Clearly that part needs a tweak.

**Comment by vitorgalvao** [comment]
Merging. Thank you.

**Pull request merged**
