### PR TITLE
Update freefilesync to 10.6

### PR DESCRIPTION
**Pull request by Wayneoween**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by Wayneoween** [comment]
Not sure why the hash changed. I uploaded the `.pkg` as well as the `.zip` to VirusTotal but both came out fine. So should ™️ be ok.

ZIP: https://www.virustotal.com/#/file/00adc3e3fb32a9d1e8d7e8204524460c03624b7238b2b9877d3474670a01bba1/detection

PKG:
https://www.virustotal.com/#/file/714b19217208b2ace27225d9d0e8d02617050827a5b29dbf530b8367c4c18636/detection

**Comment by ran-dall** [comment]
I've seen this problem before with another cask. 
Refer to: https://github.com/Homebrew/homebrew-cask/pull/54820#issuecomment-438919865

So perphaps the best way to fix this would be using  `sha256 :no_check`. It's explained on [the link](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md).

So you're code should look like:

```
cask 'freefilesync' do
  version '10.6'
  sha256 :no_check

  url "https://www.freefilesync.org/download/FreeFileSync_#{version}_macOS.zip",
      user_agent: :fake
  name 'FreeFileSync'
  homepage 'https://www.freefilesync.org/'

  pkg "FreeFileSync_#{version}_macOS.pkg"

  uninstall pkgutil: [
                       'org.freefilesync.pkg.FreeFileSync',
                       'org.freefilesync.pkg.RealTimeSync',
                     ]
end

```

Also, https://github.com/Homebrew/homebrew-cask/pull/55021 is a duplicate

**Comment by Wayneoween** [comment]
I removed the checksum as per your example.

I don't really like that, but if MediaFire does things to the file... 🤔 Not much we can do about it, I guess.

**Comment by vitorgalvao** [comment]
> but if MediaFire does things to the file... 🤔 Not much we can do about it

We can get rid of MediaFire casks, which currently sounds to me like the best bet. We’ve removed casks in the past due to them having `curl`-hostile URLs

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/55071

**Comment by vitorgalvao** [comment]
Closing in favour of #55071. This will either be removed or (more likely) fixed properly.

**Pull request closed without merging**
