### PR TITLE
USAGE.md: fix manpage name

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Comment by miccal** [comment]
I have already made this change in https://github.com/Homebrew/homebrew-cask/pull/88682 -- can we please just merge that instead for now and then continue to update it as required?

**Review by reitermarkus — APPROVED** [review]

**Comment by reitermarkus** [comment]
Sorry @miccal, approved before reading your comment. I agree we should just merge https://github.com/Homebrew/homebrew-cask/pull/88682 and continue improving from that.

**Comment by miccal** [comment]
> Sorry @miccal, approved before reading your comment. I agree we should just merge #88682 and continue improving from that.

No problem @reitermarkus -- I have resolved the conflict caused by this in my original PR, so if you would not mind approving it that would be great, thanks.

**Comment by vitorgalvao** [comment]
Forgot about the other PR! Otherwise I wouldn’t have submitted this change.

**Pull request merged**
