### PR TITLE
Update dendroscope to 3.5.10

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
sorry, no idea. last time i just changed the version ;)

**Comment by reitermarkus** [comment]
> Is there any way to implement checking for OpenJDK?

This would have to be implemented in the `brew` repo.

**Comment by ran-dall** [comment]
@reitermarkus Ah! Makes sense. 

Is that why the `depends_on java:` stanza (
https://github.com/Homebrew/homebrew-cask/issues/16383) by @vitorgalvao  is ["not functional yet"](https://github.com/Homebrew/homebrewcask/blob/master/doc/cask_language_reference/stanzas/depends_on.md#all-depends_on-keys)?

**Comment by reitermarkus** [comment]
Is that why the `depends_on java:` stanza (https://github.com/Homebrew/homebrew-cask/issues/16383) by @vitorgalvao  is ["not functional yet"](https://github.com/Homebrew/homebrewcask/blob/master/doc/cask_language_reference/stanzas/depends_on.md#all-depends_on-keys)? 

> Yes, although I'm not sure off the top of my head if that is partially implemented or not at all.

**Comment by ran-dall** [comment]
@reitermarkus All good! Thanks for the update! I think there's really nothing holding this back then...

**Pull request merged**
