### PR TITLE
Add missing rosetta caveats

### PR DESCRIPTION
**Pull request by wickles**
After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

---

Added the `requires_rosetta` caveat to many casks with only intel builds available. I'm sure I missed some but tried to cover the most popular and most obvious ones.

Methodologies used:
- grep for relevant `url` substrings such as: intel, x86, x64, amd64
- manual inspection via `file` command and Info box for apps

Potential issues: some casks might get updated in the future with arm builds so then a maintainer will need to notice and remove the caveat, especially for universal builds. Note in particular there are some casks with arm builds for development versions but not for the stable version.
- examples: beyond-compare (beta), virtualbox (beta), dolphin (beta/dev), retroarch/metal

Related problem: I identified some casks that are only built for 32-bit intel, so they do not work with Rosetta. Not sure what is the right way to handle these -- require intel arch? Can make a separate PR for this.
- examples: pgadmin3, nightingale, mame, gameranger

### CODE REVIEW

**Comment by bevanjkay** [comment]
Thank you for taking the time to create this PR @wickles 
Have all of the changes been manually verified, or do some make assumptions based on the presence of `x64` etc..
The only true way to check this is to manually verify, as you have with some of them.

**Comment by SMillerDev** [comment]
Yeah, I'm sceptical that all are still not usable on modern macs without Rosetta. It's not unlikely upstreams just made universal binaries without changing the name.

**Comment by SMillerDev** [comment]
I think these are too many files for test bot to handle. And we need to have one commit per casks anyway. Could you split this in a PR per ~50 casks?

**Comment by wickles** [comment]
> Have all of the changes been manually verified, or do some make assumptions based on the presence of x64 etc..
The only true way to check this is to manually verify, as you have with some of them.

I have checked many but not all. The new audit should help identify any false positives, once the issues are worked out.

**Comment by wickles** [comment]
Closing in favor of smaller followup PRs.

**Pull request closed without merging**
