### PR TITLE
Update wireshark from 3.0.3 to 3.1.0

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
this is a beta release - it is clearly labeled as 'development release' on the homepage. 

please do NOT update casks to beta versions.

**Comment by suschizu** [comment]
sorry for that

**Comment by core-code** [comment]
no problem if you are 'tiefenentspannt'

**Comment by suschizu** [comment]
haha - thanks siri ;)

**Pull request merged**
