### PR TITLE
Add TipToi-Manager v1.4.2

### PR DESCRIPTION
**Pull request by phschaer**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.

My ruby installation seems to be broken. The scirpt won't run with the following error message:

`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.`

- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by ran-dall** [comment]
Travis is stuck

**Comment by core-code** [comment]
@vitorgalvao  we already have a 'tiptoi-manager' over in the cask repository:

https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/tiptoi-manager.rb

i guess we can delete one of them?

**Comment by vitorgalvao** [comment]
Well spotted. Yes, we can delete this one.

**Comment by core-code** [comment]
this one is versioned, the one in 'drivers' is unversioned. i can send a delete request either way.

**Comment by vitorgalvao** [comment]
I’ve already deleted this one.

**Comment by core-code** [comment]
ok thanks

**Pull request merged**
