### PR TITLE
Upgrade Wireshark to v1.12.6

### PR DESCRIPTION
**Pull request by neilhawkins**
Upgrades Wireshark to version v1.12.6

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 3ac0642b925e3d228575623afcfd4c2c02a35512 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by darfink** [comment]
It seems as if the URL no longer works?

**Comment by vitorgalvao** [comment]
@darfink Works for me. Must be on your end.

**Comment by darfink** [comment]
Yes, it was :)

**Pull request closed without merging**
