### PR TITLE
nextcloud-vfs 3.13.2 (new cask)

### PR DESCRIPTION
**Pull request by piijai**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

`brew audit --cask --new <cask>` fails, because of 'GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)'

Nextcloud started to offer a separate package with virtual file system.

If you find another way, to have both versions of nextcloud Desktop available, please feel free to do so.
If you have any questions, feel free to comment.

### CODE REVIEW

**Review by khipp — COMMENTED** [review]
Thank you for your submission, @piijai!

Based on the [upstream discussion](https://github.com/nextcloud/desktop/discussions/6656), the client with virtual files support will be maintained as a separate application:

> From now on the Nextcloud application will come in two flavours on macOS: standard, and virtual files. [...] Please note that our current plans are to support both the standard sync client and the virtual files client concurrently. There are no plans at the moment to replace the standard client.

I left a few comments. Please also try to squash your commits to keep a cleaner history.

**Comment by p-linnane** [comment]
@piijai Please address @khipp's suggestions above. Thanks.

**Comment by piijai** [comment]
> @piijai Please address @khipp's suggestions above. Thanks.

Done. Thanks for the hint, I didn't know, I had to commit these suggestions.

**Review by p-linnane — APPROVED** [review]
Thank you @piijai!

**Comment by khipp** [comment]
@p-linnane The audit seems to fail because of the `conflicts_with` stanza added to the `nextcloud` cask. Do we have a way of skipping or should this be handled in a follow-up PR?

**Comment by p-linnane** [comment]
Yeah, we can add the conflicts in a follow up PR. They don't behave nice when trying to add them with a new cask/formula.

**Review by p-linnane — APPROVED** [review]

**Comment by khipp** [comment]
Finally, clean and green. Thank you, @piijai and @p-linnane!

**Pull request merged**
