### PR TITLE
use secure (https://) URLs where supported (attempt #2)

### PR DESCRIPTION
**Pull request by vszakats**
##### Instructions
- Look for and complete the section relevant to your submission. Delete the others, including these `Instructions`.
- `{{cask_file}}` represents the cask file you’re submitting/editing (if applicable).
- If there’s a checkbox you can’t complete for any reason, that’s OK. Just explain in detail why you weren’t able to do so.
#### Editing an existing cask
- [ ] Commit message includes cask’s name (and new version, if applicable).
- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` left no offenses.

---

I've used a script to verify if a secure alternative is available:
    https://gist.github.com/vszakats/7bdb547e367338299d029140fd8208ed

Script updated to:
- handle more `#{version.*}` macros
- try harder to verify cases where content-length is not reported
- fix a minor issue in the automatic formula update code

The PR includes a second patch, that contains manually tracked/verified
URL changes, where the script detected certain patterns of ambiguity.

Ratio of secure/insecure URLs:

Before:
Secure: 4678
Insecure: 3453

After:
Secure: 5062
Insecure: 3076

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> handle more `#{version.*}` macros

You seem to be doing a lot of manual work for this. Use `_stanza`: `brew cask _stanza url {{cask_name}}` will give you the correct `url` with all conversions done.

**Comment by vszakats** [comment]
Great stuff, I didn't know, thanks for the tip! I'm going to adapt the script.

**Comment by jawshooah** [comment]
> Error: audit failed for 15 casks: 4k-youtube-to-mp3 abyss audiomate downie gitkraken hapu marsedit nzbvortex paintcode repetier-host rubitrack synalyze-it-pro taskwarrior-pomodoro together torguard

Looks like either the `url` or `appcast` check failed for those casks. I'll merge the others for now; you can try the failed ones again in a separate PR if you'd like.

**Comment by jawshooah** [comment]
Thank you for the contribution. It needed some fixes, so they were made in b3da4e2dcb5b79251345f282f3c1dea58fbcba27. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by vszakats** [comment]
Thank you. I'll look into the failing ones.

**Pull request closed without merging**
