### PR TITLE
Updated typora (latest)

### PR DESCRIPTION
**Pull request by hevets**

### CODE REVIEW

**Comment by adidalal** [comment]
Updating the `:checkpoint` value in `appcast` is required. You can find it with `curl --silent --compressed "{{appcast_url}}" | sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256 | awk '{ print $1 }'`.

Alternatively, you may wish to use [`cask-repair`](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair). It can at once update the cask’s version (according to what you give it) taking care of updating both the cask’s `sha256` and the appcast’s `:checkpoint`, while still giving you the chance to perform other manual fixes.

You can easily install it with `brew install vitorgalvao/tiny-scripts/cask-repair`. `cask-repair --help` will show you some options, but as a whole the script will guide you through the update process.

**Comment by adidalal** [comment]
should be `e3c717ecc8179492764c5f0017451c68f3b4bc8605cac28fd2818de684c8e62f`

Looks like you did use cask-repair though, which is interesting. Wonder why it didn't update

**Comment by adidalal** [comment]
@hevets Please resubmit with a versioned URL.

`cask-repair -v 0.9.8.5 typora`

**Comment by vitorgalvao** [comment]
> Looks like you did use cask-repair though, which is interesting. Wonder why it didn't update

No idea. Just tried it and it worked as usual.

**Pull request closed without merging**
