### PR TITLE
Added BTCPayServer Vault 1.0.0

### PR DESCRIPTION
**Pull request by woutersamaey**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> + The Cask is too obscure. Examples:
>   + A self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars).
>   + [Electronic Identification (eID) software](https://github.com/Homebrew/homebrew-cask/issues/59021).

**Comment by woutersamaey** [comment]
Can we re-apply when the number of stars has gone up? It's a new project...

**Comment by NicolasDorier** [comment]
Hi, main developer of https://github.com/btcpayserver/btcpayserver.vault here.

This project is part of another very popular project https://github.com/btcpayserver/btcpayserver which has over 1000 stars.

**Comment by NicolasDorier** [comment]
I tweeted on https://twitter.com/BtcpayServer/status/1207885222257156096?s=20 we should get the required stars today.

**Comment by woutersamaey** [comment]
@vitorgalvao
Also wanted to point out that while the name of this tool suggests it’s part of BTCPay Server, its actually a very handy standalone tool that can connect any web app to a hardware wallet / external encryption key attached to your Mac in a secure way. We imagine all kinds of uses for this in the future, not just limited to wallets or eID.

**Comment by NicolasDorier** [comment]
@vitorgalvao I did some star begging https://github.com/btcpayserver/btcpayserver.vault , can you reopen?

**Comment by woutersamaey** [comment]
Thank you

**Comment by thijstriemstra** [comment]
"star begging" 😄

**Pull request merged**
