### PR TITLE
Casks/microsoft outlook.rb

### PR DESCRIPTION
**Pull request by davidmarcantonio**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by NemesisOfNo** [comment]
Microsoft Outlook 2016 15.40 being split out of the Office Suite.

**Comment by commitay** [comment]
We need to be able to publicly verify these download links. Is there a way to obtain the downloads without purchase / login?

**Comment by commitay** [comment]
You have 4 commits in this PR.

**Comment by commitay** [comment]
All of your open PRs need to be changed to use a `pkg` install and `uninstall pkgutil`

https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/pkg.md

https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-key-pkgutil

**Comment by NemesisOfNo** [comment]
https://macadmins.software is where these are all pulled down from. Should I reference this page then when building out the rb files?

**Comment by commitay** [comment]
No, we need a Microsoft website with the download links.

**Comment by vitorgalvao** [comment]
@NemesisOfNo To clarify, we needs pages that adequately serves as official homepages for each of these apps *and* that have links to the `url`s you reference, freely accessible (not behind a login).

If you can’t provide those, we’ll have to refuse these casks. It’s a matter of user security and auditability.

**Comment by vitorgalvao** [comment]
If we get nothing new by Monday, let’s close the PRs.

**Comment by commitay** [comment]
Closing, please feel free to resubmit these if you can find a suitable `homepage` https://github.com/caskroom/homebrew-cask/pull/41092#issuecomment-346224825 and the changes in https://github.com/caskroom/homebrew-cask/pull/41092#issuecomment-345874341 have been made.

**Pull request closed without merging**
