### PR TITLE
Revert "removing android-ndk cask based on #58883"

### PR DESCRIPTION
**Pull request by vitorgalvao**
https://github.com/Homebrew/homebrew-cask/issues/58883#issuecomment-509028688

### CODE REVIEW

**Comment by sesam** [comment]
Since in https://github.com/Homebrew/homebrew-cask/issues/58883 it says up top that the only ENV variable still relevant seems to be ANDROID_HOME but this code has a `caveat` suggesting to add an ENV variable that likely no longer works.

What is the proper process to get this fixed?

I guess I could maybe open a new Issue and try to tie together the existing several locations where this is discussed, but that might complicate things even further. And I'm not actively using this, just have a strong memory of the hours lost - working with Android is lots of not useful outputs, and near none useful install/post-install warnings. I rant, sorry.

**Comment by vitorgalvao** [comment]
Proper way to fix it would be a PR changing the message, if that’s the problem.

Also pinging @rcombs, since they use this.

**Comment by sesam** [comment]
Try this:
1. install cask android-ndk
2. Open /usr/local/Caskroom/android-ndk/19/android-ndk-r19/prebuilt/darwin-x86_64/bin/ndk-which
3. Lines 18-20 says this tool is DEPRECATED
4. The script uses its path on disk and steps up/out to find the ndk within which it is installed. The ANDROID_NDK_DIR is not used by ndk-which.

A question remains if there are some other tools that use the ANDROID_NDK_DIR.

@rcombs Likely `ndk-which` being marked deprecated isn't a showstopper for you. But can you see if `ndk-which` still does its job in your use-case where you don't want to have to insatll the android sdk?

**Comment by vitorgalvao** [comment]
> 3\. Lines 18-20 says this tool is DEPRECATED

That’s an important consideration that wasn’t made in the other issue. Does that mean `android-ndk` as a whole is deprecated, or just `ndk-which`? If the former, I’ll mark the cask as deprecated and remove in (let’s say) six months.

**Comment by rcombs** [comment]
It's just the `ndk-which` tool, which I use just as a portable way to locate the NDK install. Specifically, I do `ndk-which ld` and back up a few dirs from there. It wouldn't be a huge deal to just use `/usr/local/share/android-ndk` explicitly on macOS instead, if that's eventually removed.

**Comment by sesam** [comment]
@rcombs Specifically in https://github.com/Homebrew/homebrew-cask/issues/58883#issuecomment-464232674 it was suggested that the ndk can not be used independently. What parts of the android-ndk are you using? The ndk seems to contain a mix of common unix tools like make, python and some more, didn't look it all through and now I'm curious what you do after finding the actual dir? Does the not deprecated variant `$ANDROID_HOME/ndk-bundle` work equally well as your current ndk-which + going some dirs up?

**Comment by rcombs** [comment]
I don't have an `$ANDROID_HOME` env var, nor dir named `ndk-bundle` anywhere I can find. The essential components are the sysroot (`/usr/local/share/android-ndk/sysroot`, containing the Android platform headers and static and shared libraries) and the toolchains (`/usr/local/share/android-ndk/toolchains`, containing clang (AIUI with some modifications to automatically use the correct gcc components) and the binutils tools such as ld, nm, objcopy, etc. required to link for the relevant Android/Linux targets). My understanding is that the SDK provides a way to install these, but it's significantly more complex than using the cask and pointing at `/usr/local/share/android-ndk`.

**Comment by sesam** [comment]
Excellent. This clearly shows the android-ndk cask has value, as well as contradicts the loose suggestion that the ndk isn't useful on it's own.

I'm thinking maybe removing the caveat string could help limiting the amount of brew cask users that install this cask, then install the sdk, and them the two don't find each other and you land in a situation where ndk commands on the command line modify things that the sdk ignores so the sdk then goes on to "help" creating a second duplicate ndk-bundle folder.

**Pull request merged**
