### PR TITLE
Add 'Free42 Binary.app' and 'Free42 Decimal.app' v3.0.1

### PR DESCRIPTION
**Pull request by Aaron-Rumpler**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @Aaron-Rumpler.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

**Comment by Aaron-Rumpler** [comment]
The issue is that both versions (Binary and Decimal) share the same user data files, so is a user had both installed and removed one with `zap`, it would remove the shared user data files for both, which could be unexpected. Also, if both versions are installed, only one shows up in the Launchpad (seems to be random which one, caused by both versions sharing the same bundle identifier), so putting them both in the same cask is undesirable. However, they can be installed together if the Launchpad issue isn't an issue, so marking both versions as conflicting is undesirable.

**Comment by vitorgalvao** [comment]
@Aaron-Rumpler Both of those rules are offset [by](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Casks.md#homebrew-cask-is-not-a-discoverability-service):

> users are expected to have reasonable knowledge about the apps they’re installing through us before doing so. 

Please add the `zap` and remove the `caveat`.

**Comment by Aaron-Rumpler** [comment]
Done. The Launchpad issue is going to be fixed in the next release anyway. However, the CI's not liking it (`Version '3.0.1' differs from '' retrieved by livecheck.`, but there's no livecheck in this cask).

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @Aaron-Rumpler.

**Review by miccal — APPROVED** [review]

**Pull request merged**
