### PR TITLE
Add Kubebox 0.3.1

### PR DESCRIPTION
**Pull request by micdah**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
> [Rejected Casks](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md#rejected-casks)
> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core) as a formula that builds from source. If it is rejected, you may then try again as a cask (link us to the issue so we can see the discussion and reasoning for rejection).

**Comment by micdah** [comment]
Why is `parse-cli` then in casks as well, and even mentioned in readmes here https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/all_stanzas.md#optional-stanzas in relation to `binary` type.

I honestly see no benefit of building from source rather than just using the packaged binary.

I'll consider trying to add it to core, but as it is not my project but I am just a user of `kubebox` I might not decide to use the extra time to introduce it.

**Comment by micdah** [comment]
This is the specific cask I'm referring to (_and used for reference_): https://github.com/Homebrew/homebrew-cask/blob/master/Casks/parse.rb

I of course respect the wish to separate Core/Cask, but I find it a bit frustrating to commit time to add stuff when existing casks are inconsistent

**Comment by micdah** [comment]
Can you refer me to some documentation for adding formulae in core? I have yet to find any good documentation for contributing, as there is for `homebrew-casks`

**Comment by commitay** [comment]
Yes, some casks are inconsistent. We're much stricter now than in the earlier days of the project.

> Can you refer me to some documentation for adding formulae in core?

https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request
https://docs.brew.sh/Formula-Cookbook
https://docs.brew.sh/Acceptable-Formulae

**Pull request closed without merging**
