### PR TITLE
Add Teleport 1.2.2

### PR DESCRIPTION
**Pull request by johndbritton**
This adds the cask `abyssoft-teleport` which previously existed as `teleport` (renamed to not conflict with the brew package `teleport`) and was removed in https://github.com/Homebrew/homebrew-cask/pull/39558 because the homepage was inactive. The application has since been re-released as open source at https://github.com/abyssoft/teleport.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @johndbritton.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

**Comment by johndbritton** [comment]
I just created a [new release](https://github.com/abyssoft/teleport/releases/tag/v1.2.2) of Teleport, so I also updated this PR. Will work on the `zap` stanza now.

**Comment by johndbritton** [comment]
@miccal I added a `zap` stanza including all relevant files in `~/Library`. Let me know if this needs anything else

**Comment by miccal** [comment]
Thank you @johndbritton.

**Review by miccal — APPROVED** [review]

**Pull request merged**
