### PR TITLE
multiviewer-for-f1 1.17.0

### PR DESCRIPTION
**Pull request by krehel**
* Version bump to 1.17.0

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Review by razvanazamfirei — APPROVED** [review]

**Comment by razvanazamfirei** [comment]
Hi @krehel! Just a heads up that your commit is not signed, and you have [vigilant mode](https://docs.github.com/github/authenticating-to-github/displaying-verification-statuses-for-all-of-your-commits) on.

**Comment by krehel** [comment]
Thanks @razvanazamfirei - going to start signing commits here on forward.

Should've waited until these were merged before ticking it on.  Sorry about that.

**Comment by razvanazamfirei** [comment]
No worries and nothing to apologize for! Sometimes configs get messed up and just wanted to give you a heads-up. :)

**Comment by krehel** [comment]
Appreciate the vigilance! Just performing some housekeeping since I never updated configs and want it to be proper for the long run.

**Pull request merged**
