### PR TITLE
zotero: fix zap stanza to prevent removing user created data

### PR DESCRIPTION
**Pull request by 3719e04**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by yhu266** [comment]
There was a critical mistake in the zap stanza for zotero, where the directory `~/Zotero`, a directory that stores all local documents for Zotero user, was included.

**Comment by yhu266** [comment]
ping @reitermarkus

**Comment by reitermarkus** [comment]
The literal definition of `zap` is that it removes user-generated files and settings for a given application, while `uninstall` doesn't.

**Comment by yhu266** [comment]
> The literal definition of `zap` is that it removes user-generated files and settings for a given application, while `uninstall` doesn't.

By local documents, I meant academic papers, reports, slides, etc. They are managed by Zotero, by usually the users have copyright. I suppose removing an on-going manuscript and other documents, if `zap` was accidentally used, is really bad for Zotero users.

**Review by reitermarkus — APPROVED** [review]

**Pull request merged**
