### PR TITLE
updated cubicsdr (0.1.27)

### PR DESCRIPTION
**Pull request by josh64x2**

### CODE REVIEW

**Comment by adidalal** [comment]
Is there a reason you switched to an alpha release? We prefer stable releases here.

**Comment by josh64x2** [comment]
Hi,

I understand you prefer stable releases. The previous version 0.1.4 was a beta, is over 8 months old, and wasn't particularly stable. Although 0.1.27 is tagged alpha, it is a very large improvement over 0.1.4 so I thought it was appropriate to provide a newer cask.

Thanks!

**Comment by adidalal** [comment]
Took a quick look at the releases page, seems okay to use "alpha" releases as one tagged as stable is pretty far back.

**Comment by josh64x2** [comment]
Ok thanks. I'll keep it in mind next time for other casks. Cheers!

**Pull request merged**
