### PR TITLE
updating sha256 hash for mural 3.0.1 to match for a clean installation

### PR DESCRIPTION
**Pull request by aghassemlouei**
This pull request updates the sha256 hash on a mural cask to match the one directly from the source. 

When attempting to upgrade mural from an older version to 3.0.1 the following error is returned due to a sha256 hashing mismatch: 
```bash
% brew update && brew upgrade 

==> Upgrading 1 outdated package:
mural 2.0.0 -> 3.0.1
==> Upgrading mural
==> Downloading https://download.mural.co/mac-app/Mural-3.0.1.dmg
Already downloaded: /Users/redacted/Library/Caches/Homebrew/downloads/91db7487681552cd9b8bf2654a5d69f1ab30c3a941a5522855f0ee0031a233e0--Mural-3.0.1.dmg
==> Purging files for version 3.0.1 of Cask mural
Error: mural: SHA256 mismatch
Expected: 2bf4ac7c2bbf7c8d98708ffde37763b118667908e7b6c45bfbe5251ef85a2e55
  Actual: 634e07489d9ea1c7383a6a6cc58096556008c1d287c5f49986859d95c4a62f2d
    File: /Users/redacted/Library/Caches/Homebrew/downloads/91db7487681552cd9b8bf2654a5d69f1ab30c3a941a5522855f0ee0031a233e0--Mural-3.0.1.dmg
To retry an incomplete download, remove the file above.
```

Rather than simply ignoring the mismatch I downloaded the file directly from Mural and ran a hash against it to ensure it's accuracy: 
```bash
% wget https://download.mural.co/mac-app/Mural-3.0.1.dmg  

--2024-08-16 12:04:46--  https://download.mural.co/mac-app/Mural-3.0.1.dmg
Resolving download.mural.co (download.mural.co)... 13.107.253.40, 2620:1ec:29:1::40
Connecting to download.mural.co (download.mural.co)|13.107.253.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 180296479 (172M) [application/x-apple-diskimage]
Saving to: ‘Mural-3.0.1.dmg’

Mural-3.0.1.dmg                                                100%[=================================================================================================================================================>] 171.94M  25.2MB/s    in 6.4s    

2024-08-16 12:04:53 (26.7 MB/s) - ‘Mural-3.0.1.dmg’ saved [180296479/180296479]

% shasum -a 256 Mural-3.0.1.dmg 

634e07489d9ea1c7383a6a6cc58096556008c1d287c5f49986859d95c4a62f2d  Mural-3.0.1.dmg
```

### CODE REVIEW

**Comment by aghassemlouei** [comment]
> Please provide a better issue/pull request title and/or description!

Done and done! Hope this helps a few folks better understand what the issue and potential solution are!

**Comment by p-linnane** [comment]
Would you mind reaching out to upstream to confirm if this change is expected? We need to rule out any malicious changes here.

**Comment by aghassemlouei** [comment]
> Would you mind reaching out to upstream to confirm if this change is expected? We need to rule out any malicious changes here.

From the git history it seems like @krehel has been pretty active and it could have been a mistake on their part but I'll reach out to Mural support to validate that there haven't been any security related topics around version 3.0.1.

**Comment by krehel** [comment]
Version updates pass audit locally on our systems when running the update using brew tooling and then again in the CI.

That means this version with this sha256 did exist at some point. Maybe it wasn't a final build, maybe it was changed -- but it would've passed 2 gate checks on the way to merge.

**Comment by p-linnane** [comment]
To add to @krehel's comment: this is typically when upstream uploads a new binary without changing the version number, usually due to fixing a release issue. It is a poor practice, because it causes issues like this and reduces confidence in upstream's release process. Ideally they'd just bump the version number, but here we are.

**Comment by aghassemlouei** [comment]
Reached out to Mural support and they mentioned that they would follow-up via email but haven't received anything from them in over a day. 

Is there a location for a technical point of contact or email to be included to help expedite these sorts of validations?

**Comment by khipp** [comment]
@aghassemlouei A new version has just been released:

```rb
  version "3.0.2"
  sha256 "9e2c6cfbdcefb4ebbc211c3f5ad84a5e333e3e0d7d55bf4204c82b1d9f3d99e1"
```

**Comment by aghassemlouei** [comment]
Looks like @p-linnane's pull request, https://github.com/Homebrew/homebrew-cask/pull/183293, got merged into main and I've got a clean execution on macOS 14.6.1 (23G93):

> mural 2.0.0 -> 3.0.2
> ==> Upgrading mural
> ==> Downloading https://download.mural.co/mac-app/Mural-3.0.2.dmg
> ############################################################ 100.0%
> ==> Backing App 'MURAL.app' up to '/opt/homebrew/Caskroom/mural/2.0.0/MURAL.app'
> ==> Removing App '/Applications/MURAL.app'
> ==> Moving App 'MURAL.app' to '/Applications/MURAL.app'
> ==> Purging files for version 2.0.0 of Cask mural
> 🍺  mural was successfully upgraded!
> 

Thank you again for all that you all do; went ahead and deleted the branch to help keep things a bit cleaner.

**Comment by aghassemlouei** [comment]
Also, finally heard back from Mural support which seems to support the checksum change being valid:

mural-3 0 1-support-response

**Pull request closed without merging**
