### PR TITLE
Create haptickey.rb

### PR DESCRIPTION
**Pull request by chriscn**
Before I am tried to do this locally and it hasn't gone very well so this was all done through GitHub web. I can't see anything wrong so can someone run me through the steps to audit this?

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Hello @chriscn,

Have you checked the [`adding-a-cask` document](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md)? Pretty much everything about this cask is wrong. `version`’s value isn’t quoted, it has `:` in stanzas, there’s no `sha256`, there’s nothing being installed, it uses double quotes instead of single quotes.

Check the linked document as it will help you making a cask from scratch. Give it another go and we’ll continue from there.

**Comment by vitorgalvao** [comment]
Didn’t mean to close.

**Comment by chriscn** [comment]
@vitorgalvao thank you for your reply and having read that document it has helped a lot! Currently improving it and quick question is there anyway I can test a brew cask on its own? Don't really want to override my local version of brew.

**Comment by vitorgalvao** [comment]
You can clone the project and then call that specific `brew`. But for this it’s easier create your cask file and then `brew cask {whatever} /path/to/your/cask`.

**Comment by chriscn** [comment]
@vitorgalvao follow your suggestion and fixed it. Thank you for your help.

**Comment by vitorgalvao** [comment]
* You’re still adding a `:` to stanzas. Don’t.
* `sha256` needs to be set. Run `shasum -a 256` on the downloaded zip.
* Try to add an [`appcast`](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

**Comment by chriscn** [comment]
Appcast is there, as well as the hash. I am unsure what you mean when you say stanzas.

**Comment by chriscn** [comment]
I think the reason why the build is failing is due to trying to get the version into the url and I am not sure how to do that because I don't really program in Ruby. If it is unknown how to fix it the PR can just be closed.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
