### PR TITLE
rambox 2.0.1

### PR DESCRIPTION
**Pull request by miccal**
Continuation of https://github.com/Homebrew/homebrew-cask/pull/119778

### CODE REVIEW

**Comment by miccal** [comment]
Or just install `rambox-ce` from the `homebrew-cask-versions` repository.

**Comment by ric2b** [comment]
I lost all my settings and configured services after the last update, is there a way to recover it or at least prevent it from happening to other people?

**Comment by seebi** [comment]
Interesting - I thought I lost everything as well but just uninstalling rambox and installing rambox-ce healed everything ...

**Comment by ric2b** [comment]
This update should've added as a separate application until an automatic migration was in place, as it is the update is incredibly disruptive. At minimum a message should be displayed on startup with the above workaround.

**Comment by timkgh** [comment]
Disappointing that you are forcing the Pro version on CE users, no questions asked.

**Pull request merged**
