### PR TITLE
Update bespoke from 1.0.0 to 1.1.0

### PR DESCRIPTION
**Pull request by llimllib**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by llimllib** [comment]
I'm not sure how to debug the CI error, it doesn't give any output. When I tried to install the update locally, I got:

```
$ brew install bespoke
==> Downloading https://github.com/BespokeSynth/BespokeSynth/releases/download/v1.1.0/Bespoke-Mac.dmg
==> Downloading from https://github-releases.githubusercontent.com/65670631/2e73d345-a190-4f9d-bcb7-afe2242a0381?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53
######################################################################## 100.0%
==> Installing Cask bespoke
==> Purging files for version 1.1.0 of Cask bespoke
Error: It seems the App Suite source '/opt/homebrew/Caskroom/bespoke/1.1.0/BespokeSynth' is not there.
```

but I also don't know how to debug that. Any help would be appreciated

**Comment by hannesbraun** [comment]
You need to change line 16 from `suite "BespokeSynth"` to `app "BespokeSynth.app"` since the application is now contained in the root directory of the image rather than in another directory together with other accompanying files.

**Comment by llimllib** [comment]
thanks @hannesbraun ! that worked, really appreciate it.

**Comment by llimllib** [comment]
after that change:

```
$ brew install bespoke
==> Downloading https://github.com/BespokeSynth/BespokeSynth/releases/download/v1.1.0/Bespoke-Mac.dmg
Already downloaded: /Users/llimllib/Library/Caches/Homebrew/downloads/7c28dde22cdf4fd9635e2931bcbee598a11e31eebe7edf16d29fbc28f3acc641--Bespoke-Mac.dmg
==> Installing Cask bespoke
==> Moving App Suite 'BespokeSynth.app' to '/Applications/BespokeSynth.app'
🍺  bespoke was successfully installed!
```

**Comment by miccal** [comment]
Thank you @llimllib.

**Pull request merged**
