### PR TITLE
Update alfred to 3.3_799

### PR DESCRIPTION
**Pull request by neutric**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but that’s a prerelese version.

**Comment by neutric** [comment]
Not according to https://www.alfredapp.com/changelog/, unless they changed their naming scheme. But it is not linked from the homepage just yet, which I omitted to check. ;)

**Comment by vitorgalvao** [comment]
> But it is not linked from the homepage just yet, which I omitted to check. ;)

I also checked there. And inside Alfred itself, if you change to the stable channel, you’ll see `3.2.1`.

**Comment by neutric** [comment]
I believe you 100% and closing was justified, I was sloppy.

**Comment by vitorgalvao** [comment]
No need to apologise. Thank you for the continued quality contributions.

**Comment by vitorgalvao** [comment]
Changelog was updated today, with `801` now. Seems like the changelog also gets updated with prerelease versions.

**Comment by neutric** [comment]
It does. From when I started checking (after the last release) up to 799 they added 'Prerelease' after the version, which made me not check, which I should have...

**Pull request closed without merging**
