### PR TITLE
julia: update zap

### PR DESCRIPTION
**Pull request by singularitti**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by singularitti** [comment]
Don't know why it changes the sha256 of intel

**Comment by bevanjkay** [comment]
@singularitti Is the PR only meant to be adding the line to the `zap`?

**Comment by neutric** [comment]
```
% curl https://julialang-s3.julialang.org/bin/mac/x64/1.7/julia-1.7.0-mac64.dmg | sha256sum                                                                                 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 99.2M  100 99.2M    0     0  5848k      0  0:00:17  0:00:17 --:--:-- 6818k
9a7919448e13ba9cefb0f0fe8178ca089333c86e2722f1e482a1dc8c0e2f03b6  -
```

**Comment by bevanjkay** [comment]
@neutric I think the shasum change was an accident

**Comment by neutric** [comment]
@bevanjkay Oh, ah! The late hour and him using `brew bump-cask-pr` (for this?) made me misread and lead me to wrong conclusions.

**Pull request merged**
