### PR TITLE
Add cakebrewjs Latest

### PR DESCRIPTION
**Pull request by shemeshg**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by shemeshg** [comment]
Add cakebrewjs Latest

**Comment by miccal** [comment]
Thank you @shemeshg.

**Review by miccal — APPROVED** [review]

**Comment by cixtor** [comment]
At the risk of sounding dismissing…

I believe this is a low-effort application that should not be included in the public repository. At least not yet, considering the current version of [the app is not even 1.0.0](https://github.com/shemeshg/cakebrewjs/releases/latest), the repository has [less than 100 commits](https://github.com/shemeshg/cakebrewjs/commits/master), it only [has three stargazers](https://github.com/shemeshg/cakebrewjs/stargazers) and, compared to the much more mature [Cakebrew](https://www.cakebrew.com), which this app seems to be based on (except that it is now written in JavaScript rather than Objective-C like the original), is lacking a lot of functionality and UI/UX work.

In its current state, CakebrewJS looks like a weekend project.

May I suggest to revert this merge request and re-submit in a couple of months when it is more feature rich?

**Pull request merged**
