### PR TITLE
Update Timings Version and Metadata

### PR DESCRIPTION
**Pull request by merktassel**

### CODE REVIEW

**Comment by adityadalal924** [comment]
`sha256` (inside appcast) needs an indent to match styling, I think.

Also could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by merktassel** [comment]
Let me know if that takes care of everything.

**Comment by adityadalal924** [comment]
Downloaded the app to check it out...ended up making a zap so you could include that as well (normally goes under the app stanza, after a blank line)

```
  zap :delete => [
                  '~/Library/Preferences/com.mediaateller.Timings.plist',
                  '~/Library/Application Support/Timings',
                  '~/Library/Caches/com.mediaateller.timings',
                 ]
```

(also I think the appcast sha256 needs one more tab indent)

Cheers.

**Comment by merktassel** [comment]
Thanks, I'll have it updated in a minute!

**Comment by merktassel** [comment]
Thanks, I added the zap functionality and corrected the indentation.

**Comment by victorpopkov** [comment]
Thank you for the contribution. It was merged directly as cccf5e9970ff2eb9e782a42c3edd075f28bed091 to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
