### PR TITLE
Update protonmail-bridge from 2.1.0 to 2.1.1

### PR DESCRIPTION
**Pull request by colder-is-better**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
> Closing this PR since target version is a GitHub pre-release.

Livecheck says `protonmail-bridge : 2.1.0 ==> 2.1.1`, though. Not sure why GitHub is being checked for the release-status when another source has been deemed more appropriate in `livecheck`. Ping @miccal.

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/118985

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/118986

**Comment by miccal** [comment]
```
|-> brew bump protonmail-bridge
==> protonmail-bridge
Current cask version   :  2.1.0
Latest livecheck version: 2.1.1
Latest Repology version:  2.1.1
Open pull requests:       none
```

**Pull request closed without merging**
