### PR TITLE
Update qq to 5.2.0

### PR DESCRIPTION
**Pull request by nuomi1**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Update qq to 5.2.0

### CODE REVIEW

**Comment by miccal** [comment]
It seems that the download url does not accept `https`.

**Comment by nuomi1** [comment]
It works in China...

```
➜  ~ curl -I https://dldir1.qq.com/qqfile/QQforMac/QQ_V5.2.0.dmg
HTTP/1.1 200 OK
Server: nnws/1.7.3.7
Date: Fri, 21 Oct 2016 16:00:33 GMT
Content-Type: application/octet-stream
Content-Length: 33240461
Connection: keep-alive
Cache-Control: max-age=600
Expires: Fri, 21 Oct 2016 16:10:33 GMT
Last-Modified: Fri, 21 Oct 2016 08:47:02 GMT
X-Cache-Lookup: Hit From Disktank
```

**Comment by miccal** [comment]
Weird...
```
-bash-4.4.0- /Users/$USER [> curl -I https://dldir1.qq.com/qqfile/QQforMac/QQ_V5.2.0.dmg
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```
```
-bash-4.4.0- /Users/$USER [> curl -I --insecure https://dldir1.qq.com/qqfile/QQforMac/QQ_V5.2.0.dmg
HTTP/1.1 403 Forbidden
Date: Fri, 21 Oct 2016 16:09:19 GMT
Server: PWS/8.1.41.3
Connection: close
```
```
-bash-4.4.0- /Users/$USER [> curl -I http://dldir1.qq.com/qqfile/QQforMac/QQ_V5.2.0.dmg
HTTP/1.1 200 OK
Date: Fri, 21 Oct 2016 16:07:28 GMT
Server: PWS/8.1.41.3
X-Px: rf-ht h0-s33.p3-syd ( h0-s40.p3-syd), ht h0-s40.p3-syd.cdngp.net
Cache-Control: max-age=600
Expires: Fri, 21 Oct 2016 16:07:41 GMT
Age: 587
Accept-Ranges: bytes
Content-Length: 33240461
Content-Type: application/octet-stream
Last-Modified: Fri, 21 Oct 2016 08:47:02 GMT
Connection: keep-alive
```

**Comment by adidalal** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 9cf6b358e3baa36045021edc3ba1a2d09c9eec68. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by xiehao** [comment]
Error: sha256 mismatch
Expected: f396bef6a8f6389170bf14367290fc8ceeb3de26d261c66795e7e18ecbce71ef
Actual: 4a0d67db88c533b98d19b5f163259e765988339bad4c1e7b9bb72e0c5354d7c3

**Comment by adidalal** [comment]
Make a PR to update, please. Directions in reporting a bug.

**Pull request closed without merging**
