### PR TITLE
Add Kawa.app v1.0.1

### PR DESCRIPTION
**Pull request by laughedelic**
Added a cask for [Kawa](https://github.com/utatti/kawa) application.

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by laughedelic** [comment]
Travis fails, because there is a formula with the same name in homebrew-core. But it's completely unrelated. I thought that having it in different taps avoids the name conflict.

**Review by vitorgalvao — DISMISSED** [review]
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

**Comment by vitorgalvao** [comment]
> I thought that having it in different taps avoids the name conflict.

It’s not a conflict; they can coexist. It’s more of a warning so we make sure they are not duplicates.

**Comment by laughedelic** [comment]
@vitorgalvao I see that 59b7cb7 adds `appcast`. Thanks @commitay 👍 
If the name is not conflicting, can we preserve `kawa`? I think it's less confusing this way.

**Comment by laughedelic** [comment]
Force pushes are a bit confusing, but anyway.. Thanks again @commitay for changing the name back.

**Review by commitay — APPROVED** [review]

**Comment by miccal** [comment]
Thank you for your contribution.

**Pull request merged**
