### PR TITLE
Update encryptr from 2.0.0 to 2.1.0

### PR DESCRIPTION
**Pull request by JeffreyBytes**
`version` update; fixed `url`; added `desc`

### CODE REVIEW

**Comment by spaz926** [comment]
Looks like my download url is incorrect. I can't figure out how to get the direct download url.
I was able to download it by navigating here: http://www.spideroak.com/release/Encryptr/osx

**Comment by spaz926** [comment]
I didn't realize we could just use that address instead of a direct link to the file.
Thanks.

**Review by miccal — APPROVED** [review]

**Comment by spaz926** [comment]
@miccal while I have you.. It seems they will be discontinuing the product on March 4th. How does homebrew deal with apps that will be/are discontinued?
Will it get moved into a legacy tap?

**Comment by miccal** [comment]
We add a `discontinued` caveat as explained [here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats-mini-dsl).

**Pull request merged**
