### PR TITLE
Update mactex from 2020.0407 to 2021.0328

### PR DESCRIPTION
**Pull request by chkwon**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by reitermarkus — DISMISSED** [review]

**Review by reitermarkus — APPROVED** [review]

**Comment by albert-github** [comment]
Looks like that on github there are still problems loading the new version, still reports the old version:
```
==> Downloading http://mirror.ctan.org/systems/mac/mactex/mactex-20200407.pkg
==> Downloading from https://mirrors.concertpass.com/tex-archive/systems/mac/mactex/mactex-20200407.pkg
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'mactex' with message: Download failed: http://mirror.ctan.org/systems/mac/mactex/mactex-20200407.pkg
Error: Process completed with exit code 1.
```

see e.g. https://github.com/doxygen/doxygen/runs/2269348798?check_suite_focus=true

**Comment by chkwon** [comment]
In my machine, it works as it should:

```
✦ ➜ brew reinstall mactex     
==> Caveats
You must restart your terminal window for the installation of MacTex CLI tools to take effect.
Alternatively, Bash and Zsh users can run the command:

  eval "$(/usr/libexec/path_helper)"

==> Downloading http://mirror.ctan.org/systems/mac/mactex/mactex-20210328.pkg
==> Downloading from https://ctan.math.illinois.edu/systems/mac/mactex/mactex-20210328.pkg
```

**Comment by derekschinke** [comment]
I think that's an error with CTAN mirrors, some mirrors don't have the 2021 release yet. I retried the command until it found a mirror with 2021

**Comment by albert-github** [comment]
I think too that this might be the case, though the version is out for a week now.

I looked at the machine: http://mirror.ctan.org/systems/mac/mactex (one that crashed recently and there I see there the right (20210328) package present but not the requested (20200407) package. So it looks like the required file for brew install mactex has not arrived there or on GitHub? I'm not an expert where this file should be placed.

How can we get a machine that works? Retrying is not an option for the user as he has no influence what is used by GitHub Actions.

**Comment by albert-github** [comment]
Looks like the last few times I've been either lucky or the situation has stabilized as now the right version is used and no error is given anymore.

**Comment by albert-github** [comment]
Round 2:
```

==> Downloading http://mirror.ctan.org/systems/mac/mactex/mactex-20210328.pkg
==> Downloading from https://mirrors.rit.edu/CTAN/systems/mac/mactex/mactex-20210328.pkg
==> Installing dependencies: ghostscript
==> Downloading https://homebrew.bintray.com/bottles/ghostscript-9.53.3_1.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "ghostscript"
Download failed: https://homebrew.bintray.com/bottles/ghostscript-9.53.3_1.catalina.bottle.tar.gz
Error: Process completed with exit code 1.
```
Looks like this version of ghostscript is not available anymore (I think the newest version is version 9.54.0).

**Pull request merged**
