### PR TITLE
yass 1.5.18

### PR DESCRIPTION
**Pull request by Chilledheart**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your submission @Chilledheart, but we cannot accept it at this time because it does not meet our [minimum notability requirements](https://docs.brew.sh/Acceptable-Casks#rejected-casks):

> + The Cask is for an app that is too obscure. Examples:
>   + An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars).

nor does it meet our  signature verification check that is a requirement for new submissions:

> macOS on ARM requires software to be signed. Please contact the upstream developer to let them know they should sign and notarize their software.

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) .

**Comment by Chilledheart** [comment]
Thanks for the sweet advice. I have been notified by the bots about the same message.

**Comment by Chilledheart** [comment]
for futher reference, i figured out a way to pass all notarize checks (including signature check) and the new dmg is [here](https://github.com/Chilledheart/yass/releases/download/1.5.19/yass-macos-release-arm64-1.5.19.dmg). However, the project is quite small and doesn't pass the other requirement of homebrew-cask.

**Comment by miccal** [comment]
> for futher reference, i figured out a way to pass all notarize checks (including signature check) and the new dmg is [here](https://github.com/Chilledheart/yass/releases/download/1.5.19/yass-macos-release-arm64-1.5.19.dmg). However, the project is quite small and doesn't pass the other requirement of homebrew-cask.

That is great @Chilledheart, and when it meets our minimum notability requirements please re-submit this to `homebrew-cask`, thanks.

**Pull request closed without merging**
