### PR TITLE
Add FormulatePro 0.0.6

### PR DESCRIPTION
**Pull request by von-forks**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Aren’t there any alternate links? Google code will be gone soon, and if the author does not intend on moving it, no sense in adding a soon-to-be-dead cask.

**Comment by alebcay** [comment]
FYI I've started an export of the repo into my personal GitHub account, to be moved under `alehouse` (haven't had to use that in awhile...). Just in case there isn't an alternate, we can still have this placed under `homebrew-unofficial`.

**Comment by von-forks** [comment]
I see various forks outside of Google Code, but nothing that looks like an obvious transfer. In general, the project looks dormant for the last 2-3 years (but I still find the software useful, even on OS X 10.10.x). I've posted on the forums to see if it sparks any discussion about this.

**Comment by vitorgalvao** [comment]
> but I still find the software useful, even on OS X 10.10.x

Doesn’t matter, if it dies soon with no way to officially get it. Let’s wait for the forum replies, then.

**Comment by vitorgalvao** [comment]
@von-forks Any news?

**Pull request closed without merging**
