### PR TITLE
Update valentina-studio to v6.0.13

### PR DESCRIPTION
**Pull request by MatzFan**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/master/Casks/acorn.rb).

**Comment by victorpopkov** [comment]
It seems that the download URL points to the latest version, so I guess the `latest` should be used here instead.

**Comment by MatzFan** [comment]
Good point. Fixed with PR #14994

**Comment by adityadalal924** [comment]
Duplicate of #14994

**Pull request closed without merging**
