### PR TITLE
Update tunnelblick to 3.7.1a,4812

### PR DESCRIPTION
**Pull request by vitorgalvao**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

---

The app changes its own ownership on first run.

### CODE REVIEW

**Comment by commitay** [comment]
Still prompts to change ownership and permissions even with the `postflight set_ownership`.

**Comment by vitorgalvao** [comment]
> Still prompts to change ownership and permissions even with the `postflight set_ownership`.

I meant to do `uninstall_postflight`. I don’t want to change it’s permissions on usage (it does so for security reasons), only make it uninstallable (otherwise it fails). Fixed.

**Comment by commitay** [comment]
Shouldn't it be `uninstall_preflight` so it comes before the `app` is removed?

**Comment by vitorgalvao** [comment]
> Shouldn't it be `uninstall_preflight` so it is called before the `app` is removed?

Yes. Fixed. Thank you.

**Pull request merged**
