### PR TITLE
Create peazip.rb

### PR DESCRIPTION
**Pull request by 3xp0rt**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your submission @3xp0rt, but we cannot accept it at this time because it does not pass our signature verification check that are a requirement for new submissions:

> macOS on ARM requires applications to be signed. Please contact the upstream developer to let them know they should sign their app.

Please consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and if the developers sign their app in the future we would then be happy to consider adding this to `homebrew-cask`.

**Comment by mariobrostech** [comment]
@miccal Does this policy also apply to Intel versions of apps, since they can be ran on Intel Macs without fully disabling Gatekeeper? If so, can this pull request be modified to only contain the Intel build of PeaZip, allowing users of Intel Macs still obtain PeaZip via Homebrew Cask while we wait for the developer to sign future builds for Apple Silicon users?

**Comment by miccal** [comment]
> @miccal Does this policy also apply to Intel versions of apps, since they can be ran on Intel Macs without fully disabling Gatekeeper? If so, can this pull request be modified to only contain the Intel build of PeaZip, allowing users of Intel Macs still obtain PeaZip via Homebrew Cask while we wait for the developer to sign future builds for Apple Silicon users?

Yes, this policy applies to all new submission to Cask.

**Comment by mariobrostech** [comment]
Ok, thanks for the clarification! I feel like this should be emphasized a little more in the FAQ since it seemed like this policy only applies to Apple Silicon apps from what's stated there (at least that was my interpretation when I read it initially).

**Pull request closed without merging**
