### PR TITLE
Upgrade iExplorer.app to 4.0.7.0

### PR DESCRIPTION
**Pull request by Saklad5**
### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit —download {{cask_file}}` is error-free.
- [x] `brew cask style —fix {{cask_file}}` left no offenses.

Fix url in iExplorer.app Cask
Fix appcast checkpoint in iExplorer.app Cask
Update OS requirements

### CODE REVIEW

**Comment by vitorgalvao** [comment]
`audit` failed.

**Comment by Saklad5** [comment]
It was working when I ran the tests before submitting a pull request, but Macroplant happened to update iExplorer _twice_ afterwards before this build was run and failed.

I updated the formula with the new version number, checksum, and checkpoint, but now the curl is returning error 60, “invalid certificate chain” . Meanwhile, Safari had no trouble downloading from the same URL. I’m a bit confused, honestly.

It might just be that this is a transient problem with their servers.

**Comment by Saklad5** [comment]
It appears to be due to a discrepancy between the download URL on their website (cdn.macroplant.org) and their appcast (www.macroplant.org). I’ll commit the fix soon.

**Comment by vitorgalvao** [comment]
Thank you.

**Pull request merged**
