### PR TITLE
fixed bad appname for latest tor-messenger (0.2.0b2)

### PR DESCRIPTION
**Pull request by wickles**
### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by reitermarkus** [comment]
The token has to be changed, too.

**Comment by vitorgalvao** [comment]
And the filename. Doing it now.

**Comment by wickles** [comment]
Given that it was `Tor Messenger.app` up to now, I worry that the change could have been unintentional and could be changed back in a future release. They still refer to it as "Tor Messenger" on the homepage.

**Comment by vitorgalvao** [comment]
> I worry that the change could have been unintentional and could be changed back in a future release.

Wold you mind clearing that up with upstream?

**Comment by wickles** [comment]
I can look into it, sure.

**Comment by wickles** [comment]
Looks like it was intentional. 

https://gitweb.torproject.org/tor-messenger-build.git/commit/projects/tor-messenger/build.osx?id=2600de07f355ea5e544c5ec338f13cd6c1649f23

**Pull request merged**
