### PR TITLE
Update dropbox from 146.4.4836 to 147.4.4800

### PR DESCRIPTION
**Pull request by pranabdas**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by Lillithlilly — COMMENTED** [review]
Looks good

**Comment by bevanjkay** [comment]
@pranabdas Livecheck is failing, which in this instance means that upstream are still distributing the older version using the `url`.

**Comment by pranabdas** [comment]
@bevanjkay I created the PR seeing my Mac updating Dropbox. I will check the upstream, once it is updated, will merge the main to PR branch to re-run the workflow. Thank you.

**Comment by bevanjkay** [comment]
@pranabdas It's better to just ping me here when it is ready and I can restart CI. Running a merge, or pushing an empty commit stops our auto-merge workflows from operating properly.

**Comment by pranabdas** [comment]
Hello @bevanjkay, you may now re-run the workflow. Thank you.

**Review by bevanjkay — APPROVED** [review]

**Pull request closed without merging**
