### PR TITLE
Update futurerestore-gui from 1.97.1 to 1.97.2

### PR DESCRIPTION
**Pull request by eloyaldea**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
Error: Version '1.97.2' differs from '1.98.00' retrieved by livecheck.
```

**Comment by eloyaldea** [comment]
Yes but 1.98.00 is labeled as a prerelease, so I made the PR for 1.97.2 which is stable.

**Comment by carlocab** [comment]
This will need a `livecheck` block then.

**Comment by eloyaldea** [comment]
I don't know how to do that unfortunatelly.

**Comment by bevanjkay** [comment]
Superseded by #121070

**Pull request closed without merging**
