### PR TITLE
Analytics cask purge

### PR DESCRIPTION
**Pull request by vitorgalvao**
Removing unpopular casks. 777 across all repos.

All of these casks had a fair chance, as no unpopular cask on this list is younger (as a cask, not as an app) than a determined threshold. The reduction in casks will make managing them easier, as well as remove casks for dead software. As an example, I’ve grabbed quite a few at random from the list that no longer worked but no one noticed.

Pinging @Homebrew/cask, as well as prolific contributors that might be interested (@core-code @suschizu @ran-dall @brianmorton).

For now (and this might be overzealous), lest someone try to game the system, I’ll keep the criteria private between those pinged, but the method used public information *exclusively*. I’ll add and delete a reply to this thread with the metrics, so that you get pinged by email. I’ll ask that you don’t share the details, and ping me in private if you disagree or if you don’t get the reply via email.

PRs for other repos:
https://github.com/Homebrew/homebrew-cask-versions/pull/7331
https://github.com/Homebrew/homebrew-cask-drivers/pull/945
https://github.com/Homebrew/homebrew-cask-fonts/pull/1832

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Criteria used: casks that have been added over 365 ago, which have less than 3 downloads over the last 90 days (i.e. less than one a month). I’ve chosen that threshold to ignore false positives, like test installs.

In the end, removing unpopular casks is about removing unmaintained casks, so if there are removed casks that you personally use (and hence maintain), do let me know. My method includes an ignore list for those cases.

**Comment by core-code** [comment]
i'm all for reducing maintenance burden, although i think we've made good progress there already in the past year in keeping all casks up-to-date. automerging definitely helps too, despite the current drawbacks. also, i think the less popular casks are often less work, since they don't see new releases anyway. if there are no new releases, the 'cost' of keeping them around is minimal.

however, i can agree that *some* casks are definitely very very unpopular. is this list final? if not, i can correlate this with our own usage data and come up with a list of casks that we'd prefer to see kept in HBC. 

in any case, we'll probably copy a lot of those casks to our server and continue to maintain them there (all above some popularity-threshold).

**Comment by vitorgalvao** [comment]
> i think the less popular casks are often less work, since they don't see new releases anyway.

But it also happens that sometimes they’re dead without us noticing (I’ve found a few, just flipping through the results at random). And if that happens, it’s also possible that some are outdated without us noticing. I could tweak the criteria to not consider casks with `appcasts`, but as we know, those are often unreliable as well.

One advantage of removing casks is that things like `search` and autocomplete should be faster (we do sometimes get complaints of slowness, though there isn’t a lot we can do).

Another advantage of following this method is that we can be less picky regarding what gets included. We’re selective to increase the chance of not including casks that will be abandoned, but if we have a system to auto-remove abandoned casks, the system auto-corrects. That’s why it might be best to not share the criteria for now (and I feel the one I picked is reasonable and will lead to few users complaints).

> is this list final?

By no means. There should, however, be an agreed-upon criteria that can be applied across the board (and be scriptable).

> if not, i can correlate this with our own usage data and come up with a list of casks that we'd prefer to see kept in HBC.

Please do. We’ll decide how to proceed depending on the size of that list.

> in any case, we'll probably copy a lot of those casks to our server and continue to maintain them there (all above some popularity-threshold).

Let’s discuss what that threshold might be, and perhaps we can bring them in line with each other.

**Comment by ran-dall** [comment]
I would tend to think it would be more beneficial to remove casks that aren't popular (and some of these haven't received an update in years). I'm sure if something changes or gets updated (and the cask is requested by users); we could always re-add the cask. Generally IMO the 'pros.' outweigh the 'cons.', so I'm all for it. I think periodical a 'purge' is an outstanding idea @vitorgalvao.

> I could tweak the criteria to not consider casks with `appcasts`, but as we know, those are often unreliable as well.

I couldn't agree more; however, they do seem to be getting a little better lately.

**Comment by vitorgalvao** [comment]
> I'm sure if something changes or gets updated (and the cask is requested by users); we could always re-add the cask.

That’s my thought process as well. I’m betting that for most of these we’ll never hear any complaints because even the person who added them has since stopped using it.

And if a periodic purge lowers the entry barrier, we might get more satisfied users than angry ones, overall.

It will also take out the guesswork of what to approve or not, which has been on my mind for a few months.

**Comment by claui** [comment]
> It will also take out the guesswork of what to approve or not, which has been on my mind for a few months.

@vitorgalvao Very good point.

**Comment by amyspark** [comment]
LGTM, less cruft is easier maintenance.

@vitorgalvao and @core-code -- can you check in your datasets the top 95% of Casks by downloads and check how many are left out? (it's probably a non-trivial amount, but I'd like to see the overlap with this pull request).

Also, it'd be better (for the sake of merging) if we squashed this down to a single prune commit, don't you think? The total is 513 and counting 😰

**Comment by core-code** [comment]
> But it also happens that sometimes they’re dead without us noticing 

how do you define dead? i run a 'brew cask fetch' for all casks (that we track, i.e. 3654 of them) every month, and send pull requests to delete for cask that are offline a few months. i do not try to install them however.

in any case, lets talk some numbers ;-)

i've had a look which ones of those 777 casks-to-delete we use. we use 455 of them (16 from the driver repo, the rest from main - none of the versions-casks to delte are used by us, and we've never used anything font-related).

now regarding the popularity of those 455 casks, i agree that a LOT of them are very unpopular. 
however for many other casks, i cannot reproduce the unpopularity at all. e.g. "snapheal-ck" is on spot #292 of our popularity ranking that includes more than 40.000 apps. note that our stats are not totally accurate because we try to track as little data as possible (privacy!) and are skewed depending on how many updates an app has, but those numbers still a good indicator for popularity.

i've attached the text file that contains the casks names, along with how many users of our 'MacUpdater' have or had this app installed. i think it would be /great/ if all casks that have a usage-count larger than 30 could be kept, which is 80 of them.

"personally" we'll want to keep any cask that has more than 10 users, i'll just copy every one that is deleted with more than 10 users to our server. this is 172 of the currently suggest to-delete-list.

i am wondering why our stats are largely the same for many casks, but differ wildly for other apps....
[casks-to-delete-popularity.txt](https://github.com/Homebrew/homebrew-cask/files/3163479/casks-to-delete-popularity.txt)

**Comment by vitorgalvao** [comment]
> for many other casks, i cannot reproduce the unpopularity at all. e.g. "snapheal-ck" is on spot #292 of our popularity ranking

That one is particularly bad for us:

```
snapheal-ck (added 553 days ago)
30 days: n/a
90 days: n/a
365 days: 2 (#6613)
```

Its spot is 3000 places lower than the total amount of casks you track! Talk about unpopular. There is, however, the small possibility that it is a popular cask but all its users have disabled analytics. But either way, even if we have more users than we think and you have less than you think, the difference would still be staggering.

> i think it would be /great/ if all casks that have a usage-count larger than 30 could be kept, which is 80 of them.

That sounds reasonable. It’s no secret that I don’t mind bending the rules for maintainers and good contributors (after all, if the point of the rules is to make things manageable, it makes sense to conform to the methods of the people who manage them), and you’ve definitively been a positive force to the project.

If you can share, does “30” mean that in rough terms about 30 of your users have the software?

> personally" we'll want to keep any cask that has more than 10 users, (…) this is 172 of the currently suggest to-delete-list.

That means going from 777 to 605. Still sounds good for a first pass. If no one objects, I don’t mind trimming it down in favour of keeping more. Right now I’m more interested in knowing if there’s a consensus regarding the occasional purge (by submitting the PR we can discuss with real data, instead of speculating) than the exact metrics. I’m perfectly willing to be flexible on those.

Is there some kind of up-to-date stats list I could access from your side, so that whenever the script is run it auto fetches your latest data and whitelists the casks with 10 or more users? Or do you have to generate it manually every time? If it’s automated, we can further discuss the best format.

Self-interest question, while we’re on the subject. Do you have [`fog`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/fog.rb)? If so, would you mind sharing the stats? It’s likely it doesn’t have many downloads, but since It’s also likely I’ll retire it after 10.15/Marzipan, this might be the last chance to ask.

**Review by reitermarkus — APPROVED** [review]

**Comment by claui** [comment]
👍 on the occasional purge.

Also, 👍 on going for 605. In case of doubt or ambiguity, the path of least net hassle may be to just keep the cask.

**Comment by suschizu** [comment]
hey @vitorgalvao - I agree with @core-code s proposal to delete the 605 but would it be possible to make the purge after the weekend? 😬

**Comment by core-code** [comment]
> That one is particularly bad for us

there could be two causes
• we track what is already installed, you track what gets newly installed (do you numbers also include upgrades?). if am app was popular a few years ago, many people might still have it installed while few people installed it recently
• i think we have different demographics in the user base. i think HBC has more tech-savvy users while we have 'normal' users
that said, i still find it very weird that the numbers differ so wildly in some, few cases.

> That sounds reasonable. It’s no secret that I don’t mind bending the rules for maintainers and good contributors (after all, if the point of the rules is to make things manageable, it makes sense to conform to the methods of the people who manage them), and you’ve definitively been a positive force to the project.

thanks a lot! this would be great indeed ;)

> If you can share, does “30” mean that in rough terms about 30 of your users have the software?

yes. we don't have nearly as many users as HBC, so the numbers are sadly low in some cases. ;/

> That means going from 777 to 605. Still sounds good for a first pass.

that would be even better, and i am all for it ;) just for the record, i don't want to suggest anything that goes against HBC interests, so if you want to delete more, its not a problem for me. still, deleting 600 for a start, and reconsidering deleting more later, sounds like a good plan.

> Is there some kind of up-to-date stats list I could access from your side, so that whenever the script is run it auto fetches your latest data and whitelists the casks with 10 or more users?

nothing is publicly available just yet, but i could work on that next week.

> "personally" we'll want to keep any cask that has more than 10 users

note that i spoke too soon here. we'll want to keep any cask that has more than 10 users AND does not have a valid, up-to-date sparkle feed. so, if you want i can trim down the list of casks-to-keep even more, removing those with sparklefeed.  unless  you prefer to keep those casks anyway, because my numbers have suggested they might not be that unpopular after all

> Self-interest question, while we’re on the subject. Do you have fog? 

sorry, just 14 installations, spot 10.000 of 40.000 apps ;/

> make the purge after the weekend?

++ ;)

**Comment by brianmorton** [comment]
I didn't receive an email of your methodology, but I generally support removing unpopular casks periodically! I am probably on the stricter side of the what would constitute unpopular, as anyone that wants to remain with HBC would have incentive to keep their project out of the bottom X casks ;)

**Comment by core-code** [comment]
personal motivations aside, i don’t think i can agree with the general sentiment of “anything unpopular should be removed”. i think we should differentiate here and put it in relation to the work involved with the cask. why remove an unpopular cask that has seen no update in a few years anyway and wont see an update until it goes offline in a few years? there is zero “cost”
of any kind involved here anyway. however, if if a cask necessitates more work than the popularity warrants, we should remove (or, at least, set it to version: latest, if possible) in a heartbeat. i “painfully” remember the “manager” cask that had multiple version updates per day (and probably no single user) here specifically ;)

that said, i see the upside of having strict rules, that would also allow us to lower the barrier-of-entry for new casks.

**Comment by vitorgalvao** [comment]
I wrote this reply hours ago, and just now noticed I forgot to post it.

> would it be possible to make the purge after the weekend?

Sure.

> do you numbers also include upgrades?

An `upgrade` is an `uninstall` followed by an `install`, so I expect they are counted as well.

> i don't want to suggest anything that goes against HBC interests

Doesn’t even cross my mind. I know you’re respectful of not wanting to interfere with the project’s direction.

> nothing is publicly available just yet, but i could work on that next week.

Thank you. I don’t even need to see your stats or notes to which repo a cask belongs (the `=` that seem to represent the `cask-drivers` repo). A note at the top about the criteria on a line that starts with `#` (so I can filter it out) would suffice, so we always know the rules. So a text file like:

```
# MacUpdater casks with 10 or more users
onecask
anothercask
thirdcask
```

If you set up a public link but would rather I keep it secret in the script, please do say.

How often would it be updated? Once every 30 days might be enough.

>  unless you prefer to keep those casks anyway, because my numbers have suggested they might not be that unpopular after all

Sure. If they have working feeds, why not.

> sorry, just 14 installations, spot 10.000 of 40.000 apps ;/

It was expected:

```
fog (added 1250 days ago)
30 days: 12 (#1976)
90 days: 35 (#2031)
365 days: 102 (#2008)
```

Thank you for sharing.

**Comment by vitorgalvao** [comment]
@core-code Are we set on the list rules for casks to keep from your side (with over 10 users or less than 10 users but working feeds)?

No rush. I’ll hold off on this PR until we have the updated list.

**Comment by core-code** [comment]
ok. i've finalized a list of of those casks that would be great to keep for the time being here - its 95 casks:
[caskstokeep.txt](https://github.com/Homebrew/homebrew-cask/files/3173864/caskstokeep.txt)

the upper 8 entries are from the drivers repo, the rest are from the main repo. this brings the purge down from 777 to 695 which is still a decent purge ;) note that (as discussed) i've not added any casks for which we have sparkle feeds to this list-to-keep, so you may still want to look at top entries from the list i posted last time, as some things like 'textsoap' are still planned to being deleted despite being quite popular according to my numbers.

also, to automate these things more in the future, i've uploaded:
http://macupdater.net/cask-repair/stats/casks-stats.txt
this contains 3288 casks and their popularity ... 369 casks that we track don't even show up because they haven't ever been seen in-use.

also:
http://macupdater.net/cask-repair/stats/casks-without-feed-and-more-than-10-users.txt
http://macupdater.net/cask-repair/stats/casks-without-feed-and-more-than-30-users.txt

these contains the lists of casks that are fairly popular but dont have any sparkle feeds, so it would be great it we could keep the casks contained in them away from any automated purges for the time being. if you need changes to their format, just let me know. for the time being they just contain the cask names, possibly prefixed with "versions/" or "drivers/" for the other repositories

i can refresh those lists with the click of a button and will try to do so every week.

**Comment by vitorgalvao** [comment]
> i've not added any casks for which we have sparkle feeds to this list-to-keep

Please do. If you make a `casks-with-feeds-and-casks-with-more-than-10-users.txt`, that covers all the use cases you wish to keep, correct? That’s the file I’d like to reference directly. Also, it’s convenient if the prefixes (`drivers/`, `versions/`) are removed, as my code works with just the cask name.

> i can refresh those lists with the click of a button and will try to do so every week.

Once every month should be enough. The script takes a while to finish (transversing the repo for the added date takes some time) so I don’t expect to be running it more frequently than that.

**Comment by core-code** [comment]
> Once every month should be enough. 

ok, will do so, thanks.

> Please do. 

i can do so, but i think there has been some miscommunication here. we don't really use those casks that have working sparkle feeds anyway. we only do `cask-repair`s for them because it isn't much work anyway, but we only use them as a fallback when the feed is offline, and i don't care much if they are deleted. i can provide the file you've requested if you want to keep those casks because of our popularity stats, but from our end there is no need to have those casks stay.

**Comment by vitorgalvao** [comment]
> i can do so, but i think there has been some miscommunication here.

Ah, yes, I did misunderstand. Alright, I’ll be using the `casks-without-feed-and-more-than-10-users.txt` list. If you’d rather keep the repo prefixes in the names (as it is, with `drivers/` and `versions/`) it’s fine, as I’m removing those in the script.

I’ll be merging the PRs for the versions and fonts repo now since there was no overlap, and will rerun the script for the main repo and drivers.

**Comment by vitorgalvao** [comment]
> if i should remove the drivers/versions prefix (…) just let me know.

If it’s all the same to you, then I prefer without the prefix, yes.

**Comment by core-code** [comment]
no problem, i've adjusted the scripts and uploaded the updated files

**Comment by vitorgalvao** [comment]
Rerunning the script now. I’ll resubmit and merge when it’s done.

**Comment by svenjacobs** [comment]
Not really sure how I feel about (regular) purges. I just noticed that the cask for [Function Pilot](http://tinybird.com/mac/function-pilot.html) that I [contributed](https://github.com/Homebrew/homebrew-cask/pull/9840) in 2015 has been purged. I just wanted to reinstall the application through Homebrew.

**Comment by vitorgalvao** [comment]
@svenjacobs You’re free to resubmit the cask. Assuming it still fits the inclusion rules as they are now, it will be reaccepted.

**Comment by svenjacobs** [comment]
@vitorgalvao I might do this but it doesn't make any sense if the cask is purged again in the future due to unpopularity.

**Comment by vitorgalvao** [comment]
It will be exempted from such considerations for at least one year.

**Comment by brianbrownton** [comment]
Isn't that what taps are for?

**Comment by core-code** [comment]
i don't want to sound negative or rehash old arguments but i am not sure if we are taking the best approach here.

the objective of purging casks is to reduce burden on the maintainers. however what we are effectively doing now is removing casks (even if they are effectively zero-maintainance!) and replace them with other casks that are even less popular and often more work than those that have been purged to make 'room for them'. 

i feel this is a LOT more work than doing neither purging nor adding new (and unpopular!) casks all the time. 

consider a recent addition - 'eaccess'.

according to cask stats:

```
eaccess
30 days: 1 (#5360)
90 days: 1 (#6394)
365 days: 6 (#5995)
Age: 123 days (added 2020, March 05)
```

i guess that single 90 day download is from me in order to help keep the cask updated.

according to our own [CoreCode] database this app is NOT in the list of the 60.000 most popular Mac apps. even according for demographics differences (which i am sure exist), i can guarantee that this is less popular than nearly all of the purged casks have ever been. and it is versioned and requires actual maintainance in contrast to a lot of purged casks. its just one example but i feel many of these cases occured recently.

purging only those casks that require actual maintaince (either having a version stanza or something like more than 1 PRs per year could be a metric) would make sense, no? also i don't think casks like 'eaccess' that have absolute zero popularity should have ever entered the main repository. i'd be happy to provide a weekly updated list of the most popular apps (any count you wish) if it helps with making sure we don't add 'zero popularity stuff'.

just my 2 cents. sorry for the noise if there is no interest in revisting this.

**Comment by vitorgalvao** [comment]
> i am not sure if we are taking the best approach here.

I agree. I’ve been skipping the purge days.

> purging only those casks that require actual maintaince would make sense, no?

Yes. That’s a next step, though I still have to think of the metrics to use.

> having a version stanza

We encourage the use of version stanzas, so I wouldn’t want to make it a metric for removal.

> also i don't think casks like 'eaccess' that have absolute zero popularity should have ever entered the main repository.

That can be a tough call sometimes. Many of the submissions we get are for apps that are unpopular now but will be popular soon (e.g. new releases with a successful Hacker News or Product Hunt launch). That said, if they were hosted on Github we’d apply the popularity metric (and perhaps give it a few days), so your point still stands.

> i'd be happy to provide a weekly updated list of the most popular apps (any count you wish) if it helps with making sure we don't add 'zero popularity stuff'.

That might work. I guess two things would be helpful, always on the same URLs:

* A txt or csv file, so it’s a quick searchable reference for maintainers. Ideally: app name, homepage, (something more?)
* A webpage (so users can check before submitting). Ideally: app icon, app name, homepage, (something more?).

We should also make sure to point out those are guidelines and that apps are can still:

* Be included despite not being on the list, if a maintainer has a reasonable expectation it will be maintained.
* Be excluded despite being on the list, if by its complexity a maintainer predicts the maintenance burden will be higher than the app’s popularity.

**Comment by brianbrownton** [comment]
Is it not possible to have somebody that cares enough (like @core-code or others) maintain a tap of unpopular/borderline casks and only introduce them to the main homebrew cask repo once they pass certain public metrics (github popularity, downloads, whatever)? Or there could even be an official borderline/unpopular cask repo that is not actively maintained except by third party contribs until they are popular enough to graduate to the main repo?

**Comment by core-code** [comment]
> That might work. I guess two things would be helpful, always on the same URLs:

i think all that data should be available and providing it shouldn't be too difficult

> maintain a tap of unpopular/borderline casks

we have a very small collection of 75 casks on our server. unfortunately they are not a 'tap' and the vast majority are either unversioned or updated by a script.

> Or there could even be an official borderline/unpopular cask repo 

if there was such a thing i'd be happy to spend a bit more time on those casks to maintain them on this repo so that its (more) helpful for others. i am not sure if it is worth though if the casks have been 'culled' exactly because there is no interest in them.

**Comment by ran-dall** [comment]
> Is it not possible to have somebody that cares enough (like @core-code or others) maintain a tap of unpopular/borderline casks and only introduce them to the main homebrew cask repo once they pass certain public metrics (github popularity, downloads, whatever)?

I do this on my tap. Currently, I only pull in things I find interesting but I probably should pull in other things as well. The benefit of my tap is that it can provide ML coverage for updates (at least that's the plan, I don't run it often but I could). That said, so far out of the few things I pulled in, nothing has really been deemed worthy to graduate to the main tap...yet.

**Comment by vitorgalvao** [comment]
We could make an analogy between open-source and gardening. Some people bring new seeds (new casks), others tend to the plants (maintaining them). Some do both, and we all split the effort for a healthy garden—sometimes I take care of your plants, other times you take care of mine.

The trouble with unpopular casks is they’re unmaintained. A user might submit them and never touch it again or even stop using the software (we have a lot of sporadic and one-time-only committers). If nobody else uses it, what the first user planted was a weed: “a wild plant growing where it is not wanted and in competition with cultivated plants”. It takes time away from the other gardeners and makes the whole project less good.

If an HBC maintainer (or prolific contributor) is the only user of a cask but they keep it up to date, I have no quarrel with keeping it in. Maintainers are people who made a commitment to the garden and have the knowledge and interest for keeping other people’s plants within reasonable effort. If they want to keep one of their own around, I trust they’ll care for it even if no one else does, or remove it if they no longer want it.

There’s no such assurance with random contributors, hence why I think those are justified to having a higher barrier to entry.

All this to say I don’t think an official repo for unpopular casks would make any sense. The whole point of keeping casks out is making everything else maintainable; such a repo would be extra work for zero gain.

**Comment by brianbrownton** [comment]
Totally agree with everything @vitorgalvao said up to this point:

> All this to say I don’t think an official repo for unpopular casks would make any sense. The whole point of keeping casks out is making everything else maintainable; such a repo would be extra work for zero gain.

i think this is the benefit of the "official" unpopular repo - there are no guarantees or expectation of maintenance, but there are some people that do enjoying gardening weed ;)

And if a weed turns into a non-weed, it can be moved to the main garden.

**Comment by vitorgalvao** [comment]
> there are no guarantees or expectation of maintenance

If it’s an official repo, it doesn’t matter if there are no guarantees—there will be expectation.

Again, if it’s official there’s no point to it. Official means maintainers will still spend time on it, so might as well have those casks in the main repos.

An extra repo is by itself extra work. It’s much simpler to accept something and remove it if it doesn’t work out than to add every garbage to a dump and move it to the main repo if it turns out it shines. Not to mention all the duplicate requests we’d get, and having to cross-check with that repo every time, and always having to point people to the other repo.

Your suggestion creates more work, when the goal is to have less.

**Comment by brianbrownton** [comment]
Understood, thanks for explaining!

**Comment by svenjacobs** [comment]
In case anyone came here looking for a cask for [Function Pilot](http://tinybird.com/mac/function-pilot.html): I now added it to my [personal tap](https://github.com/svenjacobs/homebrew-repo/blob/main/Casks/function-pilot.rb).

**Pull request closed without merging**
