### PR TITLE
adding keybase checksum

### PR DESCRIPTION
**Pull request by cromulus**
It is crypto, after all.

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> It is crypto, after all.

Agreed, though this means the cask can break often. If that happens, we’ll need to revert this.

**Review by vitorgalvao — APPROVED** [review]

**Comment by miccal** [comment]
Would it make sense to add an `appcast` from https://github.com/keybase/client/releases to justify having a `version`?

**Comment by vitorgalvao** [comment]
> @vitorgalvao would it make sense to add an `appcast` from https://github.com/keybase/client/releases to justify having a `version`?

Yes! Thank you for finding it. Added it.

**Review by vitorgalvao — APPROVED** [review]

**Comment by miccal** [comment]
> Thank you for finding it.

You welcome, and thank you @cromulus for your contribution.

**Pull request merged**
