### PR TITLE
releasing: typographical fixes

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Comment by jawshooah** [comment]
:+1:  On this and the other typographical fixes.

For the future, I think it'd be best to merge similar changes like these into a single PR. No need to have one per-file.

**Comment by vitorgalvao** [comment]
> For the future, I think it'd be best to merge similar changes like these into a single PR. No need to have one per-file.

Agreed, but I did most of those via the web interface, hence the multiple PRs.

**Comment by jawshooah** [comment]
Gotcha, makes sense.

**Comment by vitorgalvao** [comment]
Merged as ce03169abea97bda05491ea94cc5ad713ff0fd47.

**Pull request closed without merging**
