### PR TITLE
Update musescore from 3.4.2 to 3.5.0

### PR DESCRIPTION
**Pull request by lpla**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by miccal** [comment]
I am guessing that the line:
```
exec '#{appdir}/MuseScore #{version.major}.app/Contents/MacOS/mscore' "$@"
```
needs to be changed to:
```
exec '#{appdir}/MuseScore #{version.major_minor}.app/Contents/MacOS/mscore' "$@"
```
also?

**Comment by lpla** [comment]
You are right, I missed that one. Thank you!

**Comment by core-code** [comment]
i am really unhappy with that shortversion stuff. can we use a solution here that is more in line to what we've used in other casks?

basically if the url changes we've just adjusted the URL stanza instead of trying to find a system that will work in any way the authors might change in the future. if we really want to try to do something that is 'future proof' i suggest a single-line solution like this

`  url "https://github.com/musescore/MuseScore/releases/download/v#{version.chomp(".0")}/MuseScore-#{version}.dmg"
`

**Comment by lpla** [comment]
I am okay with that. I am not familiar with Ruby lang and code style in other brew formulas, so if this solution is better, I will use it.

I know that Musescore devs changed their numbering format in Github tags, release names and app title along time, but looks like the current format is the one they kept most time.

**Comment by core-code** [comment]
thanks!

**Pull request merged**
