### PR TITLE
Add Minishift v0.5.0

### PR DESCRIPTION
**Pull request by lburgazzoli**
### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:
- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but since this is a CLI open-source tool, it should first be submitted to Homebrew. Only if refused there will we consider it here.

**Comment by lburgazzoli** [comment]
That was my first thought but I found minikube here too which is essential a similar thing. should I still submit the pr against homebrew?

**Comment by vitorgalvao** [comment]
> That was my first thought but I found minikube here too which is essential a similar thing. should I still submit the pr against homebrew?

Yes. This is a recent development and decision from our merger with homebrew. There are a lot of casks that need to have the rule retroactively applied to them.

**Comment by lburgazzoli** [comment]
Thx, I will

**Comment by lburgazzoli** [comment]
@vitorgalvao can I submit a binary cli to homebrew ? [build-requirements](https://github.com/jimmidyson/minishift#build-requirements) are quite huge.

**Comment by vitorgalvao** [comment]
You cannot, *but* it might make more sense to first open an issue explaining that to see if they find it worth adding there or not.

**Comment by lburgazzoli** [comment]
I found out some discussion about minikube:
- https://github.com/Homebrew/homebrew-binary/pull/343
- https://github.com/Homebrew/homebrew-core/pull/2417

**Comment by vitorgalvao** [comment]
> I found out some discussion about minikube

Use them in your post to HB if you find them relevant. I’m not going to make the decision if it’s appropriate or difficult to add to HB or not. Until you get a reply from opening an issue PR on HB, posting here does not advance the conversation.

**Comment by adidalal** [comment]
Appcast/version looks like it needs an update, but otherwise cask is good

**Comment by lburgazzoli** [comment]
@adidalal done

**Pull request merged**
