### PR TITLE
Update Postman to 9.0.5

### PR DESCRIPTION
**Pull request by Mazorius**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by gdams** [comment]
@Mazorius it doesn't look like `9.0.5` has been shipped yet?

**Comment by Mazorius** [comment]
In my local postman installation today it was explicitly requested to update to 9.0.5 .

After upgrading this is displayed:
```
You are up to date!
Postman v9.0.5 is the latest version.
```

I would say if the application asks it is official or not :-)

**Comment by gdams** [comment]
Hmm yeah just checked the release notes. We'll have to work out what's wrong with the livecheck

**Comment by gdams** [comment]
So it seems that the Postman folks need to update https://dl.pstmn.io/download/latest/osx because it's still serving up 8.12.4

**Comment by gdams** [comment]
I've raised https://github.com/postmanlabs/postman-app-support/issues/10345 to see if the postman team can sort out the `latest` URL

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/112632

**Pull request closed without merging**
