### PR TITLE
Firefox: Add missing locales

### PR DESCRIPTION
**Pull request by adunning**
This updates the list to include recently added translations, providing for all those listed at <https://www.mozilla.org/firefox/all/>. Generated using the list of checksums at <http://releases.mozilla.org/pub/firefox/releases/63.0.1/SHA256SUMS>

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by adunning** [comment]
Not sure why it's failing on `ach`; works on my system.

**Comment by reitermarkus** [comment]
If you are not actually using them, please don't add more, otherwise the Cask will only become harder to maintain. Thanks!

**Comment by adunning** [comment]
I am actually using one of these. Given that the entire list of SHA256 hashes are given in a file for each release, would there be some way to automate updating it?

**Comment by vitorgalvao** [comment]
Closing.

@adunning If you are using one of the languages, please add just that one.

**Pull request closed without merging**
