### PR TITLE
Update anka software + added build cloud controller and registry now that uninstaller is fixed

### PR DESCRIPTION
**Pull request by NorseGaud**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
```
❯ brew audit --cask Casks/anka-virtualization.rb                              
audit for anka-virtualization: passed

❯ brew audit --cask Casks/anka-build-cloud-registry.rb 
audit for anka-build-cloud-registry: passed

❯ brew audit --cask Casks/anka-build-cloud-controller-and-registry.rb 
audit for anka-build-cloud-controller-and-registry: passed
```

- [x] `brew style --fix {{cask_file}}` reports no offenses.
```
❯ brew style --fix Casks/anka-virtualization.rb      

1 file inspected, no offenses detected

❯ brew style --fix Casks/anka-build-cloud-registry.rb

1 file inspected, no offenses detected

❯ brew style --fix Casks/anka-build-cloud-controller-and-registry.rb 

1 file inspected, no offenses detected
```

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).

> It was rejected due to a bad uninstaller in https://github.com/Homebrew/homebrew-cask/pull/89249

- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

```
❯ brew install --cask Casks/anka-build-cloud-controller-and-registry.rb 
Updating Homebrew...
==> Caveats
Installing anka-build-cloud-controller-and-registry means you have AGREED to the license at:
  https://veertu.com/terms-and-conditions/

==> Downloading https://d1efqjhnhbvc57.cloudfront.net/AnkaControllerRegistry-1.12.0-65cba643.pkg
Already downloaded: /Users/nathanpierce/Library/Caches/Homebrew/downloads/40cd352a973ced32f122cae68c20c6d269ff8d960a2e6ba77d1b673c245b824a--AnkaControllerRegistry-1.12.0-65cba643.pkg
==> Installing Cask anka-build-cloud-controller-and-registry
==> Running installer for anka-build-cloud-controller-and-registry; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is Anka Controller And Registry
installer: Installing at base path /
installer: The install was successful.
🍺  anka-build-cloud-controller-and-registry was successfully installed!

❯ brew uninstall --cask Casks/anka-build-cloud-controller-and-registry.rb
==> Uninstalling Cask anka-build-cloud-controller-and-registry
==> Running uninstall script /Library/Application Support/Veertu/Anka/tools/controller/uninstall.sh
]] Stopping Cloud
 /usr/local/bin/anka-controller stop
]] Unloading service & Cleaning up files
 rm -f /Library/Application Support/Veertu/Anka/anka-controller/AnkaControllerAcknowledgements.pdf
 rm -f /Library/Application Support/Veertu/Anka/anka-controller/AnkaControllerEULA.pdf
 rm -f /Library/Application Support/Veertu/Anka/bin/anka-controller
 rm -f /Library/Application Support/Veertu/Anka/tools/controller/uninstall.sh
 launchctl unload /Library/LaunchDaemons/com.veertu.anka.controller.plist
 rm -f /Library/LaunchDaemons/com.veertu.anka.controller.plist
 rm -f /usr/local/bin/anka-controller
 rm -f /usr/local/bin/anka-controllerd
]] Cleaning up directories
 rmdir /Library/Application Support/Veertu/Anka/anka-controller
rmdir: /Library/Application Support/Veertu/Anka/anka-controller: Directory not empty
 rmdir /Library/Application Support/Veertu/Anka/registry
rmdir: /Library/Application Support/Veertu/Anka/registry: Directory not empty
 rmdir /Library/Application Support/Veertu/Anka/tools/controller
 rmdir /Library/Logs/Veertu/AnkaController
rmdir: /Library/Logs/Veertu/AnkaController: Directory not empty
]] Success
==> Purging files for version 1.12.0-65cba643 of Cask anka-build-cloud-controller-and-registry
```

### CODE REVIEW

**Comment by NorseGaud** [comment]
Please delay review. I might need to make some other changes.

**Comment by NorseGaud** [comment]
Let's put this on hold. I need to edit the description of the build-cloud-controller-and-registry and I'm not at work right now. Please don't merge yet.

**Comment by NorseGaud** [comment]
@miccal, please add macos back to the descriptions. We don't offer non-macOS virtualization with Anka.

**Comment by miccal** [comment]
> @miccal, please add macos back to the descriptions. We don't offer non-macOS virtualization with Anka.

[We do not allow "macOS" to be part of the `desc` stanza.](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/desc.md)

**Comment by miccal** [comment]
Thank you @NorseGaud.

**Review by miccal — APPROVED** [review]

**Pull request merged**
