### PR TITLE
Update accurics from 1.0.19 to 1.0.20

### PR DESCRIPTION
**Pull request by williepaul**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by williepaul** [comment]
Good to go.

**Comment by williepaul** [comment]
Looks like the build failure could be a caching issue. I verified the correct data is in place. We may just have to wait, but I'll check if I can invalidate the cache on this side.

**Comment by williepaul** [comment]
OK looks like that went through, the current error now is due to cloudflare's bot protection on https://www.accurics.com:


Run brew audit --cask --appcast --online './Casks/accurics.rb'
==> Downloading https://downloads.accurics.com/cli/1.0.20/accurics-cli.dmg
Already downloaded: /Users/runner/Library/Caches/Homebrew/downloads/8e9e6098698f50762e7b8512d6cc5a73768e26981dfeae94df4c40daa4ebd458--accurics-cli.dmg
audit for accurics: failed
Error: 1 problem in 1 cask detected
 - The homepage URL https://www.accurics.com/ is not reachable (HTTP status code 403)
Error: The homepage URL https://www.accurics.com/ is not reachable (HTTP status code 403)

**Review by bevanjkay — APPROVED** [review]
Thanks @williepaul

**Comment by williepaul** [comment]
Much appreciated @bevanjkay !

**Pull request merged**
