### PR TITLE
Update flash-npapi to 28.0.0.161

### PR DESCRIPTION
**Pull request by tiiiecherle**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by timsutton** [comment]
I think it's been a while since I've looked at Travis output for cask PRs, but I'm not clear on why this build failed.

**Comment by ondrejfuhrer** [comment]
It seems like invalid uninstall script. There is a leftover after the uninstall script runs.

**Comment by timsutton** [comment]
I see - thought that may have been it. That's a bit surprising, because the fpsaud launchdaemon has been around forever.

**Comment by timsutton** [comment]
See the build from the previous merged PR for this cask:

https://travis-ci.org/caskroom/homebrew-cask/builds/326727881?utm_source=github_status&utm_medium=notification

```

**Comment by timsutton** [comment]
I guess a similar fix for `com.adobe.fpsaud` could be done as was done here: https://github.com/caskroom/homebrew-cask/pull/43707/commits/f562127135d9ff18dd79f8333de1506d0055f6d8

**Comment by commitay** [comment]
> See the build from the previous merged PR for this cask ...

The "leftovers" check is relatively new and the first version didn't error out correctly.

**Pull request merged**
