### PR TITLE
updated blackvue-viewer (latest)

### PR DESCRIPTION
**Pull request by adidalal**

### CODE REVIEW

**Comment by adityadalal924** [comment]
@vitorgalvao `cask-repair` shouldn't override a shasum manually set as `:no_check` (ie. this example)

**Comment by vitorgalvao** [comment]
> `cask-repair` shouldn't override a shasum manually set as `:no_check`

For some reason, I’m not sure I’m comfortable with changing that (can’t really put my finger on why). Either one, it is done.

**Comment by adityadalal924** [comment]
Latest version is actually `1.34_20151215` which doesn't seem to play nice with the existing URL (and I'm not sure where this URL even came from)

**Comment by vitorgalvao** [comment]
To be clear (not sure it was, now that I reread it), I have indeed made the change to `cask-repair`.

**Comment by adityadalal924** [comment]
Ah sounded like you didn't. Thanks for the clarification.

**Pull request closed without merging**
