### PR TITLE
update rescuetime to 2.16.7.1

### PR DESCRIPTION
**Pull request by sschemer**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by ryan-efendy** [comment]
@bytecho @bevanjkay Is the rescuetime mac app installer here https://www.rescuetime.com/rtx/download the same or different than this rescuetime https://formulae.brew.sh/cask/rescuetime

Asking because when I navigate to https://www.rescuetime.com/rtx/overview I keep getting this popup modal after I installed rescuetime via brew `brew install --cask rescuetime`
image

**Comment by ryan-efendy** [comment]
cc: Rescuetime engs @gthank @ctweney @brnacl if any of you have any insight on this?

**Comment by gthank** [comment]
@ryan-efendy We don't actually have any relationship to this cask. That said, last year, RescueTime released a completely overhauled user experience, which relies on a much newer version of the RescueTime application (currently `3.0.13.2`, but the current version is always available at https://www.rescuetime.com/installers/RescueTimeInstaller_X.pkg). The older `2.16.7.1` is only for long-time users who have not yet migrated over to the newer user experience. Based on the screenshots, I'd guess you are a newer user who should be getting the new experience, and therefore should be on the newer application. Until the cask gets sorted out, I'd recommend downloading and installing the assistant from our webpage.

@bytecho @bevankjay You might want to make 3.x the default for new installs, since that's the version new users need. 2.x will only work for a subset of users who were around before last year.

**Comment by bfioca** [comment]
@bytecho we ACTUALLY just released a new free version of RescueTime yesterday and just haven't updated that page yet. We'll get that changed ASAP.

**Comment by k4rtik** [comment]
> Maybe a new cask for new RescueTime should be created ? @bevanjkay

I agree a new cask should be created for RescueTime X. I wrote a bit more at https://github.com/Homebrew/homebrew-cask/pull/120282#issuecomment-1072928977

**Pull request merged**
