### PR TITLE
freesmug-chromium 47.0.2526.111

### PR DESCRIPTION
**Pull request by rhendric**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Updating the `:checkpoint` value in `appcast` is required. You can find it with `curl --silent --compressed "{{appcast_url}}" | sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256 | awk '{ print $1 }'`.

Alternatively, you may wish to use [`cask-repair`](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair). It can at once update the cask’s version (according to what you give it) taking care of updating both the cask’s `sha256` and the appcast’s `:checkpoint`, while still giving you the chance to perform other manual fixes.

You can easily install it with `brew install vitorgalvao/tiny-scripts/cask-repair`. `cask-repair --help` will show you some options, but as a whole the script will guide you through the update process.

**Comment by rhendric** [comment]
Thanks for sharing cask-repair!

But it looks like you removed the appcast directive from freesmug-chromium in abc7cbb? That's the cause of this merge conflict, anyway. How would you like to proceed?

**Comment by vitorgalvao** [comment]
Yes, I removed it due to [this](https://github.com/caskroom/homebrew-cask/issues/16685), but it no longer applies.

To fix the merge conflict, you can add it back.

**Comment by rhendric** [comment]
Done!

**Pull request merged**
