### PR TITLE
Update elektriktrickquicklook to 1.1.0

### PR DESCRIPTION
**Pull request by colindunn**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by miccal** [comment]
This Cask should be renamed to just `elektriktrick.rb` now.

**Comment by colindunn** [comment]
I did think about that, but according to the homepage it's still called quicklook despite the file name change. No problem with the change.

**Comment by vitorgalvao** [comment]
> but according to the homepage it's still called quicklook

The token (name of the file and first line) conforms to the rules of the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).

**Comment by colindunn** [comment]
That's a fair point. Will keep it in mind @vitorgalvao

**Pull request merged**
