### PR TITLE
Update zap.md

### PR DESCRIPTION
**Pull request by miccal**

### CODE REVIEW

**Comment by adidalal** [comment]
Please change to relative linking (see other documentation sources), just to be consistent.

**Comment by miccal** [comment]
Done. I have performed these edits via the web interface, and cannot squash my commits (sorry).

**Comment by adidalal** [comment]
Thank you for the contribution. It needed some fixes, so they were made in d4a71959d5a9451287e882b985e183710dd473ca. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by adidalal** [comment]
No problem, did it for you.

**Comment by miccal** [comment]
Thank you.

**Pull request closed without merging**
