### PR TITLE
Update camo-studio from 1.3.6 to 1.5.1

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Ping @jamiebishop.

This is around the fifth version bump that has failed our CI tests -- I am afraid that if you cannot advise how to fix this, we will have to remove this Cask.

**Comment by miccal** [comment]
Note to self:
```
  installer script: {
    executable:   "#{staged_path}/Camo Studio.app/Contents/MacOS/Camo Studio",
    args:         ["-install"],
    sudo:         true,
    must_succeed: false,
  }

  uninstall quit:   "com.reincubate.macos.cam",
            script: {
              executable:   "/Applications/Camo Studio.app/Contents/MacOS/Camo Studio",
              args:         ["-uninstall"],
              sudo:         true,
              must_succeed: false, # necessary for now (see https://github.com/Homebrew/homebrew-cask/pull/100248)
            }
```

**Comment by bevanjkay** [comment]
@miccal This seems to be working okay locally now.

**Comment by miccal** [comment]
Thank @bevanjkay -- I am going to merge this and we can re-visit adding the `script:`'s later.

**Pull request merged**
