### PR TITLE
added :zap for filezilla

### PR DESCRIPTION
**Pull request by TimVNL**

### CODE REVIEW

**Comment by rolandwalker** [comment]
Hi!  Thanks!

What about `~/.filezilla` per the deleted comment?

**Comment by TimVNL** [comment]
@rolandwalker It isn't not present in my home folder but it's present in ~/.config/filezilla

**Comment by rolandwalker** [comment]
OK, perhaps upstream moved the location.

Per the [FAQ](https://wiki.filezilla-project.org/FAQ#FileZilla_Client_FAQ), `~/.filezilla` (possibly now moved to `~/.config/filezilla` is the answer to the question "Where does FileZilla store all its sites and settings?".

That would seem to mean that user-created documents (the sites) could be stored under that dotdir.  At least so far, we have avoided deleting user-created documents via `zap`.

Since I don't use Filezilla, I was looking for a clarification.  Does this Cask only install the client?  (Guessing maybe yes.)  If a user also installs the Filezilla *server*, does the server serve user-generated documents from the same dotdir? (Guessing maybe yes.)

**Comment by TimVNL** [comment]
@rolandwalker just did some research filezilla stores alll settings and sites in ~/.config/filezilla

Should I remove is from the zap command?

**Comment by rolandwalker** [comment]
Thanks for the info!  Greatly appreciated.

Let's change it to `:rmdir '~/.config/filezilla'` which will only remove the dir if it is empty.  Later, we can try to delete just the config files within the dir and leave the sites alone.

Farther along in the future, I'd like to add a new key, something like `:report '~/.config/filezilla'`, so that a user can be warned about the files that are intentionally left behind after zap.

**Comment by vitorgalvao** [comment]
> Farther along in the future, I'd like to add a new key, something like `:report '~/.config/filezilla'`

I think we could bypass all that by trashing files instead of deleting them. if something went wrong, the user can jut go get them again.

**Comment by vitorgalvao** [comment]
> Farther along in the future, I'd like to add a new key, something like `:report '~/.config/filezilla'`

I think we could bypass all that by trashing files instead of deleting them. If something went wrong, the user could just go get them again. I believe no files should be left behind after `zap`, not even user-created ones. `zap` should mean “get rid of everything”. Trashing would make this a non-issue.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It will be merged in [a different pull request](https://github.com/caskroom/homebrew-cask/pull/9931) due to some simple recommended alterations. Your contribution is still included (and still credited to you), with the appropriate modifications, when applicable.

Changes:
+ `:rmdir`, as requested by @rolandwalker.
+ Cleaned extraneous whitespace.

**Pull request closed without merging**
