### PR TITLE
Update rstudio.rb to version 1.0.44.

### PR DESCRIPTION
**Pull request by MarcoNiemann**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by neutric** [comment]
The [download page](https://www.rstudio.com/products/rstudio/download/) right now shows 1.0.136 as current version...

**Comment by MarcoNiemann** [comment]
Yep. Checked it. Interestingly I just started `RStudio` this morning and it told me I was using the outdated version `1.0.136` and recommended the update to `1.0.44`. If you enter the download link as specified in the cask file you can also download the updated version. 

So it might be that they really just released the new version and have not adjusted there homepage so far.

**Comment by neutric** [comment]
@MarcoNiemann Don't worry about it, I have been too fast and/or have had the version submitted in the PR disappear more than once. Maybe it'll show up shortly, if not and this'll get closed, please resubmit once 1.0.44 makes it through. Thanks for your contribution!

**Comment by vitorgalvao** [comment]
Doesn’t make much sense to me that `1.0.44` would be newer than `1.0.136`. Newer version tend to get higher numbers.

**Comment by neutric** [comment]
Good point! Germans seem to have problems ordering numbers today, it fooled me aswell. 1.0.44 was a while ago, see #26308. This can be closed.

**Pull request closed without merging**
