### PR TITLE
ghdl :latest

### PR DESCRIPTION
**Pull request by miccal**

### CODE REVIEW

**Comment by miccal** [comment]
Not sure what to do with this one ... ?

**Comment by bevanjkay** [comment]
@miccal Considering the latest version does not have built files, perhaps we just give this `version :latest` and point to the nightly?

**Comment by miccal** [comment]
I have added this to the [`github_prerelease_allowlist.json`](https://github.com/Homebrew/homebrew-cask/blob/master/audit_exceptions/github_prerelease_allowlist.json) and now is passes the CI.

**Comment by bevanjkay** [comment]
@miccal If we use nightly it will have to be `version :latest` because it doesn't look like it's the same as `1.0.0`

**Pull request merged**
