### PR TITLE
font-meltho: add livecheck

### PR DESCRIPTION
**Pull request by khipp**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by khipp** [comment]
@samford I'm sorry to bother you, but is this something you encountered before?

The command `brew fetch` fails with the following: `curl: (7) Failed to connect to bethmardutho.org port 443 after 37 ms: Couldn't connect to server`. This error seems to only occur on the GitHub-hosted runner.

**Comment by krehel** [comment]
@khipp - If it fails in the runner but succeeds locally (confirmed it worked for me also), feel free to pass `ci-skip-*` for whatever is needed.  Some upstreams block the IP ranges.

**Comment by khipp** [comment]
@krehel Thank you for the confirmation. This does seem like a case for `ci-syntax-only` since the download fails.

**Review by samford — COMMENTED** [review]
@khipp I'm late to this but yep, this isn't the first time I've seen a `livecheck` block that only fails in the CI environment.

As was mentioned, if the `livecheck` block works locally but reliably fails on CI, we can use the `ci-skip-livecheck` label to allow CI to pass without removing the `livecheck` block (or modifying it to use `#skip`). That's one of the intended purposes of that label but it shouldn't be used to merge a PR with a broken check that can be fixed by adding/updating a `livecheck` block.

**Pull request merged**
