### PR TITLE
Delete citrix-workspace.rb

### PR DESCRIPTION
**Pull request by core-code**
as discussed in pr #56708
this doesn't seem to be accessible anymore without a download token that changes daily.

current DL is
 https://downloads.citrix.com/15579/CitrixWorkspaceApp.dmg?__gda__=1546456395_defe865c339c552cca5882c7d7d87075
but i am sure it will change pretty soon again
 i think we should investigate technical ideas to circumvent the problem - if none are possible i guess we need to delete this ;(

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]
Looks like they’re going to great lengths to stop this from being downloadable any way other than visiting the website, so we should follow their wishes (actions) and remove this.

**Comment by core-code** [comment]
ok i also don't see a useful way around this, even if its sad to see a popular app go.

btw, i am not sure if it helps anyone but i've added a copy of a cask here:

https://www.corecode.io/macupdater/casks/citrix-workspace.rb

this is kept current with the current download token by a script that runs every hour - so it should never be outdated for too long.

**Comment by vitorgalvao** [comment]
If the token only changes daily and the script does hourly checks, why not point the script to submit PRs to this repo?

**Comment by core-code** [comment]
1.) i don't have any infrastructure to send pull requests from the cron-scripts on my webserver yet. i am actually not sure what would be involved there. create a separate github account with the ssh key of the server? 
2.) yes the delay until the script is run is just one hour tops. but if we add the delay until the pull request is approved and merged, i am not sure how useful this cask will be to the community. the cask would probably be offline for a few hours each day.

summary, i could probably send PRs from the script if this would be interesting to you and you think this would make keeping the cask worthwhile. if so, i'd appreciate any tips for setting up automated PRs from a script.

**Comment by ahousseini** [comment]
Why don't we use this download URL?
`http://downloadplugins.citrix.com.edgesuite.net/Mac/CitrixWorkspaceApp.dmg`

**Comment by core-code** [comment]
isn't this the old download URL that leads to the 18.09 release?

**Comment by 404NetworkError** [comment]
If core-code's second point holds back submissions directly to this repo, a tap could updated by the cronjob instead.

**Comment by vitorgalvao** [comment]
> create a separate github account

Yes. Another account that’d effectively act as a bot.

How does your script work currently? Does it generate the whole cask?

**Comment by core-code** [comment]
it just reads the existing cask on my server and replaces the url/version lines:
```

#!/usr/bin/env python

import urllib2


response = urllib2.urlopen("https://www.citrix.com/downloads/workspace-app/mac/workspace-app-for-mac-latest.html")

lines = response.readlines()
for line in lines:
	if line.find('CitrixWorkspaceApp.dmg?') != -1:
		url =  "https://" + line.split("rel=\"//")[1].split("\"")[0]
	if line.find('Citrix Workspace app ') != -1 and line.find(' for Mac') != -1:
		version = line.split('Citrix Workspace app ')[1].split(' for Mac')[0]


versionline = "  version '" + version + "'\n"
urlline = "  url '" + url + "'\n"

fi = open("/var/www/vhosts/corecode.at/corecode.io/macupdater/casks/citrix-workspace.rb", "r")
lines = fi.readlines()
fi.close()

lines[1] = versionline
lines[4] = urlline

fo = open("/var/www/vhosts/corecode.at/corecode.io/macupdater/casks/citrix-workspace.rb", "w")
fo.writelines(lines)
fo.close()

```

**Comment by vitorgalvao** [comment]
> is there any way to set up a bot without having a full checkout of the git repository?

I think not. It’s not possible to send PRs without a fork (I’d like to, for my own bot).

Do you have any idea if their key changes everyday at the same time?

**Comment by core-code** [comment]
> I think not. It’s not possible to send PRs without a fork

well thats bad ;/  on this server i am unable to store a full checkout, so that precludes sending PRs automatically in the near term 

> (I’d like to, for my own bot).

out of interest, what is that one going to do? :)

> Do you have any idea if their key changes everyday at the same time?

no idea yet but i guess i could find out. what would that knowledge gain us?

**Comment by vitorgalvao** [comment]
> out of interest, what is that one going to do? :)

It’s already doing. Homebrew but not Cask related. It’s essentially a couple of shell scripts that through [a Github account](https://github.com/thirdtapbot) send formula update PRs to my main account. They’re crude, but work so far.

They’re repos for formulae of software which the owner does not want to officially support a tap, but are happy to have me do it. One of them I don’t even use myself.

> no idea yet but i guess i could find out. what would that knowledge gain us?

My scripts are on a shared server (I use `/tmp` to dump the cloned repos and let them be) and are run from `cron` every three days. It may be feasible (but maybe not worth it) to have it run every day at a specific time, if it’d coincide with `citrix-workspace`’s update time.

Though so far I’m more inclined to delete the cask. I doubt it’s worth all the trouble.

**Comment by core-code** [comment]
thanks for the explanation!  i'd agree that its not worth the trouble at the moment. we can revisit the issue when i got a bot up to send PRs automatically.

until then, as mentioned, any user can do:
`brew cask install https://www.corecode.io/macupdater/casks/citrix-workspace.rb`

**Comment by vitorgalvao** [comment]
Merging this. But if you end up discovering the time at which they update, please let me know.

**Comment by core-code** [comment]
np, will do

**Comment by core-code** [comment]
it seems they update the token ALL THE TIME
```

https://downloads.citrix.com/15579/CitrixWorkspaceApp.dmg?__gda__=1546894035_6d1d20f1072012b35b1a762d712bf9d1  2019-01-07 20:47:16.188346
https://downloads.citrix.com/15579/CitrixWorkspaceApp.dmg?__gda__=1546894096_e9a670f9e1d011392b4837b8c146277c  2019-01-07 20:48:16.964273
https://downloads.citrix.com/15579/CitrixWorkspaceApp.dmg?__gda__=1546894157_ab4a2e1dc8b36f73cb9f992728068325  2019-01-07 20:49:17.856410
https://downloads.citrix.com/15579/CitrixWorkspaceApp.dmg?__gda__=1546894218_f437ff7aae49102f3a627cc0a739ebf0  2019-01-07 20:50:18.561361
https://downloads.citrix.com/15579/CitrixWorkspaceApp.dmg?__gda__=1546894279_a440d5887933a83c79797d423a881469  2019-01-07 20:51:19.366902
https://downloads.citrix.com/15579/CitrixWorkspaceApp.dmg?__gda__=1546894339_9c7e400de5b90c02ce4dbd7c66709fdb  2019-01-07 20:52:20.525281
https://downloads.citrix.com/15579/CitrixWorkspaceApp.dmg?__gda__=1546894401_82820b91244be23c9cdb1d6e7f0a0a56  2019-01-07 20:53:21.205218
https://downloads.citrix.com/15579/CitrixWorkspaceApp.dmg?__gda__=1546894461_ec06fab35293688fca0af2ffe1fbafe9  2019-01-07 20:54:21.920438
https://downloads.citrix.com/15579/CitrixWorkspaceApp.dmg?__gda__=1546894522_17f61cc6ffd2ab2ace60739b218c8822  2019-01-07 20:55:22.605438
```

i guess each token has an expiry date. so the question is, how long does each token stay valid?

**Comment by core-code** [comment]
ok the tokens stay valid only for exactly one hour.

which also means my script that updates a token once every hour isn't much use.

**Comment by vitorgalvao** [comment]
> which means any attempt to keep this cask is pretty much in vain.

Yep. Thank you for checking.

**Pull request merged**
