### PR TITLE
Add Frescobaldi 2.20.0.

### PR DESCRIPTION
**Pull request by marnen**
Add [Frescobaldi](http://www.frescobaldi.org) 2.20.0.

***

*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]

**Comment by vitorgalvao** [comment]
> Many users of this cask will already have a LilyPond installation, which may or may not be managed through Cask

That’s the case for every `depends_on` case. By that logic, we’d never use `depends` on and would always have `caveats`. Lilypond, as installed by as, is merely an app, so depending on it won’t be harmful.

**Comment by marnen** [comment]
@vitorgalvao I don't think you understood my point. This is not a case of mandatory dependency, so `depends_on` is inappropriate in this case. 

Does Caskroom have a concept of "recommended but optional dependency"? If so, I'll use that.

**Comment by vitorgalvao** [comment]
> Does Caskroom have a concept of "recommended but optional dependency"?

We do not.

In that case, [I’ve removed the dependency](https://github.com/caskroom/homebrew-cask/commit/2fe6d65fe5b6bc0983c3bd6495ccf6aa86d54c0b). A `caveat` is also not appropriate, as those are to be used for necessary installation instructions. The correct case here is to have nothing as [we are not a discoverability service and users are expected to have reasonable knowledge of what they are installing](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md).

**Comment by marnen** [comment]
I suppose that works. I was thinking that the caveat was good for the case of "oh crap, why can't I use the IDE to compile LilyPond source", while not forcing experienced LilyPond users to install a second copy of LilyPond. But I understand your point about discoverability.

**Pull request merged**
