### PR TITLE
Add Sling app for Sling TV

### PR DESCRIPTION
**Pull request by zerrot**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Could you please point me to the download page so I can verify the links (standard procedure for a maintainer to verify them when the download host is not the same as the homepage).

**Comment by zerrot** [comment]
No problem. The download page can be reached from the FAQ (
http://help.sling.com/FAQs ). About halfway down is the link for the Mac
download.

**Comment by vitorgalvao** [comment]
Thank you. Two things needs changing, then. Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/master/Casks/acorn.rb).

In addition, please add a `# movetv.com is the official download host per the vendor homepage` comment above `url`.

**Comment by zerrot** [comment]
Okay. I made the changes and added the comment. Let me know if it needs any additional changes.

**Comment by rolandwalker** [comment]
Looks great, thanks @zerrot !

**Pull request merged**
