### PR TITLE
mactex-no-gui 2022.0321

### PR DESCRIPTION
**Pull request by miccal**
It will take some time for all the mirrors around the world to update:

Screen Shot 2022-04-04 at 12 48 38

I will keep an eye on my local mirror at https://mirror.aarnet.edu.au/pub/CTAN/systems/mac/mactex/, and when it appears there I will merge this.

If people are impatient, they can download this from the root mirror at http://dante.ctan.org/tex-archive/systems/mac/mactex/

### CODE REVIEW

**Comment by miccal** [comment]
```
Error: ghostscript contains a recursive dependency on itself:
[283](https://github.com/Homebrew/homebrew-cask/runs/5810862153?check_suite_focus=true#step:17:283)
  ghostscript depends on itself via openjpeg
```
Ping @carlocab.

**Comment by carlocab** [comment]
Don't know why that's happening. This is the `ghostscript` dep tree:
```
ghostscript
├── fontconfig
│   └── freetype
│       └── libpng
├── freetype
│   └── libpng
├── jbig2dec
├── jpeg
├── libidn
├── libpng
├── libtiff
│   └── jpeg
├── little-cms2
│   ├── jpeg
│   └── libtiff
│       └── jpeg
└── openjpeg
    ├── libpng
    ├── libtiff
    │   └── jpeg
    └── little-cms2
        ├── jpeg
        └── libtiff
            └── jpeg
```
This is `openjpeg`'s:
```
openjpeg
├── libpng
├── libtiff
│   └── jpeg
└── little-cms2
    ├── jpeg
    └── libtiff
        └── jpeg
```
Thoughts, @Homebrew/maintainers?

**Comment by iMichka** [comment]
It's a build dependency: openjpeg -> doxygen -> texlive -> pstoedit -> ghostscript

**Comment by carlocab** [comment]
Ah yes. That's a problem.

**Comment by mmuetzel** [comment]
The previous version seems to have already disappeared from some mirrors:
https://ctan.math.washington.edu/tex-archive/systems/mac/mactex/

**Comment by fxcoudert** [comment]
`openjpeg` is a dependency of a lot of other formulas, and `texlive` is a quite complex piece of software. I'd suggest that, to cut the cycle, we build `openjpeg` without `doxygen`, even if it means shipping without doc.

**Comment by fxcoudert** [comment]
Or, actually, probably better that we revert the recent commit that introduced those heavy dependencies in doxygen. @carlocab is, as always, way ahead of this: https://github.com/Homebrew/homebrew-core/pull/98501

**Comment by miccal** [comment]
My local mirror at https://mirror.aarnet.edu.au/pub/CTAN/systems/mac/mactex/ has now been updated, and I have tested `basictex`, `mactex` and `mactex-no-gui` on several of my work colleagues machines and everything is working, so I am going to go ahead and merge this.

If any Cask user gets a "download failed" message, it is likely because your local mirror has not been updated just yet, so just give it a bit more time.

**Pull request merged**
