### PR TITLE
Update pock from 0.7.2 to 0.8.0

### PR DESCRIPTION
**Pull request by utkarshgupta137**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by utkarshgupta137** [comment]
@pigigaldi Could you update the source in the git repo and make a release? This cask update is failing because of it.

**Comment by miccal** [comment]
The `audit` failure is not the only issue, there is also in install issue:
```
ditto: Couldn't read PKZip signature
```
We had problems in the past with this Cask as seen [here](https://github.com/Homebrew/homebrew-cask/issues/93794).

**Comment by cho-m** [comment]
> The `audit` failure is not the only issue, there is also an install issue:
> 
> ```
> ditto: Couldn't read PKZip signature
> ```
> 
> We had problems in the past with this Cask as discussed in #93794.

It looks like the release is using an extra patch number.  https://pock.dev/ says version is `0.8.0-10`.
The URL for ZIP is `https://pock.dev/download.php?file=pock_0_8_0__10.zip&nw=1`.

I guess if `version "0.8.0-10"` is used, then either the dash will need to be converted to double underscore or some other manipulation needs to be done. One possible option could be `url "https://pock.dev/download.php?file=pock_#{version.dots_to_underscores.gsub(/-/, "__")}.zip&nw=1"`


In case of audit issue, GitHub release would probably be best. Another alternative option would be to remove `appcast` and do a `livecheck` on homepage. May need to confirm regex, but something like following seems to grab version: 
```
  livecheck do
    url :homepage
    strategy :page_match
    regex(/Latest version: (\d+(?:\.\d+)*(?:-\d+)?)/i)
  end
```

```
❯ brew livecheck pock
pock : 0.8.0-10 ==> 0.8.0-10
```

**Comment by utkarshgupta137** [comment]
@cho-m I've no experience with brew, I thought a simple version bump would suffice.
If you can get it working, please do create a new PR

**Comment by cho-m** [comment]
@utkarshgupta137 I created PR #98779 with changes I mentioned.

**Comment by utkarshgupta137** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/98779

**Pull request closed without merging**
