### PR TITLE
Revert "Update icollections from 6.6,66012 to 6.7,67008"

### PR DESCRIPTION
**Pull request by core-code**
Reverts Homebrew/homebrew-cask#93302

### CODE REVIEW

**Comment by core-code** [comment]
why the fuck will a faulty pr get automerged and the pr to correct this wont get merged despite 3 labels and one manual approval from our magic system?

**Comment by reitermarkus** [comment]
> despite 3 labels and one manual approval

Something unrelated to the “magic“ in the system was broken: https://github.com/Homebrew/homebrew-cask/pull/93318

**Review by reitermarkus — APPROVED** [review]

**Comment by core-code** [comment]
thanks for taking care of that

**Pull request merged**
