### PR TITLE
Update resolume-arena to 6.0.10

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
I'm a little concerned about the uninstall stanza for this and [resolume-avenue](https://github.com/Homebrew/homebrew-cask/pull/49428), as there seem to be two shared pkgs that both use. If both casks have them in the uninstall stanza, however, and a user has both apps/casks installed but then removes one it would break the other.

I believe these are the shared packages:
```
> com.resolume.pkg.ResolumeDXV
> com.resolume.pkg.ResolumeQuickLook
```

Thoughts?

**Comment by vitorgalvao** [comment]
The solution is to remove the shared packages from `uninstall` and add them to `zap`.

**Comment by vitorgalvao** [comment]
> Maybe travis doesn't do zap?

It used to, but we removed that option because it caused trouble in some situations.

**Comment by brianmorton** [comment]
bump

**Comment by brianmorton** [comment]
bump

**Pull request merged**
