### PR TITLE
Update mono-mdk to 4.2.1 stable

### PR DESCRIPTION
**Pull request by jefbarn**

### CODE REVIEW

**Comment by adityadalal924** [comment]
Using a regex of `\.[^.]*$` should match everything including and after the last period, allowing the URL to not need the hardocded `4.2.1` anymore.

**Comment by jefbarn** [comment]
You guys seriously want to get into the regex business with this stuff.
Good luck with that.

**Comment by vitorgalvao** [comment]
> You guys seriously want to get into the regex business with this stuff.
> Good luck with that.

Thank you, but no need for luck. We have been using regexes for these cases for a really long time, and they work very well.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 79cb4d96774a419cf53b4bd1cfdc51046e08ca4f. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
