### PR TITLE
Add Sampler v.1.0.0

### PR DESCRIPTION
**Pull request by sqshq**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

---

Hey guys,
Meet Sampler - a tool to build dashboards, monitoring and alerting — right from the terminal

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Welcome, and thank you, but this is a CLI-only open-source tool. Please submit it first to [Homebrew/core](https://github.com/homebrew/homebrew-core) as a formula. Return here if not accepted (linking back to the pull request where it was refused).

This policy is documented in [faq/rejected_casks](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core) as a formula that builds from source. If it is rejected, you may then try again as a cask (link us to the issue so we can see the discussion and reasoning for rejection).

**Comment by sqshq** [comment]
Hi @vitorgalvao
This application has a [commercial license option](https://sampler.dev/#pricing), so I need to request server side for key validation when user starts application with `--license` flag. Compiled binary contains request url and auth token, they are not commited in github repository (security over obscurity, but anyway).

I can't find an answer, is it allowed to create brew formula without building from source?

**Comment by vitorgalvao** [comment]
> I can't find an answer, is it allowed to create brew formula without building from source?

I think not, but I deal more with casks so forumlae rules may have changed since the last time I checked.

> Also I use the [Fair Source License](https://fair.io), not sure if it is suitable for Homebrew/core

I’d say it’s not.

**Comment by sqshq** [comment]
Ok, so these are two reasons why I opened the MR in Homebrew/Cask :)

@vitorgalvao, one more question. Since my experiment with paid option and non-open-source license might be temporary, will it be possible in future to switch to Homebrew/Core?

**Comment by vitorgalvao** [comment]
> Since my experiment with paid option and non-open-source license might be temporary, will it be possible in future to switch to Homebrew/Core?

Yes. We’d encourage that.

**Pull request merged**
