### PR TITLE
Update acquia-dev from 2-2019-02-08 to 2-2019-06-06

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
@vitorgalvao - could you perhaps have a look on the url stanza … I think there is a better solution to solve it :)

**Comment by vitorgalvao** [comment]
@suschizu Would a version of `2.2019-06.06` work for you, or would you rather keep the `-`?

**Comment by suschizu** [comment]
@vitorgalvao - I just noticed that this version stanza has nothing to do with the apps version - it's just the installers version number so your proposal is indeed ok!  Thanks and sorry for the fuss :)

**Comment by suschizu** [comment]
thanks :) have a nice weekend 🌞

**Comment by vitorgalvao** [comment]
Thank you, you too!

**Pull request merged**
