### PR TITLE
Add SonoAir v1.0-beta-4.0

### PR DESCRIPTION
**Pull request by kTitan**
Currently no stable release is available.

### CODE REVIEW

**Comment by adityadalal924** [comment]
unstable & development versions go into homebrew-versions

Open a PR on that repo @ https://github.com/caskroom/homebrew-versions

Thanks!

**Comment by kTitan** [comment]
Of course I could do that. But then the CONTRIBUTING guide is wrong:

>But There Is No Stable Version!
>
>When an App is only available as beta, development, or unstable versions, or in cases where such a version is the general standard, then said version can go into the main repo.

**Comment by adityadalal924** [comment]
Just saw your comment (no stable release) - you're absolutely right!

**Comment by vitorgalvao** [comment]
Thank you, @kTitan. Merged as https://github.com/caskroom/homebrew-cask/commit/769d5b9f316e06613fad619f2ab94459ee32c07c to keep commit history cleaner.

**Pull request closed without merging**
