### PR TITLE
Add Mail Designer.app version 2.3.1

### PR DESCRIPTION
**Pull request by vinkla**
Create moving emails with ease. http://equinux.com/us/products/maildesigner2/

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as f33c684c5e8a9b2790528f990e99d608b7a59982 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by vinkla** [comment]
:+1:

**Comment by vinkla** [comment]
Seems broken? https://github.com/caskroom/homebrew-cask/commit/f33c684c5e8a9b2790528f990e99d608b7a59982

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as e64cac0eed4fdc5e180d3337d37c321661e92962 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by vinkla** [comment]
No worries, it was just weird that I couldn't find it the in history and the commit you linked in the first comment was broken. Thanks!

**Comment by vitorgalvao** [comment]
It was an issue on my part. Fixed now.

**Comment by vinkla** [comment]
Okay.

**Pull request closed without merging**
