### PR TITLE
Update firefox.rb from 80.0.1 to 81.0

### PR DESCRIPTION
**Pull request by schwedenmut**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

The "official" release will be on the 22nd (I think), but the packages were already on the mozilla servers so I went ahead.

### CODE REVIEW

**Comment by core-code** [comment]
this is not yet available on the homepage or listed in their release-notes

**Comment by core-code** [comment]
> The "official" release will be on the 22nd (I think), but the packages were already on the mozilla servers so I went ahead.

thanks but please wait until the official release. we are not interested in unofficial releases just because they are already on a server. they can be changed before the official release.

**Comment by schwedenmut** [comment]
> > The "official" release will be on the 22nd (I think), but the packages were already on the mozilla servers so I went ahead.
> 
> thanks but please wait until the official release. we are not interested in unofficial releases just because they are already on a server. they can be changed before the official release.

thanks @core-code for the feedback, I didn't think about the implications and the possibility of changes to the packages. you are quite right and I will not rush next time 👍

**Comment by core-code** [comment]
thanks its official now. we just need to get it through CI now :)

**Review by core-code — DISMISSED** [review]

**Pull request merged**
