### PR TITLE
Fixes to several casks of jetbrains products

### PR DESCRIPTION
**Pull request by leipert**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

This PR basically:

1. adds missing appcasts
2. fixes faulty appcasts checkpoints
3. adds missing `auto_updates`
4. Update a few names and urls to canonical versions

### CODE REVIEW

**Review by adidalal — APPROVED** [review]

**Comment by leipert** [comment]
As @vitorgalvao deleted the second name of `intellij-idea`. Should we delete the second name of `intellij-idea-ce` as well?

**Comment by vitorgalvao** [comment]
@leipert No. In that case it is correct. See [`name` docs](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/name.md).

**Comment by vitorgalvao** [comment]
@leipert Can you also find appcasts for the EAP versions in [caskroom/versions](https://github.com/caskroom/homebrew-versions)?

**Comment by leipert** [comment]
I rebased the commits onto master and added the last missing appcasts for intellij-idea and intellij-idea-ce.

@vitorgalvao Regarding appcasts for eaps.
Theoretically there are urls available for eaps, but it seems like they are not available for all jetbrains products and sometimes after an release is made, the last eap vanishes...

**Pull request merged**
