### PR TITLE
Add Nanobox Cask

### PR DESCRIPTION
**Pull request by liljenstolpe**
fixed a trailing whitespace in a comment that was breaking ci (rubocop)

changed style, added uninstall

### CODE REVIEW

**Comment by liljenstolpe** [comment]
fixed based on your comments on nanobox-bundle.

**Comment by fanquake** [comment]
dup of #15287

**Comment by adityadalal924** [comment]
It looks like this is the same as the "raw binary" - opening nanobox.pkg (with Suspicious Package) confirms that.

@fanquake Not a dupe - this one is only the commandline interface

**Comment by fanquake** [comment]
Right, my mistake. The PR names and descriptions being kinda random made them look the same.

Given it's not a dupe, @liljenstolpe can you please amend you commit message to remove all the comments about fixing/changing style.

**Comment by liljenstolpe** [comment]
I can.

**Comment by liljenstolpe** [comment]
done.  Did the squash originally because @vitorgalvao asked me to squash them.

**Comment by adityadalal924** [comment]
@vitorgalvao - Tried using the raw binary but doesn't seem to work (I thought that would be better than using a `.pkg`, since one is available). Thoughts?

```
cask :v1 => 'nanobox' do
  version :latest
  sha256 :no_check

  # amazonaws.com is the official download host per the vendor homepage
  url 'https://s3.amazonaws.com/tools.nanobox.io/cli/darwin/amd64/nanobox'
  name 'nanobox'
  homepage 'http://www.nanobox.io/'
  license :mpl

  container :type => :naked

  binary 'nanobox-latest', :target => 'nanobox'

end
```

**Comment by adityadalal924** [comment]
Thank you for the contribution. It needed some fixes, so they were made in a0bb94dffa5d50d426a31ffef1e1b08d5b981f70. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by liljenstolpe** [comment]
uninstaller isn't there.  Do you want me to add it back in?

**Comment by vitorgalvao** [comment]
@adityadalal924 Looks great, no changes needed. Thank you.

**Pull request closed without merging**
