### PR TITLE
Update metashape from 2.0.0 to 2.0.1

### PR DESCRIPTION
**Pull request by razvanazamfirei**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by miccal — APPROVED** [review]

**Comment by jlarmstrongiv** [comment]
@razvanazamfirei, I tried installing metashape 2.0.1, but received this error:

```bash
brew install --cask metashape
==> Downloading http://download.agisoft.com/metashape_2_0_1.dmg
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/3244613b0358393dc7c06a92142700c9d92f66f0ea2a0189575d97e2e55e78b6--metashape_2_0_1.dmg
Error: SHA256 mismatch
Expected: 80f903d6aa61d659dfa251a7324b5c3c022f4fdfa3900cd2a2cfa5a591fb64c4
  Actual: cfe638f081e533cd85ad9c22e04ab79a7758c8504beb58c48edf5e3803e064b1
    File: /Users/user/Library/Caches/Homebrew/downloads/3244613b0358393dc7c06a92142700c9d92f66f0ea2a0189575d97e2e55e78b6--metashape_2_0_1.dmg
To retry an incomplete download, remove the file above.
```
---

According to the [changelog](https://www.agisoft.com/pdf/metashape_changelog.pdf), metashape released a hotfix, but didn’t bump the version.

I expect the original SHA256 hash comes from:

```
Version 2.0.1 build 15925 (1 March 2023)
```

Whereas the new SHA256 hash comes from:

```
Version 2.0.1 build 16069 (3 April 2023, hotfix release)
```

Homebrew will not upgrade or install if the SHA256 does not match.

**Comment by jlarmstrongiv** [comment]
Would the fix be as simple as updating the hash in https://github.com/Homebrew/homebrew-cask/blob/master/Casks/metashape.rb ?

**Comment by razvanazamfirei** [comment]
Hi @jlarmstrongiv, thanks for pointing this out! Yes, updating the hash should fix it. I just submitted a PR that should address this. If you have this repo tapped and you want to update now, you can add the new hash to your local version of the cask. It should be at `(brew --prefix)/Library/Taps/homebrew/homebrew-cask/metashape.rb`.

**Comment by jlarmstrongiv** [comment]
@razvanazamfirei Thank you for the update 😄 works perfectly now

**Pull request merged**
