### PR TITLE
Update microsoft-word from 16.27.19071500 to 16.28.19081202

### PR DESCRIPTION
**Pull request by joh-klein**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by reitermarkus** [comment]
These should have a `conflicts_with cask: 'microsoft-office'`.

**Comment by joh-klein** [comment]
Do they actually conflict?

**Comment by reitermarkus** [comment]
Do they not install Word to the same location?

**Comment by joh-klein** [comment]
Yes, true – hmm, is that already considered a conflict even though they are the same apps?

**Comment by joh-klein** [comment]
This should probably also be added to the microsoft-office cask, right?

**Comment by reitermarkus** [comment]
Yes, `conflicts_with` has to be added to both casks which conflict with each other.

**Comment by reitermarkus** [comment]
> is that already considered a conflict even though they are the same apps?

Doesn't matter whether or not it is the same app, if it installs to the same location, it is definitely a conflict.

**Pull request merged**
