### PR TITLE
Add Plan.app beta

### PR DESCRIPTION
**Pull request by oschrenk**
This is the cask for [Plan](https://getplan.co), a todo/planning tool integrating with your calendar.

It currently doesn't have a stable version.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating only the `sha256`**:

- [ ] I verified this change is legitimate [<sup>How do I do that?</sup>][version-checksum] and **am providing confirmation below**:

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please don’t just tick checkboxes without reading them. The “if updating only the sha256” checkbox has clear [instructions](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256) on how to make the verification.

You clearly have not read the instructions (*the whole section should have been skipped in this case*). Now I’m left wondering if you actually followed any of the other points.

**Comment by oschrenk** [comment]
I did read the instructions but misunderstood the checkboxes and filled them when I did the step. Please leave some room for misunderstanding instructions.

I now see little room for me to move forward. Either you disregard the pull request and close it or you tell me how prove to you that I did the other steps. Would re-doing the steps and pasting the terminal output for each step work for you?

**Comment by vitorgalvao** [comment]
There’s no need for you to redo anything. Travis will check the most important steps.

But that checkbox is an insane amount of stress. I’m almost out of ideas on that one.

**Comment by oschrenk** [comment]
You probably already have taken multitude of measures but if you feel stressed about this, there is definitly a problem and I'm sorry to add to the chaos and your stress.

If a technical solution doesn't exist or wording changes didn't help, do more contributors or just waiting time help to alleviate the problem? Because I definitly could have waited for hours or days for any progress on this issue and I don't want open source contributors to burn out.

Thanks for fixing the checkbox for me!

**Comment by vitorgalvao** [comment]
Thank you for the concern, but the problem is specifically with people not following that checkbox correctly. We don’t need more contributors (except to the [core](https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aopen+label%3Acore)); we have everything covered in that regard.

What we need is a way to make that checkbox foolproof.

**Comment by vitorgalvao** [comment]
I just had an idea for the checkbox: [removing it](https://github.com/caskroom/homebrew-cask/pull/39703#issuecomment-336920805).

We’re not there yet, but I’m confident with that one.

**Pull request merged**
