### PR TITLE
Add EV3 Classroom.app v1.1.1

### PR DESCRIPTION
**Pull request by ahousseini**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by ahousseini** [comment]
This software is replacing the cask `lego-mindstorms-ev3` according to this support article:

https://education.lego.com/en-us/support/mindstorms-ev3/mac-catalina-issues

Should I make a PR to remove the cask `lego-mindstorms-ev3`?

**Comment by miccal** [comment]
Does this new one only work on Catalina?

**Comment by ahousseini** [comment]
I could only test it on a macOS 10.14 machine and it works there. And the `LSMinimumSystemVersion` key in the `Info.plist` says `10.10.0`

**Comment by miccal** [comment]
There does exist an `appcast`, but it is not suitable to use:
```
|-> curl http://s3.amazonaws.com/ev3-education-electron-updates/latest-mac.yml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Endpoint>ev3-education-electron-updates.s3.amazonaws.com</Endpoint><Bucket>ev3-education-electron-updates</Bucket><RequestId>A967CF03999AB49C</RequestId><HostId>rjldmRN713MPMQsJ4v6D9pENcgXZCnfZ5X4HOR2pR12ONHmmLjk8CE1/ycYTBSvuA+jpputrlbk=</HostId></Error>
```

**Comment by miccal** [comment]
> I could only test it on a macOS 10.14 machine and it works there. And the `LSMinimumSystemVersion` key in the `Info.plist` says `10.10.0`

This has a minimum of Mojave according to https://education.lego.com/en-us/product-resources/mindstorms-ev3/downloads/system-requirements.

**Comment by vitorgalvao** [comment]
> This software is replacing the cask `lego-mindstorms-ev3` according to this support article:
> 
> https://education.lego.com/en-us/support/mindstorms-ev3/mac-catalina-issues

Article is dead, found an [Internet Archive version](http://web.archive.org/web/20200807100246/https://education.lego.com/en-us/support/mindstorms-ev3/mac-catalina-issues).

It’s not clear to me that the page says what you say it does.

**Comment by miccal** [comment]
> > This software is replacing the cask `lego-mindstorms-ev3` according to this support article:
> > https://education.lego.com/en-us/support/mindstorms-ev3/mac-catalina-issues
> 
> Article is dead, found an [Internet Archive version](http://web.archive.org/web/20200807100246/https://education.lego.com/en-us/support/mindstorms-ev3/mac-catalina-issues).
> 
> It’s not clear to me that the page says what you say it does.

Updated page:

https://education.lego.com/en-au/product-resources/mindstorms-ev3/troubleshooting/mac-catalina-issues

**Comment by vitorgalvao** [comment]
What it says on the page is:

> replace the current EV3 Lab software and EV3 Programming App with a completely new app, called LEGO® MINDSTORMS® Education EV3 Classroom.

How does that translate to:

> This software is replacing the cask `lego-mindstorms-ev3`

Does the PKG in that cask install EV3 Lab software and EV3 Programming App? Because it’s not clear from just looking at it.

I have no problem removing the other cask if that’s the case, I’d just like to be sure we’re not removing something that’s still in use.

**Comment by ahousseini** [comment]
We are an MSP for managed devices and provided the cask `lego-mindstorms-ev3` before and our customers asked to replace it with this new EV3 Classroom application. So I assumed this would replace it. I know what you mean, it does not state it that clear.

**Comment by vitorgalvao** [comment]
If we’re not sure, let’s keep both casks. Their names do not conflict and we don’t have a way to handle renames anyway, so there’s no harm in keeping it a little while.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
