### PR TITLE
Add Insomnia Designer v2020.1.3

### PR DESCRIPTION
**Pull request by a-p-o**
After making all changes to the cask:

- [x] `brew cask audit --download insomnia-designer` is error-free.
- [x] `brew cask style --fix insomnia-designer` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install insomnia-designer` worked successfully.
- [x] `brew cask uninstall insomnia-designer` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by cixtor** [comment]
@a-p-o please add a `zap` statement to remove these folders upon uninstallation:

```
zap trash: [
  '~/Library/Application Support/Insomnia Designer',
  '~/Library/Caches/com.insomnia.designer',
  '~/Library/Caches/com.insomnia.designer.ShipIt',
  '~/Library/Logs/Insomnia Designer',
  '~/Library/Preferences/com.insomnia.designer.plist',
  '~/Library/Saved Application State/com.insomnia.designer.savedState',
]
```

**Comment by a-p-o** [comment]
@cixtor, sure! This is the first cask I'm adding, and I didn't come across this in the documentation. Do you mind describing how you found which files to include in the `zap` statement?

**Comment by gschier** [comment]
I'm not familiar, but it looks like zap deletes a bunch of unnecessary files after installation?

I assume we probably want this to be the same as the `insomnia` config https://github.com/Homebrew/homebrew-cask/blob/8de1164b34614ee7c1086df6763ad68d8c5227b3/Casks/insomnia.rb

**Comment by cixtor** [comment]
> _I'm not familiar, but it looks like zap deletes a bunch of unnecessary files after installation_

@gschier I think you got it wrong. From the [official Homebrew documentation](https://github.com/Homebrew/homebrew-cask/blob/5e6d62a106cab1bcac48d524f5beaef73cdc87b6/doc/cask_language_reference/stanzas/zap.md):

> _The zap stanza describes a more complete uninstallation of files associated with a Cask. The zap procedures will never be performed by default, but only if the user invokes the zap verb: `brew cask zap FORMULA`_

According to this, adding the zap statement should not affect the installation process at all. It will also never run during the uninstallation, only when the user explicitly calls “brew cask zap FORMULA” which means the user actually wants to delete the app and all files and folders it created.

@a-p-o to answer your question _“how you found which files to include in the zap statement”_. I used [fswatch](https://github.com/emcrisostomo/fswatch) to monitor addition, modification and deletion of files and folders in ~/Library/, then opened the app for the first time, used it for a few minutes (changed app preferences, create a project, etc), hard quitted the app (Cmd + Q) and finally inspected the logs generated by fswatch selecting everything matching the string “*nsomnia”.

```sh
cd ~/Library/ && fswatch . 1> $TMPDIR/fswatch.log
open /Applications/Insomnia\ Designer.app
# a few minutes later…
grep -i "insomnia.designer" $TMPDIR/fswatch.log
```

**Comment by vitorgalvao** [comment]
What does this mean for [insomnia](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/insomnia.rb)?

**Comment by pawelgrzybek** [comment]
@vitorgalvao Insomnia Core (formerly Insomnia) and Insomnia Designer are two Independent apps. Should not collide.

**Comment by gschier** [comment]
Correct, we should maintain them as separate `insomnia` and `insomnia-designer` packages.

The only tricky part might come from the fact that they're currently both hosted on the same GitHub repo. I'm not sure how `appCast` works, but it looks like both `insomnia` and `insomnia-designer` `appCast` point to https://insomnia.rest/changelog/index.xml.

If it helps, we already host a JSON-formatted changelog that can be filtered per-app:

- https://api.insomnia.rest/changelog.json?app=com.insomnia.designer
- https://api.insomnia.rest/changelog.json?app=com.insomnia.app

If there's anything we can do on our end to make the automation easier, please let me know and I'll relay them to the team 💜

**Comment by ran-dall** [comment]
> If it helps, we already host a JSON-formatted changelog that can be filtered per-app:
> 
>     https://api.insomnia.rest/changelog.json?app=com.insomnia.designer
>     https://api.insomnia.rest/changelog.json?app=com.insomnia.app

@core-code I can use these with the ML. Can you pick it up the changes on your side, if we set these on the `appcast`?

**Comment by core-code** [comment]
@ran-dall thanks yes that should work. appcasts that only contain the newest version (and not old versions too) are a lot better but since these shouldn't be noisy it should be ok.

**Pull request merged**
