### PR TITLE
Update softraid to 5.5.6

### PR DESCRIPTION
**Pull request by ghost**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by jprokos** [comment]
This is the first time I have done this. Hope I didn't mess it up.  I used cask-repair softraid. When the script came to 'cask 'softraid' do' it showed the old version and its checksum; the new version and its checksum. I was able to verify the checksum from the file I downloaded from the developers website (not sure that's the proper/best way), however I didn't know how to confirm that the "appcast checkpoint" was calculated properly. I checked the web address of the file by pasting it into my browser and it download the latest version of the file. So, I decided "… is everything correct?" YES.
Then I received, "push failed due to shallow repo. Unshallowing…. and everything seemed to work fine. Are there individuals who maintain certain casks or is it the community as a whole? Why do latest versions sometimes fail to download? Hoping to learn more.

**Comment by neutric** [comment]
> This is the first time I have done this. Hope I didn't mess it up.

Nope, looking good!

> [...] I didn't know how to confirm that the "appcast checkpoint" was calculated properly.

```
%  brew cask _appcast_checkpoint --calculate https://www.softraid.com/updates/Latest_SoftRAID_Release.html
39819a5c4955646bbb59aed2cfc5b9363d774b0594f4bbb13306ba7eee89b44c
```

> Are there individuals who maintain certain casks or is it the community as a whole?

The community as a whole. Whoever gets to it first, basically.

> Why do latest versions sometimes fail to download?

What do you mean? Casks with `version :latest`?

**Comment by jprokos** [comment]
I mean there have been a few times when casks are older, but now that I know what to do I will attempt to update them. Is it mainly a change in the URL that causes the issue or does this process have to be carried out for every version?

**Comment by miccal** [comment]
Thank you for your contribution.

**Comment by neutric** [comment]
@jprokos `brew cask install` installs the version that is prescribed in the Cask file. If a cask has a `version` other than `version :latest`, we have to update the Cask to account for a new version. Most of the times that only means bumping the version like you just did. Sometimes upstream also changes the naming pattern so that `url` or `app` or others have to be adjusted.

**Pull request merged**
