### PR TITLE
Update disk-drill from 3.8.977 to 3.8.975

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
[As pointed out by `core-code`](https://github.com/Homebrew/homebrew-cask/pull/89566#issuecomment-695347115) the download link `https://dl.cleverfiles.com/diskdrill.dmg` does indeed provide version 3.8.977:
```
|-> curl -sLI https://dl.cleverfiles.com/diskdrill.dmg
HTTP/1.1 200 OK
Date: Mon, 21 Sep 2020 04:55:44 GMT
Last-Modified: Mon, 14 Sep 2020 20:01:15 GMT
```
```
|-> curl -sLI https://www.cleverfiles.com/releases/DiskDrill_3.8.977.zip
HTTP/1.1 200 OK
Date: Mon, 21 Sep 2020 05:36:29 GMT
Last-Modified: Mon, 14 Sep 2020 20:00:30 GMT
```
Also it appears that the `appcast` has been updated to:
```
https://www.cleverfiles.com/releases/auto-update/dd3-newestr.xml
```
although this still shows the previous version:
```
|-> curl https://www.cleverfiles.com/releases/auto-update/dd3-newestr.xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
	<channel>
		<title>Disk Drill - Version History</title>
		<link>https://www.cleverfiles.com/releases/auto-update/dd3-newestr.xml</link>
		<description>Most recent changes with links to updates.</description>
		<language>en</language>
		<item>
			<title>Version 3.8.975</title>
			<sparkle:releaseNotesLink>
				https://www.cleverfiles.com/releases/auto-update/dd3-newestr.html
			</sparkle:releaseNotesLink>
			<pubDate>26 June 2020 00:00:00 +0200</pubDate>			
			<sparkle:minimumSystemVersion>10.9.5</sparkle:minimumSystemVersion>
			<enclosure url="https://www.cleverfiles.com/releases/DiskDrill_3.8.975.zip" length="" type="application/octet-stream"/>
		</item>
	</channel>
```

**Comment by core-code** [comment]
lets keep '3.8.977' as long as it is on the homepage

**Comment by ran-dall** [comment]
@core-code I don't have anything for this, so just tag it `bad-update` for now...I guess.

@miccal Good work. However on these automated updates, you can just tag it something (like `bad-update`) and close it. Thanks

**Comment by ran-dall** [comment]
...and in case anyone is wondering what `bad-update` does. In a nutshell, as of right now, it just drops the specfic update from its analysis.

**Comment by core-code** [comment]
bad-update

**Pull request closed without merging**
