### PR TITLE
Update intellij-idea-ce to 2016.3.4

### PR DESCRIPTION
**Pull request by ksylvan**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/29701

**Comment by leipert** [comment]
@vitorgalvao:
This is another product than `intellij-idea` which is updated in #29701.

**Comment by ksylvan** [comment]
Correct. This is the Community Edition. Thanks.

**Comment by vitorgalvao** [comment]
Verified locally due to Travis delays.

**Pull request merged**
