### PR TITLE
dwarf-fortress-lmp: v0.45.05

### PR DESCRIPTION
**Pull request by MindTooth**
This is a bundled version for Dwarf Fortress that includes tons of extra
features.

This supersedes https://github.com/caskroom/homebrew-cask/pull/21290

However, as you can see, it has a strange versions number, that also don't follows the path inside the DMG.  Last, the script to run is named `Sierra+ users, open me once.sh`, which is named odd.

I might contact the author, and ask if maybe he could clean it up a bit, regarding names and version.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> This supersedes #21290

Then this PR should be removing that cask as well. But why the `lmp`, why not keep `lnp`? Pinging @brewingcode into the conversation as well.

**Comment by commitay** [comment]
> Last, the script to run is named `Sierra+ users, open me once.sh`, which is named odd.

Is this documented upstream? I'd rather have a caveat that says "read this" rather than "run this".

**Comment by MindTooth** [comment]
The name if this version is MacNewbie Pack, which just now I realise that it should have been called `dwarf-fortress-mnp`.

The script is actually only there so you don't need to right-click and open because of the insecure app dialog.  In hindsight, maybe just remove it all together?

**Comment by brewingcode** [comment]
> Then this PR should be removing that cask as well. But why the lmp, why not keep lnp? Pinging @brewingcode into the conversation as well.

Thanks @vitorgalvao :-) I'm fine removing #21290: the base game version is all that really matters, and the version in #21290 (42.04) is far older than the version in this PR (45.05). The only difference is in the bundled additions to make the game (somewhat) more playable.

**Comment by vitorgalvao** [comment]
> The script is actually only there so you don't need to right-click and open because of the insecure app dialog.

Then it isn’t necessary at all, because apps downloaded with HBC are not quarantined. See https://github.com/caskroom/homebrew-cask/issues/22388 for details.

Thank you for the clarification, @brewingcode.

**Review by vitorgalvao — DISMISSED** [review]
Please add a commit to remove the other cask.

**Review by commitay — APPROVED** [review]

**Comment by MindTooth** [comment]
I did not see what you did with the version parsing until now.  Learned a bit, thanks! 👍

**Pull request merged**
