### PR TITLE
makemkv 1.10.3

### PR DESCRIPTION
**Pull request by vszakats**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please fill the template.

**Comment by vszakats** [comment]
Will do, waiting for Travis CI.

**Comment by vitorgalvao** [comment]
> Will do, waiting for Travis CI.

The point is to do it *before* submitting. But I see you must’ve edited it from the web interface.

**Comment by vszakats** [comment]
I know, sorry, I just tried to install this, current SHA256 is broken, so it's just quick and dirty.

**Comment by vitorgalvao** [comment]
Ah, no, don’t close it! It was fine. I understand sometimes it’s convenient to do it via the web interface, so it was fine waiting for Travis.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/27753.

**Comment by vszakats** [comment]
Sorry for closing so fast and thank you for reviving this!

**Pull request closed without merging**
