### PR TITLE
Add 'Commander One.app' Latest

### PR DESCRIPTION
**Pull request by yurii-sorokin**
Commander One
Free dual pane file manager for Mac

### CODE REVIEW

**Comment by fortywinkz** [comment]
Thx for your comments, I've pushed update.

**Comment by Ngrd** [comment]
Thank you. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by fortywinkz** [comment]
Doh. Surely. Done.

**Comment by Ngrd** [comment]
Thank you for the contribution. It was merged directly as 95638947a1a863817ab0a3824bef08fc0b6c1182 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by fortywinkz** [comment]
Superb. Thank you for your help.

**Pull request closed without merging**
