### PR TITLE
ubports-installer: 0.8.8-beta (new cask)

### PR DESCRIPTION
**Pull request by SecKatie**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
  - This is for a beta because there is no stable version available
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by JoshuaMulliken** [comment]
@cho-m could you look at this real quick if you get a chance?

**Comment by JoshuaMulliken** [comment]
I am a GitHub sponsor of the project

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @JoshuaMulliken.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by JoshuaMulliken** [comment]
> Thank you for your contribution to `homebrew-cask` @JoshuaMulliken.
> 
> Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

I have added a zap stanza and it appears to work correctly!

**Comment by JoshuaMulliken** [comment]
@miccal @SMillerDev  I have addressed all the issues and I believe this is ready for review! Thank you all so much for your help

**Comment by miccal** [comment]
Thank you @JoshuaMulliken.

**Pull request merged**
