### PR TITLE
Update flic from 2.0.2 to 2.1.0

### PR DESCRIPTION
**Pull request by MarcelloNicoletti**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by kortenkamp** [comment]
I am not sure how I could add to this commit – @MarcelloNicoletti, can you either add a `desc` stanza or close this merge request so that I can create a new one? Thanks!

**Comment by MarcelloNicoletti** [comment]
I'm making a `desc` stanza now

**Comment by MarcelloNicoletti** [comment]
It looks like someone wrote a description elsewhere. Their version was better so I overwrote my copy.

**Comment by cho-m** [comment]
It looks like livecheck URL (https://flic.io/mac-app/download) is still downloading `2.0.2`.

However, actual webpage https://flic.io/mac-app shows `2.1.0`
(**Download app** button = https://misc-scl-cdn.s3.amazonaws.com/Flic.2.1.0.zip)

It may be worth reaching out to Flic to see if former is still valid URL.
Otherwise, livecheck may need to be updated to `page_match` on https://flic.io/mac-app

**Review by reitermarkus — DISMISSED** [review]

**Comment by kortenkamp** [comment]
Hi, I am not sure how I could help here – the new version ist definitely 2.1.0, which is the one the "download app" button points to at https://flic.io/mac-app as already pointed out by @cho-m . I can write a new livecheck, but probably @MarcelloNicoletti has to add another commit to this update? Alternatively, if someone closes this merge request I can submit a new one for 2.1.0.

**Review by miccal — APPROVED** [review]

**Pull request merged**
