### PR TITLE
Delete manopen

### PR DESCRIPTION
**Pull request by miccal**
`homepage` and `url` appear dead:
```
-bash-5.0.16- /Users/miccal (32) [> brew cask fetch manopen

==> Downloading external files for Cask manopen
==> Downloading http://www.clindberg.org/projects/ManOpen-2.6.dmg
curl: (28) Failed to connect to www.clindberg.org port 80: Operation timed out
Warning: Transient problem: timeout Will retry in 1 seconds. 3 retries left.
curl: (28) Failed to connect to www.clindberg.org port 80: Operation timed out
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
curl: (28) Failed to connect to www.clindberg.org port 80: Operation timed out
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
curl: (28) Failed to connect to www.clindberg.org port 80: Operation timed out

Error: Download failed on Cask 'manopen' with message: Download failed: http://www.clindberg.org/projects/ManOpen-2.6.dmg
```
Ping @vitorgalvao for confirmation.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Was working this month. Let’s give it a week.

```
manopen
30 days: 2 (#4494)
90 days: 12 (#3913)
365 days: 74 (#3263)
Age: 2010 days (added 2014, September 29)
```

**Comment by vladimyr** [comment]
It can be downloaded from https://web.archive.org/web/20190910122314/http://www.clindberg.org/projects/manopen.html

**Comment by vitorgalvao** [comment]
We only allow official links. Internet Archive links are absolutely not allowed, not the least of which because they provide a great service and leaning on them for bandwidth is not something we should do.

**Comment by vladimyr** [comment]
> We only allow official links. Internet Archive links are absolutely not allowed, not the least of which because they provide a great service and leaning on them for bandwidth is not something we should do.

Ofc, this wasn't a suggestion more like a pointer to those _coming from the future_ who might need it and aren't aware of it.

**Pull request merged**
