### PR TITLE
foobar2000: submission

### PR DESCRIPTION
**Pull request by i0ntempest**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by miccal** [comment]
@i0ntempest this was removed in the past because the `url` was unstable -- please see https://github.com/Homebrew/homebrew-cask/pull/73310 and https://github.com/Homebrew/homebrew-cask/pull/73629.

**Comment by i0ntempest** [comment]
I wrote a `url do` block, should make it always work.

**Comment by vitorgalvao** [comment]
Thank you, but we don’t want such blocks to circumvent draconian download policies. They should only be used for casks such as nightlies, where manual updating is impractical.

**Comment by vitorgalvao** [comment]
Thank you, but we don’t want such blocks to circumvent draconian download policies. They should only be used for casks such as nightlies, where manual updating is impractical.

[This policy is documented](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#some-providers-block-command-line-downloads).

**Pull request closed without merging**
