### PR TITLE
Update Stork to 1.0.0,1290

### PR DESCRIPTION
**Pull request by xquezme**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Why have you added the `.delete("^0-9")` parts?

**Comment by xquezme** [comment]
@miccal For some reason, automatic live check doesn't work for me. Nothing has changed in my semantic versioning system.

Before this PR, I tried updating with `brew bump-cask-pr` and `brew` tried to download `https://downloads.stork.ai/macos/release/Stork-1.0.0.1290..dmg` (the double dot at the end). It fails ofc.

I guess something changed in the live-check mechanism after October 27 (date of latest auto-updated release `1.0.0.1176`).

**Comment by miccal** [comment]
It is working for me:
```
|-> brew livecheck stork --debug

Cask:             stork
Livecheckable?:   Yes

URL:              https://downloads.stork.ai/macos/release/app_cast.xml
Strategy:         Sparkle

Matched Versions:
1.0.0,1290
stork : 1.0.0,1176 ==> 1.0.0,1290
```

**Comment by miccal** [comment]
Please remove the `.delete("^0-9")` and let's see what the CI says.

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/115100 due to CI issues.

**Pull request closed without merging**
