### PR TITLE
Add DeepGit.app V3.2

### PR DESCRIPTION
**Pull request by muescha**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by core-code** [comment]
thanks but can we make sure that all casks that are added with a version stanza also have an appcast? i propose 
appcast 'https://www.syntevo.com/deepgit/download/'

**Comment by muescha** [comment]
@core-code i don't know about an appcast for the deepgit :(

**Comment by core-code** [comment]
as noted above we can just use

appcast ’https://www.syntevo.com/deepgit/download/‘

**Comment by muescha** [comment]
ok - i missed this line in [appcast stanza](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md): 

> An appcast can be any URL hosted by the app’s developer that changes every time a new release is out (e.g. a changelog HTML page).


maybe add if this a requirement then it should added to [adding_a_cask.md](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md) and to the templates?

**Comment by core-code** [comment]
i agree that the appcast stanza should be added to the template. i'll probably send a pull request for that unless someone beats me to it ;)

**Pull request merged**
