### PR TITLE
keyboardcleantool: Adjusted version to align with version info in app

### PR DESCRIPTION
**Pull request by forsgren**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by forsgren** [comment]
When downloading from the official page https://folivora.ai/keyboardcleantool/ version 4 is provided.

**Comment by bevanjkay** [comment]
@forsgren CI is looking at the version in the app's `info.plist` file and is returning 5, unless upstream's website is using a different download url?

**Comment by forsgren** [comment]
@bevanjkay I'm new to this, thanks for explaining the procedure behind how the CI decides on version info. The download URL is the same. The app itself reports version 4 in the about window, but the `info.plist` sure reports 5. I've pinged the app creator to find out whether something has gone wrong regarding the apps version info :)

**Comment by bevanjkay** [comment]
@forsgren No worries. In this case it's due to `livecheck` stanza using the `:extract_plist` strategy (which checks the app's info.plist file, and is only used for unversioned download URLs when there is no other way to find the version data systematically). Other casks may scrape a webpage to find the latest version, or check an applications update feed.

**Comment by nevack** [comment]
This app incorrectly shows version in About dialog.
Version `6` is already available actually.
https://github.com/Homebrew/homebrew-cask/pull/162247

**Comment by krehel** [comment]
Agreed with @nevack.  Dialog box in version 6 shows correct information and aligns with `Info.plist`.  We'll merge #162247 and close this.  Thanks for submitting @forsgren!

keyboardcleantool 6

**Pull request closed without merging**
