### PR TITLE
Update quickhash to 3.0.3,1770

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> It seems the App source '/usr/local/Caskroom/quickhash/3.0.3,1770/AppleOSX/QuickHash.app' is not there.

**Comment by core-code** [comment]
hm sorry for the late AND wrong fix.

**Comment by core-code** [comment]
;) thanks!

to improve on both fronts
1.) is there a way to get e-mails when a submitted PR has a travis failure? 
2.) i guess its good practice to use QuickLook => BetterZipQL.qlgenerator to see whats actually in the ZIP, i'll try to remember that

**Comment by vitorgalvao** [comment]
> is there a way to get e-mails when a submitted PR has a travis failure?

Probably. I know I got some in the past.

But spend less time thinking Travis and more thinking Azure Pipelines, since we’re in the process of switching.

**Comment by vitorgalvao** [comment]
> is there a way to get e-mails when a submitted PR has a travis failure?

Probably. I know I got some in the past. But I wasn’t the one who configured them (they were repo- or org-specific, maybe?)

But spend less time thinking Travis and more thinking Azure Pipelines, since we’re in the process of switching.

**Comment by core-code** [comment]
ok, of course looking forward to seeing the glorious microsoft future ;)

**Pull request merged**
