### PR TITLE
stellarium 23.1

### LINKED ISSUE #145222: Stellarium file name format has changed
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

It looks like "brew update" does not recognize a new version of stellarium, perhaps because the file naming has changed:
Previous name: 
https://github.com/Stellarium/stellarium/releases/download/v1.2/Stellarium-1.2-macOS.zip

New names (note separate files for arm and intel):
https://github.com/Stellarium/stellarium/releases/download/v23.1/Stellarium-23.1-qt5-arm64.zip 
https://github.com/Stellarium/stellarium/releases/download/v23.1/Stellarium-23.1-qt5-x86_64.zip

I tried to use the bump-cask-pr command but I may not have done it right.  The result follows.

### Command that failed

brew bump-cask-pr --url https://github.com/Stellarium/stellarium/releases/download/v23.1/Stellarium-23.1-qt5-arm64.zip stellarium

### Output of command with `--verbose --debug`

```shell
% brew bump-cask-pr --verbose --debug --url https://github.com/Stellarium/stellarium/releases/download/v23.1/Stellarium-23.1-qt5-arm64.zip stellarium
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromDefaultTapPathLoader): loading stellarium
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.13-34-gad3d207\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.3.1\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=stellarium\+is\%3Apr\+repo\%3AHomebrew\%2Fhomebrew-cask\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github\+json --write-out '
'\%\{http_code\} --header Authorization:\ token\ ****** --header X-GitHub-Api-Version:2022-11-28 --dump-header /private/tmp/github_api_headers20230415-5828-phcn54
==> replace /https:\/\/github\.com\/Stellarium\/stellarium\/releases\/download\/v\#\{version\.major_minor\}\/Stellarium\-\#\{version\}\-macOS\.zip",\n\ \ \ \ \ \ verified:\ "github\.com\/Stellarium\/stellarium\// with #<URI::HTTPS https://github.com/Stellarium/stellarium/releases/download/v23.1/Stellarium-23.1-qt5-arm64.zip>
Error: no implicit conversion of URI::HTTPS into String
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/utils/string_inreplace_extension.rb:36:in `gsub!'
/opt/homebrew/Library/Homebrew/utils/string_inreplace_extension.rb:36:in `gsub!'
/opt/homebrew/Library/Homebrew/utils/inreplace.rb:86:in `block in inreplace_pairs'
/opt/homebrew/Library/Homebrew/utils/inreplace.rb:79:in `each'
/opt/homebrew/Library/Homebrew/utils/inreplace.rb:79:in `inreplace_pairs'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:199:in `bump_cask_pr'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
% brew doctor
Your system is ready to brew.

% brew config
HOMEBREW_VERSION: 4.0.13-34-gad3d207
ORIGIN: https://github.com/Homebrew/brew
HEAD: ad3d207172639396b8585899c43be97d08f58709
Last commit: 15 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cd5030546ca0161c0b27a91a67258bba277c3203
Core tap last commit: 2 hours ago
Core tap branch: master
Core tap JSON: 16 Apr 00:25 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: N/A
Xcode: 14.3
Rosetta 2: false
```

### Output of `brew tap`

```shell
% brew tap
homebrew/bundle
homebrew/cask
homebrew/core
homebrew/services
```

### PR DESCRIPTION
**Pull request by razvanazamfirei**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Fixes #145236.

**Comment by reitermarkus** [comment]
@razvanazamfirei, you should add “Fixes #XXXXX.” to the PR body so it's automatically closed when this is merged.

**Review by reitermarkus — APPROVED** [review]

**Comment by reitermarkus** [comment]
Oh, it seems like a comment also works. I wonder if that's only for maintainer comments though.

**Comment by reitermarkus** [comment]
It also doesn't underline `Fixes` like it does in the PR body to make it obvious.

**Comment by razvanazamfirei** [comment]
@reitermarkus Will do!

**Pull request merged**
