### PR TITLE
updated shadowsocksx (2.6.4)

### PR DESCRIPTION
**Pull request by aieu**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
@registe What happened with the original one? Is this new one official in any capacity?

**Comment by registe** [comment]
@vitorgalvao the original one has stopped development, the new version was not a new official at least for now.
V 2.6.5 has been released by @RobertYan 10 hours before, I will pull new request if you agree.

**Comment by vitorgalvao** [comment]
The old one says “Removed according to regulations”, which suggests it was abandoned not by choice. Do you know what happened?

**Comment by registe** [comment]
@vitorgalvao Because the government (PRC) requires, many times we have no choice.
Thanks to GPLv3,  everyone can be able to fork the repo.

**Pull request closed without merging**
