### PR TITLE
Delete kindlegen

### PR DESCRIPTION
**Pull request by slonopotamus**
1. It never actually worked on MacOS Catalina because the latter doesn't support 32-bit binaries
2. It is no longer available for download: https://www.amazon.com/gp/feature.html?docId=1000765211

> KindleGen is no longer available for download. Please use Kindle Previewer to convert, preview, and validate your eBooks.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by slonopotamus** [comment]
Note that CI has [logged an error](https://github.com/Homebrew/homebrew-cask/actions/runs/225041586) but still claims to be successful.

**Comment by vitorgalvao** [comment]
Thank you, and welcome.

**Comment by inklesspen** [comment]
Ever since this cask was removed, I get this error:
```
Error: Cask 'kindlegen' is unreadable: undefined method `undent' for #<String:0x00007fb316b1db38>
```

Even when I try uninstalling the cask.

**Comment by vitorgalvao** [comment]
@inklesspen https://github.com/Homebrew/homebrew-cask/issues/49716#issuecomment-413515303

**Comment by MrJoy** [comment]
So...  Two years on, and no proper fix?  Can't you at least catch the exception and print instructions on how to resolve things?

**Comment by vitorgalvao** [comment]
> So... Two years on, and no proper fix?

I struggle to understand what leads someone to ask of volunteers “why haven’t you spent your free time fixing this particular part of your freely-distributed work that affects me”. The code is there for everyone to see. We’ve been working on other things as well.

> Can't you at least catch the exception and print instructions on how to resolve things?

As explained on the linked issue, it isn’t a single exception (and the fix is very much a workaround) but a deeper problem.

**Comment by MrJoy** [comment]
> > So... Two years on, and no proper fix?
> 
> I struggle to understand what leads someone to ask of volunteers “why haven’t you spent your free time fixing this particular part of your freely-distributed work that affects me”. The code is there for everyone to see. We’ve been working on other things as well.

I struggle to understand how someone can spend time working on a tool with the goal of getting people to use it and then get defensive when it's pointed out that it's not fit for purpose and is costing users on-trivial amounts of time/energy.

I wouldn't have said anything of the sort, except that you threw out the link to that comment as if that solves the issue.  It comes across as dismissive, to say the least.

And yeah, I read through a bunch of the code after initial Googling didn't reveal anything newer than 2018 or so.  It's not an obvious enough codebase for me to have had luck with that in a reasonable time window.  I couldn't even find where `undent` was actually getting _called_ -- other than from test cases.  I'm sure if I were willing to blow a few hours on it I could learn enough of the project structure to figure things out but I frankly "you have the source, [so f*** off]" is not an attitude that's gonna get me to contribute.  The last time I heard that, I threw away software I'd paid hundreds of dollars for (Torque) and paid thousands of dollars for its competitor (Unity).  I did not come to regret that decision.

So, I guess it's time for me to invest some time in looking at Nix.


> As explained on the linked issue, it isn’t a single exception (and the fix is very much a workaround) but a deeper problem.

Perhaps presenting the workaround as a potential solution on _any_ uncaught exception would be a net benefit then.

Or, alternatively:  If nuking casks causes the tool to break for people who have that cask installed is a known issue, then nuking choosing to nuke casks is basically a great way to steal time from the people who chose to use this tool.  You're effectively externalizing the costs of a design flaw you haven't figured out how to resolve or even mitigate.  Instead, you could, I dunno, add a mechanism to flag a cask as _defunct_, so it doesn't show up when doing a search, or can't be installed or some such -- but leave the file around.

**Comment by vitorgalvao** [comment]
> I wouldn't have said anything of the sort, except that you threw out the link to that comment as if that solves the issue. It comes across as dismissive, to say the least.

That’s your interpretation. I’d call it effective, and the vast majority of people understand it and take no offence. Seeing as the person I gave the link to gave a positive reaction, I’d say that was also the case here.

> "you have the source, [so f*** off]"

That’s not what I said, and I wouldn’t tell you that. I haven’t insulted you or been rude to you. But I’m not surprised you interpreted it that way, given the rest of your response.

> The last time I heard that, I threw away software I'd paid hundreds of dollars for (Torque) and paid thousands of dollars for its competitor (Unity). I did not come to regret that decision.

You’re getting Homebrew for free. The comparison isn’t even close.

> So, I guess it's time for me to invest some time in looking at Nix.

I also don’t understand that threat. I don’t remember you ever having contributed to HBC before, and assuming you’re also not contributing monetarily, what’s the effect?

We’re not enemies of other package managers. We like open-source developers and can benefit from each other’s work. You should use whatever tool better you like best and better fits your needs. If you’re so quick to dismiss an entire community and piece of software based on one interaction, *and one that you misunderstood* at that, that’s your prerogative.

We appreciate every one of our users, as long as they’re respectful. I haven’t been disrespectful to you. I could perhaps have worded my reply better, but in fairness your first approach wasn’t the best either (not that that excuses anything). Unfortunately, it’s always the users with a short contributions graph to open-source that comes guns blazing, and that no doubt taints some interactions.

I genuinely wish you a good and peaceful day and that you make the choice of package manager that serves you best. I’m locking the conversation because I don’t feel continuing the discussion will be productive. You’re still welcome to make PRs or open issues for other problems not yet tackled.

**Pull request merged**
