### PR TITLE
Help wanted: Updated and renamed ankerslicer to ankermake

### PR DESCRIPTION
**Pull request by kvanzuijlen**
The previous version number was incorrect. It should've been 0.7.5 (which was also a beta version.

TODO: I suspect the live check should be updated as well, but I'm not sure about the correct way to do this. Also, I'm not sure if renaming this cask is possible.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
`livecheck` is looking for the version number inside of the app's `info.plist` file, which is reporting `2.0.0`. So there is an issue with the app where the version number present in the app's software update section is different from the version in the app's bundle.

In regards to renaming, I would recommend waiting until https://github.com/Homebrew/brew/pull/15176 is completed.

**Comment by bevanjkay** [comment]
We should wait until Cask Renames is in a tagged release before merging any rename PRs.

**Comment by unitof** [comment]
@bevanjkay It was in a tagged release May 14. Just opened an updated PR off this one: #147432.

**Pull request closed without merging**
