### PR TITLE
Update Synergy to 1.8.4

### PR DESCRIPTION
**Pull request by schlueter**
If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.

After making all changes to the cask:
- [x] brew cask audit —download synergy is error-free.
- [x] brew cask style —fix synergy reports no offenses.
- [x]  The commit message includes the cask’s name and version. Version updated.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
There was a [pull request template](https://github.com/blog/2111-issue-and-pull-request-templates) when you submitted. It must be filled.

If you were not presented a template, you may have submitted via a CLI tool (likely [`hub`](https://hub.github.com/)). It that was the case, you may wish to see if the tool has a way to let you use the template (`hub` [is working on it](https://github.com/github/hub/issues/1118)).

In either case, please [refer to the template](https://raw.githubusercontent.com/caskroom/homebrew-cask/master/.github/PULL_REQUEST_TEMPLATE.md) and update your comment.

**Comment by schlueter** [comment]
Templates aren't picked up by hub, I'm adding now.

**Comment by schlueter** [comment]
How do I clear ```
== Casks/synergy.rb ==
C:  8:  1: stanza groups should be separated by a single empty line```?

**Comment by vitorgalvao** [comment]
You need to remove `license` (no longer in use). Not sure why it’s still on the cask.

**Comment by vitorgalvao** [comment]
Why close this?

**Pull request closed without merging**
