### PR TITLE
vivid 2.9

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by antonengelhardt** [comment]
@krehel 

When upgrading or installing this returns:

```
➜ brew install --cask vivid                                                                                                                                                                                                             (base)
==> Downloading https://lumen-digital.com/apps/vivid/releases/Vivid2.9.zip
Already downloaded: /Users/antonengelhardt/Library/Caches/Homebrew/downloads/107fa9e9f23596f2c6265aaccf27b8b2fcff07c62a67feec94e93ad8f69d81cb--Vivid2.9.zip
Error: SHA256 mismatch
Expected: f864d540f8ec2add56590956bf33b9979302dec0314c69451274e0921172d291
  Actual: ccff34bbf7d0285c2076089112e4b27323b83eb8570d60213d14e0cc4676ec28
    File: /Users/antonengelhardt/Library/Caches/Homebrew/downloads/107fa9e9f23596f2c6265aaccf27b8b2fcff07c62a67feec94e93ad8f69d81cb--Vivid2.9.zip
To retry an incomplete download, remove the file above.
```

Also after deleting the mentioned file, this issues persists.

**Comment by vvvvv** [comment]
I guess they're releasing new builds without bumping the version which is pretty shady imo.  
yesterday I had the same issue like @antonengelhardt with the exact same sha256 mismatch and verified the checksum by manually downloading the zip.   

Just now I wanted to fix this issue and after another `brew upgrade` I get 
```
Expected: f864d540f8ec2add56590956bf33b9979302dec0314c69451274e0921172d291
  Actual: 45f180d875f38882eac81293fc524458ed6f1dcffac4927cf28cfbb8c617dcb4
```

```
$ shasum --algorithm=256 $(fd -i vivid $(brew --cache)/downloads)
45f180d875f38882eac81293fc524458ed6f1dcffac4927cf28cfbb8c617dcb4  [..]/downloads/107fa9e9f23596f2c6265aaccf27b8b2fcff07c62a67feec94e93ad8f69d81cb--Vivid2.9.zip

$ curl --location --show-error --silent -o vivid2.9.zip https://lumen-digital.com/apps/vivid/releases/Vivid2.9.zip && shasum --algorithm=256 ./vivid2.9.zip
45f180d875f38882eac81293fc524458ed6f1dcffac4927cf28cfbb8c617dcb4  ./vivid2.9.zip
```

So what's the correct way to proceed here? 
The vendor didn't bump the version but technically they did release several new versions after this pr was merged.

**Comment by krehel** [comment]
Yeah, this is not best practice as we're all noting.  Homebrew can certainly update it, but it would be good to know -why- this is happening and if this is a continued expectation.  If it is, we'll probably have to remove the `sha256` check to prevent ongoing breakage.  But that obviously comes with its own concerns and don't want to do that unless absolutely needed.

I don't use this software - would either of you @antonengelhardt or @vvvvv mind reaching out to the vendor to ask these questions regarding in place updates and expectations?  Thank you

**Comment by antonengelhardt** [comment]
@vvvvv Thanks!

@krehel How can i run `brew upgrade` and ignore the sha mismatch for vivid?

**Comment by krehel** [comment]
Thanks @vvvvv.

Would be nice to know if this is expected going forward or just a one off problem, and getting a note on the 'final' `sha256`.  We can then decide accordingly.

@antonengelhardt - hack way is you can update your local copy with the `sha256`, run an install, and then discard your changes to align back with Homebrew.  If it doesn't change again, you should be set.  If it does change again, once we're fixed here correctly you can then do a reinstall to get the same version with the updated `sha256`

**Comment by vvvvv** [comment]
Quick update: they replied that they indeed released multiple versions.  
I wrote a follow-up email asking politely if they would be willing to publish builds for Brew under a different path, such as https://lumen-digital.com/apps/vivid/releases/Vivid{version}_{build_number}.zip, as this would allow Brew to depend on a fixed build.

If this isn't feasible for them, then the Brew community may need to consider switching to `version :latest` and using the `Last-Modified` header to determine the build or dropping support for Vivid altogether.

In the meantime, I guess we could release a new version, vivid2.9_build1 (or 3, which would be more accurate), with the updated checksum.  
I'm in a bit of a rush right now, but I should be able to create a new pull request with the revised version tonight.

I'll keep this issue updated.

**Comment by krehel** [comment]
Thanks @vvvvv!  Much appreciated on taking the lead here. 🙏 

The obvious answer for upstream is just bump a point version on a re-release, don't publish the same version again.  Easily avoidable scenario.  We all know this already, though.

Possible concern about the long term support for a specific path for brew, i.e. it gets forgotten about and not updated.  What you're describing should just be the standard release 😄

**Comment by vvvvv** [comment]
Yes, bumping the version would be the appropriate action and I should have mentioned in my previous comment that upstream decided against it to avoid version spamming their users (I assume this is because they also distribute auto-updates).

This isn't how I would handle it but it's not my place to dictate how upstream should manage their software releases.  
Their email was friendly worded so I'm optimistic that this was a one-off situation and we can find a compromise that satisfies both parties.

In the meantime I've issued a hotfix to resolve the issue with the cask.  
I'm not proud of this code but I couldn't find a simpler solution without completely rewriting the livecheck.

I understand if this workaround is unsatisfactory for you and you prefer to leave the cask in its broken state while waiting for a response from upstream.  
My rationale for a hackish solution like the one I've implemented is that, depending on upstream's willingness to cooperate, we may need to either rewrite the livecheck or remove the cask entirely.

If we reach an agreement, I would be willing to implement a proper solution.

**Comment by krehel** [comment]
Sorry @vvvvv I missed this comment.  You're 100% correct w.r.t dictating how upstream operates, and I appreciate everything you've done here in working with upstream.

I think we'll just take the simple path now and bump the checksum along with monitoring going forward.  It's not preferred to keep broken things around, and you've gone beyond what most would do in helping to address this.

**Pull request merged**
