### PR TITLE
removed tinkertool.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
Current download url isn’t official; official download url has a key. We need to either find a way to download it bypassing that, or remove this.

### CODE REVIEW

**Comment by svenjacobs** [comment]
Since I did not find Marcel Bresink, the author of TinkerTool, on GitHub, I wrote him an email asking if he would be willing to provide a Cask-friendly download link for TinkerTool.

**Comment by vitorgalvao** [comment]
Sounds good.

**Comment by Jahhein** [comment]
I just wrote up a new tinkertool.rb for version 6.0. All checks out in the requirements and then I found this. Everything seems to work perfectly, anything I may be missing on this Application's past? If wanted, I'll push it over.

**Comment by vitorgalvao** [comment]
@Jahhein As [stated on the top](https://github.com/caskroom/homebrew-cask/pull/9082#issue-54721099):

> Current download url isn’t official; official download url has a key.

Haven’t checked now and don’t remember the details then, but out simply it seems the old official URL was unsuitable for download (had an expire key?) and the URL in this cask was not officially supported (and we don’t allow those).

**Pull request merged**
