### PR TITLE
mullvadvpn: Cleanup shell completions

### PR DESCRIPTION
**Pull request by Moulick**
After uninstalling Mullvad VPN, it leaves behind invalid symlinks for zsh and fish shell completions. The linked file in the `Mullvad VPN.app` is deleted but the symlink is not. This causes errors when running compinit in zsh

<details><summary>Error in compinit</summary>
<p>

`compinit:527: no such file or directory: /usr/local/share/zsh/site-functions/_mullvad`

</p>
</details> 

I have created a bug in mullvad's repo as well, I dunno if they can fix it on their side if the app is installed/uninstalled with brew https://github.com/mullvad/mullvadvpn-app/issues/6450

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by Moulick** [comment]
I assume the same problem exists for `mullvadvpn@beta`. If this is accepted, I'll make a PR for it as well :)

**Comment by p-linnane** [comment]
I was going to say we shouldn't hardcode the paths to the brew prefix like that...but it appears they are hardcoded within the post install script the .pkg runs. Thoughts @Homebrew/cask?

**Comment by krehel** [comment]
I think we do what we have to do to clean up files - this is pretty minor all things considered.  Maybe not the best way, but insignificant considering if the files don't exist, nothing breaks.  I'm fine to ✅

**Comment by Moulick** [comment]
> I think we do what we have to do to clean up files - this is pretty minor all things considered. Maybe not the best way, but insignificant considering if the files don't exist, nothing breaks. I'm fine to ✅
> 
> Ultimately, it would be ideal if upstream did it properly, so @Moulick I appreciate you opening the issue with it. Let's see where it goes.

As I am mostly unfamiliar with Apple packaging, Can an application actually run scripts for cleanup when uninstalled via brew?

I not sure how long upstream will take to fix this, if they can, so should this PR wait? I would rather not wait, and I'll send another PR reverting this if the actual issue is fixed by Mullvad VPN

**Review by krehel — APPROVED** [review]

**Comment by krehel** [comment]
Yes, brew can fire shell scripts on uninstall.

**Pull request merged**
