### PR TITLE
Update yuque from 0.10.2 to 1.0.3

### PR DESCRIPTION
**Pull request by vitahlin**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @vitahlin, but we keep this version as per the `livecheck` as explained in the Cask file:
```
  # The stable version is that listed on the download page. See:
  #   https://github.com/Homebrew/homebrew-cask/pull/111472
  livecheck do
    url "https://www.yuque.com/install/desktop"
    regex(/desktopDownloadVersion%22%3A%22(\d+(?:\.\d+)*)/i)
  end
```

**Comment by vitahlin** [comment]
@miccal 1.0.3 was in beta when I pulled, now it is in official version. I run `brew bump-cask-pr --version 1.0.3 yuque` but reports an error, I will keep an eye on the beta version and what I can do not to update?
```
==> Downloading https://app.nlark.com/yuque-desktop/Yuque-1.0.3.dmg
Already downloaded: /Users/vitah/Library/Caches/Homebrew/downloads/84216a868dfa6e3b69876222e031354887c1273d0dc10441e48eb91bd07dbad8--Yuque-1.0.3.dmg
==> Downloading https://app.nlark.com/yuque-desktop/arm64/Yuque-1.0.3.dmg
Already downloaded: /Users/vitah/Library/Caches/Homebrew/downloads/66281b9ecf0e50d26edca8be8254f5fe9b041fb1797cacaa9d530c35dc07d695--Yuque-1.0.3.dmg
==> replace /version\s+["']1\.0\.3["']/m with "version \"1.0.3\""
==> replace "58ca2a09b575ebc118bcb9c800a3c72b1bb5142ec17b1376f1bfc842ffbc5328" with "58ca2a09b575ebc118bcb9c800a3c72b1bb5142ec17b1
==> replace /sha256\s+["']b81398d9bc7b241deeb19e73ccea9c48229ac791617dc4cc8de518b553cdf978["']/m with "sha256 \"b81398d9bc7b241dee
audit for yuque: passed

1 file inspected, no offenses detected
fatal: A branch named 'bump-yuque-1.0.3' already exists.
Error: Failure while executing; `git checkout --no-track -b bump-yuque-1.0.3 origin/master` exited with 128.
```

**Comment by miccal** [comment]
@vitahlin you will need to delete the old branch via `git branch -D bump-yuque-1.0.3` before running `brew bump-cask-pr` again.

**Comment by vitahlin** [comment]
Thanks

**Pull request closed without merging**
