### PR TITLE
Add Musixmatch v3.2.0

### PR DESCRIPTION
**Pull request by sagelga**
Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/58737

**Comment by sagelga** [comment]
@vitorgalvao Here's what I think of why you should merge this PR instead of closing.
1. This release is now on official release. Not a beta or alpha development phase. So there will be less update hassle.
2. People does actually use the Musixmatch on Desktop, as the company still releasing new versions since 2017. That's assure of their mission to keep this app available for users. 
3. This app can automatically updates itself. No need for home-brew later on.

I understand that 3 months ago it's still annoying to maintain this, but the time has changed.
Please reconsider this PR decision. Thank you.

**Comment by vitorgalvao** [comment]
> People does actually use the Musixmatch on Desktop

Not our users. The cask was removed because it was a hassle *and* had too few users.

> This app can automatically updates itself.

So can many other casks. This is irrelevant.

> No need for home-brew later on.

Incorrect. The cask still needs to be kept up-to-date.

On another note, as you can see from the linked PR, you submission was incomplete (and not functional, even).

**Comment by saulocastelo** [comment]
> > People does actually use the Musixmatch on Desktop
> 
> Not our users. The cask was removed because it was a hassle _and_ had too few users.

I love brew because I don't need to search for any app.
I love brew because I can update all "non apple store apps" with a single command.
I love brew because It's easy to find, install and keep updated.

I don't love brew because if has too few users the cask/formula will be removed instead ask for maintainers. 👎 
I don't love brew because I don't need one more Apple Store that says what can be there or not.

Please take this feedback in consideration.

I really need one way to keep my apps updated no matter if I'm the only user or not.

I saw that we need to keep the downloaded app sha-256 checksum updated. So just an idea... If one person try to install and an error is returned, the maintainer can receive one email to check if there's a new version?

If there's any way to improve brew to be better than Apple Store, let's talk, maybe we can find some solutions.

Thanks for your hard work, I know that always will have one person that don't like something. But I'm trying to make it better.

Fell free to contact me.

PS: I'm love Musixmatch and use every time..... regarding the lyrics, I can learn another languages by listening music.

Have a great day/night/week/month/year =D

**Comment by vitorgalvao** [comment]
> I don't love brew because I don't need one more Apple Store that says what can be there or not.

> I really need one way to keep my apps updated no matter if I'm the only user or not.

The answer to both cases is the same: host and maintain your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).

I hope you’re not suggesting that maintainers—which are all volunteers—should spend their free time maintaining a cask that only you use. We have to spend our time where it makes the most difference, not serving a single user at our own personal expense.

> So just an idea... If one person try to install and an error is returned, the maintainer can receive one email to check if there's a new version?

No. That’s what this issue tracker is for.

> Thanks for your hard work

Thank you for your words of appreciation.

> I know that always will have one person that don't like something. But I'm trying to make it better.

Again: maintaining the tap for yourself and the few that want the app is the solution.

> Have a great day/night/week/month/year

Thank you. You too.

**Comment by saulocastelo** [comment]
@vitorgalvao First, thanks for taking your time to answer me so fast. And... English is not my first language so, sorry about any wrong sentence.

Now .... 
> I hope you’re not suggesting that maintainers—which are all volunteers—should spend their free time maintaining a cask that only you use.

Please don't get me wrong and please correct me if I'm wrong, but I was actually think something like this. When I saw that this cask got removed, my first thought was that there is no one to maintain, so I can do this! Then I saw this:
> Not our users. The cask was removed because it was a hassle and had too few users.
So... my thought was that even if I take my free time to maintain this, my pull request will not be accepted.

What I tried to say was: You should not remove some cask/formula just because there's only a few users (In my opinion). Specially if is automatically updated.

If the user has to search for some TAP to get an app, isn't easier just download the app and Install?
I love AUR (Arch User Repository) because every think is there.
I hate Ubuntu PPA because I need to search, find and add the PPA for what I want to be able to install.

When some package get orphan on AUR, anyone can become the maintainer.

MAYBE there's one way for us to make Homebrew more like the AUR?
Perhaps working like the TAP command: brew register formula/cask "Formula/Cask Name" "user/repo/foo" "some description"
In my case: brew register cask Musixmatch saulocastelo/my_homebrew_contributions/cask/musixmatch "One Amazing Lyrics App"

When the user type: brew cask install Musixmatch (enter)
ATENTION: THIS CASK IS NOT MAINTAINED BY THE HOMEBREW TEAM. REVIEW THE CASK CODE BEFORE INSTALL AND ONLY PROCEED IF YOU TRUST!

Again ... thanks!
Live long and prosper

**Comment by vitorgalvao** [comment]
> You should not remove some cask/formula just because there's only a few users

[I was explicit](https://github.com/Homebrew/homebrew-cask/pull/63142#issuecomment-491588791) that was not the only reason. You even quoted that part! I don’t recall why the cask was a hassle, but I do remember it gave constant problems.

We don’t have plans to readd the cask at this time. Not enough people care and it’s a net loss in maintenance time, meaning the whole project suffered by having it included.

**Comment by pbrit** [comment]
Here is Musixmatch Cask in my private tap: https://github.com/pbrit/homebrew-pbrit/commit/546707a66f9986a5f5145778c0ec5473f8e7b220

I am going to maintain it.

**Comment by vitorgalvao** [comment]
> Here is Musixmatch Cask in my private tap: [pbrit/homebrew-pbrit@546707a](https://github.com/pbrit/homebrew-pbrit/commit/546707a66f9986a5f5145778c0ec5473f8e7b220)

That cask won’t work as is, nor pass `audit` nor `style`.

**Comment by pbrit** [comment]
> > Here is Musixmatch Cask in my private tap: [pbrit/homebrew-pbrit@546707a](https://github.com/pbrit/homebrew-pbrit/commit/546707a66f9986a5f5145778c0ec5473f8e7b220)
> 
> That cask won’t work as is, nor pass `audit` nor `style`.

Could you please share the exact error or whatever why it doesn't work as it is. Thanks.

**Comment by vitorgalvao** [comment]
> Could you please share the exact error or whatever why it doesn't work as it is. Thanks.

For one, it doesn’t have an `app`, so it installs nothing. Other than that, run `brew cask style` on it and it will light up with errors.

**Pull request closed without merging**
