### PR TITLE
Upgrade Shoes to 3.2.25

### PR DESCRIPTION
**Pull request by jikkujose**
My first submission to Cask, hope I have done this right.

### CODE REVIEW

**Comment by fanquake** [comment]
You've added an extra line, please remove it, and squash any extra commits.

**Comment by JikkuJose** [comment]
Hope I have fixed it?

**Comment by vitorgalvao** [comment]
Thank you. Merged in https://github.com/caskroom/homebrew-cask/commit/361659075172aa1e9ab44aea055e7ecd23ba7376 to keep commit history cleaner. The contribution is still credited to you.

**Comment by JikkuJose** [comment]
Thanks :)

**Pull request closed without merging**
