### PR TITLE
Update amd-power-gadget from 0.6.4 to 0.6.5

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
```
Error: audit failed for casks: amd-power-gadget
audit for amd-power-gadget: failed
 - 0.6.5 is a GitHub prerelease
##[error]Process completed with exit code 1.
```

**Review by core-code — APPROVED** [review]

**Comment by core-code** [comment]
the 'ci-skip-appcast' label doesn't seem to work yet.

**Comment by core-code** [comment]
@reitermarkus am i correct that 'ci-skip-appcast' doesn't work yet but 'ci-verified-manually' has been removed?

**Comment by reitermarkus** [comment]
@core-code, you need to manually re-run CI currently after applying the label.

I'm working on an action that does it automatically again when the label is applied.

**Comment by core-code** [comment]
thanks there. i did already click 're-run' but i can try it again.

**Comment by reitermarkus** [comment]
Maybe you clicked re-run on the Review action rather than the CI action.

**Comment by reitermarkus** [comment]
Ah, the pre-release check is not an appcast check.

**Comment by miccal** [comment]
Duplicate of https://github.com/Homebrew/homebrew-cask/pull/88642

**Pull request closed without merging**
