### PR TITLE
Update camtasia from 2019.0.7 to 2019.0.8

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
i can confirm that the official download URL has version 2019.0.8 although the appcast (release notes) have not yet been updated

**Comment by core-code** [comment]
hm should we change the appcast to 'https://www.techsmith.com/api/v/1/products/getallversions/9' ?

**Comment by core-code** [comment]
or 'ftp://ftp.techsmith.com/pub/products/camtasiamac/releases/' though we'd probably need a CGI to convert a FTP directory listing to HTTP

**Comment by vitorgalvao** [comment]
You make extensive use of the appcast, so I’m fine with changing it to whatever you find works best.

**Pull request merged**
