### PR TITLE
Update dcp-o-matic-player to 2.12.13

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by alebcay** [comment]
Is there any particular reason why this appears to be a downgrade from 2.13.68 to 2.12.13?

**Comment by ran-dall** [comment]
@alebcay @reitermarkus The original download was reported broken by @core-code in #55268 and http://macupdater.net/cask-repair/failingcasks-withoutfeed-2018-12-03.txt

**Comment by ran-dall** [comment]
@alebcay Did you have an updated link or can we merge and close? 👻

**Comment by core-code** [comment]
all 2.13 releases are test releases and should have never entered HBC
https://dcpomatic.com/test-download

latest stable is 2.12.13 ( https://dcpomatic.com/download ) and therefore this PR is correct

**Pull request merged**
