### PR TITLE
Add new cask DetectX Swift 1.085

### PR DESCRIPTION
**Pull request by dmlemos**
Add DetectX Swift

After making all changes to the cask:
- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

This cask is a new version of [DetectX](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/detectx.rb). Decided to add as a new cask because it seems to be taking a new direction and the name has changed. More info on the [website](https://sqwarq.com/detectx/)

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by dmlemos** [comment]
Not sure why the `caveat` was removed, but I meant to use `if MacOS.version >= :mojave`.

**Comment by vitorgalvao** [comment]
> Not sure why the `caveat` was removed

Because [it was usage-related, not installation-related](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats).

**Comment by dmlemos** [comment]
That's true. In that case I wish there was a feature for usage-related. The problem with omitting this caveat is that the program needs this permission for `mojave` in order to function 100%. A user that installs this cask without knowing it, will inadvertently use the program in the wrong way.

**Comment by vitorgalvao** [comment]
> In that case I wish there was a feature for usage-related.

Not enough interest to justify the new feature. We discussed it in the past.

> the program needs this permission for `mojave` in order to function 100%.

As do tons of others. Such is the nature of macOS Mojave’s annoying security theatre. I’m open to discussing making such a message a proper `caveat`, depending on the evolution of macOS’s system.

**Pull request merged**
