### PR TITLE
Rename and update PhotoScan to Metashape 1.5.2

### PR DESCRIPTION
**Pull request by tomyun**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

----

Agisoft PhotoScan (Pro) has been renamed to Metashape (Pro) [since 1.5.0](https://agisoft.freshdesk.com/support/solutions/articles/31000147966-how-can-i-update-from-photoscan-to-metashape-is-it-free-).

### CODE REVIEW

**Comment by reitermarkus** [comment]
Please split this up into two PRs.

**Comment by tomyun** [comment]
Two separate PRs for each edition (standard / pro) or for each step (rename / update)?

**Comment by reitermarkus** [comment]
One for each edition, i.e. one deletion and one addition per PR.

**Comment by tomyun** [comment]
This PR now contains changes for standard edition only. Pro edition has own PR at #64262.

**Comment by reitermarkus** [comment]
Thanks, @tomyun!

**Pull request merged**
