### PR TITLE
Update audirvana-plus to 3.2.16

### PR DESCRIPTION
**Pull request by mahori**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Verifying manually.

**Comment by core-code** [comment]
doesn't actually install for me
```
brew cask install audirvana-plus
==> Satisfying dependencies
==> Downloading https://audirvana.com/delivery/AudirvanaPlus_3.2.16.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'audirvana-plus'.
==> Installing Cask audirvana-plus
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/iZotope_Resampler.framework/Resources with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/iZotope_Resampler.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/iZotope_Resampler.framework/Versions/Current with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/iZotope_Resampler.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/PrivateHeaders with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/PrivateHeaders
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Resources with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Versions/A/Resources/fr_CA.lproj with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Versions/A/Resources/fr_CA.lproj
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Versions/A/Resources/pt.lproj with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Versions/A/Resources/pt.lproj
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Versions/Current with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Modules with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Modules
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/tag.framework/Resources with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/tag.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/tag.framework/Versions/Current with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/tag.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/iZotope_MBITPlus.framework/Resources with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/iZotope_MBITPlus.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/iZotope_MBITPlus.framework/Versions/Current with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/iZotope_MBITPlus.framework/Versions/Current
==> Purging files for version 3.2.16 of Cask audirvana-plus
Error: Failure while executing; `cp -pR /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana\ Plus.app/. /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana\ Plus.app` exited with 1. Here's the output:
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/iZotope_Resampler.framework/Resources with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/iZotope_Resampler.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/iZotope_Resampler.framework/Versions/Current with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/iZotope_Resampler.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/PrivateHeaders with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/PrivateHeaders
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Resources with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Versions/A/Resources/fr_CA.lproj with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Versions/A/Resources/fr_CA.lproj
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Versions/A/Resources/pt.lproj with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Versions/A/Resources/pt.lproj
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Versions/Current with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Modules with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/Sparkle.framework/Modules
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/tag.framework/Resources with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/tag.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/tag.framework/Versions/Current with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/tag.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/iZotope_MBITPlus.framework/Resources with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/iZotope_MBITPlus.framework/Resources
cp: cannot overwrite directory /usr/local/Caskroom/audirvana-plus/3.2.16/Audirvana Plus.app/./Contents/Frameworks/iZotope_MBITPlus.framework/Versions/Current with non-directory /var/folders/4s/clr73zjj3fdgh6dbd47yx49m0000gn/T/d20190407-57754-5c3zru/Audirvana Plus.app/./Contents/Frameworks/iZotope_MBITPlus.framework/Versions/Current


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:107:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:50:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:31:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:17:in `system_command!'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/directory.rb:19:in `block in extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/directory.rb:18:in `each'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy/directory.rb:18:in `extract_to_dir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:120:in `extract'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:140:in `block in extract_nestedly'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/unpack_strategy.rb:124:in `extract_nestedly'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:186:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:75:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by mahori** [comment]
It seems to be a problem related to symbolic links.

**Comment by mahori** [comment]
Mounted `.dmg` files (version 3.2.14 and 3.2.16) and compared contents of these directories. The destination of symbolic links (`/Volumes/Audirvana Plus {3.2.14,3.2.16}/Applications`) has been changed from `/Applications` to `/Volumes/Macintosh HD/Applications`. This may be causing a problem.

**Pull request merged**
