### PR TITLE
Update qingg from 2.14 to 2.15

### PR DESCRIPTION
**Pull request by Igotit**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions)
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by asins** [comment]
@Igotit  在这看到你在你也在提交版本啊~，我也刚提交了

**Review by bevanjkay — DISMISSED** [review]

**Review by samford — COMMENTED** [review]
I updated the `livecheck` block to match the version from the filename in the enclosure URL, as the `shortVersionString` in the appcast currently contains more text than just the version (i.e., `2.15 十周年纪念版` instead of only `2.15`). We can switch back to checking `item.short_version` if/when the `shortVersionString` is guaranteed to only be a numeric version but this will address the livecheck failure for now.

-----

Beyond that, it looks like there's an issue with installing the software on CI:

```
==> Running installer for qingg with sudo; the password may be necessary.
installer: Package name is 清歌输入法
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “安装包.pkg”.)
```

**Comment by miccal** [comment]
@Igotit it appears that the `pkg` for this version included a `postinstall` script that only works on an Arm-based Mac. Are you able to confirm if this is correct, and that this can now not be installed on an Intel-based Mac?

**Comment by Igotit** [comment]
> @Igotit it appears that the `pkg` for this version included a `postinstall` script that only works on an Arm-based Mac. Are you able to confirm if this is correct, and that this can now not be installed on an Intel-based Mac?

Thanks for figuring out this problem. I will update and re-submit.

**Review by miccal — APPROVED** [review]

**Pull request merged**
