### PR TITLE
Update google-chrome.rb for zap

### PR DESCRIPTION
**Pull request by nuomi1**
- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Update google-chrome.rb for zap

### CODE REVIEW

**Comment by nuomi1** [comment]
An app from `chrome://apps/`

from `
~/Library/Saved Application State/com.google.Chrome.app.Default-dckjbbhlbmojeohhjlobfllblcoannge.savedState` to `'~/Library/Saved Application State/com.google.Chrome.app.*.savedState'`

**Comment by nuomi1** [comment]
Shall we add an accurate version for it?

**Comment by vitorgalvao** [comment]
> Shall we add an accurate version for it?

What do you mean?

**Comment by nuomi1** [comment]
e.g. `version '55.0.2883.75'`

**Comment by vitorgalvao** [comment]
There’s no versioned URL or appcast, so no.

**Pull request merged**
