### PR TITLE
Update sql-operations-studio to 0.30.6

### PR DESCRIPTION
**Pull request by TheConstructor**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
https://github.com/Homebrew/homebrew-cask/pull/48701#issuecomment-398476368

**Comment by TheConstructor** [comment]
@brianmorton as far as I know it is stable. Both according to https://github.com/Microsoft/sqlopsstudio/releases and https://sqlops-update.azurewebsites.net/api/update/darwin/stable/VERSION if that is what you comment wants to ask?

**Comment by vitorgalvao** [comment]
> Both according to https://github.com/Microsoft/sqlopsstudio/releases

It’s clearly labeled `Pre-release` in read. Stable is `Latest release` in green.

**Comment by TheConstructor** [comment]
@vitorgalvao the "current stable" is also a "Public Preview" https://github.com/Microsoft/sqlopsstudio/releases/tag/0.29.3 it is just more stable than the e.g. "Insiders Build" 0.30.5. 

0.30.6 is also the version they offer on their download-page: https://docs.microsoft.com/en-us/sql/sql-operations-studio/download?view=sql-server-2017

**Comment by brianmorton** [comment]
At this point I would tend to agree with @TheConstructor and this should be updated to 0.30.6 as they seem to have updated their site TODAY to indicate this is their June "release".

**Comment by TheConstructor** [comment]
@vitorgalvao @brianmorton Thank You! Probably see you next month ;-)

**Pull request merged**
