### PR TITLE
use https for sourceforge download urls

### PR DESCRIPTION
**Pull request by phinze**
refs #10377

### CODE REVIEW

**Comment by ndr-qef** [comment]
We originally abandoned HTTPS in SourceForge URLs because they redirected to plain HTTP. Has that changed?

**Comment by phinze** [comment]
Ah thanks for the context @ndr-qef, I was running interference for #10377 and didn't notice that it had been previously discussed. Seems like the conversation over at #10377 will determine if this gets closed or accepted. :grinning:

**Comment by CraftThatBlock** [comment]
I think this should still be implemented so when/if SourceForge migrates to https it will be caught on instantly.

**Comment by vitorgalvao** [comment]
@CraftThatBlock But if they never do (and in the meantime) it’ll give a false sense of security. It’d be misleading.

**Comment by CraftThatBlock** [comment]
I see. Would a flag like --secure that forces https be a possibility?

**Comment by vitorgalvao** [comment]
No. You can’t force the secure connection. If you could, browsers could sinply imlement that, and everything would be `https`.

**Comment by ndr-qef** [comment]
SourceForge does not support HTTPS and any specific measure (e.g. forcing mirrors) would require a standalone discussion. Closing.

**Pull request closed without merging**
