### PR TITLE
Update qgis from 3.12.1 to 3.12.3

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
`appcast at URL 'https://qgis.org/downloads/macos/qgis-macos-pr.sha256sum' does not contain the version number '3_12_3'`

ping @suschizu

**Comment by adam52** [comment]
`brew install qgis` is giving me a checksum error. `brew info qgis` still shows the current version at 3.12.1...?

**Comment by ran-dall** [comment]
@adam52 Yes, the update in this PR was closed; so the software wasn't updated.

**Comment by adam52** [comment]
Hmm... I just tried to install the cask again and I am still getting a checksum error...?

    brew update
    brew cask install qgis

Any ideas? Thanks!

**Comment by ran-dall** [comment]
@adam52 It would be preferred if you open an issue than continue commenting on the PR. Open that issue, and I'll comment back my finding on the issue ticket.

**Comment by ran-dall** [comment]
@adam52 NM I figured out the problem. The ML picked up the wrong version number entirely. I'll fix it for you shortly.

**Comment by adam52** [comment]
Fantastic. Thanks!

**Comment by ran-dall** [comment]
@adam52 I just merged that update for you. Should be fixed. Thanks for reporting this to me.

**Pull request closed without merging**
