### PR TITLE
opgg 1.4.1

### PR DESCRIPTION
**Pull request by adithyasunil26**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> Downloading https://desktop-patch.op.gg/update/general/OP.GG-1.4.1.dmg
Already downloaded: /Users/runner/Library/Caches/Homebrew/downloads/e644a473086c82d7f505b433b5cdede5f718d4693414e183a226316689e3da23--OP.GG-1.4.1.dmg
audit for opgg: failed
 - Version '1.4.1' differs from '1.2.10' retrieved by livecheck.
 - Version '1.4.1' differs from '1.2.10' retrieved by livecheck.
```

**Comment by adithyasunil26** [comment]
Here's what I am getting when running `brew livecheck opgg`
```
opgg: 1.2.10 ==> 1.4.1
```
Also verified by downloading the application directly from the website. `1.4.1` is the latest version.

**Comment by krehel** [comment]
Set CI to retry every 3 hours. It'll (hopefully) eventually pass.

**Comment by p-linnane** [comment]
Just checked:
```
╰─ brew lc opgg
opgg: 1.2.10 ==> 1.2.10
```
Going to close this. Probably best for you to reach out to upstream and ask them what is going on.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
