### PR TITLE
nightowl website does not provide versioned download links - :latest

### PR DESCRIPTION
**Pull request by stonerl**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
But it has an `appcast`.

**Comment by stonerl** [comment]
Doesn't change the fact that it can't be installed since the sha256 is wrong?

**Comment by vitorgalvao** [comment]
[Then we fix it](https://github.com/Homebrew/homebrew-cask/pull/55958). Takes less than a minute.

**Comment by stonerl** [comment]
Sorry but may I quote the [documentation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md):

> This combination of version :latest and sha256 :no_check is currently the preferred mechanism when a versioned download URL is not available.

**Comment by vitorgalvao** [comment]
Yes, you may. Thank you for pointing out it’s outdated.

https://github.com/Homebrew/homebrew-cask/pull/55959

**Comment by stonerl** [comment]
I see 😄 Thanks for the clarification.

**Pull request closed without merging**
