### PR TITLE
Fix bad SHA256 for vuescan to 9.6.16

### PR DESCRIPTION
**Pull request by lantrix**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by lantrix** [comment]
Build failed because:
`audit for vuescan:failed - only sha256 changed`

But it was the SHA that was wrong, preventing installing the cask. Hence the update [as per the docs](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

**Comment by amyspark** [comment]
I've reviewed this and the downloaded file doesn't match either the old or the new hash.

https://www.virustotal.com/#/file/8c350abc5301a52f030a3141edbf7e5d4521df4c4392b931ef6eb91919d9d5b2/detection

**Review by vitorgalvao — APPROVED** [review]

**Comment by vitorgalvao** [comment]
> I've reviewed this and the downloaded file doesn't match either the old or the new hash.

I got the same as you.

> But it was the SHA that was wrong, preventing installing the cask. Hence the update [as per the docs](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

To clarify, the shasum wasn’t wrong at the time it was introduced, which means that the package changed upstream, making the shasum *different*, not wrong. It’s to certify that the change wasn’t malicious that the error sends you to [these docs](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by lantrix** [comment]
> I've reviewed this and the downloaded file doesn't match either the old or the new hash.
> 
> https://www.virustotal.com/#/file/8c350abc5301a52f030a3141edbf7e5d4521df4c4392b931ef6eb91919d9d5b2/detection

@amyspark then does that mean that [cask-repair](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair) is generating the wrong SHA256?

```shell
$ cask-repair vuescan
Updating taps… Already up-to-date.
------------------------------------------------------------------------------------------------------------------------------------------------------------
cask 'vuescan' do
  version '9.6.16'
  sha256 '6d9dbffc19a46b39063f285eafce54e54e9e07b2aef5f110848e0c938c23d6e6'

  url "https://www.hamrick.com/files/vuex64#{version.major_minor.no_dots}.dmg"
  appcast 'https://www.hamrick.com/alternate-versions.html'
  name 'VueScan'
  homepage 'https://www.hamrick.com/'

  app 'VueScan.app'
end
------------------------------------------------------------------------------------------------------------------------------------------------------------
Type the new version (or leave blank to use current one, or use `s` to skip)
>
==> Downloading external files for Cask vuescan
==> Downloading https://www.hamrick.com/files/vuex6496.dmg
==> Downloading from https://d2bwyyzfw77fhf.cloudfront.net/vuex6496.dmg
######################################################################## 100.0%
==> No checksum defined for Cask vuescan, skipping verification
==> Success! Downloaded to -> /Users/lantrix/Library/Caches/Homebrew/Cask/vuescan--9.6.16.dmg
diff --git a/Casks/vuescan.rb b/Casks/vuescan.rb
index 7569e2633e..45bc7126d6 100644
--- a/Casks/vuescan.rb
+++ b/Casks/vuescan.rb
@@ -1,6 +1,6 @@
 cask 'vuescan' do
   version '9.6.16'
-  sha256 '6d9dbffc19a46b39063f285eafce54e54e9e07b2aef5f110848e0c938c23d6e6'
+  sha256 '93598183343f7e0c7c7b13331e7f1151bf997eaa197389276a13efaf74b3fc89'

   url "https://www.hamrick.com/files/vuex64#{version.major_minor.no_dots}.dmg"
   appcast 'https://www.hamrick.com/alternate-versions.html'
------------------------------------------------------------------------------------------------------------------------------------------------------------
Is everything correct? ([y]es / [n]o / [e]dit) y
Submitting…```

**Pull request merged**
