### PR TITLE
Add movist pro

### PR DESCRIPTION
**Pull request by kyungw00k**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
What’s the relation between this app and [Movist](https://github.com/samiamwork/Movist)?

**Comment by kyungw00k** [comment]
@vitorgalvao 

It is `pro` version of [Movist from Mac App Store](https://apps.apple.com/kr/app/movist/id461788075?l=en&mt=12). 

Since the [Movist](https://github.com/samiamwork/Movist) was moved to the [Mac App Store](https://apps.apple.com/kr/app/movist/id461788075?l=en&mt=12), the old one is literally deprecated.

**Comment by vitorgalvao** [comment]
> Since the [Movist](https://github.com/samiamwork/Movist) was moved to the [Mac App Store](https://apps.apple.com/kr/app/movist/id461788075?l=en&mt=12), the old one is literally deprecated.

Except that the last commit in that repo is newer than the last release on the Mac App Store.

**Comment by vitorgalvao** [comment]
> Since the [Movist](https://github.com/samiamwork/Movist) was moved to the [Mac App Store](https://apps.apple.com/kr/app/movist/id461788075?l=en&mt=12), the old one is literally deprecated.
 
The last commit in that repo is newer than the last release on the Mac App Store.

**Comment by vitorgalvao** [comment]
> Since the [Movist](https://github.com/samiamwork/Movist) was moved to the [Mac App Store](https://apps.apple.com/kr/app/movist/id461788075?l=en&mt=12), the old one is literally deprecated.
 
The last commit in that repo is newer than the last release on the Mac App Store.

**Comment by kyungw00k** [comment]
> > Since the [Movist](https://github.com/samiamwork/Movist) was moved to the [Mac App Store](https://apps.apple.com/kr/app/movist/id461788075?l=en&mt=12), the old one is literally deprecated.
> 
> The last commit in that repo is newer than the last release on the Mac App Store.

I see your point, but `pro` version of app is completely standalone app, and it could not be activated from the version of old one.

[New version of `Movist` was rejected from MAS due to some kind of `download` related feature](https://movistprime.com/en/notices.html), so the developer made the `pro`  version of it with awesome features.

**Pull request merged**
