### PR TITLE
wireshark.rb: fix permissions of /etc/paths.d/Wireshark

### PR DESCRIPTION
**Pull request by vitorgalvao**
As reported in https://github.com/Homebrew/homebrew-cask/issues/74479.

### CODE REVIEW

**Comment by jabenninghoff** [comment]
Should the `set_permssions` statement be part of the `postflight` stanza? I think that will fix the problem reported by @Tenzer and myself in #74479. I wasn't able to replicate the original poster's issue.

Or... as this seems to be a bug in the actual original Wireshark distribution - the `Add Wireshark to the system path.pkg` doesn't set the correct permissions (I confirmed this with testing) - is this something that should be fixed upstream?

**Comment by vitorgalvao** [comment]
> is this something that should be fixed upstream?

Yes. Would you mind informing them?

**Comment by jabenninghoff** [comment]
I don't mind - I'll file a bug report with Wireshark.

**Comment by jabenninghoff** [comment]
To be clear - I don't think this proposed PR will actually fix issue #74479. I wasn't able to replicate that issue.

**Comment by vitorgalvao** [comment]
[There have been more reports](https://github.com/Homebrew/homebrew-cask/issues/74548). This needs to be reported upstream.

**Comment by Stellarspace** [comment]
I have the same problem.

**Comment by vitorgalvao** [comment]
> I have the same problem.

Have you reported the issue upstream, [as mentioned](https://github.com/Homebrew/homebrew-cask/pull/74502#issuecomment-568228072)?

**Comment by Stellarspace** [comment]
> > I have the same problem.
> 
> Have you reported the issue upstream, [as mentioned](https://github.com/Homebrew/homebrew-cask/pull/74502#issuecomment-568228072)?

No, I don't know what that means, but I resolved it by typing the following:
`sudo chmod 644 /etc/manpaths.d/Wireshark /etc/paths.d/Wireshark`

**Comment by marques-work** [comment]
@jabenninghoff @vitorgalvao 

> Should the `set_permssions` statement be part of the `postflight` stanza?

It ought to be both `postflight` and `uninstall_preflight` to fix both cases until this is resolved upstream:

1. After installing Wireshark, the user sees a permission error from `path_helper` for every shell login session (evaluating `/etc/paths.d`
2. Fixing Wireshark uninstall.

**Comment by vitorgalvao** [comment]
[Fixed upstream](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=16284).

**Pull request closed without merging**
