### PR TITLE
Update cloudapp from 6.5.2,2245 to 6.6.0,2271

### PR DESCRIPTION
**Pull request by ghost**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by zsoltion** [comment]
@miccal It seems like the appcast is behind (the website downloads an even older version). Can we still just merge it in?

**Comment by bevanjkay** [comment]
> @miccal It seems like the appcast is behind (the website downloads an even older version). Can we still just merge it in?

The livecheck exists to ensure that we are providing the correct version from upstream. The appcast is the only place I can find a reference upstream to a specific version, so we will need to use that unless you can provide an alternative location to use for livecheck.

**Comment by gdams** [comment]
According to https://downloads.getcloudapp.com/mac/latest/CloudApp.zip I get `6.5.3` (yet another version)?

**Comment by zsoltion** [comment]
I'm not sure, that's what's running on my computer, but in that case, let's wait until it shows up again on the update server.

**Pull request closed without merging**
