### PR TITLE
sogouinput: remove

### PR DESCRIPTION
**Pull request by miccal**
As found in https://github.com/Homebrew/homebrew-cask/pull/154321, the `url` is now dynamic and as such is not suitable as a Cask.

### CODE REVIEW

**Review by krehel — APPROVED** [review]

**Comment by chenrui333** [comment]
👍

**Comment by gibfahn** [comment]
This is sad, hopefully we can find a URL that doesn't have an opaque hash in it to download this from.

**Comment by JounQin** [comment]
Hi, I just wrote a tiny service https://github.com/un-ts/rabbit-linker to resolve the random url issue, shall we use it?

The followings version and short version are both fine.

https://rabbit-linker.vercel.app/gtimg/sogou_mac/1688992049
https://rabbit-linker.vercel.app/gtimg/sogou_mac/614d
https://rabbit-linker.vercel.app/gtimg/sogou_mac

I'm currently maintaining `sogouinput` cask at https://github.com/homebrew-x/homebrew-x/blob/master/Casks/sogouinput.rb#L5

**Comment by miccal** [comment]
Great work @JounQin, but unfortunately we cannot use an external `url` resolver in Homebrew.

Thank you for maintaining a tap, though :)

**Comment by gibfahn** [comment]
@JounQin could we do the link rewriting locally in the formula definition without using the service? I don't know if homebrew would accept it, but it would avoid using an external service.

**Comment by JounQin** [comment]
@gibfahn Sure. I had a similar proposal at https://github.com/Homebrew/homebrew-cask/issues/107354, but I had limited ruby knowledge so I rejected my PR.

**Pull request merged**
