### PR TITLE
Update xamarin-mac

### PR DESCRIPTION
**Pull request by robertleeblairjr**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Cask could benefit from an update as well. It’s outdated by two minor versions.

**Comment by robertleeblairjr** [comment]
> Cask could benefit from an update as well. It’s outdated by two minor versions.

Sorry, for the late reply. Thanks. At the time of the PR, I had attempted to update the version to the current stable 6.10 but the link is broken. The current 6.8 was preview release and I could update to the current 6.14 preview release. However, this is still a preview release channel branch. But, it wouldn't be any different than this current referenced version being preview release and would be a newer version.

**Comment by robertleeblairjr** [comment]
[https://docs.microsoft.com/en-us/xamarin/mac/release-notes/6/6.14](url)

Appcast fails audit for version 6.14 doesn't exist but that's incorrect.

**Comment by robertleeblairjr** [comment]
Xamarin 6.x requires Xcode 11.x. Travis is failing because of building with Xcode 10.x.

**Pull request merged**
