### PR TITLE
add atlas-recall

### PR DESCRIPTION
**Pull request by shedali**
add Atlas Recall latest beta

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] `sha256` changed but `version` stayed the same ([what is this?][version-checksum]).  
      I’m providing public confirmation below.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
Please complete the required steps in the PR template and fix the `style` errors.

```
>>> brew cask style Casks/atlas-recall.rb
== Casks/atlas-recall.rb ==
C:  2:  3: url stanza out of order
C:  3:  3: name stanza out of order
C:  4:  3: homepage stanza out of order
C:  4: 12: 'https://www.atlas.co' must have a slash after the domain.
C:  5:  1: stanza groups should be separated by a single empty line
C:  5:  3: version stanza out of order
C:  6:  1: stanza groups should be separated by a single empty line
C:  6:  3: app stanza out of order
C:  7:  1: stanza groups should be separated by a single empty line
C:  7:  3: sha256 stanza out of order
```

**Comment by shedali** [comment]
apologies, fixed!

**Comment by commitay** [comment]
You need to fill out the template.

**Comment by shedali** [comment]
done

**Comment by miccal** [comment]
Thank you for your contribution.

**Pull request merged**
