### PR TITLE
weasis 4.4.0 (new cask)

### PR DESCRIPTION
**Pull request by nroduit**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by nroduit** [comment]
> Hi @nroduit - thank you for opening this PR! I've pushed some fixes to help with the PR, but you may need to investigate your `x86_64` pkg build - it failed to install in CI and I also attempted to install locally without success.

I do not understand where is the issue on`x86_64` pkg because in GUI it will be installed without any issues. In CLI I got an error `installer: Error - Weasis can’t be installed on this computer.` without more information (even in debug mode).
Do you have another suggestion for solving this problem?

**Comment by krehel** [comment]
I did not use Homebrew for local testing to verify it was not a CI issue  I downloaded the package directly from GitHub and it did not install using normal pkg install.

I also tested with the 4.3.0 pkg on Intel and it did install / run without issue.  4.4.0 did not.

**Comment by krehel** [comment]
It appears the 4.4.0 release for Intel is actually built for Apple Silicon.  Differences between 4.3.0 and 4.4.0 below.

4.3.0
weasis 4 3 0

4.4.0
weasis 4 4 0

**Comment by nroduit** [comment]
> It appears the 4.4.0 release for Intel is actually built for Apple Silicon. Differences between 4.3.0 and 4.4.0 below.
> 

Thanks for your support.
As I no longer have x86 hardware, I was testing on arm64 hardware and I just noticed that the mac-latest runner on GitHub has changed from x86 to arm64.

**Comment by krehel** [comment]
Thanks.  You aren't the first person to have this occur regarding the runner switch to arm64.  Glad to help.

**Comment by miccal** [comment]
Thank you @nroduit.

**Review by miccal — APPROVED** [review]

**Pull request merged**
