### PR TITLE
Windscribe 2

### PR DESCRIPTION
**Pull request by jivanpal**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**: N/A, but...

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully. **(didn't check this)**
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

***

Windscribe v2 uses an installer app (as opposed to v1, which just used drag-and-drop). If there is any way to automate installation rather than requiring the user to open the file from Caskroom due to `installer manual`, that would be good to know. However, I have not been able to discover any command-line arguments taken by the installer program that may make this possible.

Should v1 be added to [homebrew-cask-versions](https://github.com/Homebrew/homebrew-cask-versions)? It is still available on Windscribe.com as ["Legacy version"](https://assets.totallyacdn.com/desktop/mac/Windscribe-legacy.dmg).

Also, `brew style --fix` seems to have messed with the indentation of my `uninstall launchctl` block (see second commit). Should this "fix" be reverted?

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> If there is any way to automate installation rather than requiring the user to open the file from Caskroom due to `installer manual`, that would be good to know.

Check inside the installer app. Often they are thin wrappers for a `.pkg`, likely in the `Resources` or `MacOS` directories. They may also have a zip or similar with an app inside. The more corporate an app is, the likelier they’ll have a bullshit installer.

> Should v1 be added to [homebrew-cask-versions](https://github.com/Homebrew/homebrew-cask-versions)?

No. If anyone needs it, they can submit it then.

**Comment by jivanpal** [comment]
> Check inside the installer app. Often they are thin wrappers for a `.pkg`

Alas, not the case here, the `.app` appears to just be a wrapper for an executable which is a one-click GUI installer, and it apparently takes no command line arguments. Does Homebrew support/condone launching the installer `.app` so that the user doesn't have to open it from Caskroom themselves (e.g. by using `open` within a `do` block)?

**Comment by vitorgalvao** [comment]
> Does Homebrew support/condone launching the installer `.app` so that the user doesn't have to open it from Caskroom themselves (e.g. by using `open` within a `do` block)?

Not at present. If we did, we wouldn’t have `installer manual:`. See https://github.com/Homebrew/homebrew-cask/issues/24377 for future plans, but those are unlikely to happen any time soon unless we get a contribution.

**Comment by vitorgalvao** [comment]
Thank you for the contribution.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
