### PR TITLE
Update continuity-activation-tool from 1.0 to 2

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by suschizu** [comment]
@reitermarkus, @vitorgalvao - cask repair added a sha again - how should we handle this?

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/94919#issuecomment-740763433

`brew upgrade cask-repair` and try that one.

**Review by vitorgalvao — APPROVED** [review]

**Comment by suschizu** [comment]
> [#94919 (comment)](https://github.com/Homebrew/homebrew-cask/pull/94919#issuecomment-740763433)
> 
> `brew upgrade cask-repair` and try that one.

hey @vitorgalvao  - I did the brew upgrade but cask-repair doesn't work for me anymore - just receive the error:
```
Error: unknown keyword: force
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:17:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:135:in `new'
/usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:135:in `block in fetch'
/usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:91:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/fetch.rb:91:in `fetch'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
error: Cannot delete branch 'master' checked out at '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'

There was an error fetching ./houdahspot.rb. Please check your connection and try again.
```
do you perhaps have an idea how to solve this? thanks

**Comment by vitorgalvao** [comment]
Does this happen with every cask?

What’s the output of `brew info cask-repair`?

Try `brew update` as well, just to be sure.

If after that it still fails, run `bash -x cask-repair <REST OF COMMAND>` and post the output (it’s going to be long).

**Comment by suschizu** [comment]
> Does this happen with every cask?

yes (except when the url changes - then cask-repair works)

> What’s the output of brew info cask-repair?

```
vitorgalvao/tiny-scripts/cask-repair: stable 0.40.32
Quickly repair outdated/broken Casks from homebrew-cask
https://github.com/vitorgalvao/tiny-scripts
/usr/local/Cellar/cask-repair/0.40.32 (5 files, 26.7KB) *
  Built from source on 2020-12-09 at 13:06:45
From: https://github.com/vitorgalvao/homebrew-tiny-scripts/blob/HEAD/cask-repair.rb
==> Dependencies
Required: hub ✔
Recommended: hr ✔
==> Options
--without-hr
	Build without hr support
```
> If after that it still fails, run bash -x cask-repair <REST OF COMMAND> and post the output (it’s going to be long).

[output.txt](https://github.com/Homebrew/homebrew-cask/files/5669449/output.txt)

thanks for your help ❤️

**Comment by vitorgalvao** [comment]
> output.txt

That’s not the same error as above. That one seems correct, because the URL with version 6.1.0 in the version indeed does not exist (anymore?).

**Comment by vitorgalvao** [comment]
It’s not yet clear to me where the original error came from, but I just pushed a new version, so `brew upgrade cask-repair` again may fix it this time.

**Comment by suschizu** [comment]
hey @vitorgalvao - thank you - everything works again as usual 👍

**Pull request merged**
