### PR TITLE
Update adobe-acrobat-reader from 19.021.20047 to 19.021.20049

### PR DESCRIPTION
**Pull request by chuyizhang**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Welcome and thank you, but [the download page](https://get.adobe.com/reader/) still shows `19.021.20047` as the latest version; where does `19.021.20049` come from?

**Comment by core-code** [comment]
all acrobat releases listed here:
https://www.adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotesDC/index.html
are official.

so it looks good to go ;)

**Comment by vitorgalvao** [comment]
Thank you for the confirmation, @core-code. Might be worth changing the appcast to that page.

I’m on a phone, so I’ll do it when I get home. I wouldn’t be able to merge as is anyway, because GitHub doesn’t allow merging PRs with failing CIs on a phone.

If you want to go ahead and do it, @chuyizhang, you just need to change the `appcast` line to use the URL given by @core-code.

**Comment by chuyizhang** [comment]
@vitorgalvao Thank you! I found this new version via the built-in update checking mechanism. I've already committed another change and modified the appcast as you suggested. The checks passed this time. Hope it works well.

**Comment by vitorgalvao** [comment]
Right on time, I got home a few minutes ago and was checking PRs. Thank you again.

**Pull request merged**
