### PR TITLE
Update burp-suite from 2021.10.2 to 2021.10

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Ah, it appears the MacOS versions for 2021.10.2 have been pulled and are not longer available.

**Comment by miccal** [comment]
> Version 2021.10.1 is marked as an "early adopter" release - the last stable release for macOS is 2021.10

Yes I am aware of that, but they use a different install method (see https://github.com/Homebrew/homebrew-cask/pull/114641 and https://github.com/Homebrew/homebrew-cask/pull/114637), so let's just wait and see if the new versions are re-added.

**Comment by kiblik** [comment]
What about to use data from https://portswigger.net/burp/releases/data?

**Comment by tresni** [comment]
Yeah, current livecheck in appropriately says 2021.10.2 is available for OSX and it's not. Using the release, data you can find the latest community edition for MacOS as follows.

```
curl https://portswigger.net/burp/releases/data | jq '[.ResultSet.Results[].builds[] | select(.ProductPlatform == "MacOsx" and .ProductId == "community")][0]'
```

**Comment by miccal** [comment]
Ping @samford for suggestions on a `livecheck`, please :)

**Comment by bevanjkay** [comment]
@miccal and @samford There's probably a cleaner way to achieve the same result - but I've implemented a livecheck that parses the JSON from upstream's API.

**Comment by miccal** [comment]
@bevanjkay as I explained above, version 2021.10 uses a different install method -- see [#114641](https://github.com/Homebrew/homebrew-cask/pull/114641) and [#114637](https://github.com/Homebrew/homebrew-cask/pull/114637).

**Comment by bevanjkay** [comment]
@miccal The new livecheck might be a bit overkill if this is a temporary issue where only the Mac version has been withdrawn - I'm not sure the best way to move forward with handling the current versioning issue 🤷🏻‍♂️

**Comment by miccal** [comment]
Let's just revert and keep your `livecheck` :)

**Pull request merged**
