### PR TITLE
Remove snowflake cask, entire website appears to have been discontinued

### PR DESCRIPTION
**Pull request by Amorymeltzer**
http://vemedio.com/
http://vemedio.com/products/snowflake

### CODE REVIEW

**Comment by victorpopkov** [comment]
The download URL still seems to be available. I don't mind removing this cask. What do you think @vitorgalvao?

**Comment by Amorymeltzer** [comment]
Yeah, saw that.  Can't imagine it would be useful to anyone who didn't have it already, and since they won't update...  At any rate, technically discontinued.

**Comment by vitorgalvao** [comment]
Yep, lets remove it, I’ve already done so to two other of their apps, [instacast](https://github.com/caskroom/homebrew-cask/pull/15687) and [snowtape](https://github.com/caskroom/homebrew-cask/pull/15686).

**Comment by vitorgalvao** [comment]
Merged as d0de2b0c7e47b4f021d3c276c5150c131ecbae95.

**Pull request closed without merging**
