### PR TITLE
Update rocketcake to 2.2

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
CI is saying this should be HTTPS. Maybe whatever issue you found was since fixed?

**Comment by core-code** [comment]
can you try a 'brew cask fetch rocketcake'?

**Comment by vitorgalvao** [comment]
> can you try a 'brew cask fetch rocketcake'?

Working fine.

**Comment by core-code** [comment]
ok weird i get this on two different Macs.

```
iMac27:~j$ brew cask fetch rocketcake
==> Downloading external files for Cask rocketcake
==> Downloading https://www.ambiera.at/downloads/RocketCake-2.2.dmg
######################################################################## 100.0%
curl: (16) Error in the HTTP2 framing layer
Error: Download failed on Cask 'rocketcake' with message: Download failed: https://www.ambiera.at/downloads/RocketCake-2.2.dmg

```

**Comment by vitorgalvao** [comment]
Weird. Let’s revisit if we have more reports.

**Pull request closed without merging**
