### PR TITLE
Add Avira Antivirus

### PR DESCRIPTION
**Pull request by 1zaman**

### CODE REVIEW

**Comment by 1zaman** [comment]
I'm not sure if the `uninstall` stanza can handle launching an app, which Avira uses to create an uninstallation wizard which also handles quarantined files. If this is possible to integrate, then I would appreciate guidance on how to do it.

**Comment by vitorgalvao** [comment]
There are [scripts](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#uninstall-stanza-details) geared for `uninstall`.

**Comment by 1zaman** [comment]
OK, I have referenced the uninstallation script inside the app in the `uninstall` stanza. Didn't test it though :wink:

**Comment by vitorgalvao** [comment]
That won’t work, as it’ll call a GUI. Look into `pkgutil` in the linked documentation, that’s what you want.

**Comment by 1zaman** [comment]
@vitorgalvao: Well, I was forced to test it now :disappointed: The script does not call a GUI, and it worked properly.

**Comment by vitorgalvao** [comment]
Ah, yes, I was looking at it wrongly. Still, tge `pkgutil` method must be added. `script` should always be in addition to and never in detriment of.

**Comment by vitorgalvao** [comment]
Ah, yes, I was looking at it wrongly. Still, tge `pkgutil` method must be added. `script` should always be in addition to and never in detriment of.

**Comment by 1zaman** [comment]
OK, I have added the `pkgutil` key. Again, this was not tested by me. Note that among my installed packages, [Avast! Anti-virus][] and [Tuxera NTFS][] also rely upon calling a script for uninstallation.

[Avast! Anti-virus]: https://github.com/caskroom/homebrew-cask/blob/a055e9817291c84c986de9d2cb5ba58cc9961375/Casks/avast.rb
[Tuxera NTFS]: https://github.com/caskroom/homebrew-cask/blob/a055e9817291c84c986de9d2cb5ba58cc9961375/Casks/tuxera-ntfs.rb

**Comment by vitorgalvao** [comment]
> OK, I have added the `pkgutil` key

Thank you.

> Note that Avast Anti-virus and Tuxera NTFS also rely upon calling a script for uninstallation.

And those need to be fixed as well. However, it’s easier to catch these and prevent them from being merged in the first place than finding them later.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as e3fc20b6de55976437c5da13e625991acf09e3ec to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
