### PR TITLE
Delete gedit.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
See https://github.com/Homebrew/homebrew-core/pull/3331.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@AnastasiaSulyagina Can you explain to @vitorgalvao about the New Shiny Way in your PR I merged today to do this migration to Homebrew?

**Comment by MikeMcQuaid** [comment]
@vitorgalvao (can you hold off until then? Thanks 👍)

**Comment by reitermarkus** [comment]
> the New Shiny Way

Sounds intriguing. 😄

**Comment by AnastasiaSulyagina** [comment]
About the New Shiny Way : It's just about adding `"gedit": "homebrew/core"` to `tap-migrations.json` file in cask root directory for migration to be handled properly by `brew update`

**Comment by vitorgalvao** [comment]
Done.

**Comment by MikeMcQuaid** [comment]
Hooray 👍.

**Pull request merged**
