### PR TITLE
Update lando to 3.0.9

### PR DESCRIPTION
**Pull request by hussainweb**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by hussainweb** [comment]
```
==> Downloading https://github.com/lando/lando/releases/download/v3.0.9/lando-v3.0.9.dmg
Already downloaded: /Users/hw/Library/Caches/Homebrew/downloads/0057e8ce8b685ed02c36105f3347f44d3bf45d67d1e008694f9ff89499b76dd9--lando-v3.0.9.dmg
==> Verifying SHA-256 checksum for Cask 'lando'.
audit for lando: passed
```

**Comment by core-code** [comment]
please don't submit this. this is explicitely marked as a pre-release in their Github feed.

more info:

https://github.com/Homebrew/homebrew-cask/pull/86187#issuecomment-660489922

**Comment by hussainweb** [comment]
Thanks for the feedback. I know it's not possible to make exceptions but as a user, I don't see this as a pre-release release (in terms of stability). I have created an issue in the project queue to understand this and make it more consistent.

**Comment by core-code** [comment]
> I don't see this as a pre-release release (in terms of stability)

well, thats for the vendor to decide :)

> I have created an issue in the project queue to understand this and make it more consistent.

sounds good. however they already have an elaborate scheme here that is documented here:

https://docs.lando.dev/config/releases.html#toggling-channels 

so i think it is unlikely they are going to change things here

**Comment by hussainweb** [comment]
Yes, you're right. I wouldn't have created this had I known that. Thanks again. :)

**Pull request closed without merging**
