### PR TITLE
Update adoptopenjdk from 12.0.1,12 to 12.0.2,10

### PR DESCRIPTION
**Pull request by steinybot**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
we could try using
https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/latest
to exclude those nightlies

**Comment by claudionieder** [comment]
Well the current atom app cast URL also incorporates #{version.major} so I don't see an why not have an URL which incorporates also #{version.before_comma} and #{version.after_comma} if that is what it takes to make it work.

**Comment by core-code** [comment]
> Well the current atom app cast URL also incorporates #{version.major} so I don't see an why not have an URL which incorporates also #{version.before_comma} and #{version.after_comma} if that is what it takes to make it work.

i am not sure what you are suggesting. which URL would you use for an appcast?

**Comment by claudionieder** [comment]
My comment was thought as an answer to steinybot's question "It could use https://api.github.com/repos/AdoptOpenJDK/openjdk12-binaries/releases/tags/jdk-12.0.2+10 **but that is version specific**. I was thinking that anyhow the major version is already in todays used, not working, appcast URL so there is no harm in using also minor version too.

**Comment by core-code** [comment]
@steinyboy can you try changing the appcast stanza to use 'https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/latest' ?

**Comment by core-code** [comment]
thanks looks good to me

**Review by core-code — APPROVED** [review]

**Pull request merged**
