### PR TITLE
google-chrome: support both universal and x86_64 version

### PR DESCRIPTION
**Pull request by i0ntempest**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by i0ntempest** [comment]
The universal version is 2x bigger (200MB bigger) than x86_64 version and I think most people don't want to waste disk space on codes they can't run.

**Comment by reitermarkus** [comment]
I think we should prefer easier to maintain casks over disk space. Also, there is no way to test this on CI since we don't have CI for ARM.

**Comment by core-code** [comment]
> I think we should prefer easier to maintain casks over disk space.

agreed.

how about solving this by adding a new cask 'google-chrome-intel' to the versions repo for those people who require minimal disk-space consumption?

**Comment by vitorgalvao** [comment]
Closing since we’re in agreement.

> how about solving this by adding a new cask 'google-chrome-intel' to the versions repo for those people who require minimal disk-space consumption?

I think we should recommend personal taps for that. I doubt the number of people with this specific need will be common enough.

**Comment by core-code** [comment]
note if you do add a 'google-chrome-intel' to the versions repo i can keep it up-to-date with the new system i have to update casks with static urls.

otherwise, we have a version here: http://macupdater.net/casks_manual/google-chrome-intel.rb

**Comment by i0ntempest** [comment]
> note if you do add a 'google-chrome-intel' to the versions repo i can keep it up-to-date with the new system i have to update casks with static urls.
> 
> otherwise, we have a version here: http://macupdater.net/casks_manual/google-chrome-intel.rb

Is this identical to the version of the google-chrome cask file before the universal binary switch? If so I'll just add this to the versions repo.

**Comment by vitorgalvao** [comment]
> If so I'll just add this to the versions repo.

I’d rather not. I’ll gladly let this go if other maintainers disagree, but the versions repo—despite stricter rules—is still a mess. Are we prepared to start getting a bunch of low usage `-intel` casks that (I predict) will start to be abandoned as upstream and users cease to care (which I bet won’t take long)?

Will we then start having `-arm` or `-universal` versions as well when upstream starts changing what they provide?

So far we’ve had **one** user mentioning this as desirable. And it’s not even that big of a deal, but a minor inconvenience. Unless we have a horde of users asking for this, I think it’s premature to set the precedent.

**Comment by miccal** [comment]
Until Homebrew officially supports Apple Silicon, we should not accept Casks that install things that are specifically for Apple Silicon only.

See the discussion [here](https://github.com/Homebrew/brew/issues/9177), which indicates that there may be some quite fundamental changes when Apple Silicon is officially supported.

**Pull request closed without merging**
