### PR TITLE
updated praat (6.0.18)

### PR DESCRIPTION
**Pull request by wfdd**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by wfdd** [comment]
There's no 32-bit builds of the couple latest micro versions.

**Comment by wfdd** [comment]
Apropos of nothing, GitHub 'appcasts' don't have a `pubDate` and the equivalent `updated` element isn't being stripped.

**Comment by vitorgalvao** [comment]
> Apropos of nothing, GitHub 'appcasts' don't have a `pubDate` and the equivalent `updated` element isn't being stripped.

`pubDate` is being stripped because tons of feeds that have it change it every time the feed is accessed, making it useless to check their `sha256`.

**Comment by wfdd** [comment]
Thanks for explaining.

**Pull request merged**
