### PR TITLE
Update ndm to 1.1.0

### PR DESCRIPTION
**Pull request by artdevjs**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by 45kb** [comment]
Hi the v1.1.0 has been deleted from the tags and releases.

Error log when trying to install:

```
==> Downloading https://github.com/720kb/ndm/releases/download/v1.1.0/ndm-1.1.0.

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'ndm' with message: Download failed: https://github.com/720kb/ndm/releases/download/v1.1.0/ndm-1.1.0.dmg
The incomplete download is cached at /Users/45kb/Library/Caches/Homebrew/Cask/ndm--1.1.0.dmg.incomplete
Error: nothing to install
```

**Comment by artdevjs** [comment]
@45kb it looks like v1.1.0 again [on the place](https://github.com/720kb/ndm/releases/tag/v1.1.0), it will remain so?

**Comment by 45kb** [comment]
@artdevjs i think not because we are testing things, i'll tell you as it's fixed ok? :)

**Comment by artdevjs** [comment]
@45kb sure

**Comment by 45kb** [comment]
is it automatic PR on this branch? Actually, i don't understand if you guys open them or everything is automatic reading github release. @artdevjs

**Comment by artdevjs** [comment]
No, I open PR's manually when new version is available @45kb

**Comment by 45kb** [comment]
@artdevjs oh cool thanks a lot, however ... ok i'll let you know, thanks  👍

**Comment by 45kb** [comment]
@artdevjs the new v1.1.0 is ok now thank you a lot 👍  👍  this can be installed now https://github.com/720kb/ndm/releases/tag/v1.1.0

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/pull/30267

**Pull request merged**
