### PR TITLE
Update dotnet-sdk from 6.0.202 to 6.0.300 (arm64)

### PR DESCRIPTION
**Pull request by jgiannuzzi**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — APPROVED** [review]

**Comment by smarts** [comment]
@jgiannuzzi how do you get the secondary parts of the version? Did you create the SHA-256 hash yourself or did brew do that automatically?

**Comment by jgiannuzzi** [comment]
I went to dotnet.microsoft.com and checked what the URL was for this versions which contains the 2 extra parts. I then downloaded it and validated the SHA-512 hash against the one published by Microsoft. I then computed the SHA-256 hash.

**Comment by smarts** [comment]
@jgiannuzzi maybe i'm missing something. When I go to https://dotnet.microsoft.com/en-us/download/dotnet/6.0 and look at the download links, I only see vanity URLs like this:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.400-macos-arm64-installer
which do not include the GUID/UUID and hash(?) that come after the version number as seen your change.

**Comment by jgiannuzzi** [comment]
@smarts after clicking on the vanity URL, you get a direct link. In the case of the URL you mentioned above, the direct link is https://download.visualstudio.microsoft.com/download/pr/a92daceb-cf41-4c37-8e70-8a158889a9b2/c027605fb8d8b51ee0892e10ed874ab8/dotnet-sdk-6.0.400-osx-arm64.pkg.

**Comment by smarts** [comment]
💡 ! Awesome, thank you!

**Pull request closed without merging**
