### PR TITLE
Update speedify from `11.8.0` to `11.9.0,8909`

### PR DESCRIPTION
**Pull request by jasikpark**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by jasikpark** [comment]
The curious thing is that this is pulling from an un-versioned URL so it seems like you'd just get whatever the latest version is on pull, rather than a specific version, unless if I don't know how to read brew bottles

**Comment by jasikpark** [comment]
I suppose maybe that means making it a "nightly" cask? https://github.com/Homebrew/homebrew-cask-versions/blob/HEAD/CONTRIBUTING.md#nightly-builds-nightlies

**Comment by SMillerDev** [comment]
> The curious thing is that this is pulling from an un-versioned URL so it seems like you'd just get whatever the latest version is on pull, rather than a specific version, unless if I don't know how to read brew bottles

No, that's correct. But it's still useful to know which version you installed.

**Review by SMillerDev — APPROVED** [review]
Thanks @jasikpark  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request merged**
