### PR TITLE
banktivity 9.1.1-247

### PR DESCRIPTION
**Pull request by timweston**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by timweston** [comment]
Can someone assist with the check that's failing? I don't understand how to resolve `Error: Version '9.1.1-247' differs from '9.0.3-244' retrieved by livecheck.`

The change I'm trying to make is to upgrade from 9.0.3-244 to 9.1.1-247. I'm not sure what livecheck is or why it isn't retrieving 9.1.1-247.

**Comment by krehel** [comment]
Hi @timweston - do you know if the the `banktivity-versions-feed.json` file no longer updated that provides the version information?

If not, then the `livecheck` should be adjusted to check a different source (such as [Release Notes](https://www.banktivity.com/release_notes.php))

Thanks

**Comment by timweston** [comment]
@krehel I unfortunately don’t know the answer to that question. I’m just a user of Banktivity and Homebrew and am unaffiliated with Banktivity/IGG. I only knew there was a new version because the app notified me, so I figured I’d update Homebrew with the details of that update.

**Review by miccal — APPROVED** [review]

**Comment by krehel** [comment]
Thanks @miccal for making updates!

**Pull request merged**
