### PR TITLE
djv: deprecate

### PR DESCRIPTION
**Pull request by khipp**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by krehel** [comment]
Are you able to add the zap @khipp?

**Comment by khipp** [comment]
@krehel No, unfortunately. I do not have Rosetta installed.

**Comment by krehel** [comment]
No problem.  I'll add a zap shortly.

**Comment by krehel** [comment]
This was all I could come up with.  I had installed the previous version, as the 2.0.8 version as part of this Cask crashes in my VM on startup.

**Comment by bevanjkay** [comment]
I'd like to `deprecate` this too, it hasn't received an update since 2020, and no commits for two years, with potentially significant issues open.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
