### PR TITLE
Update ytmdesktop from 1.13.0 to 1.14.2

### PR DESCRIPTION
**Pull request by EloB**
This is my first PR to brew so be gentle. I'm neither a ruby developer. :)

Waiting on confirmation that the version is a stable version. Last stable version was released in 2020 and the repo seems inactive.
https://github.com/ytmdesktop/ytmdesktop/issues/205#issuecomment-1427877690
https://github.com/ytmdesktop/ytmdesktop/issues/1092

Is there any guide on how to test locally?
EDIT: When I did than it was working and I got the latest version. I'm not sure if I miss something though. Happily taking feedback.

```
brew edit ytmdesktop-youtube-music
HOMEBREW_NO_INSTALL_FROM_API=1 brew install ytmdesktop-youtube-music
```
**Important:** _Do not tick a checkbox if you haven’t performed its action. Honesty is indispensable for a smooth review process._

In the following questions `<cask>` is the token of the cask you're submitting.

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, if adding a new cask:

- [ ]  Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
> 1.14.2 is a GitHub pre-release.

It seems this isn't released yet

**Comment by EloB** [comment]
@SMillerDev I hear you but it's more like the repo is more or less inactive. Last released was this PR 1.4.2 on 2022 in May. It contains bug fixes for media buttons. I've been using this version now for very long without any problems. The latest "stable" release is buggy the one published on Brew.

I've been trying to reach the maintainer without any success.
https://github.com/ytmdesktop/ytmdesktop/issues/1092
https://github.com/ytmdesktop/ytmdesktop/issues/205

https://github.com/ytmdesktop/ytmdesktop/tags

**Comment by bevanjkay** [comment]
@EloB If the app is heading down the path of becoming unmaintained it is more likely that this could be removed from `homebrew-cask`. If you would like to manage installation of this with your own version requirements you could consider hosting this [in your own Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
