### PR TITLE
Update krita to 4.0.0

### PR DESCRIPTION
**Pull request by PandelisZ**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by greveritt — CHANGES_REQUESTED** [review]
The download page for Krita says that macOS 10.11 is now required, so I think we should change `:mavericks` to `:el_capitan`

**Comment by MathiasSM** [comment]
Sorry, but for some reason the cask is not working for me. 

I do a simple install, and this comes up:

```
==> Satisfying dependencies
==> Downloading http://download.kde.org/stable/krita/4.0.0/krita-4.0.0.dmg
(...)
==> Verifying checksum for Cask krita
==> Installing Cask krita
==> Purging files for version 4.0.0 of Cask krita
Error: It seems the App source '/usr/local/Caskroom/krita/4.0.0/Krita.app' is not there.
```

The dmg gets downloaded, I already checked that, but even copying the `Krita.app` manually to `/usr/local/Caskroom/krita/4.0.0/Krita.app` is not working, it gets deleted. Should I open a new issue? Or is this related to the upgrade to 4.0.0?

**Comment by PandelisZ** [comment]
I'm able to reliable install reinstall and remove the krita app through homebrew. I'm not intimately familiar with the brew purging process however so I'm not sure what's causing your errors. :/ 

```sh
╰─$ brew cask reinstall krita                                                                   1 ↵
==> Satisfying dependencies
==> Downloading http://download.kde.org/stable/krita/4.0.0/krita-4.0.0.dmg
Already downloaded: /Users/pz/Library/Caches/Homebrew/Cask/krita--4.0.0.dmg
==> Verifying checksum for Cask krita
==> Uninstalling Cask krita
==> Backing App 'Krita.app' up to '/usr/local/Caskroom/krita/4.0.0/Krita.app'.
==> Removing App '/Applications/Krita.app'.
==> Purging files for version 4.0.0 of Cask krita
==> Installing Cask krita
==> Moving App 'Krita.app' to '/Applications/Krita.app'.
🍺  krita was successfully installed!
╭─pz@mcb /Applications
╰─$ brew cask uninstall krita
==> Uninstalling Cask krita
==> Backing App 'Krita.app' up to '/usr/local/Caskroom/krita/4.0.0/Krita.app'.
==> Removing App '/Applications/Krita.app'.
==> Purging files for version 4.0.0 of Cask krita
╭─pz@mcb /Applications
╰─$ brew cask install krita
==> Satisfying dependencies
==> Downloading http://download.kde.org/stable/krita/4.0.0/krita-4.0.0.dmg
Already downloaded: /Users/pz/Library/Caches/Homebrew/Cask/krita--4.0.0.dmg
==> Verifying checksum for Cask krita
==> Installing Cask krita
==> Moving App 'Krita.app' to '/Applications/Krita.app'.
🍺  krita was successfully installed!
╭─pz@mcb /Applications
╰─$ brew --version
Homebrew 1.5.13
Homebrew/homebrew-core (git revision 0ed72; last commit 2018-04-02)
╭─pz@mcb /Applications
╰─$ brew cask --version
Homebrew-Cask 1.5.13
caskroom/homebrew-cask (git revision ff4d05; last commit 2018-04-02)
```

**Comment by MathiasSM** [comment]
Well, I have no problem installing this manually, but if there's anything I should do (report?), let me know.

**Comment by MathiasSM** [comment]
I think I found the error. I had the same issue with another package and found it is probably due to my macOS being case-sensitive (instead of the case-insensitive default). So the dmg has `krita.app`, but the cask asks for a `Krita.app`. Apparently, the font I used didn't let me see the difference between both k's 🙄.

**Pull request merged**
