### PR TITLE
vmware-fusion 13.5.2

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by krehel** [comment]
I regret it had to come to this.  For your review, @Homebrew/cask.

**Review by p-linnane — APPROVED** [review]
I think this is as good as it's going to get. The actual .dmg download links from Broadcom use HMAC.

**Comment by bevanjkay** [comment]
@krehel we should be able to use the `container nested:` stanza to unpack the internal archive. 

I'll have a look soon.

**Comment by krehel** [comment]
Thanks @bevanjkay. I tried that but couldn't get it to cooperate before I went this route. Definitely happy to look at it later. 

It looks like there's also ARM and Intel specific binaries we can tap into and move away from the Universal app, so I'd like to do that too.

If you don't get there I'll check it tomorrow.

**Pull request merged**
