### PR TITLE
add zap and desc stanzas to sixtyforce

### PR DESCRIPTION
**Pull request by spinofdoom**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free. ---> Throws error for no `desc` stanza which this PR fixes.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
@spinofdoom thank you for your contributions, but _please_ ensure that _both_ `brew audit` and `brew style` pass with your changes _before_ submitting a PR, thanks.

**Comment by spinofdoom** [comment]
@miccal Happy to help! Just so I understand, because I'm fairly new, what is the best procedure when, as in this case, the `brew audit` error is due to a lack of `desc` stanza? File an issue? Thanks for your help @miccal.

**Comment by miccal** [comment]
Just add a `desc` stanza as you have here -- the other error with your submission is the trailing whitespace above your `zap` stanza.

**Comment by spinofdoom** [comment]
Thank you @miccal.

**Pull request merged**
