### PR TITLE
lulu.rb: remove preflight

### PR DESCRIPTION
**Pull request by commitay**
After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Refs: https://github.com/caskroom/homebrew-cask/pull/38781

### CODE REVIEW

**Comment by commitay** [comment]
@miccal Next release will support `10.10`+

**Comment by miccal** [comment]
@commitay I know, just wanted to trigger a new build.

**Comment by miccal** [comment]
@commitay any idea as to why Travis is failing on this?

**Comment by commitay** [comment]
Yes, the `preflight` is required to install. This PR is pending until the next release.

**Comment by commitay** [comment]
I'll rebase this and revert the last commit.

**Review by vitorgalvao — APPROVED** [review]
Looks like we can finally merge it.

**Pull request merged**
