### PR TITLE
Fix lrtimelapse download URL

### PR DESCRIPTION
**Pull request by rcloran**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Do you have `HOMEBREW_DEVELOPER` set?

I guess you would need to set `HOMEBREW_NO_INSTALL_FROM_API` too in order to install the cask with your local changes.

**Comment by reitermarkus** [comment]
Alternatively, `brew install ./Casks/lrtimelapse.rb` should work for testing local changes.

**Review by reitermarkus — APPROVED** [review]

**Comment by rcloran** [comment]
Neither of those are documented in the places I saw (https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md , https://docs.brew.sh/Adding-Software-to-Homebrew) :( Anyways, thanks for reviewing -- as I'm sure you saw at the bottom of my gist I did manage to get it tested using the filename as you mentioned.

**Comment by reitermarkus** [comment]
Would be great if you could submit an improvement to the documentation in the places where you would expect to find the relevant information.

@Rylan12, maybe this can also be improved in `brew install` somehow if we detect local changes?

**Comment by Rylan12** [comment]
Yeah, this is known to be bad. We had https://github.com/Homebrew/brew/pull/14807 open to improve this but looks like it stalled.

**Pull request merged**
