### PR TITLE
add kindaVim 1b23

### PR DESCRIPTION
**Pull request by godbout**
- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

**there's one offense: the use of `macOS`. but my tagline is `Vim for the whole macOS.`. the point is **WHOLE**, not macOS. (see https://kindavim.app.). thanks!**

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask). **i don't see any other repo for Freemium?** 
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by godbout** [comment]
i'm the creator of kindaVim and i'm adding this Cask not as a mean for discovery, but because currently users are asking for it: https://github.com/godbout/kindaVim.theapp/issues/37. thank you!

**Comment by bevanjkay** [comment]
@godbout thank you for your contribution to `homebrew-cask`. Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

**Comment by godbout** [comment]
my bad, thought there was nothing to zap. will look more closely and update. thanks.

**Comment by godbout** [comment]
done. thanks!

**Comment by miccal** [comment]
Thank you @godbout.

**Pull request merged**
