### PR TITLE
open-video-downloader: update cask to fork

### PR DESCRIPTION
**Pull request by drbyte**
The former author abandoned the app, but now has a new maintainer: https://github.com/StefanLobbenmeier/youtube-dl-gui
Related: https://github.com/jely2002/youtube-dl-gui/issues/494

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by drbyte** [comment]
I'm not sure why `livecheck` is pulling a different version number. 
Here's the Releases page: https://github.com/StefanLobbenmeier/youtube-dl-gui/releases

**Comment by drbyte** [comment]
Aside: Is there value in extracting the `sha512` from the `latest-mac.yml` on Github? Or does homebrew prefer sha256?
I'm not sure how to script that out, or if there's something already in Homebrew to automate that.

**Comment by krehel** [comment]
The changes in this PR seem to be the current community agreed upon fork, and the original repo is considered abandoned.

**Review by bevanjkay — APPROVED** [review]

**Comment by razvanazamfirei** [comment]
> Aside: Is there value in extracting the sha512 from the latest-mac.yml on Github? Or does homebrew prefer sha256?
I'm not sure how to script that out, or if there's something already in Homebrew to automate that.

`brew bump-cask-pr` calculates the checksum, so there's no need to extract it from other sources.

This looks good, and I agree with @krehel! Thank you, @drbyte for opening this.

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
