### PR TITLE
Add AppGate.app v3.2.1.8632

### PR DESCRIPTION
**Pull request by rjmco**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please fill the template that was there when you opened the PR.

**Comment by rjmco** [comment]
@vitorgalvao Hi,

Apologies. I submitted the PR using [hub.github.com] hence why I didn't fill in the template on creation.

Here it is:

After making all changes to the cask:

- [x] `brew cask audit --download appgate-sdp-client.rb` is error-free.
- [x] `brew cask style --fix appgate-sdp-client.rb` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating only the `sha256`**:

- [x] I verified this change is legitimate [<sup>How do I do that?</sup>][version-checksum] and **am providing confirmation below**:

_The .dmg file is downloaded from the official site and upon personally testing it I found the application works as expected. VirusTotal also does not detect any issues with the [file](https://www.virustotal.com/#/file/db178b54893c5d291553f35ab5084cd289bf4f92180893b127d0129c4ba181f7/detection) nor with the [url](https://www.virustotal.com/#/url/673340f7b9a38bd15b99e61a79034cc9f2bb1a9fbb43684f4c623c1f36ff6f7a/detection)._

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install appgate-sdp-client.rb` worked successfully.
- [x] `brew cask uninstall appgate-sdp-client.rb` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo] _(the stable repo)_.

[hub.github.com]: https://hub.github.com/
[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

**Review by commitay — APPROVED** [review]

**Comment by rjmco** [comment]
@vitorgalvao I believe it is once again ready for review.

**Comment by miccal** [comment]
Thank you for your contribution.

**Pull request merged**
