### PR TITLE
Fix adobe-creative-cloud

### LINKED ISSUE #85080: Cannot install adobe-creative-cloud (erro code 72)
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

When I try to install creative cloud, the installer return erro code 72.

#### Command that failed

```
brew cask install adobe-creative-cloud
```

#### Output of command with `--force --verbose --debug`

```
==> Downloading https://ccmdls.adobe.com/AdobeProducts/KCCC/1/osx10/CreativeCloudInstaller.dmg
Already downloaded: /Users/misakisuna/Library/Caches/Homebrew/downloads/999ed46ed9a0fc491d156ffac99b05d559dce85d0486ebaaa663aa0e2232cec9--CreativeCloudInstaller.dmg
==> No SHA-256 checksum defined for Cask 'adobe-creative-cloud', skipping verification.
==> Installing Cask adobe-creative-cloud
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/d20200627-11810-ddg5fv /Users/misakisuna/Library/Caches/Homebrew/downloads/999ed46ed9a0fc491d156ffac99b05d559dce85d0486ebaaa663aa0e2232cec9--CreativeCloudInstaller.dmg
mkbom -s -i /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/20200627-11810-unjdmf.list -- /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/20200627-11810-1gvopfr.bom
ditto --bom /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/20200627-11810-1gvopfr.bom -- /private/var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/d20200627-11810-ddg5fv/dmg.wBqwTy /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/d20200627-11810-gag85p
diskutil eject /private/var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/d20200627-11810-ddg5fv/dmg.wBqwTy
cp -pR /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/d20200627-11810-gag85p/Creative\ Cloud\ Installer.app/. /usr/local/Caskroom/adobe-creative-cloud/latest/Creative\ Cloud\ Installer.app
chmod -Rf +w /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/d20200627-11810-gag85p
==> Running installer script '/usr/local/Caskroom/adobe-creative-cloud/latest/Creative Cloud Installer.app/Contents/MacOS/Install'
Progress of PDM is 0
Progress of PDM is 100
Progress of PDM is 0
Progress of PDM is 5
Progress of PDM is 10
Progress of PDM is 66
Progress of PDM is 80
Progress of PDM is 100
==> Purging files for version latest of Cask adobe-creative-cloud
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/adobe-creative-cloud/latest/Creative\ Cloud\ Installer.app/Contents/MacOS/Install --mode=silent` exited with 72. Here's the output:
Starting Installer...
Progress of PDM is 0
Progress of PDM is 100
Progress of PDM is 0
Progress of PDM is 5
Progress of PDM is 10
Progress of PDM is 66
Progress of PDM is 80
Progress of PDM is 100
Some error occured during installation. Instalaltion Cannot continue
Installer returning with erro code 72

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:150:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.4.2
==> macOS
10.15.5
==> SIP
Enabled
==> Java
14.0.1
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3598 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1547 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.40.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/core
mattisg/mattisg
universal-ctags/universal-ctags
```

### PR DESCRIPTION
**Pull request by ran-dall**
Closes #85080

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]

**Comment by endlesslycurious** [comment]
Just ran update via 'brew bundle' during the adobe creative cloud update it deleted my installed creative cloud applications i.e. Lightroom & Photoshop. Is this expected behaviour?

**Comment by ran-dall** [comment]
@endlesslycurious I wanna say 'no' but honestly I don't know for sure cause I haven't run `brew bundle` with it yet. I really don't think so and it might just be a hiccup with the update but then again Adobe is a pain with this type of stuff.

**Comment by endlesslycurious** [comment]
Yeah, there was allot of terminal output scrolling past during the update to see what actually happened other than from the speed that things were being removed (later confirmed by missing Apps). Does brew have cleanup code that would delete things based on triggers or is it likely to have been an Adobe action?

Mostly curious more than anything.

**Comment by ran-dall** [comment]
@endlesslycurious Well tbh the uninstall is something @danielbayley made in #69590 and #68039. However usually HBC does uninstall the casks to replace it when it upgrades them though. Hence the output.

That said, Adobe is notoriously user hostile; frankly, I avoid them like the plague. My wife (whose a Graphic Designer) depends on their software though, so I won't ever be able to banish Adobe in my house, lol. I try to use Affinity Designer / Photo / Publisher, as much as I can, although their features aren't up to par with Adobe and their bugs have always been a problem for everyone it seems (😉 @vitorgalvao).

**Comment by danielbayley** [comment]
> However usually HBC does uninstall the casks to replace it when it upgrades them though. Hence the output.

@endlesslycurious @ran-dall Yeah I think this is the problem. I have some other changes to test locally which I'll get around to pushing in another PR… I'll see if this problem can be fixed, or if it's actually an inherent problem with HBC (I think there is a similar problem when updating Backblaze…)

**Pull request merged**
