### PR TITLE
deprecate wine-stable in flavor of wine formula

### PR DESCRIPTION
**Pull request by yurikoles**
See https://github.com/Homebrew/homebrew-cask/issues/65309#issuecomment-508922390

### CODE REVIEW

**Comment by vitorgalvao** [comment]
What about the other wine versions?

**Comment by yurikoles** [comment]
`-devel` is unstable version, `-staging` also adds experimental patches on top of it.

**Comment by yurikoles** [comment]
There was a long battle on bringing those in form of formula(-s).

**Comment by vitorgalvao** [comment]
> There was a long battle on bringing those in form of formula(-s).

And do they exist as formulae?

**Comment by yurikoles** [comment]
No, they don't (yet).

**Comment by vitorgalvao** [comment]
> No, they don't (yet).

Then let’s wait a bit, or this will be confusing.

**Pull request closed without merging**
