### PR TITLE
cryptol: migrate to Homebrew

### PR DESCRIPTION
**Pull request by AnastasiaSulyagina**
Deleting cryptol from cask as part of deduplication process . See context [here](https://github.com/caskroom/homebrew-cask/issues/15603). 

_Please note that this PR is created to continue case-by-case discussions from thread linked above and if decision is made not to remove the cask, PR will be closed._

### CODE REVIEW

**Comment by reitermarkus** [comment]
Also a language, so I'm in favour.

**Comment by vitorgalvao** [comment]
There’s now a conflict (`tap_migrations.json`, since another of these was merged).

**Comment by jawshooah** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 813f611dc49036a581a22118028cf58d94368a24. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by jawshooah** [comment]
Huh, not sure what happened with that one. Sorry @AnastasiaSulyagina!

@vitorgalvao, I think that either I don't understand how to properly use `git am`, or `git rebase` would be a better choice for `prfixmaster` when there are conflicts.

**Comment by vitorgalvao** [comment]
@jawshooah Yes, I’ve seen that happen before, but never really pinpointed the cause. In my cases it always does the commits correctly, it’s just the commit hash in the message that is wrong. Thank you for your recent fix, as usual.

**Pull request closed without merging**
