### PR TITLE
Update flume to 2.8.2

### PR DESCRIPTION
**Pull request by sanyer**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by commitay — CHANGES_REQUESTED** [review]
`sha256` only changes need to be verified. See [updating the `sha256`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256) for how to provide verification.

**Comment by sanyer** [comment]
The version is the same, `sha256` and `checkpoint` were updated.

**Comment by sanyer** [comment]
VirusTotal results: https://www.virustotal.com/#/file-analysis/NDU0MTg5OWRhNDYxMWEzNjRlMDk5MTQzNTM4ZjNkYTg6MTUxMDE3OTM4OA==

**Comment by commitay** [comment]
Thanks!

**Review by commitay — APPROVED** [review]

**Pull request merged**
