### PR TITLE
active-trader-pro 1.0.50 (new cask)

### PR DESCRIPTION
**Pull request by karimbenbourenane**
Active Trader Pro is an advanced trading platform for customers of Fidelity Investments.

The original submission of this cask was for an unsigned app; since then, the developers have fixed their build process and signed the app so that it passes all Caskroom checks for new applications.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Hi, @karimbenbourenane! Thanks so much for your first contribution! I found a sparkle appcast URL in the app and made some modifications around that. The first time launching the app I ended up waiting for a few minutes while the script at `Active Trader Pro.app/Contents/SharedSupport/activetrader/Active Trader Pro/run_atp ` ran. I'll try and see what happens if we run that script in the install process.

**Comment by razvanazamfirei** [comment]
Ok, this script is pretty noisy, using `CW_INSTALL_DEPS_ONLY=1` to prevent the app from launching. In all honesty, I don't think we need to run the script on install.

**Comment by razvanazamfirei** [comment]
As it turns out the versioned URL serves an unsigned binary, reverting URL changes. Based on what I've seen, on first launch the app is setting up Wine; at some point that script should be run otherwise the app is unusable. 

@karimbenbourenane, using your submitted Casks, are you having any issues after install with launching and using the app?

**Comment by karimbenbourenane** [comment]
Indeed, I am getting stuck at this stage: 
image
It hasn't been static the whole time, the progress bar did increase a few times while I watched it, and the banner text at the bottom saying "Installing Microsoft .NET 4.6.2" did actually change during that time, so I am unsure if this is a network problem or something else. If wine was crashing because it couldn't finish, wouldn't this dialog box disappear?

**Comment by karimbenbourenane** [comment]
I spoke too soon, its now advanced to this 
image

**Comment by karimbenbourenane** [comment]
Installation completed for me, and the installer closed peacefully and with no fanfare. I went to then open `/Applications/Active Trader Pro.app` and it opened with no issues whatsoever, presenting the login screen to input Fidelity user credentials:
image

So far this has all worked for me. Thank you by the way for filling in the extra paths I missed for the uninstaller, and to answer a question I asked of you earlier on how you found the xml describing other versions, I did some reading on sparkle in the official Homebrew [docs](https://docs.brew.sh/Cask-Cookbook) and found that there is a command buried away for discovering it:

```
The :sparkle strategy takes a URL for an XML feed providing release information to an app that self-updates using the Sparkle framework. This URL can be found within the app bundle as the SUFeedURL property in Contents/Info.plist or by using the [find-appcast](https://github.com/Homebrew/homebrew-cask/blob/HEAD/developer/bin/find-appcast) script. Run it with:

"$(brew --repository homebrew/cask)/developer/bin/find-appcast" '/path/to/application.app'
```

**Review by razvanazamfirei — APPROVED** [review]

**Pull request merged**
