### PR TITLE
Add Performance Co-Pilot (PCP) Cask

### PR DESCRIPTION
**Pull request by tallpsmith**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version. -- `alas sorry I did not see this requirement until after I was preparing the Pull Request.  I'll remember for next time.   The commits do have at least PCP in the message, but in hindsight I can see now why you'd want this requirement. To be transparent I buggered my remote branch once and lost a series of commit history, and had to effectively squash some commits because the rebase went to hell..  :-|  `

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by miccal** [comment]
Won't some of the files listed in `uninstall delete:` be removed by `uninstall pkgutil:`?

**Comment by vitorgalvao** [comment]
Don’t worry too much about `The commit message includes the cask’s name and version.`. We can fix that while merging.

I second @miccal’s question.

**Comment by tallpsmith** [comment]
So yes the fact that there are a lot of manual `delete` lines in there is an obvious oddity.  I only discovered that these residual symlinks were hanging around after an uninstall when I was trying to use my local PCP and discovered that the symlinks were still there even after an `brew cask uninstall`.

I've verified that these files are not part of the package:

```
[ homebrew-cask ](pcp)$ pkgutil --file-info /usr/local/bin/pmlc
volume: /
path: /usr/local/bin/pmlc
```

and then also looked for any file from the `com.sgi.pkg.pcp` ID that lives in `bin`, but there's none..:


```
[ homebrew-cask ](pcp)$ pkgutil --files com.sgi.pkg.pcp | fgrep bin
[ homebrew-cask ](pcp)$
```

I have started conversations with the PCP team about this - their OSX build is a bit weak and there's actually a GSoC proposition for this year to improve this which I'm hopeful will get approved.

I can add a commit with a comment describing this situation if it helps.

**Comment by vitorgalvao** [comment]
> I have started conversations with the PCP team about this - their OSX build is a bit weak and there's actually a GSoC proposition for this year to improve this which I'm hopeful will get approved.
>
> I can add a commit with a comment describing this situation if it helps.

No need for the comment. Thank you for taking the time to talk with them to try to get this improved.

**Review by vitorgalvao — APPROVED** [review]

**Comment by vitorgalvao** [comment]
Verified locally due to Travis delays.

**Pull request merged**
