### PR TITLE
Update twist from 1.0.1 to 1.0.3

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
@miccal Electron-builder appcast is available at https://downloads.twist.com/mac/latest-mac.yml. Would you prefer that over the current header check?

**Comment by bevanjkay** [comment]
@neutric The appcast will follow the in-app updater, and the header_match will follow the website download link. As we're using the binaries as generated with the appcast, I would prefer to use the appcast for livecheck here.

**Comment by neutric** [comment]
@bevanjkay Since you say "here". Are there any cases where header_match would be preferred over the electron_builder appcast?

**Comment by bevanjkay** [comment]
@neutric I can't think of any. The `:electron_builder` appcasts are useful because they provide us with easy access to the versioned URL downloads.

**Pull request merged**
