### PR TITLE
Update thebrain from 10.0.51.0 to 10.0.52.0

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Appcast still shows previous version. Pinging @core-code as well, since it’s a `macupdater` appcast.

**Comment by core-code** [comment]
the appcast shows the version that the official download downloads. i've just verified whether this is still correct - it is.

since the official download still points to 10.0.51.0 and there is no other mention of 10.0.52.0 on the site, i'd recommend holding this off.

@suschizu can you ignore this release for our database check?

**Comment by suschizu** [comment]
ok 10.0.52.0 will be ignored

**Comment by core-code** [comment]
also, here is the official update check, which also doesn't show 10.0.52.0 yet:

`curl -H 'Date: Sun, 04 Aug 2019 09:57:37 GMT' -H 'Authorization: TB1 3NUJKeFovywnqgURI+51lb2ZiuobNfX4mkfqpJz9xjBoz+Jz2QKeoemv2XNyWUhEeZh6pb7khEhevMFF9cLmiPsBQ7q7qSUTCLt8ydIQIc+h5U53959EG5rhB3BERrlHlkPqiKvFODvSVQCO2alUa1Ow9jAskJQ80fQGtuJgKyuQcjs3yMOWaBcEm/DH8kcdub3hvlct3qOrSB9wtPErkalEn4/KWgwGr8MmbUWVl/1Xc0ZGL6zWglsQqIfKSjSrxoynsdPDvutZpAKjUyETOYDD2JpZmJLvUhjZsF+WUMOVQN08Bgtrd6jb1w3Y/2zC8mEn1mAkM8l+jZjx6xsP4dL1Kvqr2OqOnAdiOCJ1e3c6+hB/37l9ZYrr45lwxcwNx0Kiz5I7Q5THu872+EmKFacNmcCkdaGTyi6rhzEmWzyOnjAwEQybzjZdS0kJ1sSb3W7eAhSAJfV5y7pKFWwadg==' -H 'Content-Type: text/plain; charset=utf-8' -H 'Host: api.thebrain.com' --data-binary '{"distributionChannel":"1","hasPerpetualLicense":"false","isPaidUpgradeOffer":"false"}' 'https://api.thebrain.com/ServerLogic/GetUnauthenticatedUpdateInfo'`

**Pull request closed without merging**
