### PR TITLE
Update mediathekview to 13.2.0

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
this is maybe a better appcast:
https://download.mediathekview.de/stabil/

similarly, the latest release (currently `13.2.0` doesn't get a version number, it's just `latest` on that page) so I have updated the cask accordingly.

**Comment by mmoehring** [comment]
For this app curl get's a HTTP 503 when called from within homebrew cask. It works when curl is called standalone. I opened an issue at the maintainers website/server repository (https://github.com/mediathekview/MediathekViewDE/issues/38) for investigation.

**Comment by brianmorton** [comment]
```
I think homebrew-cask makes too many queries. I limited the download with limits. Have these now increased times. can test again?
```

we can also try using the `:fake` symbol for a UA to get around this... thoughts?

**Comment by mmoehring** [comment]
I did not find the code/value for ``:fake``. Is it randomized for each request or is it a fixed? A fixed UA might soon get the same problem.

**Comment by brianmorton** [comment]
Maintainers: I have tried this with both the `:fake` UA symbol and a real one and both times it was 503. Not sure how to make this work (it doesn't seem to take a referrer or cookies).

**Comment by reitermarkus** [comment]
Wow, this was a hard bug to figure out, but I'm not sure how this would be fixable.

It is failing because we make two requests, one to get the final URL, and one for the actual download.

If I put a `sleep 1` in between these steps, it works.

**Comment by reitermarkus** [comment]
The download is now working, but the checksum changed.

**Comment by reitermarkus** [comment]
> currently `13.2.0` doesn't get a version number

Seems like it does now.

**Comment by alex1702** [comment]
@brianmorton change checksum to `0f2eea2cd6ae188c16ecebe220e372cb27ed2e1e5307c447e9f1d1b060296155`

**Comment by brianmorton** [comment]
dropped the URL change, updated the shasum

**Pull request merged**
