### PR TITLE
defold 1.6.0

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by lzap** [comment]
Ah so it was a bug in homebrew and not a security beach, I will tell the authors. Thanks, I missed that.

**Comment by bevanjkay** [comment]
@lzap No, definitely not a bug in Homebrew. It means that the specific version was replaced in place without a new version being created. This results in a shasum mismatch and is generally frowned upon, standard procedure would be to increment the version number when a change is made.

**Comment by lzap** [comment]
Oh yeah that was not what I meant, sorry. Noted.

**Review by bevanjkay — APPROVED** [review]

**Comment by lzap** [comment]
I just updated and I don’t see the change yet, is there anything I need to update to see the change?

**Comment by miccal** [comment]
https://github.com/Homebrew/homebrew-cask/pull/157165

**Pull request merged**
