### PR TITLE
Add autoupdate to copilot-for-xcode

### PR DESCRIPTION
**Pull request by HuaDeity**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Does it actually auto-update? Or does it just tell you there is an update?

**Comment by HuaDeity** [comment]
> Does it actually auto-update? Or does it just tell you there is an update?

I didn't try, but there is a Check for Updates Button in the Application.

**Comment by SMillerDev** [comment]
You should check, since that's pretty important

**Comment by SMillerDev** [comment]
On its own without pressing buttons?

**Comment by HuaDeity** [comment]
> On its own without pressing buttons?

It can set to automatically download and install updates.

**Review by miccal — APPROVED** [review]

**Pull request merged**
