### PR TITLE
Change github-desktop URL to "latest" pattern

### PR DESCRIPTION
**Pull request by otaran**
The URL has been taken from homepage.

### CODE REVIEW

**Comment by scribblemaniac** [comment]
Versioned urls are favored over latest urls.

**Comment by Ngrd** [comment]
Thank you for the contribution. However, the versioned URLs are more preferred. Furthermore, the URL you provided just redirects to the previous one.

**Comment by otaran** [comment]
It seems to me that cloudfront URL can be easily changed by GitHub without Caskroom noticing, thus breaking the Cask. Is it ok?

**Comment by Ngrd** [comment]
Yes, it's ok. This thing happens and we cannot guarantee that even the links on vendor homepage won't change. This is the main reason why the casks have to be maintained all the time.

**Comment by otaran** [comment]
ok, thanks

**Pull request closed without merging**
