### PR TITLE
Update fawkes from 0.3.1 to 1.0

### PR DESCRIPTION
**Pull request by applemayexist**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
CI failure in SSL certificates of `:homepage`.
Not sure if issue is client certificates used by Homebrew or the webpage certificates.

Manual test using Apple's curl with LibreSSL/2.8.3 works:
```console
❯ /usr/bin/curl "https://sandlab.cs.uchicago.edu/fawkes/"
                                    <U><A href="https://people.cs.uchicago.edu/~ewillson/">Emily Wenger</a></U><sup>&#82                                <LI><A HREF="mailto:fawkes-team@googlegroups.com">Email us</A> to join <U><A HREF="...
```

But Homebrew's curl with OpenSSL/1.1.1k fails for me
```console
❯ curl "https://sandlab.cs.uchicago.edu/fawkes/"
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html
```

**Review by carlocab — DISMISSED** [review]
Thanks!

**Review by cho-m — APPROVED** [review]
Manually confirmed failing CI test:
```console
❯ brew audit --cask --appcast --online './Casks/fawkes.rb'
==> Downloading https://mirror.cs.uchicago.edu/fawkes/files/1.0/Fawkes-1.0.dmg
######################################################################## 100.0%
audit for fawkes: passed
```

**Pull request merged**
