### PR TITLE
Upgrade Fluid.app to 2.1.1

### PR DESCRIPTION
**Pull request by soupdiver**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Closing in favour of the conversation in https://github.com/Homebrew/homebrew-cask/pull/53749.

**Comment by soupdiver** [comment]
@vitorgalvao but my version is 2.1.1 and not 2.1.
Isn't the talk in the issue about 2.1 and now 2.1.1 is the next "proper" release?

**Comment by vitorgalvao** [comment]
> Isn't the talk in the issue about 2.1

No, it’s about the developer having pulled that version and discussing a new distribution method.

**Comment by commitay** [comment]
Updated in https://github.com/Homebrew/homebrew-cask/pull/53790

**Pull request closed without merging**
