### PR TITLE
Add `secure_connection_audit_skiplist` to `audit_exceptions`

### PR DESCRIPTION
**Pull request by Rylan12**
This PR corresponds with https://github.com/Homebrew/brew/pull/12185 (they can be merged in either order). It adds a list to the `audit_exceptions` directory to contain names and homepages for casks with homepages that are unreachable due to the Cloudflare issue.

@Homebrew/cask once this is merged, please add casks (and their homepages) to this list _instead of_ merging a PR with a failed audit. All you need to do is add a new line to the `audit_exceptions/cert_error_allowlist.json` file with the cask token and the homepage that is failing. Pushing that change (whether in a separate commit or ammending an existing one) should fix the failure and CI should be green.

As always, feel free to ping me once this is merged if it doesn't seem to be working right.

Currently, the list contains `accurics`, `badlion-client`, `canva`, and `ilok-license-manager` because those are the casks that I know are failing. If there are other casks that are known to have this issue, let me know so I can add them now. Otherwise, I figure this list will just be built up over time.

(Sorry for the double ping. I messed up my branches for some reason and needed to remake the PR)

### CODE REVIEW

**Review by bevanjkay — DISMISSED** [review]

**Comment by SMillerDev** [comment]
The cloudflare issue isn't with the certificates though AFAIK. It's simply blocked

**Comment by MikeMcQuaid** [comment]
> The cloudflare issue isn't with the certificates though AFAIK. It's simply blocked

@SMillerDev does this mean e.g. `curl --insecure` will fail too?

**Comment by SMillerDev** [comment]
Very likely yes. I think the details are in slack, but it blocks the homebrew user agent.

**Comment by Rylan12** [comment]
I've renamed the list `https_audit_skiplist` per feedback in https://github.com/Homebrew/brew/pull/12185

**Comment by Rylan12** [comment]
The name of the audit is [`check_https_availability`](https://github.com/Homebrew/brew/blob/6009f35365aad8e070ae82d75d2095cbabfd5e5d/Library/Homebrew/cask/audit.rb#L735-L753) which leads me to believe that it does relate to HTTPS. If that's not the problem, maybe the audit isn't catching what it's supposed to.

Also, the reason I'm trying to avoid that is that the audit checks more than just the homepage. It covers the binary, appcast, and homepage URLs.

**Comment by cho-m** [comment]
The `check_https_availability` audit does compare HTTPS and HTTP data, but it also makes sure HTTP status code is non-error. So, it ends up indirectly auditing 403/404/etc URLs.

There actually is a special-case for Cloudflare bot-protection, but I don't think the headers detection for this (e.g. `__cfduid`) encompasses the sites listed here (e.g. they have `__cf_bm` but not `__cfduid`).

https://github.com/Homebrew/brew/blob/1eaf8dbbec28e37d4f7cd7642287fa0ab58a6d86/Library/Homebrew/utils/curl.rb#L189-L193
```rb
    def url_protected_by_cloudflare?(details)
      [403, 503].include?(details[:status].to_i) &&
        details[:headers].match?(/^Set-Cookie: __cfduid=/i) &&
        details[:headers].match?(/^Server: cloudflare/i)
    end
```

https://github.com/Homebrew/brew/blob/1eaf8dbbec28e37d4f7cd7642287fa0ab58a6d86/Library/Homebrew/utils/curl.rb#L251-L255
```rb
      unless http_status_ok?(details[:status])
        return if url_protected_by_cloudflare?(details) || url_protected_by_incapsula?(details)

        return "The #{url_type} #{url} is not reachable (HTTP status code #{details[:status]})"
      end
```

---

If the binary hits this issue, we currently have to drop the Cask as there is no way to download it anymore.

If the appcast/livecheck URL hits this issue, the URL needs to be changed/removed.

These will probably be caught in a different audit/test though. Binary issue means any fetch attempt will fail while Livecheck/audit failure has its own check.

**Comment by SMillerDev** [comment]
> If that's not the problem, maybe the audit isn't catching what it's supposed to.

Https isn't specifically the problem. But due to the nature of an HTTPS check it'll also fail if no connection if any kind can be made. That's a good thing for an audit, it just makes naming kinda difficult.

How about making it a `secure_connection_audit_skiplist`? That makes it clear it checks the whole connection, including https.

**Comment by Rylan12** [comment]
I'm happy to add that change to https://github.com/Homebrew/brew/pull/12185 if desired

**Comment by bevanjkay** [comment]
@Rylan12 It looks like https://github.com/Homebrew/brew/pull/12220 has likely solved the issues for the four casks that are currently on the exception list.

**Comment by Rylan12** [comment]
Ah, good to know! If we're expecting more in the future, how would you feel about still adding this list but as an empty JSON file (like we've done [here](https://github.com/Homebrew/homebrew-cask/blob/master/audit_exceptions/gitlab_prerelease_allowlist.json)) to make it easy to add casks in the future?

**Comment by bevanjkay** [comment]
> Ah, good to know! If we're expecting more in the future, how would you feel about still adding this list but as an empty JSON file (like we've done [here](https://github.com/Homebrew/homebrew-cask/blob/master/audit_exceptions/gitlab_prerelease_allowlist.json)) to make it easy to add casks in the future?

Agreed!

**Pull request merged**
