### PR TITLE
font-0xproto 2.201

### PR DESCRIPTION
**Pull request by arjpar**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Review by khipp — APPROVED** [review]
Thank you, @arjpar!

**Comment by tsuwatch** [comment]
@arjpar I can't install, Isn't this the correct checksum? `cc383e1562085438d026ef6c3ad678ca0a12d8349013485adce9791890bf8821`

**Comment by arjpar** [comment]
@tsuwatch It seems like the checksum did not get updated or is incorrect, which is weird. I now get the checksum (sha256) as `cc383e1562085438d026ef6c3ad678ca0a12d8349013485adce9791890bf8821`. I tested it beforehand with the old checksum currently being used, on my machine, and it worked then. Weird, but yeah the checksum is currently incorrect for the zip file.

It seems like he re-uploaded the zip file and the checksum changed.

image


Despite the original release being on Sep 6.

image

That would explain why the checksum changed.

**Comment by tsuwatch** [comment]
@arjpar I see, that does seem to be the case. I will fix it, thank you!

**Pull request merged**
