### PR TITLE
Add kieler-1.1.1

### PR DESCRIPTION
**Pull request by xaaronc**
The requirement to explicitly remove the quarantine attribute is documented at the project website:
https://rtsys.informatik.uni-kiel.de/confluence/display/KIELER/Downloads

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @xaaronc.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

**Comment by xaaronc** [comment]
> Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

Done.

**Comment by miccal** [comment]
Thank you @xaaronc.

**Review by miccal — APPROVED** [review]

**Comment by vitorgalvao** [comment]
> The requirement to explicitly remove the quarantine attribute is documented at the project website

By that logic, a malware vendor would only have to document that quarantine needs to be removed to distribute their malicious code through HBC without quarantine.

Documented or not, *it’s the user’s choice to disable security features*. We as HBC can decide if we provide those security features [or not](https://github.com/Homebrew/homebrew-cask/issues/70798), but if we do we can’t disable them without telling the user.

Continued in https://github.com/Homebrew/homebrew-cask/pull/98527.

**Pull request merged**
