### PR TITLE
Update datadog-agent to 6.6.0-1

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
I’ve added all suggestions from travis but I still receive an error when uninstalling the app - could somebody perhaps have a look on that? Thank you!

**Comment by vitorgalvao** [comment]
Ping @reitermarkus.

This kind of thing has been happening a lot. Are these things we need to fix in the core, or are they Travis-related?

**Comment by ran-dall** [comment]
@vitorgalvao I had a question/suggestion. Couldn't we use something like what you suggested here: https://github.com/Homebrew/homebrew-cask/issues/36162#issuecomment-312849549

**Comment by core-code** [comment]
so, is there any way to get this un-stuck?

**Comment by core-code** [comment]
i have installed the package locally and can not reproduce the travis error. the files travis complains are missing *are* actually installed. so i believe the failure is nonsense.

in any case, why does travis complain if files that the package installs are not there? its very common that PKGs do that.

for example, this very package claims to install the application to /opt/datadog-agent/ , but actually its moved to /Applications in the postinstall. so, if travis wouldn't trip earlier, it would trip there.

because of the move-around in the postinstall, for this cask to be correct it should have an 
`uninstall delete /Applications/Datadog Agent.app`

**Comment by core-code** [comment]
ok, i've installed the updated cask, and indeed we get the error that travis claimed on uninstall ;(

the trouble is that the package is basically broken. they list files that only differ in case, and of course HFS/APFS is case insensitive. after deleting the first of them, the second one is not there. thats why my analysis was off - the file is there - but it won't be after deleting another one which differs just in case.

is there a way to have 'uninstall pkgutil' succeed even when some files aren't there? i see erroring out in this case as terribly un-useful.

**Comment by ran-dall** [comment]
@core-code Very good work!

**Pull request merged**
