### PR TITLE
Rename gogland to goland, update to 1.0 EAP,173.3531.21

### PR DESCRIPTION
**Pull request by jcbot**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

This PR has been created semi-automatically with the [jetbrains-cask-bot](https://github.com/leipert/jetbrains-cask-bot)

/cc @leipert

### CODE REVIEW

**Comment by leipert** [comment]
It seems like they are renaming `gogland` to `goland`.
Src:(https://www.jetbrains.com/go/) and https://data.services.jetbrains.com/products/releases?code=GO&latest=true&type=eap

Do we rename the cask file as well?

**Comment by leipert** [comment]
Furthermore I checked (installed and used goland) and the zap stanzas still seem to be the old (`Gogland`)

**Comment by commitay** [comment]
> Do we rename the cask file as well?

Yes.

**Comment by leipert** [comment]
Done.

**Comment by leipert** [comment]
Also here is the 110% proof that the product has been renamed:
https://twitter.com/GoLandIDE/status/926157642158034945

**Comment by leipert** [comment]
Thanks @commitay for the uninstall_postflight fix 👍

**Comment by commitay** [comment]
Thanks @leipert!

**Pull request merged**
