### PR TITLE
Update focus

### PR DESCRIPTION
**Pull request by scribblemaniac**
Add uninstall and zap stanza.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Trailing whitespace detected.

**Comment by scribblemaniac** [comment]
Fixed

**Comment by vitorgalvao** [comment]
Thank you. I don’t know how you’re finding casks to fix, and this is in no way meant as an imposition (spend your time as you like, and all your fixes are greatly appreciated), but if you’re ever finding yourself wanting to get something to fix and don’t know where to look, I’ve spent the day yesterday labeling every single issue and PR, so [open PRs relating casks](https://github.com/caskroom/homebrew-cask/pulls?q=is%3Apr+label%3Acask+is%3Aopen) (usually need fixes, if they’re labeled and still open) for example, are easy to find.

Again, thank you for all the fixes, and any work you take on is appreciated, but wanted to let you know that is there.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 994924e2e32bd6569ff7f920a71298a61d71d9be to keep commit history cleaner. Your contribution is still credited to you.

**Comment by scribblemaniac** [comment]
Thanks, I'll keep that in mind!

**Pull request closed without merging**
