### PR TITLE
aria2gui: remove

### PR DESCRIPTION
**Pull request by chenrui333**
last release was like six years ago
image

image

### CODE REVIEW

**Comment by bevanjkay** [comment]
I'm not convinced that this should be removed yet, while it is discontinued, it is still relatively popular.
So if it is still functional we should keep it.

**Comment by chenrui333** [comment]
(on one side, I agree with you, on the other side, I think this is good to be deleted so that people can look for alternative choices)

**Comment by chenrui333** [comment]
I will leave this PR open for a bit

**Comment by chenrui333** [comment]
Just like this PR, #161053 (fortunately, the repo is not archived, people have a central place to discuss the issues, IMO, this cask should be removed at this point)

**Comment by chenrui333** [comment]
cc @Homebrew/cask

**Comment by razvanazamfirei** [comment]
> I'm not convinced that this should be removed yet, while it is discontinued, it is still relatively popular. So if it is still functional we should keep it.

Agree with this.

**Comment by krehel** [comment]
Think we all agree on keeping this due to popularity and pending future implementation of `deprecate/disable`.

Closing as unmerged.

**Pull request closed without merging**
