### PR TITLE
updated jettison (1.5)

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Comment by adityadalal924** [comment]
Assuming you're confident in all of these PRs, we could just `fastmerge` them and just let Travis run once - when it checks the `master` branch

**Comment by vitorgalvao** [comment]
> Assuming you're confident in all of these PRs

Not in all. [At least one slipped through](https://github.com/caskroom/homebrew-cask/pull/16491/files) (closed it when I noticed the error, which I only did because Travis failed).

I wouldn’t oppose to `fastmerge`ing them, as long as another pair of eyes took a look before.

**Comment by adityadalal924** [comment]
Merged as 512d02cef87e0e63de5ea972474b95550039a60b.

**Comment by adityadalal924** [comment]
Going to merge all the ones with clearly negligible changes (no url changes)

**Pull request closed without merging**
