### PR TITLE
remarkable: deprecate due to moving to app store

### LINKED ISSUE #164484: Remarkable desktop app has moved to the Apple Store
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I tried installing the Remarkable app using and when i opened the app a notification informed me that this version of the app will be deprecated in the future as the app has migrated to the App store [App Store URL](https://apps.apple.com/us/app/remarkable-desktop/id1276493162).

I tried doing an update, and a clean-install. Then i saw that [On the source of the cask](https://github.com/Homebrew/homebrew-cask/blob/49884d9255bc731976b11a79589146691bec92db/Casks/r/remarkable.rb) the installation is still from the vendor site (remarkable.com), it should be migrated to use the app store instead.

### Command that failed

brew install --cask remarkable

### Output of command with `--verbose --debug`

```shell
Command works normally with old version
```

### Output of `brew doctor` and `brew config`

```shell
HOMEBREW_VERSION: 4.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: b3751bca8c4a3c76107d5aa3b75b81db93cf4bb6
Last commit: 8 days ago
Core tap JSON: 15 Jan 19:56 UTC
Core cask tap JSON: 15 Jan 19:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: vivaldi
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/code
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
brew tap
gromgit/fuse
homebrew/bundle
homebrew/services
```

### PR DESCRIPTION
**Pull request by krehel**
Closes #164484

### CODE REVIEW

**Comment by bevanjkay** [comment]
Has it moved to the App Store already, or is just going to be moved?

**Comment by krehel** [comment]
I don't have this app, but the [support page](https://support.remarkable.com/s/article/Desktop-app) instructs to download from the App Store, so I'd think it's being deprecated.  Excerpt below...

_Click Download the desktop app for Windows or Download on the Mac App Store._

**Comment by bevanjkay** [comment]
Looks like for the time being we are shipping the same version as is available in the app store.
Can we set the deprecation date in the future?

**Comment by krehel** [comment]
Yeah I can bump it out to end of Feb or March.  Not a bad idea.

**Comment by bevanjkay** [comment]
Ok, this is an interesting conflict now.
It needs the livecheck until the deprecation date, I'm not sure if it will start causing tap audits to fail afterward. Probably only if the individual cask is audited?

**Comment by krehel** [comment]
If the app tries to steer the user towards the App Store (as the issue suggested), perhaps best to just deprecate now?  If it's the same version, they may just be running the same version parallel with an expected EOL for the direct download so no users are cut off on legacy without some lead time.  I couldn't find a definitive future date for deprecating this flow.

**Comment by bevanjkay** [comment]
Ok, let's just deprecate now.

**Review by bevanjkay — APPROVED** [review]

**Comment by nhamilakis** [comment]
Sorry for adding to this discussion after it got closed, my question may be ignorant but i am not really familiar with the inner workings of homebrew. 

Is there is no way for homebrew to install an app that is on the app store ? the app store does not have an API or something ? I thought that was why the casks existed.

**Comment by SMillerDev** [comment]
No there is no API, there used to be https://github.com/mas-cli/mas but it never works reliably.

Casks are to "“To install, drag this icon…” no more!" as in the README.md

**Pull request merged**
