### PR TITLE
New casks: DCP-o-matic Playlist Editor, Disk Writer, and Combiner

### PR DESCRIPTION
**Pull request by pthariensflame**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

This completes the DCP-o-matic casks, which already partially exist.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@pthariensflame please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

**Comment by pthariensflame** [comment]
Sure!  Should I do the same for the existing casks from this project?

**Comment by bevanjkay** [comment]
@pthariensflame That would be great, but can you make the additional changes in a separate PR 👍🏻

**Comment by pthariensflame** [comment]
@bevanjkay Should be ready now!  I verified that none of these three leave behind any settings or user data.

**Comment by pthariensflame** [comment]
What needs to happen here?

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
