### PR TITLE
Update lbry from 0.45.2 to 0.46.1

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ran-dall** [comment]
> happy to adapt here to make it easier for you! what "sort of output" are you looking for?

@core-code I've trained to recognize the output of `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/developer/bin/cask-pr-local-check`, which is the offical local `ci` tool we have.

> however, i am not the only one merging PRs and there will always be cases where absolutely fine PRs are going to be closed (other one submitted first, seen first, or having a newer version are just 3 reasons that come to mind immediately). if the ML can't come with these very common situations gracefully, then thats a bug.

Of course, I didn't mean to single you out or give you the impression I was upset or anything. 

Let me explain. 

In the almost two years we've been doing this, Travis and/or GitHub Action has been doing a decent enough job of working with ML. Therefore the ML has been primarily put together on the premise of working with Travis and GitHub Actions. When those broke at a similar time, then the ML start charting into unknown waters. Hence I found that `cask-pr-local-check` tool and I trained our ML to recognize that. 

This is the foundation of my request.

When you merge something that doesn't have a `CI` ticket or an output in the comments, the ML doesn't know why PR was or was not merged. So to correct that, I have to mark it or delete it on my end manually, which can be a major time deterrent and a painful process if there's a lot.

I hope that clears it up.

**Comment by core-code** [comment]
> which is the offical local ci tool we have.

ok thanks. just to clarify, adding the output and then closing the PR is fine?

> Of course, I didn't mean to single you out or give you the impression I was upset or anything.

no problem. sorry if that came off in the wrong way. i just wanted to note that even if i add output to make the ML happy, there are others who merge too. so, ideally the ML should be able to cope with that.

> When you merge something that doesn't have a CI ticket or an output in the comments, the ML doesn't know why PR was or was not merged.
> So to correct that, I have to mark it or delete it on my end manually, which can be a major time deterrent and a painful process if there's a lot.

ok thanks i see.

> Hence I found that cask-pr-local-check tool and I trained our ML to recognize that.

ah that makes sense. ideally we'd have a fast and reliable travis. unfortunately it has never been fast and reliability has been going from bad to "not at all".

on the good news side, travis seems to work somewhat again today.

**Comment by ran-dall** [comment]
> ok thanks. just to clarify, adding the output and then closing the PR is fine?

@core-code Yep, that's works.

> so, ideally the ML should be able to cope with that.

Yeah, in light of recent events, several things came up. I've got some time to start working on those flaws. 

> unfortunately it has never been fast and reliability has been going from bad to "not at all".

I'm working on this too. I recently became familiar with the `CI`s checks we have. There's still definate room for improvement. I'm seeing what I can do.

**Comment by core-code** [comment]
> I'm working on this too. I recently became familiar with the CIs checks we have.
> There's still definate room for improvement. I'm seeing what I can do.

thats great to hear!

**Pull request closed without merging**
