### PR TITLE
Add Blobby Volley 2

### PR DESCRIPTION
**Pull request by swsnr**
It's a nice little arcade game involving jelly bears playing volley ball :)
#### Adding a new cask
- [x] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [ ] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Commit message includes cask’s name.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by lunaryorn** [comment]
I'm not sure about 3) on the checklist: The guidelines say to remove version numbers from the name, but in this case the number is part of the name, i.e. it's Blobby Volley 2 1.0.  There's an older version 1 of the game which isn't even available for Mac.

**Comment by jawshooah** [comment]
> The guidelines say to remove version numbers from the name, but in this case the number is part of the name

That's fine. But it should be `blobby-volley2`, without the third hyphen. Please change the token and rename the file accordingly.

**Comment by lunaryorn** [comment]
@jawshooah Renamed, rebased onto `master` and force-pushed.

**Comment by jawshooah** [comment]
Thanks!

**Comment by lunaryorn** [comment]
❤️ thanks

**Pull request merged**
