### PR TITLE
microsoft-office: update livecheck for individual apps

### PR DESCRIPTION
**Pull request by vladimyr**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

---

Microsoft AutoUpdate uses following feed format:
https://officecdn-microsoft-com.akamaized.net/pr/{{channel-id}}/MacAutoupdate/{{app-id}}-chk.xml
(e.g. https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409XCEL2019-chk.xml)

App IDs were extracted by intercepting MAU network traffic and there is also a separate opensource update checker listing exact same IDs used for verification: https://github.com/pbowden-msft/OfficeCDNCheck/blob/9c33167778d276859b299a0ddec63ded46d12ef4/OfficeCDNCheck#L17-L46

Additional data about particular update is available through following URL format:
https://officecdn-microsoft-com.akamaized.net/pr/{{channel-id}}/MacAutoupdate/{{app-id}}.xml
(e.g. https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409XCEL2019.xml)

I'm fully aware that existing livechecks work but using a stable update feed is better IMO than checking redirects on shortlinks that could change in the future.

### CODE REVIEW

**Comment by miccal** [comment]
> I'm fully aware that existing livechecks work but using a stable update feed is better IMO than checking redirects on shortlinks that could change in the future.

I disagree -- the current `livecheck` blocks are simple in that they use the `url`'s provided from the `homepage`'s, which the ones you have created are much more prone to changing in the future.

I will let other maintainers chime in, though.

**Comment by bevanjkay** [comment]
@miccal I agree that in this instance, using the links from the homepage for livecheck will ensure that we are serving the same version that would be received if installed manually. There is always a chance that the auto-update feed could be subject to staged releases, where I would think the download links would be more likely to be stable.

**Comment by vitorgalvao** [comment]
Agreed with @miccal and @bevanjkay, for the stated reasons. I’ll only add to:

> There is always a chance that the auto-update feed could be subject to staged releases

That this is not rare at all. So while it may be tempting to use the feed and it can be fun to figure out the update check mechanism an app uses (and I suspect @vladimyr might enjoy that process, since they’re always very well researched!), an unversioned URL which redirects to the versioned URL is the most resilient choice.

Thank you anyway, as always.

**Pull request closed without merging**
