### PR TITLE
Revert "pktriot: remove"

### PR DESCRIPTION
**Pull request by miccal**
Reverts Homebrew/homebrew-cask#110497

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why all the deletes and now the reverts?

**Comment by miccal** [comment]
@SMillerDev I accidentally deleted a few that are relatively new and hence do not have much in the way of installs as yet.

Fro example, this particular Cask was only added last month.

**Comment by bevanjkay** [comment]
@miccal Vitor's `cask-analytics` command in vitorgalvao/tiny-scripts gives the cask age

**Comment by miccal** [comment]
> @miccal Vitor's `cask-analytics` command in vitorgalvao/tiny-scripts gives the cask age

Ah, good to know, thanks :)

**Pull request merged**
