### PR TITLE
feat: use brew test-bot for audit

### PR DESCRIPTION
**Pull request by SMillerDev**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

This should get our CI closer to `Homebrew/core`, which means we won't need to keep track of as many CI things on their side.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Should the `setup-homebrew` step have `test-bot: true` instead of waiting until the automatic setup of `homebrew-test-bot` when the command is run? I'm not sure the pros and cons, but I think `homebrew-core` sets it up with the other parts.

**Comment by bevanjkay** [comment]
Any thoughts here @Bo98 ?

**Comment by Bo98** [comment]
Seems like a good idea, but this will break any `skip_readall` logic (which IMO shouldn't exist at all but we should remove it first to be sure).

**Comment by SMillerDev** [comment]
> Seems like a good idea, but this will break any skip_readall logic (which IMO shouldn't exist at all but we should remove that first to be sure).

What logic are you talking about?

**Comment by Bo98** [comment]
https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask%20skip_readall&type=code

**Comment by p-linnane** [comment]
What's the latest here?

**Comment by Bo98** [comment]
CI is still failing

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
