### PR TITLE
Update milanote from 3.1.11 to 3.1.12

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not quite sure what's going on here. My local check comes back with 3.1.12.
```
brew lc --cask --debug milanote

Cask:             milanote
Livecheckable?:   Yes

URL:              https://www.milanote.com/download-desktop-app
Strategy:         PageMatch
Regex:            /href=.*?Milanote[._-]?v?(\d+(?:\.\d+)+)\.dmg/i
URL (final):      https://milanote.com/download-desktop-app

Matched Versions:
3.1.12
milanote: 3.1.11 ==> 3.1.12

**Comment by bevanjkay** [comment]
@p-linnane I'm still seeing version `3.1.11` myself.
But if I grab the electron builder `YML` file it is showing `3.1.12` - https://milanote-app-releases.s3.amazonaws.com/latest-mac.yml

**Comment by bevanjkay** [comment]
@p-linnane I'm not adverse to using the Electron Builder appcast I posted above, as I imagine the in-app updater will utilise that.

**Comment by p-linnane** [comment]
@bevanjkay Works for me. I switched it to `:electron_builder`.

**Review by miccal — APPROVED** [review]

**Comment by p-linnane** [comment]
@bevanjkay A little after the fact but...

> Thanks for your message - this was indeed a bug, so thanks also for reporting it! 🙂 Our development team has updated it, so if you clear your cache you should be able to see our latest release, version 3.2

**Pull request merged**
