### PR TITLE
Add Sound Control 2.1.6.

### PR DESCRIPTION
**Pull request by reitermarkus**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
  Was refused before because it opened a GUI during installation, which it doesn't anymore.
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
We've had a previous PR for this https://github.com/caskroom/homebrew-cask/pull/33959

**Comment by commitay** [comment]
Sorry, didn't see the comment.

**Comment by reitermarkus** [comment]
@commitay, I just added that it doesn't open a GUI anymore.

**Comment by reitermarkus** [comment]
Oh man, that timing … 😂

**Comment by commitay** [comment]
@reitermarkus Can you enable "limit to existing users" in the repo settings please?

**Comment by reitermarkus** [comment]
@commitay Done.

**Comment by commitay** [comment]
Thanks!

**Pull request merged**
