### PR TITLE
Remove scribbleton

### PR DESCRIPTION
**Pull request by gtmgianni**
The server returns an HTTP 500 error whenever `curl` attempts to download the installer for this cask. Is this reproducible for others?

Note: I can download the installer via Safari without any issues, but can't download it via the command-line.

### CODE REVIEW

**Comment by adidalal** [comment]
Confirmed, they're doing some cookie token checking.

**Comment by vitorgalvao** [comment]
Have you tried with any of the [parameters](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#additional-https-url-parameters)?

**Comment by gtmgianni** [comment]
@adidalal @vitorgalvao I'm not sure which of those cookies are not necessary.

**Comment by commitay** [comment]
These cookies are likely of break easily, lets just remove this if upstream wants to make it that hard to download via CLI.

**Comment by commitay** [comment]
Yes, we can do that in ruby using a `url do` block but we aren't going to add it to the Cask.

**Comment by commitay** [comment]
@gtmgianni Can you update the PR to remove the Cask please?

**Comment by commitay** [comment]
Thanks!

**Pull request merged**
