### PR TITLE
Add AttacheCase.app v4.1.9

### PR DESCRIPTION
**Pull request by cohei**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by cohei** [comment]
```
❯ brew audit --cask --online attachecase
==> Downloading https://hibara.org/software/attachecase/download/?f=AtcMac419.zip
Already downloaded: /Users/cohei/Library/Caches/Homebrew/downloads/09f587ea260c693d1ec227a73e4dcfe9def5ba1f8e5a0b240529e1d51f960e14--f=AtcMac419.zip
audit for attachecase: failed
 - Version '4.1.9' differs from '' retrieved by livecheck.
 - Version '4.1.9' differs from '' retrieved by livecheck.
Error: 1 problem in 1 cask detected
```

Though there is no livecheck setting, why audit points this error out?

**Comment by cohei** [comment]
https://docs.brew.sh/Brew-Livecheck

> For casks: Collect the url and homepage URLs, in that order.

I see.

**Comment by p-linnane** [comment]
Thank you for your submission to `homebrew-cask` @cohei. Please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask.

**Comment by cohei** [comment]
I couldn't, but you magically wrote livecheck. Amazing!

I used AppCleaner to find files to zap.

**Review by p-linnane — APPROVED** [review]
Thank you @cohei.

**Comment by cohei** [comment]
Thank you too for your help @p-linnane.

**Pull request merged**
