### PR TITLE
exodus: remove

### PR DESCRIPTION
**Pull request by miccal**
https://github.com/orgs/Homebrew/discussions/4705

None of the links appear to accept `curl` requests, for example:
```
|-> curl -sLI https://www.exodus.com/
HTTP/2 403 
date: Thu, 10 Aug 2023 01:12:14 GMT
content-type: text/html; charset=UTF-8
cross-origin-embedder-policy: require-corp
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-origin
origin-agent-cluster: ?1
permissions-policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
referrer-policy: same-origin
x-frame-options: SAMEORIGIN
cf-mitigated: challenge
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
set-cookie: _cfuvid=DMbeaHJDUdSvbkcKK1Kt2ZM_2MYBTsSFru8GibGBujk-1691629934954-0-604800000; path=/; domain=.exodus.com; HttpOnly; Secure; SameSite=None
server: cloudflare
cf-ray: 7f445e952cce2d53-PER
```

```
|-> brew fetch exodus
Error: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.4-30-g1a8f1be\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://downloads.exodus.com/releases/exodus-macos-arm64-23.7.17.dmg` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 403
HTTP/2 403 
date: Thu, 10 Aug 2023 05:24:13 GMT
content-type: text/html; charset=UTF-8
cross-origin-embedder-policy: require-corp
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-origin
origin-agent-cluster: ?1
permissions-policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
referrer-policy: same-origin
x-frame-options: SAMEORIGIN
cf-mitigated: challenge
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
set-cookie: _cfuvid=mpwBCiHZDpupWW9mETgdAp1TR4OPsOhYPA5p1xtT.dM-1691645053141-0-604800000; path=/; domain=.exodus.com; HttpOnly; Secure; SameSite=None
server: cloudflare
cf-ray: 7f45cfae0e168acd-PER
```
```
==> Analytics
install: 23 (30 days), 162 (90 days), 317 (365 days)
```

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by AlexeyDmitriev** [comment]
Is it possible to tweak curl options instead?

main page downloads with

```
curl 'https://www.exodus.com/' \
  -H 'authority: www.exodus.com' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: en-US,en;q=0.9,ru;q=0.8,el;q=0.7' \
  -H 'cache-control: max-age=0' \
  -H 'cookie: ex_extension_promo_closed=true; __cfruid=50c1d11955ba335905f1cb73cce6e8c0a291aeb2-1691655788; _cfuvid=yYKfBxY99ainxc51QDzPS3LaJz2MSvE759PHcZNv7ns-1691655788106-0-604800000' \
  -H 'if-modified-since: Wed, 09 Aug 2023 23:04:29 GMT' \
  -H 'sec-ch-ua: "Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: none' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36' \
  --compressed
```

**Comment by bevanjkay** [comment]
@AlexeyDmitriev This doesn't work on my end, it looks like it requires the cookies that are set by visiting the site first.

**Review by razvanazamfirei — APPROVED** [review]

**Comment by krehel** [comment]
I was able to successfully `brew fetch` by adding `user_agent: :fake` to the url, otherwise I also get 403.  Doesn't fix `livecheck` though.

**Comment by razvanazamfirei** [comment]
Relevant livecheck issue: https://github.com/Homebrew/brew/issues/15350

**Pull request merged**
