### PR TITLE
v2rayu 4.0.0

### PR DESCRIPTION
**Pull request by i0ntempest**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by i0ntempest** [comment]
I know 4.0 was changed into a prerelease but now we have a checksum mismatch. So either merge this checksum fix or revert the 4.0 upgrade.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
let's update the checksum then.

**Comment by i0ntempest** [comment]
CI failed again, guess you need to manually merge it?

**Review by SMillerDev — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
it should be good now, update to use a different label for CI

**Pull request merged**
