### PR TITLE
Update macx-dvd-ripper-pro from 6.5.3,20200630 to 6.5.3,20200927

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
The `appcast` is out-of-date, and I cannot seem find a better one.

**Comment by suschizu** [comment]
> The `appcast` is out-of-date, but I cannot seem find a better one.

me too … I've removed it - the download contains the new version

**Comment by core-code** [comment]
there are 3 new CGIs that are supposed to help maintaining casks that have a static download (only or in addition to the versioned download):

```
https://macupdater.net/cgi-bin/check_urls/check_url_sizeandmodified.cgi?url=https://www.macxdvd.com/download/macx-dvd-ripper-pro.dmg
https://macupdater.net/cgi-bin/check_urls/check_url_filesize.cgi?url=https://www.macxdvd.com/download/macx-dvd-ripper-pro.dmg
https://macupdater.net/cgi-bin/check_urls/check_url_lastmodified.cgi?url=https://www.macxdvd.com/download/macx-dvd-ripper-pro.dmg

```

**Review by core-code — DISMISSED** [review]

**Comment by miccal** [comment]
@core-code I am not sure what is going on here -- I have tried to fix it, but have been unsuccessful and have reverted what I had done.

**Comment by core-code** [comment]
it somehow seems like the "must_contain" support is broken

**Review by core-code — APPROVED** [review]

**Comment by miccal** [comment]
> EDIT: works now. don't know if it was a fluke or if using empty strings or space doesn't work

@core-code strange that it worked [here](https://github.com/Homebrew/homebrew-cask/pull/90037) though?

Curious.

**Comment by core-code** [comment]
indeed. but having a closer look, that one did have the 'ci-skip-appcast' label.

**Pull request merged**
