### PR TITLE
Add `Cider` version `1.4.3`

### PR DESCRIPTION
**Pull request by a1eaiactaest**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @a1eaiactaest but we cannot accept this in `homebrew-cask` at this stage. Once the developers list Mac builds at https://github.com/ciderapp/cider-releases, please feel free to submit a PR to add this as a Cask.

**Comment by rtgibbons** [comment]
Via https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version - Could we not rename and commit as `cider-beta`?

**Comment by a1eaiactaest** [comment]
I guess then I should create the pull request here: https://github.com/Homebrew/homebrew-cask-versions

**Comment by coredev-uk** [comment]
For anyone who is still interested in this, the macOS builds have been moved to the correct repo. This can be done now.

**Comment by a1eaiactaest** [comment]
Oh that's great. I'll update on it later today.

**Comment by a1eaiactaest** [comment]
Submitted a new pull request with a correct repo. https://github.com/Homebrew/homebrew-cask/pull/129220

**Pull request closed without merging**
