### PR TITLE
Update ithoughtsx from 9.2.0 to 9.3.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — DISMISSED** [review]

**Comment by miccal** [comment]
Neither the `url` nor the SUFeedURL seem to allow `curl` requests:
```
|-> curl -sLI https://cdn.toketaware.com/?download=iThoughtsX.zip
HTTP/1.1 404 Not Found
Date: Sun, 12 Feb 2023 22:47:50 GMT
Server: Apache/2.4.41 (Ubuntu)
Content-Type: text/html; charset=UTF-8
```
```
|-> curl https://cdn.toketaware.com/?download=iThoughtsX.zip
ERROR: support@toketaware.com
```
```
|-> curl -sLI https://cdn.toketaware.com?download=ithoughtsx.xml
HTTP/1.1 404 Not Found
Date: Sun, 12 Feb 2023 22:52:24 GMT
Server: Apache/2.4.41 (Ubuntu)
Content-Type: text/html; charset=UTF-8
```
```
|-> curl https://cdn.toketaware.com?download=ithoughtsx.xml
ERROR: support@toketaware.com
```
May have to remove this Cask.
```
==> Analytics
install: 12 (30 days), 35 (90 days), 125 (365 days)
```

**Comment by p-linnane** [comment]
Opened a PR to remove the cask: https://github.com/Homebrew/homebrew-cask/pull/141281

**Comment by bevanjkay** [comment]
@p-linnane This is an audit issue, not a cask issue. The binary is downloading as expected, it just isn't passing a curl content check error. I can't track it yet, but I'm looking.

**Comment by bevanjkay** [comment]
It looks like one of the audits isn't passing the `referer` argument through causing the failure.

**Review by miccal — APPROVED** [review]

**Pull request merged**
