### PR TITLE
Update to docker v 1.10.1

### PR DESCRIPTION
**Pull request by ogryzek**
Update Cask to Docker version 1.10.1

Docker Update: https://github.com/docker/docker/releases

_Note_: I wasn't sure how to get the appoint checkpoint, so if someone can offer some guidance, that'd be appreciated.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> I wasn't sure how to get the appoint checkpoint

[Docs](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

You can find it with `curl --silent --compressed "{{appcast_url}}" | sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256 | awk '{ print $1 }'`.

Alternatively, you may wish to use [`cask-repair`](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair). It can at once update the cask’s version (according to what you give it) taking care of updating both the cask’s `sha256` and the appcast’s `:checkpoint`, while still giving you the chance to perform other manual fixes.

You can easily install it with `brew install vitorgalvao/tiny-scripts/cask-repair`. `cask-repair --help` will show you some options, but as a whole the script will guide you through the update process.

**Comment by ogryzek** [comment]
Very nice script! Thank you @vitorgalvao :+1:

**Comment by adidalal** [comment]
I think the appcast checkpoint is wrong. Using cask-repair gives me:

```
diff --git a/Casks/dockertoolbox.rb b/Casks/dockertoolbox.rb
index 4e16325..da44c46 100644
--- a/Casks/dockertoolbox.rb
+++ b/Casks/dockertoolbox.rb
@@ -1,10 +1,10 @@
 cask 'dockertoolbox' do
-  version '1.10.0'
-  sha256 '2ea55003578a180405eba37fc8020016a8585c3e9146a05ce0ef4af8656df181'
+  version '1.10.1'
+  sha256 'cc1358d28011b80721bd377c3b8f45e6eeda490a49ace8e23ab0ac263eaaedb8'
 
   url "https://github.com/docker/toolbox/releases/download/v#{version}/DockerToolbox-#{version}.pkg"
   appcast 'https://github.com/docker/toolbox/releases.atom',
-          checkpoint: 'ee50da3b17a6d4097f03b74c21b6142f853f08f2a11e12f3f8e0f1ac738b3e55'
+          checkpoint: '06c615666bc65c9572fc672bf94513db3cbfb1a083d4e7abae461aaf8c8aee79'
```

**Comment by adidalal** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/18787

**Pull request closed without merging**
