### PR TITLE
superduper: Add support for mavericks

### PR DESCRIPTION
**Pull request by Amorymeltzer**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Thank you, but no. That’s too much. We don’t officially support that far back.

We can keep from `mavericks` on, but no earlier. Also, the appcast needs to be outside the conditionals.

**Comment by vitorgalvao** [comment]
> would a PR clarifying that intent in the docs be welcome?

We have a line in the docs somewhere stating we only officially support the current macOS release and one back.

> Regarding the appcast

Since we changed how they operate, outside might make more sense now.

**Comment by Amorymeltzer** [comment]
Done.

> we only officially support the current macOS release and one back.

Indeed; I meant the "We can keep from `mavericks` on, but no earlier" bit.

**Comment by vitorgalvao** [comment]
> I meant the "We can keep from `mavericks` on, but no earlier" bit.

Oh, that’s unofficial. That’s me saying “in this case it doesn’t hurt, and since you’re a trusted maintainer that went to the trouble of adding these and may require older versions, fine by me to bend the rules a bit (but let’s have a cap on how much)”. I don’t shy from doing so once in a while for good contributors.

**Pull request merged**
