### PR TITLE
Add Black Screen screensaver 1.1

### PR DESCRIPTION
**Pull request by simmel**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [x] `sha256` was updated, but `version` remained the same.
      [Post a link to a public confirmation by the developer.][version-checksum]:

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not already refused in [closed issues].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> - [X] `sha256` was updated, but `version` remained the same.
      [Post a link to a public confirmation by the developer.][version-checksum]:

Could you please explain what was unclear, there?

**Comment by simmel** [comment]
>  `sha256` was updated, but `version` remained the same.
>  Post a link to a public confirmation by the developer.:

That could mean so many things.

1. When was `sha256 was updated` supposed to happen?
* When I ran any of the previously mentioned commands?
* When I updated/added it myself, as in this case?
2. Who is the developer?
* Creator of the application?
* The person adding/updating the cask, me in this case?

I never updated the `sha256` in this case, I just added it.
So I shouldn't have clicked that?
Should that be moved to a new headline, like:

> Additionally, *if updating an existing cask*:
> [ ] `sha256` was updated, but `version` remained the same.

That would make it clearer to me, at least.
🤷‍♂️

**Comment by vitorgalvao** [comment]
@simmel Thank you for the feedback. See https://github.com/caskroom/homebrew-cask/pull/33692. Clearer?

**Comment by simmel** [comment]
No problem @vitorgalvao! I added another comment on that PR :)

**Pull request merged**
