### PR TITLE
Update jdownloader from 46267 to 46280

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Upstream appears to be providing mega.nz links for macOS builds.

**Comment by miccal** [comment]
[There is not simple way to use `curl` on mega.nz links, unfortunately.](https://github.com/Homebrew/homebrew-cask/issues/60626#issuecomment-474902654)

We may have no choice but to remove this Cask, as `brew fetch` is currently failing.

Popular Cask, though:
```
==> Analytics
install: 497 (30 days), 1,541 (90 days), 4,385 (365 days)
```

**Comment by p-linnane** [comment]
@miccal I will reach out to upstream and let them know what's going on. Hopefully they can provide a direct link again.

**Comment by p-linnane** [comment]
@miccal Upstream was extremely helpful and has restored the direct link. They are going to start providing arch specific .dmg files, and I will rewrite the cask to accommodate those later this week.

**Review by miccal — APPROVED** [review]

**Pull request merged**
