### PR TITLE
Add wintertime v0.0.2

### PR DESCRIPTION
**Pull request by actuallymentor**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.

The process errored in the setting up of dependencies with `An error occurred while installing psych (3.1.0), and Bundler cannot continue.`.

- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

Edit: checked off appcast

### CODE REVIEW

**Comment by actuallymentor** [comment]
I just realised the docs didn't mean 'you should format github appcasts like this' but rather 'this is where to find your appcast'.

Added a commit to add the appcast.

**Comment by actuallymentor** [comment]
I'm now using the Travis CI to diagnose `brew cask style --fix {{cask_file}}`. It showed stanza order errors, fixed those.

**Comment by ran-dall** [comment]
@actuallymentor Just trying to save you some time here, but this wouldn't qualify to be added into HBC. 
> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is not notable enough (under 50 stars)).

**Reference** 👉 https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md

**Comment by vitorgalvao** [comment]
@ran-dall is correct. Thank you anyway, @actuallymentor.

**Comment by actuallymentor** [comment]
Thanks for the feedback. I'll revisit when the app has some more notoriety.

**Pull request closed without merging**
