### PR TITLE
Update sidplay to 4.2

### PR DESCRIPTION
**Pull request by gtmgianni**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

VirusTotal: https://www.virustotal.com/en-gb/file/11d713325deeceadf0948c239ec353ee3b2346ca9cee47e2c7680113f34ba66e/analysis/1494477913/

### CODE REVIEW

**Comment by giannitm** [comment]
Unsure how to verify this `sha256` change – can't find methods to contact the developer other than by email (which, of course, is not in the public domain, so cannot be verified). 

Any help?

**Comment by vitorgalvao** [comment]
@giannitm In these cases, a maintainer should contact the developer for the verification.

However, you’ve shown yourself to be a trustworthy contributor, so you may do so yourself and report back.

**Comment by giannitm** [comment]
@vitorgalvao I've sent them an email, and will report back when they respond.

Also, how long will the pull requests which need to be verified stay open for? If the developer does not respond within a certain number of days/weeks/months, will the pull requests be closed? We don't want to clutter up the repository with pull requests which are neither merged nor closed.

**Comment by vitorgalvao** [comment]
I’ve thought about that. Eventually (presumably) the apps will get a new version, which kind of solves the problem, but waiting for that is definitely not ideal.

Some of them, since we can see they were correctly signed and there were no reports of wrongdoing by the developers, we can assume to be fine. As for the others, no idea. I’ll have to think a bit on it.

**Comment by commitay** [comment]
> Eventually (presumably) the apps will get a new version, which kind of solves the problem, but waiting for that is definitely not ideal.

I've been thinking about this since the verification policy was implemented.

For casks that can't be verified, could we add a `unverified` `caveat` and say something like `"checksum for #{token} could not be verified, use at your own risk"`? 

Could also change the `malware` caveat as it does not seem to currently be used in a cask.

**Comment by vitorgalvao** [comment]
> For casks that can't be verified, could we add a `unverified` [`caveat`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/dsl/caveats.rb) and say something like `"checksum for #{@cask} could not be verified, use at your own risk"`?

That’s certainly a possibility. Mind opening an issue for the discussion?

**Comment by giannitm** [comment]
VirusTotal: 

https://www.virustotal.com/en-gb/file/11d713325deeceadf0948c239ec353ee3b2346ca9cee47e2c7680113f34ba66e/analysis/1494477913/

**Comment by vitorgalvao** [comment]
image

**Comment by vitorgalvao** [comment]
Untrusted signature; no developer reply. Closing.

**Pull request closed without merging**
