### PR TITLE
readme: update URL for reporting bugs

### PR DESCRIPTION
**Pull request by commitay**
Currently this sends people to the blank template.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
That was on purpose. As in “if my problem isn’t listed, it’s something else”. We don’t get many bug reporters that click on that instead. Even https://github.com/Homebrew/homebrew-cask/issues/49929, who looks like it, asserts they’ve seen the template.

**Comment by commitay** [comment]
If there clicking on this link don't we want a full report anyway?

**Comment by vitorgalvao** [comment]
> If they're clicking on this link don't we want a full report anyway?

But we don’t know what they’re reporting, so we don’t know what to ask. They’re not making a bug report or a feature/cask request, so it’s something else we don’t yet know which info we need.

Also, note [the template is not empty](https://github.com/Homebrew/homebrew-cask/issues/new). It’s just that it’s message is hidden, and it’s discouraging people from not using a template:

> It’s extremely unlikely your issue isn’t covered by one the templates. Please go back and use one of them. If you still decide to open an issue without a template and we deem it was covered by one of them, your issue will be closed without comment or review. Repeat offences might get you banned. Those templates exist to help us help you. When you don’t use them, you’re making our work more difficult. Please respect our time. Thank you for your understanding.

**Comment by commitay** [comment]
> But we don’t know what they’re reporting, so we don’t know what to ask.

What else would they be reporting? The cask URL that is printed with the error points to this section which has various options and then "My problem isn’t listed" which takes them to the "go back and try again" message.

**Comment by vitorgalvao** [comment]
> What else would they be reporting?

Something not related to code. Asking a question about the our policies/documentation or making a suggestion like https://github.com/Homebrew/homebrew-cask/issues/48862.

> takes them to the "go back and try again" message, which doesn't link to the bug report template.

Good point. [Submitted a change](https://github.com/Homebrew/homebrew-cask/pull/49936) to link them back directly from the message and not hide the message.

**Comment by commitay** [comment]
> Something not related to code. Asking a question about the our policies/documentation or making a suggestion like #48862.

The heading for this section is "Reporting bugs"?

**Comment by vitorgalvao** [comment]
> The heading for this section is "Reporting bugs"?

Ignore! I didn’t notice you were changing the README, I thought you were changing the default template.

Yes, this looks good.

**Pull request merged**
