### PR TITLE
Add utterly

### PR DESCRIPTION
**Pull request by thorpelawrence**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by thorpelawrence** [comment]
Despite SNAPSHOT and commitish name, this is the latest 'stable' version, from the website - when downloaded after entering email address (the download doesn't seem to actually need signup)

**Comment by thorpelawrence** [comment]
The uninstall failure, possibly due to it requiring password? - although I'm not sure

**Comment by thorpelawrence** [comment]
I've tried a few different methods, but unable to get the uninstall to work on the CI system unfortunately - maybe I'm missing something

**Comment by vitorgalvao** [comment]
Fill the requested `uninstall launchctl` and `uninstall quit` first, and we’ll deal with the rest after. One step at a time.

**Comment by thorpelawrence** [comment]
Wasn't really sure about adding those since the script does it already, but have done it now

Not sure why the audit fails, as I checked it again before pushing

As for https://github.com/Homebrew/homebrew-cask/runs/2236859081?check_suite_focus=true#step:18:12, not sure there's much I can do about that, as it's running in the CI

**Comment by miccal** [comment]
@thorpelawrence and @vitorgalvao I have mimicked what the `uninstall` script does, and it seems to be fine now.

@thorpelawrence could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

**Comment by thorpelawrence** [comment]
Thanks for the help @miccal, `zap stanza` added

**Comment by miccal** [comment]
Thank you @thorpelawrence.

**Review by miccal — APPROVED** [review]

**Pull request merged**
