### PR TITLE
Update plex from 1.6.5.1097-3bb9dc68 to 1.8.0.1159-67c4a549

### PR DESCRIPTION
**Pull request by mattmoore**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by ran-dall** [comment]
@mattmoore I can't find `1.8.0.1159-67c4a549` anywhere.

**Comment by mattmoore** [comment]
> @mattmoore I can't find `1.8.0.1159-67c4a549` anywhere.

@ran-dall Yeah, this is weird. So here's where I found the new version: https://www.plex.tv/media-server-downloads/#plex-app which has 1.8. I am able to install it on my Mac from their site. However, in the Plex cask I see this line:

```
appcast 'https://plex.tv/api/downloads/6.json'
```

What's bizarre is that curling that endpoint returns 1.6, not the 1.8 version. So now I'm utterly confused.

**Comment by mattmoore** [comment]
> > @mattmoore I can't find `1.8.0.1159-67c4a549` anywhere.
> 
> @ran-dall Yeah, this is weird. So here's where I found the new version: https://www.plex.tv/media-server-downloads/#plex-app which has 1.8. I am able to install it on my Mac from their site. However, in the Plex cask I see this line:
> 
> ```
> appcast 'https://plex.tv/api/downloads/6.json'
> ```
> 
> What's bizarre is that curling that endpoint returns 1.6, not the 1.8 version. So now I'm utterly confused.

@ran-dall I just realized what's happening. I have a paid Plex Pass account, and that has version 1.8. The latest available for free accounts is 1.6. This PR can be closed.

**Comment by ran-dall** [comment]
@mattmoore Thanks man for looking into that. 👏

**Pull request closed without merging**
