### PR TITLE
Add Blender-LTS 2.83

### PR DESCRIPTION
**Pull request by Aiacos**
separated support for blender-LTS

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by miccal** [comment]
How is this different from the [one already available](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/blender.rb)?

**Comment by Aiacos** [comment]
From today blender as started an Long Term Support that have 2 year
maintance instead o 4 month. For now both version are the same, all X.x3
will be an LTS

Il giorno gio 4 giu 2020 alle 23:12 miccal <notifications@github.com> ha
scritto:

**Comment by ran-dall** [comment]
@vitorgalvao I feel this would be a decision better left to you.

**Comment by vitorgalvao** [comment]
`blender` is popular enough to justify it, but this belongs in [homebrew/cask-versions](https://github.com/Homebrew/homebrew-cask-versions).

**Comment by ran-dall** [comment]
@vitorgalvao I suspected as much, but I wanted to ask, is there any guideline I should follow for this type of thing? Or did I do the right thing just leaving / marking it for your review?

**Comment by vitorgalvao** [comment]
> but I wanted to ask, is there any guideline I should follow for this type of thing? Or did I do the right thing just leaving / marking it for your review?

You did the right thing. When in doubt, feel free to ping me.

**Pull request closed without merging**
