### PR TITLE
Update paragon-extfs to 11

### PR DESCRIPTION
**Pull request by tiiiecherle**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256),
      provide public confirmation by the developer: {{link}}

### CODE REVIEW

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/issues/35893#issuecomment-311066674

**Comment by vitorgalvao** [comment]
Damn fine work, @commitay.

Started looking into it but did not notice the `product.zip`. Well done!

**Comment by commitay** [comment]
🎉  Thanks, @vitorgalvao!

Paragon has removed the uninstall script we used previously.

`quit:` kind of works but `KILL` is needed for 2.

The menubar app doesn't disappear until after you click on it, even with `KILL`.

**Comment by tiiiecherle** [comment]
Thank you both for helping me out on updating this. You are doing a really nice job with this project. Keep it up.

**Pull request merged**
