### PR TITLE
Add support for LiteIcon v4.0 on Catalina

### PR DESCRIPTION
**Pull request by LorenzoPane**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
That’s the `else` part. Please update the version there.

**Comment by LorenzoPane** [comment]
If you look at their [website](https://freemacsoft.net/liteicon/), 4.0 is only for Catalina while 3.9 covers High Sierra and Mojave.

**Comment by vitorgalvao** [comment]
Then make it `elsif MacOS.version <= :mojave` and `else`.

**Review by vitorgalvao — APPROVED** [review]

**Comment by vitorgalvao** [comment]
Thank you.

**Pull request merged**
