### PR TITLE
dbeaver-community 23.3.4

### PR DESCRIPTION
**Pull request by kaiwinter**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by bevanjkay — APPROVED** [review]

**Comment by weltonrodrigo** [comment]
@kaiwinter The sha256 sum  for arm is wrong. Or the version was recreated after the formula.

The correct is on the site: https://download.dbeaver.com/community/23.3.4/checksum/dbeaver-ce-23.3.4-macos-aarch64.dmg.sha256:
5438e6e94c70e683858554f51643660c0ade756ef9aa0a8de272aa8995d751b0

formula value:
04d18114b556af2858a018327bc83288a3b60873b25729f9b28c8accc421a4b5

**Comment by kaiwinter** [comment]
Today a "new" 23.3.4 was released. That's why the checksum may be wrong.

**Comment by bevanjkay** [comment]
Yes, this means the release artifact was changed. It is not possible for a PR to be merged if a checksum mismatch was present at the time CI was run.

**Comment by kaiwinter** [comment]
This PR is already merged. Can we use bump-cask-pr again for the same (new) 23.3.4?

**Comment by bevanjkay** [comment]
Yes, but will need to pass `--force`

**Comment by kaiwinter** [comment]
I just did that (https://github.com/Homebrew/homebrew-cask/pull/166112). Thanks @bevanjkay for the advice.

**Pull request merged**
