### PR TITLE
Update ithoughtsx from 5.29.0 to 5.30.0

### PR DESCRIPTION
**Pull request by PythonCoderAS**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
No idea what is going on here:
```
|-> brew fetch ithoughtsx
==> Downloading https://cdn.toketaware.com?download=iThoughtsX.zip
######################################################################## 100.0%
Downloaded to: /Users/miccal/Library/Caches/Homebrew/downloads/881c97c48ad9c0fd6a041c4a298c67cfff17dedf131f32f52b310c9a0c558693--iThoughtsX.zip
SHA256: c5113ec8e77cc442c554db70363ffe8c0f6d78b3b222dbde9bfe8f903204cde6
Warning: No checksum defined for cask 'ithoughtsx', skipping verification.
```

**Comment by PythonCoderAS** [comment]
I think the server was just overloaded or it had a temporary outage, the download is working now.

**Comment by PythonCoderAS** [comment]
> No idea what is going on here:
> 
> ```
> |-> brew fetch ithoughtsx
> ==> Downloading https://cdn.toketaware.com?download=iThoughtsX.zip
> ######################################################################## 100.0%
> Downloaded to: /Users/miccal/Library/Caches/Homebrew/downloads/881c97c48ad9c0fd6a041c4a298c67cfff17dedf131f32f52b310c9a0c558693--iThoughtsX.zip
> SHA256: c5113ec8e77cc442c554db70363ffe8c0f6d78b3b222dbde9bfe8f903204cde6
> Warning: No checksum defined for cask 'ithoughtsx', skipping verification.
> ```

This source is doing referrer-based blocking.

```
> curl 'https://cdn.toketaware.com/?download=iThoughtsX.zip' -H 'Referer: https://www.toketaware.com/'
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
> curl 'https://cdn.toketaware.com/?download=iThoughtsX.zip'
ERROR: support@toketaware.com
```

**Review by miccal — APPROVED** [review]

**Comment by bevanjkay** [comment]
I wonder if the binary url audit is not passing the referer, which is generating the error here during the audit stage, but fetch is successful.

**Pull request merged**
