### PR TITLE
Update docker from 4.7.1 to 4.8.0

### PR DESCRIPTION
**Pull request by ykursadkaya**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by thk-cheng** [comment]
`livecheck` seems to be dead, the rss feed is showing `4.6.1,76265` as the latest version.

**Comment by SMillerDev** [comment]
Is there another place to check the version?

**Comment by ykursadkaya** [comment]
> Is there another place to check the version?

There is a release notes page for Docker for Mac, but I don't know how up to date the page is and I couldn't find a versioned download link.

[https://docs.docker.com/desktop/mac/release-notes/](https://docs.docker.com/desktop/mac/release-notes/)

**Comment by MTCoster** [comment]
> `livecheck` seems to be dead, the rss feed is showing `4.6.1,76265` as the latest version instead of `4.8.0,78933`.

The devs seem to be [having trouble with Sparkle](https://github.com/docker/for-mac/issues/6268), so they've paused the update manifests for now.

**Comment by thk-cheng** [comment]
> > Is there another place to check the version?
> 
> There is a release notes page for Docker for Mac, but I don't know how up to date the page is and I couldn't find a versioned download link.
> 
> https://docs.docker.com/desktop/mac/release-notes/

The page should be up to date, but it seems that the second part of the version (`78933` in this case) is not mentioned anywhere on the page.

I guess one workaround for now would be to
1. base our `livecheck` on the release note `https://docs.docker.com/desktop/mac/release-notes`
2. change the version to just `4.8.0`
3. use the unversioned download url `https://desktop.docker.com/mac/main/#{arch}/Docker.dmg`

The downside is that we probably need to remove the sha256 checksum as the download url is not versioned anymore.

**Comment by bevanjkay** [comment]
We may be able to use the `:extract_plist` strategy on the unversioned download as a stopgap, however, it will be quite heavy as it is a big download, and also a big one to unpack to grab the version. The `:extract_plist` strategy cannot be passed a different url to the `url` stanza so it probably isn't worth going this route.

@thk-cheng Your method may be the best thing to do for now - and we can keep an eye on the appcast and revert when possible.

**Comment by bevanjkay** [comment]
It looks like the issue has been resolved upstream. I'll close this and setup the update in a new PR.

**Pull request closed without merging**
