### PR TITLE
marta file manager 0.4.3

### PR DESCRIPTION
**Pull request by ghost**
dual pane file manager

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

I was not yet sure what to out into the uninstall line, the app itself in the program folder should be sufficient

### CODE REVIEW

**Review by commitay — APPROVED** [review]

**Comment by victorpopkov** [comment]
Thank you for your contribution!

**Comment by monouser7dig** [comment]
thanks for your help!

**Comment by monouser7dig** [comment]
version 0.4.4 with sha256 `de190a17f642a8c483af5565c848f3de9f9cf9aa59136b35db391fd763dcd956` was released but I did not find the recommended way of pushing such an update

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/39894
____
> [Updating a Cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask)
```
# install and setup script - only needed once
brew install vitorgalvao/tiny-scripts/cask-repair
cask-repair --help
```
```
cask-repair -v 0.4.4 marta
```

**Comment by monouser7dig** [comment]
ok thanks I'll try next time

**Pull request merged**
