### PR TITLE
wkhtmltopdf-carbon / password-gorilla

### PR DESCRIPTION
**Pull request by boecko**
NEW: wkhtmltopdf-carbon 0.12.2
password-gorilla 1.5.3.7.2 -> 1.5.3.7.3

### CODE REVIEW

**Comment by ndr-qef** [comment]
Seeing that both vendors use third-party download providers, could you amend the commits to include our standard `# {domain.ext} is the official download host per the vendor homepage` comment above `url`?

**Comment by fanquake** [comment]
@boecko Do you plan on amending/rebasing this?

**Comment by vitorgalvao** [comment]
I’ve been adding the vendor download comment to all the remaining casks. I have a bunch of them queued up and should finish them all today. I’ve already updated `password-gorilla` in one of those, which breaks this submission.

@boecko In the future, please submit separate pull requests for each cask, as more often than not this type of pull request brings problems with one or more of them, and it halts the inclusion of the other ones (like now).

This would make more sense as a conditional in the existing `wkhtmltopdf` cask anyway, since the difference between them is well defined on the website


Closing.

**Comment by boecko** [comment]
sorry ... was offline the last days ..

**Comment by vitorgalvao** [comment]
Don’t worry. The submission at least let us know there was another version of `wkhtmltopdf`, so thank you on that note.

**Pull request closed without merging**
