### PR TITLE
xctu.rb URL Block and Executable Update

### PR DESCRIPTION
**Pull request by onesmallskipforman**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
We prefer not to have `url do` in the main repo. Why is it necessary?

**Comment by onesmallskipforman** [comment]
I mistakenly thought that the version stanza could not support alpha characters, which show up in the part of the url that correlates to XCTU's version (ie '40003027_Y'). The errors I encountered when originally experimenting with the version stanza were actually due to leaving the colon in (ie "version :'1.2.a'" instead of "version '1.2.a'"). I have removed the url do block and implemented versioning support.

**Comment by onesmallskipforman** [comment]
@vitorgalvao The CI/ci (pull_request) check was cancelled. None of the error messages were helpful, as they all said nothing beyond that the process was cancelled. Do you know how to restart the check?

**Comment by onesmallskipforman** [comment]
In the absence of a `url do` block I believe I can make these changes through `cask-repair`, so I am closing this pull request. I apologize for the confusion.

**Pull request closed without merging**
