### PR TITLE
Add Wasabi Wallet.app v1.1.4

### PR DESCRIPTION
**Pull request by zavan**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by zavan** [comment]
Pinging @nopara73 just so he knows about this.

**Comment by nopara73** [comment]
Thanks for the heads up. So. Unless I don't break this: `"https://github.com/zkSNACKs/WalletWasabi/releases/download/v#{version}/Wasabi-#{version}.dmg"` we're good?

However we're going to break that at one point in the future, because I think `.pkg` is a more user friendly way to release a software for OSX, it's just we're creating the `.dmg` on Windows and Linux and that way only `.dmg` can be created, but planning to move our packaging to OSX because apple code signing is not possible on other platforms.

So, while I greatly appreciate your efforts here, I'm afraid this is not future proof :/

**Comment by zavan** [comment]
@nopara73 Correct. Don't worry, It's ok if the way it's downloaded/installed is changed, it's pretty simple to adapt the formula to work with a pkg, I can do it myself once it's changed.

P.S.: Thank you for Wasabi!

**Comment by nopara73** [comment]
Yes, it's not about the difficulty, it's about that these things tend to get forgotten:)

Anyway, I'll write it in my calendar to check back this issue one year from now, just in case.

**Comment by vitorgalvao** [comment]
> because I think `.pkg` is a more user friendly way to release a software for OSX

I disagree. There are times when one doesn’t have a choice, but if your software can be distributed as an `app` and you make it a `pkg`, I’ll instantly question your motives. By converting it to a `pkg`, you’re going to make supporting it as a cask more of a pain.

**Comment by nopara73** [comment]
You think so? I haven't researched the issue so I don't really understand what you are referencing by "questionable motives with pkg" and it being a maintenance issue, but I may very well come to the same conclusion when I try to actually do it.

Could you elaborate on them?

**Comment by vitorgalvao** [comment]
> You think so?

As someone who has been dealing daily with installers for over half a decade in the context of this project, yes. But that experience might also make me an outlier.

> what you are referencing by "questionable motives with pkg"

A package is installed with administrator privileges, meaning it can do anything to the user’s system. So if your app doesn’t *need* elevated permissions, I’ll question why you’re asking for them (and if I see no reason, skip your app altogether).

> and it being a maintenance issue

`pkg` casks are more complex. They always require an `uninstall`, and necessary changes down the line are harder to detect.

**Pull request merged**
