### PR TITLE
docker 4.32.0

### PR DESCRIPTION
**Pull request by joh-klein**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
From the release notes:

> The CLI binary that used to be shipped as com.docker.cli is now shipped simply as docker. This release leaves the CLI binary as com.docker.cli, but it will be removed next release.

**Comment by p-linnane** [comment]
`docker-compose` appears to be missing from this release. We may want to open a bug report upstream.

**Comment by daeho-ro** [comment]
https://github.com/docker/for-mac/issues/7345

**Comment by dannyfallon** [comment]
> `docker-compose` appears to be missing from this release. We may want to open a bug report upstream.

This is intentional. The binary location has changed to `/Applications/Docker.app/Contents/Resources/cli-plugins/docker-compose` so the symlink in the formula needs updating. This was attempted in https://github.com/Homebrew/homebrew-cask/pull/178863 which was closed.

**Comment by SMillerDev** [comment]
> This is intentional. The binary location has changed to /Applications/Docker.app/Contents/Resources/cli-plugins/docker-compose so the symlink in the formula needs updating.

If that was the case upstream would have closed the issue. Instead they are investigating why the binary is gone. I think we should wait for that investigation.

**Comment by dannyfallon** [comment]
> If that was the case upstream would have closed the issue. Instead they are investigating why the binary is gone. I think we should wait for that investigation.

https://github.com/docker/for-mac/issues/7345#issuecomment-2213567663

>there is something wrong in the update process, the symlink should now point to the CLI plugin binary. I'll work with the Stability team to fix this

My read of this is the issue is still open to allow the stability team to fix the upgrade issue which should have changed the  the symlink to the CLI plugin. This view would be supported by the fact that if you install Docker for Mac v4.32.0 yourself without upgrading and enable it to link system binaries this is what you get:

image

```
➜  ~ ls -lha /usr/local/bin | grep docker
lrwxr-xr-x   1 root  wheel    54B  8 Jul 10:54 docker -> /Applications/Docker.app/Contents/Resources/bin/docker
lrwxr-xr-x   1 root  wheel    70B  8 Jul 10:54 docker-compose -> /Applications/Docker.app/Contents/Resources/cli-plugins/docker-compose
lrwxr-xr-x   1 root  wheel    73B  8 Jul 10:54 docker-credential-desktop -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-desktop
lrwxr-xr-x   1 root  wheel    77B  8 Jul 10:54 docker-credential-osxkeychain -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain
lrwxr-xr-x   1 root  wheel    60B  8 Jul 10:54 docker-index -> /Applications/Docker.app/Contents/Resources/bin/docker-index
lrwxr-xr-x   1 root  wheel    55B  8 Jul 10:54 kubectl.docker -> /Applications/Docker.app/Contents/Resources/bin/kubectl
```

I think there's enough information there to suggest you could push 4.32.0 with the correct symlink like Docker intends to use  and to back up that change if they push 4.32.1 that ships the binary to the old location but if you want to wait then sure.

**Comment by p-linnane** [comment]
Docker has added this as a known issue in their README. I'm closing this and we can bump to the next release.

**Comment by marcograss** [comment]
so, will this be bumped or we skip to the next release?

**Comment by p-linnane** [comment]
We're waiting for the next release.

**Pull request closed without merging**
