### PR TITLE
Update dingtalk from 5.1.5.0 to 5.1.33.3

### PR DESCRIPTION
**Pull request by ulinkwo**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
@ulinkwo I see version `5.1.8.3` as the latest one?

@core-code the download link is:
```
https://www.dingtalk.com/mac/d/qd=2020032515364694003?spm=a213l2.14171110.4290834532.7.337b549dfHwXXJ&acm=lb-zebra-631264-8036409.1003.4.7546307&scm=1003.4.lb-zebra-631264-8036409.OTHER_15839668797361_7546307
```
which does not accept `curl` requests:
```
|-> curl -sLI "https://www.dingtalk.com/mac/d/qd=2020032515364694003?spm=a213l2.14171110.4290834532.7.337b549dfHwXXJ&acm=lb-zebra-631264-8036409.1003.4.7546307&scm=1003.4.lb-zebra-631264-8036409.OTHER_15839668797361_7546307"
HTTP/1.1 405 Method Not Allowed
Server: DingTalk/1.0.0
Date: Tue, 27 Oct 2020 22:18:22 GMT
Content-Type: text/html;charset=utf-8
Connection: keep-alive
Allow: GET
Content-Language: en
```
Can you think of a better `appcast` here?

**Comment by core-code** [comment]
ok. i can confirm that the version offered for download (in europe) is 5.1.8.3 (and not 5.1.33.3).

i can also confirm that the appcast (  https://im.dingtalk.com/manifest/appcast_en.xml ) is still in-use by the app and is still set to 5.1.5.0 so this is the newest version you'll get in the app itself.

regarding finding an appcast that will let us track the newer version available on the homepage, i didn't make much progress.

you can do this:

`curl -vvvv   'https://www.dingtalk.com/mac/d/qd=2020032515364694003'   `

and the 'location' will be the download filename and version. this would translate easily enough to our redirect CGI. but the problem is the paramater. i doubt it will stay valid but we can have a look here the next few times.

for the time being i'd say lets stick with the appcast we have and verify PRs manually. this means letting PRs to 5.1.8.3 through but not to 5.1.33.3 (which i also didn't find with a Opera VPN set to 'Asia').

**Comment by core-code** [comment]
> which does not accept curl requests:

i can not confirm this. this curl line definitely downloads it:

`curl -vvvv -L   'https://www.dingtalk.com/mac/d/qd=2020032515364694003' -O `

**Comment by core-code** [comment]
i've sent a PR for 5.1.8.3

Submitted (https://github.com/Homebrew/homebrew-cask/pull/91549)

**Comment by miccal** [comment]
Thank you @ulinkwo.

Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/91549.

**Pull request closed without merging**
