### PR TITLE
Add Proton Drive.app v1.0.1

### PR DESCRIPTION
**Pull request by over-engineer**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
I assume this has a built in updater, due to the presence of Sparkle. 

If this is true can you add the stanza `auto_updates true`

**Comment by over-engineer** [comment]
>I assume this has a built in updater, due to the presence of Sparkle.
>
>If this is true can you add the stanza `auto_updates true`

Yeah, you’re right, @bevanjkay :+1:

I can confirm that Proton Drive _checks_ for updates automatically.

I added the `auto_updates` stanza. Though, I’m not 100% sure that it downloads/installs the app for you (it might just open their download page).

Screenshot 2023-11-23 at 21 19 13@2x

**Comment by bevanjkay** [comment]
@over-engineer We can remove it later if it doesn't, but starting with `true` is safer in this instance.

**Review by bevanjkay — APPROVED** [review]

**Comment by over-engineer** [comment]
Just for future reference, Proton Drive released v1.0.2 and the app auto-updated (i.e. downloaded and installed the new version). So, the `auto_updates` stanza was the right call.

**Pull request merged**
