### PR TITLE
updated black-screen (0.2.13)

### PR DESCRIPTION
**Pull request by nyaaao**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by Numbermaniac** [comment]
```
 - appcast checkpoint mismatch
Expected: 19d2356448a8c75135cd51904b45db8eae17461db42681b1afaff1ae9908d34b
Actual: a6cd8bfa45c9d54e0b5b4c05b9d6eca0e311b8d962a424b4fd0e93e4f4407edf
```
I've got no clue how appcasts work, but looks like this is the error coming from the test build.

**Comment by nyaaao** [comment]
The author seems to be forgetting to bump the release. Since there's 0.2.15 already, is it ok to close this one and resubmit?

**Comment by reitermarkus** [comment]
Yeah, it's strange, the current version is [https://github.com/shockone/black-screen/releases/download/v**0.2.16**/black-screen-**0.2.13**-mac.zip](https://github.com/shockone/black-screen/releases/download/v0.2.16/black-screen-0.2.13-mac.zip).

**Comment by reitermarkus** [comment]
FYI, the author wants to set up a tap: https://github.com/shockone/black-screen/issues/625

**Pull request closed without merging**
