### PR TITLE
Add Outguess.app v 1.1.1

### PR DESCRIPTION
**Pull request by Rbcafe**
#### Adding a new cask
- [x] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Commit message includes cask’s name.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You forgot to add an extension to the file. Also, the template is wrongly filled (I fixed it on the other commit and here).

**Comment by Rbcafe** [comment]
extension corrected

**Comment by Rbcafe** [comment]
what was your modification regarding the template ?

**Comment by vitorgalvao** [comment]
You didn’t run the `brew cask audit --download` command. Travis is finding issues. `version` and `sha256` are wrong.

**Comment by Rbcafe** [comment]
ok got it.

**Comment by Rbcafe** [comment]
audit for outguess: passed

**Comment by Rbcafe** [comment]
Add Outguess.app v1.1.1

**Pull request merged**
