### PR TITLE
dolphin 4.0-9418

### PR DESCRIPTION
**Pull request by Jerzerak**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by adidalal** [comment]
FYI a commit comment like "updated {app_name} to {version}" might be more readable, but it's a minor nitpick

**Comment by Jerzerak** [comment]
@adidalal If you guys wish for the commits to be as such then just ask, I'm just used to my workflow for homebrew-core...I find the shorter commit more readable personally.

**Comment by adidalal** [comment]
Meh, keep it as is - it is indeed readable and concise, not sure what else you could ask for 👍. If another maintainer has a preference they can let you know.

Thanks for the consistent updates, by the way, they're much appreciated!

**Comment by Jerzerak** [comment]
No worries Aditya, it's my pleasure 😁

**Pull request merged**
