### PR TITLE
Add mBlock v 3.3.6

### PR DESCRIPTION
**Pull request by paour**
Program Robots / Arduino without writing a single line of code
## Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:
- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by paour** [comment]
The Travis error is odd:

> ==> Downloading http://download.makeblock.com/mblock/v_3_3_6/mBlock_mac_v3.3.6.z
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The download URL is truncated.

**Comment by fanquake** [comment]
Rebooted the build.

**Comment by paour** [comment]
Odd, there is still the same failure, for one of the two checks…

**Comment by adidalal** [comment]
Manually verified locally

**Pull request merged**
