### PR TITLE
Add Trusteer Rapport :latest

### PR DESCRIPTION
**Pull request by gtmgianni**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please use `x`, not `*`, in the list. Difference:



Also, it’s missing `uninstall`. There are [scripts](https://github.com/caskroom/homebrew-cask/tree/master/developer/bin) and [documentation](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md) geared for that.

**Comment by giannitm** [comment]
Sorry, forgot to mention that. Rapport.dmg is bundled with an uninstaller, however the Rapport program itself does not contain one. Therefore, the uninstaller would need to be retrieved from the original .dmg file. How would one accomplish that?

**Comment by miccal** [comment]
@giannitm I have added the `uninstall pkgutil:` for you, found using the commands listed [here](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#working-with-a-pkg-file-manually).

**Review by vitorgalvao — APPROVED** [review]

**Comment by giannitm** [comment]
You do not need to respond to this (I assume you have more pressing matters to attend to), but I'm curious to know the purpose of "#{staged_path}" in the "executable" section of the uninstall script. Does it refer to the .dmg file originally downloaded?

**Comment by vitorgalvao** [comment]
Every archive (`dmg`, `zip`, whatever) gets downloaded and unpacked to a directory under (by default) `/usr/local/Caskroom/{{cask-name}}`. `staged_path` refers to that.

**Pull request merged**
