### PR TITLE
Add "Yealink Meeting.app" v4.4.14

### PR DESCRIPTION
**Pull request by dz85**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Thank you for your submission to homebrew-cask. Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask.

**Comment by dz85** [comment]
> Thank you for your submission to homebrew-cask. Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask.

But I prefer `uninstall` to `zap`, cos' I need remove these dirs when uninstalling without `--zap`.

**Comment by dz85** [comment]
Thank you for your submission to homebrew-cask. Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask.

But I prefer `uninstall` to `zap`, cos' I need to remove these dirs when uninstalling without --zap.

**Comment by razvanazamfirei** [comment]
`delete`: should only be used as a last resort, if other uninstall methods are insufficient.

Arguments to `uninstall delete` should use the following basic rules:

* Basic tilde expansion is performed on paths, i.e. leading `~` is expanded to the home directory.
* Paths must be absolute.
* Glob expansion is performed using the [standard set of characters](https://en.wikipedia.org/wiki/Glob_(programming)).
* **_To remove user-specific files, use the [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap)._**

Source: [Cask Cookbook](https://docs.brew.sh/Cask-Cookbook)

<details>
<summary>Zap</summary>

`zap` stanzas may remove:

* **Preference files and caches stored within the user’s `~/Library` directory.**
* Shared resources such as application updaters. Since shared resources may be removed, other applications may be affected by `brew uninstall --zap`. Understanding that is the responsibility of the end user.

`zap` stanzas should not remove:

* Files created by the user directly.
</details>

**Comment by miccal** [comment]
Thank you @dz85.

**Review by miccal — APPROVED** [review]

**Pull request merged**
