### PR TITLE
Update setapp from 2.7.14,1607686103 to 2.7.15,1608219081

### PR DESCRIPTION
**Pull request by vitorgalvao**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by AdamTarnoff** [comment]
Thank you, @vitorgalvao ! So that I get this right in the future, can you let me know how to find the digits after the comma for the new version (i.e. 1608219081)?

**Comment by vitorgalvao** [comment]
> So that I get this right in the future, can you let me know how to find the digits after the comma for the new version (i.e. 1608219081)?

Depends entirely on the cask. `version` is a mix of the true version and what we can interpolate in `url`, so looking at both will give you a clue on how to format it.

In this case, I looked at [the contents of the appcast](https://updates.devmate.com/com.setapp.InstallSetapp.xml), which shows this download as the latest: `https://dl.devmate.com/com.setapp.InstallSetapp/2.7.15/1608219081/InstallSetapp-2.7.15.zip`. From there, and looking at the old `version` (`2.7.14,1607686103`), it was easy to deduce the new one would be `2.7.15,1608219081`.

**Comment by AdamTarnoff** [comment]
Understood! I appreciate the tip. I was searching the installer's extended attributes etc, but that was a dead end. Parsing the [appcast](https://updates.devmate.com/com.setapp.InstallSetapp.xml) (w/ [kurtmckee/feedparser](https://github.com/kurtmckee/feedparser)) made it crystal clear. Great to know for next time. Thanks again!

**Comment by vitorgalvao** [comment]
> Parsing the [appcast](https://updates.devmate.com/com.setapp.InstallSetapp.xml) (w/ [kurtmckee/feedparser](https://github.com/kurtmckee/feedparser))

You can open the URL in Chrome, or `curl` it, or download it and `cat`/`less` it.

**Pull request merged**
