### PR TITLE
Fix 1password-cli SHA256 error

### LINKED ISSUE #48144: 1Password-cli SHA256 checksum error
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The checksum of the latest 1password-cli release has changed:

```
Expected: 1f93f2d2dc2c6c69c3b8f5636bab12f3d95da34d9e3ce3cac3ed57143b738028
Actual:   bbef180e0c83040bed0e66577eb2fa08520f1ad9907bb14f8988cc64ad67ee38
File:     /Users/tom/Library/Caches/Homebrew/Cask/1password-cli--0.4.1.zip
```

```
> curl https://cache.agilebits.com/dist/1P/op/pkg/v0.4.1/op_darwin_amd64_v0.4.1.zip | gsha256sum
bbef180e0c83040bed0e66577eb2fa08520f1ad9907bb14f8988cc64ad67ee38
```

#### Command that failed

```
brew cask install 1password-cli
```

#### Output of command with `--force --verbose --debug`

```
==> Creating Cache at /Users/tom/Library/Caches/Homebrew/Cask
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://cache.agilebits.com/dist/1P/op/pkg/v0.4.1/op_darwin_amd64_v0.4.1.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.6.7-4-g9c1a988 (Macintosh; Intel Mac OS X 10.13.5) curl/7.54.0 --fail --silent --location --remote-time --continue-at - --output /Users/tom/Library/Caches/Homebrew/Cask/1password-cli--0.4.1.zip.incomplete https://cache.agilebits.com/dist/1P/op/pkg/v0.4.1/op_darwin_amd64_v0.4.1.zip
==> Downloaded to -> /Users/tom/Library/Caches/Homebrew/Cask/1password-cli--0.4.1.zip
==> Verifying download
==> Determining which verifications to run for Cask 1password-cli
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask 1password-cli
==> Note: running "brew update" may fix sha256 checksum errors

```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.7-4-g9c1a988
Homebrew/homebrew-cask (git revision ab9d0; last commit 2018-06-06)
==> macOS
10.13.5
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 3MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3974 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1162 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/fish"

```

#### Output of `brew tap`

```
codekitchen/dinghy
homebrew/cask
homebrew/cask-fonts
homebrew/core

```

### PR DESCRIPTION
**Pull request by orf**
Closes #48144

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by claui** [comment]
I have reached out to AgileBits a few days ago for the same issue on Linux, and an AgileBits team member [has responded that the change is legitimate.](https://discussions.agilebits.com/discussion/comment/438011/#Comment_438011)

**Review by commitay — APPROVED** [review]

**Review by claui — APPROVED** [review]

**Comment by commitay** [comment]
Checked the gpg signature locally as well.

**Comment by commitay** [comment]
Thanks @claui!

**Pull request merged**
