### PR TITLE
Add DrJava 20190813-220051 (beta)

### PR DESCRIPTION
**Pull request by vladimyr**
This is a continuation of #55213

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by ran-dall** [comment]
@vladimyr Good way of fixing this. This recently got updated, however, I still don't know if it's worth the being added. Do you personally use this?

**Comment by vladimyr** [comment]
No, I don't it is really just an educational tool not something you would use professionally. And that is the primary reason why I proposed it. Serving the academic community is something I enjoy doing. We don't have to include it here, closed PR is also a good thing because those who need it can simply c/p into their personal taps or install using direct URL, it is a win-win situation 😉

**Comment by ran-dall** [comment]
@vladimyr As much as we all like to help (and participate in) the academic communities, I don't know that it makes any difference if it's an educational tool or not. The main concern I have is adding something that later breaks and turns into a burden. This is why it's prefered you only add casks that you personally use.

@vitorgalvao What are your feelings on this cask? Are we still on the position that it's not a good fit for HBC? It's been recently updated and the newest version was downloaded a few thousand times from SourceForge. Maybe we can provisionally merge it? Then if it doesn't get any traction, we can remove it in one of our analytics sweeps?

**Comment by vitorgalvao** [comment]
> closed PR is also a good thing because those who need it can simply c/p into their personal taps or install using direct URL, it is a win-win situation

Thumbs up to that.

> @vitorgalvao What are your feelings on this cask?

Negative, because it’s java-related and those casks are some of the biggest headaches we have. That said, it’s not a development kit, so not that big of a deal.

But it is essentially shim-only, which is uncommon (do we have *any* other cask like that?). Considering the shim technique is itself a bit of a hack (ideally we’d get a proper interface for it), it doesn’t feel appropriate.

And it’s a GUI that we need to call via the CLI? That feels weird and incomplete.

I’m for refusal.

All that said,  you’ve handled https://github.com/Homebrew/homebrew-cask/pull/55213 ([my interaction with that issue](https://github.com/Homebrew/homebrew-cask/pull/55213#issuecomment-445501828) followed your suggestion), so I’ll defer to you, as you’re more familiar with it.

Keep in mind that the analytics sweep—by design—only considers casks that have been present for at least 365 days, and I’m considering changing the removal threshold so that less casks get caught in it.

**Comment by ran-dall** [comment]
> Negative, because it’s java-related and those casks are some of the biggest headaches we have. That said, it’s not a development kit, so not that big of a deal.

Agreed. Java on HBC has been a headache.

> But it is essentially shim-only, which is uncommon (do we have any other cask like that?).

I haven't seen anything like this to date.

> Considering the shim technique is itself a bit of a hack (ideally we’d get a proper interface for it), it doesn’t feel appropriate.

Agreed.

> And it’s a GUI that we need to call via the CLI? That feels weird and incomplete.

This threw me for a loop when I initially encountered it.

> I’m for refusal.

Considering everything that has happened around this cask, Java, and the fact that there aren't any maintainers that use this, we're in agreement for refusal.

> Keep in mind that the analytics sweep—by design—only considers casks that have been present for at least 365 days, and I’m considering changing the removal threshold so that less casks get caught in it.

@vitorgalvao So does this mean removing the 365-day threshold? or what threshold are we talking about?

---

@vladimyr I think we have a consensus to keep this cask out of HBC. However, you can still put this on a personal tap (or I can put it on mine; which I've been working with the ML to auto-maintain); therefore it's still available for the folks that need it in whatever situation they find themselves in.

**Comment by vitorgalvao** [comment]
> So does this mean removing the 365-day threshold? or what threshold are we talking about?

Rereading, I see I should’ve been more specific. I mean the threshold for the minimum number of downloads for removal, so that less casks get removed per sweep.

**Comment by ran-dall** [comment]
@vitorgalvao Thanks for the clarification. If you don't mind me asking, what's the current threshold now and what are we moving to?

**Comment by vitorgalvao** [comment]
> what's the current threshold now and what are we moving to?

We use more than one source for it, so it’s possible (and it does happen, I’ve seen it) that a cask with zero downloads on HBC is not deleted because it has more on the other source.

I’ll send you the exact numbers privately. I don’t want to share them publicly until we settle on something (I still consider these tests), to avoid someone gaming the system.

**Comment by darkmastermindz** [comment]
@ran-dall @vitorgalvao Would be happy to help host / maintain this cask and any other future educational tools for programming you may come across. Dr. Java is popularly used as an educational interactive java development environment in AP CS courses and higher education found in a lot of intro to java textbooks. It's is a standalone portable jar so I don't foresee issues with breakages.

**Comment by ran-dall** [comment]
@darkmastermindz As I stated before, I don't think that this being an education tool really makes a difference as to what gets merged into HBC's main tap. 

That said, I'll go ahead and merge this into my tap, which I'm working to auto-maintain itself with the ML.

**Comment by darkmastermindz** [comment]
@ran-dall Thanks for providing a solution and what I was trying to get at is that education tools / SDKs like these are commonly used and downloaded frequently metrics-wise. Having them available provides exposure to using / contributing to HB / HBC in academic communities.

I understand the refusal @vitorgalvao to move to a cleaner divide between cask and non-cask as a similar concern is listed in: #62715. As far as I can tell, this package is similar to the case with [mars](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mars.rb) which is typically also used as an education tool for learning [MIPS asm language](http://courses.missouristate.edu/KenVollmar/MARS/) which is currently in homebrew-cask.

**Comment by ran-dall** [comment]
@darkmastermindz The problem isn't simply notability. There are other valid concerns which is why it was refused. I think keeping this on my tap is the best option ATM.

**Pull request closed without merging**
