### PR TITLE
Update sencha.rb

### PR DESCRIPTION
**Pull request by rednoah**
Update to Sencha ExtJS 6 and new install4j installer.

### CODE REVIEW

**Comment by adityadalal924** [comment]
Why the change to no_jre version? Also, URL should use #{version} as needed. Please also add an explicit `:sudo` true/false as needed for the script stanzas.

**Comment by rednoah** [comment]
Done.

* with JRE
* :sudo => yes

**Comment by adityadalal924** [comment]
Thank you. Could you please also [squash your commits](https://davidwalsh.name/squash-commits-git) and post another comment here when that's done, and I'll go ahead and merge it. Your commit message can be something like: "updated sencha to 6.0.2.14"

**Comment by rednoah** [comment]
https://github.com/caskroom/homebrew-cask/pull/15374

**Pull request closed without merging**
