### PR TITLE
Update travis.yml to xcode 9.1

### PR DESCRIPTION
**Pull request by commitay**
`xcode8.3` has been updated and is currently the "newest" image.

https://blog.travis-ci.com/2017-10-16-a-new-default-os-x-image-is-coming

### CODE REVIEW

**Comment by vitorgalvao** [comment]
It’s the new default, yes, but why wouldn’t we prefer `9.1`?

**Comment by commitay** [comment]
It's the most recently updated image, it doesn't require downloading the portable ruby bottle.

AFAIK the 9.1 image hasn't been updated for a while and is still based on a beta release of xcode 9.1

**Comment by commitay** [comment]
I'll check the `9.1` image just in case it has been updated recently.

**Review by vitorgalvao — APPROVED** [review]

**Comment by commitay** [comment]
Look like the `9.1` image has been updated recently.

**Pull request merged**
