### PR TITLE
Expand tilde in `uninstall :delete`

### LINKED ISSUE #12864: Allow tilde expansion in `uninstall :delete`
Currently, tilde expansion is only allowed in `zap :delete`. I don't see a need for this restriction, and the consensus in #11530 seems to be that we should get rid of it.

Before I dive into the code though, I'd like to confirm with @caskroom/maintainers that this is the right thing to do.

### PR DESCRIPTION
**Pull request by jawshooah**
Closes #12864

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Docs in #12997. Will also (finally) allow a merge of #11530.

Feel free to merge this one when you want.

**Comment by jawshooah** [comment]
Should we push a new release after this is merged, or should we wait for #12991?

**Comment by vitorgalvao** [comment]
We should likely push a minor release, just so https://github.com/caskroom/homebrew-cask/pull/11530 can be merged (otherwise it would break anyway, if someone tried to install it).

**Comment by jawshooah** [comment]
I'll push a release with this and #11200 later this evening.

**Pull request merged**
