### PR TITLE
Fetch and audit ARM in CI.

### PR DESCRIPTION
**Pull request by reitermarkus**
Depends on https://github.com/Homebrew/brew/pull/15056.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@reitermarkus Should we have a way of notating when a cask is `arm64` and therefore only fetched? A label that is added automatically, just to notate to reviewers that a full audit hasn't taken place?

**Comment by reitermarkus** [comment]
I think we could actually also install for a fake arch, except for `pkg`s and `installer`s.

**Comment by bevanjkay** [comment]
> > just to notate to reviewers that a full audit hasn't taken place
> 
> 
> 
> What should a reviewer then look out for?

When wider changes have been made or new casks added, sometimes maintainers with Arm hardware will test locally before merging.

**Comment by SMillerDev** [comment]
@Bo98 you mentioned before that it would be possible to hook up the ephemeral system to casks. Would there be more to it than just replicating the homebrew/core naming?

**Comment by reitermarkus** [comment]
This should be good to go now.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
