### PR TITLE
Init Yahoo! KeyKey Chinese input method

### PR DESCRIPTION
**Pull request by Yi-Kai**
Extract KeyKey.pkg from YahooKeyKey-OSX-Leopard-1.1.2535.dmg and add Cask yahoo-
keykey.

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars)).

**Comment by Yi-Kai** [comment]
> not being notable enough

hi @vitorgalvao 
Thank for the feedback.  My bad , I should reference this from https://github.com/yahoo/KeyKey (306 :star:) instead of my own repo.  Yahoo! KeyKey Chinese IME is famous, searching 雅虎奇摩輸入法 in Google , it has much more results than searching 中州韻輸入法 (brew cask info squirrel) . Also here is (Chinese) wiki page for it https://zh.wikipedia.org/wiki/Yahoo!%E5%A5%87%E6%91%A9%E8%BC%B8%E5%85%A5%E6%B3%95

Could you reopen this and I can make change to the https://github.com/yahoo/KeyKey ?

Regards,
yikai

> Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):
> 
> > The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars)).

**Comment by vitorgalvao** [comment]
The last commit on that repo is from 2012. To me that screams “unmaintained”. Plus, in all those years it was never submitted to HBC. I stand by the appraisal that this is too obscure. It’s likely you’d be the only user of the cask.

**Comment by Yi-Kai** [comment]
Thank @vitorgalvao 

Let me start with 3rd party way via homebrew tap , and see how's going.

**Pull request closed without merging**
