### PR TITLE
Improve error message suggestions

### PR DESCRIPTION
**Pull request by jawshooah**
- Print error message with suggestions if header parse failed
- Add `brew uninstall --force brew-cask` to error suggestions

Refs #16344

### CODE REVIEW

**Comment by adityadalal924** [comment]
Should prevent some user confusion, which is always nice (through I guess the people with such errors might still be tapped to `phinze` anyways)...

**Comment by jawshooah** [comment]
> I guess the people with such errors might still be tapped to phinze anyways

The funny thing is, since the [phinze repo](https://github.com/phinze/homebrew-cask) just redirects to us now, if you `brew tap phinze/cask` you get the same contents as if you had tapped `caskroom/cask`. With that in mind, you'd think `brew update` would be all that's needed to clean up, but apparently not.

**Comment by jawshooah** [comment]
Added `brew untap phinze/cask` to the suggestions in e429666 just to be safe. It's a bit long, though.

**Comment by adityadalal924** [comment]
It is long - though hopefully seeing such a descriptive error message will help them fix the issue by themselves. How about merging it for the time being, and seeing if that prevents most of the (same) issues being opened up? We can always remove the extra two commands, say, six months down the line.

**Pull request merged**
