### PR TITLE
Update microsoft-office to 16.19.18110915

### PR DESCRIPTION
**Pull request by indrajitr**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

Additional notes:
* The package is now known as *Microsoft Office for Mac*
* `uninstall` key `pkg` should include OneDrive.app and Microsoft_AutoUpdate.app
* `uninstall` key `delete` shouldn't be necessary anymore (`pkg` should suffice)
* `zap` key `trash` is adjusted based on [official uninstallation guide](https://support.office.com/en-us/article/uninstall-office-for-mac-eefa1199-5b58-43af-8a3d-b73dc1a8cae3)

### CODE REVIEW

**Comment by indrajitr** [comment]
Travis error `"string contains null byte"` is prevalent with all office casks and probably unrelated to the actual cask.

See: https://github.com/Homebrew/homebrew-cask/pull/53998#issuecomment-432070447

**Comment by indrajitr** [comment]
@vitorgalvao, thanks for looking into this.

FWIW, the name change is actually based on what the installer's choice XML shows.

```console
~ ❯❯❯ installer -showChoicesXML -pkg ~/Library/Caches/Homebrew/downloads/39a8a38c740be1ccb359bee4281d1b15a0c373f9b30965af2f5cd00f1f3a7db5--Microsoft_Office_16.18.18101400_Installer.pkg > /tmp/offoce-installer.plist && /usr/libexec/PlistBuddy -c Print:0:choiceTitle /tmp/offoce-installer.plist && rm -f /tmp/offoce-installer.plist
Microsoft Office for Mac
```

However, this is a trivial point. I'm fine either way :)

**Comment by indrajitr** [comment]
Updated to 16.19.18110915.

Travis fails because of the usual prevalent issue with Office casks.

**Comment by vitorgalvao** [comment]
There’s no point to having `for Mac` in `name`. HBC only work on macOS (and we have no plans to change that), so everything is “for Mac”.

**Pull request merged**
