### PR TITLE
Update Brave to 0.12.7dev

### PR DESCRIPTION
**Pull request by jikkujose**
- [x] `brew cask audit --download brave` is error-free.
- [x] `brew cask style --fix brave` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by adidalal** [comment]
Also, check out `cask-repair`, it makes Cask updates like this quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md))

**Comment by JikkuJose** [comment]
Thanks @adidalal! I was purposefully distancing from it to understand how exactly the system works. Anyways, thanks for your time & suggestion, appreciate it!

**Comment by adidalal** [comment]
https://gist.github.com/adidalal/9e6dd7630f62ec737685

To do things manually

**Comment by adidalal** [comment]
You don't need to do bundle exec rubocop, that's been replaced by Bree cask style. General process is the same though

**Comment by JikkuJose** [comment]
Cool!

**Pull request merged**
