### PR TITLE
Add sha256 sums for `spotify` casks

### PR DESCRIPTION
**Pull request by ShockwaveNN**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
Oops forgot to remove `sha256 :no_check`

**Comment by SMillerDev** [comment]
The download isn't versioned, this will mean the cask breaks on every update by Spotify. Doesn't seem like a good idea.

**Comment by ShockwaveNN** [comment]
Shouldn't updates like https://github.com/Homebrew/homebrew-cask/pull/137312/files upgrade md5 also?

Or you mean if Spotify team silencly update dmg file - anyone who will try to install it until cask repo is update - will get error?

**Comment by SMillerDev** [comment]
Exactly the latter

**Comment by ShockwaveNN** [comment]
Got that, thanks, understand the problem

Closing this PR

**Comment by ShockwaveNN** [comment]
Or maybe add some comments to `sha256 :no_check` will be a nice idea? So no one stumble on this problem again

**Pull request closed without merging**
