### PR TITLE
Hoppscotch: add cask

### PR DESCRIPTION
**Pull request by sapslaj**
Hoppscotch now has an official desktop version, so this is adding the first release.

Note: `brew audit` complains about the `releases` repository not being notable enough, however the [main repository where all of the development happens](https://github.com/hoppscotch/hoppscotch) has 56.5k stars and 3.9k forks at this time of writing.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free. _See note above_
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by krehel** [comment]
Hi @sapslaj!  Thanks for opening your first PR in Homebrew!

That's a fair comment regarding notability.  I've added a label to skip the check.

**Comment by sapslaj** [comment]
@krehel Thanks!

I hope you don't mind I also went ahead and bumped the version since a new release has already come out since I opened this PR.

**Comment by krehel** [comment]
> I hope you don't mind I also went ahead and bumped the version since a new release has already come out since I opened this PR.

Not at all - thanks for handling it!

**Review by bevanjkay — APPROVED** [review]

**Comment by bevanjkay** [comment]
Thank you @sapslaj 🎉

**Pull request merged**
