### PR TITLE
freecad 0.21.2

### PR DESCRIPTION
**Pull request by ulab**
After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by ulab** [comment]
Does it make sense instead of waiting for the homepage to be updated, to change the livecheck to github_latest?

```
  livecheck do
    url :url
    strategy :github_latest
  end
```

**Comment by p-linnane** [comment]
We can remove the entire livecheck block, which will just use the git tags from GitHub instead. Unless there's some kind of precedent where a GitHub release doesn't mean it's stable and we have to wait for the homepage. Not sure if that's the case though.

**Comment by ulab** [comment]
I see. There are releases marked as pre-release:

https://github.com/FreeCAD/FreeCAD/releases/tag/0.21rc1a

There was another one with only source-code assets that was not though:

https://github.com/FreeCAD/FreeCAD/releases/tag/0.21rc1

So we'll just wait I guess.

**Comment by p-linnane** [comment]
@adrianinsaval @chennes Apologies for the ping, but would you mind weighing in here? We want to ensure we aren't using unstable versions of FreeCAD. We currently check for homepage updates to indicate a stable release, but would using the latest GitHub release work instead?

**Comment by adrianinsaval** [comment]
> but would using the latest GitHub release work instead?

I think yes, we're gonna keep tagging release candidates but I doubt they'll get marked as latest release, if they have any assets attached to them they should be marked as pre-release always. Development releases aren't published there and if they ever are they will be marked as pre-release

**Comment by p-linnane** [comment]
Thank you for the clarification @adrianinsaval!

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
