### PR TITLE
Update renamer from 6.1.0 to 6.1.1

### PR DESCRIPTION
**Pull request by p-linnane**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
@SMillerDev Looks like this is specifying `10.16` as the minimum OS version. I'm hesitant to add that to the cask. Do we have any logic to interpret `10.16 == 11.0`?

**Comment by SMillerDev** [comment]
I'm not sure, but it would be good to notify upstream and specify the minimum as 11 here.

**Comment by p-linnane** [comment]
Email sent to upstream. Will wait for a response.

**Comment by p-linnane** [comment]
No response from upstream yet. Minimum OS set to 11 on the cask.

**Review by miccal — APPROVED** [review]

**Pull request merged**
