### PR TITLE
Update youdaonote from 3.6.3 to 7.0.10

### PR DESCRIPTION
**Pull request by warrentak18**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Why did you close your other PR and open this one? The other was about ready to merge?

**Comment by warrentak18** [comment]
> 


Last PR, I did not name and annotate as the official instructions. So, I closed it, and  open this PR in order by official instruction.  
I will upload it in the daytime tomorrow, Beijing time.

**Comment by warrentak18** [comment]
> Why did you close your other PR and open this one? The other was about ready to merge?

Last PR, I did not name and annotate as the official instructions. So, I closed it, and open this PR in order by official instruction.
I will upload it in the daytime tomorrow.

**Comment by SMillerDev** [comment]
> Last PR, I did not name and annotate as the official instructions. 

What official instructions? AFAIK Homebrew/cask doesn't have any

**Pull request merged**
