### PR TITLE
updated mattermost (1.3.0)

### PR DESCRIPTION
**Pull request by optikfluffel**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You need to actually run the commands, and not just tick the boxes.

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 1a35d32093ee014e4c94bbbc51ca3fc9fa911c4a. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by optikfluffel** [comment]
Thank @vitorgalvao, I used your [tiny-scripts/cask-repair](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair) and it checked them for me without asking or anything xD

**Comment by vitorgalvao** [comment]
Might be a bug I need to fix. I shouldn’t have let you submit. Perhaps your version of homebrew-cask or rubocop-cask is outdated, and not taking this new cop into account. Will run some tests.

**Comment by vitorgalvao** [comment]
Definitely a bug. Fixed in the latest version.

**Pull request closed without merging**
