### PR TITLE
Add Mouse Locator v1.1

### PR DESCRIPTION
**Pull request by NaanProphet**
Created new cask for Mouse Locator tool. Ordinarily requires manual
installation of vendor's app file, but it installs just a preference
pane. Automated install and uninstall instead. Tested on OS X 10.11.1
El Capitan.

### CODE REVIEW

**Comment by SirDap** [comment]
Cancelling pull request, more changes needed

**Comment by adityadalal924** [comment]
FYI you don't need a zap stanza if you use the artifact `prefpane`, an uninstall will remove it for you.
Also, remember you can use string interpolation with double quotes so you don't need to hardcode in the `1.1`

**Comment by SirDap** [comment]
Thanks, will do!

**Comment by jawshooah** [comment]
@SirDap No need to close the pull request. You can make new commits on the same branch and push them up, and we'll see them. Once it's ready, we'll just need you to [squash your commits](https://davidwalsh.name/squash-commits-git) before we merge.

**Pull request closed without merging**
