### PR TITLE
Update and rename prosys-opc-ua-client from 3.2.0-328 to 4.0.2-231

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> Error: It seems the App source '/usr/local/Caskroom/prosys-opc-ua-client/4.0.2-231/prosys-opc-ua-client.app' is not there.

**Comment by suschizu** [comment]
i was wrong - the client still exists  
https://www.prosysopc.com/products/

**Comment by suschizu** [comment]
… but the homepage link redirects to ua-browser: https://downloads.prosysopc.com/opc-ua-client-downloads.php
I'm not sure - what do you think @vitorgalvao, @reitermarkus ?

**Comment by vitorgalvao** [comment]
Client seems to be Windows only. They direct to [this page](https://downloads.prosysopc.com/opc-client-downloads.php) with no macOS downloads. Seems like your original change might be correct.

**Comment by vitorgalvao** [comment]
Missing `uninstaller`. Do they provide any meaningful instructions (or better yet, a script)?

**Pull request merged**
