### PR TITLE
secure URLs in multiple casks #2

### PR DESCRIPTION
**Pull request by vszakats**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by miccal** [comment]
Ping @victorpopkov - I think some of these may be reverting changes already incorporated via your [cask-homepage](https://github.com/victorpopkov/cask-tools/blob/master/doc/cask-homepage.md) script.

**Comment by miccal** [comment]
@vszakats please stop here for now until @victorpopkov responds, thanks.

**Comment by vszakats** [comment]
No more updates in the queue. These were found by a script and manually double-checked where the script didn't detect an exact match. (it's not just homepages, though)

**Comment by miccal** [comment]
Travis is reporting two errors:
```
audit for hbuilder: failed
 - download not possible: Download failed on Cask 'hbuilder' with message: Download failed: https://download.dcloud.net.cn/HBuilder.7.6.0.macosx_64.dmg

 audit for tinymediamanager: warning
 - appcast checkpoint mismatch
Expected: 40c74bcce7552c2dd81cb5d5ba5445e7e376d9ea65f282ce146c234625b30d0b
Actual: 7166d4ca33a343c5dbaf7a4d859b1c7914bb115a018c5642da4e46cabbbaf075
```

**Comment by vszakats** [comment]
Thanks! Strangely `hbuilder` passed and passes repeated tests here (macOS Sierra), it's a relatively large and slow download though. I've reverted it and refreshed the appcast hash in `tinymediamanager`.

**Comment by miccal** [comment]
Thanks @vszakats.

**Comment by vszakats** [comment]
I've removed `freefilesync` from the patch, even though I just wanted to update the homepage, the download fails for its existing `url` and I gave up on fixing it.

**Comment by vitorgalvao** [comment]
@vszakats https://github.com/caskroom/homebrew-cask/pull/29426.

**Comment by vszakats** [comment]
Resubmitted as #29499 #29500 #29501 #29502 #29503 plus a few others. Closing.

**Pull request closed without merging**
