### PR TITLE
Add CinePlay 13.1.0

### PR DESCRIPTION
**Pull request by NaanProphet**
Added cask for CinePlay video editing application by Digital
Rebellion. 15-day trial commerical application.

### CODE REVIEW

**Comment by adidalal** [comment]
pkg files need an uninstall stanza (most often a pkgutil with an id)

**Comment by SirDap** [comment]
Ah, thanks Aditya! i forgot preference panes were automatic, but packages needed the uninstall stanza. Coming right up.

**Comment by adidalal** [comment]
No problem - if you find our docs lacking in any specific areas feel free to open up an issue/PR, we want to make HBC as easy to contribute to as possible!

**Comment by adidalal** [comment]
Thank you for the contribution. It needed some fixes, so they were made in d57163c30c75d4bd27d2befd3f4ec9fb0e285875. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by SirDap** [comment]
Oh, should i have squashed the commits?

**Comment by adidalal** [comment]
When they are fixes, yes generally. `git rebase -i origin/master`, fixup for all commits past first one does the trick.

**Comment by SirDap** [comment]
Gotcha, will do next time!

**Pull request closed without merging**
