### PR TITLE
update wewechat to 1.1.4, update ieasemusic to 1.0.1

### PR DESCRIPTION
**Pull request by trazyn**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
@trazyn Could you rebase this against master please?

**Comment by commitay** [comment]
`cask-repair` may be useful to you for Cask version bumps.

> [Updating a Cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask)
```
# install and setup script - only needed once
brew install vitorgalvao/tiny-scripts/cask-repair
cask-repair --help
```
```
cask-repair -v  1.1.4 wewechat
```

**Comment by trazyn** [comment]
@commitay sorry for my mistake

**Comment by commitay** [comment]
Extra cask now in this PR: 
https://github.com/caskroom/homebrew-cask/pull/39774/files#diff-1b3ebe0ef679f9ce670c6972a7dac512L1

Closing in favour of https://github.com/caskroom/homebrew-cask/pull/39776  and https://github.com/caskroom/homebrew-cask/pull/39777

Please update you Caskroom fork and use a branch when submitting future pull requests. Thanks!

**Comment by trazyn** [comment]
@commitay Thanks for your help

**Pull request closed without merging**
