### PR TITLE
Update firefox to 50.1.0

### PR DESCRIPTION
**Pull request by neutric**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by neutric** [comment]
App cast will be updated once upstream does so.

**Comment by miccal** [comment]
Seems to have been updated:
```
 - appcast checkpoint mismatch
Expected: 2bbba0fc24add1ba7a0c538a195cc5243292ee7cd5ede3d9fb2b49752ae44415
Actual: 9585e7dd7d365afd92f4514fc02f9ca4532ece60d44d04251426ecd1094bd6c5
```

**Comment by colindunn** [comment]
This version doesn't seem to be generally available. Firefox is not showing an update and the 50.0.2 appcast url hasn't changed.

**Comment by neutric** [comment]
Updated!

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
