### PR TITLE
ankermake: rename from ankerslicer

### PR DESCRIPTION
**Pull request by unitof**
Revisit of #145009, now that https://github.com/Homebrew/brew/pull/15176 is in a tagged release.

- Update and rename ankerslicer.rb to ankermake.rb
- ankermake: add to cask_renames.json

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by unitof** [comment]
Potentially of note:

I tried `reinstall` with the previous name installed, and it seems like it tried to migrate twice, or recursively? Only got this error on the first `brew reinstall ankerslicer`, subsequent reinstalls worked.

Not sure if a bug with this cask or with https://github.com/Homebrew/brew/pull/15176, or just a my-end fluke.

```
▶ HOMEBREW_NO_INSTALL_FROM_API=1 brew reinstall ankerslicer
Warning: Cask ankerslicer was renamed to ankermake.
==> Migrating cask ankerslicer to ankermake
==> Downloading https://public-make-moat-us.s3.us-east-2.amazonaws.com/ankermake/slicer/AnkerMake_Installer_Mac_M1.dmg
Already downloaded: /Users/jacob/Library/Caches/Homebrew/downloads/07b5d1a81fa6d146bacf98e038b04089b934e238bb42529f5dcb2c8dd53495da--AnkerMake_Installer_Mac_M1.dmg
Warning: No checksum defined for cask 'ankermake', skipping verification.
==> Migrating cask ankermake to ankermake
Error: cannot copy directory /opt/homebrew/Caskroom/ankermake to itself /opt/homebrew/Caskroom/ankermake/ankermake
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1357:in `copy'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:478:in `block in copy_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1485:in `wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:475:in `copy_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:453:in `block in cp_r'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1558:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1572:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1556:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:452:in `cp_r'
/opt/homebrew/Library/Homebrew/cask/migrator.rb:61:in `migrate'
/opt/homebrew/Library/Homebrew/cask/migrator.rb:33:in `migrate_if_needed'
/opt/homebrew/Library/Homebrew/cask/installer.rb:568:in `load_installed_caskfile!'
/opt/homebrew/Library/Homebrew/cask/installer.rb:399:in `uninstall'
/opt/homebrew/Library/Homebrew/cask/installer.rb:153:in `uninstall_existing_cask'
/opt/homebrew/Library/Homebrew/cask/installer.rb:105:in `install'
/opt/homebrew/Library/Homebrew/cask/reinstall.rb:31:in `block in reinstall_casks'
/opt/homebrew/Library/Homebrew/cask/reinstall.rb:22:in `each'
/opt/homebrew/Library/Homebrew/cask/reinstall.rb:22:in `reinstall_casks'
/opt/homebrew/Library/Homebrew/cmd/reinstall.rb:170:in `reinstall'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by bevanjkay** [comment]
@unitof the cask renames PR was merged after the 4.0.18 release so we will need to wait until 4.0.19

**Comment by unitof** [comment]
Ah, the version-specific URL is injected via JS. Don't have time today to revisit/reverse engineer but anyone else welcome to!

Or could just make unversisioned.

The plist strategy was wrongly reporting back `2.0.0`.

**Comment by p-linnane** [comment]
So the actual `.dmg` is saying the version is `2.0.0`. Is this inaccurate?

**Comment by unitof** [comment]
Yes, that's inaccurate, at least according to their download website. https://www.ankermake.com/software

**Comment by p-linnane** [comment]
This probably warrants asking upstream which is correct.

**Comment by unitof** [comment]
I'm on it.

**Comment by miccal** [comment]
Some observations:

1. There are three download links I can find, namely:
- `https://public-make-moat-us.s3.amazonaws.com/security/PtaR1wXoSj1GXEjC.AnkerMake_V0.9.34_1.dmg`
- `https://public-make-moat-us.s3.us-east-2.amazonaws.com/ankermake/slicer/AnkerMake_Installer_Mac_Intel.dmg`
- `https://public-make-moat-us.s3.us-east-2.amazonaws.com/ankermake/slicer/AnkerMake_Installer_Mac_M1.dmg`
3. All three provide an `app` bundle called `AnkerMake.app`, and all three of them list version `2.0.0` in the `CFBundleVersion` information in their respective `.plist`'s.
4. All three also list MacOS 10.12 in the `LSMinimumSystemVersion` information in their respective `.plist`'s.
5. For all three (including the `https://public-make-moat-us.s3.us-east-2.amazonaws.com/ankermake/slicer/AnkerMake_Installer_Mac_M1.dmg` one), the `AnkerMake.app` bundle ins an Intel--64-bit executable.
6. The `livecheck` will fail, and I have been unable to come up with an alternative.

**Comment by samford** [comment]
> 7\. The `livecheck` will fail, and I have been unable to come up with an alternative.

I looked into this and the https://www.ankermake.com/software page includes an old version in the HTML and it gets replaced with the current version on load using JavaScript. The version information appears to come from https://make-app.ankermake.com/v3/pc/ota/offcial_get_pc_version but they encode and/or encrypt the data for some reason.

You can find the related JavaScript logic that works with the data in https://www.ankermake.com/_next/static/chunks/8768.473d54e30cba27a0.js, if anyone wants to dig into it.

**Comment by miccal** [comment]
Thanks for looking into this @samford.

**Review by miccal — APPROVED** [review]

**Pull request merged**
