### PR TITLE
Enable auto-merge for approved version bump pull requests.

### PR DESCRIPTION
**Pull request by reitermarkus**
When a version bump PR is approved, automatically enable auto-merge.

### CODE REVIEW

**Review by miccal — DISMISSED** [review]

**Comment by reitermarkus** [comment]
Ah, `pull_request_review` runs on the PR branch so doesn't have access to secrets.

**Review by reitermarkus — COMMENTED** [review]
Test review.

**Comment by reitermarkus** [comment]
New approach: `pull_request_review` triggers the workflow again as `workflow_dispatch` with required inputs.

**Review by miccal — DISMISSED** [review]

**Comment by reitermarkus** [comment]
Since `pull_request_review` has no access to secrets, it also cannot trigger a `workflow_dispatch` event.

**Comment by reitermarkus** [comment]
Okay, I think this should work now:

1. `automerge` (`pull_request_review`) uploads `event.json` artifact.
2. `automerge-review` (`workflow_run`) is triggered once `automerge` (`pull_request_review`) completes:
   1. `event.json` is downloaded.
   2. Pull request number and review ID are extracted.
   3. `automerge` (`workflow_dispatch`) is triggered with this pull request number and review ID.

**Review by miccal — APPROVED** [review]

**Comment by yurikoles** [comment]
Now I get emails from GitHub with topic: `[Homebrew/homebrew-cask] Run failed at startup: Enable auto-merge for review - master (90e6bc9)` and I see the following in GHA output:
```
[Error: .github#L1](https://github.com/Homebrew/homebrew-cask/commit/90e6bc9b72866091d2cf5a0744c36cf5754bc632#annotation_10120267655)
benc-uk/workflow-dispatch@798e70c97009500150087d30d9f11c5444830385 is not allowed to be used in Homebrew/homebrew-cask. Actions in this workflow must be: within a repository owned by Homebrew, created by GitHub, or matching the following: Vampire/setup-wsl@*, codecov/codecov-action@*, google-github-actions/setup-gcloud@*, peter-evans/*, reitermarkus/*, ruby/setup-ruby@*, dessant/lock-threads@*, google-github-actions/auth@*, google-github-actions/get-gke-credentials@*, algolia/algoliasearch-crawler-github-actions@*.
```

It just happened for PR #144000, in GHA run [4557188803](https://github.com/Homebrew/homebrew-cask/actions/runs/4557188803).

**Comment by reitermarkus** [comment]
@yurikoles, that workflow will be disabled again in https://github.com/Homebrew/homebrew-cask/pull/143999.

**Pull request merged**
