### PR TITLE
Update psychopy to 3.0.0b13

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
i think we should wait with upgrading to 3.0 until it is out-of-beta as per our guidelines.

**Comment by vitorgalvao** [comment]
@core-code You’re right. I was distracted by the Github feed. It shows previous betas as pre-releases and this one as a latest release, so it seemed like they were suggesting this one as the one to upgrade to, but the main website still mentions the old version.

**Comment by core-code** [comment]
i agree that the github feed labeling is confusing ... still think we should downgrade until it is out of beta. i can send a PR

**Comment by vitorgalvao** [comment]
Just downgraded. For some reason the Github website was erroring out when creating a branch for it, so I committed directly.

**Comment by core-code** [comment]
ok thanks ;)

**Pull request merged**
