### PR TITLE
Revert "MetaGrowler 0.5.2 extensible monitor using Growl for OSX"

### PR DESCRIPTION
**Pull request by jawshooah**
Reverts caskroom/homebrew-cask#26791

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Nice work 👍

**Comment by pirate** [comment]
Why was this reverted?  MetaGrowler is still [available via mirrors](http://en.freedownloadmanager.org/Mac-OS/MetaGrowler-FREE.html), and is functional Mac versions below macOS Sierra.

**Comment by miccal** [comment]
This was reverted because it was merged incorrectly - nothing to do with the Cask itself.

**Comment by pirate** [comment]
Thanks @miccal, I was mistakenly searching for `meta-growler` instead of `metagrowler` and didn't see that Cask.

**Pull request closed without merging**
