### PR TITLE
Autocompile Ghidra decompiler on AppleSilicon

### PR DESCRIPTION
**Pull request by TheZ3ro**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

(`brew style` report an offense about `on_arm` stanza being out of order, but for developer sanity I think it's better the current position instead of the one suggested by `brew style`)

----

**Pull Request Rationale**

Installing the Ghidra Cask on M1/M2/AppleSilicon devices ends up in a Gatekeeper error because the following binary[1] file is not codesigned.
This PR adds a new `on_arm`/`postflight` stanza that will compile locally the binary file using gradle from brew itself.
In this way the compiled binary file will not trigger the Gatekeeper error when the application is started.
More info is available at the following link: https://lachy.io/articles/properly-installing-ghidra-on-an-m1-mac

- [1] `/opt/homebrew/Caskroom/ghidra/10.3.3-20230829/ghidra_10.3.3_PUBLIC/Ghidra/Features/Decompiler/os/mac_arm_64/decompile`

### CODE REVIEW

**Comment by SMillerDev** [comment]
Or just ask upstream to properly sign the binaries

**Comment by TheZ3ro** [comment]
@SMillerDev yeah, unfortunately it's not that easy. The NSA should get a Gatekeeper key from Apple to sign binaries 😄 .

I remember an old discussion on a different PR/issue about adding Ghidra as a Cask instead of a formula 'cause originally the decompiler source code was not available. Now the source code is available but Ghidra is distributed as Cask so this is a "workaround".

Anyway if you plan to consider this PR, what should I do about the `brew style` matter? Should I put the `on_arm` block at the start as suggested even though it will be a weird ordering?

**Comment by SMillerDev** [comment]
We won't ever merge a PR with failing CI so you should definitely do what CI says. I don't think the cask should accommodate for upstream's lack of signing though.

**Review by razvanazamfirei — CHANGES_REQUESTED** [review]
Thank you for opening this! The implementation of this looks great and it's not unreasonable to do this. However, I am against merging this PR.

I am not a fan of compiling the binaries; even more so given the origin of the software. People can use the `--no-quarantine` flag in this situation. I don't believe we have a precedent for this; rather, we no longer accept new casks that do not meet the codesigning requirement. In casks, we are not trying to circumvent Gatekeeper by signing our own binaries.

I'm not opposed to putting the instructions in a caveat block though.

**Comment by TheZ3ro** [comment]
@razvanazamfirei Thanks for the feedback!

I was searching for Ghidra-related issues and apparently in 2019 Ghidra was not fully open source so it was originally added to brew as a Cask https://github.com/Homebrew/homebrew-core/pull/37656#issuecomment-471592113.
Later Ghidra full [source code was released](https://github.com/NationalSecurityAgency/ghidra/wiki/Frequently-asked-questions#where-is-the-complete-ghidra-source-code) but it was kept as a Cask https://github.com/Homebrew/homebrew-cask/issues/142048#issuecomment-1447424620 (with the pre-built quarantined decompiler binary).

I can make a PR to `homebrew-core` to add Ghidra as a formula and close this one if you think it's better.
Happy to accept more feedback on this.

**Comment by miccal** [comment]
> I can make a PR to `homebrew-core` to add Ghidra as a formula and close this one if you think it's better. Happy to accept more feedback on this.

Please do this @TheZ3ro, thank you. A Formula is always preferable to a Cask if possible.

**Comment by krehel** [comment]
Closing this PR.  I think it is agreed this should not be in Cask.  Formula for this and acceptability can be determined within homebrew-core.

**Pull request closed without merging**
