### PR TITLE
Use non-cask commands where possible.

### PR DESCRIPTION
**Pull request by reitermarkus**
Only `brew cask zap` and `brew cask audit` to go now.

### CODE REVIEW

**Comment by miccal** [comment]
@reitermarkus I have found that the `--cask` flag in `brew uninstall --cask {cask_name}` to be a little flaky for those (rare) cases where there is a Formula and a Cask that share the same name -- it might be easier to use `brew uninstall homebrew/cask/{cask_name}` for a Cask, and just keep using `brew uninstall` for Formula.

Just a thought ... :)

**Comment by reitermarkus** [comment]
>  a little flaky

What exactly does that mean? Specifying the `--cask` flag should definitely not be flaky.

**Comment by reitermarkus** [comment]
Ah, `brew uninstall` doesn't even support the `--cask` flag, that's why …

**Comment by miccal** [comment]
> What exactly does that mean? Specifying the `--cask` flag should definitely not be flaky.

Oh sorry, i meant with `brew install`, not `brew uninstall`.

I recently did a clean install of Big Sur and while installing the Casks `gitup` and `transmission` (which each share names with a Formula) I noticed that the `--cask` flag did not work for one of them for some reason.

I was installing many things via a single command, and hence could not isolate and further investigate why it did not work for one of them.

**Comment by vitorgalvao** [comment]
> Only `brew cask zap` and `brew cask audit` to go now.

`brew cask cat` and `brew cask _stanza` still only work with `cask`.

**Comment by reitermarkus** [comment]
I meant this in terms of the CI workflow.

**Comment by reitermarkus** [comment]
Also `fetch` is still missing.

**Comment by miccal** [comment]
And `create` and `edit`.

**Pull request merged**
