### PR TITLE
Add ArgoUML.app v0.34

### PR DESCRIPTION
**Pull request by williamboman**
Depends on Java SE 6, not sure how to set up that dependency.

### CODE REVIEW

**Comment by adityadalal924** [comment]
You can use `depends_on :java`, but it's [just a stub right now](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#all-depends_on-keys)

**Comment by williamboman** [comment]
@adityadalal924 It's Java 6 though. Would `depends_on :java6` work?

**Comment by adityadalal924** [comment]
I'm pretty sure any line you write doesn't have an impact, at this point (there's no backend code to enforce it) - probably best to just not add anything

**Comment by williamboman** [comment]
Isn't there a specification for it though?

**Comment by vitorgalvao** [comment]
> Isn't there a specification for it though?

Yes, sort of. Not officially. Until we get java dependencies working (likely not soon), you should add a caveat:

````ruby
caveats <<-EOS.undent
  #{token} requires Java 6 like any other IntelliJ-based IDE.
  You can install it with

    brew cask install caskroom/homebrew-versions/java6
EOS
```

**Comment by williamboman** [comment]
@vitorgalvao Alright, updated.

**Pull request merged**
