### PR TITLE
Add Bitrix24 latest

### PR DESCRIPTION
**Pull request by mxl**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install bitrix24` worked successfully.
- [x] `brew cask uninstall bitrix24` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]

**Comment by victorpopkov** [comment]
There is an appcast (Sparkle) available for this app so it can be versioned:

```ruby
cask 'bitrix24' do
  # note: "24" is not a version number, but an intrinsic part of the product name
  version '4.1.8'
  sha256 'fd19cc9d38fedef863693789d6501f419fb3f34eb4214ff62018055f3813a1d2'

  url 'http://dl.bitrix24.com/b24/bitrix24_desktop.dmg'
  appcast 'https://www.bitrix24.com/osx_version.php',
          checkpoint: '63ff4e4da47cd42393b7f181c7498f8062b8fd8213a1ffcd721472ea0713be0a'
  name 'Bitrix24'
  homepage 'https://www.bitrix24.com/apps/mobile-and-desktop-apps.php#desktop_app'

  app 'Bitrix24.app'
end
```

**Review by victorpopkov — CHANGES_REQUESTED** [review]
There is an appcast (Sparkle) available for this app so it can be versioned:

```ruby
cask 'bitrix24' do
  # note: "24" is not a version number, but an intrinsic part of the product name
  version '4.1.8'
  sha256 'fd19cc9d38fedef863693789d6501f419fb3f34eb4214ff62018055f3813a1d2'

  url 'http://dl.bitrix24.com/b24/bitrix24_desktop.dmg'
  appcast 'https://www.bitrix24.com/osx_version.php',
          checkpoint: '63ff4e4da47cd42393b7f181c7498f8062b8fd8213a1ffcd721472ea0713be0a'
  name 'Bitrix24'
  homepage 'https://www.bitrix24.com/apps/mobile-and-desktop-apps.php#desktop_app'

  app 'Bitrix24.app'
end
```

**Comment by mxl** [comment]
@victorpopkov Done! 👍

**Comment by victorpopkov** [comment]
Thank you for all the changes and your contribution!

**Review by victorpopkov — APPROVED** [review]

**Pull request merged**
