### PR TITLE
Add superProductivity.app v1.9.1

### PR DESCRIPTION
**Pull request by LouisStAmour**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Review by commitay — APPROVED** [review]

**Comment by johannesjo** [comment]
Hello there! Developer of super productivity here. I'm new to cask and deploying for home brew, so please forgive me if I'm asking something stupid. I was wondering if there is anything I need to do on my end for making the app available? Also: What's the recommended approach to keeping the reference up to date?

**Comment by LouisStAmour** [comment]
I’m not part of the project, but “Updating a Cask” here is one place to start: https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md

**Comment by vitorgalvao** [comment]
@johannesjo See [updating-a-cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask) for how to set up `cask-repair`. After that you need only `cask-repair --cask-version {{new_version}} --blind-submit superproductivity` and everything will be taken care of automatically, including submitting a PR to us.

**Comment by johannesjo** [comment]
Great! Thank you two very much. I will look into it! Sorry didn't see the link while skimming the README.md and google didn't give me anything useful neither :)

**Comment by johannesjo** [comment]
Is there by any chance a guide, how to set this up with travis? I'm running into the issue, that the hub is not configured:
```
`hub` is not configured.
To do it, run `cd $(brew --repository) && hub issue`. Your Github password will be required, but is never stored.
```

**Comment by johannesjo** [comment]
Sorry to bother you again. But I encountered two issues. First I get the error `No such cask was found in any official repo (superproductivity).`. Am I assuming correctly that is because it ain't registered yet in the official channels?

The other thing I'm wondering is, if there is a more convenient way to provide the auth token. I'm already using an Auth Token as an environment variable. Is it possible to provide the settings via those?

**Comment by vitorgalvao** [comment]
> Am I assuming correctly that is because it ain't registered yet in the official channels?

It might be that the CI hasn’t yet picked it. Do `brew update` beforehand.

> a more convenient way to provide the auth token.

If you already have a ready auth token, you may have your script write it to the `hub` config file. `hub` is the biggest source of errors in that script, so I’ve thought about ditching it altogether and invoking the API directly, but haven’t gotten around to it and *frankly can’t promise I ever will*. That script has evolved to way more than what bash is comfortably capable of, so while I still do bug fixes and implement small features, big ones like that will likely only be implemented with a full rewrite, which I find hard to justify in terms of commitment.

**Comment by johannesjo** [comment]
Thanks for your help and the honesty. I totally understand! 

I'll give generating the hub config dynamically a go.

**Comment by johannesjo** [comment]
I decided to do this via file encryption as creating the file dynamically might have opened up some security vulnerabilities. 
I'm still running into the issue that the cask is not available, even after `brew update`
https://api.travis-ci.org/v3/job/354709372/log.txt
```
[0K$ if [ "$TRAVIS_OS_NAME" == "osx" ]; then

     brew update

     openssl aes-256-cbc -K $encrypted_c04542ca1075_key -iv $encrypted_c04542ca1075_iv -in build/hub.enc -out ~/.config/hub -d

     cask-repair --cask-version $TRAVIS_TAG --blind-submit superproductivity

    fi

    

Already up-to-date.

[33m`caskroom/versions` not tapped. Tappingâ€¦(B[m

==> Tapping caskroom/versions

Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions'...

Tapped 0 formulae (212 files, 296.3KB)

[33m`caskroom/fonts` not tapped. Tappingâ€¦(B[m

==> Tapping caskroom/fonts

Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts'...

Tapped 0 formulae (1,199 files, 1MB)

[33m`caskroom/eid` not tapped. Tappingâ€¦(B[m

==> Tapping caskroom/eid

Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid'...

Tapped 0 formulae (76 files, 56.8KB)

[33m`caskroom/drivers` not tapped. Tappingâ€¦(B[m

==> Tapping caskroom/drivers

Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers'...

Tapped 0 formulae (184 files, 217.2KB)

Updating tapsâ€¦ Already up-to-date.

[31mNo such cask was found in any official repo (superproductivity).(B[m

```

**Comment by commitay** [comment]
I don't know why but `superproductivity` does not exist in the repo.

I've opened another PR https://github.com/caskroom/homebrew-cask/pull/44937

**Comment by johannesjo** [comment]
Thanks! Now I got a new error:
```
$ if [ "$TRAVIS_OS_NAME" == "osx" ]; then
     brew update
     openssl aes-256-cbc -K $encrypted_c04542ca1075_key -iv $encrypted_c04542ca1075_iv -in build/hub.enc -out ~/.config/hub -d
     cask-repair --cask-version $TRAVIS_TAG --blind-submit superproductivity
    fi
    
Already up-to-date.
`caskroom/versions` not tapped. Tapping…
==> Tapping caskroom/versions
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions'...
Tapped 0 formulae (212 files, 296.3KB)
`caskroom/fonts` not tapped. Tapping…
==> Tapping caskroom/fonts
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts'...
Tapped 0 formulae (1,199 files, 1MB)
`caskroom/eid` not tapped. Tapping…
==> Tapping caskroom/eid
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-eid'...
Tapped 0 formulae (76 files, 56.8KB)
`caskroom/drivers` not tapped. Tapping…
==> Tapping caskroom/drivers
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers'...
Tapped 0 formulae (184 files, 217.2KB)
Updating taps… Already up-to-date.
A `[secure]` remote does not exist. Creating it now…
Updating [secure]
From https://github.com/caskroom/homebrew-cask
 * [new branch]          master     -> [secure]/master
new remote: [secure]
--------------------------------------------------------------------------------
cask 'superproductivity' do
  version '1.9.1'
  sha256 'a286fba6e7ca75bc9a8a6f7d9da29e3c3567826c29631f11eee360f6c20f1c6d'
  # github.com/[secure]/super-productivity was verified as official when first introduced to the cask
  url "https://github.com/[secure]/super-productivity/releases/download/v#{version}/superProductivity-#{version}-mac.zip"
  appcast 'https://github.com/[secure]/super-productivity/releases.atom',
          checkpoint: 'bb1c72a2875efdaeffd4907e84be0740272719b2f5ec4b79e2f6097009e20e76'
  name 'Super Productivity'
  homepage 'https://super-productivity.com/'
  app 'superProductivity.app'
end
--------------------------------------------------------------------------------
==> Downloading external files for Cask superproductivity
==> Downloading https://github.com/[secure]/super-productivity/releases/download/v--blind-submit/superProductivity---blind-submit-mac.zip
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'superproductivity' with message: Download failed: https://github.com/[secure]/super-productivity/releases/download/v--blind-submit/superProductivity---blind-submit-mac.zip
There was an error fetching ./superproductivity.rb. Please check your connection and try again.
```

**Comment by johannesjo** [comment]
Oh. Just figured that it might be because of travis tag. I'll try again with a fixed value and then report back.

**Comment by vitorgalvao** [comment]
> Just figured that it might be because of travis tag.

That is likely. The log suggests `cask-repair` is trying to make “--blind-submit” the version number, which would happen if `$TRAVIS_TAG` is empty.

**Comment by johannesjo** [comment]
Still unable to figure this out :(

Now I got problems with the access to github.
I tried updating the token and the config file but there still seem to be permission issues:
```
--------------------------------------------------------------------------------
Submitting…
There were errors while pushing:
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Please fix the errors and try again. If the issue persists, open a bug report on the repo for this script (https://github.com/vitorgalvao/tiny-scripts).
```

**Comment by neverfox** [comment]
Sorry if this is the wrong place to bring this up, but why I'm going so will be clear below. I want to submit a PR for an out-of-date cask and installed cask-repair and did the `hub issue` step and successfully auto-submitted a PR for the cask in question. However, since then, every time I run a `brew install` (which in turn runs update), I'm getting an error mentioning this PR:

```
Updating Homebrew...
error: Failed to merge in the changes.
Patch failed at 0001 Add superProductivity.app v1.9.1 (#44824)
The copy of the patch that failed is found in: .git/rebase-apply/patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

To restore the stashed changes to /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask run:
  'cd /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask && git stash pop'
```
I don't know if this was the result of my using brew-repair or if the timing was just a coincidence. I aborted the rebase in `/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask`, but it just happens again the next time. Does anyone know why this is happening and how I can stop it? Or is this really reflecting a universal issue in the homebrew-cask tap that will eventually clear up?

**Comment by johannesjo** [comment]
@vitorgalvao Are the problems maybe related to that the original PR was submitted by someone else or does that not matter at all?

**Pull request merged**
