### PR TITLE
Update firefox from 81.0.2 to 82.0

### PR DESCRIPTION
**Pull request by robertleeblairjr**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
@robertleeblairjr you will need to update the `sha256` for _all_ the language versions, not just the `en-US` one.

[This script may help.](https://github.com/Homebrew/homebrew-cask/blob/master/developer/bin/update_multilangual_casks)

**Comment by robertleeblairjr** [comment]
> @robertleeblairjr you will need to update the `sha256` for _all_ the language versions, not just the `en-US` one.
> 
> [This script may help.](https://github.com/Homebrew/homebrew-cask/blob/master/developer/bin/update_multilangual_casks)

Thanks. But, how will this help now that the PR has been submitted? I can close it and then attempt to use for a new PR from my branch. Is the script not called when using 'bump-cask-pr' for multi-language cask PRs to update version?

**Comment by robertleeblairjr** [comment]
It seems the update_multilingual_cask script isn't called when using 'brew-cask-pr' or 'cask-repair' for firefox or other multiple language casks. Anyone know how this script actually gets called? Do you supply it as an argument when calling 'brew-cask-pr'?

**Comment by robertleeblairjr** [comment]
@miccal If you wouldn't mind giving me an idea about how to use the script with 'brew bump-cask-pr', then I'd appreciate it. Would it be easier for me to just close this one, open another, or just allow someone who's used this script before to open one?

**Comment by robertleeblairjr** [comment]
@vitorgalvao Maybe you could help me out with this. Is the 'update_multilangual_cask' script called by or an argument for 'bump-cask-pr' when submitting a PR for multiple language casks? Will it be implemented automatically later on for these?

I noticed that there have been changes with adding the --cask switch and transitioning some previous separate cask sub-commands. Will your scripts for 'cask-repair' and so on be moved to the homebrew-cask tap? Just wondering if your tap for the tiny-scripts will eventually become merged with homebrew-cask and it would become redundant.

**Comment by vitorgalvao** [comment]
You call `update_multilangual_cask` by itself. Run it with `--help` to see how.

Though I was under the impression `brew bump-cask-pr` also updated multiple languages.

As for the differences between `cask-repair` and `bump-cask-pr`, the former is an old bash script and the latter is a ruby version integrated into `brew`. Use whichever you prefer.

**Comment by robertleeblairjr** [comment]
> You call `update_multilangual_cask` by itself. Run it with `--help` to see how.
> 
> Though I was under the impression `brew bump-cask-pr` also updated multiple languages.
> 
> As for the differences between `cask-repair` and `bump-cask-pr`, the former is an old bash script and the latter is a ruby version integrated into `brew`. Use whichever you prefer.

Thanks for the reply. For this PR, I had used 'brew bump-cask-pr --version 82.0 firefox'. But, when I checked it had only submitted it for the one language default. I didn't try again. I instead just used the script 'update_multilangual_cask' to pull the sha256 for them all, redirected the output to an updated firefox.rb locally and made an edit for this PR.
Should the 'bump-cask-pr' call this script for the multiple language stanzas then and I wouldn't have to do anything extra for arguments? If so, then maybe there's something wrong with my local installation.

**Comment by vitorgalvao** [comment]
> Should the 'bump-cask-pr' call this script for the multiple language stanzas then and I wouldn't have to do anything extra for arguments?

No, they’ve always been separate. They’re different languages, even.

**Review by vitorgalvao — APPROVED** [review]

**Pull request merged**
