### PR TITLE
corrected checksum for XCA 2.1.1 download

### PR DESCRIPTION
**Pull request by g-a-c**
(sourced from the author's website at https://hohnstaedt.de/xca/index.php/download)

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please **carefully** [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

Notice how the instructions underline **if there is no *Signature Info* section, VirusTotal verification is not enough.** If there’s no such section and you post a VirusTotal link instead of asking for developer confirmation, your pull request will be closed without further comment.

**Comment by g-a-c** [comment]
The app is not signed, so uploading the DMG to VirusTotal is not applicable here.

I did post a link to the author's upstream download page which confirms the new SHA256 checksum present in this commit - is this not enough to satisfy the requirement to "Post a link to the developer's confirmation"? That text doesn't really explicitly define what's required if a link to the upstream download page is not sufficient.

**Comment by vitorgalvao** [comment]
> the author's upstream download page

That isn’t enough. An attacker that could have changed the download could have also changed that text. We mean something like asking the developer publicly (like Twitter) if they updated the package in place.

**Comment by g-a-c** [comment]
> We mean something like asking the developer publicly (opening a GitHub issue) if they updated the package in place.

Gotcha, I can do that. You may want to clarify in the documentation though, as I found it unclear.

**Comment by g-a-c** [comment]
> We mean something like asking the developer publicly (opening a GitHub issue) if they updated the package in place.

Gotcha, I can do that. You may want to clarify in the documentation though, as I found it unclear.

**Comment by g-a-c** [comment]
> We mean something like asking the developer publicly (opening a GitHub issue) if they updated the package in place.

Gotcha, I can do that. You may want to clarify it in the documentation though, as I found the wording unclear.

**Comment by g-a-c** [comment]
> > the author's upstream download page
> 
> That isn’t enough. An attacker that could have changed the download could have also changed that text. We mean something like asking the developer publicly (opening a GitHub issue) if they updated the package in place.

Fair point - I have now done that (https://github.com/chris2511/xca/issues/77) and will comment here when this issue is updated. I feel like the Cask documentation could use some improvement here as I didn't find the existing wording clear - do you accept pull requests for documentation?

**Comment by g-a-c** [comment]
https://github.com/chris2511/xca/issues/77 is now closed and the author has confirmed the correct checksum for the 2.1.1 (re-)release.

**Comment by vitorgalvao** [comment]
Thank you.

> do you accept pull requests for documentation?

Yes.

**Pull request merged**
