### PR TITLE
Update daemon-tools from 8.1.703 to 8.1.706

### PR DESCRIPTION
**Pull request by i0ntempest**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ran-dall** [comment]
@i0ntempest https://github.com/Homebrew/homebrew-cask/pull/85529#issuecomment-655208600

**Comment by i0ntempest** [comment]
What's wrong with the current app cast?

**Comment by ran-dall** [comment]
@i0ntempest I, nor the ML system, picks anything up.

Screen Shot 2020-07-07 at 7 23 52 PM

**Comment by i0ntempest** [comment]
Works for me?
Screen Shot 2020-07-07 at 22 28 40

**Comment by i0ntempest** [comment]
Oh wait you used https, that gives 403 on my end.

**Comment by ran-dall** [comment]
Also on `curl` with `$curl https://resources.web-search-home.com/xml/DAEMONToolsLite-appcast.xml` I get...

```shell
'
```


...nothing else

**Comment by i0ntempest** [comment]
Well that's weird... have you tried plain http?

**Comment by ran-dall** [comment]
@i0ntempest Good thinking! That did the trick. However, it still kinda problem because we need an accessible `appcast` on `https`...any ideas?

**Comment by i0ntempest** [comment]
The same URL with https has invalid certificate, and with `--insecure` it returns error 403. Though I still don't know why it returns a comma on your end, it looks like bad server configuration. Not much we can do except letting the vendor know I guess.

**Comment by ran-dall** [comment]
> ...letting the vendor know...

@i0ntempest Good call. I'll leave this open then for a few days and see if there's any difference. Otherwise, I think I've seen enough to merge this; but we still need to keep an eye out for the `appcast`

**Comment by i0ntempest** [comment]
I honestly didn’t expect a reply but here we go image

**Comment by ran-dall** [comment]
@i0ntempest Good work

**Pull request merged**
