### PR TITLE
Update folx from 5.11(13873).13873 to 5.12(13890).13890

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
why the weird version number here?

**Comment by ran-dall** [comment]
> why the weird version number here?

@core-code What do you mean?

**Comment by core-code** [comment]
well, it was changed from a simple version number to something more complicated in #67693

the URL doesn't need a version interpolation at all, so we can basically use what we like and what makes sense


we have
short version string: 5.12
bundle version: 13890

so, either of those, or a simple combination makes sense... however "5.12(13890).13890" seems overly complicated and .. weird

**Comment by ran-dall** [comment]
@core-code Agreed, could you make that PR or should I? Good spot BTW.

**Comment by core-code** [comment]
i can do it no problem ;-)

**Pull request merged**
