### PR TITLE
Update url for VLC player download

### PR DESCRIPTION
**Pull request by anteloio**
I couldn't download VLC using cask today so I checked the URL on the official website.

- Site link: https://get.videolan.org/vlc/3.0.6/macosx/vlc-3.0.6.dmg
- Download: https://ftp.free.org/mirrors/videolan/vlc/3.0.6/macosx/vlc-3.0.6.dmg

It's the first time I try to contribute. Can someone help me with making the tests pass?

### CODE REVIEW

**Comment by fwuensche** [comment]
It's working again. Closing it.

**Comment by fwuensche** [comment]
@suschizu i've had a couple of friends reporting the same issue this week. so two questions:

1. should we update the download url for vlc?

2. if i were to do that, what are the steps i can follow to pass the tests?

**Comment by core-code** [comment]
i am not sure why you would want to replace the official download URL of VLC, which is also used on their website, with a random mirror?

VLC downloads and installs through Homebrew-Cask for me without problem with the current (official!) URL just fine, if it doesn't for you then i'd suggest filing an issue...

**Comment by suschizu** [comment]
@fwuensche - the official download link works too for me … I can't reproduce the problem and would also suggest to keep the official url

**Comment by vitorgalvao** [comment]
We use the official download link. If the reliability of that URL is finicky, I’d recommend you contact *them* about it.

**Comment by fwuensche** [comment]
@vitorgalvao fully agreed. that makes sense

**Pull request closed without merging**
