### PR TITLE
Add CloudPBX 22.7.0.429

### PR DESCRIPTION
**Pull request by moogle19**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you. and welcome.

Can this be downloaded without a login?

**Comment by moogle19** [comment]
@vitorgalvao 
Downloadable yes, but you need an account to actually use it.

**Comment by vitorgalvao** [comment]
> Downloadable yes

Please guide me on the page how to download this without a login. I need to verify the URL.

**Comment by moogle19** [comment]
The direct download url is:  https://cpbx-hilfe.deutschland-lan.de/downloads/desktop-clients/cloud-pbx.osx-22.7.0.429
This can be found here: https://cpbx-hilfe.deutschland-lan.de/de/endgeraete-und-clients/desktop-client-download

**Comment by vitorgalvao** [comment]
> This can be found here: https://cpbx-hilfe.deutschland-lan.de/de/endgeraete-und-clients/desktop-client-download

That is not enough. I need to know how to get there from the homepage. I need steps.

**Comment by moogle19** [comment]
Here you go: 
[1](https://github.com/Homebrew/homebrew-cask/files/3325136/1.pdf) -> [2](https://github.com/Homebrew/homebrew-cask/files/3325137/2.pdf) -> [3](https://github.com/Homebrew/homebrew-cask/files/3325138/3.pdf) -> [4](https://github.com/Homebrew/homebrew-cask/files/3325139/4.pdf)

**Comment by vitorgalvao** [comment]
Thank you! Way more detailed than I was expecting.

**Pull request merged**
