### PR TITLE
Update eudic

### PR DESCRIPTION
**Pull request by m-zheng**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by m-zheng** [comment]
Seems like the file 'https://www.eudic.net/update/eudic_mac.xml' is changed somehow, which prevents users from installing.

**Comment by neutric** [comment]
The current version seems to be 4.1.5, at least this is what you get when you download https://static.frdic.com/pkg/eudicmac.dmg?v=2021-09-30 which I found [here](https://www.eudic.net/v4/en/app/download). Downloading https://static.frdic.com/pkg/eudicmac.dmg without the version string gives you 4.1.3. Both have the xml file mentioned above as SUFeedURL in their Info.plist.

**Comment by m-zheng** [comment]
> The current version seems to be 4.1.5, at least this is what you get when you download https://static.frdic.com/pkg/eudicmac.dmg?v=2021-09-30 which I found [here](https://www.eudic.net/v4/en/app/download). Downloading https://static.frdic.com/pkg/eudicmac.dmg without the version string gives you 4.1.3. Both have the xml file mentioned above as SUFeedURL in their Info.plist.

Yeah, you are right. The latest commit I made here will download from "https://static.frdic.com/pkg/eudicmac.dmg", which is 4.1.3. This commit has passed all tests. At least it will not throw any error during installation.

I think the developer of eudic will eventually update 4.1.5 to "https://static.frdic.com/pkg/eudicmac.dmg". Shall we fix the installation error (by approving my pr) and leave the version 4.1.5 for future update?

**Comment by neutric** [comment]
Not sure what the best way is for this cask. I'd do as you did except bump the version to 4.1.5,1065 and keep `url` as it was. This way you get the current version and livecheck hopefully will still alert you to a newer version. The query string in the download URL seems to be arbitrary, as was suggested [before](https://github.com/Homebrew/homebrew-cask/pull/107833#issuecomment-870531117) and still holds true.

**Comment by neutric** [comment]
Also, removing the query string from `url` reliably seems to get you the previous / an older version, as suggested by https://github.com/Homebrew/homebrew-cask/pull/109690/commits/04442ed673012a8a7f9b10e7654f5eee068818c5, which was probably merged accidentally.

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/113558

**Pull request closed without merging**
