### PR TITLE
propresenter@beta 17

### PR DESCRIPTION
**Pull request by khipp**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by krehel** [comment]
Did upstream change their numbering scheme?

**Comment by khipp** [comment]
It does seem like it:

image

**Comment by krehel** [comment]
Thanks - I couldn't dig into it but the jump from 7 to 17 seemed unusual.

**Review by krehel — APPROVED** [review]

**Comment by khipp** [comment]
@krehel No problem, I had to check for myself as well when you mentioned it.

**Pull request merged**
