### PR TITLE
Upgrade Scribus.app to 1.4.5

### PR DESCRIPTION
**Pull request by jwthomp**
Upgraded Scribus.app to stable version 1.4.5

Changed version from 1.4.5-r2 to 1.4.5
Updated sha256 to be valid for new Scribus download dmg file.

### CODE REVIEW

**Comment by radeksimko** [comment]
I'm a bit confused about the vendor's naming convention here. What exactly does the `r2` mean? Is it _release_? More importantly is `1.4.5-r2` considered as **not stable**?

The link **"Stable"** from homepage leads to sourceforge which contains both versions and `1.4.5-r2` marked as **"latest"**:

screen shot 2015-04-12 at 15 53 47

Would https://github.com/caskroom/homebrew-cask/pull/10558 solve your issue?

**Comment by jwthomp** [comment]
After looking over the versioning, I agree it is confusing. It does appear that r2 is the newest version (vs. just 1.4.5). Sorry for adding to the confusion.

[#10558][https://github.com/caskroom/homebrew-cask/pull/10558] does fix the issue.

**Comment by luzpaz** [comment]
The dev who made the change uploaded the -r2.dmg in response to this bug: http://bugs.scribus.net/view.php?id=12993 
I think they will release 1.4.6 but this preceded the release because it was important enough to upload but not important enough to announce publicly, my guess

**Comment by radeksimko** [comment]
Letting @alebcay to decide here as he originally merged the PR.
I'm :+1: for just fixing the `r2` version URL and closing this issue.

**Comment by alebcay** [comment]
According to [this page](http://wiki.scribus.net/canvas/Download), the latest stable is indeed 1.4.5. I can't seem to figure out what the `r2` is supposed to indicate, but the latest developer build is 1.5.0, so that's not what it's for either.

**Pull request merged**
