### PR TITLE
enhance arq uninstallation

### PR DESCRIPTION
**Pull request by tshu-w**
**Don't delete the folder where the backup configuration and license are stored, otherwise we need to reconfigure it every time we upgrade.**

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
That should be moved to the zap stanza then.

**Comment by tshu-w** [comment]
@SMillerDev Hi, there is already in zap stanza https://github.com/Homebrew/homebrew-cask/blob/4b5e1a08969251c61cca0c538fb35e080dde1c70/Casks/arq.rb#L30, though I don't know the difference between delete and trash

**Comment by SMillerDev** [comment]
This is `~/Library` while the one you're removing is `/Library`

**Comment by tshu-w** [comment]
@SMillerDev Sorry, I will take a look carefully and fix this PR.

**Comment by tshu-w** [comment]
@SMillerDev Hi, I added them to zap stanza. Can you take a look again?

**Review by SMillerDev — APPROVED** [review]
Thanks @tshu-w  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request merged**
