### PR TITLE
Update UniFi Controller to 4.6.6

### PR DESCRIPTION
**Pull request by mauricerkelly**
This commit updates the version, sha256 and homepage stanzas

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as aafa98ff73871ee6d9bf086b70f0b3c281771b02 to keep commit history cleaner. Your contribution is still credited to you.

**Comment by mauricerkelly** [comment]
Is there a new process that I’m failing to follow?

**Comment by vitorgalvao** [comment]
No, everything is fine. Is just that Github’s merge button makes a bit of a mess of history, and I’m trying to keep it cleaner.

Compare what the merge button does
image
to merging it this way
image

And see the results in `git log`. Way cleaner this way, and commits still retain ownership.

I also do it this way for PRs that need fixes, but in those cases the closing message is different, and warns that changes were made.

**Comment by mauricerkelly** [comment]
How do you actually achieve this? Are you rebasing?

**Comment by vitorgalvao** [comment]
No, I apply the PR as a patch on top of master, and push that. You can see the details of the procedure by taking a look at [my fastmerge script](https://github.com/vitorgalvao/tiny-scripts/blob/master/fastmerge).

**Pull request closed without merging**
