### PR TITLE
qth: update `sha256`

### PR DESCRIPTION
**Pull request by mrrsm**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by bevanjkay** [comment]
@mrrsm Are you aware of any confirmation from the vendor as to why the checksum has changed without there being a new version?

**Comment by mrrsm** [comment]
@bevanjkay  I didn't see anything in the changelog as to why it changed but I've been seeing the mismatch for a bit over a week and the sha hasn't changed again since then. 

`Fixed problem with importing license files.` was the changelog from https://www.w8wjb.com/wp/qth/qth-app-changelog/

I'm happy to reach out and see if I get a response

**Comment by bevanjkay** [comment]
@mrrsm if you can that would be good, as it rules out any chance of the download being compromised 👍🏻

**Comment by mrrsm** [comment]
@bevanjkay got a response as quoted below.  Seems intended and good to update to the current sha.

> Yes, I realized that I signed the .dmg with the wrong developer certificate and macOS was popping up a warning, so I repackaged it and uploaded it to my website.
> I don't actually maintain the Homebrew cask. though.
> - Wes W8WJB

**Comment by bevanjkay** [comment]
Thank you for confirming 👍🏻

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
