### PR TITLE
additions for El Capitan

### PR DESCRIPTION
**Pull request by vitorgalvao**
@caskroom/maintainers, please give corrections or thumbs up.

### CODE REVIEW

**Comment by nanoxd** [comment]
:+1: Looks good, I'll check version numbers for Ruby once I get back on my home desktop.

**Comment by vitorgalvao** [comment]
@nanoxd Thank you, I thought you might be the one to ask. Should be fine, though, it’s highly unlikely it has gone down.

**Comment by nanoxd** [comment]
I'm sure it hasn't gone down. It might be useful to someone :grey_question:

**Comment by ndr-qef** [comment]
I think we can safely assume Ruby has not been downgraded.

**Pull request merged**
