### PR TITLE
Add Notion Enhanced

### PR DESCRIPTION
**Pull request by bennetfabian**
https://github.com/notion-enhancer/notion-repackaged

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bennetfabian** [comment]
Searching help for:
- Introducing livecheck updates (via GitHub releases)
- Check if there are more files that have to be in the _zap trash_ section

**Review by bennetfabian — COMMENTED** [review]
@jamezrin @dragonwocky @CloudHill @Arecsu 
What name should be used? Notion Enhanced or Notion Enhancer?

**Comment by Arecsu** [comment]
I see you're submitting notion-repackaged. It installs itself as Notion Enhanced.

notion-enhancer on the other hand is a set of scripts and mods that patches vanilla Notion installations.

So, if you're using notion-repackaged, it would make sense to call it notion-enhanced. But that raises another question: should it be called notion-repackaged or notion-enhanced? 

I know nothing about homebrew naming conventions. Should it follow the repo name or the final installation name?

**Comment by bennetfabian** [comment]
> I see you're submitting notion-repackaged. It installs itself as Notion Enhanced.
> 
> notion-enhancer on the other hand is a set of scripts and mods that patches vanilla Notion installations.
> 
> So, if you're using notion-repackaged, it would make sense to call it notion-enhanced. But that raises another question: should it be called notion-repackaged or notion-enhanced?
> 
> I know nothing about homebrew naming conventions. Should it follow the repo name or the final installation name?

I think installed app name. So as a contributor you would say it should be _Notion Enhanced_?

**Comment by miccal** [comment]
Thank you @bennetfabian.

The `livecheck` is automatic from the GitHub releases, so no need to add a `livecheck` block here.

You can add more files to the `zap` stanza later if required.

And finally, the name shoulkd indeed be `notion-enhanced` to follow our [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).

**Comment by bennetfabian** [comment]
> Thank you @bennetfabian.
> 
> 
> 
> The `livecheck` is automatic from the GitHub releases, so no need to add a `livecheck` block here.
> 
> 
> 
> You can add more files to the `zap` stanza later if required.
> 
> 
> 
> And finally, the name shoulkd indeed be `notion-enhanced` to follow our [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).

Perfect. So will you merge it? Or do you want another pair of eyes to review it?

**Pull request merged**
