### PR TITLE
Update parsify from 1.8.0 to 1.9.3

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
I'd welcome input on switching `url` from *.dmg to *.zip where possible. It'd mean smaller download size and thus cache size on disk at the expense of a bit more CPU usage on install. In modern CPUs the trade-off between the two is strongly in favor of compressing where possible. Am I missing something or is this a no-brainer?

**Comment by bevanjkay** [comment]
@neutric I don't have any preference here, I'd be interested to hear if @carlocab or @SMillerDev have any insight here?

**Comment by neutric** [comment]
Just remembered https://github.com/Homebrew/homebrew-cask/issues/74998 where an unzip was guessed as culprit. Might be a factor. Another might be that the chance for *.dmg releases being there is probably higher than that for *.zip in release procedures that are not automated.

**Comment by carlocab** [comment]
No preference. We may wish to check with upstream about which artefact is generally more reliable.

**Comment by neutric** [comment]
Thanks for the feedback so far! @bevanjkay I guess this is good to go, as impact is limited and I don't expect @SMillerDev to have important reasons not to go with *.zip.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
