### PR TITLE
wechat 3.8.0.1

### PR DESCRIPTION
**Pull request by JounQin**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by razvanazamfirei — APPROVED** [review]

**Comment by razvanazamfirei** [comment]
Will run CI checks manually. No point in using resources right now.

**Review by reitermarkus — APPROVED** [review]

**Comment by viking1304** [comment]
I manually downloaded dmg from the link, extracted the app, and checked the version.

It is still 3.7.1.20

```
<key>CFBundleShortVersionString</key>
<string>3.7.1.20</string>
```

I double-checked and compared the shasum of `WeChat.app/Contents/MacOS/WeChat` from the download with my installed version.

They are the same

```
❯ shasum -a 256 WeChat
1032227bc0f46341ad8cd19f8b1119d91dff1172537ed26c1afaab666b175957  WeChat
```

@JounQin where did you see 3.8.0.1?

**Comment by razvanazamfirei** [comment]
See https://github.com/Homebrew/homebrew-cask/pull/90907#issuecomment-710107547. Versions are released earlier in some geographic regions. We should probably go back to version `:latest`.

**Comment by razvanazamfirei** [comment]
Closing for now.

**Pull request closed without merging**
