### PR TITLE
Update navicat-data-modeler to 2.1.18

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
Not sure how I feel about this PR... the interpolation for the download only takes the major and minor (`21`) and the sha256 is unchanged, however their changelog says this is `2.1.18`... but if the binary is the same as `2.1.17` what does that mean? The content is dynamic? The cask/sha256 we had for `2.1.17` is really from `2.1.18`?

**Comment by commitay** [comment]
IIRC this never matches the changelog, what is the version of the app itself?

**Comment by brianmorton** [comment]
That would require me actually installing this... :P 

Give me a minute.

**Comment by brianmorton** [comment]
image

**Comment by brianmorton** [comment]
I think what was submitted as 2.1.17 was actually 2.1.18, based on this:
image

This is about a week after the modified date on the 2.1.18 .app - so I think what we thought was 2.1.17 was actually this binary (2.1.18) and that is why the checksum didn't change.

Thoughts?

**Comment by commitay** [comment]
> Thoughts?

Yeah, Navicat casks are really annoying. I thought I had checked the version number locally when I submitted that PR but I guess I must have forgotten.

**Pull request merged**
