### PR TITLE
Trello X has been renamed to Xccello.

### PR DESCRIPTION
**Pull request by theseal**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Seeing as `url` doesn’t point to a specific version, this cask should use `version :latest` and `sha256 :no_check`. [See an example](https://github.com/caskroom/homebrew-cask/blob/f25b6babcd398abf48e33af3d887b2d00de1d661/Casks/kibako.rb).

Also, please remove `trello-x` as well.

**Comment by theseal** [comment]
Fixed according to comment.

**Comment by vitorgalvao** [comment]
Thank you.

**Comment by vitorgalvao** [comment]
On another note, there must’ve been a PR template that auto-appeared when you opened the PR.

Next time, please fill it.

**Pull request merged**
