### PR TITLE
Renamed RingCentral to RingCentral Phone

### PR DESCRIPTION
**Pull request by the-jay-schwartz**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by JayTheMarketer** [comment]
does this need any further input from me?

**Comment by JayTheMarketer** [comment]
does this require any further input from me?

**Comment by vitorgalvao** [comment]
> does this require any further input from me?

It now has conflicts, because the cask was changed in another PR. It would be better submitted in another PR.

**Comment by JayTheMarketer** [comment]
just to clarify -- i should submit this as as "new cask" with the name of ringcentral-phone in a new PR?

**Comment by vitorgalvao** [comment]
> just to clarify -- i should submit this as as "new cask" with the name of ringcentral-phone in a new PR?

Correct.

**Pull request closed without merging**
