### PR TITLE
Fix blender cask.

### PR DESCRIPTION
**Pull request by SushiDude**
Pull #14495 broke the blender cask.
It is ridiculous and rude that @scribblemaniac would submit something that was not tested.
It was irresponsible of @vitorgalvao to merge something that was not tested.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> It is ridiculous and rude that @scribblemaniac would submit something that was not tested.
> It was irresponsible of @vitorgalvao to merge something that was not tested.

Strong accusations, there.

Though we had our disagreements in certain areas, @scribblemaniac has submitted nothing but good work and was a regular here (good to see him again, occasionally). Similarly, I’m here everyday reviewing pull requests and handling issues, trying to move the project forward. What significant contributions have you done to the project, I ask.

Do you even have the faintest idea how many contributions homebrew-cask’s small team goes through  *daily*? This issue is at worst a minor inconvenience, and nothing major happened, or could have happened. Downloading and opening every submission to check for directory structure changes is a ridiculous proposition. Things are tested according to their importance.

It’s people like you that make open-source maintainers burn out. It is also not funny at all how in most of these cases, the people making the bold accusations have such a small record of open-source contributions.

Thank you for the contribution. It will be merged and you will be credited to it, as you should. Your attitude, however, is not welcome at all, and I personally do not appreciate your disproportionate, unreasonable, and unfounded remarks into a community that tries to be inclusive of all. We do not hold grudges and will not deny future contributions due to this incident, but you must check your tone as you post.

I ask that next time you decide to deride the work of *volunteers* from a project you benefit from but contribute very little to, and on a Sunday, even, reconsider.

**Comment by SushiDude** [comment]
>Strong accusations, there.

I would disagree. Just about every open source project requires that basic tests be preformed before pushing code.

>@scribblemaniac has submitted nothing but good work

I do not consider breaking blender to be good work.

>Similarly, I’m here everyday reviewing pull requests and handling issues, trying to move the project forward. What significant contributions have you done to the project, I ask.

Broken code was merged; the amount that anyone contributed is irrelevant.

>Do you even have the faintest idea how many contributions homebrew-cask’s small team goes through daily? 

Yes, I do.

>This issue is at worst a minor inconvenience, and nothing major happened, or could have happened.

But not testing code could lead to a future incident which could be major.

>Downloading and opening every submission to check for directory structure changes is a ridiculous proposition.

Is that not what you have Travis for?

>It’s people like you that make open-source maintainers burn out.

If an open source maintainer has gotten to the point where they push code without testing it, then they are already burnt out.

>Things are tested according to their importance.

Everything is important therefore everything should be tested.

>Your attitude, however, is not welcome at all

I can't criticize someone for breaking something that previously worked? 

>I ask that next time you decide to deride the work of volunteers

If a volunteer is working to break things, then I have the right and am justified to complain.

>project you benefit from

I do not benefit from things that do not work.

>but contribute very little to

If I did not contribute in this case, then blender would still be broken.

>We do not hold grudges and will not deny future contributions due to this incident

How is this an incident? You are taking my comments personally when that is not my intention. I just want you to properly test everything before it is committed. That way this issue, and many others, will never occur in the future. You should not be offended by constructive criticism. Please do not see this as an attack but rather user feedback and an opportunity to improve.

**Comment by vitorgalvao** [comment]
> I do not consider breaking blender to be good work.

A human made a small mistake that caused you nothing else than a minor inconvenience.

> Broken code was merged; the amount that anyone contributed is irrelevant.

It means the person is trustworthy.

> Yes, I do.

You don’t respect it, then.

> But not testing code could lead to a future incident which could be major.
> (…)
> Everything is important therefore everything should be tested.

No, wrong. Like I said, “nothing major happened, **or could have happened**”. It’s one of the reasons interpolation is so used in casks. The change at most could have broken the cask (which is what it did), there is no way it could’ve led to a bigger issue unless blender’s server had been compromised as well (in which case there’d be nothing we could’ve done anyway).

You think this minor issue means *nothing* is checked? Than you have very little consideration for the work done here, and I’m not sure why you even use the project.

Like I said, things are tested according to their importance. Things that could present a security issue (like changing `url`s) are throughly tested **by hand** (because that is the only way to do it). A simple version bump does not need the same amount of rigour.

Unlike you, most contributors are reasonable and understand what kind of work that means, and what kind of delay it would mean to hold up everything due to checking **minute, non-security important changes**. These changes cause minor inconvenience if missed but would cause great delays if checked with every PR. **Things have different degrees of importance.**

I do look forward to you upping your contributions and checking every pull request for these small problems.

> Is that not what you have Travis for?

Good point. Feel free to submit said improvements to the tests. They don’t write themselves. If this is that important to you, help fix it.

> I can't criticize someone for breaking something that previously worked?

You know what most of our contributors can also do? Criticise respectfully. [Point out errors helpfully](https://github.com/caskroom/homebrew-cask/pull/14455#issuecomment-148816980) instead of calling names.

> If a volunteer is working to break things, then I have the right and am justified to complain.

You know what’s better than complaining? Actually fixing things. Do you think the break was made to personally annoy you? A mistake was made, what do you believe name calling accomplishes?

You believe you have the right to complain. What you have is the right to leave. This project and its contributors owe you nothing. You do not contribute to it in any significant way and you do not pay for it. **You do not have the right to demand people’s free time to work on what you desire, for nothing.** Make no mistake, that is what you’re doing here.

> I do not benefit from things that do not work.

And homebrew-cask is pre-alpha. If you have such a big issue with broken things, leave and don’t come back until it’s stable. And even then some things might be broken, because that is the nature of humans developing software.

> If I did not contribute in this case, then blender would still be broken.

Because every cask that broke was left broken until you came around, right? If you hadn’t done it, someone else would have, like they always do. Thankfully, we have many contributors, and they catch a very great deal of things.

> You are taking my comments personally when that is not my intention.

You made them personal by specifically calling me (and @scribblemaniac) irresponsible. Are you fuzzy on the meaning of the word “personal”?

> You should not be offended by constructive criticism. Please do not see this as an attack but rather user feedback and an opportunity to improve.

I’ve been with this project for a long while. We’ve received a lot of constructive feedback. Yours was not it.

Let me make it very clear for you: your sense of entitlement to other people’s free time is frankly disrespectful. See an issue? Fix it, report it, just be mindful of how you do it. **Your tone and attitude are the issue here**, and no, you are not in the right. Many people here find mistakes and have disagreements, and they are able to do so through civilised discourse. Your comment is not an example of that.

**Comment by vitorgalvao** [comment]
As such, this conversation is no longer fruitful and I’m locking it. The point was made. Respect for the other members of the project is not negotiable, and you greatly (otherwise the conversation would’ve been different) broke my interpretation of what it means to be respectful. I’ve explained my reasoning throughly and gave an example of what pointing mistakes while being courteous (a situation where everyone benefits) is like. There are numerous other examples in the other 14499 issues.

**Comment by vitorgalvao** [comment]
[This is constructive criticism](https://github.com/caskroom/homebrew-cask/pull/14501#issuecomment-149037511). Cordiality in telling you what is wrong and suggesting an alternative. Notice how you weren’t called “ridiculous and rude” for submitting a PR that wasn’t sufficiently well constructed.

**Pull request merged**
