### PR TITLE
Update R in r.rb from 3.6.3 to 4.0.0

### PR DESCRIPTION
**Pull request by vincentarelbundock**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
I do not understand why Travis build fails. It almost surely cannot be related to the change I just made.

Screen Shot 2020-04-24 at 16 27 36

**Comment by miccal** [comment]
@vincentarelbundock changing the line
```
uninstall pkgutil: 'org.r-project*',
```
to
```
uninstall pkgutil: 'org.R-project.R*',
```
should fix the build failure.

**Comment by miccal** [comment]
Sorry @vincentarelbundock, my mistake, please change it to
```
uninstall pkgutil: 'org.R-project*',
```

**Comment by miccal** [comment]
Oh bother -- @vincentarelbundock please change it to:
```
uninstall pkgutil: [
                     'org.r-project*',
                     'org.R-project*',
                   ],
```

**Comment by vincentarelbundock** [comment]
Success! Thanks @miccal , I wouldn't have figured this out on my own.

**Pull request merged**
