### PR TITLE
Add Alire with alr v1.1.1

### PR DESCRIPTION
**Pull request by jquorning**
ALIRE: Ada Library REspository.
A catalog of ready-to-use Ada libraries plus a command-line tool 'alr' to
obtain, build, and incorporate them into your project. It aims to fulfill
a similar role to Rust's 'cargo' or OCaml's 'opam'.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
Alire is the name of the project containing the command-line tool `alr`.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @jquorning, but from our [acceptable Casks documentation](https://docs.brew.sh/Acceptable-Casks#rejected-casks):

> The app is both open-source and CLI-only (i.e. it only uses the `binary` artifact). In that case, and [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603), submit it first to [Homebrew/core](https://github.com/Homebrew/homebrew-core) as a formula that builds from source. If it is rejected, you may then try again as a cask (link us to the issue so we can see the discussion and reasoning for rejection).

**Comment by jquorning** [comment]
There is a chicken-and-egg-problem here. Alire requires an Ada compiler to build the `alr` tool. With `alr` we can install Ada compiler toolchains from binary archives. Ada compilers (GNAT) are available as binary archives and also as source archives. However building GNAT/GCC from source is a huge task requiring an Ada compiler for bootstrapping. The GNAT/LLMV which may be a better match for macOS in the future is still work-in-progress. It probably also requires an existing Ada compiler.

**Comment by miccal** [comment]
@carlocab your thoughts please.

**Comment by carlocab** [comment]
> However building GNAT/GCC from source is a huge task requiring an Ada compiler for bootstrapping.

This is true, but we should probably try first anyway. Note that Ada isn't unique in requiring itself to bootstrap -- the same is true for Rust, Go, GHC, LDC, etc.

**Pull request closed without merging**
