### PR TITLE
Add Swagger Editor Offline.app v0.0.3

### PR DESCRIPTION
**Pull request by XuluWarrior**
After making all changes to the cask:

- [*] `brew cask audit --download {{cask_file}}` is error-free.
- [*] `brew cask style --fix {{cask_file}}` reports no offenses.
- [*] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [*] Named the cask according to the [token reference].
- [*] `brew cask install {{cask_file}}` worked successfully.
- [*] `brew cask uninstall {{cask_file}}` worked successfully.
- [*] Checked there are no [open pull requests] for the same cask.
- [*] Checked the cask was not already refused in [closed issues].
- [*] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
> [Rejected Casks](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md#rejected-casks)
> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is not notable enough (< 10 stars)).

I'd suggest [creating your own tap.](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md)

**Comment by XuluWarrior** [comment]
Of course I respect you decision but I just wanted to point out that my swagger-editor-offline repository is just a simple Electron wrapper around https://github.com/swagger-api/swagger-editor

This is a very popular repository (~3000 stars) which doesn't provide any official installers.
A stand alone application has been requested in the past (https://github.com/swagger-api/swagger-editor/issues/997) but it seems their stance is that they don't have the resources to support one. And so I thought I would create one.

Homebrew Cask seemed like the ideal place for Mac developers to be able to install the editor from.  But I will admit that I only recently discovered Cask myself and perhaps I misunderstand the intention of the repository.

Any advice you have on what would need to change to make a future submission acceptable would be much appreciated.  e.g. Wait until my repository has more stars, or changes to the way I have wrapped and created the Cask.

**Comment by commitay** [comment]
> Wait until my repository has more stars

Basically this. 

For any future submission the Cask should be named `xuluwarrior-swagger-editor-offline` as it is unofficial. https://github.com/caskroom/homebrew-cask/issues/39739

However if you can get the upstream repo (https://github.com/swagger-api/swagger-editor) to approve your `app` (i.e. add it to their README) it can be named `swagger-editor-offline`.

It should also use [`#{version}`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/version.md) in the `url` and have an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md)

**Comment by XuluWarrior** [comment]
@commitay Thank you for your prompt and helpful response :)

**Pull request closed without merging**
