### PR TITLE
Update Consul to 0.6.1

### PR DESCRIPTION
**Pull request by jbeda**

### CODE REVIEW

**Comment by adityadalal924** [comment]
Thank you for the contribution. It was merged directly as 638124fb527557d42b3479428276126fe90b637c to keep commit history cleaner. Your contribution is still credited to you.

**Comment by adityadalal924** [comment]
FYI we generally prefer one Cask change per PR (ie, as `cask-repair` does), but this is also fine.

**Comment by jbeda** [comment]
Thanks.  For some reason cask-repair wasn't working for me (happy to submit an issue) and the last update to consul updated both casks in one PR.

**Comment by adityadalal924** [comment]
@jbeda Yes, we want to know where things don't work for you!

CONTRIBUTING was recently updated with a guide, if you haven't seen it yet: https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask


Otherwise, please make an issue over at https://github.com/vitorgalvao/tiny-scripts/issues with some more information and we can take a look, and hopefully get things working.

As a basis, you can copy (the bug report template):

-----------------

(Remember to run `brew update; brew cleanup; brew cask cleanup` before reporting your issue. It usually fixes things!)

### Description of issue


### Output of `brew doctor`

```
(paste output here)
```

### Output of `brew cask doctor`

```
(paste output here)
```

**Comment by jbeda** [comment]
Thanks -- bug here (for posterity): https://github.com/vitorgalvao/tiny-scripts/issues/9

**Pull request closed without merging**
