### PR TITLE
Update atom to 1.15.0

### PR DESCRIPTION
**Pull request by neutric**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by waldyrious** [comment]
I just ran `brew cask install atom` but the installed version was still v1.14.4. I even tried `brew cask uninstall --force atom` and then `brew cask fetch --force atom` per the instructions in [USAGE.md](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md), but the shown version is still v1.14.4.

Is there normally a delay for changes like these to take effect, or is there perhaps some cache that needs to be cleared?

**Comment by vitorgalvao** [comment]
@waldyrious You need to `brew update`.

**Comment by waldyrious** [comment]
@vitorgalvao thanks for the hint. However, I initially forgot the `cask` part of the command and tried `brew install atom`, which did update Homebrew -- only then I ran `brew cask install atom`. Would running `brew update` explicitly have made a difference?

```
$ brew install atom
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from b38c52f9 to 30a2f270.
Updated 2 taps (homebrew/core, homebrew/science).
==> New Formulae
(...)
==> Updated Formulae
(...)
Error: No available formula with the name "atom" 
==> Searching for similarly named formulae...
(...)
==> Searching taps...
These formulae were found in taps:
Caskroom/cask/atom                                                                                                      Caskroom/versions/atom-beta
To install one of them, run (for example):
  brew install Caskroom/cask/atom
```

```
$ brew cask install atom
==> Satisfying dependencies
complete
==> Downloading https://github.com/atom/atom/releases/download/v1.14.4/atom-mac.zip
######################################################################## 100.0%
==> Verifying checksum for Cask atom
==> Moving App 'Atom.app' to '/Applications/Atom.app'.
==> Linking Binary 'apm' to '/usr/local/bin/apm'.
==> Linking Binary 'atom.sh' to '/usr/local/bin/atom'.
🍺  atom was successfully installed!
```

**Comment by vitorgalvao** [comment]
> Would running `brew update` explicitly have made a difference?

Yes. The automatic update that HB performs does not update casks and external taps.

**Comment by waldyrious** [comment]
Ah, I see. Perhaps the auto-update message should point that out. Anyway, thank you for the explanation and sorry for the tangent :)

**Comment by vitorgalvao** [comment]
@waldyrious [You’re not the first to be confused](https://github.com/Homebrew/brew/issues/1946).

**Comment by waldyrious** [comment]
@vitorgalvao ah, thanks for pointing me to that discussion. I've subscribed to it.

**Pull request merged**
