### PR TITLE
Add DeltaChat v1.13.1

### PR DESCRIPTION
**Pull request by cwerner1**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

There was already a pull-request https://github.com/Homebrew/homebrew-cask/pull/52608 which was rejected in 2018 because the repo had too few stars.

Currently there are 421 stars for the repo https://github.com/deltachat/deltachat-desktop

### CODE REVIEW

**Comment by miccal** [comment]
Thank you @cwerner1.  

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

**Comment by cwerner1** [comment]
@miccal Added the zap Stanza

**Comment by miccal** [comment]
Thanks @cwerner1, but the last two in `/var` should not be removed by Cask -- please remove those last two lines.

**Comment by cwerner1** [comment]
Thanks @miccal for your support, finally I fixed my typos, and corrected the folders

**Comment by miccal** [comment]
Thank you @cwerner1.

**Review by miccal — APPROVED** [review]

**Pull request merged**
