### PR TITLE
Update Horos from 4.0.0 to 4.0.0RC3

### PR DESCRIPTION
**Pull request by hamiltont**
RC3 specifically has catalina bugfixes

After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by core-code** [comment]
hm i think version 4.0rcX should have never entered the cask in the first place. if there is demand for an unstable version of that cask, it should be added to the 'homebrew-cask-versions' repo

maybe use appcast 'https://github.com/horosproject/horos/releases.atom' to prevent that in the future?

**Comment by hamiltont** [comment]
I would have no problem with someone unrolling the entire 4.X line, it's
possible it was added without folks realizing that it was a release
candidate. The latest three. X release does work on Catalina. As far as I
understand the only difference with the 4.x release is bug fixes but I
could be incorrect on that.

My merge request was more about if we are going to ship a release candidate
by default we should ship the latest one

**Comment by core-code** [comment]
> My merge request was more about if we are going to ship a release candidate
> by default we should ship the latest one

fully agreed.

**Comment by vitorgalvao** [comment]
Please change it to the 3.X versions and change the appcast to the one pointed out by @core-code.

I’s fine to close this PR and make a new one, if you prefer.

**Comment by core-code** [comment]
sending a heads-up to @randall who first added the beta version in 'https://github.com/Homebrew/homebrew-cask/pull/74153'

**Comment by core-code** [comment]
Submitted (https://github.com/Homebrew/homebrew-cask/pull/78936)

**Comment by vitorgalvao** [comment]
Closing in favour of #78936.

Thank you anyway for the contribution and starting the conversation, @hamiltont.

**Comment by core-code** [comment]
yes indeed. we wouldn't have noticed that the cask does not refer to a stable version currently otherwise. thanks!

**Comment by hamiltont** [comment]
Sure thing, happy to see it fixed. Thanks folks

**Pull request closed without merging**
