### PR TITLE
update bartender v1.2.32

### PR DESCRIPTION
**Pull request by nicgen**
Updated to the latest version, changed the app cast url and added sha256.

### CODE REVIEW

**Comment by Amorymeltzer** [comment]
Hi @ngenty, thanks for the update!  The Travis build is failing because, with your new download url, the use of `#{version}` must be interpolated with `"` double quotes.  If you change that it goes through just fine (you can test locally using `brew cask audit bartender`).

Where did you find those links?  I checked the website, couldn't find 'em referenced anywhere (although they *do* work).

**Comment by ngenty** [comment]
Hi @Amorymeltzer, sorry for that and thanks a lot for the updates it's really helpful.
About the links, I just checked the old one updates.php who gives me the new appcast xml.

**Comment by Amorymeltzer** [comment]
Sorry, I wasn't clear enough - **just** the download `url` (so, `"http://macbartender.com/updates/#{version}/Bartender.zip"`) should use `"` because of `#{version}`, everything else was good with the single `'`.

When you're done, could you [squash your commits](http://davidwalsh.name/squash-commits-git)?  Thanks so much!

**Comment by ndr-qef** [comment]
Thanks, merged as cf70c17.

**Pull request closed without merging**
