### PR TITLE
Update ableton-live-standard from 10.0.6 to 10.1

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
@vitorgalvao could you please add ableton to update_cask_family :) 
there are 5 members in this family: 
ableton-live
ableton-live-lite
ableton-live-intro
ableton-live-standard
ableton-live-suite

**Comment by suschizu** [comment]
and perhaps also dcp-o-matic with 5 casks:
dcp-o-matic
dcp-o-matic-batch-converter
dcp-o-matic-encode-server
dcp-o-matic-kdm-creator
dcp-o-matic-player

**Comment by vitorgalvao** [comment]
Added both families to the script.

**Comment by suschizu** [comment]
great - thanks :)

**Pull request merged**
