### PR TITLE
Update kindavim from 6.0.0 to 7.0.0

### PR DESCRIPTION
**Pull request by godbout**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
> new try.

It worked! :)

**Comment by godbout** [comment]
not sure i can reproduce 👀️

**Comment by neutric** [comment]
> not sure i can reproduce 👀️

I am optimistic. 🚀

**Comment by godbout** [comment]
> > not sure i can reproduce 👀️
> 
> I am optimistic. 🚀

than you for believing 👀️

**Pull request merged**
