### PR TITLE
Update spotify from 1.1.83.956,be7ea9a7,21 to 1.1.83.956,be7ea9a7,21

### PR DESCRIPTION
**Pull request by rgoldberg**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by Moulick** [comment]
@rgoldberg  Hey, Spotify's `About Spotify` gives the version upto `1.1.83.956.gbe7ea9a7`, how did you find the `21` in `1.1.83.956,be7ea9a7,21`

image

**Comment by rgoldberg** [comment]
It was provided by @wongyiuhang in https://github.com/Homebrew/homebrew-cask/pull/122318#issuecomment-1107439384

Not sure where he got it.

**Comment by bevanjkay** [comment]
@rgoldberg You can get the latest version by running `brew livecheck spotify`

**Comment by rgoldberg** [comment]
If livecheck will provide the current version, should the creation of bump PRs be automated?

**Comment by bevanjkay** [comment]
There is already a similar mechanism for certain formula in `homebrew-core` however it creates additional maintenance overhead when all casks (including non-popular ones) are updated nightly, as other things can break other than just the version.

The easiest way now to bump a cask is to run `brew bump --open-pr <token>` as it will use the version detected by livecheck to create the PR (it then runs `brew bump-cask-pr in the background`).

**Pull request merged**
