### PR TITLE
Add marmaduke build of Chromium 69.0.3497.92

### PR DESCRIPTION
**Pull request by cpbotha**
Unlike the freesmug builds, these stable builds include video
codecs (H.264 for example) and widevine to watch Netflix and friends.

After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you, but we’ll be rejecting this on account of [not being notable enough](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md):

> The Cask is too obscure (for example, a self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 50 stars)).

**Comment by cpbotha** [comment]
This is the only chromium build that is both stable and contains the h264 video codecs. It is made available from the well known woolys site as one of the major stable options.

Please reconsider.

**Comment by vitorgalvao** [comment]
There has never been a single request for this software as a cask before today. The rule exists for a reason. If nobody wants it, including it will increase our maintenance burden for no benefit.

If you want this as a cask, consider hosting your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) for it.

**Comment by cpbotha** [comment]
Ok understood.

I made the external tap here: https://github.com/cpbotha/homebrew-marmaduke-chromium

**Comment by vitorgalvao** [comment]
Note the rule is permanently being applied. So if the software ever reaches the threshold, it becomes valid for inclusion.

**Pull request closed without merging**
