### PR TITLE
Update 1password from 8.7.1 to 8.7.3

### PR DESCRIPTION
**Pull request by MTCoster**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by jonathanwalter** [comment]
Looks like the regex on line 19 [is a bit off](https://github.com/Homebrew/homebrew-cask/runs/7147516921?check_suite_focus=true).

Current release is called `8.7.3-2.PRODUCTION` on https://app-updates.agilebits.com/product_history/OPM8

Something like this might work:
`regex(%r{href=.*?/1Password[._-]?v?(\d+(?:.\d+)*)[._-]?(-\d)?(.PRODUCTION-)?\$ARCH\.zip}i)`

**Comment by jonathanwalter** [comment]
I guess I should have [RTFM](https://docs.brew.sh/Brew-Livecheck#regex-guidelines)...

Maybe like this?
`regex(%r{href=.*?/1Password[._-]?v?(\d+(?:.\d+)*)[._-]?(?:\d?[._-]production[._-])?\$ARCH\.zip}i)`

**Comment by MTCoster** [comment]
> I guess I should [RTFM](https://docs.brew.sh/Brew-Livecheck#regex-guidelines)...
> 
> Maybe like this? `regex(%r{href=.*?/1Password[._-]?v?(\d+(?:.\d+)*)(?:[._-]?\d[._-]?PRODUCTION)?[._-]?\$ARCH\.zip}i)`
> 
> Check out [regexr.com/6ov5a](https://regexr.com/6ov5a)

Oops, that's on me too for not checking! Thanks for the updated regex

**Pull request closed without merging**
