### PR TITLE
Add studio-link-standalone (16.02.0-beta)

### PR DESCRIPTION
**Pull request by lukasbestle**

### CODE REVIEW

**Comment by lukasbestle** [comment]
Done. Hope it's OK now.

**Comment by victorpopkov** [comment]
Thank you for all your patience with this cask and for sumbitting https://github.com/caskroom/homebrew-cask/pull/18322. You are awesome!

**Comment by lukasbestle** [comment]
You are welcome. :)

**Comment by victorpopkov** [comment]
Thank you for the contribution. It was merged directly as 2fafe112bc2a09e084417526d59cb6f4080293c1 to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
