### PR TITLE
Add Lazy v1?

### PR DESCRIPTION
**Pull request by vladimyr**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Why the question mark?

**Comment by vladimyr** [comment]
> Why the question mark?

There is no notion of version on the webpage or in the url itself while actual binary is marked as `v1`. That's why I put `:latest` in code and question mark here because instructions require to put a version in PR title. 🤷‍♂

**Comment by vitorgalvao** [comment]
> while actual binary is marked as `v1`

Have you tried [the appcast script on it](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md)?

**Comment by vladimyr** [comment]
Yes, here is the output:
```
homebrew-cask on  add-lazy took 10s 
➜ ./developer/bin/find-appcast /Applications/Lazy.app 
Looking for Sparkle appcast… Not found.
Looking for electron-builder appcast… Not found.
```
I've also checked it using proxy and looked inside the binary itself but haven't found anything. This is quite a new app and developer probably haven't implemented it yet.
The primary reason for submitting it is: https://www.producthunt.com/posts/lazy I might as well close it atm and resubmit it once it evolves?

**Comment by vitorgalvao** [comment]
> I might as well close it atm and resubmit it once it evolves?

No need, thank you. I usually do a second pass on trying to find an appcast, but this time I wasn’t able to because I got an error extracting the PKG. Just wanted to make sure the script was tried.

**Pull request merged**
