### PR TITLE
Update capture-one from 12.1.4 to 13.0.1.19,20.0.1

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
This one is now problematic, because it became a walled build. Are we able to find another `homepage` or `url`?

**Comment by core-code** [comment]
i've looked at the appcast but wasn't able to find anything useful at the moment.

`https://cormws.phaseone.com/corm.asmx/GetNewSoftwareVersion?Platform=Mac&Version=13.0.0.177.2`

`https://cormws.phaseone.com/corm.asmx/GetNewSoftwareVersion?Platform=Mac&Version=13.0.0.186.2`

neither gives us a usable download URL. maybe its temporary because v13 is new, but at the moment it looks bad

**Comment by ifeign** [comment]
https://downloads.phaseone.com/a9562498-f874-404e-842d-9f5cc8a05efd/International/CaptureOne20.Mac.20.0.1.dmg this url works for me.

**Comment by core-code** [comment]
lets see if this still works in a day

**Comment by ifeign** [comment]
It still works.

**Comment by core-code** [comment]
@sushizu wanna re-open and update this PR?

**Comment by core-code** [comment]
```
 - appcast at URL 'https://cormws.phaseone.com/corm.asmx/GetNewSoftwareVersion?Platform=Mac&Version=20' does not contain the version number '13.0.1.19':
321
```

**Pull request closed without merging**
