### PR TITLE
Add BookMacster latest

### PR DESCRIPTION
**Pull request by gentlecat**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

Closes #39913

### CODE REVIEW

**Comment by commitay** [comment]
@gentlecat Please enable "Allow edits from maintainers"

**Comment by gentlecat** [comment]
@commitay, done!

**Comment by miccal** [comment]
Thank you for your contribution.

**Comment by luisspuerto** [comment]
Sorry... I just realized that dmg that is downloaded in the url I provided is not mounting, at least in my computer. Can be changed for a zip? 

http://sheepsystems.com/bookmacster/BookMacster.zip

At least the zip works. 

Thanks.

**Comment by gentlecat** [comment]
I don't have much experience with this, so not quite sure why this might be happening. Just tested it again and it gets installed fine here (macOS 10.13).

Do you have an error message or something else that could help?

**Comment by jerrykrinock** [comment]
I'm the developer of BookMacster.  I tested some downloaded `.dmg` files on two Macs and they work fine for me too.  But I believe @luisspuerto.  He sent me a screenshot showing that the Archive Utility app, which does the decompression in macOS, displays a _Warning_ dialog indicating _The following disk images couldn't be opened … no mountable file systems_.

Searching on the internet for this error, you'll see that it has been reported by Mac users for many years, although rarely.  Apparently there are some edge cases.  Some reported that the problem was caused by `/System/Library/Extensions/LexarFilterScheme.kext`, but that was many years ago.

I put both the `.dmg` and `.zip` on my website because some people prefer `.dmg`.  But my site also says that the `.zip` is recommended.  In my experience, `.dmg` has always been slightly problematic.  I suggest: Just do as @luisspuerto requested and change it to the `.zip`.  Thank you!

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/39953

**Comment by luisspuerto** [comment]
Thanks a lot for your work to all of you! Now works perfectly. 👍

**Comment by luisspuerto** [comment]
@gentlecat since you say that you tried on macOS 10.13 and it's working fine, I'm starting to thing that this is a compatibility issue between dmg created in High Sierra with the new file system and previous systems.

**Pull request merged**
