### PR TITLE
Add hp-eprint (new cask)

### PR DESCRIPTION
**Pull request by jawshooah**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Can we download this without logging in?

**Comment by jawshooah** [comment]
Can you not just `curl -O http://ftp.hp.com/pub/softlib/software13/COL43009/ds-104730-8/HP-ePrint_v2.5.0.dmg`? Works fine for me.

**Comment by vitorgalvao** [comment]
Should’ve been more clear. I mean manually, can you download it without logging in? I ask not for technical reasons, but due to [our rules regarding walled builds](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#unofficial-vendorless-or-walled-builds).

**Comment by jawshooah** [comment]
Gotcha. Yes, it is available to download without a login. This might
actually be a more suitable homepage:
http://h20331.www2.hp.com/hpsub/us/en/eprint/overview.html

**Comment by vitorgalvao** [comment]
> This might
actually be a more suitable homepage:
http://h20331.www2.hp.com/hpsub/us/en/eprint/overview.html

Sounds good.

**Comment by jawshooah** [comment]
@vitorgalvao Updated with the new homepage, should be good to go.

**Comment by vitorgalvao** [comment]
Thank you.

**Pull request merged**
