### PR TITLE
Add Syncplay 1.6.0

### PR DESCRIPTION
**Pull request by jamebus**
After making all changes to the cask:

- [X] `brew cask audit --download {{cask_file}}` is error-free.
- [X] `brew cask style --fix {{cask_file}}` reports no offenses.
- [X] The commit message includes the cask’s name and version.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [X] Named the cask according to the [token reference].
- [X] `brew cask install {{cask_file}}` worked successfully.
- [X] `brew cask uninstall {{cask_file}}` worked successfully.
- [X] Checked there are no [open pull requests] for the same cask.
- [X] Checked the cask was not [already refused].
- [X] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
Are the flight stanzas necessary?

**Comment by jamebus** [comment]
No they're not. That's just for convenience for VLC users. That adds integration for it.

Those can be removed and it will work fine with mpv, at least.

**Comment by commitay** [comment]
Please remove them.

**Comment by jamebus** [comment]
Willdo. I'll add a caveat for that instead. It's definitely better to avoid unnecessary complexity.

**Comment by vitorgalvao** [comment]
`caveats` are for installation-related matters: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats

As for what to do to integrate this with other software, that’s the user’s responsibility: https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md

**Comment by jamebus** [comment]
Understood. Thanks for the clarification.

**Pull request merged**
