### PR TITLE
updated retroarch (1.3.0)

### PR DESCRIPTION
**Pull request by vitorgalvao**

### CODE REVIEW

**Comment by fooness** [comment]
Thank you for updating the cask!

**Comment by fooness** [comment]
Unfortunately, I get this error:

    ~ >> brew cask install retroarch --force --download
    ==> Downloading http://buildbot.libretro.com/stable/1.3.0/apple/osx/x86_64/RetroArch-v1.3.0-osx-x86_64-OSX10.7.zip
    ######################################################################## 100,0%
    ==> Verifying checksum for Cask retroarch
    Error: It seems the symlink source is not there: '/usr/local/Caskroom/retroarch/1.3.0/RetroArch.app'

**Comment by vitorgalvao** [comment]
They’ve renamed the app. You’ll have to do `brew cask install retroarchcg`, now.

**Comment by fooness** [comment]
Oh, I see. Thank you for clarifying this!

**Pull request merged**
