### PR TITLE
Update betterzip to 3.1.1

### PR DESCRIPTION
**Pull request by My2ndAngelic**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

Just update, added new sha256, new version and new checkpoint.

### CODE REVIEW

**Comment by victorpopkov** [comment]
It seems that something went wrong with updating the existing [betterzip.rb](https://github.com/caskroom/homebrew-cask/blob/7e274d2ff7805d44e542b735d9cce74554ff5b15/Casks/betterzip.rb). If you have difficulties in fixing this manually, try checking out `cask-repair`. It makes Cask updates like this quite easy (details in [CONTRIBUTING](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md)).

**Comment by vitorgalvao** [comment]
Issue is it’s being added in the root directory, instead of updating the current cask.

**Comment by My2ndAngelic** [comment]
Oh, that's why it's strange

**Comment by adidalal** [comment]
Fixed in https://github.com/caskroom/homebrew-cask/pull/22714.
Thank you!

**Pull request closed without merging**
