### PR TITLE
llvm-arm-embedded 16.0.0 (new cask)

### PR DESCRIPTION
**Pull request by pthariensflame**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

This is a redo of #145695, after Homebrew/homebrew-core#129286 was rejected after some discussion.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
Unfortunately, this now fails signature checks.  I'd like other maintainers to chime in and see what the best way to handle this given the back-and-forth between here and `homebrew-core`.

**Comment by pthariensflame** [comment]
I renamed the binaries for a reason!  They conflict with standard LLVM, and this is specialized build for cross-complication.  Also, I had the suite there because there's a lot of stuff besides binaries being installed, but I don't know if that was truly necessary.

**Comment by razvanazamfirei** [comment]
Thanks for clarifying, I reverted the changes.

**Comment by reitermarkus** [comment]
I feel like this would work better as an addition as a formula to https://github.com/osx-cross/homebrew-arm, if it's not already there.

**Comment by pthariensflame** [comment]
> I feel like this would work better as an addition as a formula to https://github.com/osx-cross/homebrew-arm, if it's not already there.

It isn’t there yet, but I can submit it there if you’d prefer!

**Comment by miccal** [comment]
> > I feel like this would work better as an addition as a formula to https://github.com/osx-cross/homebrew-arm, if it's not already there.
> 
> It isn’t there yet, but I can submit it there if you’d prefer!

Yes please do @pthariensflame, as we require new submissions to pass our signature checks.

**Pull request closed without merging**
