### PR TITLE
Changed installation method in YouType.app cask

### PR DESCRIPTION
**Pull request by freefelt**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by p-linnane** [comment]
What's wrong with the existing install method?

**Comment by freefelt** [comment]
The main idea is to remove the com.apple.quarantine attribute with script, so users don't have to to it themselves. Because it might confuse them. It seems to me that users who install applications through homebrew want to get applications ready to work without unnecessary gestures.

**Comment by p-linnane** [comment]
We don't support things that intentionally try to circumvent Apple's security systems. Users who really don't want to have a Gatekeeper popup the first time they run the app can pass `--no-quarantine` when installing the app.

**Comment by freefelt** [comment]
I didn't know about `--no-quarantine` param, thank you! Then changing the installation method via the script is not relevant. Sorry for my ignorance, I only started to understand homebrew a couple of days ago.

**Comment by p-linnane** [comment]
No problem, we are here to help!

**Pull request closed without merging**
