### PR TITLE
Fix Valley/Heaven casks still depending on Mountain Lion or higher

### PR DESCRIPTION
**Pull request by haykam821**
This pull request fixes issue #57994.

### CODE REVIEW

**Comment by haykam821** [comment]
[Here is my other explanation.](https://github.com/Homebrew/homebrew-cask/issues/57994#issuecomment-457944984)

In #57235, all references to `:mountain_lion` and other old versions of macOS were removed. However, both the Valley and Heaven casks referenced `mountain_lion` instead, meaning that pull request skipped updated them. This pull request updates both to depend on `>= :mavericks`.

**Comment by ran-dall** [comment]
@haykam821 Thanks for PR to fix the issue! ✊ However, we only support the latest two releases of `macOS` on the main HBC Tap as stated in ["Finding a Home For Your Cask"](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask). Anything beyond that is 'best effort', especially `:mountain_lion` as it's been about 3 years since it's received an update.

**Comment by neverfox** [comment]
Looks like PRs can only fix one cask at a time or the tests fail.

**Comment by reitermarkus** [comment]
Thanks, @haykam821!

**Pull request merged**
