### PR TITLE
New cask google-chat-electron

### PR DESCRIPTION
**Pull request by cdwertmann**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@cdwertmann Thank you for your submission.
Please try to add a [zap stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap). The linked documentation provides some recommended methods to create it.

**Comment by cdwertmann** [comment]
@bevanjkay zap stanza added. The application repo is a fork because the original repo has been abandoned, can you advise on how to proceed?

**Comment by SMillerDev** [comment]
If the original repo is abandoned and upstream is therefore never going to merge back they might be interested in un-forking their repository.

**Comment by cdwertmann** [comment]
@ankurk91 would you be open to that idea?

**Comment by ankurk91** [comment]
What is the official way to un-fork?

Would this work?
https://ralphjsmit.com/unfork-github-repo/

**Comment by ankurk91** [comment]
The repo has been detached now.

**Comment by miccal** [comment]
Thank you @cdwertmann.

**Pull request merged**
