### PR TITLE
Fix incorrect checksum

### PR DESCRIPTION
**Pull request by danherd**
After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please **carefully** [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

Notice how the instructions underline **if there is no *Signature Info* section, VirusTotal verification is not enough.** If there’s no such section and you post a VirusTotal link instead of asking for developer confirmation, your pull request will be closed without further comment.

**Comment by ran-dall** [comment]
@vitorgalvao Here's the link. The `sha256` appears to be correct. I think we can close this.

https://www.virustotal.com/en/file/1792825d8b5c43e255276f2940d2a302f1b2096be13364de0f9d0b8886fd1a20/analysis/

Would we in _this instance_ use `:latest`, as the developer appears releases patch versions 'in place' and we only use `major.minor`?

**Comment by vitorgalvao** [comment]
Cask has already been updated to a newer version in the meantime.

**Comment by ran-dall** [comment]
@vitorgalvao Thanks! I got that last night; I was more asking about the use-case of `:latest` as I know it's something we're moving away from, and now it has a particular use case. I thought that this being updated in place without the 'patch' number would qualify. Just want to make sure that as I update the casks, I'm identifying the use-cases accurately. Thanks for your help...as always.

**Pull request closed without merging**
