### PR TITLE
Add initial version of ModMove

### PR DESCRIPTION
**Pull request by keith**
https://github.com/keith/ModMove/

### CODE REVIEW

**Comment by adityadalal924** [comment]
Please add `accessibility_access true` under your `app` stanza - it should take care of the "Enable Accessibily First" dialog

**Comment by keith** [comment]
Awesome! Done

**Comment by adityadalal924** [comment]
Thank you for the contribution. It needed some fixes, so they were made in dce0508ab85fce90bf3687f560ef55608ade0083. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by adityadalal924** [comment]
@keith - My apologies, I merged to my local copy instead of homebrew-cask (new maintainer) .

(I was trying to fix your commit, `accessibility_access true' needs to go under the `app`, right on top of end, but pushed the fix to my local repo instead of upstream)

Would you mind restoring your branch so I can properly commit it?

Sorry, and thanks!

**Comment by keith** [comment]
No worries! Restored

**Comment by adityadalal924** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 140b69a50bad31f6db3b9c1373d97215046c7a98. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by adityadalal924** [comment]
@keith Thanks for bearing with me, we're all set! :+1:

**Comment by keith** [comment]
No problem, thanks for helping out!

**Pull request closed without merging**
