### PR TITLE
Update mamp to 5.3

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by chrisrowe** [comment]
I'm getting a different checksum: `abc592aa5202d8312cb1def1e536d2640bfe15abe4aac18ac01168b3eae40acc`

**Comment by chrisrowe** [comment]
@ran-dall Can you please double check this yourself? Thanks!

**Comment by core-code** [comment]
@chrisrowe Submitted (https://github.com/Homebrew/homebrew-cask/pull/60375)

**Comment by chrisrowe** [comment]
❤

**Pull request merged**
