### PR TITLE
Remove 2 casks

### LINKED ISSUE #12972: Should audacity be removed?
Audacity abandoned SourceForge a while back. Their new homepage can be found at [audacityteam.org](http://audacityteam.org/). The issue that arises is briefly touched upon #10344 but no long term solution was proposed. Now they have released a new version (2.1.1) which is only hosted on FossHub. Since we cannot download things from FossHub, I propose that we remove the cask altogether. Any thoughts?

### PR DESCRIPTION
**Pull request by scribblemaniac**
Both apps do not offer cask accessible downloads for their latest versions and therefore need to be removed.

Closes #12972

### CODE REVIEW

**Comment by alebcay** [comment]
I can still retrieve both apps successfully:

```bash
$ cask audit --download audacity
==> Downloading http://downloads.sourceforge.net/project/audacity/audacity/2.1.0/audacity-
######################################################################## 100.0%
audit for audacity: passed

$ cask audit --download littleipsum
==> Downloading http://littleipsum.com/download/LittleIpsum%201.1.2.zip
######################################################################## 100.0%
audit for littleipsum: passed
```

**Comment by scribblemaniac** [comment]
@alebcay The downloads may be valid, but they are for outdated versions. The latest version are not available for direct download.

**Comment by alebcay** [comment]
I see. To clarify, Audacity's latest version is 2.1.1 and is only available via FossHub download, and LittleIpsum has moved completely to MAS.

**Comment by szhu** [comment]
So… this should be removed too, right?

https://github.com/caskroom/homebrew-cask/blob/master/Casks/wiztoolsorg-restclient.rb

**Comment by scribblemaniac** [comment]
@szhu Looks like it, care to submit a pull request?

**Pull request merged**
