### PR TITLE
ollamac 1.1.1 (new cask)

### PR DESCRIPTION
**Pull request by dcchambers**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.

**Note**: this is failing but I believe it is erroneous. The name of the app is "Ollamac" however because it ends in `mac` the `audit` command thinks it is a reference to the platform (macOS).

```
audit for ollamac: failed
 - cask token mentions platform
ollamac
  * cask token mentions platform
Error: 1 problem in 1 cask detected.
```

- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @dcchambers.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by dcchambers** [comment]
Hey @miccal - sorry for the oversight. Added one now, thank you!a

**Comment by aaronliu0130** [comment]
> Cask/ArrayAlphabetization: The array elements should be ordered alphabetically
> Style/TrailingCommaInArrayLiteral: Put a comma after the last item of a multiline array.

Try doing style --fix again

**Comment by dcchambers** [comment]
@aaronliu0130 done! 😄

**Review by bevanjkay — APPROVED** [review]

**Comment by dcchambers** [comment]
Thanks for the +1 @bevanjkay 🙇 the failing CI that I mentioned in the PR is preventing automerge, are you able to skip/bypass that and manually merge this? Otherwise any idea how ot make the CI happy? Thanks 🚀

**Comment by bevanjkay** [comment]
We don't have a "magic" auto merge on this repo anyway. There's no nice way for us to avoid this error than adding our syntax only label. I'll leave my approval here and get let another maintainer push it through.

**Review by p-linnane — APPROVED** [review]
Agreed with merging as a syntax-only PR to bypass this audit.

**Pull request merged**
