### PR TITLE
Add AlDente

### PR DESCRIPTION
**Pull request by simmac**
AlDente is an open source tool to limit maximum battery charge (in order
to increase the lifetime of the battery)

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
_It was already refused (#95182) due to apparent incompatibility with macOS Big Sur, but the documentation has now been updated and it does support Big Sur: see https://github.com/davidwernhart/AlDente/pull/48_
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @simmac.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

**Comment by simmac** [comment]
What should the zap stanza contain? You moved the plist-removal to uninstall, am I seeing this correctly?

**Comment by miccal** [comment]
> What should the zap stanza contain? You moved the plist-removal to uninstall, am I seeing this correctly?

The `zap` should contain user-specific files, usually located in various folders inside `~/Library/`.

**Comment by simmac** [comment]
> The `zap` should contain user-specific files, usually located in various folders inside `~/Library`.

AlDente does not create any other files than the Helper-service already included in the delete-command. The application directly reads and writes the value it modifies from and to the SMC, so there are no configuration files.

I double checked this by searching my entire file system for any files containing "AlDente" or "com.davidwernhart" in case I missed something (and tagging @davidwernhart just in case)

**Comment by miccal** [comment]
Thank you @simmac.

**Review by miccal — APPROVED** [review]

**Pull request merged**
