### PR TITLE
Update url in db-browser-for-sqlite.rb

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by suschizu** [comment]
not sure what this error is about:
```
audit for db-browser-for-sqlite: failed
 - download not possible: Download failed on Cask 'db-browser-for-sqlite' with message: not RFC 2822 compliant date: "2020-06-14T07:24:20Z"
Error: Download failed on Cask 'db-browser-for-sqlite' with message: not RFC 2822 compliant date: "2020-06-14T07:24:20Z"
```

**Comment by miccal** [comment]
May be better to revert to the GitHub releases `url`?

**Comment by ran-dall** [comment]
I don't think there's really anything we can do; clearly it's an upstream issue. 

Perhaps considering what at @miccal suggested, that might be a good workaround though

**Comment by core-code** [comment]
i've had a look at this. the github download is ok and contains the correct version. since the other download from the homepage doesn't work, lets just keep using the github URL which works flawlessly.

**Pull request closed without merging**
