### PR TITLE
Yousician (new cask)

### PR DESCRIPTION
**Pull request by rrooding**
After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]
Please add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) here. The [CreateZap](https://github.com/nrlquaker/homebrew-createzap) tool can help you with this.

**Comment by rrooding** [comment]
Added zap @SMillerDev

**Comment by rrooding** [comment]
@bevanjkay My experience with this app is that it has the launcher has that behaviour already, so homebrew would not be a degradation. You always launch the app through the `Yousician Launcher.app` because the `Yousician.app` is not visible. Whenever the launcher detects an update during startup, it will start downloading the new `Yousician.app` before you can use it. So during normal use, I'm already confronted with lots of downloads, but that's an issue with the app itself.

**Review by bevanjkay — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @rrooding.

**Pull request merged**
