### PR TITLE
Remove SIP Casks

### PR DESCRIPTION
**Pull request by commitay**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

Requires SIP to be disabled for > yosemite. https://totalfinder.binaryage.com/sip

Similar case: https://github.com/caskroom/homebrew-cask/issues/38746

### CODE REVIEW

**Comment by commitay** [comment]
```
Error:
 Cask totalfinder depends on macOS release being one of [10.9, 10.10], but you are running release 10.12.

Error:
 Kernel.exit
```

**Comment by vitorgalvao** [comment]
According to the rule to support only the latest two versions, at a certain point it stops making sense we even have these casks.

How about we start removing them and add a rule about not supporting casks that need a disabled SIP to install?

**Comment by commitay** [comment]
> How about we start removing them and add a rule about not supporting casks that need a disabled SIP to install?

Yes, makes sense. I'll update this to remove them and add SIP to `rejected_casks`.

**Review by vitorgalvao — APPROVED** [review]

**Comment by sscotth** [comment]
Tap for posterity: https://github.com/sscotth/homebrew-sip

**Comment by wickles** [comment]
@sscotth I take it you do not plan to maintain that tap?

**Comment by sscotth** [comment]
@wucjkes Thanks for the ping. I can add the #41971 casks if that's what you are looking for. I didn't know they existed.

**Pull request merged**
