### PR TITLE
upgrade firefox.rb

### PR DESCRIPTION
**Pull request by FinalDes**

### CODE REVIEW

**Comment by alebcay** [comment]
Looks good, thanks! :+1:

**Comment by macdao** [comment]
Why we changed the version from latest to a specific version?

Because Firefox can upgrade automatically, the `latest` version made me no worried about the upgrade.

But the specific version made me upgrade Firefox manually. It means every time Firefox cask upgraded, the Firefox get out of control of brew-cask. When I run `brew cask list firefox` then I get `Warning: firefox is not installed`

**Comment by FinalDes** [comment]
run brew cask update and brew cask install firefox without unistall

**Comment by macdao** [comment]
OK, I run `brew cask install firefox` and get brew cask list firefox works. but when I run `ls /opt/homebrew-cask/Caskroom/firefox` I got two items: `36.0.1` and `latest`

For now, every time Firefox upgrade (and cask upgrade), I have to reinstall it even Firefox can upgrade automatically.

I prefer `latest` to `36.0.1`. I'll send a pull request to change to from `36.0.1` to `latest` if there's no good reason.

**Comment by vitorgalvao** [comment]
No, you don’t have to reinstall it. Just let Firefox do it on its own. Why does the name of the directory matter to you?

There is a good reason to have it versioned: checking the integrity of the download.

**Comment by macdao** [comment]
@vitorgalvao the integrity check is a good reason. I can't find a better solution.

I think the name of the directory matters. When Firefox version upgrades, `brew cask info firefox` will tell me that `Not installed`.

I thought that the `version` should be `:latest` when the App can upgrade by itself, for example google-chrome, skype, evernote, teamviewer and so on. How do you think about these casks?

**Comment by vitorgalvao** [comment]
> I thought that the `version` should be `:latest` when the App can upgrade by itself

No, it has absolutely nothing to do with that. It is only a consequence of the url being versioned (changing with each update) or not.

**Comment by macdao** [comment]
OK, it's my misunderstanding.

For google-chrome, skype, evernote, teamviewer and firefoxdeveloperedition, they are using latest version. Will they be changed to specific version?

For `Not installed` issue, do you think it's OK?

**Comment by vitorgalvao** [comment]
> Will they be changed to specific version?

It depends if such a url exists, but that should happen closer to when `update` is implemented.

> For `Not installed` issue, do you think it's OK?

Yes, those other issues should also be fixed.

**Pull request merged**
