### PR TITLE
Add HTTPie 2022.12.0

### PR DESCRIPTION
**Pull request by moonfruit**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

There is already a `httpie` in homebrew-core, but that is a command-line program, and this is a desktop wrapper for it.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @moonfruit.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by moonfruit** [comment]
After tapping `nrlquaker/homebrew-createzap`, I ran `brew createzap httpie`, but there is no output.

**Comment by moonfruit** [comment]
OK, I add some `zap`.

**Comment by miccal** [comment]
@moonfruit do you know if this will conflict in any way with the [`httpie` formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/httpie.rb)?

**Comment by moonfruit** [comment]
No, this is a totally desktop app. And `httpie` formula is a command line program.

**Review by miccal — APPROVED** [review]

**Pull request merged**
