### PR TITLE
CONTRIBUTING.md: add rubocop instructions

### PR DESCRIPTION
**Pull request by vitorgalvao**
Refs https://github.com/caskroom/homebrew-cask/issues/14713.

### CODE REVIEW

**Comment by jawshooah** [comment]
This won't work as expected, since `rubocop` will use the default ruleset if it can't find one in the current working directory.

Better would be something like this:

```
cd "$(brew --repository)/Library/Taps/caskroom/homebrew-cask"
bundle install
bundle exec rubocop Casks/my-cask.rb
```

**Comment by vitorgalvao** [comment]
Are you sure? Because my tests suggest it does work.

I have a global `.rubocop` in my home directory. Among other rules, it prefers `%x(…)` over backticks. If I’m in my home directory, move a cask that uses backticks ([`jce-unlimited-strength-policy.rb`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/jce-unlimited-strength-policy.rb)) to `/tmp` and run `rubocop` on it, it finds the backticks as an error. However, if (still inside my home directory) I `rubocop "$(brew --repository)/Library/Taps/caskroom/homebrew-cask/Casks/jce-unlimited-strength-policy.rb", then it does not find an error.

This seems to suggest rather than just looking for a ruleset in the current directory, it looks in the directory of the file you’re checking and its parent directories.

**Comment by jawshooah** [comment]
Strange:

```
$ cd ~
$ rubocop /usr/local/Library/Taps/caskroom/homebrew-cask/Casks/adobe-air.rb
Inspecting 1 file
C

Offenses:

/usr/local/Library/Taps/caskroom/homebrew-cask/Casks/adobe-air.rb:22:13: C: Unnecessary spacing detected.
      :rmdir  => '~/Library/Application Support/Adobe/'
            ^

1 file inspected, 1 offense detected

$ cd /usr/local/Library/Taps/caskroom/homebrew-cask
$ bundle exec rubocop /usr/local/Library/Taps/caskroom/homebrew-cask/Casks/adobe-air.rb
Inspecting 1 file
Warning: unrecognized cop Style/CommandLiteral found in /usr/local/Library/.rubocop.yml
.

1 file inspected, no offenses detected
```

**Comment by vitorgalvao** [comment]
I can reproduce that. Not sure why I could do it the other way, but I can reproduce that.

Either way, we can’t have a solution if not everyone can reproduce it. Will change to your suggestion.

**Comment by jawshooah** [comment]
You could also leave out the bit about having `rubocop` installed, since `bundle install` takes care of that.

**Comment by vitorgalvao** [comment]
Right. Changed.

**Comment by jawshooah** [comment]
:+1:

**Pull request merged**
