### PR TITLE
Update maintenance from 2.7.6 to 2.7.7

### PR DESCRIPTION
**Pull request by i0ntempest**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by miccal** [comment]
I am not sure what is going on with the CI tests here ... ?

**Comment by miccal** [comment]
> #107667

You could be right @bevanjkay, good work :)

**Comment by miccal** [comment]
So it seems that the issue is the list for the `depends_on macos:` ...

**Comment by bevanjkay** [comment]
@miccal The matrix generation currently expects a given value, and not an array of values.

**Pull request merged**
