### PR TITLE
Add AutoFirma Latest

### PR DESCRIPTION
**Pull request by ignic**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] [If the `sha256` changed but the `version` didn’t][version-checksum],  
      provide public confirmation by the developer: {{link}}

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

Hello,

This is my first attempt to make a new cask, please be gentle :)

The URL has no version, so I have used "version: latest". But the zip that is downloaded has a pkg with version number in the filename. I think that this would break when a new version is updated. Is there a better way to handle this?

Thank you all for the Homebrew project!

Regards

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> But the zip that is downloaded has a pkg with version number in the filename. I think that this would break when a new version is updated. Is there a better way to handle this?

Make the cask versioned and add a `sha256`. It’ll break anyway without it, so no point in not having it.

**Comment by ignic** [comment]
Thanks to @commitay for the fixes! I have spent more than an hour to figure out that I have to use double quotes instead of single quotes if I want to use the #{version} variable.

**Comment by vitorgalvao** [comment]
> I have spent more than an hour to figure out that I have to use double quotes instead of single quotes if I want to use the #{version} variable.

That is common in languages where you use interpolation (`bash` also works like that): single quotes are literal, double quotes expand interpolation.

**Comment by vitorgalvao** [comment]
Thank you for your first contribution!

**Pull request merged**
