### PR TITLE
Add Stack 2.7.3

### PR DESCRIPTION
**Pull request by danielbayley**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not [already refused].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by danielbayley** [comment]
Not sure what the policy is for replacing a formula like this? This app can only really have `stack` as a token… and the 'vendor' seems to be just the same name. Whereas the existing `stack.rb` Cask can easily be prefixed with the vendor as `transip-stack`… So what to do in this situation?

**Comment by vitorgalvao** [comment]
The existing cask isn’t insanely popular, but it might still pose a problem to rename without a proper mechanism in place (which we don’t have)

```
stack (added 1355 days ago)
30 days: 26 (#1529)
90 days: 86 (#1410)
365 days: 301 (#1472)
```

You can call the new one `stack-stack` (vendor-appname). I think we have precedent.

**Comment by danielbayley** [comment]
> You can call the new one stack-stack

Seems a bit daft, but ok…

**Comment by vitorgalvao** [comment]
> Seems a bit daft, but ok…

I agree it looks weird, but unless you want to implement the equivalent of `formula_renames` and submit a PR before getting the cask in, there’s not really a good option.

**Comment by danielbayley** [comment]
> implement the equivalent of `formula_renames`

@vitorgalvao What do you mean by this exactly? A new stanza?

**Comment by vitorgalvao** [comment]
> @vitorgalvao What do you mean by this exactly? A new stanza?

No, it’s a JSON file. See [the documentation](https://docs.brew.sh/Rename-A-Formula) and [a working example](https://github.com/Homebrew/homebrew-core/blob/master/formula_renames.json).

**Comment by danielbayley** [comment]
> No, it’s a JSON file. See [the documentation](https://docs.brew.sh/Rename-A-Formula) and [a working example](https://github.com/Homebrew/homebrew-core/blob/master/formula_renames.json).

@vitorgalvao Right, so the process is exactly the same for a Cask?

**Comment by vitorgalvao** [comment]
> @vitorgalvao Right, so the process is exactly the same for a Cask?

No, the process doesn’t work for casks (but we’d like it to). Therein lies the problem.

**Comment by danielbayley** [comment]
@vitorgalvao Even if it did, would adding a new formula/Cask with the same name as the previously renamed one work reliably?

**Comment by vitorgalvao** [comment]
> Even if it did, would adding a new formula/Cask with the same name as the previously renamed one even work reliably?

It think so, because it’s supposed to affect current installs, not newer ones.

**Comment by core-code** [comment]
since the requested rename has been done, is this good to merge?

**Comment by vitorgalvao** [comment]
> since the requested rename has been done, is this good to merge?

Yes.

**Pull request merged**
