### PR TITLE
Add gogs v0.9.48

### PR DESCRIPTION
**Pull request by brewingcode**
- [x] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Commit message includes cask’s name.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Why would you need a wrapper for this?

**Comment by jawshooah** [comment]
@reitermarkus Haven't tested, but it's possible that the script must be run from its containing directory. Is that the case, @brewingcode?

**Comment by brewingcode** [comment]
@reitermarkus as @jawshooah guessed, the script needs to be run in its containing directory, because it:

- looks for files in `public`, `templates`, etc, and
- writes its data into the containing directory

**Comment by vitorgalvao** [comment]
But `binary` only links. Are you saying it still breaks in that case?

**Comment by jawshooah** [comment]
@vitorgalvao Yes, for the same reason that `jar` executables are usually wrapped in a shim that navigates to their containing directory before executing them. It allows the developer to assume all libraries are immediately available from the working directory.

**Comment by jawshooah** [comment]
@brewingcode All of the backup stuff going on in `uninstall_preflight` and `uninstall_postflight` is outside the scope of `homebrew-cask`. If a user wants to back up an install, they can take care of that themselves. It isn't and shouldn't be our concern.

**Comment by brewingcode** [comment]
@jawshooah fair enough, I had a feeling that might be a little out of scope, so it's been removed, I just chopped it off the HEAD of my branch.

**Comment by brewingcode** [comment]
Thanks!

**Comment by jawshooah** [comment]
Thanks for the submission!

**Pull request merged**
