### PR TITLE
Add Microsoft Office 2016

### PR DESCRIPTION
**Pull request by ryanrhughes**

### CODE REVIEW

**Comment by Ngrd** [comment]
The current official latest version of the Microsoft Office is 2016. There is no need to create the additional cask for Microsoft Office, but we should modify the original one instead: [microsoft-office.rb](https://github.com/caskroom/homebrew-cask/blob/0c424723640a7ee4764ebf3e25fce96ded0bb969/Casks/microsoft-office.rb).

**Comment by ryanrhughes** [comment]
Modified per the recommendation to update the main microsoft-office.rb file instead.

**Comment by Ngrd** [comment]
Thank you. Could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by jawshooah** [comment]
How is this different from [microsoft-office-preview](https://github.com/caskroom/homebrew-versions/blob/master/Casks/microsoft-office-preview.rb)? Has there been an official (non-preview) release?

**Comment by Ngrd** [comment]
It's not a preview anymore. The name of the cask, use the original one or create a new one still concerns me the most. Office 2016 for Mac is now available with Office 365 (released on July 9, 2015). However, the one-time purchase coming in September.

**Comment by vitorgalvao** [comment]
> In my opinion, it would be better to hold on this update until September and meanwhile create another cask with the name something like `microsoft-office-365.rb`. However, I'm still not sure…

Whatever you think best. I’m really out of the loop on MS Office stuff, so I have no opinion, here. I’m not opposed to holding off until September, since it’s right around the corner.

**Comment by ryanrhughes** [comment]
Commits squashed.

I wasn't aware of the timing difference for the one-time purchase edition. 

However, based on past history, I also wouldn't be surprised if the installers for the one-time purchase and Office 365 edition weren't completely separate even when it does come out.

**Comment by Ngrd** [comment]
Thank you for the contribution. It was merged directly as 33ef28e79333a071945a4c47f6617b34a4094775 to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
