### PR TITLE
Added CircuitJS1 app

### PR DESCRIPTION
**Pull request by phdoerfler**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [X] `brew audit --new-cask {{cask_file}}` is error-free.
- [X] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [X] `brew audit --new-cask {{cask_file}}` worked successfully.
- [X] `brew install {{cask_file}}` worked successfully.
- [X] `brew uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by phdoerfler** [comment]
This is either my first new cask or the first in a long time, so maybe have an extra close look.
One thing of note:
The version number is "1" since the app's name is "CircuitJS1". I don't know if or how frequently this will change and it might be advisable to use the last modified date instead as shown on the download page:

https://www.falstad.com/circuit/offline/

which, in this case, would be 2020-12-11.

Thoughts?

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @phdoerfler.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

**Comment by phdoerfler** [comment]
@miccal I added the zap stanza generated by [createzap](https://github.com/nrlquaker/homebrew-createzap)

**Comment by miccal** [comment]
> @miccal I added the zap stanza generated by [createzap](https://github.com/nrlquaker/homebrew-createzap)

@phdoerfler I am afraid that all you have done is revert this to your original submission, before I had made some changes, and there is still no `zap` stanza.

**Comment by phdoerfler** [comment]
> > @miccal I added the zap stanza generated by [createzap](https://github.com/nrlquaker/homebrew-createzap)
> 
> @phdoerfler I am afraid that all you have done is revert this to your original submission, before I had made some changes, and there is still no `zap` stanza.

Indeed! In my unending wisdom I have failed to `git add` my changes and, as is tradition(*), have `git commit --amend`ed and then fatally `git push **-f**`ed the changes without doing a pull before that. Sorry for this!

*) A habit that stems from some repositories wanting PRs to consist of one single commit rather than multiples, though this might be a relic of the past by now.

**Comment by phdoerfler** [comment]
@miccal Should now be properly zap stanza'd and pushed. Happy Holidays!

**Comment by miccal** [comment]
Thank you @phdoerfler.

**Review by miccal — APPROVED** [review]

**Pull request merged**
