### PR TITLE
Update sha256 and url of epic-games

### PR DESCRIPTION
**Pull request by jlaw**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by jlaw** [comment]
I downloaded and verified the sha256 to be the one I submitted. The URL submitted is the one used on their website.

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by brianmorton** [comment]
https://github.com/caskroom/homebrew-cask/pull/46625

**Comment by jlaw** [comment]
epic-games now updated to 7.9.2. Closing this pull request.

**Pull request closed without merging**
