### PR TITLE
Remove all automerge code.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
This is not secure enough.

### CODE REVIEW

**Comment by bbenzikry** [comment]
@MikeMcQuaid, @Ry0taK  I understand this has to do with #104191 
I looked at the disclosure on hackerone and it seems like you opted against opening this up to the world. 
Is it possible to change your mind? I think others will benefit from seeing what was wrong here

**Comment by MikeMcQuaid** [comment]
@bbenzikry We will be publishing a security disclosure blog post for this. We just need to write it up and coordinate with @Ry0taK.

**Comment by bbenzikry** [comment]
@MikeMcQuaid Great, thank you 👍

**Comment by MikeMcQuaid** [comment]
We have posted about this in https://brew.sh/2021/04/21/security-incident-disclosure/

**Pull request merged**
