### PR TITLE
Update powershell to 6.1.0-preview.1

### PR DESCRIPTION
**Pull request by vors**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked there are no [open pull requests] for the same cask.
- [ ] Checked the cask was not already refused in [closed issues].
- [ ] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by TheeNawMan** [comment]
Is 6.0.2 the stable? I would recommend making a new cask named powershell-preview

**Comment by vors** [comment]
Yes, that's right. I don't want multiple instances, if possible.

Does brew support any mechanics for preview versions in the same tap?

**Comment by commitay** [comment]
> Does brew support any mechanics for preview versions in the same tap?

No. We track stable versions (if there is one) in this tap and preview/beta/devel, etc go in `versions`.

**Comment by vors** [comment]
Gotcha, I think we should just wait for 6.1.0 release.

**Comment by TravisEz13** [comment]
@vors  It would be nice if we have a `powershell-preview` package in versions.  We have a tracking issue for it here: https://github.com/PowerShell/PowerShell/issues/5855

**Pull request closed without merging**
