### PR TITLE
coolterm: update url and add checksum

### PR DESCRIPTION
**Pull request by chenrui333**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

upstream helped with the artifact release (previously only on the homepage, now it is also in `https://freeware.the-meiers.org/previous`), but there is some issue of adding livecheck against `https://freeware.the-meiers.org/previous` cc @Homebrew/cask for help

### CODE REVIEW

**Comment by p-linnane** [comment]
@samford Any idea how we can get the dots into the livecheck result?

**Comment by bevanjkay** [comment]
In the past we checked here - https://freeware.the-meiers.org/version/CoolTerm.ver

**Review by samford — COMMENTED** [review]
> Any idea how we can get the dots into the livecheck result? My initial thought was to grab each digit as it's own match and add the dots that way, but not sure if there's a smarter way to handle it.

It seems like the main options are to check the homepage (and try to match the version without picking up any of the others) or naively insert dots between each digit in the filename version, as you mentioned. Both approaches work and both can fail in different ways.

If we check the homepage, we may end up picking up a version for different software if the regex is too loose or failing to match the version if the regex is strict and the structure of the HTML changes.

If we check the filename versions and naively insert dots, this will surface an incorrect version if upstream ever creates a release where one of the parts has more than two digits (e.g., 10.2.3). So far they've only used versions that include single digits but inevitably they will run out of numbers (if the software lives long enough) and have to use more than one digit somewhere.

I'm not a fan of inserting dots to naively reconstitute a version when we have other options, so I'm leaning away from that approach. Besides that, I'm not sure if there's a notable gap between when upstream uploads a new file and updates the homepage to announce the new version, so there's something to be said for checking the homepage for that reason.

> In the past we checked here - https://freeware.the-meiers.org/version/CoolTerm.ver

That's interesting. The only rub is that it returns a longer version (`2.1.1.3.0.1288`), so we would either have to truncate that at three parts (`2.1.1`) to match the homepage/filename version or use `#{version.major_minor_patch.no_dots}` in the `url`. This assumes that upstream would never release a version with more than three parts and I'm not sure how I feel about that (it's not entirely dissimilar to naively inserting dots in a no-dot version, as they both rely on assumptions).

If it's safe to assume that the filenames will only include the major/minor/patch with no dots, then that would potentially be more reliable than pulling the version out of the loose text on the homepage (so long as `CoolTerm.ver` is always kept up to date).

-----

I have `livecheck` blocks worked up for each of these options, so it just depends on what everyone else thinks. Each approach has benefits/detriments but I'm in favor of either the homepage or `CoolTerm.ver` checks.

**Comment by Bo98** [comment]
It's generally better to side with APIs etc over HTML scraping, so I'd go with CoolTerm.ver unless there's clear evidence it can't work.

**Comment by bevanjkay** [comment]
As far as I can see we never had an issues in the past using `CoolTerm.ver` and just truncating the version in the `url`.

**Comment by samford** [comment]
Works for me. I pushed a commit to reinstate the `CoolTerm.ver` `livecheck` block and update the `version`/`url` accordingly.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
