### PR TITLE
Update qladdict to 1.2

### PR DESCRIPTION
**Pull request by tattali**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
> caveats should be used sparingly and exclusively for installation-related matters

https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md

**Review by vitorgalvao — APPROVED** [review]

**Comment by vitorgalvao** [comment]
> > caveats should be used sparingly and exclusively for installation-related matters
>
> https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md

Yep. Otherwise people ignore them.

**Comment by tattali** [comment]
For me, it was "installation-related matters"
But I fully understand the reasons so you can merge it.

**Comment by vitorgalvao** [comment]
> For me, it was "installation-related matters"

A theme does not prevent you from installing and using the plugin.

**Pull request merged**
