### PR TITLE
Add vAmiga.app v1.0

### PR DESCRIPTION
**Pull request by sunfl0wer**
This is the first release of vAmiga with non-beta status.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask {{cask_file}}` is error-free.
- [X] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [X] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [X] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [X] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [X] `brew audit --new-cask {{cask_file}}` worked successfully.
- [X] `brew install --cask {{cask_file}}` worked successfully.
- [X] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @sunfl0wer.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by sunfl0wer** [comment]
I had to make a new pull request for adding the zap stanza:

https://github.com/Homebrew/homebrew-cask/pull/105923

Hope this is ok.

**Comment by SMillerDev** [comment]
Why make a new PR for the zap? You can just push to this branch again

**Comment by sunfl0wer** [comment]
I apologize if I did something wrong. I followed the instructions under https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#following-up

> git checkout vamiga
> git rebase --interactive origin/master
> git push --force

But it gives me this error:

"fatal: The current branch vamiga has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin vamiga"

After doing 

> git push --set-upstream origin vamiga

I get this error message:

"remote: Permission to Homebrew/homebrew-cask.git denied to sunfl0wer.
fatal: unable to access 'https://github.com/Homebrew/homebrew-cask/': The requested URL returned error: 403"

This is the first time I'm using git (and I think that's obvious ;-). I just don't know what to do.

The only thing that worked for me were the instructions under https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#submitting-your-changes

Sorry again. Maybe someone can help me with this?

**Comment by vitorgalvao** [comment]
Closing in favour of the other PR.

**Pull request closed without merging**
