### PR TITLE
add fugenschnitzer cask

### PR DESCRIPTION
**Pull request by githubutilities**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
It’s still not following the format. Do you need help with it?

**Comment by githubutilities** [comment]
Yes. I don't know how to make the url to follow the convention while I want to download the specific file in that project.

**Comment by vitorgalvao** [comment]
[Like so](https://github.com/caskroom/homebrew-cask/pull/11232). Thank you for the contribution. I’ll fix it in the mentioned PR. Your contribution is still included (and still credited to you), with the appropriate modifications.

**Comment by githubutilities** [comment]
How do you find that URL?

**Comment by vitorgalvao** [comment]
Look for the **bold**s in the explanation.

1. I copied yours and looked for the projects’s name

> sourceforge.net/projects/**fugenschnitzer**/files/Fugenschnitzer/0.8%20beta%202/fugenschnitzer_08b2_macosx_i386_en.dmg

2. Looked for the file’s name

> sourceforge.net/projects/fugenschnitzer/files/Fugenschnitzer/0.8%20beta%202/**fugenschnitzer_08b2_macosx_i386_en.dmg**

3. Copied [the format](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#sourceforge-urls)

> http://downloads.sourceforge.net/sourceforge/$PROJECTNAME/$FILENAME.$EXT

4. Replaced `$PROJECTNAME` with the one gotten from your url.

> http://downloads.sourceforge.net/sourceforge/**fugenschnitzer**/$FILENAME.$EXT

5. Did the same for the file’s name

> http://downloads.sourceforge.net/sourceforge/fugenschnitzer/**fugenschnitzer_08b2_macosx_i386_en.dmg**

6. Tried to download it. It worked.

**Comment by githubutilities** [comment]
Thanks for the tip.

**Pull request closed without merging**
