### PR TITLE
Update cask to reflect changes in multipass 0.6.0

### PR DESCRIPTION
**Pull request by joedborg**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Review by vitorgalvao — APPROVED** [review]

**Comment by joedborg** [comment]
@vitorgalvao Any idea why the `+` is being replaced with a ` `?

**Comment by vitorgalvao** [comment]
> @vitorgalvao Any idea why the `+` is being replaced with a ` `?

Because `+` isn’t part of the name, it’s a URL encoding of a space (like `%20`).

**Review by vitorgalvao — APPROVED** [review]

**Comment by vitorgalvao** [comment]
> installer: Error - Your CPU does not have the features necessary for Multipass. Installation cannot proceed.

Now it’s working (i.e. erroring out as it was supposed to).

**Comment by joedborg** [comment]
Thanks @vitorgalvao!

**Comment by Saviq** [comment]
Thanks @joedborg @vitorgalvao :)

**Pull request merged**
