### PR TITLE
hhkb-studio 1.0.4 (new cask)

### PR DESCRIPTION
**Pull request by yhirano**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

See: About naming this cask.
https://github.com/Homebrew/homebrew-cask/pull/170731#issuecomment-2040848285

### CODE REVIEW

**Comment by bevanjkay** [comment]
Thank you for your contribution to `homebrew-cask`, @yhirano 
I believe this application already exists here - https://github.com/Homebrew/homebrew-cask/blob/master/Casks/h/hhkb.rb

**Comment by razvanazamfirei** [comment]
I think they're technically different. Our current cask is `Happy Hacking Keyboard Keymap Tool` and this is `Happy Hacking Keyboard Studio Keymap Tool`. I'm not sure what the best way to disambiguate the two. Perhaps calling this cask `hhkb-studio`?

**Comment by yhirano** [comment]
Thank you for the review of this pull request!

As pointed out, this pull request is a cask for `Happy Hacking Keyboard **Studio** Keymap Tool`, which is a different tool from `Happy Hacking Keyboard Keymap Tool`([hhkb](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/h/hhkb.rb)).
This cask is a tool for customize [Happy Hacking Keyboard Keyboard **Studio**](https://hhkeyboard.us/hhkb-studio), and [hhkb](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/h/hhkb.rb) is a tool for customize [Happy Hacking Keyboard](https://hhkeyboard.us/hhkb).

> I'm not sure what the best way to disambiguate the two. Perhaps calling this cask hhkb-studio?

`hhkb-studio-keymap-tool` is named by the generate_cask_token script, but I would also like to rename it to `hhkb-studio` if possible.
If renaming is allowed, I will update this cask.

**Comment by bevanjkay** [comment]
I think keep this consistent with the existing cask makes sense.

**Comment by yhirano** [comment]
Renamed `hhkb-studio-keymap-tool` to `hhkb-studio`.

**Review by bevanjkay — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
