### PR TITLE
Update popo to 2.6.7

### PR DESCRIPTION
**Pull request by SteamedFish**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by SteamedFish** [comment]
popo sometimes updates its dmg (and build number) without update its version number. 

I don't know if it is the correct way to submit like this.

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Since `sha256` was updated but `version` stayed the same, this change needs to be verified. Please [follow the instructions to do so](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256).

**Comment by SteamedFish** [comment]
popo doesn't have Signature Info section. Is this means that the only way to verify is to get developer's confirmation?

popo updates its build pretty frequently, but it does not update its version number very often. 

does this means that i have to get developer's confirmation everytime popo update its build number？

the build number is at popo's about menu. There's no build number on the download URL。can I include the build number as part of the version number？

**Comment by vitorgalvao** [comment]
> can I include the build number as part of the version number？

Yes.

**Comment by SteamedFish** [comment]
I have updated my pull requests with build number included.
popo updated with a new build number today, so I have updated with a new sha256.

**Pull request merged**
