### PR TITLE
Add DeepL latest

### PR DESCRIPTION
**Pull request by HeadFox**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].
- [x] Attempted to find an [appcast].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[appcast]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

### CODE REVIEW

**Comment by reitermarkus** [comment]
Please have a look at https://github.com/Homebrew/homebrew-cask/issues/69000. Can you check if `quit` does what it is supposed to?

cc @schwedenmut

**Comment by HeadFox** [comment]
Yes quitting was perfectly working :) 
Firstly I forgot to add the status bar kill and it caused problems but now all processes are perfectly killed and new installation is possible.

**Comment by schwedenmut** [comment]
Hey @HeadFox, so I just installed DeepL with your code. That works. Version 1.0.1 has been installed. After that I started DeepL - so far it works, too.
But if you then run DeepL and run `brew cask uninstall deepl` while it is running, both the status bar service and the input field will continue to run until closed manually by the user.
Bildschirmfoto 2019-09-14 um 11 07 37-fs8

So there seems to be the same problem as with my (not yet pushed) cask - as described in the given issue, or am I missing something @reitermarkus ?

**Comment by HeadFox** [comment]
That's strange that you don't have the quitting line @schwedenmut 
image

**Comment by schwedenmut** [comment]
hmpf, that really is strange 🤔

**Comment by reitermarkus** [comment]
As I understand it, 

`launchctl list | grep com.linguee`

outputs nothing for @schwedenmut.

**Comment by reitermarkus** [comment]
Should be fixed with https://github.com/Homebrew/brew/pull/6457.

**Comment by HeadFox** [comment]
Can you confirm it works again for you @schwedenmut ?

**Comment by HeadFox** [comment]
Between I wanted to know what's the best between a versionned config package : #69102 and a latest config package ?
cc @reitermarkus

**Comment by schwedenmut** [comment]
> Can you confirm it works again for you @schwedenmut ?

@HeadFox I sure can confirm that quitting now works with the changes y @reitermarkus 🎉

**Comment by reitermarkus** [comment]
@HeadFox, versioned is preferred, so closing this in favour of https://github.com/Homebrew/homebrew-cask/pull/69102.

**Pull request closed without merging**
