### PR TITLE
superproductivity fix sha256 sums

### PR DESCRIPTION
**Pull request by thetric**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

Looks like the release binaries have changed: https://github.com/johannesjo/super-productivity/releases/tag/v8.0.0

### CODE REVIEW

**Comment by bevanjkay** [comment]
Can you open an issue to check that upstream updates the binaries without creating a new tag?

**Comment by p-linnane** [comment]
Please create an issue and ask upstream about this change: https://github.com/johannesjo/super-productivity/issues

**Comment by thetric** [comment]
See https://github.com/johannesjo/super-productivity/discussions/3026

**Review by p-linnane — APPROVED** [review]
Thank you very much for getting confirmation and taking the initiative to fix this!

**Pull request merged**
