### PR TITLE
Upgrade wechat from 2.4.2.17 to 2.4.2.18

### PR DESCRIPTION
**Pull request by alswl**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by alswl** [comment]
Due to Tencent Wechat upgrade policies, the Mainland China will have early release version than other regions **MAYBE**.

So I got the new version 2.4.2.18, and others regions got 2.4.2.17.

```
# request from Mainland China
~ $ http https://dldir1.qq.com/weixin/mac/mac-release.xml | grep 2.4.2.18
<title>2.4.2.18</title>
<h2>2.4.2.18</h2>
<h2>2.4.2.18</h2>
<h2>2.4.2.18</h2>
sparkle:version="15063" sparkle:shortVersionString="2.4.2.18"

# request from Japan
~ $ H http https://dldir1.qq.com/weixin/mac/mac-release.xml | grep 2.4.2.17
<title>2.4.2.17</title>
<h2>2.4.2.17</h2>
<h2>2.4.2.17</h2>
<h2>2.4.2.17</h2>
sparkle:version="15039" sparkle:shortVersionString="2.4.2.17"

```

Is there any solution for this upgrade case?
Maybe hold this PR for a few days?

**Comment by alswl** [comment]
discus:

- https://github.com/Homebrew/homebrew-cask/pull/82711#issuecomment-629701833
- https://github.com/Homebrew/homebrew-cask/pull/70351#issuecomment-540545744
- https://github.com/Homebrew/homebrew-cask/pull/66774#issuecomment-515422488

**Comment by ran-dall** [comment]
@alswl Give it a few days but if it doesn't change then you'd have to use `latest` and `no_check`

**Comment by core-code** [comment]
as @ran-dall mentioned using  `latest /  no_check` would be a solution. i guess we could also use country-codes to work around the problem here. basically i think this is tencents fault here - handing out different files for exactly the same URL depending on the country of the request doesn't seem like a sane solution.

**Comment by alswl** [comment]
(2020-07-28 10:09 +08) The version is still 2.4.2.17 in Japan region now.

**Comment by alswl** [comment]
Now, the CDN content is delivered.
Is there any comment to trigger the CI bots run again?

**Comment by alswl** [comment]
Version was upgrade by PR https://github.com/Homebrew/homebrew-cask/pull/86761

**Pull request closed without merging**
