### PR TITLE
Readd yabumi.rb

### PR DESCRIPTION
**Pull request by winkelsdorf**
Reverts single removal from PR #65722.

### CODE REVIEW

**Comment by core-code** [comment]
since you've reverted this... does it install for you?

```
==> Downloading external files for Cask yabumi
==> Downloading https://yabumi.cc/download/Yabumi.dmg

curl: (22) The requested URL returned error: 403 
Error: Download failed on Cask 'yabumi' with message: Download failed: https://yabumi.cc/download/Yabumi.dmg

```

**Comment by winkelsdorf** [comment]
@core-code Indeed it did. I just tried it for you and it works from my location:

```shell
Last login: Sat Sep 28 16:20:38 on console
[winkelsdorf:...pplication Support/dotfiles]$ brew cask install yabumi --force       
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 4 taps (homebrew/cask-versions, homebrew/core, homebrew/cask and homebrew/cask-drivers).
==> Updated Formulae
recon-ng

==> Satisfying dependencies
==> Downloading https://yabumi.cc/download/Yabumi.dmg
######################################################################## 100.0%
==> No SHA-256 checksum defined for Cask 'yabumi', skipping verification.
==> Installing Cask yabumi
Warning: It seems there is already an App at '/Applications/Yabumi.app'; overwriting.
==> Removing App '/Applications/Yabumi.app'.
==> Moving App 'Yabumi.app' to '/Applications/Yabumi.app'.
🍺  yabumi was successfully installed!
[winkelsdorf:...pplication Support/dotfiles]$ 
```

**Comment by core-code** [comment]
ok thanks for the quick confirmation. must be something weird at my end

**Comment by winkelsdorf** [comment]
@core-code You're welcome! Yeah, likely something with your internet connection..

**Comment by core-code** [comment]
really unsure about that since i've seen it across 3 countries in the past weeks ;)

**Comment by winkelsdorf** [comment]
Or the other way round: Many websites use Cloudflare or similar services, they might block the download from your locations for mysterious reasons? 🤔

**Comment by core-code** [comment]
it seems you are right, and i am on a cloudflare shitlist


```

curl -vvvv https://yabumi.cc/download/Yabumi.dmg
[…]
            <h2 data-translate="what_happened">What happened?</h2>
            <p>This website is using a security service to protect itself from online attacks.</p>

```

so, sorry for the noise there!

**Comment by winkelsdorf** [comment]
Nevermind, wouldn't be the first thing that came to mind mind, too. Sorry to hear, they blocked you :(

**Pull request merged**
