### PR TITLE
font-playwrite (new cask)

### PR DESCRIPTION
**Pull request by Aaron-212**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=pullrequests).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

Only several regional variants of Playwrite font is included in the Google Fonts repo. This cask is for the full family.
The cask didn't pass the notability threshold.

### CODE REVIEW

**Comment by bevanjkay** [comment]
The need to install all of these feels a bit obscure to me, for it to be included in `homebrew-cask`. 

If you're planning to use it personally it be better suited for your own tap.

**Comment by Aaron-212** [comment]
> The need to install all of these feels a bit obscure to me, for it to be included in `homebrew-cask`.
> 
> If you're planning to use it personally it be better suited for your own tap.

What about only the non-regional fonts?

```ruby
  font "variable/Playwrite[SPED,YEXT,slnt,wght].ttf"
  font "ttf/Playwrite-ExtraLight.ttf"
  font "ttf/Playwrite-ExtraLightItalic.ttf"
  font "ttf/Playwrite-Italic.ttf"
  font "ttf/Playwrite-Light.ttf"
  font "ttf/Playwrite-LightItalic.ttf"
  font "ttf/Playwrite-Maximum.ttf"
  font "ttf/Playwrite-Regular.ttf"
  font "ttf/Playwrite-Thin.ttf"
  font "ttf/Playwrite-ThinItalic.ttf"
```

**Comment by bevanjkay** [comment]
It still doesn't meet the notability requirements, sorry.

**Comment by Aaron-212** [comment]
> It still doesn't meet the notability requirements, sorry.

All right

**Pull request closed without merging**
