### PR TITLE
Update studio-3t to 5.2.2

### PR DESCRIPTION
**Pull request by revolter**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Welcome, @revolter,

Travis CI detected a few errors that should have been caught by `audit` and `style --fix` commands. I’ve already fixed them.

Next time you make a submission, please double check those before ticking the boxes. We need to know it the error messages aren’t clear enough — which made you miss them — and we need to improve them. Alternatively, if no error messages were shown it means there’s something wrong we need to fix.

It’s important to ensure those commands work correctly as they save both CI time and maintainer time.

Thank you for the contribution!

**Comment by revolter** [comment]
Well, I didn't know the process exactly, I just looked at the previous studio-3t update PR and saw that I have to run some commands.

I updated the version, manually downloaded the software, computed its sha256 and updated the spec. I then ran the `audit` command and it threw:

    audit for studio-3t: warning
     - appcast checkpoint mismatch
    Expected: first sha
    Actual: second sha
    Error: audit failed for casks: studio-3t

but I cleared the terminal and I don't know the exact SHAs. So I downloaded the changelog from http://files.studio3t.com/changelog/changelog.txt and added its SHA in the file. I ran the command again and it threw:

    ==> Downloading https://download.studio3t.com/studio-3t/mac/5.2.2/Studio-3T.dmg
    Already downloaded: /Users/iulian/Library/Caches/Homebrew/Cask/studio-3t--5.2.2.dmg
    ==> Verifying checksum for Cask studio-3t
    audit for studio-3t: warning
     - appcast checkpoint mismatch
    Expected: 627e9f98d4c76f038172125a0f95ac92c3db47e73f8ed1ded8505a8983928935
    Actual: 78ff051d040ab2537f8275e59975d9e598431d9f63530ec0492a42cd8c3cb8be
    Error: audit failed for casks: studio-3t

and I thought it's a caching problem. So I ran `brew cask cleanup` and tried again, and this time it redownloaded the app but still threw:

    ==> Downloading https://download.studio3t.com/studio-3t/mac/5.2.2/Studio-3T.dmg
    ######################################################################## 100.0%
    ==> Verifying checksum for Cask studio-3t
    audit for studio-3t: warning
     - appcast checkpoint mismatch
    Expected: 627e9f98d4c76f038172125a0f95ac92c3db47e73f8ed1ded8505a8983928935
    Actual: 78ff051d040ab2537f8275e59975d9e598431d9f63530ec0492a42cd8c3cb8be
    Error: audit failed for casks: studio-3t

so, if it expected the `627e...` SHA, I thought I messed something up and put that in the file.

**Comment by vitorgalvao** [comment]
@revolter “Expected” is whatever is already in the cask. “Actual” is the actual value. So you should’ve replaced it with the “Actual” for the `audit` to pass.

You were also looking in the wrong place. `appcast` is a different thing: [docs](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

**Comment by revolter** [comment]
I see, but I think that's confusing, as the english meaning already suggests. The expected value should be at the "Expected" key, don't you agree?

**Comment by vitorgalvao** [comment]
> I see, but I think that's confusing, as the english meaning already suggests. The expected value should be at the "Expected" key, don't you agree?

Not really. I do agree it’s ambiguous, but not that reversing those would remove the ambiguity. The key is that *the `audit` expected* a certain value to pass, but in actuality got another. We haven’t got any other complaints on this, so it’s clearly not a huge issue.

But the box you checked mentions the `audit` was error free, but it was not. It’s absolutely fine to still make the submission, but if instead of ticking the box you mentioned “I’m getting this error but I’m not sure what is wrong” that would’ve been better.

Either way, the contribution is appreciated. Again, welcome!

**Comment by revolter** [comment]
Right, you're correct. Sorry about that, I was in a hurry, didn't work with this repository at all before and just wanted to contribute this as soon as possible.

**Pull request merged**
