### PR TITLE
Add Timeless 2020.6

### PR DESCRIPTION
**Pull request by vladimyr**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Unfortunately, appcenter URLs are a pain to maintain and break all the time. Until we find a way to deal with those, I’d rather not add more casks that depend on it.

Also, while we appreciate all the submissions, please only submit new casks if they are for relatively popular software or if you use them yourself. That is to say, we don’t want a cask for something just because that something exists. Adding casks increases the maintenance burden, and it it’s for something that nobody will use, they’ll become a very real waste of volunteer time.

**Comment by vladimyr** [comment]
> Unfortunately, appcenter URLs are a pain to maintain and break all the time. Until we find a way to deal with those, I’d rather not add more casks that depend on it.

TBH it looked suspicious to me but I decided to give it a go after seeing https://github.com/Homebrew/homebrew-cask/blob/ea02552/Casks/hook.rb#L5-L9
Roger that 👍 

> Also, while we appreciate all the submissions, please only submit new casks if they are for relatively popular software or if you use them yourself. That is to say, we don’t want a cask for something just because that something exists. Adding casks increases the maintenance burden, and it it’s for something that nobody will use, they’ll become a very real waste of volunteer time.

Fair enough 👍 Personally I submit casks for the following reasons:
1. I'm using it myself
2. I've spotted it on Show HN/Reddit, Product Hunt, Github trends or awesome list
3. I find it neat & useful and doing it to help spread the word and/or increase adoption

Timeless is _silly_ little app that scored pretty well on Product Hunt: https://www.producthunt.com/posts/timeless-5
Due to these unfortunate global circumstances, we are all experiencing, it became quite useful 🙃 
https://www.dangercove.com/news/working-from-home-with-timeless/

Rest assured that I'm not in the business of putting additional pressure on maintainers back 😉

**Comment by vitorgalvao** [comment]
> I decided to give it a go after seeing

For casks that were already in and changed to to appcenter URLs, we’re allowing them to see how they work.

> Personally I submit casks for the following reasons:
> 1. I'm using it myself

That’s fine.

> 2. I've spotted it on Show HN/Reddit, Product Hunt, Github trends or awesome list

Also fine, *as long as* it’s getting traction. Considering the audience those sites serve, if an app is getting popular fast and you have a reasonable feeling it would be submitted to HBC anyway, fell free to do so. In those cases I’d even prefer if you did, because your submissions have been really good and I’d rather get a good submission than one I’ll have to fix. That’s *time saving*.

> 3. I find it neat & useful and doing it to help spread the word and/or increase adoption

That‘s the one that goes counter to our goals, because [we don’t want to be a discoverability service](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md) (one of our oldest rules).

We only want to include things people already know about and will support, otherwise we get a bunch of dead outdated software.

> Timeless is _silly_ little app that scored pretty well on Product Hunt: https://www.producthunt.com/posts/timeless-5
> Due to these unfortunate global circumstances, we are all experiencing, it became quite useful
> https://www.dangercove.com/news/working-from-home-with-timeless/

To be clear, the *sole* reason for rejecting this submission was the appcenter URL. Had it used something else, I’d have made the comment but accepted it anyway, as I did the others you submitted at the same time.

> Rest assured that I'm not in the business of putting additional pressure on maintainers back

It never once crossed my mind that you’d do it on purpose. Good contributors don’t tend to!

**Comment by JounQin** [comment]
@miccal @vitorgalvao 

I've just write a service to get the appcenter download link dynamically, https://appcenter.vercel.app/dangercove/timeless/2020.7,37 for Timeless, for example.

The source code is at https://github.com/rx-ts/appcenter.

I'm wondering can we use this service as the stable app url?

**Comment by vitorgalvao** [comment]
> I'm wondering can we use this service as the stable app url?

Thank you for the offer, but no. We only use official links.

**Comment by JounQin** [comment]
> > I'm wondering can we use this service as the stable app url?
> 
> Thank you for the offer, but no. We only use official links.

OK, that's fine, I can still use it as via custom tap.

**Comment by JounQin** [comment]
@vitorgalvao I have another approach, add a custom download strategy for AppCenter:

https://github.com/homebrew-x/homebrew-x/blob/master/shared/appcenter_download_strategy.rb

No third-party service required anymore, what do you think about it?

**Comment by vitorgalvao** [comment]
Ping @reitermarkus.

**Context:** appcenter URLs are a pain to maintain and break all the time.
**Possible solution:** https://github.com/Homebrew/homebrew-cask/pull/79549#issuecomment-735386385.

**Comment by JounQin** [comment]
@reitermarkus @vitorgalvao Any news?

**Comment by Loyalsoldier** [comment]
I think AppCenter appcast is good enough for maintaining. Just a XML file to be parsed. Isn't it?

FYI, I also filed a PR https://github.com/Homebrew/homebrew-cask/pull/100105 to add ClashX Pro and it is closed.

**Comment by JounQin** [comment]
@Loyalsoldier I came from that PR, and am using this approach at https://github.com/homebrew-x/homebrew-x/blob/master/Casks/clashx-pro.rb.

**Comment by vitorgalvao** [comment]
> I think AppCenter appcast is good enough for maintaining. Just a XML file to be parsed. Isn't it?

I don’t remember *how* they’re bad to maintain, but complaint is never the appcast’s content, it’s its URL.

An HBC user who worked at Microsoft close (or at) this division was supposed to look into it, but nothing ever came of it.

**Pull request closed without merging**
