### PR TITLE
Add BlueBubbles 1.3.0

### PR DESCRIPTION
**Pull request by jawshooah**
Note that `brew audit --new-cask bluebubbles` and `brew style --fix bluebubbles` are both failing locally with an error seemingly related to system Ruby:

<details>
<summary>`brew audit --new-cask bluebubbles`</summary>
```
➜  homebrew-cask git:(bluebubbles) brew audit --new-cask bluebubbles
==> Installing 'bundler' gem
Error: incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/api_set.rb:118:in `load'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/api_set.rb:118:in `versions'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/api_set.rb:55:in `find_all'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/composed_set.rb:55:in `block in find_all'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/composed_set.rb:54:in `map'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/composed_set.rb:54:in `find_all'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/best_set.rb:31:in `find_all'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/installer_set.rb:155:in `find_all'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/installer_set.rb:56:in `add_always_install'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency_installer.rb:478:in `resolve_dependencies'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency_installer.rb:385:in `install'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:635:in `install'
/usr/local/Homebrew/Library/Homebrew/utils/gems.rb:88:in `install_gem!'
/usr/local/Homebrew/Library/Homebrew/utils/gems.rb:106:in `install_gem_setup_path!'
/usr/local/Homebrew/Library/Homebrew/utils/gems.rb:123:in `install_bundler!'
/usr/local/Homebrew/Library/Homebrew/utils/gems.rb:138:in `install_bundler_gems!'
/usr/local/Homebrew/Library/Homebrew/style.rb:86:in `run_rubocop'
/usr/local/Homebrew/Library/Homebrew/style.rb:54:in `check_style_impl'
/usr/local/Homebrew/Library/Homebrew/style.rb:36:in `check_style_json'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:175:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```
</details>

<details>
<summary>`brew style --fix bluebubbles`</summary>
```
➜  homebrew-cask git:(bluebubbles) brew style --fix bluebubbles
==> Installing 'bundler' gem
Error: incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/api_set.rb:118:in `load'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/api_set.rb:118:in `versions'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/api_set.rb:55:in `find_all'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/composed_set.rb:55:in `block in find_all'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/composed_set.rb:54:in `map'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/composed_set.rb:54:in `find_all'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/best_set.rb:31:in `find_all'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/installer_set.rb:155:in `find_all'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/resolver/installer_set.rb:56:in `add_always_install'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency_installer.rb:478:in `resolve_dependencies'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency_installer.rb:385:in `install'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:635:in `install'
/usr/local/Homebrew/Library/Homebrew/utils/gems.rb:88:in `install_gem!'
/usr/local/Homebrew/Library/Homebrew/utils/gems.rb:106:in `install_gem_setup_path!'
/usr/local/Homebrew/Library/Homebrew/utils/gems.rb:123:in `install_bundler!'
/usr/local/Homebrew/Library/Homebrew/utils/gems.rb:138:in `install_bundler_gems!'
/usr/local/Homebrew/Library/Homebrew/style.rb:86:in `run_rubocop'
/usr/local/Homebrew/Library/Homebrew/style.rb:54:in `check_style_impl'
/usr/local/Homebrew/Library/Homebrew/style.rb:16:in `check_style_and_print'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/style.rb:75:in `style'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```
</details>
---
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thanks @jawshooah.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by jawshooah** [comment]
> Thanks @jawshooah.
> 
> Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

Done, and bumped to 1.3.0

**Review by miccal — APPROVED** [review]

**Comment by zlshames** [comment]
Hey guys, BlueBubbles maintainer here. First off, thanks for getting this onto Homebrew! I also noticed that the uninstall stanza does not include the log folder. Is that a directory that's typical to delete on uninstall?

**Comment by jawshooah** [comment]
Hey @zlshames, things like logs typically go in the `zap` stanza. Does that cover what you had in mind, or did I miss something?

**Comment by zlshames** [comment]
Sorry for the late reply. Yep, the `zap` uninstall stanza. Not sure if it's typical for the log files to be removed, but if that's the code, then the two paths for logs are the following:

* `~/Library/Logs/@bluebubbles`
* `~/Library/Logs/bluebubbles-server`

The first path is actually the "default" but I manually override it in the code. It will be empty.

**Comment by jawshooah** [comment]
@zlshames Cool beans, I believe [this](https://github.com/Homebrew/homebrew-cask/pull/130976/files#diff-dee939e3397bc2f8577af0f1f9fb42b57245291a2d4a9bb98ac187142b64751cR27-R28) should cover it but feel free to PR any changes!

**Comment by zlshames** [comment]
> @zlshames Cool beans, I believe [this](https://github.com/Homebrew/homebrew-cask/pull/130976/files#diff-dee939e3397bc2f8577af0f1f9fb42b57245291a2d4a9bb98ac187142b64751cR27-R28) should cover it but feel free to PR any changes!

Yup, it does, thanks!

**Pull request merged**
