### PR TITLE
Remove netbeans casks

### PR DESCRIPTION
**Pull request by vitorgalvao**
See conversation in https://github.com/caskroom/homebrew-cask/issues/30801.

On hold to see if anyone complains.

### CODE REVIEW

**Comment by reitermarkus** [comment]
> On hold to see if anyone complains.

Not complaining, since I'm not using NetBeans, but `netbeans` installed fine, although it did *kinda* call a GUI:

bildschirmfoto 2017-04-24 um 20 32 18

**Comment by vitorgalvao** [comment]
@reitermarkus That’s a valid datapoint, nevertheless. Which one did you install?

**Comment by commitay** [comment]
I tried`netbeans` again and it installs if I switch to `master` instead of a tag release.

**Comment by gobinathm** [comment]
I use netbeans day to day.  I tried a fresh install with HBW & did not face any issue.

**Comment by reitermarkus** [comment]
> Which one did you install?

The “default” one, `netbeans`.

**Comment by claui** [comment]
No strong opinion on removing the cask; however, installation works for me.

image

**Comment by vitorgalvao** [comment]
Weird that it’s failing for some people, but since this is clearly isn’t widespread, might as well close the issue. Thank you, everyone.

**Pull request closed without merging**
