### PR TITLE
Update mediathekview from 13.3.0 to 13.5.0

### PR DESCRIPTION
**Pull request by optikfluffel**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by optikfluffel** [comment]
Mediathekview now uses a little `MediathekView Shutdown Helper`, which makes it necessary to copy a directory including two `.app` files. Could someone give me a hint on how to do that in a Cask?

**Review by vitorgalvao — APPROVED** [review]

**Comment by Mikro-Molch** [comment]
Hi optikfluffel,

downloading the following dmg-file I receive a file with a differing checksum:

- - - - - - - - - - - - - -  -   -
cask 'mediathekview' do
  version '13.5.0'
  sha256 'efaccc25cd5bc9cefb3249868bed22d46de2309d1ae46d834face79b6950e02f'

  url "https://download.mediathekview.de/stabil/MediathekView-#{version}-mac.dmg"

- - - - - - - - - - - - - -  -   -

When I double-download and double-verify
https://download.mediathekview.de/stabil/MediathekView-13.5.0-mac.dmg

»my« sha256 checksum is:
sha256 'ac634ab0383270e61ed1fe91905c0f5c8dfa8a15408d1471ed1b2669974d07bd'

Could you please check your mentioned checksum?

Best regards

Mikro-Molch

**Comment by optikfluffel** [comment]
@Mikro-Molch You're right, it changed to `ac634ab0383270e61ed1fe91905c0f5c8dfa8a15408d1471ed1b2669974d07bd`. I wrote the Mediathekview dev(s) an email to get a clue about what's up with that. I'll come back to you as soon as I get an answer.

**Comment by optikfluffel** [comment]
@Mikro-Molch They had to re-sign the app for the new macOS release, so the change was intended.

**Comment by Mikro-Molch** [comment]
@optikfluffel Thanx a lot for your good support!

**Pull request merged**
