### PR TITLE
Add clarinet 0.12.0

### PR DESCRIPTION
**Pull request by CharlieC3**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by cho-m** [comment]
Given that this is a binary with open-source license, have you considered submitting it as a Formula in https://github.com/Homebrew/homebrew-core/ ?

**Comment by CharlieC3** [comment]
> Given that this is a binary with open-source license, have you considered submitting it as a Formula in https://github.com/Homebrew/homebrew-core/ ?

Hi @cho-m, indeed I have. Building this project from source takes quite a while for a single binary -- upwards of 5+ minutes of downloading, compiling, and fans spinning.

After discussing with the lead dev behind `clarinet`, I thought it would be best to instead first submit it as a Cask since it takes seconds to install and provides a better overall user experience. I know this goes against what's suggested in the docs, but given the intense install thought it might be eligible for an exception.

**Comment by cho-m** [comment]
When a Formula is added to homebrew-core, we generate pre-built "bottles" for the most common/recent macOS (right now from Mojave to Big Sur). This is what is installed when user runs `brew install ...` as long as they are on a supported OS. It should be pretty quick to install for users.

A lot of our Formulae would normally take a long time to build (some take a couple hours), which is part of reason why our CI nodes create the pre-builts.

**Comment by CharlieC3** [comment]
Interesting, I did not know that. I'm reading up on this now, thanks for the info!

Assuming I don't find any issues getting it to build as a Formula, I think you're right about submitting it there. I'll close this PR for now and reopen it if I hit any blockers trying that method.

**Pull request closed without merging**
