### PR TITLE
Update insomnia to 5.14.3

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
According to https://github.com/getinsomnia/insomnia/releases/ 5.14.3 is the latest stable

**Comment by commitay** [comment]
`5.14.6` is the current download on the homepage.

**Comment by brianmorton** [comment]
@commitay i agree, but they are clearly marked pre-release on github... so we can either keep on pre-release and this can be for 5.14.7 or go to stable? Or ask the devs?

**Comment by commitay** [comment]
I think what they publish on their homepage is usually the best indicator as to what version they want users to have.

**Comment by vitorgalvao** [comment]
[From `adding_a_cask.md`](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version) (emphasis added):

> When an App is only available as beta, development, or unstable versions, **or in cases where such a version is the general standard**, then said version can go into the main repo.

The version linked to in the main page matter most.

**Comment by commitay** [comment]
When upstream moved to github releases I changed the appcast over as well but the original seems to be more accurate. 

https://insomnia.rest/changelog/index.xml

**Comment by brianmorton** [comment]
Alright I'll just blacklist this cask since it doesn't follow the usual rules.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/43965

**Pull request closed without merging**
