### PR TITLE
Add Color Studio.app v1.0.4

### PR DESCRIPTION
**Pull request by malob**
After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by p-linnane** [comment]
Thank you for your contribution to `homebrew-cask` @malob. Please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap) for this cask.

**Comment by malob** [comment]
@p-linnane, I ran `brew createzap color-studio` when adding the Cask and it didn't find anything. Is that enough?

**Comment by p-linnane** [comment]
Yep that'll do. I just pushed a commit with a comment stating it's not required. Thanks!

**Comment by malob** [comment]
Actually I just found some stuff!

**Review by p-linnane — DISMISSED** [review]

**Review by p-linnane — APPROVED** [review]
Thanks for all your work here @malob!

**Pull request merged**
