### PR TITLE
updated yate (3.13.0.2)

### PR DESCRIPTION
**Pull request by reitermarkus**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by adidalal** [comment]
Not getting the same as you here.

```
-  sha256 '6611b12ef7336e1add86e35345aa2605fde79248c23354736a14384482a72eff'
+  version '3.13.0.2'
+  sha256 'a877df051f1d93086f1bd28617419dc05bd2a6d9f1c5c7c120a7359c5daa991e'
```

**Comment by reitermarkus** [comment]
The `sha256` is confirmed locally as I have downloaded it manually. But the problem is, that the site it “protected” by SiteLock. It shows a captcha when you first visit the site (only if your computer is considered infected, which apparently is always the case when you're using `curl`).

**Comment by vitorgalvao** [comment]
Might be best to just remove the `appcast`. If we can’t reliably check it, it’s worth nothing to us.

**Comment by reitermarkus** [comment]
@vitorgalvao, the problem is not (just) the appcast, it's the whole “protected by SiteLock” thing. The only thing you get with `curl` is the captcha page.

**Comment by fanquake** [comment]
Any consensus on what should happen here?

**Comment by reitermarkus** [comment]
I'm fine with removing it, as I don't think there's a way to bypass SiteLock.

**Comment by adidalal** [comment]
Yep 💀

**Comment by decrement** [comment]
It seems like replacing `user_agent: :fake` with `using: :post` worked on my side. Please verify and it may be the viable solution!

**Pull request closed without merging**
