### PR TITLE
Update home-assistant from 2020.7,3 to 2020.7,5

### PR DESCRIPTION
**Pull request by gmcinalli**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
version '2020.7,5' is marked as a pre-release in their Github release page.

**Comment by gmcinalli** [comment]
@core-code Yes, it's true, but also the `2020.7,3` that has been merged some days ago (https://github.com/Homebrew/homebrew-cask/pull/90028), is a pre-release version: [link](https://github.com/home-assistant/iOS/releases/tag/release%2F2020.7%2F3).

**Comment by core-code** [comment]
yes i've seen that and am not happy about that. in any case, previous errors should not justify continuing to make errors. 

basically we don't want pre-release versions in Homebrew Cask, exept for Casks where no stable version exists. is there a 'official/stable' version for 'home-assistant'?

**Comment by gmcinalli** [comment]
> yes i've seen that and am not happy about that. in any case, previous errors should not justify continuing to make errors.
> 
> basically we don't want pre-release versions in Homebrew Cask, exept for Casks where no stable version exists.
> 
> is there a 'official/stable' version for 'home-assistant'?

Seems legit to me, at this moment a stable version of HomeAssistant is not yet available.

**Comment by core-code** [comment]
if there is no stable version, an exception can be made

**Pull request merged**
