### PR TITLE
Rename the cask for iBank to Banktivity

### PR DESCRIPTION
**Pull request by mauricerkelly**
The version number, 5, remains the same, but the name and URL has
been updated. Additionally, I tested the URLs for the old versions
of the app (for Leopard and Lion), and they now report 404 Not Found.

### CODE REVIEW

**Comment by mauricerkelly** [comment]
Hope this approach was the right one.

**Comment by mauricerkelly** [comment]
Also - anything else needing added these days to keep the cask format up to date?

**Comment by vitorgalvao** [comment]
> anything else needing added these days to keep the cask format up to date?

Yes, you need to use the [correct stanza order](https://github.com/caskroom/homebrew-cask/tree/master/doc/cask_language_reference#stanza-order). `brew cask style --fix {{cask}}` should do it.

**Comment by mauricerkelly** [comment]
Updated and commits squashed!

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It was merged directly as 55b1259a364906092940bd5831d3f1299d9fea9a to keep commit history cleaner. Your contribution is still credited to you.

**Pull request closed without merging**
