### PR TITLE
Add Umsatz (Pro, Standard, Mini) Latest

### PR DESCRIPTION
**Pull request by lukasbestle**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
What’s the different between these?

**Comment by lukasbestle** [comment]
Pro, Standard and Mini are different editions with a different feature set (from most to least in that order).

**Comment by vitorgalvao** [comment]
In that case, standard should remain here, and both pro and mini must be in [caskroom/versions](https://github.com/caskroom/homebrew-versions).

**Comment by lukasbestle** [comment]
Alright, will do. Thanks.

**Pull request closed without merging**
