### PR TITLE
deleted synergy.rb

### PR DESCRIPTION
**Pull request by vitorgalvao**
[Page is down](http://synergy-project.org/). Lets see if it comes back up.

### CODE REVIEW

**Comment by alebcay** [comment]
I can still see it at this time. I think it may actually be behind a paywall - it's no longer free to download.

**Comment by vitorgalvao** [comment]
Looks like it. We’ll have it to remove it anyway, albeit for a different reason. Thank you for checking.

**Comment by moshen** [comment]
Does this unnamed reason prevent it from ever being reintroduced to cask?

**Comment by vitorgalvao** [comment]
It’s not unnamed. The reason is you can’t get it anymore without going through a paywall. It’s not free to download. If that ever changes, we can reintroduce it.

**Comment by moshen** [comment]
While they don't list a separate license for the binaries, I guess the way to get around any ambiguity would be to reintroduce as a build script (maybe to homebrew itself).

**Comment by vitorgalvao** [comment]
Yes, that’s a possibility. You’ll have to suggest that to homebrew, though; it’s not our domain.

**Comment by alebcay** [comment]
As a side note, the build instructions provided are quite confusing - you'll find that the default BSD versions of some build tools need to be replaced with their GNU counterparts, and some patches may need to be applied.

**Pull request merged**
