### PR TITLE
Remove google-drive

### PR DESCRIPTION
**Pull request by commitay**
Replaced by Google Backup and Sync https://github.com/caskroom/homebrew-cask/pull/36411

### CODE REVIEW

**Comment by RandomDSdevel** [comment]
@commitay:  You may want to give end users like myself a bit of a grace period between merging #36411 and going through with this PR, as it would _probably_ be a good idea to let us take advantage of the following functionality of the new application described in [its initial (pre-delay) release announcement](https://gsuiteupdates.googleblog.com/2017/06/backup-and-sync-from-google-available.html):  

> Backup and Sync is the latest version of [Google Drive for Mac/PC](https://support.google.com/a/answer/2490101), which is now integrated with the [Google Photos desktop uploader](https://photos.google.com/apps).  As such, it will respect any current Drive for Mac/PC settings in the Admin console.  

That is, I'd like to make sure my settings got migrated over before deleting the old Google Drive client.  If allowing this doesn't depend on having the relevant cask hang around in the Caskroom for a little bit, though, then carry on…

**Comment by vitorgalvao** [comment]
@RandomDSdevel Deleting the cask has no bearing on your ability to use it if you already have it installed.

**Comment by RandomDSdevel** [comment]
@vitorgalvao:  Ah, so Homebrew Cask's behavior when dealing with installed casks that no longer have in-tap descriptions is somehow similar to non-Cask Homebrew's behavior when dealing with software packages whose associated formulae have been removed from a tap without being moved to another official one&thinsp;—&thinsp;in `brew`'s case, I recall that it just falls back to the formula stored in the keg stored in the keg stored in the keg&thinsp;—&thinsp;whether Cask implements that separately or not either here or in `brew` itself (I can't remember whether or not you guys kept some of Cask's code here in the Caskroom after the merger with `brew` upstream off hand.)  Cool, got it; just making sure neither of us were missing anything here!

**Comment by krismorf** [comment]
I can't uninstall Google Drive from my casks.

When doing `brew cask list` or `brew cask uninstall google-drive` I get this:
`Error: Cask 'google-drive' is unavailable: No Cask with this name exists.`

There's also a conflict with homebrew-cask-upgrade @buo. Under State it says: no cask available.

**Comment by RandomDSdevel** [comment]
@krismorf:  Well, _that's_ strange.  @vitorgalvao thought Homebrew Cask had this exact scenario _covered_ when I asked him about it earlier in _this very thread._  Homebrew _itself_ has had code for handling an analogous case integrated upstream for a little bit now, so I _think_ you might want to submit an issue about this here since you've now reported that the code in question doesn't take care of the similar situation arising from the resolution of this PR affecting/for Google Drive down here in Homebrew Cask since it might be a symptom of a more general lack of handling for this case.  (Do I have this right, @vitorgalvao…?)

**Comment by gobinathm** [comment]
@krismorf you can uninstall just by running (This is just workaround)

```
brew cask uninstall https://raw.githubusercontent.com/tamird/homebrew-cask/50e0c025eb4464ec138e7dd1f82667b746227c48/Casks/google-backup-and-sync.rb
```

**Comment by RandomDSdevel** [comment]
@gobinathm:  Shouldn't that command you suggested to @krismorf for said GitHub user to run be something more like `brew cask uninstall https://raw.githubusercontent.com/caskroom/homebrew-cask/c4fa251ddf13f8ac830efc459d3fdbedef122aec/Casks/google-drive.rb`…?  I mean, isn't using the root of a fork tree a better idea…?  (I'd still like to wait and see whether the general handling for cases like the @krismorf encountered gets changed or not due to discussion either here or in a new issue, though…)

**Comment by gobinathm** [comment]
@RandomDSdevel   I should admit that I should not have written that comment, that's purely based on the action taken on my comment.  Being said that I do agree with you on using a fork. Thanks for catching.

**_Request to all Contributors with Privileged access. (This has no relation to this Issue Queue)_**

**Action taken on that comment made me uncomfortable.  Hope we follow a healthy way of collaborating in the issues queues (or) PR's. Correcting someone mistake is different from totally editing & removing what they said. If someone gives out the wrong solution, then it's better to correct the person,  rather than muting what he/she said.** 

**My argument would be different if an offensive comment was modified (or) deleted. Removing an offensive comment is always CORRECT to respect everyone involved. I don't think my comment was anywhere near to offensive (or) hurting any one.**

**OpenSouce Communities are better when it is healthy with there is positive collaborations**

**Comment by commitay** [comment]
@gobinathm I edited your comment and replaced it with "EDIT: incorrect uninstall removed" because it was removing the wrong app.

**Comment by RandomDSdevel** [comment]
@gobinathm:  You could have just edited your earlier comment yourself and mentioned that you had in a new, but no worries!  

<hr />

@commitay:  Looks like either @gobinathm deleted the comment in question after you edited it or your edit removed his comment somehow…?  :man_shrugging:

**Comment by RandomDSdevel** [comment]
@gobinathm:  That's alright.  You could have just edited your earlier comment yourself and mentioned that you had in a new, but no worries!  

<hr />

@commitay:  Looks like either @gobinathm deleted the comment in question after you edited it or your edit removed his comment somehow…?  :man_shrugging:

**Comment by gobinathm** [comment]
@RandomDSdevel Thanks, I deleted my comment.  I never have a problem on some one correcting my mistake, but not like this. Unfortunately, this is the kind of treatment I don't like, that made me distance myself from the Repo.  Anyway thanks.

**Comment by RandomDSdevel** [comment]
@gobinathm:  Wait, _who_ are you saying gave you some untoward treatment, and _when…?_  Based on your previous comments and my own, I'm fairly certain it isn't me who's been rough with you, but that's not entirely clear from the text of [your most recent comment](https://github.com/caskroom/homebrew-cask/pull/36413#issuecomment-317313347).  That being said, this thread has become…somewhat divorced from the discussion surrounding @krismorf's inability to uninstall Google Drive, which he reported shortly after this PR was initially closed&thinsp;—&thinsp;_speaking_ of which, @krismorf, have you been able to figure that out yet…?  In any case, you're welcome for the sort of positive interaction which I hope you've come away with the impression of having had in this PR discussion thread any time, at least from me, @gobinathm.  (Hmm, _maybe_ I should have put the sentence fragment in which I addressed @krismorf in another, new comment or after a horizontal rule in this post…?  I feel like I could have worded this comment better so as to not have to resort to making sure anybody reading it could keep which people it referenced when straight, as even _my_ head's a bit dizzy from those sorts of mental gymnastics.  I suppose it could be _worse_, though…)

**Comment by krismorf** [comment]
I manually deleted the google-drive folder from /usr/local/Caskroom to fix the issue.

**Comment by RandomDSdevel** [comment]
@krismorf:  Ah, good to hear.  Hopefully we can finally be done here, then.

**Comment by senz** [comment]
Hey. Should't you make some deprecation functionality in cask? I mean, a **big red warning** sign, that this cask have been removed/and/or replaced with… Or at least, don't break all application functionality.
This PR rendered my cask useless. And made me crawl git log until I've founded this PR. 
Imagine people that dont know heck about git, and are very frustrated now. Not cool, bro.

**Comment by RandomDSdevel** [comment]
@senz:  Create another issue or submit a PR to create this functionality, and I'm sure one of @caskroom's members will address your concern.  In the meantime, this issue discussion thread has gone on long enough and should probably be locked.

**Comment by vitorgalvao** [comment]
@senz Yes, we would like to handle these cases better, but don’t yet have the functionality because it’s lower priority.

PRs to address this are welcome.

**Pull request merged**
