### PR TITLE
Update omnigraffle from 7.19 to 7.19.1

### PR DESCRIPTION
**Pull request by jabenninghoff**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by jabenninghoff** [comment]
Per the [release notes](https://www.omnigroup.com/releasenotes/omnigraffle), version 7.18.6 is the last version to support Catalina or lower.

**Comment by neutric** [comment]
Sure, check out e.g. #113623.

**Comment by neutric** [comment]
And while you are at it: please change `depends_on macos:` to `">= :yosemite"`, otherwise it doesn't make sense to keep the first two version alternatives around. And for `MacOS.version <= :yosemite` the version should be `6.6.2`.

**Comment by miccal** [comment]
> Per the [release notes](https://www.omnigroup.com/releasenotes/omnigraffle), version 7.18.6 is the last version to support Catalina or lower. Is there a way to resolve the failed livecheck?

The release notes you linked make no mention of Catalina -- 7.18.6 is for macOS 10.14 Mojave.

I fixed and checked all of these in a previous PR -- https://github.com/Homebrew/homebrew-cask/pull/113428

**Comment by jabenninghoff** [comment]
> > Per the [release notes](https://www.omnigroup.com/releasenotes/omnigraffle), version 7.18.6 is the last version to support Catalina or lower. Is there a way to resolve the failed livecheck?
> 
> The release notes you linked make no mention of Catalina -- 7.18.6 is for macOS 10.14 Mojave.
> 
> I fixed and checked all of these in a previous PR -- #113428

7.19 requires macOS 11, so 7.18.6 is the last version that works on Mojave and Catalina.

**Comment by miccal** [comment]
> > > Per the [release notes](https://www.omnigroup.com/releasenotes/omnigraffle), version 7.18.6 is the last version to support Catalina or lower. Is there a way to resolve the failed livecheck?
> > 
> > 
> > The release notes you linked make no mention of Catalina -- 7.18.6 is for macOS 10.14 Mojave.
> > I fixed and checked all of these in a previous PR -- #113428
> 
> 7.19 requires macOS 11, so 7.18.6 is the last version that works on Mojave and Catalina.

Oh I see, ok lets assume that 7.18.6 works on Catalina then :)

**Comment by neutric** [comment]
@miccal Going by https://www.omnigroup.com/download/#omnigraffle and then clicking on "Show older downloads", macOS 10.14 Mojave is the minimum OS requirement.

**Pull request merged**
