### PR TITLE
Add Festify.app v0.2.6

### PR DESCRIPTION
**Pull request by dotWee**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] `sha256` changed but `version` stayed the same ([what is this?][version-checksum]).  
      I’m providing public confirmation below.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Please add an [`appcast`](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Waiting for appcast

**Comment by yurikoles** [comment]
from [travis log](https://travis-ci.org/caskroom/homebrew-cask/builds/268953226#L1396):

```>>> brew cask style Casks/festify.rb
== Casks/festify.rb ==
C:  6:  3: name stanza out of order
C:  7:  3: homepage stanza out of order
C:  8:  1: stanzas within the same group should have no lines between them
C:  9:  3: appcast stanza out of order
C: 10: 13: Align the parameters of a method call if they span more than one line.
1 file inspected, 5 offenses detected
Error: style check failed```

**Comment by yurikoles** [comment]
@dotWee seems like style is fixed now.

**Comment by dotWee** [comment]
Fixed with commit d645664daea526b4c515d179246725abdf63c816.

**Review by commitay — APPROVED** [review]

**Pull request merged**
