### PR TITLE
Update cisco-proximity from desktop-3.1.0 to desktop-4.0.0

### PR DESCRIPTION
**Pull request by steveh7812**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you please try and replace the appcast with a livecheck?

**Comment by steveh7812** [comment]
> Could you please try and replace the appcast with a livecheck?

I have a livecheck that works, however I wanted to ask if this is the right approach--if I add a regex that strips out `desktop-` then `brew livecheck` can detect the version. Is that going to cause an issue with the version stanza of the Cask, which includes the `desktop-` prefix? 

```
❯ brew livecheck --debug cisco-proximity
Cask:             cisco-proximity
Livecheckable?:   Yes

URL:              https://proximity.cisco.com/mac/version.txt
Strategy:         PageMatch
Regex:            /^desktop[._-]v?(\d+(?:\.\d+)+)$/i
URL (final):      https://7f3b835a2983943a12b7-f3ec652549fc8fa11516a139bfb29b79.ssl.cf5.rackcdn.com/ProximityOSX/version.txt

Matched Versions:
4.0.0
cisco-proximity : desktop-4.0.0 ==> 4.0.0
```

**Comment by SMillerDev** [comment]
That looks good, but we should drop desktop from the version too then

**Comment by steveh7812** [comment]
> That looks good, but we should drop desktop from the version too then

@SMillerDev That's done, I've pushed those changes to my branch.

**Review by SMillerDev — APPROVED** [review]
Thanks @steveh7812 !

**Pull request merged**
