### PR TITLE
Update java to 10,46:76eac37278c24557a3c4199677f19b62

### PR DESCRIPTION
**Pull request by michelole**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by commitay — APPROVED** [review]

**Comment by commitay** [comment]
Thanks @michelole!

**Comment by brcolow** [comment]
Does it make sense to add a `java9` versions cask now? If I understand correctly that's the only way to use homebrew to explicitly install java 9 now that this has been bumped to 10.

**Comment by commitay** [comment]
http://www.oracle.com/technetwork/java/eol-135779.html

> Java SE 9 will be a short term release, and users should immediately transition to the next release

**Comment by michelole** [comment]
Alternatively, there could be a `java-lts` cask, which now installs Java 8 (the current LTS release) and in September, Java 11 (thr next LTS release, see link above).

**Comment by relgames** [comment]
Makes sense to add java9 cask, as Java 10 first release contains bugs. 
For example, it's no longer possible to compile Lombok based projects.

**Comment by mynameisbogdan** [comment]
The download link seems to be broken.

```
$ brew cask fetch java
==> Downloading external files for Cask java
==> Downloading http://download.oracle.com/otn-pub/java/jdk/10+46/76eac37278c24557a3c4199677f19b62/jdk-10_osx-x64_bin.dm
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'java' with message: Download failed: http://download.oracle.com/otn-pub/java/jdk/10+46/76eac37278c24557a3c4199677f19b62/jdk-10_osx-x64_bin.dmg
```

**Comment by commitay** [comment]
All Oracle download links for all versions of Java seem to be broken at the moment. 

Trying to download from the Oracle website will also 404.

**Pull request merged**
