### PR TITLE
Adding pdftk-server cask file

### PR DESCRIPTION
**Pull request by dmerrick**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [ ] Checked that the cask was not already refused in [closed issues].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed

### CODE REVIEW

**Comment by dmerrick** [comment]
Ah damn, there is an open issue: https://github.com/caskroom/homebrew-cask/pull/11351

**Comment by corroded** [comment]
is this a no go? the final comments on the issue just asks if someone can create a cask for this, and it seems you already did it all in this PR?

**Comment by dmerrick** [comment]
I didn't see any issues (my machine has it installed via this cask), but
apparently other people had an issue where it incorrectly chowned some
paths in /usr/local


On Nov 16, 2016, at 7:10 PM, Eumir Gaspar <notifications@github.com> wrote:

is this a no go? the final comments on the issue just asks if someone can
create a cask for this, and it seems you already did it all in this PR?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/caskroom/homebrew-cask/pull/26635#issuecomment-261142934>,
or mute the thread

**Comment by marnen** [comment]
Shouldn't this either be reopened or merged with #11351? As it is, #11351 requests a cask, and this PR provides one, but because of the supposed "duplication", no action can be taken.

**Pull request closed without merging**
