### PR TITLE
Add exante-atp latest

### PR DESCRIPTION
**Pull request by simonpucher**
Trading client EXANTE-ATP added to cask library.

### CODE REVIEW

**Comment by colindunn** [comment]
Hey @simonpucher there would have been a template to fill in when you created the pull request. Can you please put it back and fill it in?

**Comment by giannitm** [comment]
@colindunn @simonpucher I think this could be used for the homepage: https://exante.eu/technology/ATP/

**Comment by simonpucher** [comment]
@colindunn sorry for the compiling error, i will fix it.
@giannitm thanks! you are absolutely right. My link was a copy & paste error.

**Comment by colindunn** [comment]
No problem. If you follow the template, as well as the following, it will make contributing much easier. Welcome!
https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md
https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Pull request merged**
