### PR TITLE
Update blockblock

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
why remove the checksum for '0.9.9.4' and change the appcast?

**Comment by suschizu** [comment]
I'm not sure why travis removed the checksum - but I changed the appcast because the changelog version is wrong (its 1.0.3 instead of 1.0.2)
I'm readding the checksum …

**Comment by core-code** [comment]
lets also keep the appcast as it is for now. hopefully they'll be more dilligent in the future

**Comment by core-code** [comment]
@objective-see just to inform you that the changelog ( https://objective-see.com/products/changelogs/BlockBlock.txt ) refers to version 1.0.3 instead of 1.0.2

**Pull request merged**
