### PR TITLE
Update visual-paradigm to 14.2,20171103

### PR DESCRIPTION
**Pull request by kwurst**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by kwurst** [comment]
It downloaded the .dmg file correctly on my computer, but it seems to be hanging during the download when running on Travis.

**Comment by kwurst** [comment]
It downloaded the .dmg file correctly on my computer, but it seems to be hanging during the download when running on Travis.

**Comment by kwurst** [comment]
It downloaded the .dmg file correctly on my computer, but it seems to be hanging during the download when running on Travis.

**Comment by kwurst** [comment]
It downloaded the .dmg file correctly on my computer, but it seems to be hanging during the download when running on Travis.

**Review by gtmgianni — APPROVED** [review]
```
1 file inspected, no offenses detected
==> Downloading https://eu6.visual-paradigm.com/visual-paradigm/vp14.2/20171103/Visual_Paradigm_14_2_20171103_OSX_WithJRE.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask visual-paradigm
audit for visual-paradigm: passed
```

**Review by commitay — APPROVED** [review]

**Pull request merged**
