### PR TITLE
Add MightyText.app v2.92

### PR DESCRIPTION
**Pull request by zanewestover**
### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

Additionally, when **adding a new cask**:
- [x] Checked there are no open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there are no closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

Send & receive SMS and MMS from your computer using your current Android phone number. Messages stay in sync with your phone's SMS inbox.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Did you really run the `brew cask style --fix` command? Because there’s an error.

**Comment by vitorgalvao** [comment]
Make that 25 errors:

```
== mightytext.rb ==
C:  2:  1: [Corrected] Use 2 (not 1) spaces for indentation.
C:  2:  1: [Corrected] Use 2 (not 3) spaces for indentation.
C:  2:  1: [Corrected] Tab detected.
C:  3:  2: [Corrected] Inconsistent indentation detected.
C:  3:  3: [Corrected] Inconsistent indentation detected.
C:  3:  4: [Corrected] Inconsistent indentation detected.
C:  5:  2: [Corrected] Inconsistent indentation detected.
C:  5:  3: [Corrected] Inconsistent indentation detected.
C:  5:  4: [Corrected] Inconsistent indentation detected.
C:  6:  2: [Corrected] Inconsistent indentation detected.
C:  6:  3: [Corrected] Inconsistent indentation detected.
C:  6:  4: [Corrected] Inconsistent indentation detected.
C:  7:  2: [Corrected] Inconsistent indentation detected.
C:  7:  3: [Corrected] Inconsistent indentation detected.
C:  7:  4: [Corrected] Inconsistent indentation detected.
C:  8:  2: [Corrected] Inconsistent indentation detected.
C:  8:  3: [Corrected] Inconsistent indentation detected.
C:  8:  4: [Corrected] Inconsistent indentation detected.
C:  9:  1: [Corrected] stanza groups should be separated by a single empty line
C:  9:  3: [Corrected] Inconsistent indentation detected.
C: 10:  2: [Corrected] Inconsistent indentation detected.
C: 10:  4: [Corrected] Inconsistent indentation detected.
C: 11:  3: [Corrected] Inconsistent indentation detected.
C: 12:  2: [Corrected] Inconsistent indentation detected.
C: 12:  4: [Corrected] Inconsistent indentation detected.

1 file inspected, 25 offenses detected, 25 offenses corrected
```

**Comment by vitorgalvao** [comment]
Thank you for the contribution. It needed some fixes, so they were made in 6a2498deb00f0761f4005ca0f6d4452da1ac0483. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by zanewestover** [comment]
I'm not sure what I did wrong. Any pointers would be helpful. This is my first submission, but I'd like to contribute more in the future.

brew cask style --fix mightytext

1 file inspected, no offenses detected

**Comment by vitorgalvao** [comment]
I’ve fixed the problems before merging. Problems included incorrect indentation, a place where there was a tab instead of a space, and the `app` stanza wasn’t in the right place. All of those are fixed automatically by `brew cask style --fix`, you just need to be sure you run it and it fixes everything, before submitting.

**Pull request closed without merging**
