### PR TITLE
import.io: latest

### PR DESCRIPTION
**Pull request by reitermarkus**
Closes https://github.com/caskroom/homebrew-cask/issues/15704.

### CODE REVIEW

**Comment by reitermarkus** [comment]
The workaround is neede because the `PKG` installer would install the app to `~/Desktop`, or – in case case of `brew cask` – to `/Desktop`.

**Comment by vitorgalvao** [comment]
They use a `pkg` just to move an `app`? I really dislike that trend some companies are following. Thank you for making this.

**Comment by vitorgalvao** [comment]
Merged as 5eb5d82fd55d9bd6d17aef64dc1ce6e0dc5e3a2e.

**Comment by reitermarkus** [comment]
Yeah, sadly. And c'mon, *who* moves an app to the desktop?

**Pull request closed without merging**
