### PR TITLE
Update passenger to 4.6.1

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
both DMG and APP properly signed

https://www.virustotal.com/#/file/860af97614dd12a751b132f0cf7d88110462ad88151a96f7e2dfacd6d2c3c8b2/detection

**Comment by commitay** [comment]
I don't see codesigning in this VirusTotal link either?

**Comment by core-code** [comment]
screen shot 2018-10-14 at 20 12 12
screen shot 2018-10-14 at 20 12 22

**Comment by core-code** [comment]
if anything else is missing please let me know

**Review by victorpopkov — APPROVED** [review]
The app seems to be properly signed by the "MacinMind Software, Inc.":

```bash
$ codesign -dv --verbose=4 /Volumes/Passenger\ 4/Passenger/Passenger.app
Executable=/Volumes/Passenger 4/Passenger/Passenger.app/Contents/MacOS/Passenger
Identifier=com.macinmind.passenger
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=77687 flags=0x0(none) hashes=2422+3 location=embedded
VersionPlatform=1
VersionMin=657664
VersionSDK=657664
Hash type=sha256 size=32
CandidateCDHash sha1=3464df7c2c5ce3acfe2d89c691459f2a80ef7bce
CandidateCDHash sha256=8b7cad50287555743b0cee8f8104c48e02197c3b
Hash choices=sha1,sha256
Page size=4096
CDHash=8b7cad50287555743b0cee8f8104c48e02197c3b
Signature size=8935
Authority=Developer ID Application: MacinMind Software, Inc. (2D3239GKS4)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=2 Jul 2018 at 21:42:23
Info.plist entries=18
TeamIdentifier=2D3239GKS4
Sealed Resources version=2 rules=13 files=73
Internal requirements count=1 size=184
```

**Pull request merged**
