### PR TITLE
Add MacStroke.app

### PR DESCRIPTION
**Pull request by mtjo**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please stop closing and recreating pull requests:

https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+macstroke+is%3Aclosed

**Comment by mtjo** [comment]
> Please stop closing and recreating pull requests:
> 
> https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+macstroke+is%3Aclosed

sorry ,

> Please stop closing and recreating pull requests:
> 
> https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+macstroke+is%3Aclosed

Ci check out “format error”, I close and modify

**Comment by mtjo** [comment]
> Please stop closing and recreating pull requests:
> 
> https://github.com/Homebrew/homebrew-cask/pulls?q=is%3Apr+macstroke+is%3Aclosed

why stop in step "conclusion  Expected — Waiting for status to be reported"

**Comment by SMillerDev** [comment]
> Ci check out “format error”, I close and modify

Just push new commits to the branch and CI will run again

> why stop in step "conclusion Expected — Waiting for status to be reported"

Because GitHub does not run PRs from first time contributors without maintainer approval to stop people from mining crypto in PR runs.

**Pull request closed without merging**
