### PR TITLE
Update stack from 2.6.2.20200306 to 2.6.4.20200506

### PR DESCRIPTION
**Pull request by brianvanburken**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by brianvanburken** [comment]
Is it failling for the same reason as #79137? It seems the download is there, but the appcast show only the previous version.

**Comment by ran-dall** [comment]
@brianvanburken I can't seem to get the download page. Is this walled? It seems that I need to login. Granted, I'm translating the page but maybe you can point me to the download page to verify? Then I merge this manually for you.

**Comment by brianvanburken** [comment]
The homepage of this cask points towards the homepage of the service. All downloads are available on https://www.transip.nl/cp/stack/download/ which is walled behind a login. The official app currently displays the following popup asking to upgrade: 
Screenshot 2020-05-23 at 21 12 37

**Comment by ran-dall** [comment]
@brianvanburken Thanks for that, however, we'd still need a way to verify the version is what's intended for release by the developer...

@vitorgalvao I'm pretty sure it's the same problem we ran into before on #83079. I'm not sure how you would like to handle it.

**Comment by brianvanburken** [comment]
I understand. The download page, sadly, does not provide any hashes to verify the downloaded file. The page only shows a link alias to the latest (https://mirror.transip.net/stack/software/Stack-osx-latest.pkg), so no version is supplied.

It does seem that the appcast gets updates; only much later. In the conversation of #79137 it gets mentioned that the appcast didn't show the latest version. It does show that version now.

After debugging using a proxy I found out that the client is making a request to: https://mirror.transip.net/stack/update/?version=2.6.2.20200306&platform=macos&oem=stack&versionsuffix=&updatesegment=18&sparkle=true. Here, as you can see, it will show the latest version. The difference with the appcast feed in this cask is that a version is set and `&updatesegment=18` is missing. After adding the missing segment to the appcast it shows the latest version: https://mirror.transip.net/stack/update/?version=0.0.0&platform=macos&oem=stack&versionsuffix=&updatesegment=18&sparkle=true. Interesting enough the number `18` can be anything but empty or `0`. If I put in zero or leave it empty it shows the previous version; version 2.6.2.20200306. Conclusion: adding the segment fixes the appcast, but it is unknown what the effect of the number has on future updates. I will update this PR and add a new commit with the fixed appcast URL

**Comment by vitorgalvao** [comment]
Nice solution with the appcast. Thank you.

**Pull request merged**
