### PR TITLE
bankid 7.14.1

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by krehel** [comment]
@razvanazamfirei, I'm analyzing this one now for the livecheck.  Thought maybe to switch to extract_plist?  header_match no longer seems to work.

**Comment by razvanazamfirei** [comment]
@krehel, seems to works fine locally. 
```
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromDefaultTapPathLoader): loading bankid

Cask:             bankid
Livecheckable?:   Yes

URL:              https://install.bankid.com/api/file-download/Mac
Strategy:         HeaderMatch

Matched Versions:
7.14.1

bankid: 7.14.0 ==> 7.14.1
```

**Comment by razvanazamfirei** [comment]
Might be IP-range dependent? Not sure if worth a lot of hassle.

```
bankid
30 days: n/a
90 days: 12 (#2405)
365 days: 98 (#2856)
Age: 3388 days (added 2014, January 22)
```

**Review by razvanazamfirei — APPROVED** [review]

**Comment by krehel** [comment]
Fair enough!  It seemed like a small package hence the idea on extract_plist - you're the boss so 😄

**Comment by razvanazamfirei** [comment]
@krehel, actually, that's a good idea! Do you mind opening another PR with the extract_plist method?

**Pull request merged**
