### PR TITLE
Update nvidia-geforce-now from 2.0.24.105,8F16A9 to 2.0.25.119,8F16A9

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by core-code** [comment]
'bad-update' SHA did not change

@vitorgalvao any idea what would take for these to be rejected by CI?

**Comment by vitorgalvao** [comment]
> any idea what would take for these to be rejected by CI?

Some of these can be legitimate. Are the bulk of these from ML submissions? If so, it might be best to instead configure the ML to not auto-submit version-only changes.

**Comment by core-code** [comment]
if they are legitimate, we can manually approve them. its the auto-merging of non-legit that bugs me.

**Comment by vitorgalvao** [comment]
Pinging @reitermarkus because that concerns the bot.

**Pull request merged**
