### PR TITLE
Added devrant.io app

### PR DESCRIPTION
**Pull request by mainrs**
#### Adding a new cask
- [x] Checked there aren’t open [pull requests](https://github.com/caskroom/homebrew-cask/pulls) for the same cask.
- [x] Checked there aren’t closed [issues](https://github.com/caskroom/homebrew-cask/issues) where that cask was already refused.
- [x] When naming the cask, followed the [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Commit message includes cask’s name.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by SirWindfield** [comment]
Done.

**Comment by SirWindfield** [comment]
Not sure if camel case is allowed. The app is officially named "devRant" but the executable is saved as deviant.io (because of the webpage). I can change the name to "devrant" if needed...

**Comment by vitorgalvao** [comment]
You deleted the cask. It will need to be called `devrantio` as per the token reference, unless it fits into one of the [acceptable cases](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/app.md#target-should-only-be-used-in-select-cases).

Unless other maintainer beats me to it, I’ll verify it later, but you need to readd the file.x

**Comment by SirWindfield** [comment]
The thing is, the service is called "devrant" the website "devrant.io". From my normal understanding the formula name should be "devrant". People looking for it wouldn't search for "devrantio" though. I can re-add the file if we came to a conclusion with the name.

**Comment by vitorgalvao** [comment]
Following the token reference is paramount to avoid duplicates. Like I said, I’ll check it later. Readd it as it was `devrantio`, since I’ll need to comment on the cask itself.

**Comment by SirWindfield** [comment]
I fk*d up my git repo, I am not that good at git. Need to fork again, add the file and create a new pull request. Sorry. Would you mind closing this one for me?

**Comment by vitorgalvao** [comment]
Not a problem. Please @mention me in the next PR.

**Pull request closed without merging**
