### PR TITLE
Update trojan-qt5 from 0.0.8 to 1.0.1

### PR DESCRIPTION
**Pull request by ran-dall**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
@TheWanderingCoel the version numbers in the app itself are damaged. i'd expect them to be "1.0.1" but they are "1.0.0". this affects both the 'CFBundleVersion' and the 'CFBundleShortVersionString'. can this be fixed for the upcoming 1.0.2? thanks!

**Comment by TheWanderingCoel** [comment]
@core-code Sure. I will fix this issue in v1.0.2

**Comment by core-code** [comment]
@TheWanderingCoel awesome, thanks!

**Comment by TheWanderingCoel** [comment]
@core-code You are more than welcome.

**Pull request merged**
