### PR TITLE
oak9 0.11.24

### PR DESCRIPTION
**Pull request by rpateloak9**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by miccal — APPROVED** [review]

**Comment by rpateloak9** [comment]
@miccal  there are cases were our cask is getting bumped automatically without us running brew bump cask pr on our end. Is there an automated process on your end, for example this PR https://github.com/Homebrew/homebrew-cask/pull/150805

**Comment by miccal** [comment]
@rpateloak9 no, anybody is able bump a version of any Cask.

**Comment by rpateloak9** [comment]
> @rpateloak9 no, anybody is able bump a version of any Cask.

thanks but how do you know that our cask needs a bump?

**Comment by miccal** [comment]
> > @rpateloak9 no, anybody is able bump a version of any Cask.
> 
> thanks but how do you know that our cask needs a bump?

By running `brew livecheck oak9` or `brew bump oak9`:
```
|-> brew livecheck oak9
oak9: 0.11.27 ==> 0.11.27
```
```
|-> brew bump oak9
==> oak9
Current cask version   :  0.11.27
Latest livecheck version: 0.11.27
Latest Repology version:  present only in Homebrew
Open pull requests:       none
Closed pull requests:     none
```

**Pull request merged**
