### PR TITLE
Volkswagen DiscoverCare

### PR DESCRIPTION
**Pull request by boboldehampsink**
*If there’s a checkbox you can’t complete for any reason, that's okay, just explain in detail why you weren’t able to do so.*

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

### CODE REVIEW

**Comment by boboldehampsink** [comment]
I need some help on how to handle the version number that is IN the zip.

**Comment by reitermarkus** [comment]
Add a `zap` stanza:

```ruby
zap delete: '~/DiscoverCare'
```

**Comment by vitorgalvao** [comment]
> I need some help on how to handle the version number that is IN the zip.

Done.

But please submit this to [caskroom/drivers](https://github.com/caskroom/homebrew-drivers). This is useless without a volkswagen, is it not?

**Comment by boboldehampsink** [comment]
Thanks, I thought I read an unversioned url couldn't have a version. But this is standalone software, used to update Volkswagen's navigation software onto ANY SD-card. Not sure it's a driver?

**Comment by reitermarkus** [comment]
> This is useless without a volkswagen, is it not?

I'd draw a line here, it's not like you need to plug in your VW, just an SD card.

**Comment by boboldehampsink** [comment]
My thoughts exactly. Not sure what to do now.

**Comment by vitorgalvao** [comment]
> it's not like you need to plug in your VW for this to work

The mental image of connection a car to a laptop via USB is making me laugh!

**Review by vitorgalvao — APPROVED** [review]

**Comment by vitorgalvao** [comment]
> Thanks, I thought I read an unversioned url couldn't have a version.

Yes, because otherwise the cask would break with every update. However, if you have a versioned container inside your unversioned URL, then the cask would break anyway.

**Comment by boboldehampsink** [comment]
Okay. So this cask will probably break now and then, and will need manual fixing?

Added the `zap` stanza BTW.

**Comment by vitorgalvao** [comment]
> So this cask will probably break now and then, and will need manual fixing?

Yep. I’m guessing this isn’t frequently-updated software, though.

**Comment by reitermarkus** [comment]
> The mental image of connection a car to a laptop via USB is making me laugh!

Or to connect to a desktop computer, you'd need a pretty long USB extension cable. But then again, a reasonable person should have a computer in the garage anyways.

**Comment by boboldehampsink** [comment]
> Yep. I’m guessing this isn’t frequently-updated software, though.

It has seen 2 releases in 2016. So thats manageable.

**Comment by miccal** [comment]
@boboldehampsink thank you for your contribution.

**Pull request merged**
