### PR TITLE
wifiman 0.3.0 (new cask)

### PR DESCRIPTION
**Pull request by btebedo**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [x] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Review by bevanjkay — DISMISSED** [review]
Please update the `token` and filename to be "wifiman".

Also, see failures from CI

```
Some launch jobs are still installed, add them to uninstall launchctl:
wifiman-desktop
```

```
Some launch jobs were not unloaded, add them to uninstall launchctl:
wifiman-desktop
```

https://docs.brew.sh/Cask-Cookbook#stanza-uninstall

**Comment by krehel** [comment]
We still need some livecheck here, but the actual install / uninstall process should be fine now.

**Comment by btebedo** [comment]
I can't find a reliable livecheck for this application, they seem to be inconsistent in announcing new releases on the forums here: https://community.ui.com/releases, and I was unable to parse any version information from this page: https://ui.com/download/app/wifiman-desktop

**Comment by bevanjkay** [comment]
I've had a bit of a look and can't uncover anything either. Hopefully once the app comes out of early access there will be a way to tap into an in-app updater mechanism.

**Review by samford — COMMENTED** [review]
https://ui.com/download/app/wifiman-desktop is rendered client-side and the page content is found in one of the JavaScript files (https://ui.com/microsite/static/js/159.e28cd5c5.chunk.js):

```javascript
...
}, {
  os: "macOS",
  items: [{
    title: "macOS Installer 64bit",
    url: "https://desktop.wifiman.com/wifiman-desktop-0.3.0-mac-x64.pkg"
  }, {
    title: "macOS Installer ARM64",
    url: "https://desktop.wifiman.com/wifiman-desktop-0.3.0-mac-arm64.pkg"
  }]
}, {
...
```

Unfortunately, the filename includes a hash that will change in the future (when the website is recompiled, the page content changes, etc.), so there isn't a fixed URL that we can check. It seems like the `main.750c91b3.chunk.js` file is responsible for loading `159.e28cd5c5.chunk.js` but I'm not sure how it calculates the hash (I didn't find a related string):

```javascript
...
Ua = o.a.lazy((function() {
 return Promise.all([n.e(3), n.e(5), n.e(4), n.e(159)]).then(n.bind(null, 3750))
})),
...
```

Unless we can somehow parse/compute the current `159.*.chunk.js` filename, I agree that it seems like there isn't anything we can reliably check for version information from what I'm seeing.

**Comment by miccal** [comment]
Thank you @btebedo and @samford.

**Review by miccal — APPROVED** [review]

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
