### PR TITLE
feat: new kindle for cn 55091

### PR DESCRIPTION
**Pull request by alswl**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by alswl** [comment]
Could I retry travis? It was failed because the bad network.
https://travis-ci.org/Homebrew/homebrew-cask/jobs/529228665

**Comment by vitorgalvao** [comment]
Thank you, but we’ve already gotten a few casks for chinese localisations and we prefer not to include those. If it could be made as a simple language addition to the cask we’d take, but otherwise we’d rather not.

**Comment by alswl** [comment]
@vitorgalvao Hi, this cask is not only for Chinese location, but for all language.
According my talk to Amazon Chinese Call Center, this version is the same with https://github.com/Homebrew/homebrew-cask/blob/master/Casks/kindle.rb , and update in high frequency.

**Comment by vitorgalvao** [comment]
Then what’s the point of it?

**Comment by alswl** [comment]
You closed this PR is right :)

**Pull request closed without merging**
