### PR TITLE
Add initial Brisk version 0.1.0

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by keith** [comment]
Loved the linting here! Green now!

**Comment by miccal** [comment]
Unfortunately we cannot accept this at this time as the Github repository is not notable enough.

**Comment by keith** [comment]
What's the stars limit for this? 🙃

**Comment by miccal** [comment]
[Rejected Casks documentation.](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected_casks.md)

**Comment by keith** [comment]
This project has 45 stars now. Can we reopen this?

**Comment by vitorgalvao** [comment]
This looks like something I’ll use. Good job with the screenshot, by the way.

**Comment by keith** [comment]
Thanks! 😄

**Comment by keith** [comment]
Thanks!

**Pull request merged**
