### PR TITLE
Update jaksta to 2.2.3

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
any ideas why this fails?

**Comment by vitorgalvao** [comment]
> Error: pkg source file not found: 'JMR-2.2.3.pkg'

https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_fix.md

**Comment by core-code** [comment]
i know the "spource not there" error, but the file 'JMR-2.2.3.pkg' is downloaded...

**Comment by vitorgalvao** [comment]
The problem is it’s downloading a naked `.pkg` but then trying to unpack it. This one is a bit of a weird fix. I’ll do the changes shortly.

**Review by vitorgalvao — APPROVED** [review]

**Comment by core-code** [comment]
any idea why this is needed on some casks that directly download the PKG and not on others?

**Comment by vitorgalvao** [comment]
@core-code If you show me an example, I’ll be able to be more precise. But in this case the downloaded file has no extension, and `file` identifies it as a `xar` archive.

**Pull request merged**
