### PR TITLE
libreoffice 7.6.2

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by ctsrc** [comment]
Anyone else getting a hash mismatch?

For me, when I retrieve it from https://ftp.osuosl.org/pub/tdf/libreoffice/stable/7.6.2/mac/aarch64/LibreOffice_7.6.2_MacOS_aarch64.dmg I get:

Expected: 592290ca223949c0f8816d0bf36fd1d7331445ddf964bde4df5658edaecf5d3d

Actual: a33ccdea5980a62fe6b5707ea663d5b48e9af9e0dda6f884b7f4585c0b408ff6

**Comment by ctsrc** [comment]
I've tried from two different machines, on two different networks and I consistently get sha256 hash sum a33ccdea5980a62fe6b5707ea663d5b48e9af9e0dda6f884b7f4585c0b408ff6 when I download the file from https://ftp.osuosl.org/pub/tdf/libreoffice/stable/7.6.2/mac/aarch64/LibreOffice_7.6.2_MacOS_aarch64.dmg

**Comment by ctsrc** [comment]
Confirmed from https://download.documentfoundation.org/libreoffice/stable/7.6.2/mac/aarch64/LibreOffice_7.6.2_MacOS_aarch64.dmg.mirrorlist

The correct sha256 hash for LibreOffice_7.6.2_MacOS_aarch64.dmg is indeed a33ccdea5980a62fe6b5707ea663d5b48e9af9e0dda6f884b7f4585c0b408ff6

The formula needs to be updated again by someone

**Comment by muescha** [comment]
done PR with updated SHA: #156636

**Pull request merged**
