### PR TITLE
Add macintosh.js

### PR DESCRIPTION
**Pull request by peterlewis**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by peterlewis** [comment]
Fails `brew cask audit --new-cask` with `GitHub repository too new (<30 days old)`. However, given the articles of this application on [MacRumors](https://www.macrumors.com/2020/07/29/mac-os-8-emulator-available-as-a-downloadable-app/) and [The Verge](https://www.theverge.com/2020/7/29/21346392/mac-os-8-electron-app-download-windows-linux-features), I felt it might be appropriate to add even so. Needless to say, up to the maintainers, but wanted to provide the option!

**Comment by peterlewis** [comment]
@vitorgalvao Apologies, you merged it whilst I was editing my comment to include further info. Can you just double-check over my latest edit and make sure you're still happy with its inclusion?

Many thanks!

Peter

**Comment by vitorgalvao** [comment]
Yes, it’s fine, thank you.

**Comment by peterlewis** [comment]
Fab, thanks for clarifying! Also thank you for switching out my `1.0.2` with `#{version}`. I always seem to omit a stanza somewhere!

**Pull request merged**
