### PR TITLE
Update scrolls from latest to 2.0.1

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
You have an extra cask (addition).

**Comment by core-code** [comment]
huh? sorry i don't get it. i've renamed the cask.

**Comment by vitorgalvao** [comment]
Ah, apologies, I misunderstood. My mistake.

**Comment by core-code** [comment]
np :)

**Comment by vitorgalvao** [comment]
I thought `cask-repair` had messed up somehow.

**Pull request merged**
