### PR TITLE
Update only-switch from 2.2 to 2.2.1

### PR DESCRIPTION
**Pull request by jacklandrin**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
@jacklandrin _please_ update your fork before submitting your pull requests, [as I have asked you in the past](https://github.com/Homebrew/homebrew-cask/pull/118271#issuecomment-1023925909) -- a simple version bump _should not_ require 33 commits.

**Comment by jacklandrin** [comment]
> @jacklandrin _please_ update your fork before submitting your pull requests, [as I have asked you in the past](https://github.com/Homebrew/homebrew-cask/pull/118271#issuecomment-1023925909) -- a simple version bump _should not_ require 33 commits.

Sure. Actually, I have done "brew update" and fetch my fork before submitting pull requests. And my fork has shown the lasted commit, but when I opened a new pull request, it's still like this, very weird. I'm sorry for that and check the reason.

**Comment by miccal** [comment]
Thanks @jacklandrin.

**Comment by carlocab** [comment]
@jacklandrin doing `brew update-reset` should help.

Note that this will destroy any modifications you've made locally that you haven't stashed or committed to a non-master branch.

**Pull request merged**
