### PR TITLE
updated sketch (39)

### PR DESCRIPTION
**Pull request by adidalal**
#### Editing an existing cask
- [x] Commit message includes cask’s name (and new version, if applicable).
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.

### CODE REVIEW

**Comment by Ephemera** [comment]
How about like https://github.com/Ephemera/homebrew-cask/commit/6a58967a5dd260c3a275e3c8f8f93447ec6bdd4f

**Comment by adidalal** [comment]
@Ephemera Looks like sketch changed their versioning entirely - see http://www.sketchapp.com/support/updates/

We lose the "version.major" in the appcast, but I've updated the URL to point to the correct one according to the official appcast

**Comment by Ephemera** [comment]
@adidalal 
How about like https://github.com/Ephemera/homebrew-cask/commit/bfc61ef7e5af133dd46267b86144585d7c4112a4
Also bohemiancoding.com is redirect to download.sketchapp.com

**Comment by adidalal** [comment]
Updated URL in https://github.com/caskroom/homebrew-cask/pull/23025, thanks.

Will keep version as is, as it's the *correct* current version (`39`, not `3.9`)

**Pull request merged**
