### PR TITLE
Update splashtop-streamer to 3.2.6.0

### PR DESCRIPTION
**Pull request by brianbrownton**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by brianmorton** [comment]
```
Error: Some applications are still running, add them to uninstall quit:
com.splashtop.Splashtop-Streamer
```

...but there's already that block on line 13

**Comment by brianmorton** [comment]
Anything I can do to move this along?

**Comment by vitorgalvao** [comment]
If the app isn’t quitting, try [`signal`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-key-signal).

**Comment by brianmorton** [comment]
`QUIT` and `TERM` both no good.

**Comment by brianmorton** [comment]
bump @vitorgalvao

**Review by vitorgalvao — APPROVED** [review]
`uninstall` worked fine in VM.

**Comment by brianmorton** [comment]
Can this be merged now?

**Comment by vitorgalvao** [comment]
I forgot why I haven’t merged this.

**Pull request merged**
