### PR TITLE
temurin: use Adoptium API in livecheck

### PR DESCRIPTION
**Pull request by FnControlOption**
- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

https://github.com/Homebrew/homebrew-cask-versions/pull/12617#issuecomment-976297942

### CODE REVIEW

**Comment by FnControlOption** [comment]
I'm thinking of using this instead https://api.adoptium.net/v3/info/release_versions?release_type=ga&architecture=x64&image_type=jdk&jvm_impl=hotspot&os=mac&page=0&page_size=1&project=jdk&sort_method=DEFAULT&sort_order=DESC&vendor=eclipse

**Comment by FnControlOption** [comment]
Actually, why use `csv` here? I thought it was only supposed to replace colons?

**Comment by miccal** [comment]
> Actually, why use `csv` here? I thought it was only supposed to replace colons?

Oh, good point --  I just thought it could be used for these cases too in the spirit of consistency, and I think it makes things much clearer that `before_comma` and `after_comma`.

**Comment by miccal** [comment]
I have already changed a few to use `csv` instead of `before_comma` and `after_comma`.

What are your thoughts here?

**Comment by FnControlOption** [comment]
I think that `before_comma` and `after_comma` are clearer, but maybe that's just because I'm not used to `csv` yet.

**Comment by miccal** [comment]
@Homebrew/cask thought on this?

I really like the `version.csv[i]` method instead of `before_comma` and `after_comma`, but perhaps that is because I work with `.csv` files _a lot_ and perhaps I am biased :)

**Comment by vitorgalvao** [comment]
> I have already changed a few to use `csv` instead of `before_comma` and `after_comma`.

I’m of the mind we should change them all. `before_comma` and `after_comma` always take me a second. It doesn’t help that the order of the first letters is the start of the alphabet and is reversed (**b**(efore) is followed by **a**(fter)).

But I’m not adamant, especially in cases with a single comma (which is most).

**Comment by carlocab** [comment]
I'm partial to `version.csv.first` and `version.csv.second`.

**Comment by vitorgalvao** [comment]
> I'm partial to `version.csv.first` and `version.csv.second`.

I’m up for that!

**Pull request merged**
