### PR TITLE
Update and rename pdfelement.rb to wondershare-pdfelement.rb

### PR DESCRIPTION
**Pull request by tifrueh**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by Timo-Frueh** [comment]
After some reviewing of other PRs I decided the zap stanza should fit better to remove additional files than my initial approach with the uninstall stanza.

**Comment by bevanjkay** [comment]
@Timo-Frueh What is your reasoning for changing the cask token from `pdfelement` to `wondershare-pdfelement`? 
[The cask cookbook would suggest that the original token is correct](https://docs.brew.sh/Cask-Cookbook#token-reference).

**Comment by bevanjkay** [comment]
I would be more inclined to leave it as is, changing the token would result in the cask not updating for existing users.
But I'll defer to the other @Homebrew/cask maintainers for feedback also.

**Comment by SMillerDev** [comment]
Yeah, agreed. Renaming casks should be done very sparingly.

**Comment by vitorgalvao** [comment]
> It is shown like that in the Launchpad, in the Menubar and even in the Finder.

That would be [an acceptable use of `target`](https://docs.brew.sh/Cask-Cookbook#target-should-only-be-used-in-select-cases), with [a comment](https://github.com/Homebrew/homebrew-cask/blob/d2a6b26df69fc28c4d84d6f5198b2b652c2f414d/Casks/devonthink-pro-office.rb#L16).

But that should’ve been done when adding. In the absence of a `cask_renames.json`, not renaming would be best.

**Comment by Timo-Frueh** [comment]
Okay, those are all valid arguments. I'll just make another commit and rename it back, is that fine?

**Comment by miccal** [comment]
Thank you @Timo-Frueh.

**Pull request merged**
