### PR TITLE
Update avidemux from 2.7.4 to 2.7.6

### PR DESCRIPTION
**Pull request by hannesbraun**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by core-code** [comment]
i am not sure if others agree but since this is a very popular app and catalina is still 'new' i think we might want to have an if/else to still support mojave. can you add that?

**Comment by core-code** [comment]
if not we need at least a proper depends_on stanza

**Comment by hannesbraun** [comment]
Oh sure, I didn't think about that. It probably makes sense to still support Mojave. I'll add it.

**Comment by core-code** [comment]
good job, thanks!

**Pull request merged**
