### PR TITLE
Update butt from 0.1.20 to 0.1.21

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by ran-dall** [comment]
@core-code @vitorgalvao  This is strange. The `sha256` keeps changing each time it gets downloaded. Both are coming from Source Forge, so I suspect that to be the culprit. Besides, I think we've observed this (or similar) behavior before from Source Forge, right?

**Comment by miccal** [comment]
@ran-dall what if you use
```
https://downloads.sourceforge.net/project/butt/butt/butt-0.1.21/butt-0.1.21.dmg
```
as the `url`?

**Comment by ran-dall** [comment]
@miccal Yeah it still does it. However, I've observed it seems to randomly repeat 3 different `sha`s.

```shell
$ http -d https://downloads.sourceforge.net/project/butt/butt/butt-0.1.21/butt-0.1.21.dmg|openssl sha256
HTTP/2 302

Downloading to "<stdout>"
Done. 349.00 B in 0.00038s (906.47 kB/s)
716ac3bddfb0d0d5169ca0869ae655561914c5c419538f9ef573a774f81b8917
```

```shell
$ http -d https://downloads.sourceforge.net/project/butt/butt/butt-0.1.21/butt-0.1.21.dmg|openssl sha256
HTTP/2 302

Downloading to "<stdout>"
Done. 339.00 B in 0.00033s (1012.80 kB/s)
ab5cdcef9a34e03535178dc1b2bd79f93f36a7305c9d378639055c8f190df2aa
```

```shell
$ http -d https://downloads.sourceforge.net/project/butt/butt/butt-0.1.21/butt-0.1.21.dmg|openssl sha256
HTTP/2 302

Downloading to "<stdout>"
Done. 337.00 B in 0.00037s (901.60 kB/s)
ef1c1e49b4c885cec5f5ed53ceed0978a697c9edcb9f10c0733ce402ed505f0f
```

```shell
$ http -d https://downloads.sourceforge.net/project/butt/butt/butt-0.1.21/butt-0.1.21.dmg|openssl sha256
HTTP/2 302

Downloading to "<stdout>"
Done. 339.00 B in 0.00037s (899.90 kB/s)
ab5cdcef9a34e03535178dc1b2bd79f93f36a7305c9d378639055c8f190df2aa
```

```shell
$ http -d https://downloads.sourceforge.net/project/butt/butt/butt-0.1.21/butt-0.1.21.dmg|openssl sha256
HTTP/2 302

Downloading to "<stdout>"
Done. 349.00 B in 0.00040s (843.37 kB/s)
716ac3bddfb0d0d5169ca0869ae655561914c5c419538f9ef573a774f81b8917
```

**Comment by core-code** [comment]
you are just downloading a random HTML page (look at the file size).

the *real* download happens in a redirect in the HTML.

the good SHA is definitely 

`1f897e94a8763058626f3ac2bdc20ba206e1ec6ce23a04aa2f8d129328e7ef5d`

**Comment by ran-dall** [comment]
@core-code 🙇‍♂️. 'nuff said...but I did notice those file sizes and found it curious when it was downloading in seconds.

Haven't we run into this before with Source Forge? I remember vaguely remember a discussion.

More importantly, any suggestions on how to fix it?

**Comment by core-code** [comment]
is it a real problem? i see 'brew install' can download just fine from sourceforge using those weird redirects...

**Comment by ran-dall** [comment]
> is it a real problem? i see 'brew install' can download just fine from sourceforge using those weird redirects...

@core-code I see your point, but I dunno. We updated this just fine on April 22 (#81188); and the `url` wasn't changed or anything.

**Comment by core-code** [comment]
hmm lets try the good sha and lets see what mr travis says.

**Comment by ran-dall** [comment]
@core-code Yeah you're right, but that's would mean that there a bug in `audit` cause it returns a completely different `sha` on the file.

```shell
$ brew cask audit --download butt
==> Downloading https://downloads.sourceforge.net/butt/butt-0.1.21.dmg
==> Downloading from https://ayera.dl.sourceforge.net/project/butt/butt/butt-0.1.21/butt-0.1.21.dmg
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'butt'.
==> Note: Running `brew update` may fix SHA-256 checksum errors.
audit for butt: failed
 - download not possible: Checksum for Cask 'butt' does not match.
Expected: e84e4aa582788cc49288bbcaa1886bd1f2044b60a5afbd24d02fecc4b32ff439
  Actual: 1f897e94a8763058626f3ac2bdc20ba206e1ec6ce23a04aa2f8d129328e7ef5d
    File: /Users/randall/Library/Caches/Homebrew/downloads/0d73c3c764c03ad0b14ea0d120e3ba8d9eadb9cd930967be9d03bd0c80359b82--butt-0.1.21.dmg
To retry an incomplete download, remove the file above.
If the issue persists, visit:
  https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md
Error: audit failed for casks: butt
```

Yet after changing it to `1f897e94a8763058626f3ac2bdc20ba206e1ec6ce23a04aa2f8d129328e7ef5d`. the same file passes? 

```shell
$ brew cask audit --download butt
==> Downloading https://downloads.sourceforge.net/butt/butt-0.1.21.dmg
Already downloaded: /Users/randall/Library/Caches/Homebrew/downloads/0d73c3c764c03ad0b14ea0d120e3ba8d9eadb9cd930967be9d03bd0c80359b82--butt-0.1.21.dmg
==> Verifying SHA-256 checksum for Cask 'butt'.
audit for butt: passed
```

**Comment by ran-dall** [comment]
@core-code You're right, so I'm assuming the problem must be in the ML's version of `cask-repair` cause `audit` actually outputs the right `sha`.

**Comment by core-code** [comment]
i am not sure about the audit problem. maybe vitor has an idea there?

**Comment by ran-dall** [comment]
@core-code How did you get that `sha`? I'm having the same problem on #83344

**Comment by core-code** [comment]
i just did a normal download in Safari. but i haven't had problems so far using 'cask-repair' for sourceforge casks (except the abysmal download speed from some mirrors which reminds me of  dialup-modem-times)

**Comment by vitorgalvao** [comment]
If anything, I think the problem would be in `fetch`, not `audit`. I think everything gets downloaded the same way.

**Comment by ran-dall** [comment]
@vitorgalvao I actually the problem spelled out on this PR but @core-code beat me to the punch. I tried this on `psi-plus` though and got the same problem. Would you mind taking a look at https://github.com/Homebrew/homebrew-cask/pull/83344#issuecomment-634991270? I outlined what's going on. The same thing happened.

**Comment by vitorgalvao** [comment]
@ran-dall Technically the problem could be anywhere that interacts with that code, but the point still stands `fetch` would be a more likely culprit than `audit`. I see no reason why `audit` would be spewing different checksums for the same file—and that doesn’t seem to be the case, as you get different results only after removing the cached file—but I see plenty of reasons why `fetch` may be grabbing the wrong thing.

[Your comment above](https://github.com/Homebrew/homebrew-cask/pull/83343#issuecomment-634952105) suggests that the issue is indeed somewhere between the server we download from and the method we use to download from it.

If this only happens with sourceforge, then it’s not a bug but some change in behaviour we need to understand and fix for. That fix will likely be changing the URL format we use for sourceforge casks or making modifications to `fetch`, which is the bit of code that downloads things. It can be as simple as hardcoding one of our `url` parameters when a URL is from sourceforge.

**Pull request merged**
