### PR TITLE
Add Swiftcord Cask

### PR DESCRIPTION
**Pull request by cryptoAlgorithm**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by cryptoAlgorithm** [comment]
Running `brew audit --new-cask swiftcord` returns an unhelpful error:
```
audit for swiftcord: failed
 - exception while auditing swiftcord: undefined method `downcase' for nil:NilClass
Error: 1 problem in 1 cask detected```

It doesn't shed much light on where or why the cask failed the audit.

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @cryptoAlgorithm.

Could you please try to add a [`zap` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-zap), thanks.

**Comment by cryptoAlgorithm** [comment]
@miccal, ok, I'll do just that. To clarify, in this case the zap stanza only needs to cleanup preferences and caches since I do not create any other files, right?

**Comment by miccal** [comment]
> @miccal, ok, I'll do just that. To clarify, in this case the zap stanza only needs to cleanup preferences and caches since I do not create any other files, right?

Correct.

**Comment by cryptoAlgorithm** [comment]
@miccal, Ive just added the zap stanza and all checks pass.

**Comment by miccal** [comment]
Thank you @cryptoAlgorithm.

**Review by miccal — APPROVED** [review]

**Comment by cryptoAlgorithm** [comment]
My pleasure :D

**Pull request merged**
