### PR TITLE
Update jamovi from 1.0.2.0 to 1.0.3.0

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
Superseded https://github.com/Homebrew/homebrew-cask/pull/65950

**Comment by core-code** [comment]
well, no. 1.0.4.0 is not a recommended, stable version. i'd rather have the stable 1.0.3.0 version in HBC

**Comment by ran-dall** [comment]
Actually, it was already merged, so technically it did supersede; regardless I see your point. I've made a note that `solid` means `stable`. 👍

**Comment by core-code** [comment]
thanks

**Pull request closed without merging**
