### PR TITLE
deepl 4.6.565727

### PR DESCRIPTION
**Pull request by ondrejfuhrer**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by razvanazamfirei — APPROVED** [review]

**Comment by ondrejfuhrer** [comment]
@razvanazamfirei can we restart the CI for it one more time? Seems it was stuck on the live check for some time, now `live check` command reports the new version again.

**Comment by ondrejfuhrer** [comment]
It's still failing even though I'm getting it :-( 
```
> brew livecheck deepl
deepl: 4.5.542015 ==> 4.6.565727
```

**Comment by bevanjkay** [comment]
@ondrejfuhrer The `ci-retry` label reruns CI every 3 hours.

**Comment by krehel** [comment]
This one may take some time.  I had the same issue last time when I bumped it, it took 4-5 days for CI to catch up.

**Pull request merged**
