### PR TITLE
Update DBeaver enterprise to v3.3.2

### PR DESCRIPTION
**Pull request by wmorin**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for these. We usually prefer separate pull requests for separate casks but in this case the changes are so straightforward and similar, you should feel free to submit them in the same PR if you so wish.

**Comment by wmorin** [comment]
Thank you for the merge Vítor. I will group DBeaver community & enterprise upgrade in the same PR next time as they are always released together.

Side request, I would like to apply to join caskroom organization on github. I'm a huge user of it doing small contrib from time to time. Should it be possible? ;-)

**Comment by vitorgalvao** [comment]
Thank you for the interest, @wmorin, but we’re not currently looking to add anyone to the team (and already have someone on hold). Either way, what we need are active maintainers to implement features and take care of fixing open issues.

These small sporadic updates, though useful in their own right, are not relevant enough to give write access to, particularly when so many other users contribute so much more, much more regularly. From these alone, I have no notion of your knowledge of the project as a whole, its rules and particularities, or if you have any notion of how to deal with common and current issues.

**Comment by wmorin** [comment]
Ok, thank you for the explanation Vítor, I understand. For sure I'm pretty new to the project ;-)
Keep up the good work!

**Comment by vitorgalvao** [comment]
Thank you. Keep contributing (especially if you can fix old open issues), and we’ll keep you in mind.

**Pull request merged**
