### PR TITLE
Update iteleport-connect to 6.0.0.2

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
seems properly signed by 'iteleport' and virustotal = https://www.virustotal.com/#/file-analysis/ZmYzMDZmMzhhMGVlYjI3MTkwNzZmY2RjNTQ4NDI4Y2M6MTUzNzA0NTY4OA==

**Comment by vitorgalvao** [comment]
Wrong VirusTotal URL?

**Comment by core-code** [comment]
ok sorry this one should work better

https://www.virustotal.com/#/file/2a845a052dfa04ae8a5c26da918944082f4a3a43ba3804cb8a078a77ad9f3b4c/relations

not sure why virustotal says the file is unsigned

screenshot 2018-09-16 at 17 57 48

**Comment by amyspark** [comment]
DMG is unsigned, but app is.

```
amalia@Sakura:~/Downloads$ spctl --assess --verbose iTeleport\ Installer.v6.0.0.2.dmg 
iTeleport Installer.v6.0.0.2.dmg: rejected
source=no usable signature

amalia@Sakura:~/Downloads$ codesign -dvv iTeleport\ Installer.v6.0.0.2.dmg
iTeleport Installer.v6.0.0.2.dmg: code object is not signed at all
```

**Comment by commitay** [comment]
This cask was deleted in https://github.com/Homebrew/homebrew-cask/pull/53039

**Pull request closed without merging**
