### PR TITLE
Update java - add uninstall_preflight

### PR DESCRIPTION
**Pull request by commitay**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

[`java-jdk-javadoc`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/java-jdk-javadoc.rb) and [`jce-unlimited-strength-policy`](https://github.com/caskroom/homebrew-cask/blob/master/Casks/jce-unlimited-strength-policy.rb) are casks installed using `system_command` into `java_home`.

Trying to uninstall/reinstall either of these casks after `java` is uninstalled/reinstalled fails.

This adds an `uninstall_preflight` that checks `#{HOMEBREW_PREFIX}/Caskroom/` for both of these casks and uninstalls them if found.

### CODE REVIEW

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/issues/36933

Might also be worth adding a postinstall_preflight to reinstall those two specific casks on install?

**Comment by commitay** [comment]
> Might also be worth adding a postinstall_preflight to reinstall those two specific casks on install?

This would be nice but I'm not sure how to check for a previously installed cask as part of a `postflight`.

**Comment by miccal** [comment]
Add a `caveat` maybe?

**Comment by commitay** [comment]
The `caveat` on this cask is already rather large.
```
  caveats <<-EOS.undent
    This Cask makes minor modifications to the JRE to prevent issues with
    packaged applications, as discussed here:

      https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

    If your Java application still asks for JRE installation, you might need
    to reboot or logout/login.

    Installing this Cask means you have AGREED to the Oracle Binary Code
    License Agreement for Java SE at

      https://www.oracle.com/technetwork/java/javase/terms/license/index.html
  EOS
```
____

Just to clarify uninstalling or reinstalling `java` with either of these to casks installed also removes them as `java` removes/overwrites their files, the purpose of this is to tidy up `{HOMEBREW_PREFIX}/Caskroom/` (and `brew cask list`) so users don't have to do it manually.

**Comment by reitermarkus** [comment]
> Just to clarify uninstalling or reinstalling `java` with either of these casks installed also removes them as `java` removes/overwrites their files

We have `conflicts_with` for that.

**Comment by commitay** [comment]
>We have conflicts_with for that.

It isn't a conflict, they install into `java_home`.

**Comment by reitermarkus** [comment]
So it is a conflict, but only when uninstalling?

**Comment by commitay** [comment]
> So it is a conflict, but only when uninstalling?

Yes, only when uninstalling/reinstalling.

**Comment by commitay** [comment]
Added a `caveat` to `java-jdk-javadoc` and `jce-unlimited-strength-policy`

**Review by vitorgalvao — APPROVED** [review]
I don’t really like that we’re calling ourselves via a system command, but if there’s no better way and this is needed, so be it.

**Pull request merged**
