### PR TITLE
Update matterhorn from 50200.10.1 to 50200.10.2

### PR DESCRIPTION
**Pull request by jtdaugherty**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by jtdaugherty** [comment]
For what it's worth, the frozen string literal issue was mentioned by one of the linting checks above.

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask` @jtdaugherty.

**Review by miccal — APPROVED** [review]

**Comment by miccal** [comment]
> For what it's worth, the frozen string literal issue was mentioned by one of the linting checks above.

Can you please let me know which check suggested this, thank you.

**Comment by jtdaugherty** [comment]
```
user@hostname:~/src/homebrew-cask$ brew cask style --fix Casks/matterhorn.rb
Casks/matterhorn.rb:1:1: C: Missing frozen string literal comment.
cask "matterhorn" do
^

1 file inspected, 1 offense detected, 1 more offense can be corrected with `rubocop -A`
Error: Style check failed.
```

**Pull request merged**
