### PR TITLE
Add ShellHere.app latest version.

### PR DESCRIPTION
**Pull request by jaredsampson**

### CODE REVIEW

**Comment by adityadalal924** [comment]
You have trailing whitespace, please fix that.

```
Offenses:
Casks/shellhere.rb:9:1: C: Trailing whitespace detected.
2858 files inspected, 1 offense detected
RuboCop failed!
```

Additionally, the last commit on that repository looks like it's from 2012 - does this work on the latest OS X? (if not, a `depends_on` stanza is generally good form)

**Comment by vitorgalvao** [comment]
If this does not work on El Capitan, might as well refuse it, since it’ll likely never work. Let’s start cutting cruft, a bit.

**Comment by jaredsampson** [comment]
Thanks for the suggestions.  

For the record, it works just fine on El Capitan.  It basically takes the place of the almost totally useless "New Terminal [Tab] at Folder" service, which only works in certain Finder views (e.g. List view is okay, but not Columns view is not).  I'll fix the whitespace.

**Comment by adityadalal924** [comment]
Thank you for the contribution. It needed some fixes, so they were made in ece0a42041a7d6352c7fe9529a29ce3f7b2d9799. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Pull request closed without merging**
