### PR TITLE
remove cask lines referencing mavericks

### PR DESCRIPTION
**Pull request by brianbrownton**
should help with https://github.com/Homebrew/homebrew-cask/issues/58046

### CODE REVIEW

**Comment by reitermarkus** [comment]
The ones with `MacOS.version <= :mavericks` should still stay. Only `depends_on macos: '>= :mavericks'` should be removed, since that's implied now that Homebrew only runs on Mavericks and later.

**Comment by brianmorton** [comment]
>The ones with `MacOS.version <= :mavericks` should still stay. Only `depends_on macos: '>= :mavericks'` should be removed, since that's implied now that Homebrew only runs on Mavericks and later.

While it is possible I've made a mistake, I don't believe I've done anything to the contrary of the above.

**Comment by reitermarkus** [comment]
> are you saying these should instead be changed to `==` instead of `<=`?

I'm saying they should not be deleted. I think we should leave them as `<=`.

**Comment by vitorgalvao** [comment]
> Forgive my ignorance, but if brew is Mavericks+ why do we need `<` (less than) Mavericks?

We don’t *need* it, but it’s nice to have. They both mean the same right now, so having the one that covers more cases is better.

For example, let’s say we decide to revert the decision and add support for pre-Mavericks, or that a project such as [Tigerbrew](https://github.com/mistydemeo/tigerbrew) uses Casks. Not having to redefine those `==` is beneficial.

And from a contributors point of view, I can see people that don’t know that we only support from Mavericks on trying to include older versions, `<=` “eases the mind” into “that’s already done”.

**Comment by vitorgalvao** [comment]
Also, by leaving them as `<=`, this PR will require less changes, as it just means not editing those casks where it was deleted.

**Comment by brianmorton** [comment]
I'll drop the PR and just resub one that removes the depends on lines.

**Pull request closed without merging**
