### PR TITLE
Add Little Snitch uninstaller

### PR DESCRIPTION
**Pull request by epsimatic**

### CODE REVIEW

**Comment by vitorgalvao** [comment]
That won’t work. It isn’t a script: calling that just opens the GUI anyway.

**Comment by epsimatic** [comment]
Objection: That actually works:

* You type `brew cask rm little-snitch`
* a window opens: 
* You click `Continue`
* Little Snitch is gone.

And it works the same way for controllermate.

A GUI uninstaller is the only way to get rid of the app.

You should really take into account that there's currently **no uninstaller** for Little Snitch. That literally means that typing `brew cask rm little-snitch` does not remove the app. Read: the package is badly broken. And I offer a fix that gets the job done.

**Comment by vitorgalvao** [comment]
Yes, we know, Little Snitch’s uninstall has been discussed on this project since before `uninstall` was even implemented. We stay clear from GUI operations. `installer :manual` is the closest we have, and even so *we don’t automatically call the GUI* (important distinction from what you’re doing here).

We may in the future implement something for GUI uninstallers but this is definitely not the way. Again, it is not a script, `uninstall :script` is absolutely the wrong way of approaching this.

In addition, no, the GUI uninstaller is not the only way to get rid of it. It is the only *official* way, but a lot of the apps in homebrew-cask don’t provide an installer and we can uninstall them anyway via other means.

**Comment by epsimatic** [comment]
Then someone has to reverse-engineer the uninstaller, I guess. Until that, `little-snitch.rb` is a one-way ticket. You can get it installed, but can't get it removed.

Well, do what you think is best for the project. I still ask for two things:

* Please add a `caveats` for Little Snitch to tell that one has to get rid of an app manually.
* Be consistent and remove https://github.com/caskroom/homebrew-cask/blob/master/Casks/controllermate.rb#L13 as well

**Comment by vitorgalvao** [comment]
Nice catch on `controllermate`. I saw the name correction and hadn’t noticed it was using the app. Thank you.

> Then someone has to reverse-engineer the uninstaller, I guess.

No, someone needs to contact the developer first and simply ask. As far as I’m aware, no one has done that yet for this cask, and asking has yielded very good results in the past. It’s also way more effective than building hacks on top of hacks.

> Until that, `little-snitch.rb` is a one-way ticket.

No, it is not, as you still have the manual uninstaller.

[Many others](https://github.com/caskroom/homebrew-cask/issues/6872) are in that situation, it’s not like we’re not aware of it. Finding a solution for those is needed, yes, but once more, yours isn’t it. It was decided long ago that one of the core features of this project would be to not call GUIs automatically, to allow for scripting.

**Pull request closed without merging**
