### PR TITLE
add graalvm-ce 19.1.1

### PR DESCRIPTION
**Pull request by DeLaGuardo**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/57374

**Comment by DeLaGuardo** [comment]
I understand concerns about enormous amount of variance of JDK/JRE available from different vendors but GraalVM isn't just "yet another JDK". It is not about "be 200ns faster when the moon is in correct position" but it is different tools set from well known vendor (Oracle) based (!) on JDK. So, please, read [rationale](https://www.graalvm.org/docs/why-graal/) and reconsider adding it to brew cask.

**Comment by vitorgalvao** [comment]
First we’ll deal with the current mess, then we can consider adding more stuff.

**Comment by DeLaGuardo** [comment]
Ok, fare point. 
So I made my own tap for this cask:
```bash
brew tap DeLaGuardo/graalvm git@github.com:DeLaGuardo/homebrew-graalvm.git
brew cask install graalvm-ce
```

**Pull request closed without merging**
