### PR TITLE
Update lingon-x to 6.3.2

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by commitay** [comment]
Previous versions are in https://github.com/Homebrew/homebrew-cask-versions

https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/lingon-x5.rb
https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/lingon-x4.rb
https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/lingon-x2.rb

**Comment by core-code** [comment]
@commitay isn't it much better to have proper version information for different OS versions in the cask? this way a user just needs to 'brew cask install' and the right thing happens automatically instead of having to do a lot of research himself for the latest version.

i think it would be ideal if any cask would install on the last 3 released OS versions. there are quite few apps that raise minimum requirements that fast anyway.

in any case, there are quite a few casks that have different versions for different OS versions. also, there are quite a few old versions stored in 'homebrew-cask-versions'. is there any clear guideline which one is preferred in which case?

**Comment by commitay** [comment]
> isn't it much better to have proper version information for different OS versions in the cask? this way a user just needs to 'brew cask install' and the right thing happens automatically instead of having to do a lot of research himself for the latest compatible version.

No, as it isn't just a "compatible version", they are paid upgrades. Including them all in this cask would mean that a user can't install an older version that they have a license for on a newer version of macOS.

> is there any clear guideline which one is preferred in which case?

Usually for "free" software when there isn't a reason not to install the latest version (unless it isn't compatible) we do include it in the same cask.  Paid upgrades go to `cask-versions`.

**Comment by core-code** [comment]
> Including them all in this cask would mean that a user can't
> install an older version that they have a license for on a newer version of macOS.

well, including them in the main cask wouldn't necessitate deleting the existing casks in homebrew-versions

> Usually for "free" software when there isn't a reason not to install the latest version
> (unless it isn't compatible) we do include it in the same cask.
>  Paid upgrades go to cask-versions.

ok, thanks for the clarification

**Comment by core-code** [comment]
don't want to beat a dead horse here. but i kind of depend on casks being installable all the way back to 10.11. i have to fork casks that don't work on older OS versions. which means the energy we spend on keeping those casks up-to-date won't be of use to anyone else since they are stored only on our server. i'd rather see us contributing to something that is of use to everyone. and i can't see any harm in adding the versions for old OS releases.

if you disagree, just ignore this message.

**Pull request closed without merging**
