### PR TITLE
aws-vpn-client 3.6.0

### PR DESCRIPTION
**Pull request by jhandguy**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by jhandguy** [comment]
AWS seems to have stopped adding release notes since version 3.4.0 (see https://docs.aws.amazon.com/vpn/latest/clientvpn-user/client-vpn-connect-macos.html#client-vpn-connect-macos-release-notes).

However, upon opening AWS VPN Client, a prompt shows that a newer version (3.6.0) is available.

image

**Comment by krehel** [comment]
Thank you @jhandguy!   Your efforts help improve the project and benefit users worldwide. Without contributions like yours it'd be impossible to keep our project going!

For me, the livecheck is working locally and found the latest `3.6.0` version.  Based on the release notes it looks like `3.4.0` had an error and was rolled back with `3.5.0` and then replaced with `3.6.0`.

Anyone else mind confirming livecheck?

**Comment by krehel** [comment]
Disregard, CI re-run picked it up correctly.

**Review by krehel — APPROVED** [review]

**Comment by jhandguy** [comment]
@krehel I reached out to AWS (via Support case) to let them know their documentation was outdated - it looks like they have fixed it! 🎉

**Pull request merged**
