### PR TITLE
Add Audirvana Plus 2.app v2.3.3

### PR DESCRIPTION
**Pull request by gk-codes**
Adds Audirvana Plus 2, an audio library manager, streaming and remote control App targeted towards audiophiles with support for external DACs and/or (headphone) amplifiers.

### CODE REVIEW

**Comment by victorpopkov** [comment]
Thank you for the contribution. It needed some fixes, so they were made in a1884ac153664da0a920f0f77786527ce763f447. Your contribution is still included (and still credited to you), with the appropriate modifications. Please feel free to ask about any of the changes.

**Comment by g1nx** [comment]
Thank you for the fixes! As a matter of fact I have a question: how did you get the appcast Url and the checkpoint?

**Comment by victorpopkov** [comment]
Sparkle framework generally uses the SUFeedURL property in Contents/Info.plist inside .app bundles. To find it you do it manually or use the `find_sparkle_appcast` in `/developer/bin/` directory to add this automatically.

The checkpoint was created manually using `curl --compressed "{{appcast_url}}" | sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256` to calculate it.

You can find this information in [cask_language_reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md).

**Comment by g1nx** [comment]
Thank you very much!

**Pull request closed without merging**
