### PR TITLE
Update telegram from 7.8.218215 to 7.8.1.219462

### PR DESCRIPTION
**Pull request by artkirienko**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by vladimyr — DISMISSED** [review]
Telegram's download page (https://macos.telegram.org) has a download link pointing to the latest version hosted at https://osx.telegram.updates/Telegram.dmg

Downloaded _damage_ contains `v7.8.1(.219462)`so this version downgrade is actually correct: 
image

**Comment by bevanjkay** [comment]
Livecheck is not returning this version as the latest, as it thinking `7.8.218215` is newer than `7.8.1.219462` due to the formatting.

brew livecheck --debug outputs

```
Matched Versions:
7.8.1.219462 => #<Version:0x00007ff53d1a5fd8 @version="7.8.1.219462", @detected_from_url=false>
7.8.218215 => #<Version:0x00007ff53d1a5f88 @version="7.8.218215", @detected_from_url=false>
7.8.218173 => #<Version:0x00007ff53d1a5f38 @version="7.8.218173", @detected_from_url=false>
```

**Comment by bevanjkay** [comment]
I'm not 100% happy with the livecheck solution, but it does work. Happy to take other suggestions. Using the sparkle strategy isn't an option for this cask as it uses a non-standard time format for the `pubDate` field.

**Review by SMillerDev — APPROVED** [review]

**Review by vladimyr — APPROVED** [review]
FWIW although it isn't that elegant it will work for the next 780_538 versions (https://github.com/overtake/TelegramSwift/blob/86fba924b8873126970115a6d43a40b7ebbe4236/tools/bump_build_number.sh)  😁

**Comment by bevanjkay** [comment]
Thanks @artkirienko

**Pull request merged**
