### PR TITLE
Add Setapp latest

### PR DESCRIPTION
**Pull request by ChristinWhite**
* Add Setapp latest https://setapp.com

* latest / no_check / url

* installer manual / uninstall / zap

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **updating a cask**:

- [ ] `sha256` changed but `version` stayed the same ([what is this?][version-checksum]).  
      I’m providing public confirmation below.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-cask/pulls
[closed issues]: https://github.com/caskroom/homebrew-cask/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by christopherdwhite** [comment]
Please note that this is my first cask in a long time so let me know if there are any issues. I believe I did the uninstall and zap portions correctly but I would appreciate a once-over to make sure.

**Comment by commitay** [comment]
Thanks for the PR! `setapp` has been refused multiple times, closing.

https://github.com/caskroom/homebrew-cask/pull/27439, https://github.com/caskroom/homebrew-cask/pull/31120, https://github.com/caskroom/homebrew-cask/pull/31121, https://github.com/caskroom/homebrew-cask/pull/31123, https://github.com/caskroom/homebrew-cask/pull/36320

**Comment by christopherdwhite** [comment]
Oh, thanks @commitay, I did a search but didn't see anything.

**Comment by christopherdwhite** [comment]
@commitay,

I've now read through the relevant info on walled apps and looked over the PRs you linked, do you mind if I ask why you've determined that this is behind a login at the bottom left of the page without logging in? 

I'm not arguing the decision, just hoping to understand it so don't put together similar pull requests in the future that won't be accepted? Just trying to be a good citizen here 🙂

**Comment by reitermarkus** [comment]
The URL `https://dl.devmate.com/com.setapp.InstallSetapp/InstallSetapp.zip` is actually visible on `https://setapp.com/download`, so this here isn't actually walled. The URL in the other PRs, `https://dl.devmate.com/com.setapp.DesktopClient/Setapp.dmg`, is walled because it is not publicly visible.

**Pull request merged**
