### PR TITLE
Update gloomhaven-helper from 8.3.6 to 8.3.1

### PR DESCRIPTION
**Pull request by samuelmurray**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by samuelmurray** [comment]
Current release of 8.3.6 crashes at startup with following exception:
```java
Exception in thread "main" com.badlogic.gdx.utils.SerializationException: Error reading animation: air-inert-strong
	at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:332)
	at com.esotericsoftware.gloomhavenhelper.App.load(App.java:218)
	at com.esotericsoftware.gloomhavenhelper.GloomhavenHelper.create(GloomhavenHelper.java:123)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:433)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:381)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:114)
	at com.esotericsoftware.gloomhavenhelper.GloomhavenHelperDesktop.main(GloomhavenHelperDesktop.java:40)
Caused by: java.lang.NullPointerException
	at com.esotericsoftware.spine.SkeletonJson.readCurve(SkeletonJson.java:886)
	at com.esotericsoftware.spine.SkeletonJson.readAnimation(SkeletonJson.java:528)
	at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:330)
	... 7 more
```
I suggest downgrading to stable release 8.3.1 until newer version is fixed.

**Comment by vitorgalvao** [comment]
> Current release of 8.3.6 crashes at startup with following exception:

On your machine. This needs to be reported upstream. For us to downgrade, we need official upstream confirmation.

**Comment by samuelmurray** [comment]
Okay, I'll contact the developers and see if it's a known issue.

**Comment by samuelmurray** [comment]
This was confirmed by the developer, who then replaced the download with a working version. After an update to the checksum (#82356) version 8.3.6 works.

**Comment by vitorgalvao** [comment]
Thank you. That’s why we prefer people contact upstream instead of adding workarounds in casks. Now the app is fixed *for everyone* and we have less maintenance to do because we don’t need to worry about an exception. Everybody wins.

**Pull request closed without merging**
