### PR TITLE
openzfs 1.5.2

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by adidalal** [comment]
Needs the PR template filled out, next time.

**Comment by ilovezfs** [comment]
@adidalal For simple bumps like this, you may want to adopt a cask-ified version of https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb :)

**Comment by adidalal** [comment]
Cask-repair already does that, afaik

**Comment by vitorgalvao** [comment]
Yep. `cask-repair` also only needs the version (it calculates the `sha256` for you), takes care of `appcast` as well, and fills out the template automatically.

**Comment by ilovezfs** [comment]
@vitorgalvao does it work if no `appcast` is available?

**Comment by vitorgalvao** [comment]
Yes.

**Pull request merged**
